### PR TITLE
Fix [QC-103] - update configuration interface usage in data sampling

### PR DESCRIPTION
**Pull request by knopers8**
This should potentially fix Jenkins 'O2 Mac - FLP Prototype alibuild from master', which uses dev branch of Configuration, and keep intact O2 dev, which uses v1.5.2 Configuration.

### CODE REVIEW

**Comment by awegrzyn** [comment]
I'll try to sync this with https://github.com/alisw/alidist/pull/1341

**Comment by Barthelemy** [comment]
do you want me to force the merge of this commit so that https://github.com/alisw/alidist/pull/1341 passes and can be merged ?

**Comment by awegrzyn** [comment]
Let's discuss it during the meeting

**Comment by Barthelemy** [comment]
Closing in favour #1418

**Pull request closed without merging**
