### PR TITLE
CCDB: make extractFromTFile helper a static method

### PR DESCRIPTION
**Pull request by ktf**
This will simplify reusing the same method for DPL Lifetime::Condition.

### CODE REVIEW

**Comment by ktf** [comment]
@costing We should discuss how to determine the way CCDB objects are stored. Are we planning to use TFile everywhere or do we still plan to have the raw messages as well? How do we encode the kind? Additional HTTP header?

**Comment by Barthelemy** [comment]
As far as I  know we plan to use TFile. The only method dealing with raw message is to retrieve old data.

**Comment by ktf** [comment]
Fine for me, but was this agreed and ratified by all sub detectors?

**Comment by ktf** [comment]
Ok. To summarise private discussions between myself, @Barthelemy and @sawenzel :

* For the moment we assume that everything is stored a TFile, the old blob / TMessage based API of DPL will not work anymore.
* If people still need it, we will add some metadata which the client will then have to deal with.
* @costing suggestion of this morning to return a `root://` should be further discussed with everyone present, because I think at the moment there is different opinions about it.

**Pull request merged**
