### PR TITLE
Fix data being dropped by the Calibration Workflows

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @chiarazampolli this allows me to get the CALIB workflow unstuck. I still see some error message which I do not understand, but I think you can already try it to see if it breaks other things.

**Comment by davidrohr** [comment]
I have tried my reproducer with this PR
```
SHMSIZE=16000000000 ENABLE_METRICS=1 DPL_REPORT_PROCESSING=1 DPL_DEFAULT_PIPELINE_LENGTH=32 WORKFLOW_PARAMETERS=CALIB,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR DPL_REPORT_PROCESSING=1 EXTINPUT=1 SYNCMODE=1 WORKFLOW_DETECTORS=ITS,TPC,TOF ~/alice/O2/prodtests/full-system-test/dpl-workflow.sh
```
but unfortunately, it is not working.
With the PR, indeed I see a message from the tpc-calibrator-gainmap-tracks that it is forwarding the messages:
```
[104202:internal-dpl-injected-dummy-sink]: [10:04:08][INFO] Dropping message from slot 0. Forwarding as needed.
```
but the calib-lhcclock-calibration is still dropping the `TOF/CALIBDATA/0, and I assume this is still since it does not receive `GLO/GRPECS` and `CTP/ORBITRESET` from tpc-calibrator-gainmap-tracks.:
```
[104197:calib-lhcclock-calibration]: [10:04:04][INFO] Silently dropping data CTP/ORBITRESETTOF/0 in pipeline slot 0 because it has timeslice 65 < 66 after receiving data from channel from_tof-matcher_to_calib-lhcclock-calibration[0].Because Lifetime::Timeframe data not there and not expected (e.g. due to sampling) we drop non sampled, non timeframe data (e.g. Conditions).
[104197:calib-lhcclock-calibration]: [10:04:04][INFO] Silently dropping data TOF/ChannelCalibCal/0 in pipeline slot 0 because it has timeslice 65 < 66 after receiving data from channel from_tof-matcher_to_calib-lhcclock-calibration[0].Because Lifetime::Timeframe data not there and not expected (e.g. due to sampling) we drop non sampled, non timeframe data (e.g. Conditions).
[104197:calib-lhcclock-calibration]: [10:04:04][INFO] Silently dropping data TOF/LHCphaseCal/0 in pipeline slot 0 because it has timeslice 65 < 66 after receiving data from channel from_tof-matcher_to_calib-lhcclock-calibration[0].Because Lifetime::Timeframe data not there and not expected (e.g. due to sampling) we drop non sampled, non timeframe data (e.g. Conditions).
[104197:calib-lhcclock-calibration]: [10:04:04][ERROR] Dropping TOF/CALIBDATA/0 Lifetime::Timeframe data in slot 0 with timestamp 65 < 66.
```

**Comment by ktf** [comment]
@davidrohr with this I see the processing messages correctly, however I am not 100% this will not get things stuck with the rate limiting.

**Comment by davidrohr** [comment]
For reference, tried this just now, and it fixes the problem with the CALIB, but as you were afraid it breaks the time frame throttling :(

**Comment by ktf** [comment]
The latest incarnation works for me and it behaves in the way I expect for the proper handling of the rate limiting.

**Comment by davidrohr** [comment]
This crashes for me with
```
[56138:tpc-calibrator-gainmap-tracks]: *** Segmentation fault (O2)
[56138:tpc-calibrator-gainmap-tracks]: Backtrace:
[56138:tpc-calibrator-gainmap-tracks]:     /lib64/libc.so.6: ()
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/O2/dev-local4/lib/libO2Framework.so: std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<fair::mq::Channel, std::allocator<fair::mq::Channel> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::vector<fair::mq::Channel, std::allocator<fair::mq::Channel> > > >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true>, true>::at(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/O2/dev-local4/lib/libO2Framework.so: fair::mq::Device::GetChannel(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/O2/dev-local4/lib/libO2Framework.so: ()
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/O2/dev-local4/lib/libO2Framework.so: o2::framework::AsyncQueueHelpers::run(o2::framework::AsyncQueue&)
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/O2/dev-local4/lib/libO2Framework.so: o2::framework::DataProcessingDevice::Run()
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/FairMQ/v1.4.51-local1/lib/libFairMQ.so.1.4: fair::mq::Device::RunWrapper()
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/FairMQ/v1.4.51-local1/lib/libFairMQStateMachine.so.1.4: boost::detail::function::void_function_obj_invoker1<std::function<void (fair::mq::State)>, void, fair::mq::State>::invoke(boost::detail::function::function_buffer&, fair::mq::State)
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/FairMQ/v1.4.51-local1/lib/libFairMQStateMachine.so.1.4: boost::signals2::detail::signal_impl<void (fair::mq::State), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void (fair::mq::State)>, boost::function<void (boost::signals2::connection const&, fair::mq::State)>, boost::signals2::mutex>::operator()(fair::mq::State)
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/FairMQ/v1.4.51-local1/lib/libFairMQStateMachine.so.1.4: fair::mq::fsm::Machine_::ProcessWork()
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/FairMQ/v1.4.51-local1/lib/libFairMQStateMachine.so.1.4: fair::mq::StateMachine::ProcessWork()
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/FairMQ/v1.4.51-local1/lib/libFairMQ.so.1.4: fair::mq::DeviceRunner::Run()
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/O2/dev-local4/lib/libO2Framework.so: doChild(int, char**, o2::framework::ServiceRegistry&, o2::framework::RunningWorkflowInfo const&, o2::framework::RunningDeviceRef, o2::framework::ProcessingPolicies, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, uv_loop_s*)
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/O2/dev-local4/lib/libO2Framework.so: runStateMachine(std::vector<o2::framework::DataProcessorSpec, std::allocator<o2::framework::DataProcessorSpec> > const&, WorkflowInfo const&, std::vector<o2::framework::DataProcessorInfo, std::allocator<o2::framework::DataProcessorInfo> > const&, o2::framework::CommandInfo const&, o2::framework::DriverControl&, o2::framework::DriverInfo&, std::vector<o2::framework::DeviceMetricsInfo, std::allocator<o2::framework::DeviceMetricsInfo> >&, boost::program_options::variables_map&, std::vector<o2::framework::ServiceSpec, std::allocator<o2::framework::ServiceSpec> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)
[56138:tpc-calibrator-gainmap-tracks]:     /home/qon/alice/sw/gentoo2_x86-64/O2/dev-local4/lib/libO2Framework.so: doMain(int, char**, std::vector<o2::framework::DataProcessorSpec, std::allocator<o2::framework::DataProcessorSpec> > const&, std::vector<o2::framework::ChannelConfigurationPolicy, std::allocator<o2::framework::ChannelConfigurationPolicy> > const&, std::vector<o2::framework::CompletionPolicy, std::allocator<o2::framework::CompletionPolicy> > const&, std::vector<o2::framework::DispatchPolicy, std::allocator<o2::framework::DispatchPolicy> > const&, std::vector<o2::framework::ResourcePolicy, std::allocator<o2::framework::ResourcePolicy> > const&, std::vector<o2::framework::CallbacksPolicy, std::allocator<o2::framework::CallbacksPolicy> > const&, std::vector<o2::framework::SendingPolicy, std::allocator<o2::framework::SendingPolicy> > const&, std::vector<o2::framework::ConfigParamSpec, std::allocator<o2::framework::ConfigParamSpec> > const&, o2::framework::ConfigContext&)
[56138:tpc-calibrator-gainmap-tracks]:     o2-tpc-calibrator-gainmap-tracks: ()
[56138:tpc-calibrator-gainmap-tracks]:     o2-tpc-calibrator-gainmap-tracks: ()
[56138:tpc-calibrator-gainmap-tracks]:     /lib64/libc.so.6: ()
[56138:tpc-calibrator-gainmap-tracks]:     /lib64/libc.so.6: __libc_start_main()
[56138:tpc-calibrator-gainmap-tracks]:     o2-tpc-calibrator-gainmap-tracks: ()
[56138:tpc-calibrator-gainmap-tracks]: Backtrace complete.
```

**Comment by ktf** [comment]
For the record, the crash is understood and fixed, as you know. We however still have a race condition when processing on the GPU is faster than the downstream device by some margin. I have tried a few things, but they do not work. I will keep trying in a bit.

**Comment by ktf** [comment]
Updated, but it still has issues... Too tired now, will continue tomorrow.

**Comment by ktf** [comment]
This version behaves correctly in my tests and as far as I understand it will solve the previous race condition where the callback is executed at the wrong moment depending on the processing speed.

**Comment by davidrohr** [comment]
@ktf : could you rebase?

**Comment by ktf** [comment]
Done.

Ciao,
Giulio

**Comment by davidrohr** [comment]
tried with this PR, and I don't see data dropped yet, but it breaks the time frame throttling :(
In my test case (max tf in flight = 5), readout-proxy has published 5 TFs, only one has arrived yet at the primary vertexer and at the end of the chain, and the chain is stuck.
Now trying without TF rate limiting / with more TF in flight.
But certainly something is wrong, since also in this setup it must not be stalled.

**Comment by ktf** [comment]
New bump. It seems to me that it behaves now, but I only ran for 20TFs or so. There is still one bit I am not 100% sure, but if you could  confirm if it works in your setup it would be great.

**Comment by davidrohr** [comment]
@ktf : Just tried with dev + this PR, but FST with CALIB and TF RATE THROTTLING still gets stuck after 5 TFs.
Command line is:
```
DPL_RAWPROXY_OVERRIDE_ORBITRESET=1550600800000 TIMEFRAME_RATE_LIMIT=5 SHMSIZE=16000000000 ENABLE_METRICS=1 DPL_REPORT_PROCESSING=1 DPL_DEFAULT_PIPELINE_LENGTH=32 WORKFLOW_PARAMETERS=CALIB,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR DPL_REPORT_PROCESSING=1 EXTINPUT=1 SYNCMODE=1 SHMSIZE=16000000000 WORKFLOW_DETECTORS=ITS,TPC,TOF ~/alice/O2/prodtests/full-system-test/dpl-workflow.sh
```
Didn't check exactly yet if it is the same problem as before or different.

**Comment by davidrohr** [comment]
closing as superseded by #9395

**Pull request closed without merging**
