### PR TITLE
Streamlining definition and reading of tables

### PR DESCRIPTION
**Pull request by pbuehler**
This is to simplify the AODReaderHelpers::rootFileReaderCallback() and the handling of DataModel and other tables.

So far the reading of tables of the DataModel and all other tables has been treated with distinct code with slightly different functionality.

DataModel tables:
. the name of the tree to read from is hard coded and part of the DataModel however contained in AODReaderHelpers.cxx
e.g.    Table description       Tree name

        TRACKPAR                 O2track
        TRACKPARCOV         O2track
        TRACKEXTRA            O2track
        CALOTRIGGER          O2calotrigger
        RUN2V0                      Run2v0
        
. there is a fixed relation between the table column names and the tree branches: colname -> fcolname.
. the reading of the DataModel tables is based on the table definition which includes a list of columns. Only branches which contain data of a defined column are read.

other tables:
. the name of the tree to read is by default assumed to have the name of the table description. This can however be configured by command line options.
. the branch names are assumed to be equal to the column names.
. the reading of the other tables is based on the tree definition. All branches of the tree are read and filled into a table.

What we strive for is:

. fix the table name - tree name relation of DataModel tables and allow for command line configuration in all other cases
. fix the column name - branch name relation of DataModel tables and allow for command line configuration in all other cases.
. in all cases only branches containing requested information should be read.

The current PR provides a first step towards the final solution and includes the following modifications:

. the set of pre-processor commands DECLARE_SOA_TABLE_* (see ASoA.h) has been extended with
  
  DECLARE_SOA_TABLE_FULL_ANDTREE(_Name_, _Label_, _Tree_, _Origin_, _Description_, ...)
  DECLARE_SOA_TABLE_ANDTREE(_Name_, _Tree_, _Origin_, _Description_, ...)
  
  The extra _Tree_ argument allows to specify the name of the tree to read from. These commands are supposed to be used in AnalysisDataModel.h only and not in user tasks. In DECLARE_SOA_EXTENDED_TABLE_FULL and DECLARE_SOA_EXTENDED_TABLE the tree name is inherited from the base table (parameter _Tabel_).
  
  In order to read this information back the tree name is included in the _Name_##Metadata structure which then can be accessed through the function
  
  o2::aod::datamodel::getTreeName(std::string tableName)
  
  in AnalysisDataModel.cxx.
  
. to retrieve the defined columns of a table the function

  o2::aod::datamodel::getColumnNames(DataHeader dh)
  
  is added to AnalysisDataModel.cxx.
  When new tables are added to the DataModel the functions in AnalysisDataModel.cxx have to be updated accordingly. With these modifications all DataModel definitions are now included in AnalysisDataModel.[cxx,h].
  
  For other tables the function getTreeName currently returns the table description and getColumnNames the empty vector std::vector<std::string>({}).

### CODE REVIEW

**Comment by ktf** [comment]
Why not simply deriving the name of the tree from the data description?

**Comment by ktf** [comment]
I mean we can simply rename `TRACKPAR` to `TRACK:PAR` and then use whatever is before the : to determine the tree name and what is after to match different tables.

**Comment by jgrosseo** [comment]
Probably this is the same comment as @ktf made. For all tables (but tracks?) it was working already before. E.g. for the v0s with providing the tree name as third argument:
DECLARE_SOA_TABLE(StoredV0s, "AOD", "O2v0", o2::soa::Index<>, v0::PosTrackId, v0::NegTrackId);

**Comment by pbuehler** [comment]
> Probably this is the same comment as @ktf made. For all tables (but tracks?) it was working already before. E.g. for the v0s with providing the tree name as third argument:
> DECLARE_SOA_TABLE(StoredV0s, "AOD", "O2v0", o2::soa::Index<>, v0::PosTrackId, v0::NegTrackId);

what about table RUN2V0 with tree RUN2V0?
There is currently no fixed scheme. We could change that of course.  TRACKPAR, TRACKPARCOV, and TRACKEXTRA are in any case however different than the other cases. Is a fixed scheme better than providing the tree name in the declaration?

**Comment by pbuehler** [comment]
> I mean we can simply rename `TRACKPAR` to `TRACK:PAR` and then use whatever is before the : to determine the tree name and what is after to match different tables.

This I can try to implement. In general in the declaration one specifies "T:S", which is transformed into the tree name "o2t" and the table description "TS". This would work for all currently defined tables in AnalysisDataModel.h except for "RUN2V0" which is contained in tree "Run2v0".

**Comment by jgrosseo** [comment]
Let's just make T explicit, so you don't add o2 to it automatically but we give the full name always like O2collision. Then it also works for Run2v0

**Comment by pbuehler** [comment]
I'll close this PR to make the changes as discussed.

**Pull request closed without merging**
