### PR TITLE
[WIP] Update of the ITS CA tracker

### PR DESCRIPTION
**Pull request by mpuccio**
@shahor02 @iouribelikov : this PR is mainly for you to check the CPU version.
Please do not merge this until I remove the WIP, we are still working with @davidrohr and @mconcas to fully integrate the CUDA part.

### CODE REVIEW

**Comment by mpuccio** [comment]
Hi @shahor02 ,
uhm... OK maybe I found the bug, but I am a bit puzzled. I am storing in the track the internal cluster index on each layer, not the index of the cluster in the external array. However, this was always the case: I am not sure why it was working before.
The patch I posted should be fixing this behaviour. Since I don't have locally events with the TPC I cannot check the matching itself, I just checked that the cluster index and its position in the track array were consistent with the cluster layer (that was not the case before).
Cheers,
Max

**Comment by mpuccio** [comment]
Hi @shahor02 ,
I am still having a memory issue with the CUDA version of the code that I would like to fix before merging this. As soon as this is fixed I will make this PR passing the tests, squash a few commits and then I would merge this PR.
Cheers!
Max

**Comment by shahor02** [comment]
@mpuccio OK, thanks. I see that the modified ```run_trac_ca_its.C``` still uses dummy MC vertex for the constraint. Could you also fix this part with the input from the real vertexer? I am gradually eliminating a per-cluster ROFcounter, later I will fix the loop over the ```o2::ITS::IOUtils::loadROFrameData```.

Cheers,
 Ruben

**Comment by mpuccio** [comment]
I am closing this in favour of more atomic PR on the different things to be implemented. Stay tuned.

**Pull request closed without merging**
