### PR TITLE
Update code-formatting.yml

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken do you know if there is a way to get the target repository programmatically?

**Comment by TimoWilken** [comment]
`${{ github.event.pull_request.repo.full_name }}`?

[Documentation](https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request) for `${{ github.event }}` for pull requests.

**Comment by ktf** [comment]
repository, not repo, no?

**Comment by TimoWilken** [comment]
You're right, it's `${{ github.event.repository.full_name }}` I think. I got `github.event.pull_request.head.repo` instead, which isn't right.

**Pull request closed without merging**
