### PR TITLE
Update Travis to clang-format 8

### PR DESCRIPTION
**Pull request by awegrzyn**

### CODE REVIEW

**Comment by dberzano** [comment]
`E: Unable to locate package clang-format-8` (otherwise it's fine for me to do the upgrade)

**Comment by sawenzel** [comment]
Can you remind me why this is necessary and where the user gets this from locally?

**Comment by dberzano** [comment]
@sawenzel there was a discussion with no objections last week at WP3 (see minutes); the rationale was that clang-format-7 still has "some problems" with our code, but I honestly don't know the details. No problem in putting this on hold until tomorrow if you need clarifications from the stakeholders.

About getting this locally, if using Ubuntu I believe you can just have a look at the Travis CI recipe (add an `apt` source and then install `clang-format-8`).

**Comment by sawenzel** [comment]
Agreed but it would be useful to know the problems and if they are actually solved by bumping.

**Comment by ktf** [comment]
One of the problem is that when having:

```C++
auto [foo, _] = somethingWhichReturnsAPairReference();
```

the `auto [foo, _]` is misunderstood as an array and  formatted as `auto[foo,_]`.

**Comment by sawenzel** [comment]
Fair enough.

**Comment by dberzano** [comment]
OK thanks for clarifying. Merging.

**Pull request merged**
