### PR TITLE
DPL: write support for TTree using arrow::Dataset API

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@sawenzel @jackal1-66 do you understand the errors about

```
545/549 Test #506: o2sim_checksimkinematics_G3 ..........................................................Subprocess aborted***Exception:   1.48 sec
```

which are starting to appear since around yesterday?

Do you also understand the other one about the missing `Pythia8.h`?

**Comment by ktf** [comment]
Does not touch anything in production just a test (which works correctly). Merging.

**Comment by jackal1-66** [comment]
I'm running a test on o2sim_checksimkinematics_G3. I see that it fails on the TPCtracks when checking for the trackref size, but I want to see if this fails also locally (and understand why the mcreader it's getting a 0). Regarding the Pythia8 issue instead I have no clue right now. The only recent modification in GeneratorPythia8.h is unrelated to this. Were there some updates on the building machine side instead? Locally on my slc9 pc I don't get this issue.

**Comment by jackal1-66** [comment]
After talking to @sawenzel I opened https://github.com/AliceO2Group/AliceO2/pull/13721 to fix the issue with the missing Pythia8 header. Still investigating on the o2sim_checksimkinematics_G3 problem instead.

**Pull request merged**
