### PR TITLE
Adding also detector list

### PR DESCRIPTION
**Pull request by chiarazampolli**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 
This we can use to retrieve the list of detectors in async reco.
Chiara

**Review by shahor02 — APPROVED** [review]
Thanks, note that the list can be also obtained as 
```
auto dets = o2::detectors::DetID::getNames( ecsObj.getDetsReadOut() );
```

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 
Indeed, I had not seen it!
If you think that it is better, I can change. 
Chiara

**Comment by shahor02** [comment]
No need to change

**Pull request merged**
