### PR TITLE
Reverting incorrect changes from commit af82ebf

### PR DESCRIPTION
**Pull request by matthiasrichter**
Commit af82ebf came with some incorrect search & replace changes, fixed with this PR in 4 separate commits

### CODE REVIEW

**Comment by MohammadAlTurany** [comment]
Squashed and merged

**Comment by matthiasrichter** [comment]
I did the separate commits on purpose, not just for fun.

**Comment by MohammadAlTurany** [comment]
Now you have your 4 commits.  It would be helpful to leave a note next time that we should not squash the commits when merging the PR. By default we consider multiple commits as "FUN" and we squash them.

best,
Mohammad

**Comment by matthiasrichter** [comment]
;-) thanks a lot, I should have been more explicit in the original comment.

**Pull request closed without merging**
