### PR TITLE
DPL: drop dataprocessor_id and use pipeline_id

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@awegrzyn @davidrohr as discussed.

**Comment by awegrzyn** [comment]
LGTM. This could come with FLP Suite release next Thu.

**Comment by awegrzyn** [comment]
Actually, @ktf What's gonna be value when there's only 1 thread? `0` or empty?

**Comment by ktf** [comment]
0

**Comment by ktf** [comment]
@davidrohr @JohannesLb  waiting for your ok before merging this.

**Comment by davidrohr** [comment]
mostly  @awegrzyn  should comment when the GUI can consume it correctly

**Comment by awegrzyn** [comment]
As I'll be away starting for next week either we merge it now, I'll get a new O2 tag tomorrow, and make sure all dashboards are OK or let's wait until 10/11.

**Comment by davidrohr** [comment]
ok, let's try tomorrow. We'll have to bump O2 on FLPs and EPNs in parallel I assume. Need to discuss with Pippo if we can do that.

**Comment by awegrzyn** [comment]
Okay, could we test it on staging tomorrow? Then production can be deployed anytime.

**Comment by ktf** [comment]
I am back on saturday.

Ciao,
Giulio

**Pull request merged**
