### PR TITLE
compact cubic splines

### PR DESCRIPTION
**Pull request by sgorbuno**
Classes for 1-D and 2-D compact cubic spines. 
These splines will replace currently used splines (IrregularSpline* and SemiregularSpline*) in the TPC fast transformation.

### CODE REVIEW

**Comment by sawenzel** [comment]
@davidrohr : Can you take a look at this, pls?

**Comment by davidrohr** [comment]
Sure, will have a look (Didn't notice the WIP was removed...)

**Comment by sgorbuno** [comment]
Hi @davidrohr, I thought you are on vacation:) This is not urgent.

**Comment by davidrohr** [comment]
@sgorbuno : I assume I'll have to create a new TPCFastTransform object with this patch?

**Comment by sgorbuno** [comment]
@davidrohr : no, not yet. This PR is only new mathematics which is not yet used in the transformation.

**Comment by davidrohr** [comment]
OK, so I cannot test it anyway, so far?

**Comment by sgorbuno** [comment]
yes, the code is not yet in use.  The only thing - I have added some test method to the FlatObject, modified the Makefile in the transformation  and added a test module.  You can check if it breaks your compilation for the GPU, but i don't think so..

**Pull request merged**
