### PR TITLE
Propagate modified TPC Digitization to all run macros

### PR DESCRIPTION
**Pull request by a-mathis**

### CODE REVIEW

**Comment by shahor02** [comment]
@a-mathis: Does this mean that only 1st sector will be digitized?

**Comment by a-mathis** [comment]
@shahor02 Indeed. We needed to adopt the structure of the TPC digitizer to be prepared for the o2 data processing workflow. Unfortunately we found no way to get this running with FairRunAna, as the workflow is such that all events are processed for a given sector before the next one can be processed. 
Therefore, one FairTask per sector would not work. What we would need is one FairRunAna per sector, but this then successively overwrites the results of the previous one in the output while processing

**Comment by shahor02** [comment]
@a-mathis Thanks, but then I don't see much use in patching the run_digi_all, since it is supposed to produce data for full TPC and ITS. FairRunAna per sector also would not work since each one would generate its own time sequence.
I am completely for giving up the FairRunAna, but if we do this for TPC without backward compatibility with FairRunAna, we should do this for all detectors at the same time, otherwise we will not be able to produce digits coherent between detectors. So I would wait to have working example with TPC, then convert asap other detectors processing to new workflow (eliminating FairRootAna based macros).

**Comment by a-mathis** [comment]
@shahor02 I completely agree. This PR was rather a bug fix and a follow up on the mail discussion we had yesterday, as the run_digi_* currently fail because of the TPC digitisation (the o2::TPC::DigitizerTask needs to be provided with a sector number).
Let me know whether you would advocate to close this PR

**Comment by shahor02** [comment]
@a-mathis Yes, I would close this PR. Sorry for not reacting yesterday, I did not realize it will work for 1 sector only.

**Comment by a-mathis** [comment]
@shahor02 No problem, fine with me!

**Pull request closed without merging**
