### PR TITLE
[QC-437] Do not throw if no DataSamplingPolicies are specified

### PR DESCRIPTION
**Pull request by knopers8**

### CODE REVIEW

**Comment by knopers8** [comment]
@Barthelemy

**Comment by Barthelemy** [comment]
good thank you

**Review by Barthelemy — APPROVED** [review]

**Comment by knopers8** [comment]
build/O2/o2 failed with internal compiler error in a random place, probably due to lack of memory:
```
Scanning dependencies of target O2test-datacompression-DataDeflater
Scanning dependencies of target O2test-datacompression-DataGenerator
[  1%] Building CXX object Utilities/DataCompression/CMakeFiles/O2test-datacompression-DataGenerator.dir/test/test_DataGenerator.cxx.o
[  1%] Building CXX object Utilities/DataCompression/CMakeFiles/O2test-datacompression-DataDeflater.dir/test/test_DataDeflater.cxx.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
gmake[2]: *** [DataFormats/MemoryResources/CMakeFiles/O2test-memoryresources-MemoryResources.dir/test/testMemoryResources.cxx.o] Error 4
gmake[1]: *** [DataFormats/MemoryResources/CMakeFiles/O2test-memoryresources-MemoryResources.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
```
macOS failed in a simulation test:
```
323/323 Test #286: o2sim_hepmc ....................................................................***Failed  Required regular expression not found. Regex=[SIMULATION RETURNED SUCCESFULLY
```
Check PR with clang-format shows me some change suggestions for a completely unrelated file:
```
--- a/DataFormats/simulation/include/SimulationDataFormat/Stack.h
+++ b/DataFormats/simulation/include/SimulationDataFormat/Stack.h
@@ -177,7 +177,6 @@ class Stack : public FairGenericStack
   /// Clone for worker (used in MT mode only)
   FairGenericStack* CloneStack() const override;
 
-
   // methods concerning track references
   void addTrackReference(const o2::TrackReference& p);
 
@@ -232,9 +231,9 @@ class Stack : public FairGenericStack
 
   /// Array of TParticles (contains all TParticles put into or created
   /// by the transport)
-  std::vector<o2::MCTrack> mParticles; //!
-  std::vector<int> mTransportedIDs;    //! prim + sec trackIDs transported for "current" primary
-  std::vector<int> mIndexOfPrimaries;  //! index of primaries in mParticles
+  std::vector<o2::MCTrack> mParticles;       //!
+  std::vector<int> mTransportedIDs;          //! prim + sec trackIDs transported for "current" primary
+  std::vector<int> mIndexOfPrimaries;        //! index of primaries in mParticles
```
As the change is quite simple and it passed most of the builds and clang-format in Travis, I would say it is clean. Can we merge it?

**Comment by Barthelemy** [comment]
Indeed, I think we can go ahead. Merging. 

@sawenzel Could you check the failing test o2sim_hepmc ? 
@MichaelLettrich @ktf Could you have a look at the compiler crash due to lack of memory ? There is also the "Check PR with clang-format" that seems pretty broken. 

@ihrivnac

**Pull request merged**
