### PR TITLE
[EMCAL-571, EMCAL-582] Interface for EMCAL calibration parameters from the CCDB

### PR DESCRIPTION
**Pull request by mfasDa**
- EMCAL-571: Provide macro storing existing Bad Channel Map from run2 data in the CCDB on the EMCAL test server
- EMCAL-582: Easy interface for the access of EMCAL calibration data from the CCDB using the CcdbApi as backend

### CODE REVIEW

**Comment by mfasDa** [comment]
@shahor02 Please review! This is a simple front-ent for storing / reading EMCAL calibration in the CCDB. Furthermore it seems to be necessary as the usage of TObjectWrapper from cling doesn't work while in compiled code it works fine.

**Comment by mfasDa** [comment]
Hi @shahor02,

When I tried without the function wrapBadChannelMap rootcling did not create a corresponding entry in the rootmap file. With this cling always complained about undeclared class TObjectWrapper<o2::emcal::BadChannelMap>. Just adding the corresponding entry in the LinkDef.h file didn't help. I suspect that I need to declare the TObjectWrapper<...> so that cling actually declares the entries. After doing so I was able to create the TObjectWrapper in macros. I suspect the reason why it worked for the TPC without explicitly declaring the function was that the TPC uses the o2::ccdb::Condition where the TObjectWrapper is implicitly declared. This fixed the write direction.

The read direction was however still problematic: Cling always produced a nullptr exception when I added code to cast the TObject to the TObjectWrapper. The nullptr exception happens during JITting as printfs placed before didn't show up. This did not happen if I do the cast in compiled code.

I would appreciate if the wrapping would be part of the CcdbApi, there is also a JIRA ticket for this (O2-519). In the mean time we must rely on our own implementation to continue with the development and testing. Once the interface is move to CcdbApi we can adapt our own adapter to still handle casting and the CCDB paths.

Cheers

Markus

**Comment by shahor02** [comment]
@mfasDa 

Just including the ``TObjectWrapper.h`` in ``BadChannelMap.h`` (though I would expect it should work w/o it) allows to generate the class dictionary from
````
#pragma link C++ class o2::TObjectWrapper<o2::emcal::BadChannelMap>+;
````
in the LinkDef.h.
I don't understand how the cast can fail, for me everything works:

````
root [0] o2::emcal::BadChannelMap bmp;
root [1] o2::TObjectWrapper<o2::emcal::BadChannelMap> mpw(&bmp);
root [2] ff = TFile::Open("tst.root","recreate");
root [3] ff->WriteObjectAny(&mpw, mpw.IsA(), "badchannels");
root [4] ff->Close();
root [5] .q
-----------------
root [0] ff = TFile::Open("tst.root");
root [1] TObject* obj = (TObject*)ff->GetObjectUnchecked("badchannels");
root [2] o2::TObjectWrapper<o2::emcal::BadChannelMap>* mpw = (o2::TObjectWrapper<o2::emcal::BadChannelMap>*)obj;
root [3] std::cout << *mpw->getObj() << "\n";
Number of bad cells:  0
Number of dead cells: 0
Number of warm cells: 0
````

**Comment by mfasDa** [comment]
Hi @shahor02,

Here is an example for the failing cast, tested on mac:

[O2/latest] ~/alice/ali-master/O2/Detectors/EMCAL/calib/macros $> root -l
root [0] .L ReadTestBadChannelMap_CCDBApi.C
root [1] auto obj = ReadTestBadChannelMap_CCDBApi()
Using CCDB server emcccdb-test.cern.ch
Got object of type o2::TObjectWrapper<o2::emcal::BadChannelMap>
(TObject *) @0x7ffee4a7e998
root [2] obj
(TObject *) @0x7ffee4a7e998
root [3] obj->IsA()->GetName()
(const char *) "o2::TObjectWrapper<o2::emcal::BadChannelMap>"
root [4] auto wrap = dynamic_cast<o2::TObjectWrapper<o2::emcal::BadChannelMap> *>(obj)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] cling_runtime_internal_throwIfInvalidPointer (no debug info)
[<unknown binary>] (no debug info)
[<unknown binary>] (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] cling::IncrementalExecutor::runStaticInitializersOnce(cling::Transaction const&) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] cling::Interpreter::executeTransaction(cling::Transaction&) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] cling::IncrementalParser::commitTransaction(llvm::PointerIntPair<cling::Transaction*, 2u, cling::IncrementalParser::EParseResult, llvm::PointerLikeTypeTraits<cling::Transaction*>, llvm::PointerIntPairInfo<cling::Transaction*, 2u, llvm::PointerLikeTypeTraits<cling::Transaction*> > >&, bool) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] cling::IncrementalParser::Compile(llvm::StringRef, cling::CompilationOptions const&) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] cling::Interpreter::EvaluateInternal(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cling::CompilationOptions, cling::Value*, cling::Transaction**, unsigned long) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] cling::Interpreter::process(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, cling::Value*, cling::Transaction**, bool) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] cling::MetaProcessor::process(llvm::StringRef, cling::Interpreter::CompilationResult&, cling::Value*, bool) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] HandleInterpreterException(cling::MetaProcessor*, char const*, cling::Interpreter::CompilationResult&, cling::Value*) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCling.so] TCling::ProcessLine(char const*, TInterpreter::EErrorCode*) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libRint.6.16.so] TRint::ProcessLineNr(char const*, char const*, int*) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libRint.6.16.so] TRint::HandleTermInput() (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCore.6.16.so] TUnixSystem::CheckDescriptors() (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCore.6.16.so] TMacOSXSystem::DispatchOneEvent(bool) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCore.6.16.so] TSystem::InnerLoop() (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCore.6.16.so] TSystem::Run() (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libCore.6.16.so] TApplication::Run(bool) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/lib/libRint.6.16.so] TRint::Run(bool) (no debug info)
[/Users/markusfasel/alice/sw/osx_x86-64/ROOT/v6-16-02-alice-4/bin/root.exe] main (no debug info)
[/usr/lib/system/libdyld.dylib] start (no debug info)
libc++abi.dylib: terminating with uncaught exception of type cling::InvalidDerefException: Trying to access a pointer that points to an invalid memory address.

This happened quite reproducibly on mac and Ubuntu and is gone when doing the access via the CalibDB class.

Cheers

Markus

**Comment by mfasDa** [comment]
@shahor02 Indeed just including the TObjectWrapper.h in the BadChannelMap.h was enough to create the dictionary - I removed the wrapper function.

I added a macro with which you can reproduce the crash in the dynamic_cast, called Detectors/EMCAL/calib/macros/BadChannelMap_CCDBApitest_V1.C. The macro Detectors/EMCAL/calib/macros/BadChannelMap_CCDBApitest.C is using the o2::emcal::CalibDB and does not crash.

**Comment by shahor02** [comment]
For me the ``dynamic_cast`` also works on ubuntu w/o any problem:
````
root [0]  ff = TFile::Open("tst.root");
root [1]  TObject* obj = (TObject*)ff->GetObjectUnchecked("badchannels");
root [2] obj->IsA()->GetName()
(const char *) "o2::TObjectWrapper<o2::emcal::BadChannelMap>"
root [3] auto wrap = dynamic_cast<o2::TObjectWrapper<o2::emcal::BadChannelMap> *>(obj)
(o2::TObjectWrapper<o2::emcal::BadChannelMap> *) @0x7ffd1f068368
root [4] std::cout << *wrap->getObj() << "\n";
Number of bad cells:  0
Number of dead cells: 0
Number of warm cells: 0
````
I will now test with your PR

**Comment by shahor02** [comment]
@mfasDa The ``BadChannelMap_CCDBApitest_V1.C`` indeed crashes but it does it on loading.
The crash is not related to wrapper, it happens even if you comment out everything but `` o2::ccdb::CcdbApi ccdbhandler;``

The ``o2::ccdb::CcdbApi`` had no dictionary generated, so I've added ClassDef and entry to the ``CCBDLinkDef.h`` (the diff is below).

Now I get exactly the same crash simply loading the api:
````
root [0] o2::ccdb::CcdbApi xx
#0  0x00007f4ca4a04687 in __GI___waitpid (pid=12605, stat_loc=stat_loc
entry=0x7fffa468bef8, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007f4ca496f067 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:149
#2  0x00007f4ca56138d4 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x55f9816597c0) at /home/shahoian/alice/sw/SOURCES/ROOT/e79be32865/0/core/unix/src/TUnixSystem.cxx:2119
#3  TUnixSystem::StackTrace (this=0x55f9816597c0) at /home/shahoian/alice/sw/SOURCES/ROOT/e79be32865/0/core/unix/src/TUnixSystem.cxx:2413
#4  0x00007f4c9fe617b5 in cling::MultiplexInterpreterCallbacks::PrintStackTrace() () from /home/shahoian/alice/sw/ubuntu1804_x86-64/ROOT/e79be32865-1/lib/libCling.so
#5  0x00007f4c9fe6120d in cling_runtime_internal_throwIfInvalidPointer () from /home/shahoian/alice/sw/ubuntu1804_x86-64/ROOT/e79be32865-1/lib/libCling.so
#6  0x00007f4ca5d5c751 in ?? ()
#7  0x00007fffa468e310 in ?? ()
#8  0x00007f4ca5d5c8b8 in ?? ()
#9  0x0000000000000000 in ?? ()
Error in <HandleInterpreterException>: Trying to access a pointer that points to an invalid memory address..
Execution of your code was aborted.
In file included from G__O2CCDB dictionary payload:238:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/FairMQ/v1.4.2-4/include/fairmq/FairMQDevice.h:13:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/FairMQ/v1.4.2-4/include/fairmq/FairMQTransportFactory.h:17:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/FairMQ/v1.4.2-4/include/fairmq/MemoryResources.h:21:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/boost/v1.68.0-6/include/boost/container/flat_map.hpp:29:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/boost/v1.68.0-6/include/boost/container/detail/flat_tree.hpp:29:
/home/shahoian/alice/sw/ubuntu1804_x86-64/boost/v1.68.0-6/include/boost/container/detail/pair.hpp:132:89: warning: invalid memory pointer passed to a callee:
static piecewise_construct_t piecewise_construct = BOOST_CONTAINER_DOC1ST(unspecified, *std_piecewise_construct_holder<>::dummy);
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/shahoian/alice/sw/ubuntu1804_x86-64/boost/v1.68.0-6/include/boost/container/detail/workaround.hpp:71:46: note: expanded from macro 'BOOST_CONTAINER_DOC1ST'
#define BOOST_CONTAINER_DOC1ST(TYPE1, TYPE2) TYPE2
````

So, something is wring in loading the CCDB related libraries, and I think this should be fixed at 1st place (pinging to @costing )

Cheers,
 Ruben


```
diff --git a/CCDB/CMakeLists.txt b/CCDB/CMakeLists.txt
index 95952c80dd..3400d79ada 100644
--- a/CCDB/CMakeLists.txt
+++ b/CCDB/CMakeLists.txt
@@ -42,7 +42,8 @@ o2_add_library(CCDB
 protobuf_generate(TARGET ${targetName})
 
 o2_target_root_dictionary(CCDB
-                          HEADERS include/CCDB/Backend.h
+                          HEADERS include/CCDB/CcdbApi.h
+                                 include/CCDB/Backend.h
                                   include/CCDB/BackendOCDB.h
                                   include/CCDB/BackendRiak.h
                                   include/CCDB/Condition.h
diff --git a/CCDB/include/CCDB/CcdbApi.h b/CCDB/include/CCDB/CcdbApi.h
index 66bfbcf13e..c8d37565c3 100644
--- a/CCDB/include/CCDB/CcdbApi.h
+++ b/CCDB/include/CCDB/CcdbApi.h
@@ -199,6 +199,8 @@ class CcdbApi //: public DatabaseInterface
 
   /// Base URL of the CCDB (with port)
   std::string mUrl;
+
+  ClassDef(CcdbApi,1);
 };
 } // namespace ccdb
 } // namespace o2
diff --git a/CCDB/src/CCDBLinkDef.h b/CCDB/src/CCDBLinkDef.h
index 29ed3e6337..31db6fec5b 100644
--- a/CCDB/src/CCDBLinkDef.h
+++ b/CCDB/src/CCDBLinkDef.h
@@ -14,6 +14,7 @@
 #pragma link off all classes;
 #pragma link off all functions;
 
+#pragma link C++ class o2::ccdb::CcdbApi + ;
 #pragma link C++ class o2::ccdb::IdPath + ;
 #pragma link C++ class o2::ccdb::IdRunRange + ;
 #pragma link C++ class o2::ccdb::ConditionId + ;
````

**Comment by mfasDa** [comment]
@shahor02 Thanks for the investigation! This is the same error I saw on Ubuntu (which is slightly different compared to the stack trace on mac), and as mentioned before it didn't happen during execution but already during just-in-time compilation. I did some checks before also commenting/uncommenting the macro line-by-line, and the I was able to compile and run the macro until I came to the line with the dynamic cast, so I was able to run the store, and the entry was also present in the test CCDB, but when doing the retrieve it was failing. It would be very nice to have this fixed in the CcdbApi, also the missing dictionary there is very inconvenient when using this in macros.

Cheers

Markus

**Comment by mfasDa** [comment]
The crash of BadChannelMap_CCDBApitest_V1.C is fixed by #2217, so the Read/Write test can now be done purely with a macro and the CalibDB class is not strictly mandatory for having the test passing. However for easy handling we would like to have the functionality. Part can be quite common for all detectors. To be decided whether this can be ported upstream.

**Comment by shahor02** [comment]
@mfasDa we discussed with @costing and @ktf, the error handling should be eventually included to the framework ccdb support (which, as far as I understand, will not be related to CcdbApi and will override it).

**Comment by ktf** [comment]
I guess you can probably use `Framework/Utils` for it, at least for now?

**Comment by shahor02** [comment]
@ktf but I don't see anything CCDB related in the Framework/Utils, what exactly do you mean?

**Comment by shahor02** [comment]
@mfasDa OK, it will take some time until @ktf will distill out the CCDB methods from the DPL to standalone utils, then the exeptions + helpers can be moved from your code to CCDB. I will merge this PR as it is once it passes the CI checks (you should add ``BadChannelMap_CCDBApitest_V1.C`` to tests and apply clang-format)

**Comment by mfasDa** [comment]
Hi @shahor02, thanks for your help! I have fixed the formatting and renamed the histograms depending on whether they use the CalibDB interface or CcdbApi interface. For the moment I excluded the macros from the tests as they would do each time a store in the CCDB - I would like to keep this feature for user requests and not in the CI tests. However running a compile test for the macros as it is done for a couple of macros would be fine - where can I add them?

**Comment by shahor02** [comment]
@mfasDa To allow only compiled test of the macro you should add in the end of the ``o2_add_test_root_macro`` the ``COMPILE_ONLY`` keyword (``LOAD_ONLY`` for opposite), e.g.
````
o2_add_test_root_macro(BadChannelMap_CCDBApitest_V1.C
            PUBLIC_LINK_LIBRARIES O2::EMCALCalib
            LABELS emcal COMPILE_ONLY)
````

**Comment by mfasDa** [comment]
@shahor02 Thanks for the help! OK, I added the compile test for the test macro and squashed the commits - the branch should be ready for merging now.

**Comment by mfasDa** [comment]
The failing test is not due to this change!

**Comment by shahor02** [comment]
Indeed, but I cannot merge unless all required tests are green, @ktf or @matthiasrichter can.

**Comment by mfasDa** [comment]
@shahor02 Now the tests are green (for whatever reason), I guess it can be merged now?

**Pull request merged**
