### PR TITLE
Code to write and reconstruct raw data analysis

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Review by shahor02 — COMMENTED** [review]
@peressounko What is the reason for this commit? Judging by the title you wanted to commit something else.

**Comment by peressounko** [comment]
This commit implements digits->raw conversion and raw reading. Non-PHOS files accidentally added reverted to dev version

**Review by shahor02 — CHANGES_REQUESTED** [review]
Hi @peressounko 

Could you please add an executable for digits to raw conversion, like https://github.com/AliceO2Group/AliceO2/blob/3f1f50ebc2d654da5c29cbc464541a43a031686a/Detectors/EMCAL/simulation/CMakeLists.txt#L26-L29 and make sure it works? 
To have the naming uniform with other detectors, I would call it ``digi2raw`` rather than ``rawcreator``.

Note that the CI's fail with:
````
[ 64%] Generating G__O2CPVCalib.cxx, ../../../stage/lib/G__O2CPVCalib_rdict.pcm, ../../../stage/lib/libO2CPVCalib.rootmap
input_line_11:1046:3: error: unknown type name 'uint'
  uint mMaxSample = 0;               ///< maximal sample
  ^
````

**Review by shahor02 — CHANGES_REQUESTED** [review]
@peressounko thanks for adding the executable, I've tested it but it always generate 1 output file, even if the option ``--file-for link`` is provided. Could you modify the RawCreator like it is done for EMCAL: https://github.com/peressounko/AliceO2/blob/5758855fcba6c3305cb2afaed885215e649e45de/Detectors/EMCAL/simulation/src/RawCreator.cxx#L102
Also, for the uniformity, please use ``PHSraw.cfg`` for the config file at https://github.com/peressounko/AliceO2/blob/5758855fcba6c3305cb2afaed885215e649e45de/Detectors/PHOS/simulation/src/RawCreator.cxx#L99

The rest seems to be ok.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
