### PR TITLE
[O2-812] Unused class rule is an error

### PR DESCRIPTION
**Pull request by aphecetche**
This PR should solve [O2-812](https://alice.its.cern.ch/jira/browse/O2-812). 

1. calls to rootcling are now wrapped in a script that detects the "Unused class rule" warnings and bails out when found
2. the existing "Unused class rule" occurrences (in DetectorsBase, TRD, PHOS and MID) have been fixed

Note that the TRD one about MCTruthContainer (also addressed in #2296) has been fixed using an include directly into the LinkDef, as per @davidrohr (very good) suggestion. But maybe in a subsequent PR the TRD people might instead consider moving the MCLabel (and the inclusion of MCTruthContainer<o2::trd::MCLabel> in the dictionary) from the base library to the simulation library ? (and then the explicit include of MCTruthContainer in the Linkdef would no longer be required). But that's of course up to them.

### CODE REVIEW

**Comment by ktf** [comment]
@aphecetche @Barthelemy I see:

```
++ cmake --build . -- -j4 install
[  1%] Generating G__QualityControlTypes.cxx, ../lib/G__QualityControlTypes_rdict.pcm, ../lib/libQualityControlTypes.rootmap
/bin/sh: ../rootcling_wrapper.sh: No such file or directory
gmake[2]: *** [Framework/G__QualityControlTypes.cxx] Error 127
gmake[1]: *** [Framework/CMakeFiles/QualityControlTypes.dir/all] Error 2
gmake: *** [all] Error 2
++ export ROOTSYS=/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-18-00-1
```

any idea?

**Comment by aphecetche** [comment]
My bad. Forgot (once again...) to check the full suite... Will do.

**Comment by aphecetche** [comment]
now ok. @Barthelemy btw I guess the AddRootDictionary.cmake from QualityControl/cmake could be simply removed (as the one from O2 is used anyway ?)

**Comment by Barthelemy** [comment]
@aphecetche yes, I think so. It is a left over. I will remove it.

**Comment by sawenzel** [comment]
@davidrohr : Yes I think we address this in a separate cleanup.

**Pull request merged**
