### PR TITLE
Fix for not throwing exception in cpv::RawReaderMemory when processin…

### PR DESCRIPTION
**Pull request by sevdokim**
…g corrupted RDH
Hello @davidrohr @shahor02 
This is a fix to catch exception which is thrown when reading corrupted cpv raw data.

### CODE REVIEW

**Comment by shahor02** [comment]
@sevdokim the https://github.com/AliceO2Group/AliceO2/blob/302104609ee006de31a28241bb675c0243ac0fcf/Detectors/CPV/reconstruction/src/RawReaderMemory.cxx#L59 will now detect the error and return a proper error code (w/o rethrowing) but the caller function does not check the returned value, it just catches exceptions. 
You should check it and in case of error abandon the TF processing (still sending output to not block the workflow and logging corresponding message, like you do for the deadbeef).

**Comment by sevdokim** [comment]
Hi @shahor02 
is it really necessary to abandon whole TF in case of bad rdh catched? Currently it just skips page with bad rdh and process the rest of TF.

**Comment by shahor02** [comment]
@sevdokim strictly speaking it is not necessary to skip whole TF, but RDH errors usually mean memory problems, likely the whole TF will be corrupted.
In any case, I don't see where do you skip the page with bad RDH: in https://github.com/AliceO2Group/AliceO2/blob/302104609ee006de31a28241bb675c0243ac0fcf/Detectors/CPV/workflow/src/RawToDigitConverterSpec.cxx#L129 you are not checking the return code of the `next()` and proceed to decoding unless the exception was caught, but it will not be caught there since you have a catch in the `nextPage()`.

**Comment by sevdokim** [comment]
Hi @shahor02 
you are absolutely right! Thank you very much for careful review of the code. Skipping of corrupted tf is implemented now. It seems to be working fine with randomly generated rdh versions.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
