### PR TITLE
[WIP][EMCAL-1055] Use EMCAL self-triggered mode for full system test

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Should fix the full system test

**Comment by mfasDa** [comment]
As I already expected the problem is the trigger configuration. For the FST we use by default run 310000, for which I found the following trigger classes:
```
Found class: CMBV0 (upper CMBV0) with class mask: 0 and input mask 0000000000000000000000000000000000000000000000000000000000000001, cluster (ALL with det mask 0000000000000000000000000000000000000000000000000011000000000010)
Found class: CMBT0 (upper CMBT0) with class mask: 1 and input mask 0000000000000000000000000000000000000000000000000000000000110000, cluster (ALL with det mask 0000000000000000000000000000000000000000000000000011000000000010)
Found class: CINT4 (upper CINT4) with class mask: 2 and input mask 0000000000000000000000000000000000000000000000000000000000110001, cluster (ALL with det mask 0000000000000000000000000000000000000000000000000011000000000010)
Found class: CINTV0T0 (upper CINTV0T0) with class mask: 3 and input mask 0000000000000000000000000000000000000000000000000000000001000001, cluster (ALL with det mask 0000000000000000000000000000000000000000000000000011000000000010)
Found class: CT0A (upper CT0A) with class mask: 4 and input mask 0000000000000000000000000000000000000000000000000000000000010000, cluster (ALL with det mask 0000000000000000000000000000000000000000000000000011000000000010)
Found class: CT0B (upper CT0B) with class mask: 62 and input mask 0000000000000000000000000000000000000000000000000000000000100000, cluster (ALL with det mask 0000000000000000000000000000000000000000000000000011000000000010)
Found class: CINTHM (upper CINTHM) with class mask: 63 and input mask 0000000000000000000000000000000000000000000000000000000010001000, cluster (ALL with det mask 0000000000000000000000000000000000000000000000000011000000000010)
```
All trigger the cluster all, none of them has any detector except TPC, T0 and V0 in the cluster - `ALL` is a lie. Consequently in the EMCAL simulation we find no trigger where EMCAL is in the cluster and reject all BCs. 

Also the inputs do not look compatible with what is expected, i.e. `MTVX` is called here `MFT0Vertex` - neither our nor the CTP digitization will get this properly. Same for the other FIT triggers.

@lietava

**Comment by mfasDa** [comment]
PR set to WIP - Roman promised me to update the trigger configuration for unanchored MC, in this case the self-triggered mode will not be needed for this purpose.

**Comment by lietava** [comment]
HI @mfasDa , I found that there is already open ticket for this:
https://alice.its.cern.ch/jira/browse/O2-3866
@shahor02 : can the configs be uploaded, please ?
Cheers, Roman.

**Comment by mfasDa** [comment]
No longer needed - with realistic CTP configuration the triggerinputs are found and triggers are accepted.

**Pull request closed without merging**
