### PR TITLE
IDCs: Adding Device for FT on EPNs

### PR DESCRIPTION
**Pull request by matthias-kleiner**

### CODE REVIEW

**Comment by matthias-kleiner** [comment]
Hello,
looking at the log of build/O2/o2, the test for the Fourier transform (testO2TPCIDCFourierTransform) sometimes ends with an error message of:

`*** Illegal instruction Register dump:….`

I think that this error is related to SIMD instructions that are automatically used when the Fourier coefficients are calculated with the FFTW3 library. For some reason the CPU does not know these instructions on some machines, so the test fails, but I am not 100% sure if this is the reason or if it is something else.
In the latest log the test goes through without any problems, but I think this error might cause problems in the future.

Does anyone have any idea why this might happen on some machines (are they using different CPUs?) and if there is something that can be done to avoid this failing test on some machines?

**Review by wiechula — DISMISSED** [review]
Fine for me.

**Comment by matthias-kleiner** [comment]
> Hello,
> looking at the log of build/O2/o2, the test for the Fourier transform (testO2TPCIDCFourierTransform) sometimes ends with an error message of:
> 
> `*** Illegal instruction Register dump:….`
> 
> I think that this error is related to SIMD instructions that are automatically used when the Fourier coefficients are calculated with the FFTW3 library. For some reason the CPU does not know these instructions on some machines, so the test fails, but I am not 100% sure if this is the reason or if it is something else.
> In the latest log the test goes through without any problems, but I think this error might cause problems in the future.
> 
> Does anyone have any idea why this might happen on some machines (are they using different CPUs?) and if there is something that can be done to avoid this failing test on some machines?

This problem also occurred now in other build tests.
@davidrohr  do you have an idea how to debug this or who could help debugging?

I have also attached the full build log for one of the failed tests:
[fullLog_o2-dataflow.txt](https://github.com/AliceO2Group/AliceO2/files/6829138/fullLog_o2-dataflow.txt)

**Comment by matthias-kleiner** [comment]
> > Hello,
> > looking at the log of build/O2/o2, the test for the Fourier transform (testO2TPCIDCFourierTransform) sometimes ends with an error message of:
> > `*** Illegal instruction Register dump:….`
> > I think that this error is related to SIMD instructions that are automatically used when the Fourier coefficients are calculated with the FFTW3 library. For some reason the CPU does not know these instructions on some machines, so the test fails, but I am not 100% sure if this is the reason or if it is something else.
> > In the latest log the test goes through without any problems, but I think this error might cause problems in the future.
> > Does anyone have any idea why this might happen on some machines (are they using different CPUs?) and if there is something that can be done to avoid this failing test on some machines?
> 
> This problem also occurred now in other build tests.
> @davidrohr do you have an idea how to debug this or who could help debugging?
> 
> I have also attached the full build log for one of the failed tests:
> [fullLog_o2-dataflow.txt](https://github.com/AliceO2Group/AliceO2/files/6829138/fullLog_o2-dataflow.txt)

It seems that this error only occurs when the build is done on alientestXX. On aliBuildXX.cern.ch it seems to work without problems. Does anyone know what the differences are between alientestXX and aliBuildXX.cern.ch e.g. are they using different hardware?

**Comment by wiechula** [comment]
> It seems that this error only occurs when the build is done on alientestXX. On aliBuildXX.cern.ch it seems to work without problems. Does anyone know what the differences are between alientestXX and aliBuildXX.cern.ch e.g. are they using different hardware?

@TimoWilken @MichaelLettrich , do you have an idea?

**Comment by TimoWilken** [comment]
Here's `/proc/cpuinfo` on two representative machines from alibuild and alientest:

`alibuild*`:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear spec_ctrl intel_stibp
```

`alientest*`:
```
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
```

**Comment by MichaelLettrich** [comment]
@wiechula @matthias-kleiner : Our builders are all VMs, the `aliBuildXX` ones are CERN openstack whereas the `alientestXX` are virtual box on some ALICE servers. For `alientestXX`, we are in control of the hardware and can assure you that the machines always stay on the same hardware host, not sure about the CERN openstack ones. In any case - the examples that @TimoWilken extracted, show that `alientestXX` machines do not seem to support AVX2, so indeed the hardware is different.

**Comment by matthias-kleiner** [comment]
> Here's `/proc/cpuinfo` on two representative machines from alibuild and alientest:
> 
> `alibuild*`:
> 
> ```
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology eagerfpu pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear spec_ctrl intel_stibp
> ```
> 
> `alientest*`:
> 
> ```
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm cpuid_fault epb pti intel_ppin ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase smep erms xsaveopt dtherm ida arat pln pts md_clear flush_l1d
> ```

Thanks for your help :) It looks like alientest does not support AVX2. The build flags for the FFTW library are set with AVX and AVX2 enabled. Do you know if it is somehow possible that alientest picks up a version of FFTW compiled with AVX2 on or are these libraries compiled individually on every machine each time O2 builds?

**Comment by MichaelLettrich** [comment]
@matthias-kleiner yes FFTW3 is built with avx2 support enabled https://github.com/alisw/alidist/blob/master/fftw3.sh - as you specified in your own recipe ;)

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner yes FFTW3 is built with avx2 support enabled https://github.com/alisw/alidist/blob/master/fftw3.sh - as you specified in your own recipe ;)

Yes I know I enabled it, but I am wondering why this could cause the error since in the instructions [https://www.fftw.org/fftw3_doc/Installation-on-Unix.html](url) it says 

> Enable various SIMD instruction sets. You need compiler that supports the given SIMD extensions, but FFTW will try to detect at runtime whether the CPU supports these extensions. That is, you can compile with--enable-avx and the code will still run on a CPU without AVX support. 

Shouldn't this then somehow detect that AVX2 is not available on Alientest? Or is there another way to disable the build flag AVX2 on machines that do not support AVX2? Or do you think the only way to fix the error is to just remove the flag?

**Comment by MichaelLettrich** [comment]
@matthias-kleiner since fftw says they have a runtime auto-detection, you will probably have to figure out why it is not working propperly for you and fix it using their documentation or support channels. 
* Another way is to have multiple builds of the library and figure out in our O2 CMake, which hardware is used on our plaform and link against the correct library (wouldn't advice that) 
* There are compile time defines that are emitted by the compiler that you can in your code (see https://stackoverflow.com/questions/28939652/how-to-detect-sse-sse2-avx-avx2-avx-512-avx-128-fma-kcvi-availability-at-compile). Again this requires to play around with our CMake. 

Throughout my studies I was working a lot with super computers and SIMD code and there are certain pitfalls. I can offer some support should you get stuck.

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner since fftw says they have a runtime auto-detection, you will probably have to figure out why it is not working propperly for you and fix it using their documentation or support channels.
> 
>     * Another way is to have multiple builds of the library and figure out in our O2 CMake, which hardware is used on our plaform and link against the correct library (wouldn't advice that)
> 
>     * There are compile time defines that are emitted by the compiler that you can in your code (see https://stackoverflow.com/questions/28939652/how-to-detect-sse-sse2-avx-avx2-avx-512-avx-128-fma-kcvi-availability-at-compile). Again this requires to play around with our CMake.
> 
> 
> Throughout my studies I was working a lot with super computers and SIMD code and there are certain pitfalls. I can offer some support should you get stuck.

@MichaelLettrich thank you very much for the detailed help :) As a first step I will disable AVX2 when compiling FFTW and see if this solves the problem. After that I try to enable AVX2 again in a separate PR.

Thank you for offering to help. If I get stuck, I will let you know.

**Comment by matthias-kleiner** [comment]
Now all tests are passing after disabling AVX2 during building of FFTW3.
Can this PR then be merged?

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
