### PR TITLE
DPL: add support for lhcPeriod in DataTakingContext

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf : While you are at it, could you also add
- Run Type
- List of participating detectors
from https://alice.its.cern.ch/jira/browse/OCTRL-622
The FMQ properties are already set by DDS:
```


  | SetProperties request properties:
-- | --
I |   | 21:34:22.956 | production | ODC | ODC |   | key: environment_id, value: 2YNxZ224AzD
I |   | 21:34:22.956 | production | ODC | ODC |   | key: run_type, value: PHYSICS
I |   | 21:34:22.956 | production | ODC | ODC |   | key: lhc_period, value: LHC22a
I |   | 21:34:22.956 | production | ODC | ODC |   | key: detectors, value: CPV,FDD,FT0,FV0,ITS,MCH,MFT,MID,PHS,TPC,TRD,ZDC
```

**Comment by ktf** [comment]
Done.

**Comment by ktf** [comment]
@vascobarroso are they propagate by ecs also in staging?

**Comment by shahor02** [comment]
@ktf can this be merged, I want to push the followup dependent changes

**Comment by ktf** [comment]
done

**Pull request merged**
