### PR TITLE
Next step towards the simulation challenge

### PR DESCRIPTION
**Pull request by victor-gonzalez**
Producing filtered tables for both
- reconstructed
- generated

Generating QA for the filter process for both
- reconstructed
- generated

### CODE REVIEW

**Comment by victor-gonzalez** [comment]
There is a wrong use of `TParticlePDG` that seems to only be caught by the build on macOS
I will commit a fix

**Comment by victor-gonzalez** [comment]
There is still one issue with the TracksExtended table remnant of the nightly tests
I will commit a fix

**Comment by victor-gonzalez** [comment]
In my understanding, the error on macOS is basically saying no errors

**Review by jgrosseo — APPROVED** [review]
@victor-gonzalez Can you also start adding comments for all columns and tables (see data model for the format)

**Comment by jgrosseo** [comment]
Mac CI empty. Merging.

**Pull request merged**
