### PR TITLE
DPL: add our own signal handler for SEGV and alike

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by davidrohr — CHANGES_REQUESTED** [review]
Can we do this such that it catches the SEGV etc. only when `O2_NO_CATCHALL_EXCEPTIONS` is not set, otherwise we get the same debugging issues as we had with the exceptions. There, we have put this check before activating exception handling:
```
static bool noCatch = getenv("O2_NO_CATCHALL_EXCEPTIONS") && strcmp(getenv("O2_NO_CATCHALL_EXCEPTIONS"), "0");
```

**Comment by ktf** [comment]
Like it is now, you mean?
For the record, I am not sure this will actually work without any issues, but at least we will be able to tell if the issue with the demangling is due to the fact we do not use the system compiler but use libSegFault from the system.

cc @jgrosseo

**Comment by davidrohr** [comment]
yes, that is what I meant

**Comment by ktf** [comment]
Ok, this seems to work (tested on hyperloop). It will only print the thread which had the exception. To do more than that we can simply fall back to the old libSegFault approach, which I leave for advanced usage.

**Pull request merged**
