### PR TITLE
FT0 simulation cuts optical volumes

### PR DESCRIPTION
**Pull request by AllaMaevskaya**

### CODE REVIEW

**Comment by mslupeck** [comment]
Hi @AllaMaevskaya,
Do you know of any document describing what each cut actually means?

Also if I understand it right you have just added now the cut file into your directory, but you are not using it in the code yet. Correct?

**Comment by AllaMaevskaya** [comment]
Hello
about these parameters you can have a look at old GEANT3 manual, PHYS section.
Did you prepare such cuts for FV0?

**Comment by mslupeck** [comment]
Not yet, I'm pushing to finish my thesis this week, so everything else is basically on hold for a few more days

**Comment by sawenzel** [comment]
@mslupeck : The framework probes for the presence of the `simcuts.dat` file and if found it will apply the cuts automatically.

**Comment by mslupeck** [comment]
Ah, I see now there is a medium ID in the dat file. I was wondering about how the framework knows which line apply to which material. Anyway thanks for the clarification

**Pull request merged**
