### PR TITLE
Add missing std namespace specifier in AnalysisDataModel

### PR DESCRIPTION
**Pull request by vkucera**

### CODE REVIEW

**Comment by ktf** [comment]
This is fine, but I think it will now use the float version, rather than the double one. Is that ok?

**Comment by vkucera** [comment]
> This is fine, but I think it will now use the float version, rather than the double one. Is that ok?

Why would it change by adding the `std::` prefix? Aren't the same functions called in both cases? I thought that we just silently use the `std` namespace because there is `using namespace std` somewhere in the headers.

**Comment by ktf** [comment]
There is (hopefully) no `using namespace std` and if there is, we should get rid of it. My point is that `tan()` is a valid function in `<cmath>` / `<math.h>` which has prototype `double tan(double)` (and similar for the others). On the other hand `std::tan` has overloads for float, double and int, and the compiler will pick the best fitting version (according to C++ overloading rules). This means that while the C version will always perform a conversion to double while the C++ version might not. This might not be numerically equivalent.

**Comment by vkucera** [comment]
That's a good point.
AFAIU, [`double tan(double)`](https://en.cppreference.com/w/c/numeric/math/tan) is defined in `math.h` and [`double std::tan(double)`](https://en.cppreference.com/w/cpp/numeric/math/tan) + overloads are defined in `cmath`.
Since `cmath` is included in O2 and not `math.h` (except for `GPU/GPUTracking/display/3rdparty/HandMadeMath.h`) and `cmath` undefines functions defined in `math.h`, I would expect that we are now using `std::tan` everywhere already.
Or am I missing something?

**Review by shahor02 — APPROVED** [review]

**Comment by shahor02** [comment]
accidentally approved/merged this PR instead of other one, then noticed the discussion. Hope it is not a problem.

**Comment by ktf** [comment]
Sorry for the delayed answer, I was away.

I am not sure what you say about cmath is true. If I have:
 
```C++
// Type your code here, or load an example.
#include <cmath>

int foo(int a) {
    return log(a);
}

int bar(int a) {
    return std::log(a);
}
```

it results in:

```
foo(int):
        push    rbp
        mov     rbp, rsp
        sub     rsp, 16
        mov     DWORD PTR [rbp-4], edi
        pxor    xmm1, xmm1
        cvtsi2sd        xmm1, DWORD PTR [rbp-4]
        movq    rax, xmm1
        movq    xmm0, rax
        call    log
        cvttsd2si       eax, xmm0
        leave
        ret
bar(int):
        push    rbp
        mov     rbp, rsp
        sub     rsp, 16
        mov     DWORD PTR [rbp-4], edi
        mov     eax, DWORD PTR [rbp-4]
        mov     edi, eax
        call    __gnu_cxx::__enable_if<std::__is_integer<int>::__value, double>::__type std::log<int>(int)
        cvttsd2si       eax, xmm0
        leave
        ret
```

See https://godbolt.org/z/rM11s5n7e for the full details. I.e. foo uses the C version (`call log`) while bar uses the C++ version `__gnu_cxx::__enable_if<std::__is_integer<int>::__value, double>::__type std::log<int>(int)`.

**Comment by vkucera** [comment]
OK, @ktf , that is indeed a convincing counter-argument.
Do you prefer to revert it then?

**Comment by ktf** [comment]
For me it is fine, it might even be faster. I think it's up to @ddobrigk and the Analysis Coordination in general to have the last word, though.

**Pull request merged**
