### PR TITLE
DPL: allow setting pipeline level via command line

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
As an example you can use this to speedup your analysis by doing something like:

```
stage/bin/o2-analysistutorial-histograms --aod-file @$HOME/src/data/filelist.txt --pipeline eta-and-phi-histograms:2 --readers 10
```

with this, it will spawn 10 AOD readers and two workers for `eta-and-phi-histograms`.

**Comment by ktf** [comment]
@ginnocen @jgrosseo @matthiasrichter you might be interested in this.

**Comment by ktf** [comment]
Obligatory screenshot:

Screenshot 2020-03-11 at 14 17 24

**Comment by ktf** [comment]
@aalkin

**Comment by jgrosseo** [comment]
Very nice!

**Pull request merged**
