### PR TITLE
DebugGUI: adding minor features to inputs/outputs display

### PR DESCRIPTION
**Pull request by ehellbar**
1) fix input/output counter in DeviceInspector
2) display input origin/descr/subspec when hovering over slot matrix
3) display input/output Lifetime in DeviceInspector and when hovering over slot matrix

### CODE REVIEW

**Comment by ktf** [comment]
Thanks! Can you add a screenshot, for the record?

**Comment by ehellbar** [comment]
Hovering over the slot matrix:
hoverslotmatrix

Hovering over the inputs in the device instpector:
hoverdeviceinspector

**Comment by ktf** [comment]
Thanks. I am not sure this will display the correct information in the case of pipelining, though. Could you verify?

**Comment by ehellbar** [comment]
The same inputs / outputs are displayed in the different pipelines. The order of the inputs / outputs might be different from pipeline to pipeline but it is always consistent between the `DataProcessingState` and the `Input/OutputRoute`, if that is what you mean. Ich checked it displaying the origin/desc/subspec both from `DataProcessingState` and `Input/OutputRoute`.

**Pull request merged**
