### PR TITLE
DPL: Add --no-catchall option to disable catching of exceptions such …

### PR DESCRIPTION
**Pull request by ktf**
…that they are passed to e.g. gdb

### CODE REVIEW

**Comment by davidrohr** [comment]
thx, will try that later.

**Comment by davidrohr** [comment]
ok, option parsing works.
But apparently I did not manage to apply it to all cases. At least some exceptions are still caught.
Will need one more update, working on it.

**Comment by davidrohr** [comment]
@ktf : OK, actually, the option parsing doesn't work. It always returns false for me, even if I run with `--no-catchall`. Could you check again? (In the meantime I have fixed 2 typos of mine in your branch...)

**Comment by ktf** [comment]
it seems also to break the analysis  stuff....

**Comment by davidrohr** [comment]
How can it possibly break the analysis stuff? This just moved some code into functions.

**Comment by ktf** [comment]
not sure yet, but reverting this systematically makes it work again.

**Pull request closed without merging**
