### PR TITLE
Implementing O2 format into AliceHLTWrapperDevice and other improvements

### PR DESCRIPTION
**Pull request by matthiasrichter**
This is the first version supporting the O2 format
https://alice.its.cern.ch/jira/browse/AOCSF-43

### CODE REVIEW

**Comment by mkrzewic** [comment]
Hi Matthias, since the HLT descriptors are 8 bytes we could easily distinguish between the "new" O2 descriptors and the "old" HLT ones by using the upper half of the dataDescription field in the O2 header. That way, for example, the legacy HLT data "ROOTTOBJ\0" would become "\0\0\0\0\0\0\0\0ROOTTOBJ\0" making it clear that it was produced by the HLT and leaving "ROOTTOBJ" free to be used in O2... This is the way I implemented it in the HLT - which currently uses this scheme for the zeromq communication - for calibration, QA and outside communication (currently only QA plots are shipped like this to DQM and to the overwatch website) etc. This simple scheme would make it easier (fully transparent) to e.g. connect O2 devices to the current HLT setup for testing/development purposes. What do you think?

**Comment by matthiasrichter** [comment]
Hi Mikolaj, that's a nice idea. Making the HLT a data producer to test O2 systems like QA or calibration would push the O2 project a lot forward.

**Comment by matthiasrichter** [comment]
looks like the code checker picks up something in the file which has non been changed at all
```bash
Utilities/aliceHLTwrapper/src/MessageFormat.cxx:208:22: error: use emplace_back instead of push_back [modernize-use-emplace]
Utilities/aliceHLTwrapper/src/Component.cxx:244:15: error: use emplace_back instead of push_back [modernize-use-emplace]
```

**Comment by ktf** [comment]
Given we have support for it now, could you add a quick and dirty man page on how the device works, what are its inputs and where to find the input files?

**Comment by ktf** [comment]
Great. Thanks. I think we can go ahead with this and have improvements in a later one.

**Pull request merged**
