### PR TITLE
[MatchITSTPCQC] Skip invalid MC labels

### PR DESCRIPTION
**Pull request by benedikt-voelkel**

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@chiarazampolli At least I see the problem occurring for the newly added ITS part here: https://github.com/AliceO2Group/AliceO2/pull/11974/files#diff-2aea412ef5b83c7eaa4da620db41216a5d46cecca685d48bce0033cfb1d313c3R533-R557

However, I could imagine that - in principle - invalid labels (such as noise --> no correspondence to MC)  could also occur in the other places which is why I added the protection there as well.

**Review by chiarazampolli — APPROVED** [review]
Thanks, it is good for me! With TPC tracks, it never happened...

**Comment by benedikt-voelkel** [comment]
@chiarazampolli @sawenzel Good to be merged I would say. Or, if any other tests would be desired, let me know.
In any case, technically it works, that I tested of course.

**Comment by chiarazampolli** [comment]
Hello @benedikt-voelkel , 

I cannot merge... maybe @sawenzel , or @shahor02 can do it?

Thanks again for fixing it!

Cheers,

Chiara

**Pull request merged**
