### PR TITLE
Data inspector

### PR DESCRIPTION
**Pull request by a-wolk**
@ktf 
Reopened #12523

### CODE REVIEW

**Review by ktf — APPROVED** [review]

**Comment by ktf** [comment]
The errors on macOS are genuine. Can you have a look?

**Review by ktf — CHANGES_REQUESTED** [review]
Please fix the macOS issues.

**Comment by mrzelak** [comment]
@ktf seems like all issues are fixed and all checks have passed.

**Comment by jotwinow** [comment]
@ktf Giulio can we go ahead with this merge?

**Comment by ktf** [comment]
Yes! Sorry I missed it!

**Pull request merged**
