### PR TITLE
Configuration lowercase namespace

### PR DESCRIPTION
**Pull request by awegrzyn**
Compatible with Configuration `v1.4.0`.
This should be merged together with alidist bump of Configuration.

### CODE REVIEW

**Comment by awegrzyn** [comment]
@ktf @knopers8

**Comment by matthiasrichter** [comment]
@awegrzyn, ok, please add a ref to the corresdonding PR in alidist

If I understand correctly, CI will fail for this PR until the other PR is merged.

**Comment by awegrzyn** [comment]
@matthiasrichter Exactly

**Comment by awegrzyn** [comment]
Both PRs are ready to be merged how can I proceed with this?

**Comment by awegrzyn** [comment]
@ktf @dberzano Why it's building `v1.4.0` instead of `v1.4.1` ?

**Comment by dberzano** [comment]
@awegrzyn give it time 😀

**Comment by Barthelemy** [comment]
Hi @dberzano , 
As discussed, the test fails for reasons unrelated to the PR. Could you merge it ? 
Thank you

**Comment by ktf** [comment]
Force merging this. This is why the current "many small packages" way of doing things is actually causing more problems than it solves. Every time you break APIs you will have this circular dependency and you will trigger a full rebuild of all the dependencies. In this particular case taking roughly 14 PRs * 4 tests * 20 minutes per rebuild => ~19 aggregated build hours. We should find a way to have all of our sources in one single place and allow users to build and package subparts independently.

**Comment by sawenzel** [comment]
Is there a way to do a group of PRs atomically (as a transaction) across repos?

**Comment by dberzano** [comment]
Nope. But it's advisable to do changes in a way that they are atomic (this
was a corner case I believe).

**Comment by Barthelemy** [comment]
I think that the best to do now is to try to see how to do better next time. 

Timeline : 
1. Yesterday Adam prepared the two PRs. Barth, Matthias and Dario are made aware of them. I tell Adam that I will merge the alidist one in the morning. I made an assumption which proved to be wrong : the second PR (O2) would rebuild quickly and can thus be merged quickly. 
1.  This morning I merge the first PR. 
1.  The second PR fails because the code of v1.4.0 is not the one apparently used by alibuild. This is probably due to the fact that v1.4.0 had been retagged. 
1.  v1.4.1 is tagged, a new alidist PR is done and merged immediately. 
1.  The O2 PR fails because v1.4.0 of Configuration is still taken for the o2check (not sure why). 
1.  The O2 PR fails because a test fails (test_Framework_test_DataAllocator , unrelated)
1.  The O2 PR waits for the last build that takes a very long time. 
1.  Giulio merges.

Ideas / questions : 
1. Try to avoid such cases by having backward compatible changes, thus atomic (alidist vs O2). 
1. If not possible, what channel to use in such a (rare) case ? 
1. Can alibuild survive retagging ? can it at least detect it and bail out ? 
1. Can the builds be sped up ? 
1. Can the build be prioritized ? 
1. I am not sure what to do with the failing test that has nothing to do with the PR. Ideas ? 
1. We should find a way to have all of our sources in one single place and allow users to build and package subparts independently. --> in my opinion this is the best of both worlds. How difficult and how much work do you estimate this change to be ?

**Comment by ktf** [comment]
1. Compatible incremental changes are always a good idea. In this particular case the problem could have been avoided by having a backward compatible namespace in `Configuration` to remove once AliceO2 was made compatible.
2. We need an integration mailing list, IMHO.
3. In general, retagging should never be allowed, IMHO. The only way to spot this is to always start from scratch so that the tag is not cached, but of course that would then take even longer for the general case.
4. Yes, by having everything in a single package and do an incremental build rather then a full rebuild. ;-) We could try stuff like ccache, but that only reduces the compilation time, not the linking, the tests, tarring up results, etc.  
5. They are already prioritised as follows: untested, tested but broken, tested and green. We can add an extra flag, but someone would need to do the development.
6. There is no simple way to check that with make based dependency handling. Some other tools, like bazel, allow you to run only the tests which depend on the changes but even in that case you might still have race conditions that are not always triggered.
7. We would need to evaluate the solution a bit and we need to move away from cmake to something like [bazel](https://bazel.build), [pants](https://www.pantsbuild.org), or [buck](https://buckbuild.com). Notice also that we would still need (at least to start with) something like alibuild to manage dependencies on real externals (e.g. ROOT, Geant4).

**Comment by aphecetche** [comment]
wrt 7. 

If I understand correctly, you are considering here to move to a monorepo with another build system. Quite a change ;-) 

Without giving (yet) an opinion on that, I can at least give my first reactions 😄, which are :  a) "wow, let's discuss it and do a serious pros and cons exercise" b) if we want to do that, the sooner the better (or, said otherwise, the longer we wait, the harder it will be to make such a change...) 

Or did I miss the point ?

**Comment by ktf** [comment]
@aphecetche you got it right and I agree with all of what you say. My current thinking is that something like:

https://www.tweag.io/posts/2018-03-15-bazel-nix.html

using alibuild rather then nix could be a good starting point.

This approach would also allow us not to have a single tool for packaging externals, but we could use pip to install python packages, npm to manage node.js and we could even mix and match different version of the various tools in different subproject.

**Comment by Barthelemy** [comment]
It would also be important to collect requirements before the pros and cons.

**Comment by ktf** [comment]
@Barthelemy I fully agree. As a start, do we have the one which was used for the current one? I found those which I used to design aliBuild, but do we have anything like that for CMake. It's also probably better if we move the discussion somewhere else (discourse?)

**Comment by Barthelemy** [comment]
@ktf There was an evaluation for alibuild but not for cmake as far as I know. Discourse could be a good place for the discussion.

**Pull request merged**
