### PR TITLE
DPL: unify the InputRecord::get API

### PR DESCRIPTION
**Pull request by ktf**
Support getting the sub-parts while doing so.

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 this should simplify retrieving the subparts, as you and @chiarazampolli requested.

**Comment by shahor02** [comment]
Thanks @ktf it works as expected, please merge asap.

**Comment by ktf** [comment]
I fixed the other issue. Waiting for the tests and then we can merge.

**Comment by ktf** [comment]
Merging this as it is unblocks @shahor02 & @chiarazampolli .

**Comment by ktf** [comment]
I am not sure it would work for an external `DataRef &` without the `std::decay` because R would be (I think) `DataRef const&`.

**Pull request merged**
