### PR TITLE
Set TrackExtra001 as default

### PR DESCRIPTION
**Pull request by fmazzasc**
To be merged after the merging of
- #12044 
- https://github.com/AliceO2Group/O2Physics/pull/3572

### CODE REVIEW

**Comment by fmazzasc** [comment]
@jgrosseo , @aalkin , @mpuccio 

I had to define the old implementation of `ITSNCls` , `ITSNClsInnerBarrel` , `ITSClusterMap` outside the namespace `v000` . The reason is that there are many O2Physics derived data models relying on these columns and I did not want to modify all of them. See for example:
- https://github.com/AliceO2Group/O2Physics/blob/fd4b69c858654559a6d3a7980b9e28435eea6d89/PWGEM/PhotonMeson/DataModel/gammaTables.h#L174
- https://github.com/AliceO2Group/O2Physics/blob/fd4b69c858654559a6d3a7980b9e28435eea6d89/PWGJE/DataModel/TrackJetQa.h#L146
- https://github.com/AliceO2Group/O2Physics/blob/fd4b69c858654559a6d3a7980b9e28435eea6d89/PWGLF/DataModel/LFNucleiTables.h#L173

If you don't like this change I can put all the columns under the namespace, then change in O2Physics all the columns relying on `track::ITSClusterMap` or `track::ITSNCls` into `track::v000::ITSClusterMap` and `track::v000::ITSNCls` . If we choose this option, we have to be aware that the compilation of O2Physics would fail between the merging of this P.R. and the patch in O2Physics.
What do you think? Any smarter ideas?

**Comment by jgrosseo** [comment]
Frankly, I would leave the old columns in the `tracks` namespace and the new ones in `tracks::v001` (as already merged). I think the rest is confusing.

**Comment by fmazzasc** [comment]
@jgrosseo , I agree with you. v001 restored

**Comment by jgrosseo** [comment]
> @jgrosseo , I agree with you. v001 restored

Thanks!
Still the diff moves some code around. Could you clean this up? We should make the minimal changes needed...

**Comment by jgrosseo** [comment]
And isn't the change of filling the table in the producer missing?

**Comment by fmazzasc** [comment]
@jgrosseo , minimal changes done. And the filling of the AODProducer should be more visible now ;)

**Review by jgrosseo — APPROVED** [review]

**Comment by jgrosseo** [comment]
Looks good!

Before merging, please test if the converter works on Hyperloop. Once you have successfully tested, I can clone it as service wagon

**Comment by fmazzasc** [comment]
I tested it on hyperloop and it works. But I would still wait for https://github.com/AliceO2Group/O2Physics/pull/3671 to be merged, as the converter name will change

**Comment by fmazzasc** [comment]
Hi @jgrosseo , @ddobrigk , the tracks-extra-converter is now ready and has the correct name. I tested it on hyperloop and I cross checked again that it preserves the correct ITSClusterMap. Whenever you want, you can merge this P.R. and create the service wagon

**Comment by jgrosseo** [comment]
I have put auto merge and then wait for fullCI
@ddobrigk Could you create the service wagon and alert people? Myself I will be offline this afternoon...

**Comment by ddobrigk** [comment]
@fmazzasc @jgrosseo thanks a lot! Service wagon has been created here: https://alimonitor.cern.ch/hyperloop/view-wagon/6495 - I will write an announcement message when merged.

**Review by mconcas — APPROVED** [review]

**Comment by ddobrigk** [comment]
Hmmm not sure why this isn't merged, I guess we still miss an approval by someone?... (I have no permissions)

**Pull request merged**
