### PR TITLE
ALICE 3: Add ECal detector

### PR DESCRIPTION
**Pull request by mconcas**
Currently simplified as a lead cylinder.
Screenshot from 2024-02-08 22-25-00

This PR requires CCDB to add an additional dummy alignment object, opening the relevant JIRA ticket.
See: https://its.cern.ch/jira/browse/O2-4643

### CODE REVIEW

**Comment by mconcas** [comment]
> Error while checking build/O2/fullCI for [0781037](https://github.com/AliceO2Group/AliceO2/commit/0781037543e26b7a0d5d26875746131eb24eee64) at 2024-02-13 11:55:
> 
> ```
> ## sw/BUILD/O2-latest/log
> c++: error: unrecognized command-line option '--rtlib=compiler-rt'
> c++: error: unrecognized command-line option '--rtlib=compiler-rt'
> 
> 
> ## sw/BUILD/o2checkcode-latest/log
> --
> ========== List of errors found ==========
> ++ GRERR=0
> ++ grep -v clang-diagnostic-error error-log.txt
> ++ grep ' error:'
> /sw/SOURCES/O2/12682-slc8_x86-64/0/DataFormats/simulation/src/MCTrack.cxx:21:6: error: namespace 'o2::MCTrackHelper' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/DataFormats/Parameters/src/GRPECSObject.cxx:42:42: error: namespace 'o2::parameters::GRPECS' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/DataFormats/Parameters/src/GRPECSObject.cxx:42:71: error: namespace 'o2::parameters::GRPECS' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:22:28: error: namespace 'o2::emcal::STUparam' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:172:34: error: namespace 'o2::emcal::TRUparam' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:173:33: error: namespace 'o2::emcal::TRUparam' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:175:31: error: namespace 'o2::emcal::TRUparam' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:189:31: error: namespace 'o2::emcal::TRUparam' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/Detectors/EMCAL/reconstruction/src/StuDecoder.cxx:190:33: error: namespace 'o2::emcal::TRUparam' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/EventVisualisation/DataConverter/src/VisualisationEventJSONSerializer.cxx:149:44: error: namespace 'o2::parameters::GRPECS' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/EventVisualisation/DataConverter/src/VisualisationEventROOTSerializer.cxx:199:44: error: namespace 'o2::parameters::GRPECS' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/EventVisualisation/DataConverter/src/VisualisationEventJSONSerializer.cxx:149:44: error: namespace 'o2::parameters::GRPECS' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/EventVisualisation/DataConverter/src/VisualisationEventROOTSerializer.cxx:199:44: error: namespace 'o2::parameters::GRPECS' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/EventVisualisation/View/src/EventManager.cxx:130:51: error: namespace 'o2::parameters::GRPECS' does not follow the underscore convention [aliceO2-namespace-naming]
> /sw/SOURCES/O2/12682-slc8_x86-64/0/Detectors/GRP/workflows/src/create-grp-ecs.cxx:87:96: error: namespace 'o2::parameters::GRPECS' does not follow the underscore convention [aliceO2-namespace-naming]
> ++ [[ 0 == 0 ]]
> ++ exit 1
> --
> ```
> 
> Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/12682/0781037543e26b7a0d5d26875746131eb24eee64/build_O2_fullCI/pretty.html).

@shahor02 do you think these are genuine errors? I tried to re-spinned the CI and they appeared again. I would not mind fixing them, but I have no idea why they appear in this PR only (?). CC-ing @TimoWilken as well.

**Comment by TimoWilken** [comment]
Indeed the errors seem unrelated. This should work around it: https://github.com/alisw/alidist/pull/5352

**Comment by mconcas** [comment]
> Indeed the errors seem unrelated. This should work around it: [alisw/alidist#5352](https://github.com/alisw/alidist/pull/5352)

Thanks a lot for taking care of this. I'd like to merge this only when all CI is green; let me know if re-triggering a build (after merging PR in Alidist) will pick up the correct version.

**Comment by TimoWilken** [comment]
I've merged the fix in alidist and restarted the fullCI check! It should pick up the fix immediately.

**Comment by mconcas** [comment]
> I've merged the fix in alidist and restarted the fullCI check! It should pick up the fix immediately.

Thanks a lot Timo!

**Pull request merged**
