### PR TITLE
The final version of merging prototype.

### PR DESCRIPTION
**Pull request by PatrykLesiak**
The final version of merging prototype.

### CODE REVIEW

**Comment by PatrykLesiak** [comment]
Thank you @MohammadAlTurany, I actually removed this file as it is not necessary for build. I think that it is some auto generated file, because I have not created it.

**Comment by MohammadAlTurany** [comment]
Hallo Patryk,

If we merge this pull request then the AliceO2 will not compile without DDS because include it explicitly in your code, so we have to choose one of four solutions:

1.  Make DDS as a requirement of the whole project

2. make it optional, but then you have to use some "#ifdef ENABLE_DDS"  to protect the DDS parts 
    (See [aliceHLTwrapper](https://github.com/AliceO2Group/AliceO2/blob/dev/Utilities/aliceHLTwrapper/src/aliceHLTWrapper.cxx) )

3. Use QC only if DDS is found (Without ifdefs but protect on CMAKE level)

4. Use the new DDS Plugin in FairRoot  (See [MQ example 3](https://github.com/FairRootGroup/FairRoot/tree/dev/examples/MQ/3-dds) ) 

of course I prefer solution number 4.

best,

Mohammad

**Comment by PatrykLesiak** [comment]
Dear @MohammadAlTurany , 

The concept of merging prototype was to measure performance of implementation with selected tools. One of them is DDS so it is an integral part for this software and without it the point is missing.
I have looked at MQ example 3, unfortunately I cannot see there use of custom commands and updating/getting DDS properties by nodes (of course there is a json file which holds values, but in my case those values have to be set by programs during execution).
If I understood this example correctly it is not the best solution for me. 
What I would prefer is to use solution no. 3. Is it OK for you?

**Comment by MohammadAlTurany** [comment]
Hallo @PatrykLesiak 

Fine with me, let us use the option 3 as it is the simplest and fastest one. For the long term it would be better to go to the "plugins". So we have to see later if there is something missing in this mechanism or what you need to change to use it.

best,

Mohammad

**Comment by PatrykLesiak** [comment]
Dear @MohammadAlTurany ,

Could you point me the best practice to ensure conditional compilation of project ? I am thinking about adding "if (DDS_FOUND)" at the beginning of the root cmake of merging prototype project, but I am not sure if this is what you want ?

**Comment by MohammadAlTurany** [comment]
Hallo @PatrykLesiak 

just add the following to the AliceO2/Utilities/CMakeList.txt :

```
if (DDS_FOUND)
     MESSAGE("DDS is found, QC Packages will be build")
     add_subdirectory (QC)
else(DDS_FOUND)
     MESSAGE("DDS is not found, QC Packages will not be build")
endif (DDS_FOUND)

```
best,

Mohammad

**Comment by PatrykLesiak** [comment]
Dear @MohammadAlTurany ,

Changes are applied in the latest commit.

Thank you, 
Patryk

**Comment by MohammadAlTurany** [comment]
Hallo @PatrykLesiak 

One simple thing: Could you please rebase your branch to the dev and push it again?

best,

Mohammad

**Comment by PatrykLesiak** [comment]
Dear @MohammadAlTurany ,
Unfortunately it is not that simple because structure of the project was change in upstream. But I will work on it. Most probably I will rebase project this evening.

**Comment by PatrykLesiak** [comment]
Dear @MohammadAlTurany ,
I think it is done (rebase).

**Pull request closed without merging**
