### PR TITLE
Fix Z bias of TRD-matched tracks

### PR DESCRIPTION
**Pull request by shahor02**
1) When the time bias of TPC timebins was introduced, it had to be explicitly accounted for in the TPC tracks refits constrained by TRD timestamps (the t0 was subtracted from the TRD time). When the TPC fitter started to account for this t0 bias provided via VDrift object, this explicit accounting had to be removed but it was not. As a result, the t0 bias was accounted for twice, leading to a few cm bias in Z for constrained TPC tracks. While we were using large (1cm) systematic errors on Z error of TPC tracks, this bias was overridden by the following refit in the TRD or in the ITS, once we adopted smaller Z-error the bias started to affect matching in the TOF.

2) The TPC refitter was called on the track at the outer ITS or inner TRD radius (for the outward and inward refits resp.). Since the refitter propagates w/o material corrections, effectively the tracks were not accounting for the material between the TPC and ITS/TRD (before the refit, so the effect was small anyway). Now the tracks are explicitly propagated before the refit to the TPC boundary using the standard propagator accounting for materials.

Comparison of Z residuals between TOF clusters and seeding tracks before and after the fix:
tofbias

### CODE REVIEW

**Review by martenole — APPROVED** [review]
Thanks @shahor02 and sorry. I was not aware of this.

**Comment by shahor02** [comment]
(1) was done by me :)

**Comment by noferini** [comment]
Hi @shahor02 , can we merge this PR?

**Comment by chiarazampolli** [comment]
Hi @shahor02 , 

Thanks for the fix. I have a doubt: you wrote that the t0 was applied 2x to constrained TPC tracks, which would include ITSTPC. But these did not show issue in the TOF matching. Could you please explain me a bit better?

Thanks,

Chiara

**Comment by shahor02** [comment]
Hi @chiarazampolli 

The double counting was only for the refits done in the TRD matcher, other refits were ok. TRD matcher re-constrains only ITS-TPC and TPC tracks before the for in the TRD. Both were affected, TPC-only having larger errors is then partially corrected by the TRD fit.

**Pull request merged**
