### PR TITLE
Implementation of GEM model (electron efficiencies, gain, energy resolution)

### PR DESCRIPTION
**Pull request by ritzratz**

### CODE REVIEW

**Comment by wiechula** [comment]
Hi @ritzratz,
do you need further help?

**Comment by ritzratz** [comment]
Hey @wiechula ..

I am trying hard to fix this error from the test "test_TPCSimulation_testTPCGEMAmplification" right now.
I traced the seg fault back and it happens in file "O2dir/O2/Detectors/TPC/base/src/CDBInterface.cxx" in line 141: return getObjectFromCDB<ParameterGEM>("TPC/Parameter/GEM"). Don't know how to solve this right now ... I changed ParameterGEM class for my model implementation so I think this might be the reason. Yet I don't know what I should change here... can you help?

**Comment by wiechula** [comment]
Sorry, overlooked this.
I see that you changed many things in `testTPCGEMAmplification.cxx`. E.g. all about the CDBInterface. From your message above, I cannot really see at which point you get the crash. But most probably you are missing the initialization of the CDBInterface, which you have removed:
```
  auto& cdb = CDBInterface::instance();
  cdb.setUseDefaults();
```
Can you add this back and try again.

**Comment by ritzratz** [comment]
Hi @wiechula  .. thank you! This solved the problem! The only thing missing now is the clang format check. This fails as there is clang version < 3.9 installed on my system (my outdated version does not support all rules as defined in .clang-format) . So I followed the instructions 
on https://github.com/AliceO2Group/AliceO2/ to build Clang:

aliBuild build --defaults o2 Clang

This worked. However loading clang as given by the instructions does not work:
alienv load Clang/latest
or
alienv load Clang/latest-o2
or
alienv enter Clang/latest
or
alienv enter Clang/latest-o2

I found multiple instructions for this. All lead to the same error: "ERROR Clang/latest not
found". I found a way to list available modules with ./alienv q but Clang is not listed there now.

Another cool thing now: After "aliBuild build --defaults o2 Clang" (according to the instructions) I generally can not enter the environment any more with "o2env". This gives a hundred times something like "GCC-Toolchain/v7.3.0-alice1-4(19):ERROR:105: Unable to locate modulefile for 'Toolchain/GCC-v7.3.0'.

Also building O2 with "../alibuild/aliBuild -z -w ../sw build O2 --defaults o2" does not work any more giving:

Traceback (most recent call last):
 File "../alibuild/aliBuild", line 19, in <module>
  from alibuild_helpers.build import doBuild, star
 File "home/gem/AliSoftware/alibuild/alibuild_helpers/build.py", line 22, in <module>
  from requests import get
ImportError: No module named requests

What can I do now? :/

**Comment by sawenzel** [comment]
@wiechula : Do you approve?

**Pull request merged**
