### PR TITLE
[WIP] Cmake migration step 2

### PR DESCRIPTION
**Pull request by aphecetche**
Getting back to CMake 3.13 (so the CI has a chance to work "as-is")

CUDA+OpenCL+HIP are now connected.

(still missing are Root test macros).

### CODE REVIEW

**Comment by davidrohr** [comment]
@aphecetche : I am currently trying this locally. One thing I noticed is: in all the FindXXX scripts, you check for non-uppercase variables, e.g. you use pythia_ROOT and cub_ROOT instead of PYTHIA_ROOT and CUB_ROOT. Is this intended? To me, it looks a bit inconsistent.

**Comment by aphecetche** [comment]
@davidrohr Yes it is intended. The reason is that the [find_package](https://cmake.org/cmake/help/v3.14/command/find_package.html?highlight=find_package#full-signature-and-config-mode) cmake function is looking (in its config variant) for {PackageName}Config.cmake or {lower-case-package-name}-config.cmake, so the letter case does matter.

Incidentally, alidist recipes also have some idea about the case (the package: keyword is case sensitive). And as far as I can tell alidist and cmake config files share the same idea about the case.
(and even if they would not match, I would go for the CMake case as that's what is relevant in the find_package calls)

**Comment by davidrohr** [comment]
well, not fully convinced but I think it is a matter of taste. Clearly we have to use correct capitalization for the library names, but the variables are a bit tedious like this. There are still plenty which are all uppercase, so one always has to check what to use.

**Comment by davidrohr** [comment]
@aphecetche : The build fails on my system. The reason is that I have a system pythia installation, with include in /usr/include/Pythia8. The new O2 cmake creates an include directive "-isystem /usr/include/Pythia8/../", and apparently one must not use "-isystem /usr/include" (didn't now that before).
At least `echo "#include <cstdlib>" | c++ -isystem /usr/include -c -x c++ -` fails for me.

**Comment by aphecetche** [comment]
> well, not fully convinced but I think it is a matter of taste. Clearly we have to use correct capitalization for the library names, but the variables are a bit tedious like this. There are still plenty which are all uppercase, so one always has to check what to use.

well, that's dictated by find_package which uses the {PackageName}_ROOT variable as first location to search for the config file. The complete [search procedure](https://cmake.org/cmake/help/latest/command/find_package.html#search-procedure) is actually more complex, but I found {PackageName}_ROOT to be a simple compromise.

We actually don't have "plenty" of  uppercase XXX_ROOT variables. If you look at [dependencies/CMakeLists.txt](https://github.com/aphecetche/AliceO2/blob/cmake-migration-step-2/dependencies/CMakeLists.txt) (or in the poor man's [auto-detection file]( https://github.com/aphecetche/AliceO2/blob/cmake-migration-step-2/dependencies/O2FindDependenciesFromAliBuild.cmake)  you'll see ROOT,CURL,VGM,DDS,GLFW, and that's about it

**Comment by aphecetche** [comment]
> @aphecetche : The build fails on my system. The reason is that I have a system pythia installation, with include in /usr/include/Pythia8. The new O2 cmake creates an include directive "-isystem /usr/include/Pythia8/../", and apparently one must not use "-isystem /usr/include" (didn't now that before).
> At least `echo "#include <cstdlib>" | c++ -isystem /usr/include -c -x c++ -` fails for me.
> 
> This seems a bit annoying, but I guess we should filter out /usr/include include directives anyway.

Thanks for the feedback. I will have a look. There might be a "CMake-way" to deal with that.

**Comment by davidrohr** [comment]
@aphecetche : I use a gentoo Linux

And I have another problem: Compiling with HIP, I get (during compilation with ninja, not during CMake):
`ninja: error: 'hip::hip_hcc-NOTFOUND', needed by 'stage/lib64/libO2GPUTrackingHIP.so', missing and no known rule to make it`
I am wondering what is happening, why is CMake outputting this weird library name. Shouldn't it break, if it doesn't find the library.

I am also wondering what exactly it doesn't find. All the variables `${hip_INCLUDE_DIR} ${hip_LIBRARIES} ${hcc_INCLUDE_DIR} ${hcc_LIBRARY}` are filled correctly.

**Comment by davidrohr** [comment]
OK, I fixed the last problem. Apparent the hip-targets.cmake file of my HIP installation was missing the IMPORTED_LOCATION property. I don't know what happened there. Still, I am wondering why CMake produces failing ninja rules instead of breaking, and complaining about the missing property.

**Comment by davidrohr** [comment]
For the pythia includes:
The problem seems to be that the path is /usr/include/Pythia8/../
CMake will automatically filter /usr/include, but it doesn't filter the thing with the ../

If I run the following only when `${CMAKE_FIND_PACKAGE_NAME}_INCLUDE_DIR}` != /usr/include/???, it works:
```
  set_target_properties(pythia
                                   INTERFACE_INCLUDE_DIRECTORIES
                                   ${${CMAKE_FIND_PACKAGE_NAME}_INCLUDE_DIR}/..)
```

**Comment by davidrohr** [comment]
@aphecetche : Compilation went through now, but there is a weird problem during make install:
```
DEBUG:O2:O2:0: CMake Error at CCDB/cmake_install.cmake:97 (file):
DEBUG:O2:O2:0:   file INSTALL cannot find
DEBUG:O2:O2:0:   "/home/qon/alice/sw/BUILD/740a1a5c0ed9697840a08e09d41501eb7786f780/O2/stage/bin/o2-ccdb-conditions-server".
DEBUG:O2:O2:0: Call Stack (most recent call first):
DEBUG:O2:O2:0:   cmake_install.cmake:50 (include)
```
The file was definitely compiled:
```
DEBUG:O2:O2:0: [206/1266] Building CXX object CCDB/CMakeFiles/O2exe-ccdb-conditions-server.dir/src/runConditionsServer.cxx.o
DEBUG:O2:O2:0: [208/1266] Linking CXX executable stage/bin/o2-ccdb-conditions-server
```
but it is not present:
```
qon@qon ~/alice/sw/BUILD/O2-latest/O2 $ find * | grep ccdb | grep -i server
CCDB/CMakeFiles/O2exe-ccdb-standalone-client.dir/test/testQueryServerStandalone.cxx.o
CCDB/CMakeFiles/O2exe-ccdb-conditions-server.dir
CCDB/CMakeFiles/O2exe-ccdb-conditions-server.dir/src
CCDB/CMakeFiles/O2exe-ccdb-conditions-server.dir/src/runConditionsServer.cxx.o
qon@qon ~/alice/sw/BUILD/O2-latest/O2 $ ls stage/bin/o2-ccdb-
o2-ccdb-conditions-client  o2-ccdb-standalone-client  
```
No idea what to do here, does install work for you?

**Comment by aphecetche** [comment]
@davidrohr About the o2-ccdb-conditions-server you observe : I've got it also on Ubuntu, but not on CentOS or MacOS... I'm currently quite puzzled about it. 
I've changed a few things (in Cmake-migration-step-2-fixes, but not sure it'll affect that issue) so I'll try that branch tomorrow on my Ubuntu VM (which I can't access right now from remote for some unknown reason...) just in case the problem vanished...

**Comment by davidrohr** [comment]
@aphecetche : I am busy with some debugging in the TPC tracking now, but I'll check the updated branch tomorrow and report back if the issue persists.

**Comment by aphecetche** [comment]
OK. Thanks. Meanwhile I've pushed the changes of cmake-migration-step-2-fixes to this branch (cmake-migration-step-2) in order to see if the tests issues I had on Mac (not really an issue with the tests themselves, but with adapting the new tests to the existing CI recipe) are solved.

**Comment by davidrohr** [comment]
@aphecetche : I rebased on dev and rebuild, not the problem with the conditions database is gone.

**Comment by davidrohr** [comment]
@aphecetche : This fixes the problem with the pythia include path in an elegant way: https://github.com/davidrohr/AliceO2/commit/87e54798b7c273018c4f3e52b93b75e4010a6a2d

CMake will strip the system paths, but only if they are absolute, and without ../ etc.

**Comment by aphecetche** [comment]
@davidrohr Sorry I force-pushed before seeing your message about your Pythia fix. Great. Thanks. I'll anyway have another round of changes (where, for one thing, I'll x-check I don't have other places where I did not properly normalise the directory names) as the CentOS CI build is expected to fail.

**Comment by aphecetche** [comment]
Closing this one. Is has served its purpose. 

For the record the current status is that it's building fine on Mac and CentOS.

The build/o2/o2 which builds O2Suite and not just o2 (thanks @davidrohr for mentioning this, I did not know) is failing because QualityControl tries to find things that are not longer named the same. In fact, QualityControl is trying to make the job a proper O2Config.cmake file should make. FYI, @Barthelemy  that's what I'll work on next on a new branch (so this one will continue failing build/o2/o2/), while David work on ironing out the GPU parts.

**Pull request closed without merging**
