### PR TITLE
Separate cluster attachment chi2 from total chi2 selections

### PR DESCRIPTION
**Pull request by mpuccio**
- Separate chi2/ndf and track-cl chi2 cuts
- Report number of fitted tracks
- Update clusters covariance with the systematics only once

### CODE REVIEW

**Review by mconcas — DISMISSED** [review]

**Review by mconcas — APPROVED** [review]

**Comment by mconcas** [comment]
Hi @TimoWilken, any information about fullCI failures?

**Comment by shahor02** [comment]
tested with local FST, merging

**Comment by TimoWilken** [comment]
Hi @mconcas, seems like something is allocating lots of memory, we're working on it.

**Comment by mconcas** [comment]
> Hi @mconcas, seems like something is allocating lots of memory, we're working on it.

thanks a lot!

**Pull request merged**
