### PR TITLE
Align member names to our convention

### PR DESCRIPTION
**Pull request by ktf**
Rename all the members called [a-z]Something to mSomething. No, this was not done by hand..

### CODE REVIEW

**Comment by ktf** [comment]
The `build/o2checkcode/o2-daq` is noisy...

**Comment by ktf** [comment]
@sawenzel @MohammadAlTurany can you review if you agree and merge it, please?

**Comment by sawenzel** [comment]
Looks very good to me. We can merge it but it will have an effect on the other pending merge requests.

**Comment by ktf** [comment]
True. Can we review and get the other code merged, then, so that I can run
again the "fixer"?

**Comment by ktf** [comment]
I've rerun the fixer to take care of the new code. Let's wait for the tests to complete and merge it, since there is no big PR pending anymore.

**Comment by bovulpes** [comment]
Hello,

As one of the contributors to the MFT code I would like to be informed whenever possible about the changes in the code, otherwise I have to deal with a lot of conflicts to be solved. I was just doing similar "alignments" of member names according to the rules plus some other fixes.
Thank you.

Bogdan.

**Comment by sawenzel** [comment]
@bovulpes: I understand. You can easily get notified about changes in the code when you become a "watcher" of the repository. 

In this case, we wanted to fix trivial things globally so that we achieve a clean state and be able to enforce coding rules in the pull-request checks.

**Pull request merged**
