### PR TITLE
Consistently use time in seconds

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Comment by peressounko** [comment]
dear @shahor02, this time error in build/O2/fullCI  may be related to PHOS. How can I run it locally?

**Comment by shahor02** [comment]
Hi @peressounko 
to run the  FST use `$O2_ROOT/prodtests/full_system_test.sh`, you will need also AEGIS and O2DataProcessing packages. Or, build at once `aliBuild build O2PDPSuite --defaults o2`.

What is the reason of using seconds? Everywhere else we use microseconds (or ps for TOF).

**Comment by peressounko** [comment]
Dear @shahor02, historically in PHOS we have time in seconds or ns. Microseconds never appear in our physics, no sense to use it. I also added fix in Digitizer for jira ticket https://alice.its.cern.ch/jira/browse/O2-2667

**Comment by peressounko** [comment]
@shahor02, dear Ruben, I run fullCl test locally: after commenting other detectors I managed to finish it for PHOS.  In full test I encountered a lot of crashes for test out of box, probably because not all env. variables were properly set. Finally I stack with 
[5995:its-tracker]: [12:43:08][INFO]  - Track finding completed in: 72356.5 ms
[5995:its-tracker]: [12:43:08][INFO]  - Extending tracks completed in: 0.000151 ms
[5995:its-tracker]: [12:43:08][INFO]  - Timeframe initialisation completed in: 3.27273 ms
[5995:its-tracker]: [12:43:08][INFO]  - Tracklet finding completed in: 88.9255 ms
[5995:its-tracker]: [12:43:08][INFO]  - Cell finding completed in: 9.04196 ms
[5995:its-tracker]: [12:43:08][INFO]  - Neighbour finding completed in: 14.6472 ms
[5995:its-tracker]: [12:43:08][INFO]  - Road finding completed in: 7.63235 ms
[5995:its-tracker]: [12:43:42][INFO]  - Track finding completed in: 33884.4 ms
[5995:its-tracker]: [12:43:42][INFO]  - Extending tracks completed in: 0.000143 ms
[5995:its-tracker]: [12:43:42][INFO]  - Timeframe initialisation completed in: 3.71014 ms
[5995:its-tracker]: [12:43:42][INFO]  - Tracklet finding completed in: 313.043 ms
[5995:its-tracker]: [12:43:42][INFO]  - Cell finding completed in: 126.262 ms
[5995:its-tracker]: [12:43:43][INFO]  - Neighbour finding completed in: 575.342 ms
[5995:its-tracker]: [12:44:32][ERROR] Exception caught: std::bad_alloc 
[5995:its-tracker]: /home/prsnko/alice/sw/ubuntu1804_x86-64/O2/dev-local4/bin/../lib/libO2FrameworkFoundation.so(_ZN2o29framework13runtime_errorEPKc+0x6f)[0x7f46b0ca338f]
[5995:its-tracker]: /home/prsnko/alice/sw/ubuntu1804_x86-64/O2/dev-local4/bin/../lib/libO2Framework.so(+0x14ccdf)[0x7f46b1176cdf]
[5995:its-tracker]: /home/prsnko/alice/sw/ubuntu1804_x86-64/O2/dev-local4/bin/../lib/libO2Framework.so(_ZN2o29framework20DataProcessingDevice5doRunERNS0_20DataProcessorContextE+0x6b)[0x7f46b129ca2b]
[5995:its-tracker]: /home/prsnko/alice/sw/ubuntu1804_x86-64/O2/dev-local4/bin/../lib/libO2Framework.so(_ZN2o29framework20DataProcessingDevice3RunEv+0x28e)[0x7f46b129d1be]
[5995:its-tracker]: /home/prsnko/alice/sw/ubuntu1804_x86-64/FairMQ/v1.4.42-local3/lib/libFairMQ.so.1.4(_ZN4fair2mq6Device10RunWrapperEv+0x372)[0x7f46ad4940c2]

**Comment by shahor02** [comment]
Hi @peressounko 
The fullCI goes to the timeout due to the slowed down ITS reco, @mpuccio is working on that. Merging.

**Pull request merged**
