### PR TITLE
DPL: make sure firstTFOrbit is set correctly

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 this fixes the issue in my synthetic tests. Can you check with your full example?

**Comment by shahor02** [comment]
@ktf: not really, you are reassigning the TF counter rather than the `firstTFOrbit`:

````
[253918:ft0-datareader-dpl]: [13:31:30][INFO] TFORB = 0 for FT0/RAWDATA
[253919:ft0-entropy-encoder]: [13:31:31][INFO] TFORB = 0 for FT0/DIGITSBC
[253921:ctf-writer]: [13:31:31][INFO] TFORB = 0 for FT0/CTFDATA

[253918:ft0-datareader-dpl]: [13:32:00][INFO] TFORB = 32 for FT0/RAWDATA
[253919:ft0-entropy-encoder]: [13:32:00][INFO] TFORB = 1 for FT0/DIGITSBC
[253921:ctf-writer]: [13:32:00][INFO] TFORB = 1 for FT0/CTFDATA

[253918:ft0-datareader-dpl]: [13:32:15][INFO] TFORB = 64 for FT0/RAWDATA
[253919:ft0-entropy-encoder]: [13:32:15][INFO] TFORB = 2 for FT0/DIGITSBC
[253921:ctf-writer]: [13:32:15][INFO] TFORB = 2 for FT0/CTFDATA

[253918:ft0-datareader-dpl]: [13:32:30][INFO] TFORB = 96 for FT0/RAWDATA
[253919:ft0-entropy-encoder]: [13:32:30][INFO] TFORB = 3 for FT0/DIGITSBC
[253921:ctf-writer]: [13:32:30][INFO] TFORB = 3 for FT0/CTFDATA

[253918:ft0-datareader-dpl]: [13:32:45][INFO] TFORB = 128 for FT0/RAWDATA
[253919:ft0-entropy-encoder]: [13:32:45][INFO] TFORB = 4 for FT0/DIGITSBC
[253921:ctf-writer]: [13:32:45][INFO] TFORB = 4 for FT0/CTFDATA

[253918:ft0-datareader-dpl]: [13:33:00][INFO] TFORB = 160 for FT0/RAWDATA
[253919:ft0-entropy-encoder]: [13:33:00][INFO] TFORB = 5 for FT0/DIGITSBC
[253921:ctf-writer]: [13:33:00][INFO] TFORB = 5 for FT0/CTFDATA
````

**Comment by ktf** [comment]
Yes, indeed. Will have a new version  in a bit.

**Comment by ktf** [comment]
Ok, I think this new version should take care of it. It will also propagate the tfCounter correctly, as a step towards dropping the DataProcessingHeader.

**Comment by shahor02** [comment]
Thanks, now it works

**Comment by ktf** [comment]
@davidrohr we should also find a way to speedup the full system test... ;-)

**Comment by davidrohr** [comment]
> @davidrohr we should also find a way to speedup the full system test... ;-)

It should take 10-20 minutes currently. It is processing 5 Pb-Pb events.
Only thing we can do is reduce the number of events, but then we also loose statistics.

**Comment by ktf** [comment]
@davidrohr I assume those are the known failures for the fullCI?

**Comment by shahor02** [comment]
> It should take 10-20 minutes currently. It is processing 5 Pb-Pb events.
> Only thing we can do is reduce the number of events, but then we also loose statistics.

We can actually decrease the multiplicity by limiting the impact parameter, before it was trivial to do but I think it was modified. Perhaps @preghenella or @sawenzel can hing, here I see only possibility to select central collisions: https://github.com/AliceO2Group/AliceO2/blob/0748bbb5e58d9dae9380bb2c68bf7c9bba6534e2/Generators/share/egconfig/pythia8_hi.cfg#L9

**Comment by davidrohr** [comment]
> @davidrohr I assume those are the known failures for the fullCI?

Yes, these were the known failures, and they should also be gone from now on after I merged #5693

**Pull request merged**
