### PR TITLE
DPL: do not reset mDidDispatch too early

### PR DESCRIPTION
**Pull request by ktf**
DPL: do not reset mDidDispatch too early

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @shahor02 this should take care of the spurious messages with proxies and readers.

**Comment by ktf** [comment]
Errors are gone both on my box and on the CI.

**Comment by martenole** [comment]
In the FST on the EPNs I doo still see errors from the readout-proxy unfortunately:
```
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data FLP/DISTSUBTIMEFRAME/0 was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data MID/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data CTP/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data TOF/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data MFT/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data MCH/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data PHS/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data TRD/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data CPV/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data FDD/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data FT0/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data FV0/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data ZDC/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data ITS/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data EMC/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:25][ERROR] Expected Lifetime::Timeframe data TPC/RAWDATA was not created for timeslice 98 and might result in dropped timeframes
[3466400:readout-proxy]: [13:27:35][ERROR] Expected Lifetime::Timeframe data HMP/RAWDATA was not created for timeslice 99 and might result in dropped timeframes
```

**Comment by martenole** [comment]
And similar errors also from the proxys on the aggregator e.g. for the TF one:
```
[3465790:aggregator-proxy-barrel_tf]: [13:27:59][ERROR] Expected Lifetime::Timeframe data GLO/UNBINNEDRES/0 was not created for timeslice 198 and might result in dropped timeframes
```
And also for the sporadic one:
```
[3465629:aggregator-proxy-barrel_sp]: [13:27:58][ERROR] Expected Lifetime::Timeframe data FLP/DISTSUBTIMEFRAME/52443 was not created for timeslice 199 and might result in dropped timeframes
[3465629:aggregator-proxy-barrel_sp]: [13:28:03][ERROR] Expected Lifetime::Timeframe data FLP/DISTSUBTIMEFRAME/52443 was not created for timeslice 200 and might result in dropped timeframes
```
@ktf

**Comment by ktf** [comment]
Issue understood. Some of the data is created automatically and fools the detection logic. Fixing.

**Pull request merged**
