### PR TITLE
Implementing workflow for extraction of a track based gain map

### PR DESCRIPTION
**Pull request by matthias-kleiner**
Example: Extraction of a pad-by-pad gainmap using simulated 400 PbPb events
[Reference gainmap](https://github.com/AliceO2Group/AliceO2/files/7676383/Reference_GainMap.pdf)
[Extracted gainmap](https://github.com/AliceO2Group/AliceO2/files/7676384/Extracted.pdf)

other changes:
- adding draw functionality for CalibPadGainTracks class + some optimizations of the class
- adding number of entries to FastHisto class
- removing unneded macro
- Painter: fixing draw function in case gPad is nullptr
- IDCDrawHelper: configurable z axis

### CODE REVIEW

**Review by shahor02 — APPROVED** [review]
shall I merge this?

**Review by wiechula — APPROVED** [review]
@shahor02 , from my side this can be merged.

**Comment by matthias-kleiner** [comment]
@shahor02 @wiechula can this PR then be merged?

**Comment by shahor02** [comment]
failure unrelated, merging.

**Pull request merged**
