### PR TITLE
Store TObjects within a TFile in the CCDB (QC-127)

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
The latest version of this PR is able to handle the two types of objects we store in the CCDB (as TFile and as a streamed object). It means that we will be backward compatible.

**Comment by Barthelemy** [comment]
This is ready to be merged. There are new methods to store and retrieve TObjects to and from a TFile in the CCDB. I added the tests for it. It should have no impact on the existing code as it is just extra methods.

**Comment by Barthelemy** [comment]
@ktf I think that there is something very wrong, but probably with the CI ? Or did I really screw up my rebase ?

**Comment by ktf** [comment]
There are a few errors, albeit I guess they are unrelated?

```
	101 - /Detectors/TPC/monitor/macro/RunFindAdcError.C (Failed)
	102 - /Detectors/TPC/monitor/macro/RunFindAdcError.C_compiled (Failed)
```

**Comment by Barthelemy** [comment]
I see the following in the logs : 
```
The following tests FAILED:
	292 - test_Framework_benchmark_ContextRegistry (Failed)
	293 - test_Framework_benchmark_DataDescriptorMatcher (Failed)
	294 - test_Framework_benchmark_DataRelayer (Failed)
	295 - test_Framework_benchmark_DeviceMetricsInfo (Failed)
	296 - test_Framework_benchmark_InputRecord (Failed)
	297 - test_Framework_benchmark_TableBuilder (Failed)
	298 - test_Framework_test_ASoA (Failed)
	299 - test_Framework_test_AnalysisTask (Failed)
	300 - test_Framework_test_BoostSerializedProcessing (Failed)
	301 - test_Framework_test_AlgorithmSpec (Failed)
	302 - test_Framework_test_BoostOptionsRetriever (Failed)
	303 - test_Framework_test_CallbackRegistry (Failed)
	304 - test_Framework_test_CallbackService (Failed)
	305 - test_Framework_test_ChannelSpecHelpers (Failed)
	306 - test_Framework_test_ContextRegistry (Failed)
	307 - test_Framework_test_ConfigParamRegistry (Failed)
	308 - test_Framework_test_CustomGUISokol (Failed)
	309 - test_Framework_test_CustomGUIGL (Failed)
	310 - test_Framework_test_CompletionPolicy (Failed)
	311 - test_Framework_test_DanglingInputs (Failed)
	312 - test_Framework_test_DanglingOutputs (Failed)
	313 - test_Framework_test_DataAllocator (Failed)
	314 - test_Framework_test_DataDescriptorMatcher (Failed)
	315 - test_Framework_test_DataProcessorSpec (Failed)
	316 - test_Framework_test_DataRefUtils (Failed)
	317 - test_Framework_test_DataRelayer (Failed)
	318 - test_Framework_test_DataSampling (Failed)
	319 - test_Framework_test_DataSamplingCondition (Failed)
	320 - test_Framework_test_DataSamplingPolicy (Failed)
	321 - test_Framework_test_DeviceMetricsInfo (Failed)
	322 - test_Framework_test_DeviceSpec (Failed)
	323 - test_Framework_test_ExternalFairMQDeviceProxy (Failed)
	324 - test_Framework_test_FairMQResizableBuffer (Failed)
	325 - test_Framework_test_Forwarding (Failed)
	326 - test_Framework_test_FrameworkDataFlowToDDS (Failed)
	327 - test_Framework_test_FairMQOptionsRetriever (Failed)
	328 - test_Framework_test_GUITests (Failed)
	329 - test_Framework_test_Graphviz (Failed)
	330 - test_Framework_test_InfoLogger (Failed)
	331 - test_Framework_test_InputRecord (Failed)
	332 - test_Framework_test_Kernels (Failed)
	333 - test_Framework_test_LogParsingHelpers (Failed)
	334 - test_Framework_test_ParallelProducer (Failed)
	335 - test_Framework_test_PtrHelpers (Failed)
	336 - test_Framework_test_Root2ArrowTable (Failed)
	337 - test_Framework_test_Services (Failed)
	338 - test_Framework_test_SimpleRDataFrameProcessing (Failed)
	339 - test_Framework_test_SimpleStatefulProcessing01 (Failed)
	340 - test_Framework_test_SimpleStringProcessing (Failed)
	341 - test_Framework_test_SingleDataSource (Failed)
	342 - test_Framework_test_SimpleTimer (Failed)
	343 - test_Framework_test_SuppressionGenerator (Failed)
	344 - test_Framework_test_TimesliceIndex (Failed)
	345 - test_Framework_test_TMessageSerializer (Failed)
	346 - test_Framework_test_TableBuilder (Failed)
	347 - test_Framework_test_TimeParallelPipelining (Failed)
	348 - test_Framework_test_TypeTraits (Failed)
	349 - test_Framework_test_Variants (Failed)
	350 - test_Framework_test_WorkflowHelpers (Failed)
	351 - test_Framework_test_WorkflowSerialization (Failed)
	352 - test_Framework_test_DeviceSpecHelpers (Failed)
	353 - test_Framework_test_ParallelPipeline (Failed)
	354 - test_Framework_test_ProcessorOptions (Failed)
	358 - test_FrameworkFoundation_test_Traits (Failed)
```

**Comment by ktf** [comment]
Fallout from #2066 . #2068 should fix it.

**Comment by ktf** [comment]
If you squash and force push we see if that is the problem...

**Comment by ktf** [comment]
For the record, all tests were failing because the wrapper script expected the separate log to be created and failed silently if not found.

**Comment by Barthelemy** [comment]
squashed. Waiting for the tests and an approved review.

**Comment by Barthelemy** [comment]
The failing tests are not related. I am merging as it does not affect anything else.

**Pull request merged**
