### PR TITLE
DPL Util: RootTreeReader extension to support unserialized output

### PR DESCRIPTION
**Pull request by matthiasrichter**
Branch configuration now allows specification of a type as template parameter
of the helper struct BranchDefinition. The type is used to deduce the optimal
serialization method. By default (without type), all objects are paublished
ROOT serialized. Messagable types with ROOT dictionary can now by published
unserialized when the type is provided in the reader configuration.

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@shahor02 this is the necessary extension to support unserialized publishing of messageable types by the RootTreeReader, can you have a look if all your workflows and tests are working with this PR

Do we have a standard testbench for the reconstruction? Some workflow which reconstructs simulated data and uses MC to calculate efficiency and other performance metrics.

**Comment by matthiasrichter** [comment]
@ktf, @MichaelLettrich the CI seems to be broken, there is no logfile after failing, could you check.

**Comment by MichaelLettrich** [comment]
@matthiasrichter currently a large fraction of CERN IT services are in a degraded or even offline state. We will check that things run smoothly again once IT resolves their problems.

https://cern.service-now.com/service-portal/ssb.do

**Comment by ktf** [comment]
CERN cloud is (almost) down: https://cern.service-now.com/service-portal/ssb.do

**Comment by shahor02** [comment]
Hi @matthiasrichter 

Unfortunately, still fails, see this: https://github.com/AliceO2Group/AliceO2/pull/2985

Regarding your question (I assume it is not related to this problem, in my PR I put the lines to reproduce the problem I steel see), we don't have a real general performance benchmark yet.

There is a O2/Detectors/ITSMFT/ITS/macros/test/run_workflows.sh
which, it the checks are uncommented, produces some performance plots, but on a rather basic level.

**Comment by matthiasrichter** [comment]
Hi @shahor02 , sorry I was not clear. I wanted to know if the workflows in their current state are working to make sure that the update does not destroy anything.

The extension allows to specify the data type of the objects to be published. Without the data type the reader can only publish ROOT serialized. The relevant PR for the TPC reco workflow is #2991

**Comment by shahor02** [comment]
@matthiasrichter OK, I see. Yes, with this PR the TPC reconstruction was working fine until I changed ``inputs.get<vector..>`` by ``inputs.get<span..>`` as in the https://github.com/AliceO2Group/AliceO2/pull/2985

**Pull request merged**
