### PR TITLE
Fix wrong uniform_int_distribution usage

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@chiarazampolli @shahor02 any objections to this?

**Comment by chiarazampolli** [comment]
Fine with me, @TimoWilken also had tried, and in his PR there was a suggestion by @shahor02 : https://github.com/AliceO2Group/AliceO2/pull/11119#issuecomment-1497540895

**Comment by ktf** [comment]
I think the comment of @shahor02 is actually accounted in my PR. I do not change the type of the class, which I agree would be dangerous, but I simply eliminate the dependency of the distribution on the actual storage type. If you need chars between (e.g.) 10 and 20, you do not care if the distribution is actually done using long long, and then downcasted or with the actual type. As long as the boundaries are compatible with the type T, you are fine.

**Comment by ktf** [comment]
Do we have any way to validate this change?

**Comment by ktf** [comment]
@chiarazampolli @shahor02 shall I merge this and then we think about possible issues?

**Comment by shahor02** [comment]
Fine for me.

**Pull request merged**
