### PR TITLE
Initial version of the simple data flow setup

### PR DESCRIPTION
**Pull request by matthiasrichter**
This corresponds to the simple setup for propagation of timeframe data described in
https://indico.cern.ch/event/493568/contributions/2014460/attachments/1223790/1790477/2016-02-05_mrichter_aliceo2-onlineformat.pdf

### CODE REVIEW

**Comment by ktf** [comment]
I would further squash the commits:

```
LHCClock and TimeStamp:
- Added definition od TimeStamp and LHCClock classes (squashed)
- Defining type enums for the selection of clock precision

HeartbeatFrame:

- Initial version of the heartbeat frame layout
- Adding HeartbeatFrame to compilation and register header file for installation

HeartbeatSampler:
- Adding module Utilities/DataFlow to compilation
- Adding module Utilities/DataFlow and sketch of HeartbeatSampler device
- Implementation of HeartbeatSampler

SubFramebuilder:
- Implementing a mockup of the SubframeBuilder
- Added a common bucket for the implementation of devices
- Adding the --self-triggered flag to command line of subframeBuilder

DataPublisher:
- Adding module Utilities/Publishers with DataPublisherDevice as first device
- adding module Utilities/Publishers to compilation
- Implemented all functions in the DataPublisher for basic setup

General
- Adding simple start script and configuration for the basic setup
```

**Comment by matthiasrichter** [comment]
yes, could squash it more. In general I prefer not to mix different modules, e.g. the definition of a common bucket in O2Dependencies has nothing to do with a particular code change, and commits to the data format headers should be separated from device implementations. Also I usually don't mix the actual code with the scripts and configurations for running. Mixing all this together makes things more difficult to track. At least for me. So a full squash like you suggested does not fit my habit. Unless there is a strong reason I would not spend more time on this now. The 'squash level' in this PR is already quite high compared to other PRs.

**Comment by ktf** [comment]
Fair enough. My personal preference is that each commit should impersonate
a somewhat complete added feature or a bug fix. A "deployable unit" if you
want. No real point, IMHO, to show how the development happened. Anyways,
as you say it's a matter of taste.

That said, on a slightly unrelated matter, in the future, once we start
having more unit tests, we should have some policy that each commit should
pass unit tests, so that we can easily do bisection.

**Comment by MohammadAlTurany** [comment]
Hi @matthiasrichter 

I am getting the the following errors when I compile this branch:
```
Scanning dependencies of target epnReceiver
/AliceO2/Utilities/Publishers/src/DataPublisherDevice.cxx:31:22: error: no matching conversion for functional-style
      cast from 'const value_type *' (aka 'const char *') to 'AliceO2::Header::DataDescription'
  mDataDescription = AliceO2::Header::DataDescription(fConfig->GetValue<std::string>(OptionKeyDataDescription).c_str());

```
and: 
```
/AliceO2/Utilities/Publishers/src/DataPublisherDevice.cxx:32:17: error: no matching conversion for functional-style
      cast from 'const value_type *' (aka 'const char *') to 'AliceO2::Header::DataOrigin' (aka 'Descriptor<gSizeDataOriginString,
      AliceO2::Header::printDataOrigin>')
  mDataOrigin = AliceO2::Header::DataOrigin(fConfig->GetValue<std::string>(OptionKeyDataOrigin).c_str());
```
Do I miss anything?

**Comment by matthiasrichter** [comment]
let me have a closer look ...

**Comment by matthiasrichter** [comment]
It's related to #242 and #240. The descriptors need to be fixed at compile time, but the DataPublisher device wants to have this configurable at runtime. I have set it to a fixed string in an additional commit as the first working version.

Interestingly enough, gcc 5.4 does not spot this problem, probably by silently ignoring the constexpr qualifier, but this sounds strange.

@MohammadAlTurany can you please check again. Please revert back to the status before pulling in these changes, I have corrected spelling in one of the commits and thus changed the commit history.

@mkrzewic we have to think about the descriptors again and soon come up with some possibility to use runtime strings in a controlled manner, and a registry for uniqueness.

**Comment by MohammadAlTurany** [comment]
@matthiasrichter It compiles now. Thanks.

**Comment by sawenzel** [comment]
The jenkins job fails because rootcint does not find `Pythia.h`.  Is there something wrong the cmake setup?

**Comment by kouzinopoulos** [comment]
The fail is probably related to https://github.com/AliceO2Group/AliceO2/issues/246

**Comment by sawenzel** [comment]
@kouzinopoulos : Thanks for pointing this out.

**Pull request merged**
