### PR TITLE
DPL: status of the variables is now time sampled.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@knopers8 can you run you tests and produce a new table with this? Thanks.

**Comment by ktf** [comment]
@knopers8 @Barthelemy Updated version. This removes completely Monitoring from my profile reports.
@awegrzyn Part of my problem is that if the monitoring buffer is full, you still send the metrics. Would it be possible to have a kind of aggregated metric where only the last metric sent for a given label is kept, so that I do not needlessly fill the buffer (and trigger the associated flush)?

**Comment by knopers8** [comment]
It seems that this time the usleep does not have any influence on the message rate. And there is very a nice improvement in general!

payload size | nb prod. | Messages/s (d4d60700 no usleep) | Std. Dev. | Messages/s (d4d60700 with usleep) | Std. Dev. | Messages/s (ef891b42 no usleep) | Std. Dev. | Messages/s (ef891b42 with usleep) | Std. Dev.
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
256 | 1 | 15420 | 100 | 6115 | 64 | 15658 | 127 | 15434 | 87
256 | 2 | 29714 | 903 | 5983 | 110 | 30822 | 273 | 30848 | 332
256 | 4 | 27028 | 407 | 5590 | 116 | 43382 | 5002 | 47058 | 4105
256 | 8 | 25002 | 681 | 4767 | 46 | 52476 | 15704 | 65652 | 10935
256 | 16 | 22022 | 287 | 3662 | 68 | 65631 | 1628 | 67340 | 1567
256 | 32 | 18747 | 451 | 2459 | 28 | 57608 | 1898 | 55600 | 1492

**Comment by ktf** [comment]
Could you provide the 2MB number?

**Comment by awegrzyn** [comment]
> @awegrzyn Part of my problem is that if the monitoring buffer is full, you still send the metrics. Would it be possible to have a kind of aggregated metric where only the last metric sent for a given label is kept, so that I do not needlessly fill the buffer (and trigger the associated flush)?

Yup, it's possible to implement it. I'll put it on my list (OMON-201).

**Comment by knopers8** [comment]
payload size | nb prod. | Messages/s (d4d60700 with usleep) | Std. Dev. | Messages/s (ef891b42 with usleep) | Std. Dev.
-- | -- | -- | -- | -- | --
2097152 | 1 | 1157 | 84 | 1097 | 148
2097152 | 2 | 865 | 66 | 805 | 39
2097152 | 4 | 798 | 46 | 808 | 85
2097152 | 8 | 832 | 111 | 739 | 58
2097152 | 16 | 738 | 84 | 751 | 85
2097152 | 32 | 538 | 69 | 487 | 49

**Pull request merged**
