### PR TITLE
DPL: cleanup struct to tuple

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo @aalkin as discussed. Having support for 99 elements rather than 40 does not seem to have any noticeable slowdown.

**Comment by ktf** [comment]
Of course this does not mean that actually parsing 99 is not slower than parsing 40. Merely that if the concern is allowing for more configurables, we can do that without a global impact.

**Comment by ktf** [comment]
Tested also on hyperloop, works.

**Comment by jgrosseo** [comment]
@ktf Thanks! Have you tried how long it takes to compile something with 99 elements?

**Comment by jgrosseo** [comment]
Any thoughts about making this also consuming structs?

**Pull request merged**
