### PR TITLE
Allow for TEfficiency merging

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by njacazio** [comment]
@chiarazampolli

**Comment by njacazio** [comment]
@knopers8

**Comment by chiarazampolli** [comment]
Hi @njacazio , 
Thanks!
I was about to open the same PR, was busy writing the mail about this to the concerned people :-) 
Why is this a Draft? This is how it should be done, unless @Barthelemy  has anything against it. 
Since @knopers8  is away, I would ask @Barthelemy to approve, if he agrees. 
Chiara

**Comment by njacazio** [comment]
Hi @chiarazampolli it was a quick fix and i couldn't resit, aplogies ;)
I move this in ready for review so that we can go forth!

**Comment by Barthelemy** [comment]
if it is not super urgent, I will let @knopers8 review as he wrote this part.

**Comment by chiarazampolli** [comment]
Hi @Barthelemy , 

It would be better to have it merged asap actually, considering that Piotr is away till Monday. So that it is taken in the nightlies, and we have the output from simulation. 
The change is quite trivial, we just add to use also TEfficiency to merge. This object contains practically 2 histograms (see https://root.cern.ch/doc/master/classTEfficiency.html), it should be no problem for the framework.

Chiara

**Comment by Barthelemy** [comment]
ok !

**Review by Barthelemy — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Thanks because we need it also for the vertexing QC, which we want to try during the pilot beam... 
Chiara

**Comment by chiarazampolli** [comment]
Hello @davidrohr , @shahor02 , @Barthelemy , @ktf , 

Is o2-cs8 broken? Once again, the error does not seem related to this PR. Can it be merged?

Chiara

**Comment by chiarazampolli** [comment]
Super thanks!!

**Comment by ktf** [comment]
For the record the issue seem to be fixed by https://github.com/alisw/alidist/pull/3462 but I am waiting for the next FLP suite to be released before we merge, as it triggers a large rebuild.

**Review by knopers8 — COMMENTED** [review]
Thanks!

**Pull request merged**
