### PR TITLE
DPL: actually support new versions of FairMQ

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by sawenzel** [comment]
I think it would make sense to actually bump o2-dev-fairroot first to have a non-trivial CI for this PR.

**Comment by sawenzel** [comment]
See here https://github.com/alisw/alidist/pull/1282.

**Comment by ktf** [comment]
Looks like we have some other problem with the new FairMQ. :-/

**Comment by ktf** [comment]
I checked and the Framework works with it, however it looks like `O2SimDeviceRunner.cxx` has a similar problem.

**Comment by sawenzel** [comment]
yes I know

**Pull request merged**
