### PR TITLE
[MRRTF-89] First version of Electronic Mapping for MCH

### PR DESCRIPTION
**Pull request by aphecetche**
The _detector mapping_, which already exists in AliceO2 (in MUON/MCH/Mapping) deals with the relationship between a tuple (detection element id, dual sampa id, dual sampa channel) and the corresponding pad (location, size) on the detector's cathodes.

This PR introduces a different mapping : the _electronic mapping_. This other mapping connects the first two elements of the preceding tuple (detection element id, dual sampa id), used by the first stages of the reconstruction code, to a new tuple (solar id, group id, index) (*). That new tuple also references a single dual sampa chip, but using elements that are directly composing the MCH raw data.
 
The core of the electronic mapping's code is _generated_ from a master table (google sheet) that is built and used at Pt2 during the commissioning of the detector.

Note that some conversion routines in this PR are still a bit WIP (in particular the CruLinkId) as the installation is still ongoing at Pt2 so we don't yet have all the information at hand.

(*) in a nutshell, a Solar card is basically one GBT, a group denotes a flex cable that connects at most 5 dual sampas on the detector itself, and index is the dual sampa index within the group.

### CODE REVIEW

**Comment by aphecetche** [comment]
@ktf is there a way to locally lint python the same way as Codacy does ? (I don't really want to use the CI just for linting...)

**Comment by ktf** [comment]
I think they simply use `pylint`. The code they run is:

https://github.com/codacy/codacy-pylint-python3/blob/master/src/codacy_pylint.py

**Comment by aphecetche** [comment]
@ktf I've fixed most of the Codacy warnings, but the remaining one I'm not so sure what to do about it. Would be tempted to just ignore it : any advice ?

**Comment by ktf** [comment]
I think I managed to ignore the issues. I am merging this.

**Pull request merged**
