### PR TITLE
ITS tracking: Improve logging in case of OOM

### PR DESCRIPTION
**Pull request by mconcas**

### CODE REVIEW

**Comment by alcaliva** [comment]
Hi @mconcas , is this needed for async 2024 pp apass1? I get conflicts when I try to port it to the tag

**Comment by mconcas** [comment]
Hi @alcaliva, for pp this is not super important, it would be nice to have, but if it creates issues I can drop it.

**Comment by chiarazampolli** [comment]
Ciao Matteo, 

Apass1 was already done, only PRs for anchored MCs should be cherry-picked for the simulations anchored to the pass. I guess this is not needed there.

Chiara

**Comment by mconcas** [comment]
> Ciao Matteo,
> 
> Apass1 was already done, only PRs for anchored MCs should be cherry-picked for the simulations anchored to the pass. I guess this is not needed there.
> 
> Chiara

ok, I removed the label.

**Pull request merged**
