### PR TITLE
[EMCAL-911] Several fixes in the RecoContainer

### PR DESCRIPTION
**Pull request by mfasDa**
- Add interaction record to the EventContainer
- Fix sorting of cell / LEDMON container
- Documentation of RecoContainerReader
- Add tests for
  - Sorting of event container
  - Reco container reader

### CODE REVIEW

**Comment by mfasDa** [comment]
All unit tests passing, the container should now have full test coverage.

**Comment by mfasDa** [comment]
CI errors unrelated

**Comment by mfasDa** [comment]
CI errors still unrelated ...

**Comment by shahor02** [comment]
run fullCI locally, merging

**Pull request merged**
