### PR TITLE
DPL: print error when getting an EndOfStream together with data

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
Not sure this is fully correct. What if we receive the sih first and then the dh?
I would store whether we received an sih at all, and then handle it below after the loop over msgidx.
If (sih && dataheader)
  [Print the Error]
Else if sih
  Return // Since this is EoS so we do not inject, and there is also no data.

**Comment by ktf** [comment]
I though about it... however, is the injection function the correct place where to spot this kind of issues?

**Comment by davidrohr** [comment]
Well, we can certainly find a better place, but it also does not hurt here.

In any case we need the check for only sih here, and in that case return without printing an error about no data header.

**Comment by davidrohr** [comment]
I merged https://github.com/AliceO2Group/AliceO2/pull/11966#event-10483466720, which should supersede this

**Pull request closed without merging**
