### PR TITLE
Use a per workflow startTime...

### PR DESCRIPTION
**Pull request by ktf**
This is a clear violation of our DataModel, however I do not see how
we can do it without copying and rewriting all the headers passed
by DD to DPL.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr as discussed, even if it works (not tested), this is far from a proper solution.

**Comment by davidrohr** [comment]
Thx, will verify whether it works before the meeting. Then we can discuss what way to go with a bit more certainty.

**Comment by davidrohr** [comment]
ok, this fixes the scheduling in the full system test (as expected). Now, we still need to implement it properly.

**Comment by ironMann** [comment]
@davidrohr Can you maintain one dev branch for GPU/FST with all temporary workarounds such as this one, which we could use and build RPMs out of for testing?

**Comment by davidrohr** [comment]
@ironMann @ktf : There is actually only this workaround. I would prefer if we could get it cleaned up and merged into dev.
@ktf said the should have this fixed up by end of last week. Do you know when you will be ready?

If we have a separate branch, I'll have to keep it up to data, and it should usually equal the dev branch anyway.
I can create such a branch, and we can use it temporarily for such things if needed. But then I'd say we still use dev for GPU/FST by default, and only if needed we switch to the special branch.

**Comment by ktf** [comment]
@davidrohr @shahor02  Is:

Detectors/TPC/spacecharge/test/testO2TPCPoissonSolver.cxx

supposed to run for 300s?

**Comment by davidrohr** [comment]
@matthias-kleiner : Could you comment on what is the normal runtime of this test? Could it be that there is a spread in the runtime? Could of course also be that this was just some other random problem during the CI run.

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner : Could you comment on what is the normal runtime of this test? Could it be that there is a spread in the runtime? Could of course also be that this was just some other random problem during the CI run.

Hi @davidrohr , I dont think it is supposed to run for 300s. I just tested it on my local computer and the time was around ~15s. And there also shouldnt be some spread in the runtime. For me it looks like its some random problem...

**Comment by ktf** [comment]
@TimoWilken could you check what is going on with the fullCI test?

**Comment by TimoWilken** [comment]
@ktf still building; it had to rebuild GCC and everything depending on it because of [a fix](https://github.com/alisw/alidist/commit/0868a8085a9a06daf1bf5e9bfa1579d0321a404d) to the recipe yesterday. It's currently at 2960/3278 of the O2 build.

**Comment by ktf** [comment]
Errors unrelated. Merging.

**Pull request merged**
