### PR TITLE
TOF: add hit info in DM

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by njacazio** [comment]
@noferini in reference to https://github.com/AliceO2Group/AliceO2/pull/13432

**Comment by noferini** [comment]
Hi @njacazio ,
I have two comments
1) column TOFHitCount: this is not a count of hits, it is more matter of patterns. I would rename in something like TOFClusPattern
2) you start to count from "1" (single hit case). If would start from 0 so that
 if(TOFClusPattern){ ... } 
 is executed only for multiple-hits cases

**Comment by njacazio** [comment]
Hi @noferini sounds good, I changed it

**Comment by jgrosseo** [comment]
Are we encoding the number of hits in the chi2 somehow now?
This we should probably discuss in the WP4/14. I am tagging also @ddobrigk

**Comment by njacazio** [comment]
indeed we use the non used float range to encode the cluster shape in order to avoid adding new columns, this is transparent for older data

**Comment by jgrosseo** [comment]
I wonder if it is really transparent because someone may simply call `TOFChi2`. It is correct that this was done for TrackTimeRes but here we even defined a TrackType to make sure what is in the data format. Anyway, best is to have a discussion at one of the meetings... Can we draft this for now?

**Comment by njacazio** [comment]
Closing, to be discussed

**Pull request closed without merging**
