### PR TITLE
Improve test coverage for DataHeader.cxx

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Please do not merge yet. This is to try the code coverage integration.

**Comment by ktf** [comment]
@matthiasrichter @mkrzewic: I was about to merge this, but then my question is: are we sure that having such a constructor is a good idea? It gives the false impression that a valid header could just have a DataOrigin, which I think is not what we want. Thoughts?

**Comment by mkrzewic** [comment]
@ktf I think we possibly don't want the DataHeader to be default constructible to avoid having a header with just invalid values - otherwise I like the assignment API. Not sure though, maybe it does make sense to keep the default ctor...

**Comment by ktf** [comment]
I gave a better look at the API. Isn't the semantic of `operator=` supposed to be "replace left side *completely* by what is there on the right side"? I.e. in case you have a complex number, e.g.:

```C++
Complex a{Real{1},Imaginary{1}};
Complex a = Real{1};
```

 you would expect:

```C++
assert(a.real == 1 && a.imaginary == 0);
``` 

while, unless I miss something trivial, following the same logic of your `operator=` would give `{1,1}`, which I think is confusing. Do you really expect that behaviour? Wouldn't explicit setters be better?

**Comment by ktf** [comment]
Actually, shouldn't we limit modification of the `DataHeader` only at construction time? Why do you need such a mutable behaviour?

**Comment by mkrzewic** [comment]
@ktf modification must be allowed at runtime for things like specification, payload size etc, so in general it is a dynamic structure. Some things could be set at compile time like maybe the DataDescription, but I don't know of a way to limit initialisation to compile time only (in a nice and readable way); which is not needed here I think. 
As for the assignment I don't see an issue: you assign values to fields, this is less verbose than using setters. Also, in general I find that using overloads and the type system to do this kind of dispatch is more flexible than using named stuff; the compiler can decide which setter to use in a more generic way e.g. in derived classes or using SFINAE. This of course does not stop us from defining other modifiers if needed.

**Comment by ktf** [comment]
The problem is not the way it works, but the fact that it changes the expectations for `operator=`. 

Why overloading `=` with a different semantic meaning, rather than add an extra "update(const T&)" or "set(const T&)" method? E.g.

```C++
dh.update(DataOrigin{"TPC"});
```

**Comment by mkrzewic** [comment]
one way would be to template the header on the compile time only fields (which would be private), but that would proliferate types and for reading the struct back we would have to have yet  another specialisation with some sentinel (type or value). Not very nice and overly complicated, but I guess it can be done :)

**Comment by mkrzewic** [comment]
about operator=() I know what you mean, I just like taking polymorphism to the limit :) I really see no issue with it, it reads fine to me. @matthiasrichter what so you think?

**Comment by matthiasrichter** [comment]
Sorry, I have not noticed the discussion until know (to many notifications from Github). I originally though, this PR was a test case for the codecov setup.

These operators are there for convenience, namely not to think about the name of the member to do an assignment to. I also liked doing this, however I understand that this probably not a good practice. The rhs term is simply not complete to do an assignment. So it is more correct to use an `update` or `set` method.

With #785 this probably becomes obsolete.

**Pull request closed without merging**
