### PR TITLE
adding FIT info to TOF matching for calib (if FIT is present)

### PR DESCRIPTION
**Pull request by noferini**
Adding fit option to tof matching workflow in O2 both for sync and async (since removed in O2DPG, https://github.com/AliceO2Group/O2DPG/pull/1422)

### CODE REVIEW

**Review by shahor02 — DISMISSED** [review]

**Comment by noferini** [comment]
fullCI failing, but I didn't find any message related to this PR. 
If I didn't overlook anything... can we merge this?

**Comment by shahor02** [comment]
@noferini it fails due to the timeout (likely ccdb / xrootd related).  Since it modifies dpl-workflow, would be good to test the FST. 
Could you run locally 
```
export NHBPERTF=128
export SHMSIZE=8000000000
export NJOBS=5 # //you N of CPUs
WORKFLOW_EXTRA_PROCESSING_STEPS=TPC_DEDX,MFT_RECO,MID_RECO,MCH_RECO,MATCH_MFTMCH,MATCH_MCHMID,MUON_SYNC_RECO,ZDC_RECO FST_SYNC_EXTRA_WORKFLOW_PARAMETERS=QC,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR QC_REDIRECT_MERGER_TO_LOCALHOST=1 GEN_TOPO_WORKDIR=`pwd` ALICE_O2SIM_DUMPLOG=1 NEvents=5 NEventsQED=100 O2SIMSEED=12345 $O2_ROOT/prodtests/full_system_test.sh
```

@costing @TimoWilken changing the xrood settings to https://github.com/alisw/alidist/blob/a2e00153b3e500bf9c4e2f6df1dc9dd3dc4618b0/o2-full-system-test.sh#L28-L30 did not help, the fetching is still extremely slow:
```
[208279:internal-dpl-ccdb-backend]: [02:05:00][INFO] Processing timeslice:0, tfCounter:0, firstTForbit:0, runNumber:310000, creation:1550600800000, action:0
[208279:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Opening connection to JCentral. Please wait
[208279:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Opening connection to 128.142.249.53
[208279:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Successfully connected to 128.142.249.53
[208279:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/CTP/Calib/OrbitReset/01/35179/b07c53e0-b4c0-11ec-b66d-90ce809b250c in SE <ALICE::CERN::EOS>
[208279:internal-dpl-ccdb-backend]: [02:06:22][INFO] ccdb reads http://alice-ccdb.cern.ch/CTP/Calib/OrbitReset/1550600800000/b07c53e0-b4c0-11ec-b66d-90ce809b250c for 1550600800000 (load to memory, agent_id: alientest01-1706493899-dHRhF5), 
...
[208279:internal-dpl-ccdb-backend]: [02:34:16][INFO] ccdb reads http://alice-ccdb.cern.ch/TRD/Calib/CTFDictionaryTree/1546300800000/b277557d-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alientest01-1706493899-dHRhF5), 
[208279:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/ZDC/Calib/CTFDictionaryTree/01/48254/dec218fb-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
//Killed by timeout
```

**Comment by noferini** [comment]
> @noferini it fails due to the timeout (likely ccdb / xrootd related). Since it modifies dpl-workflow, would be good to test the FST. Could you run locally
> 
> ```
> export NHBPERTF=128
> export SHMSIZE=8000000000
> export NJOBS=5 # //you N of CPUs
> WORKFLOW_EXTRA_PROCESSING_STEPS=TPC_DEDX,MFT_RECO,MID_RECO,MCH_RECO,MATCH_MFTMCH,MATCH_MCHMID,MUON_SYNC_RECO,ZDC_RECO FST_SYNC_EXTRA_WORKFLOW_PARAMETERS=QC,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR QC_REDIRECT_MERGER_TO_LOCALHOST=1 GEN_TOPO_WORKDIR=`pwd` ALICE_O2SIM_DUMPLOG=1 NEvents=5 NEventsQED=100 O2SIMSEED=12345 $O2_ROOT/prodtests/full_system_test.sh
> ```
> 
> @costing @TimoWilken changing the xrood settings to https://github.com/alisw/alidist/blob/a2e00153b3e500bf9c4e2f6df1dc9dd3dc4618b0/o2-full-system-test.sh#L28-L30 did not help, the fetching is still extremely slow:
> 
> ```
> [208279:internal-dpl-ccdb-backend]: [02:05:00][INFO] Processing timeslice:0, tfCounter:0, firstTForbit:0, runNumber:310000, creation:1550600800000, action:0
> [208279:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Opening connection to JCentral. Please wait
> [208279:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Opening connection to 128.142.249.53
> [208279:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Successfully connected to 128.142.249.53
> [208279:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/CTP/Calib/OrbitReset/01/35179/b07c53e0-b4c0-11ec-b66d-90ce809b250c in SE <ALICE::CERN::EOS>
> [208279:internal-dpl-ccdb-backend]: [02:06:22][INFO] ccdb reads http://alice-ccdb.cern.ch/CTP/Calib/OrbitReset/1550600800000/b07c53e0-b4c0-11ec-b66d-90ce809b250c for 1550600800000 (load to memory, agent_id: alientest01-1706493899-dHRhF5), 
> ...
> [208279:internal-dpl-ccdb-backend]: [02:34:16][INFO] ccdb reads http://alice-ccdb.cern.ch/TRD/Calib/CTFDictionaryTree/1546300800000/b277557d-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alientest01-1706493899-dHRhF5), 
> [208279:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/ZDC/Calib/CTFDictionaryTree/01/48254/dec218fb-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
> //Killed by timeout
> ```

Ok, I'll do

**Comment by noferini** [comment]
I failed to run in my laptop fst (it seems that I have not enough resources for gpu-reconstruction).
I resume the checks in the PR, hoping to get FullCI running. Let see.

**Comment by noferini** [comment]
all checks passed!

**Pull request merged**
