### PR TITLE
Debug data dump functionality

### PR DESCRIPTION
**Pull request by dak98**
This allows to output the contents of the data being sent inside the framework. It works on objects of different data types passed to the snapshot function. The --data-dump flag is provided as a toggle for the feature. A small demonstration for the code from DataDump.h can be seen here https://gist.github.com/dak98/4a7e3d410d965e1328e38d74d88387dd.

### CODE REVIEW

**Comment by jotwinow** [comment]
@ktf @jgrosseo we would appreciate your feedback on this PR

**Comment by pbuehler** [comment]
The code looks fine and seems to provide the intended functionality.

**Comment by jotwinow** [comment]
@pbuehler @ktf @jgrosseo thanks for review. Please let us know what do you plan with this piece of code.

**Comment by ktf** [comment]
First of all, thank you for you contribution. I confirm the functionality is correct, good job. However we should rework the integration a bit, as I do not like the idea of having a Singleton in DataAllocator (or in general). There are two possible ways IMHO: 

* One could percolate the `DataDumper` in the `DataAllocator` (possibly from the ProcessingContext). This still couples the DataDumper with the data allocator but at least we can guarantee we properly configure the instances upfront.
* One could move the whole functionality in a different `DataProcessorSpec` and subscribe to the things to be dumped explicitly. This as the advantage you could then easily scale the size of the input (e.g. using the DataSampling) or you could even create a GUI to inspect the data (some sort of DataDisplay, if you want). 

IMHO the latter approach has the nice advantage that it could become quite a nice project to allow users to inspect the data flow, even interactively, without touching the core functionality. The former approach is obviously easier to start with, but has several implications on the core functionality which might result in performance degradation (when active) and therefore in longer review time. Also, since you would be inspecting all the devices separately, this would remain a quick debug tool and I worry not a big project in the end.

I would prefer you go with the second approach, what do you think? If you agree, how would you start with it?

**Comment by jotwinow** [comment]
@ktf the second option sounds interesting and it would be a nice project to be implemented by @dak98. However, we need to discuss it in detail to come to you with ideas. BTW I am curious whether Gvozden et al. have similar tools to debug and check data consistency on the FLPs.

**Comment by ktf** [comment]
@jotwinow yes, we should discuss how to go forward. I know @Barthelemy has something which allows him to inspect data, so indeed it could be some integration of all these utilities into some sort of "Data Display" or "Data Inspector".

**Comment by Barthelemy** [comment]
Hello everyone, 

We had a DataDump tool earlier in QC. However the GUI was built with imGui and it made it useless as soon as we used some kind of X11 / ssh / container. Therefore it was abandoned. 

We had in mind to rebuild such a tool at some point but never got the time to. See https://alice.its.cern.ch/jira/browse/O2-773 . 
Requirements were
- Print the *raw* data (header and payload).
- Connect to any running process to spy the data it is spitting out. 

We thought of using the Data Sampling (Dispatcher) to forward data to a dangling port that could be used by a terminal application (a la EventDump). At the same time we considered having a web gui. It involved a far more complicated scheme with a "JSONator" that would connect to some dispatchers to collect the data. The "clients" should configure the Dispatcher dynamically to say what they want. I don't remember all the details unfortunately. Maybe @knopers8 does ? 

The main differences between this PR and the idea we outlined are 
1. In this PR anything that has a method "Dump()" or "Print()" can be dumped (correct?) vs dump raw data as a memory dump
2. Static connection of this feature (either with the flag or by having a separate device in the workflow) vs dynamic connection. 

I am convinced that the effort should be streamlined and that a common tool is possible. It is fortunate that we have a motivated person who started implementing it in a very nice way.

Calling people who  were involved with this in the past : @awegrzyn @graduta @vmcb @knopers8 

Possible way forward:
1. agree on requirements
2. agree on design (DS, device ? DPL feature ? )
3. agree on UI (just a dump from a device ? command line tool ? web ui? )
4. agree on who does what

**Comment by jotwinow** [comment]
@Barthelemy @ktf it all sounds good to me to have a common tool. We could address it with @dak98 et al. We should discus it asap. It is time to define engineering/master projects at the AGH :)

**Comment by jotwinow** [comment]
Dear all,
As discussed, we will implement the DataInspector as independent device. We move discussion to JIRA, 

https://alice.its.cern.ch/jira/browse/O2-773

**Pull request closed without merging**
