### PR TITLE
C++17 fixes

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
In principle this should work with C++14 as well, so the tests should pass (apart from the usual glitches, which I am trying to fix separately by the way). This is needed for alisw/alidist#1293, see also [O2-278](https://alice.its.cern.ch/jira/browse/O2-278).

**Comment by sawenzel** [comment]
Note that this PR will cause conflict with #1346. I would prefer waiting a bit until the later is merged.
Also, before pushing the C++17 stuff further, I think we need to have the CI green again.

**Comment by dberzano** [comment]
As said, the PR tests are being addressed in parallel. As for the C++17 fix (which appears not to work ATM) it depends on the ETA of #1346. If we're ready with a C++17 and 14 compliant fix, we'll merge this one first.

**Comment by sawenzel** [comment]
I plan to merge #1346 asap as it is urgently needed by other people.

**Comment by dberzano** [comment]
OK this is ready to be merged; it's equally easy to port changes both ways. I'll have this on hold for the day, no problem.

**Comment by dberzano** [comment]
In case of green tests, this needs to be merged ASAP.

**Comment by dberzano** [comment]
Errors are unrelated, merging.

**Pull request merged**
