### PR TITLE
Timeframe rate limit

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by jgrosseo** [comment]
That was fast :)

**Comment by ktf** [comment]
Unfortunately it does not improve the memory usage, at least not so far. I am back to thinking that the current rate limiting is actually doing the correct thing already...

**Comment by jgrosseo** [comment]
I think this fixes the use case of a slow task at the end. Did you try to the use case `CorrelationsFilteredOnTheFly`? I can set it up in `O2 Development` if you have the code on hyperloop.

**Comment by ktf** [comment]
I am not sure actually. What I saw (but maybe I did not not look too well) is that the number of in-fly dataframes was already low. I will look better this week. Anyways, we need it in any case also for the online, so I will make this ready to merge sometimes today.

**Comment by ktf** [comment]
@davidrohr this fixes the conflicts.

**Pull request merged**
