### PR TITLE
Correct ccdb output creation

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr in the end sorting services would have been too complicated, because the ordering really needs to happen on a callback basis, not on a service basis. It's better to have a separate callback which is guaranteed to be executed before any sending happens

**Comment by davidrohr** [comment]
ok, thx, will check

**Comment by ktf** [comment]
Actually, this is just a red herring, I think. I suspect the issue is that due to the fact the TFReader does not use DPL to send messages, pc.outputs().countDeviceOutputs(true) == 0 always.

**Comment by davidrohr** [comment]
> Actually, this is just a red herring, I think. I suspect the issue is that due to the fact the TFReader does not use DPL to send messages, pc.outputs().countDeviceOutputs(true) == 0 always.

Will the same happen in the input-proxy? I assume the input proxy also pulls in the CCDBSupport and has to send the CCDB message?

**Comment by ktf** [comment]
I am writing a fix for the TFReader. If my suspect is confirmed I will check the input proxy.

**Comment by ktf** [comment]
For the record, this is fine but not really needed. #12098 is enough to fix the issue.

**Pull request merged**
