### PR TITLE
PrimaryGenerator that can propagate mother/daughter indices

### PR DESCRIPTION
**Pull request by preghenella**
This PR allows mother and daughter indices from MC generators to be propagated up to the `PrimaryGenerator` and eventually can be propagated into the `Stack`.

### CODE REVIEW

**Comment by amorsch** [comment]
fStack->PushTrack(doTracking, mother1, pdgid, px, py, pz,
                    e, vx, vy, vz, tof, polx, poly, polz, proc, ntr,
                    weight, status, parent);
                    weight, status, mother1);
->
 fStack->PushTrack(doTracking, mother1, pdgid, px, py, pz,
                    e, vx, vy, vz, tof, polx, poly, polz, proc, ntr,
                    weight, status, parent);
                    weight, status, mother2);

**Comment by preghenella** [comment]
hi @amorsch ,

yes, this is what will have to be done.
I wanted to have this in incremental steps.
I will push a second commit with that change.

@sawenzel , please do not squash when merging. I'd like to keep the two commits separated.

**Comment by preghenella** [comment]
the `Check PR with clang-format / build (pull_request_target) ` fails
```
fatal: ambiguous argument '.github/workflows/code-formatting.yml': unknown revision or path not in the working tree.
1422
Use '--' to separate paths from revisions, like this:
``` 
which does not seem to be related to this PR

**Comment by preghenella** [comment]
@amorsch 
please check the second commit which passes the `secondparent` in the stack.
https://github.com/AliceO2Group/AliceO2/pull/4361/commits/9f00f662534f806665897a54f16ac4dacf210e99

**Comment by preghenella** [comment]
@sawenzel can this be merged?
I do not see where the problems in the checks are, look not related to the PR

**Pull request merged**
