### PR TITLE
adding HepMC tables

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Review by ktf — APPROVED** [review]

**Comment by jgrosseo** [comment]
@pzhristov Please check

**Comment by pzhristov** [comment]
@ktf @aalkin @jgrosseo Only one  question: should the comments start with ///<! to make Doxygen aware of the descriptions? This concerns all the columns/tables in the header file.

**Comment by jgrosseo** [comment]
We do not use Doxygen but a parsing developed by Paul which expects the comments exactly how they are.

**Comment by pzhristov** [comment]
Officially Doxygen is our O2 documentation tool, so this additional parser is a surprise for me.

**Comment by jgrosseo** [comment]
The tool by Paul was discussed many times in the WP14 and it is the only way to properly document the tables which Doxygen will not understand. It is producing this output nightly : https://aliceo2group.github.io/analysis-framework/docs/datamodel/ao2dTables.html
The tool is in O2 scripts/data-model. Feel free to have a look

**Pull request merged**
