### PR TITLE
Fix variant for std::vector string

### PR DESCRIPTION
**Pull request by ktf**
Fix variant for std::vector string

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo this fixes the reading of the table schema under Linux. It's indeed a rather serious bug in managing `std::vector<std::string>` parameters. I suspect no one was actually using them before, because it's basically broken.

@aalkin While I was at it, I simply used void* and removed the dependency on the storage_t. When you are around we should discuss further simplifications.

**Comment by vkucera** [comment]
@ktf @aalkin @jgrosseo Unfortunately, there is still a problem with mangled random default values of `Configurable<std::vector<std::string>>` members, which was first reported at least as early as on 26 January (https://mattermost.web.cern.ch/alice/pl/cg3dabkqpfb5388i47aapyjciw). This can be seen in the JSONs in `$O2PHYSICS_ROOT/share/dpl`, generated during compilation, as well as in the `dpl-config.json` dumped at run time. The strings saved as values of those configurables seem to be some random fragments of the command line and sometimes even contain non-Unicode characters, which breaks the JSON parsing, for example in `$O2PHYSICS_ROOT/share/dpl/o2-analysis-cf-twopartcorr-filter.json`:
```json
"defaultValue": "{\"values\":[\"rg{-3.0,3.0}-yes\",\"��f\\u0001\",\"rg{-3.0,5.0}-no\"]}",
```
You can see more (not all) examples with `grep -r "\\\u" $O2PHYSICS_ROOT/share/dpl`.

**Comment by vkucera** [comment]
@ktf @aalkin @jgrosseo Is there any update on this issue?

**Comment by ktf** [comment]
I am afraid not. Can you run valgrind on it?

**Pull request merged**
