### PR TITLE
Sanitize operator=

### PR DESCRIPTION
**Pull request by mkrzewic**
...to avoid racial jokes have assignment behave as expected, introduce a polymorphic set method to set members.

### CODE REVIEW

**Comment by mkrzewic** [comment]
@matthiasrichter only if you consider #764 trouble

**Comment by ktf** [comment]
Regarding the trouble, the fact that we didn't (and that they were not tested) is probably a good indication that we do not need them at all. After all, as an example, you'd never change data origin from TPC to ITS, no? These are only there to support the following coding pattern:

```C++
DataHeader dh;
dh.set(decideOrigin());
dh.set(decideDescription());
dh.set(decideSerialization);
```

but this could be written equally well, IMHO:

```C++
const auto origin = decideOrigin(),
const auto description = decideDescription(),
const auto serialization = decideSerialization()

const DataHeader dh{
  origin,
  description,
  serialization
};
```

or even simply:

```C++
const DataHeader dh{
  decideOrigin(),
  decideDescription(),
  decideSerialization()
};
```

**Comment by mkrzewic** [comment]
in case you send a lot of similar messages there is no reason to initialize the entire header all over again, one might want to only set e.g. the size which might be different each time.

**Comment by ktf** [comment]
Is that really an optimisation we need? This is 80 bytes we are talking about. Also, given you writeback to memory in cachelines (64 bytes) in any case, did you actually verify that changing one field is not as bad as changing the whole header? Ins't this a premature optimisation for something which we do not use anywhere in the code at the moment?

**Comment by mkrzewic** [comment]
it's not about performance here, it's about consistency. I'd rather not have to think about how small or large a struct is to decide how i'm allowed to initialize it (and why) - I think it is good practice to keep interfaces similar (e.g. in this case have setters).

**Comment by matthiasrichter** [comment]
some of the checks don't seem to run, could you have a look, @dberzano

**Comment by matthiasrichter** [comment]
It seems to open a box of questions. The usual one first: do we need setters at all if the members are not private and there is no functionality to hide? Probably not. The operators have been there for convenience. Simply changing them to setters makes them almost obsolete, because assignment directly to the member is possible. But then one needs to know the member variable name, which is hidden when using `set` with different data types.

Leaving this consideration aside I think, the setters are fine. As an example to change the data description I can imagine to set the header for the outgoing block from the incoming header, and then change data description and payload size.

I understand Giulios argument in the way that initializing the complete header using an appropriate constructor will increase readability of the code.

There is probably more to think:
- lets also add `setPayloadSize` if we want to provide setters consistently for all members, just `set` does maybe not work unambiguously in this case.
- `set(const DataIdentifier&)` can also be provided for the combination of .data description and origin
- do we need something including also the sub specification?
- another constructor allowing also to set the payload serialization type from a constructor parameter

**Comment by ktf** [comment]
First of all apologies for the extra emails from codecov. I am trying to follow up the issue with them (I did reduce the verbosity by asking to publish results only once, but apparently something makes the setting being ignore).

Regarding the discussion, which is probably better done in front of some a beer or a cup of tea, besides the comments raised by Matthias, I have a further one which is that having a mutable interface for the sake of optimising the creation of DataHeaders is potentially promoting bad coding practices as it introduces implicit state. To me, if this is really needed for performance reasons for creating any of the headers, maybe the heavy contents should be moved to be a payload and shipped as such. This would also allow for caching them on the receiver side, assuming some "validity" can be attached to it.

Anyways, I guess for the moment we can close this and merge the other one from Mikolay.

**Comment by mkrzewic** [comment]
Hi, while I have a slightly different view of coding practices named here I agree that this kind of discussion is indeed best left to more friendly surroundings. Since the use case I was aiming for is supported by the public nature of data members in question I've removed the setters, updated the examples (O2MessageMonitor) to use the safe ctor only approach and added test for the ctors and assignment.

**Comment by ktf** [comment]
Thank you for this. Appreciated. Would you mind squashing the commits?

**Comment by mkrzewic** [comment]
all sqashed

**Pull request merged**
