### PR TITLE
DPL: fix rates

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@awegrzyn @vascobarroso this should bring back the DPL dashboard. Is there a way I can check this?

**Comment by awegrzyn** [comment]
The easiest way is to just run FLP Suite CI. Otherwise I could just test it manually.

**Comment by ktf** [comment]
How do I run the FLP Suite CI?

**Comment by awegrzyn** [comment]
hmm, good questions, if you give me O2 tag or commit I'll do it...

**Comment by ktf** [comment]
50b108aed5969005808f33b7eab1413fae525188 is the commit. How difficult would that be to run the FLP suite CI on each PR?

**Comment by awegrzyn** [comment]
I don't think it's possible atm as we luck resources for that. We could think of something on-demand

**Comment by awegrzyn** [comment]
@ktf I managed to verify it now, it seems all's good

**Pull request merged**
