### PR TITLE
Move ConfigurableMacroHelper plugin service helper in CommonUtils

### PR DESCRIPTION
**Pull request by preghenella**
This PR moves the `ConfigurableMacroHelper` and contained functionalities to a scope that is more visible for common use, namely in `CommonUtils`

### CODE REVIEW

**Comment by preghenella** [comment]
This PR also adds a commit (please do not squash) that bring in the O2 simulation the concept of selective tracking with configurable behaviour.

An example is added to show the possible use of it

This is a simulation example showing how to run simulation and selectively
transport particles through the detector geometry according to configurable settings

The simulation uses Pythia8 pp generator with default settings.
The specific settings of the simulation are defined in the sim.ini file.

Only the parameters for the selective particle transport are adjusted, namely
```
[Stack]
transportPrimary=external
transportPrimaryFileName=transportPDG.macro
transportPrimaryFuncName=transportPDG(321)
transportPrimaryInvert=false
```

`transportPrimary` defines the mode of selection, `external` means that the definition is loaded from a plugin macro
defined by the function call `transportPrimaryFuncName` from the file `transportPrimaryFileName`.
`transportPrimaryInvert` allows one to invert the definition, hence to inhibit transport for the selected particles.

**Comment by preghenella** [comment]
not sure what fails in these build checks.
does not seem related to this PR

**Review by sawenzel — COMMENTED** [review]
Could you please rebase to dev? And link the new example in the main simulation .md documentation?

**Comment by preghenella** [comment]
hi @sawenzel 
things (rebase + link to example) should be in place.
Hopefully the PR will succeed

**Comment by sawenzel** [comment]
I think you need to annotate the function hook as transient. Otherwise there are dictionary errors:
```
Error in <TStreamerInfo::Build>: __function::__value_func<bool(const TParticle&)>: __function::__base<bool(const TParticle&)>* has no streamer or dictionary, data member __f_ will not be saved
```

**Comment by preghenella** [comment]
I see, I think it is `//!` what you mean @sawenzel .
Done

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
