### PR TITLE
TPC: adding MC ccdb objects for simulation and reconstruction

### PR DESCRIPTION
**Pull request by matthias-kleiner**
Digitization:
- adding loading of gas parameters from CCDB for tuning the electron attachment
- adding loading of GEM parameters for gain tuning

Reconstruction:
- adding option to load MC time gain calibration

### CODE REVIEW

**Comment by matthias-kleiner** [comment]
Hello @wiechula ,
if this PR is fine, we need to upload the default CCDB objects for the MC time gain, the gas parameters and the GEM parameters. Do you want to open a ticket for this or should I do it?

**Review by wiechula — DISMISSED** [review]

**Comment by sawenzel** [comment]
fullCI fails with 
```
JAlienFile::Open>: Accessing file /alice/data/CCDB/TPC/Calib/LaserTracks/14/60057/dd26d771-0929-11ed-8000-2a010e0a0b16 in SE <ALICE::CERN::OCDB>
[52063:internal-dpl-ccdb-backend]: [04:01:00][INFO] ccdb reads http://alice-ccdb.cern.ch/TPC/Calib/LaserTracks/1546300800000/dd26d771-0929-11ed-8000-2a010e0a0b16 for 1550600800000 (load to memory, agent_id: alientest02-1731988841-tBzZLP), 
[52063:internal-dpl-ccdb-backend]: [04:01:00][ERROR] CcdbDownloader finished transfer http://alice-ccdb.cern.ch/TPC/Parameter/Gas for 1550600800000 (agent_id: alientest02-1731988841-tBzZLP) with http code: 404
[52063:internal-dpl-ccdb-backend]: [04:01:00][ERROR] File TPC/Parameter/Gas could not be retrieved. No more hosts to try.
[52063:internal-dpl-ccdb-backend]: [04:01:00][ALARM] Curl request to http://alice-ccdb.cern.ch/TPC/Parameter/Gas/1550600800000/, response code: 404
[52063:internal-dpl-ccdb-backend]: [04:01:00][FATAL] Unable to find object TPC/Parameter/Gas/1550600800000
``` 
which appears to be related to this PR (please make sure to upload CCDB objects (even trivial ones) for all runs). Uploading of those objects needs to be done prior to merging this PR.

**Comment by wiechula** [comment]
Yes, @matthias-kleiner will prepare an upload request with the default objects.

**Comment by chiarazampolli** [comment]
Here it is: https://its.cern.ch/jira/browse/O2-5562, already uploaded.

**Comment by wiechula** [comment]
+async-label async-2023-pbpb-apass4

**Review by sawenzel — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @matthias-kleiner , 

This does not apply to async-v1-01-branch, if you wanted for PbPb 2023 apass4 MC, you should find the extra needed commits.
Here the error:

```
DEBUG: CONFLICT (content): Merge conflict in GPU/Workflow/include/GPUWorkflow/GPUWorkflowSpec.h
DEBUG: Auto-merging GPU/Workflow/src/GPUWorkflowSpec.cxx
DEBUG: Auto-merging GPU/Workflow/src/gpu-reco-workflow.cxx
DEBUG: CONFLICT (content): Merge conflict in GPU/Workflow/src/gpu-reco-workflow.cxx
```

Chiara

**Pull request merged**
