### PR TITLE
Mergers: Do not throw if an object is not mergeable.

### PR DESCRIPTION
**Pull request by knopers8**

### CODE REVIEW

**Comment by knopers8** [comment]
@chiarazampolli

**Review by Barthelemy — APPROVED** [review]

**Comment by knopers8** [comment]
The failure in fullCI is unrelated.

**Comment by chiarazampolli** [comment]
Hello @shahor02 , @davidrohr , @ktf , can you merge this?

**Review by shahor02 — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Thanks!

**Pull request merged**
