### PR TITLE
Fixes for ITS/MFT patterns dictionary generation

### PR DESCRIPTION
**Pull request by shahor02**
* Make CheckTopologies to work with QED-embedded MC + fix for processing data w/o MC info
The new way of adding QED leads to MC2ROF vector mapping global event id (including copious QED events) to ROF, while the Hits file provided as MC truth belongs to hadronic events (sourceID=0). Therefore, we have to provide the DigitizationContext and remap global interaction ID to that of hadronic events.

* Functionality of run_buildTopoDict_its was transferred to CheckTopologies.C
suppress to avoid maintaining duplicated code

### CODE REVIEW

**Comment by shahor02** [comment]
@lbariogl @iouribelikov I see that the ``ITSdictionary.bin`` size went from ~25KB to ~15MB. This is due to the ~7k "group" typologies stored with their 2.4 KB ``ClusterTopology`` object, each one containing uniformly filled bounding box matrix. Do we really need to store this trivial info? 
Also, I think we better switch to dictionary stored in the root object, rather than binary file version: the former is compressible and (more important) much easier to handle as a ccdb object.

**Comment by lbariogl** [comment]
@shahor02 there is no reason to have the full bounding box for groups. However, since the dictionary contains a vector of ```GroupStruct```, a member of type ```ClasterPattern``` (hence ```unsigned char[ClusterPattern::kExtendedPatternBytes```) is needed. I could easily replace the current pattern member with an empty one (except for the first two bytes that represent number of rows and columns), but is it sufficient to reduce the size of the dictionary through some compression mechanisms (maybe saving the dictinary in a root file)? Otherwise I have to think of something different. OK for the root file.

**Comment by shahor02** [comment]
@lbariogl  the root version will compress quite efficiently even non-empty cluster patterns (anyway the group patterns have very regular filling, good for root compression). Anyway, I would fill these patterns by 0 and (more important) get rid of binary version of dictionary, doing everything via root file.

**Comment by shahor02** [comment]
change of macro, irrelevant for GPU CI, merging

**Pull request merged**
