### PR TITLE
o2-eve: ability to show/hide tracks depending on detector used to its…

### PR DESCRIPTION
**Pull request by jmyrcha**
… reconstruction

+ naming tracks

### CODE REVIEW

**Comment by jmyrcha** [comment]
build/O2/o2-cs8 and build/O2/o2-dataflow-cs8 failed on irrelevant issues

**Comment by shahor02** [comment]
@jmyrcha if I merge this, it will appear tomorrow on EPNs. Did you test it? We don't have real rests in CI for the ED.

**Comment by jmyrcha** [comment]
I have tested it and it worked. But I am today preparing regression test script which will test workflow part automatically. I will check against that script and I will make commit (I have noticed one LOG(INFO) commented

**Comment by jmyrcha** [comment]
This changes solves a problem of crashes caused by rapidjson when float value written is not set (means may be NaN)

**Comment by shahor02** [comment]
@jmyrcha please tease to dev and push again, you picked lot of commits from others

**Comment by jmyrcha** [comment]
I make errors with git and this pull request contains changes from other code - I will prepare other (clean one) on current dev head with only my changes

**Pull request closed without merging**
