### PR TITLE
Fix addition of tpc-scaler-workflow for lumi-type=2

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by wiechula** [comment]
@shahor02 , can this be merged?

**Comment by chiarazampolli** [comment]
Hello @wiechula , 

Does this invalidate the existing tests using IDC for scaling?

Chiara

**Comment by wiechula** [comment]
Hi @chiarazampolli , at least our local test failed, since the `o2-tpc-scaler-workflow` is missing otherwise.

**Comment by chiarazampolli** [comment]
Hello @wiechula , 

Ah yes, this is the fix that I took by hand for production - I thought it was something in addition.

Chiara

**Pull request merged**
