### PR TITLE
Move to proper logger + protect file reads [O2-2423]

### PR DESCRIPTION
**Pull request by mpuccio**
Hi @sawenzel, @ktf 
this should fix O2-2423

Cheers,
Max

### CODE REVIEW

**Comment by mpuccio** [comment]
@jgrosseo do you know if there is a way to restart the CI? Currently the o2 one shows that the compilation of o2 is fine (it tests successfully the macros in O2) but somehow it breaks in QC.

**Comment by ktf** [comment]
@mpuccio the quickest way is probably to fix:

```
/sw/SOURCES/O2/6528-slc8_x86-64/0/Analysis/EventFiltering/centralEventFilterProcessor.cxx:39:13: error: use nullptr [modernize-use-nullptr]
```

and it should restart the PR checking.

**Comment by mpuccio** [comment]
@kft thanks, I missed that!

**Comment by mpuccio** [comment]
Test are back green, not sure if OSX test failure is related (to me it does not look like)

**Pull request merged**
