### PR TITLE
Add support for containers

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
Are you sure a dequeue is equally fast as a vector?

**Comment by ktf** [comment]
For push_back, it should be even faster (no copy), keep in mind that on the receiving side you still retrieve it as a vector / span.

**Comment by ktf** [comment]
Ok, let's do one step at the time, this will introduce support for generic forward containers being serialised as std::vector, via a copy.

**Comment by shahor02** [comment]
@ktf, I've tested this PR, indeed allows to reduce the memory, see below. Now comparing with the version writing directly to shared mem.


Values for RSS/SHM/speed, AB means running with the AfterBurner.Thh SHM change might be connected with slightly higher speed, decreasing the input TFs queue:

```
old_NoAB           old_AB         ktf_NoAB          ktf_AB        
5.2/3.9/10.1    9.3/5.2/28.      4.7/3.3/9.7    8.6/4.3/26
```

**Comment by ktf** [comment]
Cool, I assume the "speed" is really "time to process", correct?

**Comment by ktf** [comment]
Given this PR now only adds support for generic containers, I would merge this and open a new one with the ITS development which you can then decide to ignore if writing directly is better.

@shahor02 @davidrohr How does that sound?

**Comment by wiechula** [comment]
@ktf , for curiosity, in [std::deque](https://en.cppreference.com/w/cpp/container/deque) I read:
> As opposed to [std::vector](https://en.cppreference.com/w/cpp/container/vector), the elements of a deque are not stored contiguously

Can this be a problem?

**Comment by ktf** [comment]
If you rely on the data being contiguous in the producer, yes, it's definitely a problem. In the ITS case, it seems to me as elements are only push_back at the end.

If you only rely on continuous data in the consumer, this code actually consolidates the various chunks into a single message which can then be read by the receiving side as a single std::vector, so at the cost of an extra per-element copy, you do not have the problem. Of course, if you know in advance the size, most likely you are better off using `make<std::vector>` rather than `snapshot<std::deque>`. If you don't and you end up reallocating the vector you snapshot, `snapshot<std::deque>` is probably a win.

**Comment by wiechula** [comment]
Thanks for the explanation!

**Pull request merged**
