### PR TITLE
Change of Track and FwdTrack Data Model

### PR DESCRIPTION
**Pull request by jgrosseo**
Merging and conflict solving between the three PRs which touch the data model:
- https://github.com/AliceO2Group/AliceO2/pull/6924
- https://github.com/AliceO2Group/AliceO2/pull/6986
- https://github.com/AliceO2Group/AliceO2/pull/7033

### CODE REVIEW

**Comment by jgrosseo** [comment]
- Pending new data conversion
- Needs to be synced (forced because of cross-dependent CI) with: https://github.com/AliceO2Group/O2Physics/pull/84 and https://github.com/AliceO2Group/O2Physics/pull/74/

**Comment by sawenzel** [comment]
@jgrosseo : Is this going to affect the AOD writer? If yes, I'd prefer that the changes are directly part of this PR.

**Comment by jgrosseo** [comment]
> 
> 
> @jgrosseo : Is this going to affect the AOD writer? If yes, I'd prefer that the changes are directly part of this PR.

I think all the changes in the AODproducer are there. Do you see something missing?

**Comment by sawenzel** [comment]
Ok thanks. It's fine then.

**Comment by jgrosseo** [comment]
Getting this ready for merging when the new data is there. FullCI will fail because O2Physics need to be adapted at the same time.

**Review by ktf — APPROVED** [review]

**Pull request merged**
