### PR TITLE
Temporary patch Pythia8 to force particle vertex to (0,0,0,0)

### PR DESCRIPTION
**Pull request by preghenella**
This PR brings a temporary patch to the Pythia8 interface of the `o2`.
When running the Pythia8 heavy-ion machinery, particle production vertices are displaced from (0,0,0,0). Likely this is related to the internal machinery that sets the vertices in fm scales.

There is no clear cut to my mind to distinguish these vertices (fm scale) from genuine secondary vertices (mm scale) and it is possible that when decays are on these different scales are mixed.

While waiting for news and for a prescription from the Pythia8 authors the particle production vertices are forced at (0,0,0,0). 

Particle decays in Pythia8 have therefore to be treated with care and inhibited as much as possible. 
Currently the baseline configuration for decays inhibits all those particles with ctau < 0.001 mm.
Therefore there should be no issue.

**EDIT**

There is a possible solution (still a hack) to deal with this issue in a better way, namely without the risk of screwing up with decays.

Pythia8 event generation process can be instructed to stop right after hadronisation.
At that stage one can adjust the event record setting the production vertex of all particles to (0,0,0,0). And then let the system decay with the proper mm scale.

```
  /** As we have inhibited all hadron decays before init,
      the event generation stops after hadronisation.
      We then pick all particles from here and force their
      production vertex to be (0,0,0,0).
      Afterwards we process the decays. **/
```

### CODE REVIEW

**Comment by preghenella** [comment]
There is a possible solution (still a hack) to deal with this issue in a better way, namely without the risk of screwing up with decays.

Pythia8 event generation process can be instructed to stop right after hadronisation.
At that stage one can adjust the event record setting the production vertex of all particles to (0,0,0,0). And then let the system decay with the proper mm scale.

**Comment by shahor02** [comment]
@preghenella indeed, this would be more intelligent, provided that the secondaries are treated with correct scale.

**Comment by preghenella** [comment]
hi @shahor02 ,
yes, hadron decays are processed with mm scale (which is then converted to cm before feeding the simulation). 

I am preparing the code to update this patch.

**Comment by preghenella** [comment]
hello @sawenzel ,
do you find this PR good to merge?

**Pull request merged**
