### PR TITLE
DPL: make --forwarding-policy default to none

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
For reference (already reported in Mattermost): This breaks the full system test:
```
Exception caught: Worker is not authorised to create message with origin(FT0) description(RECPOINTS) subSpec(0)
```
and several similar errors.
The output data type (FT0/RECPOINTS) in this case is correctly defined for an output channel.
I believe that all data channels that get dropped (which were dangling before) are not not allowed to send an output anymore.

**Comment by ktf** [comment]
Ok, I will try to have something else.

**Comment by ktf** [comment]
What about `--forwarding-destination none`?

**Comment by ktf** [comment]
Superseded by #5651

**Pull request closed without merging**
