### PR TITLE
FT0reco: option for disabling time offset calibration

### PR DESCRIPTION
**Pull request by afurs**
Should be used in simulation

### CODE REVIEW

**Review by andreasmolander — APPROVED** [review]

**Comment by sawenzel** [comment]
@noferini

**Comment by sawenzel** [comment]
@afurs : Thanks for this. Would you be able to change the MC config yourself? Please open a PR here `https://github.com/AliceO2Group/O2DPG/blob/master/MC/bin/o2dpg_sim_workflow.py#L935` (and similar places where FT0 is treated).

**Comment by afurs** [comment]
Hi @sawenzel sorry, I will not be available until 10th May. Is it urgent?

**Comment by afurs** [comment]
Hi @andreasmolander If @sawenzel confirms that this modification is urgent and is needed before 10th May could you please implement it?

**Comment by noferini** [comment]
I had a look and the change in O2DPG should be quite trivial. Once this PR is merged I can take care to implement the new option in simulation.

**Comment by noferini** [comment]
PR opened in O2DPG (still WIP)
https://github.com/AliceO2Group/O2DPG/pull/1058

**Comment by chiarazampolli** [comment]
Hello @sawenzel , 
I would merge this. Maybe I can even do it since the button appears (not sure it would then work), I can try. 
@TimoWilken , all, is there any preference between "squash and merge" and "rebase and merge"?
Chiara

**Comment by noferini** [comment]
Dear all, can we merge this PR?

**Comment by chiarazampolli** [comment]
I can try, I am not sure if in O2 they prefer to rebase and merge, or squash and merge.

**Comment by martenole** [comment]
> I can try, I am not sure if in O2 they prefer to rebase and merge, or squash and merge.

Hi @chiarazampolli that depends on the PR. In this case one commit was just clang-formatting. That does not need to be in the history as a separate commit, it would only clutter it. So I have squashed merged. But sometimes commits should stay separate in the git history and then one should rebase. If in doubt, I would always ask the author of the PR for preferred way.

**Comment by chiarazampolli** [comment]
Thanks Ole! I was also curious to see if the button would have really worked for me... Next time!

**Pull request merged**
