### PR TITLE
Halves the memory allocations in the TPCITS matcher

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by davidrohr — APPROVED** [review]
This seems reasonable to do, but unfortunately it will hardly reduce the memory footprint at all, since the local buffers are in private process many, and the snapshot to messages is in SHM memory. Since all SHM memory is resident all the time anyway, the snapshot does not increase the working set of the process.
So the only thing that will change is that we release the private memory slightly earlier.

**Comment by ktf** [comment]
@shahor02 One more optimisation possibility? This should get rid of a peak in the TPCITC matching.

Notice that an even better approach, which would get rid of one copy, would be to allocate the vectors using `ctx.outputs.make()` rather than snapshotting an existing vector.

**Comment by ktf** [comment]
@davidrohr you are right, but then the second approach I mention above should be the way to go.

**Comment by davidrohr** [comment]
> @shahor02 One more optimisation possibility? This should get rid of a peak in the TPCITC matching.
> 
> Notice that an even better approach, which would get rid of one copy, would be to allocate the vectors using `ctx.outputs.make()` rather than snapshotting an existing vector.

This would really reduce the private memory footprint of the process, while the current PR, as explained above, only releases the memory slightly earlier but does not reduce the max footprint.

**Comment by ktf** [comment]
BTW, are we doing emplace_back without reserving on that vector? That means we are doubling the capacity each time it needs to reallocate, due to the requirement of amortised push_back / emplace_back cost.

**Comment by ktf** [comment]
See #12053 for the last comment.

**Comment by ktf** [comment]
> This would really reduce the private memory footprint of the process, while the current PR, as explained above, only releases the memory slightly earlier but does not reduce the max footprint.

Agreed.

**Comment by shahor02** [comment]
I agree that this PR will not reduce peak allocation. Will try to modify the code to avoid intermediate containers, writing directly to output. Concerning the capacity doubling at emplace_back: when I can have a reasonable estimate of the final size, I do reserve, but in many cases the safe guess could be too large. 
But then, because of https://github.com/AliceO2Group/AliceO2/pull/12053/files#diff-db0c79346841b217e21d4b5a118feccdf17e5b5126e2693af140243328d26af1R350-R362 using dequeue will be meaningless.

**Pull request closed without merging**
