### PR TITLE
Do not quit on empty payload

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Comment by peressounko** [comment]
failed tests seems to be unrelated to the commit

**Comment by shahor02** [comment]
@peressounko: in which case you expect no payload? Why do you return in this case w/o providing any output? This may eventually lead to the loss of the TF for the whole combined workflow.

**Comment by peressounko** [comment]
@shahor02 Dear Ruben, I removed exit without sending data. Now should be OK. Could you approve?

**Comment by shahor02** [comment]
Hi @peressounko 

The fullCI got stuck somewhere... Sorry for being picky, but could you please run it locally to be sure it is not related to PHOS? If everyhing is fine, I will merge it, it will appear in the next nightly.

Cheers,
 Ruben

**Comment by peressounko** [comment]
@shahor02, Hi Ruben,

I run test as env ALIBUILD_O2_TESTS=1 aliBuild build O2 --defaults o2 --debug.

Some tests failed but they I think not related to PHOS



2021-10-30@10:58:01:DEBUG:O2:O2:0:         Start  18: Framework/Utils/test/test_RootTreeReader.cxx
2021-10-30@10:58:01:DEBUG:O2:O2:0:  16/403 Test   #4: Common/Field/test/testMagneticField.cxx ..............................................***Failed   14.17 sec
2021-10-30@10:58:01:DEBUG:O2:O2:0: Running 1 test case...
2021-10-30@10:58:01:DEBUG:O2:O2:0: [INFO] MagneticField::CreateField: Maximim possible beam energy for requested beam is assumed
2021-10-30@10:58:01:DEBUG:O2:O2:0: Error in <TFile::TFile>: file /home/prsnko/alice/sw/BUILD/826cfc0a746577615dae152dbdc363ca0218487b/O2/stage/share/Common/maps/mfchebKGI_sym.root does not exist
2021-10-30@10:58:01:DEBUG:O2:O2:0: [FATAL] MagneticField::loadParameterization: Failed to open magnetic field data file /home/prsnko/alice/sw/BUILD/826cfc0a746577615dae152dbdc363ca0218487b/O2/stage/share/Common/maps/mfchebKGI_sym.root
2021-10-30@10:58:01:DEBUG:O2:O2:0:
2021-10-30@10:58:01:DEBUG:O2:O2:0: For later analysis we write a core dump to core_dump_12527
2021-10-30@10:58:01:DEBUG:O2:O2:0: unknown location(0): fatal error: in "MagneticField_test": unknown type
2021-10-30@10:58:01:DEBUG:O2:O2:0: /home/prsnko/alice/sw/SOURCES/O2/dev/0/Common/Field/test/testMagneticField.cxx(26): last checkpoint: "MagneticField_test" test entry
2021-10-30@10:58:01:DEBUG:O2:O2:0:
2021-10-30@10:58:01:DEBUG:O2:O2:0:         Start  19: Framework/Utils/test/test_RootTreeWriter.cxx


2021-10-30@10:59:56:DEBUG:O2:O2:0: 126/403 Test  #98: Detectors/Base/test/testMatBudLUT.cxx ................................................***Failed   58.44 sec
2021-10-30@10:59:56:DEBUG:O2:O2:0: [INFO] This is o2-sim version 1.2.0 (f490f571b60f (+local changes))
2021-10-30@10:59:56:DEBUG:O2:O2:0: [INFO] Built by ALIBUILD:v1.9.1, ALIDIST-REV:98cc216a6592b38fc495653f047bff7a2fac69f5 on OS:Linux-4.15.0-159-generic
2021-10-30@10:59:56:DEBUG:O2:O2:0: [INFO] BINDING TO ADDRESS ipc:///tmp/o2sim-notifications-14722 type pub
2021-10-30@10:59:56:DEBUG:O2:O2:0: [INFO] No events to be simulated; Switching to non-distributed mode
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:58:58][INFO] Is alien token present?: 0
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:58:58][INFO] Is alien token present?: 0
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:58:58][INFO] Initialized CCDB Manager at URL: ccdb-test.cern.ch:8080
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:58:58][INFO] Initialized CCDB Manager with timestamp : 1635580738645
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:58:59][INFO] RNG INITIAL SEED 3560587050
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:59:14][WARN] FairRun::SetOutputFile() deprecated. Use FairRootFileSink.
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:59:14][INFO] Media file used: /home/prsnko/alice/sw/BUILD/826cfc0a746577615dae152dbdc363ca0218487b/O2/stage/share/Detectors/Geometry/media.geo
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:59:14][INFO] MagneticField::CreateField: Maximim possible beam energy for requested beam is assumed
2021-10-30@10:59:56:DEBUG:O2:O2:0: Error in <TFile::TFile>: file /home/prsnko/alice/sw/BUILD/826cfc0a746577615dae152dbdc363ca0218487b/O2/stage/share/Common/maps/mfchebKGI_sym.root does not exist
2021-10-30@10:59:56:DEBUG:O2:O2:0: [10:59:14][FATAL] MagneticField::loadParameterization: Failed to open magnetic field data file /home/prsnko/alice/sw/BUILD/826cfc0a746577615dae152dbdc363ca0218487b/O2/stage/share/Common/maps/mfchebKGI_sym.root
2021-10-30@10:59:56:DEBUG:O2:O2:0:
2021-10-30@10:59:56:DEBUG:O2:O2:0: For later analysis we write a core dump to core_dump_14722
2021-10-30@10:59:56:DEBUG:O2:O2:0: Aborted (core dumped)
2021-10-30@10:59:56:DEBUG:O2:O2:0: Running 1 test case...
2021-10-30@10:59:56:DEBUG:O2:O2:0: o2sim_geometry.root does not exist. Will create it
2021-10-30@10:59:56:DEBUG:O2:O2:0: [INFO] Loading geometry from o2sim_geometry.root
2021-10-30@10:59:56:DEBUG:O2:O2:0: Error in <TFile::TFile>: file /home/prsnko/alice/sw/BUILD/826cfc0a746577615dae152dbdc363ca0218487b/O2/Detectors/Base/o2sim_geometry.root does not exist
2021-10-30@10:59:56:DEBUG:O2:O2:0: [FATAL] Failed to open file o2sim_geometry.root
2021-10-30@10:59:56:DEBUG:O2:O2:0: For later analysis we write a core dump to core_dump_14696
2021-10-30@10:59:56:DEBUG:O2:O2:0: unknown location(0): fatal error: in "MatBudLUT": unknown type
2021-10-30@10:59:56:DEBUG:O2:O2:0: /home/prsnko/alice/sw/SOURCES/O2/dev/0/Detectors/Base/test/testMatBudLUT.cxx(25): last checkpoint


2021-10-30@11:05:45:DEBUG:O2:O2:0: 245/403 Test #222: Detectors/TRD/base/test/testTRDDiffusionCoefficient.cxx ..............................***Failed   16.21 sec
2021-10-30@11:05:45:DEBUG:O2:O2:0: Running 1 test case...
2021-10-30@11:05:45:DEBUG:O2:O2:0: Error in <TFile::TFile>: file /home/prsnko/alice/sw/BUILD/826cfc0a746577615dae152dbdc363ca0218487b/O2/stage/share/Common/maps/mfchebKGI_sym.root does not exist
2021-10-30@11:05:45:DEBUG:O2:O2:0: [FATAL] MagneticField::loadParameterization: Failed to open magnetic field data file /home/prsnko/alice/sw/BUILD/826cfc0a746577615dae152dbdc363ca0218487b/O2/stage/share/Common/maps/mfchebKGI_sym.root
2021-10-30@11:05:45:DEBUG:O2:O2:0:
2021-10-30@11:05:45:DEBUG:O2:O2:0: For later analysis we write a core dump to core_dump_19644
2021-10-30@11:05:45:DEBUG:O2:O2:0: unknown location(0): fatal error: in "TRDDiffusionCoefficient_test1": unknown type
2021-10-30@11:05:45:DEBUG:O2:O2:0: /home/prsnko/alice/sw/SOURCES/O2/dev/0/Detectors/TRD/base/test/testTRDDiffusionCoefficient.cxx(32): last checkpoint: "TRDDiffusionCoefficient_test1" test entry
2021-10-30@11:05:45:DEBUG:O2:O2:0:


2021-10-30@11:10:21:DEBUG:O2:O2:0: 369/403 Test #363: o2sim_hepmc ..........................................................................***Failed  Required regular expression not found. Regex=[SIMULATION RETURNED SUCCESFULLY
2021-10-30@11:10:21:DEBUG:O2:O2:0: ] 42.45 sec
2021-10-30@11:10:21:DEBUG:O2:O2:0: [INFO] This is o2-sim version 1.2.0 (f490f571b60f (+local changes))
2021-10-30@11:10:21:DEBUG:O2:O2:0: [INFO] Built by ALIBUILD:v1.9.1, ALIDIST-REV:98cc216a6592b38fc495653f047bff7a2fac69f5 on OS:Linux-4.15.0-159-generic
2021-10-30@11:10:21:DEBUG:O2:O2:0: [INFO] BINDING TO ADDRESS ipc:///tmp/o2sim-notifications-22540 type pub
2021-10-30@11:10:21:DEBUG:O2:O2:0: [INFO] Running with 2 sim workers
2021-10-30@11:10:21:DEBUG:O2:O2:0: [INFO] CREATING SIM SHARED MEM SEGMENT FOR 2 WORKERS
2021-10-30@11:10:21:DEBUG:O2:O2:0: Spawning particle server on PID 22543; Redirect output to o2simhepmc_serverlog
2021-10-30@11:10:21:DEBUG:O2:O2:0: Spawning sim worker 0 on PID 22545; Redirect output to o2simhepmc_workerlog0
2021-10-30@11:10:21:DEBUG:O2:O2:0: Spawning hit merger on PID 22546; Redirect output to o2simhepmc_mergerlog
2021-10-30@11:10:21:DEBUG:O2:O2:0: [INFO] Process 22543 EXITED WITH CODE 0 SIGNALED 1 SIGNAL 6


2021-10-30@11:12:22:DEBUG:O2:O2:0:
2021-10-30@11:12:22:DEBUG:O2:O2:0: 98% tests passed, 9 tests failed out of 403
2021-10-30@11:12:22:DEBUG:O2:O2:0:


2021-10-30@11:12:22:DEBUG:O2:O2:0: The following tests FAILED:
2021-10-30@11:12:22:DEBUG:O2:O2:0:        4 - Common/Field/test/testMagneticField.cxx (Failed)
2021-10-30@11:12:22:DEBUG:O2:O2:0:       98 - Detectors/Base/test/testMatBudLUT.cxx (Failed)
2021-10-30@11:12:22:DEBUG:O2:O2:0:      222 - Detectors/TRD/base/test/testTRDDiffusionCoefficient.cxx (Failed)
2021-10-30@11:12:22:DEBUG:O2:O2:0:      359 - o2sim_G4 (Failed)
2021-10-30@11:12:22:DEBUG:O2:O2:0:      360 - o2sim_checksimkinematics_G4 (Not Run)
2021-10-30@11:12:22:DEBUG:O2:O2:0:      361 - o2sim_G3 (Not Run)
2021-10-30@11:12:22:DEBUG:O2:O2:0:      362 - o2sim_checksimkinematics_G3 (Not Run)
2021-10-30@11:12:22:DEBUG:O2:O2:0:      363 - o2sim_hepmc (Failed)
2021-10-30@11:12:22:DEBUG:O2:O2:0:      364 - o2sim_G3_checklogs (Not Run)


2021-10-30@11:13:28:DEBUG:O2:O2:0: 100% tests passed, 0 tests failed out of 93
2021-10-30@11:13:28:DEBUG:O2:O2:0:
2021-10-30@11:13:28:DEBUG:O2:O2:0: Label Time Summary:
2021-10-30@11:13:28:DEBUG:O2:O2:0: benchmark    =  19.76 sec*proc (2 tests)
2021-10-30@11:13:28:DEBUG:O2:O2:0: dplutils     =  19.76 sec*proc (2 tests)
2021-10-30@11:13:28:DEBUG:O2:O2:0: framework    =  45.76 sec*proc (89 tests)
2021-10-30@11:13:28:DEBUG:O2:O2:0: workflow     =  35.18 sec*proc (26 tests)
2021-10-30@11:13:28:DEBUG:O2:O2:0:
2021-10-30@11:13:28:DEBUG:O2:O2:0: Total Test time (real) =  65.72 sec
2021-10-30@11:13:28:DEBUG:O2:O2:0:
2021-10-30@11:13:28:DEBUG:O2:O2:0: The following tests did not run:
2021-10-30@11:13:28:DEBUG:O2:O2:0:       85 - test_Framework_test_BoostSerializedProcessing (Disabled)
2021-10-30@11:13:28:DEBUG:O2:O2:0:       88 - test_Framework_test_DanglingInputs (Disabled)
2021-10-30@11:13:28:DEBUG:O2:O2:0:      118 - test_Framework_test_CustomGUIGL (Disabled)
2021-10-30@11:13:28:DEBUG:O2:O2:0:      119 - test_Framework_test_CustomGUISokol (Disabled)
2021-10-30@11:13:28:DEBUG:O2:O2:0:      120 - test_Framework_test_SimpleTracksED (Disabled)

**Comment by shahor02** [comment]
Hi @peressounko 

Thanks, but i meant just the full system test, which failed in the CI. Ok i can run it myself in a few hours

**Comment by shahor02** [comment]
@peressounko ok, test passed here but I see that sometimes it is stuck due to the ITS reco in async mode, will contact @mpuccio.  Merging.

**Pull request merged**
