### PR TITLE
Must reset TRM TDC error counter in case header/trailer is not detected

### PR DESCRIPTION
**Pull request by preghenella**
In specific problematic cases with wrong raw data stream from TRM it has been observed that a TDC error was emitted, but the decoding stream was broken by wrong data from the TRM.

This caused the TDC error to be pushed in the compressed stream, but not accounted for, causing errors in decoding downstream.

### CODE REVIEW

**Comment by preghenella** [comment]
`clang-format` check failure seems to be unrelated to this PR
`build/O2/o2` fails with `c++: internal compiler error: Killed (program cc1plus)`, also unrelated.

**Review by noferini — DISMISSED** [review]

**Comment by preghenella** [comment]
all checks have passed.
I take advantage that this is not merged yet to include another commit.

**Review by noferini — DISMISSED** [review]

**Comment by preghenella** [comment]
sorry @noferini 
I keep adding commits to this PR given that is not getting merged.
There is no urgency to approve.

**Review by noferini — APPROVED** [review]

**Comment by preghenella** [comment]
not sure why it fails in `build/O2/gpu` with `aliDoctor error`.
Possibly unrelated to this PR.
@ktf, can this please be merge? Thanks

**Comment by noferini** [comment]
Hi @ktf,
is it possible to merge this PR? It seems to me everything is fine here.
I need to open a PR in the alicetof:tof-dev branch (for TOF commissioning) but I want avoid to port my commits in this PR.
Cheers
Francesco

**Pull request merged**
