### PR TITLE
TRD avoid strcmps O2-734

### PR DESCRIPTION
**Pull request by jolopezl**
Avoid string comparisons in the digitizer by extending the TRD hit.

### CODE REVIEW

**Comment by jolopezl** [comment]
I am using the same PR to add a forward reference in Detector.h instead of the full TRsim header.

**Comment by sawenzel** [comment]
This is fine and I'll merge now.

In a second step I would suggest to go further and avoid calling 
```
gGeoManager->SetCurrentPoint(pos);
gGeoManager->FindNode();
    // Go to the local coordinate system
    // loc [0] -  col direction in amplification or drift volume
    // loc [1] -  row direction in amplification or drift volume
    // loc [2] -  time direction in amplification or drift volume
    gGeoManager->MasterToLocal(pos, loc);
```
in the digitizer overall, as these are expensive operations. The local coordinates can also be cached in the hit directly.

**Comment by jolopezl** [comment]
> This is fine and I'll merge now.
> 
> In a second step I would suggest to go further and avoid calling
> 
> ```
> gGeoManager->SetCurrentPoint(pos);
> gGeoManager->FindNode();
>     // Go to the local coordinate system
>     // loc [0] -  col direction in amplification or drift volume
>     // loc [1] -  row direction in amplification or drift volume
>     // loc [2] -  time direction in amplification or drift volume
>     gGeoManager->MasterToLocal(pos, loc);
> ```
> 
> in the digitizer overall, as these are expensive operations. The local coordinates can also be cached in the hit directly.

@sawenzel: Thanks for the idea, this is easy to implement so I will implement it and request a new PR.

**Comment by jolopezl** [comment]
https://github.com/AliceO2Group/AliceO2/pull/2120

**Pull request merged**
