### PR TITLE
DPL Analysis: untangle track selection

### PR DESCRIPTION
**Pull request by aalkin**
* Use template instead of concrete track row type 
* Remove unnecessary includes in order not to expose expression stuff to rootcling
Note that this still requires major rework: using ROOT objects is not recommended for anything except the final analysis results

### CODE REVIEW

**Comment by mkruegerGitHub** [comment]
>       Note that this still requires major rework: using ROOT objects is not recommended for anything except the final analysis results

Is there an alternative to ROOT histograms for looking at QA plots of the track variables?
I was also thinking about putting the histograms in a separate task to disentangle this a bit from the actual track selection. But anyway, the histograms would be the 'final result' in the case of QA, right?

**Comment by jgrosseo** [comment]
This is my fault, because I suggested it to be a TObject such that we can configure it in user space, and stream the object. These recipes to follow require a dedicated discussion.

**Comment by aalkin** [comment]
> Is there an alternative to ROOT histograms for looking at QA plots of the track variables?
QA histograms are fine, they are final objects. The selection itself should not be done as TObject, but for now it is OK, since some required functionality is missing (namely, filtering needs to be extended, then you will not need a state for selection that will become a set of filters with parameters set by configurables).

**Comment by jgrosseo** [comment]
gpu CI broken. Merging.

**Pull request merged**
