### PR TITLE
DPL: Amend documentation based on TB feedback

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @mkrzewic @matthiasrichter this is my understanding of the feedback from the TB. Please feel free to comment or amend it.

**Comment by ktf** [comment]
Documentation only. Merging.

**Comment by davidrohr** [comment]
@ktf fine with me, at the moment it looks anyway only like a placeholder indicating that support for this will come. Let's discuss when you have some ideas for the final design.

**Comment by ktf** [comment]
yes, that's the idea. We just acknowledge it as a "user story".

**Pull request merged**
