### PR TITLE
DPL: use shared memory transport for ipc://

### PR DESCRIPTION
**Pull request by aalkin**

### CODE REVIEW

**Comment by ktf** [comment]
@knopers8 can you try with this PR to see if your benchmark improves?

**Comment by knopers8** [comment]
ok

**Comment by knopers8** [comment]
though i've been running these latest benchmarks already with ",transport=shmem", but with shorter buffers, so it wouldn't crash. I wouldn't expect much difference since that time.

**Comment by ktf** [comment]
Ok. The major difference is that FairMQ 1.4.9 should actually enable shared memory transport to work correctly. Did you use 1.4.9?

**Comment by knopers8** [comment]
no, 1.4.7 as far as i remember, i will try it out then

**Comment by knopers8** [comment]
What might be the problem, if I get "Invalid workflow: Could not match offer to original resource.", but I don't use the --resources option?

**Comment by knopers8** [comment]
For 8 producers, 1B payloads and sampling 0%, Dispatcher processes ~130000 messages/s and uses ~160% CPU then.
image
The full benchmarks are running and should finish before tomorrow morning.

**Comment by knopers8** [comment]
The number of 130000 msg/s was actually achieved without shmem, I forgot to pull the PR at first. But we have a fuller comparison thanks to that.
All the processes had buffers of size 10 set (default is 1000).

So the raw message rate is actually slower for shmem than zmq, but of course we benefit from shmem when operating on larger payload sizes. The missing values are results of crashes - it seems that there is still something wrong when we need larger amounts of memory. I will run it again on with larger shmem-segment-size and see what happens.

Payload size [B] | Messages/s | Messages/s | Messages/s | Messages/s
-- | -- | -- | -- | --
  | latest dev, 0% | latest dev, 100% | enabling shmem, 0% | enabling shmem, 100%
1 | 132212 | 131319 | 116188 | 61601
256 | 131903 | 130516 | 118726 | 49302
1k | 131139 | 128009 | 117847 | 49453
4k | 131792 | 109992 | 118421 | 49254
16k | 126418 | 63264 | 117311 | 44164
64k | 59552 | 29327 | 118862 | 31029
256k | 18770 | 8285 | 117555 | 14633
1M | 6606 | 1835 | 119179 |  
4M | 1159 | 592 | 118158 |  
16M | 292 | 112 | 117536 |  
64M | 41 | 24 | 117686 |  
256M | 10 | 5 | 101386 |  
1G | 2 | 1 | 12637 |

**Comment by knopers8** [comment]
Yes, I have to. If I adopted an input message with the DataAllocator, it would be still deleted by the original owner (at least this would happen when I tried it last time). To avoid it, we would need the framework to know that it shouldn't destroy it. Also we would need to make sure, that Dispatcher is the last process to get that message, so it is not shared by two processes at the same time later.

**Comment by knopers8** [comment]
Increasing shm-segment-size to 200000000000 helps only to some extent:

Payload size [B] | Messages/s
-- | --
  | enabling shmem, 100%
1 | 61571
256 | 52334
1k | 50236
4k | 48831
16k | 42879
64k | 34721
256k | 13903
1M | 3749
4M | 985
16M | 212
64M |  
256M |  
1G |

**Comment by ktf** [comment]
@rbx @dennisklein any idea on why `shmem` with large messages might not work? Do you have a test case with large messages?

**Comment by rbx** [comment]
Just tried with:
``
./fairmq/fairmq-bsampler --id bsampler1 --transport shmem --severity debug --channel-config name=data,method=bind,type=push,address=tcp://localhost:5555 --msg-size 1000000000 --shm-segment-size 16000000000
``
and
``
./fairmq/fairmq-sink --id sink1 --transport shmem --severity debug --channel-config name=data,type=pull,method=connect,address=tcp://127.0.0.1:5555
``
It works:
```
[16:13:30][INFO] Starting the benchmark and expecting to receive 0 messages.
[16:13:31][INFO] data[0]: in: 280 (280000 MB) out: 0 (0 MB)
[16:13:32][INFO] data[0]: in: 280 (280000 MB) out: 0 (0 MB)
[16:13:33][INFO] data[0]: in: 280 (280000 MB) out: 0 (0 MB)
[16:13:34][INFO] data[0]: in: 280 (280000 MB) out: 0 (0 MB)
[16:13:35][INFO] data[0]: in: 280 (280000 MB) out: 0 (0 MB)
[16:13:36][INFO] data[0]: in: 280 (280000 MB) out: 0 (0 MB)
[16:13:37][INFO] data[0]: in: 280 (280000 MB) out: 0 (0 MB)
[16:13:38][INFO] data[0]: in: 280 (280000 MB) out: 0 (0 MB)
```

While it is running, try launching the monitor in view-only mode to see if perhaps the memory is full (view-only only available in 1.4.9):
```
./fairmq/fairmq-shmmonitor -v -i -s <sessionid>
```
For example, this is the output for me while i run the above devices:
```
./fairmq/fairmq-shmmonitor -v -i                                                                      5ms  Tue 10 Dec 2019 04:17:56 PM CET
Starting shared memory monitor for session: "default" (shmId: 13488916)...

controls: [x] close memory, [p] print queues, [h] help, [q] quit.

|               name |       size |       free |  devices |    last hb |
|  fmq_13488916_main | 16000000000 | 14999999760 |        2 |  view only ||
```

**Comment by rbx** [comment]
What does "100%" mean in your table?

**Comment by ktf** [comment]
100% message sampled. So a copy is involved there.

**Comment by knopers8** [comment]
This is a topology with 8 producers -> 1 Dispatcher -> 1 receiver. 100% means that Dispatcher **copies** 100% of messages from the producers and sends them to the receiver. 0%, on the other hand, means that Dispatcher looks at all the messages, but doesn't send anything to the receiver.

**Comment by rbx** [comment]
> I will run it again on with larger shmem-segment-size and see what happens.

Just to be sure, the option is called `--shm-segment-size` and should be passed to all devices (the first one to start will actually use it, so you can pass it to him, if you know who is first)

**Comment by knopers8** [comment]
Yes, i used this exact option in the end, I just didn't remember the name at the beginning

**Comment by knopers8** [comment]
Thanks for that hint with fairmq-shmmonitor. I see that the free memory size gets very low and completely constant when I observe that my topology stops working. The Dispatcher and producers are sleeping (they don't crash, I wrongly assumed it seeing that they are no longer visible on the top of `top`).

I have a theory to test - they might be stuck in a dead-lock, Dispatcher has full input buffers and it cannot allocate enough memory to copy a message, but at the same time it cannot release it by dropping the messages in the buffer.

**Comment by knopers8** [comment]
So this is indeed happening, this is the stack trace of the Dispatcher
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
bt0x00007fdf087d7bdd in nanosleep () from /lib64/libpthread.so.0
(gdb) bt
#0  0x00007fdf087d7bdd in nanosleep () from /lib64/libpthread.so.0
#1  0x00007fdf077714de in std::this_thread::sleep_for<long, std::ratio<1l, 1000l> > (__rtime=...)
    at /build/workarea/sw/20156079/1/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-12/include/c++/7.3.0/thread:376
#2  FairMQMessageSHM::InitializeChunk (this=this@entry=0x251ba70, size=size@entry=5924000)
    at /build/workarea/sw/20156079/1/SOURCES/FairMQ/v1.4.9/v1.4.9/fairmq/shmem/FairMQMessageSHM.cxx:130
#3  0x00007fdf0777171c in FairMQMessageSHM::FairMQMessageSHM (this=0x251ba70, manager=..., data=0x25aeab8, 
    size=5924000, ffn=
    0x7fdf091f4fd0 <FairMQChannel::CheckSendCompatibility(std::vector<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> >, std::allocator<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> > > >&)::{lambda(void*, void*)#1}::_FUN(void*, void*)>, hint=0x24f2290, factory=0x2524d30)
    at /build/workarea/sw/20156079/1/SOURCES/FairMQ/v1.4.9/v1.4.9/fairmq/shmem/FairMQMessageSHM.cxx:76
#4  0x00007fdf077889b9 in FairMQTransportFactorySHM::CreateMessage (this=0x2524d30, data=0x25aeab8, 
    size=5924000, 
#4  0x00007fdf077889b9 in FairMQTransportFactorySHM::CreateMessage (this=0x2524d30, data=0x25aeab8, 
    size=5924000, 
    ffn=0x7fdf091f4fd0 <FairMQChannel::CheckSendCompatibility(std::vector<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> >, std::allocator<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> > > >&)::{lambda(void*, void*)#1}::_FUN(void*, void*)>, hint=0x24f2290)
    at /build/workarea/sw/20156079/1/SOURCES/FairMQ/v1.4.9/v1.4.9/fairmq/shmem/FairMQTransportFactorySHM.cxx:126
#5  0x00007fdf091f8672 in FairMQChannel::NewMessage<void*, unsigned long, FairMQChannel::CheckSendCompatibility(std::vector<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> >, std::alloca
tor<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> > > >&)::{lambda(void*, void*)#1}, FairMQMessage*>(void*&&, unsigned long&&, FairMQChannel::CheckSendCompatibility(std::vector<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> >, std::allocator<std::unique_ptr<FairMQMessage, std::default_delete<FairMQMessage> > > >&)::{lambda(void*, void*)#1}&&, FairMQMessage*&&) (this=0x252ebf0)
---Type <return> to continue, or q <return> to quit---
   slc7_x86-64/FairMQ/v1.4.9-1/include/fairmq/FairMQChannel.h:323
#6  FairMQChannel::CheckSendCompatibility (msgVec=..., this=0x252ebf0) at /home/datasampling/alice/sw/slc7_x86-64/FairMQ/v1.4.9-1/include/fairmq/FairMQChannel.h:410
#7  FairMQChannel::Send (sndTimeoutInMs=-1, msgVec=..., this=0x252ebf0) at /home/datasampling/alice/sw/slc7_x86-64/FairMQ/v1.4.9-1/include/fairmq/FairMQChannel.h:278
#8  FairMQDevice::Send (sndTimeoutInMs=-1, index=0, channel=..., parts=..., this=0x24f4b30) at /home/datasampling/alice/sw/slc7_x86-64/FairMQ/v1.4.9-1/include/fairmq/FairMQDevice.h:157
#9  o2::framework::DataProcessor::doSend (device=..., context=...) at /home/datasampling/alice/sw/SOURCES/O2/1.0.0/0/Framework/Core/src/DataProcessor.cxx:47
#10 0x00007fdf091f43a3 in o2::framework::DataProcessingDevice::<lambda(o2::framework::TimesliceSlot, o2::framework::InputRecord&)>::operator() (record=..., __closure=<synthetic pointer>, slot=...)
    at /home/datasampling/alice/sw/SOURCES/O2/1.0.0/0/Framework/Core/src/DataProcessingDevice.cxx:519
```
The available memory reported by shmmonitor is 5958272, the message payload size is 5924000 in this case. Taking into account the headers overheads and memory alignment, that might be just not enough. Dispatcher cannot create a new message, because there is not enough memory, but it also cannot flush any other messages to make room.

This is a problem, which we might encounter many times in the future. Do we have any ways to mitigate it? I will try running the topology with pub-sub channels instead of push-pull, but then, I expect that Dispatcher will anyway fail to send any messages further, but just without being blocked.

**Comment by dennisklein** [comment]
> This is a problem, which we might encounter many times in the future. Do we have any ways to mitigate it?

If you want to stick with the built-in memory allocator of the FairMQ shm transport, the relevant parameters are `--shm-segment-size` and the `Snd/RcvBufSize` knobs per channel.

However, if you need more control, FairMQ provides the [`FairMQUnmanagedRegion`](https://github.com/FairRootGroup/FairMQ/blob/master/fairmq/FairMQUnmanagedRegion.h) API, with which you can replace the builtin (boost-interprocess-based) allocator with anything you want.

The basically works as follows:
1. Allocate a large chunk of memory (region) via the `FairMQUnmanagedRegion` class in one of the devices (usually the first sender in the pipeline) at initialization time.
  * This ensures this region is configured as proper shared memory as required by the FairMQ transport.
  * Example: https://github.com/FairRootGroup/FairMQ/blob/f31be6d7a10ab0b7e4183576438268c8122117a5/examples/region/Sampler.cxx#L38-L47
2. Carve out message buffers from this region with any memory allocation strategy that fits your application best.
3. Create a `FairMQMessage` object for each of those buffers to be able to send them via a FairMQ channel.
  * Example: https://github.com/FairRootGroup/FairMQ/blob/f31be6d7a10ab0b7e4183576438268c8122117a5/examples/region/Sampler.cxx#L52-L58
4. Once a receiving device (can be even multiple hops down the pipeline) destructs the FairMQMessage object, FairMQ will call the callback you registered with the `FairMQUnmanagedRegion` object created in the process/device from step 1.

**Comment by dennisklein** [comment]
> The available memory reported by shmmonitor is 5958272, the message payload size is 5924000 in this case.

Also note, that message buffers are contiguous chunks of memory and thus subject to fragmentation of the shm segment. So, even if there is enough free memory reported by these numbers, it may not be enough to serve it as one single buffer.

**Comment by aalkin** [comment]
@ktf seeing how this thing fails in testing, did you check if it is leaving behind shhmonitor zombie processes or disrupts subsequent runs in any other way? I see errors in completely unrelated things

**Comment by knopers8** [comment]
Thanks Dennis, in a longer term I will see if I can allocate and use a separate unmanaged region inside Dispatcher, so it is not blocked by lack of memory in the common region.

I have to see if merging this PR destroys more setups, like Readout -> Data Sampling -> Quality Control.

**Comment by ktf** [comment]
@aalkin no, it looks we are clean. However it looks like the issue is only in RootTreeWriter? Didn't we have a fix for that?

**Comment by knopers8** [comment]
I am observing quite random exits of my DPL topology with readout proxy and QC, which I cannot reproduce with the latest dev as opposed to this PR. They seem to be started by the DPL driver, with the earliest point which I managed to track so far being runDataProcessing.cxx:961 - a request from GUI (I was running it with -b, so probably not) or a result of a termination policy.

**Comment by knopers8** [comment]
OK, it wasn't actually related to this PR, I am fine with merging this. QC doesn't break with usual data rates. I will have to find a solution for the problem with deadlocks in my benchmarks anyway, but I don't want to block this PR with that.

**Comment by ktf** [comment]
Bumping to the newest FairMQ made both this and #2527 green. Merging #2527 because it has one extra bit which I think we need (the info.pid != 0) and the merging this, because it has a few messages which are actually better.

**Pull request merged**
