### PR TITLE
Fix ITS CA reconstruction macros

### PR DESCRIPTION
**Pull request by mpuccio**
@mconcas have a look, if it is fine with you I think that this can me merged.

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi @mpuccio : Is also the problem I had with no roads with, which I saw when I wanted to test the ITS track fit? I can give the new macro a look tonight.

**Comment by mpuccio** [comment]
Ciao @davidrohr , running on Pb-Pb events now I see tracks in the output so the issue should be solved. However I did not run any deep QA yet.

**Comment by mpuccio** [comment]
Excellent @davidrohr ! I wait for a small patch from Matteo and then I think this can be merged if it is fine with you (o2 build fails on unrelated things)

**Comment by davidrohr** [comment]
It seems right now all C.I. tests are failing due to this "/bin/sh: fork: Cannot allocate memory" problem @dberzano.

**Comment by mpuccio** [comment]
Not sure why there is a second Travis check is pending, but in principle everything is ready to be merged.

**Comment by davidrohr** [comment]
weird, both clang-format and doxygen ran through. Let's leave it open till tomorrow, in case someone wants to check the C.I. issue. (@dberzano)

**Comment by mpuccio** [comment]
News on this?

**Comment by davidrohr** [comment]
Didn't here anything. It fixes all the problems for me and mostly macro changes anyway. If you agree, I'll merge as is.

**Comment by mconcas** [comment]
Jobs have been restarted, just to see if this fixes. Otherwise We see that tests are green, so no problems.

**Comment by dberzano** [comment]
I have restarted manually the two Travis CI jobs, let's see if it works... I have no idea why this is stuck, [this site](https://traviscistatus.com) is reporting all OK for now...

**Comment by mconcas** [comment]
Here we go

**Comment by davidrohr** [comment]
ok, great, so it was just something stuck in the C.I.
Merging, thanks for the fix

**Pull request merged**
