### PR TITLE
DPL: introduce "Optional" lifetime

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 @davidrohr I think this is what is missing to have what I was describing today in the meeting. Any input declared as "Lifetime::Optional" will be created as a dummy entry as soon as data arrives. Notice contrary to what was discussed, this will be done on the first consumer of the data, not on the output proxy, but it should be ok. I will try to elaborate more later.

**Comment by shahor02** [comment]
@ktf thanks! If I understood the ``LifetimeHelpers::dummy`` correctly, you send separate dummy message. Will it be received together with real ones in case of default completion policy?

I had a question to you on mattermost.

**Comment by ktf** [comment]
It's not "received" but directly materialised in the `InputRecord`, so yes, it should appear together with the rest in ctx.inputs(). It's either / or, though. Either you get data or you get the dummy message for a given input route. This can probably simplify a number of CompletionPolicy usecases as well, actually.

**Comment by shahor02** [comment]
Thanks, so, effectively, the only thing should be done on the raw-data processor side is to declare these inputs as ``Lifetime = Optional`` ? 
Does this cover also my question: if device has only 1 and subspec-wildcarded input defined, e.g.  ``Inputs{{"stf", ConcreteDataTypeMatcher{"ITS", "RAWDATA"}, Lifetime::Optional}}`` and no real data injected for given TF, will the dummy one inserted?

**Comment by ktf** [comment]
Yes, indeed, that would be sufficient, actually, no actual need to specify all the inputs, if we drop in any case the produced outputs before the STFS. The only issue I see is if something requires raw-data and non-raw-data / computed inputs, then one would need to extend the "expiration" logic to create the dummy message only when the actual raw-data arrives. Not for this PR, but I think it could be done.

Regarding the ConcreteDataTypeMatcher, I think one would need to add the case in

https://github.com/AliceO2Group/AliceO2/pull/4882/files#diff-cd9b976b28a2d9ef636dced782e89f70ee7b9975ff1df0386a4a2274878cad6eR228

which I think should be straightforward. However I propose we merge this as is, and then we iterate over the behaviour.

**Comment by shahor02** [comment]
OK, thanks. I think our common use case will be ConcreteDataTypeMatcher

**Comment by shahor02** [comment]
@ktf I've finally tested this feature, works fine creating a dummy message with `deadbeef` subspec and 0 payload. The only problem I see that it sets the `DataHeader.tfCounter` and `firstTFOrbit` at 0. 
They are not strictly needed for this message, but for consistency would be better to have them correct.

Below is a dump from the test where I drop in the raw-reader the detector data with `TF_id%3 == 0` and print DH of received inputs (apart from detector data proper I've requested `{FLP/DISTSUBTIMEFRAME/0}` to trigger the "delayed message" if TF data is missing.

````
[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#0 DH:[MFT/RAWDATA/0xdeadbeef] Part 0/1 of TF#0 1st_orbit:0 Payload 0
[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#1 DH:[FLP/DISTSUBTIMEFRAMEFLP/0x0] Part 0/1 of TF#0 1st_orbit:0 Payload 16

[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#0 DH:[MFT/RAWDATA/0x40] Part 0/1 of TF#1 1st_orbit:1952205804 Payload 30720
[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#1 DH:[FLP/DISTSUBTIMEFRAMEFLP/0x0] Part 0/1 of TF#1 1st_orbit:1952205804 Payload 16

[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#0 DH:[MFT/RAWDATA/0x40] Part 0/1 of TF#2 1st_orbit:1952205932 Payload 30720
[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#1 DH:[FLP/DISTSUBTIMEFRAMEFLP/0x0] Part 0/1 of TF#2 1st_orbit:1952205932 Payload 16

[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#0 DH:[MFT/RAWDATA/0xdeadbeef] Part 0/1 of TF#0 1st_orbit:0 Payload 0
[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#1 DH:[FLP/DISTSUBTIMEFRAMEFLP/0x0] Part 0/1 of TF#3 1st_orbit:0 Payload 16

[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#0 DH:[MFT/RAWDATA/0x40] Part 0/1 of TF#4 1st_orbit:1952206188 Payload 30720
[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#1 DH:[FLP/DISTSUBTIMEFRAMEFLP/0x0] Part 0/1 of TF#4 1st_orbit:1952206188 Payload 16

[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#0 DH:[MFT/RAWDATA/0x40] Part 0/1 of TF#5 1st_orbit:1952206316 Payload 30720
[3179018:mft-stf-decoder]: [15:31:39][INFO] Input#1 DH:[FLP/DISTSUBTIMEFRAMEFLP/0x0] Part 0/1 of TF#5 1st_orbit:1952206316 Payload 16
````

**Comment by ktf** [comment]
Ok. I need to propagate to `LifetimeHelper::dummy` the actual timestamp, not the internal counter. It should be quick.

**Comment by ktf** [comment]
See #5787.

**Pull request merged**
