### PR TITLE
TRD macros

### PR DESCRIPTION
**Pull request by jolopezl**
This PR does not contain code, it is intended just to keep a copy of a macro created to debug digits, and renames a OCDB2CCDB macro to add file formatting.

@bazinski, I moved OCDB2CCDB to OCDB2CCDB.C and added it to the exclusion list, so that we can see the formatting in macros.

### CODE REVIEW

**Comment by bazinski** [comment]
@jolopezl when I had it with a .C it would block the compile due to the aliroot dependency, so I took out the .C as its the logical place to have it. Maybe it will compile now. I actually have an update for that file but will do the pr tomorrow when I am more awake.

**Comment by jolopezl** [comment]
> @jolopezl when I had it with a .C it would block the compile due to the aliroot dependency, so I took out the .C as its the logical place to have it. Maybe it will compile now. I actually have an update for that file but will do the pr tomorrow when I am more awake.

`cmake/O2RootMacroExclusionList.cmake` makes the trick.

**Comment by bazinski** [comment]
@jolopezl ah shot on the fix.

**Comment by shahor02** [comment]
Hi @jolopezl 
Is there a reason to add the ``CheckDigits.C`` to the exclusion list? It has no any aliroot dependency and can be checked.
Cheers,
 Ruben

**Comment by jolopezl** [comment]
> Hi @jolopezl
> Is there a reason to add the `CheckDigits.C` to the exclusion list? It has no any aliroot dependency and can be checked.
> Cheers,
> Ruben

Could you please suggest me how? I just added there too let O2 compile. I copied other cmakes and didn't succeed.

**Comment by shahor02** [comment]
Hi
Just add in the macros dir. The CMakeLists.txt and add to it 
''''
o2_add_test_root_macro(CheckDigits.C
                       PUBLIC_LINK_LIBRARIES O2::TRDBase
LABELS trd)

and include this makefile to parent dir. makefile.

See for example Detectors/ITSMFT/ITS/macros/

Cheers
  Ruben

**Comment by jolopezl** [comment]
@shahor02, build/o2 test failed for something else. In build/o2checkcode/o2 all tests are ok for this macro. Can we merge this? If you think the macros should satisfy more requirements, please let me know before merging and I can adjust it (then it helps for newer macros).

**Pull request merged**
