### PR TITLE
DPL: warn if we are unable to forward on a channel

### PR DESCRIPTION
**Pull request by ktf**
Also printout an error if there was an error while forwarding.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr as discussed.

**Comment by davidrohr** [comment]
> @davidrohr as discussed.

thx, will you add the check of the zmq return value for the receive as well?

**Comment by ktf** [comment]
I have just added it. I am not sure what will happen on STOP, though. @teo will you tear down the channels on the RUNNING->READY transition?

**Comment by teo** [comment]
> I have just added it. I am not sure what will happen on STOP, though. @teo will you tear down the channels on the RUNNING->READY transition?

Not sure I understand the question. I only request the `STOP` transition, then it's up to FairMQ to do any channel magic it deems necessary. I don't push any properties nor perform any other call.

**Comment by davidrohr** [comment]
Let's merge this and see what happens. In principle, our stop timeout and EoS, which delays stop, should make sure that we don't get errors in case of a sane shutdown.

**Review by davidrohr — APPROVED** [review]

**Comment by ktf** [comment]
@teo I vaguely remembered that it was the plugin to create the channels, but apparently it's not. Maybe it was ODC only behaviour. Nevermind.

**Pull request merged**
