### PR TITLE
Recreate the MFT code sources; simple simulation and reconstruction, …

### PR DESCRIPTION
**Pull request by bovulpes**
…it works with MQ

### CODE REVIEW

**Comment by MohammadAlTurany** [comment]
Hallo Bogdan,
Is there a reason to have "AliceO2_TGeant3.mc_1ev_100mu.root" in repository? if not could you please remove it and push  your branch again.
best,
Mohammad

**Comment by bovulpes** [comment]
Hallo Mohammad, 

OK, root file removed, sorry. 

Bogdan. 


De: "Mohammad Al-Turany" <notifications@github.com> 
À: "AliceO2Group/AliceO2" <AliceO2@noreply.github.com> 
Cc: "Bogdan Vulpescu" <vulpescu@clermont.in2p3.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 2 Novembre 2016 11:29:09 
Objet: Re: [AliceO2Group/AliceO2] Recreate the MFT code sources; simple simulation and reconstruction, … (#173) 



Hallo Bogdan, 
Is there a reason to have "AliceO2_TGeant3.mc_1ev_100mu.root" in repository? if not could you please remove it and push your branch again. 
best, 
Mohammad

**Comment by MohammadAlTurany** [comment]
Merged

**Comment by MohammadAlTurany** [comment]
Merged

**Pull request closed without merging**
