### PR TITLE
Fix strangetrack labels reader, store them in AO2D

### PR DESCRIPTION
**Pull request by mpuccio**
The current dev has a broken data model, if strangeness tracking is enabled (it is not by default).﻿
This fixes it.

cc @jgrosseo @ddobrigk @fmazzasc

### CODE REVIEW

**Review by jgrosseo — APPROVED** [review]

**Comment by mpuccio** [comment]
@shahor02 if it is fine with you, I would merge this

**Review by shahor02 — APPROVED** [review]
Hi @mpuccio fine for me, but was modification of AOD agreed with @ddobrigk ?

**Comment by mpuccio** [comment]
Hi @shahor02, yes, as a matter of fact, he spotted the bug! But I let him comment

**Comment by ddobrigk** [comment]
Yes sure, I confirm this is fine (and in fact is a small but important bugfix to a previous PR that was merged). Thanks a lot @mpuccio for the quick action!

**Pull request merged**
