### PR TITLE
DPL: improve websocket encoding

### PR DESCRIPTION
**Pull request by ktf**
Apparently the "leak" which is observed comes from some weird allocation pattern from the metrics. If I pool allocations like done in this PR it seems to behave correctly also at low rates. Not sure what is going on, but this fixes the issue in my case.

### CODE REVIEW

**Comment by ktf** [comment]
Apparently the "leak" which is observed comes from some weird allocation pattern from the metrics. If I pool allocations like done in this PR it seems to behave correctly also at low rates. Not sure what is going on, but it fixes the issue in my case.

**Comment by ktf** [comment]
@shahor02 @davidrohr could you cross check?

**Comment by shahor02** [comment]
indeed, this eliminates the mem.leak.

**Comment by ktf** [comment]
Ok, great. Let me fix the test and then I will merge it.

**Comment by ktf** [comment]
While adapting the test I found a couple of issues with large frames. Most likely not actually used anywhere (but maybe in the remote GUI, which might explain some of the crashes we see in that PR).

**Comment by ktf** [comment]
Tested also with the FST and hyperloop. Merging.

**Pull request merged**
