### PR TITLE
Silence the most annoying unused variable

### PR DESCRIPTION
**Pull request by anerokhi**

### CODE REVIEW

**Comment by ktf** [comment]
Why not simply dropping writer (or even the line, assuming `cursor<T>()` does not have side effects)?

**Comment by anerokhi** [comment]
I don't know the details and I conservatively assumed that the result of `b.cursor<T>()` call should be alive till `b.finalize()` invocation.

**Comment by ktf** [comment]
Ok, but then one should assume `[[used]]`, no?

**Comment by anerokhi** [comment]
I'm not sure I understand what you mean

**Comment by ktf** [comment]
I meant that if you do not know if something has side effect, the correct way of marking it is to assume it's used. That said, it's just academic.

**Pull request merged**
