### PR TITLE
Revert "Update trackextension.cxx"

### PR DESCRIPTION
**Pull request by ktf**
Reverts AliceO2Group/AliceO2#5928

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo The change itself is probably fine, but this broke some of the hyperloop tests because it requires the `O2mccollisions` table. Was that expected?

**Comment by ktf** [comment]
@pzhristov

**Comment by pzhristov** [comment]
@ddobrigk, would you check the logic of this change? I propose to revert until the issues are fixed.

**Comment by ddobrigk** [comment]
Hi @pzhristov, I am already looking into how to fix PR #5928 . Please carry on with reverting this for the time being and then when I have the code with the new fixes I will make a separate, new PR. Thanks a lot!

**Pull request merged**
