### PR TITLE
first version of reduced table for CF

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@victor-gonzalez Could you let me know which additional fields you would need for the dpT task to use the same derived format?

**Comment by victor-gonzalez** [comment]
@jgrosseo For the time being the current ones will be enough. 
The idea is to use the filter task to populate the table which will feed different CF analysis? or the idea is that each CF analysis will use the filter task configured to its convenience to feed its analysis task?

**Comment by iarsene** [comment]
Hi @jgrosseo,
The o2 and macOS failures don't seem related to this commit. Is there anything else you or @victor-gonzalez  want to add?
Ionut

**Comment by victor-gonzalez** [comment]
@iarsene For the time being, not from my side
@jgrosseo In a long perspective and depending on the usage we probably will need to think on how to easy the analysis of systematics, I mean, flexibility in varying different cut selections

**Comment by jgrosseo** [comment]
I think it is fine for now, so we can test this on hyperloop.
@victor-gonzalez The idea is that we write a derived dataset with this, and use that as input which will (hopefully) need less resources. If one wants to test locally one can run this filter on the fly without writing out to a file.

**Comment by jgrosseo** [comment]
And yes, the idea is that it suits all of CF needs (or at least of one PAG)

**Pull request merged**
