### PR TITLE
DPL: hardened consumeWhenAny logic

### PR DESCRIPTION
**Pull request by ktf**
If there is no conditions at all, simply return Consume.

Wait for all conditions if they are missing.

Compared with the previous implemementation, this should force consumption for the case in which it is a non-condition input which is still missing. Not sure how that could happen, though.

### CODE REVIEW

**Comment by ktf** [comment]
@sawenzel @benedikt-voelkel this is the only thing I can think of. Do you know if empty messages have a special meaning for that particular workflow?

**Comment by benedikt-voelkel** [comment]
Maybe @davidrohr or @shahor02 can answer that?

**Comment by shahor02** [comment]
In the TPCDigitizerSpec code I don't see any special check for empty payload, but I am not sure such messages are expected at all.

**Comment by davidrohr** [comment]
> @sawenzel @benedikt-voelkel this is the only thing I can think of. Do you know if empty messages have a special meaning for that particular workflow?

@ktf : just for reference, I think empty messages can have a special meaning. E.g. if clusters are send as a vector, and empty message will represent 0 clusters.

**Comment by ktf** [comment]
By empty you mean empty payload? The cornercase here is with empty header, which I think it's not possible. I can reopen this in any case. It should not hurt.

**Comment by davidrohr** [comment]
sure, I meant empty payload.
No idea if empty headers can appear or not, but I do not see how.

**Pull request merged**
