### PR TITLE
DPL: allow only one remapping per path

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@chiarazampolli this should take care  of your request.

**Comment by chiarazampolli** [comment]
Thanks! Maybe I don't see it, but will there be an exception thrown?

**Comment by ktf** [comment]
https://github.com/AliceO2Group/AliceO2/pull/7995/files#diff-ea7315c16493f7af53ea03d6d7f9fa92ea90fb829ee2318054999c43ee56ec8bR143

**Comment by ktf** [comment]
I added a simple test.

**Pull request merged**
