### PR TITLE
Container for Alpide simulated response parametrization + data + test

### PR DESCRIPTION
**Pull request by shahor02**
Beginning of discussion here:
https://github.com/shahor02/AliceO2/commit/73a01d81f71e397bac58fb692b9c8b2122aef25f

@iouribelikov  @ktf @dberzano : before merging please check: 2nd commit contains text tables for response, 817 text files with total size of 6.5MB in O2/Detectors/ITSMFT/common/data which is installed to $O2_ROOT/share/Detectors/ITSMFT/data. 

Another question (sorry for my ignorance): what is the relation between
````sw/BUILD/O2-latest -> sw/BUILD/1d6dcf07de6e85638d56186ce4bbb4719413aea4```` 
and 
```
echo $O2_ROOT
/home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1
```
I would expect that after the build the executable testAlpideSimResponse will appear in ````$O2_ROOT/bin```` (where I see some tests) while it appears in ```` /home/shahoian/alice/sw/BUILD/1d6dcf07de6e85638d56186ce4bbb4719413aea4/O2/bin/testAlpideSimResponse```` i.e. in sw/BUILD/O2-latest. Is the $O2_ROOT just a selective copy of O2-latest/O2 ?

### CODE REVIEW

**Comment by ktf** [comment]
`$O2_ROOT` is the installation area, `sw/BUILD/O2-latest` is the build area. I think you forgot `make install`.

**Comment by shahor02** [comment]
@ktf : I am sure I do make install:
```
shahoian@alicers03:~/alice/sw/BUILD/O2-latest/O2$ make install
shahoian@alicers03:~/alice/sw/BUILD/O2-latest/O2$ sudo updatedb
shahoian@alicers03:~/alice/sw/BUILD/O2-latest/O2$ locate testAlpideSimResponse | grep "testAlpideSimResponse$"
/home/shahoian/alice/sw/BUILD/1d6dcf07de6e85638d56186ce4bbb4719413aea4/O2/bin/testAlpideSimResponse
```
but for testEPN (for example) I see
```
shahoian@alicers03:~/alice/sw/BUILD/O2-latest/O2$ locate testEPN | grep "testEPN$"
/home/shahoian/alice/sw/BUILD/1d6dcf07de6e85638d56186ce4bbb4719413aea4/O2/bin/testEPN
/home/shahoian/alice/sw/ubuntu1604_x86-64/O2/dev-1/bin/testEPN
```
I see that the testEPN is installed as O2_GENERATE_EXECUTABLE (in O2/Examples/flp2epn/CMakeLists.txt), does this mean that the tests are built but not installed by purpose?

**Comment by ktf** [comment]
Ah, wait, do you `install` the tests explicitly in your `CMakeLists.txt`? IIRC O2_GENERATE_TEST does not do it. @Barthelemy @dberzano do you remember if there was any particular reason for that (I guess not to pollute the path...).

**Comment by shahor02** [comment]
@ktf @dberzano : the test failed on testAlpideSimResponse because I need load at run time some data from from: 
```
std::string mDataPath  = "$(O2_ROOT)/share/Detectors/ITSMFT/data/alpideResponseData";
mDataPath = gSystem->ExpandPathName(mDataPath.data());
```
On my pc the test passes w/o problem, apparently the parsing of $O2_ROOT fails on the build server. 
Is $O2_ROOT defined there? For the mag.field initialization the data are loaded from (somebody suggested me to this)
```
std::string(gSystem->Getenv("VMCWORKDIR")) + std::string("/Common/maps/mfchebKGI_sym.root")
```
Using VMCWORKDIR looks quite custom solution. 

In general, the tests would be more useful if their output would be logged somewhere. Should I open an issue? (sorry if it is done but I can't find any reference to such log)

**Comment by shahor02** [comment]
@ktf : I copy/pasted the test installation from older examples, just put in ````O2/Detectors/ITSMFT/common/simulation/CMakeLists.txt````
```
set(TEST_SRCS
  test/testAlpideSimResponse.cxx
)

O2_GENERATE_TESTS(
  MODULE_LIBRARY_NAME ${LIBRARY_NAME}
  BUCKET_NAME ${BUCKET_NAME}
  TEST_SRCS ${TEST_SRCS}
)
```

**Comment by ktf** [comment]
I've exported O2_ROOT before running the tests. They should now succeed. We probably need a smarter mechanism, as discussed. To be pragmatic, I would commit the txt files (only 1MB altogether, when compressed), however we should discuss a better solution (CCDB?).

**Comment by ktf** [comment]
See https://github.com/alisw/alidist/pull/785 for the fix

**Comment by shahor02** [comment]
Thanks @ktf is the check status above updated (build/o2checkcode/o2-daq failed)?

**Comment by shahor02** [comment]
Hi @ktf , it seems your fix for $O2_ROOT being exported before the tests had no any effect
1) your merge did not trigger a new test.
2) I had to commit a fix which triggered a new test and if failed again, while locally test runs w/o problem.

Are you sure you patched version was picked by build server? Is it possible to add some verbosity, like 
````echo "O2_ROOT is set to $O2_ROOT" ```` 
before ````make test````? And surely, seeing the output of the tests would be the most useful.

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/787 should add the verbose output. Not sure why the rebuild is not triggered. @dberzano did you hardcode the hash for alidist?

**Comment by dberzano** [comment]
The tests should re-run soon, with always the most recent alidist.

**Comment by shahor02** [comment]
Hi @ktf, @dberzano , could this PR be merged also?

**Pull request merged**
