### PR TITLE
A concept for configurable parameters

### PR DESCRIPTION
**Pull request by sawenzel**
This commit introduces a concept for configurable parameters, which
means that they are class members which can be, fully-automatic, influenced
from a config file or by other means (command-line, distributed key-value stores).

The commit focuses on providing an automatic mechanism, so that the developer/user
merely needs to declare a parameter class in a special way:

```
class FooParam : public o2::conf::ConfigurableParamHelper<FooParam> {
  double getDensity() const { return mDensity; }
private:
  double mDensity = 1.1;
  int mNPlanes = 2;
  O2ParamDef(FooParam, "Foo")
};
```

After this, parameters Foo.mDensity, Foo.mNPlaces are automatically part of
a global parameter database (using boost property_tree) by means of an introspection
mechanism (using ROOT dictionaries).

Parameters can then be changed (textually) using the parameter database. Changes
are furthermore propagated to the actual C++ singletons of type FooParam.

In particular, the following works:
```
o2::conf::ConfigurableParam::setValue<double>("Foo.mDensity", 2.);
auto d = FooParam::Instance().getDensity(); // will now return 2. instead of default value 1.1
```

This mechanism is used to set/change these parameters from the command line.

As a first example, we provide the simulation cuts of the Hall volume as such parameters
and demonstrate that they can be changed from the simulation command line
```
o2sim -m HALL -n 1 --configKeyValue "HallSim.mCUTELE=10"
```
which should be useful for systematic studies.

Complementary info is available in a README in file `ConfigurableParam.md`.

### CODE REVIEW

**Comment by sawenzel** [comment]
For the record, this is about https://alice.its.cern.ch/jira/browse/O2-265, a feature that was asked several times in the WP12 meetings.

**Comment by awegrzyn** [comment]
Hi @sawenzel , I see that the code is simulation oriented but it covers some features that are already implemented in the configuration library - https://github.com/AliceO2Group/Configuration/tree/dev

Have you thought about using it or you prefer having your own implementation?

**Comment by sawenzel** [comment]
@awegrzyn : Of course, let's discuss and see what features I could use from your library. Note that the focus of this PR is the **automatic** generation of keys/values from C++ code.

**Comment by sawenzel** [comment]
added possibility to init from binary blobs coming from CCDB and to write such blobs.

**Comment by sawenzel** [comment]
Feedback from various developers was encouraging and I addressed first comments from @costing by coupling the parameters to CCDB.
Merging this now since it provides a reasonable "increment" for a demanded feature and to be able to collect feedback from actual use.

Follow up improvements will be collected / tracked in https://alice.its.cern.ch/jira/browse/O2-409.

**Pull request merged**
