### PR TITLE
LUT class for the barrel material budget

### PR DESCRIPTION
**Pull request by shahor02**
Initial commit of mat.bud. LUT classes.
see O2/Detectors/Base/test/README.md

To do: 
1) optimize segmentation for R>270 cm.
2) provide common memory pool to substitute current std::vectors (to be able to run on the GPU)

### CODE REVIEW

**Comment by shahor02** [comment]
@davidrohr I've converted the mat. LUT classes to flatObject. Note that I have to use ````Detectors/Base/include/flatObject.h```` (modified version of @sgorbuno 's class) which allows persistent objects.
I've masked the code which should not run on the GPU by ````#define _COMPILED_ON_GPU_ ````, please check if there is still a code which should be masked. 
There relevant classes are ````flatObject.h, MatCell.h, MatLayerCyl.h, MatLayerCylSet.h```` in ````Detectors/Base````. 

The manipulation with LUT object (MatLayerCylSet) are described in ````O2/Detectors/Base/test/buildMatBudLUT.C````, basically, the ````buildMatBudLUT()```` function creates a dummy (poor sampling) LUT and stores it in a root file, while the ````testMBLUT()```` shows how to retrieve and replicate the object.

Cheers,
 Ruben

**Comment by davidrohr** [comment]
@shahor02 @sgorbuno  : Hi Ruben, you have moved the flatObject to O2/Detectors/Base. Do you want to keep it there, or shall I update it in AliTPCCommon. If you want to move it to O2, I would simply add the old version to AliRoot such that the TPCFastTransformation works there.

**Comment by shahor02** [comment]
@davidrohr @sgorbuno In principle, I would prefer to keep in the O2, ideally all content of AliTPCCommon/Common should be in O2 and w/o TPC prefix, since it is not TPC specific.
BTW, @sgorbuno, right now the flat objects in TPCFastTransformation are not root persistent, and just rebasing them to my version of flatObject will be not enough: 

1. the mother object which has to be persistent should not have any persistent data members depending (or pointing) on the content of the flat buffer.
2. when the object is read from the file, it should be able to fix all internal pointers, see e.g. ````MatLayerCylSet::loadFromFile(...)````

**Comment by davidrohr** [comment]
@shahor02 : Hi Ruben, to mask code from GPU compilation, please use:
#ifndef GPUCA_GPUCODE
...
#endif

You should mask all code that uses new / delete, perhaps you can do this also in the flatObject.h (was not done before).

If you want to move the class to O2, please just go ahead with your PR. I'll then add a copy of the new class to AliTPCCommon which is used for compilation without O2.

**Comment by shahor02** [comment]
@davidrohr ok, done. What about ``std::memmove`` which should internally allocate the memory. I use it in ``flatObject::resizeArray`` for memory manipulation, but if needed, can write a custom version which handles overlapping arrays w/o extra allocations.

**Comment by davidrohr** [comment]
Yes, basically we need to mask everything that used std::
That would be the functions cloneFromObject and resizeArray.
But that is not a problem, as these are only used during creation and not on the GPU.

**Comment by shahor02** [comment]
I use resizeArray also in the moveBufferTo (you wrote you need it but not sure why it is needed on GPU).
Shall I mask the whole moveBufferTo together with resizeArray?

**Comment by davidrohr** [comment]
Hi Ruben,

the GPU part needs only setActual/setFutureBufferAddress.
you can mask the others.

**Comment by shahor02** [comment]
... also: the lookup algorithm (Ray.h) uses ``std::pair`` and ``std::array`` (not vector!) as well as the ``Point3D<float>`` from the ``Cartesian3D.h``. This also should be changed to simple arrays?

**Comment by davidrohr** [comment]
Hi Ruben,

In OpenCL these are not yet available, CUDA has limited support, don't
know for HIP.
But I guess for std::pair and std::array I can just implement simple
templated wrappers (might be convenient later anyway), so that should be
fine.

Cheers
David

**Comment by shahor02** [comment]
@davidrohr ok, thanks. I've eliminated dependence on Cartesian3D.h (``ROOT::Math::PositionVector3D<...``) in case of ``GPUCA_GPUCODE``

**Comment by davidrohr** [comment]
> @davidrohr @sgorbuno In principle, I would prefer to keep in the O2, ideally all content of AliTPCCommon/Common should be in O2 and w/o TPC prefix, since it is not TPC specific.
> BTW, @sgorbuno, right now the flat objects in TPCFastTransformation are not root persistent, and just rebasing them to my version of flatObject will be not enough:
> 
>     1. the mother object which has to be persistent should not have any persistent data members depending (or pointing) on the content of the flat buffer.
> 
>     2. when the object is read from the file, it should be able to fix all internal pointers, see e.g. `MatLayerCylSet::loadFromFile(...)`

@shahor02 : I do not fully understand why the mother object must not have any pointers to the flat buffer. One just needs to make sure that these are updated after setActual/futureBufferAddress, cloneFromObject and loadFromFile. Or do I miss something?

**Comment by shahor02** [comment]
@davidrohr root does not allow storing pointers on the simple types w/o specified dimension, i.e.
````
char* ptr0; // will produce error
````
but it is ok like:
````
int n1;
char* ptr1; //[n1] ok
````
One can use pointers on the objects with streamers, but in case of the flatObject derived classes we will write the data of these children objects as a blob of the flatBuffer, then the children objects will be stored serialized as separate objects. I.e. you cannot simply write the pointers as an abstract address.
So, the mother object should know how to rebuild everything just from the flatBuffer retrieved from the file + optionally some fixed size non-pointer data members.

Cheers,
 Ruben

**Comment by davidrohr** [comment]
@shahor02 : But you can just store them as
`char* ptr1; //!`
so root will ignore them, and then after loading the object from file, you have to reset all pointers anyway.

**Comment by shahor02** [comment]
PS: strictly speaking, one can store needed pointer data members as abstract addresses using custom streamers (e.g. writing the address as long64 and casting it back to the pointer at reading) but this is more headache than storing all needed info in the flatBuffer itself.

**Comment by davidrohr** [comment]
You do not need to use the streamer to restore the pointers. We can just store the mFlatBufferContainer (or Ptr) as
`char* ... //[mFlatBufferSize]`
and all others with `//!`
The setActualBuffer/setFutureBuffer function will need to restore all the ptrs anyway, no matter if they are in the mother object or in the flat buffer.
But if they are in the mother object you can reduce the number of indirections by 1 in some case, so I would not exclude this.

**Comment by shahor02** [comment]
> @shahor02 : But you can just store them as
> `char* ptr1; //!`
> so root will ignore them, and then after loading the object from file, you have to reset all pointers anyway.

@davidrohr : this is exactly what I said: one should not have persistent pointers except the flatBuffer itself! One could surely have auxiliary pointers which are lost at saving. But then, if you anyway can recover all info from the flatBuffer, why do you need extra pointers? It is easier to cast corresponding slot of the buffer itself...

**Comment by davidrohr** [comment]
OK, so we actually meant the same and can agree to have only pointers lost during saving.
I think if you have indirection, it is good to have the first pointer in the mother object. This reduces the max-level by 1, because you do not need to dereference the flatBuffer pointer as first level.

**Comment by shahor02** [comment]
OK, but in fact I do write the pointers on the child object as abstract addresses stored in the beginning of the ``mFlatBufferContainer``, at run-time they are available as pointers via ``reinterpret_cast<mother_layout*>(mFlatBufferPtr)`` where the ``mother_layout`` contains all pointer data members I need, and after the retrieving of ``mFlatBufferContainer`` from the file these pointers are fixed simply by offsetting them (by the difference between the stored 1st pointer and the retrieved 
 ``mFlatBufferContainer+fixed_offset_to_the_1st_pointer``).
As far as I can see, this does not imply extra dereferencing or an extra level of indirection.

**Comment by shahor02** [comment]
Hi, @dberzano 
after the alidist PR https://github.com/alisw/alidist/pull/1493 (which is supposed to allow to run CI tests with standard O2 environment) the tests ``O2/o2`` and ``o2/macos`` tests are ok, but on the ``o2checkcode/o2 `` it still fails due to the ````sh: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/O2/build_o2checkcode_o2-1/bin/o2sim: No such file or directory````. 
Do you understand what could be the reason? Aren't executables installed?

**Comment by dberzano** [comment]
I think I know the reason. I am in any case restarting all checks. Let's see if this fixes it.

**Comment by ktf** [comment]
Is this still ongoing?

**Comment by sawenzel** [comment]
The bug in MFT has been fixed. We should now be able to merge this.

**Comment by shahor02** [comment]
@sawenzel thanks! I saw. Since @davidrohr moved one of the files from this PR to https://github.com/alisw/alidist/pull/1499, let's wait until the latter is merged, then I'll adapt this PR.

**Comment by davidrohr** [comment]
@shahor02 : AliTPCCommon has been merged into O2, and I have added a dictionary for the FlatObject.

**Comment by sawenzel** [comment]
@dberzano : There is a new error in o2checkcode where it doesn't find an executable during ctesting. For the normal builds this works correctly.

**Pull request merged**
