### PR TITLE
DPL: do not allow for user printouts on --dds, --dump

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by davidrohr — APPROVED** [review]

**Comment by davidrohr** [comment]
thx, this looks good (without having tested it...)

**Comment by ktf** [comment]
@davidrohr I actually managed to come up with this. We can still do the file option, but this should avoid having it mandatory and keep it unixy. Maybe we should simply redirect all the output to stderr, if --dds / --dump is specified.

@knopers8 FYI.

**Comment by davidrohr** [comment]
I have just tried this with the full system test workflow and `--dds` option, and there are still `[INFO]` printouts, so apparently it is not working.

**Comment by ktf** [comment]
Is this with a merged workflow? I guess what might happen is that since only the last dataprocessor has --dds, only the last one does not print extra stuff on the command line... Can you put the TRD workflow last, just to check?

**Comment by davidrohr** [comment]
Yes, it is a merged workflow, but I cannot reorder it since then the outputs are used before they are defined.
I have added `--dds` to all executables, but that didn't change anything.

**Review by davidrohr — CHANGES_REQUESTED** [review]
Revoking approval since it is not working (don't know why, but it doesn't make sense to merge as is).
As was discussed, I think it would anyway be better to provide an option to write the DDS output to a file.

**Pull request closed without merging**
