### PR TITLE
Update AliRoot_Hijing example to run with o2-sim

### PR DESCRIPTION
**Pull request by preghenella**
Updating this example to run with `o2-sim` executable, now that we understood how to make it work like that.

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
Dear Roberto,
for me now it does not work but different way:
in serverlog :
o2-sim-primary-server-device-runner: symbol lookup error: /home/alla/aliO2/sw/ubuntu1910_x86-64/HepMC3/v3.0.0-git_d43693ce0e-3
/lib/libHepMCrootIO.so: undefined symbol: _ZN5HepMC5Setup22m_is_printing_warningsE

in workerlog:
[O2/latest-dev-o2 AliRoot/latest-qa-o2] /mnt/hdd/alla/hi/per/hijing $> more workerlog0 
o2-sim-device-runner: symbol lookup error: /home/alla/aliO2/sw/ubuntu1910_x86-64/O2/v1.2.0-1/lib/libO2Generators.so: undefined
 symbol: _ZTVN7Pythia811WeightsBaseE

**Comment by AllaMaevskaya** [comment]
Hello
with `alienv enter -w /home/alla/aliO2/sw/ O2/latest-dev-o2` 
`o2-sim-primary-server-device-runner` works and produce usual output 
but  with 
`alienv enter -w /home/alla/aliO2/sw/ O2/latest-dev-o2,AliRoot/latest-master-o2`
it prints error
```
> o2-sim-primary-server-device-runner
o2-sim-primary-server-device-runner: symbol lookup error: /home/alla/aliO2/sw/ubuntu1910_x86-64/HepMC3/v3.0.0-git_d43693ce0e-3/lib/libHepMCrootIO.so: undefined symbol: _ZN5HepMC5Setup22m_is_printing_warningsE
```

I expected the output to be the same in both environments.

**Comment by preghenella** [comment]
hi @AllaMaevskaya ,
it is not clear to me why the example does not for for you.
It works in my case and @sawenzel also tested it and could run it.

**Comment by sawenzel** [comment]
Could be different link behaviour across plattforms used.

**Comment by AllaMaevskaya** [comment]
Is it possible to run it on lxplus? How to set alienv ?

**Comment by sawenzel** [comment]
I doubt that Hijing (or AliRoot compiled with defaults-o2) is available on cvmfs.

**Comment by preghenella** [comment]
@AllaMaevskaya 
on which system are you?

**Comment by AllaMaevskaya** [comment]
Ubuntu 19.10

**Comment by preghenella** [comment]
uhm... @sawenzel tested it on Ubuntu (I guess it was 18.04) and it worked for him.

**Comment by sawenzel** [comment]
I tested on CC7 + Ubuntu18.04. I would recommend sticking to the current long term support version of Ubuntu (or even better use CC7 which is the production environment)

**Pull request merged**
