### PR TITLE
Hcone geometry

### PR DESCRIPTION
**Pull request by carlos-soncco**

### CODE REVIEW

**Comment by bovulpes** [comment]
HI @carlos-soncco 
Something is wrong with this pull request...

**Comment by bovulpes** [comment]
@carlos-soncco @frmanso I think it is better to close this PR, because it triggers too much activity on the checks.

**Comment by bovulpes** [comment]
I am closing the PR, we will check with @carlos-soncco and @frmanso what is wrong.

**Comment by carlos-soncco** [comment]
ok

**Pull request closed without merging**
