### PR TITLE
DPL: Fix memory leak in variant_helper

### PR DESCRIPTION
**Pull request by ktf**
DPL: Fix memory leak in variant_helper

### CODE REVIEW

**Comment by ktf** [comment]
@benedikt-voelkel can we have a +all?

**Comment by benedikt-voelkel** [comment]
Sounds good!
I will update the workflow so that we will have some better usage by Monday, including an `+async-label all`

**Comment by martenole** [comment]
Unfortunately the CCDB backend is still leaking memory at the same rate as before with this PR included

**Comment by ktf** [comment]
Mmmm... did you actually include the PR separately? For some reason is not yet merged, even if I though I did click on "merge".

**Comment by ktf** [comment]
Now merged.

**Pull request merged**
