### PR TITLE
TPCClusterFinder: Fix how to determine if a sector is empty.

### PR DESCRIPTION
**Pull request by fweig**
This PR fixes an issue where an entire sector would be incorrectly treated as empty when only the last fragment was empty.

@davidrohr @shahor02 MC labels look ok now on your testdata, Ruben. Could you double check if the issue is gone? This hopefully fixes the pp data as well, David...

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @fweig, 

Thanks! The labels are ok now. 

A question (probably to @davidrohr) unrelated to this problem: 
I see ~30% less clusters from CA clusterer, apparently the difference being mostly a junk, since the difference in number of tracks is ~3-10% depending on the selection. Still, this difference is significant, and cannot be attributed only to more efficient track-segment merging with better CA clusters:

In the reconstruction of the same cosmic data done with ``--no-ca-clusterer`` I see:
````
[1142404:tpc-tracker]: [21:08:17][INFO] Event has 367633 TPC Clusters, 0 TRD Tracklets
[1142404:tpc-tracker]: [21:08:18][INFO] found 1579 track(s)
````
with ca-clusterer:
````
[1143043:tpc-tracker]: [21:08:56][INFO] Event has 26545 8kb TPC ZS pages, 2222100 digits
[1143043:tpc-tracker]: [21:09:04][INFO] Event has 255128 TPC Clusters, 0 TRD Tracklets
[1143043:tpc-tracker]: [21:09:04][INFO] found 1423 track(s)
````
The 10% tracks difference is further reduced to 5% if I select only cosmic tracks (``GetTrackLabel()==0``, all others are low-pt secondaries from material). Furthermore, if I count the number of ``TPCTracksMCTruth.GetEventID()`` with at least 1 track with ``GetTrackLabel()==0`` reconstructed (in average I expect 2 tracks corresponding to top/bottom legs), I see  3% difference (i.e. the tracker did not find a high pT track with CA-clusters while it did with old one).

In case of pp MC (100 events) it shows the same difference in clusters and again 3% in number of tracks.
``--no-ca-clusterer``:
````
[1150560:tpc-tracker]: [21:21:01][INFO] Event has 999014 TPC Clusters, 0 TRD Tracklets
[1150560:tpc-tracker]: [21:21:01][INFO] found 6285 track(s)
````
with ``ca-clusterer``:
````
[1153194:tpc-tracker]: [21:23:31][INFO] Event has 24540 8kb TPC ZS pages, 6076794 digits
[1153194:tpc-tracker]: [21:23:33][INFO] Event has 743278 TPC Clusters, 0 TRD Tracklets
[1153194:tpc-tracker]: [21:23:34][INFO] found 6080 track(s)
````
Again, the difference is not only due to the better merging with CA clusters: if I plot number of tracks with pT>1 per event, I see systematically more tracks with old clusterer (red is for the old clusterer):
````
tree->Draw("TPCTracksMCTruth.getEventID() >> hho(100,0,100)", "abs(TPCTracks.getQ2Pt())<1")
````
cmptr_pp100


From scanning the mc labels the excess tracks look to be unique ones rather than badly merged clones of others. Although, this excess is mostly due to the short tracks:
ncl_pp100

Are the thresholds of CA clusterer simply higher, making it less efficient (but cleaner), or there is something else?

Cheers,
 Ruben

**Comment by davidrohr** [comment]
Thx @fweig , fix looks totally correct.

@shahor02 I would say that by design the ca clusterer is more stable and cleaner, while the old clusterer is more sensitive. The new clusterer has noise filter / proper cluster splitting, while with the old clusterer simply every local peak becomes a separate cluster. Seeing less clusters with the new clusterer is totally expected and intended.
Just to remark, using the old clusterer as is would be infeasible, since we could not afford to store the excess of clusters, and also it breaks in high density Pb-Pb environments.
I think when we switched to the new clusterer, I was only / mostly comparing Pb-Pb data against the old one, where the new one was generally better.
There are actually several parameters / thresholds which can be tuned. We optimized that slightly with @fweig , but basically the settings come from what I found as optimum for the Run 2 HLT clusterizer for Pb-Pb (module factor 2 in t-dimension for different sampling frequency).
So probably this can be tuner further, in particular for cosmics / low-IR pp where the density is much lower. There we can certainly reduce some thresholds to find more clusters.

One should also mention that when we did the switch, there was some problem in the TPC digitization, which was quite noise, and the old clusterer would have in average > 2 hits per track / row even at Pt > 1 GeV. Consequently the tracking quality was very poor, since the trajectory was going zick-zack inside this "cloud" of clusters. Perhaps this has improved in the meantime, but the new clusterer is just much more stable.

> From scanning the mc labels the excess tracks look to be unique ones rather than badly merged clones of others. 

I don't understand what you mean wrt. clones. Seeing more tracks with the old clusterer is also expected due to a much higher clone rate. The dominant effect when I checked was that the track merging did not work properly, due to the tracks being distorted by having 2 clusters in the same row, and then merging across sectors for higher pt tracks would often fail. To check if we really miss tracks with the new clusterer, that could be found with the old one, we have to check MC labels. Your line `tree->Draw("TPCTracksMCTruth.getEventID() >> hho(100,0,100)", "abs(TPCTracks.getQ2Pt())<1")` is not checking for clones, if I understand correctly?

> if I count the number of `TPCTracksMCTruth.GetEventID()` with at least 1 track with `GetTrackLabel()==0` reconstructed (in average I expect 2 tracks corresponding to top/bottom legs), I see 3% difference (i.e. the tracker did not find a high pT track with CA-clusters while it did with old one).

This comparison should factor in the MC labels. I agree a 3% difference is significant. We should have a look where this comes from.

> Although, this excess is mostly due to the short tracks:

I don't really understand what you are plotting in the last figure. In general, you would expect shorter tracks with the old clusterer and longer with the new one, since with the old one, you will have more unmerged segments, and also the segments themselves might be shorter when the track fit fails after going too much zick-zack.

If there are really tracks missing, I think we should try to find the systematic that makes us miss these tracks with the new clusterer, looking at individual cases.

**Comment by shahor02** [comment]
Hi @davidrohr 

 
> > From scanning the mc labels the excess tracks look to be unique ones rather than badly merged clones of others.
> 
> I don't understand what you mean wrt. clones. Seeing more tracks with the old clusterer is also expected due to a much higher clone rate. The dominant effect when I checked was that the track merging did not work properly, due to the tracks being distorted by having 2 clusters in the same row, and then merging across sectors for higher pt tracks would often fail. To check if we really miss tracks with the new clusterer, that could be found with the old one, we have to check MC labels. 

I meant I could expect seeing more tracks with old clusterer because 2 segments of the same track were not merged. This is not the case. 

> Your line `tree->Draw("TPCTracksMCTruth.getEventID() >> hho(100,0,100)", "abs(TPCTracks.getQ2Pt())<1")` is not checking for clones, if I understand correctly?

It does it for cosmics, where I expect to have 1 or 2 tracks with pT>1. If I see in some EvntID bin >2 entires, this means that there was a clone. And indeed, with old clusterer I have bit more events with 3 or 4 tracks reconstructed, which means worse cluster quality. But I also see events where with new clusterer nothing was found while with old one at least 1 track was seen.

In pp, with many tracks per event, it just shows the excess of non-loopers per event. As I wrote, I dumped the labels for these events with excess tracks and I don't see repeating labels, therefore the excess is not caused by bad merging.


> I don't really understand what you are plotting in the last figure. In general, you would expect shorter tracks with the old clusterer and longer with the new one, since with the old one, you will have more unmerged segments, and also the segments themselves might be shorter when the track fit fails after going too much zick-zack.
> 
The plot shows the number of clusters per tracks for those with pt>1. As you can see, there are more small-number of clusters tracks but also the long track peak has more clusters with old clusterer. I would say this simply tells about the higher eff. of the old one (at price of worse quality)

**Comment by davidrohr** [comment]
> I meant I could expect seeing more tracks with old clusterer because 2 segments of the same track were not merged. This is not the case.

This is what I didn't understand. How do you know that this is not the case?

> > Your line `tree->Draw("TPCTracksMCTruth.getEventID() >> hho(100,0,100)", "abs(TPCTracks.getQ2Pt())<1")` is not checking for clones, if I understand correctly?
> 
> It does it for cosmics, where I expect to have 1 or 2 tracks with pT>1. If I see in some EvntID bin >2 entires, this means that there was a clone.

Or, after reading again, so you refer to exactly those cases were old clusterer finds 1, new clusterer finds 0 tracks, and the same with 2/1. Then I see. apparently we are loosing some tracks. I'll have a look.

> The plot shows the number of clusters per tracks for those with pt>1.

So there are no additional cuts based on MC label? Ok, then indeed there are also some more longer tracks with the old clusterer, which is kind of unexpected. Thinking about it again, there is one more difference: The new clusterer runs with zer-suppression, while the old one doesn't. That can obviously also make a difference. I'll try if that makes a difference.
Just in case you want to give it a shot: you should be able to turn it off with `--configKeyValues "GPU_rec.tpcZSthreshold=0"` if you use the on-the-fly encoding in the tpc-reco-workflow (although I have to admit I never verified that it works. If you want to test it with the digits to zsraw encoder, you have to read the code, it doesn't read the settings!)

**Comment by davidrohr** [comment]
Btw, what I wrote was a bit overcomplicated, you can just use `--no-tpc-zs-on-the-fly`, then it is the exact same input for both clusterizers.

**Comment by shahor02** [comment]
@davidrohr thanks for explanations, will try clusterer options later. 
Here is the example of what I meant before in case of pp data: I dump for both cases tracks above 1GeV for particular mcLable.getEventID() (e.g. first event 7 of https://user-images.githubusercontent.com/7382029/107130466-fe5ca180-68cd-11eb-840a-ef58532175cc.gif where the different is seen), 
````
tpcrec->Scan("TPCTracksMCTruth.getTrackID() : TPCTracks.getNClusters()","TPCTracksMCTruth.getEventID()==7 && abs(TPCTracks.getQ2Pt())<1")
````
sort them in track label and compare. Below is edited/commented comparison of dumps:
````
    OLD                      |         CA_TRACKER
                             |
MC_TrackID   NClus Comment   |   MC_TrackID   NClus  Comment
 931         137             |     931         137  
 953         123             |     953         110  
1085         135             |    1085         132  
1086          83             |    1086          45  
                             |    1086	        38   clone 
1087          72             |      	             not found
1090         127             |    1090         127  
1198          45             |      	             not found
1199         138             |    1199         137   
1201         105             |    1201         111  
1203          63             |    1203          62  
1203          46   clone     |    1203          58   clone 
1270          48             |    1270          52  
1270          56   clone     |    1270          57   clone 
1271         144             |    1271         138  
1272         136             |    1272         135  
1311         113             |    1311         115  
1313          79             |    1313          83  
1317          48             |      	             not found
1376         135             |    1376         123  
1755          29             |      	             not found
````
So, with old clusterer 20 tracks were found, of which 18 unique labels. With CA_tracker 17 were found, with 14 unique labels only.

**Comment by davidrohr** [comment]
ok, thx, now I understand. So this is absolutely not what I had expected, in particular there should be less clones with the ca clusterer. I'll have a look. Do you have the pp and cosmic dataset somewhere? I'll simulate some myself, but just for reference.

One more point that came to my mind: The fact that the tracks have more hits with the old clusterer is also because the old clusterer has 2 hits per track and row more often, and the track will pick up both.

**Pull request merged**
