### PR TITLE
ALICE3toAO2D macro for tests

### PR DESCRIPTION
**Pull request by ddobrigk**
Thanks a lot to @mconcas for the help with CMake business!

### CODE REVIEW

**Comment by ddobrigk** [comment]
Eh, this is now a bit confusing. I have managed to compile and use everything in my local copy on macOS, so I am not sure what the problem is now. I will try a bit more... :-(

**Comment by ddobrigk** [comment]
@mconcas @ktf @aalkin not sure who has privileges to approve here? This is ready, I think... Thanks!

**Comment by ktf** [comment]
Apparently neither @qgp nor @marcovanleeuwen had write permission so they could not be added as reviewers. Fixed.

**Comment by ddobrigk** [comment]
Thank you, @ktf !

**Pull request merged**
