### PR TITLE
DPL: handle spurious messages when in READY state

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by knopers8** [comment]
It seems to work as expected in my laptop reproducer

**Comment by ktf** [comment]
Actually, I think you need 36f6fe1be39c0d161d0f1b2153a4e5dd3464a324 as well. Are you sure your reproducer worked?

**Comment by knopers8** [comment]
I think indeed my reproducer does not work anymore and we might need to try in combination with ECS. I propose we merge and see it on staging once it's there.

**Comment by ktf** [comment]
Ok, in any case it should be enabled only when the associated option is used.

**Pull request merged**
