### PR TITLE
DPL: Task EndOfStream example

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by shahor02** [comment]
Hi, @ktf 
Thanks, right now most of DPL devices using Task mechanism actually don't inherit from the framework::core::Task, so the compilation breaks since the base ``Task::endOfStream(..)`` is not inherited by them. We 1st need to merge [this](https://github.com/AliceO2Group/AliceO2/pull/2484).

**Comment by shahor02** [comment]
@ktf I've [adapted](https://github.com/shahor02/AliceO2/commit/b3b6e8c5947f7c4f286545c51bce638dc1579041) all devices in the FIT recoflow to call 
````
pc.services().get<ControlService>().endOfStream();
pc.services().get<ControlService>().readyToQuit(QuitRequest::Me);
````
on the completion (for inputless readers: in the end of the run(), for devices with input and output:  in the ``void endOfStream(EndOfStreamContext& eos)`` method).

Works fine my devices: ``run(..)`` not called once ``endOfStream()`` was called, but the workflow still does not quit due to the ``internal-dpl-global-binary-file-sink`` waiting for the input, although its all input devices have already called ``endOfStream()``. Don't you need to add this hook also to CommonDataProcessors?

Cheers,
 Ruben

**Comment by ktf** [comment]
79094bd32f8683bad1b2572f87f3346e42ace8f3 should avoid any change and still allow generic tasks to be used. We can do the same to avoid the dummy init.

**Comment by ktf** [comment]
ok i will merge asap

**Pull request merged**
