### PR TITLE
O2-1702 [math_utils] refactor and extend o2::mathutils

### PR DESCRIPTION
**Pull request by MichaelLettrich**
This PR refactors the MathUtils library in O2. It contains functional extensions to MathUtils and a mere clean up and unification effort to homogenize the structure of the library without altering functionailty. The commits are structured in a way that they allow to trace and comprehend the the changes.

What has been done:
* Cleans up the patchwork of namespaces inside the `MathUtils` library and unifies them to `math_utils`. 
* Enforces the O2 styleguide and naming conventions in `MathUtils`.
* Turns classes and functions into templates to make them accept both single and double precision floating point inputs. Also add a specifically named `float` version of functions to match STL behavior. Introduce type aliases to `float` and `double` version of classes.
* Enables the double spezialization of `TrackParametrization` and `TrackParametrizationWithError`.

### CODE REVIEW

**Comment by MichaelLettrich** [comment]
Apparently my proposed changes also affect the `QualityControl` package. How would we proceed with this? @Barthelemy

**Comment by davidrohr** [comment]
Apparently this fails in dependent packages, in this case QualityControl.
Can you try locally to build O2Suite instead of O2, that should show you all dependent build failures.
Then we need PRs for the other packages as well.
Either we need to merge them synchronously manually, or you can update QC in a way that is compatible with the old and the new O2, then we first merge QC, then the O2 PR, then we remove the compatibility to the old O2 from QC.

**Comment by MichaelLettrich** [comment]
@davidrohr thanks for the info. I'll look into that. Would be good though to get feedback from the major stakeholders  @shahor02 , @sawenzel  and @wiechula  who's code in `math_utils` I touched directly beforehand.

**Comment by davidrohr** [comment]
Technically this looks all ok and the changes to the GPU part seem good.
We should still test the compilation on the GPU, unfortunately the GPU still currently breaks in CMake for whatever reason. I can test this locally later.

One other point: What I do not really like is that all math functions now expose a float and a double interface, while you have the float only variant with the f suffix. But this can lead to calling the double version unintentionally.

I am not really sure what is the best solution. We discussed converting the namespace into a static class before. Perhaps we could do something like a `_t` suffix for the templated version, a `d` suffix for a double version, and the normal version without suffix would stick to float. What do you think? Then all templated code would explicitly call the _t with the correct parameter explicitly. But for all other code nothing would change.

**Review by wiechula — DISMISSED** [review]
Looks fine for me!

**Comment by MichaelLettrich** [comment]
@davidrohr thanks for checking. Indeed the problem for accidentally using the `double` version exists.  I don't have enough experience as a software architect and library developer to judge which solution is the best so good you bring it up. 
The reasons why I chose this is as follows:
* The design is consistent with the STL and  C++ as a language that treats all fp literals as `double` by default and requires specifically adding a trailing `f` to treat data as `float`. Same for functions in the STL. (Bulk renaming has been done in the code to not change semantics)
* I personally would exclude the static class as the namespace of `math_utils` spans quite a lot of classes and functions. If we want consistent handling of all of them we either need to have quite a big static _god class_ where everything is put or we accept fragmenting the namespace again. 
* The `_t` suffix is generally used for types within the STL , so that would be confusing I think. Using a facade pattern and providing  `d` sufix for `double` and no suffix for `float` could be an idea to reduce accidental calls of the double precision version with other specializations anyhow being undesirable. The templates are hidden away in the nested `detail` namespace  and can be referenced if truly needed (e.g. in template classes).

**Comment by davidrohr** [comment]
OK, if you say switching to a static class has implications at too many places let's drop that.
I don't say the suffix should be `_t`, basically it could be anything.

In my opinion I would then add whatever suffix for the templated one, `d` for double and no suffix for float.
I agree that is not according to STF, which uses `f` for float, but I believe it suits our use case better.
We can also add an additional `f` variant for float. I am just against making the default having a template version with double.

**Comment by Barthelemy** [comment]
Hello, 
The error appears in the ITS module. @JianLIUhep could you have look ? I can also help if needed. Just let me know.

**Comment by JianLIUhep** [comment]
Hi @Barthelemy, I am going to update it.

**Review by shahor02 — DISMISSED** [review]
@MichaelLettrich Looks ok to me. I also think that `d` version for doubles and not special flagging for floats should be the safest. Could you prepare the fix for the QC, looks like only few methods in the ITS code are concerned. Once you can build QC locally, I would open PR for QC, bump it to higher version then merge this PR.

**Comment by JianLIUhep** [comment]
QC PR opened: https://github.com/AliceO2Group/QualityControl/pull/518. Compiled locally with this PR. @Barthelemy

**Comment by davidrohr** [comment]
@MichaelLettrich : Could you temporarily in this PR add an alias of the namespace utils to math_utils. This will create backward compatibility. Then we can merge this PR without adjusting QC.
Afterwards we update QC and when we remove the alias in O2.
The advantage is that during now time we will break the CI and we will not affect other PRs.

**Comment by Barthelemy** [comment]
@JianLIUhep ok, thanks. will it also work with the previous O2 ? otherwise we will have a deadlock of PRs.

**Comment by JianLIUhep** [comment]
unfortunately, it won't. @Barthelemy

**Comment by MichaelLettrich** [comment]
@davidrohr @shahor02 : Thanks for the discussion and the feedback. I will ensure single precision is the standard and do the fixes.
@Barthelemy @JianLIUhep : I try to do as @davidrohr  suggested with the namespace aliasing and ensure it compiles both before pushing again. Then you can do the changes and signal me to remove the alias in a subsequent PR. Thank you so much for your swift reply and your willingness to do the necessary adaptations. I really appreciate it!

**Comment by Barthelemy** [comment]
@MichaelLettrich thank you it sounds good.

**Comment by davidrohr** [comment]
> @JianLIUhep ok, thanks. will it also work with the previous O2 ? otherwise we will have a deadlock of PRs.

For reference, it is not backward-compatible, AliceO2Group/QualityControl#518 currently fails, but as @MichaelLettrich agreed we can use namespace aliasing and then merge one after another keeping the CI green.

**Comment by MichaelLettrich** [comment]
@shahor02 @davidrohr this should be the final form as far as I am concerned if the CI passes.

**Comment by shahor02** [comment]
@MichaelLettrich Thanks! Once the tests are passed it can be merged, the GPU CI again fails due to the mem. overrun.

**Review by davidrohr — APPROVED** [review]

**Comment by davidrohr** [comment]
@ktf @TimoWilken : Could you check what is the problem with the CI here? o2checkcode is failing without build log (also in other PRs) and O2/o2 is not failing in this PR also with OOM killer (like the GPU CI does regularly).

**Comment by davidrohr** [comment]
Btw, the fact that the GPU CI is red is quite annoying since it makes people ignore it. This PR breaks GPU compilation in several places...
I am testing the checkcode/o2 and the O2/o2 manually, then I'll force merge it, then I'll clean up the GPU stuff in a follow-up PR.
But we should really try to get the CI in a working state again. It has been like this for weeks.

**Comment by ktf** [comment]
We are working on this as we speak. The promised "consolidation" of the CI has started but there were some unforeseen errors when we deployed to slc7.

**Comment by ktf** [comment]
For the record, there is genuine errors in build/O2/o2 as well:

```
/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/QualityControl/v1.4.0/v1.4.0/Modules/ITS/src/ITSRawTask.cxx: In member function 'virtual void o2::quality_control_modules::its::ITSRawTask::initialize(o2::framework::InitContext&)':
/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/QualityControl/v1.4.0/v1.4.0/Modules/ITS/src/ITSRawTask.cxx:101:49: error: 'o2::TransformType' has not been declared
   geom->fillMatrixCache(o2::utils::bit2Mask(o2::TransformType::L2G));
                                                 ^~~~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/QualityControl/v1.4.0/v1.4.0/Modules/ITS/src/ITSRawTask.cxx: In member function 'virtual void o2::quality_control_modules::its::ITSRawTask::monitorData(o2::framework::ProcessingContext&)':
/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/QualityControl/v1.4.0/v1.4.0/Modules/ITS/src/ITSRawTask.cxx:269:49: error: 'o2::TransformType' has not been declared
     gm->fillMatrixCache(o2::utils::bit2Mask(o2::TransformType::L2G));
                                                 ^~~~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/QualityControl/v1.4.0/v1.4.0/Modules/ITS/src/ITSRawTask.cxx:270:11: error: 'Point3D' does not name a type; did you mean 'Point_t'?
     const Point3D<float> loc(0., 0., 0.);
           ^~~~~~~
           Point_t
/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/QualityControl/v1.4.0/v1.4.0/Modules/ITS/src/ITSRawTask.cxx:271:41: error: 'loc' was not declared in this scope
     auto glo = gm->getMatrixL2G(ChipID)(loc);
                                         ^~~
/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/QualityControl/v1.4.0/v1.4.0/Modules/ITS/src/ITSRawTask.cxx:271:41: note: suggested alternative: 'log'
     auto glo = gm->getMatrixL2G(ChipID)(loc);
                                         ^~~
                                         log
Scanning dependencies of target QcMFT

```

**Comment by davidrohr** [comment]
Okay cool, thx. Would be really good if we can get this back in a decent shape soon :) If there is anything I can do or test please let me know.

**Comment by davidrohr** [comment]
Indeed, apparently the new version triggers more issues in QC due to moving namespaces etc. Will have a look how to fix this temporarily in O2 until  AliceO2Group/QualityControl#518 is extended and merged.

**Comment by davidrohr** [comment]
Tested locally and works except for the problem in QC, which is circumvented here: #4662 
merging

**Comment by davidrohr** [comment]
PR to revert compatibility changes in #4663 as soon as QC is updated.

**Comment by MichaelLettrich** [comment]
> 
> 
> Btw, the fact that the GPU CI is red is quite annoying since it makes people ignore it. This PR breaks GPU compilation in several places...
> I am testing the checkcode/o2 and the O2/o2 manually, then I'll force merge it, then I'll clean up the GPU stuff in a follow-up PR.
> But we should really try to get the CI in a working state again. It has been like this for weeks.

@davidrohr which parameters should I have used to build O2 to see these broken compilations and tests? I was Compiling and running tests locally with CUDA support at least. But I guess that didn't show issues in the OCL and HIP code.

**Comment by davidrohr** [comment]
@MichaelLettrich : For the QC stuff you would need to build O2Suite instead of O2.
For the other GPU backends, you can enable them in cmake with `-DENABLE_CUDA=ON -DENABLE_HIP=ON -DENABLE_OPENCL1=ON -DENABLE_OPENCL2=ON` but HIP will always fail at the moment due to an internal compiler error.
You can use the davidrohr/slc8-builder-gpu docker container to have a setup with opencl and hip compilers installed.

**Pull request merged**
