### PR TITLE
TPC Cluster Finder cleanup

### PR DESCRIPTION
**Pull request by fweig**
Changes in this pull request:
* Port cluster finder from opencl c to c++
* Delete leftover code from the standalone version
* Move cluster finder into namespace o2::gpu
* Fix divergent clusters between cpu and gpu version
* Fix segfault in cpu version

@davidrohr

### CODE REVIEW

**Comment by davidrohr** [comment]
@fweig : just some information on the CI checkers:
- Codacy usually gives some general C++ advise, and it is optional. In your case, you can ignore it.
- Travis checks for clang-format conformality and doxygen. Your PR does not comply to the clang-format rules. We use git clang format. To format your code yourself, you can use "git-clang-format origin/dev". If you click on details and then on the clang job, the console output will also display a patch, which you can simply apply. No idea why doxygen failed for your PR, probably a problem of the C.I. itself.
- The build/O2/gpu builder builds O2 for CPU, CUDA, HIP, and OpenCL 1. In your case, the HIP version seems to break. I can have a look on the weekend what is the cause, or you can try yourself. At the moment, we are a bit picky about the HIP setup. I think ideally you would just use the docker container that we use for the CI to test HIP: alisw/slc7-gpu-builder. But it might be a bit time-consuming to set up and run it in there.
- O2/o2 and o2/macos test CPU compilation on Linux and MacOS and run all ctests.
- o2codeckecker runs clang-tidy with some additional custom checks and will report violations, which must be fixed.

**Comment by fweig** [comment]
@davidrohr I'll have a closer look tomorrow. But it looks like my cern account was disabled because i haven't used it in so long. So i can't view any of the build logs. :(

**Comment by davidrohr** [comment]
@fweig : I'm sending you the logs via mail.
There is no a collision with your branch wrt. origin/dev. Could you please rebase?

**Comment by davidrohr** [comment]
The o2 checkcode failures are unrelated... all PRs are failing there.

**Comment by davidrohr** [comment]
Fix here #2738 

These are quite some changes. At first glance it looks very good, but I need some time to review and test it.

**Comment by davidrohr** [comment]
- Code checker warnings are unrelated. and have already been addressed in an independent PR.
- I see some new warnings with GCC 9, but will fix then in another independent PR
- I don't see any side effects on the remaining GPU code, no problem on this side.
- I still see some differences between clusters reconstructed on GPU and CPU. Needs some more investigation. Number of cluster seems to be the same, but there seems to be some kind of rotation that wasn't there before. Also, number of cluster marked as adjacent in the tracking differs. Don't understand why yet, perhaps different flags?
- Merging this now anyhow, to avoid diverging code branches, in particular for upcoming AMD fixes to HIP.

**Pull request merged**
