### PR TITLE
Reduce peak memory usage of TrackerTraits::findTracks

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 @mpuccio  @mconcas maybe I am missing something, but why not the following approach? It should reduce the peak memory usage (right now you keep around tracks{1,nThreads} until the end and you do an extra copy).

**Review by davidrohr — APPROVED** [review]

**Comment by mpuccio** [comment]
Looks good to me, thanks. I am not sure it will solve the issue but surely it does not hurt.

**Review by mconcas — APPROVED** [review]

**Comment by ktf** [comment]
@mpuccio agreed. This will only reduce peak memory usage by 6GB in the workflow I saw, which might or might not be enough and it's for sure only a transient peak. Besides that, it avoids one copy of the data, which does not harm as well.

The other thing which I noticed is that there is a fixed number (MaxClusters) of entries for the TrackITSExt::mIndex. As far as I can tell, this could account for up to 25% of the size of the "tracks" vector (since sizeof(TrackITSExt) is 260 bytes) . Maybe one could change to store two ints indexing ranges of ints in a common vector, saving the space for the -1. For above 4 clusters it should be a win with a (somewhat) trivial implementation. If the average is less, there are other options available as well which could be discussed.

**Comment by mconcas** [comment]
Tested it locally on `o2_ctf_run00543918_orbit0550821888_tf0000081058_epn207.root`, it works.
In terms of real memory, it looks like it is slightly improved.
This is before:
plot2

and this is after the fix:
plot1

To me this can be merged either ways.

**Comment by ktf** [comment]
@mconcas How do you do the memory plot? I suspect you do not have enough granularity (or the number of tracks is much less than what we have in PbPb).

**Pull request merged**
