### PR TITLE
fast space charge correction: extra parameters in interface

### PR DESCRIPTION
**Pull request by sgorbuno**
Some changes in the fast space charge correction code proposed by @wiechula in the other PR that is already merged:
https://github.com/AliceO2Group/AliceO2/pull/11682

### CODE REVIEW

**Review by wiechula — DISMISSED** [review]
Cool, thanks @sgorbuno !

**Comment by sgorbuno** [comment]
@wiechula, 

I can't see the log of build/O2/o2-cs8  compilation. It says my cern account "sgorbuno" has no rights to access the page.
Can you help me with this? :) Probably, one should add me to some list...

**Comment by davidrohr** [comment]
> @wiechula,
> 
> I can't see the log of build/O2/o2-cs8 compilation. It says my cern account "sgorbuno" has no rights to access the page. Can you help me with this? :) Probably, one should add me to some list...

@TimoWilken : could you check?

**Review by shahor02 — APPROVED** [review]
failures are unrelated, merging.

**Comment by TimoWilken** [comment]
> I can't see the log of build/O2/o2-cs8 compilation. It says my cern account "sgorbuno" has no rights to access the page. Can you help me with this? :) Probably, one should add me to some list...

Hi @sgorbuno, sorry for only getting to this now, I was away for some time.

I cannot find your CERN account "sgorbuno" in the CERN phonebook at https://phonebook.cern.ch/search?q=sgorbuno, unless you go by a first name other than Sergey there.

You should be able to see the log if you log in to the CERN SSO (e.g. at https://auth.cern.ch) with a CERN account that is a member of the "alice-member" e-group. Is this the case?

Feel free to email me at "timo dot wilken at cern dot ch" to discuss this.

**Pull request merged**
