### PR TITLE
CCDB api : Prevent whitespaces in file name

### PR DESCRIPTION
**Pull request by Barthelemy**
The commit also introduces a StringUtils.h with trimming functions.

### CODE REVIEW

**Comment by sawenzel** [comment]
the new clang format seems to want to do funny things.

**Comment by Barthelemy** [comment]
Yes, it seems to be confused with the lambdas ?

**Comment by Barthelemy** [comment]
There are actually a few correct changes
Let me rerun clang format on my side.

**Comment by Barthelemy** [comment]
Maybe this will do the trick

**Comment by Barthelemy** [comment]
There is still a change that clang-format in travis would like to do but I think that it is wrong. Also the build failure is probably wrong. 
@ktf  ?

**Comment by ktf** [comment]
I agree `clang-format` goes bananas. For the error I wonder if it's a side effect of the new clang on picking up the system tools...@dberzano can you remind me where to find the log?

**Comment by ktf** [comment]
I am merging this since it seems to be green now (apart from the usual issues). Any reason why `boost::algorithm::trim` was not used?

**Comment by Barthelemy** [comment]
The extraction of the trimming functions to their own file was just a side effect of using the trimming in a new place. I presume that we could use boost::trim here.

**Comment by Barthelemy** [comment]
When you will rewrite the CCDB api (merge with the DPL one) you can fix it ;)

**Comment by ktf** [comment]
Okok... ;-)

**Pull request merged**
