### PR TITLE
Rename TRD classes from TRDFoo to Foo

### PR DESCRIPTION
**Pull request by martenole**
Hi @jolopezl and @bazinski 
Since I had some time I thought I could do some cleanup of our code. We did want to rename our classes from e.g. TRDGeometry to Geometry, right? Or is this now not possible anymore due to some compatibility issues? I thought if we want to do it anyhow than better sooner than later..
For sure this interferes with your current developments, so I can wait for you to merge those and afterwards rebase. Just let me know when the timing is best for you.

Next to renaming I did the following:
- remove testArrayADC.cxx which was dummy
- remove some `using namespace o2::trd` directives in header files
- fix include in OCDB2CCDB.C

And what I also had in mind, but this could also be a later PR:
- move Digit.h and Tracklet.h from TRDBase into DataFormatsTRD

What do you think?

### CODE REVIEW

**Comment by bazinski** [comment]
Hi @martenole 

I agree with what you said above, I have a fairly big pr coming through, but no time will be pretty.
Can this be merged soon?

> * move Digit.h and Tracklet.h from TRDBase into DataFormatsTRD

I have changes coming through for digit.h, can move it at the same time, as for tracklet.h, I *think* we can dump it.
I know that now that the 32bit tracklet backwards compatibility is removed from the trapsimulator i am not using it and I suspect
nobody else either?

**Review by bazinski — APPROVED** [review]

**Review by jolopezl — APPROVED** [review]
I am happy with the changes. We considered doing this change a long time ago, but we keep postponing it. Thanks, @martenole.

**Comment by martenole** [comment]
Ok, all the checks have passed. 
@bazinski so for you it would be ok if we merge this now before your PR?

For me it is fine if you move the digits than later with your PR and for the Tracklet.h: didn't we want to keep that for debugging the TRAP sim? For sure this needs to be adapted as well to the new Run 3 format..

**Comment by bazinski** [comment]
> Ok, all the checks have passed.
> @bazinski so for you it would be ok if we merge this now before your PR?

yes, I will have a fun rebase :-D

> 
> For me it is fine if you move the digits than later with your PR and for the Tracklet.h: didn't we want to keep that for debugging the TRAP sim? For sure this needs to be adapted as well to the new Run 3 format..

Well the complexity of the trapsim was trying to maintain backward compatabilty of a 32bit and 64 tracklet, the backwards compatibility was removed, so only a 64 bit tracklet, and of course the 4x32bit raw data block, which also has the same constituent sizes as a 64 bit tracklet. The debugging is done via  a debug tracklet class inside the trapsimulator class  that holds a whole bunch of things as floats. https://github.com/bazinski/AliceO2/blob/aae2dd70eb79fa0dc146cfa59f27f990f9df0a82/Detectors/TRD/simulation/include/TRDSimulation/TrapSimulator.h#L303-L342

**Comment by martenole** [comment]
@davidrohr Could you approve this PR if the changes are fine with you at the moment?
In the GPU/TPC classes the only changes are search & replace of:
TRDGeometry -> Geometry
TRDGeometryFlat -> GeometryFlat
TRDPadPlane -> PadPlane

Another good reason for doing this change now is that we so far don't have anything in QC. If we would, a renaming would not be so easy anymore, because it would require synchronization of the repositories.

**Review by davidrohr — APPROVED** [review]

**Comment by davidrohr** [comment]
fine with me, is this ready to be merged?
Let's wait for @shahor02 to comment as well, then I'd get it merged.

**Comment by martenole** [comment]
Thanks a lot! Yes, this is ready to be merged then.

**Pull request merged**
