### PR TITLE
DPL: export environment variables when dumping DDS config.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
I think this does not respect the template keywords like `timeslice0`

**Comment by ktf** [comment]
@davidrohr fixed

**Review by davidrohr — DISMISSED** [review]
Works, thx
Only thing is that perhaps we should move the string replace stuff in a function to avoid the copy & paste

**Comment by davidrohr** [comment]
@ktf : Could you try to fix the tests before your vacation. We need this in a tag to run with more than 1 GPU using AliECS.

**Comment by ktf** [comment]
yes, sure, in a bit.

**Comment by ktf** [comment]
Ok, there was actually an unrelated (to DDS) race condition in the case LD_PRELOAD=libSegFault.so already. Now fixed.

**Pull request merged**
