### PR TITLE
Region callback

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr this should be all you need, albeit I did not have time to test it. To use it you can do:

```c++
return AlgorithmSpec::InitCallback{[=](InitContext& ic) {
   auto& callbacks = ic.services().get<CallbackService>();
   callbacks.set(CallbackService::Id::RegionInfoCallback, [](FairMQRegionInfo const& info) {
     // ... do GPU init ...
     });
   }
   //   ...
   return [task](ProcessingContext& pc) {
       // your processing loop. Guaranteed to be called synchronously
       // with the callback
     };
   }
};
```

**Comment by davidrohr** [comment]
Ok, thx, will give it a try.
I might come back with some questions how to test it, because so far I have no idea how to get the right type of region in to trigger the callback for testing.

**Comment by ktf** [comment]
Ok, albeit this might more be a question for @rbx .

**Comment by ktf** [comment]
@rbx it looks like we get:

```
[ERROR] Child 3516 had at least one message above severity ERROR: [02:03:50][ERROR] SubscribeToRegionEvents not yet implemented for ZeroMQ
```

any way we can silence that?

**Comment by rbx** [comment]
Yes, by implementing it. It's not much work, I'll do it today.

**Comment by rbx** [comment]
I opened a FairRootGroup/FairMQ#260, once that is checked & merged I'll make a new tag.
As explained earlier, ZeroMQ transport events are local to a single process only (pointers to zmq regions have no meaning in other devices - there is no shared memory). So while this should green your tests, the usefulness for your use case is probably limited.

**Comment by davidrohr** [comment]
I have retried locally with FairRootGroup/FairMQ#260 and the error `SubscribeToRegionEvents not yet implemented for ZeroMQ` has disappeared, instead I am receiving the error `Already subscribed. Only one subscription at a time possible. Unsubscribe first.`

**Comment by rbx** [comment]
Thanks for checking!
The issue was that with shmem repeated subscription would overwrite the previous one and with zmq it would disallow a new one if one is already present. I updated it to be consistent - both overwrite. Additionally you now have a method to check if a subscription is present - `SubscribedToRegionEvents()`, so you can avoid subscribing the same thing repeatedly, as you do now when iterating over channels.

**Comment by davidrohr** [comment]
I have to admit I do not understand what that means to us. @ktf: can you have a look?

**Comment by rbx** [comment]
The latest version is now tagged in FairMQ as v1.4.16. Please give it a try. Both issues with ZeroMQ ("not implemented" and the "Already subscribed...") are solved now.
As I mentioned, you can tweak your code with the help of `bool SubscribedToRegionEvents()` to avoid redundant subscriptions, but this is not critical.

Another thing we've added is a new type of event (besides `created` and `destroyed`) - `FairMQRegionEvent::local_only`. This one will fire as a first event for non-shared-memory transports (if you subscribe). The goal is to give you the ability to know if you should expect an external region info from the chosen transport.

With shmem transport, sender device creates the region and receiver devices gets notified if subscribed. In the subscription callback you can then register DMA access for the GPU and do any related things you need. 

With ZeroMQ transport the regions on the sender devices are only ever known to that device - there is no shared memory. This means that the receiver device will never get notified on any regions outside its own process. Furthermore, with ZeroMQ we have no control on where the incoming data will be put (unless we copy it additionally ourselves, which we of course do not want). ZeroMQ does not expose to its users where the data will land in advance, neither does it offer to customize that. You can know the location only when a message arrives by getting the pointer to the message buffer. So if this memory has to be registered for DMA, it can only happen on per-message basis with ZeroMQ transport. Or not registered at all and copied to GPU every time instead.

With the aforementioned event you have a trigger that you can use to enable per-message registering, or any other solution you prefer.

**Comment by ktf** [comment]
Bumping FairMQ at https://github.com/alisw/alidist/pull/2241

**Comment by davidrohr** [comment]
Thx, that, sounds good.

@ktf : I think it would be quite helpful if I could distinguish in my callback between the ZeroMQ per-message-registering case, and the shared memory register-once case.

The reason is: In general, I do not want to register the memory in the zeromq case, since registering + dma transfer is often slower than just non-dma transfer. But then in case I want to access the memory directly from a GPU kernel, I have to register to map it into the GPU address space.

**Comment by ktf** [comment]
@davidrohr yes, agreed. I will try to add that.

**Comment by ktf** [comment]
Merging this since it's green now. I will try to do some tests to understand if it fires correctly.

**Pull request merged**
