### PR TITLE
Add FT0 CTF reading and writing

### PR DESCRIPTION
**Pull request by shahor02**
* Rename and move FT0-related workflows/specs from FIT/workflow to FIT/FT0/workflow
* Add separate FT0 digits reader workflow
* CTF class for FT0, encoder/decoder and reader/writer

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @AllaMaevskaya 
before merging I want to clarify the question about the ``Trigger::amplA, amplC, timeA, timeC``: do I understand correctly that they are supposed to be the sum and average of individual channels time and amplitude but you have their independent measurement for the crosscheck? Storing them in the CTF would be quite expensive due to their large range and quazi-randomness, so, at the moment I did not add them to CTF. 
What you do if TCM values differ from those extracted from channels? If you just flag an error, we better save this flag.

**Comment by AllaMaevskaya** [comment]
Actually, we can compare Trigger::amplA, amplC, timeA, timeC with ChannelData on FLP and set special flag.We will discuss errors treatment and then I will add this part to the code. Individual channels time and amplitude we need for collision time, event plane and  multiplicity.

**Comment by shahor02** [comment]
@AllaMaevskaya ok, thanks, then for the moment I'll merge it as it is. There is still a problem of digits w/o channels produced by the simulation...

**Comment by shahor02** [comment]
test fails due to the problem in rAns, fixed here https://github.com/AliceO2Group/AliceO2/pull/3986

**Pull request merged**
