### PR TITLE
GEM clustering

### PR DESCRIPTION
**Pull request by grasseau**
@aphecetche 
An alternative to the clustering/fitting algorithm in the MCH. This is a draft version.
Currently, doesn't change the current flow (clustering/fitting and tracking in the MCH).

### CODE REVIEW

**Comment by aphecetche** [comment]
@grasseau FYI I've fixed two conflicts to get the tests started

**Comment by grasseau** [comment]
@aphecetche 
Thanks Laurent,
I saw this confict, I don't understand why it was not solved
Maybe I missed something

**Comment by grasseau** [comment]
@aphecetche 
The core of this alternative Clustering algorithm (called GEM) is  divided in the different 
files below. There are several classes of procedures : 

* Kernels must be fast, for this reason the code must be written as close as possible to C to facilitate the compiler optimizations (like vectorization, unrolling,  loop fusion, ...) in addition this kernel must favor contiguous memory accesses: 
- dataStructure.cxx/h : data representations with code to transform them   
- gaussianEM.cxx/h : Gaussian EM algorithm
- mathieson.cxx/h: computation of different kind of Mathieson      
- mathiesonFit.cxx : interface with the GSL fitting procedures
- mathUtil.cxx/h : Basic vector operations         
- padProcessing.cxx/h :  tools for image/pad processing like find the neighbors

* Core of the algorithm,:
- clusterProcessing.cxx/h  :  implement the new algorithm, manages  and calls the kernels 

* There are also utilities to compare the two algorithms. There don't belong 
to the new algorithm 
- ClusterDump.cxx     

* The current Workflow (GEM) task is able to deal with the 2 clustering (Original/GEM)
in ClusterFinderGEMSpec.cxx

**Comment by aphecetche** [comment]
@TimoWilken @ktf this one seems completely stuck. Any idea why ?

**Comment by aphecetche** [comment]
@TimoWilken @ktf actually is this one stuck or is continuously failing and being re-checked (and I happen to always have a look at it when it's building ?). 
One possible issue I can see is that there's a dependency on GSL (the Gnu Scientific Library, not the Guidelines Support Library), that should be explicitly added in o2.sh I guess. But that should only make the build break (assuming there's no gsl picked from the system, that is), not get it stuck, right ?

**Comment by TimoWilken** [comment]
Sorry I missed your earlier comment. The problem is that @grasseau hasn't authored any commits in this repository yet, so for security reasons, you'll have to approve this PR using the GitHub PR review mechanism to get the tests to start. Sorry for the inconvenience.

**Review by aphecetche — DISMISSED** [review]
Approval to get CI tests going.

**Comment by aphecetche** [comment]
@TimoWilken seems this one is stuck somehow.

**Comment by TimoWilken** [comment]
Because more commits were added after you last reviewed, GitHub automatically marked your previous review as "dismissed". You'll have to review again to get the tests going again.

**Review by aphecetche — DISMISSED** [review]
approve to get ci going

**Comment by grasseau** [comment]
@aphecetche 
CI format solved.
G.

**Comment by grasseau** [comment]
@aphecetche 
... rebased ...
G.

**Comment by aphecetche** [comment]
@grasseau are you sure about your rebasing ? seems way too many files changed (and unrelated to your clustering) ?

**Comment by grasseau** [comment]
Bonjour Laurent, 

Je suis étonné ! 

J'ai fait la procédure habituelle : 
> git checkout dev 
> git pull 
> git checkout GEM-Clustering 
> git rebase dev 
# 
# La git me dit que grasseau/GEM-Clustering dépassé, git propose de faire un pull 
> git pull 
# Git regarde les conflits, 
# ... Il y en a pas ... 
# Git propose de faire un push pour faire une maj 
> git push 
# Tout est OK (semble OK) 

A bientôt, 
Gilles 




De: "Laurent Aphecetche" ***@***.***> 
À: "AliceO2Group/AliceO2" ***@***.***> 
Cc: "grasseau" ***@***.***>, "Mention" ***@***.***> 
Envoyé: Mardi 13 Juillet 2021 11:28:08 
Objet: Re: [AliceO2Group/AliceO2] GEM clustering (#6432) 





[ https://github.com/grasseau | @grasseau ] are you sure about your rebasing ? seems way too many files changed (and unrelated to your clustering) ?

**Comment by vkucera** [comment]
@grasseau This is clearly not a result of a correct rebasing. Your PR includes commits that are not yours, whereas it should contain only your commits on top of the tip of the upstream `dev`. There is some mismatch between the history of your branch and the upstream `dev`, maybe due to some merging in between. You should rebase your branch on top of it using `git pull --rebase upstream dev`.

**Comment by grasseau** [comment]
@vkucera 
Ok, thank you. I saw my mistake
Gilles

**Comment by aphecetche** [comment]
Closing this one. Another one will be prepared...

**Pull request closed without merging**
