### PR TITLE
DPL: cleanup shmem using FairMQ 1.4.20 API

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@rbx this seems to call the correct Cleanup routine, but apparently something deletes the region before as I get:

```
Did not find 'fmq_XXXX_mng' shared memory segment. No regions to cleanup.
Did not remove 'fmq_XXXX_main'. Already removed?
Did not remove 'fmq_XXXX_mtx'. Already removed?
Did not remove 'fmq_XXXX_cv'. Already removed?
```

where XXXX is the correct `ShmId`. Notice that while running the region is there and it's gone as I hit a breakpoint in `Monitor::Cleanup`.

**Comment by rbx** [comment]
Shared memory transport destructor will attempt to cleanup the memory if it is the last device remaining. This would fail if any of the devices crashed and did not de-register themselves. Then your Cleanup() would succeed. It is basically a backup in case something goes wrong (as is the monitor executable when device is started with `--shm-monitor true`).

So I assume in your test all the destructors were called correctly and there is nothing left to cleanup.

**Comment by ktf** [comment]
Ok, good, can we have it silently failing / throwing an exception at the end if it did not manage? Right now it always prints it's failing.

**Comment by rbx** [comment]
No problem, I'll add something to be able to suppress the output.

**Pull request merged**
