### PR TITLE
Fix namespace naming: o2::its::...

### PR DESCRIPTION
**Pull request by anerokhi**
- o2::its::IOUtils
 - o2::its::IndexTableUtils
 - o2::its::MathUtils
 - o2::its::RecoWorkflow
 - o2::its::constants::IndexTable
 - o2::its::constants::Math
 - o2::its::constants::PDGCodes

### CODE REVIEW

**Comment by davidrohr** [comment]
Did you do a git grep for the appearance of these name spaces?
For the ITS Constants, you missed to fix some inside the GPU part (Detectors/ITSMFT/ITS/tracking/cuda).
You should change it there as well.

**Comment by sawenzel** [comment]
@davidrohr : Shouldn't this be caught by the cuda build. I thought this was now enabled in the CI?

**Comment by anerokhi** [comment]
> Did you do a git grep for the appearance of these name spaces?

Yes,  there are fixes for `.cu` files, like https://github.com/AliceO2Group/AliceO2/pull/2003/files#diff-2ab99abf13c3c17728991526037bb833

> For the ITS Constants, you missed to fix some inside the GPU part 

You mean previous PRs?

**Comment by davidrohr** [comment]
@sawenzel : In principle it should, but for some reason it seems it is no longer running, no idea why. @dberzano ?

**Comment by anerokhi** [comment]
BTW, there is only one NS left unfixed:
```
$ git grep GPUReconstruction_krnlHelpers
GPU/GPUTracking/Base/GPUReconstructionCPU.h:namespace GPUReconstruction_krnlHelpers
GPU/GPUTracking/Base/GPUReconstructionCPU.h:} // namespace GPUReconstruction_krnlHelpers
GPU/GPUTracking/Base/GPUReconstructionCPU.h:using namespace GPUReconstruction_krnlHelpers;
```

**Comment by davidrohr** [comment]
#1999 missed some of the Constants::its namespace in the cu files and their header.
Anyway, I just verified locally that this one here is correct and does not break the CUDA build. Please go ahead.

I'll have a look for GPUReconstruction_krnlHelpers. The idea was that it belongs to the GPUReconstruction class.

**Comment by anerokhi** [comment]
> #1999 missed some of the Constants::its namespace in the cu files and their header.

Could you show an example, please? I can't find unfixed `Constants` in `.cu` files:
```
$ ack --type-set cuda:ext:cu --cuda Constants
Detectors/ITSMFT/ITS/tracking/cuda/src/TrackerTraitsNV.cu
25:#include "ITStracking/Constants.h"
```

**Comment by davidrohr** [comment]
No worry, I already fixed the Constants when I rebased #1990

**Comment by davidrohr** [comment]
#2004 removes GPUReconstruction_krnlHelpers and solves it differently

**Comment by davidrohr** [comment]
So what is the status of this PR, should we finally get tid of the travis error and get it merged?

**Comment by sawenzel** [comment]
@anerokhi : Could you please update the PR (merge conflicts). Let's try to integrate immediately thereafter.

**Comment by languagelawyer** [comment]
@sawenzel the PR was updated.

**Comment by anerokhi** [comment]
@sawenzel the PR was updated.

**Comment by davidrohr** [comment]
@anerokhi : I think it is not your fault, you just touched the files, but could you apply the clang-format fixes?

**Comment by anerokhi** [comment]
@davidrohr done

**Pull request merged**
