### PR TITLE
Fix detection of CCDB production server in CcdbApi

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Review by costing — DISMISSED** [review]
Thanks a lot Ruben!

**Comment by davidrohr** [comment]
out of curiosity: why did the old code not work? should be the same, or do I miss something?
Or ok, if the string would start with spaces, it would break?

**Comment by shahor02** [comment]
@davidrohr because the host is not necessarily precisely `http://alice-ccdb.cern.ch`, e.g. for CCDBBasicManager it was failing since by default it sets the `host` to `http://alice-ccdb.cern.ch/`. Or it can be e.g. `http://alice-ccdb.cern.ch/Users/x/xyz/` ...

**Comment by davidrohr** [comment]
ok, makes sense.
doesn't really matter but a minor thing: rfind searches from the right, while what we are searching for should normally be on the left side of the string, so I would use find instead of rfind.

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
