### PR TITLE
TPC-ITS macthing + necessary changes

### PR DESCRIPTION
**Pull request by shahor02**
Added TPCITS matching class Detectors/GlobalTracking/MatchTPCITS
Moved many data format classes from O2/Detectors to O2/DataFormats:

``	renamed:    Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTrack.h -> DataFormats/Detectors/ITSMFT/ITS/include/DataFormatsITS/TrackITS.h
	renamed:    Detectors/ITSMFT/ITS/reconstruction/src/CookedTrack.cxx -> DataFormats/Detectors/ITSMFT/ITS/src/TrackITS.cxx
	renamed:    Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Cluster.h -> DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/Cluster.h
	renamed:    Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/ClusterTopology.h -> DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/ClusterTopology.h
	renamed:    Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/TopologyDictionary.h -> DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/TopologyDictionary.h
	renamed:    Detectors/ITSMFT/common/reconstruction/src/Cluster.cxx -> DataFormats/Detectors/ITSMFT/common/src/Cluster.cxx
	renamed:    Detectors/ITSMFT/common/reconstruction/src/ClusterTopology.cxx -> DataFormats/Detectors/ITSMFT/common/src/ClusterTopology.cxx
	renamed:    Detectors/ITSMFT/common/reconstruction/src/TopologyDictionary.cxx -> DataFormats/Detectors/ITSMFT/common/src/TopologyDictionary.cxx
``

### CODE REVIEW

**Comment by shahor02** [comment]
@iouribelikov @lbariogl : please note that I am moving ITS(MFT) data format definition classes to DataFormat directory (+ renamed CookedTrack to TrackITS, the internals are the same for moment).

@davidrohr also moved the TPC clusters conversion macros and runCATrackingClusterNative to installable O2/macro dir.

**Comment by sawenzel** [comment]
I think it would make sense putting the new features and moving the files around into separate PRs.

**Comment by shahor02** [comment]
@sawenzel : I tried to do this first, but then got a lot of circular dependencies unless I put would put new features in a priory wrong place...

**Comment by shahor02** [comment]
Hi @dario, @ktf: is there something wrong with build servers? Only the macos log is partually shown, but the link (as well as for other checks) is brocken (404)

**Comment by shahor02** [comment]
Hi @dberzano @ktf @sawenzel 

Could anybody tell me how to reproduce locally the ctest done on the macos over macros?
The log says:
````
+ ctest -j 16
Test project /build/ci_checks/o2_checker_macos_o2_ci_0/sw/BUILD/f1f20e2d07883eb47cfa0123d83ef8092f30b655/O2
...
 2/162 Test   #9: /Detectors/ITSMFT/ITS/macros/test/CheckTopologies.C ..................***Failed   16.66 sec
```` 
but it is not clear what exactly it does with the macro. If I do on the macos the `ctest`, it just runs the test executables.

Another question: compilation of some macros in the O2/macro directory fails like:
```
root alice/O2/macro/run_digi_tpc.C+
/Users/shahoian/alice/sw/osx_x86-64/O2/dev_tpcttm-1/include/SimulationDataFormat/MCTruthContainer.h:21:10: fatal error: 'gsl/gsl' file not found
```
idem with 
```
/Users/shahoian/alice/sw/osx_x86-64/O2/dev_tpcttm-1/include/TPCBase/CalArray.h:14:10: fatal error: 'Vc/Vc' file not found
```
I can bypass this by preloading the libraries which depend on these external libs as
````root loadExtLib.C  alice/O2/macro/run_digi_tpc.C````
with 
````
cat loadExtLib.C
{
  // temporary measure to load vc and gsl
  gSystem->Load("libSimulationDataFormat.so");
  gSystem->Load("libTPCBase.so");
}
````
but then the ctest fails with
````
1/162 Test  #60: /macro/loadExtDepLib.C ...............................................***Failed   11.74 sec
...
Error in <TMacOSXSystem::FindDynamicLibrary>: libSimulationDataFormat.so does not ...
````
apparently because the it runs before the installation. I can cheat it by loading explicitly 
gSystem->Load("$O2_ROOT/lib/libSimulationDataFormat.so");
but this is quite ugly. Is it clear why the libraries are not loaded automatically?

**Comment by shahor02** [comment]
@brinick @dberzano : thanks for fixing the retrieval of macos logs. But now it overkills: the logs sent for build/O2/o2-dev-fairroot , build/o2/macos  and build/o2checkcode/o2  are the same single log from macos :)

**Comment by dberzano** [comment]
@shahor02 I see, the problem is that different failed checks push the log in the same place, overwriting each other. This should be fixed, thanks for spotting it!

**Comment by shahor02** [comment]
@lbariogl : please note that temporarily I had to change (https://github.com/AliceO2Group/AliceO2/pull/862/commits/4290e49696f0e92901aa4a1c911507745694b3fc) the unordered_map to map in the BuildTopologies. The problem is that after moving the ClusterTopology class to DataFormats the check on macos fails when simply trying to load the ````Detectors/ITSMFT/ITS/macros/test/CheckTopologies.C````, apparently due to the bug in the roorcling, to be checked with experts.

**Pull request merged**
