### PR TITLE
Add ToC for Core Framework documentation

### PR DESCRIPTION
**Pull request by aphecetche**
A table of content would probably improve the readability of the doc.

### CODE REVIEW

**Comment by ktf** [comment]
Agreed, but can't we generate it automatically with doxygen?

**Comment by aphecetche** [comment]
hum, well, maybe, don't know, must confess I have the (bad?) habit to turn to *.md files first even before checking on Doxygen ... @ihrivnac do you know if we can generated ToC from MD documents with Doxygen ?

**Comment by jgrosseo** [comment]
Yes, +1 on the comment of @ktf. A by hand TOC runs out of sync on the next commit...

**Comment by aphecetche** [comment]
> Yes, +1 on the comment of @ktf. A by hand TOC runs out of sync on the next commit...

well, it's not actually by hand, as it is automatically handled by a vim plugin, but I reckon it does not help people not using vim (or even people using vim but with a different set of plugins). I was indeed a bit quick forgetting that the Markdown ToC generation is not necessarily readily available in all editors. Too bad GitHub is not handling this natively. So I guess we're left with a Doxygen solution then...

**Comment by jgrosseo** [comment]
I wanted to look into if there is some automatic tool for github pages. There seems to be some client-side javascript solutions, but I haven't looked into more...

**Comment by ktf** [comment]
Another alternative would be to have an action which updates the ToC automatically on every commit. Anyways, closing this until we find a solution we are all happy about.

**Comment by ktf** [comment]
https://alice.its.cern.ch/jira/browse/O2-2115 for the followup.

**Pull request closed without merging**
