### PR TITLE
Added trigger table to store triggerMask

### PR DESCRIPTION
**Pull request by ekryshen**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@ktf same problem here?

**Comment by ktf** [comment]
yes.

**Comment by jgrosseo** [comment]
Please wait with merging, we are still discussing the naming

**Comment by ktf** [comment]
@jgrosseo ok, simply approve the PR when you want to start testing it.

**Comment by jgrosseo** [comment]
AliPhysics is OK https://github.com/alisw/AliPhysics/pull/13755
So this can be merged once the tests pass

**Comment by ktf** [comment]
@MichaelLettrich can you check what is going on? Thanks.

**Pull request merged**
