### PR TITLE
Use `<fairmq/FwdDecls.h>` instead of downstream forward declarations

### PR DESCRIPTION
**Pull request by dennisklein**
This makes the forward declaration techniques more future-proof towards
renamed typenames in FairMQ, e.g. if forward declared types become a
type alias.

`<fairmq/FwdDecls.h>` is available since FairMQ `v1.4.39`.

---

* This PR supersedes #6657.
* FairMQ bump is proposed in alisw/alidist#3168.

### CODE REVIEW

**Comment by ktf** [comment]
What is the point of exposing all the FairMQ types everywhere?

**Comment by dennisklein** [comment]
The plan is to rename all the remaining types that are not yet in a namespace:
* `::FairMQ<Name>` will become `::fair::mq::<Name>`
* There will be type aliases to the old type name. Unfortunately, this breaks downstream forward decls as we have seen yesterday. This is one way to enable a transition. 

If you have a better way of doing that, please tell us. If you are ok by being broken from one version bump to the next, then you can close this PR.

**Comment by ktf** [comment]
Well, I was thinking about some finer grained subdivision like:

* FairMQMessage, FairMQParts
* Device, Channel, Transport
* MemoryResources
* Rest

but then again, maybe it's an overkill.

**Comment by ktf** [comment]
Fixing a merge conflict and triggering a rebuild to pick up the new version of FairMQ.

**Comment by ktf** [comment]
I am holding on this, because otherwise everyone will have to move to the new FairMQ. If you want this to be used, you should protect it with #if __has_include()...

**Comment by dennisklein** [comment]
> I am holding on this, because otherwise everyone will have to move to the new FairMQ.

Sure. That was the whole point, enabling downstream to decide when to have to adapt and/or have to bump the minimum required FairMQ version.

> If you want this to be used, you should protect it with #if __has_include()...

Consider this PR just as a friendly hint/help. I do not insist for this specific change to be merged (since I do not know or care about which range of FairMQ versions you intend to support). If you prefer different variant, please go ahead!

**Comment by davidrohr** [comment]
I think there are not so many fwd declaration, so it should be ok.
I would not put some #if has include code, it just makes the includes more complicated, at some point people will have to bump fairmq. Perhaps we can wait few more days, but then I would merge this.

**Comment by ktf** [comment]
Yes, but I want to avoid recompiling everything two days before my holidays... ;-)

**Comment by davidrohr** [comment]
Well, it is not so heavy. It will recompile FairMQ/DDS/FairROOT/O2.
Anyway, do you think it is better we do this throughout your vacation? Or do we wait for 2 more weeks until you return?

**Comment by ktf** [comment]
Can we wait until tomorrow?

**Comment by davidrohr** [comment]
Sure, merge it at your convenience. In case there are issues, I am also available at least until the end of the week to check. But I have already used the new FMQ in the FST and it seem good.

**Pull request merged**
