### PR TITLE
DPL: Do not use sleep

### PR DESCRIPTION
**Pull request by ktf**
FairMQ still has trobles with it.

### CODE REVIEW

**Comment by ktf** [comment]
@rbx @dennisklein is there any plan to improve things here?

**Comment by rbx** [comment]
We have no plans to interrupt `std::sleep`s. It is working as intended.

**Comment by ktf** [comment]
Agreed about not interrupting sleeps, but it simply hangs, it's not like it will come back at some point...

**Comment by rbx** [comment]
Just to clarify, does `sleep_for` hang or our `WaitFor`?

**Comment by ktf** [comment]
sleep_for does. WaitFor works as expected.

**Comment by rbx** [comment]
Hmm, then I'm not sure if we can do anything about it.
I assume you are referring to https://github.com/FairRootGroup/FairMQ/issues/82 and it hangs when SIGINT occurs? 

For sure nothing changed on our side in this regard.

**Comment by ktf** [comment]
Compiles on macOS and Linux. Not really tested. Merging.

**Comment by ktf** [comment]
@rbx I am not claiming it changed, I am claiming that I still see it hanging (i.e. it does not terminate after a sigint is received and the sleep is over).

**Pull request merged**
