### PR TITLE
number of channels according LUT

### PR DESCRIPTION
**Pull request by AllaMaevskaya**
Fix bug in channel numbering

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
Fail in O2 does not relate to my code

**Comment by AllaMaevskaya** [comment]
What is the problem here?

**Comment by shahor02** [comment]
Hi @AllaMaevskaya 
could you fix the formatting errors to unblock CIs? 
Also, in many places you are commenting out patched lines: the changes seem definitive, better remove commented obsolete code.

**Review by mslupeck — APPROVED** [review]

**Comment by AllaMaevskaya** [comment]
Can it be merged now?

**Comment by AllaMaevskaya** [comment]
Is it possible to merge it? Fixed are small and trivial, but we need it to start simulations

**Pull request merged**
