### PR TITLE
Fix indentation, and typo

### PR DESCRIPTION
**Pull request by chiarazampolli**
@davidrohr , @martenole , @shahor02 : I fixed the indentation, but there was also a typo:
```
FLP_ADDRESS**+**="tcp://alicr1-flp-ib${flp}:${TPC_IDC_FLP_PORT}"
```
should have been:
```
FLP_ADDRESS="tcp://alicr1-flp-ib${flp}:${TPC_IDC_FLP_PORT}"
```

### CODE REVIEW

**Comment by martenole** [comment]
Thanks, but why is then `FLP_ADDRESS` defined inside the for loop? Then it will always be `tcp://alicr1-flp-ib144:${TPC_IDC_FLP_PORT}`
If its always flp144 I think that should be defined outside the loop

**Comment by chiarazampolli** [comment]
> Thanks, but why is then `FLP_ADDRESS` defined inside the for loop? Then it will always be `tcp://alicr1-flp-ib144:${TPC_IDC_FLP_PORT}` If its always flp144 I think that should be defined outside the loop

I don't think so. We need to have one channel per FLP, so we will append to `CHANNELS_LIST` every time a different FLP. Maybe I am blind... I will try it in a shell.

**Comment by martenole** [comment]
Ah sorry, never mind. It's only used inside the loop.. I think its fine as it is now

**Comment by chiarazampolli** [comment]
Error is not related to the PR, can it be merged? @shahor02

**Comment by davidrohr** [comment]
merging, but this seems to fix only the typo, not the indentation.

**Comment by chiarazampolli** [comment]
Weird, i pushed yesterday the fix, after the first one didn’t work. I will check.

**Pull request merged**
