### PR TITLE
Add standalone AOD producer

### PR DESCRIPTION
**Pull request by peressounko**
- Standalone ao2d converter added;
- Event builder to combine parts of events from FLPs added;
- bugfix in rawtocell converter

### CODE REVIEW

**Comment by ktf** [comment]
The mac issue is real.

**Comment by peressounko** [comment]
fullCl seems to fail due to (unrelated to commit):
82349:CPVDigitizer]: [11:00:46][WARN] CCDB: Did not find an alien token; Cannot serve objects located on alien://
[82349:CPVDigitizer]: [11:00:46][INFO] CCDB: Reading o2::cpv::Pedestals from CPV/Calib/Pedestals
[82349:CPVDigitizer]: [11:00:46][WARN] CCDB: Did not find an alien token; Cannot serve objects located on alien://
[82349:CPVDigitizer]: [11:00:46][ERROR] Requested resource does not exist: http://alice-ccdb.cern.ch/download/8957ed2a-a121-11ec-982e-0aa202a21b9a
[82349:CPVDigitizer]: [11:00:46][FATAL] Got nullptr from CCDB for path CPV/Calib/Pedestals and timestamp 1647082312288

**Comment by peressounko** [comment]
Dear @ktf  it looks like remaining tests stacked. Could you have a look?

**Comment by peressounko** [comment]
Dear @ktf  it looks like remaining tests stacked. Could you have a look?

**Comment by peressounko** [comment]
Dear  @ktf, @shahor02 what can we do with this PR? Test seems to stack.

**Comment by ktf** [comment]
Errors unrelated. @TimoWilken could you verify the macOS builder?

**Pull request merged**
