### PR TITLE
Add primary vertexer on GPU + Update data reading interfaces

### PR DESCRIPTION
**Pull request by mconcas**
This PR actually contains more than the GPU vertexer introduction. Among the rest:
 - [x] Cleanup of steering macros and insertion of a new one to merge the latter
 - [x] Introduction of the serial version of the algorithms used on GPU for tracklet finding
 - [x] Trivial tracklet finder based on MC truth
 - [x] Primary vertexer on GPU, still WIP, to be completed:
 - [x]  DBSCAN-based cluster finder serial →moved to next iteration
 - [ ]  DBSCAN-based cluster finder on GPU →moved to next iteration
 - [x] Integration of primary vertexer in the TrackerSpec workflow
 - [x] Update loadROFrame usage in steering macro for primary vertexer
 - [x] This PR should be merged with the CUDA compiling test approves.
 - This is something related to #1916, indeed I need to wait its merge before rebasing
    - [x] Rebase
    - [ ]  Test with CUDA →moved to next iteration

### CODE REVIEW

**Comment by mconcas** [comment]
@shahor02 , @iouribelikov. If this will pass the ramaining tests (I know there are problems here and there with tests). I wuould remove the [WIP] tag.
Not every feature that I wanted to include is present already, but as I wrote to Yura yesterday, I will change the rate of my PRs: smaller and more frequent.
I am rushing on this since it introduce a lot of updates wtr its-reco-workflow and ROFrame.
GPU part is incomplete, but these changes are more urgent due to the inter-operation with other people's work. I added the latest most notable changes in the first comment.

**Comment by shahor02** [comment]
Thanks @mconcas! 
Could you please add the vertex seed to the  ``CookedTrackerSpec.cxx``? Should not be different from ``TrackerSpec.cxx``.

Cheers,
 Ruben

**Comment by mconcas** [comment]
Hi @iouribelikov , @shahor02. I am on the vertexer integration in CookedTracker atm.

Actually, my doubts right now is only on how the `mTracker.process()` acts with respect to the mVertices.
@iouribelikov: if you look at the `TrackerSpec.cxx` the loop over ROFrames is explicit, that means that for each ROFrame we compute all possible vertices (if we find more than one: pile-up) by running the vertexer and passing results related to that single roframe to CAtracker.
In your case, if I am not wrong, you `.process()` the entire ROFRecord, is it true?
If yes, I propose to you a first integration of the vertexer, where I will run the vertex finding for each roframe and produce a final vector filled with found vertices. After that you can run the CookedTracker on it.
So my real question is: what kind of vertices do you expect to find for the cooked tracker?

Cheers,
Matteo

PS: I would really like to have this merged by the end of this week, that is why I am bugging you before the Monday's WP12 discussion.

**Comment by iouribelikov** [comment]
@mconcas For this PR, I would go *without* the CookedTracker.
Just to avoid potential conflicts with another PR #1926.

**Comment by shahor02** [comment]
@iouribelikov OK, I thought the https://github.com/AliceO2Group/AliceO2/pull/1926 is already merged...
Then indeed, let's address the vertexing for CookedTracker in separate PR.

**Comment by mconcas** [comment]
Well, it feels good to finally see the green light PRs. 
@sawenzel if you please could hang a moment to merge, with @dberzano we would like to test the CUDA build.

Thanks

**Comment by mconcas** [comment]
@shahor02 we are ready to merge,what do you think?

**Comment by shahor02** [comment]
yes

**Pull request merged**
