### PR TITLE
FV0: Add PMTs to FV0 geometry and redistribute optical fiber volumes

### PR DESCRIPTION
**Pull request by andreasmolander**

### CODE REVIEW

**Review by mslupeck — DISMISSED** [review]
This is OK to be merged after changing log severity to lowercase

**Comment by mslupeck** [comment]
@andreasmolander I think the tests are stuck. Could you restart them? Just amend your last commit message by adding a space somewhere and force-push

**Comment by andreasmolander** [comment]
> @andreasmolander I think the tests are stuck. Could you restart them? Just amend your last commit message by adding a space somewhere and force-push

Done, but it seems the tests are stuck in the same place again?

**Review by sawenzel — DISMISSED** [review]
approve to trigger CI

**Comment by mslupeck** [comment]
@andreasmolander Judging from the log of failed CI jobs, you've forgotten to rebase your branch (git pull --rebase origin dev)

**Comment by mslupeck** [comment]
@andreasmolander Also there are several TString -> char * conversion errors in Geometry.cxx

**Review by mslupeck — APPROVED** [review]

**Pull request merged**
