### PR TITLE
DPL: allow multiple workflows in the same session

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr I am not sure this is 100% of it, but simple tests seem to work. Could you try? You probably need `--no-cleanup` as well.

**Comment by davidrohr** [comment]
ok, thx, will check later.

**Comment by davidrohr** [comment]
@ktf @rbx : I did some tests and I believe this PR itself is OK, but something is still broken. In my test I am running 2 full system tests, and I tried with different combinations of session name / shm segment id:
- sessions default0 / default1 and shm id 0 / 0 --> works
- sessions default0 / default1 and shm id 0 / 1 --> works
- sessions default0 / default0 and shm id 0 / 0 --> works
- sessions default0 / default0 and shm id 0 / 1 --> processes segfault or get stuck.
I.e. running 2 workflows in the same session works, but only when they are using the same segment id. Eventually we want to use 2 segment ids, one per NUMA domain. So this must still be fixed.
But if I use the same segment id, the 2 workflows seem to run in parallel without disturbing each other, so judging from this I'd say this PR looks ok.
But also changing the segment id when the session is not shared works. I have also observed the segment with the fairmq-shmmonitor, and indeed if I switch to segment id 1, there is nothing allocated in segment 0, so switching the segment also works in itself.
Only the combination fails.

I have also added the `--no-clleanup` flag, but I do not fully understand what it does. I was assuming the /dev/shm/* files would be left over after the workflow, but they are removed even with the flag. Is this expected?

**Comment by ktf** [comment]
Merging this following @davidrohr feedback and because in any case it should be no-op when `--channel-prefix` is not provided. I think for shared memory you need to look into `/tmp/boost_interprocess` (at least on mac it's like that).

**Comment by davidrohr** [comment]
@ktf : Now I am confused, do I need to set some `--channel-prefix` ? You didn't write anything in the thread and also I didn't see the option in the code.

**Comment by rbx** [comment]
@davidrohr Can you post the stack trace of one of the segfaults?

**Comment by rbx** [comment]
> sessions default0 / default0 and shm id 0 / 1

This has worked already before, right? Iirc this was our solution for NUMA couple months ago?

**Comment by davidrohr** [comment]
No, this has never worked, I was using 2 different sessions for the NUMA domains. But this has the problem that the 2 workflows cannot talk to the same instance of DataDistribution, because DD can only be part of 1 session.

> > sessions default0 / default0 and shm id 0 / 1
> 
> This has worked already before, right? Iirc this was our solution for NUMA couple months ago?

**Comment by rbx** [comment]
Ok. If both are in the same session there should be no issues. Even if some device is missing the shm id parameter, it will default to 0, and create messages in segment 0. This device will still be able to receive messages from segment 1. So, even if less optimal, it should not crash.

**Comment by davidrohr** [comment]
But there should be no interconnection. In my test right now I am running 2 totally independent workflows in the 2 segment ids. They are not (at least should not) exchanging any message. They should just run in the same session, but each workflow should use its own shm segment. In the next step, I'd add datadistribution to provide the input, but I am not that far yet, because already running the 2 workflows on their own without DD fails.

**Comment by rbx** [comment]
I understand and agree, I'm just trying to think what could be causing crashes and i don't think it is misconfiguration (if there is any). In FairMQ we don't do any isolation for different segments (intentionally), but you can achieve it with configuration of channels/segment-ids.

**Comment by davidrohr** [comment]
Hm, I didn't manage to get a stack trace yet, perhaps it is not even crashing but not starting up correctly. In the DebugGUI they were red, so I though they had crashed.In the log I see:
```
[37449:internal-dpl-clock]: terminate called after throwing an instance of 'std::out_of_range'
[37449:internal-dpl-clock]:   what():  _Map_base::at
```
and then all the DPL processes failed to start with `[ERROR] error while setting up workflow: Error while parsing serialised workflow`

**Comment by ktf** [comment]
yes, you need to pass --channel-prefix to each

**Comment by davidrohr** [comment]
OK, I retried with `--channel-prefix` but that doesn't change anything. It works in the same session if I use the same segment id, it fails if I use different segment IDs.
And frankly, I am wondering how it was working before in the same session with same segment id when I wasn't using the prefix???

**Comment by rbx** [comment]
`std::out_of_range` could be a mismatch in the channel name.

**Comment by ktf** [comment]
or not finding the channel after failing to create it? can you share the output?

**Comment by davidrohr** [comment]
[log.txt](https://github.com/AliceO2Group/AliceO2/files/5555775/log.txt)
attached the log when running the workflow. I am creating a tarball with the simulated raw files and script to run it, will upload in a couple of minutes.

**Comment by ktf** [comment]
can you run with --severity debug?

**Comment by davidrohr** [comment]
In order to reproduce:
- Download https://qon.jwdt.org/nmls/tmp/testcase.tar.bz2 and unpack to a folder
- edit `rawAll.cfg` and fix the absolute paths
- Run `test.sh [SESSIONID] [SEGMENTID]`
(i.e. a single invocation `test.sh 0 0` should just work. Running in 2 shells in parallel `test.sh 0 0` twice will also work (both in the same session with same segment id). Running `test.sh 0 0` and `test.sh 0 1` fails for me with the problem mentioned above. Running `test.sh 0 0` and test.sh 1 1` works - it uses 2 independent sessions.)

The dataset is rather small, currently I put 8 GB for the memory buffer of the tracker and 8GB SHM, so for running 2 instances you need > 32 GB, but I think you can reduce the buffer sizes to 4 GB or even 3.

**Comment by davidrohr** [comment]
@ktf @rbx : Are you looking into the issue / testcase I reported? Shall I open a Jira ticket to follow this up?

**Comment by ktf** [comment]
My understanding was that you asked @rbx to look into it. I can try to have a look if he did not find anything suspicious.

**Comment by ktf** [comment]
(in any case, yes, open the JIRA)

**Pull request merged**
