### PR TITLE
Remove broken & unneeded otool command.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
The otool command is actually not working correctly, see for example the logs of:

https://ali-ci.cern.ch/alice-build-logs/alisw/alidist/1750/766bbfdc44c350de163543292db594089631252a/build_O2Suite_alidist_macOS/fullLog.txt

not sure where the problem is but in any case it looks to me this is just debug code.

**Comment by ktf** [comment]
Merging this to unstuck the alidist builders. We can readd it later if really needed.

**Comment by aphecetche** [comment]
hum, indeed I now wonder why those were there... but the fact that otool is called without a file is also worrisome somehow, will check...

**Comment by aphecetche** [comment]
Not that it matters, but for the record : the otool was not given a filename but an empty variable.
Anyway those two commands called at install time (ldd _and_ otool) had nothing to do there. Most probably some leftover of some kind of test, sorry about that.

**Comment by ktf** [comment]
Yeah, no worries. Is the name of variable actually correct? Anyways, I think we agree, that is at best some leftover debug code.

**Pull request merged**
