### PR TITLE
MCH: add time clustering of MCH digits

### PR DESCRIPTION
**Pull request by aferrero2707**
The time clustering algorithm uses a brute-force peak search algorithm to find the time regions where the digits clusterize around a given point in time.

### CODE REVIEW

**Comment by aferrero2707** [comment]
Here are the things to modify in this PR:
- remove the use of the first TF orbit in the time clustering
- minimize the changes in the PreClustering workflow
- simplify the optional input data specification in the time clustering workflow

**Comment by aphecetche** [comment]
> * minimize the changes in the PreClustering workflow

actually note that the current changes break the `o2-mch-reco-workflow`, as the meaning of the `getPreClusterFinderSpec` parameters is changed by this PR (I guess that should have been caught by the fullCI anyway, if it went up to the actual FST test, but is currently failing for other reason).

**Comment by aferrero2707** [comment]
@aphecetche the issue with the `reco-workflow` is even worse... the code compiles because one of the two string parameters of the `getPreClusterFinderSpec` function has a default value, hence in the `reco-workflow` we assign the data processor name to what is supposed to be the input description.

In fact, the input description should be provided from the command line in the `reco-workflow` case as well, unless the ROOT input is used, in which case the input description should be fixed to `DIGITROFS` (or whatever is defined in `getDigitSamplerSpec()`).

This looks quite over-complicated and error-prone for the moment... any idea?

**Comment by aphecetche** [comment]
yep, the reco-workflow fails (because you've added a parameter in front of the existing one in getPreclusterFinderSpec :-( ). I've changed that in my (wip) dev branch to be able to pursue my tests : https://github.com/aphecetche/AliceO2/tree/mrrtf-129-rof-time-clustering. 
IMO the reco-workflow should be as simple as possible by default (so its number of command line option minimised if possible). 
Anyway, once I have my tests working I'll think of a clean(er) solution (if there's one)

**Comment by aferrero2707** [comment]
@ktf @aphecetche the MacOS CI job is failing due to build errors on `O2HitMerger.h` (un-related to this PR).

Could you please have a look?

Thanks!

**Review by aphecetche — APPROVED** [review]

**Comment by aphecetche** [comment]
@ktf @shahor02 as far as we can tell the CI errors are unrelated. Can this PR be merged (or the CI restarted if that's preferred ?). Thanks.

**Pull request merged**
