### PR TITLE
Code owners

### PR DESCRIPTION
**Pull request by ihrivnac**
Completed file including detector responsibles.
See also [O2-816](https://alice.its.cern.ch/jira/browse/O2-816)

### CODE REVIEW

**Comment by sawenzel** [comment]
My username was not correct. I fixed it directly in the file.

**Comment by ktf** [comment]
I think we should not use actual usernames, but groups, at least in general.

**Comment by ihrivnac** [comment]
HI @ktf,
Could you, please, post your comment in the dedicated JIRA ticket linked above? As this is already the 3rd PR related to this topic, I think it is better to keep the discussion at one place. 
Thank you,

**Comment by ktf** [comment]
Done. I've locked the conversation so that no one posts here.

**Comment by sawenzel** [comment]
Going ahead after the discussion in WP3.

**Pull request merged**
