### PR TITLE
DPL: double the number of processes which can be created by the driver

### PR DESCRIPTION
**Pull request by ktf**
This makes sure that the extra file descriptors which are needed to
setup the parent / child communication channel created as late as
possible, and closed as soon as the fork happens.

Before this change, since we were creating the file descriptors in
one go, the extra endpoints which get closed after the fork were needlessly
using resources, leading to early exhaustion.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr this should allow the driver to spawn up to ~110 devices with ulimit -n  256.

**Review by davidrohr — APPROVED** [review]
Thx, this is a significant improvement.
Now I can run the workflow (still without QC) with `ulimit -n 256`
(ping @chiarazampolli)

**Comment by ktf** [comment]
We can try to improve a few more things, however if we want to have a stable connection to the driver to report logs / metrics, we clearly cannot go beyond less than 1 fd per child.

**Comment by davidrohr** [comment]
ok, but 1 socket per child sounds more than reasonable, let's see if this helps on the grid

**Pull request merged**
