### PR TITLE
o2-eve: removing EMCAL artefacts, not showing MFT,MCH,MID on Rphi vie…

### PR DESCRIPTION
**Pull request by jmyrcha**
…w (they shadows barrel tracks)

### CODE REVIEW

**Comment by jmyrcha** [comment]
the errors are not related to PR

**Comment by davidrohr** [comment]
`Detectors/ITSMFT/ITS/macros/EVE/DisplayEventsComp.C` seems to fail after this PR

**Comment by jmyrcha** [comment]
ok, I will fix it

**Comment by jmyrcha** [comment]
I will restore previous function for compatibility

**Comment by jmyrcha** [comment]
will do it again

**Pull request closed without merging**
