### PR TITLE
DPL: handle spurious messages when in READY state, take two

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
I managed to reproduce the issue, simply by running `ctest -R ".*mult.*" --verbose` in QC. I also find it puzzling. After adding a couple of debug messages, I can see two distinct behaviours:

* When it works, the transition RUNNING ---> READY does not actually invoke the callback.
* When it does not work, the callback is correctly called, however `NewStatePending()` is always false.

Notice I keep seeing messages, so it's not like my code is stuck, it looks like being in the callback loses some state transitions or alternatively, some callbacks get lost when the state transitioning happens too fast. 
@dennisklein @rbx does that make sense? How is it possible that READY does not drop into RESETTING TASK when running with the static plugin? Shouldn't that transition be automatic?

**Comment by ktf** [comment]
So the reason why sometimes it works it is merely that it gets two sigint, and then it force quits. When it does not quit, it seems to get a single sigint and then it remains stuck in READY. Any idea of what could cause that? Is there a race condition between receiving SIGINT and the AUTO transition?

**Comment by ktf** [comment]
Actually it merely looks like while the RunShutdownSequence() is waiting for the main thread to exit from the callback. I.e., the callback is looping, dropping messages as expected and waiting for a new state:

```
* thread #1, queue = 'com.apple.main-thread', stop reason = next-branch-location
  * frame #0: 0x000000010cecfa1c libO2Framework.dylib`std::__1::__function::__func<o2::framework::specifyExternalFairMQDeviceProxy(char const*, std::__1::vector<o2::framework
::OutputSpec, std::__1::allocator<o2::framework::OutputSpec> > const&, char const*, std::__1::function<void (o2::framework::TimingInfo&, fair::mq::Device&, fair::mq::Parts&,
std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > (o2::framework::OutputSpec const&, unsigned long long)>, unsigned lon
g, bool&)>, unsigned long long, bool)::$_3::operator()(o2::framework::InitContext&) const::'lambda'(o2::framework::ServiceRegistryRef, int), std::__1::allocator<o2::framework
::specifyExternalFairMQDeviceProxy(char const*, std::__1::vector<o2::framework::OutputSpec, std::__1::allocator<o2::framework::OutputSpec> > const&, char const*, std::__1::fu
nction<void (o2::framework::TimingInfo&, fair::mq::Device&, fair::mq::Parts&, std::__1::function<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator
<char> > (o2::framework::OutputSpec const&, unsigned long long)>, unsigned long, bool&)>, unsigned long long, bool)::$_3::operator()(o2::framework::InitContext&) const::'lamb
da'(o2::framework::ServiceRegistryRef, int)>, void (o2::framework::ServiceRegistryRef, int)>::operator()(o2::framework::ServiceRegistryRef&&, int&&) at ExternalFairMQDevicePr
oxy.cxx:525:63 [opt]
```

while the shutdown thread is waiting on some condition variable, I guess for me to exit the callback:

```
    frame #0: 0x0000000184687710 libsystem_kernel.dylib`__psynch_cvwait + 8
    frame #1: 0x00000001846c4574 libsystem_pthread.dylib`_pthread_cond_wait + 1232
    frame #2: 0x00000001845ecef0 libc++.1.dylib`std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
    frame #3: 0x000000010db98a50 libfairmq.1.7.0.dylib`fair::mq::plugins::Control::RunShutdownSequence() [inlined] void std::__1::condition_variable::wait<fair::mq::StateQueue::WaitForNext()::'lambda'()>(this=0x0000000152e048a0, __lk=0x000000016b1ae860, __pred=(unnamed class) @ scalar)::'lambda'()) at __mutex_base:398:9 [opt]
    frame #4: 0x000000010db98a3c libfairmq.1.7.0.dylib`fair::mq::plugins::Control::RunShutdownSequence() [inlined] fair::mq::StateQueue::WaitForNext(this=0x0000000152e04830) at StateQueue.h:34:13 [opt]
    frame #5: 0x000000010db98a2c libfairmq.1.7.0.dylib`fair::mq::plugins::Control::RunShutdownSequence(this=0x0000000152e04770) at Control.cxx:497:33 [opt]
    frame #6: 0x000000010db96a24 libfairmq.1.7.0.dylib`fair::mq::plugins::Control::SignalHandler(this=0x0000000152e04770) at Control.cxx:456:17 [opt]
    frame #7: 0x000000010db99774 libfairmq.1.7.0.dylib`void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (fair::mq::plugins::Control::*)(), fair::mq::plugins::Control*> >(void*) [inlined] decltype(__f=0x00006000036780c8, __a0=0x00006000036780d8).*std::declval<void (fair::mq::plugins::Control::*)()>()()) std::__1::__invoke[abi:v15006]<void (fair::mq::plugins::Control::*)(), fair::mq::plugins::Control*, void>(void (fair::mq::plugins::Control::*&&)(), fair::mq::plugins::Control*&&) at invoke.h:359:23 [opt]
    frame #8: 0x000000010db99758 libfairmq.1.7.0.dylib`void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (fair::mq::plugins::Control::*)(), fair::mq::plugins::Control*> >(void*) [inlined] void std::__1::__thread_execute[abi:v15006]<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (fair::mq::plugins::Control::*)(), fair::mq::plugins::Control*, 2ul>(__t=size=3, (null)=<unavailable>)(), fair::mq::plugins::Control*>&, std::__1::__tuple_indices<2ul>) at thread:290:5 [opt]
    frame #9: 0x000000010db99758 libfairmq.1.7.0.dylib`void* std::__1::__thread_proxy[abi:v15006]<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, void (fair::mq::plugins::Control::*)(), fair::mq::plugins::Control*> >(__vp=0x00006000036780c0) at thread:301:5 [opt]
    frame #10: 0x00000001846c3fa8 libsystem_pthread.dylib`_pthread_start + 148
```

This works by accident in the multinode_test script, because somehow that test issues two sigint everynow and then which silently kills the hanged processes, and it works fine when running in the GUI, because there the shutdown sequence is not handled automatically by FairMQ. @dennisklein @rbx is this expected behaviour?

**Comment by rbx** [comment]
To be honest I cannot follow everything that you described in the first comments - lacking understanding of what you are running and I'm currently out of the office to be able to reproduce it.

But:

> the RunShutdownSequence() is waiting for the main thread to exit from the callback. I.e., the callback is looping, dropping messages as expected and waiting for a new state
> while the shutdown thread is waiting on some condition variable, I guess for me to exit the callback
> This works by accident in the multinode_test script, because somehow that test issues two sigint everynow and then which silently kills the hanged processes, and it works fine when running in the GUI, because there the shutdown sequence is not handled automatically by FairMQ

All of this makes sense and, unless I am missing something, this is how it should work. ShutdownSequence will try to find shortest path to exit and call all intermediate states and handlers, so if one of them blocks it will not proceed (until killed by the second sigint).

If you still suspect an error, try to make a FMQ-only reproducer, then it will be much easier to debug for us.

**Comment by ktf** [comment]
Sorry for the stream of consciousness. Anyway yes, I think the issue is that there is no way for the callback to know when something external has requested a new state. We need a "NewStateRequested()" more than a "NewStatePending()", i.e. something which the control thread sets before waiting to change state, rather than after transition is completed.
@teo @knopers8 That said, I think there is a problem also in how "Control" does the state switching, because I would not expect it to block like it does.

**Comment by ktf** [comment]
@teo @knopers8 do you know what might cause such "blocking" behaviour in ECS?

**Comment by teo** [comment]
I don't fully understand the discussion on FairMQ state machine internals here, the functions mentioned are unfamiliar to me. I don't think AliECS has the power to decide what blocks and what doesn't. All we do is use what the FairMQ plugin API exposes, i.e. `PluginServices::ChangeDeviceState`, `PluginServices::SubscribeToDeviceStateChange`, etc. as described in https://fairrootgroup.github.io/FairMQ/latest/classfair_1_1mq_1_1PluginServices.html

Our control interface with FairMQ is https://github.com/AliceO2Group/Control/blob/master/occ/plugin/OccFMQCommon.cxx#L169

**Comment by ktf** [comment]
I suspect the issue is that indeed ChangeDeviceState:

https://fairrootgroup.github.io/FairMQ/latest/classfair_1_1mq_1_1PluginServices.html#adb2b7857434e48018dfe6b17044dcef9

blocks in a similar way. @rbx @dennisklein could you advise how to proceed? How can we avoid the deadlock?

**Comment by dennisklein** [comment]
Do you see any deadlock, when no `SIGINT` is involved at all?

**Comment by dennisklein** [comment]
> Our control interface with FairMQ is [AliceO2Group/Control@master/occ/plugin/OccFMQCommon.cxx#L169](https://github.com/AliceO2Group/Control/blob/master/occ/plugin/OccFMQCommon.cxx?rgh-link-date=2023-09-04T14%3A27%3A48Z#L169)

I advice not to discard the return value.

**Comment by dennisklein** [comment]
When you catch a deadlock, can you please provide the following information:
* What values were passed to `--control` and `--catch-signals` command-line options, alternatively give the two debug log lines printed [here](https://github.com/FairRootGroup/FairMQ/blob/d1c99f7e150c1177dc1cab1b2adc16475cade24e/fairmq/plugins/control/Control.cxx#L72-L96)?
* Did you send `SIGINT` to the hanging process?
* Did you load any other plugin, which calls [`TakeDeviceControl()`](https://github.com/FairRootGroup/FairMQ/blob/d1c99f7e150c1177dc1cab1b2adc16475cade24e/fairmq/PluginServices.h#L93C10-L93C22) or [`StealDeviceControl()`](https://github.com/FairRootGroup/FairMQ/blob/d1c99f7e150c1177dc1cab1b2adc16475cade24e/fairmq/PluginServices.h#L101)? (if yes, which and link to source code)
* Was there an error or an uncaught (from your code) exception that fmq has seen?
* Does your device code (not plugin code) call `ChangeState()` anywhere?

I tried to read your code, but I cannot follow it. I missed too many concepts over time. DPL's DeviceProxys, raw, external, uvloop and all the wrapper code. I am lost there, sry. A much simpler reproducer would be helpful, but that may be hard to find?

Should we schedule an interactive debugging session with alexey and me? Not sure how else to proceed.

**Comment by ktf** [comment]
To simplify the issue:

```
device->SubscribeToStateChange([](...) {
  while (true) {
    device->Receive(parts);
    if (device->HasNewStatePending()) {
      break;
    }
  }
}
```

deadlocks with ChangeDeviceState, because the latter waits for the callback to finish before changing the state.

**Comment by rbx** [comment]
For this type of blocking things there are state handlers: Run(), InitTask(), etc...
Indeed, blocking in SubscribeToNewTransition will lead to a deadlock.

https://github.com/FairRootGroup/FairMQ/blob/master/fairmq/StateMachine.cxx#L111-L112

**Comment by dennisklein** [comment]
~~Yes, all our `SubscribeTo*` APIs should be used with fast-completing, non-blocking callbacks.~~  edit: well, forget that, not even true.

**Comment by ktf** [comment]
The suggestion to use the state transition came from @dennisklein, see https://gist.github.com/dennisklein/4064e4aac948be5cea37aa861b03635d. 

So, how should I drain messages while in ready state?

**Comment by dennisklein** [comment]
> So, how should I drain messages while in ready state?

Hm, do it as in my example snippet? :P see `SubscribeTo**StateChange**()`. `SubscribeToNewTransition()` informs you about the event when some controller called `ChangeState()` which is usually during the previous state.

**Comment by ktf** [comment]
I am afraid I already did. The pseudo code above was wrong, corrected. Any more thoughts?

**Comment by dennisklein** [comment]
I mean, do you have fmq debug logs of a hanging device?

**Comment by dennisklein** [comment]
> When it does not work, the callback is correctly called, however `NewStatePending()` is always false.

I added another simplified patch to https://gist.github.com/dennisklein/4064e4aac948be5cea37aa861b03635d, with that I cannot replicate the above observation. What should I change to match your setup better?

**Comment by ktf** [comment]
To reproduce the issue you can use the code below, which is FairMQ only and hangs with both `--control static` and `--control dynamic`. You can run it with:

```
o2-test-deadlock --channel-config "name=data,type=sub,method=bind,address=ipc://127.0.0.1,rateLogging=0" --id foo --transport zeromq --control static
```

and it will hang just like my more complex reproducer. I have not created a custom plugin, but I think it will hang also in that case. I would say we need a way to tell when a new state is about to be requested, so that we can exit the while loop.

```c++
// Copyright 2019-2020 CERN and copyright holders of ALICE O2.
// See https://alice-o2.web.cern.ch/copyright for details of the copyright holders.
// All rights not expressly granted are reserved.
//
// This software is distributed under the terms of the GNU General Public
// License v3 (GPL Version 3), copied verbatim in the file "COPYING".
//
// In applying this license CERN does not waive the privileges and immunities
// granted to it by virtue of its status as an Intergovernmental Organization
// or submit itself to any jurisdiction.

#include <fairmq/Device.h>
#include <fairmq/runDevice.h>

#include <string>

namespace bpo = boost::program_options;

void addCustomOptions(bpo::options_description& options)
{
}

struct Deadlocked : fair::mq::Device
{
    Deadlocked()
    {
      auto stateWatcher = [this](fair::mq::State newState) {
        static bool first = true;
        LOG(info) << "State changed to " << newState;
        if (newState != fair::mq::State::Ready) {
          LOG(info) << "Not ready state, ignoring";
          return;
        }
        if (first) {
          first = false;
          return;
        }
        fair::mq::Parts parts;
        LOG(info) << "Draining messages" << std::endl;
        auto &channels = this->GetChannels();
        LOG(info) << "Number of channels: " << channels.size();
        if (channels.size() == 0) {
          LOG(info) << "No messages to drain";
          return;
        }
        auto &channel = channels.at("data")[0];
        while (this->NewStatePending() == false) {
          channel.Receive(parts, 10);
          if (parts.Size() != 0) {
            LOG(info) << "Draining" << parts.Size() << "messages";
          }
        }
        LOG(info) << "Done draining";
      };
      this->SubscribeToStateChange("drain", stateWatcher);
    }

    void Run() override
    {
        LOG(info) << "Simply exit";
    }
};


std::unique_ptr<fair::mq::Device> getDevice(fair::mq::ProgOptions& /*config*/)
{
    return std::make_unique<Deadlocked>();
}
```

**Comment by ktf** [comment]
Actually, dynamic works, static hangs.

**Comment by ktf** [comment]
I would propose https://github.com/FairRootGroup/FairMQ/pull/481 to solve the callback ordering issue. With it my reproducer works with the static control (after prefixing the callback name with "99-").

I think however this might still break in case there are two long running callbacks. To be checked.

**Comment by ktf** [comment]
Updated with unit test to verify that the callbacks work as expected. This will need a FairMQ with the above PR.

**Comment by ktf** [comment]
QC multinode_test consistently works in my local setup.

**Comment by ktf** [comment]
This PR needs https://github.com/alisw/alidist/pull/5128 to actually work.

**Comment by ktf** [comment]
@knopers8 Shall we merge this? In any case it should be protected by the command line option and by the fact we do cherry-picks for the HI run, no?

**Comment by knopers8** [comment]
> @knopers8 Shall we merge this? In any case it should be protected by the command line option and by the fact we do cherry-picks for the HI run, no?

In QC we overwrite the default for the option `ready-state-policy` programmatically, so it's not so simple to switch it off, but indeed we were asked not to bring it to HI branch for the time being.

I did not see the side effects from earlier (stuck when stopping a run), so I think we can merge.

**Comment by ktf** [comment]
Ok, merging this. It should be safe in any case now.

**Pull request merged**
