### PR TITLE
DPL: propagate the DataHeader::runNumber information

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 apparently no one propagated the information about DataHeader::runNumber to DPL when it was added. This should fix it (not tested as I need to recompile the whole stack right now).

**Comment by shahor02** [comment]
@ktf thanks! will test it

**Review by shahor02 — APPROVED** [review]
Now works fine, thanks!

**Comment by ktf** [comment]
Tested locally on mac. Full CI works.

**Pull request merged**
