### PR TITLE
Move FIT data formats to DataFormats/Detectors, use InteractionRecord

### PR DESCRIPTION
**Pull request by shahor02**
Hi @AllaMaevskaya @mslupeck @mbroz84 , 
I have moved all persistent FIT data format classes to ``DataFormats/Detectors/FIT`` and also suppressed duplicate MCLabel header files.
Additionally, I've substituted the separate ``mBC`` and ``mOrbit`` data members in FIT related classes by the ``o2::InteractionRecord`` struct which provides the same info + some functionality like comparison of IR.
Please confirm that this is ok, so that afrer the merging I can work on the QED digitization.

Cheers,
 Ruben

### CODE REVIEW

**Comment by mslupeck** [comment]
Hi @shahor02,
To me these changes look fine, but the only person, who can make the final decision is Alla. Since it's the holiday period in Russia now (1st-of-May) it will probably take her some time to check it up.

**Comment by shahor02** [comment]
Thanks @mslupeck , I know that in Russia 1st of May is much more than 1st of May ...

**Comment by AllaMaevskaya** [comment]
Hello
Thank you so much! I agree with your changes.
The only comments: 
- why you remove FITsimulation bucket and replaced it with T0, V0 and FDD? We supposed that T0 and V0 will have common parts. Could we  keep all of them?
- DigitizerTask class is obsolete if we use DigitizerWorkflow, yes?
- Channel struct in RecPoints class is really obsolete and can be removed
Best regards
Alla

**Comment by shahor02** [comment]
Hi @AllaMaevskaya 
 
>     * why you remove FITsimulation bucket and replaced it with T0, V0 and FDD? We supposed that T0 and V0 will have common parts. Could we keep all of them?

Sorry, I did not understand what you refer to: the FITsimulation bucket is there, I've just moved the persistent data format classes to DataFormats/Detectors/FIT, in a common for all 3 subdetectors `` data_format_fit_bucket``. 

BTW, I just noticed that the V0Simulation/Hits class remained  ``O2/Detectors``, to avoid name clashes I will add sub-detector directories is ``DataFormats/Detectors/FIT`` (but with one common library). 
But then I don't understand what is really common and what is det.specific? In the original code you have in ``FIT/common/simulation/include/FITSimulation/`` the ``HitType`` and ``MCLabel`` classes. Currently, the ``HitType` is used by the T0 only, while V0 defines its own Hit class. So, should not the ``HitType`` be in T0-specific directory? And is the ``MCLabel`` indeed common for all sub-detectors?

The same applied to ``common/simulation/src/Digitizer``: currently it is doing T0 only, will it be doing also V0, FDD digitization or these will be separate classes ?


>     * DigitizerTask class is obsolete if we use DigitizerWorkflow, yes?
Yes, shall I suppress it?

>     * Channel struct in RecPoints class is really obsolete and can be removed
OK, removed.

Cheers,
 Ruben

**Comment by AllaMaevskaya** [comment]
OK, thank you.
Lets merge it, I implemented realistic signal shape and merge it with Friday dev. When your changes will be in dev, I will merge it again and make pull request.

Best regards
Alla

**Comment by shahor02** [comment]
Hi @AllaMaevskaya ,
Before it is merged, could you tell me which classes are supposed to be common for all FIT subdetectors?
Cheers,
 Ruben

**Comment by AllaMaevskaya** [comment]
I know nothing about FDD.
T0 and V0 have common 
- support structure, so it will be common/simulation/Detector;
- similar read-out electronics - I think will be common part of Digitizer  with detector specific parameters ( 
but should be decide later, when Jacek's guys will start to work), and Digits.
All these are under discussion now.

Best regards
Alla

**Comment by shahor02** [comment]
OK, then I will split data type to per-detector directories + common, like it is done for ITS and MFT.

**Comment by sawenzel** [comment]
@dberzano : All travis jobs seem to fail due to a new doxygen problem.

**Pull request merged**
