### PR TITLE
Change CMake to handle dependencies using "buckets"

### PR DESCRIPTION
**Pull request by Barthelemy**
So far we have 3 modules using the new scheme :
- CCDB
- Examples/ExampleModule1 (new)
- Examples/ExampleModule2 (new)

Basic concepts and files
In top cmake :
- O2Utils.cmake : macros and functions.
- O2Dependencies.cmake : prepares the dependencies and buckets, called in top CMakeLists.txt
In the modules :
- O2_SETUP : necessary to register the module in O2, sets the proper include directories.
- O2_GENERATE_LIBRARY : generate the library of a module.
- O2_GENERATE_EXECUTABLE : generate executables.

Tested on SLC6.

### CODE REVIEW

**Comment by Barthelemy** [comment]
Jenkins is failing because the build set up has ROOT 5 and not ROOT 6. Maybe @ktf can do something about it ?

**Comment by ktf** [comment]
Doh, I forgot to update the PR tests. Looking into it.

**Comment by ktf** [comment]
Should be done in #117 .

**Comment by Barthelemy** [comment]
For some reason the build still fails due to ROOT5 being picked up

**Comment by ktf** [comment]
Ciao, looks like you are still missing `-ldl`, no? I've started a new build, but that really looks like the actual issue.

**Comment by Barthelemy** [comment]
Hi, 
It is not a problem with a missing -ldl, I think. It complains about an AliRoot library that is missing some symbols. What I need is either a fix in AliRoot or a way to reproduce the build using docker. 
Cheers,
Barth

**Comment by MohammadAlTurany** [comment]
Hi Barth,

For me your branch does not compile, could we meet to discuss about how you handle the dependancies and includes paths centrally in the buckets?

best,

Mohammad

On 23 Jun 2016, at 13:35, Barthélémy von Haller <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi,
It is not a problem with a missing -ldl, I think. It complains about an AliRoot library that is missing some symbols. What I need is either a fix in AliRoot or a way to reproduce the build using docker.
Cheers,
Barth

**Pull request closed without merging**
