### PR TITLE
Replace commandline argument parsing in o2Eve with boost::program_options

### PR DESCRIPTION
**Pull request by pnwkw**

### CODE REVIEW

**Comment by shahor02** [comment]
@pnwkw could you resolve conflicts and pass the PR via clang-format?

**Comment by pnwkw** [comment]
I'll resolve the conflict, but I don't accept the change clang-format proposes, as it makes the configuration unreadable.

**Comment by shahor02** [comment]
You can silence clang-format by formatting it as 
```
  eveOptions.add_options()(
    "help,h", "produce help message")(
    "datafolder,d", bpo::value<typeof(this->mDataFolder)>()->default_value("./"), "name of the data folder")(
    "filename,f", bpo::value<typeof(this->mFileName)>()->default_value("data.root"), "name of the data file")(
    "json,j", bpo::value<typeof(this->mJSON)>()->zero_tokens()->default_value(false), "use json files as a source")(
    "memorylimit,m", bpo::value<typeof(this->mMemoryLimit)>()->default_value(-1), "memory usage limit (MB) - app will terminate if it is exceeded (pass -1 for no limit)")(
    "online,o", bpo::value<typeof(this->mOnline)>()->zero_tokens()->default_value(false), "use online json files as a source")(
    "optionsfilename,p", bpo::value<std::string>()->default_value("o2eve.json"), "name of the options file")(
    "randomtracks,r", bpo::value<typeof(this->mRandomTracks)>()->zero_tokens()->default_value(false), "use random tracks")(
    "saveddatafolder,s", bpo::value<typeof(this->mSavedDataFolder)>()->default_value(""), "name of the saved data folder");
```

**Comment by pnwkw** [comment]
Thanks for the suggestion, this is a sensible solution to the problem. I've included it.

**Review by shahor02 — DISMISSED** [review]
Conditionally approving to trigger CI

**Review by shahor02 — APPROVED** [review]
Again approving conditionally to trigger a CI

**Review by shahor02 — APPROVED** [review]
CI failure is unrelated, merging

**Pull request merged**
