### PR TITLE
Patch panel v3

### PR DESCRIPTION
**Pull request by carlos-soncco**

### CODE REVIEW

**Comment by sawenzel** [comment]
Please fix the formatting.

**Comment by sawenzel** [comment]
@frmanso @bovulpes : Can you approve please?

**Comment by frmanso** [comment]
Yes it's fine, we can go further. Just to merge this class with the latest GeometryBuilder (new part provided by Rodrigo related to the MFT barrel).

**Comment by sawenzel** [comment]
This PR is providing commits which are already in dev. Please rebase your work on the dev branch correctly.

**Comment by davidrohr** [comment]
The new branch here still contains a lot of commits already in dev. Could you please rebase properly.

**Comment by sawenzel** [comment]
@carlos-soncco : Please do
a) on the dev branch: `git pull --rebase origin dev`
b) `git checkout patch-panel-v3`
c) `git rebase dev`
d) push your branch again here

This should just leave commits made by you in this PR.

**Pull request merged**
