### PR TITLE
Cmake migration

### PR DESCRIPTION
**Pull request by aphecetche**
I guess this work is now ready enough to be discussed for real merging. 

Need https://github.com/alisw/alidist/pull/1724 beforehand, though, otherwise o2suite won't build.

### CODE REVIEW

**Comment by davidrohr** [comment]
@aphecetche @ktf : Can it be that the CI server for build/o2checkcode/o2 does not have simulation packages pythia and geant? Or why is it failing?

**Comment by ktf** [comment]
Mmm... Pythia and geant3 we build our own, so I would say no, it's not possible.

**Comment by aphecetche** [comment]
As far as I can tell from the logs of other PRs, indeed it seems the CI workers for o2checkcode don't seem to find simulation related packages. Which is a thing I kind of knew, but then overlooked.

Now this is a bit of a problem because in my cmake-migration I now have a BUILD_SIMULATION option (that is ON by default). If that one is set then missing simulation-related packages (pythia6,pythia,geant3,geant4,geant4vmc...) is considered a fatal error.

So the options are : 
1. add the simulation dependencies to the CI workers for o2checkcode or make them aware of the existing deps if they are indeed there
2. add the -DBUILD_SIMULATION=OFF for the o2checkcode builds
3. = ~2, i.e. make BUILD_SIMULATION=OFF the default in this PR and change o2.sh to set BUILD_SIMULATION=ON

(I would avoid 3)

In any case, it seems I kind of failed my initial goal of fitting within the existing CI boundaries ;-)

**Comment by ktf** [comment]
BTW, is this actually doing some magic instead of relying on the Cmake command line options? If yes, I think this is a terrible idea...

**Comment by aphecetche** [comment]
I don't know exactly what you consider magic, but there is indeed a piece of [adapter cmake code](https://github.com/aphecetche/AliceO2/blob/cmake-migration/dependencies/O2RecipeAdapter.cmake), to make the thing works with the _current_ o2.sh,  as I did not want to have to change the recipe to get this one working (but eventually the o2 recipe will have to be changed a bit)

That adapter's working fine on my tests under CentOS, macOS and Ubuntu. The macOS CI seems to agree as well. I would wait for the O2/o2 to pick the right QC so see if the issue is limited to o2checkcode before jumping to conclusions.

**Comment by aphecetche** [comment]
There is also something strange in the Travis CI, which complains about files which are no longer in the code (e.g. Examples/ExampleModule1/src/Foo.cxx)

**Comment by ktf** [comment]
Ah, ok, I missed it's something temporary. As long as nothing overrides `-D` options in the final version, I am fine (of course, dropping the options or changing them is also fine).

**Comment by ktf** [comment]
I would make `BUILD_SIMULATION=OFF` by if pythia and co are not found, and `BUILD_SIMULATION=ON` if they are found. If people specify on the command line `-DBUILD_SIMULATION=ON`, then you complain. I.e. never have an implicit flag which requires explicit configuration to work correctly.

**Comment by aphecetche** [comment]
well, it's not an implicit flag, it's an option (granted, should document the few options we have somewhere, but all are defined in https://github.com/aphecetche/AliceO2/blob/cmake-migration/cmake/O2DefineOptions.cmake)

I get the impression that _computing_ the option value (from the presence or not of some packages) is the implicit think that we should not do (i.e. we disagree on this one ;-) )

Anyway, before changing anything, I am running a bit blind on the CI side : I think I've seen the build/O2/o2 ran again but fail again (as the QC version it's picking is still the old one). Is there a way to see when it was attempted last and/or to know when it will be attempted again ?

**Comment by ktf** [comment]
It's implicit in the sense that you do not need to pass it on command line. What happens in general with well behaved configure / cmake using software is the following:

* Things work if you just say "./configure" or "cmake ." with some configuration which is compatible with your system.
* If you specify an option explicitly, boundary conditions for that option are checked and you get an error if they are not satisfied.

IMHO, diverging from this behavior, like you are doing here, might be debatably better but it's for sure not what happens in general, so I would avoid doing so.

**Comment by ktf** [comment]
... or if you prefer: "if something is optional, it's off by default" is also a viable solution.

**Comment by aphecetche** [comment]
indeed, I first tried the optional=off approach (which I like) but with it the current CI would behave differently as of now, i.e. it would not build the simulation dependent parts (as the BUILD_SIMULATION is not part of the o2.sh recipe) ...

**Comment by ktf** [comment]
Ok, but then I would keep the original behavior (which is what in general configure / cmake do for implicitly on options). Switching to "implicitly off" will then be just a matter of changing ON to OFF in the default value.

**Comment by aphecetche** [comment]
Now I'm confused... (will have to go to lunch and get some sugar in my brain ;-) ) Do you propose that BUILD_SIMULATION is set to ON by default (which it is, btw) and set to OFF if simulation parts are not found, i.e. we gracefully build whatever the case may be ? (instead of bailing out as I do now ?)

**Comment by davidrohr** [comment]
I would suggest auto-detect if no command line option is present. Only if the command line option is ON, fail if the packages are not found.

**Comment by ktf** [comment]
In general the behaviour is:

* Implicit ON => Autodetect and silently pass if not found 
* Implicit OFF => Disable
* Explicit ON => Detect and fail if not found
* Explicit OFF => Disable

Then you decide whether you want the default to be ON or OFF, but the behaviour described above is always the same.

**Comment by aphecetche** [comment]
ok, will try to change the logic.

**Comment by aphecetche** [comment]
here's a try with a re-worked BUILD_SIMULATION logic. 

(concerning the commits : once everything is green I'll get back to the 3 commits initial idea : the cmake* stuff itself, the documentation, and the actual source C++ code that had to be touched)

**Comment by aphecetche** [comment]
@kft the build/O2/o2 is in "expected" mode since a long time, is there any issue ?

**Comment by dennisklein** [comment]
I have one more bugfix and one more proposal for `add_root_directory`:

**Bugfix**: Absolute path argument leads to hardcoded build paths in rootmap files which is not what we want.
```diff
diff --git a/cmake/AddRootDictionary.cmake b/cmake/AddRootDictionary.cmake
index d4428a8ac..50f996fbb 100644
--- a/cmake/AddRootDictionary.cmake
+++ b/cmake/AddRootDictionary.cmake
@@ -131,7 +131,7 @@ function(add_root_dictionary target)
       ${dictionaryFile}
       -inlineInputHeader
       -rmf ${rootmapFile}
-      -rml $<TARGET_FILE:${target}>
+      -rml $<TARGET_FILE_NAME:${target}>
       $<GENEX_EVAL:-I$<JOIN:$<TARGET_PROPERTY:${target},INCLUDE_DIRECTORIES>,\;-I>>
       # the generator expression above gets the list of all include
       # directories that might be required using the transitive dependencies
```

**Proposal**: Rename `G__<LIB>_rdict.pcm` to `lib<LIB>_rdict.pcm` (This is following the convention how ROOT6 names its pcm files):
```diff
diff --git a/cmake/AddRootDictionary.cmake b/cmake/AddRootDictionary.cmake
index d4428a8ac..7d45579ec 100644
--- a/cmake/AddRootDictionary.cmake
+++ b/cmake/AddRootDictionary.cmake
@@ -101,7 +101,8 @@ function(add_root_dictionary target)
   endif()
   set(dictionary G__${basename})
   set(dictionaryFile ${CMAKE_CURRENT_BINARY_DIR}/${dictionary}.cxx)
-  set(pcmBase ${dictionary}_rdict.pcm)
+  set(pcmTarget lib${basename})
+  set(pcmBase ${pcmTarget}_rdict.pcm)
   set(pcmFile ${lib_output_dir}/${pcmBase})
   set(rootmapFile ${lib_output_dir}/lib${basename}.rootmap)

@@ -132,6 +133,7 @@ function(add_root_dictionary target)
       -inlineInputHeader
       -rmf ${rootmapFile}
       -rml $<TARGET_FILE:${target}>
+      -s ${pcmTarget}
       $<GENEX_EVAL:-I$<JOIN:$<TARGET_PROPERTY:${target},INCLUDE_DIRECTORIES>,\;-I>>
       # the generator expression above gets the list of all include
       # directories that might be required using the transitive dependencies
```

Now:
```
└── lib64
    ├── G__testlib_rdict.pcm
    ├── libtestlib.rootmap
    └── libtestlib.so
```
vs proposed:
```
└── lib64
    ├── libtestlib_rdict.pcm
    ├── libtestlib.rootmap
    └── libtestlib.so
```

**Comment by dennisklein** [comment]
Maybe offtopic, not sure: Can someone enlighten me why the build paths are baked into these pcm files?

e.g.
```
╭─dklein@gamma ~/projects/AliceO2/test ‹ruby-2.6.0› ‹cmake-migration*›
╰─➤  strings ~/alice/sw/fedora30_x86-64/FairRoot/latest/lib/G__BaseDict_rdict.pcm | grep BUILD
TFileh/home/dklein/alice/sw/BUILD/6645368508eba6377cfd84d95691480eb41f5e4d/FairRoot/base/G__BaseDict_rdict.pcm
h/home/dklein/alice/sw/BUILD/6645368508eba6377cfd84d95691480eb41f5e4d/FairRoot/base/G__BaseDict_rdict.pcm
TFileh/home/dklein/alice/sw/BUILD/6645368508eba6377cfd84d95691480eb41f5e4d/FairRoot/base/G__BaseDict_rdict.pcm
TFileh/home/dklein/alice/sw/BUILD/6645368508eba6377cfd84d95691480eb41f5e4d/FairRoot/base/G__BaseDict_rdict.pcm
╭─dklein@gamma ~/projects/AliceO2/test ‹ruby-2.6.0› ‹cmake-migration*›
╰─➤  strings ~/alice/sw/fedora30_x86-64/ROOT/latest/lib/libEve_rdict.pcm | grep BUILD
TFile^/home/dklein/alice/sw/BUILD/17fe86512615f50b92686cb41c298606a5967038/ROOT/lib/libEve_rdict.pcm
^/home/dklein/alice/sw/BUILD/17fe86512615f50b92686cb41c298606a5967038/ROOT/lib/libEve_rdict.pcm
TFile^/home/dklein/alice/sw/BUILD/17fe86512615f50b92686cb41c298606a5967038/ROOT/lib/libEve_rdict.pcm
TFile^/home/dklein/alice/sw/BUILD/17fe86512615f50b92686cb41c298606a5967038/ROOT/lib/libEve_rdict.pcm
```

It seems this is already the case for ROOT's own pcm files. Makes me wonder what is the purpose of these files? I thought they were some kind of ROOT-style precompiled headers?

**Comment by aphecetche** [comment]
@dennisklein I've applied your first fix (the relative build path for root map). The other one can wait a bit I guess.

**Comment by aphecetche** [comment]
Well, removal of `BASENAME` parameter of `add_root_dictionary` at this stage was not such a good idea after all ;-) as QC uses it... My bad. Added a protection.

**Comment by aphecetche** [comment]
One (last?) fix removing one test macro when pythia8 is missing (of o2checkcode).

**Comment by davidrohr** [comment]
@aphecetche You could also run git-clang-format once and fix the codacy warnings, should only take 1 minute

**Comment by aphecetche** [comment]
@davidrohr well the codacy stuff is kind in conflict with my current markdown editor plugin. Do you know what kind of remarkjs configuration it is using ?

**Comment by davidrohr** [comment]
no idea, sorry. That is indeed kind of annoying, but I'd still go with the style as suggested by codacy, otherwise the next PR that modifies the file will get the warnings again.

**Comment by aphecetche** [comment]
Agreed. Maybe @ktf know how codacy is configured for markdown / to replicate that locally ?

**Comment by davidrohr** [comment]
@dberzano @mconcas : Do you have any idea why the build/o2/cuda CI is failing here. Error seems unrelated to CUDA, but G4clhep is not found. I am wondering what is different wrt to build/O2/o2?

**Comment by aphecetche** [comment]
wrt Codacy : I thought I had remark-cli installed but in fact I had not. So now maybe my editor has a chance to get the right formatting. Will try for the next commit.

**Comment by aphecetche** [comment]
@davidrohr  Seems the o2checkcode is now failing with : 

```
Error while processing /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/GPU/GPUTracking/Base/GPUReconstruction.cxx.
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/GPU/GPUTracking/Base/GPUReconstruction.cxx:31:10: error: 'omp.h' file not found [clang-diagnostic-error]
#include <omp.h>
```

**Comment by davidrohr** [comment]
@aphecetche : Indeed, I encountered this before, and I couldn't fix it so I gave up. Our O2CodeChecker for some reason will not find omp.h. Normally, for GCC, you'll have to append -fopenmp, but when I tried it with the CodeChecker, it didn't work. Also, one cannot `// NOLINT` includes. If you want, you can give it a try, but for the time being, I'd ignore it. Will only be triggered when AliGPUReconstruction.cxx is changed. Next time I do it, I guess I'll have to find a proper solution.

**Comment by ktf** [comment]
> Agreed. Maybe @ktf know how codacy is configured for markdown / to replicate that locally ?

I think they use: https://github.com/codacy/codacy-remark-lint. What is also interesting is the fact you can run your own checks in codacy. Maybe we should explore that...

**Comment by aphecetche** [comment]
Added missing copyrights (in new example code) o2checkcode was complaining about. Attempt to fix the Codacy stuff as well.

**Comment by aphecetche** [comment]
Well, it's getting frustrating : I can't get locally the same o2checkcode error  : 

```
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/DataFormats/Detectors/FIT/T0/src/RecPoints.cxx:42:9: error: using integer absolute value function 'abs' when argument is of floating point type [clang-diagnostic-absolute-value]
```

what I'm doing is : 

```
export ALIBUILD_BASE_HASH=6c62d81665a0d7cf451b5dfa89a5593e30f88395
aliBuild --defaults o2 build o2checkcod
```

and it's happy : 

```
==> Build of o2checkcode successfully completed on `macbook-pro-de-laurent.home'.
    Your software installation is at:

      /Users/laurent/alice/cmake/sw/osx_x86-64

    You can use this package by loading the environment:

      alienv enter o2checkcode/latest-o2

==> Build directory for devel package O2:
    /Users/laurent/alice/cmake/sw/BUILD/O2-latest/O2
```

while the CI is not ...

( I'm setting the BASE_HASH otherwise I get errors from DebugGUI )

**Comment by davidrohr** [comment]
The codechecker will take the compile commands from the last compilation database. I.e  if you build o2 before incrementally, it will only check the files from the last incremental build.

**Comment by davidrohr** [comment]
@aphecetche : actually I think the omp.h error is not even treated as real error, it is ignored like all the system header errors. The only error that is listed in the summary is in fact:

/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/DataFormats/Detectors/FIT/T0/src/RecPoints.cxx:42:9: error: using integer absolute value function 'abs' when argument is of floating point type [clang-diagnostic-absolute-value]

**Comment by aphecetche** [comment]
> The codechecker will take the compile commands from the last compilation database. I.e if you build o2 before incrementally, it will only check the files from the last incremental build.
> […](#)

To be sure I get this straight : the compile_commands.json always contains all commands, but `o2checkcode.sh` "thins" it down, right ? 

Looking at the [output log](https://github.com/AliceO2Group/AliceO2/files/3372837/log.txt) of `ALIBUILD_BASE_HASH=6c62d81665a0d7cf451b5dfa89a5593e30f88395 aliBuild --defaults o2 build o2checkcode` it seems the set of (32) files to be checked is indeed correct (i.e. source code changes wrt ALIBUILD_BASE_HASH I requested) : 

```
++ O2_CHECKCODE_CHANGEDFILES=Algorithm/test/headerstack.cxx:DataFormats/Detectors/FIT/T0/src/RecPoints.cxx:Detectors/ITSMFT/ITS/tracking/include/ITStracking/Definitions.h:Detectors/TPC/base/src/Mapper.cxx:Detectors/TPC/simulation/include/TPCSimulation/Digitizer.h:Examples/Ex1/include/Ex1/A.h:Examples/Ex1/src/A.cxx:Examples/Ex1/src/B.cxx:Examples/Ex1/src/B.h:Examples/Ex2/include/Ex2/A.h:Examples/Ex2/src/A.cxx:Examples/Ex2/src/B.cxx:Examples/Ex2/src/B.h:Examples/Ex2/src/Ex2LinkDef.h:Examples/Ex3/include/Ex3/A.h:Examples/Ex3/src/A.cxx:Examples/Ex3/src/B.cxx:Examples/Ex3/src/Bh:Examples/Ex3/src/Ex3LinkDef.h:Examples/Ex3/src/run.cxx:Examples/Ex4/include/Ex4/A.h:Examples/Ex4/src/A.cxx:Examples/Ex4/src/B.cxx:Examples/Ex4/src/B.h:Examples/Ex4/src/Ex4LinkDef.h:Examples/Ex4/src/run.cxx:Examples/Ex4/test/test1.cxx:Examples/Ex4/test/test2.cxx:Examples/Ex5/src/run.cxx:GPU/GPUTracking/Standalone/qconfigoptions.h:GPU/GPUTracking/Standalone/standalone.cxx:run/o2sim_parallel.cxx
``` 

And indeed the culprit `DataFormats/Detectors/FIT/T0/src/RecPoints.cxx` is there.

Then I see 53 (why not just 32 ?) calls to O2codecheck, including one with `RecPoints.cxx`. But still no error ?

**Comment by davidrohr** [comment]
Without being 100% sure, I think the compile_commands.json contains the commands from the last build. It is further thinned down by o2checkcode.sh. If a file was not build in the last incremental build, I think the code checker will not check it.
At least, in order to run the code checker on all source files, I had to wipe the build directory beforehand to trigger a full rebuild.
But in any case, I think you could just easily fix that single error in /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/DataFormats/Detectors/FIT/T0/src/RecPoints.cxx and it should pass.
And I'd do a clang-format, to avoid another C.I. iteration only for clang-format at the end.

**Comment by aphecetche** [comment]
@davidrohr I can (and have) of course fix the RecPoints.cxx but locally I get other errors too, so I'm clearly not able to properly test this locally. 

For clang-format that's the same misery : I have to tweak the repository  .clang-format otherwise I get : 

```
[ cmake ]~/alice/cmake/O2 [cmake-migration] $ git-clang-format --commit=6c62d81665a0d7cf451b5dfa89a5593e30f88395
Configuration file(s) do(es) not support Proto: /Users/laurent/alice/cmake/O2/.clang-format
error: `clang-format -lines=1:2 CCDB/src/request.proto` failed
[ cmake ]~/alice/cmake/O2 [cmake-migration] $ git-clang-format --diff --commit=6c62d81665a0d7cf451b5dfa89a5593e30f88395 --binary=$HOME/alice/cmake/sw/osx_x86-64/Clang/latest/bin/clang-format
Configuration file(s) do(es) not support C++: /Users/laurent/alice/cmake/O2/.clang-format
error: `/Users/laurent/alice/cmake/sw/osx_x86-64/Clang/latest/bin/clang-format -lines=12:12 -lines=19:24 -lines=30:31 -lines=43:43 DataFormats/Detectors/FIT/T0/src/RecPoints.cxx` failed
``` 

I assume the clang-format configuration file used by Travis is indeed `.clang-format` of this repo, right ?

**Comment by davidrohr** [comment]
@aphecetche : For clang-format, yes, it is .clang-format. However, travis runs git-clang-format, which in some corner cases yields different results wrt. clang-format. If you do `git-clang-format origin/dev`, you should get the same results.

For the codechecked, I am not so sure. As I said, when you run without the HASH... env variable with a clean O2 build dir, you'll get all codechecker errors. However, the only one I see in the CI is the RecPoints.cxx, so if you fix that, I assume the CI will pass.

**Comment by davidrohr** [comment]
ah, sorry, just recognized that you ran git-clang-format. Then I have no idea. For me it works. You need the same clang version of course, which is clang 8 for travis.
Alternatively, you can just copy the patch from the travis output and apply as patch file.

**Comment by aphecetche** [comment]
Well, the last line of the Travis log says Clang 7, not 8 ... https://travis-ci.com/AliceO2Group/AliceO2/jobs/214341661

Anyway, I've made the modifications, will try to push again...

**Comment by davidrohr** [comment]
hm, that is weird. Some lines before, it says `echo "Running clang-format-8`... who knows :)

**Comment by aphecetche** [comment]
Indeed, the command which is ran is git-clang-format-8 . 
Anyway, on my machine it's now ok with clang 7 or clang 8, whatever.

**Comment by davidrohr** [comment]
nice, this looks good finally!

**Comment by aphecetche** [comment]
yep, but the jury's still out for the main part (build/O2/o2) ;-)

**Comment by davidrohr** [comment]
yes, but that was green before I remember
@ktf: How do we proceed if it passes? I'd merge it ASAP, such that @aphecetche is still around for a short time so we can blame him for whatever he broke :|
Or are there any more changes to be included?

**Comment by ktf** [comment]
It's fine with me. @ihrivnac should have the final call, though.

**Comment by aphecetche** [comment]
@ktf ok, there's now a new conflict to be resolved ...  but besides that, is that normal that the `O2/o2` build takes so long ?

**Comment by davidrohr** [comment]
I think the CI is stuck again. #2171 is in "expected" since 9 hours

**Comment by aphecetche** [comment]
Indeed the CI (at least for O2/o2) seems kind of stuck ...

**Comment by davidrohr** [comment]
The O2/o2 CI for #2171 has just finished after 11 hours, so there is hope :|

**Comment by ihrivnac** [comment]
I tried to build locally (on my MAC) this PR and I am getting errors of this kind
```
-- Configuring done
CMake Error at cmake/O2AddLibrary.cmake:69 (add_library):
  Target "O2lib-MathUtils" links to target "Vdt::Vdt" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
Call Stack (most recent call first):
  Common/MathUtils/CMakeLists.txt:11 (o2_add_library)
...
```
And this error then repeats for many targets (the error messages take ~ 3000 lines). I updated alidist to master; is there anything else what can be missing?

**Comment by aphecetche** [comment]
Hi Ivana. That is suspicious : there is indeed an issue with the vdt target, that I'm currently "patching" in our [FindROOT.cmake](https://github.com/aphecetche/AliceO2/blob/cmake-migration/dependencies/FindROOT.cmake) but the target name is vdt lowercase. Are you building with a custom Root ?

**Comment by aphecetche** [comment]
@davidrohr @kft Finally all green ! (well, except the usual o2-dev-fairroot, of course ;-) )

**Comment by davidrohr** [comment]
I think Vdt is not used in O2 itself, but ROOT uses it (and usually brings a builtin version). So I would assume this target is imported by some dependency. Are you sure you don't have any development builts? In particular ROOT? Don't know what else could depend on Vdt

**Comment by davidrohr** [comment]
Yes, finally, nice work!
But I guess now this Vdt issue should be understood :|
@ihrivnac: Do you have this line in your cmake log: `vdt target added by hand.  Please fix this upstream in ROOT`

**Comment by ihrivnac** [comment]
Yes, I have ROOT checked-out as development package; but with no changes. I had version v6-14-06. Could it be the problem? I am now rebuilding with v6-16-00. It will take some time.
And yes, there is the message "vdt target added by hand. Please fix this upstream in ROOT" present in the log.

**Comment by aphecetche** [comment]
Just to explain the "patch" I've put in FindROOT.cmake : 

```
if(APPLE AND NOT TARGET vdt)
  find_library(VDT_LIB vdt PATHS ${ROOT_LIBRARY_DIR})
  if(VDT_LIB)
    add_library(vdt SHARED IMPORTED)
    set_target_properties(vdt PROPERTIES IMPORTED_LOCATION ${VDT_LIB})
    message(
      WARNING "vdt target added by hand. Please fix this upstream in ROOT")
  endif()
endif()
```

First I'm checking APPLE because I only observe the problem on Mac (not on CentOS or Ubuntu).
Second, the problem (as far as I understand it) is that, in the installed (by Root) ROOTConfig-targets.cmake (called by ROOTConfig.cmake), there is one lib depending on "vdt" : 

```
# Create imported target ROOT::ROOTVecOps
add_library(ROOT::ROOTVecOps SHARED IMPORTED)

set_target_properties(ROOT::ROOTVecOps PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include;${_IMPORT_PREFIX}/include"
  INTERFACE_LINK_LIBRARIES "ROOT::Core;vdt"
)
```

but vdt is nowhere defined as a target.

**Comment by davidrohr** [comment]
But actually she has a dependency to Vdt::Vdt
So this should not come from ROOT, since root just puts in the lib directly (vdt, or vdt with path), or could this have been different with the older ROOT version.

Perhaps another package pulls in the Vdt requirement?

**Comment by davidrohr** [comment]
ok, it is actually the ROOT version, 6-14-06 was detecting Vdt differently and pulled in Vdt::Vdt. I guess it will compile for @ihrivnac now with 6-16-00, but let's see.

**Comment by aphecetche** [comment]
@ihrivnac yes the older Root version might explain this. There have been some changes around the treatment of the Vdt dependency in the Root repo (see e.g. https://github.com/root-project/root/pull/2863/files).
So let's wait for your build, but I'm confident it will be ok.

That also means this is something to watch out in the next Root version, in case it's changed again or fixed.

**Comment by ihrivnac** [comment]
The build has finished ok, as you expcted :)

**Comment by davidrohr** [comment]
Nice, the I would suggest to merge this now before someone creates the next conflict. We can clean up the fallout tomorrow.

**Comment by ihrivnac** [comment]
I am ok with merging (but can't do it); I may have some suggestions afterwards.

**Comment by ktf** [comment]
I've rebased my work area but now I get:

```
402 CMake Error at /nix/store/kxfkny9867qzndaskvvbk14h3i1p5hpz-clang-7.1.0/lib/cmake/clang/ClangConfig.cmake:10 (find_package):
403   Could not find a package configuration file provided by "LLVM" with any of
404   the following names:
405
406     LLVMConfig.cmake
407     llvm-config.cmake
408
409   Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
410   "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
411   provides a separate development package or SDK, be sure it has been
412   installed.
413 Call Stack (most recent call first):
414   dependencies/O2Dependencies.cmake:133 (find_package)
415   dependencies/CMakeLists.txt:11 (include)
416   CMakeLists.txt:44 (include)
417
418
419 -- Configuring incomplete, errors occurred!
```

ideas?

**Comment by ktf** [comment]
I see:

```
 find_package(LLVM)
137 set_package_properties(LLVM PROPERTIES TYPE OPTIONAL)
```

when did we add LLVM to our requirements?

**Comment by davidrohr** [comment]
It is optional, as it is needed for the OpenGL2 GPU build.
I wonder why you get this error, since it is explicitly marked as optional.

**Comment by dennisklein** [comment]
> but vdt is nowhere defined as a target.

Why does it need to be a target?

**Comment by ktf** [comment]
#2183 fixes some of the problems. I also had to disable the `doc` folder and I am still fighting vs vdt...

**Comment by aphecetche** [comment]
@ktf @davidrohr  indeed in O2 LLVM is marked as optional, but the error you see is coming from the Clang config ... which is not finding its companion LLVM. At least this is why I see from the alibuild installed Clang (can only assume it's similar for the nix one ?) 

```
[ cmake ]~/alice/cmake/sw/osx_x86-64/Clang/latest/lib/cmake/clang$ more ClangConfig.cmake
# This file allows users to call find_package(Clang) and pick up our targets.

# Compute the installation prefix from this LLVMConfig.cmake file location.
get_filename_component(CLANG_INSTALL_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(CLANG_INSTALL_PREFIX "${CLANG_INSTALL_PREFIX}" PATH)
get_filename_component(CLANG_INSTALL_PREFIX "${CLANG_INSTALL_PREFIX}" PATH)
get_filename_component(CLANG_INSTALL_PREFIX "${CLANG_INSTALL_PREFIX}" PATH)

find_package(LLVM REQUIRED CONFIG
             HINTS "${CLANG_INSTALL_PREFIX}/lib/cmake/llvm")
```

**Comment by aphecetche** [comment]
@kft, OK, you already solved it, I was too slow ;-)

**Comment by ktf** [comment]
Do I really need to bump root to 6.16?

**Comment by aphecetche** [comment]
For vdt, you mean ? I'm afraid yes. But 6.16 is the default version for O2, isn't it ?

**Comment by ktf** [comment]
yeah, but I've some developments in 6.14.8 which I need to forward port... We should change the required version as well, BTW...

**Comment by aphecetche** [comment]
Indeed, should I open a PR for that or do you want to add it to your https://github.com/AliceO2Group/AliceO2/pull/2183 ?

**Comment by ktf** [comment]
Root version fixed in #2183 as well.

**Pull request merged**
