### PR TITLE
Add none option for its tracking

### PR DESCRIPTION
**Pull request by mconcas**
@shahor02 
It is not possible to pass "" to the tracking mode, so I made it explicitly disabled if needed.

### CODE REVIEW

**Comment by shahor02** [comment]
Well, `disable-tracking` was exactly doing this: skipping tracking and writing.

**Comment by mconcas** [comment]
> Well, `disable-tracking` was exactly doing this: skipping tracking and writing.

So if you want to do tracking elsewhere and pipe its-reco into something like gpu-reco it conflicts with: 
`[ERROR] invalid workflow in o2-gpu-reco-workflow: Found duplicate outputs ITS/IRFRAMES/0 in device gpu-reconstruction (6) and ITS/IRFRAMES/0 in its-cooked-tracker (7)`

**Comment by shahor02** [comment]
why do you initialize cooked-traker? With `o2-its-reco-workflow --disable-tracking` is it impossible to get it.

**Comment by mconcas** [comment]
> why do you initialize cooked-traker? With `o2-its-reco-workflow --disable-tracking` is it impossible to get it.

True, apparently my command was polluted by some non-empty string. Now I cannot even reproduce the reported error and works as expected.

**Pull request closed without merging**
