### PR TITLE
Drop o2::byte

### PR DESCRIPTION
**Pull request by ktf**
Replace it with C++17 std::byte. This does not endorse the actual
idea behind std::byte usage, merely gets rid of an O2 specific type
and header for it.

### CODE REVIEW

**Comment by ktf** [comment]
Even better then this would be to simply replace o2::byte with just char. When do we expect the extra type safety to be actually useful?

**Comment by Barthelemy** [comment]
Concerning your second remark: what is the drawback of using std::byte ?

**Comment by ktf** [comment]
@ironMann how would you like to proceed here? Shall we simply merge this and fix DataDistribution at the same time?

**Comment by ktf** [comment]
@Barthelemy I missed you commented here. std::byte is a separate type from char, so there is casting involved everywhere this is not taken into account (e.g. when printing / formatting), which can catch some errors, but also might introduce a lot of boilerplate. As usual I guess it's a matter of tradeoffs.

**Comment by ironMann** [comment]
@kft 
As far as I've seen, we mostly (only?) use byte*, and never use dereference of byte* directly. We still randomly cast byte* to different pointers and deref that (which is broken). From the standard, byte* has the same aliasing rules as char*, so there should be no surprises. 

Go ahead and merge if this is a simple rename.

**Comment by ktf** [comment]
Ok, I did, could you tag DataDistribution with https://github.com/AliceO2Group/DataDistribution/pull/94 included?

**Pull request merged**
