### PR TITLE
[O2-1787] First (rough) implementation of ITS services

### PR DESCRIPTION
**Pull request by mario6829**
A first rough implementation of ITS services (cables, wires and the like) was introduced in the geometry. In this version the mean material budget is taken into account but not the details of each single element. (The original code was developed by A.Morsch)

### CODE REVIEW

**Comment by mario6829** [comment]
Dear @mconcas @iouribelikov here it is a very first implementation of ITS services, based on @amorsch code. Please let me know in case of problems.

**Comment by mconcas** [comment]
Hi @mario6829 , thanks for this PR!
Eventually this is going to supersede https://github.com/AliceO2Group/AliceO2/pull/11172, once I'll figure out the errors in CI.

EDIT: there was just a hiccup in the Mixture and Medium definition for the polymer.
Now should be working, if you want to check the change.

Thanks a lot!

**Comment by mario6829** [comment]
many thanks @mconcas that's perfect!

**Review by mconcas — APPROVED** [review]

**Review by sawenzel — APPROVED** [review]

**Comment by sawenzel** [comment]
pinging also @amorsch for comments

**Comment by mconcas** [comment]
As the update came on JIRA https://alice.its.cern.ch/jira/browse/O2-1787, this can be merged.

**Pull request merged**
