### PR TITLE
Renaming charge() to sign()

### PR DESCRIPTION
**Pull request by jgrosseo**
Adding dynamic column for PID hypothesis during tracking

### CODE REVIEW

**Comment by jgrosseo** [comment]
We had to rename this because we don't store the charge but just the sign. I.e. Z=2 is not considered in charge()

@ddobrigk I have kept charge in the v0s because here you probably fill 0 as well, I assume?
@iarsene I haven't replaced how you call the variable in the VarManager and the labels. Up to you if you want to do this as well
@vkucera @victor-gonzalez This also touches your code. Check if you have any doubts.

**Comment by ddobrigk** [comment]
@jgrosseo if you mean [this guy](https://github.com/AliceO2Group/AliceO2/blob/99f26589785716368acf38a80f4ba28fc703a901/Analysis/DataModel/include/AnalysisDataModel/StrangenessTables.h#L110) then actually only the sign of the bachelor track is stored (the cascade sign has to match that because the V0 is neutral) and it will never be zero, so in fact it would be fine to rename it as 'sign'...

**Comment by vkucera** [comment]
@jgrosseo It is fine. We just have to propagate it to the open PRs.

**Comment by jgrosseo** [comment]
> 
> 
> @jgrosseo if you mean [this guy](https://github.com/AliceO2Group/AliceO2/blob/99f26589785716368acf38a80f4ba28fc703a901/Analysis/DataModel/include/AnalysisDataModel/StrangenessTables.h#L110) then actually only the sign of the bachelor track is stored (the cascade sign has to match that because the V0 is neutral) and it will never be zero, so in fact it would be fine to rename it as 'sign'...

OK, then I change this one as well

**Comment by iarsene** [comment]
Hi Jan,
This can be merged as far as the DQ part is concerned. The only place where the "sign" is not very suitable is in the dilepton pairs which at the moment take 3 values: 0, +2 and -2 for PM, PP and MM pairs respectively. These are small changes which i can fix in a future PR.
Ionut

**Comment by victor-gonzalez** [comment]
@jgrosseo  Ok from my side.
Thanks for implementing it!

**Comment by ddobrigk** [comment]
> > @jgrosseo if you mean [this guy](https://github.com/AliceO2Group/AliceO2/blob/99f26589785716368acf38a80f4ba28fc703a901/Analysis/DataModel/include/AnalysisDataModel/StrangenessTables.h#L110) then actually only the sign of the bachelor track is stored (the cascade sign has to match that because the V0 is neutral) and it will never be zero, so in fact it would be fine to rename it as 'sign'...
> 
> OK, then I change this one as well

@jgrosseo, perfect, thanks a lot for the change!

**Comment by ktf** [comment]
@Barthelemy this seems to be a new issue?

```
--
[ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/TH2Reductor.cxx.o
[ 46%] Built target o2-qc-run-postprocessing
[ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/THnSparse5Reductor.cxx.o
gmake[2]: *** [Modules/Example/CMakeFiles/o2-qc-example-analysis-direct.dir/build.make:82: Modules/Example/o2-qc-example-analysis-direct.json] Error 139
gmake[1]: *** [CMakeFiles/Makefile2:2247: Modules/Example/CMakeFiles/o2-qc-example-analysis-direct.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/QualityReductor.cxx.o
Scanning dependencies of target QcExample
[ 47%] Building CXX object Modules/Example/CMakeFiles/QcExample.dir/src/BenchmarkTask.cxx.o
--
[ 47%] Building CXX object Modules/Example/CMakeFiles/QcExample.dir/src/AnalysisTask.cxx.o
[ 47%] Linking CXX executable ../tests/testCcdbDatabase
[ 47%] Building CXX object Modules/Daq/CMakeFiles/QcDaq.dir/G__QcDaq.cxx.o
gmake[2]: *** [Modules/Example/CMakeFiles/o2-qc-example-analysis-derived.dir/build.make:82: Modules/Example/o2-qc-example-analysis-derived.json] Error 139
gmake[1]: *** [CMakeFiles/Makefile2:2274: Modules/Example/CMakeFiles/o2-qc-example-analysis-derived.dir/all] Error 2
[ 48%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/EverIncreasingGraph.cxx.o
/usr/bin/ld: warning: libssl.so.1.0.0, needed by /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/ROOT/v6-20-08-alice1-1/lib/libNet.so.6.20.08, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/ROOT/v6-20-08-alice1-1/lib/libNet.so.6.20.08, may conflict with libcrypto.so.1.1
--
[ 50%] Built target QcDaq
[ 50%] Linking CXX shared library ../../lib/libQcExample.so
[ 50%] Built target QcExample
gmake: *** [Makefile:160: all] Error 2
--
```

?

**Comment by ktf** [comment]
@Barthelemy this seems to be a new issue?

```
--
[ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/TH2Reductor.cxx.o
[ 46%] Built target o2-qc-run-postprocessing
[ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/THnSparse5Reductor.cxx.o
gmake[2]: *** [Modules/Example/CMakeFiles/o2-qc-example-analysis-direct.dir/build.make:82: Modules/Example/o2-qc-example-analysis-direct.json] Error 139
gmake[1]: *** [CMakeFiles/Makefile2:2247: Modules/Example/CMakeFiles/o2-qc-example-analysis-direct.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/QualityReductor.cxx.o
Scanning dependencies of target QcExample
[ 47%] Building CXX object Modules/Example/CMakeFiles/QcExample.dir/src/BenchmarkTask.cxx.o
--
[ 47%] Building CXX object Modules/Example/CMakeFiles/QcExample.dir/src/AnalysisTask.cxx.o
[ 47%] Linking CXX executable ../tests/testCcdbDatabase
[ 47%] Building CXX object Modules/Daq/CMakeFiles/QcDaq.dir/G__QcDaq.cxx.o
gmake[2]: *** [Modules/Example/CMakeFiles/o2-qc-example-analysis-derived.dir/build.make:82: Modules/Example/o2-qc-example-analysis-derived.json] Error 139
gmake[1]: *** [CMakeFiles/Makefile2:2274: Modules/Example/CMakeFiles/o2-qc-example-analysis-derived.dir/all] Error 2
[ 48%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/EverIncreasingGraph.cxx.o
/usr/bin/ld: warning: libssl.so.1.0.0, needed by /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/ROOT/v6-20-08-alice1-1/lib/libNet.so.6.20.08, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/ROOT/v6-20-08-alice1-1/lib/libNet.so.6.20.08, may conflict with libcrypto.so.1.1
--
[ 50%] Built target QcDaq
[ 50%] Linking CXX shared library ../../lib/libQcExample.so
[ 50%] Built target QcExample
gmake: *** [Makefile:160: all] Error 2
--
```

?

**Comment by jgrosseo** [comment]
> 
> 
> @Barthelemy this seems to be a new issue?
> 
> ```
> --
> [ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/TH2Reductor.cxx.o
> [ 46%] Built target o2-qc-run-postprocessing
> [ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/THnSparse5Reductor.cxx.o
> gmake[2]: *** [Modules/Example/CMakeFiles/o2-qc-example-analysis-direct.dir/build.make:82: Modules/Example/o2-qc-example-analysis-direct.json] Error 139
> gmake[1]: *** [CMakeFiles/Makefile2:2247: Modules/Example/CMakeFiles/o2-qc-example-analysis-direct.dir/all] Error 2
> gmake[1]: *** Waiting for unfinished jobs....
> [ 46%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/QualityReductor.cxx.o
> Scanning dependencies of target QcExample
> [ 47%] Building CXX object Modules/Example/CMakeFiles/QcExample.dir/src/BenchmarkTask.cxx.o
> --
> [ 47%] Building CXX object Modules/Example/CMakeFiles/QcExample.dir/src/AnalysisTask.cxx.o
> [ 47%] Linking CXX executable ../tests/testCcdbDatabase
> [ 47%] Building CXX object Modules/Daq/CMakeFiles/QcDaq.dir/G__QcDaq.cxx.o
> gmake[2]: *** [Modules/Example/CMakeFiles/o2-qc-example-analysis-derived.dir/build.make:82: Modules/Example/o2-qc-example-analysis-derived.json] Error 139
> gmake[1]: *** [CMakeFiles/Makefile2:2274: Modules/Example/CMakeFiles/o2-qc-example-analysis-derived.dir/all] Error 2
> [ 48%] Building CXX object Modules/Common/CMakeFiles/QcCommon.dir/src/EverIncreasingGraph.cxx.o
> /usr/bin/ld: warning: libssl.so.1.0.0, needed by /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/ROOT/v6-20-08-alice1-1/lib/libNet.so.6.20.08, may conflict with libssl.so.1.1
> /usr/bin/ld: warning: libcrypto.so.1.0.0, needed by /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/ROOT/v6-20-08-alice1-1/lib/libNet.so.6.20.08, may conflict with libcrypto.so.1.1
> --
> [ 50%] Built target QcDaq
> [ 50%] Linking CXX shared library ../../lib/libQcExample.so
> [ 50%] Built target QcExample
> gmake: *** [Makefile:160: all] Error 2
> --
> ```
> 
> ?

Can this be related to the changes in `adaptAnalysisTask` ?

**Pull request merged**
