### PR TITLE
DPL: add passthrough option for input / output proxies

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ironMann this adds different policies for messages which arrive on the input-proxy which have not been declared via `--data-spec`. In particular I guess you want `--unmatched-policy forward` which will forward unmatched dataspecs to the channel "forwarding". You can then use `--extra-channel-config name=forwarding,...` to get them redirected to the StfS. Still I find it easier to simply declare `--dataspec ....;ddmeta:FLP/DISTSUBTIMEFRAME` and have the metadata known to DPL.

**Comment by ironMann** [comment]
I really prefer a solution where DPL does not need to know about data it's not interested in. It simplifies the configuration and just makes for better defaults. I'm not sure how to setup the forwarding channel. How do I combine it with the rest of  DPL outputs of an STF? StfSender does not receive data from multiple sources. It it crucial the STF move in order, one multipart at a time.

o2-dpl-forwarding

**Comment by ktf** [comment]
How can DPL reassemble the data it needs to ignore? Do you guarantee that messages always come in pairs and that every single pair of messages has a DataProcessingHeader, including your internal data distribution metadata, as per O2 Data Model? Without that information I simply cannot split, [A,B] from [X, Y], calculate [A',B'] and join it back together with the correct [X,Y] as there is no guarantee that [A, B] at t0 will reach the output proxy before [A, B] at t1 (e.g. if people want to time pipeline compression). Do you guarantee at least that a given FairMQParts you send to DPL will be associated to one and only one timeframe?

Anyways, for the tests simply passing `dd:FLP/DISTSUBTIMEFRAME` is the easiest, then.

**Comment by ironMann** [comment]
> Do you guarantee that messages always come in pairs and that every single pair of messages has a DataProcessingHeader, including your internal data distribution metadata, as per O2 Data Model?

Yes. All <x>  parts (o2 header-stack + data) have consistent DataProcessingHeaders and DataHeaders. 

> Do you guarantee at least that a given FairMQParts you send to DPL will be associated to one and only one timeframe?

Yes, the whole (sub) timeframe is pushed in as a single FairMQ-multipart, with consistent TF identification in all headers. All messages within are valid o2 messages. 

On output of DPL, the STF is expected to have the same form. One multipart per STF.

**Comment by mkrzewic** [comment]
> Do you guarantee that messages always come in pairs and that every single pair of messages has a DataProcessingHeader, including your internal data distribution metadata, as per O2 Data Model?

As far as I remember the DataProcessingHeader was not part of the data model, just a temporary DPL hack until we had what we need in the DataHeader - which I think, after many heated discussions we do (#3475). If we're not there yet, we need to iterate some more, otherwise I think it is time to phase out DataProcessingHeader.

**Comment by ktf** [comment]
@ironMann ok, stay tuned.
@mkrzewic yes, DataProcessingHeader was just filling a shortcoming of the O2 Data Model design. ;-) It will be dropped at some point.
@preghenella as discussed, adding `dd:FLP/DISTSUBTIMEFRAME` should unblock you without further changes.

**Pull request closed without merging**
