### PR TITLE
GPU: Move GPUReconstructionHIP to hip language

### PR DESCRIPTION
**Pull request by mconcas**
@davidrohr compilation went through. Will test on EPN as well.
Do you have any short reproducer to test if it runs?

### CODE REVIEW

**Comment by davidrohr** [comment]
When the CI is green, I'll check with FST on the EPNs

**Comment by davidrohr** [comment]
@mconcas : could you apply the following patch: without, the build type specific options are not propagated. And also I cleaned up some hip flags that were appended twice.

sorry, this patch was wrong, correct one will come soon...

**Comment by davidrohr** [comment]
Correct patch:
```
diff --git a/Detectors/ITSMFT/ITS/tracking/GPU/hip/CMakeLists.txt b/Detectors/ITSMFT/ITS/tracking/GPU/hip/CMakeLists.txt
index f62dccdc9..747e50550 100644
--- a/Detectors/ITSMFT/ITS/tracking/GPU/hip/CMakeLists.txt
+++ b/Detectors/ITSMFT/ITS/tracking/GPU/hip/CMakeLists.txt
@@ -11,7 +11,7 @@
 
 if(HIP_ENABLED)
   message(STATUS "Building ITS HIP tracker")
-  set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} ${O2_HIP_CMAKE_CXX_FLAGS} -fgpu-rdc")
+  set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} -fgpu-rdc")
   o2_add_hipified_library(ITStrackingHIP
                  SOURCES ../cuda/ClusterLinesGPU.cu
                          ../cuda/Context.cu
diff --git a/GPU/GPUTracking/Base/hip/CMakeLists.txt b/GPU/GPUTracking/Base/hip/CMakeLists.txt
index b7a989625..8e6961cde 100644
--- a/GPU/GPUTracking/Base/hip/CMakeLists.txt
+++ b/GPU/GPUTracking/Base/hip/CMakeLists.txt
@@ -12,7 +12,7 @@
 set(MODULE GPUTrackingHIP)
 
 # Setting flags as a global option for all HIP targets.
-set(CMAKE_HIP_FLAGS "${CMAKE_CXX_FLAGS} ${O2_HIP_CMAKE_CXX_FLAGS} -fno-gpu-rdc")
+set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} -fno-gpu-rdc")
 if(DEFINED HIP_AMDGPUTARGET)
   set(TMP_TARGET "(GPU Target ${HIP_AMDGPUTARGET})")
 endif()
diff --git a/GPU/GPUbenchmark/hip/CMakeLists.txt b/GPU/GPUbenchmark/hip/CMakeLists.txt
index 94cba1e0c..7179e6d45 100644
--- a/GPU/GPUbenchmark/hip/CMakeLists.txt
+++ b/GPU/GPUbenchmark/hip/CMakeLists.txt
@@ -10,7 +10,7 @@
 # or submit itself to any jurisdiction.
 
 message(STATUS "Building GPU HIP benchmark")
-set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} ${O2_HIP_CMAKE_CXX_FLAGS} -fgpu-rdc -isystem /opt/rocm/include -fPIC")
+set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} -fgpu-rdc -isystem /opt/rocm/include -fPIC")
 
 o2_add_hipified_executable(gpu-memory-benchmark-hip
                            SOURCES ../cuda/benchmark.cu
diff --git a/dependencies/FindO2GPU.cmake b/dependencies/FindO2GPU.cmake
index 42b4e77b5..be1c6f294 100644
--- a/dependencies/FindO2GPU.cmake
+++ b/dependencies/FindO2GPU.cmake
@@ -63,6 +63,7 @@ function(set_target_hip_arch target)
 endfunction()
 
 # Detect and enable CUDA
+STRING(REGEX REPLACE "\-std=[^ ]*" "" O2_GPU_CMAKE_CXX_FLAGS_NOSTD ${CMAKE_CXX_FLAGS}) # Need to strip c++17 imposed by alidist defaults
 if(ENABLE_CUDA)
   set(CMAKE_CUDA_STANDARD 17)
   set(CMAKE_CUDA_STANDARD_REQUIRED TRUE)
@@ -106,9 +107,7 @@ if(ENABLE_CUDA)
     endif()
   endif()
   if(CMAKE_CUDA_COMPILER)
-    # Forward CXX flags to CUDA C++ Host compiler (for warnings, gdb, etc.)
-    STRING(REGEX REPLACE "\-std=[^ ]*" "" CMAKE_CXX_FLAGS_NOSTD ${CMAKE_CXX_FLAGS}) # Need to strip c++17 imposed by alidist defaults
-    set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Xcompiler \"${CMAKE_CXX_FLAGS_NOSTD}\" --expt-relaxed-constexpr --extended-lambda --allow-unsupported-compiler -Xptxas -v")
+    set(CMAKE_CUDA_FLAGS "${CMAKE_CUDA_FLAGS} -Xcompiler \"${O2_GPU_CMAKE_CXX_FLAGS_NOSTD}\" --expt-relaxed-constexpr --extended-lambda --allow-unsupported-compiler -Xptxas -v")
     set(CMAKE_CUDA_FLAGS_DEBUG "${CMAKE_CUDA_FLAGS_DEBUG} -lineinfo -Xcompiler \"${CMAKE_CXX_FLAGS_DEBUG}\" -Xptxas -O0 -Xcompiler -O0")
     if(NOT CMAKE_BUILD_TYPE STREQUAL "DEBUG")
       set(CMAKE_CUDA_FLAGS_${CMAKE_BUILD_TYPE} "${CMAKE_CUDA_FLAGS_${CMAKE_BUILD_TYPE}} -Xcompiler \"${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}}\" -Xptxas -O4 -Xcompiler -O4")
@@ -262,7 +261,8 @@ if(ENABLE_HIP)
       string(REGEX REPLACE "(.*)bin/c\\+\\+\$" "\\1" HIP_GCC_TOOLCHAIN_PATH "${CMAKE_CXX_COMPILER}")
       set(O2_HIP_CMAKE_CXX_FLAGS "${O2_HIP_CMAKE_CXX_FLAGS} --gcc-toolchain=${HIP_GCC_TOOLCHAIN_PATH}") # -ffast-math disabled, since apparently it leads to miscompilation and crashes in FollowLooper kernel
     endif()
-    set(CMAKE_HIP_FLAGS "${CMAKE_HIP_FLAGS} ${O2_HIP_CMAKE_CXX_FLAGS}")
+    set(CMAKE_HIP_FLAGS "${O2_GPU_CMAKE_CXX_FLAGS_NOSTD} ${CMAKE_HIP_FLAGS} ${O2_HIP_CMAKE_CXX_FLAGS}")
+    set(CMAKE_HIP_FLAGS_${CMAKE_BUILD_TYPE} "${CMAKE_CXX_FLAGS_${CMAKE_BUILD_TYPE}} ${CMAKE_HIP_FLAGS_${CMAKE_BUILD_TYPE}}")
   else()
     set(HIP_ENABLED OFF)
   endif()
```

**Comment by davidrohr** [comment]
@mconcas : it seems you pulled in other changes as well. Was that intentional?

**Comment by mconcas** [comment]
> @mconcas : it seems you pulled in other changes as well. Was that intentional?

ops! absolutely not. Fixing

**Comment by aphecetche** [comment]
@mconcas @davidrohr was this tested on Mac ? I am getting :

```
CMake Error at dependencies/FindO2GPU.cmake:66 (STRING):
  STRING sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  dependencies/O2Dependencies.cmake:167 (find_package)
  dependencies/CMakeLists.txt:13 (include)
  CMakeLists.txt:67 (include)
```

Granted, I'm using a Spack build but I'd tend to think that `CMAKE_CXX_FLAGS` can (and is in my case) indeed be empty so the line 
```
STRING(REGEX REPLACE "\-std=[^ ]*" "" O2_GPU_CMAKE_CXX_FLAGS_NOSTD ${CMAKE_CXX_FLAGS}) 
```
is then wrong in this case.

**Comment by davidrohr** [comment]
@aphecetche : could you then just open a fix that works for you? Perhaps it is enough to simply do
```
STRING(REGEX REPLACE "\-std=[^ ]*" "" O2_GPU_CMAKE_CXX_FLAGS_NOSTD "${CMAKE_CXX_FLAGS}") 
```

**Pull request merged**
