### PR TITLE
O2-863 Function to return the headers for a CCDB entry

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
Ready for review if the CIs pass.
@ktf it is similar to your static method. Do you really need a static method ? the rest of the class is non static.

**Comment by Barthelemy** [comment]
@AliceO2Group/core The build has finally passed. Could someone review ? thank you

**Comment by ktf** [comment]
What is stateful about the method? Why would you want it non-static?

**Comment by Barthelemy** [comment]
We store the URL to avoid repeating it at every call to the api. Nothing more.

**Comment by ktf** [comment]
Ah, ok. In that case can you simply leave the static helper which takes the url? In principle in the DPL case you will be allowed to change the base path from Configuration, having a static method allows having a single source of truth.

**Comment by Barthelemy** [comment]
Sure!

**Pull request merged**
