### PR TITLE
TreeStream operator<< takes const objects, const_casts internally

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Review by davidrohr — DISMISSED** [review]
thx, looks better this way

**Comment by shahor02** [comment]
@davidrohr @mconcas the fullCI is systematically failing with 
```
CMake Error in GPU/GPUbenchmark/hip/CMakeLists.txt:
  Imported target "hip::host" includes non-existent path

    "/opt/rocm-5.4.2/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

--
CMake Error in Detectors/ITSMFT/ITS/tracking/GPU/hip/CMakeLists.txt:
  Imported target "hip::host" includes non-existent path

    "/opt/rocm-5.4.2/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.
```
Any idea how this can be fixed?

**Comment by davidrohr** [comment]
@TimoWilken : could you check? That looks odd. Perhaps this runs in an old builder for some reason? The new docker container I have created certainly has this path.

**Comment by TimoWilken** [comment]
Hi @davidrohr, you're right, the builder was using the wrong container, sorry! It should be fixed now.

**Pull request merged**
