### PR TITLE
DPL Analysis: introduce particle-to-tracks reverse index

### PR DESCRIPTION
**Pull request by aalkin**
@jgrosseo I propose to add this sort of index centrally, to simplify tracking efficiency studies.

### CODE REVIEW

**Comment by jgrosseo** [comment]
What do we do when this is not unique?

**Comment by aalkin** [comment]
This is my main concern with this at the moment, I expected it to be *mostly* unique, but that is not the case. This can probably be resolved by grouping or introducing 1-to-array and 1-to-slice index tables. The latter are probably useful in other cases.

**Comment by jgrosseo** [comment]
I think most studies will loop over tracks and mc particles separately to build an efficiency. Then special studies which look for duplicated tracks could profit from grouping. I would not introduce an additional index for this.

**Comment by aalkin** [comment]
If we can guarantee that most of the particles have one track, then sure, we do not need this index. The ability to build it for specialized studies would be useful, though.

**Pull request closed without merging**
