### PR TITLE
Executable for chunk large raw-data files

### PR DESCRIPTION
**Pull request by shahor02**
Allows to split single or group of large (with many TFs) raw data files to chunks each containing at most N TFs.
One can also change the grouping of the output files:
e.g.: ``o2-raw-file-split --detect-tf0 --input-conf raw.cfg -n 10 -o split/ch --file-for cru``
will regroup the data in 10 chunks per output file in split/ch_0 ... split/ch_N directories
and creating a single output file per CRU. The configuration file split/ch_X/<DET>raw.cfg will
be created for every chunk

### CODE REVIEW

**Comment by shahor02** [comment]
@iouribelikov could you check if this is ok for what you wanted to do?

**Comment by iouribelikov** [comment]
@shahor02 Thank you very much, Ruben.  Yes, it should be exactly what we would like to have so much.  I will try it asap...

**Review by iouribelikov — DISMISSED** [review]
@shahor02  Thank you very much. This seems to work quite nicely !    

But I get lots of messages like
[INFO] Link 0x1630165289x was already declared with same output, do nothing
[INFO] Link 0x1663785514x was already declared with same output, do nothing
...
coming from
https://github.com/AliceO2Group/AliceO2/blob/bbb9823c8f7f378556a75676d9ca3ca5e8942cc6/Detectors/Raw/src/RawFileWriter.cxx#L133
Is this normal ?
(Also, the log file becomes very large...)

**Comment by shahor02** [comment]
@iouribelikov thanks for spotting, fixed.

**Pull request merged**
