### PR TITLE
[ATO-581] Speed up of createDigitsFromSim()

### PR DESCRIPTION
**Pull request by mhemmer-cern**
- Merged two for loops two increase performance
- `localPadRow` in createCluster is now a const unsigned int as it should be when comparing with `Mapper::ROWSPERREGION[region]`
- remove variables that are only used once directly afterwards
- move constructor of digitContainer outside of loop and add reset call inside loop. The reset call is very expansice but meassures with TStopwatch show that it is still faster.

### CODE REVIEW

**Comment by mhemmer-cern** [comment]
@matthias-kleiner could you please check if this looks okay to you?

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner could you please check if this looks okay to you?

Hello @mhemmer-cern , this is fine for me

**Comment by sawenzel** [comment]
macro fails CI test

**Comment by mhemmer-cern** [comment]
Yes but this should be unrelated to the changes since this happens to many o2 and O2physics PRs. Cl probably needs to get updated and Timo was already pinged on multiple PRs because of this.

**Pull request merged**
