### PR TITLE
change-new-cone

### PR DESCRIPTION
**Pull request by carlos-soncco**
new version of the halfcone

### CODE REVIEW

**Comment by frmanso** [comment]
I going to review this part of the MFT code

**Comment by sawenzel** [comment]
@frmanso : Thanks.

**Comment by sawenzel** [comment]
@frmanso , @bovulpes : Do you have any news here?

**Comment by carlos-soncco** [comment]
I changed pointer names according  "Details" e.g. Variable 's_box_mb0' is assigned a value that is never used."

**Comment by sawenzel** [comment]
@carlos-soncco : Can you please fix the clang-format problems? @frmanso : Please give your review.

**Comment by sawenzel** [comment]
I see many changes being done to this PR. Is this converging or still work in progress? @bovulpes @frmanso, could you please approve when ready?

**Comment by frmanso** [comment]
Hello, It's still need work before to approve

**Comment by frmanso** [comment]
Hello, the code submitted by Carlos (half cone of MFT) is frozen since quite 2 months because of fairRoot error (see below). It doesn't see to be related to its code, what could be the problem here? 

/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-4/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lBaseVGM
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-4/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lXmlVGM
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-4/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lClhepVGM
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-4/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lGeant4GM
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-4/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot find -lRootGM
collect2: error: ld returned 1 exit status

**Comment by sawenzel** [comment]
Don't worry about this test. It's not mandatory. I was expecting to get a word / approval from @frmanso . I can merge thereafter.

**Comment by frmanso** [comment]
Hello,
    It's ok from my side, we can push this new version of the cone.
Best regards.

**Pull request merged**
