### PR TITLE
Swenzel/breakit

### PR DESCRIPTION
**Pull request by sawenzel**
DO NOT MERGE ... I LIKE TO SEE HOW FAST THE PR CHECKS ARE NOW

### CODE REVIEW

**Comment by sawenzel** [comment]
reopening ... actually the codechecker should fail ...

**Comment by sawenzel** [comment]
@dberzano : Something is wrong here as the codecheck should actually not pass. On my local machine, the recipe fails correctly.

**Comment by dberzano** [comment]
Checking.

**Comment by sawenzel** [comment]
@dberzano : This log does not show a single error. Something is wrong with the error parser.

**Comment by sawenzel** [comment]
@dberzano :  Clicking on the log link brings me to output from some other PR (is this expected)?

**Comment by dberzano** [comment]
The PR checker keeps merging your PR to the master, and two wrong files got merged from #422, which passed all tests as, probably, the checker has not correctly determined what files changed. I think there is something wrong with the way we do that.

**Comment by sawenzel** [comment]
Moreover, the actual error: nullptr violation does not seem to be reported

**Comment by sawenzel** [comment]
Closing it. Test successful.

**Pull request closed without merging**
