### PR TITLE
TRD: Fix TRD digit method names

### PR DESCRIPTION
**Pull request by jolopezl**
This pull request implements some changes in the name of Digits methods following some useful suggestions.

### CODE REVIEW

**Comment by martenole** [comment]
Thanks Jorge. Seems you missed changes in the macro `Detectors/TRD/macros/CheckDigits.C`

**Comment by jolopezl** [comment]
> Thanks Jorge. Seems you missed changes in the macro `Detectors/TRD/macros/CheckDigits.C`

It's done now. I missed that change.

**Comment by shahor02** [comment]
is this ready to be merged?

**Comment by jolopezl** [comment]
> is this ready to be merged?

This isn't critical, just a name change. You can go ahead and merge it.

**Review by martenole — APPROVED** [review]
Fine with me as the checks are green.
@jolopezl could you afterwards also change QualityControl to include the correct `DataFormatsTRD/Digit.h` header such that we can remove Digit.h in TRDBase?

**Pull request merged**
