### PR TITLE
Add FastJet::Contrib to cmake

### PR DESCRIPTION
**Pull request by qgp**
@nzardosh Could you have a look if that works for you?

### CODE REVIEW

**Comment by nzardosh** [comment]
looks good to me, i will remove it from the other PR

**Comment by qgp** [comment]
@ktf Any thoughts? 

PS: This would be eventually needed to move forward with #4512.

**Comment by nzardosh** [comment]
@ktf Can you check this please?

**Comment by nzardosh** [comment]
I assume the tests here just need to be relaunched. @qgp perhaps you can push an empty commit to trigger the rebuild

**Pull request merged**
