### PR TITLE
Make sure that we can dump at the same time mermaid and o2-control

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by ktf** [comment]
Clang format, please

**Review by ktf — COMMENTED** [review]
Fine with me. Could you have "create unit test for marmaid output" on the backlog?

**Review by ktf — APPROVED** [review]

**Comment by Barthelemy** [comment]
There is `test_Mermaid.cxx`. Do you have something more in mind ?

**Comment by ktf** [comment]
No.

**Pull request merged**
