### PR TITLE
PWGHF: Xicc task

### PR DESCRIPTION
**Pull request by JinjooSeo**
Fix the naming skimming
Need to confirm to get a Xic candidate ID

### CODE REVIEW

**Comment by vkucera** [comment]
Hi @JinjooSeo , can you please resolve the conflicts?

**Comment by JinjooSeo** [comment]
> Hi @JinjooSeo , can you please resolve the conflicts?

I made some mistake when I running --rebase.. Can I cancel this PR and made a new one?

**Comment by ginnocen** [comment]
sure @JinjooSeo

**Comment by vkucera** [comment]
> > Hi @JinjooSeo , can you please resolve the conflicts?
> 
> I made some mistake when I running --rebase.. Can I cancel this PR and made a new one?

I don't see any commit pushed to the repository yet, so the PR should be safe still.
You can abort the rebase and fix the mistake locally and push when it is fine.

**Review by ginnocen — APPROVED** [review]

**Review by jgrosseo — APPROVED** [review]

**Review by jgrosseo — CHANGES_REQUESTED** [review]
Starting the migration now. So we have to merge this into O2Physics later...

**Comment by vkucera** [comment]
> Starting the migration now. So we have to merge this into O2Physics later...

OK, no problem.

**Comment by vkucera** [comment]
Closing because of O2Physics migration

**Pull request closed without merging**
