### PR TITLE
Fix conversion from string to seconds

### PR DESCRIPTION
**Pull request by chiarazampolli**
For some reason, libstdc seems to have issues parsing the month
("%b" option), so now I use the SQL format.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
@aphecetche , FYI.

**Comment by chiarazampolli** [comment]
The error in the CI seem unrelated, concerning:
o2-test-framework-SimpleRDataFrameProcessing
o2-test-framework-ParallelPipeline
o2-test-framework-Forwarding
...
Am I wrong? Is there something related to this change too?

**Comment by chiarazampolli** [comment]
Hello, 

This should be a trivial change, no idea why the CI fails. Can someone check?

Cheers,

Chiara

**Review by shahor02 — APPROVED** [review]
failures are not related to this PR, merging

**Comment by davidrohr** [comment]
The CI is currently generally broken, with several issues. I have been looking at it during the weekend a bit.
@ktf @TimoWilken @MichaelLettrich : We should try to return to a working state ASAP.
Issues I have been seeing are:
- MacOS always fails with `dyld: Library not loaded: /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/INSTALLROOT/9ac921ecfd5f7c7ec35229b571fb57eb2d3d5618/osx_x86-64/fastjet/v3.3.3_1.042-alice1-4/lib/libfastjettools.0.dylib`
- O2/o2 sometimes suceeds, but usually just fails without leaving a log.
- Full CI fails (almost) always with one of the following 3 issues:
  - O2 Compilation Failure when the workflow JSONs are dumped: `[ERROR] Unhandled o2::framework::runtime_error reached the top of main, device shutting down. Details follow: `
  - `DataFormats/MemoryResources/test/testMemoryResources.cxx` fails the test (almost) always.
  - Other ctests are failing randomly.
  (my feeling is that these failures are since the introduction of the websocket communication in DPL.)

**Comment by chiarazampolli** [comment]
Thanks @davidrohr (I indeed thought something is broken), and @shahor02 !

Chiara

**Pull request merged**
