### PR TITLE
Make DecoderBase class an abstract one

### PR DESCRIPTION
**Pull request by preghenella**
all handlers are now pure virtual functions, to ensure this class is abstract.

### CODE REVIEW

**Comment by sawenzel** [comment]
This has compilation problems:  `warning: abstract class is marked 'final' [-Wabstract-final-class]
class Diagnostics final`

**Comment by preghenella** [comment]
hi @sawenzel ,
I cannot find `Modules/TOF/include/TOF/Diagnostics.h` in the `QualityControl` repository (`master`).
Perhaps this is because the build check is not using the `QC` master.

@njacazio and @Barthelemy perhaps can help in finding the solution for this.
The `QC` master is updated with what is needed to comply with the updates in this PR.

Cheers,
Roberto

**Comment by knopers8** [comment]
Barth is on holidays this week.
Build checks run on the releases specified in alidist (see https://github.com/alisw/alidist/blob/master/qualitycontrol.sh). This is why I was asking you in the [PR to QC](https://github.com/AliceO2Group/QualityControl/pull/452) if you need a release ;)

**Comment by preghenella** [comment]
now I see... thanks @knopers8 .
Then I think we need a release.
Thanks,
Roberto

**Comment by knopers8** [comment]
OK, I will take care of that

**Pull request merged**
