### PR TITLE
Some MCH simulation fixes of mostly stupid bugs.

### PR DESCRIPTION
**Pull request by aphecetche**
- Hit : Fix detElemId return type
- Hit : Entrance point was not recorded
- GeometryTest : Fix getNormalVector function

### CODE REVIEW

**Comment by aphecetche** [comment]
As far as I can tell the build error(s) are unrelated to this PR ?

**Comment by sawenzel** [comment]
I believe the error is unrelated and the PR can be merged.

But it is still a strange one related to graphics which I've never seen before. @ihrivnac : Do you have any idea why geant4_vmc tries to open a graphics system related to a ROOT TApplication?

**Comment by ihrivnac** [comment]
Hi Sandro,
Could you point me at the log where I can see this error?
Thank you,

**Comment by sawenzel** [comment]
Ah ... unfortunately the logs disappear once merged. Here is a copy-paste of the error extracted from a different PR:

```
Adding SpecialPhysicsList stepLimiter+specialCuts
### TG4SpecialStackingAction activated
_RegisterApplication(), FAILED TO establish the default connection to the WindowServer, _CGSDefaultConnection() is NULL.
2018-06-28 09:02:43.561 o2sim[17283:5665422] GetInputSourceEnabledPrefs user file path = /Users/alibuild/Library/Preferences/com.apple.HIToolbox.plist
2018-06-28 09:02:43.561 o2sim[17283:5665422] GetInputSourceEnabledPrefs effective user id path = 503
2018-06-28 09:02:43.561 o2sim[17283:5665422] GetInputSourceEnabledPrefs user pref content = <CFBasicHash 0x7fdf01746980 [0x7fff89b1caf0]>{type = immutable dict, count = 0,
entries =>
}
2018-06-28 09:02:43.607 o2sim[17283:5665422] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2fc286bb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x00007fff56e37942 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2fc421ed -[__NSArray0 objectAtIndex:] + 93
	3   libGCocoa.6.12.06.so                0x000000011fcecc34 _ZN4ROOT6MacOSX3X1123GetRootWindowAttributesEP18WindowAttributes_t + 52
	4   libGui.6.12.so                      0x00000001126fee0a _ZN7TGFrameC2EP8TGClientmPK8TGWindow + 586
	5   libGui.6.12.so                      0x00000001126c466d _ZN8TGClientC2EPKc + 685
	6   libGui.6.12.so                      0x00000001127b2753 _ZN16TRootApplicationC2EPKcPiPPc + 163
	7   libGui.6.12.so                      0x00000001127d1d02 _ZN15TRootGuiFactory20CreateApplicationImpEPKcPiPPc + 50
	8   libCore.6.12.so                     0x00000001088f5c24 _ZN12TApplication18InitializeGraphicsEv + 292
	9   libCore.6.12.so                     0x00000001088f58e8 _ZN12TApplicationC2EPKcPiPPcPvi + 984
	10  libRint.6.12.so                     0x00000001100b41aa _ZN5TRintC2EPKcPiPPcPvib + 42
	11  libgeant4vmc.dylib                  0x000000010c00d317 _ZN13TG4RunManager12CreateRootUIEv + 295
	12  libgeant4vmc.dylib                  0x000000010c00ca3f _ZN13TG4RunManagerC2EP19TG4RunConfigurationiPPc + 687
	13  libgeant4vmc.dylib                  0x000000010c00f76e _ZN7TGeant4C2EPKcS1_P19TG4RunConfigurationiPPc + 1390
	14  libSimSetup.dylib                   0x0000000109e2826c _ZN2o28g4config6ConfigEv + 188
	15  libSimSetup.dylib                   0x0000000109e28d1b _ZN2o28g4config8G4ConfigEv + 299
	16  o2sim                               0x0000000108860790 _ZZ10o2sim_initbENK3$_0clEv + 240
	17  o2sim                               0x000000010886068d _ZNSt3__128__invoke_void_return_wrapperIvE6__callIJRZ10o2sim_initbE3$_0EEEvDpOT_ + 45
	18  o2sim                               0x000000010885fdc9 _ZNSt3__110__function6__funcIZ10o2sim_initbE3$_0NS_9allocatorIS2_EEFvvEEclEv + 41
	19  libBase.17.dylib                    0x00000001092df7c7 _ZN10FairRunSim11SetMCConfigEv + 55
	20  libBase.17.dylib                    0x00000001092def6d _ZN10FairRunSim4InitEv + 1949
	21  o2sim                               0x000000010884e13d _Z10o2sim_initb + 3421
	22  o2sim                               0x000000010885193d _Z5o2simb + 29
	23  o2sim                               0x0000000108851a64 main + 228
	24  libdyld.dylib                       0x00007fff57a4e015 start + 1
	25  ???                                 0x000000000000000f 0x0 + 15
)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by ihrivnac** [comment]
Could it be, that this error started with re-activation of G4 test? Did we changed since that time the way how o2sim program is launched?
TGeant4 internally creates TRint, however this should not cause a break when graphics is not available.

**Comment by sawenzel** [comment]
I made sure that the tests passed when I reactivated the G4 tests. Everything was green for a while. It must be something else.

**Pull request merged**
