### PR TITLE
Mft

### PR DESCRIPTION
**Pull request by bovulpes**
In principle naming variables, plus update of the geometry.

### CODE REVIEW

**Comment by sawenzel** [comment]
@bovulpes : I believe the naming convention with "m" does not apply to static or const variables.
Please consult https://github.com/AliceO2Group/CodingGuidelines.

("Static class member variables are prefixed with s", etc.)

**Comment by bovulpes** [comment]
Naming conventions, corrected for "s" for static, but no special prefix for const, as in the rules.
Compiled the code after updating after the break in FairRoot.

**Comment by bovulpes** [comment]
I have too many conflicts, indeed, sorry, I will come back later.

**Comment by sawenzel** [comment]
@bovulpes: Don't worry too much. A merge (instead of a rebase) would actually succeeds. So we could repack all the new stuff into a new clean commit. Shall I take a look?

**Comment by sawenzel** [comment]
@bovulpes : I can take a look how to make a clean commit ...

**Comment by bovulpes** [comment]
This is exactly what I did, a merge instead of a rebase, but apparently it did not work, let my try something else.

**Comment by sawenzel** [comment]
@bovulpes : I made a clean rebaseable commit which you can take from my fork on branch mftfix.
You only need to change the author to you and add some additional comments in the commit message.

**Comment by bovulpes** [comment]
@sawenzel I did differently, I hope it works.

**Comment by bovulpes** [comment]
@sawenzel just one more question, when I opened the pull request the first check said "This branch has no conflicts with the base branch", although there were conflicts, what does it mean?

**Comment by sawenzel** [comment]
@bovulpes : The commit has my name attached to it... shall we leave it like that?

**Comment by bovulpes** [comment]
@sawenzel yes, no problem.

**Comment by sawenzel** [comment]
@bovulpes : I mentioned you in the commit message. This will now be merged with #316 ... so I am closing this one.

**Pull request closed without merging**
