### PR TITLE
ITS3: TDR Implementation Pt.1

### PR DESCRIPTION
**Pull request by f3sch**
Split of #12711.

This mostly first pushes the ITS3 relevant parts only with minimal changes to production code so that this can be reviewed separately.
The relevant files for production are:
- GeomtryTGeo.h/cxx
- DescriptorInnerBarrel.h/cxx
- Detector.cxx
115 lines of change, removing ITS3 version, Appending bools to constructors etc.

### CODE REVIEW

**Review by fgrosa — DISMISSED** [review]
Hi @f3sch thanks! I approve it from the ITS3 side.

**Review by mconcas — COMMENTED** [review]
Notice that removing that `COMPILE_ONLY` flag actually enables the tests for the loaded-only macros
```bash
root mymacro.C
```
on top of the compiled tests
```bash
root mymacro.C+
```
This we added essentially because of an internal bug in CLING with the migration to C++20.
If you know that bug has been fixed, please ignore this comment, otherwise I expect more test failing.

**Comment by f3sch** [comment]
@mconcas Thanks for explaining. I naively thought this would exclude them entirely from testing.

**Review by mconcas — APPROVED** [review]
Thanks for splitting the original PR.
Indeed, we have minimal changes on the ITS (2) code here, and they look okay to me.

Eventually, it would be better to extend the dictionary usage to converge to a single clusterer in ITS2-3.

Indeed, this is not a priority now.

**Comment by mconcas** [comment]
Failing test is unrelated and FullCI is green, Merging.

**Comment by f3sch** [comment]
> Eventually, it would be better to extend the dictionary usage to converge to a single clusterer in ITS2-3.

That is nice idea, I will check how easy it is for now. Thanks for merging.

**Pull request merged**
