### PR TITLE
Avoid Framework dependency of the library, move it to executable

### PR DESCRIPTION
**Pull request by shahor02**
Root has problem to generate a dictionary for the code depending on the include/boost/container/...
coming via Framework ... MemoryResources.h dependence.

The problem shows up in the interactive instantiation of the object of a class from the library with such a dependence, e.g. before this PR we had:
````
root [0] o2::raw::HBFUtils hh
#0  0x00007f9d83ec3687 in __GI___waitpid (pid=4318, stat_loc=stat_loc
entry=0x7ffcc12cf368, options=options
entry=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x00007f9d83e2e067 in do_system (line=<optimized out>) at ../sysdeps/posix/system.c:149
#2  0x00007f9d84acd264 in TUnixSystem::Exec (shellcmd=<optimized out>, this=0x5584dc86fb80) at /home/shahoian/alice/sw/SOURCES/ROOT/v6-18-04/v6-18-04/core/unix/src/TUnixSystem.cxx:2106
#3  TUnixSystem::StackTrace (this=0x5584dc86fb80) at /home/shahoian/alice/sw/SOURCES/ROOT/v6-18-04/v6-18-04/core/unix/src/TUnixSystem.cxx:2400
#4  0x00007f9d7f316055 in cling::MultiplexInterpreterCallbacks::PrintStackTrace() () from /home/shahoian/alice/sw/ubuntu1804_x86-64/ROOT/v6-18-04-7/lib/libCling.so
#5  0x00007f9d7f315aad in cling_runtime_internal_throwIfInvalidPointer () from /home/shahoian/alice/sw/ubuntu1804_x86-64/ROOT/v6-18-04-7/lib/libCling.so
#6  0x00007f9d85259751 in ?? ()
#7  0x00007ffcc12d1780 in ?? ()
#8  0x00007f9d852597e8 in ?? ()
#9  0x0000000000000000 in ?? ()
Error in <HandleInterpreterException>: Trying to access a pointer that points to an invalid memory address..
Execution of your code was aborted.
In file included from G__O2DetectorsRaw dictionary payload:266:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/O2/1.0.0-1/include/Framework/WorkflowSpec.h:13:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/O2/1.0.0-1/include/Framework/DataProcessorSpec.h:13:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/O2/1.0.0-1/include/Framework/AlgorithmSpec.h:13:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/O2/1.0.0-1/include/Framework/ProcessingContext.h:13:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/O2/1.0.0-1/include/Framework/InputRecord.h:14:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/O2/1.0.0-1/include/Framework/DataRefUtils.h:14:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/O2/1.0.0-1/include/Framework/TMessageSerializer.h:23:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/O2/1.0.0-1/include/MemoryResources/MemoryResources.h:30:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/boost/v1.70.0-5/include/boost/container/flat_map.hpp:29:
In file included from /home/shahoian/alice/sw/ubuntu1804_x86-64/boost/v1.70.0-5/include/boost/container/detail/flat_tree.hpp:29:
/home/shahoian/alice/sw/ubuntu1804_x86-64/boost/v1.70.0-5/include/boost/container/detail/pair.hpp:133:89: warning: invalid memory pointer passed to a callee:
static piecewise_construct_t piecewise_construct = BOOST_CONTAINER_DOC1ST(unspecified, *std_piecewise_construct_holder<>::dummy);
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/shahoian/alice/sw/ubuntu1804_x86-64/boost/v1.70.0-5/include/boost/container/detail/workaround.hpp:71:46: note: expanded from macro 'BOOST_CONTAINER_DOC1ST'
#define BOOST_CONTAINER_DOC1ST(TYPE1, TYPE2) TYPE2
````

### CODE REVIEW

**Comment by davidrohr** [comment]
@shahor02 : Unfortunately, this doesn't fix my problem. I'll life with my workaround to patch the system header. Probably a problem between ROOT and GCC 9.

**Comment by wiechula** [comment]
@shahor02 : for me it also does not solve the problem.
@davidrohr : how did you solve it in your case?

**Comment by davidrohr** [comment]
@wiechula : I hacked the system GCC header, and made the class derivation the error is complaining about public.

@shahor02 : Actually, this PR fixes the problem you introduced with the RawReaderWorkflow.
However, there is a second identical problem triggered by recent changes in the TRD workflow.

**Comment by wiechula** [comment]
Yes, I didn't look closely. Now the error is in the TRD also for me.

**Comment by wiechula** [comment]
@davidrohr : cool! Thanks for the hint.

**Comment by shahor02** [comment]
actually, this is known problem: https://sft.its.cern.ch/jira/browse/ROOT-10220

**Pull request merged**
