### PR TITLE
Disable simulation if Pythia6/8 are not found

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
@davidrohr could you please check if this fixes your problem?

**Comment by davidrohr** [comment]
@dberzano : I tried with and without Pythia8, and both works correctly now

**Comment by dberzano** [comment]
Given that the problem we see is not correlated, I am merging this one! 👍

**Comment by sawenzel** [comment]
I don't see the rational for this PR. We should be able to run simulation without having pythia ... for example by using event input from external file.

**Comment by davidrohr** [comment]
Hi Sandro,

that does not work because the TPC simulation code relies on pythia unconditionally.

i agree that we can fix that in tpc simulation and then revert this change.
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Pull request merged**
