### PR TITLE
Use llvm::SmallVector for some ITS tracking

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Testing with:

```
 o2-ctf-reader-workflow --onlyDet ITS  --delay 0.01 --ctf-input data.lst --shm-segment-size 24000000000  --max-cached-files 10  |\
 o2-its-reco-workflow --clusters-from-upstream --trackerCA --tracking-mode async --disable-mc -b
```

using 2023/LHC23zze/543918/raw/0010/o2_ctf_run00543918_orbit0550821888_tf0000081058_epn207.root and measuring RSS with:

```
while true; do ps auxwww | grep "id its-tracker" | grep -v grep | awk '{print $6}'; sleep 1; done
```

I get the following plot (tested twice, because I did not believe the initial results when I first saw them):

image

This could admittedly be an issue with the allocator on macOS not releasing pages as they get freed or being more susceptible to fragmentation, however the difference is so big it's probably worth to check if we do not see the same effect on Linux.

**Comment by mpuccio** [comment]
Hi @ktf, thanks a lot. Do we need this? As far as I can tell there is no standing issue with ITS memory (thanks to your fixes), otherwise I would be working on that.

**Comment by mconcas** [comment]
Ciao, I gave it a try on ubuntu (I also rebased on your last PR from yesterday, this had visible impact in the offset):

Screenshot 2023-10-16 at 15 35 59

It seems to be a Mac specific behaviour.

**Comment by ktf** [comment]
Well, I had a problem running it on my mac... ;-) That said, we should check on CC7, given the productions will happen there, IIRC.

That said, probably we can simply add the commit which adds llvm::SmallVector and leave ITS ones out unless we measure significant improvements on Linux.

**Comment by ktf** [comment]
Closing for now. Will reopen one if I find some other place where SmallVector makes sense.

**Pull request closed without merging**
