### PR TITLE
DDS to ODC

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr indeed @dennisklein gave me a heads up about this but I forgot when we switched to the new FairMQ.

**Comment by davidrohr** [comment]
@ktf : Could you check what failed here in the ctest? Would be good to merge this soon.

**Comment by dennisklein** [comment]
Looks like a false negative to me: https://github.com/AliceO2Group/AliceO2/blob/8f7f5ef3bc1c5c46b977799e6510b237aaa0150e/Framework/Core/test/test_FrameworkDataFlowToDDS.cxx#L118 - expected string needs to be adapted, too.

**Comment by ktf** [comment]
Indeed, I must have accidentally hit u before saving.

**Pull request merged**
