### PR TITLE
DPL GUI: add option to SIGCONT all children processes

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr

**Comment by davidrohr** [comment]
I have seen it, thanks for the fast patch

**Comment by ktf** [comment]
I needed it as well for debugging other stuff, as I said. Extension for the other signals it's bit more complicated as I think 0 includes the parent and I do not want to, say, SIGKILL it. I've an idea on how to start a debugger directly from the GUI, but it would be Mac only, unless you know how to open a xterm window and execute something into it.

**Comment by davidrohr** [comment]
executing
xterm -hold -e gdb attach [PID]
will do (xterm is a bit ugly but bettern than nothing, and should be available everywhere).
You could also allow for an env variable like O2_GDB_SHELL, and then you just execute $O2_GDB_SHELL gdb attach [PID]

**Comment by ktf** [comment]
Good idea... I would actually like to have enough stamina to integrate https://github.com/timmoorhouse/imgui-terminal in the GUI, but I guess I will leave it for a foggy Sunday evening...

**Comment by davidrohr** [comment]
or a very simple alternative: we create a simple binary o2_gdb, which one can run in a terminal. It just listens on a socket. When we start a workflow and ask it to debug one of the processors, it connects to that binary, and just starts the gdb with the specific process inside that console.

**Comment by ktf** [comment]
but then why not running a gdb server?

**Comment by davidrohr** [comment]
Indeed, I have never used gdb server, but that could work as well. Could we modify the --child-driver option to be used for only a single process? And does it work with additional command line arguments for the child-driver?

**Comment by ktf** [comment]
Making `--child-driver` support different options for different processes is indeed probably the best thing to do...

**Comment by davidrohr** [comment]
fully agreed, just updated the jira ticket, can continue the discussion there. This should cover many of the cases I came up with.

**Pull request merged**
