### PR TITLE
FIT calibration: large refactoring

### PR DESCRIPTION
**Pull request by afurs**
1. Dependencies are detached between FITcalibration and FT0/FV0 calibration libraries.
2. All calibration object structs are moved int DataFormats
3. Global offset task is moved into FT0calibration
4. New distributed time offset calibration tasks, based on FlatHisto2D structure

### CODE REVIEW

**Comment by afurs** [comment]
All FT0/FV0 calibration tasks were excluded temporary from QC: https://github.com/AliceO2Group/QualityControl/pull/1363 On local machine I also haven't seen such issue(in O2Suite). Investigating.

**Comment by afurs** [comment]
From logs I see `cmake /sw/SOURCES/QualityControl/v1.67.0/v1.67.0` So the QC is not latest, PR 1363 was implemented after.

**Comment by afurs** [comment]
Unrelated issue in CICD:
```
[130/620] Building CXX object Common/TableProducer/PID/CMakeFiles/O2Physicsexe-analysis-pid-tpc.dir/pidTPC.cxx.o
FAILED: Common/TableProducer/PID/CMakeFiles/O2Physicsexe-analysis-pid-tpc.dir/pidTPC.cxx.o 
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-5/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DDPL_ENABLE_BACKTRACE -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -DFMT_SHARED -I/sw/SOURCES/O2Physics/9559-slc8_x86-64/0 -I/sw/SOURCES/O2Physics/9559-slc8_x86-64/0/Common/Core -I/sw/SOURCES/O2Physics/9559-slc8_x86-64/0/Common/TableProducer/PID -isystem /sw/slc8_x86-64/O2/9559-slc8_x86-64-local1/include -isystem /sw/slc8_x86-64/Common-O2/v1.6.0-52/include -isystem /sw/slc8_x86-64/boost/v1.75.0-49/include -isystem /sw/slc8_x86-64/Configuration/v2.6.3-40/include -isystem /sw/slc8_x86-64/libInfoLogger/v2.5.1-4/include -isystem /sw/slc8_x86-64/Monitoring/v3.12.0-22/include -isystem /sw/slc8_x86-64/curl/7.70.0-1/include -isystem /sw/slc8_x86-64/FairMQ/v1.4.52-4/include/fairmq -isystem /sw/slc8_x86-64/FairMQ/v1.4.52-4/include -isystem /sw/slc8_x86-64/FairLogger/v1.11.1-1/include -isystem /sw/slc8_x86-64/fmt/8.1.1-6/include -isystem /sw/slc8_x86-64/ROOT/v6-26-04-patches-alice1-8/include -isystem /sw/slc8_x86-64/O2/9559-slc8_x86-64-local1/include/GPU -isystem /sw/slc8_x86-64/FairRoot/v18.4.8-16/include -isystem /sw/slc8_x86-64/VMC/v1-1-p1-39/include/vmc -isystem /sw/slc8_x86-64/arrow/v5.0.0-alice3-39/include -isystem /sw/slc8_x86-64/Vc/1.4.1-25/include -isystem /sw/slc8_x86-64/ms_gsl/4.0.0-8/include -isystem /sw/slc8_x86-64/libjalienO2/0.1.3-22/include -isystem /sw/slc8_x86-64/RapidJSON/v1.1.0-alice2-28/include -isystem /sw/slc8_x86-64/libuv/v1.40.0-25/include -isystem /sw/slc8_x86-64/TBB/v2021.5.0-17/include -isystem /sw/slc8_x86-64/ONNXRuntime/v1.7.2-alice1-20/include -fPIC -O2 -std=c++17 -Wall -O2 -g -DNDEBUG -std=gnu++17 -MD -MT Common/TableProducer/PID/CMakeFiles/O2Physicsexe-analysis-pid-tpc.dir/pidTPC.cxx.o -MF Common/TableProducer/PID/CMakeFiles/O2Physicsexe-analysis-pid-tpc.dir/pidTPC.cxx.o.d -o Common/TableProducer/PID/CMakeFiles/O2Physicsexe-analysis-pid-tpc.dir/pidTPC.cxx.o -c /sw/SOURCES/O2Physics/9559-slc8_x86-64/0/Common/TableProducer/PID/pidTPC.cxx
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
[131/620] Building CXX object PWGHF/TableProducer/CMakeFiles/O2Physicsexe-analysis-hf-x-tojpsipipi-candidate-selector.dir/HFXToJpsiPiPiCandidateSelector.cxx.o
[132/620] Building CXX object PWGHF/TableProducer/CMakeFiles/O2Physicsexe-analysis-hf-jpsi-candidate-selector.dir/HFJpsiCandidateSelector.cxx.o
```

**Comment by shahor02** [comment]
Hi @afurs 
The failure is genuine: 
/sw/SOURCES/O2/9559-slc8_x86-64/0/Detectors/FIT/FT0/calibration/testWorkflow/FT0TimeSpectraProcessor-Workflow.cxx:34:3: error: annotate this function with 'override' or (rarely) 'final' [modernize-use-override]

**Comment by afurs** [comment]
> Hi @afurs The failure is genuine: /sw/SOURCES/O2/9559-slc8_x86-64/0/Detectors/FIT/FT0/calibration/testWorkflow/FT0TimeSpectraProcessor-Workflow.cxx:34:3: error: annotate this function with 'override' or (rarely) 'final' [modernize-use-override]

Hi @shahor02 , thanks! strange, I saw only 1 failure in CDCD... Ok, fixing

**Comment by shahor02** [comment]
Hi @afurs 
Actually, the fullCI has failed due to the unrelated reasons, but it did not reach the FST and sim_challenge tests. Given the amount of changes better to pass them. Could you either push a dummy commit to trigger another test, or run them locally: 

```
FST_SYNC_EXTRA_WORKFLOW_PARAMETERS=QC,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR QC_REDIRECT_MERGER_TO_LOCALHOST=1 GEN_TOPO_WORKDIR=`pwd` ALICE_O2SIM_DUMPLOG=1 NEvents=5 NEventsQED=100 O2SIMSEED=12345 $O2_ROOT/prodtests/full_system_test.sh
```
and 
```
$O2_ROOT/prodtests/sim_challenge.sh
```

**Comment by afurs** [comment]
Hi @shahor02 I have to recomplie O2Suite on local machine, so it will be done in parallel, dummy commit + local test you mentioned. But I definitely saw all tests were successful. Does CICD restart procedure after some time?

**Comment by afurs** [comment]
Tests are completed at local machine:
```
 [O2PDPSuite/latest-dev_fit-o2] /data/work/FST $> FST_SYNC_EXTRA_WORKFLOW_PARAMETERS=QC,CALIB_LOCAL_AGGREGATOR,CALIB_LOCAL_INTEGRATED_AGGREGATOR QC_REDIRECT_MERGER_TO_LOCALHOST=1 GEN_TOPO_WORKDIR=`pwd` ALICE_O2SIM_DUMPLOG=1 NEvents=5 NEventsQED=100 O2SIMSEED=12345 $O2_ROOT/prodtests/full_system_test.sh
Found 24 physical CPU cores
Launching task: o2-sim --seed 12345 -j 24 -n 100 -m PIPE ITS MFT FT0 FV0 FDD -g extgen -e TGeant4 --configKeyValues "GeneratorExternal.fileName=$O2_ROOT/share/Generators/external/QEDLoader.C;QEDGenParam.yMin=-7;QEDGenParam.yMax=7;QEDGenParam.ptMin=0.001;QEDGenParam.ptMax=1.;Diamond.width[2]=6." --run 310000 &> qedsim.log &
Launching task: o2-sim --seed 12345 -n 5 --configKeyValues Diamond.width[2]=6. -g pythia8hi -e TGeant4 -j 24 --run 310000 &> sim.log &
Launching task: o2-sim-digitizer-workflow -n 5 --simPrefixQED qed/o2sim --qed-x-section-ratio 4417.27 --disable-mc --tpc-lanes 24 --shm-segment-size 8000000000 -b --skipDet TRD --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0;HBFUtils.orbitFirstSampled=0;HBFUtils.obligatorySOR=false;HBFUtils.runNumber=310000;HBFUtils.maxNOrbits=128;" --interactionRate 50000 &> digi.log &
Launching task: o2-sim-digitizer-workflow -n 5 --disable-mc --onlyDet TRD --trd-digit-downscaling 1000 --shm-segment-size 8000000000 -b --incontext collisioncontext.root --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0;HBFUtils.orbitFirstSampled=0;HBFUtils.obligatorySOR=false;HBFUtils.runNumber=310000;HBFUtils.maxNOrbits=128;;TRDSimParams.digithreads=24;" &> digiTRD.log &
Launching task: o2-its-digi2raw --file-for cru -o raw/ITS &> itsraw.log &
Launching task: o2-mft-digi2raw --file-for cru -o raw/MFT &> mftraw.log &
Launching task: o2-ft0-digi2raw --file-for cru -o raw/FT0 &> ft0raw.log &
Launching task: o2-fv0-digi2raw --file-for cru -o raw/FV0 &> fv0raw.log &
Launching task: o2-fdd-digit2raw --file-for cru -o raw/FDD &> fddraw.log &
Launching task: o2-tpc-digits-to-rawzs --zs-version 2 --file-for cru -i tpcdigits.root -o raw/TPC &> tpcraw.log &
Launching task: o2-tof-reco-workflow -b --file-for cru --output-type raw --tof-raw-outdir raw/TOF &> tofraw.log &
Launching task: o2-mid-digits-to-raw-workflow -b --mid-raw-outdir raw/MID --file-for cru &> midraw.log &
Launching task: o2-mch-digits-to-raw --input-file mchdigits.root --output-dir raw/MCH --file-for cru &> mchraw.log &
Launching task: o2-emcal-rawcreator --file-for link -o raw/EMC &> emcraw.log &
Launching task: o2-phos-digi2raw --file-for link -o raw/PHS &> phsraw.log &
Launching task: o2-cpv-digi2raw --file-for cru -o raw/CPV &> cpvraw.log &
Launching task: o2-zdc-digi2raw --file-for cru -o raw/ZDC &> zdcraw.log &
Launching task: o2-hmpid-digits-to-raw-workflow --file-for cru --outdir raw/HMP &> hmpraw.log &
Launching task: o2-trd-trap2raw -o raw/TRD --file-per cru &> trdraw.log &
Launching task: o2-ctp-digi2raw -o raw/CTP --file-for cru &> ctpraw.log &
Launching task: /home/flp/alice/sw/slc8_x86-64/O2/dev_fit-local1/prodtests/full-system-test/dpl-workflow.sh &> reco_NOGPU.log &
Launching task: /home/flp/alice/sw/slc8_x86-64/O2/dev_fit-local1/prodtests/full-system-test/dpl-workflow.sh &> reco_ASYNC.log &
[O2PDPSuite/latest-dev_fit-o2] /data/work/FST $> $O2_ROOT/prodtests/sim_challenge.sh
Creating GRPs ... and publishing in local CCDB overwrite
Launching task: o2-grp-simgrp-tool createGRPs --run 300000 --publishto GRP -o mcGRP &> grp.log &
Running simulation for 10 pp events with pythia8pp generator and engine TGeant3 and run number 300000
Launching task: o2-sim -n10 --configKeyValues Diamond.width[2]=6. -g pythia8pp -e TGeant3 --run 300000 &> sim.log &
Launching task: root -q -b -l /home/flp/alice/sw/slc8_x86-64/O2/dev_fit-local1/share/macro/analyzeHits.C &> hitstats.log &
Running digitization for 400 kHz interaction rate
Launching task: o2-sim-digitizer-workflow -b --run --shm-segment-size 10000000000 --interactionRate 400000 --configKeyValues HBFUtils.runNumber=300000 &> digi.log &
Return status of digitization: 0
Running TRD trap simulator
Launching task: o2-trd-trap-sim -b --run --shm-segment-size 10000000000 &> trdtrap.log &
Return status of trd trap sim: 0
Running TPC reco flow
Launching task: o2-tpc-reco-workflow -b --run --shm-segment-size 10000000000 --input-type digits --output-type clusters,tracks,send-clusters-per-sector --configKeyValues GPU_rec.maxTrackQPtB5=20 &> tpcreco.log &
Return status of tpcreco: 0
Running ITS reco flow
Launching task: o2-its-reco-workflow --trackerCA --tracking-mode async -b --run --shm-segment-size 10000000000 --configKeyValues "ITSVertexerParam.phiCut=0.5;ITSVertexerParam.clusterContributorsCut=3;ITSVertexerParam.tanLambdaCut=0.2" &> itsreco.log &
Return status of itsreco: 0
Running MFT reco flow
Launching task: o2-mft-reco-workflow -b --run --shm-segment-size 10000000000 --configKeyValues "MFTTracking.forceZeroField=false;MFTTracking.LTFclsRCut=0.0100;" &> mftreco.log &
Return status of mftreco: 0
Running MCH reco flow
Launching task: o2-mch-reco-workflow -b --run --shm-segment-size 10000000000 &> mchreco.log &
Return status of mchreco: 0
Running FT0 reco flow
Launching task: o2-ft0-reco-workflow -b --run --shm-segment-size 10000000000 &> ft0reco.log &
Return status of ft0reco: 0
Running FDD reco flow
Launching task: o2-fdd-reco-workflow -b --run --shm-segment-size 10000000000 &> fddreco.log &
Return status of fddreco: 0
Running FV0 reco flow
Launching task: o2-fv0-reco-workflow -b --run --shm-segment-size 10000000000 &> fv0reco.log &
Return status of fv0reco: 0
Running MID reco flow
Launching task: o2-mid-digits-reader-workflow | o2-mid-reco-workflow  -b --run --shm-segment-size 10000000000 &> midreco.log &
Return status of midreco: 0
Running MCH-MID matching flow
Launching task: o2-muon-tracks-matcher-workflow  -b --run --shm-segment-size 10000000000 &> mchmidMatch.log &
Return status of mchmidmatch: 0
Running ITS-TPC matching flow
Launching task: o2-tpcits-match-workflow --use-ft0 -b --run --shm-segment-size 10000000000 &> itstpcMatch.log &
Return status of itstpcMatch: 0
Running TRD matching to ITS-TPC and TPC
Launching task: o2-trd-tracklet-transformer -b --run --shm-segment-size 10000000000 &> trdTrkltTransf.log &
Return status of trdTrkltTransf: 0
Launching task: o2-trd-global-tracking -b --run --shm-segment-size 10000000000 &> trdMatch.log &
Return status of trdTracker: 0
Running MFT-MCH-MID matching flow
Launching task: o2-globalfwd-matcher-workflow -b --run --shm-segment-size 10000000000 --configKeyValues "FwdMatching.useMIDMatch=true;" &> mftmchMatch.log &
Return status of globalfwdMatch: 0
Running TOF reco flow to produce clusters
Launching task: o2-tof-reco-workflow -b --run --shm-segment-size 10000000000 &> tofReco.log &
Return status of tof cluster reco : 0
Running Track-TOF macthing flow
Launching task: o2-tof-matcher-workflow -b --run --shm-segment-size 10000000000 &> tofMatchTracks.log &
Return status of o2-tof-matcher-workflow: 0
Running TOF matching QA
Launching task: root -b -q -l /home/flp/alice/sw/slc8_x86-64/O2/dev_fit-local1/share/macro/checkTOFMatching.C &> tofmatch_qa.log &
Return status of TOF matching qa: 0
Running ZDC reconstruction
Launching task: o2-zdc-digits-reco -b --run --shm-segment-size 10000000000 &> zdcreco.log &
Return status of ZDC reconstruction: 0
Running EMC reconstruction
Launching task: o2-emcal-reco-workflow --infile emcaldigits.root -b --run --shm-segment-size 10000000000 &> emcreco.log &
Return status of EMC reconstruction: 0
Running PHS reconstruction
Launching task: o2-phos-reco-workflow -b --run --shm-segment-size 10000000000 &> phsreco.log &
Return status of PHS reconstruction: 0
Running CPV reconstruction
Launching task: o2-cpv-reco-workflow -b --run --shm-segment-size 10000000000 &> cpvreco.log &
Return status of CPV reconstruction: 0
Running primary vertex finding flow
Launching task: o2-primary-vertexing-workflow -b --run --shm-segment-size 10000000000 --condition-remap file://./GRP=GLO/Config/GRPECS &> pvfinder.log &
Return status of primary vertexing: 0
Running secondary vertex finding flow
Launching task: o2-secondary-vertexing-workflow -b --run --shm-segment-size 10000000000 &> svfinder.log &
Return status of secondary vertexing: 0
Producing AOD
Launching task: o2-aod-producer-workflow -b --run --shm-segment-size 10000000000 --aod-writer-keep dangling --aod-writer-resfile AO2D --aod-writer-resmode UPDATE --aod-timeframe-id 1 --run-number 300000 &> aod.log &
Return status of AOD production: 0
[O2PDPSuite/latest-dev_fit-o2] /data/work/FST $> 
```

**Pull request merged**
