### PR TITLE
MFT: add extension for the full chip mapping access

### PR DESCRIPTION
**Pull request by bovulpes**
This introduces some features needed in https://github.com/AliceO2Group/AliceO2/pull/5686

Information on the full software and hardware mapping, using only the chip global software index.

How to use it in a macro:

#include "ITSMFTReconstruction/ChipMappingMFT.h"

const o2::itsmft::ChipMappingMFT map;
auto chipMap = map.getChipMappingData();

/* get a digit object */

printf("%-12d%-14d%-14d%-7d%-7d%-8d%-9d0x%-7x%-7d%-12d%-7d%-7d%-10d%-12d\n",
chipMap[digit.getChipIndex()].globalChipSWID,
chipMap[digit.getChipIndex()].localChipSWID,
chipMap[digit.getChipIndex()].localChipHWID,
chipMap[digit.getChipIndex()].half,
chipMap[digit.getChipIndex()].disk,
chipMap[digit.getChipIndex()].layer,
chipMap[digit.getChipIndex()].ruSWID,
chipMap[digit.getChipIndex()].ruHWID,
chipMap[digit.getChipIndex()].ruType,
chipMap[digit.getChipIndex()].ruOnLayer,
chipMap[digit.getChipIndex()].zone,
chipMap[digit.getChipIndex()].connector,
chipMap[digit.getChipIndex()].cable,
chipMap[digit.getChipIndex()].chipOnRU);

See the attached file of a full print using:

map.print();

[mapping_full.txt](https://github.com/AliceO2Group/AliceO2/files/6136636/mapping_full.txt)

### CODE REVIEW

**Comment by shahor02** [comment]
@bovulpes thanks! One comment: you are using `GeometryTGeo` which requires the geometry to be loaded, but the methods you use from this class do not need the geometry (used only for matrices extraction). Isn't it better to do the opposite: move needed methods from `GeometryTGeo` to `mft::ChipMappingMFT` and `ChipMappingMFT` from `GeometryTGeo` when needed.

In this way the mapping will not need geometry and can be used in the analysis w/o loading it. Then you could even avoid creating the  `mft::ChipMappingMFT` and implement new features directly in the `itsmft::ChipMappingMFT`.

**Comment by bovulpes** [comment]
@shahor02 Yes, I know, we have a circular dependence in the design of the mapping which is based on the geometry class, that is why we use a macro to create mapping data hardwired in the .cxx file, since the MFT has a totally irregular mapping, unlike the ITS. On one side it is good that we have a check of the geometry stored in the OCDB also on the real data, which will be wrongly mapped if the geometry is not the good one.
For the moment that is all I can propose, maybe some other time a better solution will be implemented.

**Comment by shahor02** [comment]
@bovulpes I assume you are referring on extraction of some parameters from the geometry in the `GeometryTGeo::Build`, which are then used in e.g. `getSensorID`. But the MFT layout will not change anymore, you can simply hardcode needed lookup tables in the ChipMappingMFT and use it from the GeometryTGeo. Anyway, up to you, but I find it inconvenient to depend on the CCDB for extraction of const information.

**Comment by bovulpes** [comment]
Ok, I will extend one of the tables in ChipMappingMFT with additional information.

**Comment by bovulpes** [comment]
@shahor02 I have extended the already existing chip mapping array with more information. The macro to create the hardwired initialization of the array is updated.

**Review by shahor02 — APPROVED** [review]
Thanks!

**Comment by shahor02** [comment]
CI failure is unrelated, merging

**Pull request merged**
