### PR TITLE
Apply clang-format on all C++ in O2.

### PR DESCRIPTION
**Pull request by vkucera**
@TimoWilken It seems like the Github action checks only changes in files instead of checking entire changed files.

### CODE REVIEW

**Comment by TimoWilken** [comment]
Hi @vkucera, yes, that's intentional. That's so that all the existing code doesn't suddenly fail CI when (e.g.) clang-format gets updated, as it was recently from v8 to v11.

**Comment by vkucera** [comment]
@TimoWilken But this approach results in files that are mixture of pieces formatted with different styles, while the files themselves are not well formatted with the current style.
What I meant was, if the CI checks entire files included in a PR, there is no risk that all the existing code would fail. Only the concerned files would get reformatted.
In any case, when there is a style update, I don't see a problem reformatting the entire repository.

**Comment by davidrohr** [comment]
For reference, sometimes clang-format will produce a different output than git-clang format, so users should always run git-clang-format agains origin/dev against a PR before pushing, and not the plain clang-format.
That is a bit misleading, but that's how it is.

If there is a style update, we can indeed reformat the entire repository (we did this already), but it should be done with git-clang-format, not with clang format.

**Comment by vkucera** [comment]
> For reference, sometimes clang-format will produce a different output than git-clang format, so users should always run git-clang-format agains origin/dev against a PR before pushing, and not the plain clang-format.
> That is a bit misleading, but that's how it is.
> 
> If there is a style update, we can indeed reformat the entire repository (we did this already), but it should be done with git-clang-format, not with clang format.

Thanks @davidrohr for the clarification. Indeed I was not aware there is a difference between the two. The official guidelines should be changed then because now [the file checking examples](https://github.com/AliceO2Group/CodingGuidelines#check-files-formatting) mention only the plain `clang-format`.

**Comment by davidrohr** [comment]
OK, I will check the guidelines.
I think the background is that git-clang-format normally checks only the modified lines, which puts some constraints on what it can do, thus they have a slightly different output as compared to clang-format even when checking an entire file.

**Comment by davidrohr** [comment]
For reference: AliceO2Group/CodingGuidelines#24

**Comment by vkucera** [comment]
Thank you, @davidrohr .

**Pull request closed without merging**
