### PR TITLE
DPL: expose the TimesliceIndex as a service

### PR DESCRIPTION
**Pull request by ktf**
This should allow callbacks to create non data driven Timeslices.

### CODE REVIEW

**Comment by ktf** [comment]
@knopers8 can you check if this finally solves your timer issues?

**Comment by knopers8** [comment]
@ktf I don't think it does. You exposed `TimesliceIndex` as a service, but `ClockTick` and `Idle` callbacks receive no arguments anyway, so I cannot access the services nor data allocator there.

**Comment by ktf** [comment]
Ciao,

Can't you capture a reference to the service when you create the callback in init? That way you do the lookup only once. No need to percolate services to the callbacks, IMHO.

--
Ciao,
Giulio

**Comment by knopers8** [comment]
Fine for me, I will try it out the next week.

**Comment by knopers8** [comment]
@ktf I gave it a try - it is indeed possible to access the `ServiceRegistry` in `InitContext`, but `DataAllocator` is anyway exposed only in `ProcessingContext`, which prevents me from preparing a clock tick callback during initialization.
The second thing is that I don't really understand how do I set timestamp to my message using `TimesliceIndex`. Could you give me a hint?

**Comment by ktf** [comment]
@knopers8 That's on purpose. The idea is that you should not need `DataAllocator` in the callback. Just use `TimesliceIndex::bookTimeslice` in the call-back to create the entries and then use the `Lifetime::Timer` to populate them as before. The difference is that this times entries are created regardless of some other input arriving. This is done to ensure that you still declare your timers as inputs, rather than creating them as mere unaccounted side effects as it would happen with a callback only solution. Does it make sense?

**Comment by knopers8** [comment]
@ktf I am afraid not. This is how I understand what you've said so far:
I should put my time-based procedure of publishing an object in a `ClockTick` callback, which I should register in `InitContext`. In that callback, I should use `TimesliceIndex::bookTimeslice` to choose what timeslice my published object will have. Afterwards, in the same callback, I should publish my object, yet not by using `DataAllocator`, but `Lifetime::Timer` - I have no idea how.
In the `DataProcessorSpec` I should declare a timer input and specify the interval of the timer in `Options`. I don't understand what for, since `ClockTick` is invoked each time in `ConditionalRun` (which is _Called during RUNNING state repeatedly until it returns false or device state changes_). If I used `Idle` callback instead, the behaviour would be nearly the same.
Where do I miss your point?

**Comment by knopers8** [comment]
That would help a lot, I'll pm you on slack.

**Pull request merged**
