### PR TITLE
add calibration of splines in FastTPCTransform; bugfix in use of Vc vectors

### PR DESCRIPTION
**Pull request by sgorbuno**
add calibration of splines in FastTPCTransformation; bugfix in the use of Vc vectors

### CODE REVIEW

**Comment by davidrohr** [comment]
@sgorbuno : Please use GPUCA_NAMESPACE::gpu as namespace, otherwise we produce duplicate symbols when building o2 with AliRoot as dependency. I'll check the Vc thing later.
Do I have to a build new transformation map?

**Comment by davidrohr** [comment]
OK, I see, in the macros it won't matter, and in the code it is correct.
Thx

**Comment by davidrohr** [comment]
@sgorbuno : I verified the transformation, and the FPE in the Vc part is gone.
Also, the TPC workflow with creation and usage of the transformation map works for me.

Can you fix the clang-format issue, and force-push a new version.
The C.I. issues are fixed, so hopefully it will now pass the checks.

**Comment by sgorbuno** [comment]
@davidrohr :  for some reason the o2checkcode crashes in test_TPCWorkflow:
=== test_TPCWorkflow_test_TPCWorkflow - Process running as 10307 for attempt 1 ===
 *** Break *** segmentation violation
I need to figure out why is it so..

**Comment by davidrohr** [comment]
hm, the totally weird thing is: the test_TPCWorkflow_test_TPCWorkflow passed in the build/O2/o2 and the build/o2/macos. I wonder how it can possibly crash in the o2checkcode only.

But actually, there seem to be other errors as well: /mnt/mesos/sandbox/sandbox/sw/BUILD/0390348ee3363b643ae0a806747d7f986f4ab003/O2/tests-wrapper.sh: fork: retry: Resource temporarily unavailable. Perhaps that caused the segfault as a side effect.

I'd fix the clang format and force-push. Then the C.I. will run again. Also the problem with the normal O2 build C.I. should be fixed now, so that should become green then.

**Comment by davidrohr** [comment]
This looks pretty weird, no the codechecker passed all tests, but the cuda C.I. segfaulted ~70 times during the tests. Also, I do not see warnings about "resource temporarily unavailable" this time.

I am retrying this locally with CUDA enabled.

**Comment by davidrohr** [comment]
Locally all the tests pass, also with CUDA enabled. No idea what is the problem in the build/o2/cuda.
@sawenzel @ktf @dberzano : Any idea?
Probably it'll go away if we just retry, but would be better to understand it!

**Comment by sgorbuno** [comment]
@davidrohr,  
there are also other problems there:

=== test_DetectorsBase_testMatBudLUT - Running /build/ci_checks/o2_checker_linux_o2_ci_0/sw/BUILD/163d0620ebd976bbfd158250daa6d4c2bb7b1de6/O2/bin/test_DetectorsBase_testMatBudLUT with args  (attempt 1/1) ===
=== test_DetectorsBase_testMatBudLUT - Process running as 11458 for attempt 1 ===
Running 1 test case...
[INFO] Loading geometry FAIRGeom from ./O2geometry.root
Error in <TFile::TFile>: file ./O2geometry.root does not exist
[FATAL] Failed to open file ./O2geometry.root

        
275/339 Test #271: test_DetectorsBase_testMatBudLUT ................................................***Failed    2.06 sec

**Comment by davidrohr** [comment]
@sgorbuno : hm, no idea what was the problem. The CI did automatically rerun in the mean time, and the tests passed. However, there is still the clang-format fix missing. Could you do that, then I'll merge it.

**Pull request merged**
