### PR TITLE
DPL Analysis: rudimentary support for configurable axes

### PR DESCRIPTION
**Pull request by mario-krueger**

### CODE REVIEW

**Comment by mario-krueger** [comment]
@jgrosseo @saganatt @iarsene this should do what we discussed yesterday.
Cheers,
  Mario

**Comment by iarsene** [comment]
Hi @mario-krueger,
The CI test fails on readability braces missing. Otherwise, the PR is fine with me.
Cheers, Ionut

**Comment by jgrosseo** [comment]
Seems the removal of const broke the compilation...

**Review by jgrosseo — APPROVED** [review]

**Comment by jgrosseo** [comment]
I had a discussion with @aalkin yesterday and variable size arrays are not excluded in principle.

**Pull request merged**
