### PR TITLE
TRD gen raw data

### PR DESCRIPTION
**Pull request by bazinski**
Take output of trap simulation (data that is received by cru) and generate raw data.

- trap2raw standalone executable converts trapoutput to cru output(raw data)
- Speed up sort in trap simulator, only sort on time, hcid, mcm
- Raw files generated 1 per half cru, option to change later.
- Files pass o2-raw-file-check.
- Mapping of half chambers to cru inputs will be done seperately, for now linear 0-1079.

### CODE REVIEW

**Comment by bazinski** [comment]
I dont have a mac, trap2cru main is done the same way ft0 digit2raw. I assume something wrong with macos ci?
@sawenzel  @jolopezl @tdietel I know you guys have mac.

[ 85%] Linking CXX executable ../../../stage/bin/o2-trd-trap2cru
Undefined symbols for architecture x86_64:
  "_main", referenced from:
     implicit entry/start for main executable
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[2]: *** [Detectors/TRD/simulation/CMakeFiles/O2exe-trd-trap2cru.dir/build.make:174: stage/bin/o2-trd-trap2cru] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:21009: Detectors/TRD/simulation/CMakeFiles/O2exe-trd-trap2cru.dir/all] Error 2

**Comment by bazinski** [comment]
macos file system is case sensitive and git apparently is not ...
I thought I copied the same structure of FT0 but misread Digits2Raw.cxx and digi2raw.cxx as the same thing :-( took @jolopezl to point it out to me. So trap2cru.cxx is being overwritten by Trap2CRU.cxx and hence the message of no _main becomes a lot clearer, although @jolopezl saw a different error message.  Now renamed to tracklet2raw.cxx alhtough not accurate as it will contain non tracklet format as well. Will rename again before lifting the WIP.

**Comment by bazinski** [comment]
Dont merge yet, there is something wrong with the cru link lengths, fixnig.

**Comment by bazinski** [comment]
Done @tdietel can you approve, will put proper mapping of detector cru link in next pr.

**Review by tdietel — APPROVED** [review]

**Pull request merged**
