### PR TITLE
Add support for man pages

### PR DESCRIPTION
**Pull request by ktf**
You can now create man pages in nroff format under:

    Subsystem/Module/docs/<man-page-name>.1.in

and it will create a man page for you in:

    ${CMAKE_BINARY_DIR}/share/man/man1

if you add:

    O2_GENERATE_MAN(NAME <man-page-name>)

to your CMakeLists.txt

TODO:
- [x] Add documentation for this in `AliceO2/doc/`
- [x] Add support for different sections
- [x] Add example in Examples2

### CODE REVIEW

**Comment by Barthelemy** [comment]
I like it, very nice. 

Looking at the current directory structure we use `doc` rather than `docs` thus I would be in favour of changing this. 

I tried to add a directory `docs` in Examples/Example2 and a file `example-man-page.1.in` within. I finally added `O2_GENERATE_MAN(NAME example-man-page)` to the CMakeLists.txt. When calling make I get : 
```Scanning dependencies of target example-man-page.1
make[2]: *** No rule to make target 'Examples/ExampleModule2/example-man-page.1', needed by 'Examples/ExampleModule2/CMakeFiles/example-man-page.1'.  Stop.
CMakeFiles/Makefile2:3981: recipe for target 'Examples/ExampleModule2/CMakeFiles/example-man-page.1.dir/all' failed
make[1]: *** [Examples/ExampleModule2/CMakeFiles/example-man-page.1.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```
Maybe you could provide a working example in Example2 and also add some documentation for example in AliceO2/doc/xxxxx.md

**Comment by ktf** [comment]
Agreed. Working on this.

**Comment by ktf** [comment]
@matthiasrichter @Barthelemy I think I've addressed all your comments. Can you try again?

**Comment by Barthelemy** [comment]
It works like a charm ! 
+1

**Pull request merged**
