### PR TITLE
TPC dE/dx: using nD-piecewise polynomials instead of polynomials

### PR DESCRIPTION
**Pull request by matthias-kleiner**
Changing CCDB path for the track topology correction

### CODE REVIEW

**Comment by matthias-kleiner** [comment]
[The new calibration object](https://github.com/AliceO2Group/AliceO2/files/9338706/Tracktopology_piecewise_scaled.root.zip) which should be used.

@wiechula can you put it in the CCDB to `TPC/Calib/TopologyGainPiecewise`, otherwise the workflows will not start.

@wiechula provided a comparison for the dE/dx GPU reco performance on the EPNs for the new piecewise polynomials and old polynomials, where no significant impact is observed
GPU_perf_Polynomials

Reconstruction of dE/dx with pilotbeam pp using the new calibration + recreated residual dE/dx calibration looks fine:
dedx_sector
dedx_tgl


@chiarazampolli if an old run is reconstructed with this PR, @wiechula should recreate the http://alice-ccdb.cern.ch/browse/TPC/Calib/TimeGain objects to make them compatible with the new calibration object

**Comment by wiechula** [comment]
@matthias-kleiner , for the new calibration object, please add a JIRA ticket in O2 with an upload request.

**Review by wiechula — APPROVED** [review]

**Comment by davidrohr** [comment]
FullCI fails with
```
[131189:internal-dpl-ccdb-backend]: [20:16:15][FATAL] Unable to find object TPC/Calib/TopologyGainPiecewise/1550600800000
```
Do you need to update this new CCDB object beforehand?

**Comment by wiechula** [comment]
@davidrohr , a made an upload request.

**Comment by chiarazampolli** [comment]
> @davidrohr , a made an upload request.

Hello, see ticket, https://alice.its.cern.ch/jira/browse/O2-3203, there is now a file uploaded, but I got an error.

**Pull request merged**
