### PR TITLE
Improve metrics handling

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This is a separate PR with the developments I am doing to fix the multithreading behaviour. In principle the other developments work well as well, but maybe it a good idea to proceed step by step.

**Comment by ktf** [comment]
@TimoWilken I thought you fixed the issue with the copyright?

**Comment by TimoWilken** [comment]
@ktf I fixed it in the ["copyright headers" workflow](https://github.com/alisw/ali-bot/blob/master/.github/workflows/c%2B%2B-code-formatting.yml#L145), but not in the fullCI check -- I didn't realise that had the same check. Is it worth maintaining both?

**Comment by ktf** [comment]
no

**Comment by ktf** [comment]
Missing tests were already passing, only thing which changed was the number of metrics. Tested also on hyperloop with my local tag and the usual tests work, with no visibile change in performance.

**Pull request merged**
