### PR TITLE
Adapt to new FairMQDevice APIs for SendAsync / ReceiveAsync

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy can you crosscheck I did not do anything stupid?

**Comment by rbx** [comment]
Keep in mind that previous to the commit that deprecates the -Async methods, the timeout value had different meaning - default was 0 which meant to try sending forever (or until interrupted), and -1 had no meaning. Now 0 is "zero seconds timeout", which means try to send or return if cannot send immediately, and -1 means try to send forever (or until interrupted). The commit also updates the doxygen that describes this.

This means that giving timeout of 0 and using FairMQ older than the deprecation commit version, will try to send forever (or until interrupted).

**Comment by rbx** [comment]
Also, while you're dealing with deprecations, you can remove the `WaitForInitialValidation()` call in QC devices - it doesn't do anything meaningful for a while now and will be deprecated and removed soon as well.

**Comment by Barthelemy** [comment]
The QC folder is not actually QC, it is mergers that are going to be rewritten by Piotr inside the DPL. So for me, no problem. Even with the behaviour highlighted by Alexey I think that your changes are fine.

**Comment by ktf** [comment]
@rbx :-/

**Comment by ktf** [comment]
For the moment I will fix the mergers parts only. DPL would be broken using the production tag and this code...

**Comment by ktf** [comment]
@rbx re `WaitForInitialValidation`, will 1.2.7.1 work fine with it?

**Comment by rbx** [comment]
yes, 1.2.7.1 will work fine without it.

**Comment by ktf** [comment]
@rbx @dennisklein the dev of fairmq now dies with a CMake related error 
https://ali-ci.cern.ch/repo/logs/AliceO2Group/AliceO2/1439/cf8a2cde7b99eab490f258d39146cce811f9878b/build_O2_o2-dev-fairroot/fullLog.txt

Does it ring any bell?

**Comment by dennisklein** [comment]
> @rbx @dennisklein the dev of fairmq now dies with a CMake related error
https://ali-ci.cern.ch/repo/logs/AliceO2Group/AliceO2/1439/cf8a2cde7b99eab490f258d39146cce811f9878b/build_O2_o2-dev-fairroot/fullLog.txt
>
> Does it ring any bell?

Yes, the problem is, that FairRoot still has a [hardcoded list](https://github.com/FairRootGroup/FairRoot/blob/dev/CMakeLists.txt#L276) of Boost modules. In FairMQ dev we added a new dependency to the `container` Boost module.

**Quickfix**: Add `container` to https://github.com/FairRootGroup/FairRoot/blob/dev/CMakeLists.txt#L276
**Proper fix**: After `find_package(FairMQ)`, add the contents of the `${FairMQ_Boost_COMPONENTS}` to the list of Boost components FairRoot depends on, remove duplicates from that list and pass it to `find_package(Boost COMPONENTS ${computed_list})`.

**Comment by ktf** [comment]
This is now dying in `o2-dev-fairroot` because of some conflict created by the new polymorphic allocators which got merged in FairMQ. @mkrzewic is looking into it. See also discussion on https://github.com/alisw/alidist/pull/1363.

**Comment by ktf** [comment]
This works fine for 1.2.7 and should work as well for 1.3.X, once we manage to compile it...

**Pull request merged**
