### PR TITLE
CCDBDownloader: Correcting malformed urls

### PR DESCRIPTION
**Pull request by TrifleMichael**
Current code can lead to malformed URLs because of bad freeing of the `scheme` variable and not copying the port number. This PR aims to fix that. This is a follow up to: https://github.com/AliceO2Group/AliceO2/pull/12206

### CODE REVIEW

**Comment by ktf** [comment]
It would actually be a good idea to have some unit test for the `CCDBDownloader::trimHostUrl` function. Could you add some?

**Comment by ktf** [comment]
Apparently currently broken. Merging.

**Comment by TrifleMichael** [comment]
> It would actually be a good idea to have some unit test for the `CCDBDownloader::trimHostUrl` function. Could you add some?

Yes, I'll add tests for that function as soon as I am able to.

**Comment by ktf** [comment]
Thank you.

**Pull request merged**
