### PR TITLE
TRD raw data should be one file per CRU end point

### PR DESCRIPTION
**Pull request by martenole**

### CODE REVIEW

**Review by davidrohr — DISMISSED** [review]
makes sense. So we need new datasets for SYNTHETIC?

**Comment by martenole** [comment]
Depends.. Do you still have the simulation files lying around? Then I could run `o2-trd-trap2raw` manually again to get the correct files. Otherwise we would need new synthetics, yes. But for the single TFs I could also produce them

**Comment by martenole** [comment]
Not to be merged yet

**Comment by davidrohr** [comment]
for reference, all files in `/home/drohr/raw/new*`/TRD*` have been regenerated, with 1 file per endpoint, for usage in SYNTHETIC runs.

**Comment by martenole** [comment]
To be consistent with the other detectors, the option `o2-trd-trap2raw --file-per cru` produces now one file per CRU end point. This is what the readout is expecting and what is done in the FST

**Review by bazinski — APPROVED** [review]
I think this option change is confusing, but apparently we must change to be confusing like everyone else ...

**Comment by martenole** [comment]
> I think this option change is confusing, but apparently we must change to be confusing like everyone else ...

I agree :(

**Comment by davidrohr** [comment]
> > I think this option change is confusing, but apparently we must change to be confusing like everyone else ...
> 
> I agree :(

we can also change it for all detectors, or just rename the cru option to cruendpoint everywhere...

**Pull request merged**
