### PR TITLE
Analysis: make readability-braces-around-statements happy

### PR DESCRIPTION
**Pull request by anerokhi**
It's me continuing to annoy you with these fixes

### CODE REVIEW

**Review by sawenzel — DISMISSED** [review]

**Comment by sawenzel** [comment]
@jgrosseo : Is this ok with you?

**Comment by jgrosseo** [comment]
I don't mind too much ;-)

**Comment by iarsene** [comment]
Hi, i have nothing against them, but i am not sure how will this be sustainable in the future. Not using braces around single line statements like this is very common.

**Comment by sawenzel** [comment]
@iarsene : I'd like to comment on the rational of this activity to share some information to new developers.

- To start with, we had a dedicated working group some years ago that defined coding rules for the O2 project. The result of this working group are the documents mentioned in the main README and available here https://github.com/AliceO2Group/CodingGuidelines.

- The "brace rule" is part of these guidelines and it's one of the more important ones because it avoids logic errors that can
easily slip in otherwise. A common norm makes total sense here.

- This rule is easy to check in automated checks and we are targeting to add such check as soon as the code base is clean.

**Review by sawenzel — APPROVED** [review]

**Comment by jgrosseo** [comment]
@iarsene @sawenzel Let me just add that I will make a dedicated discussion on which parts we will enforce for O2physics, once O2physics has been created.

**Comment by iarsene** [comment]
@jgrosseo  @sawanzel @anerokhi 
Thanks. This is what i was thinking as well, to have an automated check. Ok, this is fine with me, it can be merged.

**Comment by anerokhi** [comment]
@jgrosseo In case I miss this discussion, you may record my opinion as totally against this rule. At least in its wild form, where braces added to all statements. The requirement to add braces if the statement spans more than 1 line, like in:
```c++
for (...)
   if (...)
      return;
```
would be OK (`for` should have braces, but `if` should not/doesn't need to).

**Pull request merged**
