### PR TITLE
Revert "Create DCAFitter under ./Common"

### PR DESCRIPTION
**Pull request by shahor02**
Reverts AliceO2Group/AliceO2#10644

@ddobrigk  Sorry, noticed the request to not merge too late, reverting and merging

### CODE REVIEW

**Comment by shahor02** [comment]
@ddobrigk actually, since all the tests with your PR were green, probably having it merged does not harm. Will keep this revert PR open, ping me if you want it merged.

**Comment by ddobrigk** [comment]
Hi @shahor02 , I think you are right. Let's merge this, it is harmless and then I can already start with the modifications to O2Physics. The part where we will need to be more careful is only when we go back to O2 to remove the 'original' DCAFitter. Many thanks!

**Comment by shahor02** [comment]
@ddobrigk sorry, did not understand: do you want me to merge this (which will revert your merged PR and suppress the Common/DCAFitter) ?

**Comment by ddobrigk** [comment]
Ah sorry - no, don't merge this, let's leave it as is with the other PR merged and keep the Common/DCAFitter. (Replied on smartphone, I apologize for the imprecision). Thanks!

**Pull request closed without merging**
