### PR TITLE
Missing adjustments following muon change

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@nicolovalle Do you agree?

**Comment by jgrosseo** [comment]
@sawenzel Sorry for this...

**Comment by nicolovalle** [comment]
> @nicolovalle Do you agree?

Hello, I guess that `o2::aod::fwdtrack::MCHBitMap` is also to add?

**Comment by jgrosseo** [comment]
> 
> 
> > @nicolovalle Do you agree?
> 
> Hello, I guess that `o2::aod::fwdtrack::MCHBitMap` is also to add?

Thanks. I also fixed the order.

**Comment by jgrosseo** [comment]
@sawenzel Does the full CI error look related to this change?

**Comment by jgrosseo** [comment]
Most likely this fixes the problem in the aod-producer... Merging

**Pull request merged**
