### PR TITLE
Proper time index when using timePipeline

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 this should give you the correct index. To be decided if this fix is fine or if I actually need an extra field, because the current one is actually the multiplicity of the source, not of the timePipelined device itself....

**Comment by ktf** [comment]
Mmmm... I am almost convinced we actually need to track it in an extra field....

**Comment by shahor02** [comment]
@ktf Thanks, I confirm that the time indices are ok now.

**Comment by ktf** [comment]
Ok, I also checked and as far as I can tell, this is not used anywhere (apart from the GUI, where it actually makes more sense to show the new value). Unfortunately the whole CERN cloud has troubles right now, so the tests are not completing correctly.

**Comment by shahor02** [comment]
@ktf I've checked the workflow removing the device upstream of the timePipeline, in this case the ``DeviceSpec().inputTimesliceId`` is still correctly assigned, but the staggering of timeframes is lost...

**Comment by ktf** [comment]
Failing test on macOS unrelated. The change only affects the GUI for now. Merging.

**Pull request merged**
