### PR TITLE
[EMCAL-565] Include EMCAL bad channel calib in aggregator workflow

### PR DESCRIPTION
**Pull request by mfasDa**
Split CALIB_EMC_CHANNELCALIB into CALIB_EMC_BADCHANNELCALIB and
CALIB_EMC_TIMECALIB in order to steer both calibrators separately.

### CODE REVIEW

**Comment by mfasDa** [comment]
Needs https://github.com/AliceO2Group/O2DPG/pull/574

**Review by chiarazampolli — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Seems fine to me, thanks!

**Comment by mfasDa** [comment]
Hi @chiarazampolli , 

Thanks! When do you think the two PRs could be merged (and deployed) so we can do a test at P2?

Cheers

Markus

**Comment by chiarazampolli** [comment]
Ciao @mfasDa , 
@davidrohr just merged them. I heard yesterday at the S&C meeting that maybe tomorrow there could be an update, but surely @davidrohr knows better.
Chiara

**Pull request merged**
