### PR TITLE
DPL: add workaround for O2-612

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy could you check if this solves your problem?

**Comment by Barthelemy** [comment]
ok, testing it

**Comment by Barthelemy** [comment]
Good, it fixes the problem. Thank you !

**Comment by Barthelemy** [comment]
@ktf So... your daughter drew a portrait of you ? :)

**Comment by ktf** [comment]
Yes! Can’t you tell from the haircut?;-)

**Comment by ktf** [comment]
@dberzano the tests seems to be stuck. Could you please check?

**Pull request merged**
