### PR TITLE
Robin hood flat map

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
How do we benchmark / validate this? According to some random benchmark I found it should be roughly 2x absl::flat_map performance on common operations.

**Comment by sawenzel** [comment]
I think this is the way to go. (Side note: robin_hood is also already in VecGeom and could be taken from there.)

**Review by sawenzel — APPROVED** [review]

**Comment by ktf** [comment]
> Side note: robin_hood is also already in VecGeom and could be taken from there

yes, definitely. Thank you for pointing that out.

**Comment by ktf** [comment]
If this works, the remaining issue is that all these implementation details are leaked to ROOT due to the fact, AFAICT, `EncodedBlock.h` includes a bunch of rANS internals.

**Comment by ktf** [comment]
Closing this. We stay with abseil for the time being.

**Pull request closed without merging**
