### PR TITLE
adding missing pieces in TOF cal workflow

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
@shahor02 @chiarazampolli 
I open the PR to the review.
These changed are required to produce all time calibrations entries in ccdb.
So far I filled test ccdb for all beam test runs with TOF:
/TOF/Calib/LHCPhase
/TOF/Calib/Diagnostic
/TOF/Calib/ChannelCalib (1 entry for all runs)

I'm going to reconstruct few data to validate all the chain but you can already start the review

**Comment by noferini** [comment]
Reconstruction checked: also LHCphase seems to work as expected (I applied just a small fix already in the PR)

**Comment by noferini** [comment]
Now only MacOS check is failing (it didn't start properly).
FullCI error was fixed.

**Comment by TimoWilken** [comment]
Hi @noferini, the checks for this PR seem to take very long -- some of them run for 10 hours before they time out, taking up a lot of CI capacity in the meantime. I'm not sure why this is, but as all checks on this PR are currently red, it seems like it's something in this PR's code causing these timeouts.

Specifically, it seems to be the O2Physics compilation as part of the fullCI check that gets up to

    Building CXX object PWGHF/Tasks/CMakeFiles/O2Physicsexe-analysis-hf-task-d0-alice3-barrel-mc.dir/taskD0ALICE3Barrel.cxx.o

and then just does nothing for 8 hours until it's killed by the timeout.

I'm marking this PR as draft for now, so that it is not retested automatically, in order to free up the CI builders. Please mark it as "ready for review" when you need the tests to run again.

**Comment by noferini** [comment]
@TimoWilken that's fine. Thanks for notifying me

**Comment by noferini** [comment]
Closed, since I will reponed from a different branch

**Pull request closed without merging**
