### PR TITLE
[Test] PWGHF: Configure KFParticle package and add HF analysis task for 3-prongs reconstruction with KF

### PR DESCRIPTION
**Pull request by zhujh126**
**Test. Not ready for review or merging.**
Configure KFParticle package and add HF analysis task for 3-prongs reconstruction with KF

### CODE REVIEW

**Comment by vkucera** [comment]
@zhujh126 What is the status? I don't think the other tests can run while the first three have failed.

**Review by davidrohr — APPROVED** [review]
might need 1 positive review from a new committer to start the test

**Comment by shahor02** [comment]
Also `[WIP]` needs to be removed from the title to trigger the tests (apart from the 1st time approval and fixing the format)

**Comment by vkucera** [comment]
> Also `[WIP]` needs to be removed from the title to trigger the tests (apart from the 1st time approval and fixing the format)

I thought there was no WIP check in place in this repo.

**Comment by shahor02** [comment]
@vkucera I think there is: PRs with [WIP] did not start tests: https://github.com/AliceO2Group/AliceO2/pulls?q=is%3Apr+is%3Aopen+%5BWIP%5D

**Review by vkucera — APPROVED** [review]

**Comment by vkucera** [comment]
> @vkucera I think there is: PRs with [WIP] did not start tests: https://github.com/AliceO2Group/AliceO2/pulls?q=is%3Apr+is%3Aopen+%5BWIP%5D

Both PRs are missing code owners' approval. That might be the blocker there.

**Comment by vkucera** [comment]
@zhujh126 Can you please fix the format and rebase on top of the latest `dev`?

**Comment by vkucera** [comment]
@zhujh126 Any news on this test?

**Comment by vkucera** [comment]
Closing because of O2Physics migration

**Pull request closed without merging**
