### PR TITLE
ALICE 3: Add iTOF, oTOF, fTOF and bTOF geometry proposal

### PR DESCRIPTION
**Pull request by mconcas**
@sawenzel Here is a proposal for the addition of the inner and outer TOFs in run 5 simulation.
3-letter name I chose is `TF3`, it is absolutely symbolic, as usual.

- Currently `iTOF`, `oTOF`, `fTOF` and `bTOF` are implemented as two layers of the same detector, I found not need yet to split them.
Presence should be togglable with `configKeyVals`.
- Backbone for hits is still ITSMFT one, which makes sense as TOFs in ALICE3 would be silicon detectors. Timing information seems to be present already.
- Fixed a misconfiguration that was including ITS3 in Run5 layout.

Current simulation automatically looks CCDB for alignment objects per detector, this means that it would break with merging this PR as it is.
Locally this is overridable with local CCDB + dummy `snapshot.root` in the TF3 path. I was wondering if there is any option to manually disable this fetching or if the `TF3` path should be added to the CCDB as it was done for other detectors.

CC-ing @shahor02 
Screenshot 2023-09-14 at 12 25 37

### CODE REVIEW

**Comment by sawenzel** [comment]
I'll take a look into this. Will come back to you here.

**Comment by sawenzel** [comment]
@mconcas : Currently checking if these detector additions are still compatible with the hit encoding in our MCTrack class. It could be that we no longer have enough bits left to add more detectors. In this case, I'll do the necessary modification in MCTrack first.

**Comment by sawenzel** [comment]
https://github.com/AliceO2Group/AliceO2/pull/11879 should be merged first. Then probably this PR will fail to compile but I have a fix in the pipeline.

**Comment by mconcas** [comment]
> #11879 should be merged first. Then probably this PR will fail to compile but I have a fix in the pipeline.

Thanks a lot for tanking care of this!

**Comment by mconcas** [comment]
> #11879 should be merged first. Then probably this PR will fail to compile but I have a fix in the pipeline.

Hi @sawenzel , I'm reconverting this into draft to avoid CI cycles to be wasted on this. As you mentioned compilation is now broken by the static assert on the detectorID.

**Pull request merged**
