### PR TITLE
MID afterburner for digits synchronization with collision BC

### PR DESCRIPTION
**Pull request by dstocco**
There is an offset between the collision BC and the BC that can be obtained from the electronics clock.
This offset was in principle accounted for, but a bug was found in the correction.
This PR fixes the bug and also introduces an afterburner to change the offset on-the-fly if needed.

The PR consists of 3 commits:
- The first one removes obsolete decoders, that would not compile anymore after this fix. Since they are not used, it is easier to remove them rather than correct them.
- The second improves the way the digits are synchronized in the decoding phase, and fixes a bug.
- The third one introduces an afterburner, which allows to change the offset on-the-fly if needed, instead of re-generating the CTFs.

The commits are meant to be atomic. Please do not squash.

### CODE REVIEW

**Review by aphecetche — APPROVED** [review]

**Comment by dstocco** [comment]
Errors for fullCI are once again unrelated...

**Comment by dstocco** [comment]
When merging, please do not squash...

**Comment by dstocco** [comment]
@aphecetche : all checks are passed but the merging is blocked. Did you allow automatic merge in your review?

**Comment by dstocco** [comment]
Plese do not squash...

**Pull request merged**
