### PR TITLE
Align to the latest version of AliPhysics/RUN3/AliAnalysisTaskAO2Dcon…

### PR DESCRIPTION
**Pull request by pzhristov**
…verter

### CODE REVIEW

**Comment by pzhristov** [comment]
Somehow I did not catch the following issue:

/Users/phristov/alisw/sw/SOURCES/O2/1.0.0/0/Framework/AnalysisTutorial/src/associatedExample.cxx:54:38: error: no member named 'timeframeID' in 'o2::soa::RowViewBase<o2::soa::DefaultIndexPolicy, o2::aod::collision::VtxId, o2::aod::collision::PosX, o2::aod::collision::PosY, o2::aod::collision::PosZ, o2::aod::collision::CovXX, o2::aod::collision::CovXY, o2::aod::collision::CovXZ, o2::aod::collision::CovYY, o2::aod::collision::CovYZ, o2::aod::collision::CovZZ, o2::aod::collision::Chi2, o2::aod::collision::NumContrib, o2::aod::collision::EventTime, o2::aod::collision::EventTimeRes, o2::aod::collision::EventTimeMask>'
    LOG(INFO) << "TF: " << collision.timeframeID() << std::endl;

**Comment by ktf** [comment]
I think that's because with the new cmake infrastructure `cd Framework ; make` does not built everything, I guess. @aphecetche @davidrohr didn't we have a solution for that?

**Comment by pzhristov** [comment]
I will comment out  (temporarily) the use of timeframeID since for the moment we do not have anything reasonable there.

**Comment by aphecetche** [comment]
@ktf @pzhristov Quoting myself from https://alice.its.cern.ch/jira/browse/O2-789 : 

> Rebuild only what's needed from top directory in the build tree :
> cmake --build .
> should work just fine in all cases. And be fast when cmake was configured with ninja generator.

i.e. cmake from topdir is guaranteed to work

**Comment by ktf** [comment]
there is a `"fID4"` to be replaced in `AnalysisTask`

**Pull request merged**
