### PR TITLE
[WIP] Create LICENSE file (GPLv3)

### PR DESCRIPTION
**Pull request by Barthelemy**
As discussed at length in JIRA (https://alice.its.cern.ch/jira/browse/OCCF-1) here is the license file. It is referred to in the header of every source file.

### CODE REVIEW

**Comment by Barthelemy** [comment]
WAIT, I am renaming it

**Comment by Barthelemy** [comment]
@dberzano this is the PR we were discussing

**Comment by dberzano** [comment]
Thanks, so we are missing:

- [ ] List of institutes
- [ ] All headers changed

**Comment by matthiasrichter** [comment]
And of course the [WIP] should be removed in the PR title

**Comment by dberzano** [comment]
@matthiasrichter no, I am changing it in order to make it accept the `COPYING` file at the top of the repository instead

This PR is good to me, merging.

**Comment by dberzano** [comment]
@matthiasrichter sorry I correct myself: I am changing it in order to point to: http://alice-o2.web.cern.ch/license (no https).

**Comment by matthiasrichter** [comment]
ah, ok, this is what I meant. Maybe you can allow both for a short period, that probably would make the migration easier? But probably its better to change it in one go.

**Comment by dberzano** [comment]
Thanks to @sawenzel the automatic check is run only on the files touched by the PR, doing it on one go is a matter of running `sed`. Let me do that in a second, I am on a roll :-)

**Comment by matthiasrichter** [comment]
good

**Pull request merged**
