### PR TITLE
TOF: Add T0 bias remover function 

### PR DESCRIPTION
**Pull request by njacazio**
Also improve naming for data members
@noferini

### CODE REVIEW

**Comment by noferini** [comment]
o2 check failing with
/sw/SOURCES/O2Physics/8293-slc7_x86-64/0/Common/TableProducer/PID/pidTOF.cxx:206:31: error: 'const struct o2::tof::eventTimeContainer' has no member named 'eventTime'; did you mean 'mEventTime'?
  206 |             float et = evTime.eventTime;
  
  and other simlar errors.
  Do you need to fix naming also there?

**Comment by njacazio** [comment]
@noferini indeed, this PR has an impact on O2Physics, I added the link to that one, in principle they should be merged together

**Comment by noferini** [comment]
@shahor02 
For me it is fine to merge but I don't know what is the order we have to follow

**Comment by shahor02** [comment]
Hi,
In principle, the correct way for such interdependent PRs is to have e.g. O2 PR preserving the names needed by O2Physics (on top of needed modifications), then merge fixed O2Physics, then remove obsolete members in O2. 
I cannot merge O2Physics, do you want me merge this? This will make to fail all O2 CIs until the O2Physics is merged.

**Comment by njacazio** [comment]
Hi @shahor02 you're right, I added aliases to the new variables that can be removed later in another PR, thanks a lot for the suggestion!

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
