### PR TITLE
Porting latest ITSU Outer Barrel geometry from AliRoot v2 to O2

### PR DESCRIPTION
**Pull request by mario6829**
The latest ITSU Outer Barrel description was ported from current AliRoot v2 version to O2 V3 version. This completes the porting of the sensitive volumes.

### CODE REVIEW

**Comment by mario6829** [comment]
@iouribelikov Hi Yura, I just submit a PR for the porting of OB geometry from AliRoot to O2.

**Comment by mario6829** [comment]
@sawenzel Hello, do you please have time to review my PR ? it is somehow the completion of the previous one, i.e. porting the Outer Barrel geometry from AliRoot to O2. Please let me know if any change is needed. For what concerns good practises in C++ coding, if there is anything to be fixed please let me know, I am going to prepare another PR including the remarks you made me in the previous PR. Many thanks. Kindest regards

**Comment by sawenzel** [comment]
@mario6829: Taking a look now...

**Comment by sawenzel** [comment]
I am ok with it. @iouribelikov : Any opinion?

**Comment by sawenzel** [comment]
@mario6829 : Shall we wait for Iouri to give an opinion or proceed with the merge?

**Comment by shahor02** [comment]
Hi, afaik, Yura is on vacation w/o connection. I think the PR can be merged.

**Pull request merged**
