### PR TITLE
Configurable pipeline length

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Review by davidrohr — APPROVED** [review]

**Comment by ktf** [comment]
In principle the completion policy allows overriding this already, but the extra env var is probably better...

**Comment by ktf** [comment]
Merged because it fixes hyperloop (with a pipeline of 16).

**Comment by davidrohr** [comment]
Do we understand why it fails on hyperloop with a longer pipeline length?
This could hint to another bug somewhere?

**Comment by ktf** [comment]
I think I need to move the rate limiting inside the loop which creates new timeslices, otherwise on the first iteration will end up creating all of them and do the rate limiting too late.

**Comment by davidrohr** [comment]
ok, that makes sense

**Comment by ktf** [comment]
Notice this only affect the rate limiting on shared memory usage, not the one on the timeframes (at least based  on how it's implemented right now).

**Pull request merged**
