### PR TITLE
DPL: make sure we correctly handle DPL created messages

### PR DESCRIPTION
**Pull request by ktf**
DPL: make sure we correctly handle DPL created messages

This should fix the issue about the missing DISTSUBTIMEFRAME messages for good.

### CODE REVIEW

**Comment by ktf** [comment]
@martenole this should fix the issue with the spurious messages for some of the proxies. Could you verify that is the case?

**Comment by ktf** [comment]
Nevermind, this still has some troubles. I am looking into it.

**Comment by ktf** [comment]
Ok, this time it should be the good one.

**Comment by martenole** [comment]
Thanks, I'll give it a try

**Review by martenole — APPROVED** [review]
Looks good!

**Comment by martenole** [comment]
Shall I merge @ktf ?

**Pull request merged**
