### PR TITLE
[EMCAL-843] Optimisation cell-level compression

### PR DESCRIPTION
**Pull request by mfasDa**
- Make EMCAL cell uncompressed at transient level
- New energy compression algorithm based on cell type
- Provide reading directive from packed bitset
- Perpare CTF Coder for V0-V1 switch

### CODE REVIEW

**Comment by mfasDa** [comment]
Needed to operate transiently with full precision. In a second step the compression method will be changed to optimise the bit usage to provide higher precision at lower energies.

The idea of the new compression is to make use of the cell type bit to separate the bitmap into two energy ranges, corresponding to the energy ranges of the HG (0-16 GeV) and LG (16 - 250 GeV) hardware digitisers, and take the cell type bit into account in the energy compression to distinguish the two ranges. This allows with the minimum amount of bits used in the CTF to recover the performance of the uncompressed case. A drawback of this compression is however that the energy calibration can move cell energies from the low gain to the high gain region and vice versa, and the cell type cannot be changed since the time calibration depends on it. As consequence the compression which is now used for in-memory representation must be used only when writing to / reading from CTF, which happens before any energy calibration is applied.

**Comment by mfasDa** [comment]
Continuing discussion from #11766

**Comment by mfasDa** [comment]
Needs #11215

**Comment by mfasDa** [comment]
The unit test has been adapted in a way that it simulates only 3 type FEE, LEDMON and TRU for channel type determination. In case the type is FEE the channel type will be set to HG/LG depending on the simulated energy using the HG-LG transition at approx 16 GeV. This is needed once the energy en/decoding takes into account the cell type.

**Comment by shahor02** [comment]
@mfasDa seems to work fine, also compatible with https://github.com/AliceO2Group/AliceO2/pull/11215.
Could you apply the attached patch to enable new dictionary?
[emc.patch.gz](https://github.com/AliceO2Group/AliceO2/files/12448261/emc.patch.gz)

**Comment by shahor02** [comment]
@mfasDa 

Using this PR + my patch above I've 
I've extracted cells for LHC23zc fill 8897
```
o2-raw-tf-reader-workflow --shm-segment-size 12000000000 --input-data raw_fill8897.txt --onlyDet EMC | o2-tfidinfo-writer-workflow  --shm-segment-size 12000000000 |  o2-emcal-reco-workflow  --shm-segment-size 12000000000 --input-type raw --output-type cells -b
```
The spectrum of `cell.getEnergy()` looks like this:
```
TFile *_file1 = TFile::Open("emccells.root");
t1->Draw("EMCALCell.getEnergy()");
```
cell_orig

Isn't it strange?

Then I've created a dictionary 
```
o2-emcal-cell-reader-workflow --disable-mc --hbfutils-config o2_tfidinfo.root  | o2-emcal-entropy-encoder-workflow  --ctf-dict none | o2-ctf-writer-workflow --onlyDet EMC --output-type dict   -b
cp ctf_dictionaryTree_EMC_1693145145_32.root ctf_dictionary_EMC_v1.1.root
```
and created ctf from these cells using new dictionary:
```
o2-emcal-cell-reader-workflow --disable-mc --hbfutils-config o2_tfidinfo.root  | o2-emcal-entropy-encoder-workflow  --ctf-dict ctf_dictionary_EMC_v1.1.root  | o2-ctf-writer-workflow --onlyDet EMC --output-type ctf  --min-file-size 10000000000 --max-ctf-per-file 100000 --b
```
Then, decoded cells from the new ctf as
```
o2-ctf-reader-workflow --onlyDet EMC --ctf-input o2_ctf_run00537959_orbit0128149984_tf0000040533_alicers05.root --ctf-dict ctf_dictionary_EMC_V1.1.root |  o2-emcal-cell-writer-workflow --disable-mc --outfile decCell.root -b
```
The decoded spectrum is very different:
```
TFile *_file0 = TFile::Open("decCell.root");
o2sim->Draw("EMCALCell.getEnergy()");
```
cell_dec

So, something is wrong in creation of the cell object from decoded columns, could you check?

I've copied to https://cernbox.cern.ch/s/vooYYutBVLgFFZ3 the files:
```
tar cvzf emc.tar.gz raw_fill8897.txt emccells.root decCell.root ctf_dictionary_EMC_v1.1.root
raw_fill8897.txt
emccells.root
decCell.root
ctf_dictionary_EMC_v1.1.root

```

**Comment by mfasDa** [comment]
@shahor02 Running the chain as you described above, with V1 encoding (different bit ranges for HG and LG cells) I get the comparison attached, which looks as expected. 

ComparisonCellEnergy_V1Encoding

**Comment by mfasDa** [comment]
There was one more bug which affected V0 encoding (again missing breaks in switch statements). After that I get also for V0 encoding good comparison uncompressed / compressed:
ComparisonCellEnergy_V0Encoding

**Comment by shahor02** [comment]
@mfasDa ok, good, did you use the dictionary I've created?  Once the CI is passed, I think we can merge this, the dictionary will need to be uploaded to both http://alice-ccdb.cern.ch/browse/EMC/Calib/CTFDictionary (for current dev) and http://alice-ccdb.cern.ch/browse/EMC/Calib/CTFDictionaryTree (for the code with @MichaelLettrich 's updates) in sync with o2 deployment at P2.

**Comment by mfasDa** [comment]
> @mfasDa ok, good, did you use the dictionary I've created? Once the CI is passed, I think we can merge this, the dictionary will need to be uploaded to both http://alice-ccdb.cern.ch/browse/EMC/Calib/CTFDictionary (for current dev) and http://alice-ccdb.cern.ch/browse/EMC/Calib/CTFDictionaryTree (for the code with @MichaelLettrich 's updates) in sync with o2 deployment at P2.

No, I ran all steps, including dictionary creation. I can send you the dictionary file I created in a private message.

**Comment by shahor02** [comment]
As I wrote, we need both kind of dictionaries. The best if you create a tar.gz and attach it here.

**Comment by mfasDa** [comment]
> As I wrote, we need both kind of dictionaries. The best if you create a tar.gz and attach it here.

Here it is: [emcdict.tar.gz](https://github.com/AliceO2Group/AliceO2/files/12464404/emcdict.tar.gz)

**Comment by mfasDa** [comment]
As last check reading old CTFs with old and new cell class on CTFs from LHC22m (energy calibration runs), showing that we can read old CTFs with updated CTF Coder into new cell objects:

ComparisonOldCTF

**Comment by shahor02** [comment]
Good, the CI failures are unrelated, merging.
I've opened CCDB update ticket https://alice.its.cern.ch/jira/browse/O2-4078 but will do uploads at the deployment of updated O2 at P2.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
