### PR TITLE
[O2-1334] Change the volume path names according to the presence of other volumes

### PR DESCRIPTION
**Pull request by flodamas**
Fix the MCH digitizer (see https://alice.its.cern.ch/jira/browse/O2-1334).

### CODE REVIEW

**Comment by aphecetche** [comment]
@flodamas looks fine but I see no corresponding test. I assume you don't (currently) have time to provide one ? If that's the case I'll try to provide one.

**Comment by flodamas** [comment]
@aphecetche sorry I missed your comment on the jira ticket. I did not think about a test yet and I am not sure I would have time for that this week.

**Comment by aphecetche** [comment]
@flodamas no worries, I'll do it.

**Comment by aphecetche** [comment]
@flodamas as far as I can tell your fix is not correct ? Or my test is wrong... But I believe the volume names in getTransformations should have a _1 suffix ? 

Could you please have a look at https://github.com/AliceO2Group/AliceO2/pull/3394 and tell me if you agree (if that's the case, please close this one).

**Pull request closed without merging**
