### PR TITLE
Fix trd trackletplots

### PR DESCRIPTION
**Pull request by bazinski**
1. put all tracklet plots in 1 file, no more hundreds of files.
2. correctly plot graphs for COLZ option and actually working.
3. output corresponding text for each plot to cross reference the plots with the tracklet parameters 
4. something wrong with the calcuation of offsets as the tracklet line is often off the axises, fixed later.

### CODE REVIEW

**Comment by bazinski** [comment]
> Hi @bazinski, I am wondering what is the purpose of this plots? Are these used in calculations inside the TRAP? Otherwise I would put them in a separate macro.

Purpose is mostly debugging. If it were in a macro some of the data is lost once you get the trdtracklets file, in particular the raw and filtered adc data and the hits, probably more.

Maybe your question is better formulated as should we have an exceptionally verbose tracklet debugging class with *all* info in it, adc raw/filtered, fit registers, residues, hits, etc. Then a macro would be doable.

The draw method was originally in the trapsimulator so I just followed on and left it in there.
I think it will only ever be used for debugging, it becomes almost useless to have 1000's of canvases to look at. This goes for the print method as well, which dumps the raw and filtered adc values.

**Comment by jolopezl** [comment]
> > Hi @bazinski, I am wondering what is the purpose of this plots? Are these used in calculations inside the TRAP? Otherwise I would put them in a separate macro.
> 
> Purpose is mostly debugging. If it were in a macro some of the data is lost once you get the trdtracklets file, in particular the raw and filtered adc data and the hits, probably more.
> 
> Maybe your question is better formulated as should we have an exceptionally verbose tracklet debugging class with _all_ info in it, adc raw/filtered, fit registers, residues, hits, etc. Then a macro would be doable.
> 
> The draw method was originally in the trapsimulator so I just followed on and left it in there.
> I think it will only ever be used for debugging, it becomes almost useless to have 1000's of canvases to look at. This goes for the print method as well, which dumps the raw and filtered adc values.

I see the purpose to have it there then.

**Comment by bazinski** [comment]
> I assume the drawing has to be called explicitly, to avoid clutter during normal operation. Then this implementation is fine.
Yes there is a cli option of --trd-drawtracklets  (boolean)
> 
> Will it be possible in the future to generate these plots directly from the TRAP Reg Dump?

Yes, all the info is available in the trap register dumps. It could then be changed into a root macro when finalised, as earlier queried by @jolopezl 

However what I dont get is that this was completing the CI happily, then it was failing build/O2/o2 and when I came back it was fine again, and now I see gpu is failing? But nothing has changed in this code. This could be needing a rebase to dev to get the builds working.

**Comment by bazinski** [comment]
Ooops I by mistake closed the PR .....

**Pull request merged**
