### PR TITLE
DPL: add SendingPolicy for the case destination is expendable

### PR DESCRIPTION
**Pull request by ktf**
DPL: add SendingPolicy for the case destination is expendable

---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/AliceO2Group/AliceO2/pull/12676).
* __->__ #12676
* #12675

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy @knopers8  @davidrohr @martenole this makes my standalone test behave correctly when an expendable task is killed. Indeed the oldest possible timeframe needs to use the policy mechanism and we need an explicit policy for dropping data not going to expendables. In principle this also allows things which are not "Dispatcher"s to be before expendable task.

**Comment by Barthelemy** [comment]
Thanks !

**Comment by ktf** [comment]
A couple of tests seems to be broken, actually. I am looking into it.

**Comment by ktf** [comment]
Ok, I understand what is going on. Fix coming later.

**Comment by martenole** [comment]
Hi @ktf I can reproduce the crash of the fullCI locally. Without this PR its working fine. Could you please take a look?

**Review by martenole — COMMENTED** [review]
Thanks, I don't see any errors anymore. But with this included we get backpressure on the EPNs after some time of running. Is some negative performance impact expected due to this?

**Comment by martenole** [comment]
Nevermind. This was due to additional processing steps

**Pull request merged**
