### PR TITLE
[ITS-workflow][GPU] Extend o2-its-reco-workflow configurability 

### PR DESCRIPTION
**Pull request by mconcas**
Hi, @shahor02, @iouribelikov,

I am trying to streamline a bit the usage of the vertexer and later the CA tracker, starting to include also the possibility to run GPU reconstruction as a WF.
Albeit it can eventually can converge in a unified GPU framework, I think it is nice to have a standalone invoker for CPU/GPU reconstruction that will possibly replace the steering macros.

With current PR my primary concern is to check whether the former behaviour of the `o2-its-reco-workflow` is kept.

Notably, main changes in the workflow are:

- Tracker and Vertexer traits are now taken from the O2GPUReconstruction interface. This will help to uniform the interface for traits delivering and will possibly help as a test for compatibility in case of a CPU-only installation
 - It is now possible to select the processing unit to be used in the workflow, from the help function:
```bash
$> o2-its-reco-workflow --help
[...]
--gpuDevice arg (=1)                  use gpu device: CPU=1,CUDA=2,HIP=3 
                                        (default: CPU)
```

 - It is now possible to override Vertexer configuration by the `--configKeyValues` parameters.
In this case I still need to have our local `Configuration.h` file in ITS, because of those cases that don't use the workflow interface (standalone/steering macros). Also, since the `ConfigParams` facility is not gpu-compiler friendly, I still need the intermediate struct called `VertexerTraits`  as a proxy object to be passed to three different implementations. Ultimately, there are  some parameters (mostly related to memory configuration and paramters used by GPU kernels) that at the moment are kept separated and not editable at _runtime_. It will probably kept like this even in the future.
I anyway merged some redundant configuration

Ultimately, there are various minor fixes here and there, both in GPU code and few typos found in the nice guide for ConfigParams usage.

Please, let me know what do you think.

Cheers,
Matteo

### CODE REVIEW

**Comment by shahor02** [comment]
@mconcas fine for me, just a dilettante question: do we really need to provide ``cuda`` vs ``hip`` or we can simply enable the gpu and then the system should detect itself what if it is nvidia or amd?

**Comment by davidrohr** [comment]
@shahor02 : This could be done in the future, but at the moment such autodetection is not supported in the GPUReconstruction

**Comment by mconcas** [comment]
Moreover, like in my case where I have both on the same computer, I'd like to swap from one to the other.

**Comment by iouribelikov** [comment]
@mconcas The parts of it that I may understand look fine for me.
Cheers,
Yura.

**Comment by mconcas** [comment]
Codacy's opinion has been triggered because of fixing some typos on a .md file.
If you want me to modify it to comply just tell me. At the moment I don't want to trigger any CI, because everything is green.

**Comment by shahor02** [comment]
I think it is better to fix it.

**Comment by mconcas** [comment]
> Fine with me, perhaps you can clean up the .md with the next PR, and also the indentation in the STEER CMakeFiles, which you changed here.

reverted

**Comment by mconcas** [comment]
Well, I reverted the typo correction since it appears that I am not able to comply with Codacy's config for markdown format.
I tried some tool to automatically apply some "standard" format to markdown files, however it turned out they were basically rewriting every single line.
Reverting the file does not cause Codacy to process it.

**Comment by shahor02** [comment]
@mconcas did not codacy complain only about having 2 headers? Anyway, merging as it is now, the readme can be corrected in separate PR.

**Comment by mconcas** [comment]
> @mconcas did not codacy complain only about having 2 headers? Anyway, merging as it is now, the readme can be corrected in separate PR.

Yes, initially, then I fixed that and started complaining about the marker used for lists, then was about the number of spaces in indentations before and after markers, ... at the 4th iteration i gave up.

**Pull request merged**
