### PR TITLE
Data inspector

### PR DESCRIPTION
**Pull request by a-wolk**
@ktf
* add message interception for Data Inspector

### CODE REVIEW

**Comment by ktf** [comment]
Thank you for your efforts.

Please, make sure you refactor the history in commits which you think can be merged standalone. Given most of the functionality is in a service, I would start by having a separate folder, e.g. Framework/DataInspector and move anything related to that service in there. You can then create a plugin for that which can be loaded by using the DPL_LOAD_SERVICES environment variable. Doing so should minimise the actual changes which you need on the framework side, hopefully just the extra sending policy.

As a side note, please make sure you use clang-format and that you have the correct copyright header at the top of each file.

**Comment by a-wolk** [comment]
@ktf 
We've moved almost everything to plugin (except command line arguments) and we also tried to refactor history as much as possible.

**Review by ktf — DISMISSED** [review]

**Comment by ktf** [comment]
Thanks. Approved to start the testing.

**Comment by ktf** [comment]
There seems to be some compilation errors, could you please have a look and fix them? Once you push again the tests should restart automatically.

**Comment by a-wolk** [comment]
@ktf 
I fixed two tests that probably failed, but I have also updated the branch and I think we need an approve once again to run tests.

**Comment by a-wolk** [comment]
@ktf Can we run tests again?

**Review by ktf — DISMISSED** [review]
Ok to test.

**Comment by mrzelak** [comment]
@ktf 
Most errors depend on code we didn't even touched, this includes GPU/ directory and cuda. We are not allowed to view full logs, but it seems that check failed on fullCI, which also failed on some other merged pull requests. Can you have a quick look please at these logs to check whether the failures are really related?

**Comment by ktf** [comment]
Can

**Comment by mrzelak** [comment]
@ktf 
Applied changes according to coding style, now it's ready to test.

**Comment by mrzelak** [comment]
@ktf 
Can we run tests again?

**Comment by ktf** [comment]
Sure, just reopen the PR.

**Comment by mrzelak** [comment]
@ktf
Can you reopen this PR? AFAIK I don't have the permissions.

**Comment by mrzelak** [comment]
@ktf
Any news on reopening the PR?

**Pull request closed without merging**
