### PR TITLE
DPL: make more services thread safe

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr can you verify the recursive_mutex it's not too expensive in the full test (even in non multithreaded mode)? The microbenchmark I have for DataRelayer does not show any relevant difference, but just to make sure...

**Comment by ktf** [comment]
@knopers8 can you also check the mutex does not affect performance of datasampling?

**Comment by knopers8** [comment]
It seems that the metrics from Monitoring aren't printed anymore? do i need to set some kind of flag now to enable them?

**Comment by ktf** [comment]
@Kavaldrin is this the same issue you were mentioning at some point?

**Comment by Kavaldrin** [comment]
@ktf Sorry for the late reply. But probably not, my point was that there are missing metrics from destructor logic of monitoring class (not every metric but some of them, for example cpuTimeConsumedByProcess). This issue is still existing as I checked.

**Pull request merged**
