### PR TITLE
recover TPC-TOF matching perf in Pb-Pb sim

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
This PR should recover old performance in Pb-Pb simulations, keeping matching for cosmic unchanged

**Comment by davidrohr** [comment]
Thx, I'll have a look later today

**Review by davidrohr — APPROVED** [review]
This looks much better than before. I am getting
```
[105639:TOFRecoWorkflowWithTPC]: [11:57:08][INFO] Timing prepareTOFCluster: Cpu: 9.000e-02 s Real: 9.992e-02 s in 0 slots
[...]
[105639:TOFRecoWorkflowWithTPC]: [12:01:27][INFO] Timing Do Matching: Cpu: 2.478e+02 s Real: 2.478e+02 s in 0 slots
[105639:TOFRecoWorkflowWithTPC]: [12:01:27][INFO] Shifting Z for 303699 matched TPC tracks according to TOF time info
[105639:TOFRecoWorkflowWithTPC]: [12:01:27][INFO] TOF Matching total timing: Cpu: 2.593e+02 Real: 2.592e+02 s in 1 slots
```
so 4.5 minutes instead of 30 minutes

**Comment by noferini** [comment]
> This looks much better than before. I am getting
> 
> ```
> [105639:TOFRecoWorkflowWithTPC]: [11:57:08][INFO] Timing prepareTOFCluster: Cpu: 9.000e-02 s Real: 9.992e-02 s in 0 slots
> [...]
> [105639:TOFRecoWorkflowWithTPC]: [12:01:27][INFO] Timing Do Matching: Cpu: 2.478e+02 s Real: 2.478e+02 s in 0 slots
> [105639:TOFRecoWorkflowWithTPC]: [12:01:27][INFO] Shifting Z for 303699 matched TPC tracks according to TOF time info
> [105639:TOFRecoWorkflowWithTPC]: [12:01:27][INFO] TOF Matching total timing: Cpu: 2.593e+02 Real: 2.592e+02 s in 1 slots
> ```
> 
> so 4.5 minutes instead of 30 minutes

Thanks for the check
Francesco

**Pull request merged**
