### PR TITLE
IDC deltas always on and default scaling for tracks for TimeGain calib

### PR DESCRIPTION
**Pull request by chiarazampolli**
@davidrohr , @martenole , @matthias-kleiner , @rmunzer , @wiechula

### CODE REVIEW

**Comment by davidrohr** [comment]
As we have changed the defaults for the scaling meanwhile, perhaps we should also put them here.

**Comment by chiarazampolli** [comment]
Yes, I am waiting for @rmunzer  to confirm that the ones he used lately are fine.

**Comment by martenole** [comment]
But in general we would not need this now for the PbPb test, right? As we can do all the changes with env vars

**Comment by davidrohr** [comment]
Yes, and anyway we might need different settings in Pb-Pb than in pp.

**Comment by chiarazampolli** [comment]
> But in general we would not need this now for the PbPb test, right? As we can do all the changes with env vars

Yes.

**Comment by chiarazampolli** [comment]
Hello @rmunzer , @wiechula , 
What should be the default after the tests? What about PbPb?
Thanks!

**Comment by wiechula** [comment]
@chiarazampolli , I suggest to use for now the defaults we tested:
```
SCALEEVENTS_TPC_TIMEGAIN=10
SCALETRACKS_TPC_TIMEGAIN=1000
```
They should also be fine for low rate PbPb

**Comment by chiarazampolli** [comment]
Hi @wiechula , 
Done. On Friday, the variables will have to be passed from command line, as there is no update of O2 foreseen. Then we can use synthetic to tune for high IR PbPb. 
If there are no further comments, @davidrohr , can this be reviewed?
Chiara

**Review by davidrohr — APPROVED** [review]

**Pull request merged**
