### PR TITLE
Update CODEOWNERS

### PR DESCRIPTION
**Pull request by mconcas**
@qgp it looks like you and @marcovanleeuwen were listed already.
Added myself.

### CODE REVIEW

**Comment by qgp** [comment]
@mconcas Thanks for this PR. I support the addition of Matteo as co-coordinator of the simulation and performance WG for ALICE 3.

**Comment by davidrohr** [comment]
@mconcas : I would suggest you add yourself also to DataFormats/Detectors/Upgrades.

**Comment by mconcas** [comment]
> @mconcas : I would suggest you add yourself also to DataFormats/Detectors/Upgrades.

sure, indeed

**Comment by marcovanleeuwen** [comment]
Hi Matteo, all, I keep getting reminders of this, while it looks like the commit has been merged already; do you know how to close this thread?

**Pull request merged**
