### PR TITLE
Do not try to be smart about long lines

### PR DESCRIPTION
**Pull request by ktf**
Too many things fall apart when clang-format tries to be smart about
reflowing long lines, resulting in a clearly more confusing resulting
code.

This prevents the reflowing, but results in less far positives. While
I fully agree that long lines are bad, I guess people in general tend
to avoid those and the benefit for the number of false positives is too
low.

### CODE REVIEW

**Comment by ktf** [comment]
@dberzano @sawenzel @matthiasrichter (for some reason I am not able to add you as reviewers).

**Comment by Barthelemy** [comment]
I agree. Would there be a way to check for it and generate an error in the PR while not bothering the people who use clang-format ?

**Comment by ktf** [comment]
yeah, that sounds like an extremely good idea. Will think on how to do that.

**Comment by ktf** [comment]
@Barthelemy This should have the behavior you asked. The commit with the long line will have to be dropped before merging.

**Comment by ktf** [comment]
For b), I will post a fix for it. It should be trivial.

For a), clang-format was not fixing our code either, as the output was in general not usable when a line was too long or when multiple lines could be put on the same line. Now clang format fixes everything but the long lines which we need to handle by hand in any case.

**Comment by sawenzel** [comment]
We are now still lacking tool support as there will be no replacement for a). It might be tough to teach my editor to both use clang-format as well as keeping an eye on the column limit which is handled by an external constraint.

**Comment by ktf** [comment]
Fix for a) is in #1117.

I think the point is that at the moment clang-format produces badly formatted files, requiring either manual intervention or simply skipping the reformatting because it would add too much noise.

This solution is not ideal, but any editor has a "gutter" feature which you can use to mark a given column to remind you to stay in the limits so I am not sure why this would be an issue. As a tradeoff I think using such a gutter is way less of a problem than systematically wrong reflowing of text as it is now.

**Pull request merged**
