### PR TITLE
Add MID DCS Processor

### PR DESCRIPTION
**Pull request by aphecetche**
Given that both MCH and MID share most of their DCS -> CCDB workflow,
the initial MCH-only code has been moved to a new MUON/Common
subdirectory, and the few differences between MCH and MID are handled
at compile time using compilation definition (`-DMUON_SUBSYSTEM_MCH`
or `-DMUON_SUBSYSTEM_MID`), so both subsystems share the source code (for
the dcs processor itself and the little dcs-ccdb program used to quickly
inspect what is in the CCDB for that subsystem).

From that single source code we do generate different executables :

- o2-calibration-mch-dcs-processor-workflow
- o2-calibration-mid-dcs-processor-workflow
- o2-mch-dcs-ccdb
- o2-mid-dcs-ccdb

so that each subsystem can be used completely independently.

Note that for testing there are also `o2-calibration-[mid|mch]-dcs-sim-workflow`
executables. Those executables do not share their source code as they
are merely creating aliases, which _are_ different for both subsystems.

### CODE REVIEW

**Comment by aphecetche** [comment]
@dstocco this is the first version of the MID DCS processor, could you please have a look ? Thanks.

**Comment by dstocco** [comment]
Hi @aphecetche : it looks fine for me. Just a question: you have HV_V and HV_I for MID.
Now, the I is the current, so it is not exactly the high voltage. Are you using HV only to distinguish the HV system from the LV one? If so, naming is fine. Otherwise, I should be separate.

**Comment by aphecetche** [comment]
HV_I indeed means the current drawn by the HV power supply, and yes, the HV vs LV is to distinguish between both kind of power supplies, e.g. for MCH : 

https://github.com/AliceO2Group/AliceO2/blob/004629f96c52aea6bf3d274d411234d2796a2eff/Detectors/MUON/MCH/Conditions/include/MCHConditions/DCSNamer.h#L22-L28

**Comment by aphecetche** [comment]
@TimoWilken last time the fullCI was attempted for this PR is two days ago : will it eventually be tried again automatically at some point or should something be manually triggered ?

**Comment by TimoWilken** [comment]
@aphecetche it will eventually run again, but there's a bit of a queue at the moment and yellow/untested PRs have priority. If it's urgent, I can mark fullCI on this PR as yellow, so it runs again as soon as possible.

**Comment by aphecetche** [comment]
@TimoWilken no, this one is not urgent, I can wait.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
