### PR TITLE
DPL: allow Lifetime::Optional to work with ORIGIN/DESCRIPTION

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 I think this is what is needed for the wildcard case.

**Comment by ktf** [comment]
@TimoWilken looks like something is wrong with the tests?

**Comment by shahor02** [comment]
@ktf thanks, will be able to test in a couple of days.

**Comment by ktf** [comment]
Ok. by then I should also have a proper test for this showing how to use it and making sure it works as claimed.

**Pull request merged**
