### PR TITLE
DPL: optimize processDanglingInputs

### PR DESCRIPTION
**Pull request by ktf**
Before this processDanglingInputs does NxM complex pass on the
inputs and the expirators, checking if there is anything to be
expired and eventually expiring it.

This changes things so that we do Nxm complex pass, where m is
the actual inputs that can expire, i.e. we do not do the pass
for all the inputs which do not have an expiration policy attach.
Since not having an expiration policy is the norm, this should
minimize the impact of processDanglingInputs for normal usage.

### CODE REVIEW

**Comment by ktf** [comment]
@knopers8 can you check with this?

**Comment by aalkin** [comment]
@ktf latest change, that removed metrics from DataRelayer::setPipeLength() also broke {test,benchmark}_DataRelayer, since DataRelayer::publishMetric() now needs to be explicitly called after constructing the DataRelayer.

**Comment by ktf** [comment]
@mkrzewic do you understand what is going on with the tests?

```
	 54 - DataFormats/MemoryResources/test/testMemoryResources.cxx (Failed)
	 72 - Utilities/O2Device/test/test_O2Device.cxx (Failed)
```

@davidrohr the error seems to be correlated with the merging of #2541, any idea of what could interfere?

**Comment by ktf** [comment]
Merging since errors seem unrelated and present also elsewhere.

**Pull request merged**
