### PR TITLE
MFT: add macro for conversion digits to raw

### PR DESCRIPTION
**Pull request by bovulpes**
This is a clone of the corresponding macro for the ITS, adapted to the MFT read-out.

### CODE REVIEW

**Comment by aphecetche** [comment]
@bovulpes let me know if you need help editing the new CMakeLists.txt

**Comment by bovulpes** [comment]
Thanks @aphecetche I just duplicated the ITS entries, I hope it works.

**Comment by aphecetche** [comment]
@bovulpes It should. But note that you can also check locally whether it's working or not using either : 

ALIBUILD_O2_TESTS=1 aliBuild --defaults o2 build O2

or 

aliBuild --defaults o2 build O2
eval $(alienv load O2/latest)
cd sw/BUILD/O2-latest/O2
ctest -L macro -R mft

**Comment by bovulpes** [comment]
bash: ctest: command not found   ??

**Comment by aphecetche** [comment]
If you don't have cmake installed locally (i.e. just have the one installed by aliBuild), then for the second option above you also need to load CMake/latest from alienv.

**Comment by bovulpes** [comment]
OK thanks: 100% tests passed, 0 tests failed out of 16

**Pull request merged**
