### PR TITLE
DPL: add instructions for the remote GUI

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
image
image

**Comment by ktf** [comment]
@shahor02 @davidrohr could you check if you have the same rendering issues with the GUI when running in "remote" mode, over websocket? That would tell us if the problem is at the level of the renderer or already at the level of ImGUI. Notice you might have to allow for CORS in Firefox.

**Comment by mvala** [comment]
@ktf is it possible to specify port as enviroment variable? Something like
```
export DPL_DRIVER_REMOTE_GUI_PORT=12345
```

**Comment by ktf** [comment]
Have you tried with DPL_REMOTE_GUI_PORT?

Ciao,
Giulio

**Comment by mvala** [comment]
No i didn't and i've just tried and it is working. Maybe it can be documented. Thanks

**Comment by ktf** [comment]
I have updated  the documentation in #10072 . Thank you for trying things out.

**Pull request merged**
