### PR TITLE
fix small bugs

### PR DESCRIPTION
**Pull request by AllaMaevskaya**
small bugs fix

- not store empty digit
- write last word

### CODE REVIEW

**Comment by shahor02** [comment]
@AllaMaevskaya : thanks! Now the empty digits are gone but I still see difference between the number of channels assigned to digit and the sum of its nChanA and nChanC:
nch

Could you check please?

**Comment by AllaMaevskaya** [comment]
Yes, number of channels in triggers take into account only channels with CFD time within range +-2.5ns - only these are participate in trigger decision. But in digits all channels with CFD signal are written. 
So they could be different

**Comment by shahor02** [comment]
Ok, thanks, then everything is fine.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by shahor02** [comment]
Hi @AllaMaevskaya 
I've realized that there is a potential problem in the CTF decoding due to this difference between the nChanA + nChanC and total number of channels: in the CTF decoding I rebuild the Trigger content from channels, all of them contribute to either nChanA or nChanC count, also to ``amplA/C`` and ``timeA/timeC``. I guess, there one should also apply the threshold? BTW, I see that curently ``DigitizationParameters.mTime_trg_gate`` is set to 189 ps, not 2.5 ns. 
Is this supposed to be a constant or this is as (CCDB?) parameter? I can modify the CTF coder to account for the time of the channel when rebuilding the trigger, but I don't want to use simulation-oriented parameter. Do you have corresponding CCDB object?

**Comment by shahor02** [comment]
@MichaelLettrich @ktf the build/o2 seems to be broken (also in other PRs) could you please check?

**Comment by MichaelLettrich** [comment]
@shahor02 @ktf  on it.

**Comment by MichaelLettrich** [comment]
@ktf : looks like problems with the repo server 
```
aliBuild does not automatically update such packages to avoid work loss.
In most cases this is achieved by doing in the package source directory:

  git pull --rebase

rsync: getaddrinfo: repo-ci.marathon.mesos 873: Name or service not known
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
rsync: getaddrinfo: repo-ci.marathon.mesos 873: Name or service not known
rsync error: error in socket IO (code 10) at clientserver.c(125) [Receiver=3.1.2]
```
on one of the builders. I have some ssh access right issues for costin's machines for an unknown reason.

**Comment by AllaMaevskaya** [comment]
Hello
sorry did not see comment about trigger.
In DigitizationParameters gate in number of channels; I added proper comment
 In CTF coder I will change myself

**Pull request merged**
