### PR TITLE
DPL: improve performance of ContextRegistry

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@matthiasrichter This is 5x faster on my setup and adds a unit test. Could you check on yours?

**Comment by ktf** [comment]
My numbers are:

```
Run on (8 X 2500 MHz CPU s)
2019-03-18 08:47:22
-------------------------------------------------------------------
Benchmark                            Time           CPU Iterations
-------------------------------------------------------------------
BM_ContextRegistrySingleGet          4 ns          4 ns  190432663
BM_ContextRegistryMultiGet          11 ns         11 ns   62888561
```

Merging.

**Comment by matthiasrichter** [comment]
@ktf here are my numbers:
with `unordered_map`
```bash
Run on (8 X 3400 MHz CPU s)
2019-03-18 09:41:27
-------------------------------------------------------------------
Benchmark                            Time           CPU Iterations
-------------------------------------------------------------------
BM_ContextRegistrySingleGet         21 ns         21 ns   33727618
BM_ContextRegistryMultiGet          71 ns         71 ns    9758754
```

```bash
with this PR
Run on (8 X 3400 MHz CPU s)
2019-03-18 09:34:13
-------------------------------------------------------------------
Benchmark                            Time           CPU Iterations
-------------------------------------------------------------------
BM_ContextRegistrySingleGet         38 ns         38 ns   18290805
BM_ContextRegistryMultiGet         105 ns        105 ns    6693631
```

Did you check both?

**Comment by ktf** [comment]
I was taking your numbers for good, actually. I tested on my system and the old version is:

```
→ ../../bin/test_Framework_benchmark_ContextRegistry
Run on (8 X 2500 MHz CPU s)
2019-03-18 10:09:26
-------------------------------------------------------------------
Benchmark                            Time           CPU Iterations
-------------------------------------------------------------------
BM_ContextRegistrySingleGet          5 ns          5 ns  153805252
BM_ContextRegistryMultiGet          13 ns         13 ns   51082213
```

I suspect you are building with `-O0`, then?

**Comment by matthiasrichter** [comment]
no, using `-O2`, changed this before the benchmark, have cross-checked this before the test today

**Pull request merged**
