### PR TITLE
Cosmics matcher + related changes

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
failures unrelated

**Comment by davidrohr** [comment]
@shahor02 : This was failing in the full system test with 
```
Detected critical problem in logfile reco_NOGPU.log
reco_NOGPU.log-[12839:TOFRecoWorkflow]: [00:47:20][INFO] TOF Matching total timing: Cpu: 1.150e+00 Real: 1.139e+00 s in 1 slots
reco_NOGPU.log-[12943:pvertex-track-matching]: 
reco_NOGPU.log:[12943:pvertex-track-matching]:  *** Break *** segmentation violation
reco_NOGPU.log-[INFO] QUIT_REQUESTED
reco_NOGPU.log-[10457:internal-dpl-clock]: [00:47:22][INFO] Received device shutdown request (signal 15).
```
Is this a known issue? I haven't seen it before.

**Comment by shahor02** [comment]
@davidrohr did not notice this but this PR should not affect the vertexing, will check.

**Comment by shahor02** [comment]
@davidrohr I confirm that the failure in fullCI is because of this PR (or its revealing existing error), will fix today after the MW2 stuff

**Pull request merged**
