### PR TITLE
[ITS vertexer] Fix compilation with ITS debug

### PR DESCRIPTION
**Pull request by mconcas**
It should not change anything as the flag is disabled by default.
I additionaly need the {nv, h}cc compiler to know about some dataformat methods also when compiling host code.

### CODE REVIEW

**Review by davidrohr — APPROVED** [review]
Looks OK to me, errors seem unrelated.
Shall I squash and merge, or is more coming?

**Comment by davidrohr** [comment]
@ktf @TimoWilken : There seem to be several ctests failing randomly in the last days, most of them framework test.
Like in the o2 and the dataflow CI here, but I have also seen this in other PRs.
Is someone working on this?

**Comment by ktf** [comment]
yes, me. I think it's #5484. One fix committed. Another one coming.

**Comment by mconcas** [comment]
> Looks OK to me, errors seem unrelated.
> Shall I squash and merge, or is more coming?

Sorry, missed last part. It's mergeable. Thanks.

**Pull request merged**
