### PR TITLE
Fine-tuning of the GEM model and update of the documentation 

### PR DESCRIPTION
**Pull request by a-mathis**
o work done by Viktor Ratza

### CODE REVIEW

**Comment by sawenzel** [comment]
Doing a bit more than just documentation. Could you mention in the commit message what changes in the code, pls?

**Comment by a-mathis** [comment]
@sawenzel Done, the changes in the code beyond the documentation are fine-tunings of the model I suppose

**Comment by sawenzel** [comment]
@ktf: The o2 build fails in yacc related things. Seems like not all of our machines have all the necessary system packages installed.

**Comment by ktf** [comment]
https://github.com/alisw/alidist/pull/1898 should fix the issue, once merged.

**Pull request merged**
