### PR TITLE
DataFormats: add operator< to DataDescription and DataOrigin

### PR DESCRIPTION
**Pull request by ktf**
This is needed in case we want to sort them.

### CODE REVIEW

**Comment by ktf** [comment]
@dberzano do you understand why this PR was not closed when I merged a simi

**Comment by dberzano** [comment]
It seems that your comment is incomplete 😄

**Comment by ktf** [comment]
fixed...

**Comment by dberzano** [comment]
Thanks for fixing it 😄

I don't know exactly how it works. If the commit was the same-same, meaning it had the exact same hash, probably GitHub should have closed it...

**Pull request closed without merging**
