### PR TITLE
Runtime configuration for the ITS CA Tracker

### PR DESCRIPTION
**Pull request by mpuccio**
This PR introduces the mechanism required to run a second iteration of the CA tracker. The default number of iterations is still 1 as the current tests with two iterations do not show any improvement in terms of efficiency (while they show a huge slow down): this is still work in progress.

### CODE REVIEW

**Comment by dberzano** [comment]
@mpuccio can you please rebase? The problem you see was fixed in #1198.

**Comment by sawenzel** [comment]
Is this still [WIP] or ready to be merged?

**Comment by mpuccio** [comment]
At the moment this anyway fixes a bug in the track fitting that was not visible when I was looking only at long tracks. Now the tracker can correctly reconstruct short tracks and the feature to enable cluster sharing has been implemented. If it is fine for @iouribelikov and @shahor02 I would ask to merge.

**Comment by iouribelikov** [comment]
@mpuccio  Ciao Max.  I would say, let's merge it !

**Pull request merged**
