### PR TITLE
[EMCAL-610] Fix segfault in Raw creator

### PR DESCRIPTION
**Pull request by mfasDa**
- Fix buffer overrun in findBunches leading to segfault
- In getting online ID (SRU ID in supermodule had to be
   scaled with the number of supermodules in order to get
   the DDL ID)
- Convert trailer size as size in 32bit words to size in byte in
   carryOverMethod in order to calculate properly the
   payload size

### CODE REVIEW

**Comment by mfasDa** [comment]
@shahor02 Now the raw reader runs until it stops with `libc++abi.dylib: terminating`, is this the normal behaviour. Because it leaves no information why it terminates

**Comment by shahor02** [comment]
No, it is not normal, please open PR with your changes, I will check

**Comment by mfasDa** [comment]
@shahor02 This is the PR with my changes. After applying this, it stops with the message above.

**Review by shahor02 — APPROVED** [review]
failures unrelated

**Comment by shahor02** [comment]
@mfasDa I still get the same error, are you sure you've committed all your fixes?
````
o2-emcal-rawcreator -o raw/EMC
...
[INFO] Orbit:0         BC:0    Stop:0 Page:0     Trg:00000000000000000000000000000000 Par:0     DetFld:0x0000
[INFO] Registered Link SubSpec=0x00000027(006:03:0) feeID=0x0027 with output to raw/EMC/emcal.root
terminate called after throwing an instance of 'o2::emcal::InvalidCellIDException'
  what():  Cell ID 25716 outside limits.
Aborted (core dumped)
````

**Pull request merged**
