### PR TITLE
change --ccdb-url to --ccdb-url-tof, no LOG(info) from workflow definition

### PR DESCRIPTION
**Pull request by shahor02**
The same option cannot be local and global at the same time, even in different devices.

Merging as currently the FST is brocken

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hi Ruben, 

The conflict was between the tof-reco-workflow and the e.g. FIT ones? Or which ones?

Chiara

**Comment by shahor02** [comment]
@chiarazampolli CPV and ZDC have it as a device-level option.

**Comment by chiarazampolli** [comment]
Ok, thanks for clarifying!

Chiara

**Comment by noferini** [comment]
Thanks for checking this

**Pull request merged**
