### PR TITLE
A skeleton of ITS calibration using DPL workflows

### PR DESCRIPTION
**Pull request by iouribelikov**
Dear @chiarazampolli , @shahor02 ,

This work-in-progress PR aims to provide a possibility to run ITS calibration within the common framework.
Several principal features are still missing, but some basic functionality should hopefully be there:
producing meaningful noise maps and registering them in CCDB (see ITS/calibration/testWorkflows/README.md)

Could not you please have a look, and check if (by chance) I am not going in a wrong direction already at this point ?

Thank you very much,
Yura.

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @iouribelikov 

Thanks! Some comments: your calibration workflow starts from clusters file and sends the output (as the file image for the ccdb object) which can be piped to CCDB populator. This is ok for the offline creation of the noise maps. But we going to run it as a part of the sync recoflow, right? In this case, the processing will be done on multiple EPNs. For that we have sample workflow https://github.com/AliceO2Group/AliceO2/tree/dev/Detectors/TOF/calibration/testWorkflow which prepares a calib info on every EPN and sends it (via proxy which is still in preparation) to aggregator server, which puts together data from different TFs, produces the calib info with predefined intervals then sends to the CCDB populator on the same server. I guess similar approach should be taken for this calibration, but in this case the calib. info sent to the calibrator should be prescaled cluster info (say each N-th TF). 
The main problem I see: during the accumulation the noise map can grow up to 615 GB (if all channels are fired at least once, I get 2.4GB for 100 chips):
````
o2::itsmft::NoiseMap mp{100}; 
for (int i=0;i<100;i++) for (int ir=0;ir<o2::itsmft::SegmentationAlpide::NRows;ir++) for (int ic=0;ic<o2::itsmft::SegmentationAlpide::NCols;ic++)  mp.increaseNoiseCount(i,ir,ic);
PrintMem();
VMem: 2910 (delta 2475) ResMem: 2852 (delta 2461)
````
so the only way to run such workflow is under the no-beam conditions...

BTW, why do you reimplement the ClusterReader? There is already one in the O2/Detectors/ITSMFT/common/workflow

Cheers,
 Ruben

**Comment by iouribelikov** [comment]
@shahor02 Thank you, Ruben, for the checks !

> your calibration workflow starts from clusters file and sends the output (as the file image for the ccdb object) which can be piped to CCDB populator. This is ok for the offline creation of the noise maps. 

Yes, this was for "offline purposes".  Great, that this is OK.

> But we going to run it as a part of the sync recoflow, right? 

I always thought we were going to run this calibration between LHC fills.  So "offline".

> In this case, the processing will be done on multiple EPNs. For that we have sample workflow https://github.com/AliceO2Group/AliceO2/tree/dev/Detectors/TOF/calibration/testWorkflow which prepares a calib info on every EPN and sends it (via proxy which is still in preparation) to aggregator server, which puts together data from different TFs, produces the calib info with predefined intervals then sends to the CCDB populator on the same server. 

Yes... I am digesting that complex TOF example...

> I guess similar approach should be taken for this calibration, but in this case the calib. info sent to the calibrator should be prescaled cluster info (say each N-th TF).

Do we need to update the noise maps synchronously, online ?   In principal, a map produced once (between LHC fills) should
be quite stable for days later on.

> The main problem I see: during the accumulation the noise map can grow up to 615 GB (if all channels are fired at least once, I get 2.4GB for 100 chips):
> 
> ```
> o2::itsmft::NoiseMap mp{100}; 
> for (int i=0;i<100;i++) for (int ir=0;ir<o2::itsmft::SegmentationAlpide::NRows;ir++) for (int ic=0;ic<o2::itsmft::SegmentationAlpide::NCols;ic++)  mp.increaseNoiseCount(i,ir,ic);
> PrintMem();
> VMem: 2910 (delta 2475) ResMem: 2852 (delta 2461)
> ```
> 

We would not wait until all pixels are fired.  We would stop after a certain (estimated in advance) number of analysed TFs.

> so the only way to run such workflow is under the no-beam conditions...
 
This is exactly how I see it !


> BTW, why do you reimplement the ClusterReader? There is already one in the O2/Detectors/ITSMFT/common/workflow

Stupid of me. I forgot about that reader.
Yes, I will use the common ITSMFT cluster reader. And remove my own one.

Cheers,
Yura.

**Comment by shahor02** [comment]
Hi @iouribelikov 

Concerning the processing mode: in case the masks to be updated with some regularity (e.g. once per fill), even if the workflow runs between the fills it cannot be an offline process (if by that you mean starting empty run, processing data, writing clusters file and then running the workflow).
For the memory: I think protection on the number of processed ROFs, and probably on the size of every map should be built in the accumulator itself. Alternatively, one can consider sequential processing of group of chips, in this case workflow will be able to run also on real data.

**Comment by iouribelikov** [comment]
Hi @shahor02 
 
> Concerning the processing mode: in case the masks to be updated with some regularity (e.g. once per fill), even if the workflow runs between the fills it cannot be an offline process (if by that you mean starting empty run, processing data, writing clusters file and then running the workflow).

I agree. 
But we do not (necessarily) run this calibration flow from files.  We can run it behind any other flow capable of putting clusters on DPL. Like, for example, the o2-itsmft-stf-decoder-workflow  ( see ITS/calibration/testWorkflows/README.md )

> For the memory: I think protection on the number of processed ROFs, and probably on the size of every map should be built in the accumulator itself. 

Right.
The limit on the number of TFs to be processed (estimated based on a chosen probability threshold, in my vision) should not be difficult to implement. This will be done.


> Alternatively, one can consider sequential processing of group of chips, in this case workflow will be able to run also on real data.

This calibration flow is already "run-able" on real Outer Barrel cosmic data.
A natural "group of chips" of one CRU seems to work just fine.

**Comment by shahor02** [comment]
> But we do not (necessarily) run this calibration flow from files. We can run it behind any other flow capable of putting clusters on DPL. Like, for example, the o2-itsmft-stf-decoder-workflow ( see ITS/calibration/testWorkflows/README.md )

This will require configuring the processing with single EPN taking data from all FLPs, not sure processing can sustain such a data pressure, even w/o beam.

> This calibration flow is already "run-able" on real Outer Barrel cosmic data.
> A natural "group of chips" of one CRU seems to work just fine.
I mean to foresee the mode of defining the full map for all chip in the data taking with all chips, but filling and finalizing groups of chips sequentially, which would allow to run it also during the data taking.

**Comment by iouribelikov** [comment]
@shahor02 
> This will require configuring the processing with single EPN taking data from all FLPs, not sure processing can sustain such a data pressure, even w/o beam.

The data pressure during calibration runs could be adjusted by triggering frequency...

Also, we do not have to connect the whole ITS to just one EPN.  We could consider connecting one FLP to one EPN.  (Something like is planned for the dead pixel scans...)

> I mean to foresee the mode of defining the full map for all chip in the data taking with all chips, but filling and finalizing groups of chips sequentially, which would allow to run it also during the data taking.

This is a valid option.
Another option could be just to collect from parts of the detector in parallel, and then merge the partial noise maps...

**Comment by shahor02** [comment]
@iouribelikov shall I merge this already?

**Comment by iouribelikov** [comment]
> @iouribelikov shall I merge this already?

@shahor02 Yes, I would merge it.  
( The failure of fullCl seems to be unrelated ? )

**Pull request merged**
