### PR TITLE
[WIP] Update Datasampling config format

### PR DESCRIPTION
**Pull request by Barthelemy**
QC-64

As we will have hierarchical keys in the config system in production, we move to such as scheme already.

### CODE REVIEW

**Comment by knopers8** [comment]
Ok, the test passes when built with o2-dataflow defaults, with the others it fails. @awegrzyn is it a matter of missing PPConsul?
```
config file : json:///mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/O2/dev-1/share/tests/test_DataSamplingDPL.json
unknown location(0): fatal error: in "DataSamplingSimpleFlow": std::runtime_error: Back-end 'json' not enabled
```

**Comment by awegrzyn** [comment]
This is fixed in https://github.com/AliceO2Group/Configuration/pull/14 and available in v1.5.0

**Comment by Barthelemy** [comment]
why is configuration not built with json enabled ?

**Comment by Barthelemy** [comment]
@dberzano Could you give us access to the build logs of the configuration package on the build system ? do you know why json is not enabled ?

**Comment by dberzano** [comment]
@Barthelemy logs are not available in case of a successful build (the dev-fairroot problem and the o2checkcode are unrelated). Is it right to build Configuration without JSON? If not, then I suggest its CMake should be updated in order to enforce the dependency.

In case of ROOT, for instance, since you cannot enforce it to build against the desired features (it silently disables them if, for instance, deps are not available) we check for their presence explicitly [in the recipe](https://github.com/FairRootGroup/FairMQ/blob/219487d489efef16b043ed4c1ee02087472432f8/cmake/FairMQLib.cmake#L142-L155), but since you have control over Configuration I suggest you to make the build fail in case JSON is not found (if appropriate of course).

**Comment by Barthelemy** [comment]
@dberzano We have several backends and at this stage none is mandatory. Thus it is ok that the CMake disables the corresponding classes if a dependency is missing. The dependency needed for JSON backend is RAPIDJSON which is listed in the recipe of the configuration. This is why I do not understand why Configuration is not built with json enabled.

What do you think @awegrzyn  ? 

Without the possibility to see the logs or access the build machine, I am not sure how to go ahead.

**Comment by dberzano** [comment]
[Here's the logfile of Configuration](https://github.com/AliceO2Group/AliceO2/files/2027183/Configuration.txt), this was taken from the Configuration C.I. and uses the o2dataflow default.

**Comment by sawenzel** [comment]
Is this PR is labeled [WIP] people probably assumed it wasn't ready yet. Please remove the [WIP].

**Comment by Barthelemy** [comment]
(I merged because the tests related with Data Sampling were finally passing)

**Pull request merged**
