### PR TITLE
DPL: declare DDS collection

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@rbx @AndreyLebedev @AnarManafov could you confirm this is what you would need?

**Comment by AndreyLebedev** [comment]
@ktf Yes, this is what we need.

But please change the order. First you have to declare tasks and then collections. Otherwise, the topology can't be validated.

**Comment by ktf** [comment]
Done.

**Comment by AndreyLebedev** [comment]
Now it's fine. Thank you.

**Comment by dennisklein** [comment]
Since FairMQ `v1.4.0` you may omit the `--plugin-search-path` argument (see FairRootGroup/FairMQ#133):

```diff
--- Framework/Core/src/DDSConfigHelpers.cxx
+++ Framework/Core/src/DDSConfigHelpers.cxx
@@ -49,5 +49,5 @@
       out << arg << " ";
     }
-    out << "--plugin-search-path $FAIRMQ_ROOT/lib --plugin dds";
+    out << "--plugin dds";
     out << "</exe>\n";
     out << "   </decltask>\n";
```

**Comment by ktf** [comment]
Ok. Thanks. I can clean that up, then. How do you do the lookup?

**Comment by dennisklein** [comment]
> Ok. Thanks. I can clean that up, then. How do you do the lookup?

If the `--plugin-search-path,-S` argument is present, it will search this list first. If the plugin is not found or the argument is not present, it will follow the system lookup strategy of the dynamic loader (same as for dynamically linked libraries including `$LD_LIBRARY_PATH`, and `RPATH` hints as well as system paths).

**Comment by ktf** [comment]
@dennisklein Nice. Will drop it in the next iteration.

**Pull request merged**
