### PR TITLE
Initial Event Visualisation commit

### PR DESCRIPTION
**Pull request by jniedzie**

### CODE REVIEW

**Comment by Barthelemy** [comment]
@dberzano @pzhristov 
When do you think this can be reviewed/merged ?

**Comment by dberzano** [comment]
It looks fine for me, I just have a naive question. Why two png files? Isn't one just as good? And, can't we have a vector version instead?

**Comment by jniedzie** [comment]
I think you are right, we should try to use vectorised logo. In any case, the logo is not necessary at this stage, so I remove it for the time being. I will keep in mind you comment when I start working on screenshots generation.

**Comment by dberzano** [comment]
Alright, thank you! I am merging as all the tests are green.

**Pull request merged**
