### PR TITLE
getNbins, typos, warning for too many bins

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@mario-krueger @njacazio Is this ok for you?

**Comment by mario-krueger** [comment]
Looks good to me. (probably .has_value() is not necessary)

**Comment by jgrosseo** [comment]
I liked it more than the cast to bool. Or what do you have in mind?

**Comment by mario-krueger** [comment]
There should be no need to cast it. If you just put if(nBins) it should be the same as if(nBins.has_value())
But it since both are the same, it does not really matter what is used.

**Comment by jgrosseo** [comment]
I see (ah yes, because *nBins is the value in any case). Anyway, like this it is very clear. I leave it.

**Comment by njacazio** [comment]
Looking good for me, thanks!

**Pull request merged**
