### PR TITLE
TPC: Add possibility to read StfBuilder files directly in raw reader

### PR DESCRIPTION
**Pull request by wiechula**

### CODE REVIEW

**Review by davidrohr — APPROVED** [review]
haven't tried it, but this is certainly a good idea

**Comment by wiechula** [comment]
@davidrohr , seems that a lot of tests go to timeout in `macOS`. For `fullCI` there is no log. Any idea, or can it be merged?

**Comment by davidrohr** [comment]
@shahor02 : Is this ok with you?

**Comment by wiechula** [comment]
@shahor02 , are the changes fine for you? I think the failing tests are unrelated.

**Review by shahor02 — APPROVED** [review]
sorry, for delay, looks ok (after very superficially look).

**Pull request merged**
