### PR TITLE
DPL: fix threading issue in ServiceRegistry

### PR DESCRIPTION
**Pull request by ktf**
Protect monitoring thread trying to grab ws driver before it's initialized.

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy looks like you are disabling exceptions in QC. Any reason for doing so?

```
## sw/BUILD/qcg-latest/log
--
                 from /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/QualityControl/v1.10.0-8/include/QualityControl/DatabaseFactory.h:21,
                 from ../tobject2json.cc:2:
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5571-1/include/Framework/ServiceRegistry.h: In member function 'void* o2::framework::ServiceRegistry::get(uint32_t, uint64_t, o2::framework::ServiceKind, const char*) const':
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5571-1/include/Framework/ServiceRegistry.h:199:118: error: exception handling disabled, use -fexceptions to enable
       throw runtime_error_f("Inconsistent registry for thread %d. Expected %d", threadId, mServicesMeta[pos].threadId);
                                                                                                                      ^
make: *** [tobject2json.target.mk:132: Release/obj.target/tobject2json/tobject2json.o] Error 1
make: Leaving directory '/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/76664c3c03f1a3f2a040f607c500340a2f3ecd82/qcg/node_modules/@aliceo2/qc/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
--
```

**Comment by Barthelemy** [comment]
@ktf we don't. That code is in the QCG. @awegrzyn do you rememer why the exceptions are disabled ? 
@ktf why does this sudden happen?  was there a new check ?

**Comment by awegrzyn** [comment]
Yes, in general the NodeJS core is written in C therefore it does not handle C++ exceptions, that's why it was disabled. Although as, at some point, we moved QCG binding to NodeJS C++ add-on so we could enable them back, but some additional development is needed to catch the them and translate them into JS exceptions.
As we plan to drop entirely QCG binding I'd be against investing time in doing this unless it's critical.
@graduta do we have ETA for this?

**Comment by ktf** [comment]
It now happens because the exception is new and done inline and probably gets exposed to the binding. I will also try to hide it.

**Comment by graduta** [comment]
> Yes, in general the NodeJS core is written in C therefore it does not handle C++ exceptions, that's why it was disabled. Although as, at some point, we moved QCG binding to NodeJS C++ add-on so we could enable them back, but some additional development is needed to catch the them and translate them into JS exceptions.
> As we plan to drop entirely QCG binding I'd be against investing time in doing this unless it's critical.
> @graduta do we have ETA for this?

If there are no issues encountered or priorities changed, I will have a working version by the end of the week.

**Pull request merged**
