### PR TITLE
ctp config to ccdb 

### PR DESCRIPTION
**Pull request by lietava**

### CODE REVIEW

**Review by kharlov — APPROVED** [review]

**Comment by lietava** [comment]
Hi @peressounko , @kharlov , I was looking in the log and can not see anything related to CTP. Please, let me know if there is any issue with my code.

**Comment by peressounko** [comment]
dear @lietava, this is clang formatting issue, nothing to do with code itself. OK from PHOS side. Dmitri

**Comment by lietava** [comment]
HI @shahor02, what is  holding this request ?

**Review by shahor02 — APPROVED** [review]

**Comment by lietava** [comment]
Thanks.

**Pull request merged**
