### PR TITLE
TRD digitization: Application of new labels container structure

### PR DESCRIPTION
**Pull request by sawenzel**

### CODE REVIEW

**Comment by sawenzel** [comment]
Still a bit ugly if we want to keep using DPLRootWriterSpec but it works.

**Comment by davidrohr** [comment]
@ktf : There seems to be a random but regular problem with the GPU builder running out of memory during CMake compilation.

**Review by davidrohr — DISMISSED** [review]
Looks quite reasonable to me.

**Comment by bazinski** [comment]
@sawenzel I have not religious affiliations to DPLRootWriter, we can change that. I see the tracklet writer will have to be fixed as well, currently commented out, as the labels are erroneous from the digitizer.

**Review by bazinski — DISMISSED** [review]

**Comment by sawenzel** [comment]
@bazinski : Thanks. For the record, this is just an example transformation that should allow to reach full digit timeframes even with labels enabled. I chose TRD as a first example. I guess we should target to keep the RootWriter since it saves some boilerplate.

**Pull request merged**
