### PR TITLE
Templated secondary N-prong vertex fitter

### PR DESCRIPTION
**Pull request by shahor02**
@ginnocen this is the arbitrary N-prong fitter (if you need N>3, let me know, will change the parameter). The see the Detectors/Base/README for details: the interface is essentially the same, just to get the tracks instead of ``getTrack0()`` , ``getTrack1()`` you should use ``getTrack(0)`` or ``getTrack(1)`` ...

I did not modify you vertexing class to account for the change since this would create a conflict with https://github.com/AliceO2Group/AliceO2/pull/3055 but eventually the current ``DCAFitter`` should be changed by ``DCAFitterN<2>``. Let me know if you want me to do this change, eventually, the old class should be eliminated.

At the moment there is a small instability (present also in the old DCAFitter) sometimes affecting the convergence efficiency (per-mille level for 2 prongs, %-level for 3 prongs), but otherwise, the classes are usable.

### CODE REVIEW

**Comment by ginnocen** [comment]
@shahor02 thanks! No worry I can propagate the changes. At this point i would probably wait until #3055 gets merged and then I will go ahead and update the vertexing code (including a task for the 3 prong case).  I will ping you once it is done so that we can go ahead and eliminate the old code if that works for you. Cheers GM

**Comment by sawenzel** [comment]
@shahor02 : Wondering if  DetectorBase the appropriate place for this?

**Comment by shahor02** [comment]
@sawenzel ok, moved to Detector/Vertexing

**Comment by shahor02** [comment]
Found the reason of Instability (bug), now converges practically always (test on 10^6 K0 and 10^6 Dc):
````
~/alice/sw/BUILD/O2-latest/O2$ stage/tests/o2-test-vertexing-DCAFitterN
[INFO] 2-prong vertex fitter in weighted distance minimization mode
[INFO] Bz: 5 MaxIter: 20 MaxChi2: 100
[INFO] Stopping condition: Max.param change < 0.001 Rel.Chi2 change > 0.9
[INFO] Discard candidates for : Rvtx > 200 DZ between tracks > 4
[INFO] Processed 1000000 2-prong vertices
[INFO] 2-prongs with abs.dist minization: eff= 0.999916 mean.dist to truth: 0.0274969 CPU time: 1.14
[INFO] 2-prongs with wgh.dist minization: eff= 0.999863 mean.dist to truth: 0.0274817 CPU time: 1.32


[INFO] 3-prong vertex fitter in weighted distance minimization mode
[INFO] Bz: 5 MaxIter: 20 MaxChi2: 100
[INFO] Stopping condition: Max.param change < 0.001 Rel.Chi2 change > 0.9
[INFO] Discard candidates for : Rvtx > 200 DZ between tracks > 4
[INFO] Processed 1000000 3-prong vertices
[INFO] 3-prongs with abs.dist minization: eff= 0.998792 mean.dist to truth: 0.011906 CPU time: 1.32
[INFO] 3-prongs with wgh.dist minization: eff= 0.99879 mean.dist to truth: 0.0119061 CPU time: 1.81
````

**Pull request merged**
