### PR TITLE
o2sim: added cmd line parameters to setup interaction diamond position and width

### PR DESCRIPTION
**Pull request by preghenella**
This PR allows the `o2sim` executable to accept parameters that will setup the position and width of the interaction diamond for the simulation.

`o2sim -g pythia8 --origin 0.5 0.5 0.1 --sigmaO 1.e-3 1.e-3 5.5`

On the other hand, this needs a second commit to instruct `boost::program_options` to accept negative numbers. This would require (as far as I know) to drop the possibility to use the short version of commands which cannot be correctly interpreted anymore.

Currently

`o2sim -g pythia8 --origin 0.5 -0.5 0.1 --sigmaO 1.e-3 1.e-3 5.5`

causes an error, and there is apparently no way to prevent it (by using quotes for instance, boost strips them apparently).

With the second commit (that will come)

`o2sim -g pythia8 --origin 0.5 -0.5 0.1 --sigmaO 1.e-3 1.e-3 5.5`

will work fine for the negative number, although the `-g pythia8` is not understood anymore.
The correct command would need to be

`o2sim --generator pythia8 --origin 0.5 -0.5 0.1 --sigmaO 1.e-3 1.e-3 5.5`

@sawenzel , thanks for comments.

Cheers,
Roberto

### CODE REVIEW

**Comment by sawenzel** [comment]
@preghenella : Thanks. 

Alternative one could use #1285 (once available). It would prevent having to create new command line switches for everything:

```
o2sim -g pythia8 --configKeyValue "vertex.pos={0,0,0},vertex.sigma={}"
```

or take them from config file. I would just need to implement support for vector initialization.

**Comment by preghenella** [comment]
Hello @sawenzel ,

that's a good suggestion, but which class will contain the members?
Will it be still `SimConfig`?

Cheers

**Comment by preghenella** [comment]
Uhm, the class and the members must be accessible from `macros/o2sim.C` which is where the instance of `FairPrimaryGenerator` is configured. Would it not work to put a `VertexParam mVertex` member in `SimConfig`, where `VertexParam` is a class containing whatever is related to the vertex?

**Comment by sawenzel** [comment]
Yes it would work ... but it might be better encapsulation to just make a new header and include it in o2sim. You never know where else you will include it. Of course the header could go under SimConfig.

**Comment by sawenzel** [comment]
@preghenella : #1285 was merged. You could now implement the features here using the new mechanism. I suggest to close this PR until reworked.

**Pull request closed without merging**
