### PR TITLE
Rename Configuration to SimConfig

### PR DESCRIPTION
**Pull request by dberzano**
Since the introduction of the Configuration external package, we have two conflicting libConfiguration in our stack. Given the scope of the Configuration module in O2, it has been suggested to rename it to SimConfig.

### CODE REVIEW

**Comment by dberzano** [comment]
@matthiasrichter @sawenzel @ktf @Barthelemy this should fix all PR problems we've encountered. Waiting for the tests.

**Comment by dberzano** [comment]
FairRoot problem's unrelated. Merging.

**Comment by dberzano** [comment]
Hi @matthiasrichter, this is the same old problem of leftovers in the build and installation directory, I have encountered the same. `Configuration` is still there and picked up by your CMake. Please clean the installation directory manually and the problem is gone.

**Comment by matthiasrichter** [comment]
Hi @dberzano, ah so obvious, thanks. Could you check for the pending PRs? I have seen this warning there as well, together with still failing tests. Does the CI start from a bare directory each time or is it incremental?

**Comment by dberzano** [comment]
Hi, we had to restart the PR checks this morning (meaning: after this PR was merged) for an unrelated issue, so if you have seen failures, they might be just unrelated. The build uses incremental builds, so it might happen that artifacts are still there (but not in the source directory, to be clear - just the build one).

The strategy is to checkout the PR, and merge it to current master. Being that as said CI checks were restarted with our PR merged already, it's very likely the problems you see are unrelated and should at some point disappear.

Do you have a specific PR in mind?

**Pull request merged**
