### PR TITLE
fix in tof sim for large TF offset

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
@chiarazampolli 
I implemented a fix. I still need to check it. I will move from draft to reviewed once checked

**Review by sawenzel — APPROVED** [review]

**Comment by sawenzel** [comment]
It works! Thanks.

**Comment by chiarazampolli** [comment]
Thanks @noferini !

**Comment by sawenzel** [comment]
fullCI tested locally. Merging since important fix.

**Comment by chiarazampolli** [comment]
One more comments: with this we should see 3 * N_orbits_per_TF * N_TF_in_job per job. So with a 128 orbits TF and jobs with 25 TF, we should have 6400 RO windows. @sawenzel , did you see something consistent in your local test (it clearly depends on N_orbits_per_TF and N_TF_in_job)?

**Pull request merged**
