### PR TITLE
Added simple check for availability of FairMQ in the cmake config

### PR DESCRIPTION
**Pull request by matthiasrichter**
The FairMQ module of FairRoot might be disabled in the built of FairRoot
due to missing dependencies, e.g ZeroMQ and boost. Those dependencies
also have to be available in the required (minimal) version.

### CODE REVIEW

**Comment by ktf** [comment]
+1

**Comment by matthiasrichter** [comment]
@MohammadAlTurany @pzhristov I see that the PR is not yet merged, could you check whether it is still possible to merge with all the recent commits. I have to rebase otherwise.
Cheers Matthias

**Comment by MohammadAlTurany** [comment]
@matthiasrichter, I had some small corrections to your branch, could you merge my pull request to your branch?

Cheers,
Mohammad

**Comment by matthiasrichter** [comment]
ah, let me check

**Comment by matthiasrichter** [comment]
I have merged the PR to my dev branch, this PR can be merged now, but not fast forward. Then I would need to rebase.

**Comment by MohammadAlTurany** [comment]
Merged

**Pull request closed without merging**
