### PR TITLE
Drop using namespace std from global namespace

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Apart from being forbidden by our Coding Convention, using the `using` statement in the global namespace is indeed a genuine bad practice as it paves the way to all kind of conflicts.

**Comment by ktf** [comment]
@chiarazampolli can you check if this solves your issue?

**Comment by chiarazampolli** [comment]
> @chiarazampolli can you check if this solves your issue?

Unfortunately not. Maybe I should rebuild from scratch, removing the TRD directory?

Chiara

**Comment by chiarazampolli** [comment]
> > @chiarazampolli can you check if this solves your issue?
> 
> Unfortunately not. Maybe I should rebuild from scratch, removing the TRD directory?
> 
> Chiara

No, also after removing TRD from BUILD, it does not work.

**Comment by chiarazampolli** [comment]
Ciao,

I see that TRD uses:

using namespace std;

also in Detectors/TRD/simulation/src/TrapConfig.cxx and other source files, in the global namespace, could this be the issue in my case?

Chiara

**Comment by sawenzel** [comment]
Is there a ticket that describes your problem? That would be helpful.

**Comment by chiarazampolli** [comment]
No ticket, it is in a private branch where I use boost histograms, and after updating alidist today, it does not compile anymore. The branch is:
https://github.com/chiarazampolli/AliceO2/tree/TOFchannelCalib
the error points at some conflicts with the definition of "rank" that is there in boost histogram library (for the axis) and in std. 
I can create a JIRA, for now I contacted @ktf  and @shahor02 because maybe it is just my problem.

**Comment by ktf** [comment]
This is in any case good to go. Can you open a PR with your code?

**Comment by shahor02** [comment]
Hi,
For the record: the conflict of the boost comes from the CLING. 
The https://github.com/root-project/root/blob/9a5dca211a7fba3c2ccca322956657ea01ec3a8f/core/dictgen/src/rootcling_impl.cxx#L2861 puts in all `G_...cxx` files ``using namespace std;``

For @chiarazampolli branch this leads in  generated `G__O2TOFCalibration.cxx` to
````
namespace std {} using namespace std;

// Header files passed as explicit arguments
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/CalibTOFapi.h"
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/CalibTOF.h"
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/LHCClockCalibrator.h"
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/TOFChannelCalibrator.h"
/// ^^^^ RS This one includes boost headers
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/CollectCalibInfoTOF.h"
````

If I just manually move the `std` in `G__O2TOFCalibration.cxx` after these lines, i.e.
````
// Header files passed as explicit arguments
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/CalibTOFapi.h"
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/CalibTOF.h"
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/LHCClockCalibrator.h"
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/TOFChannelCalibrator.h"
#include "/home/shahoian/alice/sw/SOURCES/O2/v1.2.0/0/Detectors/TOF/calibration/include/TOFCalibration/CollectCalibInfoTOF.h"
namespace std {} using namespace std;
````
everything compiles.

**Comment by ktf** [comment]
@chiarazampolli how about using 

https://www.boost.org/doc/libs/develop/boost/histogram/fwd.hpp

rather than whatever you expose in the headers and keep the actual conflicting header in the .cxx? In any case exposing boost to ROOT is a bad idea.

**Comment by chiarazampolli** [comment]
Ciao,

Thanks Ruben for finding the origin of the problem. I can check the fwd.hpp tomorrow, I don’t know it. I have as data member an array of boost histograms, this i why i have the include. 

Chiara

**Comment by chiarazampolli** [comment]
Ciao @ktf ,
Adding 

`#include <boost/histogram/fwd.hpp>` 

in the header file, and moving 

`#include <boost/histogram.hpp>`

to the source does not work. As I said, I have a data member that is an array of boost histograms, and it is not recognized, error:

`/usr/include/c++/7/array:110:56: error: implicit instantiation of undefined template 'boost::histogram::histogram<std::tuple<boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>, boost::histogram::axis::integer<int, boost::use_default, boost::use_default> >, boost::histogram::unlimited_storage<std::allocator<char> > >'
      typename _AT_Type::_Type                         _M_elems;
                                                       ^
input_line_12:434:29: note: in instantiation of template class 'std::array<boost::histogram::histogram<std::tuple<boost::histogram::axis::regular<double, boost::use_default, boost::use_default, boost::use_default>, boost::histogram::axis::integer<int, boost::use_default, boost::use_default> >, boost::histogram::unlimited_storage<std::allocator<char> > >, 18>' requested here
  std::array<boostHisto,18> mHisto;`

This problem does not belong to this PR. My code is in my branch "chiarazampolli/TOFchannelCalib". If you want, we can discuss in JIRA, or via mail. Let me know. There must be a way. 

Chiara

**Comment by shahor02** [comment]
Hi @chiarazampolli the only robust ways are either
1) to not expose to rootcling any headers including boost headers. I've tried yesterday to move your ` TOFChannelData` to a separate header and take it out from the dictionary generation. Unfortunately, this was not enough: one would need to give up the dictionary generation for plenty of related classes. Also, this would not solve the problem of using boost::histo operations in the macros, for which the dictionary is always generated.
2) to prevent rootcling putting ``namespace std {} using namespace std;`` ahead of 3-d party include files when generating a dictionary. I am installing root as dev. package to see if I can achieve this.

I am starting to regret for suggesting you to use boost::histo instead of Root histos....

**Comment by chiarazampolli** [comment]
Hi @shahor02 , 

Don't worry, it is a useful exercise, and it won't be difficult, in case, to change. But I admit that since the beginning I wanted to benchmark my use case. The filling should indeed be very fast with boost, but I don't know about the reduce function. Anyway, I did not do it yet :-)
My thought was also maybe to contact the root team. Let me know, in case. 

I will create a JIRA to continue the discussion.

Chiara

**Comment by chiarazampolli** [comment]
Let's continue in https://alice.its.cern.ch/jira/browse/O2-1306

**Pull request merged**
