### PR TITLE
Avoid setting the memory lock when we have no ulimit

### PR DESCRIPTION
**Pull request by chiarazampolli**
@davidrohr , this fixes running the async reco. 
@martenole , if you agree, it would be very useful to have it merged. 

@catalinristea, FYI.

### CODE REVIEW

**Comment by davidrohr** [comment]
Fine with me. But we should still disable setting this no_ulimit flag on the epns.

**Comment by chiarazampolli** [comment]
Hello @davidrohr , 
I don't know if this is set on the EPNs, but without this fix, the async reco is broken, both locally and on the grid, so could it be merged if it seems ok?
Thanks!

**Comment by chiarazampolli** [comment]
Hello @martenole , 
Can you merge this? Async reco is broken without it.
Chiara

**Comment by martenole** [comment]
Ok, I will merge it. But I think what David means is that for the async jobs which are running on the EPNs one should not set `SETENV_NO_ULIMIT=1`. I see it is not set anywhere for synchronous processing, so I don't see an issue there. But in the async scripts for example in https://github.com/AliceO2Group/O2DPG/blob/4b76fbbe8e9a6f4acde10b0734436d61d0e880f8/DATA/production/configurations/asyncReco/setenv_extra.sh#L6 that export should be protected by something so that it is not deployed for productions on the EPNs. I don't know how this can be checked though

**Comment by chiarazampolli** [comment]
> Ok, I will merge it. But I think what David means is that for the async jobs which are running on the EPNs one should not set `SETENV_NO_ULIMIT=1`. I see it is not set anywhere for synchronous processing, so I don't see an issue there. But in the async scripts for example in https://github.com/AliceO2Group/O2DPG/blob/4b76fbbe8e9a6f4acde10b0734436d61d0e880f8/DATA/production/configurations/asyncReco/setenv_extra.sh#L6 that export should be protected by something so that it is not deployed for productions on the EPNs. I don't know how this can be checked though

Ah ok, now I understand. I can protect it, so that it is disabled when we use GPUs. 
Do you (or anyone) remember why we had it there? Is it needed at all?

**Comment by martenole** [comment]
I don't know, sorry

**Pull request merged**
