### PR TITLE
[EMCAL-534, EMCAL-629] Support for different raw header formats, support for in-memory raw decoding

### PR DESCRIPTION
**Pull request by mfasDa**
Raw reader templated with template argument raw header
type in order to support different raw headers
- o2::emcal::RAWDataHeader as clone of the old CDHv3
  used in the current SRU firmware
- o2::header::RAWDataHeaderV4 produced by the raw
  writer and the raw data from run2 converted to
  run3 DMA pages
In addition Align o2::emcal::RAWDataHeader with
o2::header::RAWDataHeaderV4 to provide the same
names for the bit fields required in the raw decoding.
For the decoding of the raw headers use operator>>
in order to profit from templates. As the definition
of this operator is missing in the commom classes
provide this in the EMCAL library for RAWDataHeaderV4
and RAWDataHeaderV5 - like this changing the raw
header version will become transparent.

### CODE REVIEW

**Comment by mfasDa** [comment]
The failing test is not due to this commit!

**Comment by mfasDa** [comment]
@shahor02 Would it be possible to review this PR? This is needed for supporting simulated raw files and raw files converted from run2 format - which will use RDHv4, while the EMCAL Lab setup still send a mixed CDHv3, and for the time being until the SRU firmware is upgraded we must support both header formats.

**Comment by shahor02** [comment]
Hi, till Friday I am in almost permanent travel (Sandro is hiking in Tasmania), will review asap

**Comment by mfasDa** [comment]
I adapted the pull request in order to support in-memory raw handling. This is of relevance for the raw data obtained from the Readout application in the DPL workflows. This has two major changes:
- Add RawReaderMemory class for in-memory raw decoding
- AltroDecoder becomes templated itself
Template specifications of the EMCAL-specific raw header, which is in the same library, were not a problem, but specifications for the RawDataHeaderV4 are still pending.

**Comment by mfasDa** [comment]
Pull request should now be feature-complete. Features implemented:

- In-memory raw decoding (used in workflows)
- Support for multiple raw data header
- Correct handling of the termination characters
- Tools for RDH streaming 
- Support for payload distributed over multiple DMA pages

**Pull request merged**
