### PR TITLE
[TPC] Add RDH mapping for feeId

### PR DESCRIPTION
**Pull request by wiechula**
@davidrohr , is this fine for you?

### CODE REVIEW

**Comment by davidrohr** [comment]
@wiechula : below a patch with minor simplifications / generalizations:
```
diff --git a/Detectors/TPC/base/include/TPCBase/RDHUtils.h b/Detectors/TPC/base/include/TPCBase/RDHUtils.h
index 72122bb9428..74de96feee1 100644
--- a/Detectors/TPC/base/include/TPCBase/RDHUtils.h
+++ b/Detectors/TPC/base/include/TPCBase/RDHUtils.h
@@ -26,8 +26,9 @@ using FEEIDType = uint16_t;
 static constexpr FEEIDType UserLogicLinkID = 15;
 
 /// compose feeid from cru, endpoint and link
-static constexpr FEEIDType getFEEID(const FEEIDType cru, const FEEIDType endpoint, const FEEIDType link) { return FEEIDType((cru << 7) | (endpoint << 6) | link); }
-static constexpr FEEIDType getFEEID(const int cru, const int endpoint, const int link) { return getFEEID(FEEIDType(cru), FEEIDType(endpoint), FEEIDType(link)); }
+static constexpr FEEIDType getFEEID(const FEEIDType cru, const FEEIDType endpoint, const FEEIDType link) { return FEEIDType((cru << 7) | ((endpoint & 1) << 6) | (link & 0x3F)); }
+template <typename T>
+static constexpr FEEIDType getFEEID(const T cru, const T endpoint, const T link) { return getFEEID(FEEIDType(cru), FEEIDType(endpoint), FEEIDType(link)); }
 
 /// extract cru number from feeid
 static constexpr FEEIDType getCRU(const FEEIDType feeID) { return (feeID >> 7); }
@@ -77,14 +78,8 @@ static constexpr bool isFromUserLogic(const RDH& rdh)
   return isFromUserLogic(RDHUtils::getFEEID(rdh));
 }
 
-template <typename RDH>
-static constexpr void setFEEID(RDH& rdh, const FEEIDType cru, const FEEIDType endpoint, const FEEIDType link)
-{
-  RDHUtils::setFEEID(rdh, getFEEID(cru, endpoint, link));
-}
-
-template <typename RDH>
-static constexpr void setFEEID(RDH& rdh, const int cru, const int endpoint, const int link)
+template <typename RDH, typename T>
+static constexpr void setFEEID(RDH& rdh, const T cru, const T endpoint, const T link)
 {
   RDHUtils::setFEEID(rdh, getFEEID(cru, endpoint, link));
 }
```
With these changes, it should work for me.

**Comment by wiechula** [comment]
@davidrohr , thanks for checking and the suggestions. Looks logic ...
It is in now.

**Comment by shahor02** [comment]
@wiechula how these cru, link and endpoint relate to those in the RDH and who will set them and RDH in the real data taking? As far as I understand, the ``RDH.cruID`` and  ``RDH.linkID`` are run-time defined numbers, w/o any relation to particular region of the detector (in opposite to feeID).

**Comment by davidrohr** [comment]
@shahor02 : The TPC is using a geometrical mapping of a CRU number to sector / region in https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/TPC/base/include/TPCBase/Mapper.h
This PR maps these numbers from the mapper to the FEE id.
I agree that this is quite confusing, since this is not the cru ID in the RDH.
Perhaps we should rename this globally to avoid confusion.

**Comment by wiechula** [comment]
@shahor02 , I agree this is quite a mess and I don't understand the decision made about the CRUid. the feeid will be set by Torsten in the user logic.
I would agree to merge now and rename variables later consistently. No good idea at the moment who to distinguish the cru 'production id' from the 'geoemtrical id'.

**Comment by davidrohr** [comment]
Needed for dependent PR, names can be cleaned up later, merging

**Pull request merged**
