### PR TITLE
DPL GUI: more clang-tidy fixes

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr I've done a few more fixes but apparently my clang-tidy setup bails out after a while.

**Comment by davidrohr** [comment]
Ok, thx, i'll merge this locally and retest later.

**Comment by davidrohr** [comment]
@ktf : Attached the list of errors I am still seeing in the Framework.
[errors.txt](https://github.com/AliceO2Group/AliceO2/files/3194520/errors.txt)

**Comment by ktf** [comment]
Unfortunately it's not so straightforward because cmath and math.h are not actually 100% the same. I will need a bit more time...

**Comment by ktf** [comment]
I decided to start from the nullptrs, which should be easier to fix...

**Comment by davidrohr** [comment]
@ktf : Indeed much less now, but still plenty left.
Perhaps it is really worth thinking about a different solution, if there are so many issues. Will be tedious to repeat this after an update.
In case your clang-tidy still bails out, attached the list of errors I get now.
[errors.txt](https://github.com/AliceO2Group/AliceO2/files/3195283/errors.txt)

**Comment by ktf** [comment]
In principles the fixes are doable automatically either via clang tidy, when it works or via sed. Anyways, yes, I will probably bite the bullet and factor it out.

**Pull request merged**
