### PR TITLE
[FV0][FT0][O2-1238] Fixes, updates, FV0 embedding

### PR DESCRIPTION
**Pull request by mslupeck**
[FV0][FT0] updates and fixes
- Implemented embedding in FV0
- [O2-1238] Moved FT0 from z=333 to z=335 cm to avoid overlaps with FV0
- Fixed path for FT0 simcuts
- Added FV0 simcuts.dat
- Expanded readFV0Digits.C macro
- Expanded readFV0Hits.C macro
- Added FV0 configurable params
- Tuning of FV0 digitization parameters

_No pileup handling for FV0 yet_

### CODE REVIEW

**Comment by mslupeck** [comment]
Hi @AllaMaevskaya,
One thing to note for you here is that I have moved FT0A by 2 cm to avoid overlaps with FV0. I see in your active PR that you also modify the o2::ft0::Detector.cpp, so there may be conflicts at some point, depending which of our PRs is merged first.

Just to explain a little: I didn't want to move FV0 at this point, because I don't know what is in front of it. On the other hand, I know there is nothing closeby behind FT0, so it was easier that way.
If I moved FV0 instead, I would have to rerun several times the time-consuming procedure to check geometry overlaps in the entire O2 geometry. Anyway, I guess we will fine-tune the exact positions of the detectors in simulations once they are installed and their positions are measured in the cavern.

**Comment by AllaMaevskaya** [comment]
Hello

OK, but  if FT0 will be shifted  I need to recalculate compensating times for Digitizer

**Comment by mslupeck** [comment]
@AllaMaevskaya, OK so is it fine? I thought these 67 ps are not that significant from the point of view of electronics, considering that we have the gate +/- 2.5 ns. But I can also revert this change and postpone until later commit when we can investigate further how to move FV0 instead.

**Comment by jotwinow** [comment]
Dear Maciej, Alla, @AllaMaevskaya @mslupeck 

But how these detectors will be relatively located at P2? The distance between them will be fixed be the construction, and distance from the IP will be fixed by the FV0 detector. Am I right?

**Comment by mslupeck** [comment]
> Dear Maciej, Alla, @AllaMaevskaya @mslupeck
> 
> But how these detectors will be relatively located at P2? The distance between them will be fixed be the construction, and distance from the IP will be fixed by the FV0 detector. Am I right?

Yes. But currently both detectors are placed in the more-or-less right z-position (+/- few cm). Also FT0-A does not have the metal structure implemented, so it is a bit difficult to fix anything.

**Comment by AllaMaevskaya** [comment]
OK, I pushed shifted FT0

**Comment by jotwinow** [comment]
OK. Thanks Alla.

**Comment by sawenzel** [comment]
@jotwinow : I'll merge once approved.

**Comment by AllaMaevskaya** [comment]
I approve but I don't have button to press

**Pull request merged**
