### PR TITLE
Add GPLv3 License

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by matthiasrichter** [comment]
Using this license file would also fix what we put in the source and/or header files, correct? Its the statement starting line 633
https://github.com/AliceO2Group/AliceO2/pull/283/files#diff-9879d6db96fd29134fc802214163b95aR633

**Comment by ktf** [comment]
Indeed, having at least the copyright statement is indeed a requirement of GPL.

I also think we should use CERN as Copyright holder (unless the ALICE Collaboration is actually a juridic entity), not the person actually writing the software, to avoid:

- That some physical person gets sued regardless of the *WITHOUT ANY WARRANTY* statement.
- That some person can withdraw the source code or deny it's usage.

**Comment by Barthelemy** [comment]
https://alice.its.cern.ch/jira/browse/OCCF-1 contains what was discussed in CWG2 and in the plenary. I presume that ALICE is more appropriate than CERN but I am not sure.

**Comment by ktf** [comment]
Is ALICE Collaboration a legal entity? If not, it cannot be assigned
copyright.

**Comment by pzhristov** [comment]
Here is a link to what was discussed @ CWG2 concerning the licensing:

https://indico.cern.ch/event/347914/contributions/815069/attachments/1125754/1607061/20150714_CWG2PresentationLicenseO2plenary.pdf#search=software%20license

**Comment by pzhristov** [comment]
See also p.12 in https://cds.cern.ch/record/1482206/files/Final%20Report%20from%20the%20Task%20Force%20on%20%20Open%20Source%20Software%20Licence%20.pdf?version=1

where the suggested form is


“© Copyright [year] Copyright Holders of [name of the collaboration or joint project]. See [https://link]
for details of the Copyright Holders”
for software owned by CERN and external partners in large collaborations

**Comment by sawenzel** [comment]
What is the status of this PR? Is it ready to be merged?

**Comment by ktf** [comment]
The license is the correct one, in order to be fully compliant we would need to add the correct header to all our files.

**Comment by dberzano** [comment]
So, the headers were added as discussed in [OCCF-1](https://alice.its.cern.ch/jira/browse/OCCF-1), the relevant PR is #405. Can we merge this?

**Comment by matthiasrichter** [comment]
still TODO
- [ ] remove conflicting old license notices
- [ ] add the full license information to a public web page and cite the correct link in the license notice
- [ ] formal agreement of developers by approving PR

**Comment by matthiasrichter** [comment]
@Barthelemy follow up to my comment in #405 , I have found the page https://alice-o2.web.cern.ch/node/142, but it needs to be filled.

**Comment by sawenzel** [comment]
@dberzano , @ktf: should this PR be closed now?

**Comment by ktf** [comment]
The file is actually still needed. Since I disagree with the approach taken as well, I will let @dberzano take care of this.

**Pull request closed without merging**
