### PR TITLE
Updated geometry for OB Modules and Staves

### PR DESCRIPTION
**Pull request by mario6829**
The description of OB modules and staves have been updated to the latest specs. In particular:
- the position of modules and related dimensions were revised
- the glue volumes were updated and correctly placed
- the FPC is now more realistic
- the Power Bus is more realistic and the Bias Bus was added

### CODE REVIEW

**Comment by mario6829** [comment]
Hi @iouribelikov @shahor02 I just made a PR for the first bunch of updates in the OB geometry as I reported in the last meeting. I solved all overlaps/extrusions problems, fixed other dimensions and implemented the Bias Bus. Please let me know if there are problems. Otherwise for me it can be merged. Many thanks. Regards. Mario

**Comment by shahor02** [comment]
Hi @mario6829 

The code is fine for me (once the checks are passed) but you will need to run `git clang-format HEAD~2` to pass the Travis CI check.

Cheers,
 Ruben

**Comment by iouribelikov** [comment]
@mario6829  Hi Mario,

My basic tests seem to pass fine. 
Once you are done with the clang formatting, let's merge this PR.

Thank you very much !
Yura.

**Comment by mario6829** [comment]
@shahor02  @iouribelikov done! Thanks again. Cheers
Mario

**Comment by iouribelikov** [comment]
@mario6829 Thank you, Mario.  For me, it works also on a Mac.
@sawenzel Sandro, could we merge this PR eventually ?

**Pull request merged**
