### PR TITLE
DPL: allow unordered_maps in CCDB to be automatically handled

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@matthias-kleiner

**Comment by ktf** [comment]
@matthias-kleiner with this your branch compiles.

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner with this your branch compiles.

thanks for the fix, I just tested it and it seems to work :)

**Comment by ktf** [comment]
Cool, I fixed the typo in the test and then I will merge this once the tests are green.

**Pull request merged**
