### PR TITLE
Little fix in the Alpide digitization

### PR DESCRIPTION
**Pull request by iouribelikov**
@shahor02 Hi Ruben. Please, have a look.  And run the CheckClusters.C

### CODE REVIEW

**Comment by sawenzel** [comment]
@peressounko : Since today I see failure of 
`Detectors/PHOS/testsimulation/plot_dig_phos.C_compiled` in the checkcode CI. Would you be able to take a look and fix it?

**Comment by shahor02** [comment]
Hi @ktf, @MichaelLettrich 

Do you understand why o2checkcode/o2 fails with the messages below? I looks like the picks up files from other PR (there should be no name o2-analysistutorial-vertexingHF in this PR, the https://github.com/AliceO2Group/AliceO2/pull/2780/files is  not yet merged)
````
393/396 Test #312: ensure-executable-naming-convention ............................................***Failed    0.02 sec
WARNING: in o2-analysistutorial-associated-derived the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-analysistutorial-collision-tracks-iteration the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-analysistutorial-dynamic-columns the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-analysistutorial-filters the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-analysistutorial-full-track-iteration the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-analysistutorial-histograms the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-analysistutorial-new-collections the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-analysistutorial-track-collection-iteration the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-analysistutorial-track-iteration the subsystem analysistutorial is not in the list of know subsystem
ERROR: executable name o2-analysistutorial-vertexingHF does not follow naming convention : should only contains lowercase letters, numbers, or dashes
WARNING: in o2-analysistutorial-vertexingHF the subsystem analysistutorial is not in the list of know subsystem
WARNING: in o2-dpl-esd-2-arrow-converter the subsystem dpl is not in the list of know subsystem
WARNING: in o2-dpl-raw-parser the subsystem dpl is not in the list of know subsystem
WARNING: in o2-dpl-raw-proxy the subsystem dpl is not in the list of know subsystem
WARNING: in o2-emcal-rawreader-file the subsystem emcal is not in the list of know subsystem
WARNING: in o2-emcal-reco-workflow the subsystem emcal is not in the list of know subsystem
WARNING: in o2-fdd-reco-workflow the subsystem fdd is not in the list of know subsystem
WARNING: in o2-mft-reco-workflow the subsystem mft is not in the list of know subsystem
WARNING: in o2-phos-reco-workflow the subsystem phos is not in the list of know subsystem
WARNING: in o2-tof-reco-workflow the subsystem tof is not in the list of know subsystem
````

**Comment by ktf** [comment]
Yes. The problem is that one of the PRs has an executable which is named in the wrong way. Since we do not clean the build area between builds, the bad executable stays around also for others PRs, hence the problem. We need to have this fixed at CMake level (albeit it might not actually be even possible). For now I will simply delete it by hand.

**Comment by shahor02** [comment]
Merging since the failures are not related to this PR

**Pull request merged**
