### PR TITLE
ITS-GPU: Update the Hybrid interface

### PR DESCRIPTION
**Pull request by mconcas**
to the latest devs

### CODE REVIEW

**Comment by mconcas** [comment]
> Error while checking build/O2/fullCI for [0e6e827](https://github.com/AliceO2Group/AliceO2/commit/0e6e827d2a0f8a03c4f3f474cd6fdcca13e366c4) at 2024-08-14 19:46:
> 
> ```
> ## sw/BUILD/O2-latest/log
> c++: error: unrecognized command-line option '--rtlib=compiler-rt'
> c++: error: unrecognized command-line option '--rtlib=compiler-rt'
> 
> 
> ## sw/BUILD/o2checkcode-latest/log
> --
> ========== List of errors found ==========
> ++ GRERR=0
> ++ grep -v clang-diagnostic-error error-log.txt
> ++ grep ' error:'
> /sw/SOURCES/O2/13383-slc8_x86-64/0/GPU/GPUTracking/Global/GPUChainITS.cxx:40:14: error: use '= default' to define a trivial destructor [modernize-use-equals-default]
> ++ [[ 0 == 0 ]]
> ++ exit 1
> --
> ```
> 
> Full log [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/13383/0e6e827d2a0f8a03c4f3f474cd6fdcca13e366c4/build_O2_fullCI/pretty.html).

@ktf this is the issue I was referring to: https://github.com/llvm/llvm-project/issues/92250

The feeling is that either after the thinning of the `compile_commands.json` or in general also with the full compile_commands.json, `clang-tidy` does not find the std headers somehow and then fails on something like:
```
Error while processing /sw/SOURCES/O2/13383-slc8_x86-64/0/GPU/GPUTracking/Global/GPUChainITS.cxx.
/sw/SOURCES/O2/13383-slc8_x86-64/0/GPU/GPUTracking/Base/GPUReconstruction.h:18:10: error: 'cstddef' file not found [clang-diagnostic-error]
   18 | #include <cstddef>
      |          ^~~~~~~~~
```
then degenerates in:
```
/sw/SOURCES/O2/13383-slc8_x86-64/0/GPU/GPUTracking/Global/GPUChainITS.cxx:40:14: warning: use '= default' to define a trivial destructor [modernize-use-equals-default]
   40 | GPUChainITS::~GPUChainITS()
```

could it be related to the bumping of clang, @davidrohr ?

**Comment by davidrohr** [comment]
No idea, but I also saw bogus clang tidy warnings recently.
I think it appeared after bumping llvm. Though, I tried the codechecker with the bumped LLVM once in the build container before merging, and there I didn't get the error.

**Comment by mconcas** [comment]
> No idea, but I also saw bogus clang tidy warnings recently. I think it appeared after bumping llvm. Though, I tried the codechecker with the bumped LLVM once in the build container before merging, and there I didn't get the error.

It happens to changed files and their dependencies. Maybe you were lucky and did not change an affected file. 

Like, in this case: the thinning command is:

```
ThinCompilationsDatabase.py -exclude-files '(?:.*G\_\_.*\.cxx|.*\.pb.cc|.*\_amalgamated\..*)' -use-files Detectors/ITSMFT/ITS/tracking/GPU/ITStrackingGPU/VertexerTraitsGPU.h:Detectors/ITSMFT/ITS/tracking/include/ITStracking/Vertexer.h:Detectors/ITSMFT/ITS/tracking/include/ITStracking/VertexerTraits.h:Detectors/ITSMFT/ITS/tracking/src/Vertexer.cxx
```
then the clang-tidy is run only on a subset of the commands. Maybe in your case everything was just excluded.

**Comment by davidrohr** [comment]
No, I compiled O2 from scratch to make sure it ran over all files, and I checked that it did.

**Comment by davidrohr** [comment]
Perhaps this is also related to the fixing of GCC header path in clang, which breaks the relocation @ktf ?

**Comment by davidrohr** [comment]
Perhaps we need `${GCC_TOOLCHAIN_REVISION:+-DGCC_TOOLCHAIN_ROOT=$GCC_TOOLCHAIN_ROOT}` for the codechecker as well, as in https://github.com/alisw/alidist/pull/5579/files

**Comment by chiarazampolli** [comment]
Label async-2023-pbpb-apass4 added to allow commit 7a6665b (needed for the same label) to apply.

**Comment by chiarazampolli** [comment]
Label removed, PR is in async-v1-01-16.

**Pull request merged**
