### PR TITLE
DPL: add dummy library for FrameworkFoundation

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
Indeed strange that it didn't trigger the error before.
In general, I had to do the same for AliGPU Common library, which was also header only.

**Comment by ktf** [comment]
Actually it's even more strange, since the error seems to come from compiling QualityControl itself...

**Comment by davidrohr** [comment]
Perhaps there was a change in QualityControl, that introduced the problem, since o2 C.I. builds O2Suite? But also QualityControl C.I. should check O2Suite I assume?

**Comment by davidrohr** [comment]
@ktf: I have cherry-picked this commit and tried to build O2Suite locally. It still fails in QualityControl.

**Comment by davidrohr** [comment]
@ktf : The problem is that the headers in Framework/Foundation/include/Framework are not installed.
The "set(HEADERS ..." is missing in the CMakeLists.txt.

However, even adding the HEADERS variable seems not to work. I think this is because the include dir inside Foundation is Framework, but the modulename is FrameworkFoundation, but I am not 100% sure. #2031 installs the headers manually in the correct place, which fixes the O2Suite build for me.

This is a workaround for now, should be cleaned up eventually.

**Comment by ktf** [comment]
Superseded by #2031.

**Pull request closed without merging**
