### PR TITLE
Implementation of ITSMFT Cage Side Panels into O2 geometry

### PR DESCRIPTION
**Pull request by mario6829**
The Side Panels of the ITSMFT Cage were implemented in the O2 geometry. They were the last missing main elements of the Cage, which is now complete in its most relevant parts. A full description can be found here
https://indico.cern.ch/event/1206725/contributions/5075224/attachments/2521836/4336441/sitta_WP2_221004.pdf

### CODE REVIEW

**Comment by mario6829** [comment]
Hi @iouribelikov @mconcas this is the PR for the Side Panels of the Cage that I presented at last WP2 meeting. Please let me know in case of problems. Cheers

**Comment by iouribelikov** [comment]
@mario6829 Thank you a lot, Mario.  It looks very nice.  
But I seem to get a few rather large overlaps with the MFT volumes.

For example:

= Overlap ov00000: barrel/CageSidePanel_2/CageSidePanelRail1st_3 overlapping barrel/MFT_0/BarrelVolume_1/BoxJoint1_1 ovlp=0.6

 = Overlap ov00007: barrel/CageSidePanel_2/CageSidePanelRail1st_3 overlapping barrel/MFT_0/BarrelVolume_1/siderail0_1 ovlp=0.599999

 = Overlap ov00011: barrel/CageSidePanel_1/CageSidePanelRail1st_1 overlapping barrel/MFT_0/BarrelVolume_1/siderail1_1 ovlp=0.25


Are these "real" overlaps ?

**Comment by mario6829** [comment]
my fault @iouribelikov I forgot to crosscheck with MFT, sorry for that. Thanks for checking! The overlaps are real and due to the fact that I oversimplified the shape and position of the cage rails. I'll try to be a bit more realistic.

**Comment by mario6829** [comment]
Hi @iouribelikov with the help of the original 3D CAD files, I implemented more realistic side rails: this should fix the overlaps with the MFT volumes. I'll give an update presentation next meeting. Please let me know if this is fine. Many thanks for checking. Kind regards

**Comment by iouribelikov** [comment]
@mario6829  It's almost perfect now !

But on my machine, I still get these two overlaps:

Info in <TGeoNodeMatrix::CheckOverlaps>: Number of illegal overlaps/extrusions : 2

=== Overlaps for ccdb_object ===
 = Overlap ov00000: barrel/ITSV_2/ITSUWrapVol2_1 overlapping barrel/MFT_0/PatchPanelVolume_1/patchpanel_Volume_1 ovlp=0.1
 = Overlap ov00001: barrel/ITSV_2/ITSUWrapVol2_1 overlapping barrel/MFT_0/PatchPanelVolume_1/patchpanel_Volume_1 ovlp=0.1

They look like something trivial, and maybe not even related to the Cage.  
But could not you check them please ?

Thanks a lot and cheers,
Yura.

**Comment by mario6829** [comment]
@iouribelikov  yup, I did notice them too, but they are uncorrelated with the latest improvements in the Cage: in fact they are present also in the current version of the geometry. If you agree, I would propose a different PR to solve these overlaps, I can prepare and submit it now.
Many thanks again. Cheers

**Comment by iouribelikov** [comment]
@mario6829  Thank you very much for this confirmation.  OK, let's address these trivial overlaps in a separate PR.

**Review by iouribelikov — APPROVED** [review]

**Comment by mconcas** [comment]
@shahor02 can we please merge this?

**Review by mconcas — APPROVED** [review]

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
