### PR TITLE
[O2-845] Ensure we use only namespaced target names

### PR DESCRIPTION
**Pull request by aphecetche**
this is the follow-up PR to #2360

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi @aphecetche : thanks for the work, I am having a look into the GPU thing and will add the required aliases.

**Comment by aphecetche** [comment]
@davidrohr thanks. I'll also have to have a look at the linux build anyway as there seem to be a genuine problem there (I only tested on Mac before this PR...)

**Comment by davidrohr** [comment]
In fact, it was only a single ROCm library that has this problem. I have added an alias in a PR to your branch.

**Comment by aphecetche** [comment]
@davidrohr I merged your PR to my branch but in fact it seems the add_library alias is somehow misplaced, as it's done before the find_package(thrust) ?

**Comment by aphecetche** [comment]
@davidrohr FYI I've just pushed one more change to hopefully get the gpu green

**Comment by davidrohr** [comment]
Ok, thx, weird that it actually worked for me before. Let's see.

**Pull request merged**
