### PR TITLE
DPL: do proper ZMQ polling to avoid deadlocking

### PR DESCRIPTION
**Pull request by ktf**
The correct way to receive messages in an event based ZeroMQ is:

* Retrieve the file descriptor (already done)
* epoll it / kqueue so that you get notified on READ (already done)
* When processing, check if the ZMQ_EVENTS has ZMQ_POLLIN, which was
  missing.
* Receive the messages.

the old loop was fine as long as we were trying hard enough to receive
messages, the new one forces ZMQ to process some events from the queue
when we query for ZMQ_EVENTS.

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo suboptimal, but it should work...
@rbx, @dennisklein any idea why, despite checking for ZMQ_EVENTS, I still need to busy loop a bit in order to get some of the messages?

**Comment by rbx** [comment]
The file descriptor returned via `ZMQ_FD` is [edge-triggered](https://linux.die.net/man/3/zmq_getsockopt). So, for example, if multiple messages are available to receive, you may trigger only once, and you are supposed to call receive until `events & ZMQ_POLLIN` is no longer true, as you do with your `do ... while` loop. I find the edge-triggered fashion unfortunate. The issue has been raised several times in the past with ZeroMQ to also support level-triggered FD, but to my knowledge that was not implemented.

There is a nice explanation on it [here](https://funcptr.net/2012/09/10/zeromq---edge-triggered-notification/). But I think your `do ... while` is already doing the correct thing.

I don't understand why you need the outer `for` loop though. What happens when you leave it out?

**Comment by rbx** [comment]
Possibly because the FD can trigger even when no events (at least the ones you are interested in) have occurred. So when triggered, you could check `events & ZMQ_POLLIN` and break if it is false.

> The ability to read from the returned file descriptor does not necessarily indicate that messages are available to be read from, or can be written to, the underlying socket; applications must retrieve the actual event state with a subsequent retrieval of the ZMQ_EVENTS option.

From https://linux.die.net/man/3/zmq_getsockopt.

**Comment by ktf** [comment]
@rbx, yes, I know. That's exactly what I want to do with `(events & 1)`  (`ZMQ_POLLIN == 1`). The problem seems to be that the following happens:

1) epoll returns that the fd of zeromq is readable.
2) I check for ZMQ_EVENTS to have ZMQ_POLLIN
3) I get -2, exiting the loop.
4) I do not get notified anymore.

I wonder if the issue is that you multiplex EAGAIN and EINTR on the same exit code, while they should be treated differently...

**Comment by ktf** [comment]
@rbx this is the last incarnation of the code which we discussed live. The conclusions we got:

1) You need of course to check for ZMQ_EVENTS and if ZMQ_POLLIN is not raised, one needs to simply return.
2) If ZMQ_POLLIN is raised, contrary to our common understanding of the documentation, you can still get EAGAIN, even if a message will be shortly available. If one simply returns on the first EAGAIN, zeromq will not notify again the socket, unless new messages get queued. The solution I implemented is to busy loop for the first valid message, and only then exit the polling.
3) While probably a solution under some circumstances, having an infinite wait on the socket once ZMQ_POLLIN is raised would not work in this case, because I do not want to block the rest of the DPL loop if we get no data.

@davidrohr this is probably the culprit of the end of stream issue you were witnessing with the multithreaded framework. I will need to adapt the PR to take this into account.

**Comment by davidrohr** [comment]
ok, cool, thx, will retry with this commit.

**Comment by dennisklein** [comment]
> The solution I implemented is to busy loop for the first valid message, and only then exit ...

You could still avoid the busy wait, e.g. with a backoff strategy, meaning, trying the receive with an exponentially growing interval (up to some max interval). That way you could maintain progress on your main event loop. No?

And finally one could always busy wait in dedicated wait threads. That is how asio integrates blocking APIs into its event loop. Even its core epoll wait is hidden away like this.

**Comment by ktf** [comment]
@dennisklein that would complicate enormously the code, especially because there are cases in which I need to rate limit the looping and I would need to take into account if some iteration was triggered by "zeromq accident" or by the rate limiting itself. All in all my conclusion is that if we could have a non-edge triggered system to dispatch messages when running using shared memory, it would probably be the most reliable solution.

**Comment by jgrosseo** [comment]
@ktf @rbx Thanks for your effort!
@ktf once this is merged, can you trigger a daily build?

**Comment by ktf** [comment]
@jgrosseo yes, sure. With this I am unable to get stuck on both alinsure and my mac (tried 10 times each or so).

**Comment by ktf** [comment]
@dennisklein also notice that here we have multiple channels in input, so having any sort of delay will multiply latency by the number of channels.

**Comment by dennisklein** [comment]
> @dennisklein also notice that here we have multiple channels in input, so having any sort of delay will multiply latency by the number of channels.

Not sure if I follow your argument here.

Anyways, did anyone check, if waiting with the zmq provided [`zmq_poll`](https://linux.die.net/man/3/zmq_poll) also exhibit this behaviour? (I know this still has to be integrated with your main event loop which would be a different topic - just for my curiosity, if this facility is also broken, if anyone knows by any chance?)

**Comment by mkrzewic** [comment]
@dennisklein zmq's own event loop (zmq_poll) works fine. the problem is trying to integrate it in other event loops. I'm wondering if trying it the other way around would not be easier...

**Comment by rbx** [comment]
This works for me: https://gist.github.com/rbx/f61798bc7cb7000913b1c1e6b2767820
It doesn't have any extra loop and `events & ZMQ_POLLIN` always returns correct info (even though poller triggers with no data sometimes, as expected). Tried with zmq 4.3.2 and 4.3.3 (with TCP and IPC transports).
The major difference is that this uses Asio instead of libuv. But assuming both do the right thing, atm I don't see what goes wrong in your case...

**Comment by shahor02** [comment]
@ktf I see problem with this PR depending on the message size:
before this PR (or reverting it in the current dev) I could run TPC tracking from raw data for 200 pbpb events, the data transfer is:
````
o2-raw-file-reader-workflow $ARGS_ALL --configKeyValues "HBFUtils.nHBFPerTF=128"  --max-tf 0 --input-conf raw/TPC/tpcraw.cfg | o2-tpc-reco-workflow $ARGS_ALL --input-type=zsraw --disable-mc --output-type tracks,clusters  --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0"  --shm-segment-size 20000000000 --run
...
[5088:raw-file-reader]: [02:18:18][INFO] Sending 2699 parts to channel from_raw-file-reader_to_tpc-tracker
[5088:raw-file-reader]: [02:18:18][INFO] Sent payload of 2385414272 bytes in 2699 parts in 1 messages for TF 0 | Timing (total/IO): 7.600e-01 / 7.400e-01
[5088:raw-file-reader]: [02:18:18][INFO] Finished: payload of 2385414272 bytes in 2699 messages sent for 1 TFs
...
[5089:tpc-tracker]: [02:18:18][INFO] Event has 290741 8kb TPC ZS pages, 767985471 digits
````

With this PR the data are sent but the tpc-tracker never receives it: its processingFct is never called.
Still, it works fine with smaller input (from 70 events) 
````
[1853:raw-file-reader]: [22:30:16][INFO] Sending 1147 parts to channel from_raw-file-reader_to_tpc-tracker
[1853:raw-file-reader]: [22:30:16][INFO] Sent payload of 795746304 bytes in 1147 parts in 1 messages for TF 0 | Timing (total/IO): 2.800e-01 / 2.600e-01
````
and even with the same 200 events work if I suppress ~10% of links (i.e. total size and the number of parts in the multipart).

Any idea what could be the reason?

**Comment by ktf** [comment]
yes, there is an auto which became an int instead of a int64_t. i will fix it as soon as i am at my computer.

**Comment by shahor02** [comment]
@ktf still the same, https://github.com/AliceO2Group/AliceO2/pull/4843 does not help...

**Comment by ktf** [comment]
@rbx, is this exposing issue in FairMQ? I see that `fairmq/zeromq/Socket.h:165` has Socket::Receive() return an int.

**Comment by shahor02** [comment]
For the record: @davidrohr was able to process raw data of 500 events, i.e. 2.5 larger input than mine, so it is not just a matter of the size.

**Comment by rbx** [comment]
For ZeroMQ and single messages that particular line is fine, because `zmq_msg_recv` gives me an int only. But for single shared memory message it may be relevant - there the size can be higher but we only return int.

All multipart methods return int64 though.

Are you using single messages or multipart?

**Comment by davidrohr** [comment]
it could be that my data was in between of 4 and 6 GB, so casting to int would still have yielded a positive numer :)

**Comment by ktf** [comment]
I use:

```C++
FairMQParts parts;
result = fairMQChannel.Receive(parts, 0);
```

it's for sure returning an int, otherwise the compiler would have warned. Anyways, for now #4845 should suffice.

**Comment by ktf** [comment]
I would change the API to always return int64_t, doing the up cast for the ZeroMQ case.

**Comment by rbx** [comment]
> FairMQParts parts;
> result = fairMQChannel.Receive(parts, 0);

That returns int64_t.

> I would change the API to always return int64_t, doing the up cast for the ZeroMQ case.

Agreed.

**Comment by shahor02** [comment]
@ktf  it appears my dev was not properly updated, sorry. Actually, with https://github.com/AliceO2Group/AliceO2/pull/4843 it worked.

**Comment by ktf** [comment]
Ah, ok, that explains @rbx comment then. In any case, I would change the API.

**Comment by mkrzewic** [comment]
I remember hitting the "int" problem - it is just a problem with the public C api, zmq_msg_size(msg) will return the proper size even if return value of zmq_msg_receive is truncated (which is what happens I think). Solution for me was always using the latter.

**Comment by rbx** [comment]
@mkrzewic that's a nice workaround. I'll test and integrate it.

**Pull request merged**
