### PR TITLE
modification: noise and time structure for digitization

### PR DESCRIPTION
**Pull request by mwinn2**
- Pull request to add noise to MCH digits
- put in time information in accordance to real data digit format

### CODE REVIEW

**Comment by sawenzel** [comment]
clang format

**Comment by sawenzel** [comment]
@mwinn2 : This PR needs formatting fixes.

**Comment by mwinn2** [comment]
@sawenzel : yes, I finally will come back to it today.

**Review by sawenzel — APPROVED** [review]
I think this can be merged now. I'll do it after confirmation from @aphecetche.

**Pull request merged**
