### PR TITLE
TPC: silence error on macOS

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Not sure how this can actually compile everywhere else.

**Comment by shahor02** [comment]
different implementations of uint64_t?

**Comment by davidrohr** [comment]
yes, depending on os it can be `unsigned long` or `unsigned long long` or whatever.

**Comment by ktf** [comment]
agreed, but I would assume that my mac had the same setup as the CI mac... Also, the error is about .stop being a bitfield...

**Pull request merged**
