### PR TITLE
[QC-447] Allow to specify OutputSpecs of DataSamplingPolicies

### PR DESCRIPTION
**Pull request by knopers8**
@aferrero2707 This, together with already merged https://github.com/AliceO2Group/AliceO2/pull/4574, will allow you to put Data Sampling in the middle of your workflows with custom inputs and outputs.

### CODE REVIEW

**Comment by aferrero2707** [comment]
@knopers8 excellent! This looks exactly what we need.

What happens when there are multiple input and output specs? How are they matched together, and how the sampling works in this case? The specs are sampled independently, or all input specs from a DPL message are either passed or discarded together?

Thanks!

**Comment by knopers8** [comment]
Then you have to specify them in the same order for the query and the outputs, like:
```
"query" : "a:MCH/A;b:MCH/B;c:MCH/C",
"outputs" : "a-sampled:MCH/A_SAMPLED;b-sampled:MCH/B_SAMPLED;c-sampled:MCH/C_SAMPLED",
```
In such case, they should be all passed discarded together, at least when you use the "random" condition. It was implemented in a way that pseudo-random decisions are determined by the `DataProcessingHeader.startTime` field. So if that matches, the decision on sampling should be the same.

**Comment by knopers8** [comment]
@Barthelemy Could you have a look?

**Review by Barthelemy — APPROVED** [review]
All good. Out of curiosity what does MLEKO and CHLEB mean ?

**Comment by knopers8** [comment]
"milk" and "bread" respectively, totally random polish words that came to my mind.

**Pull request merged**
