### PR TITLE
Account getRunDuration in the cache report of BasicCCDBManager

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

Should we also change the getRunDuration to use SOX and EOX?

Cheers,

Chiara

**Review by costing — DISMISSED** [review]

**Comment by shahor02** [comment]
@chiarazampolli  I can change but do we have SOX/EOX for all runs? If not, I can implement a fall-back to SOR/EOR

**Comment by chiarazampolli** [comment]
I would for now do a fallback. There is a ticket to port SOX/EOX to 2022, https://its.cern.ch/jira/browse/O2-3868, which I need to revive (I had prepared everything, and asked for double-checking, but I did not get any feedback..). So for now, teh fallback is the best, in my opinion. 
Once we do this change, we should inform analysis also, in case it has some impact there (but surely SOX and EOX are the most appropriate times).

**Comment by shahor02** [comment]
@chiarazampolli OK, SOX (EOX) will be checked 1st, if not available or invalid, a warning will be logged and SOR (EOR) will be used:
```
auto& cc = o2::ccdb::BasicCCDBManager::instance();
auto rd = cc.getRunDuration(537901)
[WARN]  Missing/invalid SOX -> use SOR | Missing/invalid EOX -> use EOR
(std::pair<long, long> &) { 1686461166376, 1686463916384 }

auto rd = cc.getRunDuration(544124)        // note  that the SOX and EOX are present here but the EOX is 0!
[WARN]  | Missing/invalid EOX -> use EOR
(std::pair<long, long> &) { 1696574158874, 1696579333689 }

auto rd = cc.getRunDuration(544125)
(std::pair<long, long> &) { 1696579121844, 1696588528089 }
```

**Pull request merged**
