### PR TITLE
DPL: reworking AnalysisTask to have a generic process method

### PR DESCRIPTION
**Pull request by ktf**
Initial code to demonstrate how we can derive AOD inputs and outputs from an AnalysisTask.

### CODE REVIEW

**Comment by ktf** [comment]
Latest iteration seems to work for both one and two arguments of the process method. I think it will still need a bit of reshaping to workaround a GCC 7.3 bug, but we should be close.

**Comment by ktf** [comment]
@davidrohr I see an error in LLVM / CUB detection. Does it ring any bell?

```
-- Found OpenGL: /usr/lib64/libOpenGL.so   
CMake Warning at /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/O2/2210-1/lib/cmake/O2/O2Dependencies.cmake:133 (find_package):
  By not providing "FindLLVM.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LLVM", but
  CMake did not find one.

  Could not find a package configuration file provided by "LLVM" with any of
  the following names:

    LLVMConfig.cmake
    llvm-config.cmake

  Add the installation prefix of "LLVM" to CMAKE_PREFIX_PATH or set
  "LLVM_DIR" to a directory containing one of the above files.  If "LLVM"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/O2/2210-1/lib/cmake/O2/O2Config.cmake:11 (include)
  cmake/FindO2.cmake:19 (find_package)
  CMakeLists.txt:97 (find_package)


CMake Error at /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/O2/2210-1/lib/cmake/O2/Findcub.cmake:15 (message):
  CUB not found
Call Stack (most recent call first):
  /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/O2/2210-1/lib/cmake/O2/FindO2GPU.cmake:37 (find_package)
  /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/O2/2210-1/lib/cmake/O2/O2Dependencies.cmake:141 (find_package)
  /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/O2/2210-1/lib/cmake/O2/O2Config.cmake:11 (include)
  cmake/FindO2.cmake:19 (find_package)
  CMakeLists.txt:97 (find_package)


-- Configuring incomplete, errors occurred!
````

**Comment by davidrohr** [comment]
Where does this happen? In the CI? I think the problem is cub not LLVM. I fixed something in the detection yesterday. But then I am wondering why my PR passed the CI yesterday... Will have a look.

Sent from my mobile. (Excuse the typos!)

**Comment by ktf** [comment]
Yes, the O2/o2 one

--
Ciao,
Giulio

**Comment by davidrohr** [comment]
OK, that seems to be indeed my fault.
Fails in QC when it detects O2, not in O2 itself.
Still wondering why the CI didn't catch it yesterday.
Anyway, working on a fix.

**Comment by ktf** [comment]
Usual issue with incremental builds, I guess

--
Ciao,
Giulio

**Comment by davidrohr** [comment]
Merging without fixing the clang-format for now (as discussed with @ktf). Clang-format will be fixed generally next weekend anyway, and in this way we avoid conflicts.

**Pull request merged**
