### PR TITLE
Add a function to generate simple clusters and fix fake pileup

### PR DESCRIPTION
**Pull request by a-kieffer**
A function to generate simple clusters corresponding to straight lines starting from the point (0,0,0). Improvements will be added later.

### CODE REVIEW

**Comment by mconcas** [comment]
Hello, @a-kieffer , thanks for the commit.
Two little things:
1. Could you please make this PR a bit broader, to include the fix for the fake pileup?
2. Could you also put in the title the `[WIP]` tag in the title? We are still not ready for this to be merged

Thanks,
Matteo

**Comment by mconcas** [comment]
Ok, I think we are ready to remove the [WIP] tag and merge. @a-kieffer @shahor02

**Comment by shahor02** [comment]
shall I squash it to 1st commit during the merge or you want to do this?

**Comment by mconcas** [comment]
Thanks for squashing, it would be quicker.

**Pull request merged**
