### PR TITLE
Common files like GRP, geometry, matLUT can be loaded from other dirs + related changes.

### PR DESCRIPTION
**Pull request by shahor02**
*  Convert NameConf to ConfigurableParam, allow setting directories
    * one can pass --configKeyValues NameConf.mDirXXX for certain common files,
    currently defined keys are NameConf.mDirGRP, NameConf.mDirGeom, NameConf.mDirMatLUT
    * Adapt GRPObject::loadFrom and GeomManager::loadGeometry to use these paths
    * Make sure that all workflows contributing to FST and many others (which potentially may need
    to read these common files), are parsing and updating ConfigurableParam

*   Promote StringUtils to static class, collect there methods to manipulate with paths and alias path methods to boost::filesystem
    Also collect in StringUtils some common methods like tokenize(string) etc., remove some boiler-plate code.

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf @TimoWilken : The O2/o2 CI failed here again due to running out of memory. Could you restart it.
Do we have an idea what has changed? Why is it suddenly running oom still with GCC 7? Perhaps the problem with the oom in the GCC10 PR is actually unrelated, and we have  a general problem with the memory?

**Review by davidrohr — DISMISSED** [review]
didin't find obivous problems going over it, but also couldn't check everything in detail.

One general comment (for a later PR): Perhaps we should promote the `configKeyValues` to some kind of global dpl option, so we do not have to add it everywhere. This is a lot of useless copy&paste.

**Comment by shahor02** [comment]
> One general comment (for a later PR): Perhaps we should promote the `configKeyValues` to some kind of global dpl option, so we do not have to add it everywhere. This is a lot of useless copy&paste.
Agree, question to @ktf who does not like this class :)

**Comment by TimoWilken** [comment]
@davidrohr 
> Do we have an idea what has changed? Why is it suddenly running oom still with GCC 7? Perhaps the problem with the oom in the GCC10 PR is actually unrelated, and we have a general problem with the memory?

The memory use was getting quite close to 100% during the peaks on the CI builders, so maybe "normal" development just pushed it over the edge.

**Comment by davidrohr** [comment]
> The memory use was getting quite close to 100% during the peaks on the CI builders, so maybe "normal" development just pushed it over the edge.

@TimoWilken : OK, so can you reduce the number of jobs for O2/o2?

**Pull request merged**
