### PR TITLE
Follow up to PR #546, adding another underscore character to separate names

### PR DESCRIPTION
**Pull request by matthiasrichter**

### CODE REVIEW

**Comment by matthiasrichter** [comment]
The errors look like a general problem with the CI setup. I had this error today when updating and compiling my development environment. I could not figure out where the version conflict with the protobuf packages picked up from the system comes from. I had to remove them from the system in the end.

**Comment by dberzano** [comment]
See FairRootGroup/FairRoot#656, we'll wait for your scrutiny.

**Comment by dberzano** [comment]
The PR has been merged on FairRoot, and we've tagged a new reference version for O2 directly from the upstream branch. So if you update FairRoot to dev, and you update alidist too (see alisw/alidist#896, it's just a version bump), it should work.

**Comment by matthiasrichter** [comment]
Hi @dberzano , it looks like there are still problems unrelated to the PR, from another PR I see `build/O2/o2` failing with
```
[INFO   ] ---User path for Cuts and Processes (SetCuts.C) is used: /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/dev/0/Detectors/gconfig
Error in <TROOT::LoadMacro>: macro /g4libs.C not found in path .:/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/ROOT/v6-10-06+git_c54db1c10b-1/macros
input_line_60:2:3: error: use of undeclared identifier 'g4libs'
 (g4libs())
  ^
```

Here I do not see any recent post from alibuild bot.

**Pull request merged**
