### PR TITLE
Add all detectors

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Another attempt at this.

**Comment by shahor02** [comment]
I see there is not DCAL which I've added to detector identifiers. @mfasDa , will you treat the DCAL as separate detector or just EMCAL will cover both?

**Comment by ktf** [comment]
For the record, I got the list from:

http://svnweb.cern.ch/world/wsvn/alicetdrrun3/Notes/Run34SystemNote/detector-read-alice/ALICErun34_readout.pdf

**Comment by mfasDa** [comment]
@shahor02 DCAL is an extension of EMCAL. In run2 DCAL and EMCAL are handled as one detector. We will do the same for run3.

**Comment by shahor02** [comment]
Thanks @mfasDa, then I'll suppress separate identifier for DCAL

**Pull request merged**
