### PR TITLE
Fix for packing/unpacking constant or size 1 stream

### PR DESCRIPTION
**Pull request by shahor02**
Thanks to @MichaelLettrich for fast fix!

### CODE REVIEW

**Comment by mpuccio** [comment]
@shahor02: shall I try to use the nightly tag with this fix to process? Thanks a lot for the quick fix!

**Comment by shahor02** [comment]
Hi @mpuccio ,
I've tested it quite extensively, but if it does not take too much time, yes, would not hurt to test it on a larger stat.
BTW, it should be able to recover and read correctly already skimmed date.

**Comment by mpuccio** [comment]
I suspected that reading the comments in the code, unfortunately I scratched the old skimming production thinking that it was gone for good... With the nightly I will restart the skimming, then when we have one run ready we try the reconstruction. Will then the old tag we used for the apass1 work to reconstruct?
Thanks again!

**Comment by chiarazampolli** [comment]
Commit ported, label `async-2024-pp-apass1` removed.

**Pull request merged**
