### PR TITLE
[DCS][TOF] Make the data point random generator more reusable.

### PR DESCRIPTION
**Pull request by aphecetche**
Let the TOF specific things be within the Detectors/TOF/calibration only.
With the getDCSRandomGeneratorSpec function it's easy to create a dcs-sim-workflow for a given detector. See example of Detectors/TOF/calibration/testWorkflow/tof-sim-dcs-workflow.cxx

@chiarazampolli, following our private email exchange, this is what I had in mind to make the DP sim generation more easily reusable by other subsystems.

(could be considered WIP but would like to use the CI to validate it on a Linux machine...)

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Ciao @aphecetche ,
Ok, so your suggestion is to pass the list of DPs to construct the generator. Sure, this is fine with me. 
I think this is the main difference, right? You re-structured the code in the sense of moving files here and there, but I think that the main change is the one above. 
Thanks,
Chiara

**Comment by aphecetche** [comment]
@chiarazampolli yes indeed, you're correct. Sorry about the reshuffling that make the PR a bit large, but it was "necessary" to have the getDCSRandomGeneratorSpec in a public (i.e. installed) include.

**Comment by chiarazampolli** [comment]
Sure, no problem, it is indeed good (and once I realized that not so much was changed, it was quite quick!).

For me it is fine to merge, thanks again!

Chiara

**Comment by aphecetche** [comment]
@noferini  for this be merged it'd need a review/approval : can you have a look ? Thanks.

**Comment by sawenzel** [comment]
@noferini

**Review by noferini — APPROVED** [review]

**Comment by aphecetche** [comment]
@noferini thanks.
@AliceO2Group/core can this be merged then ?

**Comment by aphecetche** [comment]
we now have one failed build, but I assume this has nothing to do with that PR

**Comment by aphecetche** [comment]
can this PR be merged, please ?

**Comment by aphecetche** [comment]
@davidrohr  thanks.

**Pull request merged**
