### PR TITLE
raw-file-reader can send TF data to non-DPL FMQ channel

### PR DESCRIPTION
**Pull request by shahor02**
* raw-file-reader can send TF data to non-DPL FMQ channel
Provide e.g. --session default --raw-channel-config "name=raw-reader,type=push,method=bind,address=ipc://@rr-to-dpl,transport=shmem,rateLogging=1"

* Eliminate obsolete options of raw-file-reader
No need for options message-per-tf (must be always sent as a multipart of HBFs) and output-per-link (must be always sent per output_channel)

### CODE REVIEW

**Comment by shahor02** [comment]
@ironMann with this PR one can emulate the non-DPL message sent by DD, e.g.

````
[Terminal 1]> o2-dpl-raw-proxy --session default -b --dataspec "A:TOF/RAWDATA;B:ITS/RAWDATA;C:MFT/RAWDATA;D:TPC/RAWDATA;E:FT0/RAWDATA" --channel-config "name=readout-proxy,type=pull,method=connect,address=ipc://@rr-to-dpl,transport=shmem,rateLogging=1" | o2-dpl-raw-parser --session default  --input-spec "A:TOF/RAWDATA;B:ITS/RAWDATA;C:MFT/RAWDATA;D:TPC/RAWDATA;E:FT0/RAWDATA"
````

````
[Terminal 2]> o2-raw-file-reader-workflow  --session default --loop 1000 --delay 3 --input-conf raw/rawAll.cfg --raw-channel-config "name=raw-reader,type=push,method=bind,address=ipc://@rr-to-dpl,transport=shmem,rateLogging=1" --shm-segment-size 16000000000
````

I noticed that if for some reason the job crashes, sometimes the workflows cannot start again, they are getting stuck at
````
[6914:internal-dpl-clock]: [20:20:37][STATE] IDLE ---> INITIALIZING DEVICE
````
so I have to reboot the PC. I suspect the port to which FMQ connects becomes inaccessible. Any idea how one can reset it w/o rebooting?

**Comment by wiechula** [comment]
Hi Ruben,

Not sure if it is the same issue, but I also had problems in the past after crashes. The solution for me was described in
https://alice.its.cern.ch/jira/browse/O2-891?focusedCommentId=238562&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-238562

**Comment by ironMann** [comment]
@shahor02 as Jens points out, you can check if there are any leftover files in /dev/shm with fmq in the name. If so, they can be deleted between runs. 
@rbx I don't have this problem often. Is there any difference in how shm-monitor (cleanup) is running in DPL and vanila fmq devices?

**Comment by shahor02** [comment]
@wiechula @ironMann Thanks for the hint! Will check at the next crash.

**Comment by rbx** [comment]
@ironMann yes - DPL does not launch the cleanup daemon, but rather executes cleanup once during init and during exit of the workflow afaik. Which in principle should be fine.

**Pull request merged**
