### PR TITLE
[WIP] Update TRD validation macro for FST

### PR DESCRIPTION
**Pull request by martenole**
Hi Sean,
I think it is better to do a one to one comparison of the digits and tracklets in the FST. Since I am not sure about the ordering I have two double loops now where I try to find a match for each digit and tracklet. 
For the tracklets this works fine now when I ignore the PID values. So HCId, position etc are identical. For the digits however I can find only 15 matches out of almost 1 million digits. I don't really understand this, because when I compare the different spectra for e.g. ADC values they look identical. This is the case for all members of the digits class. Can it be that there is some mixup in during the conversion?
Cheers,
Ole

### CODE REVIEW

**Comment by bazinski** [comment]
@martenole I still like the idea of pretty pictures ;-) to do the verification, it allows for easier debugging if something is wrong, maybe leave it in as an option? But yes a 1 to 1 comparison is probably better. As for the digits, looking now.

**Comment by martenole** [comment]
But then you would actually need plots for everything, not just the detector number. And even then I am not sure how much the plots would help, if there were differences? In principle I expect the exact same number of tracklets and for every digit which is in the TF file an exact match in the simulation (there might be less digits, because of the calibration triggers). So I could also just break on the first tracklet/digit which does not have a match in simulation, right?

**Comment by bazinski** [comment]
Yes, I suppose what I am really proposing is heading into qc. Maybe I should consider the task at hand, testing the sim to raw to reco chain and 1 to 1 comparison is what is needed. It would however be nice to plot a pile of things in one macro and know kind of definitively if something is off with the digits and tracklets.

**Comment by tdietel** [comment]
Hello,
It sounds like we have quite a problem with the matching here. I agree that we probably need to do a 1:1 comparision - but with 1 million digits that's no fun. Can we run a FST with a single pp collisions? That should reduce the ambiguities quite a bit...
@bazinski, I hear you and look forward to many pretty pictures in your next presentations ;-)
But I think in this case we have a more fundamental problem that needs the 1:1 comparison.

**Comment by bazinski** [comment]
1 or a million, I think I know what is wrong. At the moment just trying to sort out why the tracklets in the data taken over the weekend are test tracklet format. Then will get to this.

**Comment by martenole** [comment]
Sure, the number of collisions in the FST is configurable. The comparison would be faster, if some matches would be found ;)
@bazinski what do you mean that the tracklets were test tracklet format? Are they not usable at all?

**Comment by bazinski** [comment]
@martenole chat on mattermost ;-)

**Comment by davidrohr** [comment]
what is the status of this? Can this be merged?

**Comment by martenole** [comment]
Sorry, not yet. Will remove WIP once ready

**Comment by bazinski** [comment]
Ok, digits problem is fixed in #PR9187.
As for this script, I think its better to sort the digits and do the tracklet and digit comparison per trigger record and then fail on the first missed one as opposed to going through the entire 2d comparison. I have a version you can merge into this.

**Comment by martenole** [comment]
Closing, macro functionality included in https://github.com/AliceO2Group/AliceO2/pull/9373

**Pull request closed without merging**
