### PR TITLE
Add option to create output directory

### PR DESCRIPTION
**Pull request by wiechula**
@davidrohr , this adds the option `-p` to create parent directories of the output directory in case it does not exist.

### CODE REVIEW

**Comment by davidrohr** [comment]
Thanks, actually, couldn't we make the -p option the default?

**Comment by wiechula** [comment]
Sure, I can change this.

**Comment by wiechula** [comment]
I reversed the logic now, that with '-n' the output directory will not automatically created

**Comment by wiechula** [comment]
Ok, gcc7 does not support `<filesystem>` only `<experimental/filesystem>` which needs `stdc++fs`. I decided now to use the ROOT functions, although I would have preferred plain c++.

**Comment by shahor02** [comment]
@wiechula you can also do this with system mkdir, but will need to create the nested directories in a loop

**Comment by wiechula** [comment]
It seems the error is not related to this PR.
Can it be merged?

**Comment by shahor02** [comment]
Hi @wiechula 
it does not create the nested directories, only the last one, i.e.
````
o2-tpc-digits-to-rawzs -i tpcdigits.root -o raw/TPC
[ERROR] could not create output directory raw/TPC/
````
but 
````
mkdir raw
o2-tpc-digits-to-rawzs -i tpcdigits.root -o raw/TPC
````
works.

**Comment by wiechula** [comment]
You are right, I forgot the `kTRUE` in the mkdir statement. See https://github.com/AliceO2Group/AliceO2/pull/3492

**Pull request merged**
