### PR TITLE
Added consistency checks and support deserialization of non-TObjects

### PR DESCRIPTION
**Pull request by matthiasrichter**
Deserialization is now possible also for all types of classes, TObject
is kept as the default.

Consistency checks for the target class info and class info of extracted
object ensure validity of reinterpret cast. The unique_ptr cleanup will
crash otherwise.

We still lack sanity check for the buffer content, TMessage might simply
crash uncontrolled.

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@dberzano @ktf, what happened to the CI? All open PRs are failing in multiple tests.

**Comment by dberzano** [comment]
@matthiasrichter I am having a look.

**Comment by dberzano** [comment]
* Tests will be turning green soon (wherever appropriate of course)
* New tests in error won't overwrite logs from other PR checkers any more

**Comment by matthiasrichter** [comment]
clang reported a real error, the default template argument in the function implementation is now removed and the tests are ok

**Pull request merged**
