### PR TITLE
Fix rate limiting

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This fixes the rate limiting in analysis for me. Most of the changes are actually unrelated, but somehow intertwined. Most of the changes are actually in other PRs already, so I will proceed to merge them as they pass tests, so that this one will finally become much simpler.

**Comment by ktf** [comment]
One more attempt. This fixes the reproducer I have on my laptop.

**Comment by ktf** [comment]
@ddobrigk @jgrosseo @aalkin @pzhristov this seems to finally fix the issue with the rate limiting. The PR is quite large, although it includes other cleanups and improvements. I tested on hyperloop using my build and a few of the usual workflows (Correlations, Histograms, SpectraTPC*). Could you verify a few of your own workflows, just to make sure I did not miss anything?

**Review by davidrohr — DISMISSED** [review]
This looks ok to me, particularly the changes in RateLimiter.cxx, though I am sure they were not the problem, since that code path is used only in async reco, but anyway they seem correct.

**Pull request merged**
