### PR TITLE
Stop CTFreader asap to avoid empty run cycle

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
Tested locally, merging.
The fullCI goes to timeout in a lot of PRs, and it seems always because of the alien access to CCDB. @costing , could you check, in this case was agent_id alimetal04.cern.ch-1696029252-pNoZNA.

**Comment by costing** [comment]
Hi @shahor02 , do you have a pointer to the client logs? Was it long in "ccdb reads" or did it reach the point of opening the file from CERN::OCDB and waiting there?

**Comment by shahor02** [comment]
Hi @costing here is it: https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11985/fbd55f16625b333b45e861f9556ace725ce63cab/build_O2_fullCI/fullLog.txt
```
231582:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Opening connection to JCentral. Please wait
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Opening connection to 137.138.47.222
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Successfully connected to 137.138.47.222
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/CTP/Calib/OrbitReset/01/35179/b07c53e0-b4c0-11ec-b66d-90ce809b250c in SE <ALICE::CERN::EOS>
[231582:internal-dpl-ccdb-backend]: [23:14:19][INFO] ccdb reads http://alice-ccdb.cern.ch/CTP/Calib/OrbitReset/1550600800000/b07c53e0-b4c0-11ec-b66d-90ce809b250c for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/CTP/Config/TriggerOffsets/05/51872/907486a2-ecaa-11ec-bea3-2a010e0a0b16 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:14:19][INFO] ccdb reads http://alice-ccdb.cern.ch/CTP/Config/TriggerOffsets/1/907486a2-ecaa-11ec-bea3-2a010e0a0b16 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/MID/Calib/CTFDictionaryTree/11/01215/e1d0cab9-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:14:19][INFO] ccdb reads http://alice-ccdb.cern.ch/MID/Calib/CTFDictionaryTree/1546300800000/e1d0cab9-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/TOF/Calib/CTFDictionaryTree/11/14372/26c89577-5b23-11ee-94e7-808d13fc24ee in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:14:20][INFO] ccdb reads http://alice-ccdb.cern.ch/TOF/Calib/CTFDictionaryTree/1546300800000/26c89577-5b23-11ee-94e7-808d13fc24ee for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/ITS/Calib/NoiseMap/00/21557/5cc82830-9fae-11ec-8357-25fc52e1250c in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:14:20][INFO] ccdb reads http://alice-ccdb.cern.ch/ITS/Calib/NoiseMap/0/5cc82830-9fae-11ec-8357-25fc52e1250c for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/ITS/Calib/ClusterDictionary/09/10449/c245a720-9fe3-11ec-975c-200114580202 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:14:20][INFO] ccdb reads http://alice-ccdb.cern.ch/ITS/Calib/ClusterDictionary/0/c245a720-9fe3-11ec-975c-200114580202 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/ITS/Calib/CTFDictionaryTree/01/12240/4049d0c2-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:14:20][INFO] ccdb reads http://alice-ccdb.cern.ch/ITS/Calib/CTFDictionaryTree/1546300800000/4049d0c2-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/MFT/Calib/NoiseMap/05/50603/a90ab5a0-9fae-11ec-8357-25fc52e1250c in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:14:20][INFO] ccdb reads http://alice-ccdb.cern.ch/MFT/Calib/NoiseMap/0/a90ab5a0-9fae-11ec-8357-25fc52e1250c for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/MFT/Calib/CTFDictionaryTree/05/53623/a61db061-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:29:32][INFO] ccdb reads http://alice-ccdb.cern.ch/MFT/Calib/CTFDictionaryTree/1546300800000/a61db061-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Error in <TJAlienConnectionManager>: Connection is broken!
[231582:internal-dpl-ccdb-backend]: Info in <TJAlien::Command>: Trying to reconnect in 1 sec
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Opening connection to JCentral. Please wait
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Opening connection to 137.138.99.140
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienConnectionManager>: Successfully connected to 137.138.99.140
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/MFT/Calib/ClusterDictionary/13/20237/c9a0bd70-9fe3-11ec-975c-200114580202 in SE <ALICE::CERN::EOS>
[231582:internal-dpl-ccdb-backend]: [23:29:34][INFO] ccdb reads http://alice-ccdb.cern.ch/MFT/Calib/ClusterDictionary/0/c9a0bd70-9fe3-11ec-975c-200114580202 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/TRD/Calib/CTFDictionaryTree/14/38726/b277557d-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:29:34][INFO] ccdb reads http://alice-ccdb.cern.ch/TRD/Calib/CTFDictionaryTree/1546300800000/b277557d-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/ZDC/Calib/CTFDictionaryTree/01/48254/dec218fb-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:29:34][INFO] ccdb reads http://alice-ccdb.cern.ch/ZDC/Calib/CTFDictionaryTree/1546300800000/dec218fb-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/CPV/Calib/CTFDictionaryTree/02/09430/d85638f3-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:29:34][INFO] ccdb reads http://alice-ccdb.cern.ch/CPV/Calib/CTFDictionaryTree/1546300800000/d85638f3-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/CTP/Calib/CTFDictionaryTree/01/14346/fbee0780-4690-11ed-a67e-2a010e0a0b16 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:29:34][INFO] ccdb reads http://alice-ccdb.cern.ch/CTP/Calib/CTFDictionaryTree/1546300800000/fbee0780-4690-11ed-a67e-2a010e0a0b16 for 1550600800000 (load to memory, agent_id: alimetal04.cern.ch-1696029252-pNoZNA), 
[231582:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/EMC/Calib/CTFDictionaryTree/07/04536/cf01a255-06d8-11ee-b4d8-200114580201 in SE <ALICE::CERN::OCDB>
[231582:internal-dpl-ccdb-backend]: [23:29:35][INFO] ccdb reads http://alice-ccdb.cern.ch/EMC/Calib/CTFDictionaryTree/1546300800000/cf01a255-06d8-11ee-b4d8-200114580201 for 1550600800000 (load to memory, agent_id: alimetal04.ce----- End of log -----
## End sw/BUILD/O2-full-system-test-latest/log

```

**Comment by costing** [comment]
Thank you @shahor02,

There is a 20 min gap, last message being about reading a file from the storage element. Looks like a storage issue and the 20 minutes is the default timeout in xrootd to open a file. The interactive shell sets the following timeouts and that reduces the waiting time to a few seconds (in this case of a non-responding server):

```
export XRD_CONNECTIONWINDOW="3"
export XRD_CONNECTIONRETRY="1"
export XRD_TIMEOUTRESOLUTION="1"
export XRD_REQUESTTIMEOUT="60"
```

Would it be possible to set the same in the test's environment? If the library doesn't get a different set of overrides, the environment variables should be applied instead.

If this works we should set them by default everywhere, for example from the module file of ROOT.

**Comment by shahor02** [comment]
pinging to @TimoWilken

**Pull request merged**
