### PR TITLE
TRD: Add calibration parameters from the CCDB to the digitizater

### PR DESCRIPTION
**Pull request by jolopezl**
Add calibrations from ccdb to the TRD digitizer.

### CODE REVIEW

**Comment by sawenzel** [comment]
Is this ready to be merged? I am currently introducing multithreading into the digitizer as well as doing some performance tunings which might touch the same lines of code.

**Comment by jolopezl** [comment]
> Is this ready to be merged? I am currently introducing multithreading into the digitizer as well as doing some performance tunings which might touch the same lines of code.

@sawenzel, please go ahead with the merge. I was planning to add something else but it didn't work, and I will be happy to see the multithreading (I tried it, but failed).

**Comment by sawenzel** [comment]
Ok. I will merge this together with https://github.com/AliceO2Group/AliceO2/pull/2638 (and take care of potential conflicts). Early next week I will introduce the multithreading and afterwards you can continue with the CCDB stuff.

**Comment by sawenzel** [comment]
should be squashed when merging

**Comment by sawenzel** [comment]
This actually breaks the digitization. Apparently no one is setting the calibrations object yet.

**Comment by jolopezl** [comment]
> This actually breaks the digitization. Apparently no one is setting the calibrations object yet.

I'm sorry, something went wrong, the calibrations are supposed to be set here: https://github.com/AliceO2Group/AliceO2/blob/3e7ed16366c08ea38997373c85f9336513fdb3ca/Steer/DigitizerWorkflow/src/TRDDigitizerSpec.cxx#L88

**Comment by sawenzel** [comment]
The problem is that this happens after your check in the constructor. In any case, I would prefer going one step back (reverting the commit) since I am now also getting strange ADC values in the digits related to this merge:
TRDdigitadc

**Comment by jolopezl** [comment]
This is strange. I agree with you, let's revert the commit. Is it possible to leave it open and see if I can fix it?

**Comment by sawenzel** [comment]
Before I looks like this (with many more digits):
adcbefore

**Comment by sawenzel** [comment]
Sure. You can reopen the PR in any case.

**Comment by jolopezl** [comment]
How are you getting the digits?, there is a macro called `CheckDigits.C` that helps. I think that the CCDB is actually helping in the direction we want to:

Screen Shot 2019-12-02 at 09 33 58

The AliRoot reference is what we are looking for.

**Comment by sawenzel** [comment]
Its fine. I am not saying that the new results are wrong. But the PR crashes and I have seen messages like "drift velocity too small" etc.
In addition, since I am doing the change towards multi-threading I would just prefer not to have these new dimensions to deal with. Let's target to bring in the CCDB stuff end of the week. Would that be ok with you?

**Comment by jolopezl** [comment]
Yes, I am fine with that. Just to be clear, did this message "drift velocity too small" came out of the digitizer after this PR?

**Comment by sawenzel** [comment]
Yes. I saw such values "0.62" coming from the CCDB.

**Pull request merged**
