### PR TITLE
reducing namespace o2::DataFormat::TPC to o2::TPC

### PR DESCRIPTION
**Pull request by matthiasrichter**
TPC data format definitions in DataFormats/Detectors/TPC got an extra
level of namespace which is not necessary.

@wiechula, @davidrohr, @sawenzel, @ktf, what do you think? I suggest removing one namespace level from the TPC data format definitions.

### CODE REVIEW

**Comment by sawenzel** [comment]
Note that clang format is not happy (by clicking on the travis report).

**Comment by ktf** [comment]
I fully agree that the less namespaces we have, the better it is. I would go even further saying that we should avoid having namespaces to differentiate detector specific types, but that's a longer discussion.

**Comment by davidrohr** [comment]
Hi, I also fully agree, in particular now, that all the detector stuff was moved to dataformats. I would skip the dataformat sub-namespace all together.

**Comment by wiechula** [comment]
I also agree

**Comment by matthiasrichter** [comment]
Just summarizing a short discussion with Giulio. Right now we are (ab)using namespaces to map the structure of Alice and to separate developers for the different detectors. While what actually matters is the content of an object, not what it is used for. In that respect it would be better to have the data format definitions all under `o2::dataformats` and specializing the class names by appropriate detector prefix or a property suffix.

This as a side note, we need to develop a concept here.

For the moment the change to`o2::TPC` makes the structure simpler and better allows moving of data format definitions to the `DataFormats` module.

**Pull request merged**
