### PR TITLE
TOF matching optimization

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
@shahor02 @chiarazampolli @davidrohr 
PR open with the last optimization.
This should improve more than a factor 10 the time performances in PbPb full TF.
Let see if we will need further optimizations

**Comment by chiarazampolli** [comment]
Hello, 
Here the results on 600 events produced by @davidrohr. 
As you can see there is a great improvement in the TPC-only matching, plus other fixes that allowed to speed up also the ITS-TPC one.

The performance in terms of matching is also maintained. The slight difference comes form the fact that Francesco has now some slightly stricter cuts. 

------------

TPC-only:

Timing prepareTOFCluster: Cpu: 0.000e+00 s
Timing prepare tracks: Cpu: 1.431e+01 s
Timing Do Matching: Cpu: 5.416e+02 s
Timing Do Matching ITSTPC: Cpu: 0.000e+00 s
Timing Do Matching TPC:    Cpu: 5.414e+02 s  --> with Francesco's change: Cpu: 3.819e+01 s  --> factor 14

Number of matched tracks:

new:

[97276:TOFCalibWriter]: [15:12:04][INFO] RECEIVED MATCHED SIZE 334358
[97277:TOFMatchedWriter_TPC]: [15:12:04][INFO] RECEIVED MATCHED SIZE 334358

dev:

[110332:TOFCalibWriter]: [15:42:13][INFO] RECEIVED MATCHED SIZE 335032
[110333:TOFMatchedWriter_TPC]: [15:42:13][INFO] RECEIVED MATCHED SIZE 335032

----------------------------------------------------------------------------------------------------


ITS-TPC and TPC-only:

Timing prepareTOFCluster: Cpu: 0.000e+00 s
Timing prepare tracks: Cpu: 1.516e+01 s
Timing Do Matching: Cpu: 3.466e+02 s
Timing Do Matching ITSTPC: Cpu: 4.540e+00 s --> with Francesco's changes Cpu: 3.930e+00 s --> factor 1.15 (because the changes affect mainly the matching to TPC-only tracks)
  Timing Do Matching TPC:    Cpu: 3.419e+02 s --> with Francesco's changes: Cpu: 2.568e+01 s --> factor 13

Number of matched tracks:

new:

[96792:TOFCalibWriter]: [15:05:00][INFO] RECEIVED MATCHED SIZE 318549
[96793:TOFMatchedWriter]: [15:05:00][INFO] RECEIVED MATCHED SIZE 105421
[96794:TOFMatchedWriter_TPC]: [15:05:00][INFO] RECEIVED MATCHED SIZE 213128

dev:

[110879:TOFCalibWriter]: [15:50:28][INFO] RECEIVED MATCHED SIZE 319013
[110880:TOFMatchedWriter]: [15:50:28][INFO] RECEIVED MATCHED SIZE 105402
[110881:TOFMatchedWriter_TPC]: [15:50:28][INFO] RECEIVED MATCHED SIZE 213611

**Comment by davidrohr** [comment]
Hi all, thx, without checking in detail, that looks already super nice. Is this only the result of the bc selection optimization or are there also algorithmic optimization? Don't get me wrong but if I understand correctly the trdatching is still faster, and i don't understand why. Perhaps we can find another factor of 2 somewhere? :)

Kind Regards
David Rohr

**Comment by chiarazampolli** [comment]
Ciao @davidrohr , 

The improvements comes from the optimization of the bc selection. There is some also from an optimization of the identification of the TOF element, but this is an additional ~10-25% on top of the ~10x from the BC.
I will look into callgrind, if it gives some hints for further improvements.

Chiara

**Comment by noferini** [comment]
I would suggest to go ahead with this PR to have the changes avilable in dev and then to continue the optimization (I have already moved to another branch for other PRs)

**Comment by chiarazampolli** [comment]
I agree.

**Review by shahor02 — APPROVED** [review]
will merge once CI is passed

**Comment by noferini** [comment]
I think failing checks are not related to this PR

**Comment by davidrohr** [comment]
Also fully agree, I'd merge this asap. I think the problem in the fullCI is the problem with the empty TRD digits which was recently introduced  @shahor02 ?

**Comment by shahor02** [comment]
Yes, fullCI is currently broken by the update in hit merging, @sawenzel is checking.

**Pull request merged**
