### PR TITLE
TOFFEElight processing

### PR DESCRIPTION
**Pull request by chiarazampolli**
second commit

New format for TOFFEELight

### CODE REVIEW

**Comment by chiarazampolli** [comment]
@preghenella , @pietro Antonioli, @noferini 

I will take care of the output of the CI tests later today/beginning next week, but meanwhile, you can take a look.

**Comment by chiarazampolli** [comment]
Hello @ktf , @TimoWilken , 

I should have fixed the CI error, but the one from dataflow is not related to my code. Let's see at the next test. 

Chiara

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , @ktf , 
I don't understand why the file that I committed shows a space less, so clang-format complains. I am attaching here the file that I have locally, and that I committed, where you see (with vi, pico, emacs) that everything is in order. This is not the first time that such mismatch happens to me... 
Before changing it with git clang-format, I would like to understand.

Thanks!

Chiara

[TOFFEElightReader_cxx.txt](https://github.com/AliceO2Group/AliceO2/files/5859247/TOFFEElightReader_cxx.txt)
PS. I had to change extension to attach here.

**Comment by TimoWilken** [comment]
Hi @chiarazampolli, clang-format complains because you have a tab character at the beginning of those lines instead of spaces. This can cause indentation to misalign, especially when some lines use spaces and some use tabs for indentation -- see the following screenshot:

image

As every other line in the code seems to use spaces for indentation, you might have to change your editor settings to insert spaces when you type a tab.

**Comment by chiarazampolli** [comment]
Ciao @TimoWilken ,
Thanks for checking! I now committed the fix suggested by clang-format. hopefully they are fine. 
I will verify the settings of my editor, sure. 
Chiara

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , 

Now it complained again, about something that I had already fixed, but that when running clang-format locally was fixed automatically by clang-format. 
I am running with Clang/v11.0.0-1.
Before I fix this again, could you check? Because it means that when I run clang-format locally, the result is not liked by the CI.

Chiara

**Comment by TimoWilken** [comment]
Hi @chiarazampolli, the CI uses `clang-format-8` for some reason, I think the default rules changed between v8 and v11. Can you install `clang-format-8` locally?

**Comment by chiarazampolli** [comment]
Ciao @TimoWilken ,
Clang 11 comes from alibuild. Does it mean that everybody needs to change the version that they get automatically, in order to be compatible with the CI? Cannot we update the CI? Or Clang from alibuild was downgraded?
For now I fixed the problem by hand.
Thanks for your patience!

**Comment by TimoWilken** [comment]
Hi @chiarazampolli, on some systems, you can install clang-format-8 next to clang 11 (e.g. on [Ubuntu]). Changing the version in CI would change the rules clang-format uses, which means that a lot of existing code would suddenly fail CI -- I'd like to avoid that for now. :)

The CI should actually make a PR in your fork of O2 with the changes it wants, but that's broken until I convince Giulio to apply a workaround for that (I can't reproduce the error with sending the PR locally). Sorry, working on it.

[Ubuntu]: https://packages.ubuntu.com/groovy/clang-format-8

**Comment by chiarazampolli** [comment]
Ciao @TimoWilken , 
I fully agree that we should not have the CI fail just because we change Clang. Definitely. But then, why aliBuild ships a different version? 
If you tell me how to install Clang 8 (both on Ubuntu 20 and Ubuntu 18) without breaking alibuild, I am happy to learn.

Chiara

**Comment by TimoWilken** [comment]
Hi @chiarazampolli, I don't know why the versions are different, I'm guessing that alibuild used to ship with clang 8, was upgraded to 11 at some point, but nobody updated the CI to avoid breaking stuff.

I haven't tried it (I don't run Ubuntu myself), but as far as I can tell, you can install the `clang-format-8` package from `universe` (same package on [18.04], [20.04] and [20.10]). I shouldn't conflict with any other clang packages that you have already installed. Then you can run `/usr/bin/clang-format-8` (instead of plain `/usr/bin/clang-format`, which will still be v11).

[18.04]: https://packages.ubuntu.com/bionic/clang-format-8
[20.04]: https://packages.ubuntu.com/focal/clang-format-8
[20.10]: https://packages.ubuntu.com/groovy/clang-format-8

**Comment by ktf** [comment]
clang-format 8 is simply what was available at the time. We should move to 11. I will open a ticket.

**Comment by chiarazampolli** [comment]
@ktf , I thought so too. Should I go back to the formatting of clang 11, and then we merge despite the failure?
@noferini , can you meanwhile check this PR? The thing with clang is just minor formatting.

Chiara

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , @ktf .

I think that you are moving to clang 11. Should I revert the change for clang 8 (which formats in a very ugly way :) )?

@noferini , can you review?

Chiara

**Comment by TimoWilken** [comment]
Hi @chiarazampolli, yes, formatting it like clang-format-11 is better.

If you rebase this PR on top of the current dev branch, you'll get the new clang-format-11 checker, but if that's too much work, just ignore the current clang-format-8 checker if it disagrees :)

**Comment by chiarazampolli** [comment]
Ciao @TimoWilken , 

Ok, so I need to re-run clang 11 locally first. 

Thanks!

Chiara

**Comment by chiarazampolli** [comment]
Rebased and reformatted. Let's see what clang says, but in case, we should ignore it.

Chiara

**Comment by chiarazampolli** [comment]
Clang complains as before, so rebasing did not help. 
Anyway, if @noferini could review, then I think we should just merge.

**Review by noferini — APPROVED** [review]

**Comment by chiarazampolli** [comment]
@ktf , @TimoWilken , 

Can we merge? clang error is known. 

Chiara

**Comment by TimoWilken** [comment]
Merged!

**Comment by chiarazampolli** [comment]
Thanks a lot!!!

**Pull request merged**
