### PR TITLE
Change CMake to handle dependencies using "buckets"

### PR DESCRIPTION
**Pull request by Barthelemy**
New PR using the branch merged by Mohammad with the changes made by Jens and others.

### CODE REVIEW

**Comment by Barthelemy** [comment]
@ktf @matthiasrichter @pzhristov @dberzano

**Comment by Barthelemy** [comment]
Does not seem to build with Jenkins...

**Comment by Barthelemy** [comment]
I don't know, I will first finish handling the include directories within the buckets before tackling this.

**Comment by ktf** [comment]
This does not merge anymore after the changes I had to do to fix missing dependencies on `boost_log` / `boost_log_setup` see #136. Can you please rebase making sure the conflict is resolved in favour of my PR (otherwise we will get the usual problems when testing with Jenkins, which is actually not a false positive)?

**Comment by ktf** [comment]
@Barthelemy can you believe it's finally green? ;-)

**Comment by Barthelemy** [comment]
All checks have passed. 

So, now, the last point remaining, that we discussed a couple of weeks ago, is to use directly FairRoot CMake macros. Meanwhile Mohammad started using directly the ROOT macros in FairRoot. We should follow the same path. 

Should I wait for you, @MohammadAlTurany , to finish your work ? if so, shouldn't we merge this PR already to avoid having to merge back and forth all the time ? Otherwise I can try to use directly the macros of ROOT.

**Comment by Barthelemy** [comment]
green again ;)

**Comment by Barthelemy** [comment]
In the end, do we squash the commits ?

**Comment by ktf** [comment]
Yes, I will do it.

**Pull request merged**
