### PR TITLE
FIT: add time-calibration command line option

### PR DESCRIPTION
**Pull request by phymanshu**

### CODE REVIEW

**Review by AllaMaevskaya — COMMENTED** [review]
Good work, but I can not imagine case when we need to calibrate data outside 2.5 ns (200 channels) range. It could be special artificial laser runs. I prefer to keep narrow range to remove tails and signals from slow particles

**Review by jotwinow — DISMISSED** [review]

**Comment by phymanshu** [comment]
Hi @shahor02 
Builds were failed but the errors are not related to the developments. Could you please check?

**Comment by shahor02** [comment]
@HimanshuCERN those which failed are unrelated, let's wait for others to converge.

**Review by AllaMaevskaya — DISMISSED** [review]

**Comment by phymanshu** [comment]
Hi @shahor02 
Are there any problems in this PR.?

**Review by AllaMaevskaya — COMMENTED** [review]
Could you change 
int FT0ChannelTimeTimeSlotContainer::sGausFitBins = 999;
to 100?
Results of fitting in so wide interval are wrong, I checked

**Comment by phymanshu** [comment]
Hi 
@AllaMaevskaya @jotwinow 
I added the same fitting option for FT0Calibration-Workflow.cxx and committed in the same branch.
Alla you can check it now from this branch and run `o2-calibration-ft0-calibration` workflow...

**Comment by phymanshu** [comment]
@jotwinow 
The error seems to be from the CCDB. I build the s/w locally twice but there is no error. Also you can see [here](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/7416/e81aebfa7afea0a974c64920c900c8505173ace8/build_O2_fullCI/pretty.html#errors)
the problem also arises with TRD... (Thanks @sbysiak for pointing this out)
@AllaMaevskaya maybe you can try to run/test changes from this repo and merge it...
Thanks a lot!!!

**Comment by AllaMaevskaya** [comment]
I merged this branch with recent dev and it passed all tests

**Pull request merged**
