### PR TITLE
Workaround on ITS upgrade to pass tests

### PR DESCRIPTION
**Pull request by mconcas**
@davidrohr : I cannot reproduce the issue myself at the moment, the most reasonable workaround I see at the moment is this, I'll anyway iterate on these files on Monday.
If the issues were only the ones pointed in #4210 it should be sufficient, let me know otherwise.

### CODE REVIEW

**Comment by davidrohr** [comment]
Still fails with `[14:34:57][FATAL] can't find ITSULayer10 volume`, is this fixed by #4250?

**Comment by shahor02** [comment]
https://github.com/AliceO2Group/AliceO2/pull/4250 has nothing to do with this. @mconcas I don't understand why ``https://github.com/AliceO2Group/AliceO2/blob/0ebee0f36ea0c575e87c10c76e009edc3a01adc7/Detectors/Upgrades/PostLS4/IT4/base/src/GeometryTGeo.cxx#L513`` triggers a fatal for ``ITSULayer10`` if you hardcode N layers to 10 (i.e. 0:9), but I see that both ITS3 and ITS4 modules are activated at the same time in the https://github.com/mconcas/AliceO2/blob/0ebee0f36ea0c575e87c10c76e009edc3a01adc7/macro/build_geometry.C#L192-L204,
since I see in the log:
````
[14:35:29][INFO] Activating IT3 module
[14:35:29][INFO] L# 4 Phi:0 R:19.6 Nst:24 Nunit:4 Lthick:0.01 Dthick:0.003 DetID:0 B:0
[14:35:29][INFO] L# 5 Phi:0 R:24.55 Nst:30 Nunit:4 Lthick:0.01 Dthick:0.003 DetID:0 B:0
[14:35:29][INFO] L# 6 Phi:0 R:34.39 Nst:42 Nunit:7 Lthick:0.01 Dthick:0.003 DetID:0 B:0
[14:35:29][INFO] L# 7 Phi:0 R:39.34 Nst:48 Nunit:7 Lthick:0.01 Dthick:0.003 DetID:0 B:0
[14:35:29][INFO] L# 0 with ITS3 geo R:1.8 Dthick:0.003 DetID:0 B:0
[14:35:29][INFO] Added layer: 0
...
[14:34:54][INFO] Activating IT4 module
[14:34:54][INFO] L# 0 with ITS4 geo R:1.8 Dthick:0.003 DetID:0 B:0
[14:34:54][INFO] Added layer: 0

[14:34:54][INFO] L# 1 with ITS4 geo R:2.4 Dthick:0.003 DetID:0 B:0
[14:34:54][INFO] Added layer: 1
...
````
This is because the geometry configurator by default enables all available modules: https://github.com/mconcas/AliceO2/blob/0ebee0f36ea0c575e87c10c76e009edc3a01adc7/Common/SimConfig/src/SimConfig.cxx#L69-L71
I think instead  of ``ENABLE_UPGRADES`` (or on top of it) one should have more targeted e.g. ``ENABLE_ITS3`` and ``ENABLE_ITS4``: the code for ITS4 is as incompatible with ITS2 as it is with ITS3.

Also, the numbers (r, z) in https://github.com/mconcas/AliceO2/blob/0ebee0f36ea0c575e87c10c76e009edc3a01adc7/Detectors/Upgrades/PostLS4/IT4/simulation/src/Detector.cxx#L142-L152 don't make sense, though this should not be related to current problem.

**Comment by davidrohr** [comment]
Wasn't the idea of the ENABLE_UPGRADES that these are built in addition to the Run 3 stuff. I.e. it should not replace ITS2, but it should build something in addition. If ENABLE_UPGRADES replaces makes us incompatible to ITS2, then I think it is a bad idea to have the upgrade check in the GPU CI, it should then be totally separate. But wouldn't that then mean that one also needs two independent O2 builds, for ITS2 and for ITS3? (adding @qgp)

**Comment by mconcas** [comment]
Numbers don't make any sense on purpose, as they are put there as a demonstrator of more than 7 layers layout, they will be adjusted later.

Concerning how CI is performed I didn't pay too much attention as I was told the CI was not running on code of upgrades, now it seems not be the case anymore.
Sorry for the sudden issues.

**Comment by mconcas** [comment]
> Wasn't the idea of the ENABLE_UPGRADES that these are built in addition to the Run 3 stuff. I.e. it should not replace ITS2, but it should build something in addition. If ENABLE_UPGRADES replaces makes us incompatible to ITS2, then I think it is a bad idea to have the upgrade check in the GPU CI, it should then be totally separate. But wouldn't that then mean that one also needs two independent O2 builds, for ITS2 and for ITS3? (adding @qgp)

The geometry builder is tested by enabling all the available modules, otherwise the flags don't make you incompatible with ITS 2, as you are always able to choose if to use it or using a ITS3 from the simulation parameters.
In the end either we are able to separately test different setups or we might just want to disable the upgrades in tests for the moment.

**Comment by shahor02** [comment]
If you want to build both ITS3 and ITS4 on top of Run2 code, then you cannot rely in default geometry initialization.
@mconcas could you change the line https://github.com/mconcas/AliceO2/blob/0ebee0f36ea0c575e87c10c76e009edc3a01adc7/Common/SimConfig/src/SimConfig.cxx#L69-L71
to
````
#ifdef ENABLE_UPGRADES
  if (d != DetID::IT3 && d != DetID::IT4) {
      active.emplace_back(DetID::getName(d));
  }
#else
  active.emplace_back(DetID::getName(d));
#endif
````

This will exclude run4/run5 modules from default initialization but will allow their initialization by explicit option to ``o2-sim``.

**Comment by mconcas** [comment]
> This will exclude run4/run5 modules from default initialization but will allow their initialization by explicit option to `o2-sim`.

This is a nice compromise, thanks a lot. 
Anyways on Monday I'll have a look with @mario6829 through upgrade detectors code, we'll check the behaviour with 10 Layers.

**Comment by davidrohr** [comment]
CI passed except for 1 clang-format problem. I have fixed that myself and merged it to get this CI green finally. Thx for the work!

**Pull request merged**
