### PR TITLE
Update IB geometry to latest data

### PR DESCRIPTION
**Pull request by mario6829**
The IB geometry was updated to the latest data as requested at ITSU plenary session. In particular the metal stack was added to the Si sensor, the FPC aluminum layers are more realistic, and the glue between the chip and the sensor was added.

### CODE REVIEW

**Comment by sawenzel** [comment]
@mario6829 : Don't worry about the failing test (this is not related); @iouribelikov : I merge once you approve.

**Comment by iouribelikov** [comment]
@mario6829 @shahor02  Hi Mario, Ruben.  I have found a little problem with this PR.  Now, since Mario adds a 15um-thick metal layer to the chip, the thickness of the sensitive part should be adjusted accordingly !   Otherwise, I observe a quite sizeable drop in the number of produced hits, and the reconstruction efficiency goes down by a factor almost 3.

To fix it, it's enough to change the line #47 of SegmentationAlpide.h like this:
  static constexpr float SensorThickness = 35.e-4;     
(Currently, it is 45e-4.  Which does not allow for inserting the 15um metal layer, because the total thickness of the IB chips is 50um)

Also, I think, we should change the line #108 of Detector.cxx like this:
  const double kSiThickOB = 100e-4;  (Currently, it is 50e-4)
This does not have that dramatic impact on the reconstruction, but the OB chips are 100um-thick.

Please, feel free to suggest a more elegant solution.

Cheers,
Yura.

**Comment by mario6829** [comment]
Dear Yura,
you spoiled my presentation of Friday :)  Indeed this is the problem I would like to discuss. The sensor thickness was increased by Ruben to take into account the charge diffusion (the actual sensor thickness, 18um, is accounted for in the digit simulation). I have different proposals to solve this issue, one is decreasing the sensor thickness, but this has to be crosschecked with Ruben. We will discuss this in the next PWG meeting.
For what concerns the OB thickness, I would leave as it is (wrong, I know), because this PR is for the IB only. I am preparing a second PR for the OB in which the thickness will be increased to 100um, but I have many more improvements to do, so I think it is better to have it in another PR and not to put the sole OB thick increase in the IB modifications.
Cheers
Mario

**Comment by iouribelikov** [comment]
@mario6829 Ciao Mario.  Sorry ! :-)   OK. No problem. Let's discuss it this Friday. Thank you a lot !
Yura.

**Comment by sawenzel** [comment]
@mario6829 , @iouribelikov : So shall we go ahead with this PR?

**Comment by iouribelikov** [comment]
@sawenzel Please, wait a bit.  At the moment, this PR does *not* work correctly.  

We already know where the problem is. But we need to agree on a solution. 
We'll do it during the ITS software meeting this Friday.

**Comment by sawenzel** [comment]
Fine. Just wanted to be sure.

**Comment by mario6829** [comment]
@iouribelikov @shahor02 Hi, I reduced Segmentation::SensorThickness to 30um. Let me know if it is ok. Cheers
Mario

**Comment by shahor02** [comment]
@mario6829 : for the moment should be ok, but eventually we can consider to use two different Miko's parameterizations for two real thicknesses, for IB and OB.

**Comment by iouribelikov** [comment]
@mario6829 Perfect. Thank you very much, Mario.
@sawenzel  +1.  Let's merge this PR.

**Pull request merged**
