### PR TITLE
DPL: Reconstruct the full command and propagate it to workflow dump tools

### PR DESCRIPTION
**Pull request by knopers8**
@ktf I took a stab on providing to the AliECS the full command used to run the workflow (including all the workflow merging). This would enable the AliECS to avoid generating intermediate files to run a topology and thus streamline it as much as possible.

### CODE REVIEW

**Review by ktf — APPROVED** [review]
This is fine with me, however it's not clear to my what is missing from the current list of arguments. Could you please elaborate?

**Comment by knopers8** [comment]
The argument list doesn't provide the command used to generate the full workflow. So if I have something like:
```
o2-dpl-a | o2-dpl-b
```
Then the execution of each process gives me only this:
```
o2-dpl-b --id <some-device-from-b> --other-arguments
```
But I need this:
```
o2-dpl-a | o2-dpl-b | o2-dpl-b --id <some-device-from-b> --other-arguments
```

There is a solution with using intermediate files (`cat dump.json`), but I would like to avoid relying on generated files.

In principle, I could reconstruct the full command from `DataProcessorInfos`, which have exec name and args, but there is no unique identifier of a part of the merged workflow. So having duplicated executables in the same merged workflow would be quite troublesome:
```
o2-qc --config json:///a/b/c.json | o2-qc --config json:///d/e/f.json
```

**Comment by ktf** [comment]
Ok, thank you for your explanations.

**Comment by knopers8** [comment]
I don't understand why o2-dataflow failed.

**Comment by ktf** [comment]
What was the error? It was transient in any case.

**Comment by knopers8** [comment]
There was no error or failed test, but the check was marked as failed. Thanks for merging

**Pull request merged**
