### PR TITLE
Fix to access MC track container 

### PR DESCRIPTION
**Pull request by chiarazampolli**
@alindner14 , @sawenzel , @knopers8 
I think that this is the correct way to access the MC track container - earlier the index was going out of range.
@shahor02 , maybe you could also take a look.

### CODE REVIEW

**Review by sawenzel — APPROVED** [review]

**Review by shahor02 — APPROVED** [review]
The fixes are correct, but the line https://github.com/AliceO2Group/AliceO2/blob/227b9317cd635acc3c7b1645b5e652740f21db2a/Detectors/GlobalTracking/src/MatchITSTPCQC.cxx#L189 is highly inefficient: for every matched track it loops over all selected TPC tracks. Why not using at https://github.com/AliceO2Group/AliceO2/blob/227b9317cd635acc3c7b1645b5e652740f21db2a/Detectors/GlobalTracking/src/MatchITSTPCQC.cxx#L175-L181
```
  std::vector<int> setTPCTrackEnry(mTPCTracks.size(), -1);
  // cache selection for TPC tracks
  for (auto itrk = 0; itrk < mTPCTracks.size(); ++itrk) {
    auto const& trkTpc = mTPCTracks[itrk];
    if (selectTrack(trkTpc)) {
      setTPCTrackEnry[itrk] = (int)mSelectedTPCtracks.size();
      mSelectedTPCtracks.push_back(itrk);
    }
  }
```
and instead of https://github.com/AliceO2Group/AliceO2/blob/227b9317cd635acc3c7b1645b5e652740f21db2a/Detectors/GlobalTracking/src/MatchITSTPCQC.cxx#L189 (and many similar lines below) using
```
if (setTPCTrackEnry[idxTrkTpc]!=-1) {
```
?

**Comment by chiarazampolli** [comment]
Hi @shahor02 , 

Yes, this is indeed much better. I will take a better look tomorrow. Thanks for the suggestion!

Chiara

**Comment by chiarazampolli** [comment]
BTW, @ktf , @TimoWilken , @shahor02 , why is this PR not merged if it was already approved and it passed all tests?

**Comment by shahor02** [comment]
Apparently the automerge was not requested, merging by hand.

**Comment by chiarazampolli** [comment]
Who should request it? Is it a new feature? It is the first time I hear about it (apart from a PR in O2DPG, but I did not know what it referred to).

**Comment by shahor02** [comment]
when opening a PR you can request that it is merged automatically once all checks are passed and reviewers approved it. But I've never used this...

**Comment by chiarazampolli** [comment]
First time I have to do it... At least I never noticed. 
Thanks for the information, next time I will pay attention.

**Pull request merged**
