### PR TITLE
splines: construction of 1D- and 2D- splines from any set of data points

### PR DESCRIPTION
**Pull request by sgorbuno**
A functionality to construct 1D- and 2D- splines from any set of data points is added.

### CODE REVIEW

**Review by shahor02 — DISMISSED** [review]
Hi @sgorbuno 
Thanks! Also for the demo macro. I've tried to understand from it how the distortions per voxel should be converted to the splines, but did not succeed. Could you please add some comments or better a short readme, outlining the interface?

**Comment by sgorbuno** [comment]
Hi @shahor02,
 
> Could you please add some comments or better a short readme, outlining the interface?

Sure, I will. Should I do it already in this PR?
I wanted first to commit the new math and see if it passes the CI tests, 
then update the TPCFastTransform initialization in another PR.
Also, the spline code is not final here. There are some leftovers that will be removed. And the initialization time will improve.

Sergey.

**Comment by shahor02** [comment]
Hi @sgorbuno 

Thanks, sure, the doc can go to another PR, as you prefer.
Note that the reported CI errors are genuine.

**Comment by sgorbuno** [comment]
Hi @shahor02 , 

could you please help me, where can I find the logs for the failed CI tests?

**Comment by davidrohr** [comment]
Hi @sgorbuno : In the fullCI you have (by clicking on the details button):
```
========== List of errors found ==========
/sw/SOURCES/O2/8096-slc8_x86-64/0/GPU/TPCFastTransformation/BandMatrixSolver.h:24:10: error: inclusion of deprecated C++ header 'stdlib.h'; consider using 'cstdlib' instead [modernize-deprecated-headers]
/sw/SOURCES/O2/8096-slc8_x86-64/0/GPU/TPCFastTransformation/SymMatrixSolver.h:24:10: error: inclusion of deprecated C++ header 'stdlib.h'; consider using 'cstdlib' instead [modernize-deprecated-headers]
/sw/SOURCES/O2/8096-slc8_x86-64/0/GPU/TPCFastTransformation/BandMatrixSolver.h:24:10: error: inclusion of deprecated C++ header 'stdlib.h'; consider using 'cstdlib' instead [modernize-deprecated-headers]
/sw/SOURCES/O2/8096-slc8_x86-64/0/GPU/TPCFastTransformation/SymMatrixSolver.h:24:10: error: inclusion of deprecated C++ header 'stdlib.h'; consider using 'cstdlib' instead [modernize-deprecated-headers]
/sw/SOURCES/O2/8096-slc8_x86-64/0/GPU/TPCFastTransformation/SymMatrixSolver.h:24:10: error: inclusion of deprecated C++ header 'stdlib.h'; consider using 'cstdlib' instead [modernize-deprecated-headers]
/sw/SOURCES/O2/8096-slc8_x86-64/0//GPU/TPCFastTransformation/BandMatrixSolver.h:1:1: error: missing or malformed copyright notice
/sw/SOURCES/O2/8096-slc8_x86-64/0//GPU/TPCFastTransformation/SymMatrixSolver.h:1:1: error: missing or malformed copyright notice
/sw/SOURCES/O2/8096-slc8_x86-64/0//GPU/TPCFastTransformation/SymMatrixSolver.cxx:1:1: error: missing or malformed copyright notice
/sw/SOURCES/O2/8096-slc8_x86-64/0//GPU/TPCFastTransformation/BandMatrixSolver.cxx:1:1: error: missing or malformed copyright notice
```

for the others I am not sure. I think at the moment they are failing for unrelated reasons with general CI errors and don't produce a log file.

**Comment by shahor02** [comment]
Hi @sgorbuno I see plenty of `std::cout` in the code, can this be changed to `LOG(info)` (w/o `\n`) ?
Since the tests are passed, one can do this in additional PR after merging this one, let me know.

**Comment by sgorbuno** [comment]
> Hi @sgorbuno I see plenty of `std::cout` in the code, can this be changed to `LOG(info)` (w/o `\n`) ? Since the tests are passed, one can do this in additional PR after merging this one, let me know.

Hi @shahor02, I removed cout"s from .cxx files, but left them in .C macros, it is ok?

**Comment by shahor02** [comment]
Hi @sgorbuno 
yes, thanks, for the macros this is not a problem.

**Comment by shahor02** [comment]
ps @sgorbuno , is this PR ready for merging?

**Comment by sgorbuno** [comment]
> ps @sgorbuno , is this PR ready for merging?

yes

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
