### PR TITLE
Alpide clusterer can mask pixels fired in previous ROFrame

### PR DESCRIPTION
**Pull request by shahor02**
In the default clusterization mode the o2::ITSMFT::Clusterer will reject in every ROFrame 
those pixels which were fired in the previous ROFrame (due to the long signal over threshold).
Option can be configured via:
clusterer->setMaskOverflowPixels(bool);
e.g.
o2::ITS::ClustererTask task;
task->getClusterer().setMaskOverflowPixels(true);
Same for the o2::MFT::ClustererTask

### CODE REVIEW

**Comment by sawenzel** [comment]
Looks good to me. @iouribelikov : Do you approve?

**Comment by iouribelikov** [comment]
@shahor02 @sawenzel  Hi Ruben, Sandro.  Looks good, indeed !

But, the ITS test suite stopped working  (the macros ITS/macros/test/Check*.C break).
So I am able to tell if the efficiencies and resolutions are the same as before...

Looks like something has happened to the MC labels of clusters and tracks.  I am debugging.

Cheers,
Yura.

**Comment by shahor02** [comment]
Hi Yura,

Actually, I see that I have also adapted the CheckDigits for the MCTruthContainer, for me it works:
````
o2sim -n20 -mITS
root -b -q $O2_ROOT/share/macro/run_digi_its.C+\(10e3,\"o2dig.root\",\"o2sim.root\",\"o2sim_par.root\"\) 2>&1 | tee dig.log
root -b -q $O2_ROOT/share/macro/run_clus_its.C+\(\"o2clus_its.root\",\"o2dig.root\",\"o2sim_par.root\"\) 2>&1 | tee clus.log
root ~/alice/O2/Detectors/ITSMFT/ITS/macros/test/CheckDigits.C++g
````
But for the large occupancy data the CheckDigits is prohibitively slow.
Cheers,
 Ruben

**Comment by iouribelikov** [comment]
@shahor02  Yes, the CheckDigits.C works.
These are the CheckClusters.C and CheckTracks.C that do not (resolutions and efficiencies). 

Anyway, this must be something trivial.  If there is anything still "in the pipe", I think we can merge this PR.   We could then open another one, fully devoted to fixes onside the test suite.

Cheers,
Yura.

**Comment by shahor02** [comment]
@iouribelikov : for me the CheckClusters.C also work, I put here https://cernbox.cern.ch/index.php/s/ucEglNW7BpcyFcP the version where I just modified the input file names according to o2sim conventions. If it works for you (just run it in top of previous commands), I can add it to the PR.

Cheers,
 Ruben

**Comment by iouribelikov** [comment]
@shahor02  Sorry.  It turned out my data files were not generated with the code from this PR :(

Now, everything seems to work.  Let's merge it !

Thank you very much and cheers,
Yura.

**Comment by shahor02** [comment]
@iouribelikov shall I add the CheckClusters with o2sim filenames convention to this PR. ?

**Pull request merged**
