### PR TITLE
DPL: add back a few tests

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by sawenzel** [comment]
Nice green CI.

**Comment by ktf** [comment]
Actually, there is a problem with fastsim, but I will close an eye for today... ;-)

**Comment by sawenzel** [comment]
FairRoot-dev it's not strictly required to pass

**Comment by ktf** [comment]
Which is a mistake and it still requires to click through the web pages, which according to your own words is a big bottleneck for some people.

**Pull request merged**
