### PR TITLE
Avoid exposing rANS internal details to ROOT

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This is probably the quickest way to fix it.

**Comment by davidrohr** [comment]
Yep, if this works sounds like the best solution to me.
Though I would still try to switch to something simpler than abseil, like robin hood, in any case.

**Comment by ktf** [comment]
@TimoWilken could you check how come the fullsystem test takes so long?

**Comment by TimoWilken** [comment]
@ktf Uploading the logs failed because they weren't valid UTF-8 apparently. I've just fixed that in ali-bot and set the fullCI status manually for this PR. The o2-cs8 check is still running, but almost done.

**Comment by TimoWilken** [comment]
Merged since all of the checks were green (except for the Intel Mac one, but that's a known problem and the compilation succeeded, at least).

**Pull request merged**
