### PR TITLE
macro to check geometry overlaps

### PR DESCRIPTION
**Pull request by sawenzel**

### CODE REVIEW

**Comment by sawenzel** [comment]
@shahor02 : Do you understand why the CI fails with  `Macro macro/run_trac_its.C should be tested` ? If have not touched (configuration of) this macro.

**Comment by davidrohr** [comment]
@sawenzel : Please rebase to dev, @pzhristov just disabled this failing test.

**Comment by sawenzel** [comment]
why should I rebase? The CI should do this, no?

**Comment by davidrohr** [comment]
O guess it would, but perhaps there was some kind of race condition between the PRs.

**Comment by shahor02** [comment]
Because it was removed from the tests w/o adding to list of macros not to be tested...
https://github.com/AliceO2Group/AliceO2/pull/3299#discussion_r404783853

**Comment by sawenzel** [comment]
Fine. But how did the original PR pass the CI in the first place?

**Comment by sawenzel** [comment]
There is something very weird going on here... I am now getting tons of merge conflicts

**Comment by sawenzel** [comment]
Closing in favour on new one #3302

**Comment by pzhristov** [comment]
It seems that my change it CMakeLists where I commented out the test did not trigger complete run of CMake and as a result the problem was not observed. Only a fresh build showed the error message:
CMake Error at cmake/O2ReportNonTestedMacros.cmake:80 (message):
  Macro macro/run_trac_its.C should be tested
Call Stack (most recent call first):
  CMakeLists.txt:103 (o2_report_non_tested_macros)
Sorry about this isssue, I did not know we had kind of duplication for the list of tests.

**Comment by davidrohr** [comment]
@pzhristov We have this O2ReportNonTestedMacros list to avoid that people just forget to add their macros to the tests :)

**Comment by pzhristov** [comment]
@davidrohr Yes, I learned it in a wrong way :)

**Pull request closed without merging**
