### PR TITLE
TPC: Make FileWriterSpec buffer data until all sectors received

### PR DESCRIPTION
**Pull request by wiechula**
Using multiple decoders it happens that data from different time frames
are received intermixed. To avoid wrong writing a wrong order to the
file, the data is buffered and only written once data from all sectors
are received.

### CODE REVIEW

**Comment by davidrohr** [comment]
I assume this is a TPC internal writer for krypton data? For normal TPC digits / clusters, the general logic should actually make sure to receive clusters for all sectors for the same TF at a given time.

**Comment by wiechula** [comment]
Yes, this is a writer for special krypton raw data. How is it done for the general data flow, that the data of the same TF arrive? I didn't find this.

**Comment by wiechula** [comment]
@shahor02 , @davidrohr , can this be merged?

**Comment by shahor02** [comment]
> How is it done for the general data flow, that the data of the same TF arrive? I didn't find this.

Does not  TPCSectorCompletionPolicy (which you use also in tpc-krypton-clusterer) provide this ?

**Review by shahor02 — APPROVED** [review]

**Comment by wiechula** [comment]
> > How is it done for the general data flow, that the data of the same TF arrive? I didn't find this.
> 
> Does not TPCSectorCompletionPolicy (which you use also in tpc-krypton-clusterer) provide this ?

It seems not. Perhaps I use it in the wrong way...

**Comment by davidrohr** [comment]
I think TPCSectorCompletionPoicy should do this, if you use it in the right way. Just loading the policy will not work, you have to configure it for which inputs it is active.
See Line 759 in GPUWorkflowSpec.cxx:
```
auto createInputSpecs = [&tpcsectors, &specconfig, policyData]() {
```
and check how policyData is used.

**Pull request merged**
