### PR TITLE
Do not limit number of entries RootTreeWriter can store

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by bazinski** [comment]
Hi @shahor02 
I made the assumption of only a singular entry in the trees to do mc to raw, I assume this will have to be fixed as well :-( 
Will fix later.
Sean

**Review by bazinski — APPROVED** [review]

**Comment by shahor02** [comment]
@bazinski Results of digitization are always stored as a single entry in the tree, regardless the time interval or number of collisions covered. MC->raw chops it to as many TFs as needed according to TF parameters definition.
Then, where reconstructing multiple TFs, result of each TF processing is stored as a single entry in the decoded/reconstructed object trees. If you set the number of expected events to 1 in the MakeRootTreeWriter, you will lose all by the 1st TF.

**Comment by bazinski** [comment]
@shahor02 Ah ok, I misread the change, I thought the trees would have multiple entries. The rest of the code in the mc to raw thing does as you say above.

**Comment by shahor02** [comment]
@bazinski The trees will have as many entries as the number of TFs processed upstream. There is no need to set N events in advance, the tree will be automatically closed once the end-of-stream is issued by upstream device.

**Pull request merged**
