### PR TITLE
[EMCAL-830] Recalibrator workflow for EMCAL cells

### PR DESCRIPTION
**Pull request by mfasDa**
Applying cell level calibrations
- Bad channel masking
- Cell time
- Absolute energy
Calibrations can be enabled and disabled one-by-one
(default: all enabled). Input and output specs mut be
specified by the user. Calibration objects are taken from
teh CCDB.

### CODE REVIEW

**Comment by mfasDa** [comment]
Needs #9740

**Comment by mfasDa** [comment]
For the CCDB access I use now a similar approach as what is implemented in the GRPRequest. The main motivation for this is to allow for static CCDB objects, mainly for testing purpose, to bypass the CCDB query and load files statically in the init function, otherwise the ccdb request is delegated to finalizeCCDB.

**Comment by mfasDa** [comment]
Case sensitivity fixed

**Comment by shahor02** [comment]
@mfasDa the fillCI failure is genuine

**Comment by mfasDa** [comment]
Missing bracket issue fixed, should be the last remaining issue from the codechecker.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
