### PR TITLE
DPL: workaround Ubuntu libc bug

### PR DESCRIPTION
**Pull request by ktf**
Apparently something is wrong with Ubuntu handling of SIGUSR1 since
the recent libc update. This works around things to work, but I am
still not clear why.

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo I Have No Mouth, and I Must Scream.

**Comment by mkrzewic** [comment]
is it not something trivial like inherited handler from some parent? (say init, session manager, shell or sth?)

**Comment by ktf** [comment]
@mkrzewic frankly speaking, I have problems believing it's a libc issue myself. As far as I can tell, there is no signal handler in the shell itself (`trap -p SIGUSR1` is empty) and the handler is there (and it works on every other platform...). I have no real explanation, just a workaround.

**Comment by ktf** [comment]
Better way to handle this is now coming.

**Pull request closed without merging**
