### PR TITLE
TPC: update Cluster QC

### PR DESCRIPTION
**Pull request by wiechula**

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken looks like all the builders have an error. What happened?

**Comment by davidrohr** [comment]
Apparently there were some cern-wide network errors that broke a lot. All CIs are reported as failed right now.

**Comment by ktf** [comment]
Actually the new machines were misconfigured. I will report what happened tomorrow.

**Comment by wiechula** [comment]
@davidrohr , @shahor02 , the `o2-cs8` error seems unrelated. Can this be merged?

**Pull request merged**
