### PR TITLE
Bump trackextra table to the latest version

### PR DESCRIPTION
**Pull request by maciacco**
@mpuccio @ddobrigk  could you have a look please?

### CODE REVIEW

**Review by mpuccio — DISMISSED** [review]
LGTM! Thanks a lot Mario!

**Comment by mpuccio** [comment]
+async-label async-2024-PbPb-apass1, async-2024-ppRef-apass1

**Comment by ddobrigk** [comment]
Thanks a lot @mpuccio , looks good to me!

**Review by pzhristov — APPROVED** [review]

**Comment by ddobrigk** [comment]
@maciacco @mpuccio just for completeness and FYI, there was something very sneaky that I overlooked when I looked at this PR... see here the fix: https://github.com/AliceO2Group/AliceO2/pull/13799 (basically, equivalency declarations of A-B and B-C are not equivalent to declaring A-C equivalent I think)

**Pull request merged**
