### PR TITLE
Provide monitoring in O2Device

### PR DESCRIPTION
**Pull request by awegrzyn**
I'm not sure from where I could pick up channel metrics.
This is the code to do so:
```cpp
for (const auto& mi : fChannels) {
  for (const auto& vi : mi.second) {
    monitoring->sendGrouped(vi.GetChannelName(), {
      {(uint64_t) vi.GetBytesTx(), "BytesTx"},
      {(uint64_t) vi.GetBytesRx(), "BytesRx"},
      {(uint64_t) vi.GetMessagesTx(), "MessagesTx"}
      {(uint64_t) vi.GetMessagesRx(), "MessagesRx"}
    }); 
  }   
}
```

Remove `#include "options/FairMQProgOptions.h"` as soon as https://github.com/FairRootGroup/FairRoot/pull/745 is merged and new version of FairRoot released in `alisw`.

### CODE REVIEW

**Comment by awegrzyn** [comment]
@alibuild will fail as `dev` branch of Monitoring is required.

**Comment by matthiasrichter** [comment]
Would it be possible to add this as a monitoring plugin for FairMQ? Preumably API needs to be specified, but that would allow to have monitoring for every device channel just by adding a plugin rather than adding code to the devices.

Adding @dennisklein to discussion

**Comment by awegrzyn** [comment]
@matthiasrichter We had a discussion with @dennisklein and @MohammadAlTurany and the idea of having Monitoring Plugin API was rejected.

**Comment by matthiasrichter** [comment]
thanks for the info. so I guess there were good reasons. too bad.

**Comment by matthiasrichter** [comment]
Hi @awegrzyn, do you want to go on with this PR? https://github.com/FairRootGroup/FairRoot/pull/745 is merged, you can proceed with the TODO list. Does this PR require a change in alidist? The CI checks are failing, packages `Configuration` and `Monitoring` could not be found.

**Comment by awegrzyn** [comment]
Hi @matthiasrichter,
Indeed I'd like to progress with it, I've been waiting for a review from @ktf 
The test are failing because the `dev` branch of Monitoring is required. I'll merge `dev` into `master` as soon as this PR is reviewed (no changes in alidist are required).

**Comment by awegrzyn** [comment]
@ktf @matthiasrichter @Barthelemy Could you please merge?

**Comment by sawenzel** [comment]
Merging since @ktf approved.

**Pull request merged**
