### PR TITLE
o2-ft0-digi2raw executable with cfg generation + options

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
OK for me, thank you.
 my button in Reviewers does not work, so i can not press it.

**Comment by shahor02** [comment]
OK, will merge it once macOS test (seems to be stuck) will pass

**Comment by mslupeck** [comment]
@shahor02 
Does it help you if any of the other code owner presses the 'approve' button? Or can you merge even without it? Also my button works and I see Alla is also the code owner. Any ideas why it doesn't work for her?

**Comment by shahor02** [comment]
@mslupeck Yes, I can merge w/o approval, still it is good for the code owner to comment if the changes are ok. But I don't know why Alla's button is not active....

**Pull request merged**
