### PR TITLE
Remove StripPatterns: only use ColumnData

### PR DESCRIPTION
**Pull request by dstocco**
Improve organisation of the basic data format for MID

### CODE REVIEW

**Comment by dstocco** [comment]
Hi all,
a gentle reminder for this PR, awaiting treatment since Jul 17.

Thanks in advance!
Cheers,
Diego

**Comment by shahor02** [comment]
To me it looks ok.
Cheers,
 Ruben

**Comment by dstocco** [comment]
Hi @shahor02 ,
thanks for the answer!
@dberzano : can this be merged?

Thanks!
Cheers,
Diego

**Comment by dberzano** [comment]
Error's unrelated.

**Pull request merged**
