### PR TITLE
add cluster pattern to TOF chi2

### PR DESCRIPTION
**Pull request by noferini**
@njacazio (as watcher)

### CODE REVIEW

**Comment by noferini** [comment]
This is an example of how the new o2match* output look like
pattern=0 -> single hit
pattern=1 -> double hit along Z
pattern=2 -> double hit along X
pattern=3 -> multiple hits with both X and Z

image

**Comment by noferini** [comment]
Dear @shahor02 ,
we are ready for the review of this PR.
Cheers,
Francesco

**Comment by ddobrigk** [comment]
Hi @noferini, @njacazio , I would prefer if we did not encode many variables inside an existing analysis data model field (the chi2) like this. I understand you want to keep backwards compatibility, but it is exactly because of backwards compatibility that we introduced versioning in O2/O2Physics. I also understand that the current versioning system may be suboptimal due to the necessity of hand-placed converters, but in that sense, it's best if we improve the existing versioning system instead of merging many pieces of information in one variable to provide backwards compatibility by hand. The data model risks becoming very unintuitive and the getter will return a very confusing variable for the average user who might want to explore variables in the future for general-purpose use. 

For now, I would still consider simply adding a data column (which ones and how they are organized I leave to you) and then having a converter. We can (and should) discuss this in one of the upcoming WP4+14 meetings. Tagging also @ktf for the developoment of an improved versioning system in which converters do not need to be explicitly added. Thank you!!

**Comment by shahor02** [comment]
I would agree with @ddobrigk

**Comment by noferini** [comment]
Hi,
I did it in this way to avoid to introduce any new variable in AO2Ds.
At the moment TOF is storing just a float per track into AO2Ds (chi2).
If I add another variable (e.g. a int) I would double the size used by TOF in AO2D.
I have no preference, but it would be nice to have this info into AO2D.

**Comment by noferini** [comment]
As discussed we will propose a different solution (to be discussed at WP4/14 meeting)

**Pull request closed without merging**
