### PR TITLE
ATO-615 - TimeSeries increase number of bins in phi, and decrease multiplicity range

### PR DESCRIPTION
**Pull request by miranov25**
### Goal - Enhancements to Analytical Fits and Calibration:

- **Space Charge Distortion Analysis:** Introduces analytical fits to evaluate distortions caused by variations in the chamber space charge, focusing on issues in sector A11 and other chambers (trips recovery)

- **Calibration from Sector Boundaries:** Implements methods to calibrate space charge effects directly from sector boundaries, enhancing precision.

- **Multiplicity Granularity Enhancement:** Extends multiplicity granularity to cover proton-proton (pp) collisions, ensuring finer detail and broader applicability.

These improvements aim to refine the accuracy and applicability of space charge distortion analyses and calibrations, supporting more detailed studies in varied collision environments.

### CODE REVIEW

**Comment by miranov25** [comment]
+async-label async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2, async, 2022-pp-apass4
,async-2022-pp-apass4-accepted
,async-2022-pp-apass6-2023-PbPb-apass2-accepted
,async-2023-pbpb-apass3-accepted
,async-2023-pbpb-apass4-accepted
,async-2023-pp-apass4
,async-2023-pp-apass4-accepted
,async-2024-pp-apass1
,async-2024-pp-apass1-accepted
,async-2022-pp-apass7
,async-2022-pp-apass7-accepted
,async-2024-pp-cpass0
async-2024-pp-cpass0-accepted

**Comment by miranov25** [comment]
+async-label async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6-2023-PbPb-apass2, async, 2022-pp-apass4,async-2022-pp-apass4-accepted, async-2022-pp-apass6-2023-PbPb-apass2-accepted, async-2023-pbpb-apass3-accepted, async-2023-pbpb-apass4-accepted,  async-2023-pp-apass4,async-2023-pp-apass4-accepted, async-2024-pp-apass1,async-2024-pp-apass1-accepted, async-2022-pp-apass7,async-2022-pp-apass7-accepted
,async-2024-pp-cpass0
async-2024-pp-cpass0-accepted

**Comment by miranov25** [comment]
Hello @wiechula 

Can you approve it so we will have it in the next itteration for the apass4 and for the pp productions

**Review by wiechula — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @miranov25 , 

This is needed for both data and MC? 
I would remove the apass4 pp 2022 and apass6 pp 2022 labels, since now we are doing apass7. 

Note that the PR was merged *after* 12 pm of today, which is the deadline (Wed @12 pm) for every week tags, so in principle it will be taken next week... @benedikt-voelkel , what do you think?

Chiara

**Comment by benedikt-voelkel** [comment]
Hello @chiarazampolli, yes, we can (and probably should) remove the labels you are mentioning.
Then, concerning the time it was merged: Yes, in principle it would now be taken next week. But I can see that it really only touches `Detectors/TPC/workflow/src/TPCTimeSeriesSpec.cxx`.
For me it would be okay to include it this time but in the future we would move it to the next week.

**Comment by miranov25** [comment]
Hello @chiarazampolli , @benedikt-voelkel  and all.

The sooner we have this in production, the more data we will be able to calibrate for modifications in space charge density, fluctuations in epsilon, and sector edges. Therefore, I would prefer to have it implemented as soon as possible.

I will soon post a time series summary to the WP12 and WP13 groups as a motivational example.

Marian

**Comment by chiarazampolli** [comment]
Cherry-picking to async-2022-pp-apass4 does not work. Since apass4 is deprecated, I remove the label.

**Comment by chiarazampolli** [comment]
Same for apass6 pp 2022 and PbPb 2023 apass2.

**Pull request merged**
