### PR TITLE
Split and updated documentation about code organisation and cmake.

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by Barthelemy** [comment]
Not sure how my changes can have broken anything...

**Comment by ktf** [comment]
No, I think it's an actual missing dependency.

**Comment by Barthelemy** [comment]
I have not touched any code, I have split a markdown file into two. I don't think that I can have broken anything.

**Comment by ktf** [comment]
no, it's not your code, but I think we have a missing dependency which gets spotted when we compile with clang.

**Pull request merged**
