### PR TITLE
Improve CMake testing (O2-499)

### PR DESCRIPTION
**Pull request by dberzano**
Following discussions in WP3, tests are now wrapped by a script that handles
timeouts and retries. Retries are not handled by native CTest. It is possible to
ignore failures if some test has failed because of a timeout (not a CTest
feature either).

A separate logfile for each test is kept in the build directory. At the end of
each test, the logfile is renamed to include the exit code in the file name.
This makes it possible for the external process driving the build (alidist
recipe, aliBuild, the C.I.) to keep logfiles and make them available even in
case of success for further investigation. Timing out processes will have their
stack trace collected before they are killed.

### CODE REVIEW

**Comment by sawenzel** [comment]
Very nice. Just one thought: Will there be any sort of automatic notification (or comment) if a test did time-out? Otherwise there might also be the danger that we gradually forget about the time-out problem.

**Comment by ktf** [comment]
+1

Can we have core dumps as well as discussed for failed tests? Alternatively could you attempt sending a SIGUSR1 (`timeout -sSIGUSR1` IIRC) the first time you timeout, so that I can have an handler which dumps a stack trace for all threads?

**Comment by dberzano** [comment]
@sawenzel yes, that's the idea, but it can't be done here (we have to slightly adapt the C.I.): I wanted to leave this PR open until the proper changes are done in the C.I. as well.

@ktf yes, that's again the idea. Note that `SIGUSR1` is probably not a general way to do it: does FairMQ trap and implement it as "print stacktrace"? In general if `SIGUSR1|2` are unhandled by the application, [the default action is to terminate it](https://www.gnu.org/software/libc/manual/html_node/Miscellaneous-Signals.html) (which is sort of what we want).

Anyway I am going to work on:

- [ ] Producing process info before killing (core/stacktrace)
- [ ] Making build information available on "success" as well

**Comment by ktf** [comment]
I plan to implement dump stack trace on SIGUSR1 in DPL and will then propose it for FairMQ adoption.

**Comment by ktf** [comment]
BTW, can we organise a campaign to cleanup the check code issues? Splitting the work between 5 of us should allow to converge quite quickly.

**Comment by sawenzel** [comment]
@dberzano : There is a merge conflict now. Please let me know if I can help resolving them.

**Comment by dberzano** [comment]
I have noticed. Once solved, I think we can merge this - there is everything we have discussed about (timeouts, stack traces, logs visible on success). Further improvements can be done later on.

**Comment by sawenzel** [comment]
G4 is now failing. Not sure why. Do you kill the process after 10s only? (Geant4 needs a bit more time to setup everything.)

**Comment by dberzano** [comment]
@sawenzel so we have two failing tests: `o2sim_G4_mt` and `o2sim_G4`. Tests are timing out, the time out is set as non-fatal (expicitly), however a regular expression is used to check its output. My new attempt is to add `MAX_ATTEMPTS 3` for those tests (to allow retry), and to specify `RUN_SERIAL` in order to prevent them from running in parallel with any other test. Let's see if this helps.

It is obviously important that _this_ PR is fully green before merging 😄

**Comment by dberzano** [comment]
@sawenzel  OK sorry I have commented without noticing your message. Timeout is 100 seconds by default. After that time, `SIGTERM` is sent. If the process does not respond to this trappable signal, after 10 _more_ seconds, `SIGKILL` is sent.

How much time do you need for G4? We can increase the value on those tests.

**Comment by dberzano** [comment]
`[INFO] Simulation process took 120.255 s` ==> I am increasing the timeout for G4 to 200.

**Comment by dberzano** [comment]
@sawenzel all green here finally

**Comment by sawenzel** [comment]
Good. Ready to go then.

**Pull request merged**
