### PR TITLE
AOD: Add thinner option to producer

### PR DESCRIPTION
**Pull request by f3sch**
The idea is produce thinner AO2Ds directly and agnostically to the data model (in contrast to the `aod-thinner`).

### CODE REVIEW

**Comment by ddobrigk** [comment]
Thanks a lot @f3sch ! It would be great if we could move this to review. This PR might be particularly useful to incorporate (of course if tested-and-true) for the Pb-Pb apass4, where it would reduce data volume from ~3.6PB to ~1.8PB and free enough disk for us to keep at least 2022 thinned pass4 pp AO2Ds on disk for longer - to be discussed

**Comment by ddobrigk** [comment]
+async-label async-2023-pbpb-apass4

**Comment by ddobrigk** [comment]
Thanks to @f3sch , this has now been fully debugged - Felix has tested this to work fine and I have also conducted independent testing on MC AO2Ds as well. It is ready to be merged

**Comment by ddobrigk** [comment]
Good evening everyone, this has passed all checks and is ready to be merged. Can we please carry on? Thanks a lot! Tagging @chiarazampolli @alcaliva @noferini @ktf @shahor02

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
