### PR TITLE
DPL: allow decoupling from JAlien and retrieve JAlienFile, if available

### PR DESCRIPTION
**Pull request by ktf**
This moves the file reading in a plugin like shared library, so that we do not need to have everything depend on JAlien.

### CODE REVIEW

**Comment by ktf** [comment]
@costing @Atlantic777 @aphecetche I've not been able to convince CMake to add the JAlien include / link paths, though. Is that actually possible at all?

**Comment by ktf** [comment]
Ok, looks like I somehow managed by working it around on the O2 side. @aphecetche could you crosscheck? @costing / @Atlantic777 can we have some work allocated to have a proper CMake module for JAlien?

**Comment by ktf** [comment]
@jgrosseo this should allow you to retrieve whatever information is needed by Hyperloop for the file stats. The lines you can hook into is https://github.com/AliceO2Group/AliceO2/pull/5073/files#diff-9e3354c94a571c4eeb0e41d2a6f49b23ffe0a74cd38dd87a07cef1d1f67e2553R305.

**Comment by ktf** [comment]
We probably need some changes in alidist/o2.sh as well, but first we need this one merged.

**Comment by jgrosseo** [comment]
Thanks!

**Comment by aphecetche** [comment]
@ktf I've had a quick look at the cmake parts, and they look reasonable. 

It's just a pity that we have to provide FindXXX.cmake files because those packages are not cmake friendly and do not provide relevant cmake config files :-(

**Comment by ktf** [comment]
@aphecetche thanks and agreed it's a pity, although given the amount of complications getting a config file in CMake requires, I am not surprised...

**Pull request merged**
