### PR TITLE
Compile against FairMQ 1.3.6

### PR DESCRIPTION
**Pull request by mkrzewic**
This is the bare minimum to make it chooch. There will be another PR that will integrate the new memory_resource stuff that got merged in FairMQ (thus removing most of the current O2 implementation).

### CODE REVIEW

**Comment by sawenzel** [comment]
I think the first step would be to get a compiling o2-dev-fairroot. Can we bump the versions there first?

**Comment by sawenzel** [comment]
@mkrzewic : Can you please fix the clang-format errors?

**Comment by dberzano** [comment]
Hi @mkrzewic, so thanks to alisw/alidist#1378 the deprecation warnings are gone in o2-dev-fairroot. We still have this error as you can see from the details:

```
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx: In member function 'virtual void O2MessageMonitor::Run()':
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx:61:90: error: invalid conversion from 'const FairMQTransportFactory*' to 'FairMQTransportFactory*' [-fpermissive]
   auto dataResource = o2::memory_resource::getTransportAllocator(subChannels[0].Transport());
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~^~
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Utilities/O2Device/include/O2Device/Utilities.h:30:0,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Utilities/O2Device/include/O2Device/O2Device.h:33,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Utilities/O2MessageMonitor/include/O2MessageMonitor/O2MessageMonitor.h:31,
                 from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Utilities/O2MessageMonitor/src/O2MessageMonitor.cxx:33:
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/DataFormats/MemoryResources/include/MemoryResources/MemoryResources.h:413:32: note:   initializing argument 1 of 'o2::memory_resource::ChannelResource* o2::memory_resource::getTransportAllocator(FairMQTransportFactory*)'
 inline static ChannelResource* getTransportAllocator(FairMQTransportFactory* factory)
                                ^~~~~~~~~~~~~~~~~~~~~
```

**Comment by mkrzewic** [comment]
cannot reproduce, I suspect you're not compiling against fairmq 1.3.6 ?

**Comment by sawenzel** [comment]
@mkrzewic : Which version/commit of FairRoot is compatible with this? Just in order to test it locally.

**Comment by sawenzel** [comment]
@mkrzewic : I was talking about FairRoot. There doesn't seem to be a version 1.3.6 in FairRoot.

**Comment by mkrzewic** [comment]
ah fairroot version does not matter for this patch. However i'm using c672f280

**Comment by ktf** [comment]
I am fixing the SFINAE right now.

**Comment by ktf** [comment]
#1462 should fix the error. Once that is merged the dev-fairroot test of this one should become green.

**Comment by mkrzewic** [comment]
@ktf that would be great, but here i dont really see how a fix in a different, independent module would fix this?

**Comment by ktf** [comment]
#1462 should make my code work in both 1.2.x and 1.3.x, so if we look at `o2-dev-fairroot` which is basically 1.3.x, my PR + yours should be green. If that is the case we can safely move from 1.2.x to 1.3.x in alidist and forget about 1.2.x.

**Comment by ktf** [comment]
If you rebase and push again we should speed up the test retrial.

**Comment by ktf** [comment]
Ok, seems we still have a few issues with boost and ROOT...

**Comment by ktf** [comment]
Nope, sorry. Maybe we need some `#ifndef __cling__` in a few places?

**Comment by dberzano** [comment]
It does compile. Tests fail. Can you recompile (with aliBuild) after exporting `ALIBUILD_O2_TESTS=1`?

**Comment by dberzano** [comment]
We have the following error during the tests:

```
In file included from G__TPCSimulationDict dictionary payload:21:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_O2_o2-dev-fairroot/0/Detectors/Base/include/DetectorsBase/Detector.h:30:
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/FairMQ/dev-17/include/fairmq/FairMQChannel.h:19:
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/FairMQ/dev-17/include/fairmq/FairMQTransportFactory.h:17:
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/FairMQ/dev-17/include/fairmq/MemoryResources.h:21:
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.68.0-9/include/boost/container/flat_map.hpp:29:
In file included from /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.68.0-9/include/boost/container/detail/flat_tree.hpp:29:
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.68.0-9/include/boost/container/detail/pair.hpp:132:89: warning: invalid memory pointer passed to a callee:
static piecewise_construct_t piecewise_construct = BOOST_CONTAINER_DOC1ST(unspecified, *std_piecewise_construct_holder<>::dummy);
                                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/boost/v1.68.0-9/include/boost/container/detail/workaround.hpp:71:46: note: expanded from macro 'BOOST_CONTAINER_DOC1ST'
#define BOOST_CONTAINER_DOC1ST(TYPE1, TYPE2) TYPE2
                                             ^~~~~
```

The solution to this problem does not seem so trivial, I have actually tried some `#ifdef` here and there as suggested but to no avail.

@mkrzewic: the code triggering ROOT's complaints is in FairMQ, and it seems to be yours. Can you have a look please?

This is essentially the only big thing that's preventing us from releasing O2 v1.0 😢

**Comment by mkrzewic** [comment]
looks like root cannot parse the boost headers, no idea how to solve it atm. will have a deeper look tomorrow, I'm able to reproduce this now thanks to @dberzano

**Comment by sawenzel** [comment]
Looking at CI output, I can't see the described error. Rather I spot the following:
```
error: cannot initialize a parameter of type 'FairMQTransportFactory *' with an rvalue of type 'const FairMQTransportFactory *'
  auto dataResource = o2::memory_resource::getTransportAllocator(subChannels[0].Transport());
```
Am I missing something?

**Comment by sawenzel** [comment]
@mkrzewic , @dberzano : I will refactor the code today to get rid of those header includes.

**Comment by sawenzel** [comment]
https://github.com/AliceO2Group/AliceO2/pull/1464 will solve the mentioned problems in detector code.

**Comment by dberzano** [comment]
With #1464 and #1465 merged, and this PR rebased (I just did it) we should finally see the `o2-dev-fairroot` test green, hopefully.

Note that we expect the `o2` and `macos` tests to fail.

As soon as the test is green, we can finally merge https://github.com/alisw/alidist/pull/1363 as well.

**Comment by dberzano** [comment]
It seems there is one last error to fix:

```
In file included from input_line_10:1:
/mnt/mesos/sandbox/sandbox/O2/Utilities/MCStepLogger/src/analyseSteps.C:24:82: error: no type named 'StepLookups' in namespace 'o2'
void volidTovolnameHist(std::vector<T> const &v, std::map<std::string,T> &m, o2::StepLookups *l){
                                                                             ~~~~^
/mnt/mesos/sandbox/sandbox/O2/Utilities/MCStepLogger/src/analyseSteps.C:75:6: error: no type named 'StepLookups' in namespace 'o2'
 o2::StepLookups *lookup =nullptr;
 ~~~~^
/mnt/mesos/sandbox/sandbox/O2/Utilities/MCStepLogger/src/analyseSteps.C:79:18: error: no member named 'StepInfo' in namespace 'o2'
 std::vector<o2::StepInfo> *steps = nullptr;
             ~~~~^
/mnt/mesos/sandbox/sandbox/O2/Utilities/MCStepLogger/src/analyseSteps.C:79:29: error: C++ requires a type specifier for all declarations
 std::vector<o2::StepInfo> *steps = nullptr;
                            ^
/mnt/mesos/sandbox/sandbox/O2/Utilities/MCStepLogger/src/analyseSteps.C:83:18: error: no member named 'MagCallInfo' in namespace 'o2'
 std::vector<o2::MagCallInfo> *calls = nullptr;
             ~~~~^
/mnt/mesos/sandbox/sandbox/O2/Utilities/MCStepLogger/src/analyseSteps.C:83:32: error: C++ requires a type specifier for all declarations
 std::vector<o2::MagCallInfo> *calls = nullptr;
```

**Comment by dberzano** [comment]
OK I came to the same conclusion and verified it as well. We indeed have `libMCStepLogger.so` twice, and I think the one from FairRoot should be renamed.

Let's proceed, and tag. Note, this is quite disruptive and requires bumping alidist. I'll try to do that quickly (with proper double-testing first).

**Comment by sawenzel** [comment]
for the record: https://github.com/FairRootGroup/FairRoot/pull/846

**Pull request merged**
