### PR TITLE
FairRoot::Detector::fDetId will be assigned from det.name

### PR DESCRIPTION
**Pull request by shahor02**
Modified Detector constructor to take predefined name and assign FairRoot::Detector::fDetId automatically via DetID class.

Eliminated DetectorList class. Detector ID (in methods like Stack::AddPoint(detID) will be taken directly from FairDetector::GetDetId().

@sawenzel , @mario6829 , @iouribelikov , @bovulpes , @mfasDa , @noferini , @wiechula, note that I've removed the det. name from the XXX/Detector constructor arguments, now it is hardcoded in the initialization of the base FairDector, and must necessarily correspond to one of the predefined det.names in DetID class (checked by assert). @mfasDa, since all detector name are 3 letters long, the EMCAL becomes EMC. 

@sawenzel, I've added AddPoint... to all detectors, like it was for ITS and TPC. If we decide we don't use this functionality (the implementation of MCTrack::getNumberOfPoints(int detId) is dummy at the moment), then we should remove it for all detectors.

### CODE REVIEW

**Comment by sawenzel** [comment]
@shahor02 : Thanks for this PR. 
I am wondering:
a) why detector names need to be exactly 3 characters? I find this a somewhat unnecessary inconvenience.
b) if we could check at compile time that a detector name is invalid rather than using runtime assert?

**Comment by mkrzewic** [comment]
@sawenzel the detector names are at most 3 characters + terminating null because this is what we use in the O2 headers - the idea was that there is defined consistently. An other thing is that I think best practice would be to avoid explicit use of those strings anywhere - would be best to use (typed) constants...

**Comment by sawenzel** [comment]
Well, we could have a human readable name and a unique 3letter code at the same time. I find using just 3letter codes restricting.

@shahor02 : We also need to address cases in the simulation with detector elements which are not actually producing hits but which need a stepping action (for instance to kill particles); These things are currently also coded as a BaseDetector but it would be hard to satisfy the DetID requirement. Maybe we need another class specialization.

**Comment by sawenzel** [comment]
So what about adding an "PASSIVE" detectorID as well as allowing long names as human readable names?
I would then impose the following constraints:
a) there can be multiple passive detectorID
b) there can be only one of the rest active detectorIDs

**Comment by ktf** [comment]
Shouldn't PASSIVE actually encoded in some "sub specification" (in DataModel-speak), rather than the name? Why would you use it as part of the detector name?

**Comment by sawenzel** [comment]
@ktf: I did not say it should be part of name. It is a property and maybe we could map each passive detector to one single DetID (instead of having to make DetectorID for magnet, absorber,  beampipe, dipol, hall, etc).

**Comment by mkrzewic** [comment]
@sawenzel why would the human readable names be char strings? Is it not better to avoid typo's and ambiguities using something typed like enums?

**Comment by shahor02** [comment]
@sawenzel: 3-letter names is the matter of convention, if we agree to allow longer ones, can change this easily. As for the static_assert check: I did not manager to make the DetID(const* char) constructor constexpr, it complains about undefined symbol when such constructor is used. Can dig more.
Do we have passive modules which have step manager?

@mkrzewic: to avoid using strings in the constructors, I can substitute them by DetID(id).getName(), though this will not work for passive modules if we don't have one to one name<->id mapping for them.

Concerning the passive property, I did not check the code, but is not it dynamic? I.e. if the TOF is not in data takings, we still create but the step manager is not called in simulation? If this is not the case, then I would simply remove it from the constructor.

**Comment by sawenzel** [comment]
@shahor02: By passive I mean purely non data-taking  parts of our detector such as exp. hall, etc. Sometimes it makes sense to have a Stepping manager for these classes too (for example to kill useless particles, etc.). So the only way I can do this at the moment is to use o2::Base::Detector which would now require to have an DetID for exphall.

This just means that we need to think a little how we want to cope with such situations. A further distinction/subclassing of DataTakingDetector and PassiveSteppingDetector might be a solution.
Then a DataTakingDetector must satisfy the requirements for data sources and data formats.

**Comment by dberzano** [comment]
@ktf @pzhristov it seems to me from this test that High Sierra + Xcode 9 are not happy with ROOT v6.10/06, am I mistaken?

**Comment by ktf** [comment]
Looks like one more `.Data()` to add

**Comment by dberzano** [comment]
Testing alisw/alidist#869.

**Comment by dberzano** [comment]
Note that the error is unrelated and it will be fixed when #603 is merged. The macOS builder is back again with High Sierra and Xcode 9.

**Comment by sawenzel** [comment]
Merging this for now as big advancement. Some adjustments might have to be done later for passive non-data taking detectors with stepping actions.

**Pull request merged**
