### PR TITLE
TPC SCD outlier filtering refactoring

### PR DESCRIPTION
**Pull request by martenole**
Outlier filtering is moved from TrackResiduals to TrackInterpolation class in order to allow for setting the maximum number of successfully processed tracks.
Some functionality is removed which allowed to process converted residuals from Run 2. This adds some cleaner separation. TPC cluster residuals are collected in TrackInterpolation. TrackResiduals is for creating the average map from these residuals.
Also added some reader/writer for unbinned residuals to run the aggregator in a standalone mode.

### CODE REVIEW

**Comment by martenole** [comment]
https://github.com/AliceO2Group/AliceO2/pull/10048/commits/0a499ec2698973cc32aa9dc85e6d6f2929416d8a allows to set the compression externally. It turns out that a significant amount of CPU cycles is spent on compression. Unfortunately, already with the fastest compression setting (ZLIB, compression level 1, corresponding to setting 101, the default) the processing gets rather slow. Without compression the processing time should become negligible. I would propose to test without compression at P2. If that works, I have to add a second stage which does the compression before the file is transferred to EOS.
Data sizes:
```
-rw-r--r-- 1 oschmidt oschmidt 9,5M oct.  12 21:00 compression-101.root
-rw-r--r-- 1 oschmidt oschmidt 7,2M oct.  12 21:02 compression-207.root
-rw-r--r-- 1 oschmidt oschmidt 8,8M oct.  12 21:01 compression-505.root
-rw-r--r-- 1 oschmidt oschmidt 9,5M oct.  12 20:47 compression-default.root
-rw-r--r-- 1 oschmidt oschmidt  15M oct.  12 20:46 compression-OFF.root
```
Processing speed with default (level 101):
```
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 2 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 4 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 3 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 1 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 5 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 6 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 3 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 1 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 5 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 1 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 3 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 4 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 4 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 2 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 2 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 2 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 2 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 1 ms. From this taken for time dependent param update: 0 ms
[103229:residual-aggregator]: [21:00:17][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
```
And without compression:
```
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
[101554:residual-aggregator]: [20:46:01][INFO] Duration for run method: 0 ms. From this taken for time dependent param update: 0 ms
```
For some CTFs from run 526937

**Comment by shahor02** [comment]
@martenole makes sense, though still it is not clear why the operation taking ~3ms on average creates a backpressure. 
Perhaps you should add optionally a few timer printouts at different steps.

**Comment by martenole** [comment]
Ok, I have added timers to emplacing new slotes and finalizing slots, since I have seen that the duration for `run()` increased a lot when slots were closed or new ones were added

**Comment by martenole** [comment]
TPC-SCD-scheme
Just adding this image here so that I can use it in a README file

**Pull request merged**
