### PR TITLE
DPL: fix inputs in GUI

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @shahor02 here is the fix for the missing inputs.

**Comment by ktf** [comment]
For the record, the GUI broke due to 05ca63298d98df124d9d295ad4a3c639f3e005e9 which commented out the metric sending.

**Comment by davidrohr** [comment]
> For the record, the GUI broke due to [05ca632](https://github.com/AliceO2Group/AliceO2/commit/05ca63298d98df124d9d295ad4a3c639f3e005e9) which commented out the metric sending.

uhm, I am very sorry. Not sure how that commenting out made it into that PR.....
Could it be that back then you had asked me to disable the metric sending, since it was crashing?

**Comment by ktf** [comment]
No worries.  I suspect it was just the first one of things which broke with the new fmt, it got commented out, and then we forgot to fix it like it was actually done for other similar issues in the same PR.

**Pull request merged**
