### PR TITLE
PWGHF: Added D resonances to PhysicsConstants.h

### PR DESCRIPTION
**Pull request by Luca610**
This PR adds the PDGid and mass information of resonant D mesons in PhysicsConstants.h, generated through the script make_pdg_header.py 
@vkucera, @fgrosa , does it look ok to you?

### CODE REVIEW

**Comment by vkucera** [comment]
@Luca610 Looks good to me. Thanks

**Comment by fgrosa** [comment]
@ktf could you please approve it? Thanks!

**Review by ktf — APPROVED** [review]

**Comment by fgrosa** [comment]
Hi @shahor02 apparently the approval of @ktf was not enough (strange?), could you please approve this PR too? Thanks!

**Review by shahor02 — APPROVED** [review]

**Comment by vkucera** [comment]
> Hi @shahor02 apparently the approval of @ktf was not enough (strange?), could you please approve this PR too? Thanks!

@ktf is not a code owner of `/Common/Constants`, @shahor02 is:
https://github.com/AliceO2Group/AliceO2/blob/d0e3199e39b0ff2fb7262423d1f38402b86b126d/CODEOWNERS#L18

**Pull request merged**
