### PR TITLE
adding protection in tof-compressor

### PR DESCRIPTION
**Pull request by noferini**
@preghenella

### CODE REVIEW

**Comment by noferini** [comment]
I found another point I want to protect.
Let's wait a bit with this PR

**Comment by noferini** [comment]
All checks passed but macOs (as usual :))
Can we merge it as soon as possible? Then we will ask to have this PR at P2 since this is critical to recover full TOF acceptance in data acquisition.
If there are major concerns with this PR let me know.
In case of minor comment, please put them as comments but I will take care of them in a next PR since I'm going to travel
Changes were tested on several Pb-Pb raw/tf files (inclusing QC) and tests show that we recover errors in TF taken at peak luminosity

**Comment by shahor02** [comment]
@noferini I've added https://alice.its.cern.ch/jira/browse/O2-4261 to the ticket with the stuff to port: https://alice.its.cern.ch/jira/browse/O2-4108. Could you put some comments in the  https://alice.its.cern.ch/jira/browse/O2-4261

**Comment by noferini** [comment]
Sure. Thanks
Francesco

**Pull request merged**
