### PR TITLE
Verbosity options for ITS-TPC matching and entropy encoding/decoding

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Review by mslupeck — DISMISSED** [review]

**Comment by shahor02** [comment]
Hi @davidrohr , there is nothing in this PR mat.LUT or geometry related, but there were failures on the GPU:
```
123/379 Test  #34: GPU/GPUTracking/Standalone/tools/createLUT.C_compiled ................................***Failed   19.44 sec
--
132/379 Test  #33: GPU/GPUTracking/Standalone/tools/createGeo.C_compiled ................................***Failed   24.35 sec
```

**Comment by davidrohr** [comment]
```
Info in <TUnixSystem::ACLiC>: creating shared library /sw/BUILD/522a6fa81a214ff0403bab7eb782eb4fdec97aff/O2/compiled_macros//sw/SOURCES/O2/7509-slc8_x86-64/0/GPU/GPUTracking/Standalone/tools/createGeo_C.so
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-4/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot open output file /sw/BUILD/522a6fa81a214ff0403bab7eb782eb4fdec97aff/O2/compiled_macros//sw/SOURCES/O2/7509-slc8_x86-64/0/GPU/GPUTracking/Standalone/tools/createGeo_C.so: No such file or directory
collect2: error: ld returned 1 exit status
```
Puh, no idea, perhaps disk full? `Cannot open output file` sounds suspicious. I don't think it is related to the test itself.
@TimoWilken could you check the disk?

**Comment by TimoWilken** [comment]
> ```
> Info in <TUnixSystem::ACLiC>: creating shared library /sw/BUILD/522a6fa81a214ff0403bab7eb782eb4fdec97aff/O2/compiled_macros//sw/SOURCES/O2/7509-slc8_x86-64/0/GPU/GPUTracking/Standalone/tools/createGeo_C.so
> /sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-4/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot open output file /sw/BUILD/522a6fa81a214ff0403bab7eb782eb4fdec97aff/O2/compiled_macros//sw/SOURCES/O2/7509-slc8_x86-64/0/GPU/GPUTracking/Standalone/tools/createGeo_C.so: No such file or directory
> collect2: error: ld returned 1 exit status
> ```
> 
> Puh, no idea, perhaps disk full? `Cannot open output file` sounds suspicious. I don't think it is related to the test itself. @TimoWilken could you check the disk?

The disk has 18TiB available.

The file path it's trying to create looks very suspicious to me -- it's a `/sw/BUILD/.../O2/compiled_macros/` prefix with another absolute path `/sw/SOURCES/O2/...` concatenated onto it. Is a script expecting a relative path somewhere?

**Comment by shahor02** [comment]
> Is a script expecting a relative path somewhere?

The script is actually not executed, it is just compiled in the root by `.L createGeo.C+`

**Pull request merged**
