### PR TITLE
jobutils/taskwrapper: use fairmq-shmmonitor

### PR DESCRIPTION
**Pull request by sawenzel**
* parse DPL session id and use fairmq-shmmonitor for shared
  memory cleanup (in case this leaked). The solution based on
  lsof is deprecated.

* this enables also the possibility to monitor shared memory
  consumption (and report the max value)

### CODE REVIEW

**Comment by ktf** [comment]
Why parsing the session and not simply setting it? DPL does take `--session`.

**Comment by sawenzel** [comment]
I am not in control of people using taskwrapper so I can't be sure that session is set.

**Comment by sawenzel** [comment]
@ktf : I think if you printed out the session id in logs, it could make things a bit cleaner. Merging for now since actual improvement.

**Comment by ktf** [comment]
I can do that, but I still do not understand, the taskwrapper could simply add `--session <unique-taskwrapper-id>` to whatever it executes no?

**Comment by sawenzel** [comment]
But if the user already chose a particular session? I would still have to detect/parse it. That can eventually be done of course.

**Comment by davidrohr** [comment]
That would require some parsing first. The task wrapper can be used for non-fmq tasks. And also there might already be a session in the command line. And one would require some logic to generate a random session, since 2 taskwrappers might run in parallel. Personally, I'd rather keep the taskwrapper script simple.

**Comment by ktf** [comment]
> The task wrapper can be used for non-fmq tasks

Ok, I guess this is what I was missing, because if it was, you could simply pass the session as an argument.

**Pull request merged**
