### PR TITLE
Incremental histo merging

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo This should be what we discussed today. I did a quick test, without pipelining, and it seems to work with almost exactly the same datasize.
@aalkin @saganatt Could you cross check I am not doing something stupid? The idea is that now I send around the pipeline size, so I need to merge pipeline number histograms before I write to file. The only difference should be the order in which I write the branches (which now depends on the order of arrival of the messages) and hopefully the memory needed for the writing.

**Comment by aalkin** [comment]
I'm not sure what this does, we have discussed this, the merging does not actually happen, because all the histograms are sent once at the end of processing.

**Comment by ktf** [comment]
end of the processing for the sources but not for the sink. i did not check with pipelining, however it seems to work fine (and save a couple hundred MB) in the hyperloop test i did. let's discuss later today.

**Comment by jgrosseo** [comment]
@ktf Great! Is this in eulisse-local? Then I do a few tests myself. I can also do one with pipelining if you want...

**Comment by ktf** [comment]
@jgrosseo I discussed a bit with @aalkin. The incremental merging indeed can only happen when a given histogram is sent multiple times. This at the moment does not happen. Apparently until now pipelining histogram producing tasks was not supported so effectively my changes here will:

1. Write histograms as they come in, if there is no pipelining.
2. Wait for all the pipelined parts, merge them, and write the histogram when there is no more pipelined parts expected. Effectively this removes the limitation on on the pipelined tasks mentioned above.
3. Last but not least, there is actually a couple of memory leaks in the current recursive writing code. I think I have fixed them in https://github.com/AliceO2Group/AliceO2/pull/11818/commits/c881aacddc6354d5f199b96b9a9689eed25be39b but we should check carefully.

With this, we will lose the (unused) ability to send histograms incrementally. However, if this works fine, I think we should merge this and reimplement the dropped feature such that the source notifies with a similar mechanism when the last histogram is sent and the flushing to disk can happen.

If we decide that this set of changes is too aggressive or undesired, we should nevertheless fix the leaks as in https://github.com/AliceO2Group/AliceO2/pull/11818/commits/c881aacddc6354d5f199b96b9a9689eed25be39b because I suspect that's the main culprit.

Without this development (https://alimonitor.cern.ch/hyperloop/wagon-test/116914)

image

With this development (https://alimonitor.cern.ch/hyperloop/wagon-test/117021)

image

You can use eulisse-local to verify things further.

**Comment by aalkin** [comment]
My vote is for merging this, the incremental sending is not used and unless we change the internal representation of histograms from ROOT to something that has much lower serialization/deserialization cost we will not use it.

**Comment by ktf** [comment]
For the record, more than half of the remaining spike at the end is indeed the ROOT runtime which gets initialised only at that point.

**Comment by ktf** [comment]
I.e.
image

**Comment by jgrosseo** [comment]
Thanks a lot for this. I support merging it (once the pipelining actually works).

You write `Apparently until now pipelining histogram producing tasks was not supported `. I think this is incorrect. I have used it and it worked fine!

**Comment by aalkin** [comment]
If it is indeed worked, it was by accident, rather than by design. Because with histograms the order of merging is not important, we do not care from which dataframe each copy of the histogram has come.

**Comment by ktf** [comment]
I fixed the issue with the pipelining. PR bumped and I am rebuilding on hyperloop.

**Comment by ktf** [comment]
@sawenzel it looks like there is something wrong with the simulation:

```
258/491 Test #445: o2sim_G4 .............................................................................***Exception: SegFault214.17 sec
```

I see error messages about:

```
Error in <TGeoCompositeShape::MakeNode>: Expression has no boolean operation
Error in <TGeoCompositeShape::ctor>: Composite halfFixationToPipe: cannot parse expression: pipeSupportTubeCarbon
```

can you have a look?

**Comment by ktf** [comment]
I am merging this since it seems to work well. If there is any regression it should be easy to fix.

**Comment by ktf** [comment]
image

For the record the profile at the end now looks like this. The plateau is mostly ROOT overhead and the small spikes are the buffers.

**Pull request merged**
