### PR TITLE
Implementation of TOF calibration chain

### PR DESCRIPTION
**Pull request by noferini**
Implementation of TOF calibration chain:

- Calibration info accumulator during matching
- LHC phase computation
- channel offset computation
- timeslewing computation
- Calib Infos stored in dedicated structure (in view of a CCDB)

### CODE REVIEW

**Comment by noferini** [comment]
add @chiarazampolli

**Comment by noferini** [comment]
test comment for Chiara

**Comment by noferini** [comment]
Dears,
I checked all the tests and it seems to me that we fixed all errors related to our piece of code.
All the rest seems to be related to issues of others.
Cheers
Francesco

**Comment by sawenzel** [comment]
Can you please fix the remaining formatting problems?

**Comment by chiarazampolli** [comment]
They must come from some changes we did yesterday. We will take care asap, but they are not blockers for the review of the PR, are they?

Cheers,

Chiara

**Comment by chiarazampolli** [comment]
Ciao @noferini , 
I ran git-clang-format, if it is ok for you, can you merge my Pull Request? Then it will come here too.
Cheers,
Chiara

**Comment by noferini** [comment]
> Ciao @noferini ,
> I ran git-clang-format, if it is ok for you, can you merge my Pull Request? Then it will come here too.
> Cheers,
> Chiara

Merged

**Comment by chiarazampolli** [comment]
Hello,

The errors in the o2checkcode are not related to this PR.

Chiara

**Pull request merged**
