### PR TITLE
fix in tof cosmic calibrator (TLinearFitter)

### PR DESCRIPTION
**Pull request by noferini**
Default = 1 thread used
fix in TLinearFitter fit to protect from non positive matrix definition (completed addpoint with missing points)

### CODE REVIEW

**Comment by noferini** [comment]
@chiarazampolli 
checked with run 505404 (now the number of channels calibrate makes sense, > 100k)

**Comment by noferini** [comment]
You can check
http://ccdb-test.cern.ch:8080/browse/TOF/Calib/ChannelCalib
entry
9ac258225eaf67951fb9b06b7f2bf45b

**Comment by noferini** [comment]
Recently added the possibility to load from a local file previous calibrations.

New calibration 505404 computed using time slewing correction (previous calibration in general) from Run-2.
entry
5eff0a70-3a9a-11ec-87a7-5d42c3e7250c

**Comment by chiarazampolli** [comment]
Thanks @noferini , very nice!

Chiara

**Comment by noferini** [comment]
Can we merge this (checks are fluctuating green <-> red)?

**Pull request merged**
