### PR TITLE
MFT cooling pipes between disks and patch panel

### PR DESCRIPTION
**Pull request by frmanso**
Coding of cooling pipes connected to each heat exchanger, these pipes go to the patch panel.

### CODE REVIEW

**Review by bovulpes — DISMISSED** [review]

**Comment by frmanso** [comment]
Please wait a little before to approve it, I have to remove some commented lines in the code, forgotten by me.

**Comment by frmanso** [comment]
The second commit removes the commented lines and the code is fine now.

**Comment by sawenzel** [comment]
@frmanso : There are codechecker complaints. Can you please fix them? Merging can proceed thereafter.

**Comment by bovulpes** [comment]
Hi @frmanso 

Just need to use {} to include the statements following the if:

Detectors/ITSMFT/MFT/base/src/HeatExchanger.cxx:3741:19: warning: statement should be inside braces [readability-braces-around-statements]
    if (disk == 0)

**Comment by frmanso** [comment]
Sorry for the delay, a lot of teaching tasks, now it's done, the braces have been added. Should be fine now.

**Pull request merged**
