### PR TITLE
Update MCTrackToDPL example

### PR DESCRIPTION
**Pull request by sawenzel**
Add `--aggregate-timeframe 1` option. Without this, the example crashed or hangs.

Thanks to @DanielSamitz for reporting.

### CODE REVIEW

**Comment by sawenzel** [comment]
@aalkin : Could you take a look why the examples crashes without the `aggregate-timeframe` option? Is it normal behaviour or does it point to some issue?

**Comment by sawenzel** [comment]
Ok I see there is already discussion elsewhere. Supposedly #https://github.com/AliceO2Group/AliceO2/pull/12141 fixes this, right?

**Comment by aalkin** [comment]
Indeed, the current version was not properly tested (I apologize for that). Because it only publishes first `aggregate` number of events it may fail with the default value of 300 (used when the argument is not explicitly provided). I will run some tests with #12141 and report.

**Comment by aalkin** [comment]
@sawenzel note, the issue is with kine-publisher, not the mctracks-proxy

**Comment by sawenzel** [comment]
Merging this for now to have example working.

**Pull request merged**
