### PR TITLE
DPL Analysis: provide metadata to workflow construction

### PR DESCRIPTION
**Pull request by ktf**
DPL Analysis: provide metadata to workflow construction

### CODE REVIEW

**Comment by jgrosseo** [comment]
Very nice! :-)

**Comment by ktf** [comment]
Tested locally with the simple test and indeed it now does not load ROOT once it finds out the options and injects them in the topology. Now testing on hyperloop.

**Comment by ktf** [comment]
This version seems to behave on hyperloop as well. Will merge if the tests pass.

**Comment by ktf** [comment]
Merging this. Works on hyperloop and it should not have any effect if the metadata is not used. Moreover, changing one line (the list of capability plugins) should be enough to completely disable the new behavior.

**Comment by mhemmer-cern** [comment]
Why the change from `aod-file` to `aod-file-private`?
Was this communicated somewhere because I did not see anything except @ddobrigk asking about this change in one of the hyperloop channels.

**Comment by ddobrigk** [comment]
Hi everyone, let me also support @mhemmer-cern 's question... this is quite a complicated change because - at least at my workplace - quite a few people lost quite some time to figure out that this had happened (and in fact nobody replied to my message in the analysis channel :-( )...

**Comment by jgrosseo** [comment]
On Hyperloop, we still use aod-file. We didn't change anything. This private must have some internal reason and it is a hack to use it externally. But I let Giulio comment...

**Comment by mhemmer-cern** [comment]
Hey @jgrosseo thanks for the reply. So the problem that I faced with this change is for local testing, which should affect pretty much everyone for local testing, since our json config files had `aod-file` as an option which no longer exists and needs to be changed to the new `aod-file-private`. 
On Hyperloop when you run a train test the newly generated [dpl-config.json](https://alimonitor.cern.ch/train-workdir/tests/0021/00219331/dpl-config.json) has that change in it as well. That was how we found the solution.

**Comment by ddobrigk** [comment]
Hi @jgrosseo my guess is you dodged that because the `aod-file` without private still works but *only in the command line* - in the json you have to write "private" or it will not work. My guess is the dpl-config is simply the system dump and since the system changed it started to dump the right thing after the change....

**Comment by jgrosseo** [comment]
@mhemmer-cern We do not use `dpl-config.json` on Hyperloop, it is generated by the running. And indeed, we use it on the command line.
@ktf should really comment...

**Comment by ktf** [comment]
indeed, the private you should ignore, why is it an issue? Can you point me to the a reproducer which breaks?

**Comment by mhemmer-cern** [comment]
Hey @ktf,
the problem is with local test scripts that people used, where in the json config file one needs to change the `aod-file` to `aod-file-private` which was not public knowledge so people where confused and struggled with this.

**Comment by ktf** [comment]
While I cannot comment on how this private script itself works, I suspect what is happening here is indeed what @jgrosseo suggested. If the config gets cached across different releases there is no guarantee that will actually work: it might, it might not or it might silently misbehave. This is in particular true for workflow options like `--aod-file`. I will make sure I add that to the documentation, if missing.

My recommendation would be to change your script to always generate the config from scratch when switching releases. If you point me to the actual script I can probably be more precise.

That said, for this specific case I think I can now get rid of the `aod-file-private` option completely and in case I do, I will make sure I will advertise it appropriately in the WP4 - WP14 meeting.

**Pull request merged**
