### PR TITLE
Do miscellaneous cleanups

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@mkrzewic are you ok with the detector names?

**Comment by ktf** [comment]
I took those from the paper by Pierre that you circulated a while ago. I
guess we can iterate with them. Any objections to the other two commits? I
am actully just trying to cleanup my history before the real PR I am
working on.

**Comment by matthiasrichter** [comment]
No objections from my side concerning the other commits. We can simply add a comment with the reference to the document. I could not find it on CDS though.

@Barthelemy could you have a look if the detector names are consistent with what is used in DAQ developments for run 3 (Control, DQM, ...)

**Comment by Barthelemy** [comment]
Very good point @matthiasrichter !

As we get rid of the old code base of the DAQ, we should be safe to use the codes listed there. Let me circulate this PR inside the DAQ to make sure. 

This being said, I am not sure that it belongs to the DataHeader class and we might want, in the future, to move it to its own utility class that would contain the mapping id <-> code <-> name and the utility functions to convert from one to another. Then everyone in the collaboration should use this class when dealing with detector codes and names.

**Comment by vascobarroso** [comment]
I'm ok with the selected 3-letter codes.
I agree with Barth's remark that this belongs in a separate class.
Not sure if we still need both names and 3-letter codes (e.g. MCH and MUON_TRK). Probably the 3-letter codes are enough.

**Comment by rdivia** [comment]
What is the use of "Any"?

What is the use of "Invalid"?

What is the use of "FLP" (DataHeader.h)? BTW: "FLP" is missing from DataHeader.cxx

**Comment by ktf** [comment]
@rdivia for "any" and "invalid", I will let @mkrzewic to comment.

For "FLP", this is what @matthiasrichter and myself came up with to indicate data that is associated to the FLP itself and not to some detector. E.g. some metadata generated on the fly on the FLP.

**Comment by matthiasrichter** [comment]
@rdivia "any" is a wildcard meaning "any origin", can e.g. be used with search algorithms, "inv"(alid) is used for default initialization, meaning that the origin is not yet set to a valid value.

**Comment by rdivia** [comment]
@matthiasrichter OK, thanks for the info. If I understand correctly:

1) "Any" can be used for matching but no actual data will be ever marked as "any".

2) "Invalid": wouldn't be better to load right away the data source and never have invalid? I mean, when a block is allocated we surely know why we are allocating it...

**Comment by rdivia** [comment]
@ktf @matthiasrichter If "FLP" == metadata, why not mark it as "FLP metadata"? Or "metadata"? I found FLP a bit misleading.

**Comment by ktf** [comment]
Another point which was raised by @shahor02 is that there is no way we can map those to a bit mask at the moment. Anyways, I will remove that commit from my PR and we need to discuss further in the WP1, I think.

**Comment by ktf** [comment]
@rdivia Because we only have 3 bytes + `\0` for that, so "FLP metadata" would not fit.

**Comment by matthiasrichter** [comment]
@rdivia 1) exactly, 2) That is true for data published into the system. Still the software needs a default value and a way to check invalidity. Having an identifier for that makes the software more readable.

**Comment by shahor02** [comment]
I think apart from unique (detector) names we need also unique consecutive identifiers which can be used for iteration over detectors and to create/combine masks a la (0x1<<detID0)|(0x1<<detID1), e.g. for GRP like object. The ItgType() cannot be used since it is basically a random integer. Should not this be a separate class coupled with uniquely defined e.g. enum for all use cases mapping like
````
using detMask=std::int16_t;

class DetID {
 public:
  /// Detector identifiers: continuous, starting from 0
  enum ID : std::int8_t {ITS,... ZDC};
  // number of defined detectors
  static constexpr int NDETECTORS = 14;
 
 /// + getters for DataOrigin, name, mask extraction
 
protected:
  ID  mID; ///< detector ID
  static constexpr DataOrigin dets[NDETECTORS];
}
````

**Comment by matthiasrichter** [comment]
@vascobarroso the "MCH and MUON_TRK"-confusion is exactly what I was referring to. It's hard even for experienced people. Lets avoid that and stick to a unique n-letter code. Looks like that most people are fine with n==3.

**Comment by Barthelemy** [comment]
@vascobarroso @matthiasrichter I totally agree with getting rid of names. Let's only keep 3 letters code.

@shahor02 What you propose is what I had in mind with the mapping id <-> code and the corresponding utility functions in a separate class.

**Comment by aphecetche** [comment]
As muon was mentioned, I figured I'd say something ;-) : I'm completely fine with using only the 3-letter thing.

Concerning the list of detector names and ids, besides putting them in C++ class "somewhere", I think it should also be explicitly written in some text/spec document. So it can be referenced, and also be implemented in other languages if need be... Just my 2 €cents.

**Comment by ktf** [comment]
Merging the unambiguous bits let's discuss the DataOrigin & co in some WP1 context.

**Pull request merged**
