### PR TITLE
Run2V0 replaced with FV0A and FV0C

### PR DESCRIPTION
**Pull request by ekryshen**
Draft PR to indicate proposed changes in the data model

### CODE REVIEW

**Review by iarsene — DISMISSED** [review]

**Comment by iarsene** [comment]
Hi @ekryshen ,
It seems your PR has conflicts. Could you look it up?
Ionut

**Comment by ekryshen** [comment]
Hi @iarsene, yes, I'll try to resolve them now

**Comment by jgrosseo** [comment]
This should not be merged before we have the converted data ready

**Comment by jgrosseo** [comment]
The conversion trains are running (96-98). Most likely we can merge this tonight.

**Comment by iarsene** [comment]
Ok, I will merge it after i see the trains have finished.

**Pull request merged**
