### PR TITLE
Jpsi task and candidate selection

### PR DESCRIPTION
**Pull request by zhangbiao-phy**
- Add a task for Jpsi to ee
- With Jpsi candidate selection

### CODE REVIEW

**Comment by nzardosh** [comment]
HI @zhangbiao-phy , thanks for the good work!
Here are some comments :
1) in HFSecondaryVertex the pdgcode you should use in the Recodecay functions should be the Jpsi not the electron
2)In the selector you can increase the default max candidate pT in the configurable
3) if (pidJpsi  && topolJpsi)  should be changed to if ((pidJpsi == -1  || pidJpsi==1) && topolJpsi)

**Comment by zhangbiao-phy** [comment]
> HI @zhangbiao-phy , thanks for the good work!
> Here are some comments :
> 
> 1. in HFSecondaryVertex the pdgcode you should use in the Recodecay functions should be the Jpsi not the electron
>    2)In the selector you can increase the default max candidate pT in the configurable
> 2. if (pidJpsi  && topolJpsi)  should be changed to if ((pidJpsi == -1  || pidJpsi==1) && topolJpsi)

Thanks for comments! I have modified it.

**Comment by nzardosh** [comment]
Hi @zhangbiao-phy

**Comment by nzardosh** [comment]
Hi @zhangbiao-phy ,

Thanks for the modifications, I have a few more comments.

1) In the Jpsi task where you have :

      if (candidate.isSelJpsi() >= d_selectionFlagJpsi) {
        registry.get<TH1>(HIST("hmass"))->Fill(InvMassJpsi(candidate));
      }
you can remove the if as you already do this in the filter


2) Here in the selector 

if ((TMath::Abs(trackElectron.pt()) < TMath::Abs(cuts[pTBin][3]))|| (TMath::Abs(trackPositron.pt()) < TMath::Abs(cuts[pTBin][3]))) {

you can remove all the Absolute operations because pT will be positive. This has now been changed in the D0 as well

3) We need to include the preselection bit as well in the selector. In the candidate loop around line 222 (before other selections) you can do this

int JpsiFlag = hfCandProng2.hfflag();

      if (!(JpsiFlag & 1 << 1)) {
        hfSelJpsiCandidate(statusJpsi);
        continue;
      }
      
  this should work when Luigi's PR for the Lc is merged

**Comment by zhangbiao-phy** [comment]
> Hi @zhangbiao-phy ,
> 
> Thanks for the modifications, I have a few more comments.
> 
> 1. In the Jpsi task where you have :
>    if (candidate.isSelJpsi() >= d_selectionFlagJpsi) {
>    registry.get(HIST("hmass"))->Fill(InvMassJpsi(candidate));
>    }
>    you can remove the if as you already do this in the filter
> 2. Here in the selector
> 
> if ((TMath::Abs(trackElectron.pt()) < TMath::Abs(cuts[pTBin][3]))|| (TMath::Abs(trackPositron.pt()) < TMath::Abs(cuts[pTBin][3]))) {
> 
> you can remove all the Absolute operations because pT will be positive. This has now been changed in the D0 as well
> 
> 1. We need to include the preselection bit as well in the selector. In the candidate loop around line 222 (before other selections) you can do this
> 
> int JpsiFlag = hfCandProng2.hfflag();
> 
> ```
>   if (!(JpsiFlag & 1 << 1)) {
>     hfSelJpsiCandidate(statusJpsi);
>     continue;
>   }
> ```
> 
> this should work when Luigi's PR for the Lc is merged

Thanks for comments! I should be more careful later.

**Comment by nzardosh** [comment]
Also you will need to do the clang cleanup command before you push next time

**Comment by zhangbiao-phy** [comment]
> Also you will need to do the clang cleanup command before you push next time

Ok

**Comment by nzardosh** [comment]
> > Hi @zhangbiao-phy ,
> > Thanks for the modifications, I have a few more comments.
> > 
> > 1. In the Jpsi task where you have :
> >    if (candidate.isSelJpsi() >= d_selectionFlagJpsi) {
> >    registry.get(HIST("hmass"))->Fill(InvMassJpsi(candidate));
> >    }
> >    you can remove the if as you already do this in the filter
> > 2. Here in the selector
> > 
> > if ((TMath::Abs(trackElectron.pt()) < TMath::Abs(cuts[pTBin][3]))|| (TMath::Abs(trackPositron.pt()) < TMath::Abs(cuts[pTBin][3]))) {
> > you can remove all the Absolute operations because pT will be positive. This has now been changed in the D0 as well
> > 
> > 1. We need to include the preselection bit as well in the selector. In the candidate loop around line 222 (before other selections) you can do this
> > 
> > int JpsiFlag = hfCandProng2.hfflag();
> > ```
> >   if (!(JpsiFlag & 1 << 1)) {
> >     hfSelJpsiCandidate(statusJpsi);
> >     continue;
> >   }
> > ```
> > 
> > 
> > this should work when Luigi's PR for the Lc is merged
> 
> Thanks for comments! I should be more careful later.

No worries at all, things always slip through when making big changes :)

**Pull request closed without merging**
