### PR TITLE
DPL: additional tracing / debug statements

### PR DESCRIPTION
**Pull request by ktf**
Now that we have an easy way to selectively enable debug messages, we can add more of them to simplify debugging.

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken I do not see any status update since over 3 ours here. Maybe an issue with the PR in ali-bot we just merged?

**Comment by TimoWilken** [comment]
@ktf you're right. Fixed now! The statuses should be updated pretty quickly as the builds have already happened.

**Comment by ktf** [comment]
@davidrohr @sawenzel is the error with the full system test known? Or maybe we are building without NDEBUG...

**Comment by ktf** [comment]
Actually I see the error elsewhere as well.

**Pull request merged**
