### PR TITLE
Fix O2-521

### PR DESCRIPTION
**Pull request by matthiasrichter**
@ktf, happy to receive your comments.

When I was about to add yet another context I figured out that the registry was not intended for that, so I made it more generic and type safe. In the next step I had to make a context which allows to control different types of `span<T>`, so I ended up making also `MessageContext`  more generic. Apart from cleanup, this should do the job now.

We can consider to move the functionality from the different contexts to specialized context objects in the future if you find the concept appropriate. But that's not urgent, the generic MessageContext would allow this with not to much extension.

### CODE REVIEW

**Comment by ktf** [comment]
Are you sure that having a single place with the knowledge of all the Context types is a good idea? If we need a way to extend the registry I would be more in favour of a dynamic registry where each registry register itself with a unique id (e.g. the pointer to some singleton) rather than have a type that knows everything. Let me try to put together a quick implementation for it so that I can show you what I mean.

**Comment by matthiasrichter** [comment]
I agree with you in general, and I have though about it. But for the use case here I prefer a type safe solution. Anyhow one needs to know the type of contexts as long as its not a policy structure where the contexts serve the same interface of the host. That was my reasoning, but sure, any other appropriate registry concept is good.

Actually this commit is not necessary any more for the fix, because I could solve it without adding yet another context. So we can leave it out and discuss other solutions if you want.

**Comment by matthiasrichter** [comment]
@ktf, in the light of the plans for breaking-up the DataAllocator API into multiple files it is indeed better to use a dynamic registry instead of the static one. In the end it was very simple to implement.

**Comment by ktf** [comment]
Yes, this is in line with what I had in mind. I made my example in #1803 (not fully tested, but it seems to work). The difference with your implementation are:

1. It uses a static bool, rather than `typeid()` to generate the lookup id in the registry. For that reason it needs a `REGISTER_CONTEXT(T)` to be added to the declaration of every type. I **think** my implementation is faster, but I have not checked.
2. Mine removes the need to create all the Contextes in the DataProcessingDevice, effectively making it completely pluggable in terms of backend supported for messaging.

I do not have a particular opinion on 1., assuming it's not performance critical, do you think your implementation could be extended to support 2?

**Comment by matthiasrichter** [comment]
@ktf I think it can be easily extended, for the moment I think it's more clear to explictely say which contexts should be used, have to think a bit more.

**Comment by matthiasrichter** [comment]
The registry related code is now moved to https://github.com/AliceO2Group/AliceO2/pull/1805

**Comment by ktf** [comment]
I guess this is ready to go now, no?

**Pull request merged**
