### PR TITLE
Introducing type trait is_messageable and replacing is_trivially_copyable/is_pod with this

### PR DESCRIPTION
**Pull request by matthiasrichter**
Extending snapshot method of framework::DataAllocator to support
trivially copyable objects in general in all specializations. On the
receiving side, DataRefUtils::as has been made consistent to that.

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@ktf, `is_trivially_copyable` has been used already for the `std::vector`-case, but there was a problem on the receiver side as this was checking for `is_pod`.

Should we also change the `DataAllocator::make` methods?

**Comment by ktf** [comment]
As privately discussed `is_trivially_copyable` is probably not what we want since it would include classes which have a virtual table. As agree we should probably refactor this and introduce a `o2::traits::is_messageable` trait which uses something like `is_trivially_copyable && !is_polymorphic`. We could later extend this to exclude structs with pointers using techniques like the one mentioned in the thread at:

https://stackoverflow.com/questions/32880990/how-to-check-if-class-has-pointers-in-c14

**Comment by matthiasrichter** [comment]
I went through all the clang-format recommendations and have applied the reasonable ones. The now remaining issues I suggest to ignore, the proposed formatting does not really make sense in terms of readability of the code.

**Comment by matthiasrichter** [comment]
Also for the last commit the clang-format is not appropriate

**Comment by ktf** [comment]
Looks good to me. Would you like to report about this change tomorrow at the 10AM meeting?

**Comment by ktf** [comment]
I assume the tpcsim_G3 issue is a spurious one, no?

**Comment by matthiasrichter** [comment]
as expected, the error went away.

I will prepare a short report about this and a few more enhancements for tomorrow.

**Comment by ktf** [comment]
Great. I created an item on the agenda for you. Do you want to do the changes in this PR or do you prefer I merge this and you do them separate ones? Can you rework the title of the PR?

**Comment by matthiasrichter** [comment]
merging this, the other development goes in a new PR

**Pull request merged**
