### PR TITLE
DPL: add initial attempt at histogram writer

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@knopers8 32362ed562acc6420e745aeb3b279d6d2ab9dac2 is probably of interest for you as well, since I imagine you have the same problem when using a wildcard for the InputSpec. Could you check?

**Comment by knopers8** [comment]
I haven't run it yet, it is building, but won't it cause problems with colliding timesliceIDs? Two messages from different producers could match the same timeslot if they have the same timesliceID, DataOrigin and DataDescription (but different subspecs).

**Comment by ktf** [comment]
Timeslots now have an actual time attached, so that should not be the case. Or am I misunderstanding your comment?

**Comment by ktf** [comment]
Mmm... There is indeed a new error:

```
[ERROR] Child 43489 had at least one message above severity ERROR: [15:17:22][ERROR] Unable to relay part.
[INFO] Process 43478 is exiting.
=== test_Framework_test_ParallelPipeline - Test attempt 3/3 failed with exit code 1 ===
=== test_Framework_test_ParallelPipeline - Test failed after 3 attempts with 1 ===
```

albeit I am not sure why that  happens...

**Comment by knopers8** [comment]
I think you understood it well. Though I am not sure if we should rely on the assumption, that timesliceIDs won't ever be the same for messages which differ only with subSpec.
That being said, I can also see a problem in o2-testworkflows-datasampling-pod-and-root, where the fake QC tasks process only the data once and after that the devices seem to receive it, but somehow they don't process it. I tried to investigate it a bit, but I am not sure what is wrong. It might have something to do with handing the TimesliceIndex.

**Comment by ktf** [comment]
This is now just the analysis part, since this development is self consistent I am merging it.

**Pull request merged**
