### PR TITLE
Reader of TOF matched tracks, ITSTPC/TPC tracks for TOF QC

### PR DESCRIPTION
**Pull request by chiarazampolli**
I have not found this workflow already available, so I created it with existing DataProcessors. If there is one that already does the same, let me know.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
@noferini , @njacazio , FYI

**Comment by shahor02** [comment]
Hi @chiarazampolli 

There is a universal reader set up by David, e.g.
````
o2-global-track-cluster-reader --track-types "ITS,TPC,ITS-TPC" --cluster-types "ITS,TPC" 
````

**Comment by chiarazampolli** [comment]
Great! Do we have a reader for the TOF matched tracks, @noferini ?
Chiara

**Comment by noferini** [comment]
> Great! Do we have a reader for the TOF matched tracks, @noferini ?
> Chiara

No,
but in the David workflow I see
  --TOFMatchedReader_tpc arg            Use '--help TOFMatchedReader_tpc' to 
  --TOFMatchedReader_glo arg            Use '--help TOFMatchedReader_glo' to 

options.
I guess this is what you need

**Comment by shahor02** [comment]
Hi @chiarazampolli 

It is supposed to read all kind of tracks. For the TOF you will need to read
````
o2-global-track-cluster-reader --track-types "ITS-TPC-TOF,TPC-TOF" 
````
to read 2 type of TOF matches and TPC tracks. If you need also TOF clusters, just add `--clusters "TOF"`

**Comment by chiarazampolli** [comment]
Hi @shahor02 , 

If this is based on the RecoContainer, then when I ask for "TPC-TOF" it will also load the TPC-TOF matches. Right? 

Chiara

**Comment by chiarazampolli** [comment]
> > Great! Do we have a reader for the TOF matched tracks, @noferini ?
> > Chiara
> 
> No,
> but in the David workflow I see
> --TOFMatchedReader_tpc arg Use '--help TOFMatchedReader_tpc' to
> --TOFMatchedReader_glo arg Use '--help TOFMatchedReader_glo' to
> 
> options.
> I guess this is what you need

Ciao @noferini , 
Where do you see it in O2? I did not find this option in GlobalTrackClusterReader.cxx
Chiara

**Comment by noferini** [comment]
> > > Great! Do we have a reader for the TOF matched tracks, @noferini ?
> > > Chiara
> > 
> > 
> > No,
> > but in the David workflow I see
> > --TOFMatchedReader_tpc arg Use '--help TOFMatchedReader_tpc' to
> > --TOFMatchedReader_glo arg Use '--help TOFMatchedReader_glo' to
> > options.
> > I guess this is what you need
> 
> Ciao @noferini ,
> Where do you see it in O2? I did not find this option in GlobalTrackClusterReader.cxx
> Chiara

I just did
 > o2-global-track-cluster-reader -b --help|grep TOF
  --TOFMatchedReader_tpc arg            Use '--help TOFMatchedReader_tpc' to 
  --TOFMatchedReader_glo arg            Use '--help TOFMatchedReader_glo' to

**Comment by chiarazampolli** [comment]
Closing, with the global reader I verified that I can access all I need. Thanks @shahor02 , @noferini !

**Pull request closed without merging**
