### PR TITLE
Move away from deprecated FairMQ API

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Keep it draft until we are happy with FairMQ 1.5.0

**Comment by ktf** [comment]
I think FLP yesterday asked to hold on this. Did I miss something?

**Comment by davidrohr** [comment]
Ah, didn't see that, perhaps...
Sorry...
But we are updating O2 today anyway, hopefully that will work out. And we are using it in production on the EPNs already. Worst case we can revert it :)

**Comment by ktf** [comment]
> Worst case we can revert it :)

Yeah, I was hoping to avoid some conflicts I have with something in my PR pipeline...

**Pull request merged**
