### PR TITLE
Sample workflows for calibration in groups of TFs, case of LHC clock calibration in TOF

### PR DESCRIPTION
**Pull request by shahor02**
1) Detectors/Calibration defines base classes templates for use time slot definition (container for the data accumulated over a certain number of TFs) and their manipulation. It also provides a generic workflow which receives binary images of the calibration data (the content is irrelevant) accompanied by the ``CcdbObjectInfo`` and puts then on the CCDB

2) Detectors/TOF/calibration implements TOF specific data accumulation slots and their processing, as well as the workflow to aggregate asynchronously TFs from different EPNs and to extract calibration data for groups of TFs.
In real life, the channelling of data from different EPNs to this aggregator device will require a special proxy device (to be written), as a place-holder at the moment data from different EPNs is emulated by the  ``data-generator-workflow`` which spawns multiple lanes (EPNs) each one generating (with randomized latency) a calibration input data for a single TF.

To be run as e.g.
````
o2-calibration-data-generator-workflow --lanes 10 --mean-latency 10000 --latency-spread 1000 --max-timeframes 500 | o2-calibration-lhc-clockphase-workflow --tf-per-slot 20 | o2-calibration-ccdb-populator-workflow --ccdb-path localhost:8080 
````

### CODE REVIEW

**Comment by shahor02** [comment]
@ktf all failed PRs show logs as a broken page with "Access Denied"...

**Comment by ktf** [comment]
I think there is some CERN wide issue.

**Comment by ktf** [comment]
It was actually a mistake on my side. Now it should be back in business.

**Comment by shahor02** [comment]
macOS test is not functioning, merging.

**Pull request merged**
