### PR TITLE
Avoid keeping large tree in memory when creating distortion maps

### PR DESCRIPTION
**Pull request by martenole**
In case `treeBinnedResiduals` is kept in memory, because the binned residuals should not be stored, the memory usage of the script grows above 6GB.
To avoid this a temporary file is created where the binned residuals are flushed during the map creation.

### CODE REVIEW

**Review by wiechula — DISMISSED** [review]
Failures look unrelated, can this be merged?

**Comment by martenole** [comment]
Actually, I wanted to avoid leaving the temporary buffer file around. But when I call `gSystem->Unlink(tmpFileName.c_str());` then valgrind complaints and I cannot test it anymore.

**Comment by wiechula** [comment]
@martenole , did you try to use https://en.cppreference.com/w/cpp/filesystem/remove

**Comment by martenole** [comment]
Same error from valgrind with that. Was already reported to ROOT: https://sft.its.cern.ch/jira/browse/ROOT-10698
But I assume it is a valgrind issue. Anyway, I monitored the memory usage with top and it was OK. So will merge this once the checks are through

**Pull request merged**
