### PR TITLE
ITS tracking works on generic N layers

### PR DESCRIPTION
**Pull request by mpuccio**
This introduces the changes required to run the ITS tracking suite on dataset with a different number of layers (ITS3 with more than 3 layers in the IB, ALICE3...).
@mconcas please check that everything is fine with you.

@qgp FYI

### CODE REVIEW

**Review by bovulpes — DISMISSED** [review]
I see no MFT or common code involved.

**Comment by mpuccio** [comment]
Hi @davidrohr, @iouribelikov 
this is the latest version of the tracker that is able to reconstruct tracks from the new ALICE3 geometry and also partial ITS2 geometry (the cosmics).
The GPU part of the code compiles, but it is not functional for the time being. We will put it in operation again once the strobe aware reconstruction is also implemented. 
Not sure why o2 CI is failing, but the rest is green so if it is fine with you I would merge (+squash).
Cheers,
Max

**Review by davidrohr — APPROVED** [review]
Fine with me, I have seen that the o2 CI is currently generally failing but fullCI and mac have passed, so it should be OK. If @iouribelikov approves as well, we can squash-merge it.

**Review by iouribelikov — APPROVED** [review]

**Comment by mpuccio** [comment]
Thanks @iouribelikov !!

**Pull request merged**
