### PR TITLE
ATO-609: Additional ITS material added (to be MOVED in ITS code)

### PR DESCRIPTION
**Pull request by marslandALICE**
This part of the code should be moved to "ITS" but for the time being it should be OK

### CODE REVIEW

**Comment by davidrohr** [comment]
@sawenzel : could you have a look how to proceed. This is needed for more realistic TPC number of clusters. Apparently it should be moved into the ITS part. Who would be responsible?
Or could we just merge it as is, and move it later?

**Comment by sawenzel** [comment]
Sorry. This PR escaped my attention. Since this material is ITS, I think we should directly put it as part of the ITS detector.
It should be easy enough to move it directly there. @mconcas will try to do so unless this is hyper-urgent?

**Comment by mconcas** [comment]
> Sorry. This PR escaped my attention. Since this material is ITS, I think we should directly put it as part of the ITS detector. It should be easy enough to move it directly there. @mconcas will try to do so unless this is hyper-urgent?

I am trying right now to append this to some lower-level ITS-related service volumes. Let's say that if this is not going to converge by tomorrow, we will merge it as it is now and re-iterate on it later.

I know this thing has been a long-standing topic that we promised to take care of, and I understand the current urgency. Therefore I would not mind having this merged even earlier if you need that.

**Comment by davidrohr** [comment]
Hi, this is not super urgent. I need it at the moment for local simulations, so I can just merge it locally.
If you can clean it up and merge it some time next week, that would be totally fine.

**Comment by sawenzel** [comment]
@mconcas : I think this was done meanwhile via an ITS PR. Can you confirm and then we can close this I believe.

**Comment by mconcas** [comment]
> @mconcas : I think this was done meanwhile via an ITS PR. Can you confirm and then we can close this I believe.

Yes this was done in the linked PR. I guess we can close indeed.

**Pull request closed without merging**
