### PR TITLE
Digit moved

### PR DESCRIPTION
**Pull request by mwinn2**
WIP: moving digits into Base
@aphecetche : I don't manage to get the linking properly done, sorry, but the easiest is, if you have a look, I think (with my cmake clumsiness it takes otherwise quite some time).

### CODE REVIEW

**Comment by aphecetche** [comment]
@mwinn2 I've opened a PR to your branch : https://github.com/mwinn2/AliceO2/pull/7 to show what I had to change to make it compile and link correctly. There's a question though on what to do with the timestamp.

**Comment by sawenzel** [comment]
Formatting is failing. Can we go on here?

**Comment by aphecetche** [comment]
@mwinn2 could you fix the clang-format stuff ?

**Comment by sawenzel** [comment]
Seems to be ok now. @aphecetche Can you approve the PR?

**Comment by shahor02** [comment]
Just out of curiosity: is there a reason to move the Digit to {{Detectors/MUON/MCH/Base}} and not to more natural {{DataFormats/Detectors/MUON/MCH}} ?

**Comment by sawenzel** [comment]
It probably makes sense to systematically collect these data structures under "DataFormats".
It would be quite natural doing it now but we can also do it later (@aphecetche, @mwinn2  your call). The same should be done for other detectors.

**Comment by aphecetche** [comment]
I would prefer we merge this one and move the relevant structures to their "final" destination on a different PR.

**Pull request merged**
