### PR TITLE
TRD tracker performance optimization

### PR DESCRIPTION
**Pull request by martenole**
Hi @davidrohr 
when I implemented some optimizations for the TRD tracking I did not see a noticeable speedup. With callgrind I saw that most time for the tracking is spent in the propagate function. Currently I propagate the track to each tracklet in the chambers where the track ends up for a comparison. This is needed because of the misalignment of the chambers (the TRD space points are at different radii). If I skip these propagation steps and only propagate once to the middle of the TRD chamber I get a speedup factor of ~18 on a single core!
So I think the greatest potential for a performance optimization is here. I could use `GPUTPCGMPropagator::GetPropagatedYZ` instead of the full propagation, but then the chi2 prediction is not correct. 
Or should I try to implement my own propagate function where only Y, Z and sin(phi) and their errors are calculated such that I can compare those parameters to the TRD space points?
I implemented a function `GetPredictedChi2` which compares tracklet and track, taking into account also the tracklet deflection (see last commit). It is not used yet. I was not sure if that could not be simplified ignoring the correlations sigma_YSinPhi and sigma_ZSinPhi. Since I don't know how to calculate them for the TRD I only use the values of the track for them.
Cheers,
Ole

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi @martenole :

first a general remark: Please set SetFitInProjections for the propagater, that should make it faster with marginal resolution penalty, if the original track estimate from the TPC is reasonable, which should be the case.

then: just to estimate the situation a bit better:
- To how many tracklets do you propagate within one chamber?
- How much does their radius differ, i.e. how long are these short propagations?

I'd do something like use the normal propagation to the average value first. Then you could:
- Use PropagateToXAlphaBz (which considers on Bz, not Bx / By, but should be ok short-term), which will be faster.
- Just use GetPropagatedYZ, and ignore the changes to the covariance, which might be small, if the distance is short.
- In that case, you could even try just a linear extrapolation (all depends on the distance).
- You could also combine this, e.g. rule out the majority of the tracklets already with a linear extrapolation, and for the good candidates, use a better one.
- In any case, you could try to use the correct propagation before the fit, once you have selected the tracklet. In that way, you would prevent that propagation errors accumulate. But not sure whether that is needed.
These are just some ideas, you can try out what works best. If you need a fast special version of the propagation that computes only few selected covariance entries, you can also talk to @sgorbuno , who wrote the propagator class.

Cheers
David

Some

**Comment by martenole** [comment]
Hi @davidrohr 
thanks for your reply! `SetFitInProjections` is enabled now. Concerning your questions:

- The radial spread of the tracklets is up to 3 cm. The RMS for individual chambers is mostly around 3 mm, but the mean position is shifted for some chambers up to 2 cm. This happens because I extrapolate always to the center radius of one certain chamber per layer and do not store the average radius for each of the 522 chambers.
- For large events the propagation could be done up to 300 times per layer for a single track. This is because I do the propagation for each tracklet in the chamber where the track ends up, without a crude check first. This I will change and only consider tracklets within the search road. Either by using `GetPropagatedYZ` or just be increasing the search road a bit I will try to account for the wrong radial position of the tracklets.

I am at a lecture week in Bergen this week and need to find some time to do that properly.

**Comment by davidrohr** [comment]
Hi  @martenole : Is the average for the individual chambers fixed, or does it change over time? If it is constant, it would make sense to store the average positions, and do the first accurate extrapolation up to there.

For 3 mm, I would try to use GetPropagatedYZ, or just a linear extrapolation. For 3 cm, linear is probably not good enough. You could even make that depend on the propagation distance from the average position you are starting from.

**Comment by davidrohr** [comment]
@martenole : Is this still [WIP] or can this be merged?

**Comment by martenole** [comment]
Hi @davidrohr 
this PR is ready to be merged. There are a few things I am not yet happy about which I will try to fix in another PR. These are

- The tracklet error parametrization depends on the B-field. Currently there is a switch in the tracker header, but this should be an external parameter I think
- I started with the interface for O2, but I could not manage to get it compiled yet. This is commented out at the moment in GPUTRDInterfaces.h. My problem is that I need to include the O2 data types for track and propagator, but I do not know which libraries to add in the CMake file so that the headers are found
- There is a function to calculate chi2 for track-tracklet taking into account all 3 parameters y, z, sin(phi). But this does not yet work, since the correct parametrization for the tracklet deflection is not so easy.

And support for time frames is still missing

**Pull request merged**
