### PR TITLE
initial commit on HyperHydrogen4Lambda analysis

### PR DESCRIPTION
**Pull request by BongHwi**
A simple modification of SVertexer and PID part for hyper nuclei analysis
@mpuccio @shahor02

### CODE REVIEW

**Comment by mpuccio** [comment]
Hi @shahor02, we started looking into this but we are not sure this is the only modification required, any feedback and suggestions are welcome!

**Comment by mpuccio** [comment]
@BongHwi let's re-open here and see if there are comments by @shahor02

**Comment by BongHwi** [comment]
Okay, let me see...

**Comment by BongHwi** [comment]
For some reasons, I couldn't reopen the current PR, I'll remake it on https://github.com/AliceO2Group/AliceO2/pull/9518 @mpuccio

**Pull request closed without merging**
