### PR TITLE
Add cmake module to find RapidJSON (and make a proper target of it)

### PR DESCRIPTION
**Pull request by aphecetche**
see https://github.com/alisw/alidist/pull/1095

### CODE REVIEW

**Comment by sawenzel** [comment]
@aphecetche: I guess this will be for your unit tests?

**Comment by aphecetche** [comment]
@sawenzel yes, and also for the geometry building

**Comment by matthiasrichter** [comment]
@aphecetche, hat do you mean by _"and make a proper target of it"_, just want to make sure that nothing is missing in the PR, which contains only the new file at the moment.

**Comment by aphecetche** [comment]
@matthiasrichter 

Nothing's missing (the code that uses it will be in a forthcoming PR).

"Proper target" (in the CMake sense) refers to those lines :  

```
if(NOT TARGET RapidJSON)
      add_library(RapidJSON INTERFACE IMPORTED)
      set_target_properties(RapidJSON PROPERTIES
              INTERFACE_INCLUDE_DIRECTORIES ${RAPIDJSON_INCLUDE_DIRS})
 endif()
```

which are not in the original FindRapidJSON.cmake file, e.g. in Configuration package.

( That might becomes a mute point though if we move away from RapidJSON :  https://github.com/alisw/alidist/pull/1095 )

**Pull request merged**
