### PR TITLE
Fix sporadic output

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 @chiarazampolli this is part of the problem. We now need to mark "sporadic" (i.e. not always produced) outputs consistently, otherwise the timeframe limiting business will not work.

That said, I will make sure that when the timeframe limiting is not enabled, the completion policy behaves as before.

**Comment by shahor02** [comment]
Aha, this means that all calibration aggregators must use this Sporadic...

**Comment by ktf** [comment]
Yes.

**Comment by chiarazampolli** [comment]
Thanks @ktf , but I am not sure I understand: in the async processing on the grid, this is not used.

**Comment by davidrohr** [comment]
@ktf : Could you check the failing tests in here?

**Comment by ktf** [comment]
I fixed the tests and included the commit from #7578 which should solve the problem with discard for real. Now working on the corrected ComsumeExisting policy which takes into account the Sporadic outputs.

**Comment by ktf** [comment]
https://github.com/AliceO2Group/AliceO2/pull/7578 is now merged and should fix issues when the rate limiting is not used.

**Comment by ktf** [comment]
@davidrohr 
```
--
 90/379 Test  #34: GPU/GPUTracking/Standalone/tools/createLUT.C_compiled ................................***Failed   16.89 sec
--
111/379 Test  #33: GPU/GPUTracking/Standalone/tools/createGeo.C_compiled ................................***Failed   24.38 sec
--
```

any idea? I guess unrelated?

**Comment by davidrohr** [comment]
Yes, unrelated:
```
/sw/slc8_x86-64/GCC-Toolchain/v10.2.0-alice2-4/bin/../lib/gcc/x86_64-unknown-linux-gnu/10.2.0/../../../../x86_64-unknown-linux-gnu/bin/ld: cannot open output file /sw/BUILD/03827887025805e7223e464be2fc561caf99b4b9/O2/compiled_macros//sw/SOURCES/O2/7569-slc8_x86-64/0/GPU/GPUTracking/Standalone/tools/createGeo_C.so: No such file or directory
collect2: error: ld returned 1 exit status
```
I have seen this several time recently. Seems to happen randomly. No idea what this is. I think we should merge this.

**Comment by shahor02** [comment]
unrelated, again this strange path pattern:
``/sw/BUILD/03827887025805e7223e464be2fc561caf99b4b9/O2/compiled_macros//sw/SOURCES/O2/7569-slc8_x86-64/0/GPU/GPUTracking/Standalone/tools/createLUT_C.so``

**Comment by ktf** [comment]
Ok, testing this once more on hyperloop then merging.

**Comment by ktf** [comment]
hyperloop fine as well. Merging.

**Pull request merged**
