### PR TITLE
[EMCAL-535, EMCAL-655] Interface simplidication of raw fitter classes

### PR DESCRIPTION
**Pull request by mfasDa**
- Remove altrocfg registers in evaluation method:
  In o2 the registers are decoded in the RCU trailer,
  the relevant setting for the zero-suppression is
  added directly
- Add Error type LOW_SIGNAL for bunches which are
  rejected because of all ADC values below threshold
- Use more meaningful function and variable names
  that express the purpose of a function / variable
  directly
- Improve doxygen documentation of most crucial
  functions

### CODE REVIEW

**Comment by mfasDa** [comment]
Supersedes https://github.com/AliceO2Group/AliceO2/pull/6848

**Comment by mfasDa** [comment]
I am getting e-mails about errors in the space checker, however looking at github I see the test passed and when I apply clang-format I don't get any changes. Is there anyone that can clarify this?

**Comment by davidrohr** [comment]
@mfasDa : This seems to be a genuine error:
```
/sw/SOURCES/O2/6864-slc8_x86-64/0/Detectors/EMCAL/workflow/src/RawToCellConverterSpec.cxx:341:25: error: statement should be inside braces [readability-braces-around-statements]
```

**Comment by shahor02** [comment]
@mfasDa please fix this:
`````
/sw/SOURCES/O2/6864-slc8_x86-64/0/Detectors/EMCAL/workflow/src/RawToCellConverterSpec.cxx:341:25: error: statement should be inside braces [readability-braces-around-statements]
`````
otherwise looks fine.

**Comment by mfasDa** [comment]
Readability stuff fixed

**Comment by mfasDa** [comment]
Now all should be OK

**Comment by mfasDa** [comment]
@shahor02 Do you think this could be merged now?

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
