### PR TITLE
DPL: mark output proxy as resiliant, if actually the case

### PR DESCRIPTION
**Pull request by ktf**
DPL: mark output proxy as resiliant, if actually the case

If the only inputs are sporadic, they can be missing by design.

If the completion policy is consumeWhenAny, it can for sure survive a
crashing upstream device.

### CODE REVIEW

**Comment by davidrohr** [comment]
I do not understand how this should solve the problem of https://its.cern.ch/jira/browse/QC-953.
In the topology there, I do not think we need a resilient output-proxy. The output proxy there is only for sending data to the EPNs, not for QC at all.
The problem is that apparently if the QC task is marked as expendable, it creates a circular dependency, which in my opinion it should not. To me it seems like a bug in the topology sorting.

**Comment by ktf** [comment]
I suspect the problem is that output proxies need to be last (to avoid copying outgoing messages) and this is what is causing the circular dependency. I am checking.

**Comment by ktf** [comment]
(that said, I would still say that an output proxy with `--sporadic-inputs` or `consumeWhenAny` should still be marked as "resilient", given that's actually the case).

**Comment by davidrohr** [comment]
I agree that it is technically the sense that it would work.
But that is also the case for all devices with consumeWhenAny, irrespective of sporadic or timeframe inputs. We could mark all of them as resilient, and the device itself will keep working. The question is whether the whole processing will work correctly.
And in my opinion it creates confusing behavior if we mark some devices as resilient implicitly, while we do not mark others. It is better and clearer to do it explicitly.

**Comment by ktf** [comment]
Given #12647, what do we want to do with this? We simply close it or we want to have some logic to mark all "consumeWhenAny" devices as "resilient" (or just the output proxy?)?

**Comment by davidrohr** [comment]
IMHO this is not needed and also a bit misleading. I generally do not like these implicit logics to automatically set some flags. So I would just close it.

**Pull request closed without merging**
