### PR TITLE
NFC: Fix codechecker for the ITS GPU code

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by mpuccio** [comment]
Ciao @davidrohr , a bit late but here the changes you asked. Not sure if the HIP compilation now is run in the CI, in case can you have a look?

**Comment by davidrohr** [comment]
@mpuccio thx. HIP compilation is not in the CI. We still do not have RPMs, and I did not succeed in moving the ROCm installation from the server into the container. It gave me weird linker errors. I'll check the compatibility.
Btw, what does NFC stands for in the PR name?

**Review by sawenzel — DISMISSED** [review]

**Comment by mpuccio** [comment]
Thanks a lot David. For NFC: I took it from the llvm commit slang, it means that the commit has no functional changes intended.

**Comment by mpuccio** [comment]
Hi @sawenzel, is the failure of the fullCI genuine? I cannot find where to look for the errors related to my PR

**Comment by davidrohr** [comment]
I don't think these errors are related to the PR. But anyway I have to check them on the AMD, so in the meantime I'll wait for the fullCI to reprocess this PR and then merge it.

**Comment by sawenzel** [comment]
It seems to be in quality control. No idea.

**Comment by mpuccio** [comment]
Hi, can this be merged?

**Comment by davidrohr** [comment]
@mpuccio : This works with HIP, but I had some problems with CUDA that the gpu namesspace is ambiguous, since now we have o2::its::gpu and o2::gpu. No idea why the CI didn't see it, my compiler is a bit newer. The patch below fixes it. Could you perhaps just add it to the PR? I don't know if we will hit this again in other places. I think for now it should be OK, but if it happens more often perhaps we should not use the gpu namespace name for 2 namespaces.

```
diff --git a/Detectors/ITSMFT/ITS/tracking/cuda/src/DeviceStoreNV.cu b/Detectors/ITSMFT/ITS/tracking/cuda/src/DeviceStoreNV.cu
index 156b70d1875..3203291d895 100644
--- a/Detectors/ITSMFT/ITS/tracking/cuda/src/DeviceStoreNV.cu
+++ b/Detectors/ITSMFT/ITS/tracking/cuda/src/DeviceStoreNV.cu
@@ -23,7 +23,7 @@ namespace
 
 using namespace o2::its;
 
-__device__ void fillIndexTables(gpu::DeviceStoreNV& primaryVertexContext, const int layerIndex)
+__device__ void fillIndexTables(o2::its::gpu::DeviceStoreNV& primaryVertexContext, const int layerIndex)
 {
 
   const int currentClusterIndex{static_cast<int>(blockDim.x * blockIdx.x + threadIdx.x)};
@@ -66,7 +66,7 @@ __device__ void fillIndexTables(gpu::DeviceStoreNV& primaryVertexContext, const
   }
 }
 
-__device__ void fillTrackletsPerClusterTables(gpu::DeviceStoreNV& primaryVertexContext, const int layerIndex)
+__device__ void fillTrackletsPerClusterTables(o2::its::gpu::DeviceStoreNV& primaryVertexContext, const int layerIndex)
 {
   const int currentClusterIndex{static_cast<int>(blockDim.x * blockIdx.x + threadIdx.x)};
   const int clustersSize{static_cast<int>(primaryVertexContext.getClusters()[layerIndex + 1].size())};
@@ -77,7 +77,7 @@ __device__ void fillTrackletsPerClusterTables(gpu::DeviceStoreNV& primaryVertexC
   }
 }
 
-__device__ void fillCellsPerClusterTables(gpu::DeviceStoreNV& primaryVertexContext, const int layerIndex)
+__device__ void fillCellsPerClusterTables(o2::its::gpu::DeviceStoreNV& primaryVertexContext, const int layerIndex)
 {
   const int totalThreadNum{static_cast<int>(primaryVertexContext.getClusters()[layerIndex + 1].size())};
   const int trackletsSize{static_cast<int>(primaryVertexContext.getTracklets()[layerIndex + 1].capacity())};
@@ -92,7 +92,7 @@ __device__ void fillCellsPerClusterTables(gpu::DeviceStoreNV& primaryVertexConte
   }
 }
 
-__global__ void fillDeviceStructures(gpu::DeviceStoreNV& primaryVertexContext, const int layerIndex)
+__global__ void fillDeviceStructures(its::gpu::DeviceStoreNV& primaryVertexContext, const int layerIndex)
 {
   fillIndexTables(primaryVertexContext, layerIndex);
 
```

**Comment by mpuccio** [comment]
Uhm, interesting! Also locally it was compiling without any problem the CUDA part (I have CUDA 11.0). I applied your patch, thanks a lot!

**Review by davidrohr — APPROVED** [review]
@mpuccio : sorry for the typo in the patch before... :(
I see you have already fixed it :)
I have tried your new version on HIP and it works. Will merge it once the CI has passed.

**Pull request merged**
