### PR TITLE
DPL: use sporadic for expendable devices output

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy do you have expendable devices already in the tests?

**Comment by ktf** [comment]
So the error must be unrelated as it happened in another PR as well. I think there is either something fishy on the machine (@TimoWilken could you please have a look?) or something in the loading of the libraries can eventually slow down processing.

**Comment by Barthelemy** [comment]
@ktf No I don't but I have a branch to play with it.

**Comment by ktf** [comment]
Ok, as discussed the testActivity test which was failing was indeed due to cold cache, bloated dependencies and slow CI VM.

**Pull request merged**
