### PR TITLE
Tracking QC: Add Efficiency vs Phi and Pt

### PR DESCRIPTION
**Pull request by njacazio**
@chiarazampolli we propose this change to have the pT dependent efficiency vs phi (e.g. to plot the efficiency at a given pT)
What do you think?

Tagging also @jloemker that will implement the Eta vs Pt efficiency

### CODE REVIEW

**Review by chiarazampolli — DISMISSED** [review]
Fine with me, sure!

**Comment by njacazio** [comment]
@chiarazampolli I think that the error is unrelated

**Comment by njacazio** [comment]
Hi @chiarazampolli can we merge this ?

**Comment by chiarazampolli** [comment]
I already approved, but you need @shahor02 or @davidrohr  or others with higher powers to merge...

**Comment by njacazio** [comment]
I see, thanks!

**Comment by martenole** [comment]
Hi, are you sure that the error is unrelated? You are changing the ITS-TPC matching QC and this one crashes in the fullCI:
```
[7816:qc-task-GLO-MTCITSTPC]: *** Program crashed (Segmentation fault, FPE, BUS, ABRT, KILL)
[7816:qc-task-GLO-MTCITSTPC]: Backtrace by DPL:
[7816:qc-task-GLO-MTCITSTPC]: SEGMENTATION FAULT
[7816:qc-task-GLO-MTCITSTPC]: Executable is /sw/slc8_x86-64/QualityControl/v1.85.0-local20/bin/o2-qc
```

**Comment by njacazio** [comment]
> Hi, are you sure that the error is unrelated? You are changing the ITS-TPC matching QC and this one crashes in the fullCI:
> 
> ```
> [7816:qc-task-GLO-MTCITSTPC]: *** Program crashed (Segmentation fault, FPE, BUS, ABRT, KILL)
> [7816:qc-task-GLO-MTCITSTPC]: Backtrace by DPL:
> [7816:qc-task-GLO-MTCITSTPC]: SEGMENTATION FAULT
> [7816:qc-task-GLO-MTCITSTPC]: Executable is /sw/slc8_x86-64/QualityControl/v1.85.0-local20/bin/o2-qc
> ```

Good catch, I will have a better look enabling tests when compiling, thanks @martenole !

**Comment by njacazio** [comment]
Ok, I finally managed to have a look, indeed there was an object named wrong

**Comment by njacazio** [comment]
Ok, it seems to me that the error is truly unrelated this time

**Comment by njacazio** [comment]
Closing as included in https://github.com/AliceO2Group/AliceO2/pull/10749

**Pull request closed without merging**
