### PR TITLE
Propagate/use TPC occupancy histo via RecoContainer

### PR DESCRIPTION
**Pull request by shahor02**
Don't merge, depends on the incomplete https://github.com/AliceO2Group/AliceO2/pull/12970.

@davidrohr I see that the https://github.com/AliceO2Group/AliceO2/pull/12970/files#diff-9dcbbb184115454e0b3e3af138b29ae072ab73bbfbbfb074d5ec6654cd9536cdL27-L41 is not finalized yet. Once finished, will you also add new output to the https://github.com/AliceO2Group/AliceO2/pull/12970/files#diff-78507aa7c5a074a27bb8763c800436d6d7b41a2f0676b3af1eec9a801aacce94L35-L38 ?

Note that I've modified https://github.com/AliceO2Group/AliceO2/pull/12970/files#diff-d491487d2d6fbeadbfdfcae25c40b5b0167772d3f51423012d41f9b9b3507e43L39-L43 to https://github.com/AliceO2Group/AliceO2/compare/dev...shahor02:pr_tpcocc?expand=1#diff-d491487d2d6fbeadbfdfcae25c40b5b0167772d3f51423012d41f9b9b3507e43R38, now it also will profit from the shared and occupancy maps via recocontaner.

### CODE REVIEW

**Comment by davidrohr** [comment]
Thx @shahor02 

> @davidrohr I see that the https://github.com/AliceO2Group/AliceO2/pull/12970/files#diff-9dcbbb184115454e0b3e3af138b29ae072ab73bbfbbfb074d5ec6654cd9536cdL27-L41 is not finalized yet. Once finished, will you also add new output to the https://github.com/AliceO2Group/AliceO2/pull/12970/files#diff-78507aa7c5a074a27bb8763c800436d6d7b41a2f0676b3af1eec9a801aacce94L35-L38 ?

Yes, it is not final yet. I have done some more work, and rebased your commit on my latest update: https://github.com/AliceO2Group/AliceO2/pull/12970

I have added additional output here: https://github.com/AliceO2Group/AliceO2/blob/ee6f9ac6b071101301dc3d30730f354df2b25890/GPU/GPUTracking/Interface/GPUO2InterfaceRefit.h#L89
The logic is:
- If no occupancyMap is provided externally (either from the tracking or from the shared map creator), the constructor of `GPUO2InterfaceRefit` needs the `nHbfPerTf` value to create it internally, if the map is required depending on `--configKeyValues`. If the map is needed but `nHbfPerTf=0` I'll throw a fatal. However, I think this does not affect any of your use cases, but e.g. TPC `CalculatedEdx` uses this internal map creation.
- For the shared map creator, you can call `fillOccupancyMapGetSize` (which also needs `nHbfPerTf`). This will return the required buffer size of the occupancy map in bytes (or 0 in case no map is needed).
  - In case of `fillOccupancyMapGetSize() = 0`, the shared map creator should just send a dummy message of size 0 to make DPL happy. (TPC tracking will eventually do the same, currently it still lacks the empty dummy message if no map is needed.)
  - I propose that in this case of size is 0, the recoContainer should provide `nullptr` as `occupancymap` to the constructor of `GPUO2InterfaceRefit`. This will make sure that in case inconsistent `--configKeyValues` are used, we will not try to access a dummy occupancy map.
  - In case of `fillOccupancyMapGetSize() != 0`, just call `fillSharedClustersAndOccupancyMap` as before, passing in addition the buffer for `ocmap` and the value of `nHbfPerTf`.
  - And obviously also in case of `0`, you still need to call `fillSharedClustersAndOccupancyMap` for the shared cluster map as before, leaving the default arguments `= 0` and `= nullptr` for `ocmap` and `nHbfPerTf`.
> 
> Note that I've modified https://github.com/AliceO2Group/AliceO2/pull/12970/files#diff-d491487d2d6fbeadbfdfcae25c40b5b0167772d3f51423012d41f9b9b3507e43L39-L43 to https://github.com/AliceO2Group/AliceO2/compare/dev...shahor02:pr_tpcocc?expand=1#diff-d491487d2d6fbeadbfdfcae25c40b5b0167772d3f51423012d41f9b9b3507e43R38, now it also will profit from the shared and occupancy maps via recocontaner.

makes sense. I have seen that the TPC `CalcularedEdx` also doesn't use the shared map. Not sure if we should add it there as well: https://github.com/AliceO2Group/AliceO2/blob/c328a12b8288f51917b85322e2cc5b7099c68706/Detectors/TPC/calibration/src/CalculatedEdx.cxx#L48

**Comment by shahor02** [comment]
>     * If no occupancyMap is provided externally (either from the tracking or from the shared map creator), the constructor of `GPUO2InterfaceRefit` needs the `nHbfPerTf` value to create it internally, if the map is required depending on `--configKeyValues`. If the map is needed but `nHbfPerTf=0` I'll throw a fatal. However, I think this does not affect any of your use cases, but e.g. TPC `CalculatedEdx` uses this internal map creation.
> 
Indeed, in all cases the sharing (will be the same with occupancy) maps are provided from the upstream.
The `CalculatedEdx` seems so far not to be used in any code, if it does, I would also provide external data to it also.

>     * For the shared map creator, you can call `fillOccupancyMapGetSize` (which also needs `nHbfPerTf`). This will return the required buffer size of the occupancy map in bytes (or 0 in case no map is needed).

OK, but once you provide the occupancy from the TPC reco or shmap creator workflow, at the moment I don't need to call it, right?

>       * I propose that in this case of size is 0, the recoContainer should provide `nullptr` as `occupancymap` to the constructor of `GPUO2InterfaceRefit`. This will make sure that in case inconsistent `--configKeyValues` are used, we will not try to access a dummy occupancy map.

RecoContaier has gsl::span objects for the sharing and occupancy maps, so, unless assigned from the DPL input, it already provides a `nullptr` for both.

>       * In case of `fillOccupancyMapGetSize() != 0`, just call `fillSharedClustersAndOccupancyMap` as before, passing in addition the buffer for `ocmap` and the value of `nHbfPerTf`.
>       * And obviously also in case of `0`, you still need to call `fillSharedClustersAndOccupancyMap` for the shared cluster map as before, leaving the default arguments `= 0` and `= nullptr` for `ocmap` and `nHbfPerTf`.


> https://github.com/AliceO2Group/AliceO2/blob/c328a12b8288f51917b85322e2cc5b7099c68706/Detectors/TPC/calibration/src/CalculatedEdx.cxx#L48

see above: it is not used anywere.

**Comment by davidrohr** [comment]
> > ```
> > * For the shared map creator, you can call `fillOccupancyMapGetSize` (which also needs `nHbfPerTf`). This will return the required buffer size of the occupancy map in bytes (or 0 in case no map is needed).
> > ```
> 
> OK, but once you provide the occupancy from the TPC reco or shmap creator workflow, at the moment I don't need to call it, right?
> 

I changed what is needed here to obtain the correct size: https://github.com/AliceO2Group/AliceO2/pull/12970/commits/5fbb39c529d8782574195373971e51c167205966
But now we still need to pass in the number of hbf per TF in the shared map creator workflow, i.e. I assume we have to query the GRP there.

**Comment by shahor02** [comment]
Already absorbed to https://github.com/AliceO2Group/AliceO2/pull/12970

**Pull request closed without merging**
