### PR TITLE
ITS threshold calibration workflow - bug fixes and performance enhancements

### PR DESCRIPTION
**Pull request by ezradlesser**
Bug fixes and performance enhancements for the ITS threshold calibration workflow:
- fix "fit" version of threshold extraction;
- switch from `short int` --> `char` for storing hit counts;
- adding command-line options for verbosity and metadata output;
- other minor efficiency changes.

### CODE REVIEW

**Comment by ezradlesser** [comment]
Hi @shahor02 -- are you able to review & merge this PR? We would like to do online testing at P2 tomorrow.
The `build/O2/fullCI` check has failed, but it is not related to our code or changes here. 
Many thanks for your time & help!

**Review by shahor02 — APPROVED** [review]
Hi @ezradlesser 
Merging since you need it for tomorrow, but at the next iteration, please remove the obsolete code you have commented out. Also, in general, we avoid new / delete pairs, preferring std::unique_ptr

**Comment by shahor02** [comment]
failures unrelated.

**Comment by ezradlesser** [comment]
Understood -- thank you @shahor02 !

**Pull request merged**
