### PR TITLE
DPL Analysis: add template to declare index binding equivalence

### PR DESCRIPTION
**Pull request by aalkin**
@jgrosseo this should solve the index problem with versioning, for example

`DECLARE_EQUIVALENT_FOR_INDEX(McParticles, McParticles_001)`

### CODE REVIEW

**Comment by jgrosseo** [comment]
Very nice! Is something still missing as it is in draft?

**Comment by aalkin** [comment]
@jgrosseo it can only be tested together with your versioning modification, it would be easier if you integrate this change there.

**Comment by jgrosseo** [comment]
OK, I'll do that.

**Comment by aalkin** [comment]
@jgrosseo this change should fix the "cannot be used in constexpr" problem, and the declaration itself can be placed outside `o2::aod` namespace, adding `o2::aod::` to the table types, of course.

**Pull request closed without merging**
