### PR TITLE
Raw file writer

### PR DESCRIPTION
**Pull request by gvolpe79**

### CODE REVIEW

**Comment by davidrohr** [comment]
Fine for the GPU symlink changes.

This PR has 197 commits. Not  100% sure whether it was rebased fully correctly, but it seems like just a long development history.
But it shouldn't be merged like this. If you want to keep some history, please squash it down partially to  a reasonable number of commits. Or the whole PR should be squashed when merging.

**Comment by shahor02** [comment]
@gvolpe79 indeed, after applying clang-format, it is better to squash the HMPID to 1 commit (since selective squash would be a nightmare with some many commits) and another one for GPU (though it is unrelated to this topic). I don't see MC->digit converter, was not it supposed to be here?

**Comment by gvolpe79** [comment]
Yes, after I will apply clang I think better to squash everything in 1 commit! Actually, this was my idea. 
Ruben, the MC --> raw data should be there! There is the workflow to convert digit vector in binary HMPID raw data file (HMPID payload)! Is this enough?! Maybe, do you need the conversion starting from digits root file?

**Comment by shahor02** [comment]
Hi @gvolpe79 
Yes, by MC->raw conversion we mean an executable which reads simulated digits root file and converts it to packaged raw data in the format it enters to STFBuilder. I thought I wrote you before that we use https://github.com/AliceO2Group/AliceO2/tree/dev/Detectors/Raw#rawfilewriter to register the links and will them payload, see .e.g. https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/FIT/FT0/simulation/src/digi2raw.cxx for the simplest example entry point.

**Comment by gvolpe79** [comment]
Ruben, yes, indeed you told me, but I understood digit --> raw data conversion as done was enough,  sorry! Anyway, at this stage this is a small step forward, since the conversion is already implemented. We will provide for that soon. Anyway, I would merge this branch as it is.

**Comment by shahor02** [comment]
@gvolpe79 at the moment it complains about the formatting, could you do ``git clang-format HEAD~197``. Perhaps you could squash the GPU links to separate commit (if there are many, I could not identify them) and the rest to 1 commit, then push with -f.

**Comment by gvolpe79** [comment]
Antonio has fixed the clang errors e committed

**Comment by davidrohr** [comment]
The clang errors are stilled not fixed, see the `Check PR with clang-format / build (pull_request_target)` link above.

**Comment by shahor02** [comment]
Hi @gvolpe79,
The https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/5525/601689fa2a8b36d0e5eb8a93d08879d7552ea3fb/build_O2_fullCI/pretty.html gives long list of complaints, mostly coding conventions and modernization, could you please fix those related to HMPID? 
@davidrohr @mconcas why the SMatrixGPU and some other GPU related stuff popped up only now?

**Comment by davidrohr** [comment]
@shahor02 : I think the SMatrixGPU is not really used yet. It is only checked by the codechecker when the file was recompiled in the incremental build. No idea why it happened exactly now.
@mconcas : Could you take care of the code checker warnings in SMatrixGPU?

**Comment by shahor02** [comment]
ok, I see also some of my files appeared there :) Will fix them.

**Comment by gvolpe79** [comment]
yes, I will take care of the HMPID one!

**Comment by shahor02** [comment]
@gvolpe79 thanks, btw, we keep data classes (like digits, clusters, those which participate in DPL messaging) in ``DataFormats/Detectors`` directory (except some old code which also should be soon or late fixed). But this can be done also in other PR, to not complicate even more this one.

**Comment by gvolpe79** [comment]
@shahor02 point taken!

**Comment by mconcas** [comment]
> @shahor02 : I think the SMatrixGPU is not really used yet. It is only checked by the codechecker when the file was recompiled in the incremental build. No idea why it happened exactly now.
> @mconcas : Could you take care of the code checker warnings in SMatrixGPU?

Hi, I'll take care of smatrixgpu!

**Comment by davidrohr** [comment]
Remaining codechecker issues are unrelated, I think this should be merged asap now and further cleanup can be done later.
Will squash-merge when all pending CIs are done.

**Pull request merged**
