### PR TITLE
Moved data definition classes to DetaFormats/... directories

### PR DESCRIPTION
**Pull request by shahor02**
To avoid circular dependencies moved some classes from O2/Detectors/Base to O2/DetaFormats/...
Also some math utilities were moved to O2/Common/MathUtils as well as constants moved to O2/Common/Constants
The massive change of multiple files is mostly due to the fixes of headers and namespaces

UPDATE: 
1) adding squashed commit from few fixes needed for the TPC/ITS matching (they were based on this initial PR and were diverging due to this PR being modified to be compatible with evolving dev...)
2) applied clang-format to all touched files

Below is the summary of moves and files which were modified.

````
	renamed:    Detectors/Base/include/DetectorsBase/Constants.h -> Common/Constants/include/CommonConstants/MathConstants.h
	renamed:    Detectors/Base/include/DetectorsBase/Utils.h -> Common/MathUtils/include/MathUtils/Utils.h
	new file:   DataFormats/Detectors/CMakeLists.txt
	new file:   DataFormats/Detectors/Common/CMakeLists.txt
	renamed:    Detectors/Base/include/DetectorsBase/AlignParam.h -> DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/AlignParam.h
	renamed:    Detectors/Base/include/DetectorsBase/DetID.h -> DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/DetID.h
	renamed:    Detectors/Base/include/DetectorsBase/DetMatrixCache.h -> DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/DetMatrixCache.h
	renamed:    Detectors/Base/src/AlignParam.cxx -> DataFormats/Detectors/Common/src/AlignParam.cxx
	renamed:    Detectors/Base/src/DetID.cxx -> DataFormats/Detectors/Common/src/DetID.cxx
	renamed:    Detectors/Base/src/DetMatrixCache.cxx -> DataFormats/Detectors/Common/src/DetMatrixCache.cxx
	new file:   DataFormats/Detectors/Common/src/DetectorsCommonDataFormatsLinkDef.h
	renamed:    Detectors/Base/test/testDetID.cxx -> DataFormats/Detectors/Common/test/testDetID.cxx
	new file:   DataFormats/Reconstruction/CMakeLists.txt
	renamed:    Detectors/Base/include/DetectorsBase/BaseCluster.h -> DataFormats/Reconstruction/include/ReconstructionDataFormats/BaseCluster.h
	renamed:    Detectors/Base/include/DetectorsBase/Track.h -> DataFormats/Reconstruction/include/ReconstructionDataFormats/Track.h
	renamed:    Detectors/Base/src/BaseCluster.cxx -> DataFormats/Reconstruction/src/BaseCluster.cxx
	new file:   DataFormats/Reconstruction/src/ReconstructionDataFormatsLinkDef.h
	renamed:    Detectors/Base/src/Track.cxx -> DataFormats/Reconstruction/src/Track.cxx
	renamed:    Detectors/Base/include/DetectorsBase/TrackReference.h -> DataFormats/simulation/include/SimulationDataFormat/TrackReference.h
	renamed:    Detectors/Base/src/TrackReference.cxx -> DataFormats/simulation/src/TrackReference.cxx
	renamed:    Detectors/Base/src/BaseLinkDef.h -> Detectors/Base/src/DetectorsBaseLinkDef.h
        renamed:    DataFormats/TPC -> DataFormats/Detectors/TPC


	modified:   Common/Constants/include/CommonConstants/MathConstants.h
	modified:   Common/MathUtils/CMakeLists.txt
	modified:   Common/MathUtils/include/MathUtils/Cartesian3D.h
	modified:   Common/MathUtils/include/MathUtils/Utils.h
	modified:   Common/MathUtils/src/Cartesian3D.cxx
	modified:   Common/MathUtils/src/MathUtilsLinkDef.h
	modified:   Common/MathUtils/test/testCartesian3D.cxx
	modified:   Common/Utils/test/testTreeStream.cxx
	modified:   DataFormats/CMakeLists.txt
	modified:   DataFormats/Detectors/Common/CMakeLists.txt
	modified:   DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/AlignParam.h
	modified:   DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/DetID.h
	modified:   DataFormats/Detectors/Common/include/DetectorsCommonDataFormats/DetMatrixCache.h
	modified:   DataFormats/Detectors/Common/src/AlignParam.cxx
	modified:   DataFormats/Detectors/Common/src/DetID.cxx
	modified:   DataFormats/Detectors/Common/src/DetMatrixCache.cxx
	modified:   DataFormats/Detectors/Common/test/testDetID.cxx
	modified:   DataFormats/Parameters/include/DataFormatsParameters/GRPObject.h
	modified:   DataFormats/Parameters/src/GRPObject.cxx
	modified:   DataFormats/Reconstruction/include/ReconstructionDataFormats/BaseCluster.h
	modified:   DataFormats/Reconstruction/include/ReconstructionDataFormats/Track.h
	modified:   DataFormats/Reconstruction/src/BaseCluster.cxx
	modified:   DataFormats/Reconstruction/src/ReconstructionDataFormatsLinkDef.h
	modified:   DataFormats/Reconstruction/src/Track.cxx
	modified:   DataFormats/simulation/CMakeLists.txt
	modified:   DataFormats/simulation/include/SimulationDataFormat/MCTrack.h
	modified:   DataFormats/simulation/include/SimulationDataFormat/Stack.h
	modified:   DataFormats/simulation/include/SimulationDataFormat/TrackReference.h
	modified:   DataFormats/simulation/src/SimulationDataLinkDef.h
	modified:   DataFormats/simulation/src/Stack.cxx
	modified:   DataFormats/simulation/src/TrackReference.cxx
	modified:   DataFormats/simulation/test/MCTrack.cxx
	modified:   Detectors/Base/CMakeLists.txt
	modified:   Detectors/Base/include/DetectorsBase/GeometryManager.h
	modified:   Detectors/Base/include/DetectorsBase/Propagator.h
	modified:   Detectors/Base/src/Detector.cxx
	modified:   Detectors/Base/src/DetectorsBaseLinkDef.h
	modified:   Detectors/Base/src/GeometryManager.cxx
	modified:   Detectors/Base/src/Propagator.cxx
	modified:   Detectors/ITSMFT/ITS/base/include/ITSBase/GeometryTGeo.h
	modified:   Detectors/ITSMFT/ITS/base/src/GeometryTGeo.cxx
	modified:   Detectors/ITSMFT/ITS/macros/test/CheckClusters.C
	modified:   Detectors/ITSMFT/ITS/macros/test/CheckDigits.C
	modified:   Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
	modified:   Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CATracker.h
	modified:   Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CAaux.h
	modified:   Detectors/ITSMFT/ITS/reconstruction/include/ITSReconstruction/CookedTrack.h
	modified:   Detectors/ITSMFT/ITS/reconstruction/src/CATracker.cxx
	modified:   Detectors/ITSMFT/ITS/reconstruction/src/CATrackingStation.cxx
	modified:   Detectors/ITSMFT/ITS/reconstruction/src/CAaux.cxx
	modified:   Detectors/ITSMFT/ITS/reconstruction/src/ClustererTask.cxx
	modified:   Detectors/ITSMFT/ITS/reconstruction/src/CookedTrack.cxx
	modified:   Detectors/ITSMFT/ITS/reconstruction/src/CookedTracker.cxx
	modified:   Detectors/ITSMFT/ITS/reconstruction/src/CookedTrackerTask.cxx
	modified:   Detectors/ITSMFT/ITS/reconstruction/src/TrivialClustererTask.cxx
	modified:   Detectors/ITSMFT/ITS/simulation/include/ITSSimulation/Detector.h
	modified:   Detectors/ITSMFT/ITS/simulation/src/DigitizerTask.cxx
	modified:   Detectors/ITSMFT/MFT/base/include/MFTBase/GeometryTGeo.h
	modified:   Detectors/ITSMFT/MFT/base/src/GeometryTGeo.cxx
	modified:   Detectors/ITSMFT/MFT/macros/CheckClusters.C
	modified:   Detectors/ITSMFT/MFT/macros/CheckDigits.C
	modified:   Detectors/ITSMFT/MFT/reconstruction/src/ClustererTask.cxx
	modified:   Detectors/ITSMFT/MFT/simulation/include/MFTSimulation/Detector.h
	modified:   Detectors/ITSMFT/MFT/simulation/src/DigitizerTask.cxx
	modified:   Detectors/ITSMFT/common/base/include/ITSMFTBase/GeometryTGeo.h
	modified:   Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/Cluster.h
	modified:   Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/Chip.h
	modified:   Detectors/ITSMFT/common/simulation/include/ITSMFTSimulation/SimulationAlpide.h
	modified:   Detectors/ITSMFT/common/simulation/src/Chip.cxx
	modified:   Detectors/ITSMFT/common/simulation/src/Digitizer.cxx
	modified:   Detectors/ITSMFT/test/HitAnalysis/src/HitAnalysis.cxx
	modified:   Detectors/TOF/simulation/src/Detector.cxx
	modified:   Detectors/TOF/simulation/src/DigitizerTask.cxx
	modified:   Detectors/TPC/reconstruction/include/TPCReconstruction/TrackTPC.h
	modified:   Detectors/TPC/reconstruction/macro/convertTracks.C
	modified:   Detectors/TPC/reconstruction/macro/runCATracking.C
	modified:   Detectors/TPC/reconstruction/macro/runCATrackingClusterNative.C
	modified:   Detectors/TPC/reconstruction/macro/testTracks.C
	modified:   Detectors/TPC/reconstruction/src/TPCCATracking.cxx
	modified:   Detectors/TPC/simulation/macro/testHitsDigitsClusters.C
	modified:   Framework/DebugGUI/src/imgui_draw.cpp
	modified:   cmake/O2Dependencies.cmake
	modified:   macro/CheckClusters_mft.C
	modified:   macro/CheckDigits_mft.C
	modified:   macro/o2sim.C
````

### CODE REVIEW

**Comment by davidrohr** [comment]
Hu  @shahor02 , perhaps we should move DataFormats/TPC to DataFormats/Detectors/TPC as well then?

**Comment by shahor02** [comment]
@davidrohr: yes, and also TrackTPC

**Comment by sawenzel** [comment]
This is probably ok. 
a) Find names like `DetecorCommonDataFormats` slightly longuish.
b) still unclear how to map to namespace names?
c) We now have a clang-format checker which screams on changed codes lines; Could you try to take a look at the travis build log (under clang-format) and see if you can incorporate the suggested formatting changes. (Can be done locally using `git clang-format` tool as well).

**Comment by shahor02** [comment]
Hi @sawenzel 
OK, I've applied clang-format to all affected files. Funnily, the Travis check complains about 2 files passed via clang-format...
Since I had some patches in the branch derived from this one, they would completely diverge after reformatting, so I've squashed and added them here (before formatting).
Cheers, 
 Ruben

**Comment by davidrohr** [comment]
For me this is fine. I would merge it soon, since it produces a lot of conflicts with every update, and I am waiting with my next PR until this is in.

**Pull request merged**
