### PR TITLE
add fill scheme info in TOF event time checker

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
Sorry for all recent changes.
Now PR is frozen.

@chiarazampolli @njacazio @ercolessi 
Calibrations are now loaded from ccdb at clusterization level for channel-offsets and time-slewing (via TOF api).

checked on EPN with 100 TF and everything went fine.

Just I got problem to access ccdb with an active alien token with a dpl, no problem with a macro.
Was this behavior already seen (see below)?

[3578963:TOFClusterer]: The lines below might hint at the cause of the crash.
[3578963:TOFClusterer]: You may get help by asking at the ROOT forum https://root.cern.ch/forum
[3578963:TOFClusterer]: Only if you are really convinced it is a bug in ROOT then please submit a
[3578963:TOFClusterer]: report at https://root.cern.ch/bugs Please post the ENTIRE stack trace
[3578963:TOFClusterer]: from above as an attachment in addition to anything else
[3578963:TOFClusterer]: that might help us fixing this issue.
[3578963:TOFClusterer]: ===========================================================
[3578963:TOFClusterer]: #6  0x00007f0ed0c63b31 in TJAlienCredentials::checkCertValidity(char const*) () from /home/fnoferin/alice/sw/slc8_x86-64/libjalienO2/0.1.3-local1/lib/libjalienO2.so
[3578963:TOFClusterer]: #7  0x00007f0ed0c65298 in TJAlienCredentials::selectPreferedCredentials() () from /home/fnoferin/alice/sw/slc8_x86-64/libjalienO2/0.1.3-local1/lib/libjalienO2.so
[3578963:TOFClusterer]: #8  0x00007f0ed1e39370 in o2::ccdb::CcdbApi::init (this=0x7f0ed3564040 <o2::ccdb::BasicCCDBManager::instance()::inst>, host=...) at /home/fnoferin/alice/sw/SOURCES/O2/dev/0/CCDB/src/CcdbApi.cxx:78

**Comment by chiarazampolli** [comment]
Ciao @noferini , 

Great that everything works!

Yes, there is some issue with SSL, being investigated (also QC does not work if you have a token). Please, be patient with it... 

Chiara

**Comment by noferini** [comment]
> Ciao @noferini ,
> 
> Great that everything works!
> 
> Yes, there is some issue with SSL, being investigated (also QC does not work if you have a token). Please, be patient with it...
> 
> Chiara

Good. Then it is not a my problem.
I have a workaround for that so I can continue my tests.
Thanks for the confirmation.

**Comment by chiarazampolli** [comment]
Note that the CVMFS distribution worked (at least till some days ago, then I did not try again).

**Comment by noferini** [comment]
Hi @shahor02 
if you don't have any objection can you approve this PR?

**Review by shahor02 — APPROVED** [review]
Hi @noferini 

The PR is fine, but could you please clarify the meaning of the https://github.com/AliceO2Group/AliceO2/blob/df02068c8fe89b0798a3c29caf47a746c02b32de/Detectors/TOF/base/include/TOFBase/Utils.h#L49 ? I see it is not the vector of the interacting bunches as reported by the LHC but something you compute from TOF signal. Why?

**Pull request merged**
