### PR TITLE
Adding WF for calibration based on diagnostic words

### PR DESCRIPTION
**Pull request by chiarazampolli**
This is the workflow to propagate to the CCDB the diagnostic words from decoding. 

Example usage:

`o2-calibration-data-generator-diagnostic-workflow --max-timeframes 10 | o2-calibration-tof-diagnostic-workflow  | o2-calibration-ccdb-populator-workflow --ccdb-path="http://localhost:8080"`

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hi @noferini , 

The CCDB entries that the workflow adds are valid till infinity to always have an entry that is valid. I have a doubt about this which we should check, namely whether the time slots are closed for sure in increasing order. If this is the case, then it should be not an issue. 

Chiara

**Comment by noferini** [comment]
> Hi @noferini ,
> 
> The CCDB entries that the workflow adds are valid till infinity to always have an entry that is valid. I have a doubt about this which we should check, namely whether the time slots are closed for sure in increasing order. If this is the case, then it should be not an issue.
> 
> Chiara

In principle it shouldn't be a problem.
The information will be used only in simulation.
Let see, in case we will limit the validity

**Review by shahor02 — APPROVED** [review]
This looks fine for me, @noferini shall I wait for your review?

**Review by noferini — APPROVED** [review]
It looks fine

**Pull request merged**
