### PR TITLE
SIMD v2 of FT0 Digitizer

### PR DESCRIPTION
**Pull request by hcab14**
This PR implements an [idea of @sawenzel](https://github.com/AliceO2Group/AliceO2/pull/2859#discussion_r372306215)

Speedup is about a factor of 4-5 _w.r.t._ previous version.

I have verified that for 100 pp events the same charges and times are produced.
@mslupeck please double-check that it indeed provides the same output as before.

### CODE REVIEW

**Comment by mslupeck** [comment]
Hi @hcab14 
Thanks for this update. I haven't checked the exact speed-up factor, but it is noticeably faster than before. I can confirm the quality of the results has not changed (within the 100 pp-event statistics).

Since you will have to restart the tests anyway because the CPV test failed, could you also implement change of gain in DigitizationParameters from:
`  static constexpr float mPmtGain = 4.21e6;              // value for PMT R5924-70 at 0.5T -> should be adjusted to the actually used gain`
to 
`  static constexpr float mPmtGain = 5e4;              // value for PMT R5924-70 at default FV0 gain`

**Comment by sawenzel** [comment]
DigitShareBefore
DigitizerShareAfter

Good work! The digitization share of FV0 is now very reasonable!

**Comment by mslupeck** [comment]
Thanks @hcab14 - great work!

**Comment by hcab14** [comment]
Thanks. 

The same optimizations can be applied to the FDD Digitizer as well. Currently virtually all digitization algorithms for FV0 and for FDD are the same. In my opinion the common parts of the digitizers for these two detectors should use common code. 

How did you measure the digitizer run times?

**Comment by sawenzel** [comment]
This is run in my nightly benchmarks done by script `prodtests/sim_performance_test.sh` with 100 pythia8 events.

**Comment by jotwinow** [comment]
well done!

**Pull request merged**
