### PR TITLE
DPL: handle region notifications as required by GPU processing

### PR DESCRIPTION
**Pull request by ktf**
* Adds an option, --expected-region-callbacks <N>, to wait for
  enough callback before going to start.
* Deliver callbacks on the main thread, always.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr

**Comment by davidrohr** [comment]
@ktf : thx, will check on Monday. But this seems to break many framework ctests and also the full system test fails in the FullCI. Perhaps it is not yet fully working?

**Comment by ktf** [comment]
I will check. I only tested the diamond topology.

**Comment by ktf** [comment]
Ok, I am missing the default argument. If you pass the option explicitly it should work. Fix coming.

**Comment by ktf** [comment]
I fixed it. Is the fullCI error actually related? The option is not really enabled.

**Comment by davidrohr** [comment]
The FullCI error is no different compared to the one before, I think this one now is not related to this PR.
I have seen it a couple of times recent, it is some segfault in the MFT reconstruction, but yet I have not been able to reproduce it locally.

**Review by davidrohr — DISMISSED** [review]
THx, both the callbacks coming from the main thread as well as the `--expected-region-callbacks` work as expected

**Comment by ktf** [comment]
Clang format merged.

**Pull request merged**
