### PR TITLE
Modify internals of RecoContainer, add fwd-declared getters + support for S-vertices (also in InputHelper)

### PR DESCRIPTION
**Pull request by shahor02**
@rpezzi this may create some conflicts with your PR, but better to cleanup it now.

### CODE REVIEW

**Comment by davidrohr** [comment]
I didn't try it yet, but looks good. I'll try later with the GPU workflow and gpu display if all inputs still work as before. Then I would merge it ASAP and clean up the TRD stuff later.

**Comment by davidrohr** [comment]
OK, actually I did a quick test just now, and in the GPU display I now see less matches to TOF. Something has changed. Will have a look later, but now really have to proceed with my CHEP slides...

To redroduce: Run
```
--read-from-files --display-clusters ITS,TPC,TRD,TOF --display-tracks TPC,ITS,ITS-TPC,TPC-TRD,ITS-TPC-TRD,TPC-TOF,ITS-TPC-TOF --configKeyValues "GPU_global.continuousMaxTimeBin=2000"
```
before and after this PR and press 8 to show the tracks.

**Comment by shahor02** [comment]
Is there a way to visualize TOF-related tracks only? I've tried with 
````
o2-gpu-display --read-from-files --display-clusters "TOF"  --display-tracks "TPC-TOF,ITS-TPC-TOF" --configKeyValues "GPU_global.continuousMaxTimeBin=2000"
```` 
but it shows TPC clusters only...

**Comment by davidrohr** [comment]
> Is there a way to visualize TOF-related tracks only?

I assume you meant "it shows TOF clusters only"?

Currently, I can show only tracks when there are also TPC tracks.
And requesting tracks without the corresponding cluster might actually crash, I'll have to fix that. Also higher tracks without the lower tracks might crash, i.e. ITS-TPC-TOF tracks currently require also ITS tracks.
What you can do is
```
o2-gpu-display --read-from-files --display-clusters "TPC,TOF"  --display-tracks "TPC,TPC-TOF" --configKeyValues "GPU_global.continuousMaxTimeBin=2000"
```

**Comment by shahor02** [comment]
@davidrohr indeed, ITSTPCTOF was not correctly attached, thanks for spotting.
I noticed that in https://github.com/AliceO2Group/AliceO2/blob/01b8b2e983907665c2b8c1c2b1055f00963e7fe5/DataFormats/Detectors/GlobalTracking/src/RecoContainer.cxx#L460-L463 you are dereferencing the pointer which will crash if there is no MC loaded. Why not returning just a pointer on MCTruthContainer? This is what I did for ITS and TOF clusters.

**Comment by davidrohr** [comment]
> you are dereferencing the pointer which will crash if there is no MC loaded. Why not returning just a pointer on MCTruthContainer?

Yes sure, we can return a pointer. (Did I actually add this getter? Don't remember...)
How is it for the TPC? Might be the same. The TPC input container might also have a nullptr to the labels.

Are you changing it here or shall I do it?

**Comment by shahor02** [comment]
The TPC clusters MClabels are actually not attached to RecoContainer, not sure they will be used in the global workflows, but will add, just in case, and change the ref to pointer for the TRD MC.

**Comment by davidrohr** [comment]
Actually they are already loaded, just not exposed directly. You can get the pointer to the container via `inputsTPCclusters->clusterIndex.clustersMCTruth`

**Review by davidrohr — APPROVED** [review]

**Comment by davidrohr** [comment]
#6128, which contains this one, passed the FullCi, so this one must be ok. merging, to go ahead.

**Pull request merged**
