### PR TITLE
Fixes in TPC-ITS matching for multi-TF processing

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
@MichaelLettrich @ktf  looks like the Travis CI again fails to report, the [link](https://github.com/AliceO2Group/AliceO2/pull/3456/checks?check_run_id=620887779) show 2 tests, the 1st one (failed) unrelated to this PR.

**Comment by ktf** [comment]
Travis is actually complaining:

https://travis-ci.com/github/AliceO2Group/AliceO2/jobs/323621480

Can it be fixed?

**Comment by shahor02** [comment]
@ktf this is exactly what I meant saying that the Travis CI failure report is not related to my PR: it complains about the file ``DataFormats/Detectors/ITSMFT/MFT/include/DataFormatsMFT/TrackMFT.h`` which is not touched by this PR.

**Comment by shahor02** [comment]
@ktf : are you panning to check what's going on here or I merge as it is (I guess the logs will disappear)

**Comment by ktf** [comment]
For the record, I did check last night but I could not understand what was going on (apart from travis not reporting the result and not allowing me to restart, I imagine due to some glitch). The hash used for the comparison was a bit in the past (we use the branch-point of the PR) so maybe git-clang-format was confused by taking some merge bifurcation the wrong way. Notice also that if I do by hand:

```
clang-format DataFormats/Detectors/ITSMFT/MFT/include/DataFormatsMFT/TrackMFT.h
```

it's correct. Bottomline, I've no clue what is going on and I would blame git-clang-format logic and some merge commit.

**Pull request merged**
