### PR TITLE
test version of the TPC inverse transformation

### PR DESCRIPTION
**Pull request by sgorbuno**
a test version of the TPC inverse transformation

### CODE REVIEW

**Comment by davidrohr** [comment]
@sgorbuno : I am testing this now. I needed the attached patch to compile it for GPU and standalone, and I see the following warnings:
```
In file included from /home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastTransform.h:21,
                 from /home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastTransform.cxx:20:
/home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.h: In member function ‘void o2::gpu::TPCFastSpaceChargeCorrection::getCorrectionInvCorrectedX(int, int, float, float, float&) const’:
/home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:233:18: warning: unused variable ‘rowInfo’ [-Wunused-variable]
  233 |   const RowInfo& rowInfo = getRowInfo(row);
      |                  ^~~~~~~
/home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.h: In member function ‘void o2::gpu::TPCFastSpaceChargeCorrection::getCorrectionInvUV(int, int, float, float, float&, float&) const’:
/home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:247:18: warning: unused variable ‘rowInfo’ [-Wunused-variable]
  247 |   const RowInfo& rowInfo = getRowInfo(row);
      |                  ^~~~~~~
In file included from /home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.cxx:16:
/home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.h: In constructor ‘o2::gpu::TPCFastSpaceChargeCorrection::TPCFastSpaceChargeCorrection()’:
/home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:178:17: warning: ‘o2::gpu::TPCFastSpaceChargeCorrection::mSliceRowInfoPtr’ will be initialized after [-Wreorder]
  178 |   SliceRowInfo* mSliceRowInfoPtr; //! (transient!!) pointer to SliceRowInfo array inside the mFlatBufferPtr
      |                 ^~~~~~~~~~~~~~~~
/home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.h:175:15: warning:   ‘o2::gpu::TPCFastSpaceChargeCorrection::SplineType* o2::gpu::TPCFastSpaceChargeCorrection::mScenarioPtr’ [-Wreorder]
  175 |   SplineType* mScenarioPtr; //! (transient!!) pointer to spline scenarios
      |               ^~~~~~~~~~~~
/home/qon/alice/O2/GPU/TPCFastTransformation/TPCFastSpaceChargeCorrection.cxx:27:1: warning:   when initialized here [-Wreorder]
   27 | TPCFastSpaceChargeCorrection::TPCFastSpaceChargeCorrection()
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

[transform.patch.tar.gz](https://github.com/AliceO2Group/AliceO2/files/4617637/transform.patch.tar.gz)
Could you fix these?

**Comment by davidrohr** [comment]
Using only the old features, it works for me and reproduces the same results in tracking at the same performance or slightly faster, good so far.

**Comment by sgorbuno** [comment]
@davidrohr 
> [transform.patch.tar.gz](https://github.com/AliceO2Group/AliceO2/files/4617637/transform.patch.tar.gz)
> Could you fix these?

I've added the patch and fixed the warnings

**Comment by sgorbuno** [comment]
@davidrohr :  Hi David, I have added methods getMaxDriftTime(..) to get the highest possible drift time for slice; slice+row; slice+row+pad.

**Comment by davidrohr** [comment]
@sgorbuno : The fast transformation tests are failing, so I assume something is still wrong with the new version. Could you have a look?

**Comment by davidrohr** [comment]
@sgorbuno : The CI is failing also with the new version. Could you have a look?

**Comment by davidrohr** [comment]
@sgorbuno : Could you include the following patch, which fixes the compilation problems for me.

[new.patch.tar.gz](https://github.com/AliceO2Group/AliceO2/files/4651591/new.patch.tar.gz)

**Comment by davidrohr** [comment]
@sgorbuno : Could you remove the `vertexTime` parameter from the `getMaxDriftTime` functions. It is anyway only an additive offset, and what I want is the actual drift time. Works for me now by setting `vertexTime` to 0, but I think we can remove it completely.

**Comment by sgorbuno** [comment]
> Could you remove the `vertexTime` parameter from the `getMaxDriftTime` functions. 

Ok, did it!

**Review by davidrohr — APPROVED** [review]
Did some tests and so far looks good and also compiles correctly on the GPU. Are you done, or do you still want do change something?

**Comment by sgorbuno** [comment]
@davidrohr  I'm done. It needs some cleanup and more tests, but for now, it is ok, I think.

**Pull request merged**
