### PR TITLE
remove TPCITS dependence of other matchers

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
@TimoWilken do you understand why o2-dataflow CI is red? I don't see any error message in the log (fullCI problem is clear, it regularly fails on the simulation)

**Comment by TimoWilken** [comment]
That's something I'm working on fixing at the moment. In the meantime, I've restarted the check.

**Comment by shahor02** [comment]
Thanks @TimoWilken , but now it produces a cryptic `aliDoctor error`.

@sawenzel were you able to reproduce the problem in the simulation, causing the failure in the fullCI? Or is there a chance to extract the `o2sim_mergerlog`, `o2sim_serverlog` and  `o2sim_workerlog0` from the failing fullCI ?

**Comment by shahor02** [comment]
errors unrelated, merging

**Pull request merged**
