### PR TITLE
FIT digitizer and reconstruction

### PR DESCRIPTION
**Pull request by AllaMaevskaya**
Now it ready to add continuous time frame

### CODE REVIEW

**Comment by shahor02** [comment]
Code looks ok for me, just a question: the MCLabel is implemented but is not used/compiled. Is the file added by accident?

**Comment by AllaMaevskaya** [comment]
Hello
MClabel.C was implemented but then  decided not to use MC information - it is not useful for Cherenkov's photons. It can be removed

**Comment by sawenzel** [comment]
Closing this in favour of #1149 where

a) I removed accidentially added files 
b) cleaned up the commit history (containing lots of cf; clang-format; bug-fix commits)
c) removed unused MCLabel class file

**Comment by AllaMaevskaya** [comment]
Thank you

**Pull request closed without merging**
