### PR TITLE
Its-gpu: add tracklet finding and cell finding on GPU (HIP+NVIDIA)

### PR DESCRIPTION
**Pull request by mconcas**
To do before merging:

- [x] Fix: `[ERROR] Exception caught: std::bad_alloc: hipErrorOutOfMemory: hipErrorOutOfMemory` error running on HIP
- [x]  Fix: eternally stuck at `thrust::unique()` call in hip -> does not occur on MI50
- [x] Remove the unneeded adaptations to CPU code
- [x] Validate MC labels creation
- [x] Thrust duplicate removal
- [x] Add Cell finding on GPU
- [x] Fix Cell finding on HIP
- [x] Refactorize passing parameters to kernels
- [x] Fix full gpu tracking

### CODE REVIEW

**Comment by mconcas** [comment]
@davidrohr: this is finally ready for review

**Comment by davidrohr** [comment]
ok, will have a look, but I'll postpone merging until after the EPN SW update on Wednesday, in order not to pull in more large changes.

**Comment by mconcas** [comment]
> ok, will have a look, but I'll postpone merging until after the EPN SW update on Wednesday, in order not to pull in more large changes.

Sure, I'd also wait for #9374 as per @shahor02 request.

**Comment by mconcas** [comment]
Hi @TimoWilken, some tests seem not to have no space left on device, just for your knowledge.

**Comment by davidrohr** [comment]
@mconcas : I merged the other PR. Could you rebase this one again :)

**Comment by mconcas** [comment]
> @mconcas : I merged the other PR. Could you rebase this one again :)

thanks, yep I'm doing it

**Comment by mconcas** [comment]
@davidrohr ok, this has been rebased. It can be merged upon green CI.

CC-ing @mpuccio

**Comment by davidrohr** [comment]
Compiles and runs fine with me, will merge later today.

**Pull request merged**
