### PR TITLE
DQ-related Analysis: add PID variables in reduced info tables.

### PR DESCRIPTION
**Pull request by dsekihat**
add PID variables in reduced info tables

### CODE REVIEW

**Comment by iarsene** [comment]
Hi Jan-Fiete,
Just in case, i just want to mention that i had a look at this PR and from the DQ side this is fine. Daiki's work is something we agreed and planned in the O2 DQ group.
Cheers, Ionut

**Comment by jgrosseo** [comment]
It's fine. Please check the clang formatting

**Comment by dsekihat** [comment]
Hello @jgrosseo ,

This PR seems stuck for 4-5 days.
Could you tell me what to do from my side, please?
I am sorry to disturb you.
As this is my first PR on O2, I do not know approval procedure.

cheers, Daiki

**Comment by jgrosseo** [comment]
The tests didn't run as this is your first commit. In the future this will happen right away. I just merged @iarsene PR, which created a conflict here unfortunately. So you need to resolve this, and push it to your branch. The PR will be updated automatically.

**Comment by dsekihat** [comment]
Oh, I see. Thank you for explanations.

**Comment by jgrosseo** [comment]
Somehow this did not resolve the conflict. Please check

**Comment by jgrosseo** [comment]
@ktf mac seems stuck, and the o2 failure unrelated. Do you confirm? Then I merge this.

**Comment by dsekihat** [comment]
Hello, merging this PR is still blocked. Please let me know, if I have to fix something.

**Pull request merged**
