### PR TITLE
Raw reader cru

### PR DESCRIPTION
**Pull request by wiechula**
* Add new raw data reader for decoding raw data taken with the CRU
* Minor beautifications

### CODE REVIEW

**Comment by wiechula** [comment]
Hi @dberzano ,
it seems that the `build/o2checkcode/o2` fails in 
`run_O2CodeChecker.py -clang-tidy-binary /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/o2codechecker/master-2/bin/O2codecheck '-header-filter=.*SOURCES.*' '-checks=-*,modernize-*,-modernize-use-default,-modernize-pass-by-value,-modernize-use-auto,-modernize-use-bool-literals,-modernize-use-using,-modernize-loop-convert,-modernize-use-bool-literals,-modernize-make-unique,aliceO2-member-name'}}`
with error messages like
```/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/TPC/base/include/TPCBase/CRU.h:25:7: error: use '= default' to define a trivial default constructor [modernize-use-equals-default]
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/TPC/base/include/TPCBase/DigitPos.h:24:3: error: use '= default' to define a trivial default constructor [modernize-use-equals-default]
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/TPC/base/include/TPCBase/FECInfo.h:21:5: error: use '= default' to define a trivial default constructor [modernize-use-equals-default]
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/TPC/base/include/TPCBase/PadPos.h:33:5: error: use '= default' to define a trivial default constructor [modernize-use-equals-default]
...
```

However, all of the mentioned files seem to be includes in the modified code. I'm not sure what to do about this. I can fix the reported issues, but this would be logically a different pull request.

Is it possible to run this locally?

Cheers,
Jens

**Comment by wiechula** [comment]
Hi @dberzano,
can you help with the question above?

Cheers,
Jens

**Comment by ktf** [comment]
What's the status of this PR? Is it still relevant?

**Comment by wiechula** [comment]
Yes, it's still relevant.
I'm updating my O2 and will rebase to dev. If everything still compiles, then I'll remove the WIP to merge it.

**Comment by wiechula** [comment]
As far as I can see the code check errors are not related to this PR. So from my side this can be merged.

**Comment by wiechula** [comment]
@sawenzel , if you don't have comments, could you please merge.

**Pull request merged**
