### PR TITLE
Adapt DataInputDirector to the new AO2D file format, which includes a subdirectory TF_%d per time frame

### PR DESCRIPTION
**Pull request by pbuehler**
The changes have been tested with simple cases. Further testing is ongoing.

### CODE REVIEW

**Comment by jgrosseo** [comment]
test_Framework_test_DataInputDirector  fails, is this due to the missing adaptation in the writer?

**Comment by pbuehler** [comment]
Not really, but I propose to disable the test for the moment and I will have to write new tests for reader/writer.

**Comment by jgrosseo** [comment]
The conversion trains are running (96-98). Most likely we can merge this tonight.

**Comment by jgrosseo** [comment]
Had passed tests before I resolved merge conflict which was just changing a comment. Merging now.

**Pull request merged**
