### PR TITLE
Optional TTL timer for event generator

### PR DESCRIPTION
**Pull request by sawenzel**
Needed for hyperloop operation.

### CODE REVIEW

**Comment by sawenzel** [comment]
@jgrosseo

**Review by jgrosseo — APPROVED** [review]
Excellent. Thank you!

**Comment by jgrosseo** [comment]
I have an unrelated comment to the original PR:
Would it be worth to have a
`Configurable<std::vector<std::string>>` for confKeyValues ?

That configurable type exists already.

**Comment by sawenzel** [comment]
> I have an unrelated comment to the original PR: Would it be worth to have a `Configurable<std::vector<std::string>>` for confKeyValues ?
> 
> That configurable type exists already.

I do have this option already in some sense and it works like elsewhere in simulation: configKeyValues are given as "A.x=1;B.y=foo" (so ; separated). Would this be different with `Configurable<std::vector<std::string>>` ?

**Comment by jgrosseo** [comment]
It depends how we want to have it on Hyperloop. The current one would appear as one string field only. The one with the vector would appear like this:
image

**Comment by sawenzel** [comment]
> It depends how we want to have it on Hyperloop. The current one would appear as one string field only. The one with the vector would appear like this: image

Ok fair enough. We can see how to do this. Would decouple it from this PR.

**Pull request merged**
