### PR TITLE
Reserve memory for tables before filling

### PR DESCRIPTION
**Pull request by nburmaso**
In continuation of #11278

### CODE REVIEW

**Comment by nburmaso** [comment]
Dear @ddobrigk, @ktf, @pzhristov, @sawenzel,
Could you please check if the changes are fine with you?

**Comment by ktf** [comment]
Hi, without actually trying the PR, your changes look correct to me.

**Comment by sawenzel** [comment]
@nburmaso : Have you tested this in an actual (MC) workflow?

**Comment by nburmaso** [comment]
Hi @sandro, yes I did test this modified version with the sim_challenge.sh MC. Should I test it with one of the DPG production scripts as well?

**Comment by nburmaso** [comment]
Fixed some errors in tables versions.

It seems that it is not possible to use predefined table descriptions from the datamodel (as Giulio proposed in #11278) 

e.g. [for McCollisionLabels the description is MCCOLLISLABEL](https://github.com/AliceO2Group/AliceO2/blob/bf993cac605003b3ccb5563bfe6a93173be6d88a/Framework/Core/include/Framework/AnalysisDataModel.h#L1461), so the name in AO2D file would be O2mccollislabel, not O2mccollisionlabel. For the moment this table is added to outputs like this `outputs.emplace_back(OutputLabel{"McCollisionLabels"}, "AOD", "MCCOLLISIONLABEL", 0, Lifetime::Timeframe)`

Nazar

**Comment by ktf** [comment]
Interesting, but then again maybe the correct thing to do is to change the name of the branch to match the description? Anyways, this we should discuss separately. if you are happy with the result of this PR, I do not thing we should delay further.

**Comment by ddobrigk** [comment]
Thanks a lot for your work, @nburmaso ! 

So, if I remember well, the issue of the description being `[MCCOLLISLABEL](https://github.com/AliceO2Group/AliceO2/blob/bf993cac605003b3ccb5563bfe6a93173be6d88a/Framework/Core/include/Framework/AnalysisDataModel.h#L1461)` is that the description has a maximal number of characters which is easily exceeded by typical table names such as McCollisionLabel - and likely the description was shortened because of that. This happened to me already a few times, so I surmise that's the reason for the awkward "MCCOLLISLABEL"... In any case, I think we should not have that stop the merging of a PR that is about calling `.reserve` but we should rather discuss this tuning separately - I agree with @ktf on that!

**Pull request merged**
