### PR TITLE
Fix metadata and remove log - TOFDCSconfig

### PR DESCRIPTION
**Pull request by chiarazampolli**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Failure in o2-cs8 should not be related to this PR, @TimoWilken , @ktf , can you check?

**Comment by TimoWilken** [comment]
@chiarazampolli looks like the CI builder couldn't find the CERN CA certs. I'm looking into it!

**Comment by chiarazampolli** [comment]
Hello @TimoWilken , @ktf , @shahor02 , 

Can this be merged?

Chiara

**Comment by ktf** [comment]
For the record, you needed @noferini approval and to click on "Auto-Merge" for this to be merged automatically using the orthodox Github way.

**Pull request merged**
