### PR TITLE
DPL: few more improvements to the GUI

### PR DESCRIPTION
**Pull request by ktf**
Prettifying a few screenshots for CHEP.

### CODE REVIEW

**Comment by ktf** [comment]
image

**Comment by sawenzel** [comment]
@dberzano : Since a few PRs we are seeing G4 failures on macos due to a failure in graphics initialization. Was anything changed on the platform recently that could explain this (like a system update)?

**Comment by sawenzel** [comment]
@ktf: The formatting of this PR has issues.

**Comment by ktf** [comment]
Mac check crash unrelated.

**Pull request merged**
