### PR TITLE
Fix ITS/MFT digitizer initializtions

### PR DESCRIPTION
**Pull request by shahor02**
All initializations of the DigitizerSpec and Digitizer are moved to updateTimeDependentParams
and are made after all info from the CCDB and ConfigurableParams is accounted.

### CODE REVIEW

**Comment by noferini** [comment]
Hi Ruben,
many thanks! Indeed it works.
It would be nice to have it merged today to resume production with the tomorrow tag.
Cheers
Francesco

**Comment by shahor02** [comment]
@noferini unfortunately, the FullCI has failed, I suspect due to the wrong default CCDB object, checking, but not sure it is worth to merge it until fullCI on the build server is green.

**Comment by noferini** [comment]
Hi Ruben,
I am not sure of the errors I found in the fullLog.txt

By grepping on 128 error I found an error on FV0Digitizer


++ SIMEXITCODE=128
++ '[' 128 '!=' 0 ']'
./digi.log[1551:SimReader]: HBFUtils.nHBFPerTF : 128		[ CODE ]
./digi.log[1577:MFTDigitizer]: [19:38:21][INFO] Added 1289 digits 
./digi.log[1577:MFTDigitizer]: ROF: 2 | 163 entries starting from 1289
./digi.log[ERROR] pid 1564 (FV0Digitizer) crashed with 128
./digi.log[ERROR] SEVERE: Device FV0Digitizer (1564) returned with 128
./digi.logTASK-EXIT-CODE: 128
./sim-challenge.logcommand o2-sim-digitizer-workflow -b --run --shm-segment-size 8000000000 --interactionRate 400000 --configKeyValues HBFUtils.runNumber=300000 had nonzero exit code 128
./sim-challenge.log[1551:SimReader]: HBFUtils.nHBFPerTF : 128		[ CODE ]
./sim-challenge.log[1577:MFTDigitizer]: [19:38:21][INFO] Added 1289 digits 
./sim-challenge.log[1577:MFTDigitizer]: ROF: 2 | 163 entries starting from 1289
**./sim-challenge.log[ERROR] pid 1564 (FV0Digitizer) crashed with 128**
**./sim-challenge.log[ERROR] SEVERE: Device FV0Digitizer (1564) returned with 128**
./sim-challenge.logTASK-EXIT-CODE: 128

not clear to me how this could be related to your PR

**Comment by shahor02** [comment]
sim_challenge has:
```
./sim-challenge.log[1576:ITSDigitizer]: [19:38:20][INFO] ITS noise map updated
./sim-challenge.log[1576:ITSDigitizer]:     /lib64/libc.so.6: ()
./sim-challenge.log[1576:ITSDigitizer]:     /sw/slc8_x86-64/O2/8964-slc8_x86-64-local1/lib/libO2ITSMFTSimulation.so: o2::itsmft::Digitizer::setNoiseMap(o2::itsmft::NoiseMap const*)
./sim-challenge.log[1576:ITSDigitizer]:     o2-sim-digitizer-workflow: decltype(auto) o2::framework::InputRecord::get<o2::itsmft::NoiseMap*, char const*>(char const*, int) const
```

**Comment by noferini** [comment]
Hi Ruben,
you are right, I missed it.
I had a look at the entries in ITS/Config/AlpideParam
There are two entries:
- the default one: which is used also in my local test (and it seems to work)
- one with a validity starting from yesterday (I guess the one which should be asked in fullCI)

However, only one (the default one) is available in GRID

AliEn[noferini]:/alice/data/2021/OCT/505673/apass3/Stage_2/001/ >find /alice/data/CCDB/MFT/Config/AlpideParam/ *     
/alice/data/CCDB/MFT/Config/AlpideParam/04/29512/fd421b4c-d4ae-11ec-90c5-2a010e0a0b16

AliEn[noferini]:/alice/data/2021/OCT/505673/apass3/Stage_2/001/ >

Is one entry corrupted?

FORGOT THIS COMMENT: I CHECKED MFT (SORRY)

**Comment by shahor02** [comment]
Hi @noferini 
the digitization has failed when attaching the ITS noise map, the same job was fine (with the same object loaded) in my local test, now checking with valgrind if there are some memory problems.

Till yesterday there was just 1 entry of AlpideParam for ITS and MFT each, then I've added the one requested by ITS for the upcoming data taking. Both FST and sim_challenge now use run 300000, so they are correctly picking default object.

**Comment by shahor02** [comment]
@noferini there was actually a serious problem with non-initialized variable after all reshuffling, now the valgrind is clean + validated locally, merging.

**Pull request merged**
