### PR TITLE
dev: ctp config saved at start of run

### PR DESCRIPTION
**Pull request by lietava**

### CODE REVIEW

**Comment by lietava** [comment]
HI @shahor02 , please, check if my timestamps are ok:
https://github.com/lietava/AliceO2/blob/d7ac42e10210e89e764156c323998a824ab3bd69/DataFormats/Detectors/CTP/src/Configuration.cxx#L572
https://github.com/lietava/AliceO2/blob/ctpdev/DataFormats/Detectors/CTP/src/Configuration.cxx#:~:text=std%3A%3Achrono%3A%3Aseconds,timeStart%20%2B%20time3days%3B
https://github.com/lietava/AliceO2/blob/d7ac42e10210e89e764156c323998a824ab3bd69/DataFormats/Detectors/CTP/src/Configuration.cxx#L592
Cheers, Roman.

**Comment by shahor02** [comment]
@lietava Looks fine, but when are calling these functions? How this is correlated with the ECS SOR/EOR?

**Comment by lietava** [comment]
config is writen at start of run:
https://github.com/lietava/AliceO2/blob/d7ac42e10210e89e764156c323998a824ab3bd69/DataFormats/Detectors/CTP/src/Configuration.cxx#L688
scalers are written at end of run:
https://github.com/lietava/AliceO2/blob/d7ac42e10210e89e764156c323998a824ab3bd69/DataFormats/Detectors/CTP/src/Configuration.cxx#L594

**Comment by shahor02** [comment]
> config is writen at start of run: https://github.com/lietava/AliceO2

I understand this, the question is when exactly this happens wrt the actual data taking. We should be sure that by  the time data arrives to the EPN the CCDB object is ready.

**Comment by lietava** [comment]
@shahor02 :
Global run for CTP starts in two steps Load and Start.
At Start CTP starts to send HB and Physics triggres.
IN the current version it is written at Start. It is possible to move it to Load. There are usually at least seconds between Load and Start.

**Comment by shahor02** [comment]
Earlier we do this, better it is.

**Comment by lietava** [comment]
ok, then, please, hold this request until I tell you or change it to draft.

**Comment by lietava** [comment]
@shahor02 , please, pull

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
