### PR TITLE
FITRaw lib, for raw2digit conversion at FIT

### PR DESCRIPTION
**Pull request by afurs**
1) FT0Raw devided into common for FIT detectors lib(FITRaw) and specialized for FT0 (FT0Raw)
2) New FT0 digit structs(DigitExt and TriggersExt) for extended TCM mode
3) some changes in Detector.cxx from Alla (@AllaMaevskaya)

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
My tests are OK. I approve changes

**Comment by AllaMaevskaya** [comment]
Who knows why its stack?

**Review by mslupeck — COMMENTED** [review]
So have you restarted the tests by making a new (or amending the latest) commit and pushing to Artur's branch, as we discussed yesterday?

**Comment by afurs** [comment]
> So have you restarted the tests by making a new (or amending the latest) commit and pushing to Artur's branch, as we discussed yesterday?

@mslupeck Hello, yes, I have restarted it yesterday (19-00 CERN time). It seems that other PRs(4664,4659,4637) have the same problem. Maybe we should wait.

**Comment by TimoWilken** [comment]
@AllaMaevskaya, for the tests to start you need to leave an approving review using the GitHub feature, instead of commenting saying you approve. At the moment, this PR shows up as "not reviewed" to the CI builders.

**Review by mslupeck — APPROVED** [review]
Let's see if the tests start now that I approved the PR...

**Review by AllaMaevskaya — APPROVED** [review]

**Comment by davidrohr** [comment]
@shahor02 @AllaMaevskaya  @afurs After this PR the full system test crashes because the `ft0-datareader-dpl-flp` crashes. Could you have a look. As a side node, personally I'd squash-merge such a PR with many cleanup commits instead of rebase-merging it.

**Comment by afurs** [comment]
> @shahor02 @AllaMaevskaya @afurs After this PR the full system test crashes because the `ft0-datareader-dpl-flp` crashes. Could you have a look. As a side node, personally I'd squash-merge such a PR with many cleanup commits instead of rebase-merging it.

Hello @davidrohr ! Can I take a look at the logs (full system test)?

**Comment by davidrohr** [comment]
Hi @afurs :
For reference, the full instructions for the full system test are here: https://alice.its.cern.ch/jira/browse/O2-1492
The part that runs for FT0 is:
```
o2-sim -n 1 -g pythia8hi -m FT0
o2-sim-digitizer-workflow
o2-ft0-digi2raw --file-per-link --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0" -o rawFT0
o2-raw-file-reader-workflow $ARGS_ALL --configKeyValues "HBFUtils.nHBFPerTF=128" --max-tf 0 --input-conf rawFT0/FT0raw.cfg | \
o2-ft0-flp-dpl-workflow --disable-root-output | \
o2-ft0-reco-workflow --disable-root-input --disable-root-output --disable-mc | \
o2-ft0-entropy-encoder-workflow
```
I see error messages (that were not there before):
```
[ERROR] Header is not a DataHeader?
```
Attached is my full log.
[ft0.log.tar.gz](https://github.com/AliceO2Group/AliceO2/files/5438485/ft0.log.tar.gz)

**Comment by afurs** [comment]
@davidrohr ,
I briefly looked at the logs. 
Log line "[5889:ft0-datareader-dpl]: [12:29:23][ERROR] Header is not a DataHeader?" caused by line https://github.com/AliceO2Group/AliceO2/blob/ca981855bbda9fff43ebda2d727c8f8a0107b07e/Framework/Core/src/DataProcessingDevice.cxx#L613 
which is located in the "DataProcessingDevice::handleData(DataProcessorContext& , FairMQParts& , InputChannelInfo& )" method. 
Something wrong with the data pushed as input to the ft0-datareader-dpl-flp,  DataHeader(pointer equals to zero) cannot be extracted from the FairMQParts. So, it means that the "trigger" of this situation located somewhere before ft0-datareader-dpl-flp. 
Could you try to change "HBFUtils.orbitFirst=0" to "HBFUtils.orbitFirst=1" and/or delete "--file-per-link" at "o2-ft0-digi2raw" stage? This is an only difference from the successful tests(done by @AllaMaevskaya ), as I know.   

P.S. Right now I cannot do any tests, O2 is compiling on my machine.

**Comment by shahor02** [comment]
Hi @davidrohr 

I've just tried with your set of commands, as well as freshly produced raw data for 70 pbpb events and don't get any error.
Is your log for fresh raw data (don't know if internals of raw data were changed, perhaps @afurs may comment).

Cheers,
 Ruben

**Comment by davidrohr** [comment]
@shahor02 @afurs : I have wiped the O2 build folder and recompiled from scratch and now the segfault is gone. No idea. I didn't change neither the code nor the dataset. Also the full system test succeeds now.
No idea, must be an incremental build issue.
I'll report back in case it appears again. Otherwise just ignore my complaint...

**Pull request merged**
