### PR TITLE
Set RDHv7 as default + related fixes

### PR DESCRIPTION
**Pull request by shahor02**
@afurs @lietava [this](https://github.com/AliceO2Group/AliceO2/commit/fa7d3b67498d75493cb5dc9063c63e431c209b36) allows to FIT and CTP decoders to work with RDHv6 data while having RDHv7 as default. Please rebase your development for unpadded RDHv7 to this.

### CODE REVIEW

**Comment by shahor02** [comment]
@afurs I see you still have old / new decoders. The one I've fixed is apparently the old one which is currently used in the FST.
In the other one there are still explicit calls to `get_if<o2::header::RAWDataHeader>()'`
```
 git grep 'get_if<o2::header::RAWDataHeader>()'
Detectors/FIT/FDD/workflow/include/FDDWorkflow/RawDataReaderSpec.h:      auto rdhPtr = it.get_if<o2::header::RAWDataHeader>();
Detectors/FIT/FT0/workflow/include/FT0Workflow/FT0DataReaderDPLSpec.h:      auto rdhPtr = it.get_if<o2::header::RAWDataHeader>();
Detectors/FIT/FT0/workflow/src/FT0DataDecoderDPLSpec.cxx:    auto rdhPtr = it.get_if<o2::header::RAWDataHeader>();
Detectors/FIT/FT0/workflow/src/FT0DataDecoderDPLSpec.cxx:      arrRdhTCMperOrbit[orbitTF].push_back(it.get_if<o2::header::RAWDataHeader>());
Detectors/FIT/FT0/workflow/src/FT0DataDecoderDPLSpec.cxx:      arrRdhPtrPerOrbit[orbitTF][feeID].push_back(it.get_if<o2::header::RAWDataHeader>());
```
this will fail if data with RDH<RDFv7 is decoded. If these decoders are used, could you please change them to use `RDHAny` like in the version I fixed?

**Comment by shahor02** [comment]
@afurs in the end I've modified alternative decoders myself since I guess they are used with FLP build hence would fail with default RDHv7.

**Comment by lietava** [comment]
@shahor02 : sorry I was off during weekend. Looking above  seems to me there is nothing to do on my side ?

**Comment by shahor02** [comment]
> @shahor02 : sorry I was off during weekend. Looking above seems to me there is nothing to do on my side ?

@lietava if CTP is fully ready for unpadded RDHv7 data then there is nothing to do.

**Comment by lietava** [comment]
> > @shahor02 : sorry I was off during weekend. Looking above seems to me there is nothing to do on my side ?
> 
> @lietava if CTP is fully ready for unpadded RDHv7 data then there is nothing to do.

I think today the CTP firmware was updated in p2 to RDHv7. So one can try to take data and test.
Do you know if such exercise is foreseen ?

**Comment by shahor02** [comment]
No idea, Pippo was planning to switch to RDHv7 on 6th.

**Comment by afurs** [comment]
> @afurs I see you still have old / new decoders. The one I've fixed is apparently the old one which is currently used in the FST. In the other one there are still explicit calls to `get_if<o2::header::RAWDataHeader>()'`
> 
> ```
>  git grep 'get_if<o2::header::RAWDataHeader>()'
> Detectors/FIT/FDD/workflow/include/FDDWorkflow/RawDataReaderSpec.h:      auto rdhPtr = it.get_if<o2::header::RAWDataHeader>();
> Detectors/FIT/FT0/workflow/include/FT0Workflow/FT0DataReaderDPLSpec.h:      auto rdhPtr = it.get_if<o2::header::RAWDataHeader>();
> Detectors/FIT/FT0/workflow/src/FT0DataDecoderDPLSpec.cxx:    auto rdhPtr = it.get_if<o2::header::RAWDataHeader>();
> Detectors/FIT/FT0/workflow/src/FT0DataDecoderDPLSpec.cxx:      arrRdhTCMperOrbit[orbitTF].push_back(it.get_if<o2::header::RAWDataHeader>());
> Detectors/FIT/FT0/workflow/src/FT0DataDecoderDPLSpec.cxx:      arrRdhPtrPerOrbit[orbitTF][feeID].push_back(it.get_if<o2::header::RAWDataHeader>());
> ```
> 
> this will fail if data with RDH<RDFv7 is decoded. If these decoders are used, could you please change them to use `RDHAny` like in the version I fixed?

Hello @shahor02 okay, but I suppose we can suspend this decoder for a while. Anyway for now we process data at EPN part.

**Comment by shahor02** [comment]
@afurs as I wrote above, I've fixed also "new" decoder.

**Comment by shahor02** [comment]
fullCI as well as the reco of 22m data was tested locally

**Pull request merged**
