### PR TITLE
Use FairMQDevice::GetConfig() getter everywhere

### LINKED ISSUE #247: Consistenly use GetConfig from FairMQDevice
FairMQDevice now offer a GetConfig() function. We should hence no longer use `fConfig` in our device code.

The task is to replace globally all use of fConfig with GetConfig().

### PR DESCRIPTION
**Pull request by ktf**
Fix #247.

### CODE REVIEW

**Comment by rbx** [comment]
I removed `fLogIntervalInMs` from the device in a recent commit. The logging interval is set per channel via channel options since a while. I'll make a PR to replace `fLogIntervalInMs` in `WrapperDevice` with `1000` (that was default for `fLogIntervalInMs`), until this (quite outdated) class is updated.

**Comment by sawenzel** [comment]
We will change this PR to include a fix to your FairRoot change. No need to make a separate PR.

**Comment by rbx** [comment]
Too late, just made it. but feel free to close it!

**Comment by ktf** [comment]
Closing it for the moment to check builder issues...

**Comment by ktf** [comment]
Finally builds correctly. Sorry for the noise. Squashing and merging.

**Pull request merged**
