### PR TITLE
New functionalities: DeepTrigger, Pythia8::UserHooks, Pythia6

### PR DESCRIPTION
**Pull request by preghenella**
This PR provides several new functionalities to the event-generator trigger facility.
It also provides a way to attach `UserHooks` to `Pythia8`.

Here is a list of the news

### update to custom triggers

The mechanism previously used to defined EG trigger was based on the definition of custom trigger classes. A comment in a recent meeting suggested to replace this with user-defined lambda functions, and this PR updates the behavior in this way. As a matter of fact, using lambda functions allows one for a more compact code with the same functionality.
An example is provided in `Generators/share/external/trigger_multiplicity.C` which is reported hereafter

```
//   usage: o2sim --trigger external --extTrgFile trigger_multiplicity.C
// options:                          --extTrgFunc "trigger_multiplicity(-0.8, 0.8, 100)"

#include "Generators/Trigger.h"
#include "TParticle.h"

o2::eventgen::Trigger
  trigger_multiplicity(double etaMin = -0.8, double etaMax = 0.8, int minNch = 100)
{
  auto trigger = [etaMin, etaMax, minNch](const std::vector<TParticle>& particles) -> bool {
    int nch = 0;
    for (const auto& particle : particles) {
      if (particle.GetStatusCode() != 1)
        continue;
      if (!particle.GetPDG())
        continue;
      if (particle.GetPDG()->Charge() == 0)
        continue;
      if (particle.Eta() < etaMin || particle.Eta() > etaMax)
        continue;
      nch++;
    }
    bool fired = nch >= minNch;
    return fired;
  };

  return trigger;
}
```

### introduction of deep triggers

Deep triggers is just a name to a new functionality that allows the user to define custom functions that will have a direct handle on the event generator interface. The functionality follows the schema of the previous point, with the user providing a custom lambda function that will receive from the framework a pointer to the internal event-generator interface object (i.e. for Pythia8, a pointer to the Pythia object) and a tagname to identify the interface. This functionality might be useful to users who want to provide triggers based on information beyond the stack of the generated particles, based on more internal counters/information in the event generator machinery.

Here is an example of a deep trigger implementation in Pythia8.

```
//   usage: o2sim --trigger external --extTrgFile trigger_mpi.C
// options:                          --extTrgFunc "trigger_mpi()"

#include "Generators/Trigger.h"
#include "Pythia8/Pythia.h"

o2::eventgen::DeepTrigger
  trigger_mpi(int mpiMin = 5)
{
  return [mpiMin](void* interface, std::string name) -> bool {
    if (!name.compare("pythia8")) {
      auto py8 = reinterpret_cast<Pythia8::Pythia*>(interface);
      return py8->info.nMPI() >= mpiMin;
    }
    LOG(FATAL) << "Cannot define MPI for generator interface \'" << name << "\'";
    return false;
  };
}
```

### Pythia8 UserHooks

Pythia8 machinery allows the user to hook some code at various stages of the event-generation process. For details, please look at Pyhia8 manual. 
http://home.thep.lu.se/~torbjorn/pythia82html/UserHooks.html

The interface is provided via a configuration macro, where the user will have to define a custom UserHooks according to the protocol defined by Pythia8. The macro will also have to provide a function to retrieve the pointer to the created custom UserHooks object. 

This functionality might be of use for users who want to be able to steer the event-generation process from very deep inside the internal routines and want to veto some specific processes based on analysis of the status of Pythia8 at the various stages, i.e. veto events that do not have charm partons, before hadronisation of partons. This can save time in the event generation process as many steps can be skipped already at early time.

An example of a configuration macro is this one

```
//   usage: o2sim -g pythia8 --configKeyValue "Pythia8.hooksFileName=pythia8_userhooks_charm.C"

#include "Generators/Trigger.h"
#include "Pythia8/Pythia.h"

class UserHooksCharm : public Pythia8::UserHooks
{
 public:
  UserHooksCharm() = default;
  ~UserHooksCharm() = default;
  bool canVetoPartonLevel() override { return true; };
  bool doVetoPartonLevel(const Pythia8::Event& event) override
  {
    for (int ipa = 0; ipa < event.size(); ++ipa) {
      if (abs(event[ipa].id()) != 4)
        continue;
      if (fabs(event[ipa].y()) > 1.5)
        continue;
      return false;
    }
    return true;
  };
};

Pythia8::UserHooks*
  pythia8_userhooks_charm()
{
  return new UserHooksCharm();
}
```

### Pythia6 interface
A new Pythia6 interface is provided via `GeneratorPythia6`. This complies with the `o2::eventgen::Generator` protocol, and hence the user is allowed to use all the trigger functionalities. The class can also be used for `DeepTriggers`  as this modified macro shows.

```
//   usage: o2sim --trigger external --extTrgFile trigger_mpi.C
// options:                          --extTrgFunc "trigger_mpi()"

#include "Generators/Trigger.h"
#include "Pythia8/Pythia.h"
#include "TPythia6.h"

o2::eventgen::DeepTrigger
  trigger_mpi(int mpiMin = 15)
{
  return [mpiMin](void* interface, std::string name) -> bool {
    int nMPI = 0;
    if (!name.compare("pythia8")) {
      auto py8 = reinterpret_cast<Pythia8::Pythia*>(interface);
      nMPI = py8->info.nMPI();
    }
    else if (!name.compare("pythia6")) {
      auto py6 = reinterpret_cast<TPythia6*>(interface);
      nMPI = py6->GetMSTI(31);
    }
    else
      LOG(FATAL) << "Cannot define MPI for generator interface \'" << name << "\'";
    return nMPI >= mpiMin;
  };
}
```

### ConfigurationMacroHelper.h

Given the increasing use of configuration macros to attach plugins for event generation triggers and other functionalities, a helper function has been defined to take care of the process of retrieving objects from macro.C files in a standardised way. This allows to simplify the code and keep in a single point of entry the functionality.

Here is the signature of the function defined there

```
template <typename T>
T GetFromMacro(const std::string file, const std::string funcname, const std::string type, const std::string unique)
```

which allows one to retrieve the object of type `T` defined in the macro `file` running the function `funcname` . The other parameter `type`  is a string version of the object type `T` which is needed during the parsing process, whereas `unique` is used to define a unique global variable name which is also needed to retrieve the object.

### CODE REVIEW

**Comment by preghenella** [comment]
does not pass `build/o2/macos` checks, but from the log it seems that the issue is not related with this PR, is it?

**Comment by preghenella** [comment]
I have force pushed to take advantage of this PR and include also the development for Pythia6, which was ready in my pipeline. In some sense it fits with the PR because it is a development meant to allow Pythia6 users to make use of the functionalities.

**Comment by preghenella** [comment]
fixed the codacy issue.

**Comment by sawenzel** [comment]
CI is stuck. I'd like to see it green before going on.

**Comment by sawenzel** [comment]
This fails in `Generators/share/external/trigger_multiplicity.C_compiled`

**Comment by sawenzel** [comment]
Could you also add the description/docu here to the simulation README?

**Comment by preghenella** [comment]
> This fails in `Generators/share/external/trigger_multiplicity.C_compiled`

Hi @sawenzel , I'm looking into that.
Can you please suggest me how to run the tests on my computer?

Thanks

**Comment by preghenella** [comment]
> > This fails in `Generators/share/external/trigger_multiplicity.C_compiled`
> 
> Hi @sawenzel , I'm looking into that.
> Can you please suggest me how to run the tests on my computer?
> 
> Thanks

sorry, testing might just work with
[root] # .L mymacro.C+

**Comment by preghenella** [comment]
hello @sawenzel ,
I'm unable to get `Generators/share/egconfig/pythia8_userhooks_charm.C_compiled` passing the test. The macro works when loaded for use with `o2-sim`, but it does not compile as a standalone macro. It seems it is not finding all the references to the pythia8 library.

Do you have any hints how to get this fixed?
Otherwise I think I will just remove this example to advance with this PR. It is not optimal because I wanted to keep somewhere in the O2 at least one example/template for each of the functionalities.

Thanks,
Roberto

**Comment by sawenzel** [comment]
@preghenella : I think you now need to list the dependencies for each macro separately in the cmake files. Please take a look at other examples.

**Comment by preghenella** [comment]
hi @sawenzel ,
thanks. I am sure I have tried to explicitly add `MC::Pythia` in the `CMakelists.txt` file, if this is what you mean. Pythia is kind of seen by the process, because the test does not complain with the `#include "Pythia8/Pythia.h"` or the `R__LOAD_LIBRARY(libpythia8.so)` in the file.

Doing
```
o2_add_test_root_macro(share/egconfig/pythia8_userhooks_charm.C
                       PUBLIC_LINK_LIBRARIES O2::Generators MC::Pythia
                       LABELS generators)
```
or
```
o2_add_test_root_macro(share/egconfig/pythia8_userhooks_charm.C
                       PUBLIC_LINK_LIBRARIES O2::Generators
                       LABELS generators)
```
does not make a difference.

What I have noticed is that, if I try to build the macro myself with
```
root # .L mymacro.C+
```
it fails at first because it cannot find `#include "Pythia8/Pythia.h"`.
So, I have to do
```
root # .include path_to_pythia_include
root # .L mymacro.C+
```
and I find myself with the same error as in the ctest.
I notice that in this case I can solve it with
```
root # .include path_to_pythia_include
root # gSystem->Load("libpythia8.so")
root # .L mymacro.C+
```
like this I can build the macro fine.

Does this perhaps helps in understanding where my issue is with the ctest system?

Thanks,
Roberto

**Comment by aphecetche** [comment]
@preghenella @sawenzel I'm having a look.

**Comment by sawenzel** [comment]
Thanks!

**Comment by aphecetche** [comment]
@sawenzel  @preghenella  well, so far no luck. It's extremely frustrating (as always with Root macros...) as compiled and non-compiled modes behave differently...
Will give it another try with a fresh mind tomorrow...

**Comment by aphecetche** [comment]
@preghenella @sawenzel Please see https://github.com/preghenella/AliceO2/pull/4 which is only half of a solution, but a solution nonetheless.

**Comment by ktf** [comment]
I suspect this is apparently breaking `o2-dataflow` in alidist. See https://github.com/AliceO2Group/QualityControl/pull/338.

**Pull request merged**
