### PR TITLE
Split vertex finding and vertex fitting

### PR DESCRIPTION
**Pull request by ginnocen**

### CODE REVIEW

**Comment by ginnocen** [comment]
@ktf @jgrosseo.  I removed the "Work In Progress" flag. This PR is ready for merging from my point of view (I see it fails some tests but they look unrelated).
It includes: 
- Giulio's PRs to fix the joins. 
- my modifications to split vertex finding and vertex fitting together to have a more realistic HF workflow implementation.

**Comment by ktf** [comment]
@Barthelemy @knopers8 there seems to be some issues when compiling qc, could you check?

**Comment by knopers8** [comment]
https://github.com/AliceO2Group/AliceO2/pull/3035 was merged prematurely, before necessary adaptations in QC: https://github.com/AliceO2Group/QualityControl/pull/321 https://github.com/AliceO2Group/QualityControl/pull/320 . I would happily merged them, but CI doesn't provide us with the build results.

**Comment by ktf** [comment]
I fixed the merge conflicts. Will merge if the tests are green.

**Pull request merged**
