### PR TITLE
DPL: do topological sort before graph creation (O2-841)

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@matthiasrichter this seems to solve https://github.com/AliceO2Group/AliceO2/pull/3112 in my local tests.

@pbuehler @ekryshen @aalkin: this produces a proper topology when doing:

```
stage/bin/o2-analysis-event-selection --aod-file ~/src/data/AO2D-1.root | stage/bin/o2-analysis-multiplicity-table | stage/bin/o2-analysis-multiplicity-qa
```

however there is a crash which I think it's actually a bug in the aod-writer, which still adds multiple AOD/COLLISION outputs and one input! Could you please check?

@shahor02 @knopers8 could you check once more if this solves your issues?

**Comment by ktf** [comment]
@ekryshen @aalkin: ok, I think I fixed the last crash, now the only missing thing for me is the trigger.root.

@pbuehler the issue with the multiple outputs is still there, however it does not seem to be the cause of the wrong topological sort.

**Comment by knopers8** [comment]
Thanks, my test example works now.
@tklemenz @mfasDa Could you check if attaching QC to your workflows works properly with this PR?

**Comment by ktf** [comment]
@matthiasrichter your proxy test hangs on the CI machine, but it works fine on my laptop. Could you try on yours? I also see you hardcode the channel name, is that really necessary?

**Comment by shahor02** [comment]
@ktf this PR breaks piping of the independent workflows which were mergeable before (although the topology seems to be correct).
To reproduce:
````
o2-sim -n 10 -m PIPE ITS TPC TOF
o2-sim -n 10 -m PIPE ITS TPC TOF -g pythia8
o2-sim-digitizer-workflow
# then, 2 workflows are working separately:
o2-its-reco-workflow 
o2-tpc-reco-workflow --tpc-digit-reader '--infile tpcdigits.root' --input-type digits --output-type clusters,tracks --tracker-options "cont refX=83 bz=-5.0068597793" --tpc-track-writer "--treename events --track-branch-name Tracks --trackmc-branch-name TracksMCTruth"
# 
# but TPC flow breaks when piped with ITS, although they are independent
o2-its-reco-workflow  | o2-tpc-reco-workflow --tpc-digit-reader '--infile tpcdigits.root' --input-type digits --output-type clusters,tracks --tracker-options "cont refX=83 bz=-5.0068597793" --tpc-track-writer "--treename events --track-branch-name Tracks --trackmc-branch-name TracksMCTruth"
````
leads to:
````
...
[14035:tpc-cluster-decoder]: [10:22:23][ERROR] requested channel has not been configured? check channel names/configuration.
[14035:tpc-cluster-decoder]: [10:22:23][ERROR] channel: from_tpc-cluster-decoder_to_tpc-native-cluster-writer, index: 0
[14035:tpc-cluster-decoder]: [10:22:23][ERROR] out of range: _Map_base::at
[14035:tpc-cluster-decoder]: [10:22:23][ERROR] Exception caught: _Map_base::at
...
````
This was working before.
So, I cannot test how the merging which was failing before behaves now, but once the problem above is solved, you can test it as 
````
o2-its-reco-workflow  | o2-tpc-reco-workflow --tpc-digit-reader '--infile tpcdigits.root' --input-type digits --output-type clusters,tracks --tracker-options "cont refX=83 bz=-5.0068597793" --tpc-track-writer "--treename events --track-branch-name Tracks --trackmc-branch-name TracksMCTruth" | o2-tpcits-match-workflow  --tpc-track-reader tpctracks.root --tpc-native-cluster-reader "--infile tpc-native-clusters.root" 
````
The GUI topology it produces looks weird:
image

**Comment by ktf** [comment]
Ok. Do you happen to have a dataprocessor with the same name in two or more sub-workflows?

**Comment by shahor02** [comment]
no (the duplications are only due to the grep hitting both ``workflow`` and ``metadata`` blocks):
````
o2-its-reco-workflow  | o2-tpc-reco-workflow --tpc-digit-reader '--infile tpcdigits.root' --input-type digits --output-type clusters,tracks --tracker-options "cont refX=83 bz=-5.0068597793" --tpc-track-writer "--treename events --track-branch-name Tracks --trackmc-branch-name TracksMCTruth" --dump-workflow | grep  '^            \"name\"' | sort
            "name": "internal-dpl-clock",
            "name": "its-clusterer",
            "name": "its-clusterer",
            "name": "its-cluster-writer",
            "name": "its-cluster-writer",
            "name": "its-cooked-tracker",
            "name": "its-cooked-tracker",
            "name": "its-digit-reader",
            "name": "its-digit-reader",
            "name": "its-track-writer",
            "name": "its-track-writer",
            "name": "tpc-cluster-decoder",
            "name": "tpc-cluster-decoder",
            "name": "tpc-clusterer",
            "name": "tpc-clusterer",
            "name": "tpc-digit-reader",
            "name": "tpc-digit-reader",
            "name": "tpc-native-cluster-writer",
            "name": "tpc-native-cluster-writer",
            "name": "tpc-tracker",
            "name": "tpc-tracker",
            "name": "tpc-track-writer",
            "name": "tpc-track-writer",
````

**Comment by tklemenz** [comment]
Hello @knopers8,
also for me the error 
`
...
[26410:QC-TASK-RUNNER-PID]: [11:59:22][ERROR] requested channel has not been configured? check channel names/configuration.
[26410:QC-TASK-RUNNER-PID]: [11:59:22][ERROR] channel: from_tpc-tracker_to_QC-TASK-RUNNER-PID, index: 0
[26410:QC-TASK-RUNNER-PID]: [11:59:22][ERROR] out of range: _Map_base::at
[26410:QC-TASK-RUNNER-PID]: [11:59:22][ERROR] out of range: _Map_base::at
[26410:QC-TASK-RUNNER-PID]: [11:59:22][ERROR] incorrect/incomplete channel configuration?
...
`
persists while piping two workflows. I use
`
o2-tpc-reco-workflow -b --infile tpcdigits.root --output-type tracks | o2-qc -b --config json://home/tklemenz/AliSoftware/QualityControl/Modules/TPC/run/tpcQCPID_direct.json
`
In case it is somehow useful for you [here](https://cernbox.cern.ch/index.php/s/xj5pth97cTIOiPq) is the log and [here](https://cernbox.cern.ch/index.php/s/6NPm2ZtwgetWvCe) the DPL configuration.

The simulation files I use come from
`
o2-sim -m TPC [ITS PIPE] -n 1 -g pythia8
o2-sim-digitizer-workflow -b
`

I hope this helps.
Cheers,
Thomas

**Comment by ktf** [comment]
Thanks. I am on it.

**Comment by ktf** [comment]
Updated version. 

@shahor02 This should bring back the merging of the completely separate workflows. With the three workflows I have troubles running the merger, I think because of garbage being printed on `std::cout`, directly on initialisation. When it works, I still get a loop at the end of the topology. Investigating.

@knopers8 Notice how in order to ensure stability the ENUM subSpec is an hash of the data processor name. Do you think it will be an issue?

**Comment by knopers8** [comment]
I don't think it should be an issue, if I understand correctly what is going on there.

**Comment by ktf** [comment]
@knopers8 @shahor02 @ekryshen @matthiasrichter : I think I managed to have a properly configured topology for all your examples. Could you check again?

@tklemenz: I do not have o2-qc in my setup. Could you please verify yourself?

**Comment by ktf** [comment]
image

Obligatory screenshot. I think I have some other issue with the simulated files, but the topology looks good.

**Comment by ktf** [comment]
One more update to fix the tests.

**Comment by ekryshen** [comment]
I was able to stack 5 workflows with the latest PR incarnation:
o2-analysis-event-selection | o2-analysis-multiplicity-table | o2-analysis-multiplicity-qa | o2-analysis-centrality-table  | o2-analysis-centrality-qa 

Many thanks, Giulio!

**Comment by shahor02** [comment]
@ktf: the flow 
````
o2-its-reco-workflow  | o2-tpc-reco-workflow --tpc-digit-reader '--infile tpcdigits.root' --input-type digits --output-type clusters,tracks --tracker-options "cont refX=83 bz=-5.0068597793" --tpc-track-writer "--treename events --track-branch-name Tracks --trackmc-branch-name TracksMCTruth" | o2-tpcits-match-workflow  --tpc-track-reader tpctracks.root --tpc-native-cluster-reader "--infile tpc-native-clusters.root" 
````
now starts, but crashes then crashes due to the mess with the readers / writers.
And I doubt it can be in principle solved from the framework side alone due to [this](https://github.com/AliceO2Group/AliceO2/pull/3319#issuecomment-612875485), unless the readers / writers register in the framework their input/output files, in a same what they do with DPL inputs/outputs.
This is probably too complicated, I am going to add options to all relevant workflows to not attach writers and corresponding readers if in the merged flow they will produce just an intermediate file.

**Comment by ktf** [comment]
Ok. I will merge assuming your reply implies there is no regression either and it does fix the use cases of a few other people. We can then think of a way of pruning intermediate outputs.

**Comment by tklemenz** [comment]
Hi @ktf, 

merging the workflows also works in my case. 
Thanks a lot for the effort!!

Cheers,
Thomas

**Pull request merged**
