### PR TITLE
Temporarily disable G4 tests

### PR DESCRIPTION
**Pull request by dberzano**
This is creating noise in other PRs. We need to disable this as PR tests will become mandatory (i.e. they'll have to be green) soon. Both MT and normal tests have been disabled

### CODE REVIEW

**Comment by sawenzel** [comment]
Please also open a ticket so that we do not forget to put it back.

**Comment by dberzano** [comment]
See [OCCF-57](https://alice.its.cern.ch/jira/browse/OCCF-57).

**Comment by dberzano** [comment]
@matthiasrichter I propose we start by disabling the mt one then we'll see!

We are not giving up, the motivation is that we're turning on mandatory tests, and we don't want to block everything if this is not OK :-)

**Comment by sawenzel** [comment]
Are you sure that the travis test is "required"? This is also testing clang-format ... which as far as I can tell is sometimes up for discussion. Does "required" mean that the merge button will be disabled upon failure?

**Comment by dberzano** [comment]
Required = merge button disabled (not for admins though). This is a matter of discussion for next Monday's WP3 meeting and what you see is essentially a test. AFAIK, the chances of having `clang-format` reporting an odd error are low IMHO, so when such cases come, we can just fix the `clang-format` test instead. I'd personally keep it on and address problems of individual PRs one by one if ever.

For what concerns `dev-fairroot`, sometimes the changes are so large that it takes more time to make sure O2 works with it, this is why it's not mandatory.

**Pull request merged**
