### PR TITLE
DPL: fix initial delay for timers

### PR DESCRIPTION
**Pull request by ktf**
Long delays between configure and run state could make the randomisation be ineffective.

### CODE REVIEW

**Review by knopers8 — APPROVED** [review]
thanks!

**Comment by vascobarroso** [comment]
@ktf @knopers8 we have an update window this Wednesday. Is it feasible to include this in tonight's tag ?

**Comment by ktf** [comment]
done

**Comment by davidrohr** [comment]
@ktf @knopers8 : I think this is probably insufficient. The run state the process knows about is only the local run state of itself, not the global one.
It can be that the process goes to RUNNING, but first data arrives only 1 minute later, if e.g. one detector takes quite long to go into RUNNING, which is usually the case in global runs at P2.
So we should initialize the timer the first time runDataProcessing is invoked, not based on state changes.

**Comment by ktf** [comment]
Well, it's a bit of a chicken / egg problem, because we actually process data when the timer expires. Wouldn't the best solution to simply delay the sending, then?

**Comment by davidrohr** [comment]
Can you start the timer when the device receives data for the first time?
Though that would be a problem for source devices....

What do you mean be delay the sending? I guess that could be done, but then the decision whether QC sends something or not would need to be made internally, not relying on timers?

**Comment by knopers8** [comment]
I don't quite understand what is the problem. QC does not wait with using the timer inputs until it gets any data. Also, as far as I understand, all EPNs go to RUNNING at the same time, right?

**Comment by davidrohr** [comment]
yes, all EPNs go to running at the same time, but they will only receive the first data 1-2 minutes later, when all detectors have finished their SOR

**Comment by knopers8** [comment]
OK, but that is really not a problem, as far as I understand. We do not require any data to publish first histograms, as you can see here https://github.com/AliceO2Group/QualityControl/blob/master/Framework/src/TaskRunner.cxx#L193

**Pull request merged**
