### PR TITLE
How to aggregate calib data from different EPNs

### PR DESCRIPTION
**Pull request by chiarazampolli**
changes to aggregator

Fix logic in case of multiple slots

Fix in OutputSpec

Tool to run EPN + aggregator simulation

Remove aggregator since raw-proxy can be used

forgotten from the CMakeLists

clang-format

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

This is the PR for the aggregation of calibration data. 
@noferini , there was an issue in the generator when simulating multiple EPNs, it is fixed in this PR.

Chiara

**Review by shahor02 — DISMISSED** [review]

**Review by noferini — DISMISSED** [review]
It's fine. Thanks

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

I added the possibility to pass the workflow to run as argument to the script. 

Chiara

**Comment by shahor02** [comment]
@chiarazampolli I was waiting for fullCI to pass, now it restarts all CI's though you changed only a script which is not checked. 
Did you notice it CIs were done?

**Comment by chiarazampolli** [comment]
Unfortunately I didn't, I even thought the PR was merged, since I saw your approval... Sorry.

**Comment by shahor02** [comment]
fullCI failure is unrelated, merging

**Pull request merged**
