### PR TITLE
DPL: fix unassigned variable

### PR DESCRIPTION
**Pull request by anerokhi**

### CODE REVIEW

**Comment by ktf** [comment]
Nicely spotted. What compilation flag did you use?

**Comment by anerokhi** [comment]
AFAIR it is `-Wuninitialized` (or `-Wmaybe-uninitialized`) which is part of `-Wall` which is... not part of O2 build flags. A MLOC-sized C++ project doesn't use even `-Wall` flag, when `-Wall -Wextra -pedantic -Werror` should be used (maybe minus few defective GCC warnings)…

**Comment by ktf** [comment]
I think the rationale at some point was that -Wall was using different flags on different platforms, which was deemed to be an issue by some and eventually turned down by WP3. The idea was to enable only the reasonably common flags explicitly.

**Comment by anerokhi** [comment]
> I think the rationale at some point was that -Wall was using different flags on different platforms

Sounds like a great opportunity to fix them all!

**Comment by ktf** [comment]
> Sounds like a great opportunity to fix them all!

I agree, but apparently considering all platforms as production was not an acceptable solution when this was discussed.

**Comment by anerokhi** [comment]
> I agree, but apparently considering all platforms as production was not an acceptable solution when this was discussed.

Just consider other platforms as additional checkers))0)0

**Comment by ktf** [comment]
I agree, but at the time the answer was usually "we should not waste time on (macOS|Ubuntu)". As I said in the framework meeting, I will raise the point again in WP3.

**Pull request merged**
