### PR TITLE
Add Readout frame records for MID

### PR DESCRIPTION
**Pull request by dstocco**
This is the first of a series of PR, whose aim is to allow MID to handle timeframes.
Currently, the MID processors expect objects with the same timestamp within a timeframe as input. This makes it difficult to correctly treat a full timeframe.
The objects with the same timestamp will be therefore referenced with the aim of a ROFRecord.
The following commits are atomic, so please do not squash them.

### CODE REVIEW

**Comment by dstocco** [comment]
@shahor02 , @sawenzel : FYI this is the first PR using the ROFRecord we were discussing about.
Cheers,
Diego

**Comment by shahor02** [comment]
Hi @dstocco 
looks ok, but why do you need another ROFRecordMC with no extra info compared to ROFRecord?

**Comment by dstocco** [comment]
Hi @shahor02 ,
because I do not want to put the root streamer (namely the ClassDef) in a class that I use in data reconstruction. The idea is to use the root streamer only for MC quantities (since it seems that in any case we will use root objects like TTrees to store them), but I keep the reconstruction objects as simple and generic as possible.

**Comment by shahor02** [comment]
@dstocco : not sure I understand this: the ClassDefNV has nothing to do with the streamers, they are added to the class once you mention it in the LinkDef with ``+`` and this is what you actually do now: ``#pragma link C++ struct o2::mid::ROFRecord + ;``. The ClassDef just adds a methods for the class inspection. 
In any case, what is a problem of having the streamer + root methods defined for the class which is used for the "reconstruction only", they don't add any non-static data member to the class.

**Comment by dstocco** [comment]
Hi @shahor02 ,
I just do not like much the fact that simple headers need to explicitly depend on ROOT headers. In particular, if I add the ClassDef I need to include RTypes.h. I understand that this does not add any non-static member, but why do I need RTypes.h in the first place?
Unfortunately, for this specific case, I need to use an InteractionRecord, that, despite being a very simple struct, loads RTypes.h just because of  the ClassDef. But again, I do not see why the InteractionRecord needs a RTypes.h, and in any case I could well use a uint32_t plus an uint16_t instead and I would not need the ROOT's RTypes.h anymore.

**Comment by sawenzel** [comment]
@dstocco : I agree with @shahor02  and I don't see the problem really. It is a well established fact and standard that we use ROOT in our software stack, in particular for streaming purposes.

**Comment by dstocco** [comment]
Hi @sawenzel , 
ok but is it the case also for objects used in reconstruction or only for MC?
I thought that this was the case only for simulation, not for reconstructed objects (clusters, tracks).
That's a fundamental point since, if this is the case, I stop making a distinction between data and MC objects.

**Comment by sawenzel** [comment]
To my knowledge we never made such distinction. (How do you plan to inspect and analyse your reconstructed objects? With something other than ROOT?)

One point we always stressed is that classes should be as simple as possible (in particular non-virtual) so that they can actually be sent between processes in a trivial way (or be kept in shared memory). But having a ROOT dictionary and the ability to stream to disc should be orthogonal to this.

**Comment by shahor02** [comment]
Hi @dstocco 

In fact, I usually add the ClassDefNV to generate the class dictionary (again, it has nothing to do with generating the streamer or storing in root or other format) because for development it is much more convenient if you can create the object interactively from the root command line and play with it.
There is no other reason (for non-TObject classes, for TObjects the ClassDef is must). 

Cheers,
 Ruben

**Comment by dstocco** [comment]
Ok, I will them modify the PR and include the ClassDef. If the inspection is done via root anyways, there is no reason to keep the distinction.

**Pull request merged**
