### PR TITLE
DPL: add DDS assets support

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr

**Comment by ktf** [comment]
Do not merge until new DDS is deployed.

**Comment by davidrohr** [comment]
OK, will test before and provide some feedback, and merge it once the new DDS is active on the EPNs and proven to work correctly.

**Comment by ktf** [comment]
Keep in mind the unit tests will also fail now. When I have your green light for the format, I will adapt them.

**Comment by davidrohr** [comment]
Works well with a minor fix.

Could you apply the following patch:
```
diff --git a/Framework/Core/src/DDSConfigHelpers.cxx b/Framework/Core/src/DDSConfigHelpers.cxx
index fca7c83b75c..a126a9077f3 100644
--- a/Framework/Core/src/DDSConfigHelpers.cxx
+++ b/Framework/Core/src/DDSConfigHelpers.cxx
@@ -104,9 +104,6 @@ std::string xmlEncode(std::string const& source)
       case '>':
         result += "&gt;";
         break;
-      case '\n':
-        result += "";
-        break;
       default:
         result += c;
     }
@@ -126,7 +123,7 @@ void DDSConfigHelpers::dumpDeviceSpec2DDS(std::ostream& out,
   WorkflowSerializationHelpers::dump(asset, workflow, dataProcessorInfos, commandInfo);
   out << R"(<topology name="o2-dataflow">)"
          "\n"
-      << fmt::format(R"(<asset name="dpl_json_{}" type="inline" visibility="global" value="{}"/>)",
+      << fmt::format(R"(<asset name="dpl_json{}" type="inline" visibility="global" value="{}"/>)",
                      workflowSuffix,
                      xmlEncode(asset.str()))
       << "\n";
@@ -168,10 +165,10 @@ void DDSConfigHelpers::dumpDeviceSpec2DDS(std::ostream& out,
     out << "   "
         << fmt::format("<decltask name=\"{}{}\">\n", spec.id, workflowSuffix);
     out << "       "
-        << fmt::format(R"(<assets><name>dpl_json_{}</name></assets>)", workflowSuffix) << "\n";
+        << fmt::format(R"(<assets><name>dpl_json{}</name></assets>)", workflowSuffix) << "\n";
     out << "       "
         << R"(<exe reachable="true">)";
-    out << fmt::format("cat ${{DDS_LOCATION}}/dpl_json_{}.asset | ", workflowSuffix);
+    out << fmt::format("cat ${{DDS_LOCATION}}/dpl_json{}.asset | ", workflowSuffix);
     for (auto ei : execution.environ) {
       out << fmt::format(ei,
                          fmt::arg("timeslice0", spec.inputTimesliceId),
diff --git a/Framework/Core/src/runDataProcessing.cxx b/Framework/Core/src/runDataProcessing.cxx
index 9e1c27c664e..c3c77968dcb 100644
--- a/Framework/Core/src/runDataProcessing.cxx
+++ b/Framework/Core/src/runDataProcessing.cxx
@@ -1473,7 +1473,7 @@ int runStateMachine(DataProcessorSpecs const& workflow,
       case DriverState::MATERIALISE_WORKFLOW:
         try {
           auto workflowState = WorkflowHelpers::verifyWorkflow(workflow);
-          if (driverInfo.batch == true && !varmap["dds"].as<std::string>().empty() && !varmap["dump-workflow"].as<bool>() && workflowState == WorkflowParsingState::Empty) {
+          if (driverInfo.batch == true && varmap["dds"].as<std::string>().empty() && !varmap["dump-workflow"].as<bool>() && workflowState == WorkflowParsingState::Empty) {
             LOGP(error, "Empty workflow provided while running in batch mode.");
             return 1;
           }
```
The newline is probably taste, but I don't like these >100k character lines.
For the asset name, the DDS suffix already contains `_`.

**Comment by ktf** [comment]
Will do.

**Comment by ktf** [comment]
Updated with the requested changes, test fixed. Do I understand correctly we can now merge this?

**Comment by davidrohr** [comment]
The new DDS with the fixes for assets will only be deployed at P2 on 13th. We have to wait with merging this PR until then, otherwise we cannot deploy alternative O2 versions in the meantime.

**Comment by ktf** [comment]
Ok. No objections on my side. This is now ready as far as I am concerned.

**Pull request merged**
