### PR TITLE
[EMCAL-501] noise digits, time response, fix bugs

### PR DESCRIPTION
**Pull request by aknospe**
[EMCAL-501,502,518] implemented noise digits, changed time response to use value of function rather than integral, fixed bugs

### CODE REVIEW

**Comment by sawenzel** [comment]
Looks good to me.

**Comment by mfasDa** [comment]
From the code it looks fine. Just needs a slight adaption of the commit message to be more specific.

**Comment by sawenzel** [comment]
According to my test, this PR is not yet fixing the wrong "pileup" signal with a low interaction rate (say 10kHz). Is this going to be fixed in another PR?

**Comment by mfasDa** [comment]
It is probably not a false pileup signal but a feature of the timeframe-based format.

**Comment by sawenzel** [comment]
Does this mean you have only one digit for the whole timeframe? I think that digits should still be created on a more elementary basis (say per readout frame or lower) ... and then I would not expect to see contributions from different collision for a digit in a given readout-frame if the interaction rate is low.

**Comment by mfasDa** [comment]
No, we have one *digits vector* for the entire timeframe, in addition we have a second vector with InteractionRecord and range reference for the digits in the digits record belonging to the same hardware trigger. This is the format we have in data, as the readout will give superpages with pages for all triggers per link for the entire timeframe, and for consistency we want to have the same format in data and simulation. Pileup we have if we have contributions from different events in Labels belonging to the same trigger record. Digits we have 1 per sample (100 ns).

**Comment by sawenzel** [comment]
It should be ok to have a single vector of Digits. Under the assumption you then keep the MC labels per individual object, I think there shouldn't be any pileup on the level of individual digits.
Could you please check this? I suggest to run the script check_embedding_pileup.sh with a low interaction rate (10000). I could be that my script is doing something wrong... ( It's not urgent of course but I would like to sort it out either way).

**Pull request merged**
