### PR TITLE
Add support for reading array columns from ROOT files

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ginnocen I also removed the old stuff we did before Christmas, I assume the new vertexer-hf supersedes that and in any case we should use the custom table reading which will be provided by @pbuehler.

**Comment by ktf** [comment]
@AliceO2Group/analysis-framework-developers this should fully enable array columns, which can now be put back in the schema (in a subsequent PR, once this passes).

**Comment by pbuehler** [comment]
> @ginnocen I also removed the old stuff we did before Christmas, I assume the new vertexer-hf supersedes that and in any case we should use the custom table reading which will be provided by @pbuehler.

shall the custom table reading be able to handle arrays as well?

**Comment by ktf** [comment]
Yes, but I thought that was a given no?

**Comment by pbuehler** [comment]
The custom reader is currently not able to read arrays. This has to be implemented.
Then what about writing? So far - at least that is my probably outdated understanding - we were talking about supporting flat trees.

**Pull request merged**
