### PR TITLE
DPL: invoke task destructor on exit

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr as discussed. You might have to remove your callback, though.

**Comment by davidrohr** [comment]
@ktf : could you rebase this? Then I would test it for my testcase.

**Comment by davidrohr** [comment]
@ktf : again, could you rebase :)

**Comment by davidrohr** [comment]
@ktf : pinging again :). Could you rebase the PR so I can test it?

**Pull request closed without merging**
