### PR TITLE
CPV geometry fix, run3 raw format. fix O2-1991

### PR DESCRIPTION
**Pull request by peressounko**
Fix for jira ticket 02-1991

### CODE REVIEW

**Comment by davidrohr** [comment]
@peressounko : I have just retried to simulate 10 Pb-Pb events with this patch and generate raw data, and it still segfaults for me.
I have uploaded my simulation files here: https://qon.jwdt.org/nmls/tmp/cpv_testcase.tar.bz2
The failing command is `o2-cpv-digi2raw --file-for link --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0" -o raw/CPV`
Output is:
```
[INFO] created output directory raw/CPV
[INFO] EP:0 CRU:0x0000 Link:0   FEEID:0x0000 SrcID:CPV[8] Packet:0   MemSize:0     OffsNext:0      prio.:0 HS:64 HV:6
[INFO] Orbit:0         BC:0    Stop:0 Page:0     Trg:00000000000000000000000000000000 Par:0     DetFld:0x0000
[INFO] Registered Link SubSpec=0x00000000(000:00:0) feeID=0x0000 with output to raw/CPV/cpv.raw
[INFO] [RawWriter] No reading calibration from ccdb requested, set default
./cpvraw.log_tmp.sh: line 1: 63697 Segmentation fault      o2-cpv-digi2raw --file-for link --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0" -o raw/CPV
```

```

**Comment by sawenzel** [comment]
I confirm @davidrohr message. This segfaults and I restarted the whole test from scratch.

**Comment by shahor02** [comment]
@peressounko with @davidrohr's  files it crashes for similar reason, now the ``row`` is in overflow:
````
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7ba49ae in o2::cpv::padCharge::padCharge (this=0x0, a=200, b=24) at /home/shahoian/alice/sw/SOURCES/O2/dev/0/Detectors/CPV/simulation/include/CPVSimulation/RawWriter.h:47
47	                                pad(b)
...
(gdb) 
#4  0x00007ffff7ba3838 in o2::cpv::RawWriter::processTrigger (this=0x7fffffff66f0, digitsbranch=..., trg=...) at /home/shahoian/alice/sw/SOURCES/O2/dev/0/Detectors/CPV/simulation/src/RawWriter.cxx:89
89	    mPadCharge[row][dilogic].emplace_back(charge, hwAddr);
(gdb) p row
$1 = 48
(gdb) p dilogic
$2 = 3
(gdb) p absId
$3 = 23061

````

**Comment by peressounko** [comment]
Dear @davidrohr, indeed in your file CPVHits already have incorrect detectorID>=23040. This causes crush in digits->raw. How did you produce hits? Is it possible they came from obsolete version? Could you please provide me command+ configuration? Best regards, Dmitri

**Comment by davidrohr** [comment]
@peressounko : I was running the script for the full system test with 10 events.
```
NEvents=10 NEventsQED=500 $O2_ROOT/prodtests/full_system_test.sh
```
This will run simulation / digitization / digits2raw / reconstruction. For me it was failing at cpv digits2raw, and the hits / digits files I sent were produced with that script.
The O2 software was the dev from this morning you commit from this PR on top.

**Review by davidrohr — APPROVED** [review]
Thx, this fixes the issues I have been seing

**Pull request merged**
