### PR TITLE
DPL: discard timeframe in case there is nothing which needs processing

### PR DESCRIPTION
**Pull request by ktf**
DPL: discard timeframe in case there is nothing which needs processing

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 as discussed. This should fix the broken fullCI test.

**Review by davidrohr — DISMISSED** [review]
seems plausible to me

**Review by shahor02 — APPROVED** [review]
Thanks! Now it worked.

**Comment by ktf** [comment]
Currently broken. Merging.

**Pull request merged**
