### PR TITLE
Basic vertexing configuration to boxgen

### PR DESCRIPTION
**Pull request by rpezzi**
Add vertex position (X, Y, Z) and widths (X, Y) to boxgen via BoxGunParam

### CODE REVIEW

**Comment by sawenzel** [comment]
This is probably not needed. We can already set the vertex with the InteractionDiamond parameter across all generators. Can you check if this is sufficient for you?

**Comment by rpezzi** [comment]
The interaction diamond method implements vertexes with Gaussian distributions for all axes, but in some cases, it may be preferable to have flat distributions. This is a standard feature of FairBoxGenerator, why not implement?

**Comment by sawenzel** [comment]
It wasn't mentioned that this is a flat distribution. I agree that it is a good feature but I think it should be done for all generators at the same time, using something like
```
InteractionDiamond.distribution = kFlat;
```

I am also wondering what will happen now if you set
```
BoxGen.vertex[0] = 3;
InteractionDiamond.vertex[0] = 5;
```
Who is taking precedence?

So, for now I would argue that we should always use the vertex set by InteractionDiamond and we can introduce the flat width property to BoxGen.  Would that be ok? Beyond that it would be fantastic if you could make a PR with a general solution.

**Comment by rpezzi** [comment]
I think you are right. Indeed, flat distributions are interesting to evaluate the track searching algorithms for vertexes along the Z axis. Unfortunately the FairBoxGenerator cannot do that, and this PR will not help.  

It would be straight forward to generalize fairroot's FairBoxGenerator class to support flat ranges in Z, but this is another story. I will close this PR.

**Comment by rpezzi** [comment]
> BoxGen.vertex[0] = 3;
> InteractionDiamond.vertex[0] = 5;

The resulting vertex is the sum of both. I will take a look at the proposed change to have configurable distributions on the InteractionDiamond.

**Pull request closed without merging**
