### PR TITLE
Revert "Empty shell VMCReplay structure"

### PR DESCRIPTION
**Pull request by ktf**
Reverts AliceO2Group/AliceO2#2767

### CODE REVIEW

**Comment by ktf** [comment]
@sawenzel @benedikt-voelkel @shahor02  this works around the missing `_pythia` symbols on Ubuntu. A proper solution probably requires some extra dependency elsewhere, but I am not completely sure where.

**Comment by sawenzel** [comment]
I think this calls for an Ubuntu CI. It will be otherwise hard to check if patches work or not.

**Comment by ktf** [comment]
Agreed.

**Comment by shahor02** [comment]
For me with this PR it works (ubuntu 18.04)

**Pull request merged**
