### PR TITLE
PWGHF: Update Xi_c task

### PR DESCRIPTION
**Pull request by aalkin**
* more signal/background histograms

@vkucera could you have at look at this one?

### CODE REVIEW

**Review by vkucera — DISMISSED** [review]

**Review by ginnocen — DISMISSED** [review]

**Comment by vkucera** [comment]
@jgrosseo @iarsene All green and approved. Can you please merge?

**Comment by ginnocen** [comment]
@aalkin can you add this variable in the selector and in the cut object as done in the Xicc analysis? 
https://github.com/AliceO2Group/AliceO2/blob/71213e027b0c26c9ea0ce4c7aab58bd5c0cfb525/Analysis/Tasks/PWGHF/HFXiccToPKPiPiCandidateSelector.cxx#L77

**Comment by ginnocen** [comment]
hi @aalkin please close it in case it is obsolete. thanks.

**Comment by aalkin** [comment]
Closing this as the similar changes are introduced elsewhere.

**Pull request closed without merging**
