### PR TITLE
Bugfix: converting integral numbers before dividing by scaling factor

### PR DESCRIPTION
**Pull request by matthiasrichter**
The float values of the TPC ClusterNative data struct are represented as
scaled integral numbers. Converting back to float has to be done before
division by the scaling factor.

Also adding a unit test for the TPC ClusterNative structure.

Minor clean up of forward declarations, in both files ClusterNative.h was
already included directly or indirectly.

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@davidrohr please also have a look

I sent you an invitation to join the team, then you can also be set as reviewer.

**Comment by davidrohr** [comment]
hi mathias, very funny, i discovered this bug today as well and was just preparing a pull request. and you initially caused the bug by asking me to change the scaling factors to integers, which removed the float conversion :| in any case, i totally agree. will have a closer look tomorrow.
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by davidrohr** [comment]
Hi Matthias,
as just discussed, I would merge it like this, modulo the name change to V1.
We had discussed this and came to the conclusion that the scale factors will not change because they basically map the TPC precision to the available integer bits, which will be constant throughout lifetime.

In addition, this is only a transient class in WP1 definition, which is not stored, and we could if needed anyway create a V2 version.

**Comment by matthiasrichter** [comment]
I have addressed the comment, merging an updated version of the commit.

**Pull request merged**
