### PR TITLE
Residual aggregator output dir specified automatically

### PR DESCRIPTION
**Pull request by martenole**
To enable automatic transfer of calibration output to EOS

### CODE REVIEW

**Comment by martenole** [comment]
This does actually not distinguish between a synthetic and a physics run. Can I check the `RUNTYPE` variable and in case it is not `PHYSICS` disable the output completely? Or should something else be checked to distinguish the run types for the synch. reco?

**Comment by davidrohr** [comment]
I think `$RUNTYPE` is the right thing to check.

**Comment by martenole** [comment]
I tested this locally with default RUNTYPE=Standalone and with RUNTYPE=SYNTHETIC. Only in SYNTHETIC I disable the file writing, because otherwise when the run type is not PHYSICS the calibration does not run at all.
Since we have only one meta file directory for all kinds of data maybe we could in a followup PR change CTF_METAFILES_DIR to METAFILES_DIR and define that centrally in setenv.sh instead of only in dpl-workflow.sh as it is now. But I don't want to change that now so that hopefully this PR can be merged today.

**Comment by chiarazampolli** [comment]
Hi @martenole , 
Which other run types (apart from PHYSICS) need this calibration? 
Chiara

**Comment by davidrohr** [comment]
I think the METAINFO_DIR should go to gen_topo.sh, since it should be set centrally for the epns. All EPN settings should go there, not to setenv.sh.

**Comment by martenole** [comment]
Hi Chiara, hi David,

> Which other run types (apart from PHYSICS) need this calibration?

this calibration is only needed for PHYSICS.

> I think the METAINFO_DIR should go to gen_topo.sh, since it should be set centrally for the epns. All EPN settings should go there, not to setenv.sh.

I agree it should be set in gen_topo.sh to the directory used on the EPNs. But in setenv.sh it should also be defined to `/dev/null` in case it was not previously set. The `/dev/null` is needed when not running on the EPNs

**Comment by chiarazampolli** [comment]
Ciao Ole, 

If it is to be run only in PHYSICS (as I thought), I don't understand the comment from before:
```
Only in SYNTHETIC I disable the file writing, because otherwise when the run type is not PHYSICS the calibration does not run at all.
```
Sorry if it is trivial.
Chiara

**Comment by martenole** [comment]
Ok I also did not say it correctly. In synthetics it should run as well, just to exercise the machinery. But in that case it should not create any ROOT output. In physics runs some files will be written and then transferred to EOS.

**Comment by martenole** [comment]
build/O2/o2 is restarting all the time. Will merge soon to have it in tomorrow's tag

**Pull request merged**
