### PR TITLE
Fix pushing bugs for ITS QC

### PR DESCRIPTION
**Pull request by JianLIUhep**
Fix pushing bugs for ITS QC.
- fixed an incorrect snapshot DataOrigin.
- fixed the pushing loop index 'j', which caused bogus outputs.

### CODE REVIEW

**Comment by shahor02** [comment]
@JianLIUhep, there are conflicts in this PR, could you please resolve them?

**Comment by JianLIUhep** [comment]
@shahor02 It's done. Thank you.

**Comment by shahor02** [comment]
@MichaelLettrich @ktf o2 check again shows ``c++: internal compiler error: Killed (program cc1plus)``, apparently due to the memory. Could the test be restarted?

**Comment by ktf** [comment]
I see it also elsewhere. I will restart it but I guess it's a problem with the machine.

**Comment by shahor02** [comment]
@MichaelLettrich the Travis CI seems to be stuck or did not update the status, is it possible to restart it?

**Comment by JianLIUhep** [comment]
Dear @shahor02, we committed our latest modifications. Could you please have a look at these? We can proceed with our QualityControl commit then. Thanks a lot!

**Pull request closed without merging**
