### PR TITLE
Ability to filter out empty events

### PR DESCRIPTION
**Pull request by sawenzel**
* Introduction of MCEventStats class to collect
  some global properties (number of hits, tracks, etc) done
  for one event. Such objects are attached to the MCEventHeader and can
  quickly be accessed for filtering MC events.

* First prototype of filtering out events which did not leave any
  detector response (hit)

* some reduction of verbosity (INFO -> DEBUG)

Implements most of https://alice.its.cern.ch/jira/browse/O2-604

### CODE REVIEW

**Comment by sawenzel** [comment]
@shahor02 : The requested feature should already work with `o2sim_serial`. I still need to make it optional and make it fully work in the parallel scenario. I leave this as WIP until finished.

**Comment by sawenzel** [comment]
@shahor02 : You could now try this out with `o2sim --noemptyevents ...`

**Comment by sawenzel** [comment]
@shahor02 : I tested using your setup and it works. Error in O2 a simple timeout (@dberzano : I thought timeouts should not cause a red cross?)

**Comment by shahor02** [comment]
Thanks @sawenzel ! Works as expected.

**Pull request merged**
