### PR TITLE
QED events integrated in DigitizationContext

### PR DESCRIPTION
**Pull request by sawenzel**
QED events are now handled by DigitizationContext so that
detectors can use them without having to provide custom treatment.

Application to ITS/MFT.

### CODE REVIEW

**Comment by sawenzel** [comment]
@shahor02: Would you be able to test this? I think we should make sure that this yields same results as before for ITS.

**Comment by shahor02** [comment]
Will test it. Why you refer to ITS/MFT? With per event treatment it should be applicable also to FIT

**Comment by sawenzel** [comment]
Yes of course but I have not enabled it for FIT yet.

**Comment by shahor02** [comment]
ok, did not notice you have suppressed the old qed treatment

**Comment by shahor02** [comment]
merging after 1st CI test passed as this is a trivial typo fix.

**Comment by shahor02** [comment]
@sawenzel terribly sorry, by mistake pressed merge button in the wrong window, reverting the merge

**Comment by shahor02** [comment]
@sawenzel Could you please reopen the PR?

**Pull request merged**
