### PR TITLE
Add protection for skipped MC particles; add filling PHOS MClabels

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Comment by peressounko** [comment]
Dear @mhemmer-cern, could you have a look at EMCAL part?

**Comment by peressounko** [comment]
Dear @sawenzel, running this code up to AO2D with 
${O2DPG_ROOT}/MC/bin/o2dpg_sim_workflow.py -eCM 14000  -col pp -gen boxgen -proc cdiff -tf 1     \
                                                       -ns 10 -e ${SIMENGINE}                   \
                                                       -j ${NWORKERS} -interactionRate 1000     \
                                                       -run 302000 -seed 624                     \
                                                       -confKey 'BoxGun.pdg=22; BoxGun.number=1; BoxGun.prange[0]=5; BoxGun.prange[1]=5.01; BoxGun.phirange[0]=250; BoxGun.phirange[1]=320; BoxGun.eta[0]=-0.12; BoxGun.eta[1]=0.12;' 


${O2DPG_ROOT}/MC/bin/o2_dpg_workflow_runner.py -f workflow.json -tt aod -j 1 --mem-limit 20000

and analyzing then AO2D with reading o2::soa::Join<aod::Calos, aod::McCaloLabels_001>, I get
[4250:calo-cluster-producer-task]: [13:09:34][ERROR] Dropping incomplete AOD/CPVCLUSTER/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[4250:calo-cluster-producer-task]: [13:09:34][ERROR] Dropping incomplete AOD/COLLISION/1 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[4250:calo-cluster-producer-task]: [13:09:34][ERROR] Dropping incomplete AOD/CALOTRIGGER/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[4250:calo-cluster-producer-task]: [13:09:34][ERROR] Dropping incomplete AOD/CALO/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[4250:calo-cluster-producer-task]: [13:09:34][ERROR] Dropping incomplete AOD/BC/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[4250:calo-cluster-producer-task]: [13:09:34][ERROR] Dropping incomplete AOD/TIMESTAMPS/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[4252:internal-dpl-aod-writer]: [13:09:34][ERROR] Dropping incomplete TFN/TFNumber/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[4252:internal-dpl-aod-writer]: [13:09:34][ERROR] Dropping incomplete TFF/TFFilename/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.

Is it possible that MC info is not stored for the very first event?
 Thanks, Dmitri

**Review by mhemmer-cern — DISMISSED** [review]
Looks good to me from EMCal side

**Comment by peressounko** [comment]
Dear @sawenzel, could you please have a look at this PR? Thanks, Dmitri

**Comment by sawenzel** [comment]
@peressounko : Can you clarify if you see the mentioned problems before or after this PR? I cannot comment much on your analysis problems. Maybe maintainers @nburmaso and analysis devs @aalkin can comment further. It might be good having a test analysis that we run nightly on PHS to test this ourselves.

Concerning the changes here: I guess you need to apply the same filtering as EMCAL ... but then instead of code duplication it might be better to introduce a helper function for the particle check which can be used by both EMC and PHS. I can try to rework your PR or you can try to do it.

**Comment by aalkin** [comment]
@peressounko please start with resolving merge conflicts here and trying with the latest code. If you provide the AO2D file, I can try to reproduce the problem at the analysis stage and probably diagnose what is wrong with the file.

**Comment by peressounko** [comment]
Dear @sawenzel, I have this problem after implementation of label propagation in this PR, otherwise we do not have PHOS labels at al. To test one needs updated version of CaloClusterProducer which consumes these labels and which I can not commit before this PR. If you do not see anything criminal here, lets merge this PR and continue discussion when I provide test code.
If @mhemmer-cern, I will merge both PHOS/EMCAL parts at they are identical now.

**Comment by aalkin** [comment]
The test code can be used from your branch in your fork of the repo, have you tested that other analysis workflows work with AO2D files made with this?

**Comment by peressounko** [comment]
Dear @sawenzel, tests passed, could you have a look? Thanks, Dmitri

**Review by mhemmer-cern — APPROVED** [review]
Changes look okay from EMCal side

**Comment by peressounko** [comment]
Dear @sawenzel, could you approve this PR? I prepared another one https://github.com/AliceO2Group/O2Physics/pull/2729 to study incomplete events, but it depends on filling of AOD implemented in this PR.
     Best regards, Dmitri

**Pull request merged**
