### PR TITLE
Install tests into tests/ instead of bin/

### PR DESCRIPTION
**Pull request by aphecetche**
Following the idea of this morning in the WP3 meeting to install the tests into a separate directory. The change here will install them into bin/test. @Barthelemy @ktf @dberzano Would that be OK for you ?

(I've also briefly tried https://stackoverflow.com/questions/39794611/how-to-put-test-executables-into-a-separate-folder-using-cmake but did not understand right away why the CMAKE_RUNTIME_OUTPUT_DIRECTORY is empty for us, so I gave up)

### CODE REVIEW

**Comment by sawenzel** [comment]
I think this is a good idea. Shall we go on? Can you remove the WIP?

**Comment by aphecetche** [comment]
@sawenzel At the last WP3 a small change was requested (change the destination directory). On my TODO ...

BTW, I'll make that one, but FYI I'm also in the process of a bigger "review" of the tests business. Details will appear someday in https://alice.its.cern.ch/jira/browse/O2-642 (which I should change the name of, as it's a bit wider scope than just changing the naming convention)

**Comment by Barthelemy** [comment]
@aphecetche what is the destination directory in the end ?

**Comment by aphecetche** [comment]
Dario proposed `tests` simply (instead of `bin/test` in this PR currently). Any objection ?

**Comment by Barthelemy** [comment]
fine with me

**Comment by Barthelemy** [comment]
I tested it and it works. If the destination directory is changed to tests then we are good to go I guess.

**Comment by ktf** [comment]
fine with me as well. Please remove the WIP when you are ready to merge.

**Pull request merged**
