### PR TITLE
Fix namespace naming: mathUtils mathBase

### PR DESCRIPTION
**Pull request by anerokhi**

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @anerokhi 

I think this will make the magnetic field (o2::field::MagneticWrapperChebyshev) objects (``O2/Common/maps/mfchebKGI_sym.root``) unreadable: it contains objects of  {{o2::mathUtils::Chebyshev3D}} class.To do this renaming cleanly, one should first dump the fields data to text format, reread them back with classes in the new namespace and regenerate the field's file, I should have somewhere the macro to do this, please hold on with this PR (at least for o2::mathUtils::Chebyshev... classes) until I find it.

**Comment by aphecetche** [comment]
@shahor02 btw, once you've located that macro, could you please commit it somewhere ? _Might_ be interesting for e.g. accessing the field from another language...

**Comment by sawenzel** [comment]
As general comment, this work is part of trying to converge to proper namespace usage according to coding rules. @anerokhi is doing this as part of his service task.
Once all namespaces fixed, the appropriate check will be enabled in the code checker. @shahor02 : Thanks for pointing out the serialization issue. I hope we don't yet have too many of those cases.

**Comment by shahor02** [comment]
@aphecetche OK, but for such exercises with dipole field you consider this "fast field" version: https://github.com/syamasak/AliRoot/commit/873958b41219dac04c85b97a598690f8461a51ec. I still need to validate it, but eventually it will substitute the dipole part of current field (order of magnitude faster).

**Comment by shahor02** [comment]
@anerokhi : once PR https://github.com/AliceO2Group/AliceO2/pull/1808 is merged, please update/rebuild dev branch, run from any directory (except ``$O2_ROOT/share/Common/maps/mfchebKGI_sym.root``)

````root -b -q alice/O2/Common/Field/macro/extractMapsAsText.C+````

this will dump the field objects to text files in local directory.
Then rebase your branch to dev, and from you branch (with modified namespaces), run
````root -b -q alice/O2/Common/Field/macro/createMapsFromText.C+````

Just copy the locally created ``mfchebKGI_sym.root`` to ``O2/Common/maps/mfchebKGI_sym.root`` and add this modification to this PR.  See https://github.com/shahor02/AliceO2/blob/dev_FldManip/Common/Field/macro/README.md

**Comment by anerokhi** [comment]
`build/o2checkcode/o2` tests failed with `fork: Cannot allocate memory`

**Comment by sawenzel** [comment]
So I guess we are ready to go here? @shahor02 ? (The new field map seems attached to the PR).

**Comment by shahor02** [comment]
@anerokhi, could you please use this version of [mfchebKGI_sym.root](https://cernbox.cern.ch/index.php/s/uzIde2BnZi1px3i). There were some irregularities in the original field map which I've fixed a long time ago locally but did not push. Now, since we are anyway updating this large file, we can fix it in O2. I have already converted it to the new namespace, just substitute your file with mine.

Cheers,
  Ruben

**Comment by anerokhi** [comment]
@shahor02 done.
BTW, wouldn't it be better to generate this `.root`-file at build time? (yes, I've seen how big the `.txt`-files are.)

**Comment by shahor02** [comment]
@anerokhi since these text files are so large and even a small modification in the field (except this namespace problem) would completely change all of them, we would not actually gain anything from storing the text version of the field...

**Pull request merged**
