### PR TITLE
fix in track propagation to TOF for MC

### PR DESCRIPTION
**Pull request by noferini**
This is to fix an issue for missing piece in track length for TOF.
For the moment it is applied only to MC since for DATA old calibrations have to be adjusted before to apply the fix

watchers: @chiarazampolli @njacazio @ercolessi

### CODE REVIEW

**Comment by noferini** [comment]
Hi @shahor02 ,
I started the review of this PR but I didn't mark it for Pb-Pb apass1. As discussed for the moment this is needed only for MC (mainly for other data passes and in view of QM approvals).
I tested it and both results and cpu performances are fine (CPU time unchanged).
... waiting for your review
Cheers,
Francesco

**Review by shahor02 — APPROVED** [review]

**Comment by shahor02** [comment]
@noferini thanks, looks good, shall I merge it already?

**Comment by noferini** [comment]
Hi @shahor02
thanks!
I think it can be merged,  since RelVal is already running and I assume this will not enter in Pb-Pb apass1 reco.
Let's wait also for a confirmation by @chiarazampolli or @alcaliva

**Comment by chiarazampolli** [comment]
Thanks, merged. 
We might cherry-pick this one or tag from the daily of 17.12 (where it will be included).

**Comment by chiarazampolli** [comment]
Hello, 

There was a misunderstanding from this PR: I thought that the worry was that it did not go to the tag for apass1 of PbPb 2024, which is actually what @noferini wanted. So in the end it did enter... We need to revert it there.

**Comment by alcaliva** [comment]
Hi @noferini , is this feature needed also for apass7? 
When porting this PR to async-v1-01-02g I get conflicts (see below)

ERROR: There was a problem cherry-picking 7e245782330f9e5bec8fb624a061edad04a7356d
  Auto-merging DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoTOF.h
  Auto-merging DataFormats/Reconstruction/include/ReconstructionDataFormats/MatchInfoTOFReco.h
  Auto-merging Detectors/GlobalTracking/include/GlobalTracking/MatchTOF.h
  Auto-merging Detectors/GlobalTracking/src/MatchTOF.cxx
  CONFLICT (content): Merge conflict in Detectors/GlobalTracking/src/MatchTOF.cxx
  error: could not apply 7e24578233... fix in track propagation to TOF for MC (#13784)
  hint: After resolving the conflicts, mark them with
  hint: "git add/rm <pathspec>", then run
  hint: "git cherry-pick --continue".
  hint: You can instead skip this commit with "git cherry-pick --skip".
  hint: To abort and get back to the state before "git cherry-pick",
  hint: run "git cherry-pick --abort".

**Comment by noferini** [comment]
Hi @alcaliva ,
I resumed only today an I saw your message.
It seems to me that the conflict was due to this missing PR
https://github.com/AliceO2Group/AliceO2/pull/13582

**Pull request merged**
