### PR TITLE
Moving T0 and V0 to VLAs

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
This is a demonstrator for using variable-length arrays for T0. It has to be carefully checked because all old AO2Ds are not readable anymore after this.
It requires the following change in O2Physics: https://github.com/AliceO2Group/O2Physics/pull/407
and the following change in the Run 2 converter: https://github.com/jgrosseo/AliPhysics/commit/0dc177907331a134663d7f0cfc3a75f5d187a656

**Comment by jgrosseo** [comment]
We need to decide which other tables should follow this schema depending on how scarce they are filled.

**Comment by AllaMaevskaya** [comment]
Great! 
One thing more : if we have now VLA may be we can add to AO2D individual channels time?

**Comment by pzhristov** [comment]
@AllaMaevskaya I have the impression that you are storing the raw data in the AO2Ds. What kind of processing do you do to fill the information added in this PR?

**Comment by AllaMaevskaya** [comment]
Yes, you are right, now I am storing uncalibrated amplitude in individual channels  for event plane and multiplicity analysis. We will do amplitude calibration based on pilot beam data before February.

**Comment by jgrosseo** [comment]
This includes https://github.com/AliceO2Group/AliceO2/pull/7857 and will be rebased after it is merged

**Review by AllaMaevskaya — DISMISSED** [review]

**Comment by jgrosseo** [comment]
AliPhysics PR: https://github.com/alisw/AliPhysics/pull/19217
We then reconvert and merge this

**Comment by jgrosseo** [comment]
Do NOT merge yet. Run 2 conversion is running.

**Comment by jgrosseo** [comment]
CI OK, except compilation of O2Physics which is expected.
Force merging the O2 and O2Physics PRs

**Pull request merged**
