### PR TITLE
Template class for a vector that reduces the memory allocation

### PR DESCRIPTION
**Pull request by dstocco**

### CODE REVIEW

**Comment by shahor02** [comment]
@dstocco What is the difference wrt the vector with reserved size?

**Comment by dstocco** [comment]
Hi @shahor02 ,
one of the most time consuming part of clustering and tracking is the memory allocation for objects.
Even if one sets the vector size, the process of creating a new object to be added to the vector is quite time consuming....and rather useless in the end since I can re-use the objects in the vector.
So the idea is to simply re-use the vector elements, creating them only when necessary.

When I clear the PersistentVector, I do not touch the objects inside, but rather sets the vector index to 0, meaning that, next time I need an object in the vector, it will return the first one.
The inner vector resize itself only if the number of objects I need is larger than the reserved ones at the beginning (I do not know a priori the number of clusters/tracks that I will have).

This is much more effective than re-constructing the objects in the vector each time, and, most importantly, does not require to know a priori the maximum size that my vector should need...

Cheers,
Diego

**Comment by shahor02** [comment]
Hi @dstocco, Actually, ``vector::push_back(x)`` does not allocate any memory if its size is less than the reserved capacity. It just calls the copy constructor with placement.

**Comment by dstocco** [comment]
Hi @shahor02 ,
ok, but this still implies creating a local object and then pushing it. Of course this issue can be circumvented with emplace_back, but it requires a proper constructor for the pushed objects.
Also, the object destructor is called when the vector is cleared.
All in all, it adds operations that can be avoided.

Finally, if one wants to avoid the std::vector to be resized, one would need to know a priori a maximum size for the vector, which is not always straightforward.

Cheers,
Diego

**Comment by shahor02** [comment]
@dstocco 

> ok, but this still implies creating a local object and then pushing it. Of course this issue can be circumvented with emplace_back, but it requires a proper constructor for the pushed objects.

Your class implies that the class has a default constructor, so you can anyway use ``emplace_back()``
The way you would use your vector is to pick an existing object and modify its state (i.e. call some setters), calling emplace_back(...) with meaningful arguments on reserved state would have the same cost.

> Also, the object destructor is called when the vector is cleared.
Yes, avoiding the destructor call the only gain from such a vector, though, in case your class allocates a memory, this will create a problem. If it does not allocate the memory, then the destructor is usually trivial and costs virtually nothing. So, effectively you just a loop over vector elements.

> Finally, if one wants to avoid the std::vector to be resized, one would need to know a priori a maximum size for the vector, which is not always straightforward.

I was speaking about ``reserve(n)`` rather thann ``resize(n)``. It will work exactly in the same way as in your class.

Anyway, I was not objecting your vector (for POD classes there will be indeed a small gain), just commented on the title that it reduces the memory allocation (it is not)...

Cheers,
 Ruben

**Comment by ktf** [comment]
I am also puzzled of what would be the advantage of this over `std::vector` + `reserve` + `emplace_back`. Moreover, you do not use polymorphic resources, so if this is to be messaged you will pay a copy of the whole think to the transport memory.

**Comment by sawenzel** [comment]
I agree with @shahor02 and @ktf. We should avoid making new container classes and in the past we had already argued the same way with several other propositions

**Comment by dstocco** [comment]
Hi all,
ok, I see your point: let me perform a quick benchmark before dropping my PR.

Best regards,
Diego

**Comment by dstocco** [comment]
Hi all,
I made a benchmark. Indeed, if I have a vector of simple types, using my PersistentVector or the std::vector yields similar times.
However, sometimes we need (for internal calculations) to have a vector of structs, and the structs contain a vector inside. This is the typical case of the clustering, where, internally, we have vector of structs containing the pre-clusters in the specific detection element.

As a dummy example I tested with the following struct:
```
struct MySubStruct {
  std::array<float, 3> array;
  float number = 0;
};

struct MyTestData {
  std::vector<MySubStruct> subStruct; ///< Position
  std::array<float, 3> array = {};    ///< Direction
  int number = 0;
};

```

Now, in this case the difference between the std:vector (that deletes the structure at each time, clearing its vector data member) and the PersistentVector, that does not perform any delete at all is a factor of ~7:
```
BM_STLVEC     8439000 ns    8425987 ns         78
BM_MYVEC      1262945 ns    1262178 ns        573
```

So I can probably use std::vector most of the time, except when I have a structure containing a vector (which, as I said, happens during clustering). Of course, this is an implementation detail, internal to the device, and I never use such structure as device output (otherwise the serialisation becomes a mess).
Cheers,
Diego

**Comment by sawenzel** [comment]
Could you please share the program that performs the benchmark? I think it is important to see how things are done.

**Comment by shahor02** [comment]
@dstocco If your underlying class allocates memory memory (e.g. vector), then, obviously clearing the top container vector will create an overhead. The price is that the ``next()`` method of your PersistentVector returns you an object with a random state, which you need to clear etc. I would say simply that using a vector of vectors is a bad idea. Also, such a PersistentVector cannot be properly stored in the root file.

**Comment by dstocco** [comment]
@sawenzel : I updated the PR adding the associated benchmarks.

@shahor02 : the point is that I never use a PersistentVector to be stored in root file. Since it is a wrapper for a std::vector, I can easily convert it to a std::vector of the proper size or a gsl::span, with basically no overhead. For what concerns the outputs, I always use std::vector (or gsl::span) of basic types, so that no serialisation is needed. So, the storage of the output in a file is not an issue.
Anyways, I can review my code before the PRs that are in my to-do list in order to use a std::vector instead of a PersistentVector whenever the gain in time is negligible...

**Comment by dstocco** [comment]
Dear all,
I reworked my code to eliminate all occurrences of PersistentVector. Since I had reduced the number of vectors of vectors to the minimum, the variation in performance does not seem to be relevant compared to std::vectors. 
I therefore close this PR.

**Pull request closed without merging**
