### PR TITLE
Update jet finder task to use dynamic track columns

### PR DESCRIPTION
**Pull request by qgp**
@jgrosseo @nzardosh using the dynamic track columns now

### CODE REVIEW

**Comment by ktf** [comment]
@MichaelLettrich any news about fixing the Mac builds? This is one example I was referring to the other day.

**Comment by ktf** [comment]
@MichaelLettrich any news about fixing the Mac builds? This is one example I was referring to the other day.

**Comment by ktf** [comment]
That said, you cannot use any type as Configurable. Are those enums?

**Comment by qgp** [comment]
> That said, you cannot use any type as Configurable. Are those enums?

@ktf Yes, I had (mis-)understood on Monday that that should already work. Should I remove those configurables (for now)?

**Comment by ktf** [comment]
Or just use `Configurable<int>`. I've added supporting enums to the todo list.

**Comment by qgp** [comment]
> Or just use `Configurable<int>`. I've added supporting enums to the todo list.

@ktf That gets ugly because of explicit casting to the enums in other places. I have taken out the Configurables for now, to be added when enums are supported.

**Comment by ktf** [comment]
I will add it later today. Should be trivial enough...

**Comment by qgp** [comment]
> I will add it later today. Should be trivial enough...

Yes, but does this really help to make things easier now? Changing these settings from the command line is not really urgent now, so we can just wait to have Configurables for enums. My two cents ...

**Pull request merged**
