### PR TITLE
Increasing timeout for DPL unit test workflows from 30 to 60 sec

### PR DESCRIPTION
**Pull request by matthiasrichter**
Looking at one of the latest log files of a failing DPL workflow unit test
on the macos CI it seems that the failing test has been aborted in the middle
of the processing. Maybe the startup for some reason takes too long time and
then the test can not properly finish within the timeout.

### CODE REVIEW

**Comment by aphecetche** [comment]
Hi,

This is only tangentially related to this PR, but I'd say at some point we should really define what we call a unit test, in particular how long can it takes. Long (how long is the question) tests are quite inconvenient during development IMO. Longer tests are also necessary of course, but I would not call them unit tests then (but more integration tests, or something alike).

Just my 2 cents anyway.

**Comment by matthiasrichter** [comment]
Hi Laurent,
point taken. Actually the longest tests we run are the G4 simulation tests with about 20 s, all the others are below 10 s with the majority less than 1 s. Also the workflow test, which are real unit tests in a slightly more complex setting, are normally done in less than 1s.

There is obviously some interference  on the build servers, probably there is too much running at the same time. So the real problem is probably there.

Is there a particular example of a unit test you are bothered by during development?

Ciao
Matthias

**Comment by matthiasrichter** [comment]
@sawenzel, @ihrivnac now the G4_mt test is failing here
```
>>> Event 9
[INFO] Stack: 635 out of 2308 stored 

Time of this run:   User=5.63s Real=5.63s Sys=0.01s
Number of events processed: 10
[INFO] Macro finished succesfully.
[INFO] Real time 12.003 s, CPU time 12s
[INFO] Memory used 563.543 MB
o2sim(47808,0x7fff9393b380) malloc: *** error for object 0x7fb0e314d810: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Produced hits 108097
Produced electrons 990123
Stepping called 114956
```
some memory corruption

**Comment by ihrivnac** [comment]
The file changes in this PR have nothing to do with simulation, unless the test was stopped before due to time-out. Do we have access to the previous logs?
The memory corruption happens at the end of everything so it looks like a problem in destructing objects. I will try to reproduce it. What's the version of FairRoot used for these tests?

**Pull request merged**
