### PR TITLE
Raw data files reader workflow

### PR DESCRIPTION
**Pull request by shahor02**
Allows to feed raw data from files (create from MC or real ones) into the DPL workflows w/o going via
``readout.exe -> StfBuilder -> o2-dpl-raw-proxy `` processes.
See README for details.

### CODE REVIEW

**Comment by shahor02** [comment]
@MichaelLettrich @ktf the Travis CI seems to be stuck in all PRs...

**Comment by sawenzel** [comment]
Could you force push? I think the travis CI should come back after that.

**Comment by wiechula** [comment]
Hi @shahor02 , what is the expected input file format?

**Comment by shahor02** [comment]
@wiechula The format is supposed to be "variable CRU page size", but as a particular case also the 8kB fixed pages should work. The details are are described here: https://alice.its.cern.ch/jira/browse/O2-972

**Comment by wiechula** [comment]
@shahor02 , thanks!

**Comment by shahor02** [comment]
@wiechula just saw the additional questions:
Yes, the input files are supposed to be equivalent to the readout.exe output, and one can combine them (see the README in the Detectors/Raw). 

What do you mean by the TF building? In principle, it emulates the behaviour of the ``readout.exe -> StfBuilder``, relaying on the TF trigger bits present in the RDHs (as StfBuilder does).
So, it takes continuous data and injects into the DPL for every link a multipart with 1 "part"/message per HBF. There is an option to generate a single message for the whole TF (like the raw-proxy does).
 
If you mean using test data and chopping it to TFs of fixed N HBFs regardless of the presence of  TF trigger, this is not done at the moment, but in principle, can be implemented (we were discussing this today for the ITS, whose test data has not TF flags).

**Pull request merged**
