### PR TITLE
[O2-4578] DPL: attempt at removing a race condition in the rate limiting

### PR DESCRIPTION
**Pull request by ktf**
[O2-4578] DPL: attempt at removing a race condition in the rate limiting

### CODE REVIEW

**Comment by davidrohr** [comment]
ok, but please merge only once the retry handling is implemted.

**Comment by ktf** [comment]
This should be what we need, but it needs testing.

**Comment by davidrohr** [comment]
@ktf : What is the status of this? All CIs are red :(

**Comment by ktf** [comment]
I am on it right now.

**Comment by ktf** [comment]
This seems to now work now. Tests are passing and AFAICT async reco works. How can we test the FIT issues?

**Pull request merged**
