### PR TITLE
Do not get B field from external file anymore, but from CCDB - O2

### PR DESCRIPTION
**Pull request by chiarazampolli**
@knopers8 , @shahor02 goes with:
https://github.com/AliceO2Group/QualityControl/pull/1692
https://github.com/AliceO2Group/O2DPG/pull/977

Tested within async reco and also as standalone with:
``` 
o2-global-track-cluster-reader --track-types "TPC,ITS-TPC" --hbfutils-config o2_tfidinfo.root --disable-mc | o2-itstpc-match-qc --disable-mc -b
```

### CODE REVIEW

**Comment by chiarazampolli** [comment]
The error is due to thd dependency between PRs…

chiara

**Comment by iravasen** [comment]
Hi @chiarazampolli thanks a lot! Few comments:
- can I kindly ask you to apply the same modification here (this task runs on FLP but I guess there is no difference right?) ? https://github.com/AliceO2Group/QualityControl/blob/22302d0a8ff43cac6372c394ef002319275a92ec/Modules/ITS/src/ITSClusterTask.cxx#L105-L118 
- can you please remove these lines here https://github.com/AliceO2Group/QualityControl/blob/22302d0a8ff43cac6372c394ef002319275a92ec/Modules/ITS/itsFhr.json#L55-L56 and herehttps://github.com/AliceO2Group/QualityControl/blob/22302d0a8ff43cac6372c394ef002319275a92ec/Modules/ITS/itsCluster.json#L47-L48 ? 

Let me know if you have troubles, thanks, cheers
Ivan

**Comment by chiarazampolli** [comment]
Hi @iravasen , 
Please, check https://github.com/AliceO2Group/QualityControl/pull/1692/commits/188d7f180704bf09da0788fbe665f7aca7d814a0, I think this is what you meant (while you pointed at https://github.com/AliceO2Group/QualityControl/blob/22302d0a8ff43cac6372c394ef002319275a92ec/Modules/ITS/src/ITSClusterTask.cxx#L105-L118 where I changed already).
Chiara

**Comment by iravasen** [comment]
Hi @chiarazampolli, sorry I commented the wrong PR and with the wrong link.... my bad. 
I continue on QC.

**Pull request merged**
