### PR TITLE
Fix some of the ALICE 3 geometry issues

### PR DESCRIPTION
**Pull request by mconcas**
Hi @sawenzel @qgp,

I just fixed some default values for the geometry of ALICE 3. I kindly need your approval and merge.

@rpezzi  I am stll trying to do the fix for FT3 escavations in vacuum volume. Unfortunately tentatives so far failed for some yet  unknown reason.
Difference with TRK is that I have to apply a transformation (z-translations) to the shapes of inner disk-holes and somehow this breaks the geometry streaming on file. For TRK it works because all the holes are centered in 0,0,0 and transformations are not required. I'll investigate a bit more on that.

### CODE REVIEW

**Review by sawenzel — DISMISSED** [review]

**Comment by sawenzel** [comment]
@afurs : A think your recent PR broke the MacOS builds. Could you please take a look and fix asap? 
```
System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6562/0/Detectors/FIT/raw/include/FITRaw/DigitBlockFIT.h:91:19: error: implicit truncation from 'int' to bit-field changes value from 131071 to -1 [-Werror,-Wbitfield-constant-conversion]
    tcmData.amplA = 131071; //2^17
                  ^ ~~~~~~
/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6562/0/Detectors/FIT/raw/include/FITRaw/DigitBlockFIT.h:292:26: note: in instantiation of function template specialization 'o2::fit::DigitBlockFIThelper::ConvertDigit2TCMData<o2::ft0::Digit, o2::fit::TCMdata>' requested here
--
In file included from /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6562/0/Detectors/FIT/FT0/simulation/src/digit2raw.cxx:26:
In file included from /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6562/0/Detectors/FIT/FT0/raw/include/FT0Raw/RawWriterFT0.h:20:
In file included from /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6562/0/Detectors/FIT/FT0/raw/include/FT0Raw/DigitBlockFT0.h:19:
/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6562/0/Detectors/FIT/raw/include/FITRaw/DigitBlockFIT.h:96:19: error: implicit truncation from 'int' to bit-field changes value from 131071 to -1 [-Werror,-Wbitfield-constant-conversion]
    tcmData.amplC = 131071; //2^17
```

**Comment by afurs** [comment]
Hello @sawenzel , 
I'm sorry for this. 

Related PR(#6566 ) is prepared.

**Comment by sawenzel** [comment]
@afurs : Thanks and no worries.

**Review by qgp — APPROVED** [review]

**Comment by ddobrigk** [comment]
Hi everyone, I am sorry to be pushy... but Bernhard and I would really like to have this merged soon so that we can run our strangeness tracking on batch farms. Would it be possible to merge this soon? Thank you very much!

**Comment by marcovanleeuwen** [comment]
Hi David, all, Jochen already approved, so it is not clear to me where/why this is stuck. I don't think I can do much myself, I don't even have the option to approve as far as I can see... It may need a force-merge to clear the errors from the CI?

**Review by marcovanleeuwen — APPROVED** [review]

**Comment by sawenzel** [comment]
Unfortunately github does not show PRs as an approved status when it's only partially approved, so it slipped my attention.

**Pull request merged**
