### PR TITLE
Use a job pool for analysis tutorial

### PR DESCRIPTION
**Pull request by ktf**
Defaults to 4 parallel jobs. Can be modified via:

cmake -DANALYSIS_JOB_POOL=<N> ...

### CODE REVIEW

**Comment by ktf** [comment]
One job at the time is far from ideal, but at least seems to cure the issue.

**Comment by davidrohr** [comment]
What is this needed for? It roughly quadrupples my O2 build time.
(This is realted to each of the analysis tutorial files whose build is serialized taking 20 - 40 seconds, which is kind of an issue by itsef (see https://alice.its.cern.ch/jira/browse/O2-2094))

**Comment by ktf** [comment]
To make sure we do not compile too many analysis jobs at the same time. It should apply to only 10 files, though. Is that really an issue?

**Comment by davidrohr** [comment]
Well, there are 32 files compiled with the job pool. When each takes ~30 seconds, you do the math.

**Comment by ktf** [comment]
I changed it to two in #5645. Let's see how that goes.

**Pull request merged**
