### PR TITLE
DPL: notify DPL about out of band data being sent by input proxy

### PR DESCRIPTION
**Pull request by ktf**
DPL: notify DPL about out of band data being sent by input proxy

This is needed to avoid skipping some of the callbacks, in particular
the CCDB one.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr this is the eventual fix for the input proxy, I did not check it yet.

**Comment by davidrohr** [comment]
should we trigger this only in case data was really sent? E.g. to avoid it for EoS?

**Comment by ktf** [comment]
Indeed, updated accordingly. I have also done https://github.com/AliceO2Group/AliceO2/pull/12101, which generalises the behaviour, and makes sure that any proxy tells DPL when they send messages out of band.

**Comment by davidrohr** [comment]
@ktf : CI seems not to fail, probably since it is not testing the input proxies. I will put the later changes in a separate PR

**Pull request merged**
