### PR TITLE
DPL: reduce the amount of stuff exposed to cling

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@aalkin the problem seems to be the `variant<SomethingWithVariantInside>`.
@Barthelemy this works around the issue with the variant, however now something else which I committed recently breaks. This is particularly weird because it was crosschecked also by @knopers8. What I also do not understand is that the error is as if QC was compiled with an old version of the compiler (i.e. the system one) rather than the one we provide. Is it possible that somehow the CMake in QC is misbehaving?

**Comment by ktf** [comment]
@aalkin it's probably a good idea if we separate the construction of the expression from the actual parsing of the AST and only expose the former in the ASoA.

**Comment by Barthelemy** [comment]
@ktf I will check the compiler

**Comment by Barthelemy** [comment]
@ktf 
I see that it finds the correct compiler : 
```
-- Check for working CXX compiler: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-2/bin/c++
-- Check for working CXX compiler: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-2/bin/c++ -- works```

The error states only : 
```
[  4%] Generating G__QualityControl.cxx, ../lib/G__QualityControl_rdict.pcm, ../lib/libQualityControl.rootmap
gmake[2]: *** [Framework/G__QualityControl.cxx] Error 1
gmake[2]: *** Deleting file `Framework/G__QualityControl.cxx'
gmake[1]: *** [Framework/CMakeFiles/QualityControl.dir/all] Error 2
gmake: *** [all] Error 2
## End sw/BUILD/QualityControl-latest/log
```
Do you have any other detail ?

**Comment by Barthelemy** [comment]
@ktf I have finally been able to see the error message from `rootcling_wrapper.sh`:
```
[O2/latest] ~/alice/sw/BUILD/d32f90f0d3074c7e4863fae17fc8726d1c53f92a/QualityControl/Framework $> more /home/bvonhall/alice/sw/BUILD/d32f90f0d3074c7e4863fae17fc8726d1c53f92a/QualityControl/Framework/G__QualityControl.cxx.log
In file included from input_line_12:138:
In file included from /home/bvonhall/alice/sw/slc7_x86-64/O2/0_O2_DATAFLOW-1/include/Framework/Task.h:13:
In file included from /home/bvonhall/alice/sw/slc7_x86-64/O2/0_O2_DATAFLOW-1/include/Framework/AlgorithmSpec.h:13:
In file included from /home/bvonhall/alice/sw/slc7_x86-64/O2/0_O2_DATAFLOW-1/include/Framework/ProcessingContext.h:14:
In file included from /home/bvonhall/alice/sw/slc7_x86-64/O2/0_O2_DATAFLOW-1/include/Framework/DataAllocator.h:13:
/home/bvonhall/alice/sw/slc7_x86-64/O2/0_O2_DATAFLOW-1/include/Framework/ContextRegistry.h:46:13: warning: inline function 'o2::framework::ContextRegistry::get<o2::framework::MessageContex
t>' is not defined [-Wundefined-inline]
  inline T* get() const;
            ^
/home/bvonhall/alice/sw/slc7_x86-64/O2/0_O2_DATAFLOW-1/include/Framework/DataAllocator.h:377:38: note: used here
    auto context = mContextRegistry->get<MessageContext>();
```
Not sure where to go from here. I am also pinging @knopers8.

**Comment by knopers8** [comment]
>  This is particularly weird because it was crosschecked also by @knopers8. 

I've built just O2 though, not QC, because the Data Sampling benchmark was on my branch in O2. I don't know what is the problem, I will try to give it more thought.

**Comment by Barthelemy** [comment]
I tried to merge the latest changes from dev

**Comment by Barthelemy** [comment]
@ktf not sure if it is my merge, but it is all broken now.

**Comment by Barthelemy** [comment]
not sure this should stay open.

**Comment by ktf** [comment]
In principle part of it would still be nice to have, but I guess I can redo it.

**Pull request closed without merging**
