### PR TITLE
Fix ITS CA tracker bug introduced while fixing OpenCL warnings

### PR DESCRIPTION
**Pull request by mpuccio**
Checked and fixed this morning with @iouribelikov.
@shahor02 can you please check if this is also working for you?

Thanks a lot!

### CODE REVIEW

**Comment by mpuccio** [comment]
@davidrohr , this should not anyway introduce any new warnings in OpenCL

**Comment by davidrohr** [comment]
@mpuccio : I already checked, it's all fine, thx for pinging me.

**Comment by shahor02** [comment]
@mpuccio: I still see much lower eff than with CM, especially at low pt and large |eta|. Results are for 20 min.bias. pbpb events (vertex in Z=0)
itspbpb20ev

**Comment by iouribelikov** [comment]
@shahor02 Hi Ruben,
What were the events you used for this test ?   Was it Hijing from AliRoot, or Pythia8 from O2 ?
Myself, I've been using Hijing from AliRoot (the kinematics files you provided, sometime ago).
And, for me, this PR works perfectly fine.

**Comment by shahor02** [comment]
@mpuccio these were pythia8hi events, can try also with Hijing, but I don't see why it should matter

**Comment by mpuccio** [comment]
@shahor02 actually this is what I see locally with Pythia8HI, but on Yura laptop on different events we were seeing larger efficiency. I will dig a little bit more...

**Comment by iouribelikov** [comment]
@shahor02 Sorry Ruben.  You were actually right. 
When checking this PR, I forgot to activate the CA tracker :(.  Forget my previous comment.

Now, I see what you saw.  Also when working with the Hijing files produced by you in AliRoot.

I am having a deeper look too.

**Comment by shahor02** [comment]
Now tried with 130 Hijing events (with external kinematics, those which I've shared), results are even stranger: now the DPL_CA is higher then DPL_CM. But the DPL_CM is consistent witn CM run via ``O2/macro/run_trac_its.C`` while the CA via ``O2/macro/run_trac_ca_its.C`` shows lower results (and almost consistent with CM...). 

Note that ``run_trac_ca_its.C`` required some fixes (suggested by David), @mpuccio , could you add the patch below to this PR?

pbpb_130ev_all

````
--- a/macro/run_trac_ca_its.C
+++ b/macro/run_trac_ca_its.C
@@ -51,10 +51,10 @@ void run_trac_ca_its(bool useITSVertex = false,
                      std::string paramfilename = "o2sim_par.root")
 {
 
-  gSystem->Load("libITStracking.so");
+  gSystem->Load("libO2ITStracking.so");
 
   std::unique_ptr<GPUReconstruction> rec(GPUReconstruction::CreateInstance());
-  auto* chainTracking = rec->AddChain<GPUChainTracking>();
+  //  auto* chainTracking = rec->AddChain<GPUChainTracking>();
   auto* chainITS = rec->AddChain<GPUChainITS>();
   rec->Init();
````

**Comment by davidrohr** [comment]
@mpuccio @shahor02 : Please don't commit the change that disables the chainTracking, it will break the ITS GPU track fit, I am working on a proper fix. (Currently, it collides with some sanity checks I added for the TPC, since there are no TPC clusters.)

**Comment by iouribelikov** [comment]
@shahor02 This we saw with Max this morning: DPL_CA higher that DPL_CM.
We also found the reason, and it was fixed locally, on my laptop. 

I am checking what could get wrong on the way to the actual PR...

**Comment by mpuccio** [comment]
@iouribelikov , this morning there was the reused cluster issue that is fixed in this PR. The higher efficiency at low pt is consistent with the difference we usually saw between CA and CM.
Two things have to be understood:

- [ ] What is the difference between DPL running and the macro
- [ ] Why we see a difference between Pythia8 and HIJING

**Comment by iouribelikov** [comment]
@mpuccio The difference between the macro and DPL is, likely, this:
the macro runs with the primary vertex at (0,0,0) by default,
whereas the DPL runs with the real vertexer by default

**Comment by mpuccio** [comment]
Uhm @shahor02 did you run the DPL workflow with this PR included? If not then Yura is right: the difference is just due to the multiple vertices in some events.

**Comment by shahor02** [comment]
@mpuccio I used your branch mpuccio:fix_CA. Also checked with pp events (pythia), the CA there is also slightly higher than the CM.

**Comment by davidrohr** [comment]
Ciao @mpuccio : Now that the CMake migration is through and there are no conflicts, since this fixes a bug introduced with the OpenCL protection, I think this can be merged? Any other fix for the ITS efficiency will anyway be unrelated and come on top?

**Comment by mpuccio** [comment]
Yes, let's merge this! Thanks!

**Pull request merged**
