### PR TITLE
Supporting also vector<pod> in the RootTreeWriter

### PR DESCRIPTION
**Pull request by matthiasrichter**
This is a first sketch for the functionality requested by @shahor02 

A couple of things need to be polished and the unit test has to be completed.

It also depends on the correct implementation of `InputRecord::get, WIP in PR #2617 

EDIT:
- [x] dependency to PR #2617 removed
- [x] unit tests for vectors of messageable types with and without ROOT dictionary and the original support for vectors of non messageable types with dictionary

### CODE REVIEW

**Comment by shahor02** [comment]
@matthiasrichter thanks! If you think the final implementation (including # https://github.com/AliceO2Group/AliceO2/pull/2525) will take more than a few days, let me know please, then I will use the trick with ``int`` wrapped to struct + dictionary.

**Comment by matthiasrichter** [comment]
With the latest update, the PR implements now the support for vectors of messageable types with and without ROOT dictionary. The latter need to be non serialized at the input. We can extend later to support both non and ROOT serialized messages as input for these types.

Storage in a ROOT tree always involves a copy. While ROOT serialized objects are deserialized and the object pointer is used for writing data to branch, the data of the non serialized messages needs to be copied to a storage object for writing. Maybe this can be avoided, but this is a task for later investigation.

**Comment by shahor02** [comment]
Hi @matthiasrichter 

Looks like this PR screws up the POD subbranches, the updated o2-test-dplutils-RootTreeWriter produces ``_0.XX`` branches:
````
testtree->Print()
******************************************************************************
*Tree    :testtree  : testtree                                               *
*Entries :        1 : Total =           11401 bytes  File Size =       3446 *
*        :          : Tree compression factor = 1.00                       *
******************************************************************************
*Br    0 :intbranch : intbranch/I                                            *
*Entries :        1 : Total  Size=        585 bytes  File Size  =         84 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................*
*Br    1 :containerbranch_0 : Int_t containerbranch_0_                       *
*Entries :        1 : Total  Size=       2482 bytes  File Size  =        104 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................*
*Br    2 :containerbranch_0.mMember : Int_t mMember[containerbranch_0_]      *
*Entries :        1 : Total  Size=        781 bytes  File Size  =        112 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................*
*Br    3 :containerbranch_0.mSecret : UInt_t mSecret[containerbranch_0_]     *
*Entries :        1 : Total  Size=        781 bytes  File Size  =        112 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................*
*Br    4 :containerbranch_1 : Int_t containerbranch_1_                       *
*Entries :        1 : Total  Size=       2482 bytes  File Size  =        104 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................*
...
*Branch :trivvecbranch *
*Entries :        1 : BranchElement (see below)                              *
*............................................................................*
*Br   10 :_0        : Int_t _0_                                              *
*Entries :        1 : Total  Size=       2916 bytes  File Size  =         89 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................*
*Br   11 :_0.mX     : UInt_t mX[_0_]                                         *
*Entries :        1 : Total  Size=        655 bytes  File Size  =         96 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................*
*Br   12 :_0.mY     : UInt_t mY[_0_]                                         *
*Entries :        1 : Total  Size=        655 bytes  File Size  =         96 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................*
*Br   13 :_0.mSecret : UInt_t mSecret[_0_]                                   *
*Entries :        1 : Total  Size=        680 bytes  File Size  =        101 *
*Baskets :        1 : Basket Size=      32000 bytes Compression=   1.00     *
*............................................................................* 
````

**Comment by matthiasrichter** [comment]
@shahor02, yes, unfortunately I have been using the wrong pointer for the branch data. ROOT IO seems to be very flexible because it was handling this. Although not silently, I should have noticed the error message but it was hidden in the lengthy log.

Please try with the fix in PR #2687. For the TPC reco workflow I have verified it.

**Comment by wiechula** [comment]
I can confirm that this is fixed. Thanks!

**Pull request merged**
