### PR TITLE
Fix: use 50 / 100 um for IB / OB chip thicknesses

### PR DESCRIPTION
**Pull request by shahor02**
@iouribelikov @mario6829 please check, if ok I will close https://github.com/AliceO2Group/AliceO2/pull/2222

### CODE REVIEW

**Comment by mario6829** [comment]
@shahor02 for me it's ok, maybe you can also update Detector.cxx line 83 to have the correct OB chip thickness (although actually unused - but just to be coherent). Then for me you can close my PR. Thanks Cheers

**Comment by iouribelikov** [comment]
@shahor02 Thank you very much, Ruben.  It is now much better.
But now if type:
gGeoManager->GetVolume("ITSUSensor0")->InspectShape()  and
gGeoManager->GetVolume("ITSUChip0")->InspectShape(),
in both cases I get dY=0.0025 ...
@mario6829 But a sensor should thinner than a chip ?

**Comment by mario6829** [comment]
@iouribelikov yes definitely the sensor is thinner than the chip

**Comment by shahor02** [comment]
OK, then it was wrong also in the old code, fixed 30um was set as epitaxial layer. Now should be fine.

**Comment by iouribelikov** [comment]
@shahor02 @mario6829 Sorry. But now, the tracking efficiency went down to 0...
(At the same time, the sensor and chip thicknesses do look OK now)

**Comment by shahor02** [comment]
Something is wrong with digitization, too few electrons are obtained from the alpideResponse, although the energy loss is similar. Will check later.

**Comment by shahor02** [comment]
@iouribelikov now should be ok, in fact, there should be (and there were) 2 sensor thicknesses: one physical (30 \um) where the charge collection is simulated, and effective one (22 \um) accounting for the non-uniformity of charge collection eff. vs depth in the sensor (used to assign the hit point along local Y)

**Comment by iouribelikov** [comment]
@shahor02  Yes.  All tests pass.  Thank you very much, Ruben.   I think we can merge it now.

**Pull request merged**
