### PR TITLE
Clarify/improve GeometryManager::loadGeometry documentation

### PR DESCRIPTION
**Pull request by sawenzel**
we need to pass a sim prefix ... not a filename.

### CODE REVIEW

**Comment by shahor02** [comment]
For the record: the general rule is: if passed 1st parameter <prefix> is
1) existing directory name: return <prefix>/<default_name>
2) existing filename: return it as is.
3) compose the full filename using <prefix> as prefix.

**Comment by chiarazampolli** [comment]
Hi @shahor02 , @sawenzel , 

We had hard-coded the o2sim_geometry-aligned.root file, I had understood that this is created also in simulation, so it should have worked. In data, we have it in the input files. Unless the anchoring script is not downloading it but uses the old one, o2sim_geometry.root... 

Chiara

**Comment by sawenzel** [comment]
@shahor02 : Then there is a problem in the logic because QC gave a concrete filename path `o2sim_geometry-aligned.root` which didn't work.

**Comment by shahor02** [comment]
For me it works:
```
root [0] const auto& nc = o2::base::NameConf::Instance();
nc.printKeyValues();root [1] nc.printKeyValues();
...
NameConf.mDirGeom : none		[ CODE ]
...
root [2] .!ls -l o2sim_geometry-aligned.root
-rw-r--r-- 1 shahoian shahoian 6376029 mai   31 13:42 o2sim_geometry-aligned.root
root [3] o2::base::GeometryManager::loadGeometry("o2sim_geometry-aligned.root");
[INFO] Loading geometry from o2sim_geometry-aligned.root
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
...
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
root [4] o2::base::GeometryManager::loadGeometry("")
[INFO] Loading geometry from o2sim_geometry-aligned.root
Warning in <TGeoManager::Init>: Deleting previous geometry: ccdb_object/FAIR geometry
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
...
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
root [5] o2::conf::ConfigurableParam::setValue("NameConf.mDirGeom","/home/shahoian/tmp/fst1");
root [6] o2::base::GeometryManager::loadGeometry();
[INFO] Loading geometry from /home/shahoian/tmp/fst1/o2sim_geometry-aligned.root
Warning in <TGeoManager::Init>: Deleting previous geometry: ccdb_object/FAIR geometry
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
...
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
root [7] o2::base::GeometryManager::loadGeometry("o2sim_geometry-aligned.root");
[INFO] Loading geometry from o2sim_geometry-aligned.root
Warning in <TGeoManager::Init>: Deleting previous geometry: ccdb_object/FAIR geometry
Info in <TGeoManager::CloseGeometry>: Geometry loaded from file...
...
Info in <TGeoManager::CloseGeometry>: ----------------modeler ready----------------
```

**Comment by sawenzel** [comment]
It doesn't work when you give a path which does not exist ... then it tries to make another file. But it's a different story. I am closing this.

**Comment by shahor02** [comment]
Yes, then it tries to interpret it as a prefix in the path built as
https://github.com/AliceO2Group/AliceO2/blob/0078222a8a7c35b46cac23d711772c0a9390d6c3/Common/Utils/src/NameConf.cxx#L36

**Pull request closed without merging**
