### PR TITLE
[O2-1334] [MCH] Fix digitizer crash due to volpath change

### PR DESCRIPTION
**Pull request by aphecetche**
And add a test to catch this kind of error

### CODE REVIEW

**Comment by flodamas** [comment]
Indeed I forgot the '_1' for the node ... sorry. Thanks a lot for the test !

**Comment by sawenzel** [comment]
There is a failing unit test: testDigitMerging.cxx

**Comment by aphecetche** [comment]
I'm on it...

**Comment by aphecetche** [comment]
@mwinn2 while I was attempting to add a test for the geometryTransformer, I've noticed that in fact the tests in MCH/Simulation/test were not running at all (due to the fact that `o2_add_test` used in the CMakeListst.txt was using the CONFIGURATIONS option which seems broken), and so it was not noticed that some of them fails (even before this PR). 

To get this PR through, I've now disabled (using `BOOST_TEST_DECORATOR(*boost::unit_test::disabled())`)  those tests that are failing : 

- testDigitization.cxx-BOOST_AUTO_TEST_CASE(DigitizerTest)
- testDigitization.cxx-BOOST_AUTO_TEST_CASE(mergingDigitizer)
- testResponse.cxx-BOOST_AUTO_TEST_CASE(Response_test)

I suspect it's just a matter of choice of reference entry/exit points that might now be wrong because of some geometry changes since the initial development of those tests, but could you please check that ? Thanks.

**Pull request merged**
