### PR TITLE
[WIP] Testing codeowners

### PR DESCRIPTION
**Pull request by sawenzel**
Just a test PR in order to verify that the codeowners mechanism works or not.

### CODE REVIEW

**Comment by sawenzel** [comment]
I would have expected that @wiechula shows up on the approver list. This does not seem to be the case, probably because codeowners need to have write rights for the main repository.

This could be a limiting factor. @ihrivnac @ktf

**Comment by ihrivnac** [comment]
Indeed. This is stated at the same beginning at:
https://help.github.com/en/articles/about-code-owners
"The people you choose as code owners must have write permissions for the repository."

**Comment by ktf** [comment]
Mmm.. I think it's something else. I do not think ruben has write permissions.

**Comment by sawenzel** [comment]
Ruben has write permissions. He merges PRs regularly.

**Comment by ktf** [comment]
We probably need to use "Require review" in conjunction with protected branches, and the allow a certain group of people to "dismiss reviews" and merge directly.

**Comment by ihrivnac** [comment]
@ktf,
Will you update the repository setting as you suggest above so that we can test if it solves the problem?

**Pull request closed without merging**
