### PR TITLE
Fix for failing dataflow build

### PR DESCRIPTION
**Pull request by jackal1-66**
Hybrid generator includes Pythia8, so when the dataflow build happens, without this fix, the Pythia8 header is loaded. It's not found due to the nature of the dataflow build. This fix prevents the Hybrid generator loading if Pythia8 is not found and it includes also HepMC3, given that a similar issue might arise with that generator as well in the future.

### CODE REVIEW

**Review by sawenzel — DISMISSED** [review]

**Comment by ktf** [comment]
Did you test it locally? If yes, I will go ahead and merge it since this is currently broken.

**Comment by jackal1-66** [comment]
Let's wait for the CI results, I rebuilt O2sim with my slc9 system and it works, but I can't test the dataflow build on cs8.

**Comment by jackal1-66** [comment]
build/O2/o2_slc9 failure is related to o2sim_checksimkinematics_G3, so unrelated to the purpose of this PR

**Comment by jackal1-66** [comment]
I managed to reproduce the error locally and I ultimately fixed the issue. If there are no other differences between my slc9 build and the cs8 one, then I expect the next dataflow test to be successful

**Pull request merged**
