### PR TITLE
Rdev compressor rdh protect

### PR DESCRIPTION
**Pull request by preghenella**

### CODE REVIEW

**Comment by preghenella** [comment]
@noferini this is a draft PR until I test the new features

**Comment by preghenella** [comment]
ciao @noferini 
the paranoid feauture is not fully working yet
but I would bring this PR forward, if you find it ok

**Review by noferini — APPROVED** [review]

**Comment by preghenella** [comment]
looks to me that the failure in the `build/O2/fullCI` test is unrelated.

**Comment by shahor02** [comment]
failure unrelated (ccdb was down), merging

**Pull request merged**
