### PR TITLE
Dev tpc eloss

### PR DESCRIPTION
**Pull request by wiechula**
* Add missing gas parameters
* Unrelated: change a parameter name for clarity

### CODE REVIEW

**Comment by sawenzel** [comment]
@wiechula @pchristi : Thanks a lot. A quick checks shows that the situation is indeed much improved. Looking at the sizes of the hit output for 10 box events (`tpc-run-sim -n 10`, I see the following [before -> after]

G3: 6.3MB -> 2.5MB
G4: 1.6MB -> 1.5MB

This is good, but there still seems to be a significant difference between G3/G4 hit production. 
It means that G3 is still producing more hits at a finer step level than G4.

Does this conform to your expectations?

**Comment by wiechula** [comment]
I think we should look into this and compare with what we have in AliRoot, since in AliRoot the energy loss was identical. This should also be checked in o2. Perhaps we have overlooked something somewhere. I'm not sure how the `Detector::SetSpecialPhysicsCuts()` affects this and how physics setting are done for Geant4 in AliRoot (if at all). I guess this also needs a wider discussion how to deal with this in O2. In AliRoot (at least for Geant3) there is a common file for the setting `data/galice.cuts`

**Comment by pchristi** [comment]
Hi,

I think it should be investigated but it is not so easy to say at the data level.
What should now be the case is that for each track the response is the same, e.g., same cluster charge, track dE/dx, same resolution. If that is not the case there is an issue.
If someone has a simple test beam like setup that should be easy to check.

What could also happen is that G3 generates more secondary particles and therefore the total data is more. As Jens mentioned, it is not even clear that the two simulations are configured the same way and so there could be a trivial reason for this difference.
This might be more tricky to understand.

Cheers,
   Peter

**Comment by sawenzel** [comment]
@wiechula , @pchristi : Fine. Let's merge it for now. And I agree that we need a central way to manage the cuts/processes. I can now also try to make a detailed comparison of O2/AliRoot with the Monte Carlo step logger.

**Pull request merged**
