### PR TITLE
reworking include directories

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@aphecetche Is it correct in this way?

**Comment by aphecetche** [comment]
@jgrosseo yes seems to compile fine as far as I can tell (tried on my machine, as it seems the CI machines are still a bit shaky at the moment).
Concerning the question about subfolders, when I see : 

```
AnalysisDataModel
├── CFDerived.h
├── Centrality.h
├── EventSelection.h
├── HFCandidateSelectionTables.h
├── HFSecondaryVertex.h
├── Jet.h
├── Multiplicity.h
├── PID
│   ├── BetheBloch.h
│   ├── DetectorResponse.h
│   ├── PIDResponse.h
│   ├── PIDTOF.h
│   ├── PIDTPC.h
│   ├── ParamBase.h
│   ├── TOFReso.h
│   └── TPCReso.h
```

I wonder why the PID part is not a library by itself. There might be some good reasons (must confess I've not looked much at the code itself), but that's my first reaction when looking at the include structure, is all I can say ;-)

**Comment by iarsene** [comment]
Hi @aphecetche and @jgrosseo ,
I think indeed that the PID part within the AnalysisDataModel could benefit from a bit of reorganization. And i think this should have its own library. However, my understanding is that the current implementation we have is not the "final" one, but more of a quick and dirty fix such that we can work and do our O2 tests for now. What we will have might as well be constructed on top of this, but i am not very sure of that. It could also be something done from scratch. Anyway, i think this should at some point be discussed involving more experts (especially TPC, i.e. Jens Wiechula) who did the PidResponse in AliPhysics. So i think PID can stay for now in AnalysisDataModel.
Cheers, Ionut

**Comment by jgrosseo** [comment]
checkcode unrelated (none of them in analysis folder), macOS unrelated. Merging

**Comment by jgrosseo** [comment]
@iarsene @aphecetche Just to note that for the PID I agree. We will take care of it.

**Pull request merged**
