### PR TITLE
Drop --old option for real

### PR DESCRIPTION
**Pull request by ktf**
Drop --old option for real

### CODE REVIEW

**Comment by ktf** [comment]
@noferini shall we do this now?

**Comment by noferini** [comment]
Hi @ktf , let's wait a bit to merge.
I'm going to open a PR in ControlWorkflow which is mandatory before to merge this.

**Comment by noferini** [comment]
here the PR I opened
https://github.com/AliceO2Group/ControlWorkflows/pull/634

**Comment by noferini** [comment]
here the PR I opened
https://github.com/AliceO2Group/ControlWorkflows/pull/634

**Comment by ktf** [comment]
@noferini I see your PR is now merged. Can we merge this one?

**Comment by noferini** [comment]
Sure

**Pull request merged**
