### PR TITLE
Apply git clang-format to Analysis.

### PR DESCRIPTION
**Pull request by vkucera**

### CODE REVIEW

**Review by jgrosseo — DISMISSED** [review]
This is OK but do we usually apply clang to the linkdef files?

**Comment by vkucera** [comment]
> This is OK but do we usually apply clang to the linkdef files?

I am relying on the configuration in the repository to know better which files should be checked.
I just ran `git clang-format` against the first O2 commit.

**Comment by vkucera** [comment]
But in general, is there a reason to not check them?

**Comment by vkucera** [comment]
- Reformatted with clang-format 11.
- Reverted changes conflicting with the GitHub check. (It doesn't apply the same rules for some reason.)

**Comment by vkucera** [comment]
Bump

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
