### PR TITLE
TPCClusterFinder: Propagate MC labels

### PR DESCRIPTION
**Pull request by fweig**
@davidrohr  This PR adds support for MC labels to the cluster finder.

Brief overview of whats happening here:
1. Collect mc labels while creating clusters.
2. Calculate offset for each cluster inside the label container inside each row.
3. With values from step 2 calculate the offsets across the entire sector.
4. Copy labels into continuous memory and wrap it in a `MCTruthContainer`.

Overhead on the cluster finder runtime is around 30% and most of that seems to come from the random reads while collecting labels.

### CODE REVIEW

**Comment by davidrohr** [comment]
@fweig : Thx, this looks really good, but I could only have a quick look. I'll need some time to really test it, since I am busy here with other AMD stuff. If you are idle, you can in the meantime clean up the other open PR :)
I thought it would be sufficient to just do this on the CPU, but now you already do it on the GPU, which is even better. For the MCTruthArray, before I thought we might pull in one internally, but if I understand correctly, this cannot work, since you are creating the labels on the GPU, so we need to adapt a buffer in any case. But I think this is totally fine.

Few remarks:
- Could you try to compile and run standalone with `set(CONFIG_O2 0)` in the config.cmake. If it doesn't find classes then, there is `GPUO2FakeClasses.h` to set up dummies.
- Could you add a setting `runMC` to `GPUSettingsDeviceProcessing`, (for the standalone benchmark you have to add a corresponding entry to `qconfigoptions.h` and forward the setting in the same way as the others in `standalone.cxx`, which steers whether MC labels are processes in general or not. If not, you should also disable the memory allocation in GPUTPCClusterFinder.cxx.
- In that case, if runMC is set to false, memory size and processing speed should be exactly as before this PR. 30% overhead for MC label processing seems reasonable. We just need to make sure it doesn't affect the processing without MC labels. In particular the memory will be critical in this case.

**Comment by fweig** [comment]
@davidrohr It compiles with `CONFIG_O2=0`.

I added the flag `runMC` flag and made sure to not allocate any memory, when it's not set.
The `o2-tpc-reco-workflow` already has a flag `--disable-mc`. I guess, these two should be unified?

There should be no overhead on GPU as the MC specific code is removed by macros. Overhead on host are just the checks for `nullptr`s if no labels were set.

**Comment by davidrohr** [comment]
> There should be no overhead on GPU as the MC specific code is removed by macros.

@fweig : thx, that sounds very good. Will test this asap and merge it. Jut one question: What do you mean by MC specific code is removed by macros? There is no compile-time setting to enable/disable mc label propagation?

**Comment by davidrohr** [comment]
@fweig : There are some clang-format violations, and I get these warnings:
```
/alicedata/drohr/tmp/AliceO2/GPU/GPUTracking/Standalone/TPCClusterFinder/GPUTPCCFClusterizer.cxx:92:8: warning: unused variable 'rowIndex' [-Wunused-variable]
  uint rowIndex = sortIntoBuckets(
       ^
/alicedata/drohr/tmp/AliceO2/GPU/GPUTracking/Standalone/TPCClusterFinder/GPUTPCCFClusterizer.cxx:196:12: warning: unused variable 'q' [-Wunused-variable]
    Charge q = cluster->updateOuter(p, d);
        
```

**Comment by fweig** [comment]
The mc labels code doesn't actually run on GPU (because it depends on `std::vector`). I just used the gpu framework for host code for convenient fan-out.  Theres the `CPU_ONLY` macro to remove mc label specific statements on GPU at compile time. The cpu code just checks at runtime if the label input / output pointers are set, to decide if labels should be collected.  


> @fweig : There are some clang-format violations, and I get these warnings:
> 
> ```
> /alicedata/drohr/tmp/AliceO2/GPU/GPUTracking/Standalone/TPCClusterFinder/GPUTPCCFClusterizer.cxx:92:8: warning: unused variable 'rowIndex' [-Wunused-variable]
>   uint rowIndex = sortIntoBuckets(
>        ^
> /alicedata/drohr/tmp/AliceO2/GPU/GPUTracking/Standalone/TPCClusterFinder/GPUTPCCFClusterizer.cxx:196:12: warning: unused variable 'q' [-Wunused-variable]
>     Charge q = cluster->updateOuter(p, d);
>         
> ```
Fixed.

**Comment by davidrohr** [comment]
Please don't merge, I have included this and #3039 into #3060 , and fixed all merge conflicts there.

**Pull request closed without merging**
