### PR TITLE
ITS-vertexer: Make cut on XY a configurable param

### PR DESCRIPTION
**Pull request by mconcas**
- Make XY cut beam-vertex distance cut
- Add tracklet resolution cut 100um

### CODE REVIEW

**Comment by mconcas** [comment]
@shahor02 this replaces #11048. From CLI I opened a PR using a branch on AliceO2Group/AliceO2 rather than mconcas/AliceO2 and then I was not able to push further changes.
Sorry for the mess.

I ran on the CTF: `o2_ctf_run00523308_orbit0319097116_tf0000000026_epn224.root`

Here the ntracks distribution when we run on pp with default cuts.
- vertNsigmaCut = 4
- vertRadiusSigma = 500 um
- trackletSigma = 100 um

Screenshot 2023-04-11 at 12 25 03

Seeding XY dist is contained into a 0.5 mm diameter circle around the beam:
Screenshot 2023-04-11 at 12 29 56

**Review by shahor02 — APPROVED** [review]

**Comment by davidrohr** [comment]
@mconcas @shahor02 : What is the status of the custom settings? Do I still need to apply some custom configKeyValues in the async reco, or is it meanwhile the default / or added to the async setenv_extra.sh?

**Comment by mconcas** [comment]
> @mconcas @shahor02 : What is the status of the custom settings? Do I still need to apply some custom configKeyValues in the async reco, or is it meanwhile the default / or added to the async setenv_extra.sh?

Defaults are now changed so as to produce the presented results.
No additional parameters need to be passed unless we found these new defaults are not good.

**Comment by davidrohr** [comment]
ok, perfect, thx, then I'll retry once more the async reco benchmark just to be sure.

**Comment by chiarazampolli** [comment]
Hello @mconcas , 
Just to be sure: do we need to change anything in https://github.com/AliceO2Group/O2DPG/blob/master/DATA/production/configurations/asyncReco/setenv_extra.sh ? Which settings should one check, in case, to be sure?
Chiara

**Comment by mconcas** [comment]
> Hello @mconcas , Just to be sure: do we need to change anything in https://github.com/AliceO2Group/O2DPG/blob/master/DATA/production/configurations/asyncReco/setenv_extra.sh ? Which settings should one check, in case, to be sure? Chiara

Hi, nothing should be changed there for the time being.
I changed the default behaviour, so the modification should come with no further additions to the params.

**Pull request merged**
