### PR TITLE
Protection against out of bound access in CTF dictionaries

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by davidrohr** [comment]
Thx, with this fix the TPC encoding has become stable. Looks good, and CPU consumption is down as well.

**Comment by shahor02** [comment]
hm, it should not have affected CPU consumption. Do you mean wrt not using external dictionaries?
Anyway, will merge one 1 test passed, @MichaelLettrich may convert it later to something more intelligent.

**Comment by davidrohr** [comment]
Yes, CPU consumption is down wrt. no external dictionaries at all. This PR doesn't change CPU consumption, it just fixed the crash.

**Comment by MichaelLettrich** [comment]
#4125 should not only fix this issue but also improve performance and memory consumption quite nicely.

**Pull request closed without merging**
