### PR TITLE
DPL: support multiplexing of dangling outputs

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ironMann `o2-dpl-raw-proxy --dangling-outputs-policy fairmq` seems well behaved with this. I am also changing the name of the channel to "downstream", since that's what you called it in the JIRA ticket. I think it makes sense.

@matthiasrichter I am changing the behaviour to have single channel for all the outputs. If needed, the old behaviour can be provided again by improving the `decideChannel` method with some policy.

**Comment by ironMann** [comment]
Thanks. 
For my understanding: the `o2-dpl-raw-proxy` will now a spawn a channel ( called "downstream") where (S)TFs are exiting DPL?
The output proxy component is now deprecated?

**Comment by ktf** [comment]
Not a channel (yet) but a separate device. Yes, the o2-dpl-output-proxy should be effectively unneeded. Basically once this PR (and the associated one for the input proxy) will be merged, all you will need is the data processing workflow itself.

**Comment by ktf** [comment]
I mean: a separate device with a "downstream" channel.

**Comment by ktf** [comment]
Already tested on macOS. @MichaelLettrich are the macs working fine?

**Comment by ironMann** [comment]
@kft, Still I cannot specify endpoints for input and output channels. See bellow. It seems that the channel specified second is always reported as an error.

```
 o2-dpl-raw-proxy --session default -b --dangling-outputs-policy fairmq --channel-config name=readout-proxy,type=pull,method=connect,address=ipc:///tmp/stfb-to-dpl,transport=shmem,rateLogging=1 name=downstream,type=push,method=bind,address=ipc:///tmp/dpl-to-stfs,rateLogging=1,transport=shmem
...
[299132:internal-dpl-output-proxy]: [16:51:33][ERROR] Unhandled exception reached the top of main: no corresponding output channel found for input 'downstream', device shutting down.
[299132:internal-dpl-output-proxy]: [16:51:33][INFO] Process 299132 is exiting.
[INFO] QUIT_REQUESTED
```

**Comment by ktf** [comment]
I will check. Can you verify that with the default path it works? I think you can force the folder with $TMPDIR.

**Comment by ktf** [comment]
The actual syntax is:

```
stage/bin/o2-dpl-raw-proxy --session default --dangling-outputs-policy fairmq --readout-proxy '--channel-config name=readout-proxy,type=pull,method=connect,address=ipc:///tmp/stfb-to-dpl,transport=shmem,rateLogging=1' --internal-dpl-output-proxy '--channel-config name=downstream,type=push,method=bind,address=ipc:///tmp/dpl-to-stfs,rateLogging=1,transport=shmem'
```

I.e. you need to specify via `--internal-dpl-output-proxy '...'` the options that pertain only to that device.

**Comment by ironMann** [comment]
@ktf Thanks! this works.  lets continue at [O2-588](https://alice.its.cern.ch/jira/browse/O2-588)

**Pull request merged**
