### PR TITLE
DPL: introduce Lifetime::Dangling

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Actual usage to prune unneeded messages to the dummy sink coming.

**Comment by davidrohr** [comment]
That could be a genuine error: `64/98 Test  #78: test_Framework_test_WorkflowHelpers ...................***Failed    0.10 sec`

**Comment by davidrohr** [comment]
Just had a quick test of this locally. What I see in the FST is that all processers now send something to the internal-dpl-injected-dummy-sink. So the logic to identify the sinks seems wrong.
Also, many processors die with
```
[28276:ft0-reconstructor]: [11:45:53][ERROR] requested channel has not been configured? check channel names/configuration.
[28276:ft0-reconstructor]: [11:45:53][ERROR] channel: from_ft0-entropy-encoder_to_ft0-reconstructor, index: 0
[28276:ft0-reconstructor]: [11:45:53][ERROR] out of range: _Map_base::at
[28276:ft0-reconstructor]: [11:45:53][ERROR] out of range: _Map_base::at
[28276:ft0-reconstructor]: [11:45:53][ERROR] incorrect/incomplete channel configuration?
[28276:ft0-reconstructor]: [11:45:53][ERROR] error while setting up workflow in o2-ft0-reco-workflow: _Map_base::at
```

**Comment by ktf** [comment]
I realised I actually need also the rest of the feature and that I cannot do things incrementally. I am on it.

**Comment by ktf** [comment]
Ok, I fixed the test and I think also the logic change wrt what was done before. Now verifying something more complex.

**Comment by ktf** [comment]
For the record, the automatic refactoring bot seems to work nicely.

**Comment by ktf** [comment]
Works on hyperloop.

**Comment by davidrohr** [comment]
Doesn't look that good in the full system test with QC. Still some processors are crashing at startup, and the dummy sink still receives a message from basically every processor.
dplgui

**Comment by ktf** [comment]
Ok, i understand the problem. We want to mark things as dangling only at the end of the workflow merging, not on a per workflow basis... I am thinking how to address that...

**Review by davidrohr — DISMISSED** [review]
seems ok in the full system test.

**Pull request closed without merging**
