### PR TITLE
Fixing CCDB filling for DCS processors

### PR DESCRIPTION
**Pull request by chiarazampolli**
This should fix the issue seen by @aphecetche , in https://github.com/AliceO2Group/AliceO2/pull/4863 - at least for the existing workflow.

### CODE REVIEW

**Comment by aphecetche** [comment]
@chiarazampolli tried this one (fresh install) and get a different issue (see below).
Does it work for you ?  

```
[ pr ]~/alice/pr$ o2-dcs-dcs-data-workflow --max-timeframes=10 | o2-calibration-ccdb-populator-workflow --ccdb-path http://localhost:6464
[INFO] Initialising O2 Data Processing Layer
[INFO] O2 Data Processing Layer initialised. We brake for nobody.
[INFO] Optimised build. O2DEBUG / LOG(DEBUG) / LOGF(DEBUG) / assert statement will not be shown.
[INFO] Redeployment of configuration asked.
[INFO] Starting internal-dpl-clock on pid 23078
[INFO] Starting dcs-data-generator on pid 23079
[INFO] Starting dcs-data-processor on pid 23080
[INFO] Starting ccdb-populator on pid 23081
[INFO] Redeployment of configuration done.
[23078:internal-dpl-clock]: [INFO] Spawing new device internal-dpl-clock in process with pid 23078
[23079:dcs-data-generator]: [INFO] Spawing new device dcs-data-generator in process with pid 23079
[23080:dcs-data-processor]: [INFO] Spawing new device dcs-data-processor in process with pid 23080
[23078:internal-dpl-clock]: [11:20:56][INFO]
[23078:internal-dpl-clock]:       ______      _    _______  _________
[23078:internal-dpl-clock]:      / ____/___ _(_)_______   |/  /_  __ \    version 1.4.25
[23078:internal-dpl-clock]:     / /_  / __ `/ / ___/__  /|_/ /_  / / /    build RELWITHDEBINFO
[23078:internal-dpl-clock]:    / __/ / /_/ / / /    _  /  / / / /_/ /     https://github.com/FairRootGroup/FairMQ
[23078:internal-dpl-clock]:   /_/    \__,_/_/_/     /_/  /_/  \___\_\     LGPL-3.0  © 2012-2020 GSI
[23078:internal-dpl-clock]:
[23078:internal-dpl-clock]: [11:20:56][ERROR] getDevice(): no valid device provided. Exiting.
[23078:internal-dpl-clock]: [11:20:56][INFO] Process 23078 is exiting.
[23079:dcs-data-generator]: [ERROR] Unhandled std::exception reached the top of main: unordered_map::at: key not found, device shutting down.
[23079:dcs-data-generator]: [INFO] Process 23079 is exiting.
[23080:dcs-data-processor]: [11:20:56][INFO]
[23080:dcs-data-processor]:       ______      _    _______  _________
[23080:dcs-data-processor]:      / ____/___ _(_)_______   |/  /_  __ \    version 1.4.25
[23080:dcs-data-processor]:     / /_  / __ `/ / ___/__  /|_/ /_  / / /    build RELWITHDEBINFO
[23080:dcs-data-processor]:    / __/ / /_/ / / /    _  /  / / / /_/ /     https://github.com/FairRootGroup/FairMQ
[23080:dcs-data-processor]:   /_/    \__,_/_/_/     /_/  /_/  \___\_\     LGPL-3.0  © 2012-2020 GSI
[23080:dcs-data-processor]:
[23080:dcs-data-processor]: [11:20:56][ERROR] getDevice(): no valid device provided. Exiting.
[23080:dcs-data-processor]: [11:20:56][INFO] Process 23080 is exiting.
[23081:ccdb-populator]: [INFO] Spawing new device ccdb-populator in process with pid 23081
[23081:ccdb-populator]: [11:20:56][INFO]
[23081:ccdb-populator]:       ______      _    _______  _________
[23081:ccdb-populator]:      / ____/___ _(_)_______   |/  /_  __ \    version 1.4.25
[23081:ccdb-populator]:     / /_  / __ `/ / ___/__  /|_/ /_  / / /    build RELWITHDEBINFO
[23081:ccdb-populator]:    / __/ / /_/ / / /    _  /  / / / /_/ /     https://github.com/FairRootGroup/FairMQ
[23081:ccdb-populator]:   /_/    \__,_/_/_/     /_/  /_/  \___\_\     LGPL-3.0  © 2012-2020 GSI
[23081:ccdb-populator]:
[23081:ccdb-populator]: [11:20:56][ERROR] getDevice(): no valid device provided. Exiting.
[23081:ccdb-populator]: [11:20:56][INFO] Process 23081 is exiting.
```

**Comment by aphecetche** [comment]
@chiarazampolli well, actually the issue is probably not related to this PR at all, my build also fails a few framework tests with the same error, e.g.

```
ctest -R SimpleTimer --output-on-failure
```

**Comment by chiarazampolli** [comment]
Ciao Laurent,

For me it works, see below. My last rebase to dev was on 16.11. 

Cheers,

Chiara

```
[O2/latest] ~/SOFT/alibuild/ali-o2/sw/BUILD/O2-latest/O2 $> o2-dcs-dcs-data-workflow --max-timeframes=10 -b | o2-calibration-ccdb-populator-workflow --ccdb-path http://localhost:8080 -b
[INFO] Initialising O2 Data Processing Layer
[INFO] O2 Data Processing Layer initialised. We brake for nobody.
[INFO] Optimised build. O2DEBUG / LOG(DEBUG) / LOGF(DEBUG) / assert statement will not be shown.
[INFO] Redeployment of configuration asked.
[INFO] Starting internal-dpl-clock on pid 27592
[INFO] Starting dcs-data-generator on pid 27593
[INFO] Starting dcs-data-processor on pid 27594
[INFO] Starting ccdb-populator on pid 27595
[INFO] Redeployment of configuration done.
[27594:dcs-data-processor]: [INFO] Spawing new device dcs-data-processor in process with pid 27594
[27594:dcs-data-processor]: [12:06:52][INFO] 
[27594:dcs-data-processor]:       ______      _    _______  _________ 
[27594:dcs-data-processor]:      / ____/___ _(_)_______   |/  /_  __ \    version 1.4.25
[27594:dcs-data-processor]:     / /_  / __ `/ / ___/__  /|_/ /_  / / /    build RELWITHDEBINFO
[27594:dcs-data-processor]:    / __/ / /_/ / / /    _  /  / / / /_/ /     https://github.com/FairRootGroup/FairMQ
[27594:dcs-data-processor]:   /_/    \__,_/_/_/     /_/  /_/  \___\_\     LGPL-3.0  © 2012-2020 GSI
[27594:dcs-data-processor]: 
[27594:dcs-data-processor]: [12:06:52][STATE] Starting FairMQ state machine --> IDLE
[27594:dcs-data-processor]: 2020-11-19 12:06:52	StdOut backend initialized
[27594:dcs-data-processor]: [12:06:52][STATE] IDLE ---> INITIALIZING DEVICE
[27593:dcs-data-generator]: [INFO] Spawing new device dcs-data-generator in process with pid 27593
[27595:ccdb-populator]: [INFO] Spawing new device ccdb-populator in process with pid 27595
[27595:ccdb-populator]: [12:06:52][INFO] 
[27595:ccdb-populator]:       ______      _    _______  _________ 
[27595:ccdb-populator]:      / ____/___ _(_)_______   |/  /_  __ \    version 1.4.25
[27595:ccdb-populator]:     / /_  / __ `/ / ___/__  /|_/ /_  / / /    build RELWITHDEBINFO
[27595:ccdb-populator]:    / __/ / /_/ / / /    _  /  / / / /_/ /     https://github.com/FairRootGroup/FairMQ
[27595:ccdb-populator]:   /_/    \__,_/_/_/     /_/  /_/  \___\_\     LGPL-3.0  © 2012-2020 GSI
[27595:ccdb-populator]: 
[27595:ccdb-populator]: [12:06:52][STATE] Starting FairMQ state machine --> IDLE
[27595:ccdb-populator]: 2020-11-19 12:06:52	StdOut backend initialized
[27593:dcs-data-generator]: [12:06:52][INFO] 
[27593:dcs-data-generator]:       ______      _    _______  _________ 
[27593:dcs-data-generator]:      / ____/___ _(_)_______   |/  /_  __ \    version 1.4.25
[27593:dcs-data-generator]:     / /_  / __ `/ / ___/__  /|_/ /_  / / /    build RELWITHDEBINFO
[27593:dcs-data-generator]:    / __/ / /_/ / / /    _  /  / / / /_/ /     https://github.com/FairRootGroup/FairMQ
[27593:dcs-data-generator]:   /_/    \__,_/_/_/     /_/  /_/  \___\_\     LGPL-3.0  © 2012-2020 GSI
[27593:dcs-data-generator]: 
[27593:dcs-data-generator]: [12:06:52][STATE] Starting FairMQ state machine --> IDLE
[27593:dcs-data-generator]: 2020-11-19 12:06:52	StdOut backend initialized
[27595:ccdb-populator]: [12:06:52][STATE] IDLE ---> INITIALIZING DEVICE
[27592:internal-dpl-clock]: [INFO] Spawing new device internal-dpl-clock in process with pid 27592
[27592:internal-dpl-clock]: [12:06:52][INFO] 
[27592:internal-dpl-clock]:       ______      _    _______  _________ 
[27592:internal-dpl-clock]:      / ____/___ _(_)_______   |/  /_  __ \    version 1.4.25
[27592:internal-dpl-clock]:     / /_  / __ `/ / ___/__  /|_/ /_  / / /    build RELWITHDEBINFO
[27592:internal-dpl-clock]:    / __/ / /_/ / / /    _  /  / / / /_/ /     https://github.com/FairRootGroup/FairMQ
[27592:internal-dpl-clock]:   /_/    \__,_/_/_/     /_/  /_/  \___\_\     LGPL-3.0  © 2012-2020 GSI
[27592:internal-dpl-clock]: 
[27592:internal-dpl-clock]: [12:06:52][STATE] Starting FairMQ state machine --> IDLE
[27592:internal-dpl-clock]: 2020-11-19 12:06:52	StdOut backend initialized
[27592:internal-dpl-clock]: [12:06:52][STATE] IDLE ---> INITIALIZING DEVICE
[27592:internal-dpl-clock]: 2020-11-19 12:06:52	Buffering enabled (100)
[27592:internal-dpl-clock]: [12:06:52][STATE] INITIALIZING DEVICE ---> INITIALIZED
[27592:internal-dpl-clock]: [12:06:52][STATE] INITIALIZED ---> BINDING
[27592:internal-dpl-clock]: [12:06:52][STATE] BINDING ---> BOUND
[27592:internal-dpl-clock]: [12:06:52][STATE] BOUND ---> CONNECTING
[27592:internal-dpl-clock]: [12:06:52][STATE] CONNECTING ---> DEVICE READY
[27592:internal-dpl-clock]: [12:06:52][STATE] DEVICE READY ---> INITIALIZING TASK
[27593:dcs-data-generator]: [12:06:52][STATE] IDLE ---> INITIALIZING DEVICE
[27593:dcs-data-generator]: 2020-11-19 12:06:52	Buffering enabled (100)
[27593:dcs-data-generator]: [12:06:52][INFO] mMaxTF = 10
[27592:internal-dpl-clock]: [12:06:52][STATE] INITIALIZING TASK ---> READY
[27592:internal-dpl-clock]: [12:06:52][STATE] READY ---> RUNNING
[27592:internal-dpl-clock]: [12:06:52][INFO] DEVICE: Running...
[27593:dcs-data-generator]: [12:06:52][INFO] Number of DCS data points: 50006 (full map); 100 (delta map)
[27593:dcs-data-generator]: [12:06:52][STATE] INITIALIZING DEVICE ---> INITIALIZED
[27593:dcs-data-generator]: [12:06:52][STATE] INITIALIZED ---> BINDING
[27593:dcs-data-generator]: [12:06:52][STATE] BINDING ---> BOUND
[27593:dcs-data-generator]: [12:06:52][STATE] BOUND ---> CONNECTING
[27593:dcs-data-generator]: [12:06:52][STATE] CONNECTING ---> DEVICE READY
[27593:dcs-data-generator]: [12:06:52][STATE] DEVICE READY ---> INITIALIZING TASK
[27593:dcs-data-generator]: [12:06:52][STATE] INITIALIZING TASK ---> READY
[27593:dcs-data-generator]: [12:06:52][STATE] READY ---> RUNNING
[27593:dcs-data-generator]: [12:06:52][INFO] DEVICE: Running...
[27595:ccdb-populator]: 2020-11-19 12:06:52	Buffering enabled (100)
[27595:ccdb-populator]: [12:06:52][STATE] INITIALIZING DEVICE ---> INITIALIZED
[27595:ccdb-populator]: [12:06:52][STATE] INITIALIZED ---> BINDING
[27595:ccdb-populator]: [12:06:52][STATE] BINDING ---> BOUND
[27595:ccdb-populator]: [12:06:52][STATE] BOUND ---> CONNECTING
[27595:ccdb-populator]: [12:06:52][STATE] CONNECTING ---> DEVICE READY
[27595:ccdb-populator]: [12:06:52][STATE] DEVICE READY ---> INITIALIZING TASK
[27595:ccdb-populator]: [12:06:52][STATE] INITIALIZING TASK ---> READY
[27595:ccdb-populator]: [12:06:52][STATE] READY ---> RUNNING
[27595:ccdb-populator]: [12:06:52][INFO] DEVICE: Running...
[27594:dcs-data-processor]: 2020-11-19 12:06:52	Buffering enabled (100)
[27594:dcs-data-processor]: [12:06:52][STATE] INITIALIZING DEVICE ---> INITIALIZED
[27594:dcs-data-processor]: [12:06:52][STATE] INITIALIZED ---> BINDING
[27594:dcs-data-processor]: [12:06:52][STATE] BINDING ---> BOUND
[27594:dcs-data-processor]: [12:06:52][STATE] BOUND ---> CONNECTING
[27594:dcs-data-processor]: [12:06:52][STATE] CONNECTING ---> DEVICE READY
[27594:dcs-data-processor]: [12:06:52][STATE] DEVICE READY ---> INITIALIZING TASK
[27594:dcs-data-processor]: [12:06:52][STATE] INITIALIZING TASK ---> READY
[27594:dcs-data-processor]: [12:06:52][STATE] READY ---> RUNNING
[27594:dcs-data-processor]: [12:06:52][INFO] DEVICE: Running...
[27594:dcs-data-processor]: [12:06:52][INFO] Number of DPs received = 50006
[27595:ccdb-populator]: [METRIC] data_relayToken >/tmp/tokencert_1001.pem< not found/created
[27595:ccdb-populator]: Token >/tmp/tokencert_1001.pem< not found/created
[27593:dcs-data-generator]: [12:06:52][INFO] Data generator reached TF 10, stopping
[27595:ccdb-populator]: Token >/tmp/tokencert_1001.pem< not found/created
[27594:dcs-data-processor]: [12:06:52][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784012880.root of size 138240 bytes, valid for 0 : 99999999999999
[27594:dcs-data-processor]: [12:06:52][INFO] Number of DPs received (delta map) = 100
[27594:dcs-data-processor]: [12:06:52][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784012948.root of size 138240 bytes, valid for 1 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013006.root of size 138240 bytes, valid for 2 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013062.root of size 138240 bytes, valid for 3 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013122.root of size 138240 bytes, valid for 4 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013178.root of size 138240 bytes, valid for 5 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27595:ccdb-populator]: er/7,0 0 1605784012159 hostname=pcalicecz3,dataprocessor_id=ccdb-populator
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784012880.root of size 138240 Valid for 0 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013233.root of size 138240 bytes, valid for 6 : 99999999999999
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784012948.root of size 138240 Valid for 1 : 99999999999999
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013006.root of size 138240 Valid for 2 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013062.root of size 138240 Valid for 3 : 99999999999999
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013122.root of size 138240 Valid for 4 : 99999999999999
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013178.root of size 138240 Valid for 5 : 99999999999999
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013233.root of size 138240 Valid for 6 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013289.root of size 138240 bytes, valid for 7 : 99999999999999
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013289.root of size 138240 Valid for 7 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013345.root of size 138240 bytes, valid for 8 : 99999999999999
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013345.root of size 138240 Valid for 8 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013400.root of size 138240 bytes, valid for 9 : 99999999999999
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013400.root of size 138240 Valid for 9 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] Number of DPs received (delta map) = 100
[27594:dcs-data-processor]: [12:06:53][INFO] Sending object Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013454.root of size 138240 bytes, valid for 10 : 99999999999999
[27594:dcs-data-processor]: [12:06:53][INFO] 
[27594:dcs-data-processor]: 
[27594:dcs-data-processor]: TIMING SUMMARY:
[27594:dcs-data-processor]: 
[27594:dcs-data-processor]: [12:06:53][INFO] Number of processed TF: 11
[27594:dcs-data-processor]: [12:06:53][INFO] Number of processed TF, processing full map: 1
[27594:dcs-data-processor]: [12:06:53][INFO] Number of processed TF, processing delta map: 0
[27594:dcs-data-processor]: [12:06:53][INFO] Number of processed TF, processing delta map per DP: 10
[27594:dcs-data-processor]: [12:06:53][INFO] Receiving binary data --> realTime = 8.23628e-07, cpuTime = 0
[27594:dcs-data-processor]: [12:06:53][INFO] Receiving binary data (delta) --> realTime = 6.28558e-07, cpuTime = 0
[27594:dcs-data-processor]: [12:06:53][INFO] Building unordered_map --> realTime = 0.0165448, cpuTime = 0.0154545
[27594:dcs-data-processor]: [12:06:53][INFO] Building unordered_map (delta) --> realTime = 0.00116574, cpuTime = 0.000909091
[27594:dcs-data-processor]: [12:06:53][INFO]  --> : Detector 0
[27594:dcs-data-processor]: [12:06:53][INFO] Processing full map (average over 1 TFs) --> realTime = 0.654177, cpuTime = 0.46
[27594:dcs-data-processor]: [12:06:53][INFO] Full delta DCS map was never processed
[27594:dcs-data-processor]: [12:06:53][INFO] Processing delta map per DP (average over 10 TFs) --> realTime = 0.00031333, cpuTime = 0.001
[27595:ccdb-populator]: [12:06:53][INFO] Storing in ccdb Test1Det/TestDCS/SimpleMovingAverageDPs/unordered_map<string,float>_1605784013454.root of size 138240 Valid for 10 : 99999999999999
[INFO] Quitting
[INFO] QUIT_REQUESTED
[27594:dcs-data-processor]: [12:06:53][INFO] Received device shutdown request (signal 15).
[27594:dcs-data-processor]: [12:06:53][INFO] Waiting for graceful device shutdown. Hit Ctrl-C again to abort immediately.
[27595:ccdb-populator]: [12:06:53][INFO] Received device shutdown request (signal 15).
[27595:ccdb-populator]: [12:06:53][INFO] Waiting for graceful device shutdown. Hit Ctrl-C again to abort immediately.
[27593:dcs-data-generator]: [12:06:53][INFO] Received device shutdown request (signal 15).
[27593:dcs-data-generator]: [12:06:53][INFO] Waiting for graceful device shutdown. Hit Ctrl-C again to abort immediately.
[27592:internal-dpl-clock]: [12:06:53][INFO] Received device shutdown request (signal 15).
[27592:internal-dpl-clock]: [12:06:53][INFO] Waiting for graceful device shutdown. Hit Ctrl-C again to abort immediately.
[27593:dcs-data-generator]: [12:06:53][STATE] RUNNING ---> READY
[27593:dcs-data-generator]: [12:06:53][STATE] READY ---> RESETTING TASK
[27593:dcs-data-generator]: [12:06:53][STATE] RESETTING TASK ---> DEVICE READY
[27593:dcs-data-generator]: [12:06:53][STATE] DEVICE READY ---> RESETTING DEVICE
[27593:dcs-data-generator]: [12:06:53][STATE] RESETTING DEVICE ---> IDLE
[27593:dcs-data-generator]: [12:06:53][STATE] IDLE ---> EXITING
[27593:dcs-data-generator]: [12:06:53][STATE] Exiting FairMQ state machine
[27593:dcs-data-generator]: [12:06:53][INFO] Process 27593 is exiting.
[27592:internal-dpl-clock]: [12:06:53][STATE] RUNNING ---> READY
[27595:ccdb-populator]: [12:06:53][STATE] RUNNING ---> READY
[27594:dcs-data-processor]: [12:06:53][STATE] RUNNING ---> READY
[27592:internal-dpl-clock]: [12:06:53][STATE] READY ---> RESETTING TASK
[27594:dcs-data-processor]: [12:06:53][STATE] READY ---> RESETTING TASK
[27594:dcs-data-processor]: [12:06:53][STATE] RESETTING TASK ---> DEVICE READY
[27592:internal-dpl-clock]: [12:06:53][STATE] RESETTING TASK ---> DEVICE READY
[27595:ccdb-populator]: [12:06:53][STATE] READY ---> RESETTING TASK
[27594:dcs-data-processor]: [12:06:53][STATE] DEVICE READY ---> RESETTING DEVICE
[27595:ccdb-populator]: [12:06:53][STATE] RESETTING TASK ---> DEVICE READY
[27592:internal-dpl-clock]: [12:06:53][STATE] DEVICE READY ---> RESETTING DEVICE
[27595:ccdb-populator]: [12:06:53][STATE] DEVICE READY ---> RESETTING DEVICE
[27594:dcs-data-processor]: Cleaning up for shared memory id 'ea73d772'...
[27594:dcs-data-processor]: No region counter found. No regions to cleanup.
[27592:internal-dpl-clock]: [12:06:53][STATE] RESETTING DEVICE ---> IDLE
[27594:dcs-data-processor]: Successfully removed 'fmq_ea73d772_m_0'.
[27592:internal-dpl-clock]: [12:06:53][STATE] IDLE ---> EXITING
[27594:dcs-data-processor]: Successfully removed 'fmq_ea73d772_mng'.
[27594:dcs-data-processor]: Successfully removed 'fmq_ea73d772_mtx'.
[27594:dcs-data-processor]: Successfully removed 'fmq_ea73d772_cv'.
[27595:ccdb-populator]: [12:06:53][STATE] RESETTING DEVICE ---> IDLE
[27595:ccdb-populator]: [12:06:53][STATE] IDLE ---> EXITING
[27592:internal-dpl-clock]: [12:06:53][STATE] Exiting FairMQ state machine
[27595:ccdb-populator]: [12:06:53][STATE] Exiting FairMQ state machine
[27592:internal-dpl-clock]: [12:06:53][INFO] Process 27592 is exiting.
[27595:ccdb-populator]: [12:06:53][INFO] Process 27595 is exiting.
[27594:dcs-data-processor]: [12:06:53][STATE] RESETTING DEVICE ---> IDLE
[27594:dcs-data-processor]: [12:06:53][STATE] IDLE ---> EXITING
[27594:dcs-data-processor]: [12:06:53][STATE] Exiting FairMQ state machine
[27594:dcs-data-processor]: [12:06:53][INFO] Process 27594 is exiting.
[INFO] Dumping used configuration in dpl-config.json
[INFO] Process 27591 is exiting.
[O2/latest] ~/SOFT/alibuild/ali-o2/sw/BUILD/O2-latest/O2 $> 
```

**Comment by aphecetche** [comment]
@chiara what are the next steps then ? A review by someone else (Ruben ? ) and merge ?

**Comment by chiarazampolli** [comment]
Ciao Laurent,
I cannot merge the code, so I guess that @shahor02 or @ktf  or someone else should take a look.
Chiara

**Review by pzhristov — APPROVED** [review]

**Pull request merged**
