### PR TITLE
FIT,TOF,TPC: Fixing sporadic/timeframe lifetimes

### PR DESCRIPTION
**Pull request by matthias-kleiner**

### CODE REVIEW

**Review by wiechula — DISMISSED** [review]

**Comment by davidrohr** [comment]
For my understanding, why is this sporadic? Do we write the output only for a subset of time frames?
One problem is that we cannot use sporadic arbitrarily. E.g., if a device has 2 inputs and receives them from different sources, if they do not arrive at the very same time and are declared sporadic, DPL will process the first one and assumes that the second one was missing. Perhaps this is not a problem for the writers, if they have only a single input. But one has to be careful.

**Comment by davidrohr** [comment]
@ktf : What does the consumeWhenAll completion policy do for sporadic inputs?
I think it starts processing when all timeframe data are there, taking the sporadics that are already there?
I'd propose we changes this such, to wait for all timeframe data to be there, and for all sporadic channels to have the right oldestPossibleTimeframe. That would guarantee that no further sporadic data can arrive?

**Comment by matthias-kleiner** [comment]
> For my understanding, why is this sporadic? Do we write the output only for a subset of time frames? One problem is that we cannot use sporadic arbitrarily. E.g., if a device has 2 inputs and receives them from different sources, if they do not arrive at the very same time and are declared sporadic, DPL will process the first one and assumes that the second one was missing. Perhaps this is not a problem for the writers, if they have only a single input. But one has to be careful.

Hi, the data is actually written for each TF, but the output is defined as Sporadic. I could also change the output to TimeFrame, if this would make more sense

**Comment by davidrohr** [comment]
ok, I think if an output is created for every timeframe, it should be declared lifetime::timeframe. That is the cleaner solution.

**Comment by ktf** [comment]
>I'd propose we changes this such, to wait for all timeframe data to be there, and for all sporadic channels to have the right oldestPossibleTimeframe. That would guarantee that no further sporadic data can arrive?

The drawback of that is that timeframes with sporadic inputs will be processed serially, which might or might not be a good idea.

**Pull request merged**
