### PR TITLE
FIT: new LookupTable class and some additional features/fixes for FITRaw and FITWorkflow libs

### PR DESCRIPTION
**Pull request by afurs**
First step of FIT LUT implementation(only for FT0). Second step(for FV0 and FDD) will be ready soon. Due to common FITRaw interface for all three detector and only for FT0 new FIT LUT implemented, some part of code(related to digit2raw convertaion) is still ugly. Fixes will be applied in next PR. New FIT LUT for FT0 was prepared ASAP by @alla 's request for urgent simulation features.
1) New FIT LookupTable and new schematics of FEE connection
2) Some refactoring for FITRaw(space reserve for ChannelData in vector, within DigitBlock class ).
3) New functionality added to FITWorkflow for sending data vectors without additional copying. Not implemented, checking by performance tests.

### CODE REVIEW

**Comment by afurs** [comment]
@AllaMaevskaya @mslupeck @jotwinow could you take a look to this PR? All tests and checks are passed, one need only review/approve

**Review by mslupeck — APPROVED** [review]
Structurally it looks good to me. But maybe better to wait with merging until @AllaMaevskaya approves it.

**Comment by afurs** [comment]
> Structurally it looks good to me. But maybe better to wait with merging until @AllaMaevskaya approves it.

Hello @mslupeck , afaik Alla is on the vacation. But she already took a look and tested my code(her commit is also in this PR).

**Comment by mslupeck** [comment]
OK @afurs, if Alla tested it then we should merge it asap to be in time for the pilot beam simulations.
Hi @shahor02, could you merge this PR?

**Comment by mslupeck** [comment]
Thanks!

**Pull request merged**
