### PR TITLE
DPL: refactor Control parsing helpers

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken I've the impression build times for PRs have increased, a lot in the last few days. Did anything change?

**Comment by TimoWilken** [comment]
@ktf, I think it might be because of the changelog-generating code -- #5323 gets rebuilt every time the changelog changes, which is every time anything gets pushed to the repo. I've been meaning to work out a good way to stop that.

The easiest thing to do is probably to put "WIP" in the PR title. Also, it maybe should only run when `dev` is changed...

**Comment by ktf** [comment]
We should probably exclude from tests PRs which only change documentation. As a stop gap solution, [WIP] is fine.

**Comment by ktf** [comment]
Or even making it a draft.

**Pull request merged**
