### PR TITLE
[EMCAL-788] EMCAL cell selection, on-the-fly calibration

### PR DESCRIPTION
**Pull request by mfasDa**
- Selection of good EMCAL cells
  - Require FEE readout (HG and LG cells)
  - Time cut around trigger peak
  - Min. cell energy
- On-the-fly recalibration
   - Optional
   - Only in synchronous workflow

### CODE REVIEW

**Comment by mfasDa** [comment]
Needs https://github.com/AliceO2Group/AliceO2/pull/11844

**Comment by mfasDa** [comment]
@jmyrcha Please review!

**Comment by mfasDa** [comment]
On-the-fly calibration should run in the synchronous stage while the it must not run in the asynchronous stage: In the asynchronous stage we apply the calibrations as part of the asynchronous reconstruction, consequently the event display will get fully calibrated cells and does not need to calibrate internally. In the synchronous stage we don't want to run the recalibration workflow because we want to make sure that the calibrated cells don't get mixed with the uncalibrated cells by some wildcarded data request, since we want to store uncalibrated cells persistently (in the synchronous stage we work with an a-priori calibration).

**Review by shahor02 — COMMENTED** [review]
Fine for me, but the formatting of CMakefiles is destroyed, could you restore it?

**Comment by mfasDa** [comment]
I have seen that there is a way to do the rejection of low-E cells in the visualization part, so this would be optional for the producer and could be removed. Not handled however and still important is the time cut. For this I attached two plots from our QC from a run with single bunches that demonstrates the effect. Uncalibrated:
CellTimeEnergy_uncalibrated
... and calibrated:
CellTimeEnergy_calibrated
One sees here that a substantial amount of hot cells fires at time far from the trigger peak however at energies sufficiently high so that they are not removed by the energy cut.

For what concerns the on-the-fly recalibration: The amount of operations is one subtraction, one multiplication and one check for status, in each cases the coefficients are taken from an array or bitfield - the CPU overhead should be moderate. Furthermore the way it is implemented allows to switch it off via a command line argument.

**Comment by davidrohr** [comment]
@mfasDa : what is the status of this PR? Is it still needed? Apparently it makes the FST crash.

**Comment by mfasDa** [comment]
@davidrohr As can be seen above it is pending in review from @jmyrcha. Currently the event display neither uses the bad channel map nor does it reject pileup via a time cut, would be advisable to do so. As I explained above the application of the online calibration should be done in the components itself in order to not have online-calibrated cells entering the CTF.

**Comment by mfasDa** [comment]
I don't fully understand the error message, since the option names match. The only issue I could imagine is an implicit cast issue due to the missing `f` in the default value specification for the new float options, which I just fixed.

**Comment by davidrohr** [comment]
@mfasDa : could you revert the CMake formatting changes, and only add your change?
Or if the formatting change came from running the O2 CMaker formatter, it should go into a seperate commit.

@jmyrcha : Could you check if you have objections? Otherwise I'll merge it once formatting changes are fixed.

**Comment by mfasDa** [comment]
Hi @davidrohr, indeed my VSCode autoformat settings applied the cmake formatter when saving the file after changes. I manually unapplied now all the formatting changes in the CMakeLists.txt - now there are only the dependencies left over which I added.

**Comment by davidrohr** [comment]
@mfasDa : Sorry, I failed to follow it up. Now it is green, and the formatting seems ok.
Shall we merge it?

**Comment by mfasDa** [comment]
@davidrohr , yes I think we should merge it. The requested review will probably never come :(

**Pull request merged**
