### PR TITLE
DPL: improve timers

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy @knopers8 this should make the `Lifetime::Timer` finally behave in terms of CPU usage.

**Comment by knopers8** [comment]
Thanks, I will try it out.

**Comment by knopers8** [comment]
The CPU usage indeed went down, but timers now do not activate without data coming (seen on `o2-qc-run-basic`).

**Comment by ktf** [comment]
Ok, indeed there is something wrong also for the ExternalProxy... Looking into it.

**Comment by ktf** [comment]
Ok, the problem is that timers are now in milliseconds, rather than microseconds. Given there the previous "microsecond" scale was mostly a lie (given that it was the minimal interval, not the actual interval ellapsed), shall we simply move to milliseconds everywhere? This only affects times, not retrieving messages from fairmq, of course.

**Comment by knopers8** [comment]
I would propose to keep microseconds, let's not waste time on changing the interface and making sure that everything follows that change.

**Comment by ktf** [comment]
Ok.

**Comment by ktf** [comment]
Updated. Tested with ExternalFairMQProxy, but I assume the problem was the same in your case. Can you check?

**Comment by knopers8** [comment]
I will check

**Comment by knopers8** [comment]
It seems ok now, QC cycles work correctly and the CPU usage is low, thanks.

**Comment by ktf** [comment]
Cool. All the other tests are also fine. Merging.

**Pull request merged**
