### PR TITLE
Modified GeometryManager and moved from ITS to o2::Base

### PR DESCRIPTION
**Pull request by shahor02**
1) Eliminated layers in the GeometyManager since they were forcing hack in ITS to overcome the
limitation on the number of sensors. Now the sensors of particular detector will be referred by DetID identifier
and the continuos sensorID (from 0 to nSensors_in_detector-1), see GeometyManager::getSensID(DetID detid, int sensid)
method.
2) Moved general purpose methods for accessings PNEs and matrices from ITS.../GeometryTGeo.cxx to GeometryManager.cxx
and eliminated reduntant methods (were not used anywhere)
3) Misc. cleaning and coding conventions fixes + clang formatting of GeometryTGeo and GeometyManager

### CODE REVIEW

**Comment by shahor02** [comment]
@mario6829 : as discussed, the GeometryManager is now in the o2::Base to serve also other detectors.
I believe it (also ITS/base/GeometryTGeo) has still many redundant methods which propagated from aliroot. They may also miss some methods: as far as I can see, the the alignable entries are not yet defined in the ITS, let me know if you miss some tools when implementing them, I would prefer to keep them in the GeometryManager rather than in particular detector code.

**Comment by shahor02** [comment]
fixed dependency in O2/cmake/O2Dependencies.cmake and squashed commits

**Comment by mario6829** [comment]
@shahor02 thanks, as soon as I finish porting the OB geometry and fixing C++ improvements, I'll go with the alignable volumes, and I let you know if something is missing or not working as expected.

**Comment by shahor02** [comment]
Thanks @mario6829 . @ktf , @sawenzel , @mkrzewic : if there are no comments, could you please merger this PR so that development of dependent code can be continued? Note that neither GeometryManager nor the GeometryTGeo classes are not final yet, at this moment these is no point of too much polishing.

**Pull request merged**
