### PR TITLE
Improve install speed on macOS (dramatically)

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by dberzano** [comment]
It should work now. Note that for the moment the `build/O2/o2` test is unrelated. Let's wait the macOS one.

**Comment by dberzano** [comment]
Merging as the O2 error is unrelated.

**Comment by aphecetche** [comment]
@dberzano with this change the *LD_LIBRARY_PATH variables can actually be removed from the o2 modulefile can't they ?

**Comment by sawenzel** [comment]
@dberzano, @aphecetche: Just to be sure what this discussion is about: Are you suggesting that in future I will have to load every single library with gSystem->Load()? (instead of relying on the fantastic ROOT6 feature to load libraries automatically)

**Comment by aphecetche** [comment]
I'll let Dario comment further, but no, that's not the idea at all ;-) 

The thing with rpath is that you don't need to have LD_LIBRARY_PATH defined for your executables to find their shared libraries. Would be one step towards cleaner environments IMHO. 

The autoload of Root libraries (a killer feature, I agree) is a different thing altogether (at least that's how I understand it).

**Comment by sawenzel** [comment]
Ok thanks.

**Comment by dberzano** [comment]
> Are you suggesting that in future I will have to load every single library with gSystem->Load()?

Absolutely not! Back in the days of Run2 I have worked to add autoload features (already present in ROOT5), even if legacy code is filled with plenty of unneeded `gSystem->Load()`.

What I am saying is that there _might_ be cases (though I hope there aren't!) where `gSystem->Load()` is needed in O2, and I seem to recall that it relies on `LD_LIBRARY_PATH` (the underlying `dlopen()` call surely does in any case).

In practice, given that O2 is still under heavy development, I suggest we try to get rid of `(DY)LD_LIBRARY_PATH` on macOS and "see if someone complains". I am pretty confident that it will work, but we can quickly revert in case it does not.

@aphecetche feel free to open a PR where you get rid of those on Mac only :-)

**Comment by aphecetche** [comment]
> @aphecetche feel free to open a PR where you get rid of those on Mac only :-)

will do as soon as I confirm this is not the cause of problems I'm observing in some simulation unit tests...

**Pull request merged**
