### PR TITLE
Hide FairMQ stuff in Detector headers

### PR DESCRIPTION
**Pull request by sawenzel**
Refactor detector functionality needed in FairMQ based simulation.
Move FairMQMessage/Channel specific stuff into source file
in order to avoid problems with ROOT macros.

### CODE REVIEW

**Comment by dberzano** [comment]
Hi @sawenzel, @mkrzewic: just to be clear, if we test current `dev` + #1464 (this one) + #1458 (Mikolaj's) with FairMQ bumped to 1.3.6 it should work, right?

(I am having a go at it locally in any case.)

**Comment by mkrzewic** [comment]
let's hope it does :) sandro probably already tested. What about submitting a bug report to root?

**Comment by sawenzel** [comment]
I did test under the new conditions. The problems coming from detector code are gone. But there a still 3 other CCDB macros that break. Not yet sure what to do with them ... (eventually we can disable them) ... but let's see.

**Comment by dberzano** [comment]
OK, let me have a look. Worst case, I agree: we disable them for the purposes of this release...

**Comment by dberzano** [comment]
By combining dev + this + @mkrzewic's PR I indeed get, as @sawenzel noticed:

```
The following tests FAILED:
	  1 - /CCDB/example/fill_local_ocdb.C (Failed)
	 67 - /macro/loadExtDepLib.C (Failed)
	 70 - /macro/putCondition.C (Failed)
Errors while running CTest
```

I believe we can disable them ATM: #1465.

**Pull request merged**
