### PR TITLE
DPL: Extending initial parsing of input messages

### PR DESCRIPTION
**Pull request by matthiasrichter**
This is a part of  #7110 in preparation for support of split payloads with pruned headers.

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@davidrohr @ktf @shahor02  I don't actually think, the fullCI failure is related to the PR, have you seen this `bad_alloc` in the its tracker before?

**Comment by shahor02** [comment]
pinging to @mpoghos concerning the `bad alloc`

**Comment by ktf** [comment]
I've never seen it myself.

**Comment by shahor02** [comment]
used wrong name, now pinging to @mpuccio

**Pull request merged**
