### PR TITLE
All root tree reader/writer devices got --input-dir and --output-dir options

### PR DESCRIPTION
**Pull request by shahor02**
* MakeRootTreeWriterSpec get `--output-dir` option (`def:=./`) 
* All root-file reader devices got `--input-dir` option

Note that if the option is provided to the whole workflow, then all readers/writers of this workflow will share this setting.
To apply it to particular reader or writer, mentions this option in the list of options for this particular device.
i.e.
````
o2-sim-digitizer-workflow --output-dir xxx
```` 
will store all digit files in `xxx` directory (it should be existing beforehand!), while 
````
o2-sim-digitizer-workflow --TPCDigitWriter "--output-dir yyy"
```` 
will store TPC digits in `yyy` and everything else in the default (cwd) directory.

### CODE REVIEW

**Review by peressounko — APPROVED** [review]

**Comment by shahor02** [comment]
fullCI failure is unrelated, local test is OK, merging

**Comment by martenole** [comment]
Hi @shahor02 
sorry to bring that up only now, but what was the reason not to provide the default `input-dir=./`  for the reader devices? And how can I properly set the input directory? After creating a small simulation and running the digitization for example the ITS reco does not seem to work with
`o2-its-reco-workflow -b --trackerCA --tracking-mode async --shm-segment-size 10000000000 --run`
Because of the error
`Unhandled std::exception reached the top of main: missing option: input-dir (No such node (input-dir)), device shutting down.`
But when trying with `--input-dir ./` I get the error `Error: unrecognised option '--input-dir'`.
Actually also the `o2-sim-digitizer-workflow` does not work for me with the current `dev` branch when running it for the first time. I get errors `[ERROR] Unable to pass configuration to children`, but when running it a second time it seems to work. 
Cheers,
Ole

**Comment by shahor02** [comment]
Hi @martenole 
the default input (and output) dir. is in fact "./". But if the user provides the full path e.g. via (--its-digit-infile), it will not be mergeable with default "./". For this reason the default is "" (and since the string option does not support an empty string, I define it as "none" which is converted to "", meargeable with any path).

For the ITS: there was a bug, now fixed.
As for the  o2-sim-digitizer-workflow, I don't think this is related, should be /dev/shm/* leftover files problem which were cleaned after the 1st attempt.

**Comment by martenole** [comment]
@shahor02 thanks. Then probably the same fix is still needed in `Detectors/ITSMFT/common/workflow/src/ClusterReaderSpec.cxx` for the `its-cluster-reader` device. For the `mft-cluster-reader` I think you added the option, but maybe missed it in line 114.

**Comment by shahor02** [comment]
@martenole fixed, thanks for spotting.

**Comment by martenole** [comment]
I obviously ran into the same error with the ITS-TPC matching so I knew where to look :)
Thanks a lot for fixing it quickly!

**Pull request merged**
