### PR TITLE
Move TRD readers into independent lib

### PR DESCRIPTION
**Pull request by martenole**
To reduce the number of dependencies which are added when including the readers.
Also cleaned up a bit leftover unused variables and includes which are no longer needed.
Ping @davidrohr

### CODE REVIEW

**Comment by martenole** [comment]
@jolopezl I noticed that the digit reader includes `TRDBase/MCLabel.h`. In this header there is only an alias defined, basically `using o2::trd::MCLabel = o2::MCCompLabel;`. Is this alias needed? If so I can also move that to `DataFormatsTRD`. Because otherwise the new library which I created for the TRD workflow readers would depend again on TRDBase and we need to reduce the number of dependencies for the readers as much as possible.

**Comment by davidrohr** [comment]
Hi @martenole : please move the header to DataFormatsTRD, there is no reason that this resides in TRDBase.

**Comment by jolopezl** [comment]
> @jolopezl I noticed that the digit reader includes `TRDBase/MCLabel.h`. In this header there is only an alias defined, basically `using o2::trd::MCLabel = o2::MCCompLabel;`. Is this alias needed? If so I can also move that to `DataFormatsTRD`. Because otherwise the new library which I created for the TRD workflow readers would depend again on TRDBase and we need to reduce the number of dependencies for the readers as much as possible.

@martenole, the alias isn't needed. It has only historical meaning and stood there waiting for a specialization. So, it can be removed, moved, left there, or – maybe better – have new readers depend on `o2::MCCompLabel` only, as you already did.

**Comment by martenole** [comment]
Ah ok, thanks. Then I'll remove it again :)

**Review by bazinski — DISMISSED** [review]

**Comment by martenole** [comment]
With the last commit I also moved the digit and tracklet writer specs into the new library (now called `TRDWorkflowIO` instead of `TRDWorkflowReaders`). The only additional dependency is `DPLUtils` for the ROOT tree writer.
@bazinski I could have also moved `TRDTrapRawWriterSpec`, but I noticed it is not added into a workflow yet. This probably comes with your https://github.com/AliceO2Group/AliceO2/pull/5912 ? Anyway I did not touch it yet to not interfere, but this can be trivially moved as well later.
@davidrohr There is also a `TRDTrackWriterSpec` which I did not move, since this would pull some GPU dependencies for the `GPUTRDTrack` type. But when I add a track reader then this will anyways be needed, so it might come later when the GPU data types are in a separate library.

**Comment by bazinski** [comment]
@martenole no TRDTrapRawWriterSpec was removed when the raw data generation was removed from the trapsim, so it used to produce digits/tracklets/triggerrecords/rawstream. The latter is no longer there. The logic that sat there was removed to trap2raw so all the raw data generation is logically contained in 1 place instead of 2.

**Comment by davidrohr** [comment]
@martenole : Please don't pull in the GPU dependency to the reader library, let's leave the writer in the normal TRDWorkflow then. I have just merged your #6026, so you have to rebase and solve a minor conflict :)

**Comment by davidrohr** [comment]
Fix for the CI failures in in #6059 
@TimoWilken : Could you restart the failed CIs?

**Comment by davidrohr** [comment]
superseded by #6057

**Pull request closed without merging**
