### PR TITLE
DPL: drop unneded abstraction

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
I think this is just some old bloat...

**Comment by ktf** [comment]
@costing @chiarazampolli @Barthelemy @sawenzel since a few days I get messages along the line of:

```
[INFO] Reading B, expect cached since only A cache was cleaned: testObjectO
/sw/SOURCES/O2/7563-slc8_x86-64/0/CCDB/test/testBasicCCDBManager.cxx(95): [1;31;49merror: in "TestBasicCCDBManager": check objB && (*objB) == hack has failed[0;39;49m
```

is this known / being looked at?

**Comment by ktf** [comment]
@davidrohr I think we have an extra bracket somewhere...

```
/sw/BUILD/f3ba72c9534f32f4feeb7410aa4c0d0884c61f91/O2-full-system-test/full-system-test-sim
Running: TIME="#walltime %e" /sw/slc8_x86-64/O2/7563-slc8_x86-64-local1/share/scripts/monitor-mem.sh /usr/bin/time --output=reco_ASYNC.log_time './reco_ASYNC.log_tmp.sh'
/usr/bin/time --output=reco_ASYNC.log_time ./reco_ASYNC.log_tmp.sh
/sw/slc8_x86-64/O2/7563-slc8_x86-64-local1/prodtests/full-system-test/dpl-workflow.sh: line 389: [[[: command not found
```

**Comment by davidrohr** [comment]
fixed in #7567

**Pull request merged**
