### PR TITLE
ITS and MFT use common materials for the ALPIDE chip

### PR DESCRIPTION
**Pull request by bovulpes**
In agreement with the ITS @mario6829 the ALPIDE chip materials are created only once and used by the ITS and the MFT independently.

### CODE REVIEW

**Comment by sawenzel** [comment]
@bovulpes: Looking good. Can you please still fix the clang-format errors reported under the travis details?
The test failure is unrelated to this PR.

**Comment by bovulpes** [comment]
@sawenzel I understand that one should privilege the content of the configuration files for IDE (CLang or Eclipse, please see also the message from Laurent A.) instead of the "ALICE O² C++ Coding Guidelines" document. The rule for nesting namespaces for instance is different in the two sources.

**Comment by sawenzel** [comment]
@bovulpes : I don't quite understand the comment but I might have missed some ongoing discussions. What do you mean by privileging IDEs?

The formatting rules are expressed in our global clang-format files which serves as the central authority for formatting checks ( IDEs should follow this file ).

**Comment by bovulpes** [comment]
Hallo Sandro,

I did a test on a dummy file and formatted it in the two ways: using Eclipse configured with the provided xml file and using the clang-format command using the file provided too in the project repository AliceO2Group/CodingGuidelines and I have found differences between those two and again different from what the "written" document indicates, for example here https://htmlpreview.github.io/?https://github.com/AliceO2Group/CodingGuidelines/blob/master/coding_guidelines.html#Namespaces
I want to mention that I have used the latter to introduce and discuss the rules during the MFT WP9 vidyo meetings, so I wonder if I was really pointing to the correct resources.
Here is an attached file with the diffs.

[o2crdif.txt](https://github.com/AliceO2Group/AliceO2/files/1766384/o2crdif.txt)

**Comment by bovulpes** [comment]
@sawenzel I want to use the global O2 .clang-format file but I have the clang version 3 and some keys 
are not recognized. Would it be possible to update instead the files for the IDE tools: 
Eclipse_O2_formatting.xml and settings-codestyle-clion.jar for people who are using them or who do not have clang version >= 4.5 ?
Should I instead go file-by -file and apply the formatting rules in the editor ?

**Comment by bovulpes** [comment]
@sawenzel I can use the O2 .clang-format file on another machine where I have installed 
clang-format-3.9 without errors about not recognised keys. I will use this one to be conformal 
with the travis ci and correct the files for this pull request.

**Comment by sawenzel** [comment]
Thanks. If you know how to update the eclipse styles, please provide a PR to sync with the style.
I personally use a clang-format plugin inside eclipse which works beautifully.

Something I had in mind is actually using the travis-CI output and provide automatic patch files (or even an automatic fix PR) which developers could just take/patch/merge. This would improve the workflow quite a lot.

**Comment by bovulpes** [comment]
I have the impression that the Travis CI did not take into account my last modifications and it keeps giving the same errors. How can I restart from the beginning?

**Comment by ktf** [comment]
Indeed. I've restarted it.

**Comment by sawenzel** [comment]
@bovulpes : I made a PR into your branch which should fix the remaining issues. We can then go on with merging this PR.

**Comment by bovulpes** [comment]
Thanks @sawenzel but finally I did not understand what was wrong, I had again to change by avoiding to have a ///< comment broken in two lines so I shortened it and it passed.

**Comment by sawenzel** [comment]
Good. Problems resolved. Merging.

**Pull request merged**
