### PR TITLE
DPL: get rid of simplified CompletionPolicy

### PR DESCRIPTION
**Pull request by ktf**
DPL: get rid of simplified CompletionPolicy

The full blown version has been there for a while now, and in any case
it's required if one wants to access the oldest possible timeframe.

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/AliceO2Group/AliceO2/pull/12450).
* #12451
* __->__ #12450

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @shahor02 @mfasDa there seems to be an error about missing EMC data in the full system test. Could you have a look? See beleow.

@TimoWilken looks like we are not grepping for error messages in the fullCI result (while accounting for them correctly) could you fix that?

```
Launching task: o2-its-digi2raw --file-for cruendpoint -o raw/ITS &> itsraw.log &
Launching task: o2-mft-digi2raw --file-for cruendpoint -o raw/MFT &> mftraw.log &
Launching task: o2-ft0-digi2raw --file-for cruendpoint -o raw/FT0 &> ft0raw.log &
Launching task: o2-fv0-digi2raw --file-for cruendpoint -o raw/FV0 &> fv0raw.log &
Launching task: o2-fdd-digit2raw --file-for cruendpoint -o raw/FDD &> fddraw.log &
Launching task: o2-tpc-digits-to-rawzs --zs-version 4 --file-for cruendpoint -i tpcdigits.root -o raw/TPC &> tpcraw.log &
Launching task: o2-tof-reco-workflow -b --file-for cruendpoint --output-type raw --tof-raw-outdir raw/TOF &> tofraw.log &
Launching task: o2-mid-digits-to-raw-workflow -b --mid-raw-outdir raw/MID --file-for cruendpoint &> midraw.log &
Launching task: o2-mch-digits-to-raw --input-file mchdigits.root --output-dir raw/MCH --file-for cruendpoint &> mchraw.log &
Launching task: o2-emcal-rawcreator --file-for link -o raw/EMC &> emcraw.log &
Launching task: o2-phos-digi2raw --file-for link -o raw/PHS &> phsraw.log &
Launching task: o2-cpv-digi2raw --file-for cruendpoint -o raw/CPV &> cpvraw.log &
Launching task: o2-zdc-digi2raw --file-for cruendpoint -o raw/ZDC &> zdcraw.log &
Launching task: o2-hmpid-digits-to-raw-workflow --file-for crorcendpoint --outdir raw/HMP &> hmpraw.log &
Launching task: o2-trd-trap2raw -o raw/TRD --file-for cruendpoint &> trdraw.log &
Launching task: o2-ctp-digi2raw -o raw/CTP --file-for cruendpoint &> ctpraw.log &
ERROR: Full system test did generate no raw data for EMC
```

**Comment by mfasDa** [comment]
This is probably related to https://github.com/AliceO2Group/AliceO2/pull/12453, where we now require FIT trigger input in the simulation. For physics this is needed, because otherwise EMCAL self-triggers would shadow real fit triggers. In case there is a problem with the trigger configuration in the unanchored range this might lead to an input mask string 0 for FT0 and consequently dropping all triggers. For the full system test I would for the moment go back to self-triggered mode, and will prepare a patch for that.

**Comment by ktf** [comment]
Thank you.

**Comment by ktf** [comment]
@davidrohr @martenole we now have some issue with ALIEN_JDL_PROCESSITSDEADMAP. Ideas?

**Comment by martenole** [comment]
> @davidrohr @martenole we now have some issue with ALIEN_JDL_PROCESSITSDEADMAP. Ideas?

I see Ruben already fixed that problem in https://github.com/AliceO2Group/AliceO2/pull/12474.

And about the EMCAL error this was already reported in the fullCI of https://github.com/AliceO2Group/AliceO2/pull/12453 and that PR was merged in any case which is not good of course. Would it be possible to provide a patch tomorrow @mfasDa ? Otherwise I suggest to revert #12453 and reopen it once the fix is available

**Comment by ktf** [comment]
Ok, the issues seems to have cured themselves.

**Comment by mfasDa** [comment]
@martenole I do not agree with reverting https://github.com/AliceO2Group/AliceO2/pull/12453. If someone of you reverts it I will immediately put it in again. As productions are starting the focus should also be that the simulation correctly reproduces the detector behaviour, and not just that the code compiles but has nothing to do with reality.

I explained here https://github.com/AliceO2Group/AliceO2/pull/12467 that failures in the full CI were due to a faulty trigger configuration for the unanchored range, where there was no trigger cluster assigned to EMCAL readout, for which consequently no trigger input could be found, in which case all events were rejected. The trigger configuration has been fixed immediately by Roman, and now from what I see the fullCI errors have been gone, so there is no need for reverting the PR Even if there would be still a problem with the trigger configuration I would rather first apply https://github.com/AliceO2Group/AliceO2/pull/12467, which only restores self-triggered mode in the fullCI than reverting the PR entirely.

**Comment by ktf** [comment]
Maybe there was some misunderstanding, the issue is gone after your fix. So no need to argue.

Please just verify fullCI passed the tests / the issues are unrelated before force merging things. Notice this should include checking the full log, not just the summary (i.e. grepping for errors can miss things, like in this case).

**Comment by martenole** [comment]
Hi Markus, all good. I see that after the upload of the new [CTP configs](https://alice.its.cern.ch/jira/browse/O2-3866) the fullCI does not complain anymore. So of course I won't revert your PR. But we should not break our fullCI! Ideally, after spotting the failure of the CI we would have waited for the CCDB upload and only afterwards merged it to not disrupt other unrelated changes to the code.

**Pull request merged**
