### PR TITLE
Add optional PV validation/rejection using FT0 timing

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @AllaMaevskaya,
 I see that in simulation with QED basically every BC has FT0 recpoint assigned. Can you suggest a recpoint selection which would suppress the QED but would cut as low as possible in hadronic multiplicity?

**Comment by AllaMaevskaya** [comment]
Hello
cut sum amplitude A+C > 70 will cut all QED events
Alla

**Comment by AllaMaevskaya** [comment]
Or you can use trigger signals
     o2::ft0::Triggers mTriggers = recPoint.getTrigger();
      (mTriggers.amplC + mTriggers.amplA) > 30  //#channels

**Comment by shahor02** [comment]
Hi @AllaMaevskaya, thanks! Indeed, ``(mTriggers.amplC + mTriggers.amplA) > 30`` removes all qed, but I see in pp it also suppresses ~40% of triggers, so, I guess the very peripheral pbpb would be also lost...

**Comment by AllaMaevskaya** [comment]
Yes, I attached plots with efficiency as a function of impact parameter
effB

**Comment by AllaMaevskaya** [comment]
I will play with cut, may be (mTriggers.amplC + mTriggers.amplA) > 20 would be enough. We have now ~2000 PbPb events and at the end of week will be ~15000. I will try to find compromise between purity and efficiency.
Efficiency of coincidence  A&C is 100% only up to b=14fm, then dropped to 60% at 17 fm for pure HI, without QED

**Comment by shahor02** [comment]
@davidrohr @ktf : the ``o2checkcode/o2 `` suddenly started to fail with 
````
Error while processing /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx.
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/ITSMFT/common/reconstruction/src/Clusterer.cxx:22:10: error: 'omp.h' file not found [clang-diagnostic-error]
#include <omp.h>
...
Error while processing /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/TPC/reconstruction/src/GPUCATracking.cxx.
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Detectors/TPC/reconstruction/src/GPUCATracking.cxx:39:10: error: 'omp.h' file not found [clang-diagnostic-error]
#include <omp.h>
````
Any idea why? This code did not change since long time.

**Comment by shahor02** [comment]
failures unrelated, merging

**Pull request merged**
