### PR TITLE
O2-4592 - adding TOF LTIntegral to time series&skimmed data

### PR DESCRIPTION
**Pull request by miranov25**
Adding TOF information structure o2::track::TrackLTIntegral ltIntegral=tpctofmatch.getLTIntegralOut() into the

### CODE REVIEW

**Comment by miranov25** [comment]
Hello @noferini , @ercolessi @matthias-kleiner 

As we agreed I am pushing the TOF information into the TPC time series & skimmed data. 
The test looks fine, I will test few correlation and request cherry pick.

New time series:
```
 treeTimeSeries->Show(0)->
....
 sqrtChi2Match   = -1
 tpcYDeltaAtTOF  = -999
 tpcZDeltaAtTOF  = -999
 mDXatTOF        = -999
 mDZatTOF        = -999
 mTOFLength      = (o2::track::TrackLTIntegral*)0x53aff90
 mL              = 0.000000
 mX2X0           = 0.000000
 mXRho           = 0.000000
 mT[9]           = 0.000000 , 0.000000 , 0.000000 , 0.000000 , 0.000000 ,
                    0.000000 , 0.000000 , 0.000000 , 0.000000
 mTOFSignal      = 0
..
```
The content looks reasonable so far:
```
treeTimeSeries->Draw("mL:tgl:abs(qpt)","mL>0","colz")
```
image

**Comment by shahor02** [comment]
@miranov25 you have to apply `clang-format`. Note that this is adding ~10 non-empty floats per TOF track.

**Comment by miranov25** [comment]
##  AddingTPC, Vertex, and TPC-TOF time
* T0 time is for a moment missing .... needs too much coding
@noferini, do we have preliminary T0 time available at all during tracking, or is it calculated only later on?

```
 mTOFLength      = (o2::track::TrackLTIntegral*)0x366e2f0
 mL              = 0.000000
 mX2X0           = 0.000000
 mXRho           = 0.000000
 mT[9]           = 0.000000 , 0.000000 , 0.000000 , 0.000000 , 0.000000 ,
                    0.000000 , 0.000000 , 0.000000 , 0.000000

 mTOFSignal      = 0
 mDeltaTTOFTPC   = 0
 vertexTime      = 0
 trackTime0      = 2541.89
```

**Comment by miranov25** [comment]
@shahor02, @davidrohr, @wiechula

Could you please review the pull request? I would like to request a cherry-pick of the code. Local tests have been successful without any issues.

Best regards,
Marian

**Comment by miranov25** [comment]
> @miranov25 you have to apply `clang-format`. Note that this is adding ~10 non-empty floats per TOF track.

Somehow clang is stuck, for a moment. I will add it clang version soon.
For the size we can optimize that size using diff to pion, for a moment it creates 3 % increase in the data volume:
```
root [16] treeTimeSeries->GetBranch("mT[9]")->GetZipBytes()/float(treeTimeSeries->GetZipBytes())
(float) 0.0340168f
```

**Comment by noferini** [comment]
> ## AddingTPC, Vertex, and TPC-TOF time
> 
>     * T0 time is for a moment missing .... needs too much coding
>       @noferini, do we have preliminary T0 time available at all during tracking, or is it calculated only later on?

Hi @miranov25 ,
- FT0-T0 is not yes associated at this stage, in TOF QC we re-match it to TOF tracks by requiring the same BC
- TOF-T0 from combinatorial algorithm is calculated later, at analysis level affter collision is defined. Again, in TOF QC we group tracks close in TOF-time to define collision and test TOF-T0.
For time-series I would take care to port only FT0-T0 which is quite efficient and provided with a good resolution. I have to check in our code if we can match FT0 and TOF-tracks already in our matching algorithm (I think I do it already for TOF calibs) to simplify your life.

**Comment by miranov25** [comment]
Hello @shahor02, @noferini, and @wiechula,  

I ran `clang-format`, and everything looks fine—there is no difference before and after formatting:  
```
[O2Physics/latest-master-o2] /scratch/alice/miranov/alicesw/O2/Detectors/TPC/workflow/src $> diff TPCTimeSeriesSpec.cxx TPCTimeSeriesSpec.cxx.clang  
[O2Physics/latest-master-o2] /scratch/alice/miranov/alicesw/O2/Detectors/TPC/workflow/src $>  
```  
This suggests there might be a bug in the build system.  

Could this be approved so I can request a cherry-pick for the **apass1 production**?  

### Data Volume for mT  
Regarding the data volume for the mT, I will apply compression with an estimated factor of **4–8**. It is straightforward since we only need to encode very small deltas relative to the expectation:  
```
t = L / <β_ι>  
<β_ι> = β0_ι + (dβ_ι / dp) * Δp  
```  
Here:  
- `Δp` is similar for all particle species.  
- The variation around the approximation is minimal, leading to very low entropy, effective residual coding

I will review how this is currently implemented in the AO2D, but it can be coded efficiently in a similar manner. I am prototyping the approach now.  

Best regards,  
Marian

**Review by shahor02 — APPROVED** [review]
The fullCI fails due to the failed git fetch of QC.

You have to assign labels.

**Comment by miranov25** [comment]
## For the record - promising formulas for the TOF delta time, delta momentum correction

image

**Pull request merged**
