### PR TITLE
DPL: check for bind result as well.

### PR DESCRIPTION
**Pull request by ktf**
Apparently due to different OS / kernel behaviors, there might be cases in
which bind can fail as well.

Also use uv_tcp_close_reset to speedup when the port will be available
again.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr can you try with this? I think we are actually hitting some libuv / BSD sockets platform specific issues.

**Comment by davidrohr** [comment]
Will test this now, but I don't see the usage of `uv_tcp_close_reset` in the commit? Did you miss a second commit?

**Review by davidrohr — APPROVED** [review]
This does not solve my problem, that it goes to the endless loop and doesn't find a port.
If I understand correctly, that different behavior is actually for macOS, Linux should have worked with the original version.
In any case, I think this change is legit and in general an improvement, so we should merge it nonetheless.

**Comment by ktf** [comment]
Actually I found a comment in the libuv tests which might explain what is happening:

```
   51   /* 127.0.0.1:<TEST_PORT> is already taken by tcp4_echo_server running in
   52    * another process. uv_tcp_bind() and uv_tcp_connect() should still succeed
   53    * (greatest common denominator across platforms) but the connect callback
   54    * should receive an UV_EADDRINUSE error.
   55    */
```

so I need to handle things also in the callback, apparently, not only in the listen call...

**Comment by ktf** [comment]
@davidrohr the full-system-test dies while trying to change the ulimit:

```
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5432-1/share/scripts/jobutils.sh: line 48: 12239 Killed                  eval ${finalcommand} >> ${logfile} 2>&1
Running: TIME="#walltime %e" /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5432-1/share/scripts/monitor-mem.sh /usr/bin/time --output=reco_ASYNC.log_time './reco_ASYNC.log_tmp.sh'
/usr/bin/time --output=reco_ASYNC.log_time ./reco_ASYNC.log_tmp.sh
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5432-1/prodtests/full-system-test/setenv.sh: line 4: ulimit: max locked memory: cannot modify limit: Operation not permitted
```

do you really need it?

**Comment by davidrohr** [comment]
@ktf : This is weird. The `ulimit -m` is required only for the GPU backend.
I have fixed that already in dev. And actually in the other PRs the full system test runs through.
I am wondering why it fails just here?
Do you perhaps need to rebase to dev? But the CI should do that itself?

**Comment by davidrohr** [comment]
@ktf : You were right, there was a typo, fixed in #5465 (still don't understand why it worked in other PRs).

**Comment by ktf** [comment]
This is in any case a good idea. Merging.

**Pull request merged**
