### PR TITLE
HistogramRegistry: allow compile-time hashing of hist names

### PR DESCRIPTION
**Pull request by mario-krueger**

### CODE REVIEW

**Comment by mario-krueger** [comment]
@ktf could it work like this?

**Comment by mario-krueger** [comment]
I guess however for Nicolos use case with flexible names this will anyhow be still evaluated at runtime.

**Comment by jgrosseo** [comment]
@njacazio I think we should constexpr these strings...

**Comment by njacazio** [comment]
Hi, all right, I will open a PR on @mkruegerGitHub later today

**Comment by mario-krueger** [comment]
We will probably have to provide some helper functions to do the compile-time string concaternation. I dont think this will work out of the box.

**Comment by jgrosseo** [comment]
I am questioning the need to have the names in a non-constexpr array. I am confident there is a better solution with similar flexibility.
We should not give examples of use cases where string operations are made per fill.

**Comment by jgrosseo** [comment]
Is there a way to enforce that the strings are known at compile time? By defining the function in the histogram manager such that it complains if the string is not constexpr?

**Comment by mario-krueger** [comment]
It seems like the only way to actually calculate the hash at compile-time and propagate this to the fill function is to explicitly create a constexpr HistName object and pass this as an argument.
When creating the HistName implicitly by just passing a string to the fill function, the compiler will still create the objec at runtime in any case (constexpr-ing the strings wont help here).
If one wants to have arrays of histogram names, it can be done like this: 
     static constexpr HistName histNames[] = {"x", "xy"};
With the implementation I have committed now, all will still work as before (hashing at runtime and per fill), but we at least have the option to do it also at compile-time (requiring some more ‘effort’ by the analyzer).
It is a bit unfortunate that there seems to be no ‘nice’ way to have this feature, but I guess we will have to live with that.

**Comment by jgrosseo** [comment]
It is fine with me to merge this. But if the usual string hashing it at run time, we have to seriously think about the interface. People will make mistakes, and this reduces the performance a lot. In my code the fill is now called in a triple loop...

**Comment by mario-krueger** [comment]
an alternative would be to do it like this:
https://github.com/mkruegerGitHub/AliceO2/commit/4f7eaa8c1cef453e726dca0580c9c730e84480b0
However, then we cannot store multiple names in an array....

**Comment by mario-krueger** [comment]
we could also use boost::hana:
https://github.com/mkruegerGitHub/AliceO2/commit/47239e6b3eb874e5bb4edf71d58e830a0c5d8b42
the user will not have to do much (just add a literal suffix '_s' to his string) and it will be only evaluated at compiletime

**Comment by jgrosseo** [comment]
Very nice! Can we fail at compile time if the string cannot be evaluated at compile time?

**Comment by mario-krueger** [comment]
with the boost::hana strings it will compile only with the 'compile-time strings' since the letters will be part of the type and therefore must be known during compilation

**Comment by jgrosseo** [comment]
Sure. I understand.

I am asking if we can cause a compilation error if somebody provides a standard string and not a hana string to the function.

**Comment by mario-krueger** [comment]
well in that case it will fail with:
```
error: constexpr variable 'histName' must be initialized by a constant expression
  static constexpr ConstHistName histName{hanaStr};
```
which I think is already quiet clear. 
But we can probably also do some static_assert magic and provide another custom error message.

**Comment by jgrosseo** [comment]
Thanks. This is perfectly fine.

**Comment by mario-krueger** [comment]
Ok I just checked. It is easy to put there a static assert with custom message (see updated code in the previous link).
So if nothing speaks against using boost::hana I can try to implement it in the registry. If you agree I will put this in a separate PR (after this one is merged). Then it is easier to retrace what was changed.

**Comment by ktf** [comment]
I am against using boost::hana, do you really need it? Can't we simply replicate the functionality we need? It will bloat compile time / compile memory even more wrt what we have now.

**Comment by mario-krueger** [comment]
Sure. I guess in the end what we need is only a few lines of code (something like in https://github.com/mkruegerGitHub/AliceO2/commit/4f7eaa8c1cef453e726dca0580c9c730e84480b0). The only thing that hana adds here in terms of functionality is the user defined literal.

**Comment by mario-krueger** [comment]
We could do it like this:
https://github.com/mkruegerGitHub/AliceO2/commit/7327c79bc5fd4269c27723312197c72e6ecc17a0
It seems that the template string literals (that are used also in boost::hana) is not strictly standard:
```
warning: string literal operator templates are a GNU extension [-Wgnu-string-literal-operator-template]
```
But according to the hana doc this is supported by both Clang and GCC.
Could we live with that? Otherwise we would probably have to use precompiler macros (then it would look like this: https://github.com/mkruegerGitHub/AliceO2/commit/f5f6f9ef0f340054567b5020f82e67dd90804e30).

**Pull request closed without merging**
