### PR TITLE
Allow skipping MC in MID ditis reader and do this in DigitsToRawWorkflow

### PR DESCRIPTION
**Pull request by shahor02**
@dstocco I've added to DigitReaderSpec an option to skip MC labels (default is to read them) and hardcoded it to false in its invocation in digits->raw converter.

### CODE REVIEW

**Comment by davidrohr** [comment]
@shahor02 : Thx, this works for the MC part, and is basically what I was trying myself, so I can think this can be merged.

For running the workflow, your commands on https://alice.its.cern.ch/jira/browse/O2-1492# work. When I was trying it I missed to use the `fwmugen` but I was just using the normal generator. I just tried this in a small test, and indeed it yields a segfault. I assume there is a problem with empty data or so. Could you try:
```
o2-sim -g pythia8 -m MID -n 10
o2-sim-digitizer-workflow --disable-mc
o2-mid-digits-to-raw-workflow --mid-raw-outdir raw/MID --mid-raw-perlink  --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0"
o2-raw-file-reader-workflow --input-conf raw/MID/MIDraw.cfg |  o2-mid-reco-workflow  |  o2-mid-entropy-encoder-workflow
```

For the full system test, shall I just run the muon simulation and digitization independently and then merge it together into a timeframe by copying together the raw files, or is there a proper way to simulate a timeframe with related data in the barrel and the forward part?

**Comment by shahor02** [comment]
@davidrohr for the seg.fault: in fact it was a general problem: for very small (a few bytes) messages the rans underestimates the required output buffer size. Added a fixed margin in https://github.com/AliceO2Group/AliceO2/pull/4681, should cover all such cases.

For the MID simulation in the full test: I would use whatever comes out from the pythia8hi unless @dstocco or @aphecetche think that its contribution to Muon is grossly underestimated.

**Comment by davidrohr** [comment]
@shahor02 @dstocco : Could you also add a --disable-root-output option to disable the track writer?

**Comment by dstocco** [comment]
Hi @davidrohr ,
yes, I'm working on it. It is taking a little bit of time because I do not simply want to add a `--disable-root-output`, but I'm rather working to separate the workflow. The idea is to split the `o2-mid-reco-workflow` into something to produce the digits (different commands if we start from raw data, MC digits, or CTF), and a part to run the reconstruction..
So the command above will be replaced by something like:

`o2-raw-file-reader-workflow --input-conf raw/MID/MIDraw.cfg |  o2-mid-raw-to-digits  |  o2-mid-entropy-encoder-workflow`

And for the MID reco I'll have: `digits-to-tracks` instead....

I'm testing the code: I hope I can perform a PR by the end of this week.
Cheers,
Diego

**Comment by shahor02** [comment]
Hi @dstocco 

In case you missed: I've already added this option: https://github.com/AliceO2Group/AliceO2/pull/4682
It is ok to create separate ``2-mid-raw-to-digits``, but all detectors (should) support possibility to pipe workflows w/o creating intermediated root files.

Cheers,
 Ruben

**Comment by dstocco** [comment]
Hi @shahor02 ,
sorry, I think I missed the PR. 
Fine for me, but when I'll split the workflow I plan to remove the file `RecoWorkflow` that you modified...unless of course the detectors must provide one single workflow that goes from are data to final files...
Cheers,
Diego

**Pull request merged**
