### PR TITLE
TPC: Add missing TF dependent ccdb update

### PR DESCRIPTION
**Pull request by wiechula**

### CODE REVIEW

**Comment by shahor02** [comment]
@wiechula is this needed for the YETS processing?

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

I also asked Jens on Mattermost, he said it is not crucial, since we ran without it till now, and possibly in January we will redo the apass1. I will anyway take it when merged. But a new tag will be done only if we understand the other issue with CCDB we discussed today.

Chiara

**Comment by davidrohr** [comment]
@wiechula : The gpu-reconstruction assumes that calib objects of the clusterization do not change. I see you changed the `PADGAINRESIDUAL`. is this the gain map used for the clusterizer, or only a residual map used during dEdx?

**Comment by wiechula** [comment]
@davidrohr , the cluster finder uses `PADGAINFULL`. The residual is only used in `dE/dx`.

**Comment by wiechula** [comment]
The errors look unrelated. From my side this can be merged.

**Pull request merged**
