### PR TITLE
DPL: Use exceptions not log messages for badly formatted messages

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
IIRC, the default behavior is to catch the exception and move to the next timeframe. I can check it.

**Comment by sawenzel** [comment]
There is a merge conflict here. Is this PR still to be merged?

**Comment by ktf** [comment]
Yeah, it's just fallout from the `clang-format` work. I've fixed the conflict and if it works I would merge it.

**Comment by davidrohr** [comment]
The conflict is solved and tests are passed. How about we fix the clang-format thing and merge it?

**Comment by ktf** [comment]
Superseded by #2460.

**Pull request closed without merging**
