### PR TITLE
DPL: improve rate limit

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo. Once this is merged, you should be able to control rate limiting with the `--aod-memory-rate-limit VALUE` option. Default is not to have any limit as it is now. It will do its best to keep memory consumption between `VALUE` and `1/3*VALUE`.

**Comment by ktf** [comment]
@aalkin could you review the logic?

**Comment by jgrosseo** [comment]
> 
> 
> @jgrosseo. Once this is merged, you should be able to control rate limiting with the `--aod-memory-rate-limit VALUE` option. Default is not to have any limit as it is now. It will do its best to keep memory consumption between `VALUE` and `1/3*VALUE`.

So this is memory consumption in bytes? 
Shouldn't we put this identical to the shared memory limit? 
Or does this only contain the tables read from the initial file (and not the ones produced on the way)? 
What else is in the shared memory?

**Comment by ktf** [comment]
Yes, VALUE is in bytes. In principle it needs to be lower, if you want to stay within the shared memory limits, because you want that `limit + size of the last timeframe + size of the in flight histograms < segment size`.
All the in fly arrow tables are accounted.

**Pull request merged**
