### PR TITLE
Global offsets and reco QC

### PR DESCRIPTION
**Pull request by AllaMaevskaya**

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
What is wrong here? Could it be merged?

**Review by mslupeck — APPROVED** [review]

**Comment by mslupeck** [comment]
HI @shahor02, could you have a look here and merge if possible?

**Comment by shahor02** [comment]
Hi, before merging: what is the role of the recoQC? Is not it supposed to be in the QualityControl ?

**Comment by AllaMaevskaya** [comment]
Hello
it should be in QC, but I did not find QC for reconstructed data after synch reconstruction. I will add it in QC later

**Pull request merged**
