### PR TITLE
add a reco option to initialize the TPC transformation from the file

### PR DESCRIPTION
**Pull request by sgorbuno**

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf @sawenzel @ihrivnac : There is again a random framework test failure, that breaks this PR. I am sure, if we just rerun the CI, this will suceed, but overall, this is pretty annoying.

How about we repeat each O2 test 3 times in case of failures (we already repeat some tests 2 times). It will not increase the CI time, because most test will anyway succeed in the first attempt. But it shold reduce such false errors significantly. We should discuss this in the next WP3 meeting.

**Comment by ktf** [comment]
Do you have the logs?

**Comment by davidrohr** [comment]
ah, unfortunately not, sorry, will save them next time.

**Comment by ihrivnac** [comment]
Hi @davidrohr ,
Could you, please, add the proposal for repeating the O2 test when it fails to the WP3 meeting 19/09 document? Its is already available in the indico.
Thank you,

**Comment by davidrohr** [comment]
@ktf : Attached a log from a randomly failing framework test: 
[fullLog.txt.tar.gz](https://github.com/AliceO2Group/AliceO2/files/3612699/fullLog.txt.tar.gz)

@ihrivnac : done

**Pull request merged**
