### PR TITLE
Hide MID decoder implementation details

### PR DESCRIPTION
**Pull request by dstocco**
This allows to chose the decoder at run-time, depending on the data header

### CODE REVIEW

**Comment by dstocco** [comment]
Hi @Barthelemy , all,
the PR modifies the function to generate the RawDecoderSpec, which is used in the QC. So, it will indeed break QC compilation. The fix is trivial, but how should I synchronise the QC and O2 repositories?

**Comment by Barthelemy** [comment]
@dstocco Is there any way to provide backward compatible synonyms / overloaded methods ? just to prevent the failure in QC and then you update QC ?

**Comment by dstocco** [comment]
Hi @Barthelemy ,
sure, I was thinking about this solution: just wanted to know if it was the correct way to proceed before going on.
Will do it and, once the PR is pushed, I will modify QC and, after, cleanup O2 with another PR.

**Comment by Barthelemy** [comment]
That's the way !

**Comment by dstocco** [comment]
@Barthelemy in the end I managed in keeping the old method. The meaning of the boolean argument of the method changed...but the value is the same, and everything is conceptually coherent, so we do not really need to change the QC, nor to amend O2 later on.

**Comment by Barthelemy** [comment]
ok thank you

**Review by aphecetche — APPROVED** [review]

**Pull request merged**
