### PR TITLE
fix in tof geo indexing initialization

### PR DESCRIPTION
**Pull request by noferini**
urgent to fix memory leak affecting also QC

### CODE REVIEW

**Comment by noferini** [comment]
@njacazio @shahor02 @davidrohr @chiarazampolli

**Comment by shahor02** [comment]
can you do clang-format ?

**Comment by noferini** [comment]
> can you do clang-format ?
Done. I still compiling but if one check passes I would propose to merge

**Comment by chiarazampolli** [comment]
Mine https://github.com/AliceO2Group/AliceO2/pull/7303 (now closed) is exactly the same, and it compiled fine.

**Comment by shahor02** [comment]
merging to have it in the nightly

**Pull request merged**
