### PR TITLE
AOD stores tracks parameters at calorimeters

### PR DESCRIPTION
**Pull request by shahor02**
@mfasDa @peressounko 

Please check. What it does is:
1) propagates tracks to emcal/dcal X = 440 cm in the proper sector
2) if not in the sector occupied by emcal/dcal (phos) or |eta_position|>0.75 
3) if in the sector with phos AND eta_pos (at emcal X) < 0.178266f (i.e. the mean between the dcal and phos acceptance, @peressounko note that this corresponds to 82.4 cm instead of 83cm you asked), then propagate to phos X=460.

If not failed on any of the previous stages, assigns position eta and phi to already existing trackEta parameters fTrackEtaEMCAL and fTrackPhiEMCAL. Otherwise -999 is assigned to both parameters.

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 @davidrohr @sawenzel all the PRs are now failing with:

```
[378:TPCDigitizer_9]: [23:18:34][INFO] TPC: Flushed 7613 digits, 8512 labels and 64 common mode entries
[ERROR] pid 363 (TPCDigitizer_0) crashed with 128
[ERROR] pid 364 (TPCDigitizer_1) crashed with 128
```

in the fullCI. Do you have any idea of what is going on?

**Comment by shahor02** [comment]
Yes, I've seen this but could not reproduce it locally. I asked @sawenzel , he thinks might be resource problem. 
We have this situation since ~1 week, initially some PRs were passing fullCI, now they seem to fail at 100% (always in TPC digitization).

**Comment by ktf** [comment]
I can confirm they get killed by the OOM reaper. Not yet sure why. Maybe related to the increase we also see with some analysis tasks? Did anything particularly relevant change in the last few days?

**Comment by peressounko** [comment]
Dear @shahor02, approach looks reasonable, will test on real/MC AODs once will be committed.

**Comment by mfasDa** [comment]
One thing a bit unfortunate is that the detectors use different radii for propagation (PHOS 460 cm, EMCAL 440 cm). In the overlap region between DCAL and PHOS how can we figure out which track was propagated to which detector?

**Comment by shahor02** [comment]
> One thing a bit unfortunate is that the detectors use different radii for propagation (PHOS 460 cm, EMCAL 440 cm). In the overlap region between DCAL and PHOS how can we figure out which track was propagated to which detector?

The `eta` almost does not change on propagation and there is a good margin to both detectors' acceptance. But, if you want, I can add e.g. 10 to eta in case of propagation to the PHOS.

**Comment by mfasDa** [comment]
> > One thing a bit unfortunate is that the detectors use different radii for propagation (PHOS 460 cm, EMCAL 440 cm). In the overlap region between DCAL and PHOS how can we figure out which track was propagated to which detector?
> 
> The `eta` almost does not change on propagation and there is a good margin to both detectors' acceptance. But, if you want, I can add e.g. 10 to eta in case of propagation to the PHOS.

For the eta I was expecting this, and we can deal here with the eta cut in the correction task as you applied in the track extrapolation. I was more worried about the the two small DCAL supermodules in case the tracks are sufficiently curved. However the effect here is probably small.

**Comment by peressounko** [comment]
Hi @mfasDa @shahor02, one indeed can imagine strongly curved tracks with |eta|<0.1 which will hit both DCal and PHOS. I think, one then should select candidate tracks extrapolated to some radii e.g. 440 with loose cuts and extrapolate once more to a calorimeter under study?

**Comment by shahor02** [comment]
Such tracks are certainly possible but most of such tracks are the secondaries created in the TPC and only a fraction of them will be reconstructible in the TPC. If they are matched in TRD or TOF, then one can trust more or less their eta (though such matches will have a lot of fakes), if they are not matched (and low-pT tracks usually do not produce TRD tracklets) then the time/Z assignment of such tracks is purely conventional so their tagging for being in the EMCAL/PHOS acceptance is anyway random.
Given this irreducible uncertainty, not sure the identification of a small fraction of low-energy tracks hitting both detectors is relevant.

**Comment by shahor02** [comment]
@mfasDa thanks for spotting the problem with the sector definition, there are too many misleading pictures around... Fixed.

**Comment by shahor02** [comment]
@peressounko @mfasDa shall I merge this?

**Review by peressounko — APPROVED** [review]
Looks fine, lets test with real data and MC

**Comment by mfasDa** [comment]
Hi @shahor02 , I am also fine with merging!

**Pull request merged**
