### PR TITLE
CPV: remove padding data in RawDecoder.cxx

### PR DESCRIPTION
**Pull request by sevdokim**
Hello! This is fix of RawDecoder.cxx which detects padding data and does not consider it as unknown word.

### CODE REVIEW

**Review by kharlov — APPROVED** [review]

**Comment by shahor02** [comment]
Hi @sevdokim 
thanks, did you try it with 532819 ?

**Comment by sevdokim** [comment]
Hi @shahor02 
No I didn't try it with 532819. Is it some saved data? Where is it stored? I want to try but need some tip how to do it.

**Comment by shahor02** [comment]
Hi @sevdokim 
here are the files which produced the errors I've reported:
```
/alice/data/2023/LHC23a/532819/raw/1120/o2_rawtf_run00532819_tf00000001_epn158.tf
/alice/data/2023/LHC23a/532819/raw/1120/o2_rawtf_run00532819_tf00000005_epn215.tf
/alice/data/2023/LHC23a/532819/raw/1120/o2_rawtf_run00532819_tf00000017_epn083.tf
/alice/data/2023/LHC23a/532819/raw/1120/o2_rawtf_run00532819_tf00000074_epn019.tf
/alice/data/2023/LHC23a/532819/raw/1120/o2_rawtf_run00532819_tf00000080_epn146.tf
...
```
Just run e.g.
```
o2-raw-tf-reader-workflow --onlyDet CPV --raw-only-det CPV --input-data /alice/data/2023/LHC23a/532819/raw/1120/o2_rawtf_run00532819_tf00000001_epn158.tf | o2-cpv-reco-workflow ...
```

**Comment by sevdokim** [comment]
hi @shahor02 
thanks for the hint! I checked /alice/data/2023/LHC23a/532819/raw/1120/o2_rawtf_run00532819_tf00000001_epn158.tf and there were no error messages. So the problem with previous commit was no detection of padding 80-bits words which is solved in this commit.

**Pull request merged**
