### PR TITLE
[WIP] Add TRD Pulse Height

### PR DESCRIPTION
**Pull request by maroozm**
Moving  creation of the pulse height spectra from QC into O2, such that
a) we avoid the sampling of digits and get more statistics in the plots
b) the PH plots can be used downstream for example for the T0 calibration
This is  a work in progress on top of the basic structure https://github.com/martenole/AliceO2/tree/trd-ph created by @martenole 

- [x] move the algorithm for creating the PH plot from QC into PulseHeight::process()
- [ ] add a writer to write the output to a file
- [ ] initialization and reset methods (if needed, depending on the output type chosen)

### CODE REVIEW

**Comment by martenole** [comment]
Hi Salman,
thanks a lot for opening this PR. I realized that a) there are some conflicts after we merged the gain calibration and b) it is much simpler for me to review your changes if I add the skeleton PH task first.
So I will update https://github.com/AliceO2Group/AliceO2/pull/11485 and merge it and then you can open a regular PR to O2 with your additional changes on top. I hope that is OK.
Cheers,
Ole

**Comment by maroozm** [comment]
Hi Ole, thanks for checking. no problem. I will open a new PR after it gets merged.

**Comment by martenole** [comment]
> Hi Ole, thanks for checking. no problem. I will open a new PR after it gets merged.

Hi @maroozm I have merged my PR now. Could you please rebase your branch on dev? There should be no need for creating a new PR. Thanks

**Comment by martenole** [comment]
Thanks @maroozm but now your git history is not clean. You should arrive at a single commit on top of `dev`. For that you can do:
```
git branch tmp maroozm/dev && git checkout tmp
git reset --soft origin/dev
# remove changes in Detectors/TRD/workflow/CMakeLists.txt, since you just added an empty line which is not needed
git commit -m "Add PH processing"
git checkout mazroozm/dev
git reset --hard tmp
git push -f
```
Note that it is in general a good idea to create a branch with a different name than dev for your work. I am assuming that your local branch on which you work is called `maroozm/dev` and that the upstream repository is called `origin`. Please adjust if they differ.

**Comment by maroozm** [comment]
> Thanks @maroozm but now your git history is not clean. You should arrive at a single commit on top of `dev`. For that you can do:
> 
> ```
> git branch tmp maroozm/dev && git checkout tmp
> git reset --soft origin/dev
> # remove changes in Detectors/TRD/workflow/CMakeLists.txt, since you just added an empty line which is not needed
> git commit -m "Add PH processing"
> git checkout mazroozm/dev
> git reset --hard tmp
> git push -f
> ```
> 
> Note that it is in general a good idea to create a branch with a different name than dev for your work. I am assuming that your local branch on which you work is called `maroozm/dev` and that the upstream repository is called `origin`. Please adjust if they differ.

Hi @martenole, Thanks for the help. I removed the empty line, and pushed it here. and for this PR, i think i have to keep working on the dev branch?

**Pull request closed without merging**
