### PR TITLE
Add support for bitmap in ROFRecords

### PR DESCRIPTION
**Pull request by mconcas**
@shahor02 : I am still testing to see if it actually works.
The logic would be to tag the ROFRecords for seeding vertices in any case with corresponding two bits (first iteration, upc iteration). Then tag the tracks ROFs if we found tracks there.
If you believe, I can tag only the track ones using vertices flags and any filtering can be done on a later analysis.

### CODE REVIEW

**Comment by shahor02** [comment]
@mconcas if you want, you can set it first to the vertices rofrecord vector than copy it to track's rofrecords, but only the latter is loaded in the AODProducer.

**Comment by mconcas** [comment]
> @mconcas if you want, you can set it first to the vertices rofrecord vector than copy it to track's rofrecords, but only the latter is loaded in the AODProducer.

Ah true, I would then just keep this logic just to save one extra iteration on the vertices.

**Comment by mconcas** [comment]
Screenshot from 2024-08-15 00-15-44
In red: bits related to the tracks ROFRecord
In blue: bits related to vert ROFRecord

- if bit==0: no vertices -> no tracks
- if bit==1 -> value==2 -> vertices from first iterations, tracks from the first iteration
- if bit==2 -> value==4 -> vertices from UPC iteration, tracks from UPC iteration

as there can be vertices with no tracks (mostly UPC ones!), red is different than blue and there are more empty ROFs

**Review by shahor02 — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Label removed, PR is in async-v1-01-16.

**Pull request merged**
