### PR TITLE
Update of  TPC reco workflow

### PR DESCRIPTION
**Pull request by matthiasrichter**
This update inludes
- support for output type `clusters`, adding writer for simulated clusters and corresponding reader spec
to run reco with input type `clusters`
- support for multiple output types in order to keep the data at different stages of the reconstruction and write these to files
- cleanup of the track writer spec, now based on generic tool MakeRootTreeWriterSpec generator
https://alice.its.cern.ch/jira/browse/O2-400
- definition of the parallel processing lanes based on the DPL helpers for defining parallelism
- the tpc sector configuration is now workflow option rather than an option of the digit publisher because it is needed in different processor specs
- a bugfix TPC digit reader spec: correctly filling the processing lanes, the workflow ran out of sync if the number of sectors to be processed was not a multiple of the number of lanes
https://alice.its.cern.ch/jira/browse/O2-399
- updated documentation

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@dennisklein @dberzano for the macos CI it looks like a unit test of the FairMQ package fails, and the O2 compilation is not even done. Could you please have a look/do you have an idea why the unit test is failing?
```
The following tests FAILED:
	 12 - FairMQ.Poller (Timeout)
```

**Comment by dennisklein** [comment]
Sry for the late reply. Can you run `ctest -V -R 'FairMQ.Poller'` and send me the log?

**Comment by matthiasrichter** [comment]
@dberzano , lets add `--output-on-failure` to fairmq ctest invocation
https://github.com/alisw/alidist/pull/1418

**Comment by matthiasrichter** [comment]
@dennisklein you can now find the log output for the failing test in the log of the macos CI

The only thing I can see is this
```
[POLLOUT][11:58:14][DEBUG] Could not bind to configured (TCP) port, trying random port in range 22000-32000
[POLLOUT][11:58:14][DEBUG] Attached channel data1[0] to tcp://127.0.0.1:23129 (bind) (push)
```
while the test seems to use fixed ports starting from 6000. I'm suspecting this to be the problem.
Has the `FairMQ.Poller` test recently been added? Can the test be changed to handle the dynamic port assignment?

**Comment by dennisklein** [comment]
Regarding the timeout I created an issue FairRootGroup/FairMQ#126 to include @rbx. The detailed logs are not conclusive and we need to check on a Mac (which I don't have at hand at the moment).

**Comment by matthiasrichter** [comment]
@dennisklein do you think something can be done to handle the ports dynamically? Otherwise it does not make much sense to use these unit tests in continuous integration.

The problem is quite clear, one device connects to port 6000, while the other one tries to bind, but since this fails, it binds dynamically to another one.
```
[POLLIN][08:30:56][DEBUG] Attached channel data1[0] to tcp://127.0.0.1:6000 (connect) (pull)
[POLLIN][08:30:56][DEBUG] Validating channel 'data2[0]'... VALID
[POLLIN][08:30:56][DEBUG] Created socket pollin_zeromq.data2[0].pull
[POLLOUT][08:30:56][DEBUG] Created socket pollout_zeromq.data1[0].push
[POLLIN][08:30:56][DEBUG] Attached channel data2[0] to tcp://127.0.0.1:6001 (connect) (pull)
[POLLOUT][08:30:56][DEBUG] Could not bind to configured (TCP) port (tcp://127.0.0.1:6000), trying random port in range 22000-23000
[POLLOUT][08:30:56][DEBUG] Attached channel data1[0] to tcp://127.0.0.1:22082 (bind) (push)
[POLLOUT][08:30:56][DEBUG] Validating channel 'data2[0]'... VALID
[POLLOUT][08:30:56][DEBUG] Created socket pollout_zeromq.data2[0].push
[POLLOUT][08:30:56][DEBUG] Attached channel data2[0] to tcp://127.0.0.1:6001 (bind) (push)
```
In principle it concerns most of the tests. many test are even using the same ports, so one might run into trouble if the tests are executed in parallel.

**Comment by dennisklein** [comment]
I have just met @dberzano in the coffee break and we agreed on disabling the test suites in the CI builds. We will probably revert, once the test suites got more robust. But currently, they are too disruptive and we don't see any interesting errors.

**Comment by dberzano** [comment]
For the record this is done in alisw/alidist#1421

**Pull request merged**
