### PR TITLE
TOF CTF: first prototype

### PR DESCRIPTION
**Pull request by noferini**
A first prototype of TOF CTF is provided.
digit->CTF and viceversa implemented and tested:
o2-tof-reco-workflow -b --output-type ctf|o2-ctf-writer-workflow -b --onlyDet TOF
o2-ctf-reader-workflow -b --ctf-input o2_ctf_0000000000.root |o2-tof-reco-workflow -b --input-type ctf --output-type digits

Currently TOF CTF size too large and needs optimization BUT this PR is needed to continue the work (since changes in digit structure are required to run on the grid pbpb)

### CODE REVIEW

**Comment by noferini** [comment]
I did a test with 500 Pbpb (TOF only in sim)  events@50 kHz (I cannot do the same with pp since I cannor run with IR > 50 kHz).
N digits = 595404
tofdigits.root (no MC) --> 3.05 MB
o2_ctf_0000000000.root --> 1.99 MB
Reduction = -35%

**Comment by shahor02** [comment]
@noferini thanks for the numbers but at the moment they are too pessimistic: in the CTF which I've created when debugging previous version the dictionary was at least as large as the payload. Eventually it will be factored out.

**Comment by shahor02** [comment]
@noferini just to not forget: could you provide (after your vacation, surely, it is not urgent) a unit test for TOF CTF encoding/decoding, like those in https://github.com/AliceO2Group/AliceO2/tree/dev/Detectors/CTF/test ?

**Comment by noferini** [comment]
Yes, I'll do.


Cheers


Francesco




Ottieni Outlook per Android







On Fri, Aug 7, 2020 at 3:42 PM +0200, "Ruben Shahoyan" <notifications@github.com> wrote:















@noferini just to not forget: could you provide (after your vacation, surely, it is not urgent) a unit test for TOF CTF encoding/decoding, like those in https://github.com/AliceO2Group/AliceO2/tree/dev/Detectors/CTF/test ?

**Pull request merged**
