### PR TITLE
DPL: introduce CallbacksPolicy

### PR DESCRIPTION
**Pull request by ktf**
Useful to customise which callbacks are set up by default depending on the device type.

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken looks like something in wrong with build/O2/o2 and build/O2/o2-dataflow. Could you have a look?

**Comment by TimoWilken** [comment]
The failures were due to errors cloning git repos. I restarted the slc7 builders to add one for the newly available machine, so they all had to fetch stuff in `sw/MIRROR` again. I've restarted the checks.

**Comment by ktf** [comment]
macos still has troubles. @TimoWilken @MichaelLettrich

**Comment by MichaelLettrich** [comment]
@ktf restarted the builder. should be back now.

**Pull request merged**
