### PR TITLE
DPL: Add initial dummy for synchronous reconstruction

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Obligatory screenshot (using yet to be committed guy changes):

untitled

@shahor02 @davidrohr

**Comment by ktf** [comment]
`clang-format` goes bananas when reformatting the WorkflowSpec, bypassing for now.

**Comment by shahor02** [comment]
Very nice! On my diagram, the data arrows going under the processor boxes are also used by these processors. I.e. the TPC-ITS matching needs not only the output (tracks) from TPC and ITS tracking but also the original clusters. Also it may require the results of the FIT reconstruction.
Idem for ITS-TPC-TRD-TOF matching and TPC SP calibration.

**Comment by ktf** [comment]
I will add the FIT connection, I merely forgot it. For the rest, as discussed privately, the arrows are not one to one to data relationships but merely indicate the path the `buffer ownership token` takes. At the moment this is rather unoptimised, and daisy-chains any parallel usage of data. In the future we can optimise this, however this will be transparent to the `AlgorithmSpec` writer.

**Pull request merged**
