### PR TITLE
New conversion digits - raw

### PR DESCRIPTION
**Pull request by cortesep**
WIP - from new digits format to raw

### CODE REVIEW

**Review by shahor02 — COMMENTED** [review]
@cortesep looks good but you have to apply clang-format to all you commits ``git clang-format HEAD~8``
If this should not be merged soon, please put [WIP] in the beginning of the title, so that it does not run tests in vain.

**Comment by shahor02** [comment]
@cortesep is this ready for review / tests?

**Comment by cortesep** [comment]
> @cortesep is this ready for review / tests?

Hi Ruben. Yes. I removed the WIP.

**Review by shahor02 — CHANGES_REQUESTED** [review]
Hi @cortesep 

For this PR specifically: could you please change the mixture of root types (UInt...) to basic or std::.. types.
I have a comment on https://github.com/AliceO2Group/AliceO2/blob/dafeb541209f69bc38a97fe2d5f84734b2053301/Detectors/ZDC/simulation/src/Digits2Raw.cxx#L308: I don't see where https://github.com/AliceO2Group/AliceO2/blob/dafeb541209f69bc38a97fe2d5f84734b2053301/Detectors/ZDC/simulation/src/Digits2Raw.cxx#L336 is used, probably can be removed.

**Comment by shahor02** [comment]
Closing as was overridden by already merged https://github.com/AliceO2Group/AliceO2/pull/5585

**Pull request closed without merging**
