### PR TITLE
ITS-SV: fix aggressive rounding in determinant

### PR DESCRIPTION
**Pull request by mconcas**

### CODE REVIEW

**Comment by mconcas** [comment]
@shahor02, long story short: the bug was on my side, we couldn't see it before last change to seeding vertexer because these clusters of lines were naturally discarded.

**Comment by mconcas** [comment]
@chiarazampolli, this is indeed a fix we want asap, especially before apass3.

**Comment by shahor02** [comment]
@mconcas thanks, will merge as soon as the CIs are passed

**Review by iouribelikov — DISMISSED** [review]

**Comment by mconcas** [comment]
@shahor02 this is now green, could you just approve it? I would like to see whether I still have permissions to merge PRs on where I am codeowner. Since it looks like I have issues in another pr.

**Review by shahor02 — COMMENTED** [review]
@mconcas done

**Review by shahor02 — APPROVED** [review]

**Comment by mconcas** [comment]
@TimoWilken It looks like I lost the permission to merge PR where I am codeowner of all files.
Could you kindly have a check, please?

**Comment by mconcas** [comment]
> @mconcas done

nevermind, I have same issue here. But I'll fix this in another spot. This can be merged, thanks.

**Pull request merged**
