### PR TITLE
Remove old classes of CCDB 

### PR DESCRIPTION
**Pull request by Barthelemy**
does not compile yet

### CODE REVIEW

**Comment by Barthelemy** [comment]
@wiechula I am trying to remove the old classes from the CCDB package. I see that you used `o2::ccdb::Manager` in the past and I have tried to replace it with `o2::ccdb::BasicCCDBManager` developed by @sawenzel . There is still the test testTPCCCDBInterface that is simply commented out. 

@sawenzel I am not sure how to proceed with testTPCCCDBInterface. BasicCCDBManager does not allow for writing/setting data, right ? and any ways the snaphsot system does not allow to store data , does it ?

**Comment by wiechula** [comment]
@Barthelemy , fine with me. We can adopt the test later. I guess that to some extend I'll need to rework the CDB access anyway. If I understand correctly, the TObjWrapper is not needed any longer. I this correct?
From my side, just go ahead.

**Comment by Barthelemy** [comment]
@wiechula The TObjWrapper is not needed anymore. Ideally I would like to adapt your test, but I need some help from @sawenzel . If it is not doable quickly, I will indeed merge. 
Thanks

**Comment by sawenzel** [comment]
Could you rebase this branch? For some reason there is a conflict. I will try to take a look at the unit test today to complete this PR.

**Comment by Barthelemy** [comment]
That is weird, it was already rebased. I have forced push without the merge commit and it seems to be ok like that.

**Comment by Barthelemy** [comment]
@sawenzel it is ok now

**Comment by Barthelemy** [comment]
@sawenzel it is passing all builds.

**Pull request merged**
