### PR TITLE
[EMCAL-548, EMCAL-614,EMCAL-687,EMCAL-757] Fill EMCAL information in AOD in simulations

### PR DESCRIPTION
**Pull request by mfasDa**
- [EMCAL-614] Set Physics Trigger in case of simulation
- [EMCAL-548] Propagate trigger type fromn digits to cell trigger record
- [EMCAL-757] Add simple publisher workflow for EMCAL cells
- [EMCAL-687, O2-2682] Add EMCAL to the list of allowed detectors

### CODE REVIEW

**Comment by mfasDa** [comment]
Affecting EMCAL-614, EMCAL-687, O2-2682

**Comment by mfasDa** [comment]
Setting WIP label because porting trigger bits was also missing in the cell fitter, will be appended to the PR after local test.

**Comment by mfasDa** [comment]
Removing WIP label - PR is ready to be merged.

**Review by sawenzel — DISMISSED** [review]

**Review by shahor02 — DISMISSED** [review]
Looks fine but let's wait for the fullCI passed before merging

**Review by davidrohr — APPROVED** [review]
FullCI is failing, but apparently all PRs are failing in fullCI in the sim challenge, so not related to this one.
I'd merge it once the o2 CI is through.

**Comment by chiarazampolli** [comment]
Yes, please, we need it for the Min Bias simulation for pp 13.6 TeV data.

**Pull request merged**
