### PR TITLE
DPL: exit immediately when we are idle

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr this works for me and it exits as expected as fast as possible on EoS.

**Comment by davidrohr** [comment]
Ok, I can only test it tomorrow evening. Will teport then.

**Comment by davidrohr** [comment]
@ktf : For me this does not solve the issue with the EoS and the timeout.
I am testing with dev (b732eb1f4df11b9ee868c0b15506cf84fbc396ba) + this PR
Commands are:
```
ARGS_ALL_EXTRA="--completion-policy=wait --exit-transition-timeout 20"  WORKFLOW_DETECTORS=TPC SYNCMODE=1 SHMSIZE=$((16<<30)) EXTINPUT=1 ~/alice/O2/prodtests/full-system-test/dpl-workflow.sh
NTIMEFRAMES=1 TFDELAY=2 ~/alice/O2/prodtests/full-system-test/datadistribution.sh
```

I am starting DD, and then just before DD sends the event, I am pressing the "Restart" button in the Debug GUI for tpc-entropy-encoder.
What I see is that the tpc-entropy-encoder receives the STOP command, and goes into the 20 seconds timeout. But the EoS does not end the timeout. Instead, the timer reaches the 20 seconds, and only then tpc-entropy-encoder goes to READY.

Note that I verified that the EoS is sent correctly by running without `--completion-policy=wait --exit-transition-timeout 20` and without pressing "Restart", and then the DPL chain terminates correctly after receiving the EoS.

Log messages:
```
[2616:tpc-entropy-encoder]: [19:25:24][STATE] INITIALIZING DEVICE ---> INITIALIZED
[2616:tpc-entropy-encoder]: [19:25:24][STATE] INITIALIZED ---> BINDING
[2616:tpc-entropy-encoder]: [19:25:24][STATE] BINDING ---> BOUND
[2616:tpc-entropy-encoder]: [19:25:24][STATE] BOUND ---> CONNECTING
[2616:tpc-entropy-encoder]: [19:25:24][STATE] CONNECTING ---> DEVICE READY
[2616:tpc-entropy-encoder]: [19:25:24][STATE] DEVICE READY ---> INITIALIZING TASK
[2616:tpc-entropy-encoder]: [19:25:24][STATE] INITIALIZING TASK ---> READY
[2616:tpc-entropy-encoder]: [19:25:24][STATE] READY ---> RUNNING
[2616:tpc-entropy-encoder]: [19:25:24][INFO] fair::mq::Device running...
[2616:tpc-entropy-encoder]: [19:25:24][INFO] Correctly handshaken websocket connection.
[2616:tpc-entropy-encoder]: [19:25:32][INFO] New state requested. Waiting for 20 seconds before quitting.
[2616:tpc-entropy-encoder]: [19:25:32][STATE] Transition RUN incoming, but another state transition is already ongoing.
[2616:tpc-entropy-encoder]: [19:25:41][INFO] Estimated output size is 25929071 bytes
[2616:tpc-entropy-encoder]: [19:25:41][INFO] TPC_CTF: 23 blocks, input size: 38893607, output size: 25929071 NDictWords: 0 NDataWords: 3087536 NLiteralWords: 39
[2616:tpc-entropy-encoder]: [19:25:41][INFO] Created encoded data of size 12352320 for TPC in 0.08 s
[2616:tpc-entropy-encoder]: [19:25:41][INFO] TPC Entropy Encoding total timing: Cpu: 8.000e-02 Real: 7.020e-02 s in 1 slots
[2616:tpc-entropy-encoder]: [19:25:52][INFO] Timer expired. Forcing transition to READY
[2616:tpc-entropy-encoder]: [19:25:52][STATE] RUNNING ---> READY
```

And here the time for the EoS by DD:
```
[2022-02-28 19:25:37.278][I] End of stream (EoS) message sent to DPL. eos_id=0 send_ret=192
```

tpc-entropy-encoder shold have received the EoS at 19:25:37, and then after finishing processing the last TF at 19:25:41, it should go to READY. But it waits for the timer to expire at 19:25:52.

**Comment by ktf** [comment]
Ok, I will look at it again tomorrow.

**Comment by ktf** [comment]
Merging this as discussed since in any case it behaves as before in the worst case scenario and it blocks / intertwines with other developments.

**Pull request merged**
