### PR TITLE
[DPL Analysis] [Event mixing] Upgrade event mixing to use BinningPolicy

### PR DESCRIPTION
**Pull request by saganatt**
... and get rid of the additional hash table messing around

### CODE REVIEW

**Comment by ktf** [comment]
@saganatt it looks like some genuine issue...

**Comment by ktf** [comment]
@saganatt it looks like some genuine issue...

**Review by ktf — CHANGES_REQUESTED** [review]
Please fix the compilation issue.

**Comment by saganatt** [comment]
I don't see it now...?

**Comment by ktf** [comment]
Indeed, probably it simply needed a rebuild.

**Pull request merged**
