### PR TITLE
[DPL Analysis] Canonical task names

### PR DESCRIPTION
**Pull request by saganatt**
Hi @ktf, @jgrosseo 
what do you think about canonizing the task names in this way?

### CODE REVIEW

**Comment by ktf** [comment]
Very nice. Let's see if it's constexpr everywhere.

**Comment by jgrosseo** [comment]
I like it :)

**Comment by ktf** [comment]
@saganatt any reason for it to be draft?

**Comment by saganatt** [comment]
> @saganatt any reason for it to be draft?

Nope, just somewhat I thought the rest of tasks won't compile but only today I realized I made it backward-compatible on purpose ;-)

**Comment by saganatt** [comment]
> Very nice. Let's see if it's constexpr everywhere.

I set as many constexpr as possible (testing with GCC 7). We don't need constexpr for ClassName->task-name conversion, do we?

**Comment by saganatt** [comment]
> > @saganatt any reason for it to be draft?
> 
> Nope, just somewhat I thought the rest of tasks won't compile but only today I realized I made it backward-compatible on purpose ;-)

Oops my first intuition was good, it needed change in all analysis tasks.

**Comment by ktf** [comment]
> > Very nice. Let's see if it's constexpr everywhere.
> 
> I set as many constexpr as possible (testing with GCC 7). We don't need constexpr for ClassName->task-name conversion, do we?

No, we don't.

**Review by jgrosseo — DISMISSED** [review]

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
