### PR TITLE
Performance improvement when applying TOF calibrations

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
FullCI failing with
task timeout reached .. killing all processes
not related to this PR

Waiting for tow more checks

**Comment by noferini** [comment]
@shahor02 
we did other changes in this PR.
Now it is stable and you can merge it once the checks are passed (hopefully today since with this changes we will produce LHCC performance plots).

**Comment by noferini** [comment]
@ercolessi

**Comment by noferini** [comment]
Hi Ruben,
just to say that this PR is no longer urgent since I manage to run aliBuild on EPN (I didn't think to that before).
My reconstruction is already running on EPN (12-31) (I will clean up everything tomorrow morning)

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
