### PR TITLE
Adding property SYSTEMINCLUDE_DIRECTORIES to bucket definition

### PR DESCRIPTION
**Pull request by matthiasrichter**
I have introduced a new property for the bucket definition to allow for include directories declared as 'SYSTEM'. That suppresses the warnings from boost again as we had it before.

@rbx @ktf @MohammadAlTurany @Barthelemy could you have a look if this makes sense

### CODE REVIEW

**Comment by matthiasrichter** [comment]
hmm, tried to get more information for the failed Jenkins test, it looks like it failed while cloning the repo

    error: index-pack died of signal 15
    [slc7] fatal: index-pack failed

**Comment by ktf** [comment]
Building again.

**Comment by MohammadAlTurany** [comment]
@matthiasrichter : yes it make sense for me, should we squash the commits on before merging them or you need to commits?

**Comment by matthiasrichter** [comment]
I suggest to have them separately, one is for the tools, the other one is the application of these tools. Thematically two different things

**Pull request merged**
