### PR TITLE
TRD: Add calibration values to the digitizer from the CCDB

### PR DESCRIPTION
**Pull request by jolopezl**
- Removes crash reverted in #2649. 
- ADC spectrum looks better than before, more work is required but is not necessarily related to the CCDB integration.
- Small drift velocities are related to the values fetched from the CCDB, not to the CCDB integration.

### CODE REVIEW

**Comment by sawenzel** [comment]
With an event simulated like this
```
o2-sim -n 1 --seed 1 -g pythia8hi --skipModules ZDC
```
I am still getting very large ADC values (much larger than shown in the meeting today):

digithighadc

Do we want to merge this?

The digitization seems quite a bit faster than before (a lot less digits).

**Comment by sawenzel** [comment]
@tdietel

**Comment by tdietel** [comment]
It looks better than what we currently have, so I would merge it.

It gives Sean more meaningful digits to feed into the TRAPsimulator, so it’s worth to have this publicly available.

**Comment by tdietel** [comment]
Did you look at the distribution of local t (and r,c)?

**Comment by jolopezl** [comment]
> Did you look at the distribution of local t (and r,c)?

Please, have a look and comment. In particular, I would like to know about the number of electrons propagated per hit.

Screen Shot 2019-12-05 at 15 18 24

**Comment by tdietel** [comment]
Hi Jorge,

The locT coordinate peaks at very few points: radiator boundary, cathode 
wire plane, pad plane. If you let all the electrons start at these 
positions, then there will be very high charge depositing in few (one?) 
timebins associated with these positions, and very little everywhere 
else.

A good cross-check would be to histogram the positions (maybe as a 2D 
plot locT vs locC) where the electrons start to drift.

The energy deposition for one tracklet (I know this does not exist for 
the MC hits...) should be distributed over the whole length of the 
tracklet in the chamber. Are you doing anything like this at the moment? 
I really need to take a closer look at the code...

I think AliRoot did not do a clean job at this: there are very few hits 
per chamber (sometimes only 1), which means that we are not using Geant 
to distribute the charge deposition in the chamber. I remember talking 
to Jens Wiechula from the TPC and they use step size of O(mm), i.e. they 
get many more hits along the track.

Can you try to reduce the step-size to something much smaller, e.g. on 
the order of half a time-bin? This would create many more MC hits, but 
the number of electrons should be the same, but they should be 
distributed more equally.

Cheers,
  - Tom.

**Pull request merged**
