### PR TITLE
DPL: automatically subscribe the ccdbBackend to the correct clock

### PR DESCRIPTION
**Pull request by ktf**
* If someone provides the DISTSUBTIMEFRAME message, use it
* If someone provides the analogous for analysis, use it
* If someone requires a timer (and only a timer) use the timer.
* If no one provides the DISTSUBTIMEFRAME message, add it to the
  first device which only gets an enumeration.

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02

**Comment by ktf** [comment]
@shahor02 I understood what you meant by callback now. I've added a new commit to which should handle that automatic adding of the message.

@chiarazampolli this is the development I was referring about in the meeting.

**Comment by ktf** [comment]
@shahor02 @sawenzel do you understand if the issues in sim_challenge are actually related to the PR or simply missing objects in CCDB?

**Comment by ktf** [comment]
@shahor02 @sawenzel do you understand if the issues in sim_challenge are actually related to the PR or simply missing objects in CCDB?

**Comment by shahor02** [comment]
> @shahor02 @sawenzel do you understand if the issues in sim_challenge are actually related to the PR or simply missing objects in CCDB?

Analysis tries to access an object with non-existing URL `Analysis/PID/TPC/Response`, pinging to @njacazio and @AnnalenaKa

**Comment by ktf** [comment]
Merging this. We can make the extra fixes separately if needed.

**Comment by shahor02** [comment]
This RP has also clang-format problems. Also, see this comment: https://github.com/AliceO2Group/AliceO2/pull/8305#issuecomment-1063333191, not sure if this PR causes this.

**Comment by njacazio** [comment]
> > @shahor02 @sawenzel do you understand if the issues in sim_challenge are actually related to the PR or simply missing objects in CCDB?
> 
> Analysis tries to access an object with non-existing URL `Analysis/PID/TPC/Response`, pinging to @njacazio and @AnnalenaKa

Hi @shahor02 indeed the parameters are not there, this is not intended we will correct this ASAP

**Comment by ktf** [comment]
@shahor02 don't you simply lack a "final" ?

**Pull request merged**
