### PR TITLE
DPL: account for the case in which outputs are not user created

### PR DESCRIPTION
**Pull request by ktf**
DPL: account for the case in which outputs are not user created

### CODE REVIEW

**Comment by ktf** [comment]
@martenole this should handle the cornercase missing in #12539

**Comment by ktf** [comment]
Tested by ole and currently broken. Merging.

**Comment by martenole** [comment]
Thanks a lot @ktf I can confirm that this fixes all bogus errors during running. But for the last timeslice I still see errors :/ Not sure if this is the end of stream message causing confusion? For example from the readout-proxy I see all raw data + the FLP/DISTSUBTIMEFRAME/0 and the FLP/DISTSUBTIMEFRAME/52443 messages missing:
```
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data FLP/DISTSUBTIMEFRAME/52443 was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data HMP/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data FLP/DISTSUBTIMEFRAME/0 was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data MID/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data CTP/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data TOF/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data MFT/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data MCH/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data PHS/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data TRD/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data CPV/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data FDD/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data FT0/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data FV0/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data ZDC/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data TPC/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data ITS/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
output_0.log:[3534726:readout-proxy]: [15:11:38][ERROR] Expected Lifetime::Timeframe data EMC/RAWDATA was not created for timeslice 100 and might result in dropped timeframes
```

**Comment by martenole** [comment]
With enabled metrics I see that the errors indeed come at eos now. As below, 10 time slices are processed OK and on number 11 (timeslice:10, here we start counting at zero) the eos arrives and then no lifetime::timeframe data is created as expected.
```
[3561688:readout-proxy]: [15:23:47][INFO] Done processing timeslice:9, tfCounter:19, firstTForbit:0, runNumber:0, creation:1550600800000, action:0, wall:9999865614
[3561688:readout-proxy]: [15:23:47][INFO] Processing timeslice:10, tfCounter:10, firstTForbit:0, runNumber:0, creation:9223372039902795367, action:0
[3561688:readout-proxy]: [15:23:52][INFO] Received (on channel 0) 1 end-of-stream from 1 peers, forwarding end-of-stream (shouldstop 0, nEos 1, newRun 0)
[3561688:readout-proxy]: [15:23:52][INFO] Done processing timeslice:10, tfCounter:0, firstTForbit:0, runNumber:0, creation:1550600800000, action:0, wall:4942292345
[3561688:readout-proxy]: [15:23:52][ERROR] Expected Lifetime::Timeframe data FLP/DISTSUBTIMEFRAME/52443 was not created for timeslice 10 and might result in dropped timeframes
```

**Comment by ktf** [comment]
I need to check. Indeed we should not send the automated CCDB messages at EoS. I am not sure if this is some old behaviour which is now spotted, or if the changes in #12539 is what triggers it.

**Comment by martenole** [comment]
I don't think its the CCDB message. As I wrote above I see the message `FLP/DISTSUBTIMEFRAME/52443 ` in the list of missing data for the EoS message. Is there something else which is sent at EoS maybe?

**Pull request merged**
