### PR TITLE
QC: disable compilation of old QC

### PR DESCRIPTION
**Pull request by ktf**
This is being replaced by the new, DPL-enabled, version.

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy this is what you meant, correct?

**Comment by Barthelemy** [comment]
yes

**Comment by Barthelemy** [comment]
failing tests don't seem related

**Comment by matthiasrichter** [comment]
Should we probably start moving code to a legacy folder?

**Comment by ktf** [comment]
Or simply remove it? In the end that's what git is for...

**Pull request merged**
