### PR TITLE
DPL: dump metrics every three minutes if enabled

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ironMann:

I see a bunch of errors about:

```
                 from /mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/include/spdlog/async.h:17,
                 from /mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/src/stdout_sinks.cpp:11:
/mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/include/spdlog/logger.h: In member function 'void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, const FormatString&, Args&& ...)':
/mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/include/spdlog/logger.h:344:58: error: 'runtime' is not a member of 'fmt'
  344 |             fmt::format_to(std::back_inserter(buf), fmt::runtime(fmt), std::forward<Args>(args)...);
      |                                                          ^~~~~~~
In file included from /mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/include/spdlog/spdlog.h:14,
--
                 from /mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/include/spdlog/spdlog-inl.h:7,
                 from /mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/src/spdlog.cpp:8:
/mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/include/spdlog/logger.h: In member function 'void spdlog::logger::log_(spdlog::source_loc, spdlog::level::level_enum, const FormatString&, Args&& ...)':
/mnt/mesos/sandbox/sandbox/o2/sw/BUILD/1afc069b8c76798b7b3cb62ccd0971e349fd36a1/DataDistribution/3rdparty/spdlog/include/spdlog/logger.h:344:58: error: 'runtime' is not a member of 'fmt'
  344 |             fmt::format_to(std::back_inserter(buf), fmt::runtime(fmt), std::forward<Args>(args)...);
```

do you need a newer version of fmt?

**Comment by ironMann** [comment]
I think spdlog expects fmt 8.0 now... Are there plans to bump the fmt?

**Comment by ktf** [comment]
we can try, but how come this entered silently in the build? do you download spdlog yourself?

**Comment by ironMann** [comment]
yes, for now DD tracks the stable rolling release branch of spdlog. They bundle a private fmt version, but while ago you asked me to use the one from alidist.

**Comment by ktf** [comment]
Can we use a tag of spdlog? I think it would be a good idea to avoid rolling releases (FWIW, I think we even forbid it explicitly somewhere in our policies).

**Comment by ironMann** [comment]
Makes sense, I'll bump DD shortly.

**Comment by ktf** [comment]
For the record, I have an API for bumping fmt to 8.0.0, and @davidrohr is preparing one with the associated changes in O2.

**Comment by davidrohr** [comment]
For reference @ironMann :
Trying to build DD with fmt 8.0.0 from @ktf's PR fails for me with
```
2021-06-28@09:57:23:DEBUG:O2-full-system-test:DataDistribution:0: Scanning dependencies of target base
2021-06-28@09:57:23:DEBUG:O2-full-system-test:DataDistribution:0: [ 18%] Building CXX object src/common/base/CMakeFiles/base.dir/FilePathUtils.cxx.o
2021-06-28@09:57:23:DEBUG:O2-full-system-test:DataDistribution:0: [ 19%] Building CXX object src/common/base/CMakeFiles/base.dir/DataDistLogger.cxx.o
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: In file included from /home/qon/docker/sw/SOURCES/DataDistribution/v0.10.18/v0.10.18/src/common/base/DataDistLogger.cxx:14:
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/SOURCES/DataDistribution/v0.10.18/v0.10.18/src/common/base/DataDistLogger.h: In member function 'void o2::DataDistribution::DataDistLogger::do_vformat(fmt::v7::string_view, fmt::v7::format_args)':
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/SOURCES/DataDistribution/v0.10.18/v0.10.18/src/common/base/DataDistLogger.h:81:48: error: no matching function for call to 'vformat_to(fmt::v7::memory_buffer&, fmt::v7::string_view&, fmt::v7::format_args&)'
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:    81 |       fmt::vformat_to(mLogMessage, format, args);
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:       |                                                ^
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: In file included from /home/qon/docker/sw/slc8_x86-64/fmt/8.0.0-local1/include/fmt/format.h:44,
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/SOURCES/DataDistribution/v0.10.18/v0.10.18/src/common/base/DataDistLogger.h:20,
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/SOURCES/DataDistribution/v0.10.18/v0.10.18/src/common/base/DataDistLogger.cxx:14:
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/slc8_x86-64/fmt/8.0.0-local1/include/fmt/core.h:2896:6: note: candidate: 'template<class OutputIt, typename std::enable_if<fmt::v7::detail::is_output_iterator<OutputIt, char>::value, int>::type <anonymous> > OutputIt fmt::v7::vformat_to(OutputIt, fmt::v7::string_view, fmt::v7::format_args)'
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:  2896 | auto vformat_to(OutputIt out, string_view fmt, format_args args) -> OutputIt {
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:       |      ^~~~~~~~~~
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/slc8_x86-64/fmt/8.0.0-local1/include/fmt/core.h:2896:6: note:   template argument deduction/substitution failed:
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/slc8_x86-64/fmt/8.0.0-local1/include/fmt/core.h:2895:11: error: no type named 'type' in 'struct std::enable_if<false, int>'
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:  2895 |           FMT_ENABLE_IF(detail::is_output_iterator<OutputIt, char>::value)>
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:       |           ^~~~~~~~~~~~~
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: In file included from /home/qon/docker/sw/SOURCES/DataDistribution/v0.10.18/v0.10.18/src/common/base/DataDistLogger.h:20,
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/SOURCES/DataDistribution/v0.10.18/v0.10.18/src/common/base/DataDistLogger.cxx:14:
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/slc8_x86-64/fmt/8.0.0-local1/include/fmt/format.h:2797:6: note: candidate: 'template<class OutputIt, class Locale, typename std::enable_if<(fmt::v7::detail::is_output_iterator<OutputIt, char>::value && fmt::v7::detail::is_locale<Locale>::value), int>::type <anonymous> > OutputIt fmt::v7::vformat_to(OutputIt, const Locale&, fmt::v7::string_view, fmt::v7::format_args)'
2021-06-28@09:57:25:DEBUG:O2-full-system-test:DataDistribution:0:  2797 | auto vformat_to(OutputIt out, const Locale& loc, string_view fmt,
```

**Comment by davidrohr** [comment]
@ironMann : I have tried with DD 10.20 and fmt 8.0.0, but it still fails with:
```
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/common-inl.h: In constructor 'spdlog::spdlog_ex::spdlog_ex(const string&, int)':
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/common-inl.h:63:50: error: cannot convert 'const string' {aka 'const std::__cxx11::basic_string<char>'} to 'const char*'
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:    63 |     fmt::format_system_error(outbuf, last_errno, msg);
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:       |                                                  ^~~
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:       |                                                  |
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:       |                                                  const string {aka const std::__cxx11::basic_string<char>}
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: In file included from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/fmt/fmt.h:26,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/common.h:36,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/spdlog.h:12,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/spdlog-inl.h:7,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/src/spdlog.cpp:8:
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/slc8_x86-64/fmt/8.0.0-local1/include/fmt/format.h:2262:46: note:   initializing argument 3 of 'void fmt::v7::format_system_error(fmt::v7::detail::buffer<char>&, int, const char*)'
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:  2262 |                                  const char* message) FMT_NOEXCEPT;
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:       |                                  ~~~~~~~~~~~~^~~~~~~
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: In file included from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/pattern_formatter-inl.h:10,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/src/spdlog.cpp:13:
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/details/fmt_helper.h: In function 'void spdlog::details::fmt_helper::pad2(int, spdlog::memory_buf_t&)':
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/details/fmt_helper.h:57:40: warning: 'fmt::v7::appender fmt::v7::format_to(fmt::v7::basic_memory_buffer<char, SIZE, Allocator>&, fmt::v7::format_string<T ...>, T&& ...) [with T = {int&}; long unsigned int SIZE = 250; Allocator = std::allocator<char>; fmt::v7::format_string<T ...> = fmt::v7::basic_format_string<char, int&>]' is deprecated [-Wdeprecated-declarations]
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:    57 |         fmt::format_to(dest, "{:02}", n);
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:       |                                        ^
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: In file included from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/fmt/fmt.h:26,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/common.h:36,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/spdlog.h:12,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/include/spdlog/spdlog-inl.h:7,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:                  from /home/qon/docker/sw/BUILD/026ca9d2475f16123056b31532228019615033de/DataDistribution/3rdparty/spdlog/src/spdlog.cpp:8:
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0: /home/qon/docker/sw/slc8_x86-64/fmt/8.0.0-local1/include/fmt/format.h:2787:21: note: declared here
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:  2787 | FMT_DEPRECATED auto format_to(basic_memory_buffer<char, SIZE, Allocator>& buf,
2021-06-28@11:57:22:DEBUG:O2-full-system-test:DataDistribution:0:       |                     ^~~~~~~~~
2021-06-28@11:57:23:DEBUG:O2-full-system-test:DataDistribution:0: [ 42%] Building CXX object CMakeFiles/spdlog.dir/src/color_sinks.cpp.o
```

**Comment by ktf** [comment]
Works locally on my mac and build/O2/o2 is compiling. Merging.

**Pull request merged**
