### PR TITLE
Fix the Copyright header

### PR DESCRIPTION
**Pull request by ZdravkoD**
Remove the unnecessary option "-*- Mode: C++ -*-" from the first line, since it does not match the guidelines for Copyright.

### CODE REVIEW

**Comment by sawenzel** [comment]
@ktf: Only 2 checks seem to have been run here. Is one of them down or was it disabled?

**Comment by sawenzel** [comment]
@ZdravkoD : Is this related to #427?

**Comment by ZdravkoD** [comment]
@sawenzel : Yes, it is related to #427, since it corrects those errors.

**Comment by sawenzel** [comment]
Good (better to mention it next time -:))

**Pull request merged**
