### PR TITLE
Move to RAWDataHeaderV6 as default header

### PR DESCRIPTION
**Pull request by shahor02**
* TOF: fixes: use RDHUtils to access RDH fields, dont use RAWDataHeader as template typename
* FT0: fixes: use RDHUtils to access RDH fields
* TPC: fixes: use RDHUtils to access RDH fields
* MID: fixes: use RDHUtils to access RDH fields
* Link RAWDataHeader to RAWDataHeaderV6

I've fixed compilation conflicts + hardcoded particular RDH version + obvious cases of direct access to RDH fields for detectors above.
@wiechula, @noferini, @preghenella, @AllaMaevskaya, @dstocco, could you please check if these fixes are ok?
Will merge this on Fri. if there are no blockers.

@JohannesLb I see that in 0422b5cdb35adbbc714795f70b73851068deb29a you have reverted usiage of some RDHUtils getters to direct access to RDH fields. Was there any reason for that? In this PR I've reverted to RDHUtils usage.

### CODE REVIEW

**Comment by preghenella** [comment]
thanks @shahor02 ,
the TOF compression part looks ok.

**Comment by dstocco** [comment]
Hi @shahor02 ,
for what concerns MID, after [this](PR https://github.com/AliceO2Group/AliceO2/pull/3478)and [this](https://github.com/AliceO2Group/AliceO2/pull/3570) PR some other classes have become obsolete.
Indeed, I have in stock a commit that:
- Removes: RawBuffer and CRUBareDecoder
- Improves RawFileReader (also using your HBFUtils)
I was waiting to perform the changes since we are currently testing the regional card output, so some checks that I'm performing are still evolving.
But the change is planned. So you might even drop your changes in case the code is compiling without them (this would spare me the conflict solving part).
But ok, if this creates compilation issues, then please go ahead with the modifications as they are now and I'll take care of the conflicts when I'll do my PR.
Thanks,
Cheers,
Diego

**Comment by shahor02** [comment]
@davidrohr ok, thanks, but using RDHUtils getters could not conflict with code using particular hardcoded version.

**Comment by davidrohr** [comment]
It can, when the encoder moves to RDH6 while the decoder still tries to decode hardcoded RDH4. It will not crash but just complain about incorrect RDH version. Anyhow, with both PRs it will be fine.

**Comment by shahor02** [comment]
Hi @dstocco, dev compilation was failing in MID with RAWDataHeader linked to V6. If you already have a private version for MID working with V6, you can commit it, then I will drop my commit for MID in this PR.

**Comment by dstocco** [comment]
Hi @shahor02 ,
well, I need to do some cleanup first. If you have green light from the others, it is better if you go ahead and I fix the conflicts on my side later on.
Thanks,
cheers,
Diego

**Comment by JohannesLb** [comment]
> 
> 
> It can, when the encoder moves to RDH6 while the decoder still tries to decode hardcoded RDH4. It will not crash but just complain about incorrect RDH version. Anyhow, with both PRs it will be fine.

Yes, it was to circumvent problems with RDH v6 in the workflow and will be fine with the general switch to v6. 
Looks good.

**Comment by AllaMaevskaya** [comment]
Thank you, for FT0 its OK
Best regards
Alla

**Comment by davidrohr** [comment]
Thx, will take care of the tpc gpu part now

**Comment by wiechula** [comment]
Hi @shahor02 ,
for the TPC this looks all fine. Thanks for the modifications.

**Pull request merged**
