### PR TITLE
TPC: Adding possibility to correct for V-shape distortions

### PR DESCRIPTION
**Pull request by matthias-kleiner**
The time dependent distortions that we observe in the DCAs on the A-side can be similarly corrected as the space-charge distortions. For this a new model is added which we can linearly scale up or down according to current V-shape observed in DCA.

Further changes:
- TPC IDC scaler adding helper function to split the scalers, when writing to file
- fixing timestamp in TPC time series

### CODE REVIEW

**Comment by miranov25** [comment]
As motivation, I would like to refer to the recent performance studies.
* V shape fluctuation is currently the most important residual fluctuation which we should fix.
* For the extraction of the V shape scaling value - we should use  normalized time series  as mentioned by @mkleine above


* https://indico.cern.ch/event/1339452/#248-alice-time-series-and-perf
image

**Comment by matthias-kleiner** [comment]
Hello @wiechula and @shahor02 
can you take a look if the implementation is fine for you?
I think in some places in the O2 code I missed the `setCorrMapVShape` as I see that the `setCorrMapRef` is also used in other parts of the code that I didnt modify in this PR (for example the `O2GPUDPLDisplay.cxx`).

In my local tests it was working as expected. In the plot you can see the DCAs from cpass8 in black and the DCAs after the V-shape correction in red. Also in the 1D histogram the RMS is significantly decreased after the correction.
We will show more to it in the space-charge meeting.
vshape 005

**Comment by shahor02** [comment]
@matthias-kleiner looks fine but I think you should replicate for the V-shape maps what is done for the RefMap in :
GPU/GPUTracking/Global/GPUChainTracking.cxx
GPU/GPUTracking/Global/GPUChainTrackingIO.cxx
GPU/Workflow/src/GPUWorkflowTPC.cxx
GPU/Workflow/src/O2GPUDPLDisplay.cxx

For the Detectors/TPC/calibration/src/TrackDump.cxx : I am not sure what it is used for, the maps there are anyway read from the local files rather than from the CCDB.

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner looks fine but I think you should replicate for the V-shape maps what is done for the RefMap in : GPU/GPUTracking/Global/GPUChainTracking.cxx GPU/GPUTracking/Global/GPUChainTrackingIO.cxx GPU/Workflow/src/GPUWorkflowTPC.cxx GPU/Workflow/src/O2GPUDPLDisplay.cxx
> 
> For the Detectors/TPC/calibration/src/TrackDump.cxx : I am not sure what it is used for, the maps there are anyway read from the local files rather than from the CCDB.

Thanks. I just added it to the places in o2. As I see in the `TrackDump.cxx` the reference map is currently anyway not used, so I didnt add it there. Maybe @wiechula can comment if I should also add it there

**Comment by matthias-kleiner** [comment]
I added the possibility to recalculate the inverse correction to get the consistent inverse correction.
This gets relevant when we linearly combine the different models
VShape_V1 007

**Comment by shahor02** [comment]
@matthias-kleiner also dpl-workflow.sh need to be taught to connect the tpc-scaler workflow if V-shape correction is requested.
Additionally, I see that with the introduction of the tpc-scalers the workflows which need TPC correction cannot be run in the standalone mode driven by root readers (i.e. o2-tpc-reco-workflow or o2-tpcits-match-workflow). They will need to check internally which options are passed and, when needed, add TPCSalersSpec.

I will create a patch on top of your PR which you can merge.

**Comment by shahor02** [comment]
@matthias-kleiner still cannot open PR to your branch, somehow the origin does not know about your O2 fork...

Could you rebase to https://github.com/shahor02/AliceO2/tree/DCAd_monitoring_rs or just cherry-pick the top 2 commits:
https://github.com/shahor02/AliceO2/commit/dfab439928724a7e19148d5af3d99ebfd7a897f0
and
https://github.com/shahor02/AliceO2/commit/13053ae487f25abc0dea2aecf9bd5cd046b89ef6

And please remove the draft tag so that the CI could start.

**Comment by miranov25** [comment]
## Posting proposal for the next interface as sent by e-mail 13.12.2023



Dear all,

Currently, there is a pull request on the O2 GitHub related to the implementation of time-dependent calibration for a specific effect. This pull request, which Matthias and I prepared for the Analytical maps, is considered an essential interim solution for calibrating V-shape fluctuations.

After the Christmas break, our objective should be to develop a comprehensive, scalable, and testable solution. This solution will rely on a general Taylor expansion in both space and time. Adopting such a strategy will soon be crucial for effectively addressing the remaining challenges in calibration and reconstruction.

**Proposal Elaboration:**

We have previously discussed the proposal for the Taylor expansion of distortion maps several times. I would like to now elaborate on it with greater detail.

**Contributing Factors:**

There are multiple factors contributing to the distortion, each with distinct shapes and time profiles. Different measurements can be utilized to decompose these components:

- **3D Nominal Maps**: Coarse granularity.
- **3D Average Sector Maps**: Higher granularity in both space and time (high gradient distortion at the sector boundaries).
- **2D Phi-Symmetric Maps**: Superior spatial and temporal granularity (O-rings, drift strips, charging up).
- **Highly Time-Granular 2D Maps**: Time x (sector, tgl, mult) with 1TF time granularity.
- **IDC**.

**Combining Calibrations:**

Several methods exist for combining these calibrations to obtain distortion/correction maps at a specific moment.

If the delta maps are obtained under varying nominal conditions, a specialized procedure will be required to combine them. In this specific approach, we will employ Taylor expansion in the local vectors instead of adding them directly to the full maps.

**Flexibility and Quality Assurance:**

To enhance flexibility and enable effective comparison of calibration modes, as well as facilitate quality assurance, it would be preferable to generate calibration and inverse calibration maps for a given timestamp. These could be processed individually, either as a ROOT macro or a Python script.

**Inputs:**

- Timestamp.
- CCDB.
- Time series.
- Any other accessible process.

**Outputs:**

- Correction and inverse maps.

**Process Callback:**

The reconstruction/simulation process should have the capability to callback such a function or device.

**Advantages of the Proposed Interface:**

Implementing an interface in this manner offers several advantages:

- **Custom Calibration and Sensitivity Studies**: Allows for custom calibration methods without the need to recompile the O2 code, significantly reducing the development cycle.
- **Method's Self-Consistency**: Enables testing of the method's self-consistency.
- **Testing and Comparison**: Simplifies testing our assumptions and comparing different approaches.

Looking forward to your feedback and further discussions on this proposal.

Best regards,

Marian

**Comment by matthias-kleiner** [comment]
Hello @miranov25 and @shahor02 ,
I implemented in the latest commit the possibillity to load the correction map from a local macro and to execute some python script before. Is this implementation fine for local testing? 
I also added the `orbitReset` as the input for the timestamp, but I was not sure how to request the `orbitReset` as input only in case the local macro is requested.

**Comment by shahor02** [comment]
> I also added the `orbitReset` as the input for the timestamp, but I was not sure how to request the `orbitReset` as input only in case the local macro is requested.

@matthias-kleiner the only way to do this is make its request conditional of the workflow-level option, defined via `addGlobalOptions`. I would not do this: the orbitReset is cheap and is anyway always queried from the CCDB.

**Comment by miranov25** [comment]
> Hello @miranov25 and @shahor02 , I implemented in the latest commit the possibillity to load the correction map from a local macro and to execute some python script before. Is this implementation fine for local testing? I also added the `orbitReset` as the input for the timestamp, but I was not sure how to request the `orbitReset` as input only in case the local macro is requested.

Hello @matthias-kleiner,  @wiechula  and @shahor02 

This development, focusing on arbitrary corrections and their inverses, is crucial for the commissioning and optimization of complex, time-dependent corrections.

To illustrate, I aim to apply this approach to our recent work on 2D space charge distortion fluctuation correction. In this project, our goal is to deploy a parameterized response to the ion discs. Throughout the commissioning phase, we intend to assess the impact of various z granularity levels on overall performance. This is reminiscent of similar studies I conducted three years ago, which I presented at the ML workshop, where I examined the influence of FFT harmonics on the precision of corrections.

### Related information for 2D distortion fluctuation calibration
* https://indico.cern.ch/event/1078970/contributions/4833313/attachments/2442800/4185177/ATO-490-ATO-589-DataDrivenSCCorrection_5thML_10052022_v3.pdf

image
* ML workshop comparing performance for the single scaling (FFT0) and scaling with 20 harmonic
image

**Comment by shahor02** [comment]
@miranov25, as I told you during our discussion, this way of loading the maps has no advantage wrt using a map from the local ccdb snapshot. In fact, it substitutes a centralized loading of a single object and its distribution to different devices which require TPC corrections by an individual loading of the map by each device separately, optionally an external process before this loading. To me, this is very error-prone.

**Comment by miranov25** [comment]
> @miranov25, as I told you during our discussion, this way of loading the maps has no advantage wrt using a map from the local ccdb snapshot. In fact, it substitutes a centralized loading of a single object and its distribution to different devices which require TPC corrections by an individual loading of the map by each device separately, optionally an external process before this loading. To me, this is very error-prone.

@shahor02, in light of our discussion last Wednesday, I have carefully considered your points about maintaining the operational stability of centralised grid production. In response, we have committed to not using our callback in central production to mitigate any potential issues.

**Regarding your functionality comment, I would like to point you to my previous comment, as it addresses some important aspects of our work.**
https://github.com/AliceO2Group/AliceO2/pull/12439#issuecomment-1853441547

**Our code there is not limited to loading CCDB entries. We are heavily involved in developing composite corrections that span both spatial and temporal dimensions.**

We must be flexible in code development, testing, and evaluation of different methods. This flexibility is especially important for fine-tuning the variations of our composed correction. Therefore, I strongly advocate maintaining this adaptability and keeping our development code on the TPC GitHub. Only a select subset of the algorithms will be integrated into the final version of O2 and pushed to the O2 github repository.

This approach is key to avoiding misunderstandings when comparing different methods. It allows us to test the code in a modular way, keep all code together with results in github, define invariants (such as maps and inverse maps), and save a lot of time. Such time time-efficient approach will enable us to concentrate on the calibration and tracking aspects, improving our overall workflow and results.

I believe that performing organised calibration/reconstruction parameter scans at GSI using a variety of parameters and algorithms would be very beneficial. It is important that the results and comparative analyses of these performance tests be carefully documented along with the source code for future reference. For example, I am currently investigating different approaches to build composed correction  integrating 2D+time and 3D+time maps, e.g. using local vectors instead of global maps.

The "flexibility" introduced by our code changes is crucial. Without it, a comprehensive review of parameters/algorithms would be difficult, if not impossible. To illustrate, when I oversaw the commissioning of Run2 pass 2, I performed a parameter scan that included 250 different parameters.

**Comment by shahor02** [comment]
@miranov25, in the end, this crucial development sets a single TPCFastTransform object for processing a single TF.  Whatever the content of this object is, this is exactly what  CorrectionMapsLoader does, extracting it from the official or custom CCDB.
But, in opposite to the standard procedure, which knows how to distribute a proper object to different devices processing the same or different TFs, this hack will lead to different devices requesting the same or different maps independently and simultaneously. With respect to creating in advance a well-controlled set of local CCDB objects, this will only add possible sources of errors, w/o providing any advantage.

Anyway, you decide how you run your tests, this was my last attempt to explain why I consider such a hack a step back wrt the possibilities the framework provides and possible problems you may encounter.

**Comment by matthias-kleiner** [comment]
> @miranov25, in the end, this crucial development sets a single TPCFastTransform object for processing a single TF. Whatever the content of this object is, this is exactly what CorrectionMapsLoader does, extracting it from the official or custom CCDB. But, in opposite to the standard procedure, which knows how to distribute a proper object to different devices processing the same or different TFs, this hack will lead to different devices requesting the same or different maps independently and simultaneously. With respect to creating in advance a well-controlled set of local CCDB objects, this will only add possible sources of errors, w/o providing any advantage.
> 
> Anyway, you decide how you run your tests, this was my last attempt to explain why I consider such a hack a step back wrt the possibilities the framework provides and possible problems you may encounter.

Hi @shahor02 , do I understand correctly that it is also possible with the `--condition-remap` feature to load time dependent local objects? If it is possible, than it would be indeed better to just use the local CCDB with pre-calculated correction maps.

**Comment by shahor02** [comment]
@matthias-kleiner yes, the `--condition-remap` remaps selected paths to a fully functional separate instance of CcdbApi, which can fetch objects either from the time-independent snapshots (if the URL is file://<path>) or from the fully-fledged time-aware ccdb server. This latter can be either the [test server](http://ccdb-test.cern.ch:8080/browse/?report=true), the [user directory on the production server ](http://alice-ccdb.cern.ch/browse/Users/s/shahoian) or [local ccdb server](https://docs.google.com/document/d/1_GM6yY7ejVEIRi1y8Ooc9ongrGgZyCiks6Ca0OAEav8/edit)

**Comment by matthias-kleiner** [comment]
Hello @shahor02 could you take a look to the code? I have also included the changes you made some time ago, but I am not sure if they are still needed.

**Review by shahor02 — DISMISSED** [review]
@matthias-kleiner thanks, superficially looks fine. Perhaps it is worth to put in the [message](https://github.com/AliceO2Group/AliceO2/blob/6f78b47ac3881c5e38e633e6140c3edecb225754/GPU/TPCFastTransformation/CorrectionMapsHelper.cxx#L101) report on the MShape correction, at least 
`mCorrMapMShape.get()!=nullptr`, but if it is possible from the map to deduce if the MShape correction is actually non-dummy for given TF, also this info.

**Comment by shahor02** [comment]
@costing @TimoWilken The full-CI seems to timeout due to the slow CCDB access:
```
grep 'internal-dpl-ccdb-backend'  fullLog.txt
[205417:internal-dpl-ccdb-backend]: [15:41:49][INFO] Processing timeslice:0, tfCounter:0, firstTForbit:0, runNumber:310000, creation:1550600800000, action:0
[205417:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/CTP/Calib/OrbitReset/01/35179/b07c53e0-b4c0-11ec-b66d-90ce809b250c in SE <ALICE::CERN::EOS>
[205417:internal-dpl-ccdb-backend]: [15:43:10][INFO] ccdb reads http://alice-ccdb.cern.ch/CTP/Calib/OrbitReset/1550600800000/b07c53e0-b4c0-11ec-b66d-90ce809b250c for 1550600800000 (load to memory, agent_id: alientest01-1706197308-n5tXxt), 
...
[205417:internal-dpl-ccdb-backend]: [16:10:55][INFO] ccdb reads http://alice-ccdb.cern.ch/FT0/Calib/CTFDictionaryTree/1546300800000/5725acbf-06d9-11ee-b4d8-200114580202 for 1550600800000 (load to memory, agent_id: alientest01-1706197308-n5tXxt), 
[205417:internal-dpl-ccdb-backend]: Info in <TJAlienFile::Open>: Accessing file /alice/data/CCDB/CPV/Config/CPVCalibParams/00/49554/6809d8f9-d82e-11ec-8000-0aa202a21b9a in SE <ALICE::CERN::OCDB>
[205417:internal-dpl-ccdb-backend]: [16:11:19][INFO] ccdb reads http://alice-ccdb.cern.ch/CPV/Config/CPVCalibParams/946684800000/6809d8f9-d82e-11ec-8000-0aa202a21b9a for 1550600800000 (load to memory, agent_id: alientest01-1706197308-n5tXxt), 
TIMEOUT
```
So, it takes 20-30 s per object, what could be the reason?

**Comment by costing** [comment]
Hi @shahor02 ,

In the past we had cases where the storage was in a funny state, blocking the client for a long while. I cannot reproduce it now with the two examples above but it depends on which EOS replica is actually accessed. Will contact our EOS friends to check them up in case it's the same issue.

The jobs set the following env variables to try to move faster to a different replica. Is this also set in the CI ? If not, could they be added?

```
export XRD_CONNECTIONWINDOW=3
export XRD_CONNECTIONRETRY=1
export XRD_TIMEOUTRESOLUTION=1
```

Cheers,

.costin

**Comment by shahor02** [comment]
Thanks @costing 
I've opened https://github.com/alisw/alidist/pull/5331 with xrootd settings.

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner thanks, superficially looks fine. Perhaps it is worth to put in the [message](https://github.com/AliceO2Group/AliceO2/blob/6f78b47ac3881c5e38e633e6140c3edecb225754/GPU/TPCFastTransformation/CorrectionMapsHelper.cxx#L101) report on the MShape correction, at least `mCorrMapMShape.get()!=nullptr`, but if it is possible from the map to deduce if the MShape correction is actually non-dummy for given TF, also this info.

Thanks, I added a simple check for the dummy M-shape map and put it to the log message

**Review by wiechula — APPROVED** [review]
Can be merged from my side.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
