### PR TITLE
[AOD] Fix the AOD stored MC collision time relative to the BC

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by sawenzel** [comment]
This is reasonable if I understand the specification in `https://aliceo2group.github.io/analysis-framework/docs/datamodel/ao2dTables.html` correctly.

**Review by sawenzel — APPROVED** [review]

**Comment by njacazio** [comment]
+async-label async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass4, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7

**Comment by njacazio** [comment]
@noferini

**Comment by njacazio** [comment]
+async-label !async-2023-pbpb-apass3

**Pull request merged**
