### PR TITLE
DPL: inputs need to be consumed also on discard

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Currently broken. Merging.

**Comment by shahor02** [comment]
@ktf I confirm that it solves the problem.

**Comment by ktf** [comment]
@chiarazampolli do you want a daily build with this in to attempt production on the grid?

**Comment by chiarazampolli** [comment]
This will be in tonight’s tag, right? Or you are proposing to tag earlier? I will be online from 22, if a new tag is there, i can try it.

**Pull request merged**
