### PR TITLE
Use raw string to fix check

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 to fix the codechecker...

**Comment by shahor02** [comment]
thanks, but where it was failing? https://github.com/AliceO2Group/AliceO2/pull/9123 passed all formatting checks before I merged it.

**Comment by ktf** [comment]
fullCi, where we run clang static checks

Ciao,
Giulio

**Comment by shahor02** [comment]
OK, but then this also should be fixed : 
https://github.com/AliceO2Group/AliceO2/blob/387b76446d374a6e8c141cb85e847a78b5e51718/Detectors/GRP/workflows/src/create-grp-ecs.cxx#L192

**Comment by ktf** [comment]
Indeed... Merging since it's currently broken. Tested locally.

**Pull request merged**
