### PR TITLE
MRRTF-188: MCH reco downscaling (for Pt2 sync reco ONLY)

### PR DESCRIPTION
**Pull request by aphecetche**

### CODE REVIEW

**Review by shahor02 — APPROVED** [review]
Thanks, looks fine to me, is it tested? Shall I merge it already?

**Comment by aphecetche** [comment]
@shahor02 I tested it (locally only), yes, just checking that the (diminution of the) reco time (and the number of tracks) I get goes along the rejection fraction : 

```
📦dev🚀~/alice/spack/laurent/dev$ rg duration run521150*/reco.log | grep "] cluster finder duration = "
run521150/reco.log:[36516:mch-cluster-finder]: [22:55:49][INFO] cluster finder duration = 16.6048 s
run521150-reject-90/reco.log:[79311:mch-cluster-finder]: [18:35:39][INFO] cluster finder duration = 17.9633 s
run521150-reject-50/reco.log:[66997:mch-cluster-finder]: [17:44:48][INFO] cluster finder duration = 83.2805 s
run521150-reject-0/reco.log:[40318:mch-cluster-finder]: [15:44:44][INFO] cluster finder duration = 167.447 s

```

Don't know if @aferrero2707 wants to have a look before merging ?

**Review by aferrero2707 — APPROVED** [review]
@aphecetche looks ok for me.

**Comment by aphecetche** [comment]
@shahor02 we're good to merge.

**Pull request merged**
