### PR TITLE
Add detection of trailing whitespaces in the CI tests

### PR DESCRIPTION
**Pull request by vkucera**

### CODE REVIEW

**Comment by vkucera** [comment]
@TimoWilken

**Comment by ktf** [comment]
@awegrzyn it's aido2osx3.cern.ch fine?

**Comment by awegrzyn** [comment]
It looks fine, although on top of `clang` and `ninja` there's a lot of `o2-qc` processes running, @Barthelemy any idea why?

**Comment by Barthelemy** [comment]
related to: https://alice.its.cern.ch/jira/browse/QC-583

We made a number of PRs to fix it. I will release a new QC.

**Comment by ktf** [comment]
I think @MichaelLettrich already restarted the build script. Are those processes zombies?

**Pull request merged**
