### PR TITLE
Add native support to send around strings

### PR DESCRIPTION
**Pull request by ktf**
This introduces preliminary support to create and send around `std::string`s. While this could have been done in other ways (e.g. using root serialization) we use this as a prototype of what is needed to create yet another serialization backend.

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy @gabrielefronze you might (for different reasons) be interested in this.

**Comment by ktf** [comment]
Known issue with `clang-format` reformatting. Merging.

**Comment by gabrielefronze** [comment]
Thanks @ktf!
I will base my implementation on this.

**Comment by Barthelemy** [comment]
Hi Giulio, 
Thank you, I will try it out. 
JIRA : O2-290 #close Fixed

**Pull request merged**
