### PR TITLE
Macro to build the rejectlist for MID

### PR DESCRIPTION
**Pull request by dstocco**
This PR introduces a macro that allows to analyse the QCDB in search of problems occurring during the run, and build a reject list out of it.
The corresponding README is also provided.

### CODE REVIEW

**Comment by dstocco** [comment]
@lmassacr pointed out that I was not correctly following the prescriptions for the time range for CCDB objects. I'm therefore modifying the macro to correctly take this into account. Will soon push a modification.

**Comment by dstocco** [comment]
I pushed again including the correction: the time is now computed with `o2::ccdb::BasicCCDBManager::getRunDuration` with a 2 minutes margin at the start and end of TF.

**Review by lmassacr — DISMISSED** [review]
Hi @dstocco, thanks for making the change for the start of run and end of run. I approve the commit. 
Laure

**Comment by dstocco** [comment]
It looks like the addition of `BasicCCDBManager` is making the text fails (although compilation and execution are working just fine). I'm having a look to the CMakeLists.txt....

**Comment by dstocco** [comment]
For some reason `#include "CCDB/BasicCCDBManager.h"` breaks root cling. I added a protection. The tests should work now.

**Review by pillot — APPROVED** [review]
re-approving after the last little fix.

**Pull request merged**
