### PR TITLE
TPC: DCS processing

### PR DESCRIPTION
**Pull request by wiechula**
* Add DCS processing for TPC
* Some unrelated fixes

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @wiechula , 

Thanks! I have an immediate feedback: on Friday, we found out that DCS modified the data they send, they are not of type "RAW" (e.g. RAW_FLOAT) but DPVAL (e.g. DPVAL_FLOAT), maybe you did not noticed you were mentioned here:

https://github.com/AliceO2Group/AliceO2/pull/8317#issuecomment-1065521359

Could you update the PR?

Cheers,

Chiara

**Comment by chiarazampolli** [comment]
Another question: is DARMA a tool to export to file the DCS DPs? We have a pending issue related to how to retrofit CCDB entries in case something goes wrong with the processing, and additionally I wanted to implement a dumping to file of what is read from ADAPOS, is this doing either of the two?

**Comment by wiechula** [comment]
@chiarazampolli , thanks for pointing this out. Indeed, I missed this message. I updated the PR.

DARMA is a web interface to export DCS DPs. For testing my development I downloaded 3 days of all our data points we want to send to ccdb. The code I added can play back this text file. At the moment all data is sent in one TF. The functionality can be extended, of course. But with this it is possible to easily send DPs to ccdb of older data. Although it is some manual work ...

**Comment by wiechula** [comment]
@davidrohr , @shahor02 , do you know if there is a problem with the CI? o2 and macOS are expected since more then 12h now.

**Comment by shahor02** [comment]
I've already asked @TimoWilken to check o2 in other PR, I also think they are stuck.

**Comment by wiechula** [comment]
Thanks @shahor02 !

**Comment by wiechula** [comment]
Thanks @shahor02 !

**Comment by wiechula** [comment]
Thanks @shahor02 !

**Comment by wiechula** [comment]
@TimoWilken , @shahor02 , o2 and macOS still didn't report, unfortunately. Could someone please check?

**Comment by wiechula** [comment]
@davidrohr , @shahor02 , can this be merged? The error in fullCI seems unrelated.

**Pull request merged**
