### PR TITLE
DPL GUI: allow GUI to move between different states

### PR DESCRIPTION
**Pull request by ktf**
DPL GUI: allow GUI to move between different states

### CODE REVIEW

**Comment by ktf** [comment]
@knopers8 @davidrohr @aalkin if you could stress test a bit this i would appreciate.

**Comment by knopers8** [comment]
In general, it seems to work OK. Is it possible to control the state of devices globally or only individually?

Also, it seems that the GUI hangs during exit when running with `--completion-policy wait`, I am not sure if this is natural consequence of the option or not.

**Comment by ktf** [comment]
Can you update alidist? I think you need the new DebugGUI to fix that hang.

**Comment by knopers8** [comment]
I will leave it compiling with new alidist overnight

**Comment by knopers8** [comment]
it still hangs, see `o2-qc-run-basic --completion-policy wait` as a reproducer

**Comment by Barthelemy** [comment]
This is something that would be extremely helpful for the SSS debugging and testing. Would it be possible to resume the effort ?

**Comment by Barthelemy** [comment]
@ktf @aferrero2707 we would really need this to exercise SSS locally.

**Pull request closed without merging**
