### PR TITLE
Add CUDA autodetection

### PR DESCRIPTION
**Pull request by dberzano**
* CUDA is treated as a language by CMake
* Set both `ENABLE_CUDA` CMake variable for consistency with `HIP` and a
  compiler definition with the same name

### CODE REVIEW

**Comment by dberzano** [comment]
@mconcas @davidrohr this is what we've agreed upon yesterday (with `ENABLE_CUDA` kept as CMake variable, _and_ compiler definition).

**Comment by davidrohr** [comment]
@dberzano : I am just wiping o2 build dir and recompiling over lunch to verify the CheckLanguage works now.

Another point is: I'd suggest to have a check for a minimum CUDA version. I.e. I need at least CUDA 9 I guess, but we could also just require 10.1 for now. If we auto-detect an older version and try to compile, it'll fail and people won't understand why.

**Comment by mconcas** [comment]
@dberzano yes, it would work fine.
I also agree with David upon setting the minimum CUDA version required and to be able to manually bump the requirement.

**Comment by dberzano** [comment]
@mconcas @davidrohr I fully agree with you. Let me add a check for CUDA 10.1 for now.

**Comment by davidrohr** [comment]
Another point that came to my mind: perhaps we want to have a cmake option that makes CUDA mandatory (like the for -DENABLE_CUDA did).

**Comment by dberzano** [comment]
I thought of it, it may be a good idea. So, autodetect by default, and `-DENABLE_CUDA=ON` makes it fail hard in case CUDA's not found.

**Comment by davidrohr** [comment]
In that case, perhaps we could also do -DENABLE_CUDA=OFF disables autodetection.

**Comment by davidrohr** [comment]
@dberzano : The CheckLanguage thing seems to have been fixed in the meantime in cmake, at least it works for me now:

DEBUG:O2:O2:0: -- Looking for a CUDA compiler
DEBUG:O2:O2:0: -- Looking for a CUDA compiler - /opt/cuda/bin/nvcc
DEBUG:O2:O2:0: -- The CUDA compiler identification is NVIDIA 10.1.105
DEBUG:O2:O2:0: -- Check for working CUDA compiler: /opt/cuda/bin/nvcc
DEBUG:O2:O2:0: -- Check for working CUDA compiler: /opt/cuda/bin/nvcc -- works

So I am fine with it.

**Comment by dberzano** [comment]
@davidrohr yes everything's addressed now. From the commit message:

* CUDA is treated as a language by CMake
* Set both `ENABLE_CUDA` CMake variable for consistency with `HIP` and a
  compiler definition with the same name
* By default, it performs autodetection. If `ENABLE_CUDA=ON`, if CUDA is not
  found if will fail with a fatal error. If `ENABLE_CUDA=OFF`, CUDA
  detection is not performed and CUDA is always disabled
* We explicitly demand CUDA to have a minimum version (10.1 for now)

OK?

**Comment by davidrohr** [comment]
Yes, looks good to me.

**Comment by dberzano** [comment]
Hi @davidrohr, since we're testing the CUDA compilation as well, do you have some insight on the following?

```
/home/alidock/ci/ci_checks/o2_checker_linux_o2_ci_0/sw/slc7_x86-64/AliTPCCommon/alitpccommon-v2.3.2.1-4/sources/TPCCAGPUTracking/GlobalTracker/cuda/AliGPUReconstructionCUDA.cu(21): error: dynamic initialization is not supported for a __constant__ variable

/home/alidock/ci/ci_checks/o2_checker_linux_o2_ci_0/sw/slc7_x86-64/AliTPCCommon/alitpccommon-v2.3.2.1-4/sources/TPCCAGPUTracking/GlobalTracker/cuda/AliGPUReconstructionCUDA.cu(22): error: dynamic initialization is not supported for a __constant__ variable

2 errors detected in the compilation of "/tmp/tmpxft_0000df9f_00000000-6_AliGPUReconstructionCUDA.cpp1.ii".
```

[Full log here.](https://ali-ci.cern.ch/repo/logs/AliceO2Group/AliceO2/1833/bdeb1634bee3b96691e9bb3f8fd5ee08cdaa65c3/build_o2_cuda/fullLog.txt)

**Comment by davidrohr** [comment]
Indeed, it will currently fail with cuda 10.1. the fix is in the large pr of the alitpccommon merge.

Am 28. März 2019 17:24:14 MEZ schrieb Dario Berzano <notifications@github.com>:
>Hi @davidrohr, since we're testing the CUDA compilation as well, do you
>have some insight on the following?
>
>```
>/home/alidock/ci/ci_checks/o2_checker_linux_o2_ci_0/sw/slc7_x86-64/AliTPCCommon/alitpccommon-v2.3.2.1-4/sources/TPCCAGPUTracking/GlobalTracker/cuda/AliGPUReconstructionCUDA.cu(21):
>error: dynamic initialization is not supported for a __constant__
>variable
>
>/home/alidock/ci/ci_checks/o2_checker_linux_o2_ci_0/sw/slc7_x86-64/AliTPCCommon/alitpccommon-v2.3.2.1-4/sources/TPCCAGPUTracking/GlobalTracker/cuda/AliGPUReconstructionCUDA.cu(22):
>error: dynamic initialization is not supported for a __constant__
>variable
>
>2 errors detected in the compilation of
>"/tmp/tmpxft_0000df9f_00000000-6_AliGPUReconstructionCUDA.cpp1.ii".
>```
>
>[Full log
>here.](https://ali-ci.cern.ch/repo/logs/AliceO2Group/AliceO2/1833/bdeb1634bee3b96691e9bb3f8fd5ee08cdaa65c3/build_o2_cuda/fullLog.txt)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/AliceO2Group/AliceO2/pull/1833#issuecomment-477669292

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by davidrohr** [comment]
I don't know if it would make sense to backport the fix to AliTPCCommon. AliceO2Group/AliceO2#1747 should be merged soon anyway.

**Comment by davidrohr** [comment]
@dberzano : CUDA test is marked as failed, but I cannot test the details. Was it rerun after the merge of AliTPCCommon?

**Comment by mconcas** [comment]
@davidrohr The CUDA test is not enabled by default, afaik. Probably it hasn't be run after the merge.

**Comment by dberzano** [comment]
As @mconcas said.

**Comment by mconcas** [comment]
@davidrohr we are back online with the CUDA test.

**Comment by davidrohr** [comment]
nice, great.

@dberzano : Would you be interested to add autodetection for hip / opencl / openclcpp in the same way. I could give it a try. We could just install the AMDAPPSDK + ROCm on the node where you run the CUDA test, and the build will allow to test all GPU builds at once.

When I am done with my current work for the compression I can give it a try to change the build system to auto-detection in the same fashion as for CUDA, also for HIP / OpenCL.

**Pull request merged**
