### PR TITLE
DPL: allow resetting the oldest possible timeframe mechanism

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf : What happens actually at stop/start. Will the timeSlice start again at 0? Then it must also be reset at several other places?

**Comment by vascobarroso** [comment]
@davidrohr for the O2 tasks (readout/DD/reco/QC/calib) a stop/start reusing an existing environment should be indistinguishable from a fresh start using a new environment.

**Comment by davidrohr** [comment]
well, depends. If we want to use that stop/start as PAR perhaps not?

**Comment by vascobarroso** [comment]
Indeed. But I think the current stop/start being developed is closer to the fast SOR/EOR we had during Run 2. PAR will come later.

**Comment by vascobarroso** [comment]
@ktf @davidrohr any reason why this has not yet been merged ?

**Comment by vascobarroso** [comment]
@ktf @davidrohr @shahor02 any chance this will be merged this week ? There is a scheduled START/STOP/START test at P2 on Tuesday next week, but if this will not be there I think it would be better to postpone.

**Comment by ktf** [comment]
Sorry this week was complicated. I just fixed the conflict and I am trying this again.

**Comment by davidrohr** [comment]
@ktf : shall we merge this now?

**Comment by davidrohr** [comment]
this fixes issues I see on the EPN, tested locally, only fixed clang format, merging

**Pull request merged**
