### PR TITLE
20% speed up of the GPU NeighborsFinder

### PR DESCRIPTION
**Pull request by sgorbuno**
20% speed up of the GPU NeighborsFinder via manual loop unrolling.

before:
AMD: 13,692 us NVIDIA: 5,169 us

after:
AMD: 11,406 us NVIDIA: 4,129 us

### CODE REVIEW

**Comment by davidrohr** [comment]
@sgorbuno : OpenCL 1.2 doesn't know constexpr, you can use CONSTEXPR.
For the #pragma unroll, I am not sure whether opencl will work with a variable (even if const) as unroll factor.
One point I was thinking about, is to have a for loop with 2 iterations and pragma unroll 2 around your splitting of the loop. First iteration could do the shared memory part, 2nd one the scratch memory part. If the compiler unrolls correctly, that should compile to the same code you have right now. But not sure whether the HIP compiler will understand it and how many lines of code we can save this way.

**Comment by sgorbuno** [comment]
> For the #pragma unroll, I am not sure whether opencl will work with a variable (even if const) as unroll factor.

nvcc doesn't work with a macro as an unroll factor. That is why I introduced constexpr ...

**Comment by davidrohr** [comment]
you can use GPUCA_UNROLL

the syntax is GPUCA_UNROLL(CUDA, HIP), where CUDA and HIP can be:
- empty: no unroll
- U() : becomes #pragma unroll
- U(n) : becomes #pragma unroll n

I also have to add OpenCL and CPU here, but the time being, this should
be sufficient for you I guess, in combination with CONSTEXPR

**Comment by davidrohr** [comment]
@sgorbuno : I think you can try to use the GPUCA_UNROLL macro, to avoid the OpenCL problems, as discussed via e-mail.

**Pull request merged**
