### PR TITLE
TPC: do not depend on TPCMonitor for the reconstruction workflow

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
`O2::TPCMonitor` depends on the kitchen sink, so we should not include it in the default TPC reconstruction workflow.

**Comment by ktf** [comment]
@chiarazampolli FYI

**Comment by chiarazampolli** [comment]
@ktf , by how much will this reduce the number of opened files?

**Comment by ktf** [comment]
@shahor02 @davidrohr is:

```
## sw/BUILD/O2-latest/log
 26/434 Test  #24: GPU/TPCFastTransformation/test/testMultivarPolynomials.cxx ...........................***Failed    9.05 sec
99% tests passed, 1 tests failed out of 434
100% tests passed, 0 tests failed out of 102
```

a known issue?

@sawenzel @costing I think there is some issue with CCDB.

**Comment by ktf** [comment]
@chiarazampolli I need to check. It depends if this also reduces the huge amount of .pcm files we are currently loading as a side effect.

**Comment by ktf** [comment]
ARM mac issue unrelated. Merging.

**Pull request merged**
