### PR TITLE
DPL: forward message early when possible

### PR DESCRIPTION
**Pull request by ktf**
When coupled with FairMQ 1.4.41 this should allow for parallel
processing on data matching the same O2 Signature without sacrificing
the concept of being a message passing framework.

The optimization is disabled in the case an Optional field is present,
because we do not want to forward those before their potential by-products
due to processing.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @wiechula this works as expected with FairMQ 1.4.41 and my synthetic tests. It would be good if you could test in your environment.

I need to test this for analysis as well, as it might interfere with the rate limiting.

**Comment by davidrohr** [comment]
OK, thx, can test it with large FST on the EPN tonight, but will have to rebuild with the new FairMQ.

**Comment by wiechula** [comment]
Thanks, I'll have a look!

**Comment by davidrohr** [comment]
For reference, the FST is not running with the new FairMQ alisw/alidist#3312 thus testing of this PR is on hold.

**Comment by davidrohr** [comment]
@ktf : Can you restart the CI for this? The FMQ part is merged. In parallel I'll try in the FST

**Comment by ktf** [comment]
i actually already did. the issue is real and i am looking into it.

Ciao,
Giulio

**Comment by ktf** [comment]
So the error seems real, but I get it ragardless of this PR. So I suspect it's actually a regression in FairMQ 1.4.41/42

**Comment by ktf** [comment]
Maybe I did not actually rebuild...

**Comment by ktf** [comment]
Ok, I confirm that rebuilding with the new FairMQ removes the issue with the test. I am trying to reset the tests...

**Comment by davidrohr** [comment]
@ktf : Seems it fails again. And the FullCI failure seems like something is not working with the custom completion policy.

**Comment by ktf** [comment]
Indeed, I was missing a `break` statement.

**Comment by ktf** [comment]
I also suspect we cannot forward early with the custom completion policy, because otherwise we could end up forwarding many times...

**Comment by davidrohr** [comment]
I don't understand that. Can't you keep track and make sure we only forward once?
Or let's say, you only forward-early at the point in time when the run function is called and the message is consumed?
The tpc workflow has a custom policy and it consumes raw data. So if we cannot forward-early there, it will be blocking.

**Comment by ktf** [comment]
> I don't understand that. Can't you keep track and make sure we only forward once?

Yes, this is probably the best option.

> Or let's say, you only forward-early at the point in time when the run function is called and the message is consumed?

The problem is that we support "Process", besides "Cunsume" which means that the subsequent iteration the message will still be there and processed (or consumed) again.

> The tpc workflow has a custom policy and it consumes raw data. So if we cannot forward-early there, it will be blocking.

Ok.

**Comment by ktf** [comment]
Ok, nevermind. I think it's actually just a matter of checking for CompletionOp::Consume, with the caveat that if one uses "Process" it will not be optimized.

**Comment by davidrohr** [comment]
Ok, i think that should be ok for now. Process with a custom policy is anyhow a corner case.

**Comment by wiechula** [comment]
I tested with my pedestal workflow on a few TFs with 4-12 workers. It is about 30-40% faster, depending a bit on the number of parallel workers! I think this looks good.

**Comment by ktf** [comment]
@wiechula nice! can you tell me about the CPU consumption?

**Comment by ktf** [comment]
Merging this, however there is an additional problem for the analysis. Given we now shallow copy messages, the accounting which is being done to regulate the incoming data will be wrong. I will workaround that in a separate PR.

**Comment by wiechula** [comment]
@ktf , can you explain a bit more what you mean with CPU consumption or how to measure it?

**Comment by ktf** [comment]
I mean CPU load during the processing. Given you are 40% faster, I assume that's due to more cores being used in parallel, so I was wondering how the load changed.

**Pull request merged**
