### PR TITLE
Fixes for TOF CTF creation

### PR DESCRIPTION
**Pull request by noferini**
Mainly to fix CTF encoding from digits.
Diagnostic patterns moved to 8bit words to deal with 26bit limits

### CODE REVIEW

**Comment by noferini** [comment]
The last changes were tested on the raw data collected by cosmic runs (MW1).
With this fix we are able to write and read CTF for real data.

**Comment by noferini** [comment]
errored checks seem not be related to this PR...

**Comment by davidrohr** [comment]
This PR should be fine, it was built correctly in o2-dataflow.
If you want to keep both commits separate, please manually squash the formatting commit in there. Otherwise the PR should be squashed when merging.

**Comment by noferini** [comment]
I did a squash of the commits

**Comment by shahor02** [comment]
Hi @noferini 
could you please fix this?
````
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/SOURCES/O2/5410/0/Detectors/TOF/base/src/WindowFiller.cxx:305:52: warning: statement should be inside braces [readability-braces-around-statements]
      if (mReadoutWindowData.size() < nwindowperTF)
````

**Comment by noferini** [comment]
> Hi @noferini
> could you please fix this?
> 
> ```
> /mnt/mesos/sandbox/sandbox/o2-fullci/sw/SOURCES/O2/5410/0/Detectors/TOF/base/src/WindowFiller.cxx:305:52: warning: statement should be inside braces [readability-braces-around-statements]
>       if (mReadoutWindowData.size() < nwindowperTF)
> ```

Done

**Comment by shahor02** [comment]
failures unrelated

**Pull request merged**
