### PR TITLE
DPL: allow configuring FairMQ channels used by DPL

### PR DESCRIPTION
**Pull request by ktf**
In particular use it to configure the logging rate.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr `--fairmq-rate-logging 0` to turn it off. We should probably make it default.

**Review by davidrohr — APPROVED** [review]
Thx for this improvement, just tried it and it works.

**Comment by ktf** [comment]
You are welcome, this will come handy for other stuff as well, actually...

**Comment by ktf** [comment]
@costing @sawenzel CCDB is down again. Can it be resuscitated?

**Comment by sawenzel** [comment]
@ktf: I can't see CCDB failures here. On Mac, all tests are down. O2 fails with compiler out of memory. FullCI has 100% tests  ok. Could you please point me to the correct log?

**Comment by sawenzel** [comment]
@ktf: You probably mean the one on QualityControl. @Barthelemy.

**Comment by davidrohr** [comment]
Can we merge this, or will you push more on top @ktf ?
The fullCI has passed O2, o2 failed due to unrelated reasons, and macOS fails after compilation due to the known macro-ctest error, so I think this one is OK.

**Pull request merged**
