### PR TITLE
Update in ZDC reconstruction

### PR DESCRIPTION
**Pull request by cortesep**
This is a long due update of the reconstruction code that provides correction for TDC time and amplitude, for isolated signals and in presence of pile-up for previous bunches. For the moment the pile-up correction has been tested for 50 and 75 ns bunch spacing. For 100 ns bunch spacing we assume no effect. For 25 ns the pile-up correction is under test.
This pull request includes a fast simulation/testing framework.

### CODE REVIEW

**Comment by shahor02** [comment]
@cortesep fullCI fails because the newly uploaded CPV object is accessible only via alien and the CI servers still don't have an alien-token. I'll ask @costing to sync the server versions to alien ones so for a while it can work w/o the alien token, but this may take while.

**Comment by cortesep** [comment]
Hi Ruben,
can we proceed with merging then?

**Review by shahor02 — APPROVED** [review]

**Comment by shahor02** [comment]
@cortesep the run successful local `$O2_ROOT/prodtests/full_system_test.sh` I had to upload the `33fcedc0-9556-11ec-825c-200107602601` object of http://ccdb-test.cern.ch:8080/browse/ZDC/Calib/TDCCorr?report=true to http://alice-ccdb.cern.ch/browse/ZDC/Calib/TDCCorr.

**Comment by cortesep** [comment]
Ok. Thanks. It usually gets wiped after a while. Did you make it persistent?

Ciao,
Pietro

**Comment by shahor02** [comment]
Hi, it is never wiped out, it may go out of validity. I've set it till October 2022, as for other zdc objects.



Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Pull request merged**
