### PR TITLE
Convert collision time to ps in TOF PID response

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by njacazio** [comment]
@jgrosseo

**Comment by jgrosseo** [comment]
Thanks! This will stay draft until new filtered data is available.

**Review by jgrosseo — DISMISSED** [review]

**Comment by jgrosseo** [comment]
Conversion train 112 now contains the TOF time in ps. @njacazio could you check on a file from that train? 
There seems to be a conflict here now. Could you check that? Many thanks!

**Comment by njacazio** [comment]
@jgrosseo sure thing, I'm on it

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
