### PR TITLE
Misc fixes O2-513

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr

**Comment by ktf** [comment]
@matthiasrichter could you have a look in particular at 87d29d76705343bd927ff596669ec14d9952ff08 which touches the way we do argument processing. I was discussing with @davidrohr and we agreed that maybe it would be a better behaviour to fail when an unknown option is passed. E.g.:

```bash
../stage/bin/o2-testworkflows-diamond-workflow --B='--child-driver="valgrind" --foo'
``` 

should complain about `--foo` (but it does not).

**Comment by ktf** [comment]
This should fix the extra reported issues:

* valgrind error when sending metrics
* Force killing a process when it's started with -s
* Spurious printouts about the GLFW not available

Could you please confirm the bad behaviour in option handling is not due to a regression introduced by this PR?

**Comment by davidrohr** [comment]
> Could you please confirm the bad behaviour in option handling is not due to a regression introduced by this PR?

@ktf : I tried with the current dev branch: when I run the tpc workflow via: `o2-tpc-reco-workflow --infile tpc-native-clusters.root --input-type=clusters --tracker-options "gpuType=CUDA" --tpc-tracker='--child-driver konsole -e'`, the gpuType=CUDA gets lost. If I just run `o2-tpc-reco-workflow --infile tpc-native-clusters.root --input-type=clusters --tracker-options "gpuType=CUDA"`, it works correctly. So this problem was present also before your PR.

Now having a look at the other points.

**Comment by davidrohr** [comment]
>     * Force killing a process when it's started with -s

Works when I click the "X", but does still not work when I move to the console (while the processes are stopped) and press CTRL-C.

**Comment by davidrohr** [comment]
@ktf @matthiasrichter : I would also suggest to give a proper name to the option that affects only one process. E.g. something like --procopt-[process_name]. Only --[process_name] is a bit misleading to me. Also, the --help printout should list this possibility.

**Comment by ktf** [comment]
> Works when I click the "X", but does still not work when I move to the console (while the processes are stopped) and press CTRL-C.

Could you let me know where it hangs?

**Comment by matthiasrichter** [comment]
> @ktf @matthiasrichter : I would also suggest to give a proper name to the option that affects only one process. E.g. something like --procopt-[process_name]. Only --[process_name] is a bit misleading to me. Also, the --help printout should list this possibility.

@davidrohr, sure, can be changed. However, for the moment it's consistent, and also the help printout explains it correctly. So I consider it some polishing which can be done. On a side note `--procopt-something` sounds not much better, even awkward to me.

**Comment by davidrohr** [comment]
@matthiasrichter : Indeed, --help contains
```
  --tpc-tracker arg                     Option groups by process name: 
                                        --tpc-tracker "<processor options>"
  --tpc-track-writer arg                Option groups by process name: 
                                        --tpc-track-writer "<processor 
                                        options>"
```
but I didn't realize that this is used to forward options to only one child. I was looking for something like `--child-option [process_name] args`. I actually also confused it with the --tracker-options option that I have been using to provide the option string to the tracker worker class.
So indeed, if one knows, it is kind of consistent, but at least to me it did not become clear after reading the --help message.
In particular, I think having a general help text --[process_name]='args' : Forward args to child process with id [process_name], would be much clearer than listing all --tpc-tracker, --tpc-track-writer, etc. individually. Instead, I would just list the possible process ids with the help text to --[process_name].

I kind of agree that --procopt-[something] looks awkward, but at least it would make clear that this is an option forwarded to only one child, which is not so obvious with --[process_name]

**Comment by davidrohr** [comment]
> One thing I never liked of the current approach is that one needs: [...]

@ktf : btw, for me both `--tpc-tracker '--child-driver "konsole -e"'` and `--tpc-tracker='--child-driver "konsole -e"'` work equally.

**Comment by ktf** [comment]
zsh-ism...

**Comment by ktf** [comment]
@davidrohr can you try now? I am setting the descriptor to `O_NONBLOCK` which hopefully solves the issue. I cannot reproduce the behaviour on my mac, BTW...

**Comment by davidrohr** [comment]
Ctrl-c is fully working now. Only remaining issue is that --tracker-options are lost when i use --tpc-tracker.

**Comment by ktf** [comment]
Ok, but that's not a regression, correct?

**Comment by davidrohr** [comment]
No, problem was there before. This PR can be merged.

**Comment by ktf** [comment]
Did you manage to check valgrind?

**Comment by davidrohr** [comment]
Yes, valgrind is working with the child-driver options.i just had to hack in the tracker-options hard in the binary, since the option string wad bot passed. The bug in the tracking was fixed yesterday evening.

**Comment by ktf** [comment]
I meant the issue in `ConditionalRun()` you mailed me yesterday should be now gone. Could you verify?

**Comment by davidrohr** [comment]
Yes, that is fixed as well.

**Pull request merged**
