### PR TITLE
Ctpinp

### PR DESCRIPTION
**Pull request by lietava**
CTPRunScalers::GetRate and GetRateGivenT for any class level and inputs

### CODE REVIEW

**Comment by lietava** [comment]
Hi @sawenzel , I modified GetRate and GetRateGivenT which I think were written by you. I used parameter type which was already there. PLease, comment/suggest.

**Comment by lietava** [comment]
@sawenzel : I tested (see PlotPbLumi.C) and fixed bug.
eg [O2/latest-ctpinp-o2] ~/alice/O2/Detectors/CTP/macro $> root -l "PlotPbLumi.C(544491,9246)"

**Comment by sawenzel** [comment]
Fine with me. Please remove "draft" as soon as this is ready to go.

**Comment by lietava** [comment]
@shahor02 : now I dont see CTP related error , please, merge.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
