### PR TITLE
Move cluster related classes to reconstruction

### PR DESCRIPTION
**Pull request by wiechula**
* Move all classes related to clusters and cluster finding to reconstruction, as it is more appropriate
* Also move the tpc simulation and reconstruction executable to the global run directory and add the option for tracking
* Do some cleanup to fix compiler warnings

### CODE REVIEW

**Comment by wiechula** [comment]
I wonder why I don't see any warnings of this kind during my local compilation. Do I miss something?

**Comment by sawenzel** [comment]
@wiechula : The PR checker runs a bit more restrictive (in particular in -Werror mode + running the unit tests). You can easily get the same behaviour by saying `ALIBUILD_O2_TESTS=ON alibuild build O2 ...`

**Comment by wiechula** [comment]
@sawenzel, thanks for the comment!

I think the errors above are not related to my PR. Can it be merged and the errors above fixed by the responsible people?

**Comment by wiechula** [comment]
Thanks for the commit, for curiosity, did you squash commit? Also for my last commit I had the impression that the single commit were lost, so no simple rebase merge was done.

**Pull request merged**
