### PR TITLE
Update QC flag type

### PR DESCRIPTION
**Pull request by JianLIUhep**

### CODE REVIEW

**Comment by JianLIUhep** [comment]
Hi @knopers8, I created this PR to include what we discussed offline on the changes to the current existing flag type. 
I did not add the IDs for the newly proposed items. Please let me know which values should be assigned to them.

Another point is on the `CertifiedByExpert`. Is it supposed to be set by hand by detector experts? For example, if the value is 1, it represents the quality for this run/time_interval is not yet certified. A following question, should this flag be associated with the verification button in RCT? 
CC @xsalonx

**Comment by xsalonx** [comment]
Just to be aware, as IDs of QC flag types differ from those in the table, they should be updated as well

**Comment by knopers8** [comment]
Yes, please update the IDs as well.

Regarding `CertifiedByExpert`, I do not know if it is used for the "validation" feature in the RCT. If it is not, we could drop it. Would you know @xsalonx ?

**Comment by xsalonx** [comment]
There is no special treatment of `CertifiedByExpert` flag type, so it can be verified as well. If it provides notion of something else than verification itself it probably should not be deleted, as verification is feature to enforce additional checking of flags provided.

**Comment by knopers8** [comment]
So in this sense, I do not think we need it here anymore. I think I've put it initially here to represent the "verification" feature, so if this is handled differently, the flag can be deleted.

**Comment by knopers8** [comment]
I see that in RCT there is no `Unknown` flag anymore, while you did not remove it here. Should it appear in the RCT or you do not want it to be used anymore?

As a reminder, `Unknown` is usually used by the module developers when an automatic Check sees there is something wrong, but the exact influence on the data quality is **unknown**. See examples:
- https://github.com/AliceO2Group/QualityControl/blob/9d5ee3f063848df69b9aca81796acd70e6a105ee/Modules/ITS/src/ITSTrackCheck.cxx#L62
- https://github.com/AliceO2Group/QualityControl/blob/9d5ee3f063848df69b9aca81796acd70e6a105ee/Modules/EMCAL/src/RawErrorCheck.cxx#L224
- https://github.com/AliceO2Group/QualityControl/blob/9d5ee3f063848df69b9aca81796acd70e6a105ee/Modules/TOF/src/CheckRawToT.cxx#L86

This flag is probably overused, but we might need one or other way of saying "there is something wrong, but we do not know exactly how wrong". If you have another name proposal for this flag, we can always talk!

**Comment by JianLIUhep** [comment]
Regarding the `Unknown `, I believe we overlooked it when implementing them into the RCT (perhaps only checked the diff version in the PR). 

@xsalonx could you please add the `Unknown ` to the RCT? Thank you.

**Comment by knopers8** [comment]
@JianLIUhep , @xsalonx any news about the IDs?

**Comment by JianLIUhep** [comment]
@knopers8 @xsalonx, I updated the IDs wrt the values in [RCT](https://ali-bookkeeping.cern.ch/?page=qc-flag-types-overview). Note, I changed `CertifiedByExpert` to obsolete for now.

**Comment by knopers8** [comment]
At this stage we can still remove `CertifiedByExpert` completely. I will not include it in my PR which updates these.

**Comment by JianLIUhep** [comment]
Done.

**Comment by knopers8** [comment]
Superseded by https://github.com/AliceO2Group/AliceO2/pull/13092

**Pull request closed without merging**
