### PR TITLE
aod-writer: metadata writing and ordered completion policy

### PR DESCRIPTION
**Pull request by nburmaso**

### CODE REVIEW

**Review by sawenzel — APPROVED** [review]
Looks ok to me.

**Comment by sawenzel** [comment]
@ktf: Can you please take a look if ok for the aod-writer in Framework?

**Comment by davidrohr** [comment]
ok, don't see the random crashes any more, looks good

**Comment by shahor02** [comment]
Hi @nburmaso 
It looks like after this PR overwriting existing AO2D file leads to an error:
```
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::ReadClassBuffer>: class: TNamed, attempting to access a wrong version: 28005, object skipped at offset 232
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::CheckByteCount>: object of class TNamed read too few bytes: 2 instead of 879912289
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::CheckByteCount>: Byte count probably corrupted around buffer position 226:
[1435576:internal-dpl-aod-writer]:      879912289 for a possible maximum of 10340
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::ReadClassBuffer>: Could not find the StreamerInfo for version 2 of the class TNamed, object skipped at offset 258
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::CheckByteCount>: object of class TStreamerString read too many bytes: 16 instead of 2
[1435576:internal-dpl-aod-writer]: Warning in <TBufferFile::CheckByteCount>: TStreamerString::Streamer() not in sync with data on file .//AO2D.root, fix Streamer()
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::CheckByteCount>: object of class TStreamerString read too many bytes: 6 instead of 2
[1435576:internal-dpl-aod-writer]: Warning in <TBufferFile::CheckByteCount>: TStreamerString::Streamer() not in sync with data on file .//AO2D.root, fix Streamer()
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::ReadClassBuffer>: Could not find the StreamerInfo for version 2 of the class TNamed, object skipped at offset 899
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::ReadClassBuffer>: class: TNamed, attempting to access a wrong version: 103, object skipped at offset 913
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::CheckByteCount>: object of class TStreamerString read too many bytes: 117 instead of 2
...
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::CheckByteCount>: object of class TStreamerObjectPointer read too many bytes: 29 instead of 2
[1435576:internal-dpl-aod-writer]: Warning in <TBufferFile::CheckByteCount>: TStreamerObjectPointer::Streamer() not in sync with data on file .//AO2D.root, fix Streamer()
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::CheckByteCount>: object of class TStreamerSTL read too many bytes: 14 instead of 2
[1435576:internal-dpl-aod-writer]: Warning in <TBufferFile::CheckByteCount>: TStreamerSTL::Streamer() not in sync with data on file .//AO2D.root, fix Streamer()
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::ReadClassBuffer>: class: TNamed, attempting to access a wrong version: 101, object skipped at offset 9250
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::ReadClassBuffer>: class: TNamed, attempting to access a wrong version: 115, object skipped at offset 9582
[1435576:internal-dpl-aod-writer]: Error in <TBufferFile::ReadClassBuffer>: class: TNamed, attempting to access a wrong version: 119, object skipped at offset 9930
[1435576:internal-dpl-aod-writer]: Error in <TStreamerInfo::BuildOld>: Could not find base class:  for TTree and could not find any matching rename rule
[1435576:internal-dpl-aod-writer]: 
[1435576:internal-dpl-aod-writer]: Error in <TStreamerInfo::BuildOld>: Could not find base class:  for TTree and could not find any matching rename rule
[1435576:internal-dpl-aod-writer]: 
[1435576:internal-dpl-aod-writer]: Error in <TStreamerInfo::BuildOld>: Could not find base class:  for TTree and could not find any matching rename rule
[1435576:internal-dpl-aod-writer]: 
[1435576:internal-dpl-aod-writer]: Error in <TStreamerInfo::BuildOld>: Could not find base class:  for TTree and could not find any matching rename rule
[1435576:internal-dpl-aod-writer]: 
[1435576:internal-dpl-aod-writer]: *** Program crashed (Segmentation fault, FPE, BUS, ABRT, KILL)
[1435576:internal-dpl-aod-writer]: Backtrace by DPL:
[1435576:internal-dpl-aod-writer]: SEGMENTATION FAULT
[1435576:internal-dpl-aod-writer]: Executable is /home/shahoian/alice/sw/ubuntu2204_x86-64/O2/dev-local1/bin/o2-aod-producer-workflow
[1435576:internal-dpl-aod-writer]:     /lib/x86_64-linux-gnu/libc.so.6:     0x00007fa9cf5a2520: ?? ??:0
[1435576:internal-dpl-aod-writer]:     [0x5561f1abc724]:     0x00005561f1abc724: ?? ??:0
[1435576:internal-dpl-aod-writer]: Backtrace complete.
[ERROR] pid 1435576 (internal-dpl-aod-writer) crashed with 1
```

Could you please check?

**Comment by nburmaso** [comment]
Hi @shahor02 

Ok, I will take a look

**Pull request merged**
