### PR TITLE
Revert "Extended table for the modified cov. matrix"

### PR DESCRIPTION
**Pull request by ktf**
Reverts AliceO2Group/AliceO2#3838

### CODE REVIEW

**Comment by ktf** [comment]
@pzhristov I think #3838 actually broke the builds. Do you understand why or shall we revert?

**Comment by pzhristov** [comment]
@ktf It was green when I tested it at the end of last week. Do you have an example of failing build? It might be an interference with the changes of Anton, however yesterday evening I tested both locally...

**Comment by ktf** [comment]
Yeah, I suspect it's multi PR interference.

**Comment by pzhristov** [comment]
We better fix the origin of the problem. I propose to close this PR.

**Pull request closed without merging**
