### PR TITLE
Clarify readme clang format

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by awegrzyn** [comment]
Not sure whether it's worth mentioning in the README but I often use:
```
clang-format -style=file <SOURCEFILE> | diff <SOURCEFILE>  -
```
to just display what needs to be fixed.

**Comment by Barthelemy** [comment]
Definitely useful, I will add it.

**Comment by ktf** [comment]
Can you have a look at the codacy issues? I think they are genuine.

**Comment by Barthelemy** [comment]
To me it says that it is reviewing.

**Comment by Barthelemy** [comment]
@ktf I am not sure I agree with codacy : 

> [list-item-indent] Incorrect list-item indent: add 1 space
> 1. Build clang (to be done once)

The line 
`1. Build clang (to be done once)`  is valid according to https://commonmark.org/help/

I presume that it is a matter of configuration.

**Pull request merged**
