### PR TITLE
[O2-1338] Implement writing of TPC clusters found by ca-clusterer

### PR DESCRIPTION
**Pull request by matthiasrichter**
https://alice.its.cern.ch/jira/browse/O2-1338

Test sequence to produce the ca clusters and store in `tpc-native-clusters.root`
```
o2-tpc-reco-workflow --infile tpcdigits.root --output-type tracks,clusters --tracker-options "cont refX=83 bz=-5.0068597793 qa" --ca-clusterer
```

Run tracking from the stored clusters
```
o2-tpc-reco-workflow --input-type clusters --infile tpc-native-clusters.root --output-type tracks --tracker-options "cont refX=83 bz=-5.0068597793 qa"
```

The resulting tracks and qa blocks are from first glimpse identical.

### CODE REVIEW

**Comment by shahor02** [comment]
@matthiasrichter thanks, seems to work, but one has to enable sending clusters with rawZS input, could you apply this patch ?:
````
diff --git a/Detectors/TPC/workflow/src/RecoWorkflow.cxx b/Detectors/TPC/workflow/src/RecoWorkflow.cxx
index 2428e025b7f..93ac37bc212 100644
--- a/Detectors/TPC/workflow/src/RecoWorkflow.cxx
+++ b/Detectors/TPC/workflow/src/RecoWorkflow.cxx
@@ -102,8 +102,8 @@ framework::WorkflowSpec getWorkflow(std::vector<int> const& tpcSectors, std::vec
   if (inputType == InputType::Clusters && (isEnabled(OutputType::Digits) || isEnabled(OutputType::ClustersHardware))) {
     throw std::invalid_argument("input/output type mismatch, can not produce 'digits', nor 'clustershardware' from 'clusters'");
   }
-  if (inputType == InputType::ZSRaw && (isEnabled(OutputType::Clusters) || isEnabled(OutputType::Digits) || isEnabled(OutputType::ClustersHardware))) {
-    throw std::invalid_argument("input/output type mismatch, can not produce 'digits', 'clusters' nor 'clustershardware' from 'zsraw'");
+  if (inputType == InputType::ZSRaw && (isEnabled(OutputType::Digits) || isEnabled(OutputType::ClustersHardware))) {
+    throw std::invalid_argument("input/output type mismatch, can not produce 'digits' nor 'clustershardware' from 'zsraw'");
   }
 
   if (inputType == InputType::ZSRaw && !caClusterer) {
````

@rohr I've created 4 PbPb TFs each one 4 HBs long, the tracking works but I see strange track times for all TFs but the 1st one:
trtime
Some offset is set wrongly, shall I debug or you know where to look?

Finally, the workflow with input from raw data both for  ITS and TPC + their reco + matching now at least starts:
image
but reading the TPC clusters into the matcher device I get 
````
[29437:itstpc-track-matcher]: [13:59:42][INFO] TPCITSMatchingDPL 0 NLanes 36
[29437:itstpc-track-matcher]: [13:59:42][INFO] Reading lane 0 clusTPC0
...
[29437:itstpc-track-matcher]: [13:59:42][INFO] Reading lane 35 clusTPC35
[29437:itstpc-track-matcher]: [13:59:42][ERROR] Exception caught: Did not receive TPC clusters data for all sectors
````
It still uses the old way of fetching the TPC data, explicitly looping over the lanes set in advance, but it works when I run from TPC digits. Will need to dig out why.

**Comment by davidrohr** [comment]
@shahor02 : I'll have a look for the offset, shouldn't be too complicated.
And you used rohr not @davidrohr to tag me, but that is not me.

**Comment by matthiasrichter** [comment]
good, I will include your patch @shahor02

**Comment by matthiasrichter** [comment]
@shahor02 Regarding reading the clusters in the matching workflow, the format should be exactly the same as before. Can you send me the commands you are using for the TF generation and running the workflow.

**Comment by matthiasrichter** [comment]
Is the workflow with  itstpc-track-matcher a combination of multiple workflows, i.e. with tpc-reco-workflow. Then you need to specify `--output-type tracks,clusters` in the TPC reco workflow. But this can not be the problem as the workflow is generated and the input routes for the matcher are available.

But I do not see the cluster writer process in your screenshot. It's maybe some missing option, also for invoking tpc reco workflow from within another workflow (not merging on the command line).

**Comment by shahor02** [comment]
@matthiasrichter preparing raw data with short TFs (otherwise the TPC reco will die) requires a patch which is in https://github.com/AliceO2Group/AliceO2/pull/3408, so  put [here](https://cernbox.cern.ch/index.php/s/bBomO4cYR8N1qjh) the full data set you need, prepared as
````
o2-sim -n 10 -m PIPE ITS TPC TOF T0 -g pythia8 | tee sim.log
o2-sim-digitizer-workflow -b --run | tee dig.log
mkdir raw
o2-its-digi2raw --configKeyValues "HBFUtils.nHBFPerTF=4" -c -o raw
o2-tpc-digits-to-rawzs --configKeyValues "HBFUtils.nHBFPerTF=4" -i tpcdigits.root -o raw
cat raw/tpcraw.cfg raw/ITSraw.cfg > raw/Allraw.cfg
````

To reproduce the problem, untar it, go to ``pp10`` dir. then do:

1) Combined reconstruction/matching workflow, dies with 
``[ERROR] Exception caught: Did not receive TPC clusters data for all sectors``
You will see also lot of errors like 
``[ERROR] Expected orbit=256 but got 4 for 0-th HBF in TF#1 of ITS/RAWDATA/0x3360918577``,  ignore them, if just complains about non-standard TF size

````
o2-raw-file-reader-workflow --conf raw/Allraw.cfg  | o2-itsmft-stf-decoder-workflow |  o2-its-reco-workflow --disable-mc --clusters-from-upstream --disable-root-output  | o2-tpc-reco-workflow --ca-clusterer --input-type=zsraw --disable-mc  --output-type tracks,clusters,disable-writer | o2-tpcits-match-workflow  --disable-root-input --disable-mc
````

2) Same but with reconstruction and matching in different w-flows: works fine

````
o2-raw-file-reader-workflow --conf raw/Allraw.cfg  | o2-itsmft-stf-decoder-workflow |  o2-its-reco-workflow --disable-mc --clusters-from-upstream  | o2-tpc-reco-workflow --ca-clusterer --input-type=zsraw --disable-mc  --output-type tracks,clusters --tpc-track-writer "--treename events --track-branch-name Tracks"
````
````
o2-tpcits-match-workflow  --tpc-track-reader tpctracks.root --tpc-native-cluster-reader "--infile tpc-native-clusters.root" --disable-mc
````

**Comment by shahor02** [comment]
the cluster-writing in combined w/flow is disabled by ``disable-writer`` option, since the matcher should get the inputs directly from the TPC wflow (and merging wflows with writers/readers does not work well), but the result is the same if I run w/o ``disable-writer``

**Comment by matthiasrichter** [comment]
@shahor02 I found the problem, at the place where the clusters are published in the tracker, the activeSector variable is already reset, so this causes a mismatch on the receiver side.

**Comment by matthiasrichter** [comment]
fix is pushed, all processors of the merged workflow are now running in my local test with the provided test data. @shahor02 please check.

**Comment by davidrohr** [comment]
@shahor02 : I haven't fully understood the offset thing yet, but I believe the following is the case:
- The tracks with negative time0 are legitimate, they have clusters at the beginning of the TF and when extrapolated to the vertex, the vertex should be in the previous time frame.
- The first time frame has none / very few clusters with less than 500 time bins, therefore there are simply no such tracks by chance. This could be a digitization artifact?

Have to run some more tests to be sure.

**Comment by shahor02** [comment]
@davidrohr your explanation seems plausible, thanks! The 1st frams is 1st, by construction there are no tracks from the past, why would you expect them?

@matthiasrichter Thanks for the fix! Will check tomorrow.

**Comment by davidrohr** [comment]
@shahor02 : The explanation is plausible, but what I still didn't understand is why the distribution for the first TF starts at a value >> 0. I just digitized 1 single pbpb event with interaction rate = 3e7.
What I see is the very first nonempty time bin is ~450 in the tpc digits. Shouldn't there be hits in the TPC more or less directly after the start at such a high rate? 450 is almost a full drift time.
Or is this related to the bunch structure (e.g. abort gap) or do we have some offset in the digitization?

**Comment by shahor02** [comment]
@davidrohr The interactions sampling for digitization starts from orbit 1]. I did this (at the moment in [hardcoded]((https://github.com/AliceO2Group/AliceO2/blob/b1ca6d2e14592156e3ce588f0c41643fbd0bb87c/Steer/include/Steer/InteractionSampler.h#L32) to avoid problems with negative bc/orbit prior to 0/0 if some detector need to read some data prior the trigger. This is e.g. the case for ZDC which may read up to 3BCs before the triggered one.
Since the orbit will be set to 0 before starting the run, we anyway will never see it in the real data.

**Comment by davidrohr** [comment]
Thx, that explains my confusion.

**Comment by matthiasrichter** [comment]
If the merged workflows are running as expected I suggest we merge the PR, is this ok?

**Comment by shahor02** [comment]
@matthiasrichter I will check it once the meeting I am in now will be over, will reply asap.

**Pull request merged**
