### PR TITLE
FT0: updates on fuctions for event plane reconstruction

### PR DESCRIPTION
**Pull request by jikim1290**

### CODE REVIEW

**Comment by jikim1290** [comment]
My previous test was fully passed at some moments and the results of test were changed to failure without any error messages. I don't understand the issue and I re-made the pull request. I don't know how to resolve or understand to fix this with my local. The installation is surely SUCCEEDED in my local.

Please approve this for the test again and I will let you know

**Review by martenole — DISMISSED** [review]
approving to start the CI. Would be great if someone from FIT could also approve so that we can merge this when the CI is green

**Review by afurs — DISMISSED** [review]

**Review by afurs — APPROVED** [review]

**Comment by jikim1290** [comment]
> approving to start the CI. Would be great if someone from FIT could also approve so that we can merge this when the CI is green

Could you please approve this?
test for build/O2/o2-cs8 is failed however test for build/O2/fullCI is passed.

**Review by afurs — APPROVED** [review]

**Comment by afurs** [comment]
Looks like unrelated issue during QC tests. I guess this can be merged, @martenole am I right?

**Pull request merged**
