### PR TITLE
add track extras for run 2 + store SPD tracklet flag for free vs. shared clusters

### PR DESCRIPTION
**Pull request by maciacco**
@jgrosseo I reopened this PR with the proposed changes implemented. I changed the name of the new table to Run2TrackExtras to comply with the canonical format. I also have an updated version of the relative AliPhysics code ready

### CODE REVIEW

**Review by jgrosseo — DISMISSED** [review]

**Comment by jgrosseo** [comment]
Great. Will you create a new AliPhysics one or post in the existing one? We can then reopen it.

**Comment by maciacco** [comment]
I opened this one https://github.com/alisw/AliPhysics/pull/23640

**Comment by maciacco** [comment]
Dear @jgrosseo I modified a bit the PR removing the number of PID clusters in TPC from the new run 2 table. This way, it should be easier to integrate the changes done by Max. I am also preparing a PR in AliPhysics for this.

**Comment by maciacco** [comment]
@jgrosseo could we re-open and merge this PR since the relative one in AliPhysics was merged?

**Pull request closed without merging**
