### PR TITLE
CCDBApi: avoid leaking curl handle.

### PR DESCRIPTION
**Pull request by ktf**
CCDBApi: avoid leaking curl handle.

### CODE REVIEW

**Review by costing — DISMISSED** [review]

**Comment by martenole** [comment]
Hi @ktf 
thanks, this looks very good and if I run the FST with it the leak rate is strongly reduced. It seems the build checks are failing though, could you check please?
```
/sw/SOURCES/O2/13061-slc7_x86-64/0/CCDB/test/testCcdbApiDownloader.cxx(173): [1;31;49merror: in "asynch_schedule_test": check httpCode == 200 has failed[0;39;49m
```

**Comment by ktf** [comment]
I frankly think the test is wrong, but indeed it needs understanding. @costing could you cc Michal? I do not recall his handle.

**Comment by ktf** [comment]
Also the rest of the leak comes from the HTTPHEADER slist, however the way the code is currenlty structured, it's not easy to clean it up correctly.

**Comment by costing** [comment]
Adding @TrifleMichael

**Comment by ktf** [comment]
Updated with the fix for the remaining leak. I think the delete in the test should not be there, but someone should probably doublecheck the logic. With this, my reproducer does not show any leak whatsoever.

**Review by martenole — APPROVED** [review]
Looks good. I don't understand why the formatting check fails

**Comment by ktf** [comment]
I think it's some glitch on the github side, actually. The code formats fine locally.

**Pull request merged**
