### PR TITLE
DPL: automatically include --exit-transition-timeout

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
I assume this is only for the FLP?
In general, I think we should also enable it for the EPN. Couldn't we make the default depend on the QuitPolicy?
I.e., when the Policy is quit, like in the DPL driver by default, we don't need it.
And when the policy is wait, like with DDS/ECS (I assume it is like that), we have the timeout by default?
Is the waiting for EoS fixed in the meantime?

**Comment by ktf** [comment]
Mmm.. No, the GUI uses the wait policy as well. What really makes the difference is being run alone vs being run with the driver. Maybe I should add way to notify that to the executable.
The issue with the EoS is still there, because the readout-proxy is not really the first device in the chain (because the channel is managed out of bound) so I am still trying to see how to handle that.

**Review by knopers8 — COMMENTED** [review]
In principle the PR seems correct, but won't it put `--exit-transition-timeout` twice if it is also added to a workflow command explicitely?

**Comment by ktf** [comment]
Closing this in favour of #8245.

**Comment by ktf** [comment]
@knopers8 as discussed elsewhere.

**Review by knopers8 — DISMISSED** [review]
thank you

**Comment by ktf** [comment]
Test fixed and tested locally. Merging to get it in the build.

**Pull request merged**
