### PR TITLE
adding infologger

### PR DESCRIPTION
**Pull request by sy-c**
This adds infologger support to AliceO2:
find.cmake, bucket, example usage & test

### CODE REVIEW

**Comment by dberzano** [comment]
Hi @sy-c, note that `clang-format` is complaining (see the Travis CI Details). It also suggests you what changes to apply in order to comply:

```
Running clang-format-3.9 against branch dev, with hash 0dc15c779917ff8486f1303dfc8bcbebcc42d6de
clang-format failed.
To reproduce it locally please run
	git checkout dev
	git-clang-format --commit 0dc15c779917ff8486f1303dfc8bcbebcc42d6de --diff --binary /usr/local/clang-5.0.0/bin/clang-format
diff --git a/Framework/Core/test/test_InfoLogger.cxx b/Framework/Core/test/test_InfoLogger.cxx
index 597fc4a..e287f6d 100644
--- a/Framework/Core/test/test_InfoLogger.cxx
+++ b/Framework/Core/test/test_InfoLogger.cxx
@@ -16,15 +16,15 @@
 #include <InfoLogger/InfoLogger.hxx>
 using namespace AliceO2::InfoLogger;
 
-BOOST_AUTO_TEST_CASE(InfoLoggerTest) {
- 
+BOOST_AUTO_TEST_CASE(InfoLoggerTest)
+{
+
   // define infologger output to stdout, as we don't want to use the default infoLoggerD pipe which might not be running here
   setenv("INFOLOGGER_MODE", "stdout", 1);
-  
+
   // create the infologger interface
   InfoLogger theLog;
-  
+
   // log a test message
   BOOST_CHECK(theLog.log("This is a log message test to stdout") == 0);
-  
 }
```

Can you please take care of it? Thanks!

**Comment by sy-c** [comment]
sure, I will include it in the fix!

**Comment by sy-c** [comment]
Dear reviewers,
the macos build has been fixed with https://github.com/alisw/alidist/pull/1276
and the formatting updated.
But it seems there's now a new requirement about build/o2checkcode/o2 which was not there when the PR was created. The detailed logs point to imgui.h ,which is outside the scope of this PR.

I noticed though this one:
InfoLogger.hxx:289:25: error: field declaration 'pImpl' does not match naming rule [aliceO2-member-name]

Not sure about how to proceed... can you please comment?

**Comment by ktf** [comment]
I think it needs to be `mImpl`, not `pImpl`.

**Comment by sy-c** [comment]
ok, rebased done

**Comment by sy-c** [comment]
test looks almost ok now,
only this one is failing: 	 90 - test_Framework_test_ProcessorOptions (Timeout)

**Comment by dberzano** [comment]
Hi @sy-c, it looks it wasn't properly rebased. I have done it for you, it should be OK now. Let's wait once more for the tests 🙂

p.s. the test you mentioned should be unrelated to your PR.

**Comment by sy-c** [comment]
now it's a segfault in 	 77 - test_Framework_test_SimpleRDataFrameProcessing (Timeout)

**Comment by ktf** [comment]
I would say that's unrelated. Merging this.

**Pull request merged**
