### PR TITLE
Use FairLogger standalone package in Detectors/TPC

### PR DESCRIPTION
**Pull request by ktf**
Usage of `FairLogger.h` from FairRoot has been deperecated in favour of
`fairlogger/Logger.h` from the standalone
https://github.com/FairRootGroup/FairLogger package.

### CODE REVIEW

**Comment by rbx** [comment]
Take note that logger in FairRoot would handle FATAL log message by printing the message, calling gSystem->StackTrace() and aborting the execution. In the recent FairRoot version it is now exception throw instead of abort.

If you want this behavior with fairlogger (personally I hope you don't), you would need to call the fair::Logger::OnFatal(std::function<void()>) to set the callback with what you want to happen in Fatal case.

**Comment by rbx** [comment]
Also you can/should use lower case severity levels to avoid confusion with MACRO NAMES. E.g. LOG(error) instead of LOG(ERROR).

**Comment by sawenzel** [comment]
@ktf: For a start, could you please edit the titles of all related PR to something more distinguishable? Otherwise, it will be hard to see the impact and whom to ask for review.

I am a little worried about the comment from @rbx. I believe we use the (FATAL) feature in a few places. This would need more thinking and more work.

**Comment by ktf** [comment]
@rbx @sawenzel: I will update my script to:

* Use lowercase verbosity names.
* Not touch files which have LOG(FATAL) in it.
* Update the PR name to take the Detector into account.

Anything else?

**Comment by ktf** [comment]
@sawenzel @rbx I updated all the PRs as discussed. As said elsewhere we probably should have a separate effort to change LOG(FATAL) to actual `throw`s.

**Comment by sawenzel** [comment]
I have more worries (maybe to be answered by @rbx). 
In the simulation I was using the fact that FairLogger::GetLogger() is a singleton (for instance to set the log severity once at the beginning of simulation). If I now change the logger header in some places and not in others (where we use FATAL) ... what will be the behaviour? Is there still the guarantee that behind the scene the same singleton is used?

Also, I would be in favour of doing a single atomic change instead of many PRs, in order not to have inconsistent intermediate states and to make rolling-back easier in case there are problems.

**Comment by ktf** [comment]
@sawenzel My hope was that the many PR would converge quicker than a single one. That said I can of course have a single PR / commit.

Regarding the GetLogger(), we indeed need to get rid of those and replace with the corresponding static methods in the new API. I can update my script to do that as well.

**Comment by rbx** [comment]
@sawenzel There should be no problem mixing the calls to the FairRoot version and FairLogger library directly. The severity setting is just passed through to the FairLogger library, which stores it as a static variable. But just to be clean I would advise to get rid of calls to the singleton, it doesn't add any value as it is now.

The only real difference is the handling of the fatal call. I recommend letting logger do the logging, and if you really want to abort after the fatal log message, or do anything else, then do it in code afterwards. Or wrap the whole thing in your own `Fatal()` method. In fact I imagine this is where this whole idea of exiting on fatal comes from - ROOT has `Fatal()` method, which prints and exits. But `LOG(fatal)` should only log.

**Comment by ktf** [comment]
@rbx That said, I think I've managed to remove all the `GetLogger()` as well. Can you please confirm the mapping to the static functions is the correct one?

@sawenzel: In line of principle the only remaining issue is the LOG(FATAL) now. My changes do not affect any file which uses LOG(FATAL), so I think it should be safe to merge the PRs, provided they compile. Alternatively, I can introduce an exception class which behaves like a ostream, and we could replace all the LOG(FATAL) with it.

**Comment by rbx** [comment]
@ktf The mapping in this and in other PRs is correct.

**Pull request closed without merging**
