### PR TITLE
ParticleDatabase: Update Lambda(1520) info according to the latest Pythia8

### PR DESCRIPTION
**Pull request by BongHwi**
The PDG code of Lambda(1520) has been updated from `3124` to `102134`.

https://pythia.org/manuals/pythia8308/ParticleData.html

Accordingly, I updated the particle information on the O2 and O2DPG for the injection production.

https://github.com/AliceO2Group/O2DPG/pull/1534

The BR and decay modes are also updated based on the values in the pythia8.

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@BongHwi Thanks for following up on this.
Just to clarify: When you say you took the decay-related info from the Pythia manual, shouldn't the actual source be something like the PDG?
But I'd assume that the Pythia authors use that as a source anyway.

**Comment by BongHwi** [comment]
Actually, the main decay channel that we use is almost the same (22.3% -> 23%) but it includes more decay channels including gamma and consistent with the latest PDG table. The B.R. is usually corrected regardless of this value at the analysis level.
To be honest, I don't think we'll use the updated channels, but I wanted to keep the same information with the pythia8 to prevent any confusion in future.

**Review by benedikt-voelkel — DISMISSED** [review]

**Comment by benedikt-voelkel** [comment]
The failed CI is unrelated. Can we merge this @sawenzel ?

**Comment by BongHwi** [comment]
It looks like it takes a little bit delay to merge this PR.
Can I add some other commits here meanwhile? @benedikt-voelkel

**Comment by benedikt-voelkel** [comment]
Fine with me of course.
Let me know when you are done and then we can merge it; probably today!

**Comment by BongHwi** [comment]
Done! @benedikt-voelkel

**Review by benedikt-voelkel — APPROVED** [review]

**Comment by BongHwi** [comment]
+async-label async-2022-pp-apass6-2023-PbPb-apass2

**Comment by BongHwi** [comment]
+async-label async-2022-pp-apass4,async-2023-pbpb-apass3

**Pull request merged**
