### PR TITLE
Importing AliRawReader related classes from AliRoot in dedicated Legacy module

### PR DESCRIPTION
**Pull request by matthiasrichter**
Starting the Legacy module and importing AliRawReader related classes from AliRoot. This will allow to access Run1/2 raw files within Alice O2

### CODE REVIEW

**Comment by sawenzel** [comment]
I believe this will (for sure) not be accepted by the code checker. So we should add a way to make the codechecker spot legacy code (or add a simple filter in the o2checkcode recipe). I prefer that this be done before merging this in order to keep a clean state.

**Comment by matthiasrichter** [comment]
That is expected. We have been discussing previously that such code should be in a specific module, thus the `Legacy` module. So that's the first call for that scheme.

Lets keep the open as a reminder and merge when the functionality is in place.

**Comment by sawenzel** [comment]
@ktf: Do you know why the log above does not point to the concrete codecheck error?

**Comment by matthiasrichter** [comment]
I think the bot uses the wrong log file when it tries to extract the error, see here
https://github.com/alisw/ali-bot/issues/441

**Comment by aphecetche** [comment]
Hi,

Don't know exactly how to articulate this but I feel feeding the AliceO2 repo with "bare" AliRoot code is wrong somehow. Because I believe it's easier to _add_ code than to _remove_ it afterwards...

I clearly understand that we need _now_ some functionality that is currently not in AliceO2 but is in AliRoot, for instance the raw data reading (of Run2 data). 

But can't we take another route ? I mean, instead of having AliceO2 absorbing bits and pieces of AliRoot (even in "legacy" modules), can't we have separate repository(ies) which depends _both_ on AliRoot and O2 and thus act as the glue between the two (e.g. having O2 devices reading Run2 data with RawReader) ? Glue which will be simply dropped as soon as the functionality is integrated into AliceO2 proper or not needed anymore.

I should add that this is the route we've taken in the muon group, but admittedly with a __very__ limited scope so far (a few HLT-like components, see https://github.com/mrrtf/alo). So maybe I'm just underestimating what it would take to generalize this, but maybe that's worth considering still ?

Regards,

**Comment by matthiasrichter** [comment]
Hi Laurent, you have a very valid point and one has to think twice. Earlier this year, we have discussed briefly  how to handle legacy code, but maybe there was no final conclusion. And there are probably more opinions.

In this particular case the code will never evolve into some O2 code because it's just a tool to access old raw files. And it does not make any sense to write new code. It could be of course in a separate repository, I see the advantage of this. However I was hesitating to set it up and I don't see anybody who will have time to set it up and maintain it. Sure, the work is limited since we have a working build system and adding a new recipe is probably easy. Still I'm expecting glitches and we continue of bloating the list of sub-repositories.

I can also add some glue code in AliceO2 which uses the AliRoot libraries and which is conditionally compiled.

So there are multiple solutions with individual pros and cons. I do not insist on any particular one.

**Comment by Barthelemy** [comment]
One option that we also considered, along with the rest, is to have a dedicated namespace "legacy" for it. I would be in favour of using it here. It is a minimal change to the code. I don't have a strong opinion on the way to handle the legacy code. I understand your feeling, Laurent.

**Comment by sawenzel** [comment]
@Barthelemy : There is one advantage to the "legacy" folder: Disabling code checks can be done much easier. For namespaces we would have to encode/query this in each check.

**Comment by Barthelemy** [comment]
@sawenzel : yes, I see. I was thinking of doing both, ie. to add a namespace to the classes in the Legacy folder. but maybe it is an overkill.

**Comment by mkrzewic** [comment]
@Barthelemy @sawenzel i think both would be good - one of the options we were discussing was having legacy code in the legacy namespace and only allowing complying wrappers to be used in O2 code. Direct use of legacy:: is then easy to catch anywhere...

**Comment by matthiasrichter** [comment]
I agree, a dedicated legacy namespace would be mandatory.

**Comment by aphecetche** [comment]
Agree a Legacy folder + legacy namespace would be best for the code we have to integrate into O2.

Still, on this specific case, as far as I understand the code would just be "swallowed" by O2, i.e. there's no new feature added (except for the unit test (*)). Of course, without seeing how this code is supposed to be used, it's difficult to say for sure, but I'd maintain it does not look a good fit for an import. 

(*) which brings another question : where to store the input files that may be (like in this one) needed by our (automatic) tests ?

**Comment by ktf** [comment]
Actually the requested changes seems to be trivial and in principle it should be possible to clean them automatically. I've documented how to run the code checker / fixer in #364 . Can you at least give it a try and check if this does not correct all issues?

**Comment by sawenzel** [comment]
Is there any news on this PR?

**Comment by ktf** [comment]
I would personally still give a try to use the automatic fixing of code conventions violations.

**Comment by mkrzewic** [comment]
Hi all, regarding injecting run2 raw data into O2 chain: why not use the zeromq functionality we already have in AliRoot in the HLT module? If Aliroot is built together with O2 (which seems to be the preferred case) the HLT ZMQ "devices" are accessible - they speak the O2 dialect (using zeromq only) and would be easy to use as data sources. There is no device that reads the RAW files, but it is trivial to make. That way we would not have to introduce this part of code into O2 for that specific purpose. I imagine a lot of other cases would be possible too.

**Comment by matthiasrichter** [comment]
This PR has triggered a lot of discussions with many valid points. Let me summarize:
1. we still need to discuss whether we want to handle legacy code in one or the other way
2. there are different approaches how to handle imported code from external packages, some of us prefer to keep it as close as possible to the original, some prefer to adjust it to guidelines and conventions
3. the particular development was triggered by an early discussion whether we could use the available data for testing, but it is probably not so relevant any more
4. there are possible other ways for publishing the data
5. the code will stay in the fork and is going to be maintained. We can reopen whenever we see the need to have it

Following the summary I close the PR.

**Pull request closed without merging**
