### PR TITLE
[FDD] TCM trigger signals added to Simulation

### PR DESCRIPTION
**Pull request by arvindkhuntia**

### CODE REVIEW

**Comment by arvindkhuntia** [comment]
Hi @andreasmolander, please approve this one.

**Comment by arvindkhuntia** [comment]
Hi @afurs Could you please approve it, I came to know Andreas is off due to fever. Thanks.

**Review by afurs — APPROVED** [review]

**Comment by sawenzel** [comment]
In which way is this PR different to #11862 ? It would be preferable to do improvements on the original one. But you may also close the other one and make a reasonable PR title/description here.

**Comment by arvindkhuntia** [comment]
Hi @sawenzel, please merge this PR. Thanks.

**Pull request merged**
