### PR TITLE
ITS tracker: Reserve output buffers

### PR DESCRIPTION
**Pull request by mconcas**
As a follow-up to #12078

### CODE REVIEW

**Comment by mconcas** [comment]
@shahor02

**Review by shahor02 — CHANGES_REQUESTED** [review]
Thanks, but why not using `make<>` and `reseve...` for all outputs. For the conditional MC output you can do like this: https://github.com/AliceO2Group/AliceO2/blob/f23de2b600bc249f1cd1470138e17ae943a8fca6/Detectors/GlobalTrackingWorkflow/src/TPCITSMatchingSpec.cxx#L110

**Review by shahor02 — CHANGES_REQUESTED** [review]
Thanks, but the CI errors are genuine, there are redefinitions.

**Comment by mconcas** [comment]
> Thanks, but the CI errors are genuine, there are redefinitions.

should be fixed now

**Pull request merged**
