### PR TITLE
Adding TPCSpaceChargeBase library built from AliTPCCommon rep.

### PR DESCRIPTION
**Pull request by ehellbar**
Adding TPCSpaceChargeBase bucket and adding it to tpc_simulation_bucket requirements. Modifying TPCSimulation build to link TPCSpaceChargeBase library from AliTPCCommon repository.

### CODE REVIEW

**Comment by davidrohr** [comment]
I have tested the build here locally and it works.
TPC code is integrated from AliTPCCommon in the same way as the TPC CA Tracking.
From my side we can merge this.

**Comment by ehellbar** [comment]
The test build failed due to errors/warnings in TPCSpaceChargeBase classes in AliTPCCommon. I fixed these issues and committed them to AliTPCCommon, but did not request a new tag. In order for the build errors to be solved, we need a new AliTPCCommon tag. David, can you do this?

**Comment by davidrohr** [comment]
@ehellbar : I'll create a new tag.
Let me have a look first, I think some of my changes are still incompatible with current AliRoot again, so I guess I will create a tag that will just cherry-pick your fix.

**Comment by davidrohr** [comment]
@ehellbar : I do not see a new commit in AliTPCCommon, are you sure you pushed it?

**Comment by ehellbar** [comment]
Hi @davidrohr , it's commit c5c94009671d072ca36b5b223894d83ecf46e96c from July 16 on the master branch, "Fixing string literal warnings during compilation in ROOT Info and Error messages".

**Comment by davidrohr** [comment]
Oh, sorry, how obvious, I was looking for something more recent...
tag is on its way.

**Comment by davidrohr** [comment]
for reference: alisw/alidist#1232

**Comment by davidrohr** [comment]
@ehellbar : The AliTPCTommon tag is in alidist now. Can you do git --amend and git force push to your branch, to trigger a new CI test.

**Comment by davidrohr** [comment]
@sawenzel  @matthiasrichter : The compile warnings are fixed now with the new AliTPCCommon tag. This PR enables the build of additional classes from AliTPCCommon for O2. Can you have a look and approve it.

**Pull request merged**
