### PR TITLE
Optionally extract GBT calib data with digits, unify ITS/MFT digits readers

### PR DESCRIPTION
**Pull request by shahor02**
* o2-itsmft-stf-decoder-workflow, when called with option --enable-calib-data together with --digits,
will produce (apart from digit vector) also a vector  with GDB calibration words extracted from the
raw data (if any, otherwise 0s). The words (see struct GBTCalibData) will be stored per RU and per
ROF, i.e. for every ROF stored the vector will get extra N_RU entries. In order to write these data into
the digits tree, the writer should be also called with the same option, i.e.
````
o2-itsmft-stf-decoder-workflow --enable-calib-data --digits | o2-itsmft-digit-writer-workflow --enable-calib-data --disable-mc
````
(ITS case, add `--runmft` to every workflow to run it for MFT).

*  The separate DigitReaders in the ITS/workflow and MFT/workflow are suppressed, instead common
ITSMFT/common/workflow/DigitReaderSpec added. In opposite to deleted workflows, it supports reading trees with multiple entries

* To read the calibration data, one should supply similar option to the reader:
````
o2-itsmft-digit-reader-workflow --enable-calib-data --disable-mc
````

### CODE REVIEW

**Comment by shahor02** [comment]
@arakotoz, @mcoquet642, this PR (when used with latest ChipMappingMFT) should provide the same info as https://github.com/AliceO2Group/AliceO2/pull/5686, but in ITS/MFT unified way:
this structure https://github.com/shahor02/AliceO2/blob/7d993653dc1929373d4abc04046a2386f91c8480/DataFormats/Detectors/ITSMFT/common/include/DataFormatsITSMFT/GBTCalibData.h#L23-L24 is filled for every RU like here: https://github.com/shahor02/AliceO2/blob/7d993653dc1929373d4abc04046a2386f91c8480/Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/GBTLink.h#L266
and can be stored in the digits file as an additional branch <DET>Calib.

Please let me know if you see some problem with using such info.

**Comment by arakotoz** [comment]
@shahor02 Thanks a lot for your fast reaction and writing of this PR. It will be very useful indeed. We will try it, and let you know the outcome.

**Comment by bovulpes** [comment]
I have checked on a a file from an analog scan (/eos/project/m/mft/WP8_Commissioning/data/p2/h1/analog/data-d0-2021_03_04__17_26_26__-20491-0.raw) and it works. For a total of 5110 ROFs I have 408800 entries in the tree MFTCalib, which corresponds to the nr of TFs (511, extracted from the RDH), times the number of ROFs per TF (10 pulses), times the number of RUs (80). As only one RU is active, I see the counter going 511 times from 0 to 9 and the value of the user fields, the same for all (0x0000000a00aa). For the other 79 RUs the values accumulate in zero.

**Review by bovulpes — DISMISSED** [review]

**Comment by mcoquet642** [comment]
Hello @shahor02, @bovulpes, thank you for this. We tested these features on a file from a noise scan (/eos/project/m/mft/WP8_Commissioning/data/p2/both/noise/bb0/raw/data-2021_03_12__16_24_08__-20490-0.raw) and got some strange output in the digits : there are some entries with a ChipIndex from 10000 upto 60000. This happens whether or not we use the `--enable-calib-data` option. Could you test this file yourself to check if we are doing some wrong ?

**Comment by shahor02** [comment]
Hi @mcoquet642, I have no access to this directory, could you compress this file and put somewhere publicly available?

**Comment by mcoquet642** [comment]
@shahor02 Sorry about this, here is a link : https://cernbox.cern.ch/index.php/s/qW50J6O7jcqMdiJ
The command we used for decoding is the following : `o2-raw-file-reader-workflow -b --nocheck-missing-stop --nocheck-starts-with-tf --nocheck-packet-increment --nocheck-hbf-jump --nocheck-hbf-per-tf --detect-tf0 --configKeyValues "HBFUtils.nHBFPerTF=128" --input-conf MFTraw.cfg | o2-itsmft-stf-decoder-workflow -b --enable-calib-data --runmft --digits --no-clusters --no-cluster-patterns | o2-itsmft-digit-writer-workflow -b --enable-calib-data --runmft --disable-mc --outfile out.root`

**Comment by shahor02** [comment]
@mcoquet642, indeed, there was a bug in creating conditional DPL output using more economic `make<>` mechanism. At the moment reverted to old `snapshot` mechanism, now the digits are identical to that produced with old code.

**Comment by arakotoz** [comment]
@shahor02 Thanks for the cross-check and finding quickly the fix! We will try and will report at the start of next week if we see anything strange again.

**Comment by mcoquet642** [comment]
Hello @shahor02, I tried to check again the decoding with the same file as before (using a build of https://github.com/shahor02/AliceO2/tree/pr_ITSMFTCalib_XXX ) and the problem in mentioned seem to remain. Is this expected ? It seemed to work fine for me when reverting to the old DPL output method in STFDecoderSpec ( https://github.com/MFTDecoding/AliceO2/commit/b3f6da3e78f323d9a149e14e329c2ab1b52ae451 ). Thank you in advance.

**Comment by shahor02** [comment]
Hi @mcoquet642 you should not have used https://github.com/shahor02/AliceO2/tree/pr_ITSMFTCalib_XXX, it was created exactly as reproducer for the bug you have indicated (which appeared to be a problem on the FairMQ side, now fixed but did not yet propagate to O2).
You should use the branch of this PR, but it got conflict after I've merged https://github.com/AliceO2Group/AliceO2/pull/5786 which affects also the decoder. Will fix the conflict in a hour or two.

**Comment by mcoquet642** [comment]
@shahor02 I see, thanks a lot for the quick answer. We will wait for the resolution.

**Comment by shahor02** [comment]
@mcoquet642 took longer, sorry. Now should work.

**Comment by arakotoz** [comment]
@shahor02 Thanks for the update. Will now build and try.

**Comment by mcoquet642** [comment]
Hi @shahor02, thanks a lot for the fix. We confirm that now the decoding works as expected on our side, including calibration informations.

**Comment by shahor02** [comment]
Thanks for checking @mcoquet642! The fullCI failure is unrelated, merging.

**Pull request merged**
