### PR TITLE
Add pythia8_userhooks_charm.C to the list of not tested macro for e.g…

### PR DESCRIPTION
**Pull request by aphecetche**
…. o2-dataflow

Should fix the issue in https://github.com/AliceO2Group/QualityControl/pull/338

### CODE REVIEW

**Comment by Barthelemy** [comment]
Testing on my machine

**Comment by Barthelemy** [comment]
With the second macro it passes the configuration.

**Comment by Barthelemy** [comment]
mmm, not sure why the o2 build fails.

**Comment by ktf** [comment]
o2 build was a machine issue, apparently. Merging.

**Pull request merged**
