### PR TITLE
Executable to retrieve the CCDB entries for the Milestone Week 2

### PR DESCRIPTION
**Pull request by chiarazampolli**
Adding also a fix for the TOF macro to generate the CCDB DCSconfig
entry.

### CODE REVIEW

**Review by shahor02 — COMMENTED** [review]
Hi @chiarazampolli 
I've realized, that in order to profit from the CCDB cache, we should use for reading the BasicCCDBManager, rather that CcdbAPI directly.
Could you please change this? I would also add an option to disable (enabled by default) caching, via ``BasicCCDBManager::setCaching(bool)``

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

Done. A (general, out of the scope of this PR) question: the CCDBManager does not allow to retrieve an object through the Metadata, right?

Chiara

**Comment by shahor02** [comment]
@chiarazampolli right, but there is no particular reason for that, I can add a method allowing metadata.

**Comment by chiarazampolli** [comment]
Hi Ruben,
It is not for this use case, but it could be that we need to query an object using the metadata. 
Thanks!
Chiara

**Comment by chiarazampolli** [comment]
The test complain that some things defined in populateCCDB.C are not defined in the retrieveFromCCDB.C macro:

```
In file included from input_line_106:1:
/mnt/mesos/sandbox/sandbox/o2/O2/Detectors/Calibration/testMacros/retrieveFromCCDB.C:24:33: error: use of undeclared identifier 'CCDBObj'
void retrieve(const std::vector<CCDBObj>& objs, float procTimeSec, std::mutex& mtx, std::atomic<int>& n, size_t tfID);
                                ^
/mnt/mesos/sandbox/sandbox/o2/O2/Detectors/Calibration/testMacros/retrieveFromCCDB.C:31:15: error: use of undeclared identifier 'readObjectsList'
  auto objs = readObjectsList(fname);
              ^
```

shouldn't it be enough to include the "populateCCDB.C" macro?
Locally things work, I don't know how the test is run exactly, or I would try to reproduce the error.

**Comment by shahor02** [comment]
@chiarazampolli this is becuse in non-compiled test the ``#include populateCCDB.C`` is guarded by ``#if !defined(__CLING__) || defined(__ROOTCLING__)``, it should go after this guide. I've fixed a few other problems, will open a PR in your repo.
But at the moment I am getting segm. violation when reading via BasicCCDBManager, looks like again related to threads.

**Comment by chiarazampolli** [comment]
Hi Ruben,

Thanks!! i tried with the manager, before committing, and it was working. I can check again tomorrow.

Chiara

**Comment by shahor02** [comment]
You were simply lucky: it was crashing because the retrieved object was deleted while it was owned by the CCDBManager.
I've opened a PR in your repo.

**Comment by chiarazampolli** [comment]
Hi @shahor02 ,
Now I see the error too, I did not let it run enough... 
I will merge your PR, thanks for taking care.

**Comment by chiarazampolli** [comment]
Hi @shahor02 , 

I think you forgot to include in the PR the CMakelist. I can create it myself, unless you commit it before I am done.

Chiara

**Comment by chiarazampolli** [comment]
Done. Let's see if now it works.

**Comment by chiarazampolli** [comment]
So far, errors in CI and macOS seem unrelated to the PR.

**Comment by shahor02** [comment]
@chiarazampolli indeed, forgot to add the [CMakeLists.txt](https://github.com/AliceO2Group/AliceO2/files/5950461/CMakeLists.txt), it had also files installation, could you please add it?

**Comment by chiarazampolli** [comment]
Done!

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
