### PR TITLE
[WIP] Data Sampling

### PR DESCRIPTION
**Pull request by knopers8**

### CODE REVIEW

**Comment by knopers8** [comment]
Is there a way to stop that boring troll?

**Comment by ktf** [comment]
@knopers8 I think the problem is that you need to rebase on top of the latest dev commit. If you have troubles I can try to help you out later today.

**Comment by knopers8** [comment]
@ktf I think it calmed down, thanks. But still, could you please help me solve the problem of alibuild failing the checks because of Configuration?

**Comment by ktf** [comment]
@knopers8 the compilation issue is now gone. Can you check the segmentation fault? You should be able to reproduce it with `ctest -R test_Framework_test_DataSampling` I suspect you depend on some configuration file which is not there.

**Comment by ktf** [comment]
Merging this. We can iterate further as we go on with the exercise.

**Pull request merged**
