### PR TITLE
[EMCAL-610] Raw encoder for EMCAL

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Work in progress - don't merge yet!

**Comment by shahor02** [comment]
@mfasDa this PR is stalled and has conflicts. What is the status here?

**Comment by mfasDa** [comment]
@shahor02 After https://github.com/AliceO2Group/AliceO2/pull/2583 I will rebase this to dev in order to resolve the merge conflicts, and then it can be merged. The PR mentioned above only needs minor polishing.

**Comment by mfasDa** [comment]
After the merge of #2583 I rebased and fixed the merge conflicts. It should compile now. @shahor02 after the build test would it be possible to merge the PR?

**Comment by shahor02** [comment]
@ktf @MichaelLettrich the Travis CI seems to fail for internal reasons...

**Comment by ktf** [comment]
Running again.

**Comment by mfasDa** [comment]
Build errors are not related to this PR.

**Comment by shahor02** [comment]
@mfasDa  the macos errors are indeed unrelated, but those in Travis CI are, please fix them then I will merge.

**Comment by mfasDa** [comment]
The crash is not related to this PR

**Pull request merged**
