### PR TITLE
GPU: test SMatrixGPU with OpenCL2.0

### PR DESCRIPTION
**Pull request by mconcas**
This will test if the SMatrixGPU.h implementation also works with new OpenCL 2 compiler in fullci.

### CODE REVIEW

**Comment by davidrohr** [comment]
@mconcas : Seems to break also with clang 13. I'd suggest you open a bug report on https://bugs.llvm.org/ for the OpenCL component of clang, just to trigger them to fix it in the future. Then we'll see whether this is fixed quickly, or whether we'll need to find a workaround for us.

**Comment by mconcas** [comment]
@davidrohr: welI, I'll need to provide a reproducer.
This will take some time, as I also don't have opencl on my workstation (I'll use the container).

Concerning the issue itself, according to your experience, do you think opencl has something only with pointer to functions or is it something more critical?

I was just wondering if that specific single function i want to pass could be encapsulated as some class' member function. Then I'd pass the class instance...
Still quite clean approach, or not?

**Comment by davidrohr** [comment]
@mconcas : OK, I understand. Please note: we moved the container to alisw, so please use alisw/slc8-gpu-builder, and no longer davidrohr/slc8-gpu-builder!

I assume it has to do with the function pointer, if you pass a class it might work. I think that would still be fine for us. But in any case, the problem should reported, such that they can fix it eventually.

**Comment by mconcas** [comment]
@davidrohr for the moment I tried switching to a functor. I also pulled the fullci container already, but I guess the CI will be anyways faster than me.
Will file a report to llvm as soon as I can.

**Comment by davidrohr** [comment]
Thx, looks good and works also with OpenCL 2. Merging. Please follow up a bug report to clang offline. If you have issues reproducing it in the container and producing a reproducer you can ping me.

**Pull request merged**
