### PR TITLE
Read SimParams from CCDB; clear CluElements; 

### PR DESCRIPTION
**Pull request by peressounko**
protection against corrupted samples in FitterGS

### CODE REVIEW

**Comment by peressounko** [comment]
fullCI failed due to "No space left on device" - test should be restarted

**Comment by peressounko** [comment]
Dear @shahor02 , @sawenzel could you please  have a look at this PR and probably trigger another attempt of fullCI test?

**Review by shahor02 — DISMISSED** [review]
@peressounko changes for the ConfigurableParam / CCDB are fine, cannot comment on algorithmic details. 
To trigger new CI, could you push some dummy commit (but it will anyway redo the CI in a while).

**Comment by peressounko** [comment]
dear @shahor02, now all checks passed, could you approve once more?

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
