### PR TITLE
Use make_unique rather than unique_ptr

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Checking the codechecker..

**Comment by mkrzewic** [comment]
btw. looks like the patch has a nasty memory leak.

**Comment by ktf** [comment]
Not really the patch, but the original code itself, right? For what is worth, that's the least of the problems since it actually SIGABRT.

**Comment by mkrzewic** [comment]
well, sure. i meant: make_unique already does the resource allocation and simply forwards the arguments to the ctor - so if you pass a "new T" to it it might only compile if you have a copy ctor that takes a pointer and leave the heap based instance of T dangling.

**Comment by ktf** [comment]
indeed, and not sure how could it have worked.

**Pull request closed without merging**
