### PR TITLE
Fix logs

### PR DESCRIPTION
**Pull request by chiarazampolli**

### CODE REVIEW

**Comment by chiarazampolli** [comment]
I don't know why I closed https://github.com/AliceO2Group/AliceO2/pull/4082#event-3617760950... Anyway, @davidrohr , @noferini , here it is.

**Comment by chiarazampolli** [comment]
@shahor02 , I followed your suggestion in the PR #4082 (no idea why I had closed it...).

**Review by davidrohr — DISMISSED** [review]
thx, looks good. Apparently clang-format wants some white space changes :)

**Comment by chiarazampolli** [comment]
I will fix it later, i am out of office in principle:-) But i will do it before tomorrow-then i will leave to holidays.

**Comment by chiarazampolli** [comment]
Done. Let's see.

Chiara

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
