### PR TITLE
TPC sac: implementation in O2

### PR DESCRIPTION
**Pull request by chiarazampolli**
Goes with https://github.com/AliceO2Group/O2DPG/pull/681
@davidrohr , @matthias-kleiner , @rmunzer

### CODE REVIEW

**Review by davidrohr — CHANGES_REQUESTED** [review]
I would propose we merge the aggregator workflows for IDCs and SACs in one. No need to deploy this as 2 collections.
Background is a bit: If we want this TPC stuff on an isolated EPN calib node, which is currently enforced by requesting 128 cores for the collection, we cannot split it in 2 collections.

**Comment by chiarazampolli** [comment]
Ciao @davidrohr , 
Ok, I will change this. 
Chiara

**Comment by chiarazampolli** [comment]
Note, though, that currently there is the possibility to have IDC_A and IDC_B separately. Should this also disappear? Or should I add the SAC to the `AGGREGATOR_TASKS == TPCIDC_BOTH`?

**Comment by davidrohr** [comment]
> Note, though, that currently there is the possibility to have IDC_A and IDC_B separately. Should this also disappear? Or should I add the SAC to the `AGGREGATOR_TASKS == TPCIDC_BOTH`?

I would add it for TPCIDC_BOTH, since that is what we'll use in the long run. Once we have the TPCIDC running, we should also remove the obsolete individual IDC_A and IDC_B. Perhaps for now we can leave them for testing.

**Comment by chiarazampolli** [comment]
@davidrohr , can you check my second commit? Note that I added also some changes to calib-workflow.sh, because I think the output proxy should be added to the EPNs only if we are not calibrating via FLPs.

**Comment by davidrohr** [comment]
didn't try, but looks correct

**Comment by chiarazampolli** [comment]
Hello @davidrohr , 
Should we merge this, or wait?

**Pull request merged**
