### PR TITLE
move aod merger to O2

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@davidrohr @sawenzel Here the draft of moving it to O2. Let me know if you have comments...

**Review by davidrohr — DISMISSED** [review]
fine with me, you can mark as ready for review to run the CI.

**Review by sawenzel — APPROVED** [review]

**Comment by sawenzel** [comment]
Thanks a lot!

**Comment by davidrohr** [comment]
@jgrosseo : could you please fix this warning, which made it through:
```
2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx: In function 'int main(int, char**)':
2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx:453:48: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'long unsigned int' [-Wformat=]
2023-08-28@20:53:44:DEBUG:O2:O2:0:   453 |         printf("  Tree %20s | Compressed: %12llu (%2.0f%%) | Uncompressed: %12llu (%2.0f%%)\n", tree.first.c_str(), tree.second, 100.0 * tree.second / totalCompressed, sizeUncompressed[tree.first], 100.0 * sizeUncompressed[tree.first] / totalUncompressed);
2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                           ~~~~~^                                                                    ~~~~~~~~~~~
2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                                |                                                                         |
2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                                long long unsigned int                                                    long unsigned int
2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                           %12lu
2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx:453:81: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'std::map<std::__cxx11::basic_string<char>, long unsigned int>::mapped_type' {aka 'long unsigned int'} [-Wformat=]
2023-08-28@20:53:44:DEBUG:O2:O2:0:   453 |         printf("  Tree %20s | Compressed: %12llu (%2.0f%%) | Uncompressed: %12llu (%2.0f%%)\n", tree.first.c_str(), tree.second, 100.0 * tree.second / totalCompressed, sizeUncompressed[tree.first], 100.0 * sizeUncompressed[tree.first] / totalUncompressed);
```

**Comment by jgrosseo** [comment]
> @jgrosseo : could you please fix this warning, which made it through:
> 
> ```
> 2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx: In function 'int main(int, char**)':
> 2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx:453:48: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'long unsigned int' [-Wformat=]
> 2023-08-28@20:53:44:DEBUG:O2:O2:0:   453 |         printf("  Tree %20s | Compressed: %12llu (%2.0f%%) | Uncompressed: %12llu (%2.0f%%)\n", tree.first.c_str(), tree.second, 100.0 * tree.second / totalCompressed, sizeUncompressed[tree.first], 100.0 * sizeUncompressed[tree.first] / totalUncompressed);
> 2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                           ~~~~~^                                                                    ~~~~~~~~~~~
> 2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                                |                                                                         |
> 2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                                long long unsigned int                                                    long unsigned int
> 2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                           %12lu
> 2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx:453:81: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'std::map<std::__cxx11::basic_string<char>, long unsigned int>::mapped_type' {aka 'long unsigned int'} [-Wformat=]
> 2023-08-28@20:53:44:DEBUG:O2:O2:0:   453 |         printf("  Tree %20s | Compressed: %12llu (%2.0f%%) | Uncompressed: %12llu (%2.0f%%)\n", tree.first.c_str(), tree.second, 100.0 * tree.second / totalCompressed, sizeUncompressed[tree.first], 100.0 * sizeUncompressed[tree.first] / totalUncompressed);
> ```

Actually it was `lu` before but for Mac I had to change it to `llu` (see last commit in this PR). I am not sure how to solve it then...

**Comment by jgrosseo** [comment]
I haven't even tested the `llu` run time I admit.

**Comment by ddobrigk** [comment]
Super thanks @jgrosseo :-D
(this was really in the wrong place before ...)

**Comment by davidrohr** [comment]
> > @jgrosseo : could you please fix this warning, which made it through:
> > ```
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx: In function 'int main(int, char**)':
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx:453:48: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type 'long unsigned int' [-Wformat=]
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0:   453 |         printf("  Tree %20s | Compressed: %12llu (%2.0f%%) | Uncompressed: %12llu (%2.0f%%)\n", tree.first.c_str(), tree.second, 100.0 * tree.second / totalCompressed, sizeUncompressed[tree.first], 100.0 * sizeUncompressed[tree.first] / totalUncompressed);
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                           ~~~~~^                                                                    ~~~~~~~~~~~
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                                |                                                                         |
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                                long long unsigned int                                                    long unsigned int
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0:       |                                           %12lu
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0: /home/qon/alice/sw/SOURCES/O2/dev/0/Framework/AODMerger/src/aodMerger.cxx:453:81: warning: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'std::map<std::__cxx11::basic_string<char>, long unsigned int>::mapped_type' {aka 'long unsigned int'} [-Wformat=]
> > 2023-08-28@20:53:44:DEBUG:O2:O2:0:   453 |         printf("  Tree %20s | Compressed: %12llu (%2.0f%%) | Uncompressed: %12llu (%2.0f%%)\n", tree.first.c_str(), tree.second, 100.0 * tree.second / totalCompressed, sizeUncompressed[tree.first], 100.0 * sizeUncompressed[tree.first] / totalUncompressed);
> > ```
> 
> Actually it was `lu` before but for Mac I had to change it to `llu` (see last commit in this PR). I am not sure how to solve it then...

@ktf : could you have a look and solve it? I remember you solved a similar issue in framework recently. When I changed it to %lu, it was complaining on macos...

**Pull request merged**
