### PR TITLE
Rdev pythia8 process name and code

### PR DESCRIPTION
**Pull request by preghenella**
this PR adds to the MC Event Header the process name and process code that comes from the Pythia8 info record.
it also adds a macro to read that info from the Kine file

### CODE REVIEW

**Review by sawenzel — DISMISSED** [review]

**Comment by sawenzel** [comment]
@preghenella : There are still compile problems.

**Comment by preghenella** [comment]
I see, while fixing some space checker issue I inadvertently pushed some work-in-progress fraction.
will fix that

**Comment by preghenella** [comment]
I managed to mess up, will need to look at it tomorrow.

**Comment by preghenella** [comment]
there is plenty of `missing or malformed copyright notice` in the failed error.
not related to this PR.
@sawenzel can it be merged?
thanks

**Comment by jotwinow** [comment]
Dear both, 
@sawenzel @preghenella 
Do you plan to merge it soon? We would like to use it asap for the pp trigger simulations. 

Regards,
Jacek

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
