### PR TITLE
Storing DCS DPs at least every "x" seconds

### PR DESCRIPTION
**Pull request by chiarazampolli**
where "x" is passed as an option.

clang

### CODE REVIEW

**Comment by chiarazampolli** [comment]
@shahor02 : this is the change relative to the discussion at the MW2, to store the CCDB object for TOF for the DPs every fixed time interval (not just at EndOfStream).

**Review by shahor02 — DISMISSED** [review]
looks ok.

**Comment by chiarazampolli** [comment]
There was an issue with macOS, I don't know if this commit fixes it. Let's see.

**Comment by chiarazampolli** [comment]
Error from CI related to analysis:
```
Scanning dependencies of target O2exe-analysistutorial-weak-decay-iteration
Scanning dependencies of target O2exe-analysistutorial-track-collection-iteration
Scanning dependencies of target O2exe-analysistutorial-filters
[ERROR] Unhandled o2::framework::runtime_error reached the top of main, device shutting down. Details follow: 

[ERROR] Unhandled o2::framework::runtime_error reached the top of main, device shutting down. Details follow: 

/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/lib64/libO2FrameworkFoundation.so(_ZN2o29framework15runtime_error_fEPKcz+0xf7)[0x7f2c2560f9b7]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/lib64/libO2FrameworkFoundation.so(_ZN2o29framework15runtime_error_fEPKcz+0xf7)[0x7fd8a58d39b7]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/lib64/libO2Framework.so(_Z15runStateMachineRKSt6vectorIN2o29framework17DataProcessorSpecESaIS2_EERK12WorkflowInfoRKS_INS1_17DataProcessorInfoESaISA_EERNS1_13DriverControlERNS1_10DriverInfoERS_INS1_17DeviceMetricsInfoESaISJ_EERN5boost15program_options13variables_mapENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x747)[0x7fd8a86205f7]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/lib64/libO2Framework.so(_Z15runStateMachineRKSt6vectorIN2o29framework17DataProcessorSpecESaIS2_EERK12WorkflowInfoRKS_INS1_17DataProcessorInfoESaISA_EERNS1_13DriverControlERNS1_10DriverInfoERS_INS1_17DeviceMetricsInfoESaISJ_EERN5boost15program_options13variables_mapENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x747)[0x7f2c2835c5f7]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/lib64/libO2Framework.so(_Z6doMainiPPcRKSt6vectorIN2o29framework17DataProcessorSpecESaIS4_EERKS1_INS3_26ChannelConfigurationPolicyESaIS9_EERKS1_INS3_16CompletionPolicyESaISE_EERKS1_INS3_14DispatchPolicyESaISJ_EERKS1_INS3_15ConfigParamSpecESaISO_EERNS3_13ConfigContextE+0x3021)[0x7fd8a86277c1]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/lib64/libO2Framework.so(_Z6doMainiPPcRKSt6vectorIN2o29framework17DataProcessorSpecESaIS4_EERKS1_INS3_26ChannelConfigurationPolicyESaIS9_EERKS1_INS3_16CompletionPolicyESaISE_EERKS1_INS3_14DispatchPolicyESaISJ_EERKS1_INS3_15ConfigParamSpecESaISO_EERNS3_13ConfigContextE+0x3021)[0x7f2c283637c1]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/bin/o2-analysistutorial-outputs[0x41b25e]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/bin/o2-analysistutorial-track-iteration[0x416f2e]
/lib64/libc.so.6(__libc_start_main+0xf3)[0x7f2c1bdfb7b3]
/lib64/libc.so.6(__libc_start_main+0xf3)[0x7fd89c0bf7b3]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/bin/o2-analysistutorial-track-iteration[0x4171ce]
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/0161e19ebce43cd67f8911c5eb7fe9929c8a7284/O2/stage/bin/o2-analysistutorial-outputs[0x41b4ee]
Scanning dependencies of target O2exe-analysistutorial-aodreader
gmake[2]: *** [Analysis/Tutorials/CMakeFiles/O2exe-analysistutorial-track-iteration.dir/build.make:154: stage/bin/o2-analysistutorial-track-iteration] Error 1
gmake[2]: *** Deleting file 'stage/bin/o2-analysistutorial-track-iteration'
gmake[2]: *** [Analysis/Tutorials/CMakeFiles/O2exe-analysistutorial-outputs.dir/build.make:154: stage/bin/o2-analysistutorial-outputs] Error 1
gmake[2]: *** Deleting file 'stage/bin/o2-analysistutorial-outputs'
gmake[1]: *** [CMakeFiles/Makefile2:42156: Analysis/Tutorials/CMakeFiles/O2exe-analysistutorial-track-iteration.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake[1]: *** [CMakeFiles/Makefile2:41892: Analysis/Tutorials/CMakeFiles/O2exe-analysistutorial-outputs.dir/all] Error 2
```

**Comment by chiarazampolli** [comment]
All green, but "fullCI", I think we need to merge by hand... @shahor02 , could you do that? At your convenience, of course.

**Pull request merged**
