### PR TITLE
Fix DetMatrixCache: deleted member function should be public

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
Hi, can this be merged quickly to make other PR to pass the check? 
The error in o2checkcode seems to be DPL-framework related.

**Comment by davidrohr** [comment]
If it doesn't break the CI with current stable version of AliTPCCommon, it should be fine.
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by sawenzel** [comment]
Not sure it's related to this, but I am now seeing:
```
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-3/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../include/c++/7.3.0/variant:238:46: error: cannot cast 'std::variant<std::function<bool (const o2::framework::DataRef &)>, std::function<o2::framework::MakeRootTreeWriterSpec::TerminationCondition::Action (const o2::framework::DataRef &, bool &)> >' to its private base class 'std::__detail::__variant::_Variant_storage<false, std::function<bool (const o2::framework::DataRef &)>, std::function<o2::framework::MakeRootTreeWriterSpec::TerminationCondition::Action (const o2::framework::DataRef &, bool &)> >' [clang-diagnostic-error]
      return __get(std::in_place_index<_Np>, std::forward<_Variant>(__v)._M_u);
                                             ^
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-3/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../include/c++/7.3.0/variant:1198:35: note: in instantiation of function template specialization 'std::__detail::__variant::__get<1, std::variant<std::function<bool (const o2::framework::DataRef &)>, std::function<o2::framework::MakeRootTreeWriterSpec::TerminationCondition::Action (const o2::framework::DataRef &, bool &)> > &>' requested here
      return __detail::__variant::__get<_Np>(__v);
                                  ^
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-3/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../include/c++/7.3.0/variant:744:14: note: in instantiation of function template specialization 'std::get<1, std::function<bool (const o2::framework::DataRef &)>, std::function<o2::framework::MakeRootTreeWriterSpec::TerminationCondition::Action (const o2::framework::DataRef &, bool &)> >' requested here
      return get<__detail::__variant::__index_of_v<_Tp, _Types...>>(__v);
             ^
```
In any case, we can merge the other PR independently on this.

**Comment by shahor02** [comment]
@davidrohr Actually the purpose of this PR is avoid breaking CI due to the "deleted member function should be public". I've just moved your ``void setSize(int s) = delete;`` to public part, this should not affect the AliTPCCommon

**Comment by shahor02** [comment]
@sawenzel @davidrohr : indeed, for the reasons I don't understand making deleted function public (as requested by CI) leads to these CI errors:
````/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-3/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../include/c++/7.3.0/variant:238:46: error: cannot cast 'std::variant<std::function<bool (const o2::framework::DataRef &)>, std::function<o2::framework::MakeRootTreeWriterSpec::TerminationCondition::Action (const o2::framework::DataRef &, bool &)> >' to its private base class 'std::__detail::__variant::_Variant_storage<false, std::function<bool (const o2::framework::DataRef &)>, std::function<o2::framework::MakeRootTreeWriterSpec::TerminationCondition::Action (const o2::framework::DataRef &, bool &)> >' [clang-diagnostic-error]
/mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/GCC-Toolchain/v7.3.0-alice1-3/bin/../lib/gcc/x86_64-unknown-linux-gnu/7.3.0/../../../../include/c++/7.3.0/variant:238:74: error: '_M_u' is a private member of 'std::__detail::__variant::_Variant_storage<false, std::function<bool (const o2::framework::DataRef &)>, std::function<o2::framework::MakeRootTreeWriterSpec::TerminationCondition::Action (const o2::framework::DataRef &, bool &)> >' [clang-diagnostic-error]````.

Not sure it is not some artifact of the incremental rebuild, but at the moment abandoning this PR.

**Comment by sawenzel** [comment]
@shahor02 : I've seen these problems even without this PR. Investigating. Maybe we can reopen this later.

**Pull request closed without merging**
