### PR TITLE
Update ZDC datamodel

### PR DESCRIPTION
**Pull request by njacazio**
@ddobrigk @coppedis

### CODE REVIEW

**Comment by ddobrigk** [comment]
Ciao @njacazio that's exactly it. Thanks!! Can you convert to actual PR?

**Comment by njacazio** [comment]
let's

**Comment by njacazio** [comment]
I forgot to update the producer, apologies ;)

**Comment by ddobrigk** [comment]
It would be important to merge this soon. It's been extensively tested by Pietro, so it should be fine to merge; the CI seems not relevant as far as I can tell. Could you please also take a look at this, @shahor02 ? Thanks!

**Pull request merged**
