### PR TITLE
Warning fixes

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Comment by sawenzel** [comment]
There is a failure in CPV raw data reading in the full-CI.

**Comment by shahor02** [comment]
Something was wrong with CPV digits tee, just run FST locally, did not see any problems.

**Comment by peressounko** [comment]
Indeed writing for(;;) instead of range based for( a: b)  causes crush. Probably this is related to compiler optimization?
Reverted previous form. Not clear how to fix warning (unused evnt) here?
// First version of for loop causes fault Optimizer???
//  for (auto evnt = treereader->begin(); evnt != treereader->end(); ++evnt) {
  for (auto evnt : *treereader) {
    rawwriter.digitsToRaw(*digitbranch, *triggerbranch);
  }
Also reverted CPVPedestalCalibrator where few lines were erroneously removed.

**Comment by peressounko** [comment]
dear @shahor02, @sawenzel could you please look and merge this PR?

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
