### PR TITLE
fix in the namespace provided to dictionary

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
@ktf: again o2-dev-fairroot build check reports an error on my PR...

**Comment by shahor02** [comment]
@matthiasrichter I was forced to add the changes in logging once PR check failed on old files (following deprecation of Logger->Fatal)

**Comment by matthiasrichter** [comment]
ok, thanks. The impact of the latest changes in FairRoot regarding logging is handled in PR https://github.com/AliceO2Group/AliceO2/pull/769 , so lets wait for @ktf to finish the work.

**Comment by ktf** [comment]
I should be almost done...

**Comment by sawenzel** [comment]
I think o2-dev-fairroot is allowed to fail. It only means that we have to do something before we move our FairRoot tag.

**Comment by shahor02** [comment]
@matthiasrichter as agreed reverted commit with fix for deprecated logging.

**Pull request merged**
