### PR TITLE
Introduction of a second charge-collection table in ALPIDE response

### PR DESCRIPTION
**Pull request by AlexBigO**
With this PR we introduced a second charge-collection table in ALPIDE response. 
A possibility to choose either of the tables or both from the command line is implemented as well.

For the moment, the second table is just a clone of the previously existing table for Vbb=-3V.
But it will eventually be replaced with a true table for Vbb=0V.

### CODE REVIEW

**Review by shahor02 — COMMENTED** [review]
Hi @AlexBigO 

Thanks for the development. Not sure it makes sense to upload 800+ dummy files cloned from Vbb0 just to override them later by real Vbb3. Since the Vbb3 anyway cannot be used now, I would propose to leave the code part of your PR (making sure that if Vbb3 is selected it prints a proper message and produce fatal) + moving current data files to the proper Vbb0 directory.

**Comment by AlexBigO** [comment]
> Hi @AlexBigO
> 
> Thanks for the development. Not sure it makes sense to upload 800+ dummy files cloned from Vbb0 just to override them later by real Vbb3. Since the Vbb3 anyway cannot be used now, I would propose to leave the code part of your PR (making sure that if Vbb3 is selected it prints a proper message and produce fatal) + moving current data files to the proper Vbb0 directory.

Hi @shahor02 

It is not yet clear when the true table for Vbb=0 will become available. The current idea is to try to tweak the existing table for Vbb=-3V, working freely on an independent clone of the table.
Does this create problems with managing the repository? If yes, we can remove the clone, of course. 
But eventually, we would have to commit the second table anyway.

**Comment by shahor02** [comment]
Hi @AlexBigO 
I let to @ktf to comment if committing 800+ new files which are anyway cannot be used until they are completely overwritten (not just a small diff applied) will cause extra stress to the git repository. Personally, I would not do this.

**Comment by ktf** [comment]
I agree it would be best to avoid it. How much bigger does the repository become? Do you have any other way this could be done?

**Comment by shahor02** [comment]
> I agree it would be best to avoid it. How much bigger does the repository become? Do you have any other way this could be done?

6.4MB made of 817 files, duplicated from the data of the currently used map as a placeholder for the alternative map, which will be produced later.

**Comment by shahor02** [comment]
@AlexBigO thanks for changing! Could you apply clang-format, then I'll approve to start CI tests.

**Review by shahor02 — DISMISSED** [review]
approving to trigger CI tests.

**Review by iouribelikov — APPROVED** [review]

**Review by shahor02 — APPROVED** [review]

**Comment by iouribelikov** [comment]
@everybody.   I do not understand... This PR was already "in green" during the weekend.
Now, 5 checks failed :(  
And I do not see anything calling for corrections in the logs.

Cannot we simply merge this PR ?

**Comment by shahor02** [comment]
some builders are failing to start. Merging.

**Comment by ktf** [comment]
For the record, Gitlab at CERN is having troubles, so this might result in failed builds with no logs.

**Pull request merged**
