### PR TITLE
DPL: support macOS < 10.14

### PR DESCRIPTION
**Pull request by ktf**
In principle `std::visit` is fine without exception.

### CODE REVIEW

**Comment by ktf** [comment]
Can someone give this a try on high sierra? Just to check if it is this easy...

**Comment by ktf** [comment]
@sawenzel this should work, however in order to rebuild I have a bunch of recompilation to do, due to updated alidist, can you check if this is ok for you?

**Comment by sawenzel** [comment]
@ktf: I will give it a try.

**Comment by ktf** [comment]
Given it compiles and tests run everywhere, I assume it also fixes the `std::visit` issue as I moved to the exceptionless `std::get_if<>`. Merging.

**Comment by ktf** [comment]
cross posted...

**Comment by sawenzel** [comment]
For the moment, I am not able to confirm compilation on MacO2 10.13; Compilations fails way before that in RapidJSON: 

```
error: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Werror,-Wstdlibcxx-not-found]
```

**Pull request merged**
