### PR TITLE
[StrangenessTracking] Pass ITS cluster information to AO2Ds

### PR DESCRIPTION
**Pull request by fmazzasc**
@mpuccio , @alcaliva

### CODE REVIEW

**Comment by fmazzasc** [comment]
+async-label async-2023-pbpb-apass4, async-2023-pp-apass4, async-2024-pp-apass1

**Review by shahor02 — APPROVED** [review]

**Comment by shahor02** [comment]
@fmazzasc you have tagged this as relevant for pbpb23 pass4, but I thing the tag for that pass already exists. Perhaps you should ping @alcaliva if it needs to be ported.

**Comment by alcaliva** [comment]
Hi @fmazzasc, unfortunately, this PR cannot be taken for PbPb. We would prefer not to take this PR for 2024 pp data unless this is urgent for skimming. We could take this at the next opportunity when we branch from dev (in September). If you have comments or additional input, you could join today's WP12/13 meeting and we can have more discussion.

**Comment by chiarazampolli** [comment]
Hello @fmazzasc ,

Same for the async-2023-pp-apass4: if we take this PR, MC will be different from data. 

Chiara

**Comment by fmazzasc** [comment]
+async-label !async-2023-pbpb-apass4, !async-2023-pp-apass4, !async-2024-pp-apass1

**Pull request merged**
