### PR TITLE
Eliminate full ITS/MFT cluster

### PR DESCRIPTION
**Pull request by shahor02**
Hi @iouribelikov @bovulpes @rpezzi 

I am trying to eliminate the traces of full clusters but I see it is still used in some classes which may require algorithmic changes:

ITS/workflow/src/CookedTrackerSpec.cxx

MFT/reconstruction/src/Tracker.cxx

MFT/reconstruction/src/TrackerTask.cxx  uses FairTask !!!   Can it be removed

MFT/tracking/include/MFTTracking/TrackFitter.h
MFT/tracking/include/MFTTracking/TrackParamMFT.h
MFT/tracking/src/IOUtils.cxx
MFT/tracking/src/TrackFitter.cxx
MFT/workflow/src/ClusterReaderSpec.cxx
MFT/workflow/src/ClusterWriterSpec.cxx

Could you please cleanup these classes in separate PR or send me the patches for this one?  
Also, I see that plenty of macros, especially the drawing ones, are based on ``Cluster.h``, those which I did not touch are:
````
git grep -l 'DataFormatsITSMFT/Cluster.h' | grep '\.C'
Detectors/ITSMFT/ITS/macros/EVE/DisplayEvents.C
Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
Detectors/ITSMFT/ITS/macros/test/CheckLUtime.C
Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
Detectors/ITSMFT/ITS/macros/test/dictionary_integrity_test.C
macro/CheckClusters_mft.C
macro/compareTopologyDistributions.C
macro/run_primary_vertexer_ITS.C
macro/run_trac_ca_its.C
macro/run_trac_its.C
````
I guess some of them can be eliminated, while others should be rebased to CompClusters, Yura, could you please check?

### CODE REVIEW

**Comment by bovulpes** [comment]
Hi @rpezzi 
I have modified some of the files, I leave the other for you, the partial commit is in my mft-trac branch
on https://github.com/bovulpes/AliceO2

**Comment by mpuccio** [comment]
Hi, just a comment: if the fullClusters are completely removed then we should also update the macros to run the ITS trackers. I can take care of the ca one. (cc @mconcas)

**Comment by shahor02** [comment]
@mpuccio thanks, yes, mostly the macros should be cleaned and better to do this starting from this branch, since most of places is already cleaned. And I would prefer to eliminate as much macros as possible, if there is a corresponding workflow. Now, that the DPL is quite mature and provides reasonable debugging possibilities, supporting both workflows and macros is an overkill.

**Comment by mpuccio** [comment]
On the other hand debugging with macros is faster, since I can play with many functions and settings without recompiling the workflow binary, I honestly never used the workflow for development (but if necessary I will learn...)

**Comment by shahor02** [comment]
@mpuccio As you prefer, then we just need to remove the old Clusters from these macros, they are not really used.
The problematic part is the visualization, which is still using full Clusters (and therefore anyway does not work since there clusters are not generated).

**Comment by shahor02** [comment]
Rebased to MFT cleaned-up code and fixed macros in O2/macro. @mpuccio, @iouribelikov, now they work with compact clusters. 

What remains are:
````
Detectors/ITSMFT/ITS/macros/EVE/DisplayEvents.C
Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
Detectors/ITSMFT/ITS/macros/test/CheckLUtime.C
Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
Detectors/ITSMFT/ITS/macros/test/dictionary_integrity_test.C
````
@iouribelikov : is DisplayEvents needed? @lbariogl could you please take care of dictionary related stuff?

**Comment by iouribelikov** [comment]
> Rebased to MFT cleaned-up code and fixed macros in O2/macro. @mpuccio, @iouribelikov, now they work with compact clusters.
> 
> What remains are:
> 
> ```
> Detectors/ITSMFT/ITS/macros/EVE/DisplayEvents.C
> Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
> Detectors/ITSMFT/ITS/macros/test/CheckLUtime.C
> Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
> Detectors/ITSMFT/ITS/macros/test/dictionary_integrity_test.C
> ```
> 
> @iouribelikov : is DisplayEvents needed? @lbariogl could you please take care of dictionary related stuff?

@shahor02 Hi Ruben.  Indeed, that DisplayEvents.C macro is not really needed now.   There is an equivalent DisplayEventsComp.C macro that works with compact clusters.

**Comment by shahor02** [comment]
@iouribelikov ok, thanks, removed it. The only dictionary macros + ``Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C`` is remaining. What about latter?

**Comment by iouribelikov** [comment]
> @iouribelikov ok, thanks, removed it. The only dictionary macros + `Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C` is remaining. What about latter?
@shahor02 That DisplayTrack.C was useful on a few occasions in the past,  to understand why certain clusters did not want to get associated with their own track.  I would keep this macro, if it is OK with you.

**Comment by shahor02** [comment]
ok, but it uses full clusters, could you move it also to compact ones?

**Comment by iouribelikov** [comment]
> ok, but it uses full clusters, could you move it also to compact ones?

@shahor02 OK. I will do it.

**Comment by lbariogl** [comment]
> Rebased to MFT cleaned-up code and fixed macros in O2/macro. @mpuccio, @iouribelikov, now they work with compact clusters.
> 
> What remains are:
> 
> ```
> Detectors/ITSMFT/ITS/macros/EVE/DisplayEvents.C
> Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
> Detectors/ITSMFT/ITS/macros/test/CheckLUtime.C
> Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
> Detectors/ITSMFT/ITS/macros/test/dictionary_integrity_test.C
> ```
> 
> @iouribelikov : is DisplayEvents needed? @lbariogl could you please take care of dictionary related stuff?

Ok @shahor02 , I'll take care of dictionary-related stuff

**Comment by shahor02** [comment]
@iouribelikov @lbariogl I want to merge this since other PR depends on this. So at the moment I've excluded from the test the macros which are anyway not used, they can be fixed in dev, then the last commit of this PR will be reverted:
````
Detectors/ITSMFT/ITS/macros/test/CheckCOG.C
Detectors/ITSMFT/ITS/macros/test/CheckLUtime.C
Detectors/ITSMFT/ITS/macros/test/DisplayTrack.C
Detectors/ITSMFT/ITS/macros/test/dictionary_integrity_test.C
````

**Pull request merged**
