### PR TITLE
SIM: Possible fix for -run5 executables for detectorList

### PR DESCRIPTION
**Pull request by f3sch**
Hi @sawenzel, @mconcas noticed that for `o2-sim-serial-run5` the default for the dectorList is ALICE2 which makes IMO little sense.
This MR would fix this by setting the default to ALICE3 for those run5 executables. I however do not like that I have to extend several function calls to propagate a single boolean. What would you suggest to `fix` this (does it even need fixing?). One other idea would be to `clone` the allsim target and add a preprocessor define like `SIM_RUN5`. What do you think?

### CODE REVIEW

**Comment by sawenzel** [comment]
Do we still need o2-sim-run5 at all? In principle we could just use o2-sim, now that we have detectorlists? (At least, this may be a goal)

**Comment by f3sch** [comment]
If you want I can also remove the executable entirely since they are from what I see anyways just copies with different names and I do not see any usage of `SimConfigData::mIsUpgrade`.

**Comment by f3sch** [comment]
Hi @sawenzel, following the recent discussion on the run5 executables I would propose to remove them entirely.
Also with the second commit, the printing of which list is used is slightly cleared up, e.g., not intermixing them anymore if the SimConfig constructed was called. Let me know if this is okay.

**Comment by f3sch** [comment]
Hi @sawenzel, should I close this PR?

**Comment by f3sch** [comment]
@sawenzel since we do not do releases, there is no deprecation policy, so should we keep it just as it is for now?

**Comment by sawenzel** [comment]
@f3sch : I took a look. For me, the amount of changes seem substantial and I would not be in favour of merging it at this moment. There may be alternative/shorter ways of influencing the default list (as a function of the executable).

**Comment by f3sch** [comment]
sure, thanks for commenting :)

**Comment by sawenzel** [comment]
@mconcas @f3sch : Could you take a look if https://github.com/AliceO2Group/AliceO2/pull/13430 would be good step forward?

**Pull request closed without merging**
