### PR TITLE
Analysis: speedup table-maker

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo @iarsene please verify correctness, but this + #4542 should speed up significantly table-maker.

**Comment by iarsene** [comment]
Hi @ktf @jgrosseo ,
I am preparing a commit with this file involved which would now be in conflict. I would add Partition in this task eventually, but i am focusing on various other things. Moreover, in this task, which prepares the skimmed data for later analysis, we will in principle need also to know the number of events and tracks rejected. If i add that partition now, how would i look into the tracks before the cuts are applied?

**Comment by jgrosseo** [comment]
We had discussed that a partition and filter should have some counters of number of rejected objects. I don't think this is in place yet. @aalkin can you comment?

I would propose we merge this, even if then you need to comment out the partition for now in your next commit and put it back later.

Btw. you can always loop over all tracks, even if you use a partition.

**Comment by jgrosseo** [comment]
Sorry, I didn't know that the other PR was already there, I merged it. @iarsene could you import the important updates from this PR into your code and make another PR, please?

**Comment by aalkin** [comment]
All tables, including filtered and partitioned, provide `.size()` and `.tableSize()` methods, selected and full numbers of rows, respectively.

**Comment by iarsene** [comment]
Hi @ktf , @jgrosseo, @aalkin ,
I am probably a bit less preocupied in cpu performance at the moment and focus more on developing the different analysis tools. But i will add the Partition and filter the track table (most of the track should be rejected at this point), then the additional analysis cuts will come on top of the Partition.
Cheers, Ionut

**Comment by aalkin** [comment]
@iarsene the main change for speeding things up is `muon.bcId() != collision.bcId()` - this way you compare indices directly, without creating two temporary iterators (which is what happens without `Id`).

**Comment by ktf** [comment]
and the reserve() part! The one which probably is just minimal is the expression column one.

**Comment by iarsene** [comment]
Yes, i saw the reserve as well. Is this similar as the reserve in std containers? I am just wondering what happens if i reserve a larger number than what i will actually fill in the table, since most likely i would apply some more cuts on top of the partition expression.

**Comment by ktf** [comment]
yes, it works similarly. That's why the partition is probably a good idea as well, so that you reserve to the exact number of selected tracks.

**Comment by ktf** [comment]
Closed as agreed with @iarsene who will include changes in his.

**Pull request closed without merging**
