### PR TITLE
use a quicksort implementation from Thrust as a fallback solution for GPU/CPU sorting

### PR DESCRIPTION
**Pull request by sgorbuno**

### CODE REVIEW

**Comment by davidrohr** [comment]
Sergey, is this the implementation we got from AMD? It is not thrust but from rocPRIM.

Did you compare it to the quicksoet you developed?

**Comment by sgorbuno** [comment]
> Sergey, is this the implementation we got from AMD? It is not thrust but from rocPRIM. Did you compare it to the quicksoet you developed?

Hi, yes. This is the AMD implementation. It is 15% faster than my qsort or std::sort().
I removed the dependencies from std::, so it can also compile with CUDA. 

I tried this qsort with the GPU tracker on NVIDIA.
the GPUTPCGMMergerTrackFit
and 
GPUTPCCompressionKernels_step1unattached
run as fast as with the Thrust sort.

**Comment by davidrohr** [comment]
Ok, for the compression one I am surprised. What you added is single threaded, right, but the compression kernel can theoretically use many threads. This will be important for large input data. What input data set are you using?

**Comment by sgorbuno** [comment]
I use one event with 40000 particles generated with the boxgen :

o2-sim -n 1 --seed 1  -g boxgen -e TGeant3 --skipModules ZDC MID --configKeyValues 'Diamond.position[2]=0.; BoxGun.pdg=13 ; BoxGun.number=40000'

**Comment by davidrohr** [comment]
@sgorbuno : I tried to run it, and performance before and after on NVIDIA is identical (do I understand correctly that you are disabling thrust on CUDA as well? This is fine with me, if the performance is the same.)

**Comment by sgorbuno** [comment]
> @sgorbuno : I tried to run it, and performance before and after on NVIDIA is identical (do I understand correctly that you are disabling thrust on CUDA as well? This is fine with me, if the performance is the same.)
 
No. For CUDA the thrust library is used. You can run the AMD quicksort instead, but for that, you need to disable the load of the GPUCommonAlgorithmThrust.h manually in the GPUCommonAlgorithm.h.

**Pull request merged**
