### PR TITLE
Disable flp2epn-distributed test temporarily

### PR DESCRIPTION
**Pull request by dberzano**

### CODE REVIEW

**Comment by matthiasrichter** [comment]
There seems to be a strange issue when running the unit tests in the CI. Whenever a test which has failed is disabled, another tests fails which had been ok before. Also the disabled here had been working before.

**Comment by ktf** [comment]
Indeed, looks like a timeout or something like that. @dberzano can you look into it?

**Comment by dberzano** [comment]
Yep

**Comment by dberzano** [comment]
Hi @matthiasrichter, @ktf - I don't see the problem any longer, do you?

**Comment by matthiasrichter** [comment]
Hi Dario, the last message from the Alice Builder is from 16:33 on this issue https://github.com/AliceO2Group/AliceO2/pull/370#issuecomment-303117941, I think the problem is still there.

**Comment by matthiasrichter** [comment]
Follow up on this: there was a real problem with the failing unit test. But it looks like that the condition whether it was failing or not was depending on the history of unit tests as the test was not failing when the flp2epn-distributed test was failing. Can the actual error message from a failing test be part of the log? Right now that seems to be missing.

**Comment by rbx** [comment]
I don't know from where this issue originated, but I would suggest to re-enable the test. If it is something unique to the flp2epn-distributed, then I will fix the origin of the fail. We shouldn't hide the problem by disabling the test. (Sorry if I am missing some parts of the discussion not present here!)

I tried to reproduce any failures on MacOS/Linux but couldn't. @matthiasrichter Indeed, seeing the actuall failure message would be very useful :).

**Pull request merged**
