### PR TITLE
[CPV] --file-for cru option for CPV digi2raw converter

### PR DESCRIPTION
**Pull request by sevdokim**
Hello!
the option --file-for cru is added to CPV digi2raw converter (RawCreator.cxx). Also RawWriter is modified to produce data for 3 GBT links (previously it was producing all data in 1 GBT link). One can also use --file-for link option for o2-cpv-digi2raw in order to  write data in 3 different files.

### CODE REVIEW

**Comment by kharlov** [comment]
Hi Sergey, 
The CPV FLP name is alio2-cr1-flp162, but in RawWriter.h you have alio2-cr1-flp163. If I understand GBTLinkAttributes, it should be corrected.
Yuri

**Comment by sevdokim** [comment]
Hi @kharlov 
Yes, you are absolutely right! Thanks for spotting it.

**Review by kharlov — APPROVED** [review]

**Comment by sevdokim** [comment]
Dear @shahor02 
sometimes check jobs fails with no obvious reason. For example, now build/O2/o2 had failed with no logs. 
I'm not sure what is a reason but it seems to be checking facility failure. Do you know if there is a possibility to re-run failed job by user? Thank you!

**Comment by shahor02** [comment]
Hi @sevdokim 
o2 CI failed to start, this happens from time to time. If other CIs get green I will merge this PR.
Cheers,
 Ruben

**Pull request merged**
