### PR TITLE
MFT: Update the noise scan to protect from double EOS.

### PR DESCRIPTION
**Pull request by tomas-herman**

### CODE REVIEW

**Review by shahor02 — DISMISSED** [review]

**Comment by shahor02** [comment]
Hi @tomas-herman 
github refuses to merge this PR with rebase. This might be related to github problems we observe since yesterday, but could you please rebase your branch to fresh dev and forcepush?

**Comment by tomas-herman** [comment]
Hi @shahor02,
Thanks for looking into it. I did the force push of latest dev version on the branch.

**Comment by shahor02** [comment]
Still fails to merge, will try again in a few hours, assuming this is a github problem.

**Review by shahor02 — APPROVED** [review]
was green, merging

**Pull request merged**
