### PR TITLE
Get rid of abseil dependency

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
ok, but this is also only a temporary workaround for the compilation. It will make CTF encoding 4x slower according to Michael, so it cannot be used. Why don't we make this depending on whether abseil is available?

**Comment by ktf** [comment]
Agreed, although I wonder if the problem does not mean we are basically locking our CTF format to the absl::flat_map schema at the moment of datataking. I did also https://github.com/AliceO2Group/AliceO2/pull/11890 which according to some random benchmark I found is supposed to be 2x faster than abseil (and it's a single file addition). How can we check with our own data?

**Comment by davidrohr** [comment]
Well, if I understand correctly, the map is only used for the encoding, and will not go into the bitstream. I am wondering why the rANS header needs to be processed by root at all.

**Comment by shahor02** [comment]
@ktf I'll compare the performance with https://github.com/AliceO2Group/AliceO2/pull/11890 to abseil,

**Comment by ktf** [comment]
Added a missing `#include <optional>` which was apparently brought in by absl.

**Pull request closed without merging**
