### PR TITLE
[O2-2748] Enable More Compiler Warnings for O2

### PR DESCRIPTION
**Pull request by MichaelLettrich**
* Documents on how to build O2 with warnings in `README.md`
* Small improvements in filter-warnings.sh

Can be merged bypassing CI since it does not affect any code or the build directly.

### CODE REVIEW

**Comment by MichaelLettrich** [comment]
@ktf or @davidrohr can you check this in the next days so that I can finally start sending the warning mails?

**Review by davidrohr — APPROVED** [review]

**Comment by davidrohr** [comment]
Are we sure this works with `ALIBUILD_O2_WARNINGS=1`?
I just ran a full O2 rebuild locally with
```
ALIBUILD_O2_WARNINGS=1 aliBuild --defaults o2 build O2 --debug
```
But I didn't get many warnings.

**Comment by MichaelLettrich** [comment]
@davidrohr  can you try with either 
```bash
export ALIBUILD_O2_WARNINGS=1 
aliBuild --defaults o2 build O2 --debug
```
or 
```
aliBuild -e ALIBUILD_O2_WARNINGS=1 build O2 --defaults o2  --debug
```
which is what we do with jenkins.

**Comment by davidrohr** [comment]
I had a custom CMAKE_BUILD_TYPE, and warnings were only applied for the default ones. Fix is here: #8557

**Comment by MichaelLettrich** [comment]
@davidrohr thanks for spotting and correcting this!

**Pull request merged**
