### PR TITLE
DPL: better message when child dies

### PR DESCRIPTION
**Pull request by ktf**
DPL: better message when child dies

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo @davidrohr @costing this provides the actual type of signal which killed a given device. It works fine for me (including on hyperloop) however I was wondering if we had any kind of post processing of the logs which relied on the old message.

**Comment by jgrosseo** [comment]
Thanks! Hyperloop relies on the O2 command exit code, so not on the printout.

**Review by davidrohr — DISMISSED** [review]
perhaps I would leave the word crashed in, as people often grep for it in logs. Grepping for exited with != 0 is more annoying.

How about ... crashed and exited with ...?

**Comment by costing** [comment]
Indeed, we rely on the exit code of the top-level process. So one thing to consider is propagating the exit code all the way up to the steering script.

There is another way in which human-readable messages could be transported to AliEn. If you write (append) something to a file called `.alienValidation.trace`, it will be included in the job trace. Should be kept short but a one liner with the root cause of a crash there could help a lot in debugging.

**Comment by ktf** [comment]
@davidrohr ok, the second message is back to what it was. I was more worried about the current list of crash reasons, which is now substituted by the string associated to `WTERMSIG(status)`.

@costing I will do that, but in a separate PR.

**Review by davidrohr — APPROVED** [review]

**Pull request merged**
