### PR TITLE
TRDSimulation: add missing headers

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Spotted while using ROOT master on macOS.

**Comment by davidrohr** [comment]
@ktf @qgp : This problem here is triggered by `Analysis/Tasks/jetfinder.cxx` 
```
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/build_o2checkcode_o2/0/Analysis/Tasks/jetfinder.cxx:87:3: internal compiler error: Segmentation fault
   }
   ^
0xb4024f crash_signal
	../../gcc/gcc/toplev.c:337
0x7a88d3 lookup_page_table_entry
	../../gcc/gcc/ggc-page.c:630
0x7a88d3 ggc_set_mark(void const*)
	../../gcc/gcc/ggc-page.c:1527
0x700901 gt_ggc_mx_lang_tree_node(void*)
	./gt-cp-tree.h:133
0x6efda0 gt_ggc_mx(deferred_access_check&)
	./gt-cp-semantics.h:36
0x6efd82 void gt_ggc_mx<deferred_access_check>(vec<deferred_access_check, va_gc, vl_embed>*)
	../../gcc/gcc/vec.h:1110
0x6efd82 gt_ggc_mx_vec_deferred_access_check_va_gc_(void*)
	./gt-cp-semantics.h:28
0x68d7d7 gt_ggc_mx_tree_check(void*)
	./gt-cp-parser.h:38
0x68d842 void gt_ggc_mx<cp_token>(vec<cp_token, va_gc, vl_embed>*)
	../../gcc/gcc/vec.h:1110
0x68d842 gt_ggc_mx_vec_cp_token_va_gc_(void*)
	./gt-cp-parser.h:49
0x68d8ac gt_ggc_mx_cp_lexer(void*)
	./gt-cp-parser.h:76
0x68da0d gt_ggc_mx_cp_parser(void*)
	./gt-cp-parser.h:136
0x916435 ggc_mark_root_tab
	../../gcc/gcc/ggc-common.c:77
0x916710 ggc_mark_roots()
	../../gcc/gcc/ggc-common.c:94
0x7a92c7 ggc_collect()
	../../gcc/gcc/ggc-page.c:2197
0x80d0e4 cgraph_node::finalize_function(tree_node*, bool)
	../../gcc/gcc/cgraphunit.c:480
0x6ed6df expand_or_defer_fn(tree_node*)
	../../gcc/gcc/cp/semantics.c:4279
0x6af8c4 cp_parser_function_definition_after_declarator
	../../gcc/gcc/cp/parser.c:26293
0x6afba4 cp_parser_late_parsing_for_member
	../../gcc/gcc/cp/parser.c:27166
0x690ed5 cp_parser_class_specifier_1
	../../gcc/gcc/cp/parser.c:22347
Please submit a full bug report,
```
and seems to be a bug in the gcc we have in the CI container. I can reproduce the same issue locally in the CI container, but with my system GCC it compiles correctly.

What do we do here?
Could we try to circumvent it by changing `Analysis/Tasks/jetfinder.cxx` slightly? Otherwise we'll have to bump GCC, and I am not sure we are ready for that.

**Comment by ktf** [comment]
I think this happens only if you use the master of root, not the last tagged version.

**Comment by ktf** [comment]
@davidrohr I am investigating.

**Comment by davidrohr** [comment]
@ktf In my docker container that showed the same issue I have ROOT v6-20-02-alice3

**Pull request merged**
