### PR TITLE
[EMCAL-798]: Prepare offline calibrator. 

### PR DESCRIPTION
**Pull request by hjbossi**
Designed to produce objects used as input for the offline calibration. Linked with ctf reader workflow.

### CODE REVIEW

**Review by mfasDa — DISMISSED** [review]
Looks good!

**Comment by mfasDa** [comment]
Forwarding to @shahor02 for final merge. This is an offline calibrator we need to calibrate what we have taken so far. We need a dedicated processor for this and cannot use the workflow running on the aggregator since we need to run in batch mode (parallel, per run) and produce output which we can write out, merge and post process.

**Comment by shahor02** [comment]
@mfasDa the errors are genuine:
```
FAILED: Detectors/EMCAL/workflow/CMakeFiles/O2lib-EMCALWorkflow.dir/src/OfflineCalibSpec.cxx.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DDPL_ENABLE_BACKTRACE -DENABLE_UPGRADES -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -DFMT_SHARED -DGENERATORS_WITH_HEPMC3 -DGENERATORS_WITH_PYTHIA6 -DGENERATORS_WITH_PYTHIA8 -DO2lib_EMCALWorkflow_EXPORTS -DZDC_FASTSIM_ONNX -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Detectors/EMCAL/workflow/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/BUILD/772a98f94e4b7cf4806cdc9a89030d539c2c47bb/O2/Detectors/EMCAL/workflow -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/BUILD/772a98f94e4b7cf4806cdc9a89030d539c2c47bb/O2/Detectors/EMCAL/workflow/src -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Framework/Core/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Common/Utils/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/common/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Common/Constants/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/GPU/Common -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Framework/Logger/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Common/MathUtils/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/Headers/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/MemoryResources/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/CCDB/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Framework/Foundation/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Framework/Foundation/3rdparty/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Utilities/PCG/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/Detectors/CTP/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/simulation/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/Detectors/Common/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/GPU/Utils -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Utilities/rANS/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Detectors/Base/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/Reconstruction/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Common/Field/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/Parameters/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Common/Types/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Common/SimConfig/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/DataFormats/Detectors/EMCAL/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Detectors/EMCAL/simulation/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Detectors/EMCAL/base/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Detectors/Raw/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Detectors/EMCAL/reconstruction/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Steer/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Generators/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Framework/Utils/include -I/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Algorithm/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/Common-O2/v1.6.0-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/boost/v1.75.0-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/Configuration/v2.6.3-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/libInfoLogger/v2.5.1-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/Monitoring/v3.12.0-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/curl/7.70.0-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/FairMQ/v1.4.52-local1/include/fairmq -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/FairMQ/v1.4.52-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/FairLogger/v1.11.1-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/fmt/8.1.1-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/ROOT/v6-26-04-patches-alice1-local4/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/FairRoot/v18.4.8-local4/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/VMC/v1-1-p1-local4/include/vmc -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/arrow/v9.0.0-alice1-local2/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/Vc/1.4.1-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/ms_gsl/4.0.0-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/libjalienO2/0.1.3-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/RapidJSON/v1.1.0-alice2-local3/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/libuv/v1.40.0-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/TBB/v2021.5.0-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/pythia/v8304-local1/include -isystem /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/osx_arm64/HepMC3/3.2.5-local4/include -fPIC -O2 -std=c++17 -Werror -Wno-error=deprecated-declarations -O2 -g -Wno-unknown-warning-option -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=10.15 -fPIC -std=gnu++17 -MD -MT Detectors/EMCAL/workflow/CMakeFiles/O2lib-EMCALWorkflow.dir/src/OfflineCalibSpec.cxx.o -MF Detectors/EMCAL/workflow/CMakeFiles/O2lib-EMCALWorkflow.dir/src/OfflineCalibSpec.cxx.o.d -o Detectors/EMCAL/workflow/CMakeFiles/O2lib-EMCALWorkflow.dir/src/OfflineCalibSpec.cxx.o -c /System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Detectors/EMCAL/workflow/src/OfflineCalibSpec.cxx
/System/Volumes/Data/build/nomad/alloc/2a93ae05-6ab2-ab1b-aeeb-44de2ea51f23/ci/local/o2/sw/SOURCES/O2/9650/0/Detectors/EMCAL/workflow/src/OfflineCalibSpec.cxx:62:15: error: no member named 'getCellEnergy' in 'o2::emcal::Cell'; did you mean 'getEnergy'?
        if (c.getCellEnergy() > 0.5) {
```

**Comment by hjbossi** [comment]
Apologies for the errors - my local tests did not catch the errors in the new added files. I will fix this and then re-push!

**Comment by hjbossi** [comment]
@shahor02 @mfasDa The errors are now fixed and this compiles locally. Pending successful checks, should be ready to merge.

**Comment by mfasDa** [comment]
@shahor02 fullCI error unrelated, I think it can be merged

**Review by shahor02 — APPROVED** [review]
@mfasDa merging this, but the fullCI error is caused by the emcal, see my comment in other PR: https://github.com/AliceO2Group/AliceO2/pull/9651#issuecomment-1218531640

**Pull request merged**
