### PR TITLE
[Tracking] Templetize Propagator and TrackLTIntegral to allow double precision

### PR DESCRIPTION
**Pull request by MichaelLettrich**
To allow double precision calculations needed for Alignment, `TrackLTIntegral` and `Propagator` have been templetized
Along the way,`base::math_utils` were extended providing single and double precision floating point overloads of functions in  `gpu::CAMath`

### CODE REVIEW

**Review by davidrohr — DISMISSED** [review]
mathutils changes are OK.
Only point is that you mentioned you would remove some of the double versions from GPUCommonMath, which are no longer needed, which I don't see here. But this can also be done afterwards.

For the templatization, looks OK but didn't try it.

**Comment by MichaelLettrich** [comment]
I currently assigned a WIP label to the PR as I am asking for feedback @shahor02 : 

In the `Propagator` Material Budget and Field are based on float numbers - even though the according classes have double precision getters. How do we proceed here? is this enough?
* `Propagator::getMatBudget()`
* `Propagator::getFieldXYZ()`
are the methods in question.

**Comment by MichaelLettrich** [comment]
@davidrohr done.  removed `CopySignD`as it is not used in any code outside `math_utils`. `SinCosD`  however is used in some code.

**Review by shahor02 — CHANGES_REQUESTED** [review]
@MichaelLettrich thanks, looks nice. I assume the GPU-macros related stuff is ok for @davidrohr.

There was no need to templatize the TrackLTIntegral, we will neve use its double version. As we discussed, it would be enough to change 1 method: from ``addStep(float dL, const TrackPar & track)`` to ``addStep(float dL, float p2)`` and call it as ``addStep(dl, track.getP2Inv())``.

**Comment by MichaelLettrich** [comment]
@shahor02, I am sorry - somehow I forgot to write this point down during our discussion. So what do you propose? 
Should I revert the templetization of `TrackLTIntegral` and change the method?

**Comment by shahor02** [comment]
yes, please, I would change only this part.

**Comment by MichaelLettrich** [comment]
@shahor02 should be done. lets see if all tests pass.

**Review by shahor02 — DISMISSED** [review]
Thanks, looks fine.

**Comment by MichaelLettrich** [comment]
@davidrohr : does OCL understand `using` or do I need `typedef`?

**Comment by davidrohr** [comment]
C++17 should be ok syntax-wise, just stl is not available.

**Comment by MichaelLettrich** [comment]
@davidrohr
I had to replace the forward declaration of 
```cpp
class Propagator
```
in `GPUDataTypes.h` with 
```cpp
template <typename>
class PropagatorImpl;
using Propagator = PropagatorImpl<float>;
```
since aliases/ typedefs cannot be forward declared. However OpenCL doesn't like it complaining about 
```bash
          identifier "Propagator" is undefined
  using Propagator = PropagatorImpl<float>;
        ^
```
do you have a clue what could be causing this?

**Comment by shahor02** [comment]
@MichaelLettrich @davidrohr do you understand why these lines in the  `GPUDataTypes.h` produce error?
````
template <typename>
class PropagatorImpl;
using Propagator = PropagatorImpl<float>;
````

**Comment by MichaelLettrich** [comment]
@shahor02 : It is apparently related to OpenCL 1.2 however I have no clue where the issue lies.

**Comment by davidrohr** [comment]
OK, indeed the OpenCL1.2 part doesn't understand the `using`, but I could work around that quite easily by just using the explicit template version in the header.
Afterwards I saw plenty of additional GPU compilation problems. The attached patch fixes the compilation for me.
[gpufix.patch.gz](https://github.com/AliceO2Group/AliceO2/files/6150922/gpufix.patch.gz)

**Comment by MichaelLettrich** [comment]
@davidrohr thank you very much for your help on this.

**Comment by davidrohr** [comment]
@TimoWilken : Could you restart the O2/o2 CI for this PR? I have the impression something weird went wrong in there.

**Comment by TimoWilken** [comment]
@davidrohr OK, restarted.

**Comment by davidrohr** [comment]
@TimoWilken : It seems it failed again. It looks some files are missing in the FairRoot and FairLogger installations.
Could it be that the hard disk ran full or the filesystem is corrupted?
Could you check, wipe the build are, and restart once more?

**Comment by TimoWilken** [comment]
@davidrohr I've cleaned out the `sw/` dir for this PR, but are you sure it's not related to #5650 / #5589?

**Comment by davidrohr** [comment]
At least this error should not be related to a FairLogger header:
```
No rule to make target `/mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/FairRoot/v18.4.1-1/lib/libBase.so', needed by `stage/lib64/libO2FV0Base.so'.  Stop.
```

**Comment by MichaelLettrich** [comment]
@TimoWilken thanks for clearing the builder. I will reset the build.

**Comment by MichaelLettrich** [comment]
@sawenzel  can we merge?

**Pull request merged**
