### PR TITLE
DPL GUI: propagate information about uint32 metrics

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Obligatory screenshot:

image

**Comment by ktf** [comment]
@shahor02 should allow you to better debug the orbit / tfCounter.

**Comment by shahor02** [comment]
Thanks!

**Comment by ktf** [comment]
@sawenzel is this expected?

```
qedsim.log-GeneratorExternal.fileName=/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5880-1/share/Generators/external/QEDLoader.C;QEDGenParam.yMin=-7;QEDGenParam.yMax=7;QEDGenParam.ptMin=0.001;QEDGenParam.ptMax=1.;Diamond.width[2]=6.
qedsim.log-$$$$
qedsim.log:[ERROR] Uncaught exception reached the top of main: An error occurred while loading static plugin config: boost::dll::shared_library::load() failed (dlerror system message: /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5880-1/bin/o2-sim-primary-server-device-runner: cannot dynamically load executable): Bad file descriptor
qedsim.log-------------- START OF SIM WORKER(S) LOG --------
qedsim.log-[INFO] ipc:///tmp/primary-get_250051516
killing child 1501
killing child 1504
killing child 1509
killing child 1510
killing child 1513
killing child 1516
killing child 1600
killing child 1702
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5880-1/share/scripts/jobutils.sh: line 48:  1501 Killed                  eval ${finalcommand} >> ${logfile} 2>&1
Running: TIME="#walltime %e" /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5880-1/share/scripts/monitor-mem.sh /usr/bin/time --output=qedsim.log_time './qedsim.log_tmp.sh'
/usr/bin/time --output=qedsim.log_time ./qedsim.log_tmp.sh
[INFO] This is o2-sim version 1.2.0 (31727010c)
[INFO] Built by ALIBUILD:LAST-TAG, ALIDIST-REV:503c6b464209e43ee6c7d179b06ab40d1b87607e on OS:Linux-4.4.0-197-generic
[INFO] Running with 24 sim workers 
[INFO] CREATING SIM SHARED MEM SEGMENT FOR 24 WORKERS
```

**Pull request merged**
