### PR TITLE
Please consider the refactoring changes to AliceO2Group/AliceO2#7719

### PR DESCRIPTION
**Pull request by alibuild**
AliceO2Group/AliceO2#7719

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf @TimoWilken : Perhaps we shouldn't open such refactoring changes PRs against other PRs that are opened automatically? Could actually create an endless PR creation loop in the worst case.

**Comment by ktf** [comment]
In principle the refactoring are always opened to the user repository, so it should not be an issue, as long as we do not start to automatically merge PRs which are opened against alibuild/AliceO2.

**Comment by davidrohr** [comment]
well, I think the problem is PR #7719 has been opened not from a user repository but from the AliceO2Group/AliceO2 repo.
Such cases should be excluded I think.

**Comment by ktf** [comment]
Agreed, but we should fix the automatic opening from the AliceO2Group repository, IMHO. I think it's just historical it uses the official one. I.e. all bot actions should create  PRs from the alibuild/AliceO2 repo, not from the official one.

**Comment by sawenzel** [comment]
Can this be closed?

**Pull request closed without merging**
