### PR TITLE
[WIP] TRD digitizer unordered_map instead of map (O2-734)

### PR DESCRIPTION
**Pull request by jolopezl**
https://alice.its.cern.ch/jira/browse/O2-734

@sawenzel, we should try this simple change and see if it outperforms the current version of the digitizer. On the mean time, I am also finalizing the version with flat structures only, but it shouldn't be better than this.

### CODE REVIEW

**Comment by davidrohr** [comment]
@jolopezl : @sawenzel is away in vacation. Perhaps you can just open another PR for the flat structure as well, then we can compare directly. I will run some benchmarks tomorrow.

**Comment by davidrohr** [comment]
I just did a quick benchmark with 2 pythia8hi events:
- Before this patch: 9 min 17 sec
- with this patch: 7 min 37 sec
So this is a significant improvement, but still far away from reasonable performance. Let's wait if the version with the flat array performs better, and then we'll have to identify other bottlenecks.

**Comment by jolopezl** [comment]
@davidrohr, thank you very much for doing the tests. I remembered that @sawenzel is on vacations, but I wanted to open the PR anyway. I will keep the PR open, and see what comes out performing the best. It's still nice to see that this version performs a bit better that the previous one.

**Comment by davidrohr** [comment]
@jolopezl : Actually, after thinking again, I would actually merge this right now. It is very simple, and will help anyone who simulates something right now. We can reevaluate v.s. the flat array when that PR is ready?

**Comment by jolopezl** [comment]
> @jolopezl : Actually, after thinking again, I would actually merge this right now. It is very simple, and will help anyone who simulates something right now. We can reevaluate v.s. the flat array when that PR is ready?

I would not merge it since we still want to compare with the other version, but I don't see a real objection not to merge it right now. So, if you think this is a positive PR, go ahead and merge.

**Comment by davidrohr** [comment]
Well, it's an improvement for anyone who uses it, so I'll merge it.
When you have the new version ready, we anyway want to compare with the best alternative, which is the unordered map so far.

**Comment by sawenzel** [comment]
This is an improvement but I still expect significant speedup by using flat vectors. Unordered_map access has better scaling but still constant factor overhead compared to vector access.

**Comment by davidrohr** [comment]
I agree, for now it is better than nothing, but we still need to speed up by one order of magnitute. So I'd consider a flat array access version high priority.

**Comment by jolopezl** [comment]
> This is an improvement but I still expect significant speedup by using flat vectors. Unordered_map access has better scaling but still constant factor overhead compared to vector access.

I agree with you @sawenzel. The other version is almost ready.

**Pull request merged**
