### PR TITLE
Cut files for Passive, TPC, HMPID, PHOS (copied from AliRoot)

### PR DESCRIPTION
**Pull request by amorsch**

### CODE REVIEW

**Comment by sawenzel** [comment]
Looks good to me. @wiechula : Could you please check for TPC as this might modify your logic?

**Comment by wiechula** [comment]
For me this is fine.
Just for education, how are the cuts applied. I guess the logic is not part of this PR.

**Comment by amorsch** [comment]
> For me this is fine.
> Just for education, how are the cuts applied. I guess the logic is not part of this PR.

The logic is the same as with AliRoot + galice.cuts. The lower cuts (in particular for delta-electrons) are effective for Geant3 and Geant4. In the present version (master) loser cuts are only applied for the drift gas and only for Geant3.

**Comment by sawenzel** [comment]
@ktf: The logs are not accessible 
```
<Error>
<Code>AccessDenied</Code>
<BucketName>alice-build-logs</BucketName>
<RequestId>tx00000000000000425a99c-005e60b2ad-9b5a49b-default</RequestId>
<HostId>9b5a49b-default-default</HostId>
</Error>
```


and the log for MacOS is weird (some pip python error).

**Comment by ktf** [comment]
The macOS issue seems a change in one of the upstream python modules. I will check.

I am investigating the issue with the logs.

**Comment by wiechula** [comment]
Thanks, I mean where in the code they are loaded and applied, since the {SetSpecialPhysicsCuts()} is removed in this PR. I don't see, where the {dat} files are loaded. I assume in the base class.

**Comment by sawenzel** [comment]
@wiechula : Yes, this is done in the base class generically for all detectors.

**Comment by sawenzel** [comment]
@amorsch : I fixed a merge conflict (with MID) as a maintainer. I'll merge this as soon as possible.

**Comment by sawenzel** [comment]
@ktf: logs cannot be accessed: 
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<BucketName>alice-build-logs</BucketName>
<RequestId>tx0000000000000043a0745-005e6206c4-9b5a441-default</RequestId>
<HostId>9b5a441-default-default</HostId>
</Error>
```
Did anything fundamental change?

**Comment by ktf** [comment]
There was some change to report the time of the test, I am trying to understand if that silently broke something.

**Comment by ktf** [comment]
The macOS issue is weird, as it looks like the build machine was misconfigured and python2 is used rather than python3. Unfortunately @MichaelLettrich is on holidays and the setup is not particularly documented.

**Comment by ktf** [comment]
That said, there seems to be an actual error with this PR:

```
CMake Error at cmake/O2DataFile.cmake:56 (file):
  file COPY cannot find
  "/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3073/0/Detectors/ITSMFT/ITS/simulation/data":
  No such file or directory.
Call Stack (most recent call first):
  Detectors/ITSMFT/ITS/simulation/CMakeLists.txt:24 (o2_data_file)


CMake Error at cmake/O2DataFile.cmake:56 (file):
  file COPY cannot find
  "/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3073/0/Detectors/ITSMFT/MFT/simulation/data":
  No such file or directory.
Call Stack (most recent call first):
  Detectors/ITSMFT/MFT/simulation/CMakeLists.txt:20 (o2_data_file)
```

**Comment by sawenzel** [comment]
superseded by #3099. (Kept your commits and added empty placeholder files to fix cmake problem).

**Pull request closed without merging**
