### PR TITLE
DPL: do not schedule processes when running with --dds

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @sawenzel @shahor02 there seems to be an issue with the full system test:

```
Launching task: o2-raw-file-reader-workflow --session default --shm-segment-size 8000000000 --configKeyValues "HBFUtils.nHBFPerTF=128" --detect-tf0 --input-conf raw/FT0/FT0raw.cfg | o2-ft0-flp-dpl-workflow  --session default --shm-segment-size 8000000000 -b &> o2-raw-file-reader-workflow.log &
Launching task: o2-ft0-test-raw-conversion &> o2-ft0-test-raw-conversion.log &
command o2-ft0-test-raw-conversion had nonzero exit code 134
----- Last log: -----
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/3a479f1cde41f24b13f4ffd2215bec40346f174f/O2-full-system-test/full-system-test-sim
Running: TIME="#walltime %e" /usr/bin/time --output=o2-ft0-test-raw-conversion.log_time ./o2-ft0-test-raw-conversion.log_tmp.sh
[FATAL] Decoded digits file ft0digits.root is absent
For later analysis we write a core dump to core_dump_32418
./o2-ft0-test-raw-conversion.log_tmp.sh: line 1: 32418 Aborted                 (core dumped) o2-ft0-test-raw-conversion
----- End of log -----
```

**Comment by ktf** [comment]
Only affects DDS file generation, so error unrelated. Merging.

**Comment by davidrohr** [comment]
From the log I cannot tell what happened, apparently there is something wrong with ft0 data. But I would need to get access to the simulation artifacts of that particular run to reproduce it.

**Comment by davidrohr** [comment]
ok, perhaps related to #5728
Let's see if it happens again.

**Comment by shahor02** [comment]
I think this is due to the PR I've merged this night, just merged a hotfix provided by @afurs https://github.com/AliceO2Group/AliceO2/pull/5728#issuecomment-802538596 and testing the FST locally.

**Comment by afurs** [comment]
`[FATAL] Decoded digits file ft0digits.root is absent Decoded digits file ft0digits.root is absent`
This is due to incorrect TriggerInput(trgInput) flag for DigitWriter(https://github.com/AliceO2Group/AliceO2/blob/0f327ec83dfa44c69eaaf33cb18cdd8b7d83a53e/Detectors/FIT/FT0/workflow/src/FT0DigitWriterSpec.cxx#L48), I guess that o2_ft0digits.root was generated in tests.
After hotfix(https://github.com/AliceO2Group/AliceO2/pull/5746) it should be gone.

**Comment by shahor02** [comment]
@afurs yes, I've run the test locally, it fixes the problem, thanks.

**Pull request merged**
