### PR TITLE
DPL: automatically match dangling RAWDATA messages to rawProxy (O2-588)

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ironMann I've not tested it (will do tomorrow), but it should not be too far...

**Comment by ironMann** [comment]
@ktf Will this still require for all messages to be explicitly matched by a rule?

The output proxy should catch **all** unmatched messages on output of dpl components (input-proxy).
For example, a compressor component might want to send some uncompressed data also, for offline validation. In that case there will be CRAWDATA and RAWDATA both present (maybe only in some STFs). There are also meta messages that are not RAWDATA at all.

**Comment by ktf** [comment]
This is for the input. My point is that if some task erroneously asks about "AOD" it should not be attached to the `o2-dpl-raw-proxy`, it should complain that no one is providing AODs. For the output I can indeed add a match all rule, assuming that whatever is produced will be forwarded (right now we have something similar which writes to disk).

**Comment by ktf** [comment]
I've done one for the outputs which should behave as you request.

**Comment by ktf** [comment]
#4381

**Comment by ktf** [comment]
@ironMann updated to compile.

**Comment by ktf** [comment]
Closing this. As discussed it is not particularly needed to be able to forward consumed data to the output proxy.

**Pull request closed without merging**
