### PR TITLE
fix TOF digitizer bug and add tof trigger info in raw encoding from sim

### PR DESCRIPTION
**Pull request by noferini**

### CODE REVIEW

**Comment by noferini** [comment]
No idea about the problem with whitespace check
Any suggestion?

**Comment by shahor02** [comment]
You have some tabs instead of spaces. 
I use this script before pushing the PR:
```
#!/bin/bash

git diff --diff-filter d --name-only $(git merge-base HEAD origin/dev) | xargs sed -i 's/\t/ /g'
git diff --diff-filter d --name-only $(git merge-base HEAD origin/dev) | xargs sed -i 's/[[:space:]]*$//'

git diff --diff-filter d --name-only $(git merge-base HEAD origin/dev) | xargs perl -p -i -e 's|LOGP[(]ERROR|LOGP(error|g;s|LOGP[(]INFO|LOGP(info|g;s|LOGP[(]WARN|LOGP(warn|g;s|LOGP[(]DEBUG|LOGP(debug|;s|LOG[(]ERROR|LOG(error|g;s|LOG[(]INFO|LOG(info|g;s|LOG[(]WARN|LOG(warn|g;s|LOG[(]DEBUG|LOG(debug|g'

git status
```

**Comment by noferini** [comment]
Hi @shahor02 ,
thanks!

**Comment by noferini** [comment]
Ready to be merged

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
