### PR TITLE
Adding BitstreamReader utility

### PR DESCRIPTION
**Pull request by matthiasrichter**
some minor compiler warnings fixed in addition

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@Barthelemy I see the following error in the build log for QualityControl package. No idea if this is causing the o2 CI to fail.
```
-- Found InfoLogger: /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/libInfoLogger/v1.3.0-1/lib/libInfoLogger.so  
-- InfoLogger found : /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/libInfoLogger/v1.3.0-1/lib/libInfoLogger.so
CMake Error at /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/CMake/v3.13.1-8/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  AliceO2 could not be found.  Install package AliceO2.  (missing:
  AliceO2_LIBRARY_FrameworkFoundation AliceO2_LIBRARY_Framework
  AliceO2_LIBRARY_Headers AliceO2_LIBRARY_CCDB AliceO2_LIBRARY_DebugGUI
  AliceO2_LIBRARY_DetectorsBase AliceO2_LIBRARY_ITSBase
  AliceO2_LIBRARY_ITSSimulation AliceO2_LIBRARY_ITSReconstruction
  AliceO2_LIBRARY_ITSWorkflow AliceO2_LIBRARY_ITSMFTReconstruction
  AliceO2_LIBRARY_ITSMFTBase AliceO2_LIBRARY_DetectorsCommonDataFormats)
Call Stack (most recent call first):
  /mnt/mesos/sandbox/sandbox/sw/slc7_x86-64/CMake/v3.13.1-8/share/cmake-3.13/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindAliceO2.cmake:48 (find_package_handle_standard_args)
  CMakeLists.txt:89 (find_package)

-- Configuring incomplete, errors occurred!
See also "/mnt/mesos/sandbox/sandbox/sw/BUILD/254ea16763e0a6c2053da8d8ee168bbcf8dd667c/QualityControl/CMakeFiles/CMakeOutput.log".
See also "/mnt/mesos/sandbox/sandbox/sw/BUILD/254ea16763e0a6c2053da8d8ee168bbcf8dd667c/QualityControl/CMakeFiles/CMakeError.log".
```

**Comment by matthiasrichter** [comment]
I actually can't find any other error in the log, O2 is build and everything installed, all unit tests pass. Either it's the above mentioned error or a glitch in the CI. @ktf @dberzano

**Comment by Barthelemy** [comment]
Hi @matthiasrichter , 
This has been fixed here : https://github.com/AliceO2Group/QualityControl/pull/179
QualityControl had to be adapted to the new naming scheme. 
Cheers, 
Barth

**Comment by matthiasrichter** [comment]
thanks for the info, @Barthelemy

**Pull request merged**
