### PR TITLE
Updated copyright headers in all files with new text …

### PR DESCRIPTION
**Pull request by ihrivnac**
… agreed in the O2 project

### CODE REVIEW

**Review by bovulpes — DISMISSED** [review]

**Review by iarsene — DISMISSED** [review]

**Comment by ktf** [comment]
Are you sure about the link? It actually gives "access denied".

I would also use the https version.

**Comment by ihrivnac** [comment]
@ktf, the link should be working now without login, can you check again?
When I go to the page with "http", the browser then changes to "https", so it is working as it is; but we can update it to 'https", if it is safer.

**Review by rpezzi — COMMENTED** [review]
Listing institutions is nice for aesthetical reasons but I am afraid the written statement does not have legal value. By default, authors are the copyright holders of their creations and  I am sure that not every O2 contributor have transferred the copyright of their production to their hosting institution. Formal transfers of copyrights are needed to back the new wording in the header + linked list. To illustrate, here are two examples of collaborative projects with a complex and simple solution to this dilemma, respectively: : 
* [GNU Project](https://www.gnu.org/licenses/why-assign.html): FSF request formal transfer of ownership to defend the rights in court
*  [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Copyrights): Simply states on each article "Author: Wikipedia contributors"

**Comment by ihrivnac** [comment]
> Listing institutions is nice for aesthetical reasons but I am afraid the written statement does not have legal value. By default, authors are the copyright holders of their creations and I am sure that not every O2 contributor have transferred the copyright of their production to their hosting institution. Formal transfers of copyrights are needed to back the new wording in the header + linked list. To illustrate, here are two examples of collaborative projects with a complex and simple solution to this dilemma, respectively: :
> 
> * [GNU Project](https://www.gnu.org/licenses/why-assign.html): FSF request formal transfer of ownership to defend the rights in court
> * [Wikipedia](https://en.wikipedia.org/wiki/Wikipedia:Copyrights): Simply states on each article "Author: Wikipedia contributors"

@rpezzi,
This update of header the files text was consulted with the CERN Legal and Knowledge Transfer Teams. Please, see more details in JIRA [O2-1381](https://alice.its.cern.ch/jira/browse/O2-1381). It has been then discussed in several O2 meetings (including PDP/FLP Plenaries) and approved by all three O2 project leaders, so the purpose of this PR is not to reopen a discussion, but to put the agreed text in place.

**Comment by rpezzi** [comment]
> @rpezzi,
> This update of header the files text was consulted with the CERN Legal and Knowledge Transfer Teams. Please, see more details in JIRA [O2-1381](https://alice.its.cern.ch/jira/browse/O2-1381). It has been then discussed in several O2 meetings (including PDP/FLP Plenaries) and approved by all three O2 project leaders, so the purpose of this PR is not to reopen a discussion, but to put the agreed text in place.

Sorry for not following the discussion in time and on the proper place. But I have say that it is odd to read that CERN is claiming copyright over something it does not have nor does a third party on a list. The current header is vague enough `Copyright CERN and copyright holders of ALICE O2`, i.e., without an exhaustive list. I am surprised the legal team did not raise this issue.  The simplest solution I can think of to simply add something like "and others" to the bottom of the copyright owners list.

However, it is also possible that I missed copyright transfer clause on my employment contract or on the ALICE membership agreement. If this is the case, I apologize for the noise.

**Review by awegrzyn — DISMISSED** [review]

**Comment by ihrivnac** [comment]
> > @rpezzi,
> > This update of header the files text was consulted with the CERN Legal and Knowledge Transfer Teams. Please, see more details in JIRA [O2-1381](https://alice.its.cern.ch/jira/browse/O2-1381). It has been then discussed in several O2 meetings (including PDP/FLP Plenaries) and approved by all three O2 project leaders, so the purpose of this PR is not to reopen a discussion, but to put the agreed text in place.
> 
> Sorry for not following the discussion in time and on the proper place. But I have say that it is odd to read that CERN is claiming copyright over something it does not have nor does a third party on a list. The current header is vague enough `Copyright CERN and copyright holders of ALICE O2`, i.e., without an exhaustive list. I am surprised the legal team did not raise this issue. The simplest solution I can think of to simply add something like "and others" to the bottom of the copyright owners list.
> 
> However, it is also possible that I missed copyright transfer clause on my employment contract or on the ALICE membership agreement. If this is the case, I apologize for the noise.

@rpezzi,  we cannot now change the text, which was discussed and approved by the procedure which I described above. Also note, that the update in this PR does not change the way the copyright holders are presented wrt what was there before.

**Review by rpezzi — DISMISSED** [review]

**Review by vkucera — DISMISSED** [review]

**Pull request merged**
