### PR TITLE
[O2-789] Remove unneeded (and harmful) cross-check about existing target.

### PR DESCRIPTION
**Pull request by aphecetche**
CMake is able to do this much better than this all by itself, e.g.
allowing to reference a not-yet-defined target, while still checking
before the actual building phase that all referenced targes do exist.

### CODE REVIEW

**Comment by davidrohr** [comment]
Do I understand correctly that CMake actually allows "forward" declaration, and we just fooled ourselves because we didn't allow it?

**Comment by aphecetche** [comment]
To be confirmed to see if I did not miss some corner case this time, but yes, that’s my understanding now ...  which is totally opposite to what I argued in some other mail/github exchange at some point, btw. My apologies about that.
If that's confirmed, I'll be able to give back some sanity and simplicity to the top CMakeLists.txt ...

**Comment by davidrohr** [comment]
That would indeed be ideal.
I wonder if this will delay some of the errors that were caught during CMake so far to the link phase of make? If so, perhaps we could have one final check, looping over all dependencies for all O2 libraries at the very end, and check if the dependency-targets exist (should be the case by then)?

**Comment by ktf** [comment]
I would not be surprised if CMake actually did the check itself (after all, it cannot generate a proper makefile if you have circular dependencies). The less O2 specific code, the better, history teaches us.

**Comment by davidrohr** [comment]
I am not sure if CMake can fully check it. The dependency could also be a system library. In that case, CMake would have no control over it, but just add -lfoo to the linker command.

**Comment by ktf** [comment]
wouldn't the system library still be part of some target, with modern CMake?

**Comment by davidrohr** [comment]
not necessarily, if there is no config style CMake file for it on the system.
CMake cannot be sure about this, so I think if the target doesn't exist, it will just forward to the linker.

**Comment by aphecetche** [comment]
I believe we should target (pun intended) to use only targets in our `target_link_libraries` calls, not bare libraries, exactly to avoid such kind of issues. I guess we're mostly in that position already (some improvements could be made to make more obvious that we are using targets, e.g. for the Pythia things, which are targets but are not using the ns::target syntax, so it's not readily obvious those are indeed targets)

If we miss some configs then I would better make a custom Find module (with the associated maintenance burden, so should be avoided as much as possible) to provide a proper target than using a bare library name.

**Comment by aphecetche** [comment]
I assume the Mac build failure is not related to this PR (but to the usage of cmake 3.15 most probably), so I guess this PR is now ready. 
Maybe @ktf you want to give it a try and x-check it actually solves your original problem before merging it ?

**Pull request merged**
