### PR TITLE
Fixes in MCCompLabel, cleanup of redundant labels in matching

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Review by sawenzel — DISMISSED** [review]

**Comment by sawenzel** [comment]
Looks good to me. Ok to merge when last compile errors solved.

**Review by davidrohr — APPROVED** [review]
The changes to the complabel itself seem fully correct to me, didn't look at the mathing code

**Comment by shahor02** [comment]
@ktf @TimoWilken the o2-dataflow CI reports the error from the log of previous failed test: the PR was updated at ~9:30 while the log with error shows ``Finished building on alientest02 at 2021-02-03-08:25:17``
and the errors are exactly those which were corrected...

**Comment by TimoWilken** [comment]
@shahor02 that's because the build fails without producing logs to overwrite the old ones, so the old ones get uploaded again... I've cleaned up the build and reset it, hopefully it'll work this time.

**Pull request merged**
