### PR TITLE
DPL GUI: display metrics for input and output channels

### PR DESCRIPTION
**Pull request by ktf**
This adds labels to each of the channels in input and in output.

In particular the current implementation allows to display the
oldest possible timeslice as seen by the inputs and the one notified
on the output.

Notice that due to the way sending works, the metric on the output
channel might be somewhat delayed wrt its real value.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr as discussed, this provides the oldest possible timeframe as labels to the channels. It should also significantly speedup some GUI related processing for metrics, but I would still advise to run with DPL_DEFAULT_PIPELINE_LENGTH=32...

**Comment by davidrohr** [comment]
I would propose to merge at least the speedup of the GUI soon.
The display of the oldestPossible values could be made optional, I don't think they are always needed.
Also, there is still the problem that the GUI gets messed up when too many devices are present.

**Comment by ktf** [comment]
New PR with just the speedup part at https://github.com/AliceO2Group/AliceO2/pull/9082

**Comment by ktf** [comment]
@matthias-kleiner could you please apply this PR and send me a screenshot of the multiple lanes workflow you have which is getting stuck?

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner could you please apply this PR and send me a screenshot of the multiple lanes workflow you have which is getting stuck?

Yes sure, I will do it. Thanks for your help

**Comment by davidrohr** [comment]
I would opt for making this an optional feature enabled on command line / via env variable, and then merge it in O2 :)

**Comment by ktf** [comment]
Ok, since I came handy also to debug the forwarding, I added the generic support for enabling / disabling services. This can be done by setting either DPL_OVERRIDE_SERVICES or DPL_DRIVER_OVERRIDE_SERVICES, where the former only apply to the dataprocessors. They take a comma separate list of `<device-name>:<enable/disable>` pairs. For this specific case:

```bash
DPL_OVERRIDE_SERVICES=gui-metrics:enable # or 1
```

will behave as requested.

**Comment by ktf** [comment]
Missing nullptr fixed.

**Pull request merged**
