### PR TITLE
ctpdev: raw decoder output size protection 

### PR DESCRIPTION
**Pull request by lietava**
I put protection size as parameter which can be tuned on data.

### CODE REVIEW

**Comment by lietava** [comment]
HI @shahor02 , I added protection as parameter so I can tune it with data and can be fully swicthed off. Please, let me know your comments.

**Comment by shahor02** [comment]
@lietava I thought you wanted to cut on the raw data size before decoding. But this also looks fine. 
At the moment you just log an error, I guess you should count a certain number of consecutive TFs with this error and then produce Fatal?

**Comment by lietava** [comment]
@shahor02 : thanks. Yes, one can cut also on raw input. Anyway I would start like this - just one frame maybe enough for 40 mhz ringing  - and test with raw or directly in P2.

**Comment by lietava** [comment]
PLease, merge

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
