### PR TITLE
Support reading remotely in the strainer

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by mpuccio** [comment]
+async-label async-2024-pp-apass1

**Comment by mpuccio** [comment]
@chiarazampolli @shahor02 if we could merge this for the tag of tonight, it would be great as it will enable a more stable straining (large scale test shows that manually doing alien_cp makes most of the job fail for exhausted workdir size quota).

**Review by shahor02 — APPROVED** [review]
@mpuccio , merging as trivial but for the future it is better to change it to
```
if (line.BeginsWith("alien://") && !gGrid && !TGrid::Connect("alien://")) {
   LOGP(fatal, "failed to connect to the alien");
}
```

**Comment by mpuccio** [comment]
+async-label !async-2024-pp-apass1

**Pull request merged**
