### PR TITLE
Removing full clusters from DisplayTrack.C macro

### PR DESCRIPTION
**Pull request by iouribelikov**

### CODE REVIEW

**Review by shahor02 — DISMISSED** [review]

**Comment by shahor02** [comment]
Thanks @iouribelikov , since you have just suppressed the rootlogons, one should also remove them from https://github.com/AliceO2Group/AliceO2/blob/302a10e1041616547e6b1bd00c7af92d6447a240/cmake/O2RootMacroExclusionList.cmake#L20-L21

**Comment by iouribelikov** [comment]
> Thanks @iouribelikov , since you have just suppressed the rootlogons, one should also remove them from
> 
> https://github.com/AliceO2Group/AliceO2/blob/302a10e1041616547e6b1bd00c7af92d6447a240/cmake/O2RootMacroExclusionList.cmake#L20-L21

@shahor02 Sorry, I forgot to do that. Will do it asap

> Thanks @iouribelikov , since you have just suppressed the rootlogons, one should also remove them from
> 
> https://github.com/AliceO2Group/AliceO2/blob/302a10e1041616547e6b1bd00c7af92d6447a240/cmake/O2RootMacroExclusionList.cmake#L20-L21

@shahor02  Sorry about forgetting that.  Done now.

**Comment by shahor02** [comment]
something is wrong in the formatting, could you pass it via clang-format?

**Comment by iouribelikov** [comment]
> something is wrong in the formatting, could you pass it via clang-format?

@shahor02 Weird. Locally, clang-format works perfectly fine.  But it fails (complaining about the absence of rootlogon.C) on the build machine...

**Comment by shahor02** [comment]
I also cannot reproduce it locally, perhaps @ktf or @sawenzel  can hint why 
````
fatal: ambiguous argument 'Detectors/ITSMFT/ITS/macros/EVE/rootlogon.C': unknown revision or path not in the working tree.
````
is produced by Travis CI?

**Comment by shahor02** [comment]
The Travis CI failure is bogus, locally everything is ok, merging

**Pull request merged**
