### PR TITLE
Fixes for MeanVertex calibrator

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by davidrohr** [comment]
@shahor02 : this sees not correctly rebased

**Comment by shahor02** [comment]
Hi @chiarazampolli, shall I merge this?

**Comment by chiarazampolli** [comment]
> Hi @chiarazampolli, shall I merge this?

Hi @shahor02 , sorry, I will look today.

**Comment by shahor02** [comment]
@chiarazampolli I've tested locally with real data, a few more fixes were needed, will merge after CI

**Comment by martenole** [comment]
@shahor02 and @chiarazampolli all required checks are successful. Shall we merge this now?

**Comment by chiarazampolli** [comment]
Hi @martenole , 
I trust Ruben since he also tested it thoroughly, please merge. Thanks!

**Pull request merged**
