### PR TITLE
quick fix for uint32_t ITSClusterSizes in AnalysisDataModel.h

### PR DESCRIPTION
**Pull request by dsekihat**
quick fix for uint32_t ITSClusterSizes in AnalysisDataModel.h

### CODE REVIEW

**Review by jgrosseo — APPROVED** [review]

**Comment by jgrosseo** [comment]
image
@TimoWilken @ktf Why I don't have the right to merge this without using super powers?

**Review by ktf — APPROVED** [review]

**Comment by ktf** [comment]
Indeed I cannot find any reason why this should not merge. I even did my approval.

@TimoWilken did anything change on the approval side recently?

**Comment by TimoWilken** [comment]
Hi @jgrosseo, @ktf, I think I made a mistake moving from "branch protection rules" to "branch rulesets". The "Restrict updates" option was enabled under the old system, but I should not have enabled it under the new system. Disabled now, it seems to work -- the "merging is blocked" message disappeared and I could merge this without admin permissions.

Let me know if you see this problem again!

**Comment by jgrosseo** [comment]
Thanks!

**Pull request merged**
