### PR TITLE
Avoid segv in case of no selected elements

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@aalkin @ktf Validated on one fully converted file. The selection with filter is identical to the manual selection. :)

**Comment by ktf** [comment]
Is it also faster?

**Comment by jgrosseo** [comment]
Yes, more than factor 10 for the 2PC nested loop :)

**Comment by ktf** [comment]
Cute. Do you have any reasonable comparison with Run1 / Run2?

**Comment by jgrosseo** [comment]
Not for now. Can you approve?

**Comment by ktf** [comment]
I just noticed that @aalkin cannot approve PRs, so I will do it.

**Pull request merged**
