### PR TITLE
Embedded fast field (L3) to MagneticField + test

### PR DESCRIPTION
**Pull request by shahor02**
The test will at the moment due to the absence of O2_ROOT at the moment of test

### CODE REVIEW

**Comment by dberzano** [comment]
Hi @shahor02, it seems the timeout error was indeed temporary, and the compilation moved on. Can you check for the new errors instead?

**Comment by shahor02** [comment]
thanks @dberzano , these were just requests to modernise the header + put the copyright above the ifdef...

**Comment by dberzano** [comment]
Hi @shahor02, it looks fine to me, is this ready to be merged?

**Comment by shahor02** [comment]
@dberzano: yes, thank you

**Pull request merged**
