### PR TITLE
DPL: switch to ws:// as default client for self hosted

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr can you check this is now working correctly for you?

**Comment by ktf** [comment]
@teo, this should not have any effect for AliECS. If you see any, please let me know.

**Comment by teo** [comment]
I don't even know what this is, are you piping stdout somewhere via websocket? Are CLI flags affected?

**Comment by ktf** [comment]
Yes, but only for the case in which the DPL driver is used. When running under a "Control" things should behave exactly the same.

**Comment by ktf** [comment]
@davidrohr do you understand what:

```
reco_NOGPU.log:[58926:CPVClusterizerSpec]: [20:10:47][ERROR] Exception caught: bitset::test: __position (which is 23040) >= _Nb (which is 23040) 
reco_NOGPU.log-[58926:CPVClusterizerSpec]: /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5535-1/lib/libO2FrameworkFoundation.so(_ZN2o29framework13runtime_errorEPKc+0x74)[0x7fe9968a7a54]
reco_NOGPU.log-[58926:CPVClusterizerSpec]: /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5535-1/lib/libO2Framework.so(+0x1106e5)[0x7fe9979c16e5]
killing child 56782
killing child 56785
killing child 56787
killing child 56788
killing child 56793
killing child 56794
killing child 56834
killing child 57752
killing child 58347
killing child 58779
killing child 60094
killing child 62747
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5535-1/share/scripts/jobutils.sh: line 48: 56782 Killed                  eval ${finalcommand} >> ${logfile} 2>&1
Running: TIME="#walltime %e" /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5535-1/share/scripts/monitor-mem.sh /usr/bin/time --output=reco_NOGPU.log_time './reco_NOGPU.log_tmp.sh'
/usr/bin/time --output=reco_NOGPU.log_time ./reco_NOGPU.log_tmp.sh
```

means?

**Comment by shahor02** [comment]
@ktf: bitset overflow will be fixed by https://github.com/AliceO2Group/AliceO2/pull/5499

**Comment by ktf** [comment]
Ok. Looks like there is still some errors, though.

**Comment by shahor02** [comment]
If you mean this:
````
[ 93%] Building CXX object Modules/FT0/CMakeFiles/o2-qc-ft0-data-producer.dir/src/runDataProducer.cxx.o
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/SOURCES/QualityControl/v1.10.0/v1.10.0/Modules/PHOS/src/runQCPHOSRaw.cxx:6:10: fatal error: PHOSWorkflow/PublisherSpec.h: No such file or directory
 #include <PHOSWorkflow/PublisherSpec.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````, 
it is in the QC. @peressounko has moved a class in O2 and will provide corresponding patch for QC.

**Comment by ktf** [comment]
@TimoWilken could you restart the fullCI on this PR?

**Comment by TimoWilken** [comment]
@ktf done!

**Comment by ktf** [comment]
@jgrosseo @davidrohr @sawenzel I am merging this, since the tests seem to pass. If you have any regression you can revert back to the old behaviour with `--driver-client-backend stdout://`.

**Comment by shahor02** [comment]
@ktf this PR leads to a memory buildup: I am running gdb on the last device in the workflow which processes just 1 TF read from the disk (i.e. all upstream devices should not do any processing once the last one starts). 
While gdb is paused on a breakpoint, all dpl devices show 100% cpu usage, the memory consumption keeps growing (~100MB/s), eventually it system starts swapping and everything freezes. 

If I revert this (and https://github.com/AliceO2Group/AliceO2/pull/5537) or run with ``--driver-client-backend stdout://``, everything is back to normal.

**Comment by ktf** [comment]
Ok, reverting back... Can you provide me more details on your workflow?

**Comment by shahor02** [comment]
@ktf to reproduce it you can download input data from https://cernbox.cern.ch/index.php/s/6Ij0dQbkhvCYGad and start
````
o2-primary-vertexing-workflow  --shm-segment-size 10000000000 --disable-vertex-track-matching -s
````
then start ``gdb`` on ``primary-vertexing`` device, set e.g. ``bre PVertexer.cxx:540`` and run. Once it stops on the breakpoint, the memory keeps growing (with this small data slower than in my full test, still well noticeable).

**Pull request merged**
