### PR TITLE
DPL: fix memory leak in ws:// driver.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 can you check if this improves the situation with `--driver-client ws://`?

**Comment by shahor02** [comment]
@ktf thanks, this fixes the problem.

**Comment by ktf** [comment]
Does it fix also the 100% cpu consumption problem?

**Comment by shahor02** [comment]
No, but 100% cpu is there also with ``stdout://``, at least when one of devices is paused in gdb.

**Comment by ktf** [comment]
Ok. I will check.

**Pull request merged**
