### PR TITLE
DPL: broadcasts messages containing SourceInfoHeader

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@wiechula can you check if with this the end of stream is correctly broadcast without having to mess with the dataspec?

**Comment by wiechula** [comment]
@ktf , it does not compile, see logs:
```
/data/Work/software/alicesw/sw/SOURCES/O2/O2-work/0/Framework/Core/test/test_ExternalFairMQDeviceWorkflow.cxx: In function ‘std::vector<o2::framework::DataProcessorSpec> defineDataProcessing(const o2::framework::ConfigContext&)’:
/data/Work/software/alicesw/sw/SOURCES/O2/O2-work/0/Framework/Core/test/test_ExternalFairMQDeviceWorkflow.cxx:184:5: error: could not convert ‘converter’ from ‘defineDataProcessing(const o2::framework::ConfigContext&)::<lambda(FairMQDevice&, FairMQParts&, o2::framework::ChannelRetriever)>’ to ‘o2::framework::InjectorFunction’ {aka ‘std::function<void(o2::framework::ControlService&, FairMQDevice&, FairMQParts&, std::function<std::__cxx11::basic_string<char>(const o2::framework::OutputSpec&, long unsigned int)>)>’}
  184 |     converter));
      |     ^~~~~~~~~
      |     |
      |     defineDataProcessing(const o2::framework::ConfigContext&)::<lambda(FairMQDevice&, FairMQParts&, o2::framework::ChannelRetriever)>
```

**Comment by wiechula** [comment]
@ktf , any news on this?

**Comment by ktf** [comment]
I need to push a refactoring I have.

**Comment by ktf** [comment]
Updated. Can you check?

**Comment by aferrero2707** [comment]
@ktf there is some error regarding the conversion of lambda functions to `o2::framework::InjectorFunction`. I am getting a different but equivalent error on my local builds.

**Comment by ktf** [comment]
I fixed one but I missed the second one. Update coming.

**Comment by ktf** [comment]
Can you try now?

**Comment by aferrero2707** [comment]
@ktf I have been able to compile O2 with the patch from this PR, however I still do not see the end-of-stream being called when I terminate the workflow with ctrl-C (the method that used to work in the past).

What is the proper way of terminating a workflow such that the eos message gets propagated?

**Pull request closed without merging**
