### PR TITLE
CPV: read and write raw data with dataformat = 0x2

### PR DESCRIPTION
**Pull request by sevdokim**
Hello! This commit enables reading and writing cpv raw data with dataformat = 0x2

### CODE REVIEW

**Review by kharlov — APPROVED** [review]

**Review by shahor02 — APPROVED** [review]
@sevdokim thanks, looks fine to me, shall I merge or you need to do more tests?

**Comment by sevdokim** [comment]
hi @shahor02,
I checked with MC and pedestal data. It is read fine. So I think you can merge.

**Comment by shahor02** [comment]
Hi @sevdokim 
Please note that decoding of cosmic data with dataformat=2 complains about "unknown words": https://ali-bookkeeping.cern.ch/?page=log-detail&id=42855. Could you check please?

**Comment by sevdokim** [comment]
Hi @shahor02 
Seems that o2 version that was used in run 532819 was OVERRIDE_PDPSUITE_VERSION='O2PDPSuite/epn-20230309-DDv1.5.3-flp-suite-v0.89.0-1' which does not contain this commit. Or am I wrong?

**Comment by shahor02** [comment]
Hi @sevdokim 
I was reconstructing in my PC with O2 dev after merging your PR

**Pull request merged**
