### PR TITLE
Support decoding old ITS/MFT format

### PR DESCRIPTION
**Pull request by shahor02**
With option --old-format provided the STFDecoderSpec will interpret data as
in old format: single trigger per HBF, no GBT trigger word

### CODE REVIEW

**Comment by shahor02** [comment]
@iouribelikov this PR allows to decode old ITS format in the ``o2-itsmft-stf-decoder-workflow``.

I've tested it with this [config file](https://cernbox.cern.ch/index.php/s/Tns1WjTrDJtytti) (you will need to unpack the lz4-ed files, the reader does not support reading directly from compressed files, at least at this moment) as:
````
o2-raw-file-reader-workflow ---conf run200029.cfg   | o2-itsmft-stf-decoder-workflow  --old-format
````

Note that cosmic data files contain lot of errors, particularly all ``RDH.stop`` are missing. The data are still decodable but lot of error messages are produced. You can suppress them as 
````
o2-raw-file-reader-workflow --nocheck-missing-stop --max-tf 100 --conf run200029.cfg   | o2-itsmft-stf-decoder-workflow  --old-format --decoder-verbosity -1
````
but these options will be available only when https://github.com/AliceO2Group/AliceO2/pull/3496 is merged (also ``--max-tf`` which allows to read only limited number of TFs).

**Comment by shahor02** [comment]
@davidrohr Do you understand what is wrong with gpu CI?
I fails with 
````
Preprocessed source stored into /tmp/ccdGj73W.out file, please attach this to your bugreport.
gmake[2]: *** [Analysis/Tasks/CMakeFiles/O2exe-analysis-jetfinder.dir/build.make:80: Analysis/Tasks/CMakeFiles/O2exe-analysis-jetfinder.dir/jetfinder.cxx.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:25677: Analysis/Tasks/CMakeFiles/O2exe-analysis-jetfinder.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
````
on something which has nothing to do with my PR, but in my docker dev+this PR is build w/o problem.

**Comment by davidrohr** [comment]
It fails here:
```
/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3497/0/Analysis/Tasks/jetfinder.cxx:87:3: internal compiler error: Segmentation fault
```
I have seen this internal compiler error also in the other CIs sporadically. For me, it happens only with GCC 7.3, not with newer version. I believed it is a GCC bug. I actually commented on this on other PRs before, when we had this problem before.
I have no idea why it disappeared in the meantime or whether or how it was solved and why it appears again now.

**Comment by shahor02** [comment]
OK, sorry for spamming, did not notice the line with internal error.

**Pull request merged**
