### PR TITLE
DPL: make sure the WSDriverClient flushes only on main thread

### PR DESCRIPTION
**Pull request by ktf**
This will avoid thread safety issues within libuv. Notice this
will most likely kill any rate limiting as currently implemented
as I will need a protection against event loop being waken up by
metrics rather than sigusr1.

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken also here the checkers are not running...

**Comment by ktf** [comment]
@davidrohr @shahor02 @sawenzel I see:

```
[INFO] PHS is in grp? yes; is skipped? yes
[INFO] CPV is in grp? yes; is skipped? yes
[INFO] CTP is in grp? yes; is skipped? yes
Error: unrecognised option '--enable-trd-trapsim'
Job finished; Exiting 
PROCESS MAX MEM = 202.317
PROCESS AVG MEM = 118.803
```

does it ring any bell?

**Comment by davidrohr** [comment]
@ktf : Problem that was introduced after a rebase conflict, I just merged Ruben's fix here: #5899

**Comment by sawenzel** [comment]
@ktf: Rate limiting is used (sometimes when it works) in the GRID workflows to keep CPU under control, since https://alice.its.cern.ch/jira/browse/O2-1907 + https://alice.its.cern.ch/jira/browse/O2-1781 are still pending.

We should hence be careful not to break the GRID productions here. Could we not solve the above issues before going on with this PR?

**Comment by ktf** [comment]
@sawenzel is this the same rate limiting we are talking about? The one I am referring too is the one which is enabled only for the Analysis Framework. Anyway, you are right, I will make sure everything is correctly handled before I merge this.

**Comment by ktf** [comment]
Ok, I think this actually works and fixes the TPC-spectra workflow using websockets. The issue with 100% CPU usage is also understood and fixed in #5922.

**Pull request merged**
