### PR TITLE
Renaming EMCAL libraries starting with libO2EMCAL...

### PR DESCRIPTION
**Pull request by mfasDa**
Avoiding naming clash for EMCAL base library between
AliRoot and o2. This is needed in case one needs to
use libraries from both packages.

### CODE REVIEW

**Comment by mfasDa** [comment]
Ideally this should be handled more on the framework level ...

**Comment by sawenzel** [comment]
@dberzano , @ktf , @Barthelemy : Indeed I am wondering if we should handle this inside the O2_GENERATE_LIBRARY consistently?

**Comment by Barthelemy** [comment]
yes, we could totally do that. When we get rid of the MACROS we should be careful to preserve the naming.

**Comment by mfasDa** [comment]
@sawenzel Thanks! I would be very much in favour of having this in O2_GENERATE_LIBRARY rather than somewhere in the EMCAL CMakeLists. I also think it is not exclusively an EMCAL problem since I guess every detector has a libXXXBase in o2 and AliRoot, so having a general solution would help everyone.

**Comment by sawenzel** [comment]
@mfasDa : Would you be available to try doing the more systematic change in the cmake macro?

**Comment by mfasDa** [comment]
@sawenzel Can we open a JIRA ticket for this and do the discussion there?

**Comment by Barthelemy** [comment]
Here it is : https://alice.its.cern.ch/jira/browse/O2-616

**Comment by mfasDa** [comment]
On hold - will be replaced by #1896

**Comment by mfasDa** [comment]
Closed. Replaced by #1896

**Pull request closed without merging**
