### PR TITLE
Fix compile warning (unused variables)

### PR DESCRIPTION
**Pull request by sawenzel**

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi Sandro,

where did you get these compile warnings?

In general, I agree to fix unused variables, but I am not so sure about unused function parameters as here.
The GPU code has a lot of stuff like:
```
void foo(track& x, int iThread) {
#ifdef GPUCA_GPUCODE_DEVICE
[something with iThread]
#endif
[normal code]
```
This will throw quite some unused function parameter warnings (currently I think it doesn't), but this cannot be fixed as easily.

Cheers
David

**Comment by sawenzel** [comment]
The CI for macos was failing because of this (as it treats warnings as errors) during the checking of the ROOT macros.

**Comment by davidrohr** [comment]
But I don't understand how this suddenly happened, when it was working before?

Anyway, perhaps we could also consider `-Wno-unused-parameter`. As I said before, unused-variable makes sense, not so sure about unused parameters.

**Comment by sawenzel** [comment]
Actually it could be that this always happened. Indeed, the real problem is this one:
```
os_o2_ci_1/sw/SOURCES/O2/2043/0/GPU/TPCFastTransformation/macro/IrregularSpline2D3DTest_C.so
Undefined symbols for architecture x86_64:
  "o2::gpu::IrregularSpline2D3D::construct(int, float const*, int, int, float const*, int)", referenced from:
      IrregularSpline2D3DTest() in IrregularSpline2D3DTest_C_ACLiC_dict.o
  "o2::gpu::IrregularSpline2D3D::IrregularSpline2D3D()", referenced from:
      IrregularSpline2D3DTest() in IrregularSpline2D3DTest_C_ACLiC_dict.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error in <ACLiC>: Compilation failed!
```
which is still present even here.

**Comment by davidrohr** [comment]
Hi Sandro,
the tpc split test is not the one that breaks the CI.
The actual failure is in this test: test_CCDB_testCcdbApi

The IrregularSpline2D3DTest_C.so indeed fails, but it is known to fail on MacOS. It is a linking problem with Vc in the header. I have no idea how to fix it and stopped investigating.

This test is actually running in a non-fatal way, set in `set(EXCLUDE_MACROS_FROM_COMPILED_TEST`.
Dario wrote the macro test CI such that these tests actually run, the will always fail, but be non fatal. Perhaps we should just stop running them completely, to avoid misleading output and false negatives like here?

**Comment by davidrohr** [comment]
Btw, the problem with the ccdb test might be that the ccdb test instance is down again. We had the same problem two weeks ago. No idea who fixed it. But perhaps you can check who is responsible, because this will again break all PRs!

**Comment by davidrohr** [comment]
ok, its is no problem with the ccdb instance I guess. The test just segfaults on MacOS, also for other PRs (e.g. 2038).

**Pull request closed without merging**
