### PR TITLE
Move DataHeader to use fmt::format

### PR DESCRIPTION
**Pull request by ktf**
Allows us to remove some code from DataHeader.h, which is
included pretty much everywhere.

### CODE REVIEW

**Comment by ktf** [comment]
@mkrzewic @matthiasrichter @davidrohr @shahor02 this should simplify the formatting and the Descriptor class itself. We can probably get rid of as<std::string> and use a std::string_view instead.

**Comment by davidrohr** [comment]
fine for me if it works

**Comment by ktf** [comment]
I  need to patch QualityControl or do things in steps... :-/

**Comment by ktf** [comment]
I have refactored the parts of this PR which do not break QC in #5819. We will be able to merge this only once #5819 is merged and a QC tag adapted to use the new functionality.

**Comment by ktf** [comment]
Now that the associated QC is released (thanks @Barthelemy!), we can merge this.

**Pull request merged**
