### PR TITLE
Optionally select CTFs in timestamps or orbits range

### PR DESCRIPTION
**Pull request by shahor02**
```
--run-time-span-file <text file with run range_min range_max entries>
```
This option allows to push to DPL only those TFs which overlap with the `<runnumber> <range-min> <range-max>` (separators can be any whitespace, comma or semicolon) records provided via text file (assuming that there are some entries for a given run, otherwise the option is ignored).
Multiple ranges per run and multiple runs can be mentioned in a single input file. The range limits can be indicated either as a UNIX timestamp in `ms` or as an orbit number (in the fill the run belongs to).

In case an option
```
--invert-irframe-selection
```
is provided, the selections above are inverted: TFs matching some of the provided ranges will be discarded, while the rest will be pushed to the DPL

At the end of the processing the `ctf-writer` will create a local file `ctf_read_ntf.txt` containing only the number of TFs pushed to the DPL.
If no TF passes the selections above, this file will contain 0.

### CODE REVIEW

**Comment by shahor02** [comment]
@chiarazampolli

**Comment by chiarazampolli** [comment]
Thanks!

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

Can one add a tab separation? This is the easiest to export in csv format (even if also the others work).

Chiara

**Comment by shahor02** [comment]
Hi, as the commit says, the separator can be whitespace (tab, space), comma or `;`

**Pull request merged**
