### PR TITLE
Implementation of generic workflow utilities in DPL

### PR DESCRIPTION
**Pull request by gabrielefronze**
Generic broadcaster, gatherer, merger and splitter are implemented to be used in users workflows.

### CODE REVIEW

**Comment by gabrielefronze** [comment]
Compilation errors should now be fixed.

**Comment by sawenzel** [comment]
@ktf: Should we go on with this?

**Comment by ktf** [comment]
I would go on with this, yes. We can always revisit it later.

**Comment by gabrielefronze** [comment]
Thanks!
Feel free to comment, I'll apply suggestions asap.

**Pull request merged**
