### PR TITLE
MFT: speed-up the tracking

### PR DESCRIPTION
**Pull request by bovulpes**
- re-write and simplify many parts of the code
- clean-up very old stuff, not used anymore
- fix some tricky bugs
- speed-up the track finding

### CODE REVIEW

**Comment by shahor02** [comment]
@ktf I see here "Check PR with clang-format" reporting PR not clean, w/o extra details. Shall I ignore it?

**Comment by ktf** [comment]
No, @bovulpes could you merge the fix proposed by the check? https://github.com/bovulpes/AliceO2/pull/6/files

**Comment by bovulpes** [comment]
OK, fixed, but it is difficult to spot such problems, the closing curled bracket was indented by a combination of one tab and several spaces, emacs did this, I did not run clang-format again, it is true...

**Comment by ktf** [comment]
That's why we now have the bot creating a PR with the fixes to your PR, now. :-)

**Pull request merged**
