### PR TITLE
ITS-GPU: Fix undetected checkode errors

### PR DESCRIPTION
**Pull request by mconcas**
Errors to fix:
```
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VectorHIP.h:18:10: error: inclusion of deprecated C++ header 'assert.h'; consider using 'cassert' instead [modernize-deprecated-headers]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VertexerTraitsHIP.h:50:11: error: prefer using 'override' or (rarely) 'final' instead of 'virtual' [modernize-use-override]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/src/StreamHIP.hip.cxx:24:12: error: use '= default' to define a trivial default constructor [modernize-use-equals-default]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/src/StreamHIP.hip.cxx:29:12: error: use '= default' to define a trivial destructor [modernize-use-equals-default]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VectorHIP.h:18:10: error: inclusion of deprecated C++ header 'assert.h'; consider using 'cassert' instead [modernize-deprecated-headers]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VectorHIP.h:18:10: error: inclusion of deprecated C++ header 'assert.h'; consider using 'cassert' instead [modernize-deprecated-headers]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/include/ITStrackingHIP/VertexerTraitsHIP.h:50:11: error: prefer using 'override' or (rarely) 'final' instead of 'virtual' [modernize-use-override]
/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/src/VertexerTraitsHIP.hip.cxx:18:10: error: inclusion of deprecated C++ header 'assert.h'; consider using 'cassert' instead [modernize-deprecated-headers]
```

### CODE REVIEW

**Comment by mconcas** [comment]
@davidrohr Unfortunately I am not able to test it right now.
A part from one error, which I am not sure I understood the others should be fixed.
The error is:
``/home/qon/alice-builder/sw/SOURCES/O2/v1.1.0/0/Detectors/ITSMFT/ITS/tracking/hip/src/StreamHIP.hip.cxx:29:12: error: use '= default' to define a trivial destructor [modernize-use-equals-default]`

To me it appears that a destructor like:

```
StreamHIP::~StreamHIP()
{
  (void)hipStreamDestroy(mStream);
}```

is not trivial.
Am I missing something?

Cheers

**Comment by davidrohr** [comment]
@mconcas : That is a problem related to HIP headers and the codechecker. You can silence it like I did here: https://github.com/AliceO2Group/AliceO2/pull/2893/files#diff-abdbc81a2f8f7625a367c7b120f1ea26R62

**Comment by mconcas** [comment]
Ok, this should be now silenced.

**Comment by davidrohr** [comment]
ah, nice, you found a different way to silence it :|

**Comment by mconcas** [comment]
> ah, nice, you found a different way to silence it :|

no, I just committed the wrong thing, fixing...

**Comment by mconcas** [comment]
Not sure if the CI problem is related to this. When you have the time to test it locally feel free to merge it.
@davidrohr Please, let me know if further issues arise.

Cheers

**Pull request merged**
