### PR TITLE
TRD: Fix FeeParam variable initialization

### PR DESCRIPTION
**Pull request by jolopezl**

### CODE REVIEW

**Review by bazinski — APPROVED** [review]

**Review by martenole — APPROVED** [review]
It is better readable now, but the functionality is exactly the same, right? Or is this fixing a bug?

**Comment by jolopezl** [comment]
> It is better readable now, but the functionality is exactly the same, right? Or is this fixing a bug?

In the previous code the variable `j` is stuck in `0`.

**Comment by martenole** [comment]
Oh, you are right. It should have been `j++` inside the lambdas.. Nice catch

**Review by tdietel — APPROVED** [review]

**Comment by davidrohr** [comment]
@TimoWilken : Could you trigger a restart of the O2/o2 CI here? Apparantly it also ran out of memory.
This is kind of strange, since this here is still running with GCC 7.3.

**Comment by davidrohr** [comment]
actually, this is trivial, merging

**Pull request merged**
