### PR TITLE
CCDB: Sanitize the path and object name (QC-165)

### PR DESCRIPTION
**Pull request by Barthelemy**
Do not merge until we ahve a fix on the QC side as well !

### CODE REVIEW

**Comment by Barthelemy** [comment]
@awegrzyn

**Comment by awegrzyn** [comment]
Can we test it with a string that actually broke NodeJS JSON parser?

**Comment by Barthelemy** [comment]
I tested it with several strings that we saw in the past and were illegal. I will check what is wrong with the build failure on mac.

**Comment by awegrzyn** [comment]
It's a O2 test that fails recently quite often, the problem is that because of that QC is not built at all.

**Comment by Barthelemy** [comment]
There is a CCDB test failing too. I am putting more output because I can't reproduce it.

**Comment by Barthelemy** [comment]
@dberzano Can a test access the ccdb-test.cern.ch:8080 from the build server ?

**Comment by Barthelemy** [comment]
Ok, errors are unrelated, I will merge.

**Pull request merged**
