### PR TITLE
DPL: workaround std::variant ABI issue with devtoolset-7 (O2-1384)

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
Nice, did you test it in the CI container? Shall I run a test locally?

**Comment by ktf** [comment]
If I understand correctly, the issue is that `std::variant` move constructors using the RH GCC 7.3 compiler is **not** `noexcept`:

```c++
variant& operator=(variant&&) = default;
```

leading to ABI issues when something which has an std::variant member uses a `noexcept` move constructor. 

The reason this works fine on mac and with the vanilla GCC 7.3 is that there it is `noexcept`. In particular both mac and linux have:

```
variant(variant&&) noexcept((is_nothrow_move_constructible_v<_Types> && ...)) = default;
```

If I understand correctly [what the standard says](https://en.cppreference.com/w/cpp/utility/variant/variant) the RH version is wrong.

**Comment by ironMann** [comment]
Um, sorry too late. I had a different solution ... It was just reversing the implementations of `DataDescriptorMatcher(DataDescriptorMatcher const& other)` and `DataDescriptorMatcher::operator=(DataDescriptorMatcher const& other)`.  

What I saw in debugger is that sort was using the assignment operator which is calling itself recursively. My change is moving the body of copy constructor to the assignment operator, and using that to implement the copy constructor.
Does that make sense?

**Comment by ktf** [comment]
Yeah, I saw the same... I wonder if the noexcept is simply making it ignore the the move constructor because one of the underlying classes is not `noexcept`. In principle I would have assumed:

```c++
*this = Something{other};
```

meant "Create a copy and move it in place of the current one". Clearly if it gets compiled as "Create a copy and assign to the current one" we have a problem.

Does it actually work with noexcept if you reshuffle the code?

**Comment by ironMann** [comment]
Yes, it works without changing noexcept. I think the move assignment here does not participate in overload resolution for some reason. Also, the default move assignment operator should not be declared `noexcept` because the `Node` is not nothrow-move-assignable. I.e., even this trips:
`static_assert(std::is_nothrow_move_assignable_v<OriginValueMatcher>);`

Ultimately, not sure what exactly is going on. Your assumption is ocrrect, and it works if when you only remove noexcept from the move assigment operator.

**Comment by matthiasrichter** [comment]
interesting!

**Comment by ktf** [comment]
Yes, in your case it would use the copy and then the current implementation is wrong. However without the noexcept it should use the move constructor, so I would keep it as it is. The problem is that also std::string is not non-`noexcept` on RH, by design (I think that's exactly what their GCC reverts compared to the system one for ABI compatibility sake).

**Comment by ktf** [comment]
Time to move to rust...

**Pull request merged**
