### PR TITLE
MCH: added explicit cluster size data member to SampaCluster structure

### PR DESCRIPTION
**Pull request by aferrero2707**
This allows to keep track of the cluster size also in charge sum mode.

### CODE REVIEW

**Comment by aferrero2707** [comment]
The addition of the correct cluster size in charge sum mode is now making two test fail, namely
```
Detectors/MUON/MCH/Raw/test/testClosureCoDec.cxx
```
and
```
Detectors/MUON/MCH/Raw/Decoder/src/testUserLogicEndpointDecoder.cxx
```
They can be both traced back to [this variable](https://github.com/AliceMCH/AliceO2/blob/mch-sampacluster-csize-fix/Detectors/MUON/MCH/Raw/Decoder/src/UserLogicElinkDecoder.h#L325) that is not initialized properly, since in clusterSum mode the cluster size and the number of 10-bit words do not match.
We plan to solve this issue in a subsequent PR which contains a number of bug fixes in the UserLogic decoder. So how should we proceed with this one?

**Comment by aphecetche** [comment]
@aferrero2707 ah, that's annoying, but what can be done (if the next PR is not too distant in the future) is to de-activate those two tests (in the relevant CMakeLists.txt) and then re-activate them in the next PR. 
The alternative would be to integrate the minimal changes from the bug fixes to make those tests pass in this PR, of course.

**Comment by aferrero2707** [comment]
I would personally vote for the second option, which would leave the code in a working state.
In the present state of this PR the decoding of UL charge-sum data is completely broken, as the failing tests indicate...

**Comment by aphecetche** [comment]
@aferrero2707, agreed that would of course be better.

**Comment by aferrero2707** [comment]
@aphecetche I have committed the fix and the tests seem to be ok now.

**Comment by aferrero2707** [comment]
@davidrohr there is one check that fails due to a timeout. From [this log file](https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/3735/1b9025937545bf5efec40083fcf41b2c7b9ca028/build_O2_o2/fullLog.txt):
```
28/34 Test #34: testQcTPC ........................   Passed    8.56 sec
29/34 Test #30: testFactory ......................   Passed   13.16 sec
30/34 Test #33: testQcTOF ........................   Passed   10.51 sec
31/34 Test #35: testQcITS ........................   Passed    3.81 sec
32/34 Test #36: testQcMFT ........................   Passed    3.35 sec
33/34 Test #24: testWorkflow .....................   Passed   19.50 sec
34/34 Test #23: testCheckWorkflow ................***Timeout  20.16 sec
```
Any idea what might be wrong?

**Pull request merged**
