### PR TITLE
DO NOT MERGE Drop boost::serialize support

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by knopers8** [comment]
In QC, we were considering to support `boost::histograms` in a more distant future. I guess we would have to (de)serialise them by hand in such case, wouldn't we? Or they can fall back to other group of types?

**Comment by ktf** [comment]
For now I just want to see if this is the culprit with memory utilisation when compiling. If it is, we think about the strategy.

**Comment by knopers8** [comment]
I gave it a try, -j 5 with 8GB RAM still fails, but I've managed to build it with -j 2, which wasn't possible before (but it could have been just luck now).

**Comment by ktf** [comment]
Any chance to try on a 16GB machine?

**Comment by knopers8** [comment]
Not specifically on 16GB, but I can try on 128GB and measure memory usage during the build, I'll let you know what happened.

**Comment by ktf** [comment]
Yes, that would also do.

**Comment by knopers8** [comment]
image

CC7, 128GB RAM, -j16 ( just as in Sylvain's plot). The peak usage is 27GB. Trying with dev, to be sure it changes something (Sylvain reported 32GB at peak)

**Comment by knopers8** [comment]
I see 28GB peak with dev.

**Pull request closed without merging**
