### PR TITLE
Adding Forward (MFT+Muon) tables

### PR DESCRIPTION
**Pull request by jgrosseo**
Work by @rpezzi

### CODE REVIEW

**Comment by jgrosseo** [comment]
@rpezzi @pillot @aphecetche Please check if everything is OK

**Comment by rpezzi** [comment]
Hi @jgrosseo , thanks for the final touches. Looks fine. Worth mention #5360 here.

**Comment by pillot** [comment]
Thanks @rpezzi and @jgrosseo. Just a small correction:
the number of clusters `NClusters` is needed for every tracks, like the chi2, so it should be added to `StoredFwdTracks`too.
Beside that, everything looks fine to me.

**Comment by jgrosseo** [comment]
> Thanks @rpezzi and @jgrosseo. Just a small correction:
> the number of clusters `NClusters` is needed for every tracks, like the chi2, so it should be added to `StoredFwdTracks`too.
> Beside that, everything looks fine to me.

Added

**Pull request merged**
