### PR TITLE
GPU: Add SMatrixGPU and Fwd decls

### PR DESCRIPTION
**Pull request by mconcas**
Also replaces the inclusion in DCAfitterN.h

### CODE REVIEW

**Comment by mconcas** [comment]
@davidrohr I set up a possible implementation, did I get correctly the approach?
No GPU test included yet.

**Review by davidrohr — DISMISSED** [review]
Looks good to me. Do you want to do more tests, or shall I merge?

**Comment by mconcas** [comment]
> Looks good to me. Do you want to do more tests, or shall I merge?

It actually looks like we have an issue with OpenCL or it is something unrelated?

**Comment by davidrohr** [comment]
Argh, indeed, I hadn't checked the CI yet :(
Indeed, it seems to have a problem with the function pointer.
It might actually be that this is already fixed in clang 12, since I have reported it to them some time ago.
But to upgrade, I'd have to create a new GPU CI container with a build of the current clang trunk (which I have to do anyway for other reasons).
Could you perhaps for now add an `#ifndef __OPENCL__` for the include you put in the cartesian.h, such that it is not seen in OpenCL? I'll follow up this OpenCL issue in the meantime.

**Comment by mconcas** [comment]
> Argh, indeed, I hadn't checked the CI yet :(
> Indeed, it seems to have a problem with the function pointer.
> It might actually be that this is already fixed in clang 12, since I have reported it to them some time ago.
> But to upgrade, I'd have to create a new GPU CI container with a build of the current clang trunk (which I have to do anyway for other reasons).
> Could you perhaps for now add an `#ifndef __OPENCL__` for the include you put in the cartesian.h, such that it is not seen in OpenCL? I'll follow up this OpenCL issue in the meantime.

Yes, I can for sure.
I investigated a bit and it looks like passing the funciton is forbidden in OpenCL 1.2.
Are we so lucky that they improved with 2.0 and the error is triggered just by the flag `#pragma OPENCL EXTENSION __cl_clang_function_pointers : enable` not taken into account?

Just to understand whether it will be required some changes on the code in near future.

Thanks, setting up the workaround in the meanwhile...

**Comment by davidrohr** [comment]
Yes, clang has this extension for function pointers (although it does not work with all types of function pointers, but I guess yours are fine. We'll see). I'll check with clang master, if it fails there, you'd need to change the code indeed, but let's hope not.

**Comment by mconcas** [comment]
@davidrohr seems to me that error is not related to this pr. Should I fix it here? Not a problem to me.

**Comment by davidrohr** [comment]
Ah, that is my standalone benchmark, which can be compiled after I updated the GPU CI container.
Beforehand, some libs were missing in the container, so before the CI never compiled it, thus never saw the violations.
I'll take care of them.

**Pull request merged**
