### PR TITLE
ZDC digi2raw options --file-for all,flp,cru,link

### PR DESCRIPTION
**Pull request by cortesep**

### CODE REVIEW

**Review by shahor02 — DISMISSED** [review]
Hi @cortesep 
thanks, looks fine. But I see that you still keep merging dev instead of rebasing to it.
You should do `git pull --rebase` or run once `git config --global pull.rebase true` so that the `rebase` becomes default.

**Comment by davidrohr** [comment]
Hi @cortesep : Could you please edit `prodtests/full_system_test.sh` where the ZDC raw encoder is used, and change the option there from the old syntax to the new `--file-for` syntax? Could you please also rebase this commit on dev instead of merging it as mentioned by Ruben?

**Comment by cortesep** [comment]
I made rebase and modified the file. Should be ok now

**Comment by davidrohr** [comment]
Hi @cortesep : there are still plenty of merge commits, and also several new empty files are created in this PR. Could you rebase on dev, remove these files, and then squash everything into one commit?

**Comment by cortesep** [comment]
Opening a new pull request from new branch

**Pull request closed without merging**
