### PR TITLE
infologger renaming

### PR DESCRIPTION
**Pull request by sy-c**

### CODE REVIEW

**Review by ktf — DISMISSED** [review]
Fine with me. I had to fix one merge conflict though.

**Comment by davidrohr** [comment]
Actually, `INFOLOGGER_OPTIONS` must be renamed, too in here: https://github.com/AliceO2Group/AliceO2/blob/44399b0acec599ac0657ecd067330fb670b1f329/prodtests/full-system-test/convert-raw-to-tf-file.sh#L31

**Comment by ktf** [comment]
@sy-c done

**Comment by sy-c** [comment]
@ktf thank you !

**Pull request merged**
