### PR TITLE
DPL: do not update the new run flag unless we do process data

### PR DESCRIPTION
**Pull request by ktf**
DPL: do not update the new run flag unless we do process data

Data might be dropped by the oldest possible timeframe mechanism for the
first timeslice which arrives, at which point we lose the information about
the new run.

Moving it down ensures that the check is done for the first timeframe which arrives.

---
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/AliceO2Group/AliceO2/pull/12600).
* #12605
* __->__ #12600

### CODE REVIEW

**Comment by martenole** [comment]
This breaks the GPU reconstruction. I can reproduce that also on the EPNs.

**Comment by ktf** [comment]
Ok, I can reproduce it locally as well.

**Comment by ktf** [comment]
@martenole this seems to finally work.

**Comment by martenole** [comment]
Thanks, also FST on the EPNs is passing. Merging

**Pull request merged**
