### PR TITLE
PHOS raw reader barebone  implementation with mapping

### PR DESCRIPTION
**Pull request by policheh**

### CODE REVIEW

**Comment by sawenzel** [comment]
Is there any development here?

**Comment by policheh** [comment]
Hi Ruben,

> The CI test on all platforms fails. More important: you are loading the mapping from the data files ?>starting from `$O2_ROOT/shared/...` which is defined only after installation. This will make >problematic running the tests later. Is the mapping you are loading defined once and forever (in >which case it is better implemented programmatically) or it is a kind of condition data (then it >should be loaded from the CDB object with some reasonable defaults).

It's not foreseen to change mappings.
However, I'd prefer to store them to CDB and not to hardcode them.

So I need first to put these files into the centralized CDB storage.
From AliceO2/CCDB/README I figured out that I have to use command o2-ccdb-upload. Unfortunately, this command is not working in my O2 installation. So my first question: how can I put my mapping files?

Cheers,
Boris

**Comment by shahor02** [comment]
Hi @policheh 
what exactly does not work with ccdb upload? As an example you can use this ZDC macro creating and uploading an object to ccdb: https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/ZDC/macro/CreateModuleConfig.C
Cheers,
 Ruben

**Comment by policheh** [comment]
Hi Ruben,
thank you for this example.

> what exactly does not work with ccdb upload? As an example you can use this ZDC macro creating and uploading an object to ccdb: https://github.com/AliceO2Group/AliceO2/blob/dev/Detectors/ZDC/macro/CreateModuleConfig.C

However, is it still possible to use $O2_ROOT/share/Detectors/PHS/.. as a place for input files for some kind of such macros that feeds the PHOS CCDB? I've already seen such examples: $O2_ROOT//share/Detectors/EMC/files/RCU* .

If so, do I have rights to commit to $O2_ROOT//share/Detectors/ ?

Cheers,
Boris

**Pull request closed without merging**
