### PR TITLE
[CPV] Fix CPV calibration objects

### PR DESCRIPTION
**Pull request by sevdokim**
Added protection against accessing non-existing addresses in o2::cpv::CalibParams,  o2::cpv::BadChannelMap and o2::cpv::Pedestals.

### CODE REVIEW

**Review by kharlov — DISMISSED** [review]

**Comment by sevdokim** [comment]
Dear @shahor02, 

I added checks for valid addresses into calibration objects but probably this is too much checks (thanks @peressounko for pointing this out). Some checks are already present in the RawDecoder and RawWriter. Is it better to discard checks proposed in this PR?

**Comment by shahor02** [comment]
Hi @sevdokim 
If you are sure non-existent channels are rejected upstream, then it is indeed better to not check them again. But where these channels some from? Are they produced by your firmware? 

In an case, the CI fails due to the missing {} after if.

**Comment by sevdokim** [comment]
Hi @shahor02,

currently checks are actually done in Detectors/CPV/base/src/Geometry.cxx when calculating addresses from and to Hardware address. So I suppose that non-existent addresses shouldn't appear during reading or writing raw data. I think it's better to remove the checks from reading from calibration objects as this operation is quite often. However writing to calibration object is not happening so frequently so why not to let the check be in there, right?

**Comment by shahor02** [comment]
Hi @sevdokim 
I want to understand where the non-existent channels may appear at all, Who produces them, your firmware?

**Comment by sevdokim** [comment]
@shahor02, yes, sometimes non-existent channels were appearing due to firmware problems. I'm not sure that this is actually a problem of firmware because originally some FEE cards were designed to read 64 channels but we use only 48. Some times some of remaining 16 channels appears in raw data. Before my previous commit they weren't tracked and they become like non-existent channels in data flow which lead to many errors. Now I track and exclude such channels in RawDecoder, and in principle we will not see them anymore.

**Comment by sevdokim** [comment]
Dear @shahor02,

I also want to undestand if I need @kharlov or @peressounko to approve the PR? 
It seems that their approval do nothing actually. Or not?

**Comment by shahor02** [comment]
Thanks @sevdokim , then, if the FW cannot be fixed, I would introduce a check only in the beginning of the decoding, and would eliminate all others. Adding unnecessary protections might be even dangerous since will hide real bugs (apart from eventual overhead). If you suspect appearance of wrong channels beyond this FW problem, better to add an assert(...) (which will be compiled out in production) and compile w/o NDEBUG.

**Comment by shahor02** [comment]
> I also want to undestand if I need @kharlov or @peressounko to approve the PR?
> It seems that their approval do nothing actually.

Technically, I can merge w/o approval, but it is better if a few detector experts crosscheck their code.

**Review by kharlov — APPROVED** [review]

**Comment by shahor02** [comment]
Hi @sevdokim @kharlov 

Before merging: so what is the source and earliest point of rejection of invalid channels? If they come only from the real FW and can be rejected on the raw data decoding level (?), what is the reason to check them again in the calibration?

**Comment by sevdokim** [comment]
Dear @shahor02, 

I just removed checks during the calibration. So the non-existent channels are checked now only during the decoding.
Checks for writing to calibration objects are present  because this operation is performed rarely and why not?

**Comment by shahor02** [comment]
@sevdokim ok, merging, though I don't see the point of checking something with should not happen.

**Comment by sevdokim** [comment]
@shahor02 All right! I'll reconsider this behaviour when will work on calibration procedure. For now I'm not sure if those checks are implemented to the CalibDevices.

Thank you for guiding!

**Pull request merged**
