### PR TITLE
 [MCH] [MRRTF-114] Add MCHDigitIO debug library.

### PR DESCRIPTION
**Pull request by aphecetche**
This PR introduces a new (private) library `MCHDigitIO` which gather code to read and write digit files in binary form (but not in CTF form), for debug purposes **only** (e.g. using digits extracted from Run2 data). 

That new library is in turn used by a few workflow pieces that can be piped to feed digits to DPL workflow and/or output digits to disk from DPL workflow : 

- `o2-mch-digits-file-reader-workflow` to read digits from a binary file 
- `o2-mch-digits-writer-workflow` to dump digits to a binary file 
- `o2-mch-digits-r23-workflow` to convert digit ids from Run2 to Run3.

Both the reader and the writer share a number of options to select a range of timeframes to be processed : `--max-nof-tfs` and `--first-tf`; and whether or not to dump things on screen during processing (`--print-digits` and `--print-tfs`options)

In addition a small program `o2-mch-digits-file-dumper`(not a DPL workflow) can be used to quickly inspect a digits binary file. 

Note that the existing digit-related workflows (the digit sink and sampler in Detectors/MUON/MCH/Workflow) are not deleted by this PR, but will be in another one, once we confirm those new workflows fit all our needs.

Some documentation is available in [Detectors/MUON/MCH/DevIO/Digits/README.md](https://github.com/AliceO2Group/AliceO2/blob/5323a738a6b9624e801b1ffea4ed4778cf6c11ab/Detectors/MUON/MCH/DevIO/Digits/README.md)

### CODE REVIEW

**Comment by shahor02** [comment]
@aphecetche is this ready to be merged?

**Comment by aphecetche** [comment]
@shahor02 I'd prefer to wait for a review from @pillot or @aferrero2707 before merging it (another pairs of eyes never hurt)

**Comment by aphecetche** [comment]
Incorporated changes requested by @pillot

**Comment by aphecetche** [comment]
@ktf @TimoWilken do you understand why `build/O2/o2` is actually failing ? Can't find what's wrong from the log.

**Comment by TimoWilken** [comment]
@aphecetche restarted, that should fix it.

**Comment by aphecetche** [comment]
@shahor02 now it is ready to be merged

**Comment by aphecetche** [comment]
@shahor02 thanks for #5898. Could you also merge this one please ?

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
