### PR TITLE
trd fix corrupt data at end of digits

### PR DESCRIPTION
**Pull request by bazinski**
add option trd-datareader-fixdigitcorruptdata
Jump over the data corruption at the end of the digit data.
This should be temporary and is default false.

### CODE REVIEW

**Comment by shahor02** [comment]
@bazinski what kind of corruption you refer to?
In any case, the license header should be fixed, fullCI fails on it.

**Comment by bazinski** [comment]
Hi @shahor02 corrupted data is coming out of the CRUs cause to be identified, but seems to be something wrong with the code on the CRU. After the end of link marker there is still a large amount of data 70-100 256 bits. No longer causes problems.

Shot for pointing out the copyright error.

**Review by tdietel — DISMISSED** [review]

**Comment by bazinski** [comment]
rebased to kick ci

**Review by tdietel — DISMISSED** [review]
Looks ok. Let's get it merged.

**Comment by davidrohr** [comment]
@bazinski : Can you rebase  and solve the conflict?

**Comment by bazinski** [comment]
@davidrohr thanks for pointing out the clash. merged and hopefully get through ci.

**Pull request merged**
