### PR TITLE
Fix path to volume

### PR DESCRIPTION
**Pull request by dstocco**
This solves: https://alice.its.cern.ch/jira/browse/O2-1317

### CODE REVIEW

**Comment by sawenzel** [comment]
@ktf @MichaelLettrich : It looks like that many PRs on linux fail because of "internal compiler error 
/ memory problems"

**Comment by MichaelLettrich** [comment]
@ktf Could that be zombies?

**Comment by MichaelLettrich** [comment]
I checked. The machine has 16 cores and 28GB of RAM  of which 4 are used. It does not look like zombies or anything alike are present on the machine. Any other idea? Circular dependencies in the build system for example?

**Comment by sawenzel** [comment]
Going ahead by majority CI vote. Small change and it unblocks other stuff.

**Pull request merged**
