### PR TITLE
CPV pedestal calibration based on TimeSlotCalibration

### PR DESCRIPTION
**Pull request by sevdokim**
Hello! Workflow based on TimeSlotCalibration for CPV pedestal calibration is created.

### CODE REVIEW

**Review by kharlov — DISMISSED** [review]

**Review by kharlov — DISMISSED** [review]

**Comment by sevdokim** [comment]
Hello @davidrohr @shahor02 all,

today I was fighting with o2codechecker and finally found a way of running it locally. 
Why not to add several strings to https://github.com/AliceO2Group/CodingGuidelines#readme explaining how to run it? I think it could save some time for people like me and also CPU resources of testing facilities. Running the codechecker is pretty simple (it was enough to run `aliBuild build o2checkcode --defaults o2` in my case), but it really helps to speed up passing the checks. Sorry if I write something obvious. 

Cheers,
Sergey

**Comment by davidrohr** [comment]
Hi, thx for the feedback. Feel free to add some documentation..my problem is that e.g. on my laptop it doesn't work due to different place of system headers. What i personally do is to run the command you wrote in the docker container. Thus, you see, it is not so simple :(

**Review by kharlov — APPROVED** [review]

**Comment by sevdokim** [comment]
Hi @shahor02 
I'm a bit worry that build/O2/fullCI check has fell into "Expected - Waiting for status to be reported" for a while. Could it be that it is stuck somewhere? Other checks are passed successfully and I'm wandering which status is expected to be reported?
Thanks, cheers,
Sergey

**Comment by shahor02** [comment]
Hi @sevdokim 
Giulio has checked and did not see any anomaly, one should wait a little bit more. Different checks are independent of each other.

**Comment by sevdokim** [comment]
> Hi @sevdokim
> Giulio has checked and did not see any anomaly, one should wait a little bit more. Different checks are independent of each other.

Hi @shahor02 
Thanks for the info. Now I keep patience.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
