### PR TITLE
Str: Silence predicted chi2 calculation

### PR DESCRIPTION
**Pull request by f3sch**
Around 60-70% of the async logs are polluted by the strangeness trackers update step with negative values which is of little help.
Also the abs of the chi2 is taken afterward so the logged message is by definition ignored thus silencing it just follows this logic.

### CODE REVIEW

**Comment by f3sch** [comment]
@fmazzasc would this be fine for you?

**Comment by fmazzasc** [comment]
Yes, it makes sense to me. Thank you!

**Comment by f3sch** [comment]
@shahor02 is it also fine for you, if so please merge?

**Comment by shahor02** [comment]
I cannot say that I like to accept negative chi2's quietly, but let's have it merged now. Eventually, if we don't manage to avoid bad cov.matrices, we should either redefine the cov.matrix to have chi2 positive, we should at kill the cluster.

**Pull request merged**
