### PR TITLE
[FIT] Separate Trigger class and make it common for FT0, FV0 and FDD.…

### PR DESCRIPTION
**Pull request by mslupeck**
… Fix Trigger class initial values.

### CODE REVIEW

**Review by AllaMaevskaya — COMMENTED** [review]
I like your changes. The only thing I don't agree is  
 static const int16_t DEFAULT_TIME = -127; // for average/8 of one side (A or C)
1. average time should not be divided by 8, only sum amplitude does;
2. -127 is too sharp threshold, if we want vertex cut +-50cm we will be out of this. Time channels are from -2048 to +2048, so let set number out of this

**Comment by mslupeck** [comment]
> I like your changes. The only thing I don't agree is static const int16_t DEFAULT_TIME = -127; // for average/8 of one side (A or C)
> 
> 1. average time should not be divided by 8, only sum amplitude does;

Good catch - I modified the comment. Thanks!

> 2. -127 is too sharp threshold, if we want vertex cut +-50cm we will be out of this. Time channels are from -2048 to +2048, so let set number out of this

Actually, I reverted it back to the previous value (-5000)

**Review by AllaMaevskaya — DISMISSED** [review]

**Review by AllaMaevskaya — DISMISSED** [review]

**Comment by mslupeck** [comment]
Hi @shahor02 
Could you merge it?

**Review by shahor02 — APPROVED** [review]
@mslupeck before I merge this: given the changes in the format and CTFCoder, did you check that the old, e.g. pilot beam data are readable with this PR?

**Comment by mslupeck** [comment]
@shahor02 - thanks for the hint. Now I've tested it using:
`o2-ctf-reader-workflow --ctf-input o2_ctf_run00505582_orbit0316488698_tf0000167535.root --onlyDet FV0 | o2-fv0-digits-writer-workflow --disable-mc -b`
`o2-ctf-reader-workflow --ctf-input o2_ctf_run00505582_orbit0316488698_tf0000167535.root --onlyDet FT0 | o2-ft0-digits-writer-workflow --disable-mc -b`
They were executed without errors and the output digit files are the same as in dev branch (except the sum of amplitude default value, which was modified from -5000 to 0 in this PR). I think it can be merged.

**Pull request merged**
