### PR TITLE
Fix flagging in GRP file for CRO

### PR DESCRIPTION
**Pull request by mconcas**
- Current macro for digitization does not set the proper flag for continuous readout mode in ITS in the `o2sim_grp.root` file.
- Adapted the function to be more friendly when working with files generated with `o2sim`.
- The changes are freely picked up from the `run_digi_all.C` macro in the same directory, adapted to work with ITS only.
- Notice that this can be taken as a proposal, but my idea is that eventually we would have something that works properly with continuous readout.

### CODE REVIEW

**Comment by shahor02** [comment]
@mconcas: thanks for the upgrade of this macro. Just one point: it was used by the ````Detectors/ITSMFT/ITS/macros/test/run_test.sh````, working with the file-names format incompatible with o2sim output (and w/o producing the grp). When updating the run_track_its.C, I left the old signature for backward compatibility, which falls back to new one. Could you do the same here, just add a method: 
````
void run_digi_its(Int_t nEvents = 10, TString mcEngine = "TGeant3", Bool_t alp=kTRUE, Float_t rate=50.e3)
{
  // Input and output file name
  std::stringstream inputfile, outputfile, paramfile;
  inputfile << "AliceO2_" << mcEngine << ".mc_" << nEvents << "_event.root";
  paramfile << "AliceO2_" << mcEngine << ".params_" << nEvents << ".root";
  outputfile << "AliceO2_" << mcEngine << ".digi_" << nEvents << "_event.root";
  run_digi_its(rate, outputfile, inputfile,paramfile, "",alp);
}
````
Called with old signature, it will log an error due to missing grp, but otherwise will work.

Cheers,
 Ruben

**Comment by mconcas** [comment]
Hi @shahor02,
thanks for the review. I added the function overload. 
Since now the function should be backward compatible, I also reverted the `macro/run_digi_its.sh` to old fashion.

Cheers,
Matteo

**Comment by shahor02** [comment]
Thanks!

**Comment by matthiasrichter** [comment]
all comments have been addressed, merging

**Pull request merged**
