### PR TITLE
Optimization of FT0 digitization

### PR DESCRIPTION
**Pull request by hcab14**
This commit improves the FT0 digitization run time by a factor of about 3.7
https://alice.its.cern.ch/jira/browse/O2-1402

Please don't merge yet. I'd like to do some more cosmetic changes.

@AllaMaevskaya: I have checked that it reproduces the INFO log messages for 500 pythia events from before. Please check on your side if it reproduces previous behaviour.

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
Thank you very much. 
For p-p output histograms look very similar. I will try with Pb-Pb and will show results, OK?

**Comment by AllaMaevskaya** [comment]
Just 2 remarks

The cache seems to be empty in the CFD dead time which might break `val_prev` computation.

The logic is: when `5 * val_prev - val` changes sign from negative to positive and val is above threshold, CFD fires. After CFD fires, it doesn't fire for the next mCFDDeadTime. We only record the first firing (`particle`), but output the last firing (`deadTime`) to account for it in the next BC.

**Comment by AllaMaevskaya** [comment]
I compared results with dev and this branch. Histograms look rather similar.

**Comment by hcab14** [comment]
> The cache seems to be empty in the CFD dead time which might break `val_prev` computation.
> 

when there is no value in the cache (-1.0f) or the computed index is outside the allowed range `val_prev` is computed by calling `value_at(...)`:
```
    float val_prev = 0.0;
    int const index_prev = std::lround((time - mParameters.mCFDShiftPos + 0.5 * mParameters.bunchWidth) / DP::SIGNAL_CACHE_DT);
    val_prev = ((index_prev < 0 || index_prev >= mSignalCache.size() || mSignalCache[index_prev] < 0.0f)
                  ? value_at(time - mParameters.mCFDShiftPos) //  was not computed before                                                                                                                          
                  : mSignalCache[index_prev]);                //  is available in the cache        

```
so it should be there in any case.

> The logic is: when `5 * val_prev - val` changes sign from negative to positive and val is above threshold, CFD fires. 

I have the impression that the CFD is quite sensitive to the signal shape function, _i.e_, I had to use linear interpolation instread of a simple table lookup to have the same INFO messages as before. Is there in hardware some kind of hysteresis for detecting the sign change? If yes this would help numerical stability in simulation.

> After CFD fires, it doesn't fire for the next mCFDDeadTime. We only record the first firing (`particle`), but output the last firing (`deadTime`) to account for it in the next BC.

Thanks. Now the logic is clear to me.

> I compared results with dev and this branch. Histograms look rather similar.

How similar are they? Ideally they should be identical, but there is loss of precision due to
* lookup-tables for the sinc and for the signal shape function
* using float instead of double arithmetic

In the latest commit I have increased the number of bins for the signal shape function.

**Comment by AllaMaevskaya** [comment]
Test with yesterday commit : amplitudes are identical; time little bit different. I attached plot with trigger average time at A and C sides  
image
image
red line - dev
blue - optimized code

**Comment by hcab14** [comment]
> Test with yesterday commit : amplitudes are identical; time little bit different. I attached plot with trigger average time at A and C sides

Is this difference significant?
Which simulation have you run, pp or PbPb?

With the latest commit, I have exactly one difference in `timeC` in 500 pythia pp events.

**Comment by AllaMaevskaya** [comment]
Difference is not significant, may be time is more correct :) It were 100 Pb-Pb pythia8hi events.

Some remarks:

- -1.0f is an allowed value of `val`. NaN and Inf are better placeholders for uninitialized cache elements

- Linear interpolation is also a great way to improve precision so I think we better keep it. We can also increase time step or even make it dynamic based on the current value. Or we can implement more complex algorithm like Newton's method to increase both speed and precision. We just need to find a way to guarantee that no zero crossings are lost. It can be done but might require some theoretical (mathematical) investigation.

My suggestion is to merge as it is now - improvement is great and results are correct. I will take care about next development and corrections.

**Comment by sawenzel** [comment]
Thanks. Great progress. Merging.

**Pull request merged**
