### PR TITLE
DPL: report data relaying process metrics (QC-139)

### PR DESCRIPTION
**Pull request by ktf**
This reports the following metrics via the monitoring interface:

* dpl/relayed_messages: messages which might end up for processing
* dpl/dropped_computations: timeslices dropped because one of the inputs
  did not arrive in time.
* dpl/dropped_incoming_inputs: inputs dropped because they arrived
  too late and their computation was dropped.
* dpl/malformed_messages: messages which were not suitable for DPL
  processing.

### CODE REVIEW

**Comment by ktf** [comment]
clang-format issue was actually fixed by https://reviews.llvm.org/D37132. Can we get a more recent version of clang-format in the CI, please?

**Comment by sawenzel** [comment]
What issue? I guess this is just a matter of updating the travis file, no?

**Comment by ktf** [comment]
Nope, I think it requires us building a `clang-format` based on a more recent version of clang which includes the fix for structured bindings.

**Comment by sawenzel** [comment]
Then we could run it similar to o2checkcode. In principle, we have our own build.

**Pull request merged**
