### PR TITLE
DPL: enable core dumps when O2_NO_CATCHALL_EXCEPTIONS is defined

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This works on macOS, provided one codesigns the executable with the correct entitlements:

```cpp
/usr/libexec/PlistBuddy -c "Add :com.apple.security.get-task-allow bool true" tmp.entitlements
codesign -s - -f --entitlements tmp.entitlements ./a.out
```

**Comment by ktf** [comment]
I am not sure we want core files to be the default when O2_NO_CATCHALL_EXCEPTIONS is set, but I guess we can simply control that with ulimit -c.

**Comment by ktf** [comment]
@TimoWilken the build/O2/fullCI test is failing with a missing o2-sim. Could you check what is going on?

**Comment by TimoWilken** [comment]
Seems like this is affecting multiple PRs.

On the machine, I can only seen the following `o2-sim*` executables, but no plain `o2-sim`:

```
$ ls sw/slc8_x86-64/O2/latest-11541-slc8_x86-64-o2/bin/o2-sim*
sw/slc8_x86-64/O2/latest-11541-slc8_x86-64-o2/bin/o2-sim-ccdbfetcher-testworkflow
sw/slc8_x86-64/O2/latest-11541-slc8_x86-64-o2/bin/o2-sim-digitizer-workflow
sw/slc8_x86-64/O2/latest-11541-slc8_x86-64-o2/bin/o2-sim-mctruth-testworkflow
```

...but #11531 (built yesterday morning at a similar time) still has a plain `o2-sim` executable.

**Comment by ktf** [comment]
@sawenzel could it be due to the new GDML support?

**Comment by ktf** [comment]
@martenole @Sean any idea for the TRD failed assertion?

Ciao,
Giulio

**Comment by martenole** [comment]
> @martenole @sean any idea for the TRD failed assertion? Ciao, Giulio

Ciao, only seeing it now. Which failed assertion? I don't see it in the log you quoted (which was successful)

**Comment by ktf** [comment]
```
## sw/BUILD/O2-latest/log
--
        Start 269: Detectors/TRD/calibration/macros/makeTRDCCDBEntryForDCS.C
264/487 Test #267: Detectors/TRD/base/test/testCoordinateTransforms.cxx .................................Subprocess aborted***Exception:   0.37 sec
Running 1 test case...
[ERROR] Geometry is not loaded yet
Assertion failed: (!(pad < 0.0 || pad > double(mNcols))), function getPad, file PadPlane.cxx, line 179.

        Start 270: Detectors/TRD/calibration/macros/readTRDDCSentries.C
```

in https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/11541/da71cf43a342ccaff90802bca0c1ea39e688e736/build_AliceO2_O2_o2_macOS-arm/pretty.html

**Pull request merged**
