### PR TITLE
Discard afterburner tracks

### PR DESCRIPTION
**Pull request by shahor02**
https://its.cern.ch/jira/browse/QC-1114

### CODE REVIEW

**Comment by f3sch** [comment]
Hi @shahor02, intuitively I would have thought this should be added here
```
 for (int itrk = 0; itrk < static_cast<int>(mITSTPCTracks.size()); ++itrk) {       // line 461
      auto const& trk = mITSTPCTracks[itrk];
      auto idxTrkTpc = trk.getRefTPC().getIndex();
      if (trk.getRefITS().getSource() != GID::ITS) {
             continue;
        }
      if (isTPCTrackSelectedEntry[idxTrkTpc] == true) {
        auto lbl = mRecoCont.getTrackMCLabel({(unsigned int)(itrk), GID::Source::ITSTPC});
        if (!lbl.isValid()) {
          continue;
        }
```
so before we build this mMapLabels, because otherwise I could imagine that this would somewhat mess with the normalisation. In this case we would exclude AB tracks entirely from the efficiency (might also not be ideal). I tested that they stop the crash.

**Comment by shahor02** [comment]
@f3sch  Makes sense, thanks!

**Comment by chiarazampolli** [comment]
I added the labels for pp 2023 apass3/PbPb apass3 only.

**Comment by chiarazampolli** [comment]
Tested by @f3sch .

**Review by chiarazampolli — APPROVED** [review]

**Pull request merged**
