### PR TITLE
Splitting IO and wait time in metrics

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@ktf The clang check failed and your usual nice PR which fixes clang does not work anymore :-(

**Comment by ktf** [comment]
? I see it green? @TimoWilken did anything change?

**Comment by jgrosseo** [comment]
@ktf Yes, I then fixed clang myself

**Comment by TimoWilken** [comment]
The error in the clang-format checker happens because it tries to push the cleanup branch to [alibuild's fork](https://github.com/alibuild/AliceO2), which is "1396 commits behind" this repo. Some of those commits change workflows, but alibuild can't push those commits to its own repo without the workflow permission.

@ktf I suggest the clang-format checker gets the workflow permission, so it can make PRs again.

**Comment by jgrosseo** [comment]
@ktf btw. are you fine with the changes itself?

**Pull request merged**
