### PR TITLE
TPC: releasing memory of aggregated currents

### PR DESCRIPTION
**Pull request by matthias-kleiner**
- always return true for have enough data to write out currents also if some TFs are missing

### CODE REVIEW

**Review by wiechula — DISMISSED** [review]

**Comment by wiechula** [comment]
Can this be merged?

**Comment by matthias-kleiner** [comment]
> Can this be merged?

I am just testing it again and I think the `vector<float>.erase()` makes it very slow. I just noticed it. I will have to modify it I guess. So please dont merge it yet

**Comment by matthias-kleiner** [comment]
> > Can this be merged?
> 
> I am just testing it again and I think the `vector<float>.erase()` makes it very slow. I just noticed it. I will have to modify it I guess. So please dont merge it yet

I had to change it a bit to make it release the memory of the `vector<float>`. When the checks have passed it can be merged from my side.

**Comment by matthias-kleiner** [comment]
Can this then be merged?

**Pull request merged**
