### PR TITLE
#13173 - fixing DCA for combined tracking + adding nshared clusters

### PR DESCRIPTION
**Pull request by miranov25**
Relates to:
https://github.com/AliceO2Group/AliceO2/pull/12928

Should fix  -not yet fully
https://github.com/AliceO2Group/AliceO2/issues/13173

### CODE REVIEW

**Comment by miranov25** [comment]
* getting shared clusters - more complicated than in the Run1, Run2, not clear if possible without device input  modification
> Laura Serksnyte
> [11:33 AM](https://mattermost.web.cern.ch/alitpccomact/pl/aq5otfi9gbdofedr5nh8nxq9we)
> 
> hi Marian, I am not sure how you make your skimmed data; I wrote the code for shared cluster QC in the the framework; i can send you the tasks
> 
> Jens helped me with this task so I am not sure there is some better way to do it

https://github.com/AliceO2Group/AliceO2/blob/5b5abc2382d6cf7e86689512e0ac48dc42d1ee25/Detectors/TPC/qc/src/TrackClusters.cxx#L61

**Comment by miranov25** [comment]
In the figure below, the DCA for combined tracks after the bug fix is displayed. Previously, modulation was observed and the DCA had to be adjusted for vertex_x and vertex_y using the formula:

```
tree->SetAlias("dcar_itstpc0","dcar_itstpc+sin(phi)*vertex_x+cos(phi)*vertex_y");
```



image

In earlier performance parameterizations for DCA resolution and bias, I corrected for mismatches by applying a vertex_x and vertex_y correction as a first-order approximation. However, it is preferable to compute the DCA properly, as second-order effects were influencing precision.

**Comment by davidrohr** [comment]
@miranov25 : please run clang format, so that we can merge it

**Comment by miranov25** [comment]
I did not make modification in O2 for some time, I forgot how I made that clang-format  check. Last time somebody provided me the command, but I did. not have it in my history anymore. 
Which style do we use?

Or do we use the default one?

**Comment by davidrohr** [comment]
The style file comes with O2
You can use the git-clang-format command, to format only your changes correctly.
Also, in the PR checker list above, you can check the `Formatting / PR formatting / clang-format` check to see what is wrong.

**Comment by miranov25** [comment]
+async-label async-2022-pp-apass4, async-2023-pbpb-apass3, async-2023-pbpb-apass4, async-2022-pp-apass6 2023-PbPb-apass2, async-2023-pp-apass4, async-2024-pp-apass1, async-2022-pp-apass7, async-2024-pp-cpass0

**Comment by benedikt-voelkel** [comment]
Thanks for labelling @miranov25 .
I already took care of adding the missing label. Maybe there was a typo. Anyway, it's there now.

**Comment by chiarazampolli** [comment]
Cherry-picking to async-2022-pp-apass4 does not work. Since apass4 is deprecated, I remove the label.

**Comment by chiarazampolli** [comment]
Same for apass6 pp 2022 and PbPb 2023 apass2.

**Pull request merged**
