### PR TITLE
Dropping old / obsolete / unmaintained code

### PR DESCRIPTION
**Pull request by ktf**
Taking ownership in WP4 for the test_O2Device.cxx test
and renaming in to test_FairMQ.

### CODE REVIEW

**Comment by ktf** [comment]
@matthiasrichter @mkrzewic as discussed.

**Comment by ktf** [comment]
@TimoWilken @MichaelLettrich what happened to aido2osx3.cern.ch?

**Comment by TimoWilken** [comment]
Strange error:
```
2021-05-20@07:43:33:DEBUG:O2:O2:6208: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DBOOST_UNIT_TEST_FRAMEWORK_DYN_LINK -DDPL_ENABLE_BACKTRACE -DENABLE_UPGRADES -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -DMS_GSL_V3 -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Framework/Core/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Common/Utils/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/DataFormats/common/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Common/Constants/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/GPU/Common -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Framework/Logger/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/DataFormats/Headers/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/DataFormats/MemoryResources/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Common/MathUtils/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Framework/Foundation/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Framework/Foundation/3rdparty/include -I/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Utilities/PCG/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/Common-O2/v1.6.0-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/boost/v1.75.0-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/Configuration/v2.6.1-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/libInfoLogger/v2.1.0-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/Monitoring/v3.8.4-3/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/curl/7.70.0-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/FairMQ/v1.4.37-1/include/fairmq -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/FairMQ/v1.4.37-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/FairLogger/v1.9.1-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/fmt/7.1.0-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/ROOT/v6-20-08-alice1-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/FairRoot/v18.4.1-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/arrow/v1.0.0-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/ms_gsl/3.1.0-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/Vc/1.4.1-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/RapidJSON/v1.1.0-alice2-1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/libuv/v1.40.0-1/include -fPIC -O2 -std=c++17 -Werror -Wno-error=deprecated-declarations -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.0.sdk -mmacosx-version-min=10.15 -std=gnu++17 -MD -MT Framework/Core/CMakeFiles/O2test-framework-FairMQ.dir/test/test_FairMQ.cxx.o -MF Framework/Core/CMakeFiles/O2test-framework-FairMQ.dir/test/test_FairMQ.cxx.o.d -o Framework/Core/CMakeFiles/O2test-framework-FairMQ.dir/test/test_FairMQ.cxx.o -c /Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Framework/Core/test/test_FairMQ.cxx
2021-05-20@07:43:33:DEBUG:O2:O2:6208: clang: error: no such file or directory: '/Volumes/build/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/6208/0/Framework/Core/test/test_FairMQ.cxx'
2021-05-20@07:43:33:DEBUG:O2:O2:6208: clang: error: no input files
[...]
2021-05-20@07:43:44:DEBUG:O2:O2:6208: ninja: build stopped: subcommand failed.
```

**Comment by ktf** [comment]
I forgot to commit one file...

**Comment by TimoWilken** [comment]
It's interesting that the other tests worked, then!

**Pull request merged**
