### PR TITLE
Basic comparison with MC done at the outermost layer

### PR DESCRIPTION
**Pull request by iouribelikov**

### CODE REVIEW

**Comment by sawenzel** [comment]
It seems there a conflicts for this PR (due to overlapping work in other PRs). Can you please resolve them?

**Comment by iouribelikov** [comment]
@sawenzel Yes, Sandro. I am working on it...

**Comment by iouribelikov** [comment]
@sawenzel @shahor02 Done !  Please consider merging this PR.

**Comment by shahor02** [comment]
Hi @iouribelikov , thanks, for me this PR is OK. It still sticks to old macro input arguments, incompatible with o2sim, but this should be probably addressed in the separate PR, getting rid of ````macro/run_sim.C```` and its legacy.

**Pull request merged**
