### PR TITLE
Applying the DPL timeslice concept correctly for TPC digitizer workflow

### PR DESCRIPTION
**Pull request by matthiasrichter**
This is the final step to remove some workarounds from the early days of
DPL. The first implementation of the TPC digitizer workflow has been using
parallel processing of sector data by distributing the data over multiple
time slices. While the TPC reco workflow has been changed already a while
ago, this has been pending for the digitizer workflow.

Sector data belonging together are now sent within one timeslice.
This includes the following changes:
- Using lane configuration of TPC reco workflow in digitizer workflow
- Sending the context info for TPC sectors in one DPL timeslice (SimReader)
- Defining custom dispatching policy set for the SimReader to publish immediately
  allows staggered processing of parallel data sets
- setting completion policy for pipeline processors to process data as it
  comes in
- Defining TPC part of digitizer workflow by using the DPL parallel-pipeline
  helper
- Using one route per sector, the routes are distributed over the available
  processing lanes by the parallel-pipeline helper

### CODE REVIEW

**Comment by matthiasrichter** [comment]
I have tested the PR with the CA tracker QA, the plots are identical. However, I've made some interesting observations:
1. depending on the number of lanes, the produced digits seem to be slightly different, so the output of the tracking is slightly different (@wiechula)
2. running the tracking on a digit file produced with `--TPCtriggered`, gives me an error (independently of this PR) @davidrohr 
```
[31011:tpc-tracker]: [21:17:29][INFO] Event has 2806 TPC Clusters, 0 TRD Tracklets
[31011:tpc-tracker]: [21:17:29][ERROR] GPU Tracker returned Error Code 4 (GPUCA_ERROR_TRACKLET_HIT_OVERFLOW) in slice 23 (Clusters 392)
[31011:tpc-tracker]: [21:17:29][INFO] found 0 track(s)
[31011:tpc-tracker]: [21:17:29][INFO] sending 0 track label(s)
[31011:tpc-tracker]: o2-tpc-reco-workflow: malloc.c:4023: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
```

**Comment by sawenzel** [comment]
I think point 1. is likely due to the usage of random number sequences within each lane.

**Comment by davidrohr** [comment]
The fix for 2. should be in https://github.com/AliceO2Group/AliceO2/pull/3342

**Comment by matthiasrichter** [comment]
GPU CI is failing in Python-modules, unrelated.

**Pull request merged**
