### PR TITLE
TPC: Adding streamer for FastTransform in reconstruction

### PR DESCRIPTION
**Pull request by matthias-kleiner**
SpaceCharge: adding option to use analytical formula for corrections and distortions
 - adding simple default analytical distortions/corrections
 - add streamer in digitizer

DebugStreamer: Allow  writing out streams in parallel

### CODE REVIEW

**Comment by davidrohr** [comment]
What is sizeof(o2::utils::DebugStreamer)?
Is it guaranteed to be the same on CPU and GPU?
Otherwise it will break GPU reconstruction.

**Comment by matthias-kleiner** [comment]
> What is sizeof(o2::utils::DebugStreamer)? Is it guaranteed to be the same on CPU and GPU? Otherwise it will break GPU reconstruction.

The class is only defined when DEBUG_STREAMER was set during compiling o2. If it was not specified then the class should be always empty and the same size for CPU and GPU.
If o2 was compiled with DEBUG_STREAMER and one runs on GPU, then I guess it would be of different size, but I will check what happens.

**Comment by davidrohr** [comment]
Ok, thx. Then it should be fine.

However, I propose we add a check at the initialization of the GPUReconstruction class when the DEBUG STREAMER define is set, and if so we throw a fatal if the backend is not CPU, to avoid confusing crashes if accidentally they are used together.

**Review by wiechula — CHANGES_REQUESTED** [review]
@matthias-kleiner , thanks for the implementation!
Concerning the streamers, could you please also add then here:
https://github.com/AliceO2Group/AliceO2/blob/dev/GPU/TPCFastTransformation/TPCFastTransform.h#L657
https://github.com/AliceO2Group/AliceO2/blob/dev/GPU/TPCFastTransformation/TPCFastTransform.h#L668
These functions are also called in reconstruction. @davidrohr  are there others needed?

**Comment by matthias-kleiner** [comment]
> Ok, thx. Then it should be fine. However, I propose we add a check at the initialization of the GPUReconstruction class when the DEBUG STREAMER define is set, and if so we throw a fatal if the backend is not CPU, to avoid confusing crashes if accidentally they are used together.

This would be good. Can you implement this?

**Review by shahor02 — COMMENTED** [review]
@matthias-kleiner did you check if the streaming to trees (even different ones) works in multithreaded code? The root I/O is in general not thread safe, see e.g. https://root-forum.cern.ch/t/root-i-o-and-thread-safety/5857

**Comment by davidrohr** [comment]
Sure, will take care

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner did you check if the streaming to trees (even different ones) works in multithreaded code? The root I/O is in general not thread safe, see e.g. https://root-forum.cern.ch/t/root-i-o-and-thread-safety/5857

Yes I checked this and it is working fine for me. If each thread gets its unique TFile then it is working without problems.

**Comment by matthias-kleiner** [comment]
**Just some information on how to use it, in case someone wants to use it**
1. Create the space-charge object which can be used in the digitizer and the fast transform which can be used in the reconstruction (default analytical formulas are used, in case of custom formulas they should be set in the `createTPCSpaceChargeCorrectionAnalytical()` function)
```
.L O2/Detectors/TPC/reconstruction/macro/createTPCSpaceChargeCorrection.C+
createTPCSpaceChargeCorrectionAnalytical("tpctransform_ana.root");
```

Output of debug spline object:
```
r fastTransformUnitTest_debug1_gridsize180-129-129.root
fastTransform -> Draw("((lx*50-254.5)/49-lx) : lx","","colz");
```
[corrections local X](https://user-images.githubusercontent.com/48915672/217817735-9c560bdb-3919-43b9-bb85-357f7143e13e.png)
[corrections local Y](https://user-images.githubusercontent.com/48915672/217817955-b28d5b21-31aa-4ea2-91d8-76ad4a2d0bcf.png)
[corrections local Z](https://user-images.githubusercontent.com/48915672/217818022-c3bc34f6-29fc-4d24-9124-fd4d6d45031f.png)
[formula - corrections local X](https://user-images.githubusercontent.com/48915672/217818385-adcb0489-d071-48ef-806e-0e9832d43e08.png)

2. Running the digitizer with the analytical distortions and create debug output
```
o2-sim-digitizer-workflow --onlyDet TPC --distortionType 2 --readSpaceCharge "distortions_analytical.root" --configKeyValues "DebugStreamerParam.StreamLevel=32;" --tpc-lanes 4 -b
```
3. Running the reconstruction
```
mkdir -p TPC/Calib/CorrectionMap
cp tpctransform_ana.root TPC/Calib/CorrectionMap/snapshot.root
o2-tpc-reco-workflow --output-type "tracks" --infile "tpcdigits.root" --condition-remap "file:///data/mkleiner/tmp/anasc/sim/=TPC/Calib/CorrectionMap" --configKeyValues "DebugStreamerParam.StreamLevel=8;" -b
```

4. In case debug output was created merge the TTrees
```
hadd debug_fasttransform.root  debug_fasttransform*
root.exe
o2::utils::DebugStreamer::mergeTrees("debug_fasttransform.root", "debug_fasttransform_merged.root");
```
5. Comparing output corrections with expectation:
```
root.exe debug_fasttransform_merged.root
```
[corrections local X - formula:`tree_0 -> Draw("dx - ((lx*50-254.5)/49-lx)  : lx","","");`](https://user-images.githubusercontent.com/48915672/217819650-ab697b57-d71c-4b17-acb5-c8082f2e2fb9.png)
[corrections local Y - formula: `tree_0 -> Draw("(lyT -ly) - (-(2 + 0.01 * (lx + (lx * 50 - 254.5) / 49 - lx)))  : lx","","*")`](https://user-images.githubusercontent.com/48915672/217819787-ed005883-f832-42a3-9dbd-f669ccb998a0.png)
[corrections local Z - formula: `tree_0 -> Draw("(lzT - lz) - (lz * 50 / 51 - lz)  : lz","","*")`](https://user-images.githubusercontent.com/48915672/217819948-f1d16f46-cfb3-4661-aa89-b728c4d70873.png)

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner , thanks for the implementation! Concerning the streamers, could you please also add then here: https://github.com/AliceO2Group/AliceO2/blob/dev/GPU/TPCFastTransformation/TPCFastTransform.h#L657 https://github.com/AliceO2Group/AliceO2/blob/dev/GPU/TPCFastTransformation/TPCFastTransform.h#L668 These functions are also called in reconstruction. @davidrohr are there others needed?

Thanks, I just added them

**Comment by wiechula** [comment]
> > @matthias-kleiner , thanks for the implementation! Concerning the streamers, could you please also add then here: https://github.com/AliceO2Group/AliceO2/blob/dev/GPU/TPCFastTransformation/TPCFastTransform.h#L657 https://github.com/AliceO2Group/AliceO2/blob/dev/GPU/TPCFastTransformation/TPCFastTransform.h#L668 These functions are also called in reconstruction. @davidrohr are there others needed?
> 
> Thanks, I just added them

My idea was to add streamers directly in the functions above, as in the `Transform` to see the values which are called.

**Comment by matthias-kleiner** [comment]
> > > @matthias-kleiner , thanks for the implementation! Concerning the streamers, could you please also add then here: https://github.com/AliceO2Group/AliceO2/blob/dev/GPU/TPCFastTransformation/TPCFastTransform.h#L657 https://github.com/AliceO2Group/AliceO2/blob/dev/GPU/TPCFastTransformation/TPCFastTransform.h#L668 These functions are also called in reconstruction. @davidrohr are there others needed?
> > 
> > 
> > Thanks, I just added them
> 
> My idea was to add streamers directly in the functions above, as in the `Transform` to see the values which are called.

Now I understand, I added this

**Pull request merged**
