### PR TITLE
Write pixels in topology from left to right

### PR DESCRIPTION
**Pull request by lbariogl**

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@lbariogl, the failing tasks in the CI are not related to your PR, they are known issues.

**Comment by lbariogl** [comment]
Thank you @matthiasrichter, you are right. I made the changes you suggested

**Comment by matthiasrichter** [comment]
Thanks, @lbariogl 

@sawenzel , I think this PR can be merged, the remaining failed test concerns the unit test issue and is unrelated.

**Comment by sawenzel** [comment]
@iouribelikov, @shahor02 : Can one of you still approve this?

**Comment by shahor02** [comment]
Hi, yes, it is ok

On Oct 24, 2017 09:53, sawenzel <notifications@github.com> wrote:

@iouribelikov<https://github.com/iouribelikov>, @shahor02<https://github.com/shahor02> : Can one of you still approve this?

**Pull request merged**
