### PR TITLE
TPC cdb interface

### PR DESCRIPTION
**Pull request by wiechula**

### CODE REVIEW

**Comment by ktf** [comment]
Great work on the unit testing. Would it be possible to invoke `CDBInterface::createDefaultNoise()` and `CDBInterface::createDefaultPedestals()` somewhere in a unit test to make sure they are at least invoked and that they do not crash?

**Comment by wiechula** [comment]
Sure, I'll extend the test.
Just a short question about the codecov, it seems to run quite often. At least I get a huge number of mails, even if I did not commit any changes. I have to admit that this flood of mails is a bit annoying and might result in just filtering them out at some point.
Or do we need these mails at all? I guess a summary of the checks might suffice, one can go to the github page and check anyhow.

**Comment by wiechula** [comment]
One more question.
Codecov reports 

> 1 file has unexpected coverage changes not visible in diff.
I guess this refers to `Detectors/EMCAL/simulation/src/Detector.cxx`.
However my commit didn't touch this file, neither others like `MessageFormat.cxx` or `ConditionId.cxx`. I'm not sure what to do about this.

**Comment by ktf** [comment]
I am looking in what is going on with the codecov reports, but I was away the whole afternoon.

**Comment by ktf** [comment]
(sorry for the noise)

**Comment by wiechula** [comment]
Thanks for looking into it. No reason to be sorry. The tool is really good I think.

**Comment by sawenzel** [comment]
@ktf, @dberzano : It seems that something broke some ROOT macros (as seen by this PR). While I am not 100% sure, I believe that this is not due to any change in O2 itself but due to the recent ROOT version change.
What about actually putting changes in alidist under PR checks to avoid bugs introduced like this?

**Comment by matthiasrichter** [comment]
@wiechula, probably that should be merged at some point. Can you rebase and resolve the merge conflict and remove the WIP mark if no additional work is needed.

**Comment by wiechula** [comment]
@matthiasrichter, I agree, this should be merged soon. Our discussions stalled a bit unfortunately. I will bring this forward again this week. Rebased is done and pushed.

**Comment by sawenzel** [comment]
@wiechula: If you think this is ready from your side, please remove the WIP label from the title.

**Comment by wiechula** [comment]
Ok, I think we can go ahead and merge it.

**Pull request merged**
