### PR TITLE
ITS-SeedingVertexer: Use dynamic TimeFrame splitting for GPU vertexer

### PR DESCRIPTION
**Pull request by mconcas**

### CODE REVIEW

**Comment by mconcas** [comment]
@davidrohr : this should be merged after https://github.com/AliceO2Group/AliceO2/pull/10809 (which is ready, just with a random error in CI).
I would like to this after rebasing on that. Just to be sure.

**Comment by mconcas** [comment]
@shahor02 @davidrohr: hi, this can be merged.

**Comment by shahor02** [comment]
Is it ok to squash it?

**Comment by mconcas** [comment]
> Is it ok to squash it?

sure

**Pull request merged**
