### PR TITLE
[WIP] Framework demonstrator

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
This is WIP, do not merge.

**Comment by ktf** [comment]
@dberzano any idea why the tests for this are not running?

**Comment by dberzano** [comment]
@ktf I am checking the tests.

**Comment by ktf** [comment]
@dberzano @brinick looks like the logs of all the tests are stored using the same id, an hash. Was this always the case?

@sawenzel @ZdravkoD I could not find the namespace violation in my code, could you have a look?

**Comment by sawenzel** [comment]
@ktf: No, it appears that a unit test inside o2codechecker is failing. We should not actually be checking the namespaces yet. Not sure why it is failing. On my tested platforms (mac + ubuntu) everything is fine. Do you manage to extract the test log from the build machine?

**Comment by brinick** [comment]
Yes. The individual logs are cat'ed into the fullLog.txt file,
and the only information - check_name - that can distinguish between these
checks is not part of the path to the log file. So they are all
merrily overwriting each other

**Comment by ktf** [comment]
Can we disable the Copyright check for the `DebugGUI` folder? It contains imported code from a third party project.

**Comment by ktf** [comment]
Obligatory screenshot with the Debug GUI.

framework debug gui

**Comment by matthiasrichter** [comment]
To compile the GUI on Linux I had to install `libglfw3-dev` which requires and automatically installed the following packages:
```
libxcursor-dev
libxi-dev
libxinerama-dev
libxrandr-dev
```

**Comment by matthiasrichter** [comment]
To compile the GUI on Linux I had to install `libglfw3-dev` which requires and automatically installs the following packages:
```
libxcursor-dev
libxi-dev
libxinerama-dev
libxrandr-dev
```

**Pull request closed without merging**
