### PR TITLE
DPL GUI: improve legend

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr Obligatory screenshot:

image

**Comment by davidrohr** [comment]
@ktf : Thx for the improvements. But somehow, no the colors are missing in the legend for me.
Screenshot_20210401_193635

**Comment by ktf** [comment]
Can I blame the drivers? ;-) Can you try changing the alpha component or using 1.f fr it?

**Comment by davidrohr** [comment]
Well, the strange thing is that it was working before this patch :)
But I can have a look how to fix it. Apparently it works for you, so will be difficult to reproduce.

**Pull request merged**
