### PR TITLE
FT0 mc->raw->digits test added to full_system_test_ci_extra_tests

### PR DESCRIPTION
**Pull request by shahor02**
@davidrohr added Alla's test converted to simple executable to `full_system_test_ci_extra_tests`.

Shall we simply add `taskwrapper ${logfile} "$O2_ROOT/prodtests/full-system-test/full_system_test_ci_extra_tests.sh"` in the end of the  `full_system_test.sh`. I don't think we need all these metrics extraction like for the dpl-workflow.

@AllaMaevskaya I've slightly modified your loops to account for eventually multiple entries in the decoded tree. 
Would be good to add also a comparison for the content of digits, not just their numbers.

### CODE REVIEW

**Comment by davidrohr** [comment]
I think there is no need to change full_system_test.sh. the full_system_test_ci_extra_tests.sh is started on alidist-level.

But I would use the taskwrapper script inside. Or at least you need some other exit code treatments, such that if one of the commands fails, full_system_test_ci_extra_tests.sh exits with non-zero. This is automatically guaranteed if you use the taskwrapper.

**Comment by shahor02** [comment]
OK, but then should not alidist call  `JOBUTILS_PRINT_ON_ERROR=1 JOBUTILS_JOB_TIMEOUT=900 SHMSIZE=8000000000  $O2_ROOT/prodtests/full_system_test_ci_extra_tests.sh` ?

**Comment by davidrohr** [comment]
Indeed, why not. I just thought the shm was unnecessary or the tests and actually didn't thinkg about the other parameters.

**Comment by davidrohr** [comment]
@shahor02 : I have merged your alidist change for the env variables. Could you force-push an amended commit to trigger a restart of the CI?

**Comment by davidrohr** [comment]
QC testWorkflow ctest time-outing, unrelated, merging this

**Review by davidrohr — CHANGES_REQUESTED** [review]
Ah, wait:
@shahor02 : Your change to `full_system_test.sh` was rebased incorrectly, the raw converters are all present twice. Could you please fix that before merging.

**Pull request merged**
