### PR TITLE
DPL: improve forward handling

### PR DESCRIPTION
**Pull request by ktf**
* handle forwarding in FairMQDeviceProxy
* refactor forwardign itself so that it can be done via a free
  function.

Should simplify the forwarding code and allow it to be done
already at the level of DataRelayer, so that we can handle
the issue with forwarding of obsolete timeframes.

### CODE REVIEW

**Comment by ktf** [comment]
New version passes all tests on my box.

**Comment by davidrohr** [comment]
@ktf : what is actually with this PR? Do we still need it / want it?

**Comment by ktf** [comment]
It's actually included in the other PR for the fix-calib.

**Comment by davidrohr** [comment]
closing as superseded by #9395

**Pull request closed without merging**
