### PR TITLE
[EMCAL-518, EMCAL-613] Updates in EMCAL digitization

### PR DESCRIPTION
**Pull request by mfasDa**
- EMCAL-518: Proper delay handling in time response
- EMCAL-613: Load calibration objects via CalibLoader

### CODE REVIEW

**Comment by mfasDa** [comment]
Stupid CI! I am speachless

This file has be formatted with clang-format, in fact I configured my VSCode that it always formats on save. 

I don't know what to say more. Maybe people should update the CI to use recent stuff and not always tools that are outdated since decades ...

**Comment by mfasDa** [comment]
Now formatted on linux with clang-format-10, seems to work. Ridiculous

**Comment by mfasDa** [comment]
Please wait with merging until I confirm! There are still a couple of tests ongoing.

**Comment by mfasDa** [comment]
Ready for merging.

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
