### PR TITLE
Medium for HalfCone

### PR DESCRIPTION
**Pull request by frmanso**
The medium for HalfCone has been moved in Detector file.

### CODE REVIEW

**Comment by frmanso** [comment]
The Check PR says that I have to modify the star position for pointers, example: 
-  TGeoTranslation *tr1_up = new TGeoTranslation("tr1_up", -7.4, 0, 8.28);
+  TGeoTranslation* tr1_up = new TGeoTranslation("tr1_up", -7.4, 0, 8.28);
I don't understand the reasons. From a older pull request, I already changed this star position and put it just before the name pointer... Before to make the pull request, I performed a pull rebase to get the latest Clang version and I applied it to the files. Why the files are not modified automatically if the rules have changed?

**Comment by sawenzel** [comment]
@rpezzi ? Could you please approve this. @frmanso : I slight more verbose commit message with few more explanations of why this is done would be appreciated.

**Review by bovulpes — APPROVED** [review]

**Comment by bovulpes** [comment]
It is a little difficult to see what has really changed, since there are many things from clang-format modifications. Please try to avoid this. In principle it has to do with moving the material definitions there where they belong, since some of them were wrongly put in other files.

**Comment by frmanso** [comment]
Thanks for the commit Sandro. 28 days needed for this small commit with all green lights and no comments, presented in MFT meeting, it's difficult to understand this so long delay.

**Pull request merged**
