### PR TITLE
GPU: Improve gather kernel performance

### PR DESCRIPTION
**Pull request by fweig**
This PR improves the performance of the gather kernel by 
- buffering data in shared memory for more efficient dma writes
- distributing work equally among all threads

With these changes, throughput should be now at ~10 GB/s.

### CODE REVIEW

**Comment by davidrohr** [comment]
@fweig : I had a quick look. The new algorithm seems to work with large data sets, but it fails with memory errors on small data sets (e.g. try my timeframe o2-pp-10 on asustest04, which crashes reproducibly for me).

For the OpenCL problem, I assume that RemoveReference<...> might have problems with __generic and __private address spaces. Not fully sure how / if we can get this to work. Most likely it is a bug in C++ for OpenCL in clang (or basically a missing case that noone attempted yet and which is therefore not properly implemented). Or perhaps RemoveReference<..> is simply not available, but the compiler is not complaining correctly. Not sure if we want to file a bug report v.s. clang, or just fix it manually in the code.

**Comment by fweig** [comment]
@davidrohr Finally fixed the segfault. Should work on smaller datasets now as well.
Regarding OpenCL: i just rewrote it in a way that gets rid of RemoveReference.

**Comment by fweig** [comment]
Just played a bit around with this by changing the chunk size that every thread sends to the host. Reducing the thread count didn't yield any significant changes. Here are my results:
- Old Kernel: 1121 GPUs
- New Kernel, 16 byte chunks: 1165 GPUs
- New Kernel, 8 byte chunks: 1117 GPUs
- New Kernel, 4 byte chunks: 1132 GPUs

My guess is, that the new kernel should perform better on AMD. As the current version is bad at utilizing the larger warps. This could be also part of the reason why this kernel currently so slow on AMD.
If it's ok with you, i would extend the `tpcCompressionGatherMode` flag to select any of the four configurations above so we can easily test which works best for each gpu.

**Comment by davidrohr** [comment]
Hi @fweig, I agree on adding a flag to select the kernel. But could you add a new flag tpcCompressionGatherModeKernel instead, because in any case it's a gather kernel.

**Comment by davidrohr** [comment]
>     * Old Kernel: 1121 GPUs

Perhaps not so important, but I am wondering how you measured 1121 GPUs, since I am getting consistently 1140 GPUs (using my above command line, and the software version from yesterday). Did you run exactly my command line on asustest04?

**Comment by fweig** [comment]
@davidrohr Yupp, i checked out `dev` and copied your command.

Pushed an update that added the tpcCompressionGatherModeKernel flag to switch between kernels.

**Comment by davidrohr** [comment]
OK, that is weird, can you still reproduce this? Can you point me to an installation on asustest04 to reproduce? Just curious. It is only 2% performance, bu no reason to leave it lying dead.

For your PR: the selection works, but when I select kernel 0 I get a crash due to CUDA memory error. Could you have a look?

And the new kernel versions are all slower than before, even though your post above suggests the 8 byte chunk kernel should be as fast/faster. We should also understand this.

**Comment by fweig** [comment]
I think someone else was occupying the pcie bus on asustest04. I tried to reproduce the gpu count before pushing my changes but i got >2000 gpus. And the gather kernel in dev was much slower as well.
I'll retry both tomorrow.

**Comment by davidrohr** [comment]
@fweig : I found the difference. I have set Turing as explicit NVIDIA GPU target. You didn't. Apparently, it is faster without. Must be a compiler problem ... :)

**Comment by fweig** [comment]
@davidrohr Ok, nice. :) 

I found out why the gpu count went up: apparently the 16 chunk variation uses too much shared memory. This probably slows down the other compression kernels. If i remove that one the gpu count goes down again for all variations of the gather kernel. I'll split shared memory of the kernels.

Also looks like my changes are triggering a bug in rocm? From the CI:
```In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Base/hip/GPUReconstructionHIP.hip.cxx:45:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Base/hip/GPUReconstructionHIP.h:17:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Base/GPUReconstructionDeviceBase.h:17:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Base/GPUReconstructionCPU.h:17:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Base/GPUReconstruction.h:31:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Base/GPUConstantMem.h:24:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Merger/GPUTPCGMMerger.h:24:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Merger/GPUTPCGMMergerTypes.h:18:
In file included from /mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/3885/0/GPU/GPUTracking/Base/GPUGeneralKernels.h:25:
In file included from /opt/rocm/include/hipcub/hipcub.hpp:31:
In file included from /opt/rocm/include/hipcub/rocprim/device/../../config.hpp:50:
In file included from /opt/rocm/include/rocprim/rocprim.hpp:48:
In file included from /opt/rocm/include/rocprim/device/detail/../../block/block_scan.hpp:33:
/opt/rocm/include/rocprim/block/detail/block_scan_reduce_then_scan.hpp:508:13: error: 
loop not unrolled: the optimizer was unable to perform the requested transformation; 
the transformation might be disabled or specified as part of an unsupported transformation ordering [-Werror,-Wpass-failed=transform-warning]
            for(unsigned int i = idx_start + 1; i < idx_end; i++)```

**Comment by davidrohr** [comment]
Seems so with the compiler bug, but I wouldn't bother too much at this point. AMD promised to provide RPMs for the new version latest on 7th of July, then I'll replace the CI container anyway. We just need to wait a bit to merge this PR.
Did you look at the memory error with kernel 0 that I reported?

**Comment by fweig** [comment]
I couldn't reproduce it. But I applied the same fix for the memory error in the other kernels.

Just pushed another update. Gather shared memory is now separated from the other gather kernels. Gpu count is down again.

**Comment by davidrohr** [comment]
@fweig : Performance looks better than before, but didn't try all combinations yet.
However, I still see the memory error. But then, I actually see the memory error also with the old version running on differrent GPU models. I presume something is just wrong with my double-pipeling. So actually your PR might proof helpful to fix this on my side.
I'll leave this pending for now, anyhow we have to wait for the GPU CI container to be updated.
I'll double-check the performance tomorrow and then report back.

**Comment by davidrohr** [comment]
@fweig : We need to wait some more time to merge this.
We have a working HIP compiler that can compile this code, but it fails to compile the ITS code.
That needs to be fixed first in HIP, otherwise we break the CI in other places...

For this PR, could you adapt to the change in the settings files from #4012 (I added your settings already to avoid rebase conflicts on my side..., but you'll neeed to change 2 lines in GPUReconstruction and GPUChainTracking.

**Comment by fweig** [comment]
To merge this I could just add a workaround and emulate the reduction with a scan. The performance impact shouldn't matter in this case.

**Comment by davidrohr** [comment]
I don't really care, if you want go ahead.
But in principle, we need this compiler fixed anyway, also for other pending PRs.

**Pull request merged**
