### PR TITLE
[MFT] Enables MFT tracker for non-continuous detector mode

### PR DESCRIPTION
**Pull request by rpezzi**

### CODE REVIEW

**Comment by bovulpes** [comment]
Hi @rpezzi , the "continuous" variable is still needed (is not used, now) ?

**Comment by rpezzi** [comment]
> Hi @rpezzi , the "continuous" variable is still needed (is not used, now) ?

Hi Bogdan, 
it is used only to display. For non non-continuous mode the user should configure `roFrameLengthInBC` [here](https://github.com/AliceO2Group/AliceO2/blob/f8e83ae6e37be45fe62a21ed6d0627901fbc81f3/Detectors/ITSMFT/common/base/include/ITSMFTBase/DPLAlpideParam.h#L38-L39).  I think this message should remain there.

**Comment by shahor02** [comment]
Is this ready to be merged?

**Comment by rpezzi** [comment]
yes

**Pull request merged**
