### PR TITLE
Hide random ring

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@sawenzel it looks like including RandomRing.h (due to the usage of Vc/Vc) is now one of the largest offenders when it comes to compile time and memory. I suspect this is the cause of the various:

```
[2949/3277] Building CXX object Steer/DigitizerWorkflow/CMakeFiles/O2exe-sim-digitizer-workflow.dir/src/SimpleDigitizerWorkflow.cxx.o
FAILED: Steer/DigitizerWorkflow/CMakeFiles/O2exe-sim-digitizer-workflow.dir/src/SimpleDigitizerWorkflow.cxx.o 
/mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/GCC-Toolchain/v10.2.0-alice2-1/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DDPL_ENABLE_BACKTRACE -DENABLE_UPGRADES -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Framework/Core/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Common/Utils/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/common/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Common/Constants/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/Common -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Framework/Logger/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Headers/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/MemoryResources/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Common/MathUtils/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Framework/Foundation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Framework/Foundation/3rdparty/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Utilities/PCG/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Steer/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/Common/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/Utils -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Utilities/rANS/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/Base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Common/Field/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Parameters/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Common/Types/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Common/SimConfig/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/EMCAL/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/EMCAL/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/EMCAL/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/Raw/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FT0/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FT0/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/FIT/FT0/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/CCDB/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/Calibration/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Calibration/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FV0/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FV0/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/FIT/FV0/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FDD/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FDD/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/FIT/FDD/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/CTP/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/CTP/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/CTP/workflow/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Framework/Utils/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FDD/workflow/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FDD/reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FDD/raw/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/raw/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/HMPID/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/HMPID/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/HMPID/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/common/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/common/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/common/reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/ITSMFT/common/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/ITS/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/ITS/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/common/workflow/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/MFT/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/MUON/MCH/Simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/MUON/MCH/Base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/MUON/MCH/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/Passive/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/MUON/MCH/Mapping/Interface/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/MUON/MCH/Geometry/Creator/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/MUON/MCH/Geometry/Transformer/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/MFT/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/MUON/MID/Simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/MUON/MID/Base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/MUON/MID/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/MUON/MID/Clustering/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/PHOS/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/PHOS/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/PHOS/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/CPV/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/CPV/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/CPV/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/CPV/calib/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TOF/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TOF/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/TOF/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TOF/calibration/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/DCS/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TOF/reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TOF/workflow/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TPC/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TPC/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/TPC/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Algorithm/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TPC/spacecharge/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TRD/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TRD/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/TRD/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TRD/workflow/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TRD/reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TRD/calibration/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/Definitions -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/DataTypes -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/Base -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/SliceTracker -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/TPCConvert -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/dEdx -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/ITS -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/TRDTracking -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/qa -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/display -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/Global -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/HLTHeaders -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/Interface -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/Merger -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/Refit -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/Debug -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/DataCompression -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/GPUTracking/TPCClusterFinder -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/ITS/tracking/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/ITSMFT/ITS/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/TPCFastTransformation -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/TPCFastTransformation/devtools -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/GlobalTrackingWorkflow/readers/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/GlobalTracking/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ITSMFT/ITS/reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FT0/reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/FT0/calibration/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/FIT/common/calibration/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TPC/reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/GlobalTracking/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/ITSMFT/MFT/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/GPU/Workflow/helper/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TPC/workflow/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TPC/calibration/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TPC/qc/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TPC/workflow/readers/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/TRD/workflow/io/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ZDC/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ZDC/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/ZDC/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ZDC/workflow/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ZDC/raw/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/ZDC/reconstruction/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/Upgrades/IT3/simulation/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/Upgrades/IT3/base/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/Upgrades/IT3/workflow/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/DataFormats/Detectors/ITSMFT/IT3/include -I/mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Detectors/Upgrades/IT3/reconstruction/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/Common-O2/v1.6.0-5/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/boost/v1.75.0-10/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/Configuration/v2.6.1-17/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/libInfoLogger/v2.1.0-2/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/Monitoring/v3.8.4-10/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/curl/7.70.0-29/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/FairMQ/v1.4.38-1/include/fairmq -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/FairMQ/v1.4.38-1/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/FairLogger/v1.9.1-5/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/fmt/7.1.0-17/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/ROOT/v6-20-08-alice1-78/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/FairRoot/v18.4.1-115/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/arrow/v1.0.0-68/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/ms_gsl/3.1.0-3/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/Vc/1.4.1-62/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/RapidJSON/v1.1.0-alice2-9/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/libuv/v1.40.0-5/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/DebugGUI/v0.5.4-1/include -isystem /mnt/mesos/sandbox/sandbox/o2/sw/slc7_x86-64/GLFW/3.3.2-18/include -fPIC -O2 -std=c++17 -Werror -Wno-error=deprecated-declarations -O2 -g -std=gnu++17 -MD -MT Steer/DigitizerWorkflow/CMakeFiles/O2exe-sim-digitizer-workflow.dir/src/SimpleDigitizerWorkflow.cxx.o -MF Steer/DigitizerWorkflow/CMakeFiles/O2exe-sim-digitizer-workflow.dir/src/SimpleDigitizerWorkflow.cxx.o.d -o Steer/DigitizerWorkflow/CMakeFiles/O2exe-sim-digitizer-workflow.dir/src/SimpleDigitizerWorkflow.cxx.o -c /mnt/mesos/sandbox/sandbox/o2/sw/SOURCES/O2/6267/0/Steer/DigitizerWorkflow/src/SimpleDigitizerWorkflow.cxx
c++: fatal error: Killed signal terminated program cc1plus
```

we see, now that I got rid of most of the std::apply in `AnalysisTask.h`. 

Do you think it would be possible to use the approach of this PR (or anything better you can think of) in all the places where `RandomRing.h` is exposed in an header?

@davidrohr do you think we can hide Vc/Vc from the GPU headers as well?

**Comment by davidrohr** [comment]
For the `GPU/TPCFastTransformation/Spline...` headers this might be difficult. These functions are meant to be inline.
@sgorbuno : Could we perhaps split the headers, and have `.inc` files with the inline functions, to be included only if the user actually uses the splines, and leave only the class definitions in the normal headers?

**Comment by davidrohr** [comment]
@mattkretz : do you by chance have any experience on whether memory consumption or compile time increases by including `<Vc/Vc>` ?

**Comment by sawenzel** [comment]
@ktf: About how much memory are we talking here? And how much does the present PR improve the situation?

**Comment by sawenzel** [comment]
@ktf: In this concrete case, I think I can offer a solution without inclusion of <Vc> in RandomRing (PR will follow). I am not in favour of introducing additional "Context" classes.

**Comment by ktf** [comment]
The profile I did was on a mac, the compile time was measured using `clang's` `-ftime-trace` option via the script:

```
scripts/profile-compilation Steer/DigitizerWorkflow/src/SimReaderSpec.cxx
```

I used `SimReaderSpec.cxx` rather than `SimpleDigitizerWorkflow.cxx` (which is the one which I've seen failing) because in the former hiding Vc can be done easily (while in the latter is a bit everywhere). The results of the two time profiles are at:

* With VC : https://www.speedscope.app/#profileURL=https://raw.githubusercontent.com/ktf/profile-reports/main/SimReaderSpec-with-vc.cxx.json
* Without VC: https://www.speedscope.app/#profileURL=https://raw.githubusercontent.com/ktf/profile-reports/main/SimReaderSpec-without-vc.cxx.json

As you can see, RandomRIng alone takes ~0.8s, out of ~5s of compilation.

The memory usage on a mac with clang (which is admittedly not the platform failing, merely one which allows me to profile) goes from ~1.4GB to ~1GB, which is the same behaviour I saw when getting rid of `std::apply` in the analysis code.

I have the impression that also in this case the actual culprit is `std::tuple` usage...

For completeness, as already reported in the JIRA, the other big offenders are ptree, boost::serialise, FairTMessage, but for those I do not have a simple solution.

**Comment by sawenzel** [comment]
If Vc is really leading to a compiler crash, something must be done of course ... but in my opinion we shouldn't focus on compile time in this discussion.  Saving a handful of seconds will not change anything.

So wouldn't it finally make more sense to ask for more dedicated hardware like we discussed before?
I am worried that these CI problems force us to use coding patterns which may not be applicable all the times, or which may not be known to all developers.

By the way, we also compile VecGeom where Vc is massively used and no problems are known there. 

In any case, if we want to do something now, we could merge this PR or try to avoid including Vc/Vc in headers completely as done here https://github.com/AliceO2Group/AliceO2/pull/6274. We can see if this really improves the situation.

**Comment by ktf** [comment]
The compile time argument is just something which can be measured easily and which seems to correlate to pathological behaviours of GCC. Unfortunately there is no `-ftrace-mem`, neither in clang nor in GCC, so it's not exactly a science... As I said the `std::tuple` (and before that the constexpr misbehaviour) was spotted looking at the compile time plot. That said, this PR seems to shave off not only almost a second, but also a few hundreds MB.

I like your solution in #6274 better, though, so we can close this.

**Comment by sawenzel** [comment]
Done for now via #6274. Closing

**Pull request closed without merging**
