### PR TITLE
Make CLING see the header for creation of TruthContainer<trd::MCLabel>

### PR DESCRIPTION
**Pull request by sawenzel**
Fixes https://alice.its.cern.ch/jira/browse/O2-804

### CODE REVIEW

**Comment by davidrohr** [comment]
@sawenzel : I think the correct fix would be to add the header in the TRD/base/CMakeLists.txt here:
```
o2_target_root_dictionary(TRDBase
                          HEADERS include/TRDBase/TRDPadPlane.h
```
Although in general, I'd move the part with the MCLabel to DataFormats/Detectors/TRD.
This explicitly lists the header files, which are used for the ROOT dictionary.

**Comment by sawenzel** [comment]
@davidrohr : Does this  work for you? In my case I am getting 
```
CMake Error at cmake/AddRootDictionary.cmake:87 (message):
  add_root_dictionary was given an inexistant input include
  /Users/swenzel/alisw_new/sw/SOURCES/O2/1.0.0/0/Detectors/TRD/base/include/SimulationDataFormat/MCTruthContainer.h
```
when just adding "include/SimulationDataFormat/MCTruthContainer.h" to the list of HEADERS.

As for the location of TRD data headers: I think this is a different discussion and should be addressed in a different PR.

**Comment by davidrohr** [comment]
You'll have to put the full relative Path inside O2, since the headers are not yet installed:
`../../../DataFormats/simulation/include/MCTruthContainer.h`

**Comment by sawenzel** [comment]
Well. This is imho rather inconvenient as this makes this CMakeFile specific to its absolute location in the code.

**Comment by davidrohr** [comment]
I also don't like it, but what we basically do is to create a dictionary from two classes that do not depend on each other, so we'll have to pass both files explicitly to CLING or include one into the other (as you are doing). Don't know if that is better. I think this is by construction and there are only poor solutions.

Another alternative might be to include the headers directly in the linkDef.h? But that would be a general change on how we define headers for the linkDef. But actually, to me it would make sense, because then we would maintain the required headers and the dictionary definitions in one place?

**Comment by sawenzel** [comment]
In this case, the library target already depends on SimulationDataFormat so it knows those headers (locations). I think it should be possible to just propagate this knowledge also to dictionary creation.

**Comment by davidrohr** [comment]
Well, but how would you know which header exactly? You could only pass all headers out of SimulationDataFormats to CLING, which would also not be what we want.

What I meant is to change the linkDef files to something like:
```
[...]
// or submit itself to any jurisdiction.

#ifdef __CLING__

#include "SimulationDataFormat/MCTruthContainer.h"
[...]

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ class o2::trd::TRDPadPlane + ;
[...]
#pragma link C++ class o2::dataformats::MCTruthContainer < o2::trd::MCLabel> + ;

#endif
```

Then we would not need the extra list of header files in the CMake.
To me it is actually more consistent than what we have now.
To be honest, I didn't try yet whether this works, but in principle it should.

**Comment by sawenzel** [comment]
Fine. What I meant is: I am ok to specify MCTruthContainer.h explicitely but not with full relative path since the search paths should be known.

**Comment by davidrohr** [comment]
OK, now I understand, but then you should just add `SimulationDataFormat/MCTruthContainer.h` without the `include` beforehand. That might work.

**Comment by sawenzel** [comment]
code checker has problems. This needs to be checked again.

**Comment by davidrohr** [comment]
Weird error, no idea, but don't have a working O2 installation right now, so I cannot check at the moment.

**Comment by sawenzel** [comment]
Should be fixed with https://github.com/AliceO2Group/AliceO2/pull/2328. Closing.

**Pull request closed without merging**
