### PR TITLE
DPL: fixing the printout for uncaught exception at top level

### PR DESCRIPTION
**Pull request by matthiasrichter**
Format specifier for the exception reason was missing

### CODE REVIEW

**Review by ktf — APPROVED** [review]

**Comment by ktf** [comment]
Thank you for spotting this!

**Comment by matthiasrichter** [comment]
Don't know what is the exact failure of the fullCI, but it's for sure unrelated to this PR.

**Comment by ktf** [comment]
@TimoWilken I have seen this a few times already. It looks like we mark some "green" builds as red. Could you cross check what was going on?

**Comment by TimoWilken** [comment]
> @TimoWilken I have seen this a few times already. It looks like we mark some "green" builds as red. Could you cross check what was going on?

The CI builder ran out of GitHub API requests, so after the last successful build, it uploaded the logs, but couldn't change the status from red to green.

**Comment by ktf** [comment]
how come this is still an issue? didn't we move to the GraphQL API?

**Pull request merged**
