### PR TITLE
DPL Analysis: avoid std::function in literal node

### PR DESCRIPTION
**Pull request by ktf**
A function pointer with a non-capturing lambda should
be more than enough.

### CODE REVIEW

**Comment by ktf** [comment]
@aalkin any reason for the std::function?

**Comment by aalkin** [comment]
The plan was to extend it to more generic placeholders.

**Comment by ktf** [comment]
Ok, but shouldn't the placeholder in any case be available at the moment of invocation? Why the capturing lambda?

**Comment by aalkin** [comment]
I wanted to have a simple generic placeholder so any required info can be stored directly in retriever lambda. For example, the external entity for which placeholder is made can provide it directly.

**Comment by ktf** [comment]
Ok, but then, isn't it a policy class? That would allow us to decouple it completely, without paying the cost of a `std::function`.

**Comment by aalkin** [comment]
Expression nodes cannot be generic templates, since we store them in a variant and there would be too many options.

**Comment by ktf** [comment]
It does not need to be templated, does it?

```c++
template <typename T>
PlaceholderNode(Configurable<T> v, RetrieverPolicy retriever = default_retriver_policy<T>()) : LiteralNode{v.value}
: retriever{p}
{
}

void reset(InitContext& context)
{
  value = retriever(context, *this);
}
```

notice the `std::function` does the same thing internally.

**Comment by aalkin** [comment]
True, this can work. I also wanted to change the `OptionManager` so it would use configurable's own retriever when available. One of the reasons to use catching lambda was to have the value cached - for arrays and other large configurables - so it would not be copied again from the context.

**Comment by ktf** [comment]
Why copying? Ownership should be in the Parameter store, not in the configurable itself.

**Comment by aalkin** [comment]
Configurables do have a copy they own, since they may contain a whole object, while framework only has pieces of it.

**Comment by ktf** [comment]
Ok, but still, that can be kept in the policy, no? Why pollute the placeholder with the actual implementation of what it can contain?

**Comment by aalkin** [comment]
Yes, I agree that this logic can be confined to policy.

**Comment by ktf** [comment]
Ok, merging this for the meanwhile. We can then turn the lambda into a fully featured policy.

**Pull request merged**
