### PR TITLE
[Strangeness tracking] Add Decay3Body strangeness tracking

### PR DESCRIPTION
**Pull request by creetz16**
@fmazzasc @mpuccio
Before merging this we can discuss it in one of the PAGs next week.

DCA distributions and mass are looking good, the efficiency (tracked/found) is comparable with what was observed for cascades (~30% pT integrated).

Screenshot 2024-03-21 at 17 26 25
Screenshot 2024-03-21 at 17 26 40
Screenshot 2024-03-21 at 17 26 54

### CODE REVIEW

**Comment by creetz16** [comment]
+async-label <mc>, <data>

**Comment by fmazzasc** [comment]
Hi @creetz16 , the p.r. looks good from my side,  thanks a lot for the development! I would maybe just add a configurable to optionally disable the 3-body loop

**Comment by creetz16** [comment]
Thanks @fmazzasc , I added the configurable.

**Comment by fmazzasc** [comment]
Hi @shahor02 , could we merge this pr ? Thanks!

**Review by shahor02 — COMMENTED** [review]
Sure, but since it is enabled by default, do you know what is the time overhead in pp and pbpb?

**Comment by chiarazampolli** [comment]
Hello @creetz16 , @fmazzasc , @shahor02 , 

In my opinion, this should be enabled via an option in the strangeness tracking, so that we can disable it if needed. If this is not the case (I don't see a switch but maybe I overlooked something), then we cannot take it in production till it is tested in both pp and PbPb and the timing + memory is checked in detail. 

I think the best is to make it configurable, and for now OFF by default. Then you should present it at the next WP12+13 (there is one tomorrow) with your findings on timing and memory. 

Cheers,

Chiara

**Review by shahor02 — APPROVED** [review]
Merging with new feature disabled by default.  Would be good to collect some stat. on the timing overhead.

**Comment by creetz16** [comment]
Ciao @chiarazampolli and @shahor02 thanks for having a look. I am preparing the estimation of the overhead both in pp and PbPb at the moment. There is a switch in the strangeness tracking code already, I changed it now to be OFF by default.

**Comment by creetz16** [comment]
+async-label async-2023-pbpb-apass4, async-2024-pp-apass1

**Comment by chiarazampolli** [comment]
This is already in async-v1-01-branch.

**Pull request merged**
