### PR TITLE
Fix ITS chip mapping: swap module high/low cables

### PR DESCRIPTION
**Pull request by shahor02**
@davidrohr @mpuccio this will make already emulated ITS raw data tracking inefficient (will be ok if regenerated from existing digits): I had to swap some pairs of cables to match the decoder/encoder mapping to real detector.

### CODE REVIEW

**Comment by iouribelikov** [comment]
@shahor02 Hi Ruben.  Does this PR mean that the clusterisation of real raw data needs to be re-done ?

**Comment by shahor02** [comment]
> @shahor02 Hi Ruben. Does this PR mean that the clusterisation of real raw data needs to be re-done ?

Hi @iouribelikov yes, if the clusterization was done starting from raw TFs, it should be redone to get correct chips positions. 
Or, one can apply a hack by swapping the chipIDs of the module upper / lower 7 chips.
Since the data in the CTFs is already clusterized, there, the only way to get correct positions would be this trick with swapping chipIDs.

**Comment by iouribelikov** [comment]
> > @shahor02 Hi Ruben. Does this PR mean that the clusterisation of real raw data needs to be re-done ?
> 
> Hi @iouribelikov yes, if the clusterization was done starting from raw TFs, it should be redone to get correct chips positions.
> Or, one can apply a hack by swapping the chipIDs of the module upper / lower 7 chips.
> Since the data in the CTFs is already clusterized, there, the only way to get correct positions would be this trick with swapping chipIDs.

@shahor02  The funny thing is that, even with the incorrect chip positions, I do not see anything wrong in the cosmic-track residuals...  So I wonder how it will look like once these changes are merged.
May be, we should wait a bit, until I get new residuals.  With my current capacity, this would take a few days of running.

**Comment by shahor02** [comment]
What are the current residuals? Can't reprocess with this PR just a couple of TFs which where you see the tracks and compare results? The problem with delaying merging this PR is that the CTFs currently written contain a wrong mapping.

**Comment by iouribelikov** [comment]
> What are the current residuals? Can't reprocess with this PR just a couple of TFs which where you see the tracks and compare results? The problem with delaying merging this PR is that the CTFs currently written contain a wrong mapping.

Here are the residuals that I seem to get on the layer6, for tracks initiated on layers3, 4 and 5.
(Two days of running clusterization, to get this number of tracks. Because of copying data.)
l6y

**Comment by shahor02** [comment]
indeed look strangely good. But don't you record the TF filenames which contain these tracks?

**Comment by iouribelikov** [comment]
> indeed look strangely good. But don't you record the TF filenames which contain these tracks?

Yes, this information can extracted from logs !    So we can re-reconstruct just these TFs. (which will be a lot faster)

**Comment by iouribelikov** [comment]
@shahor02 Hi Ruben.  So I have selectively reconstructed a few TFs containing cosmics.  
The results are unexpected: The software chip IDs assigned to cosmic-track clusters do *not* change.
(Of course, the residuals do not change as well)

**Comment by shahor02** [comment]
Hi @iouribelikov 

Thanks! I have to think, indeed this is strange, I have to think what's going on. You were running starting from the raw data, not CTF, right? 
In any case, I would merge this PR once the test is passed, since Felix confirmed that the HW addresses were swapped and the fix does not deteriorate the reconstruction.

**Comment by iouribelikov** [comment]
> Hi @iouribelikov
> 
> Thanks! I have to think, indeed this is strange, I have to think what's going on. You were running starting from the raw data, not CTF, right?

Yes. This was a reconstruction from raw-data TFs.

 
> In any case, I would merge this PR once the test is passed, since Felix confirmed that the HW addresses were swapped and the fix does not deteriorate the reconstruction.

Could not it be that we still have (somewhere) another "swap" ?   that goes in a "compensating direction" ?

OK to merge it.    Thank you very much for this fix !

**Comment by shahor02** [comment]
There could be still many errors, but this PR only reassign chips to other HW cable. Actually, you say that residuals did not change, it this true for the abs. tracks position?

**Comment by iouribelikov** [comment]
> There could be still many errors, but this PR only reassign chips to other HW cable. Actually, you say that residuals did not change, it this true for the abs. tracks position?

Nothing changes.  The global positions of cosmic clusters remain the same.

**Comment by shahor02** [comment]
@MichaelLettrich are macOS, o2 and o2-dataflow-cs8 builders dead?

**Comment by shahor02** [comment]
@iouribelikov ok, I've sorted out what is going on: since the Alpide data encodes the complete chipID in module, as 0:6,8-14 (and not the chip position on cable), the global chip ID extracted from 2 cables serving the same module does not change if we swap these 2 cables: each one will anyway uniquely identify the chip within the module. That's why the result of decoding does not change. 
The effective result of this PR is that:
1) chips are now decoded in global chipID increasing order (actually, I've noticed the problem after seeing that the decoding is not ordered, as it was meant to be).
2) Mapping the MC raw data now is consistent with that of real ITS. The old MC raw data should still be ok: internally it has swapped cables but since what matters is the correspondence of the chipInModule to globalChipID (which is not affected by the cabling), the positions of the clusters don't change (the 2 cables in total ship exactly the same data, simply in a different order). 
Confusing but fact...

Some CI's are dead, merging.

**Comment by iouribelikov** [comment]
@shahor02 Excellent news !

**Pull request merged**
