### PR TITLE
TPC QC tasks on Tracks and PID: fix phi range

### PR DESCRIPTION
**Pull request by stheckel**
o Phi range has been changed from -pi to +pi now to 0 to 2pi
o This is changed here in the TPC O2 QC tasks
o In addition, the hard coded cut on TPC clusters in the tracks task
  is switched off for the tests during TPC pre-commissioning

### CODE REVIEW

**Comment by wiechula** [comment]
Please fix the clang format issue. Best is to always run clang format before committing.

**Comment by stheckel** [comment]
Hi @wiechula,
sorry, forgot it this time, files are now clang formatted.
Cheers, Stefan

**Comment by wiechula** [comment]
Hi @davidrohr ,
it seems there is a problem with the GPU check. Can this PR be merged nevertheless, the changes are rather trivial and the other tests are all fine.

**Comment by davidrohr** [comment]
Merging since it cannot affect the GPU anyway

**Pull request merged**
