### PR TITLE
Fix importing decay products:

### PR DESCRIPTION
**Pull request by ihrivnac**
Do not include the decaying particle

### CODE REVIEW

**Comment by sawenzel** [comment]
Thanks. I guess this solves the problem with explosion of the log file?

**Comment by ihrivnac** [comment]
Yes.

**Comment by preghenella** [comment]
@sawenzel @ihrivnac , can I ask what the problem was?

**Comment by sawenzel** [comment]
Geant4 crashed  and had GB of log messages.

**Comment by preghenella** [comment]
ok, thanks.

But understand better, perhaps @ihrivnac can explain.
Why is removing the particle to be decayed is the solution for the problem?

I might expect then that if unstable particles passed by the external decayer are injected back into Geant4 we have a general issue with the decays. What I mean is that the external decayer might perform a chain of decays (for instance D0 -> K0_bar + anything -> K0s + anything).
Eventually also the already-decayed K0_bar would be passed the Geant, which is wrong.

So I believe the issue is general and not only related to the first particle.
This can be fixed in the decayer, but I wanted to understand why it is so that particles with status code != 1 are passed back to Geant4. And why there is an apparently different behavior wrt. Geant3 and Geant4.

Thanks,
Roberto

**Comment by ihrivnac** [comment]
Hi @preghenella,
The decayer is supposed to pass only the decay products not the decaying particle; the decaying particle is not included in the AliRoot decayer implementations. 
I agree, that we can still have a problem in case of a decay chain; on the other hand I don't see why this particle filtering (excluding of the particles with status code != 1) should be done in each MC implementation, while it is the same for all MCs. 
But as this is already the case for the AliRoot decayer implementations (which we did not spot earlier),  I will add the filtering in the Geant4 VMC decayer, too, and make a tag with this fix.

**Comment by preghenella** [comment]
Hi @ihrivnac ,
maybe I do not see it correctly, but to me it seems that in the AliRoot decayer we are importing all particles.
From https://github.com/alisw/AliRoot/blob/master/PYTHIA6/AliPythia6/AliDecayerPythia.cxx
```
Int_t AliDecayerPythia::ImportParticles(TClonesArray *particles)
{
// Import the decay products
//
  const Float_t kconvT=0.001/2.999792458e8; // mm/c to seconds conversion
  const Float_t kconvL=1./10; // mm to cm conversion
  int np = fPythia->ImportParticles(particles, "All");
  // pythia assigns decay time in mm/c, convert to seconds
  for (int ip=1;ip<np;ip++) {
    TParticle* prod = (TParticle*)particles->At(ip);
    if (!prod) continue;
    prod->SetProductionVertex(prod->Vx()*kconvL,prod->Vy()*kconvL,prod->Vz()*kconvL,kconvT*prod->T());
  }
  return np;
}
```
The call `ImportParticles(particles, "All")` puts all particles from `Pythia6` into the `particles` array (including decayed particles and I would say also including the original particle to be decayed).

Perhaps @amorsch can add a comment on that.

**Comment by amorsch** [comment]
We pass all particles back to the transport code in order to have the full decay history in the output. Concerning the original particle, note that the loop starts at 1, so I think it is skipped.

**Comment by preghenella** [comment]
Hi @amorsch ,
the loop starts at 1 but the entry n. 0 of the array is untouched and it is still passed out with the array (and the size of the return value is the size of the array). The loop only converts the (x,y,z,t) coordinates to (cm,cm,cm,s).

From what I could see from Geant3, it does not matter if we pass all particles: we are not going to have the full decay history because the particles with status != 1 are dropped and not passed back to Geant3 at all (at least, this is the observation from the O2 point of view).

**Comment by preghenella** [comment]
Here is what happens in `Geant4` if I inject a D0 particle (this is `o2`).
The D0 decay is handled by the Pythia8 decayer (`DecayerPythia8`, including the modification discussed here). The decay is force to be
```
D0 -> K*- + anything 
```
The relevant part of the log is
```
--------  PYTHIA Event Listing  (complete event)  ---------------------------------------------------------------------------------
 
    no         id  name            status     mothers   daughters     colours      p_x        p_y        p_z         e          m 
     0        421  (D0)               -11     0     0     1     3     0     0     -2.170     -2.348     -0.623      3.753      1.865
     1        -13  mu+                 91     0     0     0     0     0     0     -0.863     -0.372      0.163      0.960      0.106
     2         14  nu_mu               91     0     0     0     0     0     0     -0.559     -0.369     -0.427      0.794      0.000
     3       -323  (K*-)              -91     0     0     4     5     0     0     -0.748     -1.607     -0.359      1.999      0.852
     4       -311  (Kbar0)            -91     3     0     6     6     0     0     -0.535     -1.454     -0.147      1.634      0.498
     5       -211  pi-                 91     3     0     0     0     0     0     -0.213     -0.152     -0.212      0.365      0.140
     6        130  K_L0                91     4     4     0     0     0     0     -0.535     -1.454     -0.147      1.634      0.498
                                   Charge sum:  0.000           Momentum sum:     -2.170     -2.348     -0.623      3.753      1.865

 --------  End PYTHIA Event Listing  -----------------------------------------------------------------------------------------------
nofParticles: 6
  0th particle PDG: -13     G4 particle name: mu+
  1th particle PDG: 14     G4 particle name: nu_mu
  2th particle PDG: -323     G4 particle name: k_star-
  3th particle PDG: -311     G4 particle name: anti_kaon0
  4th particle PDG: -211     G4 particle name: pi-
  5th particle PDG: 130     G4 particle name: kaon0L
nofParticles for tracking: 6
```
where you can see that we have 6 particles for tracking.
K*- was decayed by Pythia8, but is being tracked and eventually decayed again by Geant.
So, the net result is that we have the K*- decay happening twice.
This can be seen in the kinematics as well (scanning PDG code and mother ID)
```
File name : o2sim_Kine.root
***********************************************
*    Row   * Instance * MCTrack.m * MCTrack.m *
***********************************************
*        0 *        0 *       421 *        -1 *
*        0 *        1 *       -13 *         0 *
*        0 *        2 *      -323 *         0 *
*        0 *        3 *      -311 *         0 *
*        0 *        4 *      -211 *         0 *
*        0 *        5 *       130 *         0 *
*        0 *        6 *      -321 *         2 *
*        0 *        7 *       111 *         2 *
*        0 *        8 *        13 *         6 *
*        0 *        9 *        22 *         7 *
*        0 *       10 *        22 *         7 *
*        0 *       11 *       130 *         3 *
*        0 *       12 *        13 *         4 *
***********************************************
```
What you can see here is the following:
Instance n.2 is the K*- that has been decayed by Pythia producing n.3 (K0_bar) and n.4 (pi-). Pythia8 also transformed n.3 (K0_bar) in n.5 (K0_L).
Everything went in Geant, that has decayed again n.2 into n.6 (K-) and n.7 (pi0). Geant has also converted again n.3 (K0_bar) into n.11 (K0_L).

**Comment by preghenella** [comment]
What happens with Geant3 is different, here it is for the same settings
```
 --------  PYTHIA Event Listing  (complete event)  ---------------------------------------------------------------------------------
 
    no         id  name            status     mothers   daughters     colours      p_x        p_y        p_z         e          m 
     0        421  (D0)               -11     0     0     1     3     0     0     -0.374      0.262     -0.431      1.967      1.865
     1        -13  mu+                 91     0     0     0     0     0     0     -0.399      0.317      0.206      0.560      0.106
     2         14  nu_mu               91     0     0     0     0     0     0     -0.199      0.161     -0.392      0.468      0.000
     3       -323  (K*-)              -91     0     0     4     5     0     0      0.224     -0.216     -0.245      0.939      0.852
     4       -311  (Kbar0)            -91     3     0     6     6     0     0      0.191     -0.363     -0.036      0.646      0.498
     5       -211  pi-                 91     3     0     0     0     0     0      0.033      0.147     -0.209      0.293      0.140
     6        130  K_L0                91     4     4     0     0     0     0      0.191     -0.363     -0.036      0.646      0.498
                                   Charge sum:  0.000           Momentum sum:     -0.374      0.262     -0.431      1.967      1.865

 --------  End PYTHIA Event Listing  -----------------------------------------------------------------------------------------------
```
Geant3 does not verbosely state which particles came back for tracking, but we can again scan the kinematics and see what is there
```
File name : o2sim_Kine.root
***********************************************
*    Row   * Instance * MCTrack.m * MCTrack.m *
***********************************************
*        0 *        0 *       421 *        -1 *
*        0 *        1 *      -211 *         0 *
*        0 *        2 *       130 *         0 *
*        0 *        3 *      -211 *         2 *
*        0 *        4 *       -11 *         2 *
*        0 *        5 *        13 *         3 *
*        0 *        6 *        11 *         5 *
*        0 *        7 *        13 *         1 *
*        0 *        8 *        11 *         7 *
***********************************************
```
As you can see, there is no sign of the K*- here and no sign of the K0_L.

**Comment by ihrivnac** [comment]
There is indeed something wrong in the geant4_vmc implementation. There is a check for the particle status but it does not work correctly. I will investigate.

**Comment by preghenella** [comment]
Hi @ihrivnac , 
I noticed the following from Geant3 VMC.
https://github.com/vmc-project/geant3/blob/74ab9dde34ebd906a7fa05ffe28932497299b4a6/TGeant3/TGeant3gu.cxx#L285
```
 // Fetch Particles
      Int_t np = decayer->ImportParticles(particles);
      if (np <= 1)
         return;
```
This line seems to tell me that the original particle must be kept in the array.
I do not have a very good example to illustrate where things could go wrong if the original particle is not included in the array, but I have one example nonetheless.

Assume we inject K0 particles in Geant and we instruct Geant to pass the particle to the external decayer for its decay. Pythia would take the K0 and transform it into a K0_S (or K0_L).
If we then remove the original K0 from the array, we are left with only the K0_S (or K0_L).
But the array size will be 1, the code will return and nothing will happen.

**Comment by preghenella** [comment]
testing and looking better, I can confirm that not including the original particle breaks Geant3
https://github.com/vmc-project/geant3/blob/74ab9dde34ebd906a7fa05ffe28932497299b4a6/TGeant3/TGeant3gu.cxx#L299
```
     // Particle loop
      for (i = 1; i < np; i++) {
         iparticle = (TParticle *)particles->At(i);
```
the particle loop in the user decay routine skips the first particle.

I think this commit must be reverted.

**Comment by sawenzel** [comment]
@preghenella : If I understand correctly, the conclusion is that this PR needs to be reverted.

I guess we can do it, but not immediately as it would bring back G4 to a crashing state.  Or we could maybe disable the pythia8 decayer until the whole system works and then re-enable later on again.

**Comment by ihrivnac** [comment]
@preghenella ,
You are right, the problem obserevd with the new decayer was not in including the origin particle. I made too fast this conclusion when seeing the loop starting from 1 in AliRoot.
The different behaviour comes from the return particle status, which is in your class 
statusHepMC(), while in AliRoot implementation this is isFinal().

The code in Geant4 VMC uses the value of the status code for decision about passing  or not the particle in Geant4. 
I created a new PR (as this one was already merged) for this change: https://github.com/AliceO2Group/AliceO2/pull/3840
Please, check.

**Comment by ihrivnac** [comment]
@sawenzel , the new PR reverts this one.

**Comment by preghenella** [comment]
Thanks @ihrivnac ,
`isFinal()` should be good as well.
Roberto

**Pull request merged**
