### PR TITLE
DPL GUI: allow using external DebugGUI package

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr could you take a look at this and check if it does not break the TPC Tracking GUI? You can also add DebugGUI as a dependency to O2 in `alidist` and it should pick the new version (PR coming).

**Comment by davidrohr** [comment]
Sure, will check tonight or tomorrow. Just sitting at the beach.
Kind Regards
David Rohr

**Comment by ktf** [comment]
🌞

**Comment by ktf** [comment]
@dennisklein macOS build fails in FairRoot with:

```bash
-- Build CbmModule with Gdml support
CMake Error at MbsAPI/CMakeLists.txt:19 (CHECK_SYMBOL_EXISTS):
  Unknown CMake command "CHECK_SYMBOL_EXISTS".


-- Configuring incomplete, errors occurred!
See also "/build/ci_checks/o2_checker_macos_o2_ci_0/sw/BUILD/f6238fbb307f372f12bb2aff1c7e731b1d98310c/FairRoot/CMakeFiles/CMakeOutput.log".
```

any idea?

**Comment by davidrohr** [comment]
This might be the problem with the new fairroot? I belive to remember that peter had a fix.

**Comment by ktf** [comment]
@pzhristov does it ring any bell?

The codacy issue is spurious, instead...

**Comment by dennisklein** [comment]
@ktf I remember this, it was fixed by you in march https://github.com/FairRootGroup/FairRoot/commit/7beb33524a7afe64a4a20534c9f7b38b4657924c already.

**Comment by davidrohr** [comment]
@ktf : I have found few issues with the current external DebugGUI built, which I only fixed now after my vacation :|
1. The library should be glfw not GLFW (In O2 this was correct, but in DebugGUI's CMake, it is upper case). The attached patch 
[debuggui.patch.gz](https://github.com/AliceO2Group/AliceO2/files/3563343/debuggui.patch.gz) fixes this.
2. DebugGUI finds GLFW, but then in turn O2 does not find it in the DebugGUI's DebugGUIConfig.cmake. The problem seems to be that there is just "find_dependency(GLFW)" without the NAMES setting pointing to glfw3, for the glfw3 target CMake file. When I change this to "find_dependency(GLFW NAMES glfw3 CONFIG)", it works. Not sure, if the CONFIG is needed. Patch is here: 
[debuggui2.patch.gz](https://github.com/AliceO2Group/AliceO2/files/3563348/debuggui2.patch.gz)
3. I am using the functions ImGui_ImplGlfwGL3_Init and ImGui_ImplGlfwGL3_Shutdown which are defined in imgui_impl_glfw_gl3.h, but this file is not installed. You'll need to either install it, or add the declarations to imgui.h.
4. Please add #2359 to have correct include paths.
With these 4 fixes, the display work.
Cheers
David

**Comment by ktf** [comment]
I've merged your changes in DebugGUI. Assuming we can merge #2359 and this one, then all is left should be alisw/alidist#1798.

**Comment by davidrohr** [comment]
Looks good for me, we can go ahead I think.
These MaxOS errors seem unrelated, because they are everywhere.
In general though, I'd prefer to still first fix the CI problems (even if they are unrelated), otherwise we cannot be sure if what we merge has side effects.

**Comment by ktf** [comment]
Yeah, agreed. Not clear at this moment what the issue with mac builds is.

**Pull request merged**
