### PR TITLE
AOD to HepMC tool

### PR DESCRIPTION
**Pull request by cholmcc**
The class `o2::eventgen::AODToHepMC` converts events stored in AOD
tables to `HepMC3::GenEvent` objects.   The objects are kept in-memory
so that clients (e.g., a future `o2::analysis::RivetWrapper` or similar)
can pick up that event structure and process it.

The converter class will convert `o2::aod::McCollisions` and
`o2::aod::McParticles` information, as well as auxiliary information in
`o2::aod::HepMCXSections`, `o2::aod::HepMC::PdfInfos`, and
`o2::aod::HeavIons`.

The built `HepMC3::GenEvent` data structures can optionally be stored on
disk in HepMC3 ASCII files.

The application `o2-aod-mc-to-hepmc` uses this converter class to
convert AOD files to HepMC files.

Note that the converter _only_ depends on
`Framework/AnalysisDataFormats.h` and not any other AOD information.

Compilation of `Generators/src/AODToHepMC.cxx` is contingent on HepMC3
being found at configure time.

The code is heavily documented and commented.

### CODE REVIEW

**Comment by cholmcc** [comment]
`build/AliceO2/O2/o2/macOS` failes somewhere deep when ROOT tries to AcLIC some scripts.  Not related to the changes of this MR.  Same for `build/AliceO2/O2/o2/macOS-arm`.  `build/O2/fullCI ` failed because of missing braces around a single-statement branching - even though there is no ambiguity - sigh :-/

**Comment by cholmcc** [comment]
Failures of `build/AliceO2/O2/o2/macOS-arm` and `build/AliceO2/O2/o2/macOS` are _not_ related to this MR. 

The problem is that Apache `arrow` uses the symbol `PREALLOCATE` which MacOSX defines as a preprocessor macro to be `0x00000001`.  However, Apache `arrow` uses that name in places where an identifier is expected.  

MacOSX defines `PREALLOCATE` in line 126 the header 

 ```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/sys/vnode.h

```

Apache `arrow` uses it for example in line 535 of 

```
include/arrow/compute/kernel.h
```

like 

```
  MemAllocation::type mem_allocation = MemAllocation::PREALLOCATE;
```

which wont work.  Perhaps a work-around is to introduce the lines 

    #ifdef PREALLOCATE 
    #undef PREALLOCATE 
    #endif           

in the appropriate header of the ALICE `arrow` fork.  

Funny thing is that it only shows up when ROOT tries to AcLIC a script, which would indicate that ROOT's AcLIC includes headers implicitly - specifically the `vnode.h` header.  Otherwise, if `arrow` somehow included that header directly or indirectly, then compilation of the ALICE fork of `arrow` would fail too. 

In any case, these two failures are **false negatives**

**Comment by cholmcc** [comment]
Hi all, 

Any news on this?   Thanks.

**Comment by cholmcc** [comment]
Hi all, 

Please advice as to what to do next.  Thanks. 

Yours,
_Christian_

**Comment by cholmcc** [comment]
I just resynced this branch against `dev`.   

Please advice as to the next steps.  Thank you. 

Yours,
_Christian_

**Review by pzhristov — APPROVED** [review]

**Comment by pzhristov** [comment]
The errors in the CI are not related to this PR, we can merge it.

**Comment by ktf** [comment]
The errors in the CI are actually related. ;-) This PR exposed some arrow header to cling, which is not actually able to digest it, due to some injected system header. Fixed by https://github.com/AliceO2Group/AliceO2/pull/12248.

**Pull request merged**
