### PR TITLE
Optimization on TRD digitizer

### PR DESCRIPTION
**Pull request by sawenzel**
Speed up TRD digitizer by using circular pre-computed random numbers.
This is also a step towards multi-threading since we are no longer using the gRandom singleton.

See previous discussion here https://alice.its.cern.ch/jira/browse/O2-734.

### CODE REVIEW

**Comment by sawenzel** [comment]
This step yields roughly 20% improvement for a central PbPb event.

**Comment by davidrohr** [comment]
Great, thx, good first step

**Comment by sawenzel** [comment]
[trddigits2.pdf](https://github.com/AliceO2Group/AliceO2/files/3905792/trddigits2.pdf)
[trddigits_1.pdf](https://github.com/AliceO2Group/AliceO2/files/3905795/trddigits_1.pdf)

Digit distribution unaffected.

**Comment by sawenzel** [comment]
after
before

Digit distribution unaffected by this change.

**Pull request merged**
