### PR TITLE
Analysis: speed up PID

### PR DESCRIPTION
**Pull request by ktf**
* Avoiding virtual inheritance to DetectorResponse.
* Reserve memory upfront.

### CODE REVIEW

**Comment by ktf** [comment]
@njacazio @jgrosseo any objection to this appoach? DetectorResponse is not really a base class (because you will never have a polymorphic container of DetectorResponses), so I changed it to have the actual detector response as a policy. Probably some renaming would help...

The other fix is to reserve memory upfront, which we could merge separately if you do not agree with the rest of the changes.

**Comment by njacazio** [comment]
Hi @ktf, for me it's fine.
Be aware that we will delegate PID (as well as the used PID objects) to dedicated tasks so as to simplify the whole workflow.
Only parameters will be fetched from the CCDB and not the actual implementation.
According to plans I should be able to do this in the next few days.

**Review by jgrosseo — APPROVED** [review]

**Comment by ktf** [comment]
Ok. One refactoring you should do, IMHO, is to move the track properties outside the Response class and pass it to the method each time. This will the allow you to easily template the Response on the actual PID::ID, and take advantage of the constexprs (by having one constexpr Response<PID> instance per particle type, inside the process method itself). Right now, since you pass them as parameters, the compiler cannot assume they are constexpr when simplifying the code.

**Comment by njacazio** [comment]
Yes, I agree on this. This is actually what I prepared so far, I will try to open a PR soon.

**Pull request merged**
