### PR TITLE
Add PCG pseudo-random number generator

### PR DESCRIPTION
**Pull request by knopers8**
I would like to use that PRNG in Data Sampling soon.
Though, I am not really sure, what is the nicest way to include to the project a little header only library. Making it a proper dependency seems to be an overkill.
Also, as it has no .cxx files, having empty CMakeLists is enough to use it. Is that ok?

What are your thoughts on this? @Barthelemy @dberzano

### CODE REVIEW

**Comment by Barthelemy** [comment]
What we (Adam, Vladimir and myself) did in the QC is to have a folder "external" in the src directory. At least, it makes it clear that it is not to be installed and that it is not us who developed it.

**Comment by Barthelemy** [comment]
Now, looking at what you did, I think that it is ok, but maybe just add a little readme to say where to find the latest version and that it is not us who maintain it ? 
Alternatively, put it in `Utilities/external`

**Comment by knopers8** [comment]
Done. What about the coding guidelines? Since it is external library, I suppose it does not have to follow them.

**Comment by Barthelemy** [comment]
Indeed it does not have to follow them.

@dberzano what do you think ? is it ok like that ?

**Comment by dberzano** [comment]
Hi, @Barthelemy is absolutely right. We need to add an exception for that. Let me have a look.

**Comment by dberzano** [comment]
For the record I have fixed the `clang-format` issue in this very PR. macOS problem is unrelated, I believe this is ready for merging.

**Comment by knopers8** [comment]
Thank you for taking care of that. Since Barth is on holidays this whole week, can you merge it please?

**Comment by sawenzel** [comment]
@knopers8 : Sorry for the late posting.

I am wondering why you need this particular external rng? Could you maybe summarize the plus points that this thing has in comparison to what comes with C++11 (or ROOT)?

Thanks

**Comment by sawenzel** [comment]
Thanks for the info and the link. This is probably quite similar to counter-based rngs like `Random123` https://www.deshawresearch.com/resources_random123.html.

For the record, please note that ROOT nowadays may have better rngs than the ones you studied. There is for instance an implementation of the MixMax generator which should also be really fast and one for Mersenne Twister (not sure if this is TRandom5 ... )

**Comment by knopers8** [comment]
Thanks, I did not find this `Random123` family earlier, but yes, it sure looks like something I could have evaluated as well. If I do some bigger tests in the future, I will include it and the rest of ROOT PRNGs (which might happen while writing my thesis).

**Pull request merged**
