### PR TITLE
Framework/Core/src/HistogramSpec.cxx: increase MAX_DIM

### PR DESCRIPTION
**Pull request by dsekihat**
Framework/Core/src/HistogramSpec.cxx: increase MAX_DIM

### CODE REVIEW

**Comment by dsekihat** [comment]
Dear experts, I would like to increase MAX_DIM of THnSparse for flow analyses at pair and leg level simultaneously.

**Comment by ktf** [comment]
I think this has already been discussed and there were concerns about the scalability of such an increase.

@jgrosseo @ddobrigk @aalkin @pzhristov  do you remember the details?

I suspect we would be better off if we discussed the change in a WP4 / WP14 meeting.

**Comment by pzhristov** [comment]
20-D histogram is completely useless - you should consider ntuple or other non-binned data collection for multi-dimensional analysis.

**Comment by dsekihat** [comment]
At least, MAX_DIM should not prevent users from defining histograms. Users can decide whether multi-dimensional histograms are useful or not, depending on their needs. In the end, if they are not useful for me, I don't use them. The point is that system should allow users to produce multi-dimensional histograms.

**Comment by dsekihat** [comment]
If there are concerns about scalability in O2, I don't insist. if MAX_DIM = 10 was chosen, just because it was expected to be large enough in the past, can you consider to increase it? Thank you.

**Comment by ddobrigk** [comment]
Hi everyone, personally, I think the limit of 10 dimensions is simply a number and I would not a priori object to increasing it. The main problem that is encoded in the statement "completely useless" from Peter is that at its bare minimum of usefulness, any dimension must have, say, at least 2 bins (and then under/overflow) and therefore even using 4 values / dimension and 11 dimensions (one more than our limit) this histogram would occupy at least 16MB of memory (probably more due to multidimensional over/underflow). Even a char-based histogram (8 bits per value) with a more reasonable 10-bins-per-dimension and at 11 dimensions would use 100 GB of RAM. So, these numbers do beg the question: Daiki, are you sure you actually have a viable use case for that? Maybe you can elaborate on how that would work in practice without exploding memory. Thanks! :-D

**Comment by dsekihat** [comment]
Hi David and all, No, unfortunately, I don't have any viable cases without increasing memory. If the number of dimensions increases, the occupied memory definitely increases. So, I close this PR.

**Comment by fgrosa** [comment]
Hi @ddobrigk @pzhristov @dsekihat @ktf sorry if I comment late on this PR, however I did not notice it before.
I also would like to have the possibility to have a number of axes larger than 10. I am also not sure about the comment of @ddobrigk. In this train https://alimonitor.cern.ch/hyperloop/train-run/221837/general I had 4 THnSparses with 9 dimensions (for a total of 9.4x10^14 bins each) and no issues at all with memory consumption (it was indeed well below the threshold of hyperloop). @ddobrigk are you sure that the number of bins reflects directly on the memory also in case of THnSparses? If this was the case, I would have had much more than 100 GB in memory. Let me know what you think, thanks!

**Comment by ddobrigk** [comment]
Hi @fgrosa you're right, my argument only holds for non-sparse histograms, very good point. As I stated before, I have no objections to anyhow increasing this if we have a use case and indeed sparse histos are a good case :-)

**Comment by fgrosa** [comment]
Hi @ddobrigk thanks for your feedback!
@ktf @pzhristov do you think that sparse histograms are a good motivation for this, or do you prefer to discuss this on monday at the WP4/WP14 meeting?

**Comment by ddobrigk** [comment]
Hi @fgrosa @pzhristov @ktf I don't really see any big disadvantage in bumping this number up to 20: as far as I can tell, it's just a hardcoded upper limit, and in the end it is (as always) up to the user to make sure memory usage stays under control. People can anyway also explode memory consumption even using only 10 dimensions - however, and most importantly, a careful user can, indeed, make a valid use of a THnSparse with more than 10 dimensions right now, and we should not prevent that. Shall we merge? Thank you very much!

**Comment by pzhristov** [comment]
Hi all, I think even the THnSparse makes no sense with such a big number of dimensions. In the example of @fgrosa, only if the values are highly correlated you would get reasonable size in memory. If they are not, the number of "fired" bins will be roughly proportional (or equal) to the number of collisions/combinations  and will grow linearly in memory. This is serious problem also when you try to merge the THnSparse histograms, we have seen it since the introduction of the code in Root. So my suggestion is to keep the max number of dimensions to 10 just to discourage misuse of inappropriate tools :)

**Comment by fgrosa** [comment]
> Hi all, I think even the THnSparse makes no sense with such a big number of dimensions. In the example of @fgrosa, only if the values are highly correlated you would get reasonable size in memory. If they are not, the number of "fired" bins will be roughly proportional (or equal) to the number of collisions/combinations and will grow linearly in memory. This is serious problem also when you try to merge the THnSparse histograms, we have seen it since the introduction of the code in Root. So my suggestion is to keep the max number of dimensions to 10 just to discourage misuse of inappropriate tools :)

Hi @pzhristov in Run2 we had THnSparses with 15 dimensions that were correctly merging. This depends also on the number of entries and not only on their correlation, so what you say is not always the case. This allowed us to have anyway a much smaller output compared to a NTuple, so it was rather convenient. In general, one can misuse even 2 and 3 dimensional histograms, but I don't think this is a good reason to forbid them ;-) So I still think that having an arbitrary limit because users might misuse them is not a good motivation to limit all the users, but of course this is my point of view and I cannot decide alone (I would anyway much like to have more than 10 dimensions for my analyses for instance). Here you can find one example with 11 dimensions from Run2, that had no issue and was used for analysis https://cernbox.cern.ch/s/ymI5OvBpZOG32iG (sorry I could not find anymore the one with 15 dimensions :)). You can check in the PWG3_D2H_InvMassDplus directory, inside you find 6 TLists each one containing a THnSparse called hMassPtCutVarsAll.

**Comment by pzhristov** [comment]
Hi @fgrosa, I had a look in one of the 12-D THnSparse histograms from your file. It confirms my statement that the number of fired bins is about the same as the number of entries. Since the number of entries is relatively small (~2x10^6), the size is OK. I suppose you filled this histogram after very strict selection. Anyway, as discussed yesterday, we can increase the MAX_DIM and let those who do not use THnSparse carefully to suffer from runtime and merging problems :)

**Comment by fgrosa** [comment]
> Hi @fgrosa, I had a look in one of the 12-D THnSparse histograms from your file. It confirms my statement that the number of fired bins is about the same as the number of entries. Since the number of entries is relatively small (~2x10^6), the size is OK. I suppose you filled this histogram after very strict selection. Anyway, as discussed yesterday, we can increase the MAX_DIM and let those who do not use THnSparse carefully to suffer from runtime and merging problems :)

Many thanks @pzhristov! If this should create any trouble, as discussed yesterday, I am happy to revert it, so let's keep updated on this.

**Pull request merged**
