### PR TITLE
TPC dEdx: Send empty output in case of sampling

### PR DESCRIPTION
**Pull request by matthias-kleiner**
- this should ensure that no calibration interval is lost on the aggregator

### CODE REVIEW

**Review by shahor02 — COMMENTED** [review]
To be sure: why do we need to send dummy output for a sporadic channel?

**Comment by matthias-kleiner** [comment]
> To be sure: why do we need to send dummy output for a sporadic channel?

This we discussed shortly on friday. On the aggregator node we see sometimes big gaps between the received TFs. We suspected that the reason might be that we just send no data at all for some TFs from the EPNs, which could cause some problems (but not sure if this is the real reason for the problem we see).

Also in the `void MIPTrackFilterDevice::sendOutput(DataAllocator& output) { output.snapshot(Output{header::gDataOriginTPC, "MIPS", 0, Lifetime::Timeframe}, mMIPTracks); }` we set the `Lifetime` to `Timeframe`. Could this cause some problem, when the output is only sporadic?

**Comment by shahor02** [comment]
Perhaps this sending of dummy output can be made optional?

For the Lifetime in the snapshot, I think it should not matter, the output cannel settings will override it.

**Review by wiechula — DISMISSED** [review]

**Comment by davidrohr** [comment]
What matters is mostly the input channel, although I have asked @ktf to add sanity checks:
- lifetime of output channels should match the lifetime of the input channels, where they are used.
- If an output channel has lifetime::timeframe, it must send data for every time frame, otherwise the framework should throw an error.
- Not sure if this is already implemented.

In any case: if your output is sporadic, it should be used as sporadic input only, and you do not need to send dummy data.
If you use lifetime::timeframe input, also the output should be lifetime::timeframe, and you must sent something for every tf.

**Comment by matthias-kleiner** [comment]
> What matters is mostly the input channel, although I have asked @ktf to add sanity checks:
> 
>     * lifetime of output channels should match the lifetime of the input channels, where they are used.
> 
>     * If an output channel has lifetime::timeframe, it must send data for every time frame, otherwise the framework should throw an error.
> 
>     * Not sure if this is already implemented.
> 
> 
> In any case: if your output is sporadic, it should be used as sporadic input only, and you do not need to send dummy data. If you use lifetime::timeframe input, also the output should be lifetime::timeframe, and you must sent something for every tf.

Thanks for the explanation. Indeed if I look at the input https://github.com/AliceO2Group/AliceO2/blob/257f2eefa47050976e4b418f2fde981eeee5da34/Detectors/TPC/workflow/src/CalibratordEdxSpec.cxx#L142C15-L142C24 the lifetime is the default one, which should be `timeframe` I assume. Perhaps this is just the problem that we see. I will change that too.

**Comment by davidrohr** [comment]
@matthias-kleiner : what is the status of this PR, did you do the inputs/outputs correctly now as discussed above? Can we merge it?

**Comment by matthias-kleiner** [comment]
> @matthias-kleiner : what is the status of this PR, did you do the inputs/outputs correctly now as discussed above? Can we merge it?

Yes, I changed the input to sporadic. From my side it can be merged

**Pull request merged**
