### PR TITLE
Test workflow: add initial mockup workflow for FLP qualification

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@matthiasrichter @davidrohr there is a timeout after 100 seconds in `test__testTPCSpaceChargeBase`. Is that expected and we need to extend the time or something else?

@dberzano it says it dumped the core, where is it?

Merging since it's unrelated.

```
=== test__testTPCSpaceChargeBase - /Environment ===
=== test__testTPCSpaceChargeBase - Timeout prefix: timeout --signal=SIGTERM --kill-after=10s 100s ===
=== test__testTPCSpaceChargeBase - Running /mnt/mesos/sandbox/sandbox/sw/BUILD/d209a2b2b08c8706f0cc511addb3faaa2f9195c3/O2/bin/test__testTPCSpaceChargeBase with args  (attempt 1/1) ===
=== test__testTPCSpaceChargeBase - Process running as 30164 for attempt 1 ===

 *** Break *** segmentation violation
Running 1 test case...
timeout: the monitored command dumped core
/mnt/mesos/sandbox/sandbox/sw/BUILD/d209a2b2b08c8706f0cc511addb3faaa2f9195c3/O2/tests-wrapper.sh: line 134: 30161 Segmentation fault      $TIMEOUT_CMD "$CMD" "$@"
=== test__testTPCSpaceChargeBase - Test attempt 1/1 failed with exit code 139 ===
=== test__testTPCSpaceChargeBase - Test failed after 1 attempts with 139 ===
```

**Comment by matthiasrichter** [comment]
somehow this error has popped up today, and effects all PRs. Since its a segfault, increasing timeout would not help.

Mystic, there has not been any change neither in AliceO2 nor in AliTPCCommon which would be a candidate causing this problem. ping @davidrohr @sgorbuno

**Comment by davidrohr** [comment]
Hi @matthiasrichter : I have seen it as well but didn't have time to investigate. @ehellbar is working on the space charge code.

**Comment by davidrohr** [comment]
@matthiasrichter : I had a closer look, seems to me like memory corruption. A pointer is overwritten, and it crashes in the destructor when it tries to quit. It seems to depend on compile flags / memory initialization, e.g. I cannot reproduce the crash in valgrind. @ehellbar : Can you have a look?
For the time being, I'll just disable the test in the merge PR of AliTPCCommon.

**Comment by ehellbar** [comment]
Hi @davidrohr ,
I'll have a look!

**Comment by davidrohr** [comment]
@matthiasrichter : @ehellbar has fixed the issue and it is included in the large PR to merge AliTPCCommon to O2. I'll fix the continuous tracking today, and bring it up in the WP3 meeting tomorrow. Hopefully, we can merge it then.

**Pull request merged**
