### PR TITLE
DPL: tweak the exponential backoff factor

### PR DESCRIPTION
**Pull request by ktf**
Apparently 6 is not enough.

### CODE REVIEW

**Comment by ktf** [comment]
@Barthelemy can you check if this is better?

**Comment by davidrohr** [comment]
Are we sure about this. The factor 10 we had before severely affected the TPC reco workflow performance. Perhaps there is no one-number-helps-all here?

**Comment by ktf** [comment]
I agree probably there is no catch-all number here and things will still have to be tweaked in production as a configuration parameter. I think the aim is to find something which works well enough for "laptop" tests. Maybe we could provide two modes or we could have a policy on the default values based on the name of the device...

**Comment by Barthelemy** [comment]
It did not help. I tried to go back to 10 and it did not work. I tried on another machine (both CC7) with the same result. Adding `-b 100` brings back the CPU usage to zero.

On my Mac it is working with a value of 6: CPU usage is low. 

I don't know. It is not urgent, we can drop this PR.

**Comment by ktf** [comment]
Ok, I will investigate a bit later..

**Comment by ktf** [comment]
Closing as this will not be needed anymore once #3852 is merged.

**Pull request closed without merging**
