### PR TITLE
Updating hypernuclei information in O2 Databases

### PR DESCRIPTION
**Pull request by jditzelnew**
Refers to https://github.com/AliceO2Group/AliceO2/pull/13746
No format changes, only inserts or deletes of lines.

### CODE REVIEW

**Review by sawenzel — DISMISSED** [review]
triggering the CI

**Comment by sawenzel** [comment]
@jditzelnew : Could you please accept pull request https://github.com/jditzelnew/AliceO2/pull/4 in your fork? Then the clang-format issues will be automatically fixed and we can go ahead.

**Comment by jditzelnew** [comment]
> @jditzelnew : Could you please accept pull request [jditzelnew#4](https://github.com/jditzelnew/AliceO2/pull/4) in your fork? Then the clang-format issues will be automatically fixed and we can go ahead.

Done, thanks!

**Comment by amorsch** [comment]
Looks ok to me.

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
