### PR TITLE
Fix namespace naming

### PR DESCRIPTION
**Pull request by anerokhi**
@sawenzel

### CODE REVIEW

**Comment by jgrosseo** [comment]
Do we truly believe that our coding conventions help readability?

**Comment by anerokhi** [comment]
I don't. And also I have no idea why clang-format is unhappy. When I run it locally on the diff, it modifies nothing.

**Review by sawenzel — DISMISSED** [review]
I'd say this looks good and according to the namespace rules. @noferini @wiechula @davidrohr, any objections?

**Comment by wiechula** [comment]
Sure, fine for me.

**Comment by davidrohr** [comment]
fine with me, it just seems some occurrences in the GPU part were missed.

**Comment by anerokhi** [comment]
Could some1 please look at build/O2/gpu? I think it takes too much time.

**Pull request merged**
