### PR TITLE
Development of the generic format API

### PR DESCRIPTION
**Pull request by matthiasrichter**
I have collapsed my development of a mockup for the format API, the final data header is not part of this development but is in the fork of @mkrzwic . We will soon merge it.

### CODE REVIEW

**Comment by MohammadAlTurany** [comment]
Hi Matthias,
The test crashes with:
* thread #1: tid = 0x597d9, 0x0000000100001f7f testMessageList`void print_list<AliceO2::Format::messageList<TestMsg, SimpleHeader_t> >(list=<unavailable>, hdrsel=<unavailable>) + 191 at testMessageList.cxx:77, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x0000000100001f7f testMessageList`void print_list<AliceO2::Format::messageList<TestMsg, SimpleHeader_t> >(list=<unavailable>, hdrsel=<unavailable>) + 191 at testMessageList.cxx:77
   74  	       it != list.end();
   75  	       ++it) {
   76  	    // the iterator defines a conversion operator to the header type
-> 77  	    std::cout << static_cast<typename ListType::header_type>(it) << std::endl;
   78  	    // dereferencing of the iterator gives the payload
   79  	    std::cout << *it << std::endl;
   80  	  }

**Comment by matthiasrichter** [comment]
Hi Mohammad,
seems that I have been using static_cast in an inappropriate way to invoke the type cast operator. On some architectures it works, but it's undefined, what takes precedence.

I have pushed a fix to my dev branch and it looks like it automatically appears in the PR (cool ;-). Could you please try again.

Ciao
Matthias

**Comment by MohammadAlTurany** [comment]
Hi Matthias,

Still crashing on MAC,

```
Process 85821 launched: '/Users/turany/fairsoft/releases/src/AliceO2/build/bin/testMessageList' (x86_64)
simple list:
Header ID: 1
Process 85821 stopped
* thread #1: tid = 0x6dab31, 0x000000010000267f testMessageList`void print_list<AliceO2::Format::messageList<unsigned char const*, SimpleHeader_t> >(list=<unavailable>, hdrsel=<unavailable>) + 191 at testMessageList.cxx:78, queue = 'com.apple.main-thread', stop reason = EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
    frame #0: 0x000000010000267f testMessageList`void print_list<AliceO2::Format::messageList<unsigned char const*, SimpleHeader_t> >(list=<unavailable>, hdrsel=<unavailable>) + 191 at testMessageList.cxx:78
   75  	       ++it) {
   76  	    // the iterator defines a conversion operator to the header type
   77  	    typename ListType::header_type hdr = it;
-> 78  	    std::cout << hdr << std::endl;
   79  	    // dereferencing of the iterator gives the payload
   80  	    std::cout << *it << std::endl;
   81  	  }

```

**Comment by MohammadAlTurany** [comment]
Hi Matthias,

it crashes in the line:

`stream << "Header Specification: " << std::hex << header.specification;
`

**Comment by matthiasrichter** [comment]
Hi Mohammad,
in the end, it was much simpler: a missing return statement in the custom ostream operator<<. Fix is pushed, the previous one is removed. I tested also with clang. I hope its working now.

Ciao
Matthias

**Comment by MohammadAlTurany** [comment]
Hi Matthias,
Thanks, now it works! it is merged with the dev.
best,
Mohammad

**Comment by matthiasrichter** [comment]
Hi Mohammad,
very good. But I just noticed that the first attempt also is merged now, even though it was not part of the PR.

Cheers
Matthias

**Pull request closed without merging**
