### PR TITLE
Fix for EPN ctf writer ordering which works on FLP

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr this seems to work for both the CTF writer issue and the ITS workflow on the FLP in staging. Could you cross check?

**Comment by davidrohr** [comment]
Unfortunately, this seems to break the FST on the EPNs, with ctf-writer to writing all CTFs.
Actually the situation is even worse than before.
Before I needed to introduce fluctuations in the publishing rate by stalling the readout-proxy with gdb to produce this behavior.
With this PR, it failed by itself after only 5 TFs written.

**Comment by ktf** [comment]
Updated. This seems to work now on my box (in previous attempts I forgot to revert back to use consumeOrdered) when I inject artificial delays via lldb and on the FLP.

**Comment by ktf** [comment]
Error in QC unrelated. This does not break things more than they are already broken so we merge it so that we can have a smaller "fix" PR.

**Pull request merged**
