### PR TITLE
First commit for a DQ skimmed data model, skimming task and analysis tools (VarManager and HistogramManager)

### PR DESCRIPTION
**Pull request by iarsene**

### CODE REVIEW

**Comment by iarsene** [comment]
This is just so that Giulio can have a look at the arrow errors i get. The PR contains all the commit history i had in my own branch, so maybe after we fix the issue, we reject this commit and i commit just the new files with a fresh history?
Ionut

**Comment by iarsene** [comment]
So, i managed to fix the clang issues.
In the meantime, both the VarManager and HistogramManager work fine with the currently implemented features and they can be approved, as we discussed in the meeting. I will add also the StepTHn in VarManager.
Cheers, Ionut

**Comment by iarsene** [comment]
The tableReader.cxx task now also contains examples of all the types of histograms which can be defined.

**Comment by jgrosseo** [comment]
No error according log. Merging

**Pull request merged**
