### PR TITLE
PWGDQ utility classes moved from AnalysisCore to Analysis/Tasks/PWGDQ

### PR DESCRIPTION
**Pull request by iarsene**
1) PWGDQ utility classes moved from AnalysisCore to Analysis/Tasks/PWGDQ.
2) Removed the reducedEventAnalysis.cxx obsolete task from Analysis/Tasks

### CODE REVIEW

**Comment by jgrosseo** [comment]
The include files will not work like this. The library name has to match the top level directory name. We probably need to discuss how to restructure if we want to do this...

**Comment by iarsene** [comment]
So you mean to change PWGDQCore with PWGDQ ?

**Review by jgrosseo — CHANGES_REQUESTED** [review]
To my understanding but @aphecetche may comment as well, we would need to put the includes into include/PWGDQCore similar e.g. Analysis/Core/include/AnalysisCore for the includes of the AnalysisCore library. 
In addition, for the logic, it would be properly better to have the code itself in directory corresponding to that library, instead of having it mixed into the Analysis/Tasks/PWGDQ directory.
I guess we need to discuss how we want to the structure overall...

**Comment by jgrosseo** [comment]
This is not just an aesthetic question: in your case the includes like VarManager.h are currently not installed with make install because they are not found in the right place.

**Comment by iarsene** [comment]
Hi @jgrosseo,
Ok, maybe we can briefly discuss it tomorrow at the meeting.
Cheers, Ionut

**Comment by iarsene** [comment]
Hi, so after our discussion, i created the Analysis/PWGDQ. The headers are now in include/PWGDQCore and sources in src/

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
