### PR TITLE
DPL GUI: apply clang-modernize to imported ImGUI

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
I will still try to move it out, but this should at least keep the linter happy.

**Comment by ktf** [comment]
@davidrohr

**Comment by davidrohr** [comment]
Thx, will test it later

**Comment by ktf** [comment]
macOS build tested locally. Merging.

**Comment by davidrohr** [comment]
@ktf : I just rechecked the code-checker. Many errors are gone, but there is still plenty of errors in the DebugGUI (see attached log)
[errors.txt](https://github.com/AliceO2Group/AliceO2/files/3193895/errors.txt)

**Pull request merged**
