### PR TITLE
Add missing protection for ROOTCLING

### PR DESCRIPTION
**Pull request by wiechula**

### CODE REVIEW

**Review by davidrohr — APPROVED** [review]
Fine with me if it passes the CI

**Comment by chiarazampolli** [comment]
Hello @ktf , @TimoWilken , @davidrohr , 

Can this be merged, and then a new exceptional tag be made *today* for O2? I would like to test it on the grid, for tha sync reco that is supposed to start ~today.

Thanks, 

Chiara

PS thanks @wiechula !

**Comment by ktf** [comment]
I've started the build at https://alijenkins.cern.ch/job/DailyBuilds/job/AdHocO2Physics/77/

**Comment by chiarazampolli** [comment]
Thanks a lot!!
How do I know if the build ended? The link says that it started, but not much more.

**Comment by ktf** [comment]
It will become green when done. That said. I made a mistake and I need  to restart it again, given I assume you want to bump O2 and I relized that job by default bumps only O2Physics

**Comment by ktf** [comment]
It will become green when done. That said, I made a mistake and I need  to
restart it again, given I assume you want to bump O2 and I relized that job
by default bumps only O2Physics

Ciao,
Giulio

**Comment by ktf** [comment]
New build https://alijenkins.cern.ch/job/DailyBuilds/job/AdHocO2Physics/78/

Ciao,
Giulio

**Pull request merged**
