### PR TITLE
Fix for ambigous overload (Ubuntu 18.04)

### PR DESCRIPTION
**Pull request by pzhristov**

### CODE REVIEW

**Comment by davidrohr** [comment]
Can you send me the error messages you get during compilation without this PR?
Since I cannot reproduce it, and don't want to set up a Ubuntu VM just for it.

**Comment by pzhristov** [comment]
I will send it this evening, it is on a machine I do not have access now.

**Comment by davidrohr** [comment]
@pzhristov : could you check if #8549 solves the issue for you?

**Comment by pzhristov** [comment]
Replaced by #8549.

**Pull request closed without merging**
