### PR TITLE
Fix for PVertexer stall + debug reco method

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
@mfasDa the `calib-emcalchannel-calibration` crashes FST in different PRs, https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/AliceO2/9651/9563977a39bdfda5a52570678e63a567796b02fa/build_O2_fullCI/fullLog.txt
```
[36614:calib-emcalchannel-calibration]: [21:01:21][INFO] GRP ECS object updated
[36614:calib-emcalchannel-calibration]: [21:01:21][INFO] Caching in 140417102331728 ptr to GLO/GRPECS/0 (0x52d6120)
[36614:calib-emcalchannel-calibration]: [21:01:21][INFO] CTP/ORBITRESET/0
[36614:calib-emcalchannel-calibration]: [21:01:21][INFO] orbit reset time updated to 1550600800000
[36614:calib-emcalchannel-calibration]: [21:01:21][INFO] Caching in 140416996749616 ptr to CTP/ORBITRESET/0 (0x600f5f0)
[36614:calib-emcalchannel-calibration]: *** Program crashed (Segmentation fault, FPE, BUS, ABRT, KILL)
[36614:calib-emcalchannel-calibration]: Backtrace by DPL:
[36614:calib-emcalchannel-calibration]:     /lib64/libc.so.6: ()
[36614:calib-emcalchannel-calibration]:     /sw/slc8_x86-64/O2/9651-slc8_x86-64-local1/lib/libO2DetectorsBase.so: o2::base::TFIDInfoHelper::fillTFIDInfo(o2::framework::ProcessingContext&, o2::dataformats::TFIDInfo&)
[36614:calib-emcalchannel-calibration]:     o2-calibration-emcal-channel-calib-workflow() [0x454d27]
```
Could you check ?

Also, the `qc-task-EMC-CellTask ` tries to extract CCDB objects from `http://localhost:8084`, e.g.
```
6664:qc-task-EMC-CellTask]: [21:01:22][ALARM] Curl request to http://localhost:8084/EMC/Calib/BadChannelMap/1660770082812/ failed with result 7, response code: -1
[36664:qc-task-EMC-CellTask]: [21:01:22][ALARM] Curl request to http://localhost:8084/EMC/Calib/TimeCalibParams/1660770082813/ failed with result 7, response code: -1
```
which is the host to be used for the FLP/EPN processing only, otherwise http://alice-ccdb.cern.ch should be used.

@sevdokim the same problem is for 
```
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] Retrieving CPV/Calib/Gains directly from CCDB
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][ALARM] Curl request to http://localhost:8084/CPV/Calib/Gains/1660770081164/ failed with result 7, response code: -1
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] failed to retrieve CPV/Calib/Gains
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] Retrieving CPV/Calib/BadChannelMap directly from CCDB
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][ALARM] Curl request to http://localhost:8084/CPV/Calib/BadChannelMap/1660770081165/ failed with result 7, response code: -1
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] failed to retrieve CPV/Calib/BadChannelMap
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] Retrieving CPV/Calib/Pedestals directly from CCDB
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][ALARM] Curl request to http://localhost:8084/CPV/Calib/Pedestals/1660770081166/ failed with result 7, response code: -1
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] failed to retrieve CPV/Calib/Pedestals
```

**Comment by shahor02** [comment]
failures unrelated, merging

**Comment by mfasDa** [comment]
@shahor02 For the calibration here is our CCDB upload request: https://alice.its.cern.ch/jira/browse/O2-3116
 
For the QC I guess it is taking the qc config inside QualityControl that was created long time ago for development, where we were using the local CCDB and local QCG for testing and development. Indeed it should now use the production CCDB for calibration parameters - I will take care of it.

**Comment by shahor02** [comment]
@mfasDa are you sure calib-emcalchannel-calibration crash is due to the missing object? Usually in this case we have a corresponding error logged by the CcdbApi.

**Comment by mfasDa** [comment]
@shahor02 I see a different problem in the calib-emcalchannel-calibration which should be trivial to fix, which I suspect the reason for the full CI crash

**Comment by sevdokim** [comment]
hello @shahor02 
is this problem still in place for cpv qc in FST?
```
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] Retrieving CPV/Calib/Gains directly from CCDB
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][ALARM] Curl request to http://localhost:8084/CPV/Calib/Gains/1660770081164/ failed with result 7, response code: -1
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] failed to retrieve CPV/Calib/Gains
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] Retrieving CPV/Calib/BadChannelMap directly from CCDB
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][ALARM] Curl request to http://localhost:8084/CPV/Calib/BadChannelMap/1660770081165/ failed with result 7, response code: -1
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] failed to retrieve CPV/Calib/BadChannelMap
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] Retrieving CPV/Calib/Pedestals directly from CCDB
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][ALARM] Curl request to http://localhost:8084/CPV/Calib/Pedestals/1660770081166/ failed with result 7, response code: -1
[36646:qc-task-CPV-PhysicsOnEPNs]: [21:01:21][INFO] failed to retrieve CPV/Calib/Pedestals

```

**Comment by shahor02** [comment]
@sevdokim I have not seen this error since the default ccdb in O2DPG jsons was set to production one.

**Pull request merged**
