### PR TITLE
bug fix in interaction sampler for event time jitter

### PR DESCRIPTION
**Pull request by noferini**
gRandom->Gaus(mTimeBCRMS) invoked in the wrong way (1 argument has to be the mean and not the RMS). RMS moved as second argument

### CODE REVIEW

**Comment by shahor02** [comment]
Thanks @noferini for fixing my bug!

**Comment by chiarazampolli** [comment]
Ciao @ktf , 

The format check did not pass (a space was missing). We were about to correct it. Should we fix it in a new PR?

Chiara

**Comment by ktf** [comment]
Please do. Could you also add a unit test for it so that we test it in the build?

**Comment by ktf** [comment]
forget about it... I understood something different...

**Pull request merged**
