### PR TITLE
Add ShmManager utility

### PR DESCRIPTION
**Pull request by rbx**
- Starting code for the shm utility needed for R3C-646.
@davidrohr This can be already using in this form. Example config:
```
./shm-manager --shmid 1 --segments 1,1000 2,3000 --regions 1,2000 2,5000
[INFO] Created segment 1 of size 1000, starting at 0x7f3277c8e000. Locking...
[INFO] Done.
[INFO] Zeroing...
[INFO] Done.
[INFO] Created segment 2 of size 3000, starting at 0x7f3277c8d000. Locking...
[INFO] Done.
[INFO] Zeroing...
[INFO] Done.
[INFO] Created unamanged region 1 of size 2000, starting at 0x7f3277c8c000. Locking...
[INFO] Done.
[INFO] Zeroing...
[INFO] Done.
[INFO] Created unamanged region 2 of size 5000, starting at 0x7f3277c8a000. Locking...
[INFO] Done.
[INFO] Zeroing...
[INFO] Done.
^C[INFO] stopping.
[INFO] Cleaning up for shared memory id '00000001'...
[INFO] Found 2 unmanaged regions...
[INFO] Found RegionInfo with path: '', flags: 0, fDestroyed: 0.
[INFO] Successfully removed 'fmq_00000001_rg_2'.
[INFO] Found RegionInfo with path: '', flags: 0, fDestroyed: 0.
[INFO] Successfully removed 'fmq_00000001_rg_1'.
[INFO] Found 2 managed segments...
[INFO] Successfully removed 'fmq_00000001_m_2'.
[INFO] Successfully removed 'fmq_00000001_m_1'.
[INFO] Successfully removed 'fmq_00000001_mng'.
```

### CODE REVIEW

**Comment by rbx** [comment]
Fixed formatting.

**Comment by davidrohr** [comment]
Thx a lot, from the example it looks nice. Will test with the managed region in the full system test.
@ironMann : When can we expect support in DD for this?

**Comment by rbx** [comment]
To remind you what is needed on DD/DPL side (as I wrote in the [ticket](https://alice.its.cern.ch/jira/browse/R3C-646)):

DD:
```cpp
fair::mq::RegionConfig regionCfg;
regionCfg.id = 1; // the id corresponding to the region IDs set by the tool, to locate the open region instead of creating it
regionCfg.removeOnDestruction = false; // do not remove this region when it destructs.
fRegion = fair::mq::UnmanagedRegionPtr(NewUnmanagedRegionFor("channel", 0, regionSize, yourAckCallback, regionCfg));
```
In principle the code above can be the same even if workflow+DD run without this tool. The ID would then be used to create (not open) the region and `removeOnDestruction` will skip only the destruction in the destructor of `UnmanagedRegion`, but the final `Monitor::Cleanup()` will still clean everything unconditionally.

DPL & DD:
When this tool is active, both have to run with:
- `--shm-monitor false` (should already be the case, at least for DPL) to not launch shmmonitor.
- `--shm-no-cleanup true` to skip the `Monitor::Cleanup()` step when final device in a session leaves. Or whatever the equivalent is on DPL side, to actually skip shmem cleanup.
- `--shmid <id-corresponding to the shmid in the tool>` to actually find everything.

**Comment by davidrohr** [comment]
ok, thx. How does shmid work in detail? By default it is deduced from the sessionid, which normally comes from DDS?
But if I set --shmid explicitly, it overrides what comes from the sessionid?

**Comment by rbx** [comment]
> How does shmid work in detail? By default it is deduced from the sessionid, which normally comes from DDS? But if I set --shmid explicitly, it overrides what comes from the sessionid?

That's right, it overrides it for shm objects only. Devices still need session id for other purposes.

**Comment by ktf** [comment]
Can you also fix the copyright statement?

**Comment by rbx** [comment]
> Can you also fix the copyright statement?

Done.

**Comment by ktf** [comment]
Copyright is actually correct now, it's the test that was sticking to 2020. Fixed.

**Comment by davidrohr** [comment]
Hi @rbx : I have one question for the usage:
at some point you had added a feature to "reinitialize" the shm segment.
We need a way to do that in between.
If we run one workflow, and it fails somehow, it might leave messages in the segment, correct?
So before we start the next workflow, we should get rid of all messages in there.
Is that already foreseen? Perhaps I just missed it?

**Comment by rbx** [comment]
This line does the "soft reset": https://github.com/AliceO2Group/AliceO2/pull/7960/files#diff-4bd4b5fb9352adb5460d9cdff3697bbf396c0e04db4cfefde633f193316f0d48R100.
It is not called anywhere, but you can extend the tool and call that as a reaction to some signal/message/input. You could even make a separate executable and call it from there, as long as all the ids stay the same it should be fine to do so. Or the same executable with a boolean switch - `ShmManager --shmid <id> --soft-reset`, which would only call the soft reset.

I would only call soft reset when you have more or less error-free shutdown - which can still leave buffers in shm if there were orphaned messages in the IPC queues.

But if you get a real crash, all kinds of things could be wrong, including in management parts of shared memory, then I would only do a full reset: https://github.com/AliceO2Group/AliceO2/pull/7960/files#diff-4bd4b5fb9352adb5460d9cdff3697bbf396c0e04db4cfefde633f193316f0d48R103-R108. Full reset cannot be in a separate executable in this case, then "the state" in this tool is no longer correct. For full reset you'll need either some signal, or just restart the tool with the same parameters.

**Comment by davidrohr** [comment]
OK, I tested the tool with a DPL workflow (just a single workflow, so no cleanup needed in between) and it seems to work as expected, very nice. workflow startup is much faster as expected.
I couldn't test with DataDistribution, since it lacks the feature still.
Giulio already merged it, so nothing left to do.

We need one more additional feature:
We must have per-segment-id control over the NUMA policy, to bind to particular NUMA domain or to interlaved memory.
I'll comment everything on the jira ticket.

Thx for the tool. Good to have finally some progress here!

**Comment by ktf** [comment]
This breaks the EPN builds:

https://alijenkins.cern.ch/job/DailyBuilds/job/DailyO2Dataflow/395/console

because the flp-suite branch we are using does not yet pick-up the latest FairMQ. @vascobarroso @awegrzyn do you plan to do so for the next version?

@rbx ~can we replace fairmq/shmem/Common.h by something equivalent which is backward compatible?~ Actually the file seems to be there since ever. Maybe it needs to be installed?

**Comment by davidrohr** [comment]
I'll add FairMQ to the overrides for the EPN builds temporarily, FMQ will be bumped on the FLPs on Monday, and in the meantime we don't need to update software on the EPNs anyway.

**Comment by awegrzyn** [comment]
@ktf Yes, FLP Suite branches are always based on master.

**Comment by ktf** [comment]
@davidrohr ok

**Comment by rbx** [comment]
> @rbx ~can we replace fairmq/shmem/Common.h by something equivalent which is backward compatible?~ Actually the file seems to be there since ever. Maybe it needs to be installed?

This file was not installed before because it is an implementation detail. Although it is still a detail now, some of the shmem headers are now public, to provide shmem-specific APIs needed by this tool, including this header.

**Pull request merged**
