### PR TITLE
Rdev compressor devel

### PR DESCRIPTION
**Pull request by preghenella**
This PR brings the new TOF raw data format, updated to the latest DRM firmware.

It also updates the compression algorithm, more specifically in the following points:
- Split compressor main algorithm in multiple routines
- Adapt compressor for CONET data processing
- New definition of diagnostic bits based on enum + new checks
- Use pointers for data summary 
- Use decoding macros from RawDataHeader.h
- Make compressor a template to handle multiple RDH versions
- Write TDC errors in compressed stream

### CODE REVIEW

**Comment by preghenella** [comment]
Hello @ktf ,
I am not sure if you are the right person to ask, please let me know whom to ask in case.

This PR makes some changes in the `o2` that make the some `QualityControl` TOF code not to compile. This is expected and a modification in the `QualityControl` will have to come.

On the other hand, this is blocking the PR because one of the checks apparently is trying to build `QualityControl` and fails because of those compilation errors.

How can this situation be resolved?
Changes in `QualityControl` cannot be put before this PR is merged.

Thanks for help,
Roberto

**Comment by preghenella** [comment]
it is not clear to me why `build/o2/macos` did not pass the test.
I cannot see any errors in the log.

the other case is `build/O2/o2` that fails while building `QualityControl`.

Can someone please advice?
@noferini , what are we supposed to do here?

Thanks

**Comment by ktf** [comment]
@preghenella macOS did pass the test. 
@preghenella do I understand correctly that the class has been renamed? One possibility is:

```C++
#include "Framework/CheckTypes.h"

using ActualDecoderBase = std::conditional_t<is_type_complete_v<struct OldDecoderBase>, OldDecoderBase, NewDecoderBase>;
```

assuming the APIs are the same. Alternatively we can just merge the two PRs at the same time.

**Comment by preghenella** [comment]
Ciao @ktf ,
thanks. The API is slightly modified, so it is not only a matter of the base class name.
The base class was not renamed, but it has been templated.
I will get the changes in a PR for `QualityControl` and possibly we merge them at the same time.
Roberto

**Comment by preghenella** [comment]
Hello @ktf and @Barthelemy ,
I have implemented some changes in the API such that this PR will not break `QualityControl` build.
Roberto

**Comment by ktf** [comment]
Thanks. @noferini could you please review?

**Comment by noferini** [comment]
For me it is fine. All the tests using simulation were ok,
I'm going to approve.
Cheers
Francesco

**Comment by noferini** [comment]
1

**Pull request merged**
