### PR TITLE
fast implementation of atan2(y,x)

### PR DESCRIPTION
**Pull request by sgorbuno**
A fast implementation of atan2() as discussed here:
https://alice.its.cern.ch/jira/browse/ALICEHLT-221

### CODE REVIEW

**Comment by sawenzel** [comment]
I am wondering whether one could not just use the VDT fast math (that is included in ROOT)?
It is probably worth in any case to investigate and do a benchmark comparison?

**Comment by shahor02** [comment]
@sawenzel VDT gives factor 2 increase wrt atan2 https://iopscience.iop.org/article/10.1088/1742-6596/513/5/052027/pdf, this one factor ~5, see https://alice.its.cern.ch/jira/browse/ALICEHLT-221.
Also, this should work also on the GPU (though probably vdt also?)

**Comment by sawenzel** [comment]
Fair enough!

**Comment by davidrohr** [comment]
@sgorbuno : Looks pretty good, thx. Could you include `#include "GPUCommonDef.h"` and prepent 
inline float FastATan2(float y, float x) with `GPUd()`, the lambdas can stay as they are.

**Comment by sgorbuno** [comment]
@davidrohr , 
ok!  I've put the GPUdi() prefix.

**Pull request merged**
