### PR TITLE
switch the variable initialization order

### PR DESCRIPTION
**Pull request by zhaomr13**

### CODE REVIEW

**Review by ktf — DISMISSED** [review]

**Comment by zhaomr13** [comment]
@ktf @shahor02 
 Giulio asked me to fix the warnings in the codes. 
In principle I should fix one file in one PR. However I didn't realized this PR have not been merged and I fixed warnings in another file.  But since the changes in the two files are both minor, I think it should be safety and most easier to use this PR for these two files. 
Is it ok for you?

**Comment by ktf** [comment]
Could you please rebase the PR on top of the current dev branch?

**Comment by zhaomr13** [comment]
> Could you please rebase the PR on top of the current dev branch?

Rebased

**Review by ktf — APPROVED** [review]

**Comment by zhaomr13** [comment]
It failed on build/O2/o2-cs8, should I do something?

**Pull request merged**
