### PR TITLE
Add support for RemoteGUI

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Similar to #6964, however https://github.com/ktf/AliceO2/commit/c630e6cd7cc4695cf4b79f376421a347353f9a7f can be merged as is to support the new API in DebugGUI, which should reduce the possible issues.

**Comment by ktf** [comment]
@luigifusco can you have a look at:

```
FAILED: Framework/Core/CMakeFiles/O2lib-Framework.dir/src/DPLWebSocket.cxx.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DDPL_ENABLE_BACKTRACE -DENABLE_UPGRADES -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -DO2lib_Framework_EXPORTS -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Core/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Core/src -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Core -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Common/Utils/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/DataFormats/common/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Common/Constants/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/GPU/Common -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Logger/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Common/MathUtils/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/DataFormats/Headers/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/DataFormats/MemoryResources/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/CCDB/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Foundation/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Foundation/3rdparty/include -I/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Utilities/PCG/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/Common-O2/v1.6.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/boost/v1.75.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/Configuration/v2.6.2-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/libInfoLogger/v2.1.1-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/Monitoring/v3.8.7-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/curl/7.70.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/FairMQ/v1.4.40-local1/include/fairmq -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/FairMQ/v1.4.40-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/FairLogger/v1.9.1-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/fmt/7.1.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/ROOT/v6-24-06-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/FairRoot/v18.4.2-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/arrow/v5.0.0-alice1-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/Vc/1.4.1-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/ms_gsl/3.1.0-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/libjalienO2/0.1.3-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/RapidJSON/v1.1.0-alice2-local1/include -isystem /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/osx_x86-64/libuv/v1.40.0-local1/include -fPIC -O2 -std=c++17 -Werror -Wno-error=deprecated-declarations -O2 -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk -fPIC -std=gnu++17 -MD -MT Framework/Core/CMakeFiles/O2lib-Framework.dir/src/DPLWebSocket.cxx.o -MF Framework/Core/CMakeFiles/O2lib-Framework.dir/src/DPLWebSocket.cxx.o.d -o Framework/Core/CMakeFiles/O2lib-Framework.dir/src/DPLWebSocket.cxx.o -c /System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Core/src/DPLWebSocket.cxx
/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Core/src/DPLWebSocket.cxx:125:13: error: enumeration value 'Control' not handled in switch [-Werror,-Wswitch]
    switch (opcode) {
            ^
/System/Volumes/Data/build/ci_checks/alice_ci_0/o2/sw/SOURCES/O2/7000/0/Framework/Core/src/DPLWebSocket.cxx:125:13: note: add missing switch cases
--
```

why is it unhandled?

**Comment by luigifusco** [comment]
leftover, can be removed

**Comment by ktf** [comment]
You mean the Control enum?

**Comment by luigifusco** [comment]
Yes

**Comment by ktf** [comment]
This is finally ready to go after I understood (and fixed) the last couple of crashes on my laptop. DebugGUI v0.6.3 is required for macOS not to die when using this.

**Comment by ktf** [comment]
Merging this so that @Zowlyfon can rebase on it.

**Pull request merged**
