### PR TITLE
Add o2 interface for TRD tracker

### PR DESCRIPTION
**Pull request by martenole**
Hi @shahor02 , hi @davidrohr 
I am trying to add the interface to O2 to the TRD tracker, but I cannot include the necessary headers.
The build fails when trying to include DetectorsBase/Propagator.h.
I am not sure whether I am missing something in the CMake configuration or if there is another issue with the Propagator class.
The error log is attached. But as the error is found in TObject.h of ROOT it does not really help me..
[o2-build-error-trd-interface.log](https://github.com/AliceO2Group/AliceO2/files/4328618/o2-build-error-trd-interface.log)

Do you know what might go wrong?
Cheers,
Ole

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @martenole 
With https://github.com/AliceO2Group/AliceO2/pull/3150 should work.
Cheers,
 Ruben

**Comment by davidrohr** [comment]
Hi @martenole , looks good. You should add explicit template instantiations at the end of GPUTRDTracker.cxx, like
```
template class GPUTRDTrack_t<trackInterface<GPUTPCGMTrackParam>>;
```
in GPUTRDTrack.cxx, and perhaps I'd also rename GPUTRDTracker to GPUTRDTracker_t and create 2 typedefs for GPUTRDTracker and GPUTRDTrackerGPU? That might make it more readable from the outside.

**Comment by martenole** [comment]
Hi @davidrohr ,
thanks! The explicit instantiations were already there.
I have added the two typedefs and with the macro the tracking is running now.

But at the moment the standalone build fails, because of an invalid use of an incomplete type:
/home/oschmidt/alice/O2/GPU/GPUTracking/TRDTracking/GPUTRDTrack.h:42:7: error: invalid use of incomplete type ‘class o2::gpu::trackInterface<o2::track::TrackParCov>’

I don't know at the moment how to fix this. If I remove the additional typedef of the o2::track::TrackParCov as TRDBaseTrack in GPUTRDDef.h and analog for the propagator and remove the explicit template specializations which would be duplicated in that case then it works. So maybe I need another #ifdef(STANDALONE) #else in my code? Because in case of the standalone version only the GPU data types are needed, or not?

**Comment by davidrohr** [comment]
@martenole : You are right, this needs an additional `#ifdef`, at least I don't see a different way. Attached is a patch that adds this + some other minor fixes.

One more comment: The TRD tracking class on GPU is called `GPUTRDTrackerGPUTypes`, I assume it should be `GPUTRDTrackerGPU` and this is just a typo?

[trd-interface.patch.gz](https://github.com/AliceO2Group/AliceO2/files/4365450/trd-interface.patch.gz)

**Comment by martenole** [comment]
Thanks a lot @davidrohr I'll take a look at the patch later.

Concerning `GPUTRDTrackerGPUTypes`: this is not a typo, because the class `GPUTRDTrackerGPU` already exists. I think you use it for the kernel definition of the GPU tracking. Or should we rename that class instead?

**Comment by davidrohr** [comment]
Indeed, you are right :) But let's clean up this mess...
Could you rename GPUTRDTrackerGPU to GPUTRDTrackerKernels, and then you can use GPUTRDTrackerGPU for your class. That makes it much more consistent in my opinion.

**Comment by martenole** [comment]
Hi David,
thanks a lot for the patch! For me now both O2 and standalone builds work well. Only AliRoot fails at the moment, but I think that is not TRD tracking related. The first error I got is in GPUChainTracking.cxx:41 the header Digit.h is not found.
Cheers,
Ole

**Comment by davidrohr** [comment]
@martenole : I also tested AliRoot. Some fixes for AliRoot were already in the patch I sent you. There are more fixes for non-trd related stuff for AliRoot in my dev branch. Even on top of that, the GPU version of AliRoot is still broken by the TRD changes, but I didn't check in detail yet what happens.
If you apply all my patches, you should be able to run in AliRoot on CPU.

**Comment by davidrohr** [comment]
@martenole : I checked the new version, and it doesn't cause any problems for me, so I think it can be merged.
Just 2 points:
-I'll merge #3174 soon, which will cause a conflict with the ignored root macros in this PR, you'll have to resolve that quickly.
- I'll also post here a fix for the AliRoot GPU compilation soon, and I think it would be best if you include it here.
Then we have to wait for the CI again, then we can merge it.

**Comment by davidrohr** [comment]
@martenole : the other PR is merged, could you solve the conflict and apply this small patch in addition:
```
diff --git a/GPU/GPUTracking/Base/GPUConstantMem.h b/GPU/GPUTracking/Base/GPUConstantMem.h
index ff74d134bab..25e0c2f8b26 100644
--- a/GPU/GPUTracking/Base/GPUConstantMem.h
+++ b/GPU/GPUTracking/Base/GPUConstantMem.h
@@ -30,10 +30,12 @@ namespace gpu
 class GPUTPCGMMerger
 {
 };
-class GPUTRDTrackerGPU
+template <class T, class P>
+class GPUTRDTracker_t
 {
   void SetMaxData(const GPUTrackingInOutPointers& io) {}
 };
+typedef GPUTRDTracker_t<GPUTRDTrackGPU, GPUTRDPropagatorGPU> GPUTRDTrackerGPU;
 } // namespace gpu
 } // namespace GPUCA_NAMESPACE
 #endif
```
Cheers
David

**Comment by davidrohr** [comment]
weird, didn't have this OpenCL failure locally, will retry, and then provide another patch

**Comment by davidrohr** [comment]
@martenole : There was a problem with incremental buils locally before, therefore I didn't see it. The attached patch should fit the OpenCL compilation:
[trd-opencl.patch.gz](https://github.com/AliceO2Group/AliceO2/files/4375018/trd-opencl.patch.gz)

**Pull request merged**
