### PR TITLE
[DPL Analysis] Helper to create partitions in process() + extended expressions to int64_t

### PR DESCRIPTION
**Pull request by saganatt**
Hi @jgrosseo , this is the example for partitions. `groupedTracks.bindTable(tracks);` does the actual job.

For comparison with index columns I extended expression nodes to accept int64_t - @aalkin , is that OK for you?

### CODE REVIEW

**Review by jgrosseo — APPROVED** [review]
Thanks!

**Comment by aalkin** [comment]
Adding `int64_t` is fine, of course. But we use `int32_t` for index anyway.

**Comment by saganatt** [comment]
> Adding `int64_t` is fine, of course. But we use `int32_t` for index anyway.

Hm, strangely it fails for me without int64_t. It says e.g. that cannot match T = long int to any of other LiteralNode variants.

**Comment by aalkin** [comment]
> Hm, strangely it fails for me without int64_t. It says e.g. that cannot match T = long int to any of other LiteralNode variants.

True, this is not an index column but rather the index counter, that one is indeed `int64_t`. All good then.

**Pull request merged**
