### PR TITLE
Add instructions for clang-format

### PR DESCRIPTION
**Pull request by Barthelemy**
And also remove the clang-format file as it lives in a different repo

### CODE REVIEW

**Comment by Barthelemy** [comment]
Indeed, you have got a point. I feared that they would diverge but we could add a comment. Let's see if others have an opinion.

**Comment by matthiasrichter** [comment]
I think this file will be almost static so the potential for divergence is small. We can even add a test program which checks the file against the one in the upstream repository.

Actually it's a very common case for external pieces one needs in a repository. From browsing the opinions and suggestions on the web I draw the conclusion that it is best practice to preserve the consistency of the repository by a direct import and preserving the information to the upstream master repo in some way.

**Comment by Barthelemy** [comment]
Ok, so we could copy it from the CodingGuidelines repo and add a note and I would not even bother to add a check on this. As you say it is mostly static. Then we could copy it in the other repos (Configuration, etc...) and from time to time, if needed, copy the latest version.

**Comment by kouzinopoulos** [comment]
I would also prefer a copy of the configuration file to exist in the O2 repository. Else most people will probably not notice it

**Comment by Barthelemy** [comment]
Ok, thank you for the feedback. I am restoring it.

**Comment by MohammadAlTurany** [comment]
Hi Barth,
Could you resolve the conflict in this PR?
best,

Mohammad

**Comment by Barthelemy** [comment]
Sure, on it.

**Comment by Barthelemy** [comment]
it is ok now

**Pull request merged**
