### PR TITLE
Revert "Add labelled string array"

### PR DESCRIPTION
**Pull request by jgrosseo**
Reverts AliceO2Group/AliceO2#11707

### CODE REVIEW

**Comment by jgrosseo** [comment]
This will break Hyperloop. Please read carefully the first line above the enum !!!
image

**Comment by jgrosseo** [comment]
@njacazio You can redo the PR with simply reordering the enum and putting the new entry at the end. Note that this type of configurable will not be supported by Hyperloop until we implement it. I can add it to the todo list.

**Comment by njacazio** [comment]
ok thx!

**Comment by njacazio** [comment]
Hi @jgrosseo isn't there any way to spot this locally or at CI? Should I have done things differently?

**Comment by jgrosseo** [comment]
I think the only way to spot this is to read the comment above the enum... So read more code ;-)

**Comment by jgrosseo** [comment]
I missed this PR because it appeared during my vacation and then when it was revived this week I was too slow...

**Comment by njacazio** [comment]
it's ok, I triggered Anton because it was going to go stale :) thanks!

**Comment by jgrosseo** [comment]
You can now create it again and simply put the new value at the right place. I will review it then

**Comment by jgrosseo** [comment]
My lesson learned: All configurable changes have to be validated by me for Hyperloop

**Comment by ktf** [comment]
Something I already knew but I always feel too embarrassed to admit: comments in code are useless.

**Pull request merged**
