### PR TITLE
DPL: Query based input handling

### PR DESCRIPTION
**Pull request by ktf**
This refactors TimesliceIndex and DataRelayer to be based
on `DataDescriptorMatcher` for the caching logic. This
really means we now do support queries on the data, both
in terms of description and in terms of time ranges. If
we had a way to specify such queries from the InputSpec API, it should actually work out of the box or with minimal changes.

It also sports a few GUI improvements like the ability to visualise the actual input matchers and the value of the matched variables (currently only the first one will actually match to the timeslice value). 

This is based over #1447 which can be merged separately, or discarded, depending on how fast people like this one.

### CODE REVIEW

**Comment by ktf** [comment]
dpl-matchers

Obligatory screenshot.

**Comment by ktf** [comment]
@sawenzel there is a few simulation related crashes, which I think are unrelated. Can you please have a look?

**Comment by ktf** [comment]
I've pushed a new update which also has an example of how to use the new API. However I think there is some issues with Github,since the last commit should really be `04dd8aa`. Investigating.

**Comment by knopers8** [comment]
I compiled it and ran some executables, Data Sampling seems to work as before.

**Comment by matthiasrichter** [comment]
I have some observations when running the tpc reco workflow with this PR
1) it appears to be ~20% slower, but this needs to be checked with a release compilation
2) if using multiple lanes and more then one event, some cache lines are not completed anymore at the tracker, so the workflow can not process all events correctly, see picture
3) filling of the cache lines seems to be paused while in the processing callback (this is probably independent of this PR)

**Comment by matthiasrichter** [comment]
tpc-reco-workflow_pr1483

**Comment by ktf** [comment]
So, almost half of the time in the benchmark is indeed taken by sending the metrics to update the GUI. Removing `sendVariableContextMetrics()` in `DataRelayer::relay()` gives:

```
Run on (8 X 2500 MHz CPU s)
2018-11-29 10:33:00
---------------------------------------------------------------
Benchmark                        Time           CPU Iterations
---------------------------------------------------------------
BM_RelayMessageCreation        674 ns        674 ns    2075258
BM_RelaySingleSlot            3247 ns       3246 ns     426390
BM_RelayMultipleSlots         3613 ns       3612 ns     391354
BM_RelayMultipleRoutes        7003 ns       6994 ns     201188
```

This is being followed up with @awegrzyn on https://alice.its.cern.ch/jira/browse/O2-421. 

Can you check if commending out `sendVariableContextMetrics()` in `DataRelayer.cxx` gives you back the original performance? Given this scales with the number of inputs, I suspect in your example the effect is even more pronounced.

**Comment by sawenzel** [comment]
@ktf: Are these metrics also sent if the GUI is not there? Can one disable sending metrics at all?

**Comment by ktf** [comment]
What is taking time is not the sending (which is done asynchronously in general and not done when the GUI is not active), but preparing the metrics to be sent. In particular there is a mutex which is getting created a destroyed every time you do something like:

```C++
monitoring.send({"value", "key"});
```

I can for sure reduce / shortcut the number of metrics sent per message received (I already wanted to do so) and maybe disable it completely when running without the GUI, but IMHO having good observability on a message by message basis is actually nice to have, also in production. Clearly 20% overhead is not ok.

**Comment by awegrzyn** [comment]
@ktf I'll fix it today/tomorrow

**Comment by ktf** [comment]
I am away in any case until monday, so no rush.

**Comment by matthiasrichter** [comment]
here are the commands to reproduce the incomplete cache lines when running with multiple lanes
```
o2sim -n 10 -g pythia8 -j 1
digitizer-workflow --tpc-lanes 4 --skipDet ITS,FIT,MFT,TOF,EMC,HMP --TPCtriggered
tpc-reco-workflow --infile tpcdigits.root --tracker-options "cont refX=83 bz=-5.0068597793" --nevents 10 
mv tpctracks.root tpctracks_matching-inputs.root 
tpc-reco-workflow --infile tpcdigits.root --tracker-options "cont refX=83 bz=-5.0068597793" --nevents 10 --tpc-lanes 4
mv tpctracks.root tpctracks_matching-inputs_4lanes.root 
```

**Comment by ktf** [comment]
Mmm... I get a:

```
Unhandled exception reached the top of main: can not find branch TPCDigit_0, device shutting down.
```

message when trying to run with this. Any idea of what I am doing wrong?

**Comment by ktf** [comment]
Nevermind, I updated and the error went away... AFAICT everything works as expected. Can you check again with the current master + this PR?

What I see is that messages accumulate on the FairMQ queue for `tpc-tracker` which struggles to keep-up. Is that expected? Does it really make sense to parallelise the decoding step over the tracking one?

**Comment by ktf** [comment]
Ok, I managed to reproduce. However I see that behaviour only when I run the `tpc-reco-workflow` a second time. Could it be that something is wrong in the way things are written to disk?

**Comment by ktf** [comment]
I think I understand what is going on. It's indeed a race condition with the way I do the matching. To exemplify:

* A message for timeslice 0 arrives, gets assigned slot 0.
* A message for timeslice 1 arrives, gets assigned slot 1.
* A message for timeslice 0 arrives and completes slot 0. Slot 0 is now empty.
* A message for timeslice 1 arrives and gets assigned the first empty slot: slot 0.

In the end you have one message in slot 0 and one in slot 1, hence our problem. I will change the data relaying mechanism so that first I try to match against partial matches, then I match against the empty slots.

**Comment by matthiasrichter** [comment]
Very good that it is understood. Actually I had the same experience that the problem was only from the second time on when I prepared the test and started in a clean folder. I was puzzled about that. However when I did the same on a different machine, it was failing already the first trial.

**Comment by ktf** [comment]
Ok. I have a reproducer and a fix in 
https://github.com/AliceO2Group/AliceO2/pull/1483/commits/0424d08d048556d32cc2e69c576f2b346f6ac95f (which I will squash before merging). Can you please check everything works as expected now?

**Comment by ktf** [comment]
Merging this following feedback from @matthiasrichter if bugs arise, they will be fixed in a subsequent PR.

**Pull request merged**
