### PR TITLE
Clean up the documentation generation

### PR DESCRIPTION
**Pull request by Barthelemy**
It simplifies it drastically. Simply issue "make doc" to generate the doc.

https://alice.its.cern.ch/jira/browse/OCCF-15

This is only a cmake refactoring, the content is still messy.

### CODE REVIEW

**Comment by ktf** [comment]
We should probably do also the following:

- Pushing results to github pages
- Add a test for documentation generation

Can we actually have an incremental build for the doxyngen stuff?

**Comment by Barthelemy** [comment]
@ktf 
- I am not sure that cmake should push to github. Shouldn't it be a task done post PR ? 
- Could you give more details concerning the test ? I am not sure to understand. 
- I don't know for incremental build, to be checked. 

Extra question : 
- should we have an installation target ? It is easy

**Comment by ktf** [comment]
* Regarding the publishing, it should not be done by cmake, but by a separate task which we run in the background.
* Regarding the test, I was just thinking we can do "make doc" in the PR checker, if it does not take too long.
* Installation target for the docs (if they are enabled) sounds like a very good idea.

**Comment by Barthelemy** [comment]
Ok, please do not merge until I add the installation target. It should install in share/doc/AliceO2.

**Comment by Barthelemy** [comment]
it seems that I messed up. There is a commit of sandro in the middle.

**Comment by Barthelemy** [comment]
I can't believe I successfully removed the extraneous commit and squashed my 2 commits. I will add "git" to my CV ;)

Ok, I think that this can be merged.

**Comment by ktf** [comment]
Let me just check the code checker does the right thing and I will merge this.

**Comment by ktf** [comment]
This time the error is legit (i.e. coming from our current code), but not related to this PR. Merging this, and masking out the issue until we enable C++14 and actually fix it.

**Comment by Barthelemy** [comment]
@ktf As a matter of fact I am wondering if there should not have been a checker error. If the documentation is not generated by `make doc` prior to `make install` I get an error on my setup. 
Sorry for not noticing before. 

I will prepare a fix and make a new PR. 

Do you have an idea why it was not catched by the checker ? or was it ?

**Pull request merged**
