### PR TITLE
DPL: add wildcards when creating matchers via DataDescriptorQueryBuilder::parse

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 @chiarazampolli this is at least part of the puzzle. It will allow you to create InputSpecs which match description and subspec simultaneously via something like:

```
inputs = {
  {DataDescriptorQueryBuilder::parse("header:CALH")},
  {DataDescriptorQueryBuilder::parse("payload:CALP")}
}
```

it still requires WorkflowSerialization.cxx to handle it correctly, but I should be able to get it later this evening (I need to take the day off).

**Comment by shahor02** [comment]
thanks, can you make it work also for outputs?

**Comment by chiarazampolli** [comment]
So this will take any pairs that have the data origin "CALH" and "CALP", and then same description and subSpec, right?

**Comment by ktf** [comment]
Yes.

**Comment by ktf** [comment]
@shahor02 this should work also for outputs, what do you get?

**Comment by shahor02** [comment]
will check later this evening

**Comment by ktf** [comment]
The correct syntax is actually:

```
DataDescriptorSpec{
{
  Inputs{DataDescriptorQueryBuilder::parse("header:CALH;payload:CALP")},
  ...
}
}
```

It however needs some fix in workflowSerialization.cxx, as I said. Looking into it.

**Comment by shahor02** [comment]
@ktf : It fails
````o2-calibration-data-generator-workflow --lanes 10 --mean-latency 1000000 --max-timeframes 500 | o2-calibration-lhc-clockphase-workflow --tf-per-slot 10| o2-calibration-ccdb-populator-workflow --ccdb-path localhost:8080 
Invalid workflow: No matching output found for <matcher query: (and origin::CLW (and description:$1 (and subSpec:$2 (just startTime:$0 ))))>. Candidates:
-DPL/ENUM/2564289612
-TOF/DATASIZE/0
-TOF/CALIBDATA/0
-CLP/TOF_LHCphase
-CLW/TOF_LHCphase

````
i.e. ``CLW/TOF_LHCphase`` was not matched to ``CLW``

The test branch with my code + your commit from this PR is https://github.com/shahor02/AliceO2/tree/pr_clb1.
The inputs and outputs are defined here:
https://github.com/shahor02/AliceO2/blob/92147a54c67f5a220c736d58726b12f0c2ba10e6/Detectors/Calibration/workflow/CCDBPopulatorSpec.h#L81
https://github.com/shahor02/AliceO2/blob/92147a54c67f5a220c736d58726b12f0c2ba10e6/Detectors/TOF/calibration/testWorkflow/LHCClockCalibratorSpec.h#L107-L108

For the wildcarded output: how the ``DataDescriptorQueryBuilder::parse(...`` can be used for the OutputSpec if it returns InputSpec?

**Pull request merged**
