### PR TITLE
Force TOF cluster to be messageable

### PR DESCRIPTION
**Pull request by shahor02**
And use span instead of the vector to retrieve clusters from DPL input

### CODE REVIEW

**Comment by martenole** [comment]
Hi @shahor02 ,
thanks a lot. Just to let you know I took this from the TOF `RecoWorkflowSpec.cxx` which at the moment also does a copy of the input clusters (and also tracks) which could be avoided now.
Cheers,
Ole

**Comment by shahor02** [comment]
@martenole yes, in the writer it is legitimate: one should use a vector to feed it to TTree branch (which cannot take spane). 
But [here](https://github.com/AliceO2Group/AliceO2/blob/e584a12b21ab54d297a016157922cedd3e204b4e/Detectors/GlobalTrackingWorkflow/tofworkflow/src/RecoWorkflowSpec.cxx#L66-L67) both tracks and clusters should be fetched by a span rather than the vectors, pinging to @noferini

**Comment by noferini** [comment]
Hi,
the suggestion is to propagate the same change (vector to span) also to the tof RecoWorkflow.
It is fine with me. How to proceed? Shell I wait this PR is merged and then open a new one?

**Comment by shahor02** [comment]
@noferini yes, you should way this one to be merged.

**Pull request merged**
