### PR TITLE
Sanitize metadata keys, avoiding forbidden characters

### PR DESCRIPTION
**Pull request by chiarazampolli**
@sawenzel , @costing

### CODE REVIEW

**Comment by costing** [comment]
Ciao Chiara,

I'm of two minds about this. It's good to avoid problems later on, but it silently modifies what the user has passed, so that `my key` becomes `mykey` (if I understand it correctly). But from then on they would have to use `mykey` in all queries instead of the original string. Wouldn't it be better to throw a fatal error in this case and force a correct, consistent string to be used in both setting and retrieving later on?

Cheers,

.costin

**Comment by chiarazampolli** [comment]
I don't have a strong opinion, I was asked if it was possible to fix this on the framework side. 
If the query will be done with the wrong key, then the object won't be found, and there will be fatal (unless disabled).

**Comment by ktf** [comment]
Objects won't be found unless there is a matching key without the forbidden characters. IMHO this is dangerous, I would simply throw / FATAL if the key is considered to contain invalid characters.

**Comment by chiarazampolli** [comment]
> Objects won't be found unless there is a matching key without the forbidden characters. IMHO this is dangerous, I would simply throw / FATAL if the key is considered to contain invalid characters.

I don't understand the objection: if the key that is passed is different from the one in CCDB, the object will not be found, and the code will have to be fixed. 
What you mean is that you prefer that even before that the user notices the wrong characters, while uploading the object, right? But this could also break the calibration workflow if the wrong key goes in by mistake. 

Anyway, I don't have a strong preference, I can change that there is fatal if there is a match instead of a replacement of the key. 
Should I do this, or we wait for the S&C meeting to see if there are further feedback?

**Comment by sawenzel** [comment]
One could still offer this function to the user, so that one sanitizes before calling CcdbApi??

**Comment by chiarazampolli** [comment]
@sawenzel , do you mean as an optional feature?

**Comment by costing** [comment]
As there are other potential clients to ccdb, there is no guarantee that all calls would be sanitized via this utility. 

I am in favor of the fatal error in case of malformed strings. This would be caught immediately in the first test that the user will perform and corrected even before committing it.

I'll add a similar check on the server side, to reject uploads when invalid metadata keys are passed. That doesn't replace this functionality as an HTTP error code is too obscure to the user, the explicit error message is good to have.

**Comment by jgrosseo** [comment]
I am also in favour of fatal in case of invalid strings.

**Comment by chiarazampolli** [comment]
Agreed, i will change to fatal, then.

thanks for the feedback!

**Comment by chiarazampolli** [comment]
Fatal implemented, is this ok?

**Review by sawenzel — DISMISSED** [review]

**Comment by sawenzel** [comment]
We have a small code checker complaint: `/sw/SOURCES/O2/8462-slc8_x86-64/0/CCDB/src/CcdbApi.cxx:1674:39: error: escaped string literal can be written as a raw string literal [modernize-raw-string-literal]`

**Comment by chiarazampolli** [comment]
@sawenzel , thanks, it should be fixed.

**Comment by chiarazampolli** [comment]
Hello, 

Any further comment, or can this be merged?

Chiara

**Comment by chiarazampolli** [comment]
Hello, 

Can we merge this?

Chiara

**Review by costing — APPROVED** [review]

**Comment by chiarazampolli** [comment]
No useful logs in the reported errors... The PR was green (unless I remember wrong) this morning.

**Comment by shahor02** [comment]
This happened with a few PRs today, looks like a few builders failed to start the job. Merging

**Pull request merged**
