### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@teo can you please confirm you do not actually need the Cmake config related change?

**Comment by teo** [comment]
> @teo can you please confirm you do not actually need the Cmake config related change?

AFAICT I do. By using `find_package(Protobuf REQUIRED)` instead of `find_package(protobuf CONFIG REQUIRED)`, we would end up with CMake's `FindProtobuf`.

Unfortunately, in order to have correct transitive deps with gRPC (and avoid a whole bunch of other problems with gRPC's old Makefile that required us to patch it), we need to build gRPC with CMake, and in order to build gRPC with CMake we also need Protobuf built with CMake. This way all the `*Config.cmake` are generated and used properly, and we don't need to carry around a `FindGRPC.cmake`.

The downside is that Protobuf built with CMake yields different target names compared to CMake's `FindProtobuf`, which makes us incompatible with system Protobuf as long as the latter is built with legacy Automake. On CC7 system Protobuf is very old, so we need to build our own anyway. Beyond target names, generator functions are also different between `FindProtobuf` and Protobuf built with CMake.

**Comment by ktf** [comment]
Ok, but then we should remove the `prefer_system` option for protobuf, because at the moment it breaks if it finds a compatible protobuf on the system which was built with autotools (like basically any non-ALICE build of protobuf). Could you take care of that?

**Comment by teo** [comment]
@ktf Sure thing.

**Comment by teo** [comment]
@ktf https://github.com/alisw/alidist/pull/1601

**Comment by ktf** [comment]
Merging this so that we can go forward with the new FairMQ, without the deprecated API.

**Pull request merged**
