### PR TITLE
Event filter: Add first implementation of event filter for HF

### PR DESCRIPTION
**Pull request by fgrosa**
This PR implements the first version of the event-filtering task for HF observables. Currently it supports the selection of events containing high-pT charm hadrons and with beauty hadrons. Please feel free to comment @mpuccio @strogolo @ginnocen @vkucera

### CODE REVIEW

**Comment by strogolo** [comment]
Hi @fgrosa,
I just had a quick look to your PR and I'm just wondering if you can create a folder PWGHF inside EventFiltering and move your code there. The general plan that @mpuccio and myself discussed is to have one directory per PWG and commit the related code inside it.

I'll have a closer look to the PR later on.

Thanks,
Stefano

**Comment by fgrosa** [comment]
> Hi @fgrosa,
> I just had a quick look to your PR and I'm just wondering if you can create a folder PWGHF inside EventFiltering and move your code there. The general plan that @mpuccio and myself discussed is to have one directory per PWG and commit the related code inside it.
> 
> I'll have a closer look to the PR later on.
> 
> Thanks,
> Stefano

Done!

**Comment by vkucera** [comment]
> > Hi @fgrosa,
> > I just had a quick look to your PR and I'm just wondering if you can create a folder PWGHF inside EventFiltering and move your code there. The general plan that @mpuccio and myself discussed is to have one directory per PWG and commit the related code inside it.
> > I'll have a closer look to the PR later on.
> > Thanks,
> > Stefano
> 
> Done!

If there are going to be PWG directories outside `Analysis/Tasks/`, the respective reviewers should be added in `CODEOWNERS`.

**Comment by mpuccio** [comment]
Hi @vkucera, for the CODEOWNERS it is something that we will discuss in the trigger coordination (as you can see not even myself or @strogolo are officially reviewers). Anyway, we will also discuss with the PWG conveners how to structure this.

**Pull request closed without merging**
