### PR TITLE
Fix parsing for InputSpec with DataOrigin only

### PR DESCRIPTION
**Pull request by shahor02**
@ktf this fixes the problem reported by @chiarazampolli and @peressounko : addition of the fake `CLP/PEDDIFFLG` input to CCDB populator.

### CODE REVIEW

**Comment by ktf** [comment]
What was the actual problem? having the subspecification?

**Comment by chiarazampolli** [comment]
Yes, and two conditions were fulfilled.

**Comment by shahor02** [comment]
Actually, after creation of the inputSpec for the DataOrigin only, because of the lack of the `else` it was creating extra inputs with DataDescription of the previous iteration (although the hasDescription is false).

**Comment by chiarazampolli** [comment]
Yes, this is what I meant, that 2 InputSpecs were created since 2 conditions were fulfilled.

**Pull request merged**
