### PR TITLE
Fill PDG code database before event generation

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by davidrohr** [comment]
@ktf @TimoWilken @sawenzel : There seems to be a general problem with the codechecker if I understand correctly:
```
## Begin sw/BUILD/o2checkcode-latest/log
++ cp /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5082-1/compile_commands.json .
+++ python -c 'import json,sys,os; sys.stdout.write( os.path.commonprefix([ x["file"] for x in json.loads(open("compile_commands.json").read()) if not "G__" in x["file"] and x["file"].endswith(".cxx") ]) )'
/mnt/mesos/sandbox/sandbox/o2-fullci/sw/SPECS/slc8_x86-64/o2checkcode/1.0-38/o2checkcode.sh: line 10: python: command not found
++ O2_SRC=
## End sw/BUILD/o2checkcode-latest/log
```
This fails in all full-ci builds. I believe it does not find python in the CC8 container.

**Comment by davidrohr** [comment]
@ktf @TimoWilken @sawenzel @anerokhi : The fix alisw/alidist#2719 by @ktf fixed the first python3 problem, but there are more, since O2CodeChecker itself uses python.
E.g. `O2CodeChecker/utility/ThinCompilationsDatabase.py` starts with `#!/usr/bin/env python`.

I am not fully sure what we are supposed to do. Do we suppose that python 3 is always available now, and we always use the python3 command instead of python. Could you clarify, then I think I can fix this easily. Just want to be sure this is the right approach. I am also wondering why there is no python symlink to the current python version in the CC8 container, but anyway.

**Comment by TimoWilken** [comment]
@davidrohr (CC: @ktf) CC8 [intentionally][redhat] doesn't include `/usr/bin/python` by default. I don't think I can change the docker container that the fullCI script runs in, but you should be able to (it's `davidrohr/slc8-gpu-builder` on dockerhub). If you'd like to make python3 the default on the fullCI build containers, use:
```bash
alternatives --set python /usr/bin/python3
```
in the docker container's provisioning script. Note: currently, the CC7 builders have `python -> python2`, as does the Ubuntu 18.04 builder.

I can restart the builders with the new image if you push the new image to dockerhub and tell me when.

[redhat]: https://developers.redhat.com/blog/2019/05/07/what-no-python-in-red-hat-enterprise-linux-8/

**Comment by davidrohr** [comment]
@TimoWilken (CC @ktf) : thx for the reply. Obviously I can update the GPU CI container. My question was rather what should be our policy for python? Do we want to rely on a python symlink to some version (like in CC7 / ubuntu1804 to python2), or do we want to use the python3 command explicitly? If we say we rely on the symlink, I'll update the container. If we are explicit, I'd update the CodeChecker instead.

**Comment by preghenella** [comment]
ciao @mpuccio 
this is not the right place to put

**Comment by mpuccio** [comment]
Ciao @preghenella, where could I put it?

**Pull request merged**
