### PR TITLE
GBT data decoding + related changes in ITS(/MFT)

### PR DESCRIPTION
**Pull request by shahor02**
Bunch of changes for decoding of CRU raw data from ITS (and to create such a data from MC digits).

The ``o2::ITSMFT::ChipPixelData`` object filled by ``RawPixelReader::getNextChipData()`` method (as well as DigitPixelReader...)  now contains the interaction record (orbit/bc) and trigger from the RDH.
The ROFrame counter is kept only for bwd-compatibility, should be gradually eliminated.

Sample macros:
1. to produce raw data from MC digits: ``O2/macro/run_digi2raw_its.C``
2. to decode it:  ``O2/macro/run_rawdecoding_its.C``

Other changes: the steering of the Alpide digitization parameters in the ``digitizer-workflow`` is changed to ``o2::conf::ConfigurableParam`` based ``DPLDigitizerParam``, but this is still not fully operational since the DPL at the moment does not parse key/values supplied.

For the MFT (@bovulpes ): one should adapt ``ChipMappingMFT.h`` to the new interface used by the ``RawPixelReader<ChipMapping...>``. At the moment the needed functions are dummy.

### CODE REVIEW

**Comment by shahor02** [comment]
@iouribelikov @bovulpes : I've modified ClusterizerTasks (also its-reconstruction-flow) to create and store in a trees the ROFRecord vectors and MC->ROFRecord references. Also, eliminated the FairRunAna dependency of ClusterizerTasks.
For me this PR can be merged.

**Comment by sawenzel** [comment]
There are some compiler warnings: 
```
/build/ci_checks/o2_checker_macos_o2_ci_0/sw/SOURCES/O2/1753/0/Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h:148:62: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
    printf("%lu bytes for %lu RUs processed in %lu pages\n", nBytesProcessed, nRUsProcessed, nPagesProcessed);
            ~~~                                              ^~~~~~~~~~~~~~~
            %llu
/build/ci_checks/o2_checker_macos_o2_ci_0/sw/SOURCES/O2/1753/0/Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h:148:79: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
    printf("%lu bytes for %lu RUs processed in %lu pages\n", nBytesProcessed, nRUsProcessed, nPagesProcessed);
                          ~~~                                                 ^~~~~~~~~~~~~
                          %llu
/build/ci_checks/o2_checker_macos_o2_ci_0/sw/SOURCES/O2/1753/0/Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h:148:94: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
    printf("%lu bytes for %lu RUs processed in %lu pages\n", nBytesProcessed, nRUsProcessed, nPagesProcessed);
                                               ~~~                                           ^~~~~~~~~~~~~~~
                                               %llu
/build/ci_checks/o2_checker_macos_o2_ci_0/sw/SOURCES/O2/1753/0/Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h:149:55: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
    printf("%lu hits found in %lu non-empty chips\n", nHitsDecoded, nNonEmptyChips);
            ~~~                                       ^~~~~~~~~~~~
            %llu
/build/ci_checks/o2_checker_macos_o2_ci_0/sw/SOURCES/O2/1753/0/Detectors/ITSMFT/common/reconstruction/include/ITSMFTReconstruction/RawPixelReader.h:149:69: error: format specifies type 'unsigned long' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Werror,-Wformat]
    printf("%lu hits found in %lu non-empty chips\n", nHitsDecoded, nNonEmptyChips);
                              ~~~                                   ^~~~~~~~~~~~~~
                              %llu
```

**Comment by shahor02** [comment]
@sawenzel thanks, there is something weird, initially I had "%llu", but with that on ubuntu I get an opposite message. Any idea?

````
input_line_12:345:65: warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
    printf("%llu bytes for %llu RUs processed in %llu pages\n", nBytesProcessed, nRUsProcessed, nPagesProcessed);
            ~~~~                                                ^~~~~~~~~~~~~~~
            %lu
input_line_12:345:82: warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
    printf("%llu bytes for %llu RUs processed in %llu pages\n", nBytesProcessed, nRUsProcessed, nPagesProcessed);
                           ~~~~                                                  ^~~~~~~~~~~~~
                           %lu
input_line_12:345:97: warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
    printf("%llu bytes for %llu RUs processed in %llu pages\n", nBytesProcessed, nRUsProcessed, nPagesProcessed);
                                                 ~~~~                                           ^~~~~~~~~~~~~~~
                                                 %lu
input_line_12:346:57: warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
    printf("%llu hits found in %llu non-empty chips\n", nHitsDecoded, nNonEmptyChips);
            ~~~~                                        ^~~~~~~~~~~~
            %lu
input_line_12:346:71: warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
    printf("%llu hits found in %llu non-empty chips\n", nHitsDecoded, nNonEmptyChips);
                               ~~~~                                   ^~~~~~~~~~~~~~
                               %lu

````

**Comment by iouribelikov** [comment]
@shahor02 Hi Ruben,
With this PR merged, will we be able to run in triggered readout mode ?
Cheers,
Yura.

**Comment by shahor02** [comment]
@iouribelikov No, this will require new development

**Comment by shahor02** [comment]
@iouribelikov ... I've realized that I might have answered the question you did not ask: with this PR raw data both from triggered and continuous readout can be decoded and clusterized (the cluster output will have proper ROFrecords vector, with the InteractionRecord covering every RO frame, but the old ROFrame counter will be always 0, we have to get rid of it gradually).

My previous answer was about the MC digitization, which at the moment works only in the continuous RO mode.

**Comment by iouribelikov** [comment]
@shahor02 How do we now run the cluster finder ?  If we do it from the its-reco-workflow, will it work in the triggered mode ?   (Sorry to ask all that.  I am away from my machine and cannot check it myself)

**Comment by shahor02** [comment]
@iouribelikov With the raw data one should use old ``macro/run_clus_itsSA.C`` (works also for MC digits), it will work both for continuous and triggered data.
The its-reco-workflow cannot run with raw data since it explicitly uses DigitPixelReader. More important: current its-reco-workflow topology itself is not good for the raw data: there our input is a pointer on the CRU DMA page, and the memory allocated for the CRU data may be huge (though very sparsely populated). There is no point in sending these data as a blob the reader, instead there should be a sampler (@ktf works on this) which chops the data to sub-TFs and provides a pointer to the reader.

The only change I made in the its-reco-workflow in this PR is to propagate the ROFrecords and MC2ROFrecords vectors (now stored in the trees to allow chaining in future) from digits to cluster output + use real orbit/BC record instead of the improvised ROFrame counter. This will work out of box also for the the raw data, once the RawPixelReader will be used by the flow.

**Comment by iouribelikov** [comment]
@shahor02 OK. So the macro to run the cluster finder is the run_clus_itsSA.C
I will modify the ITS tests accordingly, and try to run them.
Thank you, Ruben.
Yura.

**Comment by iouribelikov** [comment]
@shahor02 
I am still not able to run the ITS test :  Now, the CookedTracker breaks.
This should be related to getting rid of the FairRoot run style, but it may take some time to fix it.

Cannot we split this PR ?

The first part would be about the GBT decoding (as stated in the title of this PR).
We urgently need it.  It can be merged straightaway, without any interference with anything around.

The second part would then be all the rest (new navigation structures, parameters, cleaning the FairRoot dependencies, etc).  This is less urgent.  We could work on it calmly and cleanly as long as it would be needed.

Do you think such a split is technically possible ?

**Comment by shahor02** [comment]
@iouribelikov Can you explain in which condition and with what input the CookedTracker breaks? For me, the its-reco-workflow (with input from itsdigits.root) works fine. I don't understand how getting rid of the  FairRunAna legacy code could affect any result: this code managed the digitization and clusterization in the flow which is not used since long.
Note in the clusters from decoded raw data you will always have ROFrame counter at 0 (instead the ROFRecor vector should be used to separate ROFs and its orbit/BC to deduce the sequential frame ID in the cont. RO mode). Note that these navigation structers (ROFRecord and MC2ROFRecord) did not change (except that the InteractionRecord does not have anymore absolute time), but just their vectors are stored in the trees rather than directly stored in the output files. 

In any case, splitting this PR to a few parts will take days since a lot of things are interconnected, it should be easier to fix the problem once you describe it.

Cheers,
 Ruben

**Comment by iouribelikov** [comment]
@shahor02  Hi Ruben.  How did you test it ?

There are two ITS tests:
1) For the DPL running:  ITS/macros/test/run_workflows.sh
This one works (modulo the limitations you mentioned).
2) For the macro-driven running: ITS/macros/test/run_test.sh
For me, this one stopped working.  Even if it has nothing to do with the raw data.

True, it must be something trivial. So we may consider merging this PR blindly.
 (Since you say the raw data part cannot be easily extracted).
Or, we would need to have a deeper look at the second test.
(Sorry, I would be able to switch to this not before next Tuesday afternoon.)

Cheers,
Yura.

**Comment by shahor02** [comment]
Hi @iouribelikov 

For the DPL workflow: there should be no any limitations (wrt dev) for the MC, all changes are incremental (but it obviously does not work with raw data)

For the ``ITS/macros/test/run_test.sh``,  the  run_digi_its.C actually still works, since by accident I forgot to delete it. The ``run_clus_its.C`` is now removed and is overridden by the the ``run_clus_itsSA.C`` which works both with MC digits and with raw data. It obviously fails on the 
output of the fairroot-based digitization because the latter is not producing the ROFRecords navigation structures. I've explicitly made the Clusterizer to check for the presence of these structures since their absence in the digits produced by the DPL-flow means that there was an error. Note that these structures are the only way to navigate over the digits. I don't see why do we need to support the fairroot-based simulation if is not compatible with requirements and makes impossible ITS simulation with other detectors? 
Note that the Check... macros used in the ``run_test.sh`` work w/o problem with the output of the workflow.

I agree that it is worth to have a standalone digitization code (outside of the DPL), but it must comply with the format expected by digits consumers. Current DigitizerTask of ITS and MFT can be easily modified to work standalone, but I would not do this before the Digitizer itself is modified to work also in a triggered mode (this may require quite some changes in a way the Digitizer is invoked).

Cheers,
 Ruben



I don't understand why do you want to

**Comment by iouribelikov** [comment]
@shahor02  Sorry. But the second ITS test does *not* work.  It breaks with the CookedTracker.
The <O2>/macro/run_trac_its.C and CookedTrackerTask need to be cleaned of FairRoot dependencies.  

This has little connection with the main purpose of this PR, and can be fixed later.
Let's merge this PR, if everything else is ready.

Cheers,
Yura.

**Comment by shahor02** [comment]
@iouribelikov : the old chain does not work not because of the CookedTrackerTask but because the clusterization does not work with the FairRunAna-controlled chain. And this has a direct connection with the raw data decoding + making clusterization to work with new RawPixelReader: 

1. This latter has no ROFrame index and has to rely on the orbit/bc to disentangle RO frames. 

2. As a consequence, the DigitPixelReader also had to be modified to provide the same info (together with the old ROFrame index). 

3. Since the FairRunAna-based chain does not provide this info, I would either need to introduce it in this chain or to disable it. I did the 2nd since the 1st one is a waste of time: this chain does not allow full barrel digitization and must be eliminated asap.

The CookedTrackerTask itself does not have FairRunAna dependencies, the ``macro/run_trac_itc.C`` had. I've just added a commit substituting old ``macro/run_trac_itc.C`` by my private version which does not need FairRunAna. But the clusters must be obtained via ``digitizer-workflow -> run_clus_itsSA.C`` or ``digitizer-workflow -> its-reco-workflow``.
That said, the CookedTrackerTask still relies internally on the ROFrame index to separate the frames, the same is true for the CA tracker. This should be fixed asap to be able to work with raw clusters.

I think this PR should be merged asap to allow other developments.

Cheers,
 Ruben

**Comment by iouribelikov** [comment]
@shahor02  Hi Ruben,
Thank you very much for cleaning the tracking macro, and for the additional clarifications.
We will fix the second test and the rest in a separate pull request.
@sawenzel  Sandro, can you merge this PR please ?
Cheers,
Yura.

**Pull request merged**
