### PR TITLE
DPL: dummy sink should discard when any

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @shahor02 shouldn't we be doing this now? Do we actually still need counting the timeframes, as opposed to the oldest possible timeframe? I think this might affect the behaviour of the dummy sink seen in the synthetic run.

**Comment by shahor02** [comment]
I am not aware (or forgot) why we were counting them.

**Comment by ktf** [comment]
@sawenzel @shahor02 do you understand the errors  about:

```
Error in <TGeoCompositeShape::ctor>: Composite halfFixationToPipe: cannot parse expression: pipeSupportTubeCarbon
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to open /eos/alice/cond/00/40863/a8cfa540-ec84-11ec-8c09-08f1eaf024ee; Permission denied
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to open /00/35980/f849da65-bc3e-11ec-b66d-08f1eaf0250c; Permission denied
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to open /eos/alice/cond/00/35980/f849da65-bc3e-11ec-b66d-08f1eaf0250c; Permission denied
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to open /00/35980/f849da65-bc3e-11ec-b66d-08f1eaf0250c; Permission denied
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to open /00/35980/f849da65-bc3e-11ec-b66d-08f1eaf0250c; permission denied
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to open /00/35980/f849da65-bc3e-11ec-b66d-08f1eaf0250c; Permission denied
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to open /00/35980/f849da65-bc3e-11ec-b66d-08f1eaf0250c; Permission denied
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3010] Unable to open /home/aliprod/data/00/35980/f849da65-bc3e-11ec-b66d-08f1eaf0250c; permission denied
```

is it some issue with EOS / alien?

**Comment by ktf** [comment]
@costing @adriansev could you check as well if everything is ok on the JAlien side?

**Comment by costing** [comment]
If this happened last night, could you please retry the test?

**Comment by ktf** [comment]
I did, but I still have one out of three that fails. Is there some known issue?

**Comment by costing** [comment]
Hm, not that I'm aware of. Can you tell me to which service they were connecting to ?

**Comment by adriansev** [comment]
@ktf so, with alien.py i tried each SE that hosts guid f849da65-bc3e-11ec-b66d-08f1eaf0250c
and every endpoint was valid (transfer successful). So, problems related to central services or of the data servers most probable can be excluded.

**Comment by ktf** [comment]
At a third attempt everything is indeed fine.

**Comment by ktf** [comment]
@costing it looks like there is again troubles with cvmfs not being correctly mounted. This time it is on alissandra01.

**Comment by costing** [comment]
Looking into it. Some weird things in `dmesg` so far:
```
[8276538.961748] audit: type=1400 audit(1656125395.628:109): apparmor="DENIED" operation="mkdir" info="Failed name lookup - name too long" error=-36 profile="docker-default" name="/0a404d9bae23a4742b722dc267378094454ee2b4/GCC-Toolchain/build-gdb/gnulib/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdir3/confdi
```
```
[8393920.562581] O2codecheck[1560616]: segfault at 18 ip 0000000000417d84 sp 00007ffed9975890 error 4 in O2codecheck[410000+217b000]
[8393920.562591] Code: 0b 90 48 89 14 25 00 00 00 00 0f 0b 83 83 d0 26 00 00 01 48 8b 04 25 00 00 00 00 0f 0b 90 48 c7 84 24 d8 00 00 00 00 00 00 00 <8b> 04 25 18 00 00 00 0f 0b 90 48 8b 04 25 00 00 00 00 0f 0b 48 8b
```

**Comment by costing** [comment]
`service autofs restart` cured it. A couple of more funny lines in dmesg showed up as effect of this command:
```
Jun 26 14:00:49 alissandra01 cvmfs2[1462662]: (alice.cern.ch) PANIC: /home/sftnight/jenkins/workspace/CvmfsFullBuildDocker/CVMFS_BUILD_ARCH/docker-x86_64/CVMFS_BUILD_PLATFORM/ubuntu2004/build/wd_src/cvmfs/monitor.cc : 519
Jun 26 14:00:53 alissandra01 cvmfs2[1631486]: (alice.cern.ch) looks like cvmfs has been crashed previously
```
but nothing else leading up to it ...

**Comment by davidrohr** [comment]
In principel I think you are right. I think we still have to make sure that we send the dummy messages there, to make sure we account for all sinks. Then we should check with the FST with tf rate limiting. If it still works as it should, we can merge.

Kind Regards
David Rohr

**Pull request merged**
