### PR TITLE
Porting the "cooked matrix" standalone tracker

### PR DESCRIPTION
**Pull request by iouribelikov**

### CODE REVIEW

**Comment by iouribelikov** [comment]
@mkrzewic 
Hi Mikolaj,

You are perfectly right.  
But why Jenkins does not swallow Lambdas ?  Or, what else could be wrong with the commit 756fcd1 ??
Cheers,
Yura.

**Comment by mkrzewic** [comment]
@iouribelikov 
not sure, maybe it's picky about the signature? std::algorithrms you use expect bool(&,&), so maybe specifying the lambda return type would help?

**Comment by mkrzewic** [comment]
@iouribelikov 
or maybe it's that Cluster is not implicitly convertible to Double, from the docs:
'
comp	-	comparison function object (i.e. an object that satisfies the requirements of Compare) which returns ​true if the first argument is less than the second. 
The signature of the comparison function should be equivalent to the following:
 bool cmp(const Type1 &a, const Type2 &b);
The signature does not need to have const &, but the function object must not modify the objects passed to it.
The type Type1 must be such that an object of type T can be implicitly converted to Type1. The type Type2 must be such that an object of type ForwardIt can be dereferenced and then implicitly converted to Type2. 
'

**Comment by iouribelikov** [comment]
@mkrzewic  Hi again Mikolaj,

1) Is Jenkins working today at all ?    I am not getting any output !

2) IMHO, the signatures for those two initial Lambdas should be OK... 

3) The c-like casts in the Track.h are surely not bullet-proof. But, at least, they work with two different compilers I tried (gcc 4.9.2 and clang 8.0.0).  
On contrary, the initial reinterpret casts do NOT work (execute) correctly with either of those two compilers.
I agree with you: inheritance could be a solution.  But then we would need to convince Ruben, who is the author of the Track.h 

Cheers,
Yura.

**Comment by mkrzewic** [comment]
@iouribelikov the casts probabaly not work correctly due to alignment (i'm guessing here). This should work (as it actually expresses what is intended): `reinterpret_cast<const TrackPar*>(&mPC[kX]);` But i still would feel uneasy to have something like this in one of the base classes. We should convince Ruben to rethink:)

**Comment by shahor02** [comment]
Hello and Happy New Year,

Yura, 1st of all, it looks like you are using quite old version of 
Track.h, the last one, committed in
December (https://github.com/shahor02/trackO2) , does not use any 
reinterpret_cast. I thought
@mpuccio already changed to new version, perhaps he can comment.
Also, the new version is explicitly defined as "final", exactly to avoid 
inheritance (to keep the class non-virtual).
What is the reason to inherit from it instead of having as a data member?

Cheers,
  Ruben

**Comment by mkrzewic** [comment]
@shahor02 Hi Ruben, no need for inheritance, composition is fine, see my original comment. Can you update to latest version asap?
thanks,

**Comment by mkrzewic** [comment]
@shahor02 why declare this final? inheritance does not imply virtuality. We just need to keep the struct layout in mind when composing/inheriting.

**Comment by iouribelikov** [comment]
@shahor02  Hi Ruben,

I was using the version of Track.h from the dev branch of AliceO2.  
If there exist a better version, let's pull it to dev asap.

And.  Happy New Year indeed !!! :-)

Yura.

**Comment by shahor02** [comment]
Hi Mikolaj,
how can you avoid having virtual destructor for a class which can be 
used as a base one (w/o relaying on
users to remember to not destroy derived class via its base pointer)?
Cheers,
  Ruben

**Comment by shahor02** [comment]
It will take me some time to install and learn all this machinery. I any 
case, I think the
version used by @mpuccio should be pulled, let's see what Max says.

Cheers,
  Ruben

**Comment by mkrzewic** [comment]
@shahor02 Hi, indeed, this is not easy, point taken. It does get easier however when you get used to the convention that you should never destroy anything explicitly :)

**Comment by mpuccio** [comment]
Hello everyone,
I just created a pull request with the latest track class that removes the old `reinterpret_cast` madness. This pull request should be rebased on top of that.
Cheers,
Max

**Comment by shahor02** [comment]
Hi Max,
I see this is TrackPar -> TrackParCov version, did not you switch to my 
latest version
of https://github.com/shahor02/trackO2/blob/master/Track.h
TrackParBase -> TrackPar, TrackParBase -> TrackParCov ?

Cheers,
    Ruben

**Comment by iouribelikov** [comment]
@mpuccio  Ciao Max,  and happy New Year !

Thanks a lot for your pull request. I will now try my stuff with this version of Track.h 

But, we would still need to add ClassDef / ClassImp into this header ?
Or, do you know another way to make it streamable ?

Cheers,
Yura

**Comment by mkrzewic** [comment]
@iouribelikov @mpuccio Hi guys, it is OK to make the class "ROOT streamable" but if it is also to be "O2 streamable" it has to have a fixed layout - looking at the layout I think this is the intention. If this is the case we would need to go back to a raw array storage: std::array is only guaranteed to have the same *semantics* as a raw array, not necessarily the same storage layout. I would however switch to using std::array in the API: e.g. don't pass int[3] in the ctor, pass std::array<int,3>. Difference is that int[3] decays into int* and anything can be passed to such a function.

**Comment by iouribelikov** [comment]
@mkrzewic Hi Mikolaj, everybody,

Let's go step by step.

1) Pull the best available version of Track.h to the AliceO2 dev branch.  
(I would let Ruben to decide which of the versions is the best)
2) I will add ClassDef / ClassImp into the pulled Track.h,  and add it to this my pull request
3) Pull my stuff to the dev.

This will immediately give us quite some room for further ITS development !

4) Think together how to make Track  "O2 streamable".
Because, this will concern other classes as well. Which we would do in parallel with the "further ITS
development".

Everybody agrees ?

Yura.

**Comment by mkrzewic** [comment]
@iouribelikov I agree. I would make the "O2 streamable" a priority though, we are designing for O2, not for aliroot. An O2 streamable struct can be trivially stored in a root file even without the dictionary, ROOT IO is NOT the priority here though IMHO.

**Comment by iouribelikov** [comment]
@mkrzewic   Great !
Can you point me to a piece of "O2 streamable" code, please ?
I would then do that (instead of the ClassDef/ClassImp) at the step 2) ...

Cheers,
Yura.

**Comment by shahor02** [comment]
@iouribelikov, <https://github.com/iouribelikov> what is the reason of 
adding ClassDef to Track.h? The latter is supposed to be a very light-weight
class for kinematics manipulation only. The IO, customization to 
specific detector track classes is supposed to be
done via composed class, which, if streaming is needed, can be equipped 
with ClassDef.

BTW, the Track.h is non-virtual class. For such classes, if for some 
reasons the ClassDef functionalities are needed,
one should use ClassDefNV: 
https://root.cern.ch/how/how-use-classdef-preprocessor-macro

Cheers,
   Ruben

**Comment by iouribelikov** [comment]
@shahor02 
Adding ClassDef* to Track.h is the most natural (for me) way to make tracks persistent in root trees/files.
Can you suggest something better than that ?
(Custom streamers are not welcome, are they ?)

I will have a look at ClassDefNV.   Thank you, Ruben.
Cheers,
Yura.

**Comment by mkrzewic** [comment]
@iouribelikov Hi Yura,
"O2 streamable" in this case would be: no streaming needed. It should be safe memcpy to buffer on write and reinterpret_cast on read from buffer.
Of course any streaming mechanism (ROOT, protobuffers, flatbuffer, whathaveyou) is in principle supported, just a matter of performance.

In this case Ruben's suggestion might be worth exploring: keep critical base classes lean and fast (and memory contiguous), make a composite wrapper for root persistence.

**Comment by shahor02** [comment]
@iouribelikov

Hi Yura,

Track.h is an equivalent of AliExternalTrackParam in aliroot, what is 
the reason to make persistent? I.e.
what is the use case of storing the bare Track.h? I was thinking having 
the track object used in algorithms
as light as possible, while for IO it can be wrapped to TObject - based 
class, something like:

class TrackIO : public TObject
{
   public:
    TrackIO(const Track& trcSrc, ...);
    const Track& GetTrack() const {return mTrack;}
   protected:
     Track mTrack;  // kinematics
     Int_t   mNClusters; // for instance ...
     Float_t mChi2;       // ...
     ClassDef(TrackIO)
}

Cheers,
   Ruben

**Comment by iouribelikov** [comment]
@shahor02 
This is *exactly* what is done in CookedTrack (see the code of in this pull request).
And, this does *not* work without having ClassDef in Track.h...

@mkrzewic 
Sure. Sure. But I am an old guy.  First of all, I would prefer having my tracks in local files ( please :-) ),
and only then I would start learning how read them from network streams :-)

**Comment by mpuccio** [comment]
According to the [link](https://root.cern.ch/how/how-use-classdef-preprocessor-macro) that Ruben posted the ClassDef **does not** change the layout in memory of the objects (if we do not, as we must not, add the TObject inheritance) but it only adds static member functions (you can cross check the code [here](https://root.cern.ch/root/html/Rtypes.h)).
If the solution proposed by Ruben does not work, there should not be any overhead in adding the ClassDef, right?

**Comment by iouribelikov** [comment]
@mpuccio  Right !

**Comment by iouribelikov** [comment]
@shahor02 Sorry Ruben.  You might be right...
In fact, in the commit 1c8b865, I added the ClassDef to Track.h *and* modified one "pragma" in BaseLinkDef.h...  So, may be, it was that mod in LinkDef, that made my tracks properly saved.

I will now check if it works also without the ClassDef, and let you know.

Cheers,
Yura.

**Comment by shahor02** [comment]
@iouribelikov Hi Yura, after some digging and tests I confirm that the ClassDef is *not* need to make the object persistent (it is needed for TObject-based classes for other reasons).  I've just updated my 
https://github.com/shahor02/trackO2 package with test persistent class https://github.com/shahor02/trackO2/blob/master/TrackIO.h
```
class TrackIO::Track : public TObject {
 ...
  protected:
   TrackParCov mTrack;
   Float_t  mChi2;
   ClassDef(Track,1)
}
```
The only thing needed to make it able to write its TrackParCov datamember is to generate a dictionary for the latter: see https://github.com/shahor02/trackO2/blob/master/trackO2LinkDef.h
```
#pragma link C++ class AliceO2::Base::Track::TrackParBase;
#pragma link C++ class AliceO2::Base::Track::TrackParCov;
#pragma link C++ class AliceO2::Base::Track::TrackPar;
```
See also https://root.cern.ch/phpBB3/viewtopic.php?f=3&t=11917#p51767

I also tried adding ClassDefNV to TrackParBase, TrackPar and TrackParCov, there was no difference on compilation/functionality, except that the output file with single object was 400 bytes shorter, although the disk and memory size of the track object itself is exactly the same in both cases. I'll study bit more if ClassDefNV indeed reduces the file size for multiple object, at the moment I would propose not to use ClassDefNV. In any case, it does not change the class interface.

Cheers,
 Ruben

Cheers,
 Ruben

**Comment by iouribelikov** [comment]
@shahor02  Yes, Track.h works without a ClassDef inside !
But the BaseLinkDef.h still needs the right pragmas corresponding to the classes define in Track.h

@mpuccio  Max, could you please add to the BaseLinkDef.h in your pull request:
#pragma link C++ class AliceO2::Base::Track::TrackParBase+;
#pragma link C++ class AliceO2::Base::Track::TrackParCov+;
And, if I am not wrong, we can remove from the same file the line:
#pragma link C++ class AliceO2::Base::Track::Track+;

Cheers,
Yura

**Pull request merged**
