### PR TITLE
[EMCAL-918, EMCAL-1045] Treatment of page corruptions

### PR DESCRIPTION
**Pull request by mfasDa**
[EMCAL-918] Handing of corrupted trailer words
[EMCAL-1045] Handling of corrupted RDH
[EMCAL-534] Remove error message about missing trailer word
[EMCAL-834] Apply incomplete rejection per event instead of timeframe

### CODE REVIEW

**Comment by mfasDa** [comment]
Unit tests also fixed

**Comment by mfasDa** [comment]
CI errors unrelated

**Comment by shahor02** [comment]
Let's wait for the fullCI

**Comment by shahor02** [comment]
Errors unrelated, run FST locally, merging.

**Comment by davidrohr** [comment]
Thx for checking, is this needed for synchronous processing on EPNs?

**Comment by mfasDa** [comment]
@davidrohr Yes, it is connected to https://ali-bookkeeping.cern.ch/?page=log-detail&id=69881 . We get from time to time corrupted RDHs from the C-RORC, they make the process stuck. This commit handles the RDH corruption. See also request here: https://indico.cern.ch/event/1315109/

**Comment by shahor02** [comment]
yes

**Pull request merged**
