### PR TITLE
TRD: DCS Chamber Status post production update

### PR DESCRIPTION
**Pull request by leo-barreto**
## Main Goal

Apply changes to the processing of DCS Chamber Status DPs after running the processor in production. The main change is the removal of the DCSDPsRun object upload to CCDB and the setup necessary for it, as it caused unnecessary outputs in the processor log. 

Follow-up of https://github.com/AliceO2Group/AliceO2/pull/12319 .

---
Relevant JIRAs: [TRD-109](https://its.cern.ch/jira/browse/TRD-109) [O2-4658](https://its.cern.ch/jira/browse/O2-4658)

### CODE REVIEW

**Comment by leo-barreto** [comment]
@martenole One thing that I did not change but I need your opinion on.

The following lines of `workflow/TRDDCSDataProcessorSpec.h` imply that a new CCDB object of Chamber Status/CFGtag will be uplaoded at the end of stream:

```cpp
   void endOfStream(o2::framework::EndOfStreamContext& ec) final
   {
      sendDPsoutputGas(ec.outputs());
      sendDPsoutputVoltages(ec.outputs());
      sendDPsoutputCurrents(ec.outputs());
      sendDPsoutputEnv(ec.outputs());
      sendDPsoutputFedChamberStatus(ec.outputs());
      sendDPsoutputFedCFGtag(ec.outputs());
    }
```

I kept it as it is the procedure for the other objects, but it results in possible two objects for the same run (at the start, as expected, and when the end of stream is called). I am not sure how common this would be, but it does happen using simulations.

Let me know if removing this would be better, otherwise we should keep it in mind this consequence for a script that reads the object given the run metadata.

**Comment by martenole** [comment]
@leo-barreto  good point! I think we should indeed make the `endOfStream` completely empty. In simulations you see it, because you inject a certain number of inputs after which the workflow is stopped. Online the workflow is supposed to run continuously and is only restarted for maintenance reasons, e.g. if we update O2. In that case we don't really want to upload CCDB objects. Can you take care of the change?

**Comment by leo-barreto** [comment]
End of Stream is now turn off by default and can be enabled with the option `--enable-uploadAtEoS` for all objects with time-based uploads.

**Comment by martenole** [comment]
Hi @leo-barreto we had to patch the outputs to the CCDB populator in https://github.com/AliceO2Group/AliceO2/pull/12758. Could you please resolve the conflicts and update your PR?

**Review by martenole — APPROVED** [review]
Thanks, looks good! Will merge once the CI is green

**Comment by martenole** [comment]
Failures unrelated, merging

**Pull request merged**
