### PR TITLE
Implement completion policy

### LINKED ISSUE #987: O2 workflow executable quits if gui not installed and in batch mode
My workflow devices quit unexpectly before doing something useful. I tracked down the problem to the following code, which might have a wrong logic. This causes the application to exit whenever we are in batch mode (`driverInfo.batch = true`). 

```C++
  if (driverInfo.batch || guiQuitRequested || (checkIfCanExit(infos) == true)) {
          // Something requested to quit. Let's update the GUI
          // one more time and then EXIT.
          LOG(INFO) << "Quitting";
          driverInfo.states.push_back(DriverState::QUIT_REQUESTED);
          driverInfo.states.push_back(DriverState::GUI);
  }
```

Can this be please fixed urgently? (Just taking out the check on `driverInfo.batch` does the job for me but I am not sure if this is covering all the use-cases).

### PR DESCRIPTION
**Pull request by ktf**
It's now possible to specify what to do when a workflow is done.

It defaults to quitting.

Fixes #987 as well.

### CODE REVIEW

**Comment by ktf** [comment]
@matthiasrichter any idea why one would get:

```
[61405]: [17:06:22][INFO] from_source_to_sink[0]: in: nan (nan MB) out: nan (nan MB)
[61406]: [17:06:23][INFO] TST TIMER 4
[61406]: [17:06:23][ERROR] Exception caught: Attempt to extract a TMessage from non-ROOT serialised message
[61406]: 
```

? I think my change is actually unrelated to that.

**Comment by matthiasrichter** [comment]
@ktf the error looks strange, I have to think

**Comment by sawenzel** [comment]
One possibility **could** be something like this: A previous process failed to cleanup properly and still occupies a port; The new process takes the same port but fails to send on this.
[ Very hard to debug ... I was intending to make a feature request to warn about such situations ]

**Comment by ktf** [comment]
Could this be the case in which two parallel workflows are started and they cross talk?

**Comment by ktf** [comment]
yeah, I think that's it. I will take it as an opportunity to fix the hardcoded starting port.

**Comment by matthiasrichter** [comment]
I had a look to the logfile, and I can confirm that. Originally I though the log was from `test_DataAllocator`, but it comes from `test_RootTreeReader`. So indeed two processes from different workflows connected to each other.

Actually, because of this bug, we have not been running any unit test based on workflow in the CI, which runs in batch mode. That's what we see the errors now.

**Comment by ktf** [comment]
yeah. I just realised the same thing...

**Pull request merged**
