### PR TITLE
Residual aggregator avoid writing to same file for different calib slots

### PR DESCRIPTION
**Pull request by martenole**
@chiarazampolli this should avoid the error we see in the grid jobs

edit: error reported in https://alice.its.cern.ch/jira/browse/O2-3754?focusedCommentId=303494&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-303494

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @martenole , 
Thanks! So I will need to cherry-pick this for apass1, right?
Chiara

**Comment by martenole** [comment]
Yes, sorry... Will merge once the CI has passed

**Comment by chiarazampolli** [comment]
No need to say sorry, you fixed an issue!
Thanks,
Chiara

**Comment by martenole** [comment]
Tested locally, merging

**Pull request merged**
