### PR TITLE
MRRTF-177: MCH electronic mapping fixes

### PR DESCRIPTION
**Pull request by aphecetche**
Fixes to electronic mapping (St345), spotted using pseudo-efficiency plots from 2022 pilot beam data.

@aferrero2707 as stated by mail I'm no longer able to x-check using `o2-mch-cru-page-reader-workflow` (on my Mac at least) but I'm opening the PR nonetheless.

### CODE REVIEW

**Comment by aphecetche** [comment]
@TimoWilken any idea what the o2-dataflow-cs8 failure is about ?

**Comment by aferrero2707** [comment]
@aphecetche I checked and I get results equivalent to those obtained with the custom text-based mapping, so for me this one is ok for merging.

Incidentally, when the pre-clustering is linked to the `Impl4` version of the mapping the external portions of Station 2 are also ok.

**Review by pillot — DISMISSED** [review]

**Comment by aphecetche** [comment]
@aferrero2707 ok, nice. Given that the CI is kind of stuck in o2-dataflow-cs8, I'll add the fix to the linking of the pre-clustering to this PR.

**Review by pillot — APPROVED** [review]

**Comment by aphecetche** [comment]
@shahor02 seems the fullCI keeps failing for reason(s) unrelated to this PR. Can you force merge it ?

**Pull request merged**
