### PR TITLE
Fix #489: avoid comparison of float values

### LINKED ISSUE #489: unit test test_DataGenerator fails on MacOS 10.11
error: in "test_DataGenerator": check mostAbundantValue == mostProbableValue has failed;

Might be due to a comparison of floating point values? @matthiasrichter: Can you please take a look?

### PR DESCRIPTION
**Pull request by matthiasrichter**
using bin numbers instead of float values in 'equal to' check

### CODE REVIEW

**Comment by sawenzel** [comment]
@matthiasrichter: This patch does unfortunately not fix the problem on Mac (or with Clang compiler).

**Comment by sawenzel** [comment]
The problem is still present on the Mac.

**Comment by matthiasrichter** [comment]
Hi @sawenzel , I have traced it down to a property of the Poisson distribution, correctly handled now. I also have included a couple of cleanups and and corrected compilation warnings. PR should be ready to be merged now.

**Comment by sawenzel** [comment]
@matthiasrichter : Thanks. Merging.

**Pull request merged**
