### PR TITLE
First version of pedestal calibration workflow raw data -> ccdb

### PR DESCRIPTION
**Pull request by wiechula**
Includes
* modification of pedestal calibration workflow, allowing for sending data to ccdb
* modification of raw -> digits -> tracking, not fully working yet
* modularization of raw data decoding in workflows
* extension of raw data decoder to dump sync event position
* extension of raw data decoder to dump raw data per GBT link

### CODE REVIEW

**Comment by wiechula** [comment]
@shahor02 , @davidrohr , could you have a look if this can be merged? I fail to understand the problem in the failed tests. The only thing I see is something in CMake which doesn't seem to be related to my commits.

**Comment by shahor02** [comment]
Hi @wiechula 
The CMake "Manually-specified variables were not used by the project" warning is produced everywhere, so the o2 and o2-dataflow failures are not related to your PR. I would wait for fullCl then merge. Shall I squash the PR?

**Comment by wiechula** [comment]
Hi @shahor02 , thanks! The commits are only partly related, so I would prefer not to squash if possible.

**Review by shahor02 — APPROVED** [review]
failures unrelated, merging

**Pull request merged**
