### PR TITLE
Timers added for some workflows + minor fixes

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by sawenzel** [comment]
Ok. Just to add: Timings are automatically taken also in the sim_challenge.sh script. They are collected in a special file for each stage: Example: itstpcMatch.log_time.

**Comment by shahor02** [comment]
@sawenzel OK, but these is timing spent in the processingFct of the processers, discarding IO etc.

**Comment by sawenzel** [comment]
Sure.

**Comment by shahor02** [comment]
@ihrivnac Again the same problem popped up in the O2 test...

**Comment by ihrivnac** [comment]
@shahor02 ,

The warning was fixed in FairRoot a few days ago (https://github.com/FairRootGroup/FairRoot/commit/9cbedc755cdd9aacc9243e61e76e5f514469b6bc) I had already this fix in my tests, so I did not get the warnings anymore.
As there were further fixes committed after this one, (one of which we need for move to Geant4 10.6), I will test locally the current head of the  FairRoot dev, and if it works ok, make a PR. 

As the warnings make the log so huge it's not easy to see what went wrong in MT test. It could be that some detector update during the time when Geant4 MT mode was set off (and the MT test ran de facto in sequential mode) causes this error.

**Comment by shahor02** [comment]
@ihrivnac OK, thanks, merging since it is not related to my PR.

**Pull request merged**
