### PR TITLE
[MCH] [MRRTF-107] Move Digit class from MCHBase to DataFormatsMCH

### PR DESCRIPTION
**Pull request by aphecetche**
The only changes in this PR are related to the move of the MCH Digit class from MCHBase library to DataFormatsMCH library (or to the replacement of `FairMQLogger` by `Framework/Logger` to simplify MCHBase lib dependencies declaration @pillot)

### CODE REVIEW

**Comment by aphecetche** [comment]
@Barthelemy I naively believed that with my prep work https://github.com/AliceO2Group/QualityControl/pull/647 this PR would be green at first try ... I was wrong ;-) 
I wrongly assumed the CI would pick the latest and greatest QC, but apparently it's using a tagged version... So I guess I'll have to wait for a QC tag for this one to pass, is that correct ?

**Comment by davidrohr** [comment]
@aphecetche : yes, QC tests v.s. O2/dev, but O2 tests agains QC/tagged (since the latter is what is installed by default with aliBuild)

**Comment by Barthelemy** [comment]
I plan on releasing QC today or tomorrow.

**Comment by Barthelemy** [comment]
https://github.com/alisw/alidist/pull/2922

**Comment by Barthelemy** [comment]
v1.14 is out

**Comment by aphecetche** [comment]
@shahor02 this one is ready to be merged (I don't mention the review part as it's basically just moving things around, but of course feel free to actually review if you want to ;-) )

(note that once moved the digit class will undergo some changes following discussions on the CTF we had with you and that we are having with Andrea & Philippe, e.g. time will probably disappear altogether, and ADC will be shortened to 32 bits)

**Pull request merged**
