### PR TITLE
Adjust handling of decoding in CONET mode

### PR DESCRIPTION
**Pull request by preghenella**
This PR has no impact on normal running of the TOF compressor.
It adjusts the way it runs when in `conet` mode.

### CODE REVIEW

**Review by noferini — DISMISSED** [review]

**Comment by preghenella** [comment]
ciao @noferini ,
the same adjustment was done in `DecoderBase`.
Also here, the change only affects the `conet` mode.

**Review by noferini — APPROVED** [review]

**Comment by ktf** [comment]
@Barthelemy @knopers8 the ccdb test server seems to be broken again:

```
20/37 Test #14: testCcdbDatabase .................***Failed    1.69 sec
2020-10-05 04:30:00.549768     QC infologger initialized
2020-10-05 04:30:00.549804  !  [1;33mWarning - QUALITYCONTROL_ROOT is not set thus the the streamerinfo ROOT file can't be found.
Consequently, old data might not be readable.[0m
2020-10-05 04:30:00.549835     *** ccdb_create ***
2020-10-05 04:30:00.549850     Truncating data for my/task/*
2020-10-05 04:30:00.565616  !  [1;33mWarning - QUALITYCONTROL_ROOT is not set thus the the streamerinfo ROOT file can't be found.
Consequently, old data might not be readable.[0m
2020-10-05 04:30:00.565649     *** ccdb_store ***
Running 11 test cases...
2020-10-05 04:30:00.669663     Storing MonitorObject qc/TST/MO/my/task/quarantine
```

can you take a look?

**Comment by Barthelemy** [comment]
@ktf sure

**Comment by Barthelemy** [comment]
@ktf it is a spurious error because the test probably ran in parallel on two machines. I have a ticket to fix that. Will do ASAP. Sorry about that.

**Comment by preghenella** [comment]
hi @ktf 
can this be merged in the meantime?

**Pull request merged**
