### PR TITLE
Added option for MFT standalone tracking to use a cone for the LTF an…

### PR DESCRIPTION
**Pull request by AudreyFrancisco**
Added an option for the MFT standalone tracking to use a cone for track finding in the LTF and CA algos. Default is the previous cylinder option.

### CODE REVIEW

**Review by rpezzi — DISMISSED** [review]

**Review by bovulpes — DISMISSED** [review]

**Review by rpezzi — DISMISSED** [review]

**Comment by bovulpes** [comment]
Yes, still needed. Thank you.

**Comment by rpezzi** [comment]
This PR is good to go. Please merge.

**Comment by shahor02** [comment]
It has some conflicts. Could you try to rebase it to dev and resolve them?

**Review by rpezzi — DISMISSED** [review]

**Comment by rpezzi** [comment]
> It has some conflicts. Could you try to rebase it to dev and resolve them?

Sorry, Github was not showing any conflict on my end.

**Review by shahor02 — APPROVED** [review]

**Pull request merged**
