### PR TITLE
DPL: improve DataSpecUtils

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@TimoWilken can you check the issue with o2-dataflow?

**Comment by TimoWilken** [comment]
@ktf Here's the error I see:
```
[...]
Using cached build for ROOT
Using cached build for ReadoutCard
Using cached build for MCStepLogger
Using cached build for FairRoot
Using cached build for LLA
Building O2@4824
ERROR: Error while executing .../o2suite-dataflow/sw/SPECS/slc7_x86-64/O2/4824-1/build.sh on `alibuild07.cern.ch'.
ERROR: Log can be found in .../o2suite-dataflow/sw/BUILD/O2-latest-4824/log
ERROR: Please upload it to CERNBox/Dropbox if you intend to request support.
ERROR: Build directory is .../o2suite-dataflow/sw/BUILD/O2-latest-4824/O2.
ERROR: 
ERROR: Note that you have packages in development mode.
ERROR: Devel sources are not updated automatically, you must do it by hand.
ERROR: This problem might be due to one or more outdated devel sources.
ERROR: To update all development packages required for this build it is usually sufficient to do:
ERROR: 
ERROR:   ( cd O2 && git pull --rebase )
++ report_pr_errors --no-comments
++ short_timeout report-pr-errors --default master --pr AliceO2Group/AliceO2#4824@353c176245e9345b29de936d8471876fdfa9a928 -s build/O2/o2-dataflow --logs-dest ... --log-url ... --no-comments
++ timeout -s9 600 report-pr-errors --default master --pr AliceO2Group/AliceO2#4824@353c176245e9345b29de936d8471876fdfa9a928 -s build/O2/o2-dataflow --logs-dest ... --log-url ... --no-comments
Searching all logs matching: sw/BUILD/*latest*/log, sw/BUILD/*latest/log
Found:

rm -rf copy-logs && mkdir -p `dirname copy-logs/AliceO2Group/AliceO2/4824/353c176245e9345b29de936d8471876fdfa9a928/build_O2_o2-dataflow/fullLog.txt`
echo "Builing on: $(hostname) at $(date +%Y-%m-%d-%H:%M:%S)" >> copy-logs/AliceO2Group/AliceO2/4824/353c176245e9345b29de936d8471876fdfa9a928/build_O2_o2-dataflow/fullLog.txt

echo 'No logs found. Please check actual builders log in aurora.
See http://alisw.github.io/infrastructure-pr-testing for more instructions.' >> copy-logs/AliceO2Group/AliceO2/4824/353c176245e9345b29de936d8471876fdfa9a928/build_O2_o2-dataflow/fullLog.txt

Github API used 3106/5000
Last status for build/O2/o2-dataflow does not match. Updating.

Github API used 3104/5000
Github API used 3104/5000
++ LAST_PR_OK=0
```

**Comment by ktf** [comment]
Can you run with `config/debug` and try again?

**Comment by TimoWilken** [comment]
@ktf Here's the error:
```
2020-11-12@18:05:56:DEBUG:O2Suite:O2:4824: +++++ source /mnt/mesos/sandbox/sandbox/o2suite-dataflow/sw/slc7_x86-64/FreeType/v2.10.1-1/etc/profile.d/init.sh
2020-11-12@18:05:56:DEBUG:O2Suite:O2:4824: /mnt/mesos/sandbox/sandbox/o2suite-dataflow/sw/slc7_x86-64/Python/v3.6.10-77/etc/profile.d/init.sh: line 2: /mnt/mesos/sandbox/sandbox/o2suite-dataflow/sw/slc7_x86-64/FreeType/v2.10.1-1/etc/profile.d/init.sh: No such file or directory
```

**Comment by ktf** [comment]
@TimoWilken can you  shorten the "Pending — Build queued (3 ahead) on build/mesosci/prod/ci_alisw_slc7..." message so that we see the actual instance which is running? Maybe "Queued — (3 ahead) on build/mesosci/prod/ci_alisw_slc7..." is enough.

**Comment by ktf** [comment]
Builds build/O2/fullCI, builds on my mac. Merging.

**Pull request merged**
