### PR TITLE
Fixes in TOF for arbitrary TF processing

### PR DESCRIPTION
**Pull request by shahor02**
* Ensure TOF matching uses TF 1st orbit for time reference

* Do not send ROMode for GRPUpdated from CompressedDecodingTask

* Fix TOF digit fields to allow multiple TF processing
Since the TOF digit stores as BC the absolute bunch count from orbit 0, with int32 it will overflow after ~100 s. Change it uint64_t.
Also fix the orbit/bc to uint32_t / uint16_t resp.

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @noferini 

These fixes are needed to ensure that the matching works for multiple TFs, taking as the time reference the 1st orbit of the TF (at the moment I have to duplicate setting the 1st orbit from the DPL header by the orbit calculated in the HBFUtils, once the framework will propagate the orbit, the line https://github.com/shahor02/AliceO2/blob/a00a9cc172346f7165f5897ab6a572cdc8e6d6ba/Detectors/TOF/workflow/src/TOFClusterizerSpec.cxx#L68-L72 will be removed).
I had to change your Digit class as the mBC was too short to hold the absolute bunch counter.
When testing with multiple TFs, I see lot of messages like 
````
[30688:tof-compressed-decoder]: [18:22:24][INFO] Digit lost because we jump too ahead in future. Current RO window=-1
````
Is this normal?

For the record: I've checked this PR reconstructing 8 different  
````
o2-sim -n 2000 -m PIPE ITS TPC TOF -g pythia8
o2-sim-digitizer-workflow --interactionRate 100000  --shm-segment-size 12000000000
o2-its-digi2raw --configKeyValues "HBFUtils.nHBFPerTF=32" -o raw32/ITS
o2-tof-digi2raw --configKeyValues "HBFUtils.nHBFPerTF=32" -o raw32/TOF
o2-tpc-digits-to-rawzs  --configKeyValues "HBFUtils.nHBFPerTF=32" -o raw32/TPC
cat raw32/*/*.cfg > raw32/rawAll.cfg

o2-raw-file-reader-workflow --loop 3 --delay 5 --part-per-hbf  --input-conf raw32/rawAll.cfg  --configKeyValues "HBFUtils.nHBFPerTF=32" | \
o2-itsmft-stf-decoder-workflow  --configKeyValues "HBFUtils.nHBFPerTF=32" | \
o2-its-reco-workflow  --disable-mc --clusters-from-upstream  --configKeyValues "HBFUtils.nHBFPerTF=32"  | \
o2-tpc-reco-workflow --ca-clusterer --input-type=zsraw --disable-mc --output-type tracks,clusters  --configKeyValues "HBFUtils.nHBFPerTF=32" | \
o2-tpcits-match-workflow --disable-root-input --disable-mc  --configKeyValues "HBFUtils.nHBFPerTF=32" | \
o2-tof-compressor | \
o2-tof-reco-workflow --input-type raw --disable-mc  --configKeyValues "HBFUtils.nHBFPerTF=32"   --shm-segment-size 16000000000
````

**Comment by noferini** [comment]
Hi Ruben,
the message 
[30688:tof-compressed-decoder]: [18:22:24][INFO] Digit lost because we jump too ahead in future. Current RO window=-1
is in the TOF digitizer. It occurs when the digit time is lower than the one of the current readout window. I guess that this is normal if an event occurs before of the first orbit of the timeframe.
Can this happen?
Cheers
Francesco

**Comment by shahor02** [comment]
Hi @noferini 

Not sure I understood the question: the events are coming in strictly time increasing order, but obviously, there could be a situation when the particular hit time of older event I is more than the hit time of event I+1, this should be handled by the digitization to create an ordered container of digits. Then you map them on the set of contiguous windows. If the digit precedes given window, should not it have been accounted in the previous one?

Cheers,
 Ruben

**Comment by noferini** [comment]
Hi Ruben,
the digitizer does close a readout window only if the new interaction time is in the next ones.
Therefore no hit can be before of the current readout window since interaction times are ordered.

However the first readout window is set to zero time.  If the first interaction time can be negative (and then hit time also negative) this can lead to such a behavior.
I was wondering if this can happen.
Cheers
Francesco

**Comment by shahor02** [comment]
No, there could be no negative times. In fact, due to the ZDC reading out a few BCs prior the triggered BC, the interactions sampling starts by default from orbit 1 (so the orbit 0 should be empty).

**Comment by noferini** [comment]
Hi Ruben,
ok. Probably I did a mistake in the interpretation of the error.
It seems that you ddin't get the error in digitization but in decoding.
The piece of code used in decoding (WindowFiller::checkIfReuseFutureDigits) is still probably affected by truncation effect:
.   double timestamp = digit->getBC() * Geo::BC_TIME + digit->getTDC() * Geo::TDCBIN * 1E-3; // in ns
    int isnext = Int_t(timestamp * Geo::READOUTWINDOW_INV) - (mReadoutWindowCurrent + 1);    // to be replaced with uncalibrated time

I cleaned up all such effects in digitization (moving to work only with integer) but not in the part used by decoder.
I will do it.
You can go ahead with this PR. I will fix it later (but soon).

Cheers
Francesco

**Pull request merged**
