### PR TITLE
SIM: Adding experiment versions and dynamic library loading

### PR DESCRIPTION
**Pull request by f3sch**
Hi @sawenzel, this a draft based on our discussion to have the possibility to specify the detectors via list.
The first commit introduces two new program options, namely  `detectorVersion version` and `detectorVersionJSON file` and the relevant parsing. Two cases are covered:
1. only `detectorVersion` specify: then the version is taken from a predefined map with 'official' versions
2. both options are specified: then the custom file is parsed to build the same map as in 1. and the modules are taken from there.

AFAICT this 'works' but I did not test this really thoroughly but running 'o2-sim' with different options seems to do what I want.

The second commit introduces dynamic library loading with a custom dll manager modelled as a singleton. As an example I removed the dependency on 'O2{ITS,TPC,TRK}Simulation' which works as expected and I think can be extended to most other detector simulation libraries. I do not have much experience with this and was more fun experiment :).

### CODE REVIEW

**Comment by sawenzel** [comment]
Thanks. Will take a look.

**Comment by f3sch** [comment]
Hi @sawenzel, I update the code and the help description AFAICT it does what we discussed. Maybe after testing, should I undraft to test CI?

**Comment by sawenzel** [comment]
Thanks. Already took away the draft status. Will test it once more then merge it.

**Comment by sawenzel** [comment]
PR is fine for me. Only problem is the build/AliceO2/O2/o2/macOS-arm CI. Some macros seem to fail... should probably take a look. @ktf : Is this a known problem ?

**Comment by ktf** [comment]
The mac issue is not a known problem (or better, there was a known issue that got hopefully fixed which was masking this other one, I guess). I need to check what is going on.

**Comment by ktf** [comment]
Actually, I think it's a problem with this PR. It looks like a clash between boost filesystem and std::filesystem.

**Comment by f3sch** [comment]
Hi @ktf, thanks for taking a look, indeed it was clashing with the boost filesystem.
@sawenzel I removed thus this dependency altogether and now CI is green. If you haven’t already done it, can you please test that the parsing is doing what we discussed? Cheers

**Comment by sawenzel** [comment]
Works fine for me. Thanks a lot for this development. Merging.

**Pull request merged**
