### PR TITLE
DPL: provide metric for rate in and out of each channel

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@vascobarroso as requested.

**Comment by ktf** [comment]
The rates will be called `channel_{}_rate_out_mb_s` / `channel_{}_rate_out_mb_s` where `{}` is the actual channel name.

**Comment by vascobarroso** [comment]
@ktf cool thanks! What channel(s) should we use in the grafana dashboard ? Do we have well known channel names ?

**Comment by awegrzyn** [comment]
Would it be possible to use `channel_rate_in_mb_s` name, and then `.addTag(tags::Key::ID, 0);` ? Instead of having different name for each channel

**Comment by ktf** [comment]
@awegrzyn can ID be alphanumeric? I do not have a unique numeric ID per channel.

**Comment by ktf** [comment]
Merging this to have something in tomorrow build. Not clear to me how one can distinguish between the different channels actually.

**Comment by awegrzyn** [comment]
@ktf Is it possible to revert this? It's produces ~10 kHz of metrics, but it does not provide what we need.

**Comment by ktf** [comment]
For the record: metrics were marked as Debug.

**Pull request merged**
