### PR TITLE
[WIP] Fix CCDB tests on Mac (O2-726)

### PR DESCRIPTION
**Pull request by Barthelemy**

### CODE REVIEW

**Comment by sawenzel** [comment]
@Barthelemy : The failure is still there. Seems like the server is actually reachable.

**Comment by davidrohr** [comment]
Hi, I think in any case we should keep the check whether the server is not reachable, so the CI won't break again in case the server becomes unreachable.

**Comment by Barthelemy** [comment]
@davidrohr I totally agree

We discussed with Sandro and we agreed to keep the workaround of disabling the faulty tests on Mac for the time being. I need to access the machine to be able to understand what is going on. Once I get access to it I will debug.

**Comment by Barthelemy** [comment]
Actually I could just let the `if (NOT APPLE)` and we could merge the rest.

**Comment by sawenzel** [comment]
I think this would be a good idea. (Please also fix the clang-formatting in the new code).

**Pull request merged**
