### PR TITLE
Prototype of tpc reco workflow

### PR DESCRIPTION
**Pull request by matthiasrichter**
Workflow contains:
- `DigitReaderSpec`:       digit reader, read data from root files
- `ClustererSpec`:         clusterer
- `ClusterConverterSpec`:  cluster converter
- `ClusterDecoderRawSpec`: raw decoder to ClusterNative data
- `CATrackerSpec`:         CA tracker
- `RootFileWriterSpec`:  final output of the workflow, root file with reconstructed tracks in a tree

Instead of digit reader and clusterer, the cluster reader ClusterReaderSpec
can be used to publish clsuters from ROOT file.

Next steps:
- [ ] parallel workflow
- [x] include the raw data decoder
- [x] connect reconstruction with cluster converter and tracking
- [ ] propagation of MC
- [ ] incorporate the latest RDH format

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi Matthias, cool, this is a good step ahead to get some TPC reconstruction running in the framework.
I'll give it a try when I am back from vacation.
btw: Did you already modify the HardwareClusterDecoder to use your rawDataFormat reader?

**Comment by matthiasrichter** [comment]
Hi David, not yet, I first wanted to see the bare functionality of the macros running, but with the reference I can go ahead. Right now the raw pages are simply written into a binary file, so this I still have to connect.

**Comment by matthiasrichter** [comment]
Hi @davidrohr , I'm thinking about how to flatten the `ClusterNativeContainer`. It annotates the `std::vector<ClusterNative>` member  by properties sector and global padrow. The container is not messagable and would need serialization. I would like to avoid this between FLP and EPN.

The containers are specific for sector and global padrow, i.e. many, and I don't think it makes much sense to send one message per container. In order to group clusters of e.g. one sector together one would need either
- [ ] a number-of-elements member in the properties of the container
- [ ] remove global padrow from the properties 

In the first approch with an additional `nelements` member, we can construct one binary buffer on the sender side, and provide some kind of view to iterate over the elements of the binary buffer on the receiver side.

In the latter approach we need an 8-bit member for every cluster, which makes clusters unique within one sector. The 8-bit flag field could be used for that. The question would be how many flag bits we need and if those can be in the MSBs of the qmax field (don't think we need 16 bits here, should be less since qtot has the same width).

**Comment by davidrohr** [comment]
Hi @matthiasrichter  (@mkrzewic, adding Mikolaj because this is about data model).

There is a couple of points to discuss:
1. In the reconstruction (I mean the actual processing), the ClusterNative clusters are accessed via ClusterNativeAccessFullTPC (defined in the same header). The ClusterNativeContainer was just a simple mockup to enable root serialization of the clusters such that Ruben can run the root macro chain for TPC/ITS matching tests (and there is DataFormatsTPC/helpers::accessNativeContainerArray to create the ClusterNativeAccessFullTPC structure from a list of ClusterNativeContainers.

2. We can easily change the Container format (either add a second one, or switch to something that can be used in the DPL processing / in devices / as well as in root macros), and adapt the helper accordingly.
The container was meant to be independent from the processing, it is just a container to transport the data.

3. Each FLP will receive only some pad rows. (Each channel of the CRU will have 3-5 pad rows of one sector). We will have the ClusterHardwareDecoder on the FLP processing all channels on the FLP, so we can merge all the CRU cluster channels, but still, it will only be several pad rows. So, sending each on its own comes with some overhead, but we thought it will not be significant. Anyway, we will have the multi-part messages, so the transport can coalesce everything in one multi-part message, and already the data for one pad row (since it is a full 20ms time frame) will be large enough to have reasonable packet sizes over the network. I discussed this with Gvozden, in particular I had the idea to coalesce everything (from all FLPs) in a single buffer on the EPN. The advantage would be that would have one single consecutive array of clusters, and we could simply use a single 32 bit integer to index the clusters (instead of 3 indexes: sector, row, index inside sector-row-cluster-array). However, this coalescing is not possible. Even further, it might also be difficult for the shared memory subsystem to guarantee to provide buffers that large.
Long story short: we could coalesce clusters of multiple rows in one container (on the FLP during the HardwareClusterDecoding step), but there is no strong reason to do so. It is an optional optimization. Im am neither for nor against this, but let's do it in a way that does not complicate things.

4. We will need at least 3 flag bits, and probably some more. Indeed, we have some bits left in the qmax/qtot (and probably after upcoming updates, also in the cluster width). However, I am not sure if we should squeeze every single bit out in the ClusterNative format. We might want to add more flags later as well. And from the processing side, there is no gain in having an extra row field (it would help if we would add row + sector, but then we would need even more bits and it would not fit in the 96 bit). So, I would not add the row property to the cluster.

5. In general, I think we will have the problem several times that we want to ship some kind of "array" of things + some meta data, and I would actually use the stacked header for this. I think we should have something generic that can take a container of something + metadata, and ship it as the message (with the array data as payload, and the metadata in a stacked header).
In the HLT we have this always with the 0-zize arrays, like
struct AliHLTTPCClustersData {
  //metadata...
  AliHLTTPCCluster fClusters[0];
}
I think we need a modern, generic, easy to use replacement for this, that enables shipment as message, and root serialization for tests with macros.

I am attaching a very simple pseudo code of what I have in mind.
[clusterTransport.zip](https://github.com/AliceO2Group/AliceO2/files/1858100/clusterTransport.zip)
This can easily be extended to support multi-containers with a consecutive payload buffer, as suggested by Matthias.

Please let me know what you think. I'm actually in vacation till some time next week, so replies will be delayed, but I am happy to think about it in the evening.

Cheers
David

**Comment by matthiasrichter** [comment]
HI David,
thanks a lot for the comprehensive information. I did not think about the fact, that it's really just the data of a few padrows which arrive in the individual CRU channels. So the natural property to annotate the data array is indeed `{sector, padrow}`. Do you know about a document describing the TPC readout, in particular which padrows are going to be received together by the CRUs?

I'm at the moment trying to find a reasonable solution for point 5 of your answer, that's why my question popped up. Using an extra header for the meta information is a possibility for larger meta data. The easiest solution is to use the sub-specification. We simply need 16 bits for the sector and padrow numbers together. The DPL already now supports sending an `std::vector` of messageable structs and receiving it as a `span`. However I'm trying to simplify the API on the receiver side.

I also will be on vacation next week.
Have a good time
Matthias

**Comment by davidrohr** [comment]
Hi Matthias,

I agree the subspecification would work.actually i did not even think about it.

in general, i would be in favor of support for meta information in a separate struct defined in a header. even if we can fit sector and row into the specification, i believe there will be other cases where the metadata not fit. Thus I think a separate header will be more generic. the api could put the data in the subspecification if it fits and otherwise use the header stack, or just always use the header stack.

for the tpc readout: i think the tpc has a note. you can ask jens. personally, i use the tpc "mapper" class as reference...
Kind Regards
David Rohr

(Sent from my mobile, excuse the typos.)

**Comment by ktf** [comment]
@davidrohr we should indeed discuss this somewhere (WP1? @mkrzewic). I think the DataHeader should actually be used to express parallelism either in time (therefore the discussion we had on including some timestamp, which is still unactioned BTW) or in space (and therefore I think it actually makes sense to use have `{sector, padrow}` as @matthiasrichter suggests).

**Comment by matthiasrichter** [comment]
@wiechula, @davidrohr, @sawenzel, this PR with the basic reco workflow is ready for merging now.  I will continue with the development, so if you have further comments please let me know. Next steps are propagation of MC info and the application of latest RDH format and decoder.

@davidrohr, once the MC info is propagated I will also prepare the workflow to be run in ROOT macros as we discussed.

**Comment by sawenzel** [comment]
I am also in favour of merging it now if no one disagrees. Then I could try to couple it directly to the digitization devices.

**Comment by matthiasrichter** [comment]
Hi Jens, indeed, I should have added some instructions, my goof. I will add more detailed documentation and probably also a man page soon. For the moment to test it, here are some simple instructions:
- run the normal simulation and digitization to get the `o2dig.root` file
- name of the executable for the workflow is `tpc-reco-workflow`
- get a list of options:
  `tpc-reco-workflow --help`
- run for input file `o2dig.root`:
  `tpc-reco-workflow --infile o2dig.root` --outfile tpc-tracks.root

This will produce a tree of tracks in the same manner as the reconstruction chain based on the individual macros.

I'm currently rebuilding my development environment, but I think that should be the commands to run.

Ciao
Matthias

**Comment by matthiasrichter** [comment]
@dberzano, can we switch off `o2-dev-fairroot` until it is functional again?

**Comment by matthiasrichter** [comment]
merging this as a first prototype, knowing that there will be more work on that in the next days

**Comment by davidrohr** [comment]
@matthiasrichter : Hi Matthias, this is great progress, and I think it is indeed correct to merge it as soon as possible. Did you already do something for the switch between continuous and triggered mode as we discussed. I have been working on moving the tracking to the new AliTPCCommon library. Howver, the TPCCATracking class as interface will remain, so this should not affect your prototype.

David

**Comment by davidrohr** [comment]
Indeed, it makes sense to finalize the full workflow with simulation. Would it be possible to integrate into the binary the option to run only a part of the workflow, e.g. start with clusters and run only the converter and tracking. Current, you specify only the digits input and the tracks output if I understand correctly?

**Comment by sawenzel** [comment]
@davidrohr : Yes this is foreseen with "workflow options". This feature will be available soon and will allow to customize workflows without recompiling.

**Pull request merged**
