### PR TITLE
Disable rANS benchmarks unless required

### PR DESCRIPTION
**Pull request by ktf**
Breaks standalone compilation on the flp otherwise.

### CODE REVIEW

**Comment by ktf** [comment]
```
[1/19] Building CXX object Utilities/rANS/CMakeFiles/O2bench-rans-Histogram.dir/benchmarks/bench_ransHistogram.cxx.o
FAILED: Utilities/rANS/CMakeFiles/O2bench-rans-UnPack.dir/benchmarks/bench_ransUnpack.cxx.o
/opt/rh/gcc-toolset-10/root/usr/bin/c++ -DFMT_SHARED -DRANS_ENABLE_JSON -DRANS_OPENMP -DZDC_FASTSIM_ONNX -I/home/pdp/O2/Utilities/rANS/include -O3 -fopenmp -std=gnu++17 -MD -
MT Utilities/rANS/CMakeFiles/O2bench-rans-UnPack.dir/benchmarks/bench_ransUnpack.cxx.o -MF Utilities/rANS/CMakeFiles/O2bench-rans-UnPack.dir/benchmarks/bench_ransUnpack.cxx.o
.d -o Utilities/rANS/CMakeFiles/O2bench-rans-UnPack.dir/benchmarks/bench_ransUnpack.cxx.o -c /home/pdp/O2/Utilities/rANS/benchmarks/bench_ransUnpack.cxx
In file included from /opt/rh/gcc-toolset-10/root/usr/include/c++/10/pstl/parallel_backend.h:16,
                 from /opt/rh/gcc-toolset-10/root/usr/include/c++/10/pstl/algorithm_impl.h:22,
                 from /opt/rh/gcc-toolset-10/root/usr/include/c++/10/pstl/glue_execution_defs.h:50,
                 from /opt/rh/gcc-toolset-10/root/usr/include/c++/10/execution:32,
                 from /home/pdp/O2/Utilities/rANS/benchmarks/bench_ransUnpack.cxx:22:
/opt/rh/gcc-toolset-10/root/usr/include/c++/10/pstl/parallel_backend_tbb.h: In function ‘void __pstl::__par_backend::__cancel_execution()’:
/opt/rh/gcc-toolset-10/root/usr/include/c++/10/pstl/parallel_backend_tbb.h:70:10: error: ‘tbb::task’ has not been declared
   70 |     tbb::task::self().group()->cancel_group_execution();
```
if not patched. Does it have some implicit dependency on TBB?

**Comment by MichaelLettrich** [comment]
@ktf I'm using the parallel stl, which relies on tbb for the benchmarks.

**Review by MichaelLettrich — APPROVED** [review]
This will work. The benchmarks obviously are not necessary for production settings. I will inspect more in depth during this weekend

**Comment by ktf** [comment]
Ok, thanks. Merging this for now.

**Pull request merged**
