### PR TITLE
DPL: allow extracting data from processing context directly using arguments

### PR DESCRIPTION
**Pull request by ktf**
DPL: allow extracting data from processing context directly using arguments

---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/AliceO2Group/AliceO2/pull/12707).
* #12708
* __->__ #12707

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @vascobarroso this would require C++20. Did you deploy it at P2? Can I simply merge it, if it passes the tests?

See #12708 for how it can be used.

**Comment by ktf** [comment]
@TimoWilken is this stuck?

**Comment by TimoWilken** [comment]
@ktf Looks all green to me, is something missing?

**Comment by ktf** [comment]
it took a lot of time. maybe tomorrow we check.

**Pull request merged**
