### PR TITLE
Make HBFUtils singleton (ConfigurableParam)

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by aphecetche** [comment]
@shahor02 what's the underlying reason to make this class a singleton ?

**Comment by shahor02** [comment]
@aphecetche: this class defines which orbit/bc should receive TF and HBF tags and these tags should be the same for all detectors. Having it as a const (on the level of particular detector process) singleton derived from the ConfigurableParam allows to set it externally (N HBF per TF and the orbit/bc of the 1st TF) either from the command line or from config file (in future also from the cdb) and to guarantee that all processes will see the same state and will not modify it.

**Comment by ktf** [comment]
I think all this using of singleton everywhere is going to hit us back. It's a well known antipattern (https://stackoverflow.com/questions/12755539/why-is-singleton-considered-an-anti-pattern) and it requires significant amount of boilerplate and manual handling. Why not simply percolating it from the outside and have a proper place where the configuration reading happens? DPL does it via the ConfigParamSpec and the associated registry which allows for tracking of parameters and proper lifecycle (e.g. on state machine reconfiguration).

**Comment by shahor02** [comment]
@ktf it creates const instance, so the counter-arguments of thread-safety don't apply here. Which boilerplate you refer to?

**Comment by ktf** [comment]
Re thread safety: you will pay the price of one check per access even if it is const (as the static still needs to be initialised once and only once). Not claiming this is relevant in this particular case. Just a general bad practice.
Re boilerplate: for example you need to have one ROOT dictionary per configurable. I am not 100% sure, but this might also mean that we get the cost duplicated over several processes because they are not standard shared libraries.

**Comment by sawenzel** [comment]
@ktf @aphecetche : I don't understand the discussion on this PR which is merely applying the concept of ConfigurableParameters which have been in use for quite a while now. 

The hole system actually takes away the boilerplate stuff and makes it easy to define and use parameters and to percolate them from the outside via config files / CCDB / command line. See `Common/SimConfig/doc/ConfigurableParam.md`. Const singletons are in use here to have a consistent state.

Maybe we should schedule a meeting focusing more on a fundamental discussion of the concept and how we can improve it. An integration of this and DPL would actually be nice.

**Comment by shahor02** [comment]
@ktf I agree with @sawenzel , we better discuss this in more general context.

**Comment by ktf** [comment]
@sawenzel I think I have had same comment multiple times, since a while. However, given they were mostly used in simulation, I did not make too much noise about it as that's of course up to you to define. Since now it seems these are moving to be used as a more general solution, I think they do require a proper review of the concept and its usage.

**Comment by shahor02** [comment]
@ktf incidentally, this use case is also related to simulation (mc->raw conversion). In other situations only the static methods of this class are used.

**Pull request merged**
