### PR TITLE
[EMCAL-501] store energy in Digits in ADC counts

### PR DESCRIPTION
**Pull request by aknospe**
[WIP EMCAL-501] store energy in Digits in ADC counts

 - Change "Energy" -> "Amplitude" in Digit and related classes
 - Store amplitude in ADC counts (either Low or High Gain) in Digits
 - Add constants::EMCAL_HGLGFACTOR = 16
 - Change constants::EMCAL_HGLGTRANSITION to Int_t
 - Digitizer.h: set mBusyTime = 35000 and mDelay = 7 for consistency with default values in SimParam.h

### CODE REVIEW

**Comment by sawenzel** [comment]
just to understand: is this marked WIP or not?

**Comment by ktf** [comment]
nope.

**Comment by mfasDa** [comment]
@sawenzel I think it is marked as WIP, therefore I wait with the final approval until testing is done. Should be fixed in both the commit message (without WIP tag) and the PR (as "[WIP][EMCAL-501]").

**Comment by sawenzel** [comment]
Note that WIP is usually not test. It is accidentially tested here. Better not to mark as WIP if it is a simple PR.

**Comment by ktf** [comment]
Rationale now documented at:

https://aliceo2group.github.io/quickstart/devel.html#draft-wip-pull-requests

**Comment by sawenzel** [comment]
Any news here? Is it going to stay WIP?

**Comment by aknospe** [comment]
I believe this is ready to be merged. I have removed the "[WIP]" tag.

**Pull request merged**
