### PR TITLE
Disable currently broken tests

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
In principle, can we disable them only on Mac?
And the test_O2Device is failing as well.

**Comment by ktf** [comment]
Ok for only apple. I am using the web UI. ;-)

**Comment by davidrohr** [comment]
haha, working with the iPad from the couch? :)

**Comment by ktf** [comment]
nah, just too lazy to do a stash... I want an editor which allows me to work directly with (remote )PRs. I would even be ok with "ed" with GitHub API support...

**Pull request merged**
