### PR TITLE
ndsplines: added approximateFunctionBatch function

### PR DESCRIPTION
**Pull request by matthias-kleiner**

### CODE REVIEW

**Comment by davidrohr** [comment]
Just for reference, there are already bethe bloch functions in Detectors/TPC/simulation/include/TPCSimulation/Detector.h and DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackUtils.h. Could you just check that we don't have unnecessary duplicates.

**Comment by matthias-kleiner** [comment]
> Just for reference, there are already bethe bloch functions in Detectors/TPC/simulation/include/TPCSimulation/Detector.h and DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackUtils.h. Could you just check that we don't have unnecessary duplicates.

Hi @davidrohr , what do you mean by this? Is this related to this pull request?

**Comment by davidrohr** [comment]
> > Just for reference, there are already bethe bloch functions in Detectors/TPC/simulation/include/TPCSimulation/Detector.h and DataFormats/Reconstruction/include/ReconstructionDataFormats/TrackUtils.h. Could you just check that we don't have unnecessary duplicates.
> 
> Hi @davidrohr , what do you mean by this? Is this related to this pull request?

OK, forget about.... reading quickly about my mails today I read "added approximateBetheBlock" :).

**Review by sgorbuno — APPROVED** [review]
Hi @matthias-kleiner,
fine with me.

**Pull request merged**
