### PR TITLE
Fixes in FDD 

### PR DESCRIPTION
**Pull request by shahor02**
@mbroz84 These are mininal fixes needed for FDD to use it in different workflows: bug-fixes + the same carry-over method as for FT0 (see https://github.com/AliceO2Group/AliceO2/pull/5326).

Still, I see lot of ``WARNING! INCORRECT DATA BLOCK!`` from FDD, so at the moment it is impossible to put in full system test. Will open a Jira ticket.

@afurs : I've added here ``DataBlockType dataBlock{};`` fix.

### CODE REVIEW

**Comment by afurs** [comment]
@shahor02 , thanks for adding this fix!
I also suggest to put:
```
LOG(INFO) << "Byte position: "<<srcPos-dataBlock.mSize<<" | "<<binaryPayload.size()<<" | "<<dataBlock.mSize;
dataBlock.print();
```
after line https://github.com/AliceO2Group/AliceO2/blob/464b5ea671d4ce95b5caacffd0caf809528b99f3/Detectors/FIT/raw/include/FITRaw/RawReaderBase.h#L55
It will help to track "Incorrect datablock" warnings faster.
Is it possible to add within this PR?
Or I can do it in the next PR.

**Comment by shahor02** [comment]
@afurs ok, added, this triggered other fixes due to the missing methods asked for template substitution. Also, I've moved all print methods from all RawEventData.h to cxx, to avoid heavy include in these headers. 
@mbroz84 , @mslupeck : I see you have ``printHexEventHeader`` and ``printHexEventData`` which are routinely called from ``to_vector(...)``: these print methods *always* do expensive stringstream building end then pass it do ``LOG(DEBUG)``, which is even not compiled unless DEBUG build requested. Why don't you use ``LOGF(DEBUG,"...")`` or ``LOGP(DEBUG,"...")`` for printf- or fmt-like formatted output, w/o using stringstream. Then it will not incur any cost in production with default built (and no need for dedicated method for that).

The [error on FDD raw data decoding ](https://alice.its.cern.ch/jira/browse/O2-2010?filter=-2) is:
````
[22857:fdd-datareader-dpl]: [18:58:00][WARN] INCORRECT DATA BLOCK! Byte position: 720 | 8128 | 7408
[22857:fdd-datareader-dpl]: [18:58:00][INFO] HEADER
[22857:fdd-datareader-dpl]: 
[22857:fdd-datareader-dpl]: Pringting element number: 0
[22857:fdd-datareader-dpl]: ################EventHeader###############
[22857:fdd-datareader-dpl]: startDescriptor: f
[22857:fdd-datareader-dpl]: nGBTWords: 0
[22857:fdd-datareader-dpl]: BC: ec
[22857:fdd-datareader-dpl]: Orbit: 0
[22857:fdd-datareader-dpl]: ##########################################
[22857:fdd-datareader-dpl]: [18:58:00][INFO] DATA
[22857:fdd-datareader-dpl]: [18:58:00][WARN] INCORRECT DATA BLOCK! Byte position: 64 | 8128 | 8064
[22857:fdd-datareader-dpl]: [18:58:00][INFO] HEADER
[22857:fdd-datareader-dpl]: 
[22857:fdd-datareader-dpl]: Pringting element number: 0
[22857:fdd-datareader-dpl]: ################EventHeader###############
[22857:fdd-datareader-dpl]: startDescriptor: f
[22857:fdd-datareader-dpl]: nGBTWords: 0
[22857:fdd-datareader-dpl]: BC: 2d3
[22857:fdd-datareader-dpl]: Orbit: 0
[22857:fdd-datareader-dpl]: ##########################################
[22857:fdd-datareader-dpl]: [18:58:00][INFO] DATA
[22857:fdd-datareader-dpl]: [18:58:00][WARN] INCORRECT DATA BLOCK! Byte position: 0 | 240 | 240
[22857:fdd-datareader-dpl]: [18:58:00][INFO] HEADER
[22857:fdd-datareader-dpl]: 
[22857:fdd-datareader-dpl]: Pringting element number: 0
[22857:fdd-datareader-dpl]: ################EventHeader###############
[22857:fdd-datareader-dpl]: startDescriptor: f
[22857:fdd-datareader-dpl]: nGBTWords: 0
[22857:fdd-datareader-dpl]: BC: 7d8
[22857:fdd-datareader-dpl]: Orbit: 0
[22857:fdd-datareader-dpl]: ##########################################
[22857:fdd-datareader-dpl]: [18:58:00][INFO] DATA
[22857:fdd-datareader-dpl]: [18:58:00][WARN] INCORRECT DATA BLOCK! Byte position: 784 | 8112 | 7328
[22857:fdd-datareader-dpl]: [18:58:00][INFO] HEADER
[22857:fdd-datareader-dpl]: 
[22857:fdd-datareader-dpl]: Pringting element number: 0
[22857:fdd-datareader-dpl]: ################EventHeader###############
[22857:fdd-datareader-dpl]: startDescriptor: f
[22857:fdd-datareader-dpl]: nGBTWords: 0
[22857:fdd-datareader-dpl]: BC: ee
[22857:fdd-datareader-dpl]: Orbit: 0
[22857:fdd-datareader-dpl]: ##########################################
[22857:fdd-datareader-dpl]: [18:58:00][INFO] DATA
[22857:fdd-datareader-dpl]: [18:58:00][WARN] INCORRECT DATA BLOCK! Byte position: 64 | 8128 | 8064
[22857:fdd-datareader-dpl]: [18:58:00][INFO] HEADER
[22857:fdd-datareader-dpl]: 
[22857:fdd-datareader-dpl]: Pringting element number: 0
[22857:fdd-datareader-dpl]: ################EventHeader###############
[22857:fdd-datareader-dpl]: startDescriptor: f
[22857:fdd-datareader-dpl]: nGBTWords: 0
[22857:fdd-datareader-dpl]: BC: 2be
[22857:fdd-datareader-dpl]: Orbit: 0
[22857:fdd-datareader-dpl]: ##########################################
[22857:fdd-datareader-dpl]: [18:58:00][INFO] DATA
[22857:fdd-datareader-dpl]: [18:58:00][WARN] INCORRECT DATA BLOCK! Byte position: 0 | 1696 | 1696
[22857:fdd-datareader-dpl]: [18:58:00][INFO] HEADER
[22857:fdd-datareader-dpl]: 
[22857:fdd-datareader-dpl]: Pringting element number: 0
[22857:fdd-datareader-dpl]: ################EventHeader###############
[22857:fdd-datareader-dpl]: startDescriptor: f
[22857:fdd-datareader-dpl]: nGBTWords: 0
[22857:fdd-datareader-dpl]: BC: 73b
[22857:fdd-datareader-dpl]: Orbit: 0
[22857:fdd-datareader-dpl]: ##########################################
````

**Comment by mslupeck** [comment]
@shahor02 Thanks for the hint - I'll get rid of the stringstreams in FV0 at the next raw-related PR.

**Comment by afurs** [comment]
@shahor02,

well, I see source of the problem. Due to FT0 FEE logic, `o2::ft0::EventData::MinNelements=1` and `o2::ft0::EventData::MinNelements=12`, which  means that nGBTwords should be in range [1,6] (borders for nGBTwords are calculated here: https://github.com/AliceO2Group/AliceO2/blob/464b5ea671d4ce95b5caacffd0caf809528b99f3/Detectors/FIT/raw/include/FITRaw/DataBlockBase.h#L104 
and 
https://github.com/AliceO2Group/AliceO2/blob/464b5ea671d4ce95b5caacffd0caf809528b99f3/Detectors/FIT/raw/include/FITRaw/DataBlockBase.h#L107 ). This logic is also applied for FDD, and condition `nGBTWords==0` triggers this warnings. So, if FDD FEE differs from FT0 FEE, and empty data blocks( only EventHeader, no EventData) are allowed, then line https://github.com/AliceO2Group/AliceO2/blob/464b5ea671d4ce95b5caacffd0caf809528b99f3/DataFormats/Detectors/FIT/FDD/include/DataFormatsFDD/RawEventData.h#L58 should be replaced by:  
```
static constexpr int MinNelements = 0;
```
Here is several lines of description https://github.com/AliceO2Group/AliceO2/blob/464b5ea671d4ce95b5caacffd0caf809528b99f3/Detectors/FIT/raw/include/FITRaw/DataBlockBase.h#L16

**Comment by shahor02** [comment]
@afurs thanks for checking, but with modification you've suggested I get much more "INCORRECT DATA BLOCK" errors. @mbroz84 could you check ?

**Comment by afurs** [comment]
@shahor02 ,

there are another place which also related to non-zero checking of `nGBTwords`, `sanityCheck` method:
https://github.com/AliceO2Group/AliceO2/blob/aa4fa4d2c47d4440d64249064c43938708fc8327/Detectors/FIT/FDD/raw/include/FDDRaw/DataBlockFDD.h#L54
Zero value of `nGBTwords`, also causes zero for `mNelements`
I suggest to remove this line:
https://github.com/AliceO2Group/AliceO2/blob/aa4fa4d2c47d4440d64249064c43938708fc8327/Detectors/FIT/FDD/raw/include/FDDRaw/DataBlockFDD.h#L57


@mbroz84 , are you sure about this logic(events without data, only header) for FDD?

**Comment by shahor02** [comment]
@afurs Thanks, this indeed suppresses the error! Will commit this and require validation by @mbroz84.
But I still see a problem: decoding of data mentioned [here](https://alice.its.cern.ch/jira/browse/O2-2010?filter=-2)
produce a message:
````
[19104:fdd-datareader-dpl]: [10:32:06][INFO] FDD RawDataReaderSpec
[19104:fdd-datareader-dpl]: [10:32:06][INFO] Pages: 1542
[19104:fdd-datareader-dpl]: [10:32:06][INFO] Number of Digits: 589
[19104:fdd-datareader-dpl]: [10:32:06][INFO] Number of ChannelData: 1802
````
If I look in the ``fdddigits.root``, I see 
````
root [0] TFile *_file0 = TFile::Open("fdddigits.root");
root [1] o2sim->Scan("@FDDDigitCh.size() : @FDDDigit.size()");
************************************
*    Row   * @FDDDigit *  @FDDDigi *
************************************
*        0 *      9424 *       589 *
************************************
````
So, while all triggers are found, most of channels seem to be lost. No idea if this is decoding or mc->raw conversion problem.

**Comment by shahor02** [comment]
@mbroz84 Merging this since all these changes are anyway needed. Your fixes will come on top.

**Pull request merged**
