### PR TITLE
Add option to enable address sanitizer

### PR DESCRIPTION
**Pull request by qgp**
@ktf @davidrohr What about adding an option to enable sanitizers? For now just address sanitizer, but could be extended.

### CODE REVIEW

**Comment by davidrohr** [comment]
Hi @qgp : that is quite fine with me. So far, I was just adjusting the CXX Flags for using the sanitizer, which is kind of equally simple if you know what to do.
Just one remark: I ran into issues when I enabled multiple sanitizers at once, like address + undefined.
Didn't check whether that is still the case, but if I'd add such an option, I'd add an option to directly provide the list of sanitizers to use.

**Comment by davidrohr** [comment]
Also, the global option will trigger a full rebuild of O2 when changed, while with the CXX flags you can restrict the rebuild to some libraries. That doesn't mean I am against this, could still be helpful for someone who doesn't want to mess with the CXX FLAGS.

**Comment by ktf** [comment]
Shouldn't we use `CMAKE_CXX_FLAGS_SANITIZER` and `CMAKE_BUILD_TYPE=Sanitizer`.

**Comment by sawenzel** [comment]
I think one could just set the CXX flags in the o2.sh recipe to have the same effect whereas the current solution needs changes in 2 places. Otherwise, the idea is of course good. Maybe one could think about enabling this always in the CI phase (if no big overhead)?

**Comment by ktf** [comment]
Personally I would not have single flags added to the o2.sh. We can simply switch to `-DCMAKE_BUILD_TYPE=Sanitized`. I am also in favour of switching it on by default for the tests.

**Comment by qgp** [comment]
> Hi @qgp : that is quite fine with me. So far, I was just adjusting the CXX Flags for using the sanitizer, which is kind of equally simple if you know what to do.
Yes, but to have this tested more consistently it would be easier if it was part of the workflow. But I am not insisting on the implementation in this PR.

> Just one remark: I ran into issues when I enabled multiple sanitizers at once, like address + undefined.
Yes, also for me address + undefined does not work (at least with gcc 9).

> Didn't check whether that is still the case, but if I'd add such an option, I'd add an option to directly provide the list of sanitizers to use.
And what would we then use for the CI?

**Comment by qgp** [comment]
> Shouldn't we use `CMAKE_CXX_FLAGS_SANITIZER` and `CMAKE_BUILD_TYPE=Sanitizer`?

@ktf That's also fine with me, I can test this and update the PR.

**Comment by qgp** [comment]
> I think one could just set the CXX flags in the o2.sh recipe to have the same effect whereas the current solution needs changes in 2 places. Otherwise, the idea is of course good. Maybe one could think about enabling this always in the CI phase (if no big overhead)?

I don't particularly like forcing compile flags from outside the cmake workflow. And, at least for me, requiring changes in two places is not really an argument, that's also what we do for other build options.

**Comment by ktf** [comment]
If we want to customise which sanitizer to run, we could have something along the lines of:

```
set(O2_SANITIZER_LIST "-fsanitize=address")
set(CMAKE_CXX_FLAGS_SANITIZER ${O2_SANITIZER_LIST})
```

**Comment by aphecetche** [comment]
I'm late to comment on this one that I've kind of missed, sorry about that. 

The one (big) disadvantage of messing with the CMakeLists.txt (in addition to complexifying to logic of flags setting) is that you'll have to repeat the same steps to add address sanitizing (or other types of sanitizing) to other projects that might want it as well (e.g. QC). 

One alternative option would be to use a CMake script (that does build + tests, as after all you have to run something to benefit from the sanitizing) to drive special builds, as "recommended" in https://youtu.be/bsXLMQ6WgIk?t=3487, and that I kind of started in https://alice.its.cern.ch/jira/browse/QC-206 (in the context of coverage, but that's quite similar). The thing that was not completely sorted out at the time is indeed the proper integration with recipes (see an attempt https://github.com/Barthelemy/alidist/blob/coverage/qualitycontrol.sh though)

**Pull request closed without merging**
