### PR TITLE
Use data processing states

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by davidrohr** [comment]
Full system test on the EPNs fails with this PR:
```
[42516:Dispatcher]: [14:22:32][FATAL] Unhandled o2::framework::runtime_error reached the top of main of o2-qc, device shutting down. Reason: State size is 5140. States larger than 1024 bytes not supported for now.                                                                                                                                     
[42516:Dispatcher]:  Backtrace follow:                                                                                                                                                                                 
[42516:Dispatcher]:
[42516:Dispatcher]: terminate called after throwing an instance of 'o2::framework::RuntimeErrorRef'
[42516:Dispatcher]: *** Program crashed (Segmentation fault, FPE, BUS, ABRT, KILL, Unhandled Exception, ...)
[42516:Dispatcher]: Backtrace by DPL:
[42516:Dispatcher]: ABRT
[42516:Dispatcher]: Executable is /home/drohr/alice/sw/slc8_x86-64/QualityControl/v1.99.0-local1/bin/o2-qc
[42516:Dispatcher]:     /lib64/libc.so.6:     ?? ??:0
[42516:Dispatcher]:     /lib64/libc.so.6:     ?? ??:0
[42516:Dispatcher]:     /lib64/libc.so.6:     ?? ??:0
[42516:Dispatcher]:     /home/drohr/alice/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-3/lib64/libstdc++.so.6(+0xa9a49) [0x7f9ba16a2a49]:     ?? ??:0
[42516:Dispatcher]:     /home/drohr/alice/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-3/lib64/libstdc++.so.6(+0xb507a) [0x7f9ba16ae07a]:     ?? ??:0
[42516:Dispatcher]:     /home/drohr/alice/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-3/lib64/libstdc++.so.6(+0xb50e5) [0x7f9ba16ae0e5]:     ?? ??:0
[42516:Dispatcher]:     /home/drohr/alice/sw/slc8_x86-64/GCC-Toolchain/v12.2.0-alice1-3/lib64/libstdc++.so.6(+0xb5338) [0x7f9ba16ae338]:     ?? ??:0
[42516:Dispatcher]:     /home/drohr/alice/sw/slc8_x86-64/O2/dev-local1/lib/libO2Framework.so:     ?? ??:0
[42516:Dispatcher]:     /home/drohr/alice/sw/slc8_x86-64/FairLogger/v1.11.1-11/lib/libFairLogger.so.1.11: fair::Logger::~Logger()
[42516:Dispatcher]:     /home/drohr/alice/sw/slc8_x86-64/O2/dev-local1/lib/libO2Framework.so: doDPLException(o2::framework::RuntimeErrorRef&, char const*)
[42516:Dispatcher]:     o2-qc() [0x411897]:     main.cold at runDataProcessing.h:252
```

Async reco on the EPNs seems to work.

**Comment by davidrohr** [comment]
ok, just retried with your latest version of the PR, and now it works. Please ignore the previous comment.

**Comment by ktf** [comment]
Yes, I had to increase the (artificial) limit on the size of a reported state (e.g. the description of the inputs) to accommodate one of the QC devices which apparently has many of them. Maybe I should simply print a warning, rather than quitting.

**Comment by ktf** [comment]
All tests pass. Tested on hyperloop before my holidays, only minor changes since then. Merging and dealing with the eventual fallout tomorrow. Should be safe and actually increase performance and memory usage when running with the driver.

**Pull request merged**
