### PR TITLE
Update on MFT Assessment : Histogram of recoTrueMC added, harmonization of phi definition

### PR DESCRIPTION
**Pull request by sarahherrmann**
Phi definition chosen as `phiGen = TMath::ATan2(mcParticle->Py(), mcParticle->Px());`, brought back to 0 2pi. This ensures a y=x correlation in the phiRec versus phiGen plot.

### CODE REVIEW

**Review by rpezzi — APPROVED** [review]

**Comment by sarahherrmann** [comment]
Hi ! Just to notify you that my PR passed all checks and has been approved by @rpezzi

**Comment by chiarazampolli** [comment]
Hi @ktf , @TimoWilken , @shahor02 , @sarahherrmann , @rpezzi 

I tried to rebase and merge but github says there are conflicts. Should i squash?

Chiara

**Comment by ktf** [comment]
Yes. Merged.

**Comment by chiarazampolli** [comment]
Thanks @ktf , but why "rebase and merge" gave conflicts?

**Comment by ktf** [comment]
because intermediate commits had extra changes which produced the conflict.

**Comment by chiarazampolli** [comment]
OK, so in general one should better squash, or just when the rebase produces conflicts?

**Comment by ktf** [comment]
I would always squash, yes.

Ciao,
Giulio

**Pull request merged**
