### PR TITLE
Fix in rewinding the raw data to read + decrease verbosity

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by ktf** [comment]
@MichaelLettrich can you check what is wrong with macOS?

**Comment by MichaelLettrich** [comment]
@ktf on it.

**Comment by davidrohr** [comment]
@shahor02 : Perhaps I was too quick. This fixes the --loop=n with n > 0, but --loop=-1 doesn't lead to an infinite loop for me.

**Comment by MichaelLettrich** [comment]
The issues with macOS are a simple glitch in git.

```bash 
DEBUG: Updating reference repository: cd /build/mirror/alice-grid-utils && git fetch -f --tags https://gitlab.cern.ch/nhardi/alice-grid-utils.git 2>&1 && git fetch -f https://gitlab.cern.ch/nhardi/alice-grid-utils.git '+refs/heads/*:refs/heads/*' 2>&1
DEBUG: fatal: the remote end hung up unexpectedly
ERROR: Error while updating reference repos https://gitlab.cern.ch/nhardi/alice-grid-utils.git.
++ BUILD_ERROR=1

```

**Comment by shahor02** [comment]
@davidrohr right , fixed now, also switched off an annoying false-position error message.

**Pull request merged**
