### PR TITLE
DPL: reduce chances of cyclic dependencies

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@aalkin @ekryshen can you try to see if this fixes your merging problems?

@shahor02 @knopers8 you might be interested in this as well.

**Comment by ktf** [comment]
This fixes the issues for analysis and simple merging in general. @shahor02 / @knopers8 can you check for regressions in your domains? I will have a solution which should work for everything soon.

**Comment by shahor02** [comment]
@ktf I don't see regressions in the piping of those workflows which were piped correctly before, but there is no improvement either when merging workflow with writers/readers for the same message types. I think the only way to solve this is letting the topology builder to know which devices should be considered as intermediate and if they can be dropped.

image

**Comment by ktf** [comment]
I will merge this since it fixes simpler cases (e.g. in the analysis framework). I will have the full fledged topological sort implemented tomorrow.

**Comment by shahor02** [comment]
I was considering to add options to some workflows which would allow to skip adding reader / writer devices to avoid conflicts (and intermediate root files if they were produced only to feed the separate workflow). Shall I do this? Just to be sure, how you will handle the case of e.g.

WF1: {Dev11: clusterizer sends clusters} -> {Dev12: cluster_writer writes clusters to file}
WF2: {Dev21: cluster_reader sends clusters read from file} -> {Dev22: tracker receives clusters}

How the  ``WF1 | WF2`` will handle 2 devices Dev11 and Dev21 sending the same output?

**Comment by knopers8** [comment]
That didn't help for this case:
https://github.com/knopers8/AliceO2/commit/b7bcc8883568954510fd55680d98c6df4f7f8065

**Comment by matthiasrichter** [comment]
Thanks @ktf, but does not fix #3112 either.

**Pull request merged**
