### PR TITLE
DPL: fix warnings

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr this should improve the situation with the warnings you reported (a few are missing because I am currently refactoring the associated code).

**Comment by ktf** [comment]
@mkrzewic looks like the code checker is complaining about something related to the header stack. Can you have a look?

Error in dev-fairroot unrelated.

**Comment by matthiasrichter** [comment]
Out of curiosity, how does this fix warnings? The program aborts before entering the stage with the warnings?

**Comment by ktf** [comment]
In principle assert(false); should prune the path from being a valid exit path.

**Comment by matthiasrichter** [comment]
regarding the codechecker warnings related to header stack, unfortunately we can not rely on the codechecker CI right now. This is due to the updated `clang-tidy` which uses more modernize flags. We would need to actively filter out `modernize-use-equals-default`. Or we fix the warnings. For the header stack I tried, but there was a problem.

**Pull request merged**
