### PR TITLE
[O2-1341] Speedup test phase

### PR DESCRIPTION
**Pull request by aphecetche**
The main point of this PR is to propose a change in the way we test the Root macros : make the "load test" the only test we do per macro, per default. Keep the "compile test" possible but only on request. That way we cut in half the testing time for non framework tests.

In addition, some changes are made to some CMakeLists.txt in order to allow to call `ctest` in an already configured build directory, without having to setup any specific environment. As a bonus, this makes also the `ctest` command succeed on Macs with SIP enabled (which is not currently the case).

See rationale in https://alice.its.cern.ch/jira/browse/O2-1341

### CODE REVIEW

**Comment by aphecetche** [comment]
@davidrohr Any idea on why 4 tests are failing only on the gpu test ? What is fundamentally different in the GPU CI machine (if anything ?) ?

**Comment by davidrohr** [comment]
The GPU CI uses --always-prefer-system.
There was recently a general problem with python, and apparently in the meantime something was merged that breaks in the GPU CI. I'll run some tests in the normal CI container with --always-prefer-system to investigate whether this is really the cause.

**Comment by matthiasrichter** [comment]
Hi @aphecetche , after this PR and running `make` my setup is reporting 
```
CMake Error at cmake/O2AddTestWrapper.cmake:130 (add_test):
  Error evaluating generator expression:

    $<REMOVE_DUPLICATES:/home/richter/src/alisw/sw/ubuntu1804_x86-64/pythia/v8243-2/include;/home/richter/src/alisw/sw/ubuntu1804_x86-64/O2/v1.2.0-1/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/O2/v1.2.0-1/include/GPU:/home/richter/src/alisw/sw/ubuntu1804_x86-64/AEGIS/v1.0-3/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/fastjet/v3.3.3_1.042-alice1-1/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/ms_gsl/1-2/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/HepMC3/v3.0.0-git_d43693ce0e-3/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/Vc/1.4.1-2/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/FairRoot/6af7e84858-3/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/GEANT4_VMC/v3-6-p6-2/include/g4root:/home/richter/src/alisw/sw/ubuntu1804_x86-64/GEANT4_VMC/v3-6-p6-2/include/geant4vmc:/home/richter/src/alisw/sw/ubuntu1804_x86-64/GEANT4_VMC/v3-6-p6-2/include/mtroot:/home/richter/src/alisw/sw/ubuntu1804_x86-64/GEANT4/v10.4.2-2/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/GEANT4/v10.4.2-2/include/Geant4:/home/richter/src/alisw/sw/ubuntu1804_x86-64/GEANT3/v2-7-3/include/TGeant3:/home/richter/src/alisw/sw/ubuntu1804_x86-64/FairMQ/v1.4.12-1/include/fairmq:/home/richter/src/alisw/sw/ubuntu1804_x86-64/FairMQ/v1.4.12-1/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/boost/v1.70.0-2/include:/home/richter/src/alisw/sw/ubuntu1804_x86-64/FairLogger/v1.5.0-2/include;$<TARGET_PROPERTY:O2::Field,INTERFACE_INCLUDE_DIRECTORIES>>

  Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
  cmake/O2AddTestRootMacro.cmake:103 (o2_add_test_wrapper)
  Common/Field/CMakeLists.txt:35 (o2_add_test_root_macro)
```
for every `o2_add_test_root_macro`. 

Re-running cmake in the normal make does not create the configuration correctly I guess. Building the O2 stack from scratch obviously seems to work as the CI is ok, but I don't want to rebuilt. Do you have a hint what to do?

**Comment by aphecetche** [comment]
@matthiasrichter hum, my first guess is that it looks like if your cmake did not know about generator expressions $<REMOVE_DUPLICATES> and $<TARGET_PROPERTY:O2::Field,INTERFACE_INCLUDE_DIRECTORIES>
what version of CMake are you using ? This error would make sense for CMake < 3.15 I would say. 
But we moved to CMake 3.17 a few days (weeks?) ago I think...

Oh, but way, the cmake_minimum_required version has not been changed in O2/CMakeLists.txt. That could be it.

**Comment by matthiasrichter** [comment]
yes, than my cmake version is too old. And the configuration is wrong because the required version was not updated. Good that you found that. Thanks for your help.

**Pull request merged**
