### PR TITLE
Fix namespace naming: o2::Base

### PR DESCRIPTION
**Pull request by anerokhi**
Let's try this.

### CODE REVIEW

**Comment by sawenzel** [comment]
@dberzano : Could you please restart the CI for this PR in a fresh environment? (Previously generated test artefacts seem to interfere with this one.)

**Comment by anerokhi** [comment]
I've managed to step into the issue with missing dictionary when I build as
```
ALIBUILD_O2_TESTS=1 aliBuild build O2 --defaults o2
```
and switch between the `dev` and `anerokhi-fix-namespaces-o2-base` branches.
But when I remove all the `.root` files in the `sw/BUILD/.../O2` cached by tests and restart `ALIBUILD_O2_TESTS=1 aliBuild build O2 --defaults o2`, it finishes successfully.

So I don't understand why it is failed in the CI when it was restarted in a fresh environment.

**Comment by sawenzel** [comment]
Can you please rebase to dev and fix one more instance in a new file `/Detectors/ITSMFT/ITS/macros/test/run_buildTopoDict_its.C`? Thanks.

**Comment by anerokhi** [comment]
@dberzano `build/o2checkcode/o2` stuck?

**Comment by anerokhi** [comment]
@dberzano could you look at `build/o2checkcode/o2`, please? It seem stuck.

**Comment by sawenzel** [comment]
This is an important step forward towards having namespaces according to coding guidelines.
The codechecker complains because the known "framework_gui" false positives where not filtered out as usual and we can ignore this for now.

Merging

**Pull request merged**
