### PR TITLE
Finder tuned: prefiltering for performance

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by jgrosseo** [comment]
@davidrohr @sawenzel If we want analyzers to consider the output of the checkcode test without our help, we have to improve its output. I don't even find the problem in the checkcode output in this PR. Could you let me know?
I propose we redo the output in a way, that the errors are printed at the beginning, and ideally the full build output goes to a different file where we just indicate the link. What do you think about this?

**Review by jgrosseo — DISMISSED** [review]

**Comment by jgrosseo** [comment]
ps - In case it is a false positive, please merge.

**Comment by davidrohr** [comment]
There is already a summary for the checkcode errors. You can find it if you search the log for "list off". But I agree, it would make sense to move this to the beginning of the log.

**Comment by ddobrigk** [comment]
So, if I understand correctly this PR failed the o2checkcode because of me not adding underscores before capital letters in the middle of the names of table columns - is that it? ...

**Comment by sawenzel** [comment]
@jgrosseo : Like for other builds the output shown is the complete log of the build process (I usually grep for "error"). In order to make this appear at the top or having it stand out, one would need to do adjustments in the CI logic I believe.

**Comment by sawenzel** [comment]
@ddobrigk : Yes, the rule for namespaces (as described here https://github.com/AliceO2Group/CodingGuidelines/blob/master/naming_formatting.html) is  `Namespace names follow underscore convention and start with a lower case letter: <code>my_namespace</code>.`

**Comment by ddobrigk** [comment]
@jgrosseo @sawenzel now changed to stick to naming convention. Thanks!

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
