### PR TITLE
Split MID reconstruction workflow into digits reader and digits to track

### PR DESCRIPTION
**Pull request by dstocco**
This PR allows for a better modularity of the MID reconstruction workflows.
In particular, the reconstruction always run from digits, which can be published:
- from raw data
- by reading MC simulated digits
- from CTF
by using dedicated devices.

The commits in this PR are meant to be atomic. Please do not squash

### CODE REVIEW

**Comment by dstocco** [comment]
I force pushed to add the --disable-mc options (which allows to avoid propagating the MC information)

**Review by aphecetche — APPROVED** [review]

**Comment by aphecetche** [comment]
@ktf @TimoWilken is it expected that a simple change in a doc file (README.md) triggers a full CI rebuild ?

**Comment by TimoWilken** [comment]
@aphecetche yes, any change will trigger a rebuild, even if no actual code is changed.

**Comment by aphecetche** [comment]
@TimoWilken it's probably not critical but looks like a waste of (precious) CI CPU time. Would it be difficult to change this behaviour so that we not rebuild if only e.g. markdown or txt files are changed ? (this of course assumes that no one is using markdown or text files as build dependencies...)

**Pull request merged**
