### PR TITLE
TRD correct Q2 calculation for TrapSimulator

### PR DESCRIPTION
**Pull request by bazinski**
Correct the calculation of Q2 for the PID.
The sum from times 3 to 5, as consts in the header file.
New TrapConfig to be finalised still.

### CODE REVIEW

**Comment by bazinski** [comment]
As far as I can tell those errors are not related to the code of this PR

**Review by tdietel — DISMISSED** [review]
Hi Sean,

I approve the request. As you wrote, we need to pull this information from the TRAPconfig, i.e. from the CCDB. Do you have a list where you keep all the small things we need to revise at some point?

Cheers,
  - Tom.

**Comment by bazinski** [comment]
Hi Tom

Currently the best(simplest) is probably to put a todo list in Detectors/TRD ?
Unless you want a section of TDP.

Cheers
Sean

**Comment by bazinski** [comment]
ci kicked via a rebase

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
