### PR TITLE
Revert "GPU: test SMatrixGPU with OpenCL2.0"

### PR DESCRIPTION
**Pull request by mconcas**
Reverts AliceO2Group/AliceO2#5472

Somehow I was convinced I reverted it already.

### CODE REVIEW

**Comment by davidrohr** [comment]
I am a bit confused that the log in the FullCI still reports CUDA 11.2, while my other PR which just passed the CI correctly reported 11.3. I'll wait for the CI to rerun, just to double-check it actually used the new container before merging.

**Comment by davidrohr** [comment]
@TimoWilken : Same issue here as in #5983

**Comment by davidrohr** [comment]
@mconcas : I am a bit çonfused. I agree we should revert ` Revert "Use functor to check if we trick Clang13 (3a3a4c4)", to use the original code. But why do you revert also ` Revert "GPU: test compatibility of SMatrixGPU OpenCL2.0 (3a9df5e)`? Doesn't that mean the new code is actually not compiled on OpenCL?

**Comment by mconcas** [comment]
> @mconcas : I am a bit çonfused. I agree we should revert `Revert "Use functor to check if we trick Clang13 (3a3a4c4)", to use the original code. But why do you revert also` Revert "GPU: test compatibility of SMatrixGPU OpenCL2.0 (3a9df5e)`? Doesn't that mean the new code is actually not compiled on OpenCL?

It was definitely the case. I just pressed the "revert" button but I overlooked the ifdef guard.

**Pull request merged**
