### PR TITLE
[Test] PWGHF: configure KFParticle package and add analysis task for 3-prongs reconstruction with KF

### PR DESCRIPTION
**Pull request by zhujh126**
The link of PR in O2: https://github.com/zhujh126/AliceO2/commit/4714a60d7a2296a8b7ca83089ece077d0998cd34
The link of PR in O2Physics: https://github.com/zhujh126/O2Physics/commit/08206ad894e9e58454f793e471d9d316596aba5e

### CODE REVIEW

**Comment by jgrosseo** [comment]
Why is this not added as a dependency in O2Physics? Will it also be needed in O2?

**Comment by pzhristov** [comment]
KFParticle is required package in O2 and as such is build when one compiles O2Physics. For the moment we do not use any functionality in O2, so probably the dependency can be moved to alisw/o2physics.sh in a related PR.

**Comment by zhujh126** [comment]
Thanks a lot for your comments. I tried to implement a similar way as other packages (like HepMC3). However, it does not work. Could you please tell me how to make KFParticle works? Now it is complied when O2 is installed, but it is not configured properly.

**Comment by zhujh126** [comment]
I 

> KFParticle is required package in O2 and as such is build when one compiles O2Physics. For the moment we do not use any functionality in O2, so probably the dependency can be moved to alisw/o2physics.sh in a related PR.

I managed to add it in O2Physics. So we can close this PR.

**Pull request closed without merging**
