### PR TITLE
DPL: initial attempt at rate limiting.

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Not yet fully working, but it's getting there.

**Comment by ktf** [comment]
@Barthelemy @knopers8 did you update QC recently? Somehow it fails there, although this did not change the affected code. Maybe some new include?

**Comment by Barthelemy** [comment]
There are few changes in the past 7 days (if that's the correct interval). In particular there are few which change the headers. I see https://github.com/AliceO2Group/QualityControl/commit/86cd29edb6822d36960f12f5738c06c703e563d8 but I fail to understand how it could result in this failure.

**Comment by Barthelemy** [comment]
Am I correct that it is only in this PR that it happens ?

**Comment by ktf** [comment]
Yes, it's actually some `#include` addition in this PR which triggers the issue. Are you really building QCG with exceptions disabled? Is that a node / npm thing? Anyways, I will cleanup my headers.

**Comment by Barthelemy** [comment]
Calling @awegrzyn for your question concerning npm and qcg.

**Comment by awegrzyn** [comment]
Unfortunately to make it work I had to disable the exceptions

**Comment by ktf** [comment]
Ok. I removed the header so it is not a problem for now. If you have a JIRA ticket about what was happening with exceptions, could you forward it to me? thanks.

**Pull request merged**
