### PR TITLE
DPL: Dropped obsolete messages with faster rates and input wildcards (O2-1924, O2-1919, O2-1966)

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @knopers8 this should be close to addressing the problem. I only ran a simple test, though, but I need to run. I will continue later tonight.

**Comment by davidrohr** [comment]
Thx, I assume you refer to https://alice.its.cern.ch/jira/browse/O2-1966. What do you mean by `be close to`. Let's say I will wait until you believe it fixes my issue, then I'll try it.

**Comment by davidrohr** [comment]
OK, I did a quick check with this PR. The situation seems to have improved, i.e. less messages are lost, but still there are some lost. My test with 50 pp events losses the messages for 6 events, and the reconstruction processes only 44 of them.
To reproduce:
```
o2-sim -n 50 -g pythia8 --skipModules ZDC
o2-sim-digitizer-workflow --TPCtriggered
o2-tpc-reco-workflow -b --infile tpcdigits.root --output-type clusters,tracks
```
You'll see in the output of the tpc-reco-workflow less than 50 messages `[***:tpc-track-writer]: [***][INFO] writing *** track(s)`, since messages are lost.

**Comment by ktf** [comment]
"be close to" in the sense for sure it solved some of the dropping, but I tested only the synthetic reproducer I added in the PR.

**Comment by ktf** [comment]
I seem to have troubles recompiling:

```
/include/PHOSBase/RCUTrailer.h;/Users/ktf/src/sw/SOURCES/O2/2021-01-server-support/0/Detectors/PHOS/base/include/PHOSBase/Mapping.h;/Users/ktf/src/sw/SOURCES/O2/2021-01-server-support/0/Detectors/PHOS/base/src/PHOSBaseLinkDef.h" && /usr/local/Cellar/cmake/3.19.2/bin/cmake -E copy_if_different /Users/ktf/src/sw/BUILD/O2-latest/O2/Detectors/PHOS/base/G__O2PHOSBase_rdict.pcm /Users/ktf/src/sw/BUILD/O2-latest/O2/stage/lib/G__O2PHOSBase_rdict.pcm
input_line_12:182:30: error: implicit instantiation of undefined template 'std::__1::array<TGeoHMatrix, 5>'
  std::array<TGeoHMatrix, 5> mPHOS; //Rotation/shift matrices
                             ^
```

am I missing something?

**Comment by shahor02** [comment]
It is from 3-weeks old commit with all CI's green, including macOS: https://github.com/AliceO2Group/AliceO2/pull/5230

**Comment by davidrohr** [comment]
> I seem to have troubles recompiling:

Just tried, but I cannot reproduce that issue here.

**Comment by aphecetche** [comment]
@ktf 

> input_line_12:182:30: error: implicit instantiation of undefined template 'std::__1::array<TGeoHMatrix, 5>'
>   std::array<TGeoHMatrix, 5> mPHOS; //Rotation/shift matrices

I think I did encounter this error at some point as well (and added an #include <array> in Detectors/PHOS/base/include/PHOSBase/Geometry.h which is missing I would say), but right now I could not say in which context (maybe trying a new version of root that could have change the indirect includes that gets imported in that file ?)

**Comment by aphecetche** [comment]
@ktf see https://github.com/AliceO2Group/AliceO2/pull/5471

**Comment by knopers8** [comment]
I gave it a try, the logs about "obsolete messages" are gone and QC Tasks see much more messages than before.
I am still wondering if some messages aren't lost, because the rates seen by QC Tasks are lower when they are too slow to sustain the message flood.
E.g. if 4 producers create 12000 msgs/s, the Task sees 48000, because it can keep up.
But it 4 producers send 13000 msgs/s, the Task sees ~38000 for some reason.
Either something becomes slower when put under high pressure or some messages are still dropped then.

**Comment by davidrohr** [comment]
> I am still wondering if some messages aren't lost, because the rates seen by QC Tasks are lower when they are too slow to sustain the message flood.

I think that coincides with what I reported: I believe there are still messages lost, but less than before.

**Comment by ktf** [comment]
Yeah, I think there is still an issue with the Completion policies. I suggest we merge this (once the new version with the actually terminating test finishes) and I will investigate more.

**Comment by davidrohr** [comment]
Fine with me. I didn't test much but I also didn't see a regression.

**Comment by knopers8** [comment]
Same with me, it is an improvement, so I am fine with merging it, but we need a follow up, since QC detector teams start to notice the problem as well.

**Comment by ktf** [comment]
I do not understand why the test fails though, as it terminates just fine on my mac... :-/ Investigating.

**Comment by ktf** [comment]
Ok... I missed the fact the limit is only 30s, not 90...

**Comment by ktf** [comment]
Relevant test passed. Merging to tag 21.07.

**Pull request merged**
