### PR TITLE
DPL: do not mask errors when generating workflows

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @mfasDa can you check if this improves your building issues?

**Comment by ktf** [comment]
@knopers8 @Barthelemy this fails to generate the workflow configuration because the datasampling is not a real standalone workflow. Can we move to use o2_add_executable rather than o2_add_workflow?

**Comment by davidrohr** [comment]
@ktf : For reference: rebuilding with this PR, I am still getting the segfaults
```
[Mi Jan 13 09:52:06 2021] o2-testworkflow[19695]: segfault at 0 ip 0000000000000000 sp 00007ffeb315d5b8 error 14 in o2-testworkflows-aod-dummy-workflow[55a881839000+7000]
[Mi Jan 13 09:52:06 2021] Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
```
due to the zero function pointer, but at least now the build fails properly:
```
FAILED: stage/bin/o2-analysistutorial-associated-derived
2021-01-13@09:52:07:DEBUG:O2:O2:0: [ERROR] libO2FrameworkAnalysisSupport.so: cannot open shared object file: No such file or directory
2021-01-13@09:52:07:DEBUG:O2:O2:0: [ERROR] /usr/lib64/libuv.so.1: undefined symbol: dpl_plugin_callback
```

**Comment by knopers8** [comment]
> @knopers8 @Barthelemy this fails to generate the workflow configuration because the datasampling is not a real standalone workflow. Can we move to use o2_add_executable rather than o2_add_workflow?

OK, sure. I'll post a fix soon.

**Comment by davidrohr** [comment]
rebased to dev, since the dependency is apparently required for the build order.

**Review by sawenzel — APPROVED** [review]

**Pull request merged**
