### PR TITLE
Remove extra windows-style characters from  at end of line

### PR DESCRIPTION
**Pull request by matthiasrichter**

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@Barthelemy can you approve this, @ktf I suggest to merge

**Comment by ktf** [comment]
I verified that changes were only whitespaces.

**Comment by Barthelemy** [comment]
My apologies, I came too late.

**Comment by ktf** [comment]
For the record, you can simply add `?w=1` to the files url, e.g.:

https://github.com/AliceO2Group/AliceO2/pull/661/files?w=1

and get the whitespace-changes normalised output.

**Comment by ktf** [comment]
(don't try that with python, of course...;-))

**Pull request merged**
