### PR TITLE
Make sure PID is propagated to all global track params.

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @martenole 

Could you please check if more is needed for https://github.com/AliceO2Group/AliceO2/pull/12376? The refit of ITS-TPC-TRD tracks with full ITS-TPC seed was starting from the ITS track and therefore was ignoring the TPC PID set on ITS-TPC track (with afterburner tracks there was no such problem). 
But I could not understand if there is a way to set non-default PID for TRD tracking (finding step) per se: the ITS-TPC tracks are cloned to TRD tracks seeds, but it seems there is no way to transfer their PID. Did I get it right?

**Comment by martenole** [comment]
But the GPUTRDTrack inherits from the TrackParCov. So when the seeds are created from the ITS-TPC tracks I thought the PID hypothesis (which is part of TrackPar) is transferred to the TRD track seeds as well.

**Comment by shahor02** [comment]
Yes, but then in the in the tracker the PID info is lost. Isn't the trackparcov converted to GPU format there?

**Comment by martenole** [comment]
But the TRD tracking is currently done on the CPU. Then the O2 version of the track and propagator are instantiated and during the track following the function `PropagateToXBxByBz` of o2::base::Propagator is called (https://github.com/AliceO2Group/AliceO2/blob/74d21cdef3f32af432d4975c18549bfc35d75d02/GPU/GPUTracking/TRDTracking/GPUTRDInterfaces.h#L154) which should take into account the PID, right?

**Comment by martenole** [comment]
Actually, as far as I know that O2 track types and propagator are GPU compatible by now. In that case it might make sense to remove the GPU type interfaces from the TRD tracking. Is that the case @davidrohr ?

**Comment by shahor02** [comment]
Hi @martenole 

I was suspecting that the PID info is lost in the track following because the code was not compiled with e.g.
`auto pid0 = trkStart.getPID();` I wanted to add at https://github.com/AliceO2Group/AliceO2/blob/1b18b37d7fcdaf642cba2bbdb16bc65852ee6828/GPU/GPUTracking/TRDTracking/GPUTRDTracker.cxx#L416

Now, checking the `trk.getPID` at https://github.com/AliceO2Group/AliceO2/blob/1b18b37d7fcdaf642cba2bbdb16bc65852ee6828/Detectors/TRD/workflow/src/TRDGlobalTrackingSpec.cxx#L531 I see that the PID is preserved to this level. 
So, the only problem was that in the refit it was overwritten by the track param from the ITS, which obviously has pion PID.

Merging.

**Comment by martenole** [comment]
> I was suspecting that the PID info is lost in the track following because the code was not compiled with e.g.
auto pid0 = trkStart.getPID(); I wanted to add at 

Ah I understand. This would work, but then you would have needed to add the `getPID()` method to the interface for the GPU track type at https://github.com/AliceO2Group/AliceO2/blob/509150419668e4801d89591dd080ec309d3603e1/GPU/GPUTracking/TRDTracking/GPUTRDInterfaces.h#L281
Because the GPU track type is always instantiated, even if it is not used at runtime.

But OK, checking after the tracking is done is even better of course. :)

Thank you for the fix!

**Pull request merged**
