### PR TITLE
V0 geometry and Hits

### PR DESCRIPTION
**Pull request by AllaMaevskaya**

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
Dear Sandro
I can not understand reason of this crash and how to solve problem:
== /Detectors/FIT/T0/macros/readHitsDigits.C - /Environment ===
=== /Detectors/FIT/T0/macros/readHitsDigits.C - Will not get stack trace of processes timing out: pstack not found ===
=== /Detectors/FIT/T0/macros/readHitsDigits.C - Timeout prefix: gtimeout --signal=SIGTERM --kill-after=10s 100s ===
=== /Detectors/FIT/T0/macros/readHitsDigits.C - Running root with args -n -b -l -q -e .L /build/ci_checks/o2_checker_macos_o2_ci_0/sw/SOURCES/O2/1836/0/Detectors/FIT/T0/macros/readHitsDigits.C (attempt 1/1) ===

G__BaseDict dictionary payload:4645:22: error: 'FairDetector' is an incomplete type
           fDetector=dynamic_cast<FairDetector *>(mod);
                     ^           ~~~~~~~~~~~~~~~~
/build/ci_checks/o2_checker_macos_o2_ci_0/sw/osx_x86-64/FairRoot/c672f280ec-13/include/FairDetector.h:25:7: note: definition of 'FairDetector' is not complete until the closing '}'
class FairDetector : public FairModule
      ^

**Comment by shahor02** [comment]
Hi @AllaMaevskaya ,
Can you try to guard the included headers of the macro as 
````
#if !defined(__CLING__) || defined(__ROOTCLING__)                                                                                                                     
#include ...
#endif 
````
BTW, the ``FIT/T0/macros/readHitsDigits.C`` seems not to use ``T0Simulation/Detector.h``, so you don't need to include it.

**Comment by AllaMaevskaya** [comment]
Yes, macros does not use Detector.h - so what can I do with crash?

**Comment by shahor02** [comment]
Remove unnecessary headers and guard remaining ones by 
````
#if !defined(__CLING__) || defined(__ROOTCLING__)                                                                                                                     
...
#endif 
````

**Comment by AllaMaevskaya** [comment]
Dear Sandro,
is it possible to merge branches now and we will continue from here.  For us is very important to have T0/V0 separated code in dev as soon as possible. 

Best regards
Alla

**Comment by sawenzel** [comment]
I am on it. Unit tests still fail.

**Comment by mslupeck** [comment]
@sawenzel I see the test in DataFormats fail, because the length of detector names is not 3-characters long ("T0" and "V0"). What's the best approach to fix it? Should we modify the whole new code so that all the namespaces, names, etc are 3-letters long, or is it enough to just modify the test and add T0 and V0 as 2-letter exceptions there? 

#12 Detector T0 ID=12 mask: 001000000000000
/build/ci_checks/o2_checker_macos_o2_ci_1/sw/SOURCES/O2/1836/0/DataFormats/Detectors/Common/test/testDetID.cxx:29: [1;31;49merror: in "DetID_test": check std::strlen(det.getName()) == 3 has failed[0;39;49m
#13 Detector V0 ID=13 mask: 010000000000000
/build/ci_checks/o2_checker_macos_o2_ci_1/sw/SOURCES/O2/1836/0/DataFormats/Detectors/Common/test/testDetID.cxx:29: [1;31;49merror: in "DetID_test": check std::strlen(det.getName()) == 3 has failed[0;39;49m
#14 Detector ACO ID=14 mask: 100000000000000

[1;31;49m*** 2 failures are detected in the test module "Test DetID"

**Comment by AllaMaevskaya** [comment]
For us better to modify the test. 

Best regards
Alla

**Comment by sawenzel** [comment]
For now, I will modify the test so that we can go on (independently) from here. But we need to see if a 2 letter detector specifier would not cause problems somewhere else. We might eventually call the detector "T0+" and "V0+" if this can be used as names for ROOT branches.

**Comment by AllaMaevskaya** [comment]
Thank you

**Comment by shahor02** [comment]
I think DataOrigin also requires 3-char name, I would rename to T0+, V0+

**Comment by sawenzel** [comment]
Agreed. I tried but needs a few changes and there which I leave to the original authors.

**Comment by ktf** [comment]
`DataOrigin` is an int actually, so 1-4 chars. No need for zero termination. If you use two chars, make sure you also set the forth byte.

**Pull request merged**
