### PR TITLE
Return code is != 0 if storing fails

### PR DESCRIPTION
**Pull request by chiarazampolli**
@knopers8 , @shahor02 , see https://ali-bookkeeping.cern.ch/?page=log-detail&id=54512
Other things than the upload may fail (e.g. `api.updateMetadata...`), I don't know if we want to protect also for those.

### CODE REVIEW

**Comment by shahor02** [comment]
thanks, you can add also the check for the updatemetadata (will need https://github.com/AliceO2Group/AliceO2/pull/11427)

**Comment by chiarazampolli** [comment]
> thanks, you can add also the check for the updatemetadata (will need #11427)

Ok, I will add that once the other PR is merged.

**Comment by chiarazampolli** [comment]
> > thanks, you can add also the check for the updatemetadata (will need #11427)
> 
> Ok, I will add that once the other PR is merged.

Done!

**Comment by chiarazampolli** [comment]
PS: I guess it works fine, but when I tried locally, to the test ccdb, the updateMetaData gave me an error:
```
[INFO] Init CcdApi with UserAgentID: pcalicecz5-1685713004-oDNMMD, Host: http://ccdb-test.cern.ch:8080
[INFO] Uploaded to http://ccdb-test.cern.ch:8080/GLO/Config/GRPECS with validity 10:600020 for SOR:10/EOR:20
[INFO] Overriding run 123 SOR-only version http://ccdb-test.cern.ch:8080/10/81b3e7f8-014a-11ee-ba5e-fdb938091960 validity to match complete SOR/EOR version validity
<!doctype html><html lang="en"><head><title>HTTP Status 400 – Bad Request</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 400 – Bad Request</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> The EoV of this object cannot be reduced since it does not contain an adjustableEOV key</p><p><b>Description</b> The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).</p><hr class="line" /></body></html>[O2PDPSuite/latest-o2] ~ $> 
```
This running:
`o2-ecs-grp-create --ccdb-server http://localhost:8080 -p LHC10p -r 123 -n 64 -s 10` and then `o2-ecs-grp-create --ccdb-server http://localhost:8080 -p LHC10p -r 123 -n 64 -s 10 -e 20`

**Review by shahor02 — APPROVED** [review]

**Review by chiarazampolli — COMMENTED** [review]
I forgot to catch the return value of the metadata update, i will open a new PR.

**Pull request merged**
