### PR TITLE
Cleanup: Remove Examples directory

### PR DESCRIPTION
**Pull request by sawenzel**
Compilation time is becoming a problem.

Removing the Examples directory which was originally meant
to provide templates to structure modules and to give first
examples using FairMQ.

We now have gained experience for both of them so that
these examples are no longer needed.

### CODE REVIEW

**Comment by sawenzel** [comment]
Any thoughts on this?

**Comment by ktf** [comment]
How about we add a `-DBUILD_EXAMPLES=OFF` flag to cmake instead? Having the generic templates for the project could actually be useful.

**Comment by ktf** [comment]
How about #858?

**Comment by sawenzel** [comment]
Closing in favour of #858.

**Pull request closed without merging**
