### PR TITLE
[O2-616] Add tag "O2" to library names

### PR DESCRIPTION
**Pull request by mfasDa**
In order to avoid naming clashes with libraries
from other projects, in particular AliRoot, the
O2 libraries get a tag "O2" at the beginning
of the library names.

### CODE REVIEW

**Comment by mfasDa** [comment]
@Barthelemy @ktf @dberzano @sawenzel @davidrohr  Please review!

Note that the PR won't compile as the package AliTPCComm also needs an adaption.

**Comment by davidrohr** [comment]
Hi Markus: AliTPCCommon should be merged into AliRoot anyway (for such reasons). The PR for this is basically ready but on hold due to a license incompatibility.

I am currently in vacation till end of the week, then I'll follow it up.
Kind Regards
David Rohr

**Comment by davidrohr** [comment]
HI markus: FYI: we'll merge AliTPCCommon into O2 beginning of next week. Then you can update your PR and change the files in the O2 repo only. I'll let you know when it is done.
Kind Regards
David Rohr

**Comment by davidrohr** [comment]
Hi Markus,

FYI: I have discussed with Dario, and we will merge AliTPCCommon next
Monday, the 29th.
You can see the current version of the upcoming PR in my fork, branch
dev_pull_request.

Cheers
David

**Comment by davidrohr** [comment]
@mfasDa : The AliTPCCommon code has been merged. You can rebase this PR now and apply the required changes directly in O2.

**Comment by mfasDa** [comment]
@davidrohr Thanks a lot!

I have adapted the PR to the merge of the AliTPCCommon code. The code compiles now locally. @dberzano @Barthelemy @ktf @sawenzel Please review!

The main change is that library dependencies for O2 libraries in O2dependencies.cmake must include the O2 tag. I don't see any automatic way to add the tag in front of a library as the dependencies is a mixture of O2 and non-O2 libraries. This might be annoying for some users. On the other hand this clearly identifies the libraries coming from this package compared to libraries coming from other packages, i.e. ROOT, which can also be an advantage.

**Comment by sawenzel** [comment]
There is a cmake error: 
```
CMake Error at Detectors/MUON/MCH/Mapping/Impl3/CMakeLists.txt:33 (target_compile_options):
  Cannot specify compile options for target "MCHMappingImpl3" which is not
  built by this project.
```

**Comment by Barthelemy** [comment]
Same error for me

**Comment by dberzano** [comment]
@mfasDa can this be rebased and conficts solved? Thanks!

**Comment by Barthelemy** [comment]
We should add a rule to the coding guidelines as well... I'll take care of it.

**Comment by Barthelemy** [comment]
https://alice.its.cern.ch/jira/browse/O2-688

**Comment by mfasDa** [comment]
Hi @dberzano, Hi @Barthelemy, Hi @sawenzel , 

I have resolved the merge conflicts. On my platform (macOS Mojave) O2 now builds fine and the O2 tag is added to all the libraries. The muon part is rather tricky as there is a file created on the fly (which also needs the O2 tag) - maybe @aphecetche would like to check. However if a more elegant solution is desired here it is the task of the muon experts. Generally I would prefer to merge this rather soonish as the O2Dependencies.cmake is currently changing frequently and all changes in this file must be merged manually.

Cheers

Markus

**Comment by davidrohr** [comment]
I agree to merge this soon, let's solve the current C.I. issues, and then merge this immediately.

**Comment by aphecetche** [comment]
unless the muon part is a blocker for this one right now, I would propose to proceed and I'll adapt the muon part later on.

**Comment by davidrohr** [comment]
@mfasDa : Unfortunately, this seems to break some macros. I guess some of them have library names in them. I suggest you set ALIBUILD_O2_TESTS=1 as environment variable, and then build O2 with alibuild. This will enable all the ctests that are run by the C.I.. In this way, you can fix the issues locally.

**Comment by mfasDa** [comment]
Hi @davidrohr ,  I see 4 compile tests breaking:

   2 - /Common/Field/macro/createMapsFromText.C_compiled (Failed)
   4 - /Common/Field/macro/extractMapsAsText.C_compiled (Failed)
171 - /macro/convertClusterToClusterHardware.C (Failed)
187 - /macro/runCATrackingClusterNative.C (Failed)

Running the macros locally I saw that the macros didn't find several header files. The header files were installed in the common path but they are missing in the rootmap file. I suspect the issues are related. Looking into the rootmap file I see quite a lot of headers missing. I am wondering where this can come from as I didn't modify the O2_GENERATE_DICTIONARY function and with some debug statements I saw that the headers are actually passed to rootcling. Any idea how this can happen?

Cheers

Markus

**Comment by davidrohr** [comment]
For
171 - /macro/convertClusterToClusterHardware.C (Failed)
187 - /macro/runCATrackingClusterNative.C (Failed)

Some of the GPU headers are not passed to CINT/CLING. Therefore, they do not appear in the ROOTMap. I think this could be solved for some of them meanwhile, since AliGPU is now also a part of O2.

Anyhow, the macros load the libraries explicitly:
#pragma cling load("libTPCReconstruction")
#pragma cling load("libDataFormatsTPC")
You'll have to fix the library names in the macros, as they are written explicitly, then It'll work.

I think for
2 - /Common/Field/macro/createMapsFromText.C_compiled (Failed)
4 - /Common/Field/macro/extractMapsAsText.C_compiled (Failed)
This must be a different problem, not related to headers of the tracking.

**Comment by davidrohr** [comment]
@mfasDa : I see that you are also breaking the CUDA test, since the ITS cuda tracking also has a hardcoded library name that needs to be fixed:

DEBUG:O2:O2:0: CMake Error at Detectors/ITSMFT/ITS/tracking/cuda/CMakeLists.txt:33 (set_property):
DEBUG:O2:O2:0:   set_property could not find TARGET ITStrackingCUDA.  Perhaps it has not yet
DEBUG:O2:O2:0:   been created.

**Comment by mfasDa** [comment]
Indeed the errors in the two tests failing in compilation are unrelated and go away by themselves, however I am still worried about the missing headers in the rootmaps, but I think this is unrelated to this commit. I will update the commit accordingly. For the CUDA it wasn't tested as I don't have CUDA installed - is it sufficient to just add the O2 tag to the set_target_property?

Cheers

Markus

**Comment by davidrohr** [comment]
@mfasDa : I am just trying this locally, will need some minutes.

Btw: I am facing another error on my system. (probably not related to GPU) Can you have a look:
DEBUG:O2:O2:0: CMake Error at Detectors/MUON/MCH/Mapping/Impl3/CMakeLists.txt:33 (target_compile_options):
DEBUG:O2:O2:0:   Cannot specify compile options for target "MCHMappingImpl3" which is not
DEBUG:O2:O2:0:   built by this project.

**Comment by davidrohr** [comment]
@mfasDa : Can you try this fix: https://github.com/davidrohr/AliceO2/commit/7e59b65de4c7d28bf02031570f285fcf9cfa771c
It fixes the ITS GPU and also the MUON issue for me.
I am now rebuilding to test the macros.

**Comment by davidrohr** [comment]
FYI: my local test with the fix succeeded.

**Comment by mfasDa** [comment]
OK, worked for me as well on mac

**Comment by davidrohr** [comment]
But that should be OK now, worked for me.
And the C.I. will also test the CUDA part again.

**Comment by mfasDa** [comment]
@davidrohr Do you take care of merging the PR (with your patch included) or shall I add your patch to the PR first?

**Comment by davidrohr** [comment]
Hi Markus, can you please add the patch and push again to make the CI check it. Then I'll take care.

**Comment by mfasDa** [comment]
Hi @davidrohr, OK I pushed the patch to this branch. However now there are conflicts mentioned now in one file which I don't see local.

**Comment by davidrohr** [comment]
Hi Markus,then please rebase locally and force push.

**Comment by mfasDa** [comment]
OK, rebased to dev and force-pushed.

**Comment by davidrohr** [comment]
@mfasDa : There is a collission with the TPC change to remove the deprecated cluster class, which breaks the CI. I'll fix that and open a new PR that will supersede this one, if you are fine with it.

**Comment by sawenzel** [comment]
Merged via #2058 .

**Pull request closed without merging**
