### PR TITLE
FT0/FV0/TPC: adding workflows for integrated currents

### PR DESCRIPTION
**Pull request by matthias-kleiner**
FT0,FV0,TPC: The workflows for the integrated currents are analog to the workflows for the TOF (integration of the cluster, writing of the clusters to file, reading in the clusters and merging the clusters to contigous intervals)
- integrated currents can be stored in the CCDB or in local files
- see for the TOF PR for further details https://github.com/AliceO2Group/AliceO2/pull/10608
- examples of the integrated currents and use case for FT0,FV0,TOF,TPC https://indico.cern.ch/event/1237926/contributions/5251727/attachments/2585970/4461305/ATO-615O2%20Multiplicity%20counters%20-%20normalization%20and%20interactive%20visualization-3.pdf

TOF
- templating TOFIntegratedClusterCalibrator to be able to use the same calibrator for different detectors
- Adding filtering of noise during integration of currents
- Add option to store calibration objects to local files

TPC:
- IDCFactorization: parallelising writing of files for speed up
- removing unneded code for integrated clusters which was in the IDC chain
- Integrated cluster processing can be done in 1D (faster, less memory consumption, outliers e.g. out-of-sync FECs are not taken into account) or in 3D (outliers taken into account)

Running the workflows for all the currents from list of input files:

```
ARGS_ALL="--shm-segment-size 50000000000"
o2-ctf-reader-workflow --copy-cmd no-copy  --onlyDet FT0,FV0,TOF,TPC --ctf-input "list.txt" --severity warning $ARGS_ALL \
| o2-ft0-reco-workflow --disable-mc --disable-root-input --disable-root-output \
| o2-ft0-integrate-cluster-workflow --disable-root-output \
| o2-fv0-reco-workflow --disable-mc --disable-root-input --disable-root-output \
| o2-fv0-integrate-cluster-workflow --disable-root-output \
| o2-ft0-merge-integrate-cluster-workflow --dump-calib-data --meta-output-dir none \
| o2-fv0-merge-integrate-cluster-workflow --dump-calib-data --meta-output-dir none \
| o2-tof-reco-workflow --input-type none --output-type "clusters" --disable-mc --disable-root-output $ARGS_ALL \
| o2-tof-integrate-cluster-workflow --disable-root-output \
| o2-tof-merge-integrate-cluster-workflow --dump-calib-data --meta-output-dir none \
| o2-tpc-reco-workflow --input-type compressed-clusters-ctf --output-type "clusters,disable-writer" --disable-mc \
| o2-tpc-integrate-cluster-workflow $ARGS_ALL --disable-root-output \
| o2-tpc-merge-integrate-cluster-workflow --dump-calib-data --meta-output-dir none --nthreads 32 --enableWritingPadStatusMap -b
```

### CODE REVIEW

**Comment by matthias-kleiner** [comment]
Hello all,
Can this PR please be reviewed by the relevant people so that it can be merged. We want to extract the TPC currents during apass 3 if possible.

**Comment by noferini** [comment]
Hi @matthias-kleiner ,
I have only one comment.
You are using for all the tasks the data structure defined in
#include "TOFCalibration/TOFIntegratedClusterCalibrator.h"
This introduces a dependency in the TOF dir for all other detectors.
I would suggest to move it in a more general place, for instance in DataFormats/Calibration
and in o2::dataformats namespace

**Comment by matthias-kleiner** [comment]
> Hi @matthias-kleiner , I have only one comment. You are using for all the tasks the data structure defined in #include "TOFCalibration/TOFIntegratedClusterCalibrator.h" This introduces a dependency in the TOF dir for all other detectors. I would suggest to move it in a more general place, for instance in DataFormats/Calibration and in o2::dataformats namespace

Hello @noferini , yes you are right. Thanks for the suggestion. I will move it then to DataFormats/Calibration

**Comment by matthias-kleiner** [comment]
> > Hi @matthias-kleiner , I have only one comment. You are using for all the tasks the data structure defined in #include "TOFCalibration/TOFIntegratedClusterCalibrator.h" This introduces a dependency in the TOF dir for all other detectors. I would suggest to move it in a more general place, for instance in DataFormats/Calibration and in o2::dataformats namespace
> 
> Hello @noferini , yes you are right. Thanks for the suggestion. I will move it then to DataFormats/Calibration

I had to move it to `DetectorsCalibration` due to some cyclic dependencie, but I assume this is also fine

**Review by noferini — APPROVED** [review]
Thanks for applying the change. It is fine for me

**Comment by matthias-kleiner** [comment]
Are there any other suggestions, or can this be merged?

**Pull request merged**
