### PR TITLE
DPL: add workflow serialization utilities

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 could you apply this minimal change to your setup and  test if `../../bin/test_Framework_test_WorkflowSerialization` works without segfaulting? It should be a minimal reproducer for your crash in the workflow merging (albeit it doesn't reproduce in my case)...

**Comment by shahor02** [comment]
@ktf: for me also the test works w/o problems:
``
shahoian@alicers02:~/alice/sw/BUILD/O2-latest/O2$ bin/test_Framework_test_WorkflowSerialization
Running 1 test case...
--
*** No errors detected
``

**Comment by ktf** [comment]
:-/

**Comment by ktf** [comment]
Error unrelated. Merging this to simplify integration of the workflow merging PR.

**Pull request merged**
