### PR TITLE
[ITS] Factorise description of ITS inner barrel for ITS3 geometry implementation

### PR DESCRIPTION
**Pull request by fgrosa**
@mconcas this PR factorizes the inner barrel description from the geometry, in order to enable different versions needed for ITS3 studies. I still have to move part of the code from `Detector.cxx` to `DescriptorInnerBarrel.cxx` (such as services, alignment objects), but you can start to have a look and let me know if this makes sense to you. 
I already tested the current version and it gives exactly the same result as the old implementation.

### CODE REVIEW

**Comment by mconcas** [comment]
Thanks @fgrosa! I'm cc-ing also @iouribelikov, for revision.
I think we could also maybe setup a brief discussion at one of next wp2s just to for everyone to be on the same page.

**Comment by iouribelikov** [comment]
@fgrosa Thank you very much, Fabrizio.   To me, it looks good.
But the changes are numerous.  Let's quickly ( 10min ) discuss them at the ITS2 soft meeting next Tuesday, as was suggested by @mconcas.  Especially, because we expect Mario ( @mario6829 ) to be connected.

**Comment by fgrosa** [comment]
> @fgrosa Thank you very much, Fabrizio. To me, it looks good. But the changes are numerous. Let's quickly ( 10min ) discuss them at the ITS2 soft meeting next Tuesday, as was suggested by @mconcas. Especially, because we expect Mario ( @mario6829 ) to be connected.

Hi @iouribelikov, thanks a lot for your feedback! Indeed I think that discussing it at the next wp2 meeting is a good idea, there is also no hurry to merge this PR.

**Comment by fgrosa** [comment]
@mconcas @iouribelikov after the last checks, I confirm that this code gives exactly the same result as the old one, so I would say that is ready for review!

**Review by iouribelikov — DISMISSED** [review]
@fgrosa Thank you very much, Fabrizio.  For me, it works fine.
(But, of course, I was able to test the ITS2 part only)

**Comment by fgrosa** [comment]
> @fgrosa Thank you very much, Fabrizio. For me, it works fine. (But, of course, I was able to test the ITS2 part only)

Hi @iouribelikov thanks a lot for testing it! There is nothing for ITS3 yet, so if you tested ITS2 it's good enough.

**Comment by fgrosa** [comment]
After few fixes, finally the CI is green @mconcas @iouribelikov. Do you think we can merge it? Thanks!

**Review by mconcas — APPROVED** [review]
Fine with me

**Pull request merged**
