### PR TITLE
[WIP] Add two test cases of DPL that generate errors

### PR DESCRIPTION
**Pull request by knopers8**
Error in Framework/Core/test/test_Parallel.cxx - "same header and timeslice twice" in qcTask
Error in Framework/Core/test/test_TimePipeline.cxx - "missing header" in processingStages
@ktf

### CODE REVIEW

**Comment by ktf** [comment]
Thanks. Errors unrelated and will be fixed separately.

**Comment by matthiasrichter** [comment]
just changed the title because it's a demonstrator for some framework errors; not to be merged

**Comment by knopers8** [comment]
These two files actually found their way into the repo with another PR.
https://github.com/AliceO2Group/AliceO2/blob/dev/Framework/Core/test/test_TimePipeline.cxx
https://github.com/AliceO2Group/AliceO2/blob/dev/Framework/Core/test/test_Parallel.cxx

**Comment by sawenzel** [comment]
This seems to be pretty outdated. Is it still relevant or can it be closed?

**Comment by knopers8** [comment]
You are right, these workflows are in the repo anyway. This was mostly a reminder, that the problem still exists.

**Pull request closed without merging**
