### PR TITLE
[WIP] DPL: enable shmem transport for local FairMQ channels by default

### PR DESCRIPTION
**Pull request by aalkin**
@ktf This actually enables shmem transport. And breaks all parallel tests...

### CODE REVIEW

**Comment by ktf** [comment]
this is weird because we do see boost::interprocess when doing the profiles of transport =shmem on a channel basis. @rbx/@dennisklein could you clarify us how the shmem transport should be enabled?

**Comment by aalkin** [comment]
boost::interprocess::rbtree_best_fit is called both with `--transport shmem` and without it, but in the first case it segfaults in that call (but only for one of the processes in parallel group).

**Comment by dennisklein** [comment]
The ```--transport shmem``` is not needed, if you set it per channel-config. The session id is needed for shmem. I am also compiling at the moment to double-check, but I didn't have a recent aliBuild stack lying around, so it might take a bit of time to get there.

**Comment by dennisklein** [comment]
It is also important that the session id is different, if you run multiple independent workflows in parallel on the same host.

**Comment by aalkin** [comment]
@dennisklein even with session id set behavior changes depending on whether `--transport shmem` is set, despite the fact that all channels already have `,transport=shmem` in `--channel-config`.

**Comment by dennisklein** [comment]
`--id` also needs to be unique for each device within a session.

**Comment by aalkin** [comment]
For the test_ParallelPipeline spawned devices have id with index within a parallel group added, so they are indeed different.

**Comment by rbx** [comment]
> boost::interprocess::rbtree_best_fit is called both with `--transport shmem` and without it, but in the first case it segfaults in that call (but only for one of the processes in parallel group).

This sounds like a bug in FairMQ at first glance. Enabling shmem should work both via --transport or channel config. I'm not sure if I will be able to reproduce/fix it until Monday.

For now please set it only via channel config and leave --transport with the default, so you are not blocked.

**Comment by dennisklein** [comment]
I can reproduce this now: https://gist.github.com/dennisklein/e47750dc7f80ea190411ea14a61ede70. @rbx and I will be looking into this in more detail Monday after lunch.

> could you clarify us how the shmem transport should be enabled?

In terms of enabling the shmem transport you are doing the right thing. I would recommend to not set `--transport` at all (it as just setting a default) and just set it on a per channel basis, but it really should work in both cases.

**Comment by ktf** [comment]
great as usual. thanks to both.

**Comment by dennisklein** [comment]
We tracked down a regression bug in FairMQ in the handling of empty parts in a multipart shmem message (introduced long ago in Mar 2018). @rbx is preparing a fix which you can expect within the next days.

We analysed mainly the `test_Framework_test_ParallelPipeline` ctest. What we have not yet understood, is, why passing `--transport` changes the behaviour of the `trigger` device. If the `--transport` argument is present, `trigger` produces multipart messages that contain empty parts. If the `--transport` argument is not present, `trigger` does not produce empty parts. This may also indicate a problem in the DPL?! We have not looked into this yet, it is probably faster, if you have a look first since you are more familiar with your codebase.

Once this issue is resolved we will have a new testing release FairMQ `v1.4.9` for the fix on top of our `dev` branch which also picks up a new dependency of the DDS plugin which is currently enabled in alidist. To have everything built again, you will then need the following modification of the `fairmq.sh` recipe:

```diff
diff --git a/fairmq.sh b/fairmq.sh
index 962c188..1e9c675 100644
--- a/fairmq.sh
+++ b/fairmq.sh
@@ -1,6 +1,6 @@
 package: FairMQ
 version: "%(tag_basename)s"
-tag: v1.4.7
+tag: v1.4.9
 source: https://github.com/FairRootGroup/FairMQ
 requires:
  - boost
@@ -8,6 +8,7 @@ requires:
  - ZeroMQ
  - DDS
  - asiofi
+ - flatbuffers
 build_requires:
  - CMake
  - "GCC-Toolchain:(?!osx)"
@@ -45,11 +46,13 @@ cmake $SOURCEDIR                                                 \
       ${FAIRLOGGER_ROOT:+-DFAIRLOGGER_ROOT=$FAIRLOGGER_ROOT}     \
       ${ZEROMQ_ROOT:+-DZEROMQ_ROOT=$ZEROMQ_ROOT}                 \
       ${DDS_ROOT:+-DDDS_ROOT=$DDS_ROOT}                          \
+      ${FLATBUFFERS_ROOT:+-DFLATBUFFERS_ROOT=$FLATBUFFERS_ROOT}  \
       ${ASIOFI_ROOT:+-DASIOFI_ROOT=$ASIOFI_ROOT}                 \
       ${OFI_ROOT:+-DOFI_ROOT=$OFI_ROOT}                          \
       ${OFI_ROOT:--DBUILD_OFI_TRANSPORT=OFF}                     \
       -DDISABLE_COLOR=ON                                         \
       ${DDS_ROOT:+-DBUILD_DDS_PLUGIN=ON}                         \
+      ${DDS_ROOT:+-DBUILD_SDK_COMMANDS=ON}                       \
       -DBUILD_NANOMSG_TRANSPORT=OFF                              \
       ${BUILD_OFI:+-DBUILD_OFI_TRANSPORT=ON}                     \
       -DBUILD_EXAMPLES=ON                                        \
```

**Comment by aalkin** [comment]
Closing for now as it seems to be breaking tests in containers.

**Comment by dennisklein** [comment]
We believe the segfault is fixed now in FairMQ `dev`. I am still not sure if this fixes the entirety of the problem. One should still understand why the DPL test devices produce empty message parts in the case `--transport` is given and not otherwise?!

@ktf Once you give me a go, I will make the `v1.4.9` release of FairMQ. Or should I also wait for the resolution of FairRootGroup/FairMQ#217?

**Pull request closed without merging**
