### PR TITLE
Use O2LongInt aliased to long int instead of int64_t in persistent ob…

### PR DESCRIPTION
**Pull request by shahor02**
…jects with pair<...>

This is to make readable on the MacOS the CCDB objects with pair<std::int64_t,...> (stored as pair<long int, ...>). A static_assert is added to ensure that the long int is at least 8 bytes long.

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @chiarazampolli 
Could you please check if with this PR you can read on MacOC objects like 

http://alice-ccdb.cern.ch/browse/FV0/Calib/DCSDPs
https://alice-ccdb.cern.ch/browse/MFT/Condition/DCSDPs
or 
https://alice-ccdb.cern.ch/browse/GLO/Config/EnvVars ?

**Comment by chiarazampolli** [comment]
Hi @shahor02 , 

Thanks for taking care. I need to recompile quite an old O2 version, I will let you know when I manage.

Chiara

**Review by ktf — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hello @shahor02 , 

For me now it works on macos:

{code}
root [0] 
Attaching file o2-grp-GRPEnvVariables_1734616480932.root as _file0...
(TFile *) 0x154140c70
root [1] .ls
TFile**		o2-grp-GRPEnvVariables_1734616480932.root	
 TFile*		o2-grp-GRPEnvVariables_1734616480932.root	
  KEY: o2::grp::GRPEnvVariables	ccdb_object;1	object title
root [2] o2::grp::GRPEnvVariables* cc = (o2::grp::GRPEnvVariables*)_file0->Get("ccdb_object")
(o2::grp::GRPEnvVariables *) 0x600002d1d8c0
root [3] cc->print()
CavernTemperature             
timestamp 1734615883019   val 18.060
SurfaceAtmosPressure          
timestamp 1734615879030   val 955.205
CavernAtmosPressure           
timestamp 1734615880519   val 958.999
CavernAtmosPressure2          
timestamp 1734615880519   val 958.830
root [4] 
{code}

**Comment by shahor02** [comment]
Thanks for checking, merging.

**Pull request merged**
