### PR TITLE
Fixes to propagate updates of GPU params (D.Rohr)

### PR DESCRIPTION
**Pull request by shahor02**
These are the fixes needed to make https://github.com/AliceO2Group/AliceO2/pull/13753 work.

### CODE REVIEW

**Comment by davidrohr** [comment]
Looka good

**Comment by chiarazampolli** [comment]
Removing  async-2024-PbPb-cpass0, since cpass0 is over.

**Comment by alcaliva** [comment]
Hi @shahor02 is this needed for async 2024 pp apass1? I get conflicts when I try to port it to the tag

**Comment by shahor02** [comment]
@alcaliva no, sorry, wrong tag.

**Pull request merged**
