### PR TITLE
Update AnalysisDataModel.h

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by ddobrigk** [comment]
This is required to swap the PV cov matrix XZ and YY elements following the discussion in the WP4+WP14 meeting (more info [here](https://indico.cern.ch/event/1219192/contributions/5128952/attachments/2542060/4376840/DDChinellato-MondayMeeting-7Nov2022-1.pdf))

**Comment by jgrosseo** [comment]
This looks good. 

To make the transition more smooth, I propose to first merge this and have still Collision_000 as the default and then after the O2Physics PR is merged, make another PR which changes the default to _001.

**Comment by aalkin** [comment]
You will also need to add `DECLARE_EQUIVALENT_FOR_INDEX` to make sure both versions are interchangeable.

**Comment by ddobrigk** [comment]
Thanks, now done: Collisions_000 is the default and the index equivalency has been declared. Actually like this we could already merge, so if there are no objections, I will change to ready for review shortly.

**Comment by ddobrigk** [comment]
I think the test that failed was just a timeout, likely due to the system problems today. I guess this can be merged now in case we agree... thanks!

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
