### PR TITLE
DPL: Cleanup, removing RootObjectContext

### PR DESCRIPTION
**Pull request by matthiasrichter**
The context became obsolete in PR #2221 with commit 24700f51, which implements
ROOT serialization also for non `TObject` types.

### CODE REVIEW

**Comment by ktf** [comment]
+100

**Comment by matthiasrichter** [comment]
obviously I did not compile the complete project, need to fix a few dependencies

**Comment by matthiasrichter** [comment]
There is a dependency in the QualityControl control package using the removed code. I'm going to make a PR there.

**Comment by matthiasrichter** [comment]
o2checkcode CI failure is unrelated, see #2897

**Comment by matthiasrichter** [comment]
AliceO2Group/QualityControl#305 has been merged, going to trigger rebuilt of the CI

**Comment by matthiasrichter** [comment]
The CI is still failing because it doesn't use the master of QualityControl but tag v0.20.1, @Barthelemy how often are you creating tags? For creating the next one we can probably wait for the pending PR.

**Comment by Barthelemy** [comment]
We publish releases when there are new features that are awaited (like here) or when we got enough done that would make sense. 

I think that releasing a new version makes sense, I would just wait for https://github.com/AliceO2Group/QualityControl/pull/304 if that's ok. 

@knopers8 what do you think ?

**Comment by knopers8** [comment]
sure

**Comment by ktf** [comment]
Restarting gpu tests.

**Comment by ktf** [comment]
Travis seems fine but for some reason it does not report the result.

**Comment by matthiasrichter** [comment]
I think the Travis check is stuck, just checked manually once again the formatting, merging.

**Comment by ktf** [comment]
Thanks.

**Pull request merged**
