### PR TITLE
Store ROFRecord and MCROFRecord in the same tree as referred objects

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
@iouribelikov @bovulpes @jmyrcha @mpuccio @mconcas 
I've modified the way ROFRecord and MCROFRecord is stored in output files: instead of writing them as a single vector in the dedicated tree in the same file as the referred objects (digits, clusters etc.) I now write them as a branch in the same tree on the referred objects. This simplifies the handling of the references and will eventually allow to use RootTreeWriter/Reader instead of using custom readed/writier classes. 
Also, I've eliminated the possibility of storing the clusters of single time-frame in multiple entries of the output tree: this was making ITS/MFT code special wrt other detectors and complicated its handling w/o clear benefits.
I hope I've fixed all dependent code, but don't be surprised if something fails. Obviously, using new code will require new data (reprocessed starting from the digitization).

**Comment by iouribelikov** [comment]
@shahor02  Hi Ruben,

The DPL test .../ITS/macros/test/run_workflows.sh does not produce any clusters (and so no tracks).
I am having a deeper look.

The macro-driven test .../ITS/macros/test/run_test.sh goes all the way to the end, with reasonably looking results. But the macro .../ITS/macros/test/CheckClusters.C fails.

Cannot we quickly merge the PR #2755 , rebase this PR, and then fix the macro ?

**Comment by shahor02** [comment]
Hi @iouribelikov 
OK, I'll rebase this PR to Artur's, and check the results.
Cheers,
 Ruben

**Comment by iouribelikov** [comment]
@shahor02 Thank you very much !

For this PR, when running in DPL, the cluster finder does not get any digits, somehow. But the digits are there inside the file.  And they look good ! (according to the CheckDigits.C macro).  Strange glitch...

**Comment by shahor02** [comment]
@iouribelikov thanks for check, I'll run more thorough tests after lunch

**Comment by iouribelikov** [comment]
@shahor02  We should probably do the following little fixes in DigitReaderSpec.cxx : 
Line 74 :  allDigits --> digits
Line 77 :  allLabels --> labels

**Comment by shahor02** [comment]
Hi @iouribelikov 
Indeed, that was the problem. I've also changed the ROFRecord itself (now just an offset + N.entries, no event ID, since all TF data is not in a single entry) and fixed also few other problems (not directly related to these changes, like initializing the branch address by a pointer valid in a limited scope).

**Comment by iouribelikov** [comment]
@shahor02  Now, both ITS tests pass. The results look OK. Thank you very much, Ruben.

The comparison macros also work well with the results of the DPL test.  
But with the macro-driven test, the CheckClusters.C macro does not work.  
(I will have a look later.  Not so important, I think.)

**Comment by shahor02** [comment]
Hi @iouribelikov 

If you remind me how you run the macro-based test I can check. Btw, running the CheckClusters I up to 20 \mum Z-dependent bias. Did you check the response matrix surface is aligned with the sensitice layer surface?

**Comment by iouribelikov** [comment]
@shahor02  Just run (or have a look inside) the .../ITS/macros/run_test.sh script (no arguments).

But this script runs the digitization in "triggered" mode. The produced RO frames do not have any consecutive numbering.  Which may somehow confuse the comparison macros.

**Comment by shahor02** [comment]
Hi @iouribelikov 
Indeed, this is related to the fact that the MC2ROFRecord is not correctly set in case of the "triggered" RO (and it should not be related to this PR). I think this should be fixed by proper implementation of the triggered mode rather than patching current wrong code.
If there are no other comments on this PR, I would merge it to avoid conflicts with other devs.

**Comment by iouribelikov** [comment]
@shahor02  OK. Let's merge this PR !

**Pull request merged**
