### PR TITLE
DPL: Add missing includes

### PR DESCRIPTION
**Pull request by dennisklein**
Dependency of #2547

### CODE REVIEW

**Comment by ktf** [comment]
Why is this needed?

**Comment by dennisklein** [comment]
> Why is this needed?

When compiling against FairMQ `dev` I get a lot of these:

```cpp
DEBUG:O2:O2:0: [3/1186] Building CXX object Framework/TestWorkflows/CMakeFiles/O2exe-testworkflows-test_CompletionPolicies.dir/src/test_CompletionPolicies.cxx.o
DEBUG:O2:O2:0: FAILED: Framework/TestWorkflows/CMakeFiles/O2exe-testworkflows-test_CompletionPolicies.dir/src/test_CompletionPolicies.cxx.o
DEBUG:O2:O2:0: /usr/bin/c++  -DBOOST_ERROR_CODE_HEADER_ONLY -DGLFW_DLL -I/home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Framework/Core/include -I/home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Common/Utils/include -I/home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Framework/Foundation/include -I/home/dklein/alice/sw/SOURCES/O2/1.0.0/0/DataFormats/Headers/include -I/home/dklein/alice/sw/SOURCES/O2/1.0.0/0/DataFormats/MemoryResources/include -I/home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Utilities/PCG/include -I/home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Framework/DebugGUI/include -I/home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Framework/Logger/include -isystem /home/dklein/alice/sw/fedora31_x86-64/Common-O2/v1.4.6-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/boost/v1.70.0-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/Configuration/v2.2.4-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/libInfoLogger/v1.3.5-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/Monitoring/v2.6.3-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/FairMQ/shmem-fixes-2019-10-1/include/fairmq -isystem /home/dklein/alice/sw/fedora31_x86-64/FairMQ/shmem-fixes-2019-10-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/FairLogger/v1.5.0-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/ROOT/v6-18-04-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/RapidJSON/091de040edb3355dcf2f4a18c425aec51b906f08-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/arrow/v0.14.1-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/ms_gsl/1-1/include -isystem /home/dklein/alice/sw/fedora31_x86-64/fmt/5.3.0-1/include -fPIC -O2 -std=c++17 -O2 -g -DNDEBUG   -std=c++17 -MD -MT Framework/TestWorkflows/CMakeFiles/O2exe-testworkflows-test_CompletionPolicies.dir/src/test_CompletionPolicies.cxx.o -MF Framework/TestWorkflows/CMakeFiles/O2exe-testworkflows-test_CompletionPolicies.dir/src/test_CompletionPolicies.cxx.o.d -o Framework/TestWorkflows/CMakeFiles/O2exe-testworkflows-test_CompletionPolicies.dir/src/test_CompletionPolicies.cxx.o -c /home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Framework/TestWorkflows/src/test_CompletionPolicies.cxx
DEBUG:O2:O2:0: /home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Framework/TestWorkflows/src/test_CompletionPolicies.cxx: In lambda function:
DEBUG:O2:O2:0: /home/dklein/alice/sw/SOURCES/O2/1.0.0/0/Framework/TestWorkflows/src/test_CompletionPolicies.cxx:54:16: error: 'std::this_thread' has not been declared
DEBUG:O2:O2:0:    54 |           std::this_thread::sleep_for(std::chrono::seconds(1));
DEBUG:O2:O2:0:       |                ^~~~~~~~~~~
```

I guess the `<thread>` header was picked up via some FairMQ header file which no longer includes it.

**Comment by ktf** [comment]
ah, we should probably move to use the fairmq helper though.

**Comment by dennisklein** [comment]
> ah, we should probably move to use the fairmq helper though.

Of course, whatever you prefer.

**Comment by ktf** [comment]
Can you reopen this? We can do the cleanup afterwards, sorry for the confusion.

**Pull request merged**
