### PR TITLE
Restore O2 compilation with --disable DebugGUI

### PR DESCRIPTION
**Pull request by ihrivnac**

### CODE REVIEW

**Comment by ihrivnac** [comment]
> Did you try with `--disable GLFW`?

Yes, it did not help.

**Comment by ktf** [comment]
The problem is in the `CMakeLists`. If GLFW / DebugGUI are disabled, those files are not part of the compilation unit at all. See:

https://github.com/AliceO2Group/AliceO2/blob/dev/Framework/Core/CMakeLists.txt#L11

Something is pulling in GLFW (from the system?) even if disabled. That's the issue that should be fixed, IMHO.

**Comment by ihrivnac** [comment]
Ane where is the "--disable GLFW" info passed to cmake ? I don't see anything relevant in o2.sh.

**Comment by ktf** [comment]
Because of the changes in https://github.com/alisw/alidist/pull/1788 the dependency is implicit via the GLFW_ROOT variable.

**Comment by ihrivnac** [comment]
When running with --disable GLFW, then compilation fails on DebugGUI; the GLFW_ROOT is filled by brew, see https://github.com/alisw/alidist/blob/master/debuggui.sh#L18in debuggui.sh :
```
case $ARCHITECTURE in
    osx*)
      [[ ! $GLFW_ROOT ]] && GLFW_ROOT=`brew --prefix glfw`

```
There should be taken into account the info that GLFW was disabled, but I don't know how aliBuild passes the info into the recipe.

**Comment by ihrivnac** [comment]
@ktf, can we get this merged? 
The tests passed ok, while your solution proposed above fails. When switching off via --disable GLFW works, the added ifs can be removed from the code.

**Comment by ktf** [comment]
please hold on this. It's not so urgent since there is no particular drawback in building with DebugGUI enabled. As I said, it should be fixed at the CMakeLists.txt level, IMHO.

**Comment by ihrivnac** [comment]
On my side (Mac) building DebugGUI fails; there is another issue report about the failure due to DebugGUI on Mac here: https://github.com/alisw/alidist/issues/2399
So having the possibility to switch off building this library would help.

**Comment by ihrivnac** [comment]
Here is the failure which I get when DebugGUI build is enabled:
Undefined symbols for architecture x86_64:
  "___glewActiveTexture", referenced from:
      ImGui_ImplOpenGL3_RenderDrawData(ImDrawData*) in imgui_impl_opengl3.o
  "___glewAttachShader", referenced from:
      ImGui_ImplOpenGL3_CreateDeviceObjects() in imgui_impl_opengl3.o
  "___glewBindBuffer", referenced from:
      ImGui_ImplOpenGL3_CreateDeviceObjects() in imgui_impl_opengl3.o
      ImGui_ImplOpenGL3_RenderDrawData(ImDrawData*) in imgui_impl_opengl3.o
      ImGui_ImplOpenGL3_SetupRenderState(ImDrawData*, int, int, unsigned int) in imgui_impl_opengl3.o
...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[1]: *** [Tracy-debug] Error 1
make: *** [debug] Error 2

GLFW used is build locally; the path to the library in make command is
`++ make 'LIBS=-L/Users/ivana/work/projects/aliceO2/sw/osx_x86-64/capstone/4.0.2-2/lib -L/Users/ivana/work/projects/aliceO2/sw/osx_x86-64/GLFW/3.3-090b16bfae-1/lib -L/usr/local/opt/freetype/lib -lglfw ...`

**Comment by ktf** [comment]
see the comment in the other issue. Did you install the required packages with brew?

**Comment by ihrivnac** [comment]
I did when upgrading to Catalina; but as this was in March I tried to run the command again and got
(after long message about updating brew):
```
Warning: alisw/system-deps/o2-full-deps 19.6-1 is already installed and up-to-date
To reinstall 19.6-1, run `brew reinstall o2-full-deps`

```

**Comment by ktf** [comment]
can you try the reinstall? i suspect we did not bump the version...The error you have is because freetype seems to come from some old XQuartz installation rather than brew. Or maybe you have XQuartz in the path before brew?

**Comment by ihrivnac** [comment]
Ok, done. It took a while, as after reinstalling prerequisites, I had also to upgrade aliBuild, and then aliBuild was rebuilding most of packages again, up to DebugGUI, which build ends with the same error as reported above.

@MichaelLettrich , would it be possible to take a look at the DebugGUI build log at the CI Mac machine, whether there is used the same version of GLFW  built via our build system?

**Comment by ktf** [comment]
I think the problem is that you have XQuartz in front in the PATH. Changing that fixed the issue for https://github.com/alisw/alidist/issues/2399.

**Comment by ihrivnac** [comment]
I checked this, too, but it is at the end:
```
[MacBook-Pro-4] ~/work/projects/aliceO2/alidist > which xquartz
/opt/X11/bin/xquartz
[MacBook-Pro-4] ~/work/projects/aliceO2/alidist > echo $PATH
/usr/local/opt/ruby/bin:/Users/ivana/.rbenv/shims:/Users/ivana/bin:/usr/local/opt/gettext/bin:/usr/local/bin:/opt/bin:/opt/local/bin:/opt/local/sbin:/Users/ivana/perl5/perlbrew/bin:/Users/ivana/perl5/perlbrew/perls/perl-5.28.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/texbin:/opt/X11/bin


```

**Comment by ktf** [comment]
what does `which freetype-config` say?

**Comment by ihrivnac** [comment]
```
[MacBook-Pro-4] ~/work/projects/aliceO2/alidist > which freetype-config
/usr/local/bin/freetype-config

```

**Comment by ihrivnac** [comment]
```
[MacBook-Pro-4] ~/work/projects/aliceO2/alidist > ls -l /usr/local/bin/freetype-config 
lrwxr-xr-x  1 ivana  admin  45 Jul 30 01:22 /usr/local/bin/freetype-config -> ../Cellar/freetype/2.10.2/bin/freetype-config

```

**Pull request closed without merging**
