### PR TITLE
Fix broken TPC tests

### PR DESCRIPTION
**Pull request by dberzano**
See #655.

### CODE REVIEW

**Comment by sawenzel** [comment]
This is not necessary. Just rename "tpc-run-sim" to "runTPC" in one of the CMakeFiles.

**Comment by dberzano** [comment]
OK it should be fine now, with the new executable name. Given that the C.I. reuses the old installation directory, the problem was not caught in the first place as CMake kept finding the legacy executable.

Now, the problem can be probably addressed within CMake itself by instructing it to clean no longer existing files at `make install` stage by looking up a certain list. There is a certain (quite convolute) way to do that.

**Comment by dberzano** [comment]
@ktf @sawenzel can we merge?

**Comment by sawenzel** [comment]
@dberzano : Let's wait until the macos build is ok (as this was the only one seeing a problem).

**Pull request merged**
