### PR TITLE
DPL GUI: add ability to attach a debugger from the GUI

### PR DESCRIPTION
**Pull request by ktf**
Uses lldb in Terminal.app on macOS, gdb in an xterm on Linux.

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr @matthiasrichter as we discussed in a few places. It works on my mac (apart from the fact that the window does not get raised to front). Could you confirm it works on linux as well?

**Comment by ktf** [comment]
Obligatory screenshot:

debug-screenshot

**Comment by ktf** [comment]
Window also gets raised on mac. You might get an empty one a side effect. Good enough for now, not sure why I did not do it before... Merging.

**Comment by matthiasrichter** [comment]
@ktf, wow, that's nice! And indeed simple. Window opens also on linux. The only problem is that `gdb` needs to be started with `sudo`, at least in my case. I added a mall update to the cookbook in https://github.com/AliceO2Group/AliceO2/pull/1794

We can also change the linux default command, but I would leave it like it is.

**Comment by ktf** [comment]
I think that (using sudo) is an ubuntism. I would leave it as is.

**Comment by matthiasrichter** [comment]
correct, can attach on the hlt dev cluster without sudo. we leave the code (that was my feeling).

Is the addon in the cookbook ok?

**Comment by ktf** [comment]
Yes, sure the addition to the doc is fine.

**Comment by wiechula** [comment]
Hi @matthiasrichter ,
can this https://askubuntu.com/questions/41629/after-upgrade-gdb-wont-attach-to-process solve your gdb sudo problem on ubuntu?

**Comment by matthiasrichter** [comment]
Hi @wiechula, indeed, thanks. the threshold was not reached to search for this, since I did not consider it a problem. But now I learned even something new ;-)

**Comment by anerokhi** [comment]
```
sw/SOURCES/O2/1.0.0/0/Framework/Core/src/FrameworkGUIDeviceInspector.cxx:123:11: error: ignoring return value of 'int sy
stem(const char*)', declared with attribute warn_unused_result [-Werror=unused-result]
     system(getenv("O2DPLDEBUG"));
     ~~~~~~^~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
Framework/Core/CMakeFiles/Framework.dir/build.make:789: recipe for target 'Framework/Core/CMakeFiles/Framework.dir/src/FrameworkGUIDeviceInspector.cxx.o' faile
d
```

**Pull request merged**
