### PR TITLE
Print PID of driver process when starting

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@davidrohr is the issue:
 
```
## sw/BUILD/O2-full-system-test-latest/log
--
Detected critical problem in logfile reco_NOGPU.log
reco_NOGPU.log-[27499:raw-file-reader]: [23:03:56][ERROR] Failed to open input file /mnt/mesos/sandbox/sandbox/o2-fullci/sw/BUILD/85607e85095be7a13c8a5bc208c75bcc76854e2b/O2-full-system-test/full-system-test-sim/raw/ITS/ITS_cru1600_link0_ep0_feeid20501.raw
reco_NOGPU.log-[27499:raw-file-reader]: [23:03:56][STATE] Exiting FairMQ state machine
reco_NOGPU.log:[27499:raw-file-reader]: [23:03:56][ERROR] Unhandled std::exception reached the top of main: wrong raw data file path or origin/description, device shutting down.
reco_NOGPU.log:[27620:cpv-digit-reader]: [ERROR] error while setting up workflow: Error while parsing serialised workflow
reco_NOGPU.log:[27675:tpc-tracker]: [ERROR] error while setting up workflow: Error while parsing serialised workflow
reco_NOGPU.log:[27773:PHOSRawToCellConverterSpec]: [ERROR] error while setting up workflow: Error while parsing serialised workflow
reco_NOGPU.log:[27817:CPVRawToDigitConverterSpec]: [ERROR] error while setting up workflow: Error while parsing serialised workflow
reco_NOGPU.log:[27931:its-stf-decoder]: [ERROR] error while setting up workflow: Error while parsing serialised workflow
reco_NOGPU.log:[28001:mft-stf-decoder]: [ERROR] error while setting up workflow: Error while parsing serialised workflow
reco_NOGPU.log-[28058:EMCALRawToCellConverterSpec]: [INFO] Spawing new device EMCALRawToCellConverterSpec in process with pid 28058
reco_NOGPU.log-[28058:EMCALRawToCellConverterSpec]: [23:03:59][INFO] 
```

related to the limit on files you were telling about before? @TimoWilken is the ulimit fix already deployed on that mac?

**Comment by davidrohr** [comment]
Yes, exactly. No idea why this showed up now suddenly, since I assume the ulimit in the FullCI container has not changed?

**Comment by TimoWilken** [comment]
@ktf @davidrohr Hm, I thought 1024 was the ulimit on Linux. https://github.com/alisw/ali-bot/pull/978 sets it even higher, and doesn't change it if the existing ulimit is even higher than that, so that should fix the fullCI trouble.

**Comment by davidrohr** [comment]
1024 is the default I guess, but you can go higher. So, your PR was chainging it for all OS, not only for MacOS, so it might have reduced it for Linux. Then that is why the full CI started to fail again.

**Pull request merged**
