### PR TITLE
Changing CCDB path for configuration of DCS DPs

### PR DESCRIPTION
**Pull request by chiarazampolli**
@aphecetche , @wiechula , @mpoghos , @shahor02 , @syano0822 : this is following the convention of 3 level path for CCDB entries, plus change in DCSconfig --> DCSDPconfig, for clarity. 

Please, regenerate your entries in the CCDB to process Data Points.

### CODE REVIEW

**Review by aphecetche — APPROVED** [review]

**Comment by chiarazampolli** [comment]
Hi, 

Any idea of what are the merge conflicts? I don't see any log.

Chiara

**Comment by shahor02** [comment]
Should be a false positive, could you push some dummy commit to trigger another check?

**Comment by chiarazampolli** [comment]
Thanks @shahor02! Let's see...

**Comment by chiarazampolli** [comment]
No idea of the macOS error... In general, anyone against this PR?

**Review by shahor02 — APPROVED** [review]
Merging, but detectors should regenerate their configs

**Pull request merged**
