### PR TITLE
Use ROF records in the MC reconstruction workflow

### PR DESCRIPTION
**Pull request by dstocco**
This is the second of a series of PRs to use ROFrecords in MID reconstruction.
This is needed to be able to handle objects with the same timestamp inside a timeframe.
I profit of this change also to fully separate the MC reconstruction workflow from the data reconstruction workflow.
This will avoid some message synchronization issues, due to the fact that, when reconstructing MC, the label propagation is much slower than the data propagation.
The PR consists of 3 atomic commits that should not be squashed.

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @dstocco, @aphecetche  

Concerning the separation of the MC and data workflows, is not this bit dangerous? I understand that the underlying tracker/clusterer etc is the same, but don't you risk to configure them in different way in respective workflows? So far, we are implementing the workflows where the propagation of MC data is just an option, if it is off, the MCtruth is simply not propagated. Perhaps I misunderstood the comment about the synchronization, but as far as I can see, the separation of workflows will not help to avoid such problems in the MC workflow, where the labels are propagated. 

Cheers,
 Ruben

**Comment by dstocco** [comment]
Hi @shahor02 ,
in the previous configuration I implemented the MC clusters and track labeller as separate devices. 
The cluster labeller (for example) needs to get as input both the digits (which are the clusterizer inputs) and the clusters (which are the clusterizer output). So I needed to broadcast the digits to both the clusterizer and the labeller. Then the labeller needed to wait for the clusterizer to finish processing in order to get the clusters. This led to synchronisation problems because, in the meanwhile the reconstruction chain (which is much faster) was finished and new digits were sent.
Of course, one could put the labeller in the same device as the clusterizer (which is what I do now), and the synchronization problem is gone.
Now, of course one could put a flag to propagate or not the MC truth. But the data and MC workflow are different. The MC workflow starts with the digits reader while the data workflow will start from the RAW reader. Also, when I run the pure reconstruction I initialise the input in such a way that it does not compute the needed information to associate the clusters to the digits (needed for the labeller). All this is done to speed-up the reconstruction.
Otherwise I need to add a certain number of if-conditions in the device in order to initialise things differently if I'm running on data or MC. So, all in all, I'm not sure that one would gain much in keeping the same devices with different conditions for data/MC with respect to separate them from the beginning. 
In addition, if I do so, it means that the data reconstruction workflow must depend on simulation libraries, which is conceptually not so good. I think that @aphecetche was against this as well.
I can further discuss with him on this point.

Cheers,
Diego

**Comment by shahor02** [comment]
Hi @dstocco 
thanks for explanations. Concerning the synchronization problems, I think they should be solved anyway with: the situation when the device needs an input from fast as slow devices is quite standard and we should be able to handle it. Perhaps @ktf or @matthiasrichter can comment.
I was not clear enough in my previous comment: it is obvious that the workflows for MC and raw data will start from different input devices, so the workflows are formally different. But my concern is using different (e.g. clusterizer) devices for MC and data: this is prone to having divergent behaviour in 2 cases. Compared to this, the dependence of the workflow on the sim. libraries even if they are not used in case of raw data reco is a minor issue. 
The way we do it for other reconstruction chain is exactly to check in the processor/writer devices if the MC needs to be propagated and add to add relevant input/output channels to DPL specs. This will allow to use the same device in both MC and raw workflow.

Anyway, we don't have a strict policy on this, so my comment is more an invitation to discuss if we should avoid separate MC and raw data processor devices.

Cheers,
 Ruben

**Comment by ktf** [comment]
@shahor02 @dstocco regarding the unbalanced queues issue. This is on the todo list (admittedly since a while). Hopefully next in the round of cleanups, keeping into account CHEP.

**Comment by dstocco** [comment]
Hi @shahor02 ,
I understand your worries, but the consistency between the MC and data reconstruction is ensured by using the same algorithms (Clusterizer.cxx and Tracker.cxx). Only the Specs change, and account for the different settings needed for MC and data.

For what concerns the dependency on simulation that I would introduce if I use a single Spec for data and MC, for the moment I agree that it is not an issue. But what is the plan for FLP? Do we plan to compile the full O2 (including the simulation specific part, e.g. O2::SimulationDataFormat) on FLP, or will we foresee to only compile the data reconstruction part with the defaults 'dataflow'?
In this second case, the splitting of the workflow will become a necessity for everyone.

**Comment by shahor02** [comment]
@dstocco I was referring to eventual difference in the algorithms configuration from the specs file (at the moment you do just init, so it does not apply so far to your code). Anyway, if you are confident that this will not change I can merge this PR as it is.

Concerning the allowing simulation libraries on the FLP,  the shared code size certainly will not the dominant memory consumer, I don't see why a few extra libraries should harm. Note that separating out the "MC labelers" from the reconstruction algorithms usually will create an overheads for most of detectors compared with filling the MC truth for the reconstructed objects in place (e.g. one should either create temporary containers with cluster -> digits associations or to do lot of extra looping to recover this info from the geometry).

Cheers,
 Ruben

**Comment by dstocco** [comment]
Hi @shahor02 ,
> Anyway, if you are confident that this will not change I can merge this PR as it is
At the moment, I do not see how this could evolve much from the current implementation. Anyways, in the remote case where it will evolve we can always merge back the MC and data in the future (but I do not think it will be the case).
Thanks,
cheers,
Diego

**Comment by aphecetche** [comment]
@shahor02 concerning the separation sim vs rec my position has admittedly always been a bit on the uncompromising side. For instance I would go as far as ensuring that the reconstruction code can _compile_ (also) without any dep to the simulation, so it's not only a matter of runtime dependency but a truly complete separation of concern. But I realize that I'm a bit alone in this (radical) thinking, so I won't fight for it.

**Comment by shahor02** [comment]
@aphecetche this would impose significant overhead on reconstruction of all large detectors...

**Pull request merged**
