### PR TITLE
Introduce o2_add_dpl_workflow

### PR DESCRIPTION
**Pull request by ktf**
Such an helper can be used to generate executables which are
known to be DPL workflows. Besides adding automatically the dependency
on O2::Framework, this helper will also make sure that the workflow
is executed once with the `--dump` flag so that a JSON representation
is generated and put in `${CMAKE_INSTALL_DATADIR}/dpl` for the sake
of consumption by various deployment mechanisms, e.g. the AliHyperloop
infrastructure. Notice it's also valid to start one of those workflows
with:

  o2-dpl-run < $O2_ROOT/share/dpl/some-workflow.json

### CODE REVIEW

**Comment by ktf** [comment]
@aphecetche I probably need some of your cmake-fu to understand how to properly have a target dependency declared as a resource and installed in the proper place, without having to rely on the ALL option.

**Comment by ktf** [comment]
@knopers8 some of the datasampling workflows in Framework/TestWorkflows seem to crash when invoked with --dump. Could you please have a look?

**Comment by knopers8** [comment]
Probably I have to properly install and access the configuration files, I will have a look.

**Comment by ktf** [comment]
Weird. Works fine on checkcode but not on the macOS / linux builds. :-/

**Comment by ktf** [comment]
checkcode and gpu do not test anything in addition. Merging.

**Pull request merged**
