### PR TITLE
HepMC via configurable params, cleanup of deprecated old HepMC version

### PR DESCRIPTION
**Pull request by preghenella**
This PR brings the following features
* clean up the temporary solution to transition to the new HepMC3 version
* HepMC is now configured via `ConfigrableParam` 
* removed the HepMC filename setup via `o2-sim` command line
* updated simulation example
* and documentation

### CODE REVIEW

**Comment by sawenzel** [comment]
This fails in the o2sim_hepmc  test.

**Comment by preghenella** [comment]
yes, I have to fix it.

**Comment by preghenella** [comment]
this PR went out of my radar.
Will be fixed asap.

**Comment by preghenella** [comment]
ok, this made me suffer a bit for a stupid thing.
Hopefully the `o2sim_hepmc` test will pass now.

The issue was that in the `CMakeLists` I needed to pass the `configKeyValue` string with proper `\` 
```
--configKeyValue \"HepMC.fileName=${CMAKE_SOURCE_DIR}/Generators/share/data/pythia.hepmc\;HepMC.version=2\"
```

**Comment by preghenella** [comment]
ok, I found also another issue.
I was using `--configKeyValue` instead of `--configKeyValues`.
Apparently `o2-sim` does not complain about that, but did not pass the parameters properly.
Perhaps to be fixed, best would be not to allow boost to guess the cmd options.

In this PR I also modified other files where `--configKeyValue` was used, to avoid possibile issues.

**Comment by preghenella** [comment]
two tests are failing, but apparently not related to this PR.

`build/o2checkcode/o2` fails with
```
[ 75%] Building CXX object aliceO2/CMakeFiles/clangTidyAliceO2Module.dir/SizeofCheck.cpp.o
CMakeFiles/clangTidyPluginModule.dir/PluginTidyModule.cpp.o: In function `clang::tidy::plugin::PluginModule::addCheckFactories(clang::tidy::ClangTidyCheckFactories&)':
/mnt/mesos/sandbox/sandbox/sw/SOURCES/o2codechecker/master/acafa2477b/plugin/../ClangTidyModule.h:59: undefined reference to `clang::tidy::ClangTidyCheckFactories::registerCheckFactory(llvm::StringRef, std::function<clang::tidy::ClangTidyCheck* (llvm::StringRef, clang::tidy::ClangTidyContext*)>)'
collect2: error: ld returned 1 exit status
```
`build/O2/o2` fails in the test of 
```
=== Framework/Utils/test/test_DPLOutputTest.cxx - Test attempt 3/3 failed with exit code 1 ===
=== Framework/Utils/test/test_DPLOutputTest.cxx - Test failed after 3 attempts with 1 ===
```

**Pull request merged**
