### PR TITLE
adjust to production CCDB

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by jgrosseo** [comment]
Pending https://github.com/AliceO2Group/AliceO2/pull/4811

**Review by iarsene — APPROVED** [review]

**Comment by ktf** [comment]
@TimoWilken we have again the issue where `build/AliPhysics/release` and co are added to the O2 builds, even if they do not apply.

**Comment by ktf** [comment]
Builds macOS and fullCI, merging.

**Comment by TimoWilken** [comment]
@ktf see alisw/ali-bot#856.

**Pull request merged**
