### PR TITLE
CCDB fetcher remapping to different hosts or local files

### PR DESCRIPTION
**Pull request by shahor02**
Allows remapping certain conditions to different hosts or local directories, e.g.
```
 --condition-remap “http://alice-ccdb.cern.ch/user/username:TOF/Calib/LHCPhace,TOF/Calib/Diagnostics;\
http://ccdb-test.cern.ch:8080:ITS/Calib/Align;\
file:///<localDirectory>:GLO/Config/GRPECS” 
```

### CODE REVIEW

**Comment by shahor02** [comment]
Don't merge yet!

**Comment by ktf** [comment]
Wasn't  this supposed to be a feature of CCDB API?

**Comment by shahor02** [comment]
@ktf if you mean using separate CCDBApi instance per host, yes, we could use just one but re-init it every time to a new host. Apart from some overhead of reinitialization, there will be at least 2 extra string comparisons per query (current vs queried host) + check if the host to query is a local dir. (in which case we can skip the query if the object was already cached, since there is no time validity involved).
Do you see a problem with that?

**Comment by shahor02** [comment]
@ktf BTW, what is the purpose of allowing `/` in the remapping? If this is to refer to the local directory, the CcdbAPI expects `file://` for that, which I've added.

**Comment by ktf** [comment]
> @ktf BTW, what is the purpose of allowing `/` in the remapping? If this is to refer to the local directory, the CcdbAPI expects `file://` for that, which I've added.

Yes, that was the idea.

**Comment by shahor02** [comment]
Then, if you don't mind, I would remove it: the format accepted by the CcdbAPI is `file://`.

**Comment by ktf** [comment]
> @ktf if you mean using separate CCDBApi instance per host, yes, we could use just one but re-init it every time to a new host. Apart from some overhead of reinitialization, there will be at least 2 extra string comparisons per query (current vs queried host) + check if the host to query is a local dir. (in which case we can skip the query if the object was already cached, since there is no time validity involved).

Well, the expensive part is the reconnect / SSL negotiation, I guess. So what I was thinking is that we could keep a map of host->curl_handle in the CCDB API and reuse accordingly, which at least would avoid the curl_init_handle reinitialisation. What would really be beneficial is using curl_multi_perform (so that we can have multiple fetches in fly, without using threads) or maybe even a shortlived websocket (but that would require backend support).

**Comment by ktf** [comment]
> Then, if you don't mind, I would remove it: the format accepted by the CcdbAPI is `file://`.

Sure.

**Comment by shahor02** [comment]
> Well, the expensive part is the reconnect / SSL negotiation, I guess. So what I was thinking is that we could keep a map of host->curl_handle in the CCDB API and reuse accordingly, which at least would avoid the curl_init_handle reinitialisation. What would really be beneficial is using curl_multi_perform (so that we can have multiple fetches in fly, without using threads) or maybe even a shortlived websocket (but that would require backend support).

Is there is difference between yet non-existing cashing of host->curl_handles in the CcdbApi or using a cache of CcdbApi instances? In my PR each instance (I would not expect more then 2-3) is initialized only once. Note that currently every change of host, i.e. `CcdbAPI::init(..)` also checks for the alien-token.

**Comment by ktf** [comment]
Indeed, with the current CCDBApi i guess the minimal change is what you have here.

**Comment by ktf** [comment]
Dataflow CS8 worked.

**Comment by ktf** [comment]
@awegrzyn @davidrohr do we still need the dataflow build on CC7?

**Comment by davidrohr** [comment]
For the epn we don't need it.

**Pull request merged**
