### PR TITLE
Fix deprecation in FairROOT dev: Switch to new FairMQMessage::Copy() semantics

### PR DESCRIPTION
**Pull request by mkrzewic**

### CODE REVIEW

**Comment by ktf** [comment]
@brinick can you please tag FairRoot dev branch tip and bump the configuration in alidist for the tagged tests? Thanks.

**Comment by brinick** [comment]
Done

**Comment by matthiasrichter** [comment]
hmm, I hope we don't pick up other problems by changing to the FairRoot dev branch tip, at least there should be more testing. Also we have the problem that some of our CI setups don't use the dev branch. so our CI is any how broken.

**Comment by ktf** [comment]
@matthiasrichter, @brinick's change will be ok for all the CI setups, who all refer to `alidist` to pickup their version (maybe using different defaults, but still nothing is hardcoded in the CI setup). Given this PR seems to be all green, I suggest we approve this and if any issue arises we make it break as a unit test as well.

That said, in this particular case we actually managed to spot the issue immediately, which  I think is the correct behavior. The only possible intermediate step I can think about is first moving to a tag where both APIs are present and not deprecated, so that we can update without breaking tests explicitly on old API usage.

**Comment by ktf** [comment]
Discussed privately with @matthiasrichter . We are actually all on the same page.

**Pull request merged**
