### PR TITLE
Fixes for combining reco workflows

### PR DESCRIPTION
**Pull request by shahor02**
* TPC::TRACKMCLBL make outputSpec names consistent
Depending on the device the Tracks MC labels were called either TRACKMCLBL or TRACSKMCLBL

* TOF workflow: allow disabling root I/O for w-flows merging
In the ``raw`` mode the input from the root files (e.g. TPCITS tracks) should be disabled in favor of direct DPL input from TPC/ITS matcher. Explicitly add option to disable root input and output to be able to merge different workflows.
Fix in tree filling.

--------------------------
Instructions to run (just for the record) combined w-flow:

In ``raw`` data mode:
````
o2-raw-file-reader-workflow --loop 1 --conf raw/rawAll.cfg | o2-itsmft-stf-decoder-workflow |  o2-its-reco-workflow --disable-mc --clusters-from-upstream --disable-root-output  | o2-tpc-reco-workflow --ca-clusterer --input-type=zsraw --disable-mc  --output-type tracks,clusters,disable-writer |  o2-tpcits-match-workflow  --disable-root-input --disable-mc | o2-tof-compressor  | o2-tof-reco-workflow --input-type raw --disable-mc  --run
````

In ``digits`` mode:
````
o2-its-reco-workflow | o2-tpc-reco-workflow  --tpc-digit-reader '--infile tpcdigits.root' --input-type digits --output-type clusters,tracks | o2-tpcits-match-workflow  --disable-root-input --disable-root-output | o2-tof-reco-workflow --disable-root-input --run
````

Preparing raw data:
````
o2-sim -n 10 -m PIPE ITS TPC TOF -g pythia8
o2-sim-digitizer-workflow
mkdir raw
o2-tpc-digits-to-rawzs -i tpcdigits.root -o raw/TPC/
o2-its-digi2raw -c -o raw/ITS/
o2-tof-reco-workflow -b --output-type raw
mkdir raw/TOF
mv cru*rawtof.bin  raw/TOF/

# create a config file, e.g. raw/TOF/TOFraw.cfg (at the moment needs manual intervention)
[input-TOF-0]
dataOrigin = TOF
dataDescription = RAWDATA
filePath = raw/TOF/cru00rawtof.bin
[input-TOF-1]
dataOrigin = TOF
dataDescription = RAWDATA
filePath = raw/TOF/cru01rawtof.bin

[input-TOF-2]
dataOrigin = TOF
dataDescription = RAWDATA
filePath = /home/shahoian/tmp/digfl/pbpb100/raw/TOF/cru02rawtof.bin

[input-TOF-3]
dataOrigin = TOF
dataDescription = RAWDATA
filePath = /home/shahoian/tmp/digfl/pbpb100/raw/TOF/cru03rawtof.bin
#---------------------

# create combined raw data config file:
cat raw/*/*.cfg > raw/rawAll.cfg
````

### CODE REVIEW

**Comment by shahor02** [comment]
@noferini could you add to ``o2-tof-reco-workflow -b --output-type raw`` an option to write a config file (like the one in the instructions above: w/o ``default`` settings to allow configs merging)?

**Comment by shahor02** [comment]
@ktf @MichaelLettrich : the O2 and o2checkode tests went banana...

**Comment by ktf** [comment]
Checking.

**Comment by ktf** [comment]
Ok. The machine which is hosting the repository for the PR checkers is still not up 100%.

**Comment by noferini** [comment]
> @noferini could you add to `o2-tof-reco-workflow -b --output-type raw` an option to write a config file (like the one in the instructions above: w/o `default` settings to allow configs merging)?

I can add this. I will do it once this PR is merged. Is it fine?

**Comment by shahor02** [comment]
@noferini sure, thanks. This is just for general convenience. Note that other converters have also option of the output directory, e.g. https://github.com/AliceO2Group/AliceO2/blob/14393740225f4172ac3c4d13233572062e7c3bfd/Detectors/ITSMFT/ITS/simulation/src/digi2raw.cxx#L105-L112

**Comment by noferini** [comment]
I will add also that.
By the way, from my side this PR is fine.
Since it involves also changes affecting other parts I leave also other reviewers to comment.

**Pull request merged**
