### PR TITLE
DPL Analysis: streamline readers from TTree [O2-968]

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@jgrosseo I think you are missing at least this for the latest incarnation of the AOD file.

@pzhristov we need to decide on a naming convention for the index columns. Shall we settle on "f" + indexed table + "Id"?

**Comment by ktf** [comment]
Ok, I understand the problem. Previously the index column were called "fID4Collisions" and since "Collisions" was the name of the table it could do the mapping. Now the index is called "fCollisionId", without the "s" so the name does not match anymore (we need to drop an s). @pzhristov can we go back to `fID4Collisions`?

**Comment by jgrosseo** [comment]
@ktf Wouldn't it be enough to call it fCollisionsID?

**Comment by ktf** [comment]
If you prefer, yes. The main point is that it needs to have a trivial mapping to the table name.

**Comment by ktf** [comment]
This works for me with a file which has `fCollisionsID` rather than `fCollisionID`. The command to reproduce is:

```
stage/bin/o2-analysistutorial-histograms --aod-file ~/Downloads/AO2D-2.root 
```

and `results.root` will contain the phi / eta histograms.

**Pull request merged**
