### PR TITLE
DPL Inputrecord: fixing compilation error when trying to use get<std::vector<pod>>

### PR DESCRIPTION
**Pull request by matthiasrichter**
There was compilation problem when using the InputRecord API with vectors of
PODs. Adding also a test case to the unit test.

### CODE REVIEW

**Comment by shahor02** [comment]
@matthiasrichter I also get a compilation error when trying to add a branch with ``std::vector<pod>`` to RootTreeWriter. The problem can be reproduced simply by changing 
``using Container = std::vector<o2::test::Polymorphic>;`` to 
``using Container = std::vector<int>;`` in your ``Framework/Utils/test/test_RootTreeWriter.cxx``. The compilation produces (full log [attached](https://github.com/AliceO2Group/AliceO2/files/3899235/cmp.txt)) :
````
/home/shahoian/alice/sw/SOURCES/O2/1.0.0/0/Framework/Core/include/Framework/SerializationMethods.h:55:3: error: static assertion failed: wrapped type can not be a pointer
   static_assert(std::is_pointer<T>::value == false, "wrapped type can not be a pointer");
   ^~~~~~~~~~~~~
````

Happens both with dev and this branch.

**Comment by matthiasrichter** [comment]
Hello @shahor02, right now this is actually by concept. We do not want to use ROOT serialization for `std::vector<pod>`, furthermore the streamer can not be detected at compile time if the ClassDef macros are not used, which is the case for `std::vector<fundamental_type>`.

I will investigate if it is enough to introduce a special type trait handling for vectors of fundamental types. I think in your case you want to have `vector<int>` stored in the branch in order to use macros and TreeViewer. I will try to enhance the ROOTTreeWriter to handle such cases.

There is a way to store the message as a binary blob in a binary branch, you have to specify `BranchDef<const char*>`. The ROOTTreeReader will restore the original message payload. This can be used for storage.

**Comment by matthiasrichter** [comment]
@shahor02 this concerns only the automatically generated streamers for vectors of fundamental types. With the current implementation of `ROOTTreeWriter`, a possible solution is e.g.
```
struct TheIndex {
  int index;

  ClassDefNV(TheIndex, 1)
};
```
and sending/storing `std::vector<TheIndex>`. This is messageable, and at the same time ROOT serializable for the TreeWriter.

**Comment by shahor02** [comment]
@matthiasrichter thanks! What I need is to store a vector<uint32_t> (not for macros/TreeViewer but to have a single container of cluster indices instead of per-track vector<uint32_t> of TrackTPC class (which makes it non-messagable). As a last resort, I can use the struct you suggested, but if takes a couple of days to learn if the TreeWriter can be adapted to trivial types, I better wait: anyway, there is another showstopper with ITS Cluster not being understood to be messagable.

**Comment by matthiasrichter** [comment]
There is more work needed to avoid the copy when extracting the unserialized vector object. In fact this PR only makes sense if this can be solved, the API needs to be corrected otherwise and this PR will be obsolete. Working on a prototype.

**Comment by ktf** [comment]
Is this still needed?

**Comment by matthiasrichter** [comment]
yes, I have now adjusted all conflicting code for #2697 and we can go on with these two PRs. This one is ready for merging once the tests are ok.

**Pull request merged**
