### PR TITLE
Allow to use a configurable delay in MID electronics

### PR DESCRIPTION
**Pull request by dstocco**
The delays were hard-coded until now, but they can change in real life.
This PR allows us to modify them at will.
The commits are atomic: please do not squash.

### CODE REVIEW

**Comment by dstocco** [comment]
@aphecetche : the clang-format code is failing with the following error:
`fatal: ambiguous argument 'Analysis/Core/include/Analysis/PairCuts.h': unknown revision or path not in the working tree.`
I'm not sure what it means since I did not modify this file....

**Comment by aphecetche** [comment]
@ktf you mentioned something about this kind of errors (clang-format running on the wrong set of files if I understood correctly) at the last WP3, didn't you ?

**Review by aphecetche — DISMISSED** [review]

**Comment by ktf** [comment]
Yes, but they should be fixed now. Can you rebase?

**Comment by dstocco** [comment]
Rebasing to trigger the CI...

**Comment by dstocco** [comment]
The clang-format is now good, but gpu fails (rather common) and now Mac compilation fails du to unrelated errors in building the Monitoring package.
@ktf : are those errors known as well?

**Comment by ktf** [comment]
Monitoring issue was introduced by an Xcode update and it was fixed by @awegrzyn today.

**Comment by dstocco** [comment]
@ktf so should I rebase to re-trigger a build?

**Comment by dstocco** [comment]
GPU is still failing: @ktf can this be force-merged?
Thanks!
Cheers,
Diego

**Pull request merged**
