### PR TITLE
FIT: new lib DataFormatsFIT, common for all three FIT subdetectors, new bit added to TCM

### PR DESCRIPTION
**Pull request by afurs**

### CODE REVIEW

**Review by AllaMaevskaya — DISMISSED** [review]

**Review by mslupeck — APPROVED** [review]

**Comment by shahor02** [comment]
Hi @afurs 
The FullCI is at the moment not particularly effective. Since this PR affects raw data, did you run locally the `prodtests/full_system_test.sh` ?

**Comment by afurs** [comment]
> Hi @afurs
> The FullCI is at the moment not particularly effective. Since this PR affects raw data, did you run locally the `prodtests/full_system_test.sh` ?

Hello @shahor02 ,

I just tried to run it:
```
[O2/latest-dev_fit-o2] ~/tmp $> $O2_ROOT/prodtests/full_system_test.sh  
Missing O2sim environment
```

Did I miss some package to load in environment(O2 was loaded at that moment)?

**Comment by shahor02** [comment]
Hi @afurs 
The FST needs the AEGIS package, which should be built and loaded on top of the O2.
Alternatively, you can build O2Sim, which does exactly this.

**Comment by afurs** [comment]
@shahor02 ,

ok, I did it. Here some log from terminal:
```
[O2sim/latest-dev_fit-o2 O2/latest-dev_fit-o2] ~/tmp $> $O2_ROOT/prodtests/full_system_test.sh
Found 16 physical CPU cores
Launching task: o2-sim --seed -1 -j 16 -n1000 -m PIPE ITS MFT FT0 FV0 FDD -g extgen -e TGeant4 --configKeyValues "GeneratorExternal.fileName=$O2_ROOT/share/Generators/external/QEDLoader.C;QEDGenParam.yMin=-7;QEDGenParam.yMax=7;QEDGenParam.ptMin=0.001;QEDGenParam.ptMax=1.;Diamond.width[2]=6." &> qedsim.log &
Launching task: o2-sim --seed -1 -n 10 --configKeyValues Diamond.width[2]=6. -g pythia8hi -e TGeant4 -j 16 &> sim.log &
Launching task: o2-sim-digitizer-workflow -n 10 --simPrefixQED qed/o2sim --qed-x-section-ratio 4343.26 --disable-mc --tpc-lanes 16 --shm-segment-size 8000000000 -b --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0;HBFUtils.orbitFirstSampled=0;HBFUtils.maxNOrbits=128;" --skipDet TRD &> digi.log &
Launching task: o2-sim-digitizer-workflow -n 10 --disable-mc --onlyDet TRD --shm-segment-size 8000000000 -b --incontext collisioncontext.root --configKeyValues "HBFUtils.nHBFPerTF=128;HBFUtils.orbitFirst=0;HBFUtils.orbitFirstSampled=0;HBFUtils.maxNOrbits=128;;TRDSimParams.digithreads=16" &> digiTRD.log &
Launching task: o2-its-digi2raw --file-for link -o raw/ITS &> itsraw.log &
Launching task: o2-mft-digi2raw --file-for link -o raw/MFT &> mftraw.log &
Launching task: o2-ft0-digi2raw --file-per-link -o raw/FT0 &> ft0raw.log &
Launching task: o2-fv0-digi2raw --file-per-link -o raw/FV0 &> fv0raw.log &
Launching task: o2-fdd-digit2raw --file-per-link -o raw/FDD &> fddraw.log &
Launching task: o2-tpc-digits-to-rawzs --file-for link -i tpcdigits.root -o raw/TPC &> tpcraw.log &
Launching task: o2-tof-reco-workflow -b --tof-raw-file-for link --output-type raw --tof-raw-outdir raw/TOF &> tofraw.log &
Launching task: o2-mid-digits-to-raw-workflow -b --mid-raw-outdir raw/MID --mid-raw-perlink &> midraw.log &
Launching task: o2-emcal-rawcreator --file-for link -o raw/EMC &> emcraw.log &
Launching task: o2-phos-digi2raw --file-for link -o raw/PHS &> phsraw.log &
Launching task: o2-cpv-digi2raw --file-for link -o raw/CPV &> cpvraw.log &
Launching task: o2-zdc-digi2raw --file-per-link -o raw/ZDC &> zdcraw.log &
Launching task: o2-hmpid-digits-to-raw-workflow --file-for link --outdir raw/HMP &> hmpraw.log &
Launching task: o2-trd-trap2raw -o raw/TRD --fileper halfcru &> trdraw.log &
Launching task: /home/flp/alice/sw/slc7_x86-64/O2/dev_fit-local10/prodtests/full-system-test/dpl-workflow.sh &> reco_NOGPU.log &
Launching task: /home/flp/alice/sw/slc7_x86-64/O2/dev_fit-local10/prodtests/full-system-test/dpl-workflow.sh &> reco_ASYNC.log &
```
Also a lot of log files were generated, looks ok. Do you want to take a look? I can upload them into CernBox.

**Comment by shahor02** [comment]
Thanks @afurs ! The errors, if any, would have been reported by the top script, so everything looks fine. Merging.

**Comment by afurs** [comment]
@shahor02 , ok, thanks!
BTW, should I make FST for next PRs?

**Comment by shahor02** [comment]
Well, normally it is done automatically by the FullCI, but at the moment it systematically fails. I don't know when it will be repaired, if by the time of your next PR you see that the FullCI is red in al PRs, yes, better to run the test locally.

**Pull request merged**
