### PR TITLE
Modifications to auto-detect and decode link-base zero suppression

### PR DESCRIPTION
**Pull request by wiechula**

### CODE REVIEW

**Comment by wiechula** [comment]
@shahor02 ,
it seems the failing test is unrelated. Can this PR be merged?

**Comment by davidrohr** [comment]
@TimoWilken : The FullCI is failing again with
```
fatal error: error writing to /tmp/ccC0jXok.s: Cannot allocate memory
```
Could you check what is the problem? I assume /tmp is mounted as tmpfs and it runs out of memory?

**Comment by TimoWilken** [comment]
@davidrohr no, nothing special is mounted on `/tmp`, it's just a regular directory under `/`, the docker overlay fs. I assume the builder is running out of memory because it's running too much in parallel... reducing `JOBS` again should probably solve this.

**Comment by davidrohr** [comment]
@TimoWilken @ktf @ihrivnac : Perhaps we can discuss in a CWG3 meeting how we proceed with the memory. Reducing the number of jobs over and over is no panacea, since it increases the CI time significantly, It would be interesting to see what is the average CPU load on the CI servers, to understand if the CPUs are currently properly used. If not, we should actually install more memory and increase the number of jobs.

**Pull request merged**
