### PR TITLE
Add PWGPP directory for common QA tools

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by njacazio** [comment]
@mmazzilli do you agree with the changes?

**Comment by njacazio** [comment]
Hi @mario-krueger what about moving here most of the common QA tools?
(Then we can merge the separate tasks into fewer)

**Comment by mario-krueger** [comment]
Great idea!

**Comment by njacazio** [comment]
> Great idea!

Ok great, let's do this after this is merged then!!

**Review by jgrosseo — APPROVED** [review]

**Review by vkucera — APPROVED** [review]

**Comment by jgrosseo** [comment]
CI unrelated. Merging.

**Pull request merged**
