### PR TITLE
Update runDataProcessing.cxx to allow for `-` and `_` in (`Process`?)`Configurable<bool>` names

### PR DESCRIPTION
**Pull request by cholmcc**

### CODE REVIEW

**Comment by cholmcc** [comment]
`build/O2/o2-dataflow-cs8` failure seems unrelated.

**Comment by ktf** [comment]
@aalkin I think you were saying privately that this happens because we do have some convention on the process options which is not respected? Can you comment here?

**Comment by aalkin** [comment]
@ktf indeed, this code is only applied to process switches, and by default those inherit their names after the process function which cannot contain dashes due to them being C++ identifiers. However, this is not a strict requirement as long as the names are OK to be put in JSON.

@cholmcc could you please change the title to say `ProcessConfigurable` ?

**Comment by jgrosseo** [comment]
I am not against this PR but I don't understand why you, Christian, use instead of normal configurables the ones of process switches?

**Comment by cholmcc** [comment]
> @ktf indeed, this code is only applied to process switches, and by default those inherit their names after the process function which cannot contain dashes due to them being C++ identifiers. However, this is not a strict requirement as long as the names are OK to be put in JSON.

I'm afraid that the above is not entirely correct.  The code in question is _also_ called for regular switches as far as I can tell.    

Take the `O2Physics:PWGMM/Rivet/Tasks/rivet.cxx` workflow, which among other things defines regular (not process) boolean switches like `hepmc-recenter`.   The code in question is called on these options too.    That may not be the intention, but it is what happens, I believe. 

> @cholmcc could you please change the title to say ProcessConfigurable ?

I'm not sure it only applies to `ProcessConfigurable` only - but will change to something similar. 

> I am not against this PR but I don't understand why you, Christian, use instead of normal configurables the ones of process switches?

I don't.  i use _one_ `ProcessConfigurable` in `O2Physics:PWGMM/Rivet/Tasks/rivet.cxx` called `hepmc-no-aux` and that is it.   This is defined _not_ via the relevant pre-processor macro _exactly_ to allow a name scoping to the "family" of "hepmc" (i.e., "hepmc-no-aux" instead of "hepmcNoAux" in line with f.ex. "hepmc-recenter").

Yours,

_Christian_

**Comment by cholmcc** [comment]
BTW, if the fundamental requirement is that option name can be put into a JSON key, then perhaps the regular expression for the option should capture that requirement - perhaps 

    ([^"']+)

That is, anything not a quote or double quote, since JSON keys can be any UTF-8 character string - including white-space and so on.   One could even allow for `'"` if they are properly escaped. 

Just a though. 

Yours,
_Christian_

**Comment by aalkin** [comment]
> The code in question is also called for regular switches as far as I can tell.

@cholmcc absolutely not, this is specifically made to extract configuration parameter name from the string metadata attached to inputs, that is placed there based on process switches only. You can look at O2Physics codebase and find plenty of configurables with dashes and underscores.

**Pull request closed without merging**
