### PR TITLE
DPL: provide unique DDS id as --id when running with --dds

### PR DESCRIPTION
**Pull request by ktf**
This makes sure the XML is generated with the template macro
we then need to make sure FairMQ sees a unique id across the whole
DDS deployment.

### CODE REVIEW

**Comment by ktf** [comment]
@AndreyLebedev @davidrohr as discussed...

**Comment by davidrohr** [comment]
@ktf : I think this works only with standalone workflows but not with merged workflows.
`o2-dpl-raw-proxy --dds` does what it should but `o2-dpl-raw-proxy | o2-dpl-run --dds` does not work.

**Comment by ktf** [comment]
Ok, should be fixed.

**Comment by davidrohr** [comment]
This seems to work correctly now, at least looking at the XML file.
Still need to test the generated XML on the EPNs.

**Review by davidrohr — APPROVED** [review]
works on the EPN, should go in tomorrows nightly

**Pull request merged**
