### PR TITLE
Add initial benchmark for analysis

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ginnocen this should be a reasonable attempt for a first benchmark. you should then be able to cut & paste the results in my google docs sheet and it should update plots directly.

**Comment by ginnocen** [comment]
Thanks @ktf! I also tried to use simply "time" as you suggested yesterday and the results do not look bad.  I will give you more details soon 👍

**Comment by ktf** [comment]
@davidrohr @MichaelLettrich can you reduce the number of iterations in your benchmark so that they do not go above the time limit?

**Comment by davidrohr** [comment]
@ktf : I didn't follow this up. What benchmark are you talking about?

**Comment by ktf** [comment]
gpu tests fail because of:

```bash
407/411 Test  #22: test_GPUsortCUDA ...............................................................***Failed    0.17 sec
=== test_GPUsortCUDA - Starting test. Max attempts: 3. Timeout per attempt: 100. ===
=== test_GPUsortCUDA - Argument: --name ===
=== test_GPUsortCUDA - Argument: test_GPUsortCUDA ===
=== test_GPUsortCUDA - Argument: --max-attempts ===
=== test_GPUsortCUDA - Argument: 3 ===
=== test_GPUsortCUDA - Argument: --timeout ===
=== test_GPUsortCUDA - Argument: 100 ===
=== test_GPUsortCUDA - Argument: -- ===
=== test_GPUsortCUDA - Argument: /mnt/mesos/sandbox/sandbox/sw/BUILD/2f769f1162e657679d1caba6d4c62f2816822675/O2/stage/tests/o2-test-gpu-GPUsortCUDA ===
```

and a similar one for HIP. Can we reduce the size of that test so that it fits the limit? I think this is more for @MichaelLettrich.

**Comment by davidrohr** [comment]
@MichaelLettrich : Why are these tests actually run? Does it run on a GPU-enabled server?
If not, we are just benchmarking std::sort.
For only a sanity check, I also think we should indeed reduce the test size.

**Comment by MichaelLettrich** [comment]
Hi, sorting 100 elements should not be a problem, especially for a sanity check. Nevertheless - the tests should only be compiled if CUDA and HIP are present but they never should run.

**Comment by davidrohr** [comment]
@MichaelLettrich :
1.: Why do you say they shouldn't be run? If they are added as test, I think they are run automatically. I think one can only disable them explicitly.
2.: Agreed, 100 elements shouldn't take that long. Are you sure it is only 100. But again, is it running on the GPU at all. Perhaps it is stuck somewhere else, not while sorting the 100 elements?

**Comment by MichaelLettrich** [comment]
Also I now don't see the problem anymore. Was there a possible glitch? 
CTests are executed using 
```ctest -E '(test_Framework)|(test_GPUsort(CUDA|HIP))' --output-on-failure -j 7```
and only 409 tests instead of the 411 tests you reported are run.

**Comment by MichaelLettrich** [comment]
I am wondering why the tests should even be able to run tbh, they should fail by default because there is no machine with GPUs and both HIP and CUDA tests are platform dependent  `.cu` and `.hip.cxx` files which launch kernels. This is why they should not run.

**Comment by MichaelLettrich** [comment]
Yes, also fully sure it is just 100 elements.

**Comment by davidrohr** [comment]
Ah, wait, forgive my ignorance.
The tests are indeed disabled, but on alidist level:
```
ctest -E "(test_Framework)|(test_GPUsort(CUDA|HIP))" --output-on-failure ${JOBS+-j $JOBS} || TESTERR=$?
```
in `alidist/o2.sh`
So @ktf: where did you get the timeout you pasted above? It shouldn't happen in the normal CI.

**Comment by ktf** [comment]
It happens in the GPU one, indeed, which still runs somewhere without a GPU...

**Comment by ktf** [comment]
(it passed now, BTW)...

**Comment by davidrohr** [comment]
@ktf: But that is weird. When I checked a second ago the log file of the GPU CI that had passed, it didn't run these GPU tests in the GPU CI. And also other PRs don't run the tests. As said above, they are disabled on alidist level. So why did it run the test in the case you pasted above where it failed. That is fully unclear to me. It shouldn't run it.

**Comment by MichaelLettrich** [comment]
@ktf  I was also surprised to see that because it is as @davidrohr said: these tests are disabled on alidist level and should not run and I could not find any evidence of these tests even running in the logs.

**Pull request merged**
