### PR TITLE
add explicit functions to create sampler and sink specs

### PR DESCRIPTION
**Pull request by aphecetche**
Hi,

Not a big deal, but I had those small mods in my drawer. Would make it a tiny bit more immediately clear  what is what in a workflow declaration code.

### CODE REVIEW

**Comment by ktf** [comment]
I suppose some issue with C++17 and clang-tidy.

**Comment by aphecetche** [comment]
The parameter position is simply to follow the original position of the DataProcessorSpec ctor.

I can of course move that code in a separate header. Will do.

I don't see how you can automatically connect e.g. a dangling input to a file reader for instance : how do you know which file reader is able to read that particular data ? Or do I misunderstand "connect by default" ?

**Comment by ktf** [comment]
My idea was to make this configurable from the command line (with some sensible defaults). The source or the sink would still be DataProcessors. Let me publish a WIP PR for what I had in mind for the sink.

**Comment by ktf** [comment]
Regarding the order, you have `<inputs>`, `<algo>` and `<algo>`,`<outputs>`, however the order in the `DataProcessorSpec` is `<inputs>`, `<outputs>`, `<algo>`. That said, I was thinking that maybe the correct approach is to have some template magic that allows you to specify things in the order you prefer, possibly omitting some field.

**Comment by matthiasrichter** [comment]
I think, the option-part of the spec should also be passed, many of the processor specs will have options. Can be again some template magic to be flexible.

**Comment by sawenzel** [comment]
What is the status here? Is this useful, being followed up elsewhere or should we close it?

**Comment by ktf** [comment]
I have an idea on how to make this generic. Kinda like what happens in #1549. @aphecetche how critical is this for your code?

**Comment by aphecetche** [comment]
Hi,

Not critical at all. As said, was merely a "thing I had in my code drawer". I guess this can be closed.

**Pull request closed without merging**
