### PR TITLE
TRD hits

### PR DESCRIPTION
**Pull request by sawenzel**
* Update TRD with a basic but functional version of hit creation
* demonstrate hit creation across detectors in a first version of a global o2sim macro

### CODE REVIEW

**Comment by sawenzel** [comment]
@ktf, @dberzano : One of the PR checks fails with a compilation error in lhapdf.

**Comment by dberzano** [comment]
We know, I am working on that.

**Comment by sawenzel** [comment]
@dberzano : Thanks!

**Comment by dberzano** [comment]
It's fixed now, it will clear out automatically.

**Pull request merged**
