### PR TITLE
DPL: add support for string_view in Variant

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ginnocen this should allow you to write `Configurable<std::string_view> foo`, however it's not working yet, and returns an empty string when used. Investigating.

**Comment by ktf** [comment]
@ginnocen this works.

**Comment by ginnocen** [comment]
Hi Giulio, thanks I will give it a try😀! GM

**Comment by ktf** [comment]
Ma vai a dormire! :-)

**Comment by ginnocen** [comment]
Hi @ktf, i confirm that it works fine! thanks

**Pull request merged**
