### PR TITLE
CTF name contains run, TF 1st orbit and ID, + misc fixes

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
@davidrohr @sawenzel Do you understand what exactly it fails to load in fullCI QED generation?
````
qedsim.log:[ERROR] Uncaught exception reached the top of main: An error occurred while loading static plugin config: boost::dll::shared_library::load() failed (dlerror system message: /mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5899-1/bin/o2-sim-primary-server-device-runner: cannot dynamically load executable): Bad file descriptor
````
I suspect that from time to time if fails to load the AEGIS libs.

**Comment by davidrohr** [comment]
@sawenzel: the log output you requested should now be there. Could you have a log.

**Comment by davidrohr** [comment]
I compared a bit the logs of this PR here (which failed) and #5890, where the Full CI succeeded. And I do not see any difference wrt. AEGIS. They both have the same `$VMCWORKDIR` set (`/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/O2/5899-1/share`) and both have the same AEGIS path (`/mnt/mesos/sandbox/sandbox/o2-fullci/sw/slc8_x86-64/AEGIS/v1.4-1/lib`) in their `$LD_LIBRARY_PATH`.
So I am pretty puzzled what is the difference, and why this fails.

@sawenzel : Which files from AEGIS and from O2_INSTALL_ROOT/share do we actually need for the simulation? Perhaps I can do an ls on these folders inside the recipe to check whether they are there?

Can we find out which library does it actually fail to load? I have checked for calls to `boost::dll::shared_library::load()` inside O2 but I cannot find any, so I assume the problem appears somewhere downstream.

@shahor02 : I am merging this despite this error, since this error appears only randomly, and this PR at least fixes the problem with the wrong TRD option which makes all PRs fail.

**Comment by shahor02** [comment]
@davidrohr The share/Generators/external/QEDLoader.C loads libTEPEMGEN from the AEGIS, and triggers compilation of share/Generators/external/QEDepem.C

**Pull request merged**
