### PR TITLE
Improving sensitive hit creation for HMPID in Detector.cxx

### PR DESCRIPTION
**Pull request by zovarga**
- For HMPID the `Detector::ProcessHits(FairVolume* v)` function had too many string comparisons which made it slow. The comparison was modified to be based on integer IDs instead.
- The new integer IDs have been defined in Detector.h, then added to Detector.cxx (modified functions: `Detector::InitializeO2Detector()` and `Detector::ProcessHits(FairVolume* v)`).
- The calculation of chamber number (idch) in `Detector::ProcessHits(FairVolume* v)` has been modified to be based on volume IDs.

### CODE REVIEW

**Comment by shahor02** [comment]
@zovarga the fullCI complains are genuine, could fix:
```
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:91:32: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:93:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:95:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:97:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:99:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:101:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:103:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:142:32: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:144:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:146:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:148:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:150:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:152:37: error: statement should be inside braces [readability-braces-around-statements]
/sw/SOURCES/O2/8340-slc8_x86-64/0/Detectors/HMPID/simulation/src/Detector.cxx:154:37: error: statement should be inside braces [readability-braces-around-statements]
--
```

**Comment by zovarga** [comment]
Hello @shahor02, thank you for checking my PR. I fixed the fullCI complain.

**Comment by shahor02** [comment]
Hi @zovarga 

Now there are some conflicts, could you check if rebasing to dev reveals them? If not, I will do manual merge tomorrow.

**Comment by zovarga** [comment]
Hi @shahor02, now it looks good.

**Pull request merged**
