### PR TITLE
Use as UserField 2 bytes of TrackPar lost for alignment padding

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by shahor02** [comment]
@preghenella @sawenzel the CI failures in ``o2sim_hepmc`` are real but I cannot reproduce it on ubuntu:
````
=== o2sim_hepmc - Running /mnt/mesos/sandbox/sandbox/sw/BUILD/d933b979257be98dd66a2b1e465d0bf222302209/O2/stage/bin/o2-sim with args -n 2 -j 2 -g hepmc --configKeyValues HepMC.fileName=/mnt/mesos/sandbox/sandbox/sw/SOURCES/O2/4479/0/Generators/share/data/pythia.hepmc;HepMC.version=2 -o o2simhepmc (attempt 1/3) ===
=== o2sim_hepmc - Process running as 16578 for attempt 1 ===
[INFO] Running with 2 sim workers 
[INFO] CREATING SIM SHARED MEM SEGMENT FOR 2 WORKERS
Spawning particle server on PID 16595; Redirect output to serverlog
Spawning sim worker 0 on PID 16597; Redirect output to workerlog0
Spawning hit merger on PID 16598; Redirect output to mergerlog
[INFO] DISTRIBUTING EVENT : 1
[INFO] DISTRIBUTING EVENT : 2
[INFO] EVENT FINISHED : 1
/mnt/mesos/sandbox/sandbox/sw/BUILD/d933b979257be98dd66a2b1e465d0bf222302209/O2/tests-wrapper.sh: line 130: /usr/bin/sleep: Argument list too long
[INFO] Merger process 16598 returned
[INFO] Simulation process took 87.0933 s
Error in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libRIO, output: $ROOT_DYN_PATH/libRIO
Error in <TSystem::ExpandFileName>: input: $ROOT_DYN_PATH/libCling, output: $ROOT_DYN_PATH/libCling
Warning in <TFile::Init>: file o2simhepmc_Kine.root probably not closed, trying to recover
Warning in <TFile::Init>: no keys recovered, file has been made a Zombie
````

**Comment by preghenella** [comment]
hi @shahor02 ,
I will try to have a look at it, but it has been working fine so far.

**Comment by shahor02** [comment]
failures in o2sim_hepmc are unrelated, merging.

**Comment by preghenella** [comment]
@shahor02 FYI
```
DEBUG:O2:O2:0: 322/325 Test #288: o2sim_hepmc ....................................................................   Passed   87.68 sec
```
on Ubuntu 20.04.
Next I will check on CC7

**Comment by shahor02** [comment]
I know, I also have no problem on ubuntu. But on build servers it fails in all PRs, in all tests.

**Comment by preghenella** [comment]
the test is passed also on CC7
```
2020-10-01@14:08:17:DEBUG:O2:O2:0: 324/325 Test #288: o2sim_hepmc ....................................................................   Passed  190.77 sec
```

**Pull request merged**
