### PR TITLE
[WIP] Testing Mattermost integration.

### PR DESCRIPTION
**Pull request by MichaelLettrich**
Testing. Don't panic.

### CODE REVIEW

**Comment by davidrohr** [comment]
fyi: You can indicate that a PR is not meant for mering right now by prepending the title with "[WIP]"

**Comment by MichaelLettrich** [comment]
does that do anything?

**Comment by davidrohr** [comment]
yes, it cannot be merged, and people will more or less ignore it while it's called [WIP], and won't review it.

**Comment by MichaelLettrich** [comment]
Another irrelevant test message to mattermost.

**Pull request closed without merging**
