### PR TITLE
Avoid copy of tracks

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@shahor02 @mconcas am I missing something trivial?

**Review by shahor02 — APPROVED** [review]
To me looks fine. Given that the total number of tracks to store is known after the https://github.com/AliceO2Group/AliceO2/blob/6d19642f6d08061f923f4abb052ebfa939c959c6/Detectors/ITSMFT/ITS/workflow/src/TrackerSpec.cxx#L271, one can put after this line:
```
size_t totTracks = 0, totClusIDs = 0;
for (size_t ir=0; ir<rofs.size(); ir++) {
  const auto& tracks = mTimeFrame->getTracks(ir);
  totTracks += tracks.size();
  for (const auto& trc : tracks) {
    totClusIDs += trc,getNumberOfClusters();
  }
}
allTracks.reserve(totTracks);
allClusIdx.reserve(totClusIDs);
irFrames.reserve(rofs.size());
vertROFvec.reserve(rofs.size());
```

With a little bit more permutations one can have all outputs made with `make<...`> and reserve correct sizes before filling them. 
The same for GPUWorkflowITS.

Perhaps it is better to merge your PR then I or @mconcas fix the rest.

**Comment by mconcas** [comment]
I can take care of that tomorrow

**Comment by ktf** [comment]
Ok, merging this since it passes all tests. I will let you have fun with the rest.

**Comment by ktf** [comment]
@chiarazampolli this is one of the PRs I was talking about.

**Pull request merged**
