### PR TITLE
DPL Data Model: introduce bit to keep track of data created after EoS

### PR DESCRIPTION
**Pull request by ktf**
DPL Data Model: introduce bit to keep track of data created after EoS

### CODE REVIEW

**Comment by ktf** [comment]
This will fingerprint the data which is created by DPL itself and not injected by the first device in the chain. A separate PR will take care of adding the extra timers for the new calibration handling and dropping the data coming from data taking.

**Comment by ktf** [comment]
@singiamtel xcursor is also not available...

**Comment by singiamtel** [comment]
> @singiamtel xcursor is also not available...

Added it https://github.com/alisw/docks/commit/e8046e9b2f89cb83e9695d04a48a8fe52ec54de2

 I don't understand why these libs weren't a problem before, are they new dependencies that we failed to catch before the merge?

**Comment by ktf** [comment]
I suspect before they were picked up when building the full release in the jenkins machine, which probably has the o2-full-deps RPM installed. Maybe we should consolidate to install o2-full-deps. Can you have a look at what it would take?

**Pull request merged**
