### PR TITLE
DPL: set run number in start rather than in init

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
Updated to fix the warning / error.

**Review by davidrohr — COMMENTED** [review]
Why don't you do both? If it is already avaialble at init time, messages at that time will already be flagged correctly. Then you overwrite it at start.

**Comment by vascobarroso** [comment]
@davidrohr the run number is only available at start, not before.

**Comment by davidrohr** [comment]
ah, ok, that makes sense. I though it might be different between EPN and FLP, but it is by design...

**Pull request merged**
