### PR TITLE
Add attempted code owner for MUON

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@ihrivnac @aphecetche I guess we agree on this.

**Comment by ktf** [comment]
@ihrivnac unless you strongly object, I would try to merge this and similar PRs without having to wait for the full list of interested parties, because otherwise I get spammed as "fall back solution".

**Comment by ktf** [comment]
Apart from the fact that I do want to be notified as "core" if some of the top-level files change (e.g. the travis and codecov stuff), removing core means that people will be able to add new files and folders at top-level, which for sure we want to catch.

**Comment by ktf** [comment]
What is the issue with the incremental approach, out of curiosity?

**Comment by ihrivnac** [comment]
I did not propose to remove core.
The global approach (which was setup in the WIP PR) would have the advantage that we would keep all comments/discussion related to this at a single place.

**Comment by ktf** [comment]
Can't we have a JIRA ticket for that?

**Comment by ihrivnac** [comment]
The JIRA ticket already exists (was create at the same time as the WIP PR):
[O2-816](https://alice.its.cern.ch/jira/browse/O2-816)

**Comment by ktf** [comment]
Anyways, as you prefer. If it's matter of a few days I guess I can survive with a few extra emails.

**Comment by sawenzel** [comment]
This is now part of #2357. I guess we can close this.

**Pull request closed without merging**
