### PR TITLE
[MFT] Fix digi2raw output segmentation

### PR DESCRIPTION
**Pull request by rpezzi**
This PR adapts the MFT MC to raw converter to produce one file per CRU endpoint. `o2-mft-digi2raw --file-for cru` produces the following raw files:

```
MFT_alio2-cr1-flp182_cru567_0.raw
MFT_alio2-cr1-flp182_cru567_1.raw
MFT_alio2-cr1-flp182_cru570_0.raw
MFT_alio2-cr1-flp182_cru570_1.raw
MFT_alio2-cr1-flp183_cru548_0.raw
MFT_alio2-cr1-flp183_cru548_1.raw
MFT_alio2-cr1-flp183_cru554_0.raw
MFT_alio2-cr1-flp183_cru554_1.raw
MFT_alio2-cr1-flp184_cru543_0.raw
MFT_alio2-cr1-flp184_cru543_1.raw
MFT_alio2-cr1-flp184_cru569_0.raw
MFT_alio2-cr1-flp184_cru569_1.raw
MFT_alio2-cr1-flp185_cru541_0.raw
MFT_alio2-cr1-flp185_cru541_1.raw
MFT_alio2-cr1-flp185_cru552_0.raw
MFT_alio2-cr1-flp185_cru552_1.raw
MFT_alio2-cr1-flp186_cru542_0.raw
MFT_alio2-cr1-flp186_cru542_1.raw
MFT_alio2-cr1-flp186_cru547_0.raw
MFT_alio2-cr1-flp186_cru547_1.raw
```

### CODE REVIEW

**Comment by shahor02** [comment]
Hi @sawenzel, @davidrohr ,
 
If I interpret the fullCI log correctly, it has failed due to the analysis test returning 1 instead of 1, which seems to be something recently added:
```
++ SIM_CHALLENGE_ANATESTING=ON
++ /sw/slc8_x86-64/O2/8052-slc8_x86-64-local1/prodtests/sim_challenge.sh
++ grep 'Return status' sim-challenge.log
++ grep -v ': 0'
Return status of MCHistograms: 1
++ false
```

**Comment by benedikt-voelkel** [comment]
Hej @shahor02 
The analysis testing was not working properly actually and we fixed that for the first in https://github.com/AliceO2Group/AliceO2/pull/8046. After that, the introduction of the versioned MCParticle table caused a failure of the analysis tests in the fullCI. @jgrosseo fixed everything related to that and it was tested again (with 2 other analyses failing for related reasons).
In https://github.com/AliceO2Group/AliceO2/pull/8054 we see that all analyses pass now. So also here it should be green when tested again I reckon.
I will propagate this info tomorrow to one or two appropriate mattermost channels.

For clarification: The expected return value is `0` in which case no output is printed.

**Comment by davidrohr** [comment]
I don't really understand how this change in digi2raw can break the sim challenge.

**Comment by davidrohr** [comment]
OK, thx, that explains it, will wait for the CI to rerun and then merge.

**Comment by shahor02** [comment]
Hi @benedikt-voelkel 
thanks for the info (I had typo in my comment, should have been `failed due to the analysis test returning 1 instead of 0`). I see that the test finished in the morning, let's see if at next test it gets green.

**Review by davidrohr — APPROVED** [review]
tested, and output looks good.

**Pull request merged**
