### PR TITLE
PWGHF: Fix Dplus selector device name

### PR DESCRIPTION
**Pull request by fcatalan92**
@vkucera From my understanding of the mattermost discussion, this is the new approach to follow.

P.S. What is currently in the O2 dev for `HFDplusToPiKPiCandidateSelector` has to be updated in any case

### CODE REVIEW

**Review by ginnocen — DISMISSED** [review]

**Review by vkucera — COMMENTED** [review]
I don't think these are the needed changes. The device names are used also for the histogram directories in the output files so any change of the device name will need to be propagated to the validation framework.
If I understand the name generating algorithm correctly, this would result in the following changes:
`hf-dplus-topikpi-candidate-selector` -> `h-f-dplus-to-pi-k-pi-candidate-selector`
`hf-task-dplus` -> `task-d-plus`
`hf-task-dplus-mc` -> `task-d-plus-m-c`
And I don't think that's what we want.
The proper changes will require renaming the `struct` names so that the device names stay the same if possible and I would prefer to do it centrally, in one go for all the HF code and for the validation framework.
@ginnocen What do you think?

**Comment by ginnocen** [comment]
hi @vkucera @fcatalan92 I am fine if we want to do it centrally in one shot.

**Comment by ginnocen** [comment]
@fcatalan92 I converted it to draft. But should we close it at this point?

**Comment by fcatalan92** [comment]
Hi @ginnocen, fine for me if the renaming is done centrally. I just updated this PR keeping only a small fix to align to the current O2 code

**Pull request closed without merging**
