### PR TITLE
Noise mc hdigitizer

### PR DESCRIPTION
**Pull request by mwinn2**
- Simple implementation of electronic noise for mch
- parameters still to be tuned in a later step

### CODE REVIEW

**Comment by aphecetche** [comment]
@mwinn2 seems you have genuine compilation error in this PR

**Comment by sawenzel** [comment]
Tests are passing now. Let's wait for @aphecetche to approve.

**Comment by sawenzel** [comment]
@aphecetche : Could you take a look here, pls?

**Comment by aphecetche** [comment]
@sawenzel will have a look next week (it's unfortunate but Michael and myself got completely out-of-sync with the holidays ;-: I'm just getting back and Michael is now off until ~end of august)

**Comment by sawenzel** [comment]
This PR needs proper rebasing to dev.

**Comment by aphecetche** [comment]
@mwinn2 could you please rebase this one to dev ?

**Comment by mwinn2** [comment]
@aphecetche @sawenzel 
Apologies for the long silence, I didn't catch a calm moment to work sufficiently long to make it earlier. 
I am opening a new merge request, since I messed up the branch .

**Pull request closed without merging**
