### PR TITLE
changing printf to LOG

### PR DESCRIPTION
**Pull request by chiarazampolli**
Pinging @davidrohr  and @noferini .

@noferini : I changed the printf to LOG(INFO) or LOG(DEBUG) according to my feeling... You can clearly change this. 
@davidrohr : when we print the info on the stopwatch, will this work for you:

```
   mTimerTot.Stop();
-  printf("Timing:\n");
-  printf("Do Matching:        ");
+  LOG(INFO) << "Timing:\n";
+  LOG(INFO) << "Do Matching:        ";
   mTimerTot.Print();
```

### CODE REVIEW

**Comment by davidrohr** [comment]
I believe the `TStopWatch::Print` will also just print to stdout?
Don't know if that can be changed? One can of course use LOG(INFO) << "CPU time: " << mTimerTot.CpuTime() << " Real time: " << mTimerTot.RealTime() << std::endl;` But that is a bit annoying if repeated in many places.

**Comment by chiarazampolli** [comment]
I think it will print in the stdout, yes. Look, I will do as you suggest, annoying but it won't take longer than a few minutes.

**Comment by shahor02** [comment]
@chiarazampolli I use: https://github.com/AliceO2Group/AliceO2/blob/3232790562a72eb263fd622be99ea43c39f8d3da/Detectors/ITSMFT/common/workflow/src/STFDecoderSpec.cxx#L153-L154

**Comment by chiarazampolli** [comment]
I wanted also to add the counter, but then I decided not to. 
I can change to have the same format as you, give me a minute.

**Pull request closed without merging**
