### PR TITLE
Mch mapping helpers

### PR DESCRIPTION
**Pull request by aphecetche**

### CODE REVIEW

**Comment by aphecetche** [comment]
I guess the "c++: internal compiler error: Killed (program cc1plus)" has nothing to do with the PR itself ?

**Comment by davidrohr** [comment]
Often this means the ci ran out of memory

**Comment by aphecetche** [comment]
@davidrohr will the build/O2/o2 be attempted again automatically at some point, or do I have to do something ?

**Comment by davidrohr** [comment]
It will retry automatically after a while. You can do a forced push with a different commit hash to move it to the beginning of the queue to speed things up.

**Comment by aphecetche** [comment]
ok, it did reran, but now it's build/o2checkcode/o2 which is failing, on a phos test. How can that be ?

**Comment by aphecetche** [comment]
@sandro any idea what's wrong here ?

**Comment by sawenzel** [comment]
No idea what introduced this CI failure. We ignore it.

**Pull request merged**
