### PR TITLE
SIM: Prefer detector list by default

### PR DESCRIPTION
**Pull request by f3sch**
Hi @sawenzel, now the detectorList is always preferred. I checked that:

1. 'o2-sim -m FOC' does not work
2. 'o2-sim -m FOC --detectorList ALICE2' does not work
3. 'o2-sim -m FOC --detectorList ALICE2.1' works
4. 'o2-sim --detectorList ALICE2' works
5. 'o2-sim --detectorList ALICE2.1 --skipModules ITS' does not
6. 'o2-sim --detectorList ALICE2.1 --skipModules IT3' works

I am not sure how to properly deprecate the 'isRun5' option for the grp-tool since it does not make sense  with this.

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
Thanks @f3sch !

Let's say I do
```
o2-sim --skipModules ZDC
```

would that build FOCAL?

If so, I think it should be changed to **not** building FOCAL in that case because it would mean that we need to change all official scripts, some code running on the GRID etc.

**Comment by f3sch** [comment]
Hi @benedikt-voelkel, no as you can see in the detector list for 'ALICE2' there is no FOCal hence it would not be built.
To clarify, previously '--detectorList' was _completely_ optional and not used unless explicitly specified. The performance regression observed in simulation is AFACIT due to #13225. FOCal was since probably its introduction or move away from 'ENABLE_UPGRADES' always built and simulated in official scripts _if_ '-m' defaulted to 'all'.

**Comment by f3sch** [comment]
One ugly thing right now is that by using for example
``` bash
o2-sim --skipModules ZDC --detectorList ALICE2.1
[INFO] This is o2-sim version 1.2.0 (a067a54d92)
[INFO] Built by ALIBUILD:1.17.2, ALIDIST-REV:0278f039799d7e54417169944b5ae7c8055b473d on OS:Darwin-23.5.0
[INFO] BINDING TO ADDRESS ipc:///tmp/o2sim-notifications-78232 type pub
[INFO] Running with official detector version 'ALICE2'
[INFO] Running with official detector version 'ALICE2.1'
[INFO] Running with official detector version 'ALICE2'
[INFO] Running with official detector version 'ALICE2.1'
```

you can see that there are multiple calls `SimConfig::resetFromParsedMap` with different arguments. While not nice it does the right thing, I am not entirely sure where these other calls come from and if this should be improved, e.g., the logging?

**Comment by benedikt-voelkel** [comment]
Perfect, thanks!
Understood 👌

**Review by sawenzel — DISMISSED** [review]

**Review by sawenzel — DISMISSED** [review]

**Pull request merged**
