### PR TITLE
[QC-356] Data Sampling: increase the maximum amount of allowed policy inputs

### PR DESCRIPTION
**Pull request by knopers8**

### CODE REVIEW

**Comment by knopers8** [comment]
@Barthelemy @JianLIUhep

**Comment by Barthelemy** [comment]
will the next increment be 999 ?  :)

**Comment by Barthelemy** [comment]
I cannot approve but I approve

**Comment by knopers8** [comment]
yes, this way we keep our jobs

**Comment by ktf** [comment]
Maybe we should move DataSampling in a separate package and give you access (or simply give you access to framework)/

**Comment by knopers8** [comment]
Yes, actually i was also considering something like that (for example moving them to Utilities).

**Comment by knopers8** [comment]
The failing test is unrelated, the rest are green.

**Comment by Barthelemy** [comment]
@ktf Any idea why I cannot simply merge but I have to use my administrator privileges ?

**Comment by Barthelemy** [comment]
I think that you have to approve

**Comment by ktf** [comment]
Seems to require two approvals.

**Comment by ktf** [comment]
Ah, yes, it's because it modifies Framework.

**Pull request merged**
