### PR TITLE
Fix O2-2843: handling empty rofs

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by mpuccio** [comment]
@shahor02 , I confirm that I obtain the exact same result on MC and that the processing of the cosmics data you gave me does not crash. Ready to be merged as soon as the CI is green.

**Review by shahor02 — DISMISSED** [review]
Thanks! Code looks fine, will merge after CI has passed.

**Comment by mpuccio** [comment]
@shahor02 I think the fullCI is failing for a unrelated issue

**Comment by shahor02** [comment]
The fullCI did not rerun yet after fixing the alien-token. Did you try the reconstruction locally?

**Comment by mpuccio** [comment]
Yes, and I get the same results before and after (I used the simulations from alibi to check, thanks to Benedikt)

**Review by shahor02 — APPROVED** [review]
fullCI failure is unrelated

**Pull request merged**
