### PR TITLE
On the fly converter from RUN2 ESDs to RUN3 AOD format

### PR DESCRIPTION
**Pull request by ktf**
This adds a standalone copy of the Run 2 ESD event model so
that we can have a standalone converter for DPL in O2. This
allows us to start working on Run 3 AOD-like analysis using
Run2 data.

None of the headers are meant for inclusion in other packages
and the package itself does not expose any public interface but
the one required to build the converter.

### CODE REVIEW

**Comment by davidrohr** [comment]
Just wondering whether it is ideal to have a copy of all these files in O2. Couldn't we just build O2 v.s. AliRoot for such cases?

**Comment by ktf** [comment]
@pzhristov @ginnocen this is the converter I was talking about.

Please, have a look at:

Framework/Run2ESDConverter/src/o2AODRun2ESDReader.cxx

for and example of how to set it up (for now) to write a Run3 style analysis which derives data from Run2 ESDs. For the moment only RDataFrame is supported, next natural step would be to have other options for data navigation.

**Comment by ktf** [comment]
@davidrohr I do not have a strong very strong opinion, however I think people objected against having AliRoot as a dependency already twice in the last three years, so I think this might converge faster. This is also my preferred solution because:

* It limits the ability to reuse old code forcing people to think when they want to port stuff from AliRoot.
* It's only less than 1/10 of the size of AliRoot and it compiles in 3 minutes on my 2015 laptop.
* They sync with the upstream AliRoot happens via a script, so that maintenance cost should be limited.

I would actually strip it down even further, e.g. I would be even more aggressive and remove all the methods `AliESDEvent.h` which I do not need for the converter and hence reduce the files to be copied.

Given this is fully self contained, I would propose we go ahead with this (once I fix the last compilation issues) and then schedule a WP3 meeting (@dberzano) to decide what is the best strategy.

**Comment by davidrohr** [comment]
Sure, I agree to all your points and perhaps it is indeed bad to have AliRoot as a dependency. Still don't like copying files :|
Perhaps this could be done at build-time automatically?

**Comment by ktf** [comment]
If you mean at "make" time, I am strongly against that option, as that's the most fragile solution of all I've experienced with over the years. It's complicated to catch errors, it does not work reliably when disconnected and it makes revisioning complicated. Frankly to me there are only two viable options:

* Depend on AliRoot
* This one

If you are worried about people modifying the copy, I would suggest we have a check which assures no one can get his PR merged if one of the old files is touched.

**Comment by davidrohr** [comment]
Well, requiring internet-access during make-time is indeed bad. We would need some git subtree stuff or whatever. Anyway, I have no real objection, just don't like copying files if not needed.

**Comment by ktf** [comment]
To be clear, I do not like it either, but given it's automated, I think it's the least of all possible evils.

**Comment by sawenzel** [comment]
I thought about this a bit more. It's true that we did not foresee a coupling to AliRoot in the past. But given the new circumstances, I would actually also favour making AliRoot a (runtime) requirement for this conversion. In any case, AliRoot can be distributed via cvmfs or cached alibuild. In the end, this would cost much less compilation time for developers in comparison to having to compile the 500 new files in O2 (given that we have lot's of new commits/development in there). It is also the cleaner solution.

**Comment by aphecetche** [comment]
I also dislike the inclusion of all this AliRoot code into O2.

When I brought the question of the AliRoot vs O2 relationship a few months back (https://alice-talk.web.cern.ch/t/c-17-aliroot-and-o2/141) Giulio's advice at the time was to go through files or pipes. 
Why can't that be done here for the conversion ? 

BTW, if I had a vote (I know I don't ;-) ), and ignored that the policy is to limit the number of repos, I would vote to put this ESD Run2 ->Run3 data conversion in a separate repo altogether, where you'd have the double dependency on O2 and -parts of- AliRoot.

**Comment by mkrzewic** [comment]
@aphecetche I proposed today to make a zeromq reader device for ESD/AOD in aliroot, then it becomes rather trivial to ship data to a zeromq speaking fairmq device. The aliroot zmq message format we used in the HLT is the same as O2 (was in fact an o2 prototype) so it has a chance :) I'll implement a prototype soon.

**Comment by ktf** [comment]
@aphecetche when I said files or pipes I guess I referred to the fact that I would not mix, within the same process, AliRoot & O2. This approach is a glorified pipe, if you want. I could also move it to be a real pipe and have a separate package, with the O2 part reading from stdin. That might actually be a good compromise if I manage to converge quickly on it (again, I want something like this to be working "yesterday").

BTW, the new version is only 300 files, 150 .cxx, and compiles in less than a minute on my laptop from scratch and adds less than what I can measure in when doing an incremental build.

**Comment by davidrohr** [comment]
Btf: there is one other thing that we need to check, regardless of which solution we go for. There is the option to build O2 versus AliRoot, in which case all AliRoot libraries will be visible to O2, and we need to make sure there is no collision.

**Comment by ktf** [comment]
@davidrohr I think this should not be an issue, because this package only builds a single library which is named in a different way from the AliRoot ones.

**Comment by mkrzewic** [comment]
I made a pull request to AliRoot (https://github.com/alisw/AliRoot/pull/900) with the prototype device we were talking about. Sends the data as plain arrays (one column per data block), if we want arrow metadata describing them we just add them in O2.

**Comment by davidrohr** [comment]
@ktf : in case Mikolaj's solution will be insufficient, and since it looks like we will not make AliRoot a dependency for O2, I think what you said today in the WP3 meeting, to create an extra repository with your ported ESD files (kind of AliRoot - light), is much better than copying all files into O2.

**Comment by ktf** [comment]
That's what I am working on, yes.

**Comment by ktf** [comment]
Closed in favour of https://github.com/AliceO2Group/Run2ESDConverter/blob/master/README.
Thank you @aphecetche for suggesting to follow my own good advice.

**Pull request closed without merging**
