### PR TITLE
[ITS] Improve MC test by comparing evtID

### PR DESCRIPTION
**Pull request by mconcas**
This is just an addendum to last one. The `compare` function helps also to be sure to match id only on the same eventID.
Three small questions for @shahor02:
1. is `MCCompLabel::compare` suitable for checking ITS clusters on different layers are generated by the same track in the same event? 
2. in the `MCCompLabel::compare` function there is a check on the `isFake` flag. What does it mean?
3. I also separately ask for `isValid` to be true. Is it redundant in the case of ITS clusters, after having already passed the compare test?

Thanks

### CODE REVIEW

**Comment by davidrohr** [comment]
@mconcas : isFake() flag is mostly for tracks indicating a high fake cluster contamination. (meaning some fraction (by default I think 10%) of the attached clusters do not carry the MC label of the track).
In addition, isFake() is true if it is a noise hit, or if the label was not set at all (which shouldn't be the case). In case of tracks, the track would be noise if the majority of its clusters are noise.
You can specifically check for noise with isNoise(), and you can check whether the label is set at all with isSet().

compare() kind of contains the isValid() check? compare() will return 0 if the labels do not match. If they match, it will return -1 if they are (fake or noise or not set) and +1 otherwise. So if you do if(compare(...) == 1), it will contain isValid(), if(compare(....)) will not contain isValid.

compare() is suitable to check if ITS clusters on different layers belong to the same track.

**Review by davidrohr — APPROVED** [review]
Fine with me, only comment as last time is to perhaps separate the MC treatment from the processing. But this is for the future.

**Comment by mconcas** [comment]
@davidrohr I have this well in mind.
First I have to fix some low efficiencies and struggle with  non 0,0,0 vertices.
As soon as it works ~100% we can also sit together and restructure the whole code to be better.
Indeed for the GPU it will be needed.

Thanks for having a look.

**Comment by mconcas** [comment]
> @mconcas : isFake() flag is mostly for tracks indicating a high fake cluster contamination. (meaning some fraction (by default I think 10%) of the attached clusters do not carry the MC label of the track).
> In addition, isFake() is true if it is a noise hit, or if the label was not set at all (which shouldn't be the case). In case of tracks, the track would be noise if the majority of its clusters are noise.
> You can specifically check for noise with isNoise(), and you can check whether the label is set at all with isSet().
> 
> compare() kind of contains the isValid() check? compare() will return 0 if the labels do not match. If they match, it will return -1 if they are (fake or noise or not set) and +1 otherwise. So if you do if(compare(...) == 1), it will contain isValid(), if(compare(....)) will not contain isValid.
> 
> compare() is suitable to check if ITS clusters on different layers belong to the same track.

Hi @davidrohr, I opted for the `if(compare(...) == 1` option, hence I removed the redundant check.
Ready to be merged. Thanks a lot for clarifications

**Comment by sawenzel** [comment]
There is a clang-format issue. Can this be fixed please?

**Pull request merged**
