### PR TITLE
Clean up the ITS TF when reading a new TF

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Review by mconcas — COMMENTED** [review]
Concerning ALICE 3 part: macro is not operational anyways. You can remove that if you want.
We will see in the future with @ddobrigk how to fix this.

**Comment by shahor02** [comment]
Hi @mpuccio 
could you please fix the CI complains?

**Comment by mpuccio** [comment]
Now it should be fixed (thanks to @mconcas)

**Comment by mconcas** [comment]
@shahor02 is the error in fullci a genuine one?

**Comment by shahor02** [comment]
Hi @mconcas 

yes, the log contains:
```
[15537:its-tracker]: [02:05:00][INFO]  - Context initialisation completed in: 49.4342 ms
[15537:its-tracker]: terminate called without an active exception
```

**Comment by shahor02** [comment]
@mpuccio @mconcas is the problem understood?

**Comment by mpuccio** [comment]
Yes, it was my incompetence in rebasing. Now it works.

**Comment by mpuccio** [comment]
@shahor02, all green now

**Pull request merged**
