### PR TITLE
Apply git clang-format to GPU.

### PR DESCRIPTION
**Pull request by vkucera**
Some unreasonable changes reverted.

### CODE REVIEW

**Comment by vkucera** [comment]
@davidrohr This time I ran `git clang-format` against the initial commit. It seems that the GitHub action applies different rules.

**Comment by davidrohr** [comment]
It also depends on the clang version unfortunatelly...

**Comment by vkucera** [comment]
I see, thanks. I will try with `Clang/latest` then.

**Comment by davidrohr** [comment]
Note: The clang of the github action is not necessarily the same version as in alidist Clang/latest.

**Comment by davidrohr** [comment]
Btw, what you can also try to get a clean state: Apply git-clang-format first wrt to the very first commit of O2. Then apply it again only on the last formatting commit.

**Comment by vkucera** [comment]
> Btw, what you can also try to get a clean state: Apply git-clang-format first wrt to the very first commit of O2. Then apply it again only on the last formatting commit.

I just tried that with clang-format version 11.0.0 which should be the version used by the GitHub action and there are still discrepancies.

**Comment by vkucera** [comment]
By the way, the URL from where one is supposed to download `git-clang-format` returns 403 Forbidden. I don't know if it might be a short-term or local issue though.

**Pull request merged**
