### PR TITLE
Removing converter step from TPC reco workflow, added flexible lane configuration

### PR DESCRIPTION
**Pull request by matthiasrichter**
**Removing the converter step from the TPC reconstruction workflow**

The TPC HW Clusterer is capable of writing the HW cluster raw data directly, this
makes the conversion step obsolete.

**Implementing more flexible configuration of TPC lanes**

The TPC sector data which are distributed among the defined lanes can either be
transported over a single channel per lane (one for data and one for mc labels), or
over individual channels per sector. The lane setup is configured by passing a
list of sub specifications. This can be either
- a list from [0, nLanes - 1], or
- the list of TPC sector numbers (i.e. channel sub specification matches sector number)

### CODE REVIEW

**Comment by matthiasrichter** [comment]
@wiechula, @davidrohr, @KlewinS, this PR will remove the cluster conversion step and the dependency to the old cluster format.

The rest is a preparation to avoid the buffering of inputs in the tracker by using the DPL functionality to accumulate data in time slices. This will also allow to parallelize the tracker on time slices.

**Comment by wiechula** [comment]
Hi Matthias,
very good!

**Comment by davidrohr** [comment]
Just tried it and works nicely. So then we can finally get rid of the old cluster class.

**Comment by matthiasrichter** [comment]
For the record, I'm noticing a tiny difference in the number of found tracks when writing the hardware clusters directly. It's 5 tracks out of 11900 in 100 pp events. I assume this can be ignored for the moment.

**Pull request merged**
