### PR TITLE
Fix OpenCL compilation errors in the ITS tracker

### PR DESCRIPTION
**Pull request by mpuccio**

### CODE REVIEW

**Comment by davidrohr** [comment]
@mpuccio : thx, this fixed most/all the OpenCL issues I had with ITS, but created some new.
```
/home/qon/alice/O2/Detectors/ITSMFT/ITS/tracking/include/ITStracking/Cluster.h:47:3: warning: explicitly defaulted default constructor is implicitly deleted [-Wdefaulted-function-deleted]
  TrackingFrameInfo() = default;
  ^
/home/qon/alice/O2/Detectors/ITSMFT/ITS/tracking/include/ITStracking/Cluster.h:54:22: note: default constructor of 'TrackingFrameInfo' is implicitly deleted because field 'positionTrackingFrame' has no default constructor
  GPUArray<float, 2> positionTrackingFrame;
```

Could use just use size_t here?
```
/home/qon/alice/O2/Detectors/ITSMFT/ITS/tracking/include/ITStracking/Definitions.h:90:23: error: use of undeclared identifier 'std'
template <typename T, std::size_t Size>
```

I am not 100% sure, but I think non-literal return types are only allowed for constructors. Or did this change in c++14 / c++17?
```
/home/qon/alice/O2/Detectors/ITSMFT/ITS/tracking/include/ITStracking/Constants.h:67:62: error: constexpr function's return type 'GPUArray<float, its::LayersNumber>' (aka 'Array<float, 7>') is not a literal type
GPU_HOST_DEVICE constexpr GPUArray<float, its::LayersNumber> InverseZBinSize()
```

**Comment by mpuccio** [comment]
Hi @davidrohr, fixing the PR I added a copy constructor that made the type non-literal. Now everything should be fixed. If it works for you I will squash everything. As @mconcas was suggesting it might be good to have a test for OpenCL, such we should not always ping you for that!

**Comment by davidrohr** [comment]
Ciao Max,

Thx, I'll have a look.

For the test: first I plan to add autodetection for HIP and OpenCL1.2, and then add these to the CI like CUDA already is. 

The OpenCL 2.0 version right now uses clang 9 trunk + additional fixes that are not yet in the clang master. And there are still other errors besides ITS. Once this is stabilized and we can use a clang release, I'll add that as well.
Kind Regards
David Rohr

**Comment by davidrohr** [comment]
@mpuccio : I just tried it. The errors in the ITS are gone. There are still some OpenCL address space issues in both ITS and TPC code, but I first need to understand this better. Might also be another clang bug.
I suggest since the initial errors are gone and CUDA compiles correctly now, I'll squash and merge this, if you don't want to add anything more.

**Comment by mpuccio** [comment]
OK, squashed and ready to be merged!

**Comment by davidrohr** [comment]
@mpuccio : fyi: github has a "squash and merge" function, so basically you wouldn't need to squash yourself and rerun the CI.

**Pull request merged**
